### ISSUE TITLE
md文档在render时会往内嵌<div>添加<br>, 如何避免

### ISSUE THREAD

**Issue by yedeying999** [hexojs/hexo#1001]
eg:
markdown文件
``` html
### example
<div class="a">
  <span class="b">something</span>
  <span class="b">something</span>
  <span class="b">something</span>
  <span class="b">something</span>
<div>
```
会得到以下html
``` html
<h3 id="example">example</h3>
<p></p>
<div class="a">
  <br>
  <span class="b">something</span>
  <br>
  <span class="b">something</span>
  <br>
  <span class="b">something</span>
  <br>
   <span class="b">something</span>
</div>
<p></p>

```
渲染引擎是默认的marked，请问有没有什么办法去除html tag内的br呢。
因为本人常在md内写demo，br的产出会导致样式错乱

**Comment by liyouhai** [comment]
并列一行就可以了..
<div class="a"><span class="b">something</span><span class="b">something</span><span class="b">something</span><span class="b">something</span><div>

**Comment by mingming-killer** [comment]
这个好像是渲染引擎的一个 bug，我之前插入 html table 标签也是一样：只要有换行就有 br，楼上说并成一行是可以解决，但是写起来痛苦无比，我暂时放弃在 markdown 里嵌入一些 html 标签了。
