### ISSUE TITLE
hexo: 3.0.0-beta.2 ERROR Plugin load failed: hexo-renderer-marked

### ISSUE THREAD

**Issue by huixisheng** [hexojs/hexo#1003]
$ npm install hexo@beta -g
    $ hexo init blog
    $ cd blog
    $ sudo npm install
    $ hexo server

显示

    ERROR Plugin load failed: hexo-renderer-marked
    TypeError: Cannot read property 'highlight' of undefined
    ***/test/node_modules/hexo-renderer-marked/index.js:4:19

原因

> Besides, utilities are separated into a standalone module. hexo.util is not reachable anymore.

**Comment by huixisheng** [comment]
$hexo init blog 
    
    生成的 `package.json`  
    "hexo-renderer-marked": "^0.1.0",  版本有问题。解决：

    sudo npm install hexo-renderer-marked@0.2.3


最终解决办法还是要更新源码

**Comment by tommy351** [comment]
I have updated the default dependencies for a new blog in commit https://github.com/hexojs/hexo/commit/8bb634ed76c81cef3b437daa4f7b2231c1f2f4d2
