### ISSUE TITLE
post tag in the same tag nane directory, generate tag list not right 

### ISSUE THREAD

**Issue by youxiachai** [hexojs/hexo#1004]
i found hexo 3.0 generate tag will use source directory, how to disable it?

**Comment by tommy351** [comment]
Sorry I don't understand what you mean. Could you describe more detail?

**Comment by youxiachai** [comment]
@tommy351 

like 

```bash
source/_posts/game
```

if game  dir have 2 posts

will gererate tag like
```
game(1)
game(1)
```

**Comment by tommy351** [comment]
I see. I'll fix it.
