### ISSUE TITLE
Open markdown file after running hexo new?

### ISSUE THREAD

**Issue by andrewboni** [hexojs/hexo#1007]
Hi, I'm wondering how to run some custom commands after doing a `hexo new "My post"`. I'd like to immediately open the `my-post.md` file in my editor of choice (with a `vi my-post.md`). Anyone have a solution to this? Thanks!

**Comment by tommy351** [comment]
You can try to listen to the `new` event. For example:

``` js
var spawn = require('child_process').spawn;

// Hexo 2.x
hexo.on('new', function(path){
  spawn('vi', [path]);
});

// Hexo 3
hexo.on('new', function(data){
  spawn('vi', [data.path]);
});
```

**Comment by andrewboni** [comment]
Thanks for the reply. Where should this live?

**Comment by tommy351** [comment]
You can add a JavaScript file to `scripts` folder.
http://hexo.io/docs/plugins.html#Script

**Comment by Xuanwo** [comment]
Closed for no more update.

**Comment by ArchitectBeaver** [comment]
> var spawn = require('child_process').spawn;
> // Hexo 3
> hexo.on('new', function(data){
>   spawn('vi', [data.path]);
> });

For me, this failed to open `Vim` in terminal.
I added `{ stdio: 'inherit' }` option to let `Vim` use parent's stdios. 

```
var spawn = require('child_process').spawn;
 // Hexo 3
hexo.on('new', function(data){
spawn('vim', [data.path], { stdio: 'inherit' });
});
```
It opens `Vim` in terminal now.

**Comment by weilining** [comment]
hexo 5 Not working
