### ISSUE TITLE
hexo server not load file like xxx.min.js

### ISSUE THREAD

**Issue by youxiachai** [hexojs/hexo#1008]
Use hexo beta 4
If theme source have file like

```
js/jquery.min.js
js/bootstarp.mini.js
```

run
```
hexo server 
```

visit
```
http://localhost:4000/js/jquery.min.js 
``` 
show 404 not found

hexo 2.8.3 not this problem

**Comment by tommy351** [comment]
This bug has been fixed in commit 4b02500ba6879e63fa684316902c42425250088c
