### ISSUE TITLE
Help with EXIF data plugin

### ISSUE THREAD

**Issue by andrewboni** [hexojs/hexo#1009]
Hi, I'm in the process of writing a plugin to display EXIF information from a photo, for things like camera make, model, focal length, shutter speed, aperture, ISO, etc.

I'm using the [gm-exif](https://www.npmjs.com/package/gm-exif) node plugin, which makes getting EXIF data easy.

I can extract the EXIF data successfully, but the plugin returns nothing, as it's presumably not waiting for the async `exif()` task. How can I fix this, so that the plugin waits for the EXIF data to be extracted?

Sample plugin usage:
```
{% exifinfo 2015-01-25-luchadors-in-the-mission/luchadors.jpg %}
```

Plugin code:
```javascript
hexo.extend.tag.register('exifinfo', function(args){
    var exif = require('gm-exif');
    var imagePath = args[0];
    exif(imagePath, function(err, exifData) {
        return '<p>' + exifData.Make + ' ' + exifData.Model + ' | ' + exifData.FocalLength +'mm | ' + exifData.ExposureTime + 'sec exposure | ƒ/' + exifData.FNumber + ' | ' + 'ISO' + exifData.ISOSpeedRatings + '</p>';
    });
});
```

**Comment by tommy351** [comment]
You can't do async task in tag plugins because Swig render files synchronously.

**Comment by andrewboni** [comment]
Got it- makes sense. Can you point me in the right direction of how I might
be able to implement EXIF data reading functionality then? Thanks!

**Comment by tommy351** [comment]
You can try to write a filter. But it's more difficult. I'm thinking whether to replace Swig with [Nunjucks] which supports async rendering.

[Nunjucks]: https://github.com/mozilla/nunjucks

**Comment by andrewboni** [comment]
I see okay- yes, I'm all in favor of async support

**Comment by tommy351** [comment]
You can use async tag plugins since Hexo 3.

https://github.com/hexojs/hexo/wiki/Breaking-Changes-in-Hexo-3.0#async-tag-plugins
