### ISSUE TITLE
How can I create a blog for a group?

### ISSUE THREAD

**Issue by truonguit2010** [hexojs/hexo#1010]
Hi,
- I have a team and I want to create a blog for a team. A member can have an name, permission to write, edit, ... Do hexo support these function?

Thank you.

**Comment by gingters** [comment]
Hi,

Hexo is a static site generator, that means it generates a website consistent of static html, css, js files.
Editing / writing is done by editing the 'source code' for the site. To make that easy, the source are article (or post) files, usually in markdown format.

Permissions could be granted by giving people write access to a git repository containing your blog source, if that is what you want.
