### ISSUE TITLE
Problem about hexo 3

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#1011]
What i should do to upgrade hexo from 2.8.3 to 3.0?

**Comment by tommy351** [comment]
``` bash
npm install hexo@beta -g
```

And don't forget this: [Migrating from 2.x to 3.0](https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0)

**Comment by Xuanwo** [comment]
I don‘t need to change the css/js of my theme?

**Comment by tommy351** [comment]
No. But you may need to update plugins.

**Comment by Xuanwo** [comment]
OK, got it.
