### ISSUE TITLE
输出信息不完善

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#1012]
不能显示渲染后的文章的名称

**Comment by tommy351** [comment]
可以更詳細的說明嗎？

**Comment by Xuanwo** [comment]
```
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
INFO  Generated:
```
输出信息只有这些

**Comment by tommy351** [comment]
![2015-01-26 21 39 25 2](https://cloud.githubusercontent.com/assets/411425/5900412/d155e67c-a5a3-11e4-9491-6a5921b7a64f.PNG)

這應該是 bug，在我的電腦上正常，可以用 `--debug` 再跑一次嗎

**Comment by Xuanwo** [comment]
好的，稍等

**Comment by Xuanwo** [comment]
简直神奇，我全选之后复制出来是可见的
```
21:47:12.427 INFO  Generated: imgs/404.jpg
21:47:12.429 INFO  Generated: imgs/daily/xuanfeng-2.jpg
21:47:12.429 INFO  Generated: imgs/daily/xuanfeng-1.jpg
```
但是：
![image](https://cloud.githubusercontent.com/assets/5351546/5900543/49e6e63a-a5a5-11e4-9d71-cb45fab0fc22.png)

**Comment by Xuanwo** [comment]
我不确定是不是PowerShell的问题，现在正在测试系统自带的CMD

**Comment by Xuanwo** [comment]
测试完毕，CMD下正常，但是PowerShell下面无法显示出来。

那么问题来了，这是什么鬼现象？。。。。。。

**Comment by tommy351** [comment]
可能是 PowerShell 沒辦法正確顯示顏色？

**Comment by tommy351** [comment]
似乎黃色和粉紅色沒辦法在 PowerShell 顯示
ref sindresorhus/chalk#2

**Comment by Xuanwo** [comment]
明白了，已经确认不是Hexo的问题~
