### ISSUE TITLE
Hexo 3.0.0-beta.4 静态文件（themesName/source/*）如果是  .min.js  无法传输到 public 

### ISSUE THREAD

**Issue by huixisheng** [hexojs/hexo#1016]
themes
        |-- amazeui
            |-- source
                |-- js/debugger.min.js
                |-- js/handlebars.min.js
                |-- css/landing.min.css

    
    INFO  Generated: js/debugger.min.min
    INFO  Generated: js/handlebars.min.min
    INFO  Generated: css/landing.min.min

调试发现 hexo/lib/plugins/generator/asset.js 存在问题，无法处理 filename.min.js这样的静态文件

    if (self.render.isRenderable(path)){
    // Replace extension name if the asset is renderable
        var extname = pathFn.extname(path);
        var filename = path.substring(0, path.length - extname.length);
        var subext = pathFn.extname(filename);

        path = filename + '.' + (subext ? subext.substring(1) : self.render.getOutput(path));

**Comment by tommy351** [comment]
Already fixed in commit 4b02500ba6879e63fa684316902c42425250088c
