### ISSUE TITLE
Added pictures can't show after adding read more.

### ISSUE THREAD

**Issue by ronansparks** [hexojs/hexo#1017]
After I add  I can't see my pictures in summary or inside the article. Before that, I can see the pictures. How am I gonna do to show pictures in this situation?  #pictures dismiss

**Comment by tommy351** [comment]
Please post the content of your source file.

**Comment by ronansparks** [comment]
//1. here's my blog address http://ronansparks.github.io/Code/Swift01/
//2. the code below is part of my xx.md. 
//3. and I've tried not using , pictures can show normally.
@tommy351 
**最新支持Xcode 6.1.1**

Swift是苹果在2014 WWDC上推出的一门全新的编程语言。

与此同时，苹果还推出了很棒的 [Swift参考指导](https://itunes.apple.com/us/book/swift-programming-language/id881256329?mt=11&ign-mpt=uo%3D8)，有英文基础的朋友可以看看。

但是，这本参考书太长了！如果你没有那么多的时间快速学习Swift，本系列教程正是为你而写。

本节教程大概需要15分钟，能够带你快速了解Swift语言，其中包括变量，控制流，类，以及量身定制的练习。

本节结束时，你将能够做出一款简易的费用计算器。



在本教程中，你需要准备最新的Xcode(在写本教程时6.1.1为最新版本)。**你不需要任何的Swift或者Objcetive-C编程经验，**当然如果你有其他编程经验那就再好不过了

**重点:** 确保有最新的Xcode(在Mac App Store查看是否已经是最新版本)。因为Swift在不断的完善，有些代码可能在旧版本的Xcode中无法运行。

##介绍Playgrounds

打开Xcode 6， **File\New\File**，选择 **iOS\Source\Playground**，点击Next。

![](../images/article01/01.png)

**Comment by tommy351** [comment]
Can't reproduce this bug.

**Comment by ronansparks** [comment]
@tommy351  I'm using  this theme. Could this be the theme's problem?
git clone https://github.com/hexojs/hexo-theme-light.git themes/light

**Comment by leesei** [comment]
You used `` ` `` to wrap your image link. Have you tried removing them?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
