### ISSUE TITLE
post'<' '>' 符号遇到英文内容和中文逗号就无法正常显示

### ISSUE THREAD

**Issue by Wilbeibi** [hexojs/hexo#1018]
比如post中有
"abc，\<def\>，ghi"

def就被当成html tag，显示不了

**Comment by tommy351** [comment]
Where's "def" in your text?

**Comment by Wilbeibi** [comment]
@tommy351 额，貌似是markdown 解析不了

**Comment by tommy351** [comment]
Then it's not a problem of Hexo.

**Comment by Wilbeibi** [comment]
@tommy351 嗯，我自觉close掉 %>_<%
