### ISSUE TITLE
Conditional tags work incorrectly in Hexo 3.0.0-rc.1

### ISSUE THREAD

**Issue by iissnan** [hexojs/hexo#1020]
[Conditional tags](http://hexo.io/docs/helpers.html#Conditional_Tags) are all evaluated to false when I upgrade to Hexo 3.0.0-rc.1.

I used `swig` as theme templates and used those tags to detect which page current is.
Did I miss something?

For your information, here are some information I have got:

```
hexo: 3.0.0-rc.1
os: Windows_NT 6.1.7601 win32 x64
http_parser: 1.0
node: 0.10.29
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.27
zlib: 1.2.3
modules: 11
openssl: 1.0.1h
```

Tags used in my theme:
```
 {% if is_home() or is_post() %}
   {% set postsClass = "posts-expand" %}
 {% else %}
   {% set postsClass = "posts-collapse" %}
 {% endif %}
```

**Comment by tommy351** [comment]
What's your `permalink` setting?

**Comment by iissnan** [comment]
It is:
```
permalink: :year/:title/
```

**Comment by tommy351** [comment]
It seems `is_post` helper is ok.

**Comment by iissnan** [comment]
Thanks. I will check it again with your fix.

By the way, what about other conditional tags, such as `is_archive/is_page` etc?

**Comment by tommy351** [comment]
Other conditional plugins use new rules now. They don't check path anymore. You can check this file for detail: https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/is.js

**Comment by iissnan** [comment]
Cool.
