### ISSUE TITLE
How to hidden left Tags defaultly?

### ISSUE THREAD

**Issue by CKJOKER** [hexojs/hexo#1022]
the tags are unfolded defaultly,can i set it folded defautly?

**Comment by iissnan** [comment]
Could you please provide a bit context about your question?

It seems you are asking something about a theme.

**Comment by CKJOKER** [comment]
oh,yes,i use the theme -Pacman,this is my [blog] (https://ckjoker.github.io/)

**Comment by CKJOKER** [comment]
maybe i should open the issue in Pacman :)
