### ISSUE TITLE
是否可以在正文里引用site或config变量

### ISSUE THREAD

**Issue by Jinjiang** [hexojs/hexo#1024]
文档中描述只有page变量可以在正文里通过类似 `{{title}}`、`{{date}}` 的方式进行展示，但是不知道是否有机会展示 site configuration (即 `_config.yml` 里的信息)

谢谢

**Comment by chenall** [comment]
这个估计要写插件来实现
也可以试试我自己定制的主题(不支持3.x的版本)

https://github.com/chenall/hexo-theme-chenall

有ijs功能,可以通过它访问所有hexo的变量.

**Comment by leesei** [comment]
用plugin 或主題支持
