### ISSUE TITLE
代码片段前后的序号似乎会出现问题

### ISSUE THREAD

**Issue by outfield** [hexojs/hexo#1025]
我在编辑时，输入的序号是1...2...3...4..
但是在段落3中，如果插入一段代码，那么之后的序号4就会变成序号1了。
请问下这个问题有什么好的解决方法吗？

1. XXX
2. XXX
3. XXX
```bash
$ ls
```
4. XXX《——这里我输入的是4，被自动转化成1了

**Comment by Xuanwo** [comment]
是的，我也发现了，但是好像跟Hexo无关，是Markdown渲染的问题- -
