### ISSUE TITLE
搭建页面在IE11浏览器下显示不正常

### ISSUE THREAD

**Issue by hiddow** [hexojs/hexo#1027]
![页面如上](http://ww3.sinaimg.cn/large/73d5ebd6jw1eowbxk656aj20y40k9gnz.jpg)

**Comment by Xuanwo** [comment]
大概是你这个主题不支持IE11？
使用Chrome来看看是不是正确？

**Comment by hiddow** [comment]
Chrome正常的，IE默认显示这个页面是IE7的文档模式才这样的

**Comment by tommy351** [comment]
Add this to `<head>` of your template.

``` html
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
```

**Comment by hiddow** [comment]
是修改_config.yml吗

**Comment by iissnan** [comment]
Your theme template.

**Comment by Xuanwo** [comment]
一般来说是`head.ejs`里面

**Comment by hiddow** [comment]
多谢大家的热心支持解决了
