### ISSUE TITLE
hexo-site in package name?

### ISSUE THREAD

**Issue by szarouski** [hexojs/hexo#1029]
Hi, apparently for hexo3-rc2 if my package.json is not named "hexo-site", I'll not be able to use generate and some other commands:
![1](https://cloud.githubusercontent.com/assets/911388/6034278/c5c76320-abee-11e4-85a9-768f856595b8.png)

However when my package name is "hexo-site", I can use full set of commands. How come?
Also package version is getting modified to 3.0.0-rc.2.

**Comment by tommy351** [comment]
Since Hexo 3.0.0-rc.1, we use `package.json` instead of `_config.yml` to verify whether the folder is a Hexo site.

https://github.com/hexojs/hexo/releases/tag/3.0.0-rc.1

**Comment by szarouski** [comment]
Will it make more sense to use a custom meta object in package.json instead of using name and version? Something like:
```js
...
_hexo: {
  version: '3.0.0-rc.2',
  ...
}
...
```
I see it as a more straight forward thing. Newcomers to hexo will tend to change package name and be confused why some commands are missing. Also there could be scenarios when people might want to publish their hexo projects to npm and they will not be able to do that without some extra effort because all of them will be called 'hexo-name', by default.

Please let me know what are your thoughts.

**Comment by tommy351** [comment]
Indeed. It's more straight. I think we can remove the prefixing `_`. Just use `hexo` in `package.json`.

``` js
...
hexo: {
  version: '3.0.0-rc.2',
  ...
}
...
```

**Comment by szarouski** [comment]
Sounds like a plan, thank you
