### ISSUE TITLE
server_middleware for 404 page

### ISSUE THREAD

**Issue by szarouski** [hexojs/hexo#1030]
Hi, I was trying to set 404 page handler using server_middleware, but it appears that plugins code from my theme folder will execute before hexo-server plugin will register its own 'server_middleware' plugins. 404 page middleware should be set at the end of connect middleware, but because it was registered first it will handle even valid pages and I don't see a way to handle 404 myself. Any ideas? Thank you.

In my theme plugins folder:
```js
hexo.extend.filter.register('server_middleware', function _404middleware(app) {
	/***/
	app.use(function handle404(req, res, next) {
		res.writeHead(302, {
			'Location': hexo.config.url + hexo.config.root
		});
		res.end();
	});
});
```

**Comment by tommy351** [comment]
You can try to add `priority` option to the filter. Bigger priority runs later. The default priority is 10.

``` js
hexo.extend.filter.register('server_middleware', function(app){
  // ...
}, 99)
```

**Comment by szarouski** [comment]
Very nice, thank you
