### ISSUE TITLE
As of 2.8 release, markdown pages are not processed by hexo, even if layout is true

### ISSUE THREAD

**Issue by the-simian** [hexojs/hexo#1031]
I updated to the latest hexo, 2.8. I ran generate, and the site looked correct with the posts and the archives. Unfortunately the routes to the pages themselves, served the raw markdown. This is on version 2.8.3

I downgraded back to 2.7.1 and the problem is resolved. The pages generate correctly!

**Comment by leesei** [comment]
Please open new issue if problem persists with latest build.
