### ISSUE TITLE
Is it possible to specify page size for archive/tag/category separately?

### ISSUE THREAD

**Issue by iissnan** [hexojs/hexo#1033]
Hi

Currently, we can set page size in site configurations. For instance:

```
# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page
```

This size will be applied for all types of archives, including  archive, tag and category. The only thing we can do is turning on/off pagination:

```
# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 0
tag: 2
```

I am wondering if we can set page size for different type of archive, and also home page separately?
For example, I can set page size of home page as `10`, and `20` for tag, etc:

```
#Pagination
per_page: 
  default: 5
  home: 10
  tag: 20
  archive: 0
```

**Comment by tommy351** [comment]
In Hexo 3.0, you can set different `per_page` for each generators.

- [hexo-generator-archive](https://github.com/hexojs/hexo-generator-archive)
- [hexo-generator-category](https://github.com/hexojs/hexo-generator-category)
- [hexo-generator-index](https://github.com/hexojs/hexo-generator-index)
- [hexo-generator-tag](https://github.com/hexojs/hexo-generator-tag)

**Comment by iissnan** [comment]
That's great.
