### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by shoumu** [hexojs/hexo#1034]
添加多篇文章之后，首页下面无法正常显示分页。如下面的效果。
![image](https://cloud.githubusercontent.com/assets/2498069/6059678/7ffa1928-ad6f-11e4-9e98-9e634946f7b9.png)
具体的代码形式为：
![image](https://cloud.githubusercontent.com/assets/2498069/6059682/93390760-ad6f-11e4-8a12-629cc82fbb1e.png)

hexo版本为：3.0.0-rc.2
配置只有如下改变：
![image](https://cloud.githubusercontent.com/assets/2498069/6059717/db1397ee-ad6f-11e4-8a1e-3fa343136b14.png)

**Comment by iissnan** [comment]
See: https://github.com/hexojs/hexo/issues/1023

**Comment by tommy351** [comment]
Already fixed

**Comment by shoumu** [comment]
Thanks
