### ISSUE TITLE
Hexo 3.0 生成的Tags出现重复

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#1035]
![image](https://cloud.githubusercontent.com/assets/5351546/6075078/67ee8714-ae06-11e4-96b5-52602128f8cd.png)

使用的主题是[Alex](https://github.com/ppoffice/hexo-theme-alex)

**Comment by Xuanwo** [comment]
下面附上我的md文件头信息
```
title: UVa 1607 Gates
date: 2014-11-7 08:55:29
tags: [ACM, UVa, C ]
categories: Exercise
toc: true
---
```

**Comment by tommy351** [comment]
Did you update to 3.0.0-rc.2? This bug should have been fixed.

**Comment by Xuanwo** [comment]
是的，我一直用的是最新版。

我使用Travis CI进行生成
![image](https://cloud.githubusercontent.com/assets/5351546/6075141/a572908e-ae07-11e4-9888-1eafd777cf7c.png)

**Comment by youxiachai** [comment]
@tommy351 rc2 already have this bug, just not beta.3 serious

**Comment by tommy351** [comment]
Any idea to reproduce this bug?

**Comment by Xuanwo** [comment]
使用我的md文件，然后使用Alex主题？

**Comment by Xuanwo** [comment]
你可以下载这个
https://github.com/Xuanwo/xuanwo.github.io/tree/blog

**Comment by tommy351** [comment]
@Xuanwo Thanks. I'll give it a try.
