### ISSUE TITLE
Highlight.js is slow

### ISSUE THREAD

**Issue by tommy351** [hexojs/hexo#1036]
[Highlight.js](https://highlightjs.org/) is slow. After turning off the highlighting, the loading speed dropped from 46s to 16s. Maybe we should change another highlighting library or use [SyntaxHighlighter](http://alexgorbatchev.com/SyntaxHighlighter/) or [Prism](http://prismjs.com/) to let browsers do this job.

**Comment by Xuanwo** [comment]
From my point of view, it is worthwhile sacrificing some loading time for a quicker open in browser.
And I don't know how much time browsers do this job will take, can you give out some data?

**Comment by tommy351** [comment]
Actually it's fast to do highlight on browsers, since browsers only need to render a page at a time and Hexo has to render hundreds of pages in a few seconds. It takes lots of CPU time to do this.

**Comment by Xuanwo** [comment]
OK, I will support your idea.

*Since I use Travis CI to do this, so I'm not care about the time highlight.js used, hahaha*

**Comment by iissnan** [comment]
Is there any other lib which has high performance than highlight.js on rendering pages?

**Comment by iissnan** [comment]
I mean rendering pages in command line, not in browsers.

**Comment by tommy351** [comment]
@iissnan Maybe we can give [highlights](https://github.com/atom/highlights) a try. It's used by atom.

**Comment by iissnan** [comment]
@tommy351 Executed a simple performance test with [hexo-util](https://github.com/hexojs/util) and [highlights](https://github.com/atom/highlights).

`highlights` spends only `1469`, while `hexo-util` spends `3793`.

LGTM.

**Comment by iissnan** [comment]
By the way, if this change has effect on theme highlight styles?

**Comment by tommy351** [comment]
`hexo-util` may run slow at the first time because it needs to load highlight.js. The speed may be faster after the first run.

The styles may need changes if we change the library.

**Comment by iissnan** [comment]
Sorry for the incorrect testing.
Using [highlight.js](https://highlightjs.org/) instead of `hexo-util`, time drops to `3215`.

**Comment by tommy351** [comment]
Thanks for the testing. I'll try to optimize that function.

**Comment by tommy351** [comment]
I just made a benchmark and this is the result:

``` 
[00:38:28]    highlight.js - auto detect x 33.79 ops/sec ±1.83% (61 runs sampled)
[00:38:34]    highlight.js - language set x 1,092 ops/sec ±1.46% (90 runs sampled)
[00:38:39]    util.highlight - auto detect x 34.44 ops/sec ±1.12% (62 runs sampled)
[00:38:45]    util.highlight - language set x 1,100 ops/sec ±1.54% (92 runs sampled)
[00:38:45] Fastest tests are util.highlight - language set,highlight.js - language set at 1.01x faster than highlight.js - language set
```

There's no large differences between two of them. Here's the source code: https://gist.github.com/tommy351/48401ae93dbf6aa2e94d

**Comment by tommy351** [comment]
And this is the test for [highlights](https://github.com/atom/highlights).

```
[00:46:25]    highlight.js - auto detect x 35.18 ops/sec ±2.72% (56 runs sampled)
[00:46:31]    highlight.js - language set x 1,042 ops/sec ±9.13% (77 runs sampled)
[00:46:37]    util.highlight - auto detect x 34.77 ops/sec ±1.15% (56 runs sampled)
[00:46:42]    util.highlight - language set x 1,162 ops/sec ±1.37% (89 runs sampled)
[00:46:48]    highlights x 2,098 ops/sec ±1.57% (87 runs sampled)
[00:46:48] Fastest test is highlights at 2.0x faster than highlight.js - language set and util.highlight - language set
```

*P.S. highlights detects languages automatically.*

**Comment by Xuanwo** [comment]
WOW, it's sound like highlights is good.

**Comment by zphj1987** [comment]
I tell the md the tab text what it is,like bash ,like raw ,the highlight make it so  fast

**Comment by leesei** [comment]
Any plan to move to highlights?

Also see #1543.

**Comment by tommy351** [comment]
Remove highlight.js may need to update the stylesheet of all curernt themes.

**Comment by SukkaW** [comment]
Emm, I run a test on travis ci and get the result:
When there are more than 300 posts(tags & categories included), Hexo will generate 1073 files in 35s with `fragment_chche`, `highlight` enabled, while in 22s when `fragment_chche` enabled. If `highlight` was disabled Hexo finish generating in 22s.

[Travis CI Log](https://travis-ci.org/SukkaW/hexo-theme-suka/jobs/447669526)

![image](https://user-images.githubusercontent.com/40715044/47639365-0c260700-db9c-11e8-8826-3d9436015ecf.png)

**Comment by curbengh** [comment]
@hexojs/core 
Continuing from https://github.com/hexojs/hexo-util/issues/19#issuecomment-531486643.

What do you think of atom [highlights](https://github.com/hexojs/hexo-util/issues/19#issuecomment-531486643)? feasible?
