### ISSUE TITLE
WARN  No layout: index.html

### ISSUE THREAD

**Issue by scaljeri** [hexojs/hexo#1037]
I just download install Hexo version 3.0.0-rc.2

I followed the steps and created the blog site. Now when I try to load it in my browser I get the following message in the console where the server is running:

    blog % hexo server
    INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
    WARN  No layout: index.html

Also when I do:

    blog % hexo new "Hello Hexo"
    blog % hexo generate
    INFO  Files loaded in 403 ms
    WARN  No layout: 2015/02/06/Hello-Hexo/index.html
    WARN  No layout: 2015/02/06/Hello-Hexo/index.html
    INFO  Generated: 2015/02/06/Hello-Hexo/index.html
    WARN  No layout: 2015/02/06/hello-world/index.html
    WARN  No layout: 2015/02/06/hello-world/index.html
    INFO  Generated: 2015/02/06/hello-world/index.html
    WARN  No layout: archives/index.html
    WARN  No layout: archives/index.html
    INFO  Generated: archives/index.html
    WARN  No layout: archives/2015/index.html
    WARN  No layout: archives/2015/index.html
    INFO  Generated: archives/2015/index.html
    WARN  No layout: archives/2015/02/index.html
    WARN  No layout: archives/2015/02/index.html
    INFO  Generated: archives/2015/02/index.html
    WARN  No layout: index.html
    WARN  No layout: index.html
    INFO  Generated: index.html
    INFO  6 files generatd in 31 ms

And the browser remains completely white. Did I do something wrong or could this be an (known) issue ?

**Comment by celsomiranda** [comment]
This usually happens when you don't have a an index template.

Check inside your `themes/your-theme/layout/` folder for a file called `index.ejs` (The `ejs` part could change if you use jade or swig for templates)

**Comment by scaljeri** [comment]
There's nothing in that directory. However, if I do:

    git clone https://github.com/hexojs/hexo-theme-landscape.git themes/landscape

It works!

Following the steps on http://hexo.io/ this should not be necessary. So I guess one ore more themes should be available by default right ?

**Comment by celsomiranda** [comment]
The steps in the site refer to version `2.8.3`. My guess is that they'll be updated once `3.0` ships.

You should check the Wiki section of this repo if you're using the Betas/Release Candidates.

**Comment by scaljeri** [comment]
ok, thanks. This issue can be closed!

**Comment by Xuanwo** [comment]
So, please close it

**Comment by gringolalia** [comment]
I have a `default.swig" file in the layout directory of my theme. Copying it to `index.swig` has no result.

**Comment by obsession707** [comment]
I have the same problem! How does it get work?

**Comment by seminelee** [comment]
Just check you themes. if everything is right.

**Comment by liumingming123** [comment]
I meet the same question,but I don't know how to fix it,

**Comment by JohnLockwood** [comment]
I came across this -- in my case because I renamed my theme directory but neglected to update _config.yml to the new name.  Your mileage may vary.

**Comment by mofeiyu** [comment]
I found the _config.yml of my themes was error. So I think you can try to check your _config.yml in this link: [yaml-validator](http://codebeautify.org/yaml-validator)

**Comment by VictorZhang2014** [comment]
@celsomiranda Thank you! You're right. The theme folder is empty.

**Comment by MichaelJCole** [comment]
Things to check:
1) validate `./_config.yml`  (https://yaml-online-parser.appspot.com/)
2) verify `./_config.yml`'s `theme:` entry is a directory in `./themes`
3) verify `./themes/[themedir]/_config.yml` is valid
4) verify post's front matter is valid yml
5) verify post's front matter `layout:` entry is a file (w/o extension) in `./themes/[themedir]/layout/[name]`

If you make any changes to _config files, restart the hexo server.

**Comment by bennyn** [comment]
@MichaelJCole great debugging tips!

What also helps when debugging your own theme is to run `hexo clean` before `hexo generate` and to remove other themes within the "themes" directory.

**Comment by hitsmaxft** [comment]
```
Configuration Files

After the installation of Hexo and NexT, you may found that there are two configuration files using by Hexo and both called _config.yml:

    The first one is under site root directory, which contains Hexo's config.
    The second one is under theme root directory (e.g. themes/next/_config.yml or node_modules/hexo-theme-next/_config.yml), which is provided by NexT and contains theme's config.

Let's call the first one – Hexo config file, and the second one – NexT config file.
```

https://theme-next.js.org/docs/getting-started/#Configuration-Files

next's document still tell user to place theme config under `themes/next/_config.yml` ,  which only works for themes add as submodule or manually clone. But to users install next-theme by `npm i hexo-theme-next`, this way will breaks hexo server

**Comment by stevenjoezhang** [comment]
@hitsmaxft I'm afraid you misunderstood the NexT documentation. Below the section you quoted, the documentation strongly advises against using `themes/next/_config.yml` and tells the correct way of using `_config.{theme-name}.yml`.
<img width="886" alt="截屏2024-02-24 16 40 35" src="https://github.com/hexojs/hexo/assets/16272760/f7f89a84-8ca4-4765-91b8-dc052f8ee0e5">

**Comment by hitsmaxft** [comment]
> @hitsmaxft I'm afraid you misunderstood the NexT documentation. Below the section you quoted, the documentation strongly advises against using `themes/next/_config.yml` and tells the correct way of using `_config.{theme-name}.yml`. <img alt="截屏2024-02-24 16 40 35" width="886" src="https://private-user-images.githubusercontent.com/16272760/307507520-f7f89a84-8ca4-4765-91b8-dc052f8ee0e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NjU5MTEsIm5iZiI6MTcwODc2NTYxMSwicGF0aCI6Ii8xNjI3Mjc2MC8zMDc1MDc1MjAtZjdmODlhODQtOGNhNC00NzY1LTkxYjgtZGMwNTJmOGVlMGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA5MDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYjY5YWJlYzI3MDAwOGY1NzM4ZjAwMGVlZjRjMTBkZjliMDQ1YTJlNGE4M2NkN2E4MDhhOGY3YTg2MjY0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZazBOqGr1jUHTOg9Ox40Alix4SkSDzfRtz1PElqYxjY">

The second way should only used by users who clone Next source code into ./themes/next/. It's harmfully to show up here
