### ISSUE TITLE
正文中单双引号匹配不正常

### ISSUE THREAD

**Issue by ArtinHuang** [hexojs/hexo#1038]
在win7+sublime2的环境下用Markdown编写的文档，单双引号在代码行显示无误，可是正文显示却出错了，本来应该都是英文半角输出。How to solve this？
![image](https://cloud.githubusercontent.com/assets/10860203/6096317/de7c641c-afc5-11e4-96f4-f02aacf07ac2.png)

**Comment by Xuanwo** [comment]
建议删了重新切到英文模式输入一遍

**Comment by ArtinHuang** [comment]
```
最后，理解变量在计算机内存中的表示也非常重要。当我们写：<code>a ='ABC'</code>时，Python解释器干了两件事情：

1.  在内存中创建了一个<code>'ABC'</code>的字符串；
1.  在内存中创建了一个名为a的变量，并把它指向<code>'ABC'</code>。
```
最后，理解变量在计算机内存中的表示也非常重要。当我们写：<code>a ='ABC'</code>时，Python解释器干了两件事情：

1.  在内存中创建了一个<code>'ABC'</code>的字符串；
1.  在内存中创建了一个名为a的变量，并把它指向<code>'ABC'</code>。

---

PS:我尝试用其他在线Markdown编辑器进行编辑，结果解析正常，或许是因为Hexo的Markdown解析器自身的问题？还是说要修改CSS样式？我不是很懂，我用的是[air主题](https://github.com/hustcer/hexo-theme-air.git)。
