### ISSUE TITLE
Hexo3 post_asset_folder: true, but asset folder is not copied with 'generate'

### ISSUE THREAD

**Issue by szarouski** [hexojs/hexo#1041]
```
hexo: 3.0.0-rc.3
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
```

Steps to reproduce:
1) hexo new test (under `source/_posts/` we now have `test.md` and `test/` folder)
2) add something to a `test/` folder
3) hexo generate
4) go to public folder, observe that under /public/test we only have index.html

Expected result is to have post assets copied somewhere to the public folder.
However there might be something that I'm missing, please clarify.

Thank you

**Comment by Xuanwo** [comment]
I don't think it is a bug.
If your want to add a page instead of a post, you need to add a floder in `source` instead of `_post`.
From my ponit of view, hexo will miss the floder in `_post`.

**Comment by szarouski** [comment]
Let me put it other way, it you try to use `{% asset_img myimageinpostfolder.jpg %}`, it will work for hexo server, but will not work for hexo server -s, once you generate your files, because posts asset folder is missing. Also `hexo new postname` is creating postname folder, I believe that is on purpose.

**Comment by tommy351** [comment]
The asset is in router but somehow not generated. I'm trying to find the reason.
