### ISSUE TITLE
能否增加访客统计功能？// How to increase the number of visitors statistics?

### ISSUE THREAD

**Issue by ccchan** [hexojs/hexo#1042]

**Comment by tommy351** [comment]
Use Google Analytics.

**Comment by youxiachai** [comment]
这个应该是主题功能..跟hexo 没啥关系吧..

**Comment by ccchan** [comment]
Google Analytics 在天朝局域网内有时访问不了，即使能访问又要登陆点击什么的很麻烦，想直接在网站底部显示访客人数。

**Comment by Xuanwo** [comment]
Hexo是一个静态博客，不能存储动态数据。

想要实现这样的功能，你可以
- 第三方服务，比如google统计，百度统计
- 自己基于某云平台开发一个计数统计

而以上所有操作，都与Hexo本身无关。
*google了一下“hexo 访客统计”，内容还是蛮多的，可以去看看*

**Comment by ccchan** [comment]
嗯，谢谢。

我已经注册了Google 和百度统计，用这两种方式进行访客统计。

我提出这个问题源于在网上看到有人说用firebase 在线数据库可以实现。

**Comment by Xuanwo** [comment]
我刚才去看了firebase，感觉很有意思，研究一下。
不过这个issue可以先关掉了~
