### ISSUE TITLE
Date showing problem

### ISSUE THREAD

**Issue by ronansparks** [hexojs/hexo#1043]
For example. 
I wrote a article last night which contains a external link url  xxx.com/bla    , now the url has been changed to xxx.com/bbbbb by other peole. So I change the url to new xxx.com/bbb, but the date shows The date I modified, not the time create. 
What If I wrote a article last year, I want to update. It changed to now.  
Why can't I set the article showing date with its create time.

**Comment by Xuanwo** [comment]
modify your yml info in your post

**Comment by ronansparks** [comment]
@Xuanwo can you give more specific? I can't find this kind of setting neither in offical document nor _config.yml file

**Comment by ronansparks** [comment]
If you delete the date line in your .md file, They'd put the last modify time as the post time.
