### ISSUE TITLE
Feature request: Split Hexo in hexo-cli for global installation and an project-specific (local) hexo package for Hexo3

### ISSUE THREAD

**Issue by gingters** [hexojs/hexo#1045]
Hello,

title probably says it's all. This way, with a global hexo-cli that just executes a locally (per project) installed hexo, one could have separate versions per project. That would especially interesting now with Hexo3. This way one could have stable Hexo blos and some experimental hexo3 upgraded projects without breaking existing projects. Prominent examples: grunt & grunt-cli.

**Comment by tommy351** [comment]
This sounds interesting. But we need to discuss about what should put in hexo-cli.

**Comment by Xuanwo** [comment]
maybe the mode like node.js&hexo?

**Comment by Xuanwo** [comment]
something like
```
hexo-cli ls
//for listing all the version installed
hexo-cli ls-remote
//for listing the version provided
hexo-cli install 3.0
//to install hexo@beta
hexo-cli remove 3.0
//to remove hexo@beta
```

**Comment by tommy351** [comment]
It's meaningless to do npm things in hexo-cli. It should like grunt & grunt-cli or gulp & gulp-cli.

**Comment by Xuanwo** [comment]
OK, now i got it.

**Comment by gingters** [comment]
Yeah. In fact, hexo-cli should only check if there is hexo locally installed. If not, tell the user. If yes, just pass the whole commandline arguments to the local hexo and that's it.

This way, the user can either just install hexo locally in his project and can call ./node_modules/hexo/hexo to execute it. If he's a shell wizard he probably sets an alias and is fine to go. If he wants more convenience, he installs hexo-cli globally and can execute it directly.

Main benefit is that you don't have a single version of hexo installed for all your projects. You can have different versions of hexo locally, one per project. The CLI would simply be a totally stupid thing checking for a local installation and passing the arguments to it. This way the cli would never have to be updated, as it does not really contain any logic of hexo.

**Comment by tommy351** [comment]
Some basic plugins should be put in hexo-cli:

- console: help, init, migrate, version
- some filters
- some renderers

And for the backward compatibility, `bin/hexo` will be remained, but call `hexo-cli` directly. Just like gulp 4.0.

This is my thought so far. Anything missed?

**Comment by gingters** [comment]
I would make the cli as lean as possible. If you put a filter in it, and in Hexo 4 you would need to introduce an incompatible change in the filter API, the CLI would be incompatible with the new version. Same goes for renderers.

Also: Version should be in both. You don't actually want to see the cli version, but rather the version installed in your project. Displaying the cli version would be a bonus rather, as it would be expected to be as version agnostic as possible.

This is why init is difficult indeed. There's sort of a chicken-egg problem. Without init in the cli you would not be able to set up a new project that easily. However, if you have init in it, what layout would it create? The version of the cli or the latest Hexo? Init would need to be more sophisticated, downloading the latest project template and use that unless the user states a specific version, making it as version agnostic as possible.

So, I would need to ponder about that a bit more and dig deeper in the hexo structure to make a good and well thought out proposal.

**Comment by tommy351** [comment]
I just pushed a new package: [hexo-cli](https://github.com/hexojs/hexo-cli)

**Comment by Xuanwo** [comment]
I can't get your idea.
what's the difference between `grunt & grunt-cli` mode and `node.js & nvm` mode ?
It seems like the `hexo-cli` do more things than I used to thinl. But I think my idea will make it more clear that the `hexo-cli` control the hexo version, and `hexo` just do the render job.

**Comment by tommy351** [comment]
`hexo-cli` don't control versions. It's npm's job. These are what `hexo-cli` do:

- Load Hexo for the current directory.
- Initialize a new Hexo site.

**Comment by szarouski** [comment]
@tommy351, can you please give me a hint, what is current way of running hexo server from script (for PM2)? I've been using following code, but of course it is not working anymore
```js
require('hexo/lib/cli/init')({
	_: ['server'],
	'static': true
});
```

Thank you

**Comment by szarouski** [comment]
Nevermind, I can do something like `pm2 start app.js -- server -s` and contents of the app.js will be 
```js
require('hexo-cli');
```
Very nice, thanks for great job!
