### ISSUE TITLE
node v0.12.0, npm 2.5.1时安装失败

### ISSUE THREAD

**Issue by bigbigwei** [hexojs/hexo#1047]
如题，mac下安装报错。
环境：node 0.12.0  npm 2.5.1

**Comment by leesei** [comment]
Please provide more info.
Or close this issue if it is already solved.

**Comment by Xuanwo** [comment]
hexo只在node0.10,0.11以及iojs下测试通过

**Comment by leesei** [comment]
I'm using hexo3 on node v0.12.1 without problem.
