### ISSUE TITLE
Error parse parenthesis in the link

### ISSUE THREAD

**Issue by breestealth** [hexojs/hexo#1048]
If I want to write a link to a URI with the parenthesis, Hexo will give the error result no matter whether I use the escape character(\\).
For example:
```
[Click and get an alert](javascript:alert\("Alert For U."\))
```
will the the result:
```
<a href='javascript:alert\("Alert For U."\' target="_blank" rel="external">Click and get an alert</a>
")"
```

**Comment by leesei** [comment]
Use [link tag](https://hexo.io/docs/tag-plugins.html#Link).
