### ISSUE TITLE
How could I append a permalink after every posts

### ISSUE THREAD

**Issue by kqkq** [hexojs/hexo#1053]
I've tried `hexo.extend.filter.register('before_post_render',function);` but failed. `post.permalink` seems undefined on this stage.

**Comment by tommy351** [comment]
What do you want to do with permalink? Maybe you can try to edit `permalink` setting.

**Comment by kqkq** [comment]
I hope there's a link to original post when someone (or some automatic program) repost my post.

**Comment by leesei** [comment]
How about modifying your theme's layout?
`post.permalink` should be valid there.

**Comment by Xuanwo** [comment]
agree with @leesei , your just need to insert it int your md.

**Comment by Xuanwo** [comment]
Closed for sovled.
