### ISSUE TITLE
hexo shows error message

### ISSUE THREAD

**Issue by haifengkao** [hexojs/hexo#1055]
'hexo' command shows the error message:
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

Am I missing something in the installation steps?

**Comment by appleboy** [comment]
What is hexo version? 2.x or 3.x

**Comment by haifengkao** [comment]
hexo --version
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
hexo: 3.0.0-rc.4
os: Darwin 14.1.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l

**Comment by tommy351** [comment]
Maybe it's related to https://github.com/trentm/node-bunyan/issues/216

**Comment by tommy351** [comment]
Try to install with `--no-optional` option.

```
$ npm install hexo --no-optional
```

**Comment by haifengkao** [comment]
Thx. It works. Can you explain what happened?

**Comment by tommy351** [comment]
Though I don't know why dtrace module not working on your computer so far. In fact, Hexo didn't use dtrace feature and it's just a optional dependency. So you can just skip the installation.

**Comment by haiiiiiyun** [comment]
```
$ npm install hexo --no-optional
 ```
also works for me.

Environment:

```
hexo_blog $ hexo --version
hexo: 3.1.1
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by iqiancheng** [comment]
```
$ npm install hexo --no-optional
```
it works.

**Comment by Xuanwo** [comment]
In the newest version , you may need `npm install hexo --no-optional --save`

**Comment by JeremyDa** [comment]
$ npm install hexo --no-optional
also works for me.

**Comment by geekplux** [comment]
$ npm install hexo --no-optional

it doesn't work for me...

**Comment by zgpeace** [comment]
work for me, thx

**Comment by FrancisShi** [comment]
"npm uninstall hexo" first  if you need

**Comment by JeffreyChu** [comment]
first: $ npm uninstall hexo
then: $ npm install hexo --no-optional --save

That works for me.

**Comment by allenkung** [comment]
Reinstall hexo with --no-optional doesn't work for me. So I backup and delete my hexo folder and redo hexo init. After that this error msg gone.

**Comment by lvtraveler** [comment]
I had install hexo --no-optional much times,but it does not work for me when hexo deploy.

**Comment by B1gtang** [comment]
npm install hexo --no-optional

It works for me.

**Comment by leesei** [comment]
@lvtraveler you are probably having a different issue
please open new issue and post your log
