### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by RomanBogachev** [hexojs/hexo#1058]
Greetings! 

I'm migrate from Octopress my markdown files to Hexo, but code syntax highlight doesn't show correctly.
I try to use "Backtick Code Block" and "Swig Code Block" like Octopress, but it looks equally.

Maybe need plugin or not? 
Help me please with this issue.

**Comment by RomanBogachev** [comment]
For example "diff", "sql", "php" doesn;t display correctly.

How it should look like

```diff
=== modified file 'support-files/mysql.server.sh'
--- support-files/mysql.server.sh	2013-07-16 17:09:54 +0000
+++ support-files/mysql.server.sh	2014-02-17 10:10:30 +0000
@@ -147,68 +147,12 @@
 		    datadir_set=1
 	;;
       --pid-file=*) mysqld_pid_file_path=`echo "$arg" | sed -e 's/^[^=]*=//'` ;;
+      --socket=*) socket=`echo "$arg" | sed -e 's/^[^=]*=//'` ;;
       --service-startup-timeout=*) service_startup_timeout=`echo "$arg" | sed -e 's/^[^=]*=//'` ;;
     esac
   done
 }
 
-wait_for_pid () {
-  verb="$1"           # created | removed
-  pid="$2"            # process ID of the program operating on the pid-file
-  pid_file_path="$3" # path to the PID file.
-
-  i=0
-  avoid_race_condition="by checking again"
-
-  while test $i -ne $service_startup_timeout ; do
-
-    case "$verb" in
-      'created')
-        # wait for a PID-file to pop into existence.
-        test -s "$pid_file_path" && i='' && break
-        ;;
-      'removed')
-        # wait for this PID-file to disappear
-        test ! -s "$pid_file_path" && i='' && break
-        ;;
-      *)
-        echo "wait_for_pid () usage: wait_for_pid created|removed pid pid_file_path"
-        exit 1
-        ;;
-    esac
-
-    # if server isn't running, then pid-file will never be updated
-    if test -n "$pid"; then
-      if kill -0 "$pid" 2>/dev/null; then
-        :  # the server still runs
-      else
-        # The server may have exited between the last pid-file check and now.  
-        if test -n "$avoid_race_condition"; then
-          avoid_race_condition=""
-          continue  # Check again.
-        fi
-
-        # there's nothing that will affect the file.
-        log_failure_msg "The server quit without updating PID file ($pid_file_path)."
-        return 1  # not waiting any more.
-      fi
-    fi
-
-    echo $echo_n ".$echo_c"
-    i=`expr $i + 1`
-    sleep 1
-
-  done
-
-  if test -z "$i" ; then
-    log_success_msg
-    return 0
-  else
-    log_failure_msg
-    return 1
-  fi
-}
-
```


How it's realy look like:

![](http://i.bogachev.biz/uploads/big/a89fb8efebf868441678b0f9ad3f6d2a.png)


How i can enable normal syntax highlight?

**Comment by RomanBogachev** [comment]
Who can share information as possible to make it?

**Comment by Voidly** [comment]
I think you can read this <http://popozhu.github.io/2013/06/15/hexo%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE/>.You may get help from it.Enjoy hexo!

**Comment by lzjqsdd** [comment]
@RomanBogachev ,whic theme did you use?Pacman or others? I have seen this problem before,didn't work for every language

**Comment by RomanBogachev** [comment]
@Voidly Thank you! will observe later)
@lzjqsdd I am use hueman theme. https://github.com/ppoffice/hexo-theme-hueman

**Comment by RomanBogachev** [comment]
@Voidly I accept the fact that you offered. But it's not. I have markdown syntax.
I have more than 400 articles that need to be corrected for the code block.
This is not a good idea ;)

On Octopress was http://pygments.org/ with http://ethanschoonover.com/solarized

**Comment by Voidly** [comment]
@Xuanwo

**Comment by Xuanwo** [comment]
Well, the problem now become how to correct the codeblocks in files?
Maybe you can use some editors to do this, for example, Sublime Text 3, it can search and change words in files.

**Comment by RomanBogachev** [comment]
@Xuanwo 
Please read my first message again.
Pay special attention to the attached images.
And their differences.

To be clear, I need highlighting like GitHub, when using markdown syntax.

**Comment by leesei** [comment]
Hexo uses highlight.js, which [supports diff](https://github.com/isagalaev/highlight.js/tree/master/src/languages).

Did you specify the lang in backtick syntax?

<pre>
```diff
=== modified file 'support-files/mysql.server.sh'
--- support-files/mysql.server.sh   2013-07-16 17:09:54 +0000
+++ support-files/mysql.server.sh   2014-02-17 10:10:30 +0000
@@ -147,68 +147,12 @@
            datadir_set=1
    ;;
       --pid-file=*) mysqld_pid_file_path=`echo "$arg" | sed -e 's/^[^=]*=//'` ;;
+      --socket=*) socket=`echo "$arg" | sed -e 's/^[^=]*=//'` ;;
       --service-startup-timeout=*) service_startup_timeout=`echo "$arg" | sed -e 's/^[^=]*=//'` ;;
     esac
   done
 }

-wait_for_pid () {
-  verb="$1"           # created | removed
-  pid="$2"            # process ID of the program operating on the pid-file
-  pid_file_path="$3" # path to the PID file.
-
-  i=0
-}
```
</pre>

**Comment by RomanBogachev** [comment]
@leesei 
But it does not work =/
![](http://habrastorage.org/files/b64/3bf/a5b/b643bfa5bdc24f598d4d7cec8ed9379b.png)

**Comment by celsomiranda** [comment]
I would need to examine the output code to be sure, but I'm guessing that your highlight theme in the CSS doesn't have support for `diff` code blocks.

Hexo only generates the HTML, you'll need the proper CSS to style the code blocks.

**Comment by leesei** [comment]
Weird, those CSS rules should be in highlight.js.
I tried the code block in [xing5/hexo-theme-codeland](https://github.com/xing5/hexo-theme-codeland).

![selection_010](https://cloud.githubusercontent.com/assets/544400/7363040/2e6c027a-eda6-11e4-94d8-f47c5a8a095a.png)


The `pre diff` rule is in `/css/style.css:1254-1257`
```css
pre .deletion {
  background: #fdd;
}
pre .addition {
  background: #dfd;
}
```

**Comment by celsomiranda** [comment]
Like I said, highlight.js just adds classes to HTML elements. It's up to the CSS to provide the decorations.

Highlight.js does not inject css into the HTML, nor it should. If it did, It would always take precedence over the CSS rules, making customs themes unable to style the code blocks.

As I see it, this is not a Hexo bug, and should be taken to theme developer.

**Comment by RomanBogachev** [comment]
@celsomiranda Thank`s. I`ll try to contact with theme developer.
