### ISSUE TITLE
In 3.0.0-rc.4, can not apply responsive theme like jacman, pacman

### ISSUE THREAD

**Issue by yyz20002008** [hexojs/hexo#1059]
according the command in https://github.com/hexojs/hexo
I create hexo folder but not blog folder
I run 

$ hexo init // in hexo folder

then

$ npm install

then

$ hexo g
$ hexo s

Right the original theme landscape works fine.
Then I  want to change theme to jscman.
I install upon commands in https://github.com/wuchong/jacman

$ git clone https://github.com/wuchong/jacman.git themes/jacman
$cd themes/jacman
$git pull origin master

Then I change _config.yml file in hexo folder:
theme: jacman
I open git base in hexo folder
run
$ hexo clean
$ hexo g
$ hexo s
it doesn't work. I found it can not find style.css file.
![image](https://cloud.githubusercontent.com/assets/1105915/6250532/1973dc5e-b754-11e4-992a-82c7f6d3a9b0.png)

I read the solution in 2.0.0-rc3, but it doen't work in this version.

**Comment by Xuanwo** [comment]
in RC-4, you can see https://github.com/hexojs/hexo/issues/1054

**Comment by yyz20002008** [comment]
I ran this two instructions
npm install hexo-cli -g
npm install hexo@beta --save

but it doesn't work

**Comment by Xuanwo** [comment]
can i see your _config.yml?
maybe there are somgthing wrong.

**Comment by yyz20002008** [comment]
Thanks. Happy the Goat Year!
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: jacman

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:

**Comment by Xuanwo** [comment]
maybe your should run 'npm install hexo-renderer-stylus --save'

**Comment by yyz20002008** [comment]
it still doesn't work

**Comment by Xuanwo** [comment]
make your `_config.yml` like this:
```
theme: examlpe
exclude_generator:
plugins:
- hexo-renderer-stylus
```

it seems that the hexo hadn't excute your css file.

**Comment by yyz20002008** [comment]
I think there is no white space after "exclude_generator:" and "plugins:".
It looks like there is a whiter space between "-" and "hexo-renderer-stylus".
But it still doesn't work

**Comment by Xuanwo** [comment]
use other theme to have a test that make sure your setting is right.

**Comment by yyz20002008** [comment]
I tested my hexo works in theme of "air" and "light", but doesn't work in "jacman" and "pacman", which are responsive themes.

**Comment by wuchong** [comment]
maybe you have not install npm successfully ?  try `$ sudo  npm install` again ?

**Comment by yyz20002008** [comment]
actually "sudo: command not found "

**Comment by wuchong** [comment]
run `npm ls` in your hexo folder , and post the result here

**Comment by yyz20002008** [comment]
Thanks a lot.
Here it is:
hexo-site@0.0.0 g:\UTDALLAS\hexo
├─┬ hexo@3.0.0-rc.4
│ ├── abbrev@1.0.5
│ ├── archy@1.0.0
│ ├── bluebird@2.9.9
│ ├─┬ bunyan@1.3.3
│ │ ├─┬ dtrace-provider@0.4.0
│ │ │ └── nan@1.5.3
│ │ ├─┬ mv@2.0.3
│ │ │ ├─┬ mkdirp@0.5.0
│ │ │ │ └── minimist@0.0.8
│ │ │ ├── ncp@0.6.0
│ │ │ └── rimraf@2.2.8
│ │ └── safe-json-stringify@1.0.
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├─┬ cheerio@0.18.0
│ │ ├─┬ CSSselect@0.4.1
│ │ │ ├── CSSwhat@0.4.7
│ │ │ └─┬ domutils@1.4.3
│ │ │   └── domelementtype@1.1.
│ │ ├─┬ dom-serializer@0.0.1
│ │ │ └── domelementtype@1.1.3
│ │ ├── entities@1.1.1
│ │ ├─┬ htmlparser2@3.8.2
│ │ │ ├── domelementtype@1.1.3
│ │ │ ├── domhandler@2.3.0
│ │ │ ├── domutils@1.5.1
│ │ │ ├── entities@1.0.0
│ │ │ └─┬ readable-stream@1.1.1
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10
│ │ └── lodash@2.4.1
│ ├─┬ hexo-cli@0.1.2
│ │ └── minimist@1.1.0
│ ├── hexo-front-matter@0.2.2
│ ├─┬ hexo-fs@0.1.3
│ │ ├─┬ chokidar@0.12.6
│ │ │ ├── async-each@0.1.6
│ │ │ └─┬ readdirp@1.3.0
│ │ │   ├── graceful-fs@2.0.3
│ │ │   ├─┬ minimatch@0.2.14
│ │ │   │ ├── lru-cache@2.5.0
│ │ │   │ └── sigmund@1.0.0
│ │ │   └─┬ readable-stream@1.0
│ │ │     ├── core-util-is@1.0.
│ │ │     ├── inherits@2.0.1
│ │ │     ├── isarray@0.0.1
│ │ │     └── string_decoder@0.
│ │ ├── escape-string-regexp@1.0
│ │ └── graceful-fs@3.0.5
│ ├─┬ hexo-i18n@0.2.1
│ │ └── sprintf-js@1.0.2
│ ├─┬ hexo-util@0.1.4
│ │ └── highlight.js@8.4.0
│ ├─┬ js-yaml@3.2.6
│ │ ├─┬ argparse@0.1.16
│ │ │ ├── underscore@1.7.0
│ │ │ └── underscore.string@2.4
│ │ └── esprima@1.0.4
│ ├── lodash@3.2.0
│ ├─┬ minimatch@2.0.1
│ │ └─┬ brace-expansion@1.1.0
│ │   ├── balanced-match@0.2.0
│ │   └── concat-map@0.0.1
│ ├── moment@2.9.0
│ ├── moment-timezone@0.3.0
│ ├─┬ nunjucks@1.1.0
│ │ ├─┬ chokidar@0.9.0
│ │ │ └── recursive-readdir@0.0
│ │ └─┬ optimist@0.6.1
│ │   ├── minimist@0.0.10
│ │   └── wordwrap@0.0.2
│ ├── pretty-hrtime@1.0.0
│ ├─┬ strip-indent@1.0.1
│ │ └── get-stdin@4.0.1
│ ├─┬ swig@1.4.2
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.2
│ │ └─┬ uglify-js@2.4.16
│ │   ├── async@0.2.10
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.2
│ │   ├─┬ source-map@0.1.34
│ │   │ └── amdefine@0.1.0
│ │   └── uglify-to-browserify@1
│ ├── text-table@0.2.0
│ ├─┬ through2@1.1.1
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.3
│ │ └── xtend@4.0.0
│ ├─┬ tildify@1.0.0
│ │ └── user-home@1.1.1
│ ├── titlecase@1.0.2
│ └─┬ warehouse@1.0.1
│   ├── cuid@1.2.4
│   ├── graceful-fs@3.0.5
│   └─┬ JSONStream@0.10.0
│     ├── jsonparse@0.0.5
│     └── through@2.3.6
├─┬ hexo-generator-archive@0.1.1
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@2.0.0
├─┬ hexo-generator-category@0.1.1
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@2.0.0
├─┬ hexo-generator-index@0.1.0
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@2.0.0
├─┬ hexo-generator-tag@0.1.0
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@2.0.0
├─┬ hexo-renderer-ejs@0.1.0
│ ├── ejs@1.0.0
│ └── lodash@2.4.1
├─┬ hexo-renderer-marked@0.2.4
│ ├─┬ hexo-util@0.1.4
│ │ ├── bluebird@2.9.9
│ │ └── highlight.js@8.4.0
│ ├── marked@0.3.3
│ ├── object-assign@2.0.0
│ └─┬ strip-indent@1.0.1
│   └── get-stdin@4.0.1
├─┬ hexo-renderer-stylus@0.2.1
│ ├── nib@1.1.0
│ └─┬ stylus@0.49.3
│   ├── css-parse@1.7.0
│   ├─┬ debug@2.1.1
│   │ └── ms@0.6.2
│   ├─┬ glob@3.2.11
│   │ ├── inherits@2.0.1
│   │ └─┬ minimatch@0.3.0
│   │   ├── lru-cache@2.5.0
│   │   └── sigmund@1.0.0
│   ├── mkdirp@0.3.5
│   ├── sax@0.5.8
│   └─┬ source-map@0.1.43
│     └── amdefine@0.1.0
└─┬ hexo-server@0.1.2
  ├── bluebird@2.9.9
  ├─┬ chalk@0.5.1
  │ ├── ansi-styles@1.1.0
  │ ├── escape-string-regexp@1.0.
  │ ├─┬ has-ansi@0.1.0
  │ │ └── ansi-regex@0.2.1
  │ ├─┬ strip-ansi@0.3.0
  │ │ └── ansi-regex@0.2.1
  │ └── supports-color@0.2.0
  ├─┬ compression@1.4.1
  │ ├─┬ accepts@1.2.4
  │ │ ├─┬ mime-types@2.0.9
  │ │ │ └── mime-db@1.7.0
  │ │ └── negotiator@0.5.1
  │ ├── bytes@1.0.0
  │ ├─┬ compressible@2.0.2
  │ │ └── mime-db@1.7.0
  │ ├─┬ debug@2.1.1
  │ │ └── ms@0.6.2
  │ ├── on-headers@1.0.0
  │ └── vary@1.0.0
  ├─┬ connect@3.3.4
  │ ├─┬ debug@2.1.1
  │ │ └── ms@0.6.2
  │ ├─┬ finalhandler@0.3.3
  │ │ ├── escape-html@1.0.1
  │ │ └─┬ on-finished@2.2.0
  │ │   └── ee-first@1.1.0
  │ ├── parseurl@1.3.0
  │ └── utils-merge@1.0.0
  ├── mime@1.3.4
  ├─┬ morgan@1.5.1
  │ ├── basic-auth@1.0.0
  │ ├─┬ debug@2.1.1
  │ │ └── ms@0.6.2
  │ ├── depd@1.0.0
  │ └─┬ on-finished@2.2.0
  │   └── ee-first@1.1.0
  ├── object-assign@2.0.0
  ├── open@0.0.5
  └─┬ serve-static@1.9.1
    ├── escape-html@1.0.1
    ├── parseurl@1.3.0
    ├─┬ send@0.12.1
    │ ├─┬ debug@2.1.1
    │ │ └── ms@0.6.2
    │ ├── depd@1.0.0
    │ ├── destroy@1.0.3
    │ ├─┬ etag@1.5.1
    │ │ └── crc@3.2.1
    │ ├── fresh@0.2.4
    │ ├── ms@0.7.0
    │ ├─┬ on-finished@2.2.0
    │ │ └── ee-first@1.1.0
    │ └── range-parser@1.0.2
    └── utils-merge@1.0.0

**Comment by yyz20002008** [comment]
anyone has any idea?

**Comment by wuchong** [comment]
is there any error message in the terminal?

**Comment by yyz20002008** [comment]
Actually when I run "npm ls", there is no error. Do you think this result is normal?

**Comment by yyz20002008** [comment]
The issue is that style.css can not be found. But how can I fix this?

**Comment by wuchong** [comment]
I have not so many output with npm ls .  I mean is there any error after hexo s ？

发自我的 iPhone

**Comment by yyz20002008** [comment]
sorry, I just got what you mean.
=========================================
The error is
ERROR Asset render failed: css/style.css
TypeError: hexo/themes/pacman/source/css/_base/variable.styl:54:43
   50| //comment
   51| duoshuo = hexo-config("duoshuo.enable")
   52|
   53| //highlight
   54| highlight = hexo-config("highlight.enable")
-------------------------------------------------^
   55|

Cannot read property 'enable' of undefined
=================================================
I read this issue:https://github.com/zhyu/yaht/issues/1
But I have 
===================
highlight:
 enable: true
 line_number: true
 tab_replace:
======================
in my _config.yml

**Comment by wuchong** [comment]
please use \`\`\`  include your output and file content.  your response is unreadable

发自我的 iPhone

**Comment by yyz20002008** [comment]
it looks good right now?

**Comment by wuchong** [comment]
reinstall your hexo to version 2.8.3 which is stable for all I know 



发自我的 iPhone

**Comment by yyz20002008** [comment]
Do you know how can I install version 2.8.3? right now command I know to install hexo is only "npm install hexo-cli -g"

**Comment by wuchong** [comment]
npm uninstall hexo -g
npm install hexo@2.8.3 -g

发自我的 iPhone

**Comment by yyz20002008** [comment]
Thanks.Right now jacmen works. It is very nice.
I may update hexo after he release a stable version of hexo.
![qq 20140328201256](https://cloud.githubusercontent.com/assets/1105915/6424956/c7bed998-bed5-11e4-9f69-70c97aa87ad2.png)

**Comment by wuchong** [comment]
congratuations 

发自我的 iPhone

**Comment by tommy351** [comment]
Add highlight setting to _config.yml or update to hexo-renderer-stylus@0.2.3.

**Comment by wuchong** [comment]
@tommy351  thank u. 

A question: 

How to get the `highlight` setting in `blog/_config.yml` ? 

`hexo-config("highlight.enable")`  can only get settings in `themes/jacman/_config.yml`

**Comment by Xuanwo** [comment]
in Hexo 3.0,  There is a `highlight` setting ~

**Comment by 12obin** [comment]
I install hexo on windows 10, I am going to use hueman theme, but the result is not like the demo
![error-hueman-theme-hexo](https://cloud.githubusercontent.com/assets/6492764/12529115/dea73372-c1df-11e5-87a1-37c44ef7b894.PNG)

**Comment by LOUSANPANG** [comment]
**问题描述 🌹**
1. 之前也是旧版本,好久没更新,今天重新更新了下hexo
```
    "hexo": "^4.2.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.1.0",
    "hexo-renderer-stylus": "^0.1.0",
    "hexo-server": "^1.0.0"
```
2. `hexo g` 报css解析不出来
3. 降级
···
npm install hexo@2.8.3 -g
npm install hexo-renderer-ejs@0.1.0 
hexo-renderer-marked@0.1.0 
hexo-renderer-stylus@0.1.0
···
2. 降级后，报 `primordials is not defined`
![image](https://user-images.githubusercontent.com/36870764/82449813-5d7b4b80-9ade-11ea-9f84-f351fc097c43.png)
