### ISSUE TITLE
change hexo server to hexo serve

### ISSUE THREAD

**Issue by gaboesquivel** [hexojs/hexo#1060]
I think it the verb makes more sense, and kinda standard across projects.
It's also consistent with other options publish, render, generate

**Comment by tommy351** [comment]
In fact, `hexo serve` is also available in Hexo 3 because we use [abbrev](https://github.com/isaacs/abbrev-js).

**Comment by gaboesquivel** [comment]
I think it would be good to make `hexo serve` the official command in docs and --help ... and keep supporting server.  For consistency.

**Comment by leesei** [comment]
@tommy351 I concur with @gaboesquivel for the consistency of terms.
