### ISSUE TITLE
draft are generated in production

### ISSUE THREAD

**Issue by eephyne** [hexojs/hexo#1061]
I currently learn to use hexo and found weird behavior

When I do a draft, its created in \_draft (so far so good)
and hexo server don't render it.
But if I do hexo server --draft __once__ ,then even if I run it without --draft flag it still render it.

Even worse when generating and deploying it render the draft like it was a normal post.

If I delete the _draft folder (or just the draft itself), the server still render it and the generate still generate it.

The only way I found to remove it , is to hexo clean.

It seem that hexo server --draft is modifying something that make believe  to hexo that the draft is not a draft anymore.

**Comment by eephyne** [comment]
I tested with two projects with two different computer, still the same issue.

I wonder what I'm doing wrong because draft like that are totally useless.

**Comment by eephyne** [comment]
just tested git version 3.0.0-rc4 and the same happen (and the --draft is not working anymore, only render_draft in _config work)

**Comment by leesei** [comment]
Hexo 3 is stable and has more themes now.
Please open new issue if the problem persists with latest build.

**Comment by daiyitastic** [comment]
I'm having this problem!

My drafts are being generated when I run `hexo generate`.
