### ISSUE TITLE
exclude_generator post

### ISSUE THREAD

**Issue by gabdara** [hexojs/hexo#1062]
I'm interested in only generating the home page and not the individual posts.
I've set in _config.yml `exclude_generator: post` but it doesn't seem to work.
I'm using hexo v3.0.0-rc.4.

Regards!

**Comment by tommy351** [comment]
`exclude_generator` setting was removed in 3.0.0.beta-1

**Comment by gabdara** [comment]
@tommy351 Thanks for answering!
Any way I could generate only the home page?
