### ISSUE TITLE
图片位置问题

### ISSUE THREAD

**Issue by maplewizard** [hexojs/hexo#1064]
我的博客位置设置在maplewizard.github.io/blog/下，图片的位置在maplewizard.github.io/blog/images下，但是hexo自动索引到maplewizard.github.io/images下，因此出现找不到图片的情况。请问如何解决？是否需要添加类似 {{BASE_PATH}}之类的全局变量？

**Comment by iissnan** [comment]
从两个方面确认下：

1. 站点配置 `_config.yml` 中 `root` 路径的设置。
2. 图片的引用写法，绝对路径引用 `/images/` 还是相对路径引用 `images/`。

**Comment by maplewizard** [comment]
@iissnan 我用的`/images/`,是要用`images/` ?

**Comment by iissnan** [comment]
如果是在 post 里面，应该要写成 `![](/blog/images/)`。

**Comment by maplewizard** [comment]
我以为在配置文件中指定了根目录他会自动添加路径

**Comment by Mindzy** [comment]
我也是这个问题，希望在以后版本里解决这个问题，希望能在配置文件中指定了根目录Hexo会自动添加路径。否则写文章的时候预览看不到图，改来改去的很麻烦。

**Comment by xiaoheiAh** [comment]
为什么我的图片总加载不出来呢?
`![](/source/images/mint.png "Linux Mint")`
这种方法加载出来都是框框 本地预览没有问题 deploy到github就不行了
还有就是官方的改post_asset_folder=true 用
`{%asset_img example.png example%}`
本地预览没效果，发布到github上更没有.....
求解！
