### ISSUE TITLE
Custom generator to render embeddable posts

### ISSUE THREAD

**Issue by c0bra** [hexojs/hexo#1065]
I'd like to be able to render a post or set of posts using just the post template, and not have it wrapped by the layout.

I think I'm getting close but I don't know if I can do it with the base render() method supplied to generators, or if I'll have to work it out doing hexo.route.set.

Has anyone tried to do something like this?

**Comment by leesei** [comment]
Have you tried `layout = false`?
Or set a custom layout `layout = mylayout` and add `mylayout.ejs` to the theme?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
