### ISSUE TITLE
[Q] Source folder.htaccess

### ISSUE THREAD

**Issue by acesyde** [hexojs/hexo#107]
Hi,

In my Sources folder, I have an .htaccess for my website.

It's possible to copy the .htaccess file automatically in the generate folder when I use hexo generate cmd ?

Thk a lot

**Comment by floriancargoet** [comment]
What's the best way to include a `.htaccess` file?

**Comment by borisschapira** [comment]
+1

**Comment by wudong** [comment]
+1 same problem.

**Comment by victornalves** [comment]
+1

**Comment by moklick** [comment]
Why is this closed? A possible workaround is to copy the .htaccess in the public folder and then run `hexo deploy`. For this we added this line to our package.json:
```
"scripts":{
    "deploy" : "cp .htaccess public && hexo deploy"
}
```

Then you can run `npm run deploy`.

**Comment by Macxim** [comment]
@moklick Even if it's copied to the `public` folder, it's completely ignored when pushing to the GitHub repo.

**Comment by moklick** [comment]
@Macxim I am using hexo-deployer-ssh and everything works fine. Are you using hexo-deployer-git to deploy your site?

**Comment by Macxim** [comment]
@moklick Yes, indeed I am.

**Comment by fourpixels** [comment]
I don't understand what's the problem with that, as it's a pretty common issue? At least provide some workaround!

I've seen that there's a code for including/excluding files, but it works **only** for content (posts or pages) inside /source folder.
Also in themes, the source processor just uses: 
```js
if (common.isHiddenFile(path) || common.isTmpFile(path) || ~path.indexOf('node_modules'))
    return false;
```

Why is not similar as the asset processor:
```js
if (common.isTmpFile(path) || common.isMatch(path, ctx.config.exclude))
    return;

if (common.isHiddenFile(path) && !common.isMatch(path, ctx.config.include)) {
    return;
}
```

Just saying "no" is not a professional open-source solution. It sounds like "I don't want to fix this"..

**Comment by lebarde** [comment]
+1 for this.

**Comment by scorchio** [comment]
+1 - it would be really nice if deploying htaccess files would be possible.

**Comment by fourpixels** [comment]
Unfortunately it seems like this is dead :(
@tommy351 @naokiy

**Comment by lebarde** [comment]
This has been solved. See my comment!

**Comment by NoahDragon** [comment]
@scorchio @fourpixels 
Add to the _config.yml:
``` yml
include:
  - .htaccess
```

**Comment by scorchio** [comment]
@NoahDragon This does the trick, thanks!

**Comment by Loyea** [comment]
@NoahDragon  it works! thanks!

**Comment by oupala** [comment]
Just to mention that the .htaccess file must be in the `source` directory.

I tried several times unsuccessfully, so it might help anyone.

**Comment by TimDaub** [comment]
I added 

```
include
  - ".well-known/*"
```

in config.yaml and now when I do `hexo clean && hexo deploy` it even tells me that `.well-known/keybase.txt` has been found. But it seems deploy does still not upload it to GitHub?

**Comment by TimDaub** [comment]
👋 It's me again. I had to do this again and I still notice that things are somewhere broken. I followed this thread and issue #2715 and I seem to not be able to make it work.

I'd really like to add a file to `.well-known` and simply use `hexo deploy`. If anyone points me to the source code, I can try to make an edit and send over a PR.
