### ISSUE TITLE
current hexo version 3.0.0.rc4,not work with plugins like hexo-admin,hexo-generator-feed,hexo-generator-sitemap

### ISSUE THREAD

**Issue by bluesky4485** [hexojs/hexo#1072]
see the issues in hexo-admin:
https://github.com/jaredly/hexo-admin/issues/19

**Comment by celsomiranda** [comment]
I don't think this is an issue with hexo.

The version bump from 2 to 3 means that third party stuff will be broken.

As I see it, maintainers of the third party plugins are responsible for compatibility. 

IMO this should not be an issue here.

**Comment by leesei** [comment]
These are working with 3.0
    "hexo-generator-feed": "^1.0.1",
    "hexo-generator-sitemap": "^1.0.1"

Please close this issue and wait for hexo-admin's udpate.
