### ISSUE TITLE
compatibility issue with hexo-2.x (hexo-cli and  hexo)

### ISSUE THREAD

**Issue by hanfeisun** [hexojs/hexo#1074]
I am working on a github page which depends on `hexo 2.5.7`.

https://github.com/vuejs/vuejs.org

It works well when I use `npm install -g hexo` to install `hexo 2.x`. 

However, when I execute `npm install -g hexo-cli` to install newer version `hexo 3.0`, the old version of `hexo` is replaced by newer version. And `hexo server` doesn't work now..

Is it possible to make hexo 3.x compatible with hexo 2.x? If not, would there be a way to make them coexist instead of being replace by the other?

**Comment by celsomiranda** [comment]
I don't think you can make them coexist.

If you're looking to upgrade to 3.0.0 look at [this wiki article](https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0).

**Comment by hanfeisun** [comment]
@celsomiranda Thanks for the reference. 

Some legacy sites maintained by others are not going to migrate to 3.0... I was just wondering whether  there is a easier way to switch between hexo 2.x and hexo 3.0. 

Currently the approach I used to switch is run `npm install -g hexo` to switch back and run `npm install -g hexo-cli` to switch forward, which looks a little clumsy.
