### ISSUE TITLE
How to make a custom homepage in hexo 3

### ISSUE THREAD

**Issue by DanielBaird** [hexojs/hexo#1077]
According to #1062 the config option for `exclude_generator` was removed from hexo 3.0.  I'm using hexo 3 partly because I need the `page.more` feature, and figured why not try out the latest RC.

So: what's the correct way in hexo 3 to make a custom `(root)/index.html` file?  Do I have to put all my homepage content into the theme's index.ejs or something?

**Comment by tommy351** [comment]
Add `index.md` to `source` folder. You can see [hexojs/site](https://github.com/hexojs/site) for example.

**Comment by pierrickrouxel** [comment]
It dosn't work for me. The index.md is totally ignored.

**Comment by ike** [comment]
@pierrickrouxel make sure you don't have the `hexo-generator-index` module installed.

**Comment by wanghaisheng** [comment]
if  I have a index.html and dont want to use theme to generate this index from md  ,how could I  realize this using hexo 3

**Comment by iqiancheng** [comment]
`` npm install hexo-generator-index  --save ``

**Comment by shadowysean** [comment]
@ike Removing that package works! Thx~ 
As I see, the `exclude_generator` option brings some convenience, why was it deprecated in 3.0+? @tommy351

**Comment by ChongTang** [comment]
@shadowysean How do you make the custom home page works? I removed the hexo-generator-index dependency from package.json, and added an index.md file in source folder. But I got some errors when I run "hexo generate" command. Those errors are from theme's .ejs file. Looks like the theme doesn't support custom homepage. Which theme are you using? Thanks!

**Comment by theRiddler91** [comment]
@ike I was working on this problem for 5 hours and I got it to work by taking your advice! Thanks!

**Comment by luofanghao** [comment]
The solution in this issue seems already out-of-date? Is there any way that still working?

**Comment by lekhnath** [comment]
@luofanghao  I am using [Hexo Theme Icarus](https://github.com/ppoffice/hexo-theme-icarus) and the solution is working for me.

**Comment by luofanghao** [comment]
@lekhnath  thanks for your reply, I just looked through the theme. But what this post (and my) need is to create a customised index.html, through this index.html can be linked with a blog, or some other stuff. like [this one](http://blog.ivanyang.me)

**Comment by NoahDragon** [comment]
@luofanghao your scenario is not same as this question. 

You could modify the index layout in the theme folder to meet your requirment.

**Comment by paul-hammant** [comment]
Yup, as @ike said `npm remove hexo-generator-index` worked.

**Comment by MoezGholami** [comment]
Hi
I still have the hexo-generator-index, I changed its path to /blog in my _config.yml. In order to have my custom homepage (based on what @sergiolepore said in #713), I added the following lines on top of my index.html (don't worry, they'll be removed):
```
layout: false
---
```

**Comment by nouyang** [comment]
Confirming that simply creating an `index.md` file in the `my-site/source` folder allows me to change the homepage.

I still wished to have a page which listed my most recent blog posts. So in my `my-site/_config.yml` I put
```yaml
index_generator:
  #path: ''  # DELETE
  path: '/blog'
```

After creating the file (and running `hexo g` `hexo s`), when I access `localhost:4000`, I get my custom homepage. And then when I access `localhost:4000/my-site/blog`, I get the "original" homepage listing my blog posts.


I did not need to `npm uninstall hexo-generator-index`. I also did not need to create an html file, and did not need to do what @MoezGholami says above.

hexo: 3.7.1
hexo-cli: 1.1.0

**Comment by leimao** [comment]
> Confirming that simply creating an `index.md` file in the `my-site/source` folder allows me to change the homepage.
> 
> I still wished to have a page which listed my most recent blog posts. So in my `my-site/_config.yml` I put
> 
> ```yaml
> index_generator:
>   #path: ''  # DELETE
>   path: '/blog'
> ```
> 
> After creating the file (and running `hexo g` `hexo s`), when I access `localhost:4000`, I get my custom homepage. And then when I access `localhost:4000/my-site/blog`, I get the "original" homepage listing my blog posts.
> 
> I did not need to `npm uninstall hexo-generator-index`. I also did not need to create an html file, and did not need to do what @MoezGholami says above.
> 
> hexo: 3.7.1
> hexo-cli: 1.1.0

Just put more clarification on @nouyang 's suggestion. You need to do these two things in order to get a custom home page:
1. creating an `index.md` in the `my-site/source`
2. change the path for `index_generator` in `my-site/_config.yml`

**Comment by justinemar** [comment]
> > Confirming that simply creating an `index.md` file in the `my-site/source` folder allows me to change the homepage.
> > I still wished to have a page which listed my most recent blog posts. So in my `my-site/_config.yml` I put
> > ```yaml
> > index_generator:
> >   #path: ''  # DELETE
> >   path: '/blog'
> > ```
> > 
> > 
> > After creating the file (and running `hexo g` `hexo s`), when I access `localhost:4000`, I get my custom homepage. And then when I access `localhost:4000/my-site/blog`, I get the "original" homepage listing my blog posts.
> > I did not need to `npm uninstall hexo-generator-index`. I also did not need to create an html file, and did not need to do what @MoezGholami says above.
> > hexo: 3.7.1
> > hexo-cli: 1.1.0
> 
> Just put more clarification on @nouyang 's suggestion. You need to do these two things in order to get a custom home page:
> 
> 1. creating an `index.md` in the `my-site/source`
> 2. change the path for `index_generator` in `my-site/_config.yml`

Huh so i have to write my custom index page in markdown?

**Comment by phicarre** [comment]
Hello,
With hexo 4.2.0 that doesn't work for me !
I created an empty file <index.md> in the <source> directory
I modified in <_config.yml> the path
I didn't uninstall <hexo-generator-index> (version 1.0.0)

**Comment by hillswidth** [comment]
I am so happy that I am not the only one having this problem!!!lol
I thought it was easy to solve... I've stuck here for 2 days already.

**Comment by hillswidth** [comment]
> Hello,
> With hexo 4.2.0 that doesn't work for me !
> I created an empty file `index.md` in the `source` directory
> I modified in `_config.yml` the path for `index_generator`
> I didn't uninstall `hexo-generator-index` (version 1.0.0)

Mine is 
hexo: 5.1.1
hexo-cli: 4.2.0
I have done the same things and not working.

so, question is, Sep, 2020, ghost, did you solve ur trouble?

**Comment by antalyanakliye** [comment]
# Osman

**Merhaba Duplicate of 
**

**Comment by leimao** [comment]
@hillswidth I tried this on the latest Icarus theme and it still works as of now.
https://github.com/ppoffice/hexo-theme-icarus

**Comment by enkr1** [comment]
is there a way to customise home page for Next theme? I wanna keep it simple on next theme but im struggling to find a way to do that :/
