### ISSUE TITLE
Anyway to disable curly braces interpolation in markdown?

### ISSUE THREAD

**Issue by yyx990803** [hexojs/hexo#1079]
Markdown source files that contain curly braces, e.g. `{{title}}`, are considered template interpolations against the YAML front-matter of that post. I have to escape the braces like `&#123;&#123;title&#125;&#125;` in order to output them without causing a hexo error.

In hexo 2.x this behavior also affects code inside markdown code blocks, which makes writing code samples for curly brace templates very annoying. Now in 3.0 this has been fixed, which is great.

However I would still like to have a config option that allows me to completely disable this feature. I don't really need interpolation in my markdown; I just want to use curly braces as I would in normal HTML.

**Comment by jzk** [comment]
+1

**Comment by leesei** [comment]
Use `raw` block
https://hexo.io/docs/troubleshooting.html#Escape_Contents

**Comment by cleechtech** [comment]
+1 for using `{% raw %}` and `{% endraw %}`

**Comment by ensigma96** [comment]
Btw, how to display `{% raw %}` and `{% endraw %}` in a post?
