### ISSUE TITLE
Set up & deploy hexo into subdirectory on GitHub pages (User & Organization Pages)

### ISSUE THREAD

**Issue by GEEKIAM** [hexojs/hexo#1081]
Hello.

I want to create project structure like this:

```
├── stylesheet/
├── javascript/
├── blog/ ----------> username.github.io/blog/ (hexo w/ it sources and generated pages)
├── index.html -----> username.github.io/index.html
```

so what are the ways to do this?

**Comment by leesei** [comment]
Create `blog` repo and put generated pages to `gh-pages` branch.
Link to `username.github.io/blog/` in your `username.github.io` site.
