### ISSUE TITLE
HEXO报错，建议HEXO增加更详细的日志记录

### ISSUE THREAD

**Issue by chenshenglu** [hexojs/hexo#1082]
本周用HEXO搭建了一个主页，看起来能用效果不错。后来在自己本地搭建环境，表示无法访问
http://localhost:4000/blog/报Cannot GET /blog/
我的操作如下：HEXO模块之前已经安装
$hexo init blog
$cd blog
$npm install
$hexo server
看起来操作没问题，就是报错。谁遇到过求教？
要是能够有一个详细的日志记录就好了。。。

**Comment by chenshenglu** [comment]
我发现执行了$hexo server之后public静态网页都没有生成
Administrator@SLCHEN /F/workspace/学习/nodejs/sample/blog
$ ls
_config.yml  db.json  node_modules  package.json  scaffolds  source  themes

**Comment by chenshenglu** [comment]
我找到原因了，可能是因为了建了太多项目，清除浏览器缓存访问正常

**Comment by liboyue23** [comment]
我清除了浏览器缓存，但是还是cannot get！楼主你是怎么弄好的？
