### ISSUE TITLE
$npm install -g hexo 失败，报错如下

### ISSUE THREAD

**Issue by Kuosoong** [hexojs/hexo#1083]
windows系统
请问什么意思，谢谢？
>0 info it worked if it ends with ok
>1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
>1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
>1 verbose cli   'install',
>1 verbose cli   '-g',
>1 verbose cli   'hexo' ]
>2 info using npm@2.5.1
>3 info using node@v0.12.0
>4 silly cache add args [ 'hexo', null ]
>5 verbose cache add spec hexo
>6 silly cache add parsed spec { raw: 'hexo',
>6 silly cache add   scope: null,
>6 silly cache add   name: 'hexo',
>6 silly cache add   rawSpec: '',
>6 silly cache add   spec: '*',
>6 silly cache add   type: 'range' }
>7 verbose addNamed hexo@*
>8 silly addNamed semver.valid null
>9 silly addNamed semver.validRange *
>10 silly addNameRange { name: 'hexo', range: '*', hasData: false }
>11 silly mapToRegistry name hexo
>12 silly mapToRegistry using default registry
>13 silly mapToRegistry registry https://registry.npmjs.org/
>14 silly mapToRegistry uri https://registry.npmjs.org/hexo
>15 verbose addNameRange registry:https://registry.npmjs.org/hexo not in >flight; fetching
>16 verbose request uri https://registry.npmjs.org/hexo
>17 verbose request no auth needed
>18 info attempt registry request try #1 at 15:34:55
>19 verbose request id 6e32c4b95fcecd85
>20 http request GET https://registry.npmjs.org/hexo
>21 info retry will retry, error on last attempt: Error: socket hang up
>22 info attempt registry request try #2 at 15:40:18
>23 http request GET https://registry.npmjs.org/hexo
>24 info retry will retry, error on last attempt: Error: read ECONNRESET
>25 info attempt registry request try #3 at 15:56:37
>26 http request GET https://registry.npmjs.org/hexo
>27 verbose stack Error: getaddrinfo ENOENT
>27 verbose stack     at Object.exports._errnoException (util.js:746:11)
>27 verbose stack     at errnoException (dns.js:49:15)
>27 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
>28 verbose cwd c:\Users\kuosoong\Desktop
>29 error Windows_NT 6.3.9600
>30 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program >Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "hexo"
>31 error node v0.12.0
>32 error npm  v2.5.1
>33 error code ENOENT
>34 error errno ENOENT
>35 error syscall getaddrinfo
>36 error enoent getaddrinfo ENOENT
>36 error enoent This is most likely not a problem with npm itself
>36 error enoent and is related to npm not being able to find a file.
>37 verbose exit [ 1, true ]

**Comment by youxiachai** [comment]
3.0 用这个...
npm install -g hexo-cli

**Comment by Kuosoong** [comment]
谢谢您，可以了

**Comment by leesei** [comment]
Please close this issue.
