### ISSUE TITLE
怎么安装hexo3.0+

### ISSUE THREAD

**Issue by hackzb** [hexojs/hexo#1086]
怎么安装hexo3.0+

**Comment by tommy351** [comment]
http://hexo.io/docs/

**Comment by spritegirl** [comment]
看看这篇文章吧https://coderq.com/t/hexo3-dot-0fa-bu/1801 ，我就是按照这文章安装好了hexo3.0，非常的值得学习，哈哈^_^  
![1](https://cloud.githubusercontent.com/assets/9048606/6528603/0d5e8632-c45e-11e4-87a0-3c8fcc162c5c.jpg)
