### ISSUE TITLE
Conditional tags helper is broken in hexo 3?

### ISSUE THREAD

**Issue by banbanchs** [hexojs/hexo#1088]
It seems `is_category`, `is_tag`, `is_archive` helpers always return `false`. -> #1020 

Test template(always return None in `category`, `tag`, `archive` page):
``` ejs
<% if (is_category()) { %>
<h1>Category: <%= page.category %></h1>
<% } else if (is_tag()) { %>
<h1>Tag: <%= page.tag %></h1>
<% } else if (is_archive()) { %>
<h1>Blog Archive</h1>
<% } else { %>
<h1>None</h1>
<% } %>
```

`permalink` setting
```
permalink: :year/:month/:day/:title/
```

Version information:
```
hexo: 3.0.0
os: Linux 3.19.0-1-uksm-ck linux x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.2
```

Also can test with [landscape](https://github.com/hexojs/hexo-theme-landscape)

https://github.com/hexojs/hexo-theme-landscape/blob/master/layout/_partial/head.ejs#L22

**Comment by WolfgangKluge** [comment]
I think, the helper function should be rewritten, e.g.
https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/is.js#L93
`this.category` should be `this.page.category`

**Comment by leesei** [comment]
@WolfgangKluge, I've been studying the code and I agree with you.
