### ISSUE TITLE
skip_render 这个究竟怎么使用,官网上面没有例子.

### ISSUE THREAD

**Issue by twocucao** [hexojs/hexo#1089]
麻烦哪位懂的人举个例子来说明一下.

**Comment by leesei** [comment]
see [Hexo常见问题解决方案 | Xuanwo's Blog](http://xuanwo.org/2014/08/14/hexo-usual-problem/#Hexo3-0以上支持)

**Comment by Xuanwo** [comment]
请问还有问题么？没有的话请主动close吧~
