### ISSUE TITLE
从2.8.3升级到3.0.0的问题

### ISSUE THREAD

**Issue by huanz** [hexojs/hexo#1093]
从2.8.3升级到3.0.0之后，运行hexo g更久都没有反应。是文件太多的原因。但是用2.8.3就不会出现问题。。。

**Comment by yzx41099298** [comment]
我也遇到了..

**Comment by Svtter** [comment]
我这里生成也是太慢了。。2.x没有这个问题，升级3.0以后速度特别慢。。

**Comment by YumeMichi** [comment]
慢死了都 load file花了快3分钟 实际generate才花了3秒

**Comment by Xuanwo** [comment]
额，好像新版本对磁盘性能要求很高，试试看放在SSD上

**Comment by tommy351** [comment]
因為 Hexo 3 在載入檔案時會比對 SHA1 hash

**Comment by Draveness** [comment]
那这个也太慢了, 30篇blog等了好久都没反应

**Comment by Xuanwo** [comment]
参考https://github.com/hexojs/hexo/issues/1039

我不知道为什么你们是这样的- -，反正我是感觉3.0速度飞快。。

**Comment by YumeMichi** [comment]
debug模式下看了一下在loading file的时候会卡在某个文件，而且这个文件每次debug都不一样，不知道怎么回事

**Comment by Xuanwo** [comment]
我觉得。。是不是换个主题看看？
主题文件太多太乱，可能导致loading要很多时间，我之前有一个特别复杂的主题，生成就超慢。

**Comment by joysboy** [comment]
我也碰到这个问题，是在load文件时卡住，还未到generate，后来改了卡住文件的内容发现是因为一个单行特别长的代码段导致。。。。。，2.8.x没有问题

```
Z2xvYmFsICRibG9nLCAkZGJfcHJlZml4LCAkbWJjb247DQokaG90dmlldz0kYmxvZy0+Z2V0Z3JvdXBieXF1ZXJ5KCJTRUxFQ1QgKiBGUk9NIGB7JGRiX3ByZWZpeH1ibG9nc2AgV0hFUkUgYHByb3BlcnR5YCA9MCBPUkRFUiBCWSBgdmlld3NgIERFU0MgTElNSVQgMCAsIHskbWJjb25bJ2VudHJ5bnVtJ119Iik7DQppZiAoaXNfYXJyYXkoJGhvdHZpZXcpKSB7DQokdmlld2hvd3M9Jzx1bD4nOw0KZm9yZWFjaCAoJGhvdHZpZXcgYXMgJG9uZWhvdHZpZXcpIHsNCiR2aWV3aG93cy49IjxsaT5beyRvbmVob3R2aWV3Wyd2aWV3cyddfV08YSBocmVmPVwicmVhZC5waHA/Ii4kb25laG90dmlld1snYmxvZ2lkJ10uIlwiPnskb25laG90dmlld1sndGl0bGUnXX08L2E+PC9saT4iOw0KfQ0KJHZpZXdob3dzLj0nPC91bD4nOw0KfSBlbHNlIHsNCiR2aWV3aG93cz0nTm8gdmlldyEnOw0KfQ0KJHBocHJldHVybj0kdmlld2hvd3M7
```

**Comment by YumeMichi** [comment]
问题貌似解决了，因为自带的highlight.js的问题
[#1036](https://github.com/hexojs/hexo/issues/1036)

**Comment by Xuanwo** [comment]
你好- -，请问修改了文档内容之后，问题还存在么？

**Comment by Draveness** [comment]
问题很大可能是因为markdown文件中的 `---` 可能会注释掉hexo的部分代码, 亲测, 文件中有 `--------` 就会block generate 的进行, 没有就不会, 问题不知道存在不了, 改用ghost了

**Comment by Liam0205** [comment]
慢到令人发指……

![image](https://user-images.githubusercontent.com/3348485/51725742-fd69c600-209e-11e9-947d-b83d28048d2e.png)
