### ISSUE TITLE
How to delete category?

### ISSUE THREAD

**Issue by reaniwen** [hexojs/hexo#1097]
How to delete a category with 0 post?
I tried "hexo clean", "hexo clean life"(life is the cat that I want to delete).  It doesn't work.

**Comment by Xuanwo** [comment]
delete the `db.json` and `.deploy` and try to `hexo g` again.

**Comment by reaniwen** [comment]
I tried db.json, it doesn't work.
I didn't find .deploy file. I just found a folder called .deploy_git and deleted it. Then it worked.
Thank you

**Comment by Xuanwo** [comment]
Fine~
