### ISSUE TITLE
Doesn't compile new styles from @import unless parent style is changed

### ISSUE THREAD

**Issue by natew** [hexojs/hexo#1098]
This is the repo to reproduce the error: https://github.com/reapp/new-site

When I run `hexo generate` it works.

But if I change `base.styl` and run `hexo generate` again, it just generates a new `base.css`.

It _should_ generate a new `style.css` with the base style included but it does not.

If I then change `style.styl` to be different (for example add a new line), then `hexo generate`, it will then output the correct `style.css` with the updated base.css styles inside.

**Comment by tommy351** [comment]
This is not a bug. Hexo don't know what you imported in a stylus file.

**Comment by natew** [comment]
Ah, so you must use .css? Good to know. Would be a nice feature :)

**Comment by natew** [comment]
In the Landscape theme this means when you change a file it doesn't add it to the header when you run `hexo generate`? At least with my theme it doesn't:

https://github.com/reapp/new-site/blob/master/themes/landscape/source/css/style.styl

How would I fix that?

**Comment by yshrsmz** [comment]
I ended up using gulp-stylus for generating css.
But be careful, `hexo generate` will delete everything in output directory if that is not controlled by hexo.
you should output compiled css in hexo source directory.
