### ISSUE TITLE
Hexo之Reference Error: match is not defined

### ISSUE THREAD

**Issue by Ye-luqing** [hexojs/hexo#1102]
[我的博客](http://blogmath.org/)是使用Hexo架设在Github上的.在2015.3.10当我使用

```
hexo g
```
的时候,Hexo显示如下信息:
```
[error] HexoError: Process failed: _posts/混合偏导数的Clairaut定理.md
ReferenceError: match is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/hexo/lib/plugins/filter/external_link.js:25:46)
    at exports.each (/usr/local/lib/node_modules/hexo/node_modules/cheerio/lib/api/traversing.js:268:24)
    at module.exports (/usr/local/lib/node_modules/hexo/lib/plugins/filter/external_link.js:11:10)
    at /usr/local/lib/node_modules/hexo/lib/post/render.js:112:11
    at iterate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:165:9)
    at /usr/local/lib/node_modules/hexo/lib/post/render.js:111:15
    at /usr/local/lib/node_modules/hexo/lib/extend/renderer.js:78:20
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)

```
Google许久不能找到解决方案.最后通过排除法不断实验终于确定是博文 [混合偏导数的Clairaut定理](http://blogmath.org/2015/02/23/混合偏导数的Clairaut定理/)里的链接问题.当链接到我自己的网站 blogmath.org 里的内容的时候,`http://blogmath.org/` 不能出现.比如要链接到 [平面转动系统中质点的运动](http://blogmath.org/2015/03/03/平面转动系统中质点的运动) ,不能写
```
[平面转动系统中质点的运动](http://blogmath.org/2015/03/03/平面转动系统中质点的运动)
```
而要写
```
[平面转动系统中质点的运动](/2015/03/03/平面转动系统中质点的运动)
```

这真奇怪,我以前编译博文的时候都没出现这样的问题的,为何在2015.3.10偏偏出现了.

**Comment by Xuanwo** [comment]
链接最后加上一个`/`试试看？

**Comment by Ye-luqing** [comment]
@Xuanwo 刚才试了一下,链接最后加 `/`后问题依然存在.

**Comment by Xuanwo** [comment]
参考 https://raw.githubusercontent.com/Xuanwo/xuanwo.github.io/blog/source/works/index.md
我并没有出现这样的问题，有没有可能是因为中文连接的问题？

**Comment by Ye-luqing** [comment]
@Xuanwo  我以前编译都没出现问题.就是昨天晚上当我使用 `hexo backup`进行备份之后,问题就出现了.hexo backup 插件在这里 https://github.com/coneycode/hexo-git-backup     但是我以前使用`hexo backup` 的时候也没出现这样的问题.所以昨天这个问题出现得莫名其妙.

**Comment by Ye-luqing** [comment]
@Xuanwo  我以前编译都没出现这样的问题.也就是说,应该不是中文链接的问题.这个问题昨晚已经通过试验解决了,但是我感到奇怪,所以在这里问一下.

**Comment by tommy351** [comment]
Are you using Hexo 2.x? Because I didn't see any variables named `match` in the latest source code.

**Comment by Ye-luqing** [comment]
@tommy351 Yes.I am using Hexo 2.8.3

**Comment by leesei** [comment]
Please open new issue if problem persists in latest code.
