### ISSUE TITLE
从2.8.3 迁移到3.0出现问题

### ISSUE THREAD

**Issue by zhiyue** [hexojs/hexo#1103]
按照wiki 迁徙到3.0 
使用的是[jacman](https://github.com/wuchong/jacman)的主题

升级完成后 使用

```
hexo g
```
出现以下问题:
![](http://ww4.sinaimg.cn/large/8d6e2d38gw1eq1mwuwravj20hr0cs764.jpg)

**Comment by liudonghua123** [comment]
same problem , see https://github.com/hexojs/hexo/issues/1059 ， https://github.com/hexojs/hexo/issues/1094

**Comment by tommy351** [comment]
Add `highlight` setting to `_config.yml` or update to `hexo-renderer-stylus@0.2.3`.
