### ISSUE TITLE
页面文章数显示

### ISSUE THREAD

**Issue by imhentai** [hexojs/hexo#1104]
我想实现：首页只显示一篇文章，归档页面显示全部文章
应该如何设置？
per_page: 1
pagination_dir: page
这儿改成“1”的话，归档页面也只显示一篇文章了

**Comment by tommy351** [comment]
Modify the setting of archive generator.

``` yaml
archive_generator:
  per_page: 0
```

**Comment by imhentai** [comment]
thanks
