### ISSUE TITLE
url_for does not allow specifying the root of the site if the site is in a subfolder.

### ISSUE THREAD

**Issue by TigerLeep** [hexojs/hexo#1105]
The helper url_for only prepends the url with config.root if the path passed in doesn't start with a "/", but the first line of url_helper changes undefined or empty string to "/".  This prevents url_for() or url_for("") from returning the correct root of your site.  If you call url_for("blah") it will return "/root/blah" but if you call url_for() it will return "/" and leave the /root off.

Results from "hexo version":
```
hexo: 3.0.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
```

**Comment by ccqgithub** [comment]
我也遇到了这个问题，等等解决

**Comment by anjianshi** [comment]
A Temporary Solution, use this:
```
url_for("index.html");
```
