### ISSUE TITLE
HELP！！！！How can I use the command “hexo d” to push  it on my git pages？

### ISSUE THREAD

**Issue by liuhao2050** [hexojs/hexo#1106]
我clone了一个到本地，也配置了 _config.yml 文件，顺带换了个主题，可以用在本地使用了，但是问题来了，我弄不到github上去， 我明明在_config.yml 配置了github 但是我敲 hexo d 却没有任何反应， 但也不报错，HELP！！！！

**Comment by Xuanwo** [comment]
Easy, easy, = =.
我去看了一下你的库，有以下几个问题：
- 库的名字应当是xxx.github.io而不是xxx.github.com
- 源文件不应当存放在master分支下，可以另外新建一个blog分支保存，deploy时，需要使用master分支。
- 你是否通过了github的邮件验证？
- 你是否在github上面开启了gh-pages的选项？

可以参考http://xuanwo.org/2014/08/14/hexo-usual-problem/

**Comment by liuhao2050** [comment]
您好！
首先，我非常感谢您的分析
     1.我删除了库里的所有文件
     2.我进行了如下设置：
            deploy:
                      type:git
                      repository:https://github.com/liuhao2050/liuhao2050.github.io.git
                      branch:master
         3.我 可以正常向github仓库推送，但是无论我怎么配置默认用户名和邮箱，每次push都要输入用户名和密码， 不知是否影响？
         4.  我查到“Your site is published at http://liuhao2050.github.io.”
         5.当我输入hexo  deploy 时，会出现等待两秒后直接结束命令，给出了$提示符，没有任何反馈，这是为何？

再次感谢您的回复！

**Comment by liuhao2050** [comment]
您好！
首先，我非常感谢您的分析
     1.我删除了库里的所有文件
     2.我进行了如下设置：
            deploy:
                      type:git
                      repository:https://github.com/liuhao2050/liuhao2050.github.io.git
                      branch:master
         3.我 可以正常向github仓库推送，但是无论我怎么配置默认用户名和邮箱，每次push都要输入用户名和密码， 不知是否影响？
         4.  我查到“Your site is published at http://liuhao2050.github.io.”
         5.当我输入hexo  deploy 时，会出现等待两秒后直接结束命令，给出了$提示符，没有任何反馈，这是为何？

再次感谢您的回复！

**Comment by liuhao2050** [comment]
还有,我想知道当我输入hexo d 的时候 hexo是将静态的html和css等推送到库里去还是 将生成的代码和html等一起推上去 形成如你库中结构，还是要我通过git 手动去推送呢？

**Comment by liuhao2050** [comment]
###更奇怪的是我从window下迁移到ubuntu下之后同样的事出现了，同样出现了
haoliu@haoliu:~/hexo$ vi _config.yml 
haoliu@haoliu:~/hexo$ hexo deploy
haoliu@haoliu:~/hexo$ hexo deploy
 但是不同的是 我ubuntu下是可以无密码提交的（windows下ssh-add 无论如何都加不进去），但我好像发现了一个bug，就是在_config.yml中：
deploy:
 70   type:github
 71   repo:https://github.com/liuhao2050/liuhao2050.github.io.git
 72   branch:master
键值对之间好像敲一个空格就会报错

**Comment by Xuanwo** [comment]
1. 不影响
2. 静态文件会自动上传的
3. 你本地的git环境配置好了么= =
4. windows下使用SSH需要安装git-bash，你可以参考[窝的文章](http://xuanwo.org/2015/02/07/generate-a-ssh-key/)
5. 这并不是BUG= =，yml是一个语法相当的格式，缺少或者多出任何空格都会报错。

**Comment by Xuanwo** [comment]
1. 不影响
2. 静态文件会自动上传的
3. 你本地的git环境配置好了么= =
4. windows下使用SSH需要安装git-bash，你可以参考[窝的文章](http://xuanwo.org/2015/02/07/generate-a-ssh-key/)
5. 这并不是BUG= =，yml是一个语法相当的格式，缺少或者多出任何空格都会报错。

**Comment by Xuanwo** [comment]
1. 不影响
2. 静态文件会自动上传的
3. 你本地的git环境配置好了么= =
4. windows下使用SSH需要安装git-bash，你可以参考[窝的文章](http://xuanwo.org/2015/02/07/generate-a-ssh-key/)
5. 这并不是BUG= =，yml是一个语法相当的格式，缺少或者多出任何空格都会报错。

PS. 你不需要连续回复三次= =，可以直接在原来基础上修改的。

**Comment by Xuanwo** [comment]
1. 不影响
2. 静态文件会自动上传的
3. 你本地的git环境配置好了么= =
4. windows下使用SSH需要安装git-bash，你可以参考[窝的文章](http://xuanwo.org/2015/02/07/generate-a-ssh-key/)
5. 这并不是BUG= =，yml是一个语法相当的格式，缺少或者多出任何空格都会报错。

PS. 你不需要连续回复三次= =，可以直接在原来基础上修改的。

**Comment by Xuanwo** [comment]
1. 不影响
2. 静态文件会自动上传的
3. 你本地的git环境配置好了么= =
4. windows下使用SSH需要安装git-bash，你可以参考[窝的文章](http://xuanwo.org/2015/02/07/generate-a-ssh-key/)
5. 这并不是BUG= =，yml是一个语法相当的格式，缺少或者多出任何空格都会报错。

PS. 你不需要连续回复三次= =，可以直接在原来基础上修改的。

**Comment by liuhao2050** [comment]
折腾累了，换个方法凑合用吧，就是直接手动将生成的publish文件中的html push上来，但是这个问题出现的原因我还是不知道，我想可能是因为缺少某些组件？最不好的就是它直接在hexo d 命令后无任何提示退出了...再次感谢您的帮助。                                                                                                                                                                                                                                       祝好！

**Comment by vnexus** [comment]
遇到了同样的问题  原因是
deploy:
type: github
repository: https://github.com/nothingcpd/nothingcpd.github.io.git
branch: master
这几个”：”后边需要有一个”空格”

**Comment by liuhao2050** [comment]
thanku 发自网易邮箱大师 在2015年06月18日 18:20 ，vnexus写道： 遇到了同样的问题 原因是 deploy: type: github repository: https://github.com/nothingcpd/nothingcpd.github.io.git branch: master 这几个”：”后边需要有一个”空格” — Reply to this email directly or view it on GitHub.
