### ISSUE TITLE
fatal: Unable to create '/Users/xxx/hexo/.deploy_git/.git/index.lock': File exists.

### ISSUE THREAD

**Issue by cielpy** [hexojs/hexo#1108]
I have migrated my blog from 2.x to 3.x follow this doc https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0
everything is well,but when I run hexo deploy command,there have an error occur

fatal: Unable to create '/Users/xxx/hexo/.deploy_git/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: Unable to create '/Users/xxx/hexo/.deploy_git/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

    at ChildProcess.<anonymous> (/Users/xxx/hexo/node_modules/hexo-deployer-git/node_modules/hexo-util/lib/spawn.js:42:17)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

the file '.deploy_git/.git/index.lock' does not exists,but the error appear,is this a bug? Anything help?

OS:OS X 10.10.2
git version:2.3.2

update: 2015.3.12 23:58
I have two repository to public,github and gitcafe,if I remove either of them,the deployer run well...

**Comment by Xuanwo** [comment]
delete `.deploy_git`

**Comment by cielpy** [comment]
I have try to delete the .deploy_git folder,but it also does't work.
Why 3.0 can't use different git service together?Anything limited?

**Comment by tufu9441** [comment]
I found the same problem too, because I tried to deploy to Github and Gitcafe at the same time. After I removed either of them, it could run well.

**Comment by isetsuna** [comment]
我也遇到了同样的问题
![qq 20150313180437](https://cloud.githubusercontent.com/assets/11231154/6636772/320a900c-c9ae-11e4-851a-21aa77792334.png)

**Comment by cielpy** [comment]
@isetsuna remove one of github and gitcafe deploy option,try again.

**Comment by tommy351** [comment]
Could you post your config for me to testing?

**Comment by isetsuna** [comment]
@tommy351 您是需要_config.yml还是需要全部文件？

**Comment by isetsuna** [comment]
@tommy351 把所有文件打包发到您的gmail了

**Comment by tommy351** [comment]
@isetsuna thanks

**Comment by wanghaisheng** [comment]
这个问题解决了么

**Comment by isetsuna** [comment]
@wanghaisheng 似乎还没有，删掉其中一个就没问题。。反正这两天GitHub也在被搞中。。

**Comment by wanghaisheng** [comment]
我删掉一个也是卡住的 未完成deploy

**Comment by isetsuna** [comment]
@wanghaisheng 试试GitCafe，应该没问题的。可能GitHub Pages被搞中

**Comment by Channely** [comment]
确认被搞肿——。

**Comment by Xuanwo** [comment]
2333，看来我提前搞好travis的自动构建实在是太机智了。

**Comment by deltacat** [comment]
I encountered same problem.
One repo is fine, but if I use two repo in config at same time will got the error.
Seems Hexo 3.0 remove multi-repo support or just a bug.

**Comment by Xuanwo** [comment]
我试了一下多配置，然后报错信息如下：

```
  hexo d
      Deploying: git
INFO  Setting up Git deployment...
Initialized empty Git repository in e:/代码/xuanwo.github.io/.deploy_git/.git/
[master (root-commit) 3611a5a] First commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 placeholder
INFO  Clearing .deploy folder...
INFO  Copying files from public folder...
fatal: Unable to create 'e:/代码/xuanwo.github.io/.deploy_git/.git/index.lock':
File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do
cs/troubleshooting.html
Error: fatal: Unable to create 'e:/代码/xuanwo.github.io/.deploy_git/.git/index.
lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

    at ChildProcess.<anonymous> (e:\代码\xuanwo.github.io\node_modules\hexo-depl
oyer-git\node_modules\hexo-util\lib\spawn.js:42:17)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

            /e/代码/xuanwo.github.io (blog)

```

**Comment by tommy351** [comment]
I think the reason may be git can only do one thing at a time. I just modified the deployer to make it deploy in series. You can try hexo-deployer-git@0.0.4.

**Comment by cielpy** [comment]
Good,it works!

**Comment by tufu9441** [comment]
I also solve this multi-repo deploying problem via this way, good!

**Comment by csuldw** [comment]
解决：
1.删除.deploy_git文件：rm -rf .deploy_git
2.重新编译发布：hexo d -g
