### ISSUE TITLE
新版_config.yml的"permalink:"的错误

### ISSUE THREAD

**Issue by naog** [hexojs/hexo#1110]
permalink: :title.html
会识别成“文件名.html”
无视“_posts”中的文章页头“title: XXX”
且无视“permalink: url”重写

**Comment by Xuanwo** [comment]
http://hexo.io/zh-cn/docs/permalinks.html#变量

这不是BUG，Hexo本身就是这样的设定，`:title  文件名称`。
所以要是想要用文章标题做链接的话，就用文章标题来命名你的MD文件吧。

**Comment by naog** [comment]
@Xuanwo 
<http://hexo.io/zh-cn/docs/front-matter.html>
Front-matter中的`permalink`参数的描述为`覆盖文章网址`，在3.0中也不能覆盖。

**Comment by liudongkai** [comment]
@naog 

我也碰到了一样的问题，这几天经过测试发现，2.x的 post `permalink` 参数应该变量名冲突了，在post里命名一个新的、不冲突的参数就可以了，比如 `permalinks`

_config.yml
>permalink: **:permalinks/**

source/_posts/hello-world.md
>title: Hello world
**permalinks: world2**

url =>  [http://yourdomain/**world2**/]()

**Comment by Xuanwo** [comment]
@naog Hello, @liudongkai 的方法能解决问题么？
