### ISSUE TITLE
部署到自己服务器问题

### ISSUE THREAD

**Issue by heibai01** [hexojs/hexo#1111]
作者真的很棒，我已经搭建了个人博客了。但是公司工作使用还想搭一个到内部服务器上，
所以有此问，如下：
请问一下，使用pm2如何启动应用？
我按照官网来做的，无法访问我的服务。
app.js的内容是否要和官网描述的一模一样？
app.js文件官网说的站点文件夹下，是指public目录下，还是整个应用下呢？

**Comment by wanghaoListening** [comment]
不好意思，我对pm2不是很熟
app.js内容不需要和官网描述的一模一样
app.js文件官网说的站点文件夹下，应该是整个应用
我没有按照官网描述的去搭建，
而是根据几篇blog搭建的http://ibruce.info/2013/11/22/hexo-your-blog/
www.zhaokongnuan.com

**Comment by heibai01** [comment]
我的确有搭建在github上的应用，但是我还需要搭建一个在我公司的服务器上。
相当于我不用hexo d命令上传静态文件到github page或者其他平台了。
而是hexo s运行服务，但是因为单进程原因，需要借助pm2运行。

**Comment by akar1nchan** [comment]
生成的文件在public下  都是静态文件  服务器上跑个nginx基本就可以了

**Comment by heibai01** [comment]
不行，只剩下内容了，骨架没有了。。。（nginx服务器试过了，甚至放在express项目的子目录下访问也是同样的情况。）

**Comment by Xuanwo** [comment]
骨架没有了？我猜是不是静态资源调用的地址错了。

**Comment by akar1nchan** [comment]
看瀏覽器console的報錯咯  是不是有些文件路徑錯了？

**Comment by heibai01** [comment]
大家好，我没有用其他静态服务器什么的。。。我直接用linux子进程运行搞定了：(hexo s &)

**Comment by Xuanwo** [comment]
恩，解决了就close吧
