### ISSUE TITLE
is_current('') is always true, regardless of current page url

### ISSUE THREAD

**Issue by webuniverseio** [hexojs/hexo#1112]
I expect that is_current('') should return false for pages like `/about/`, `/contact`, etc... Do I misunderstand something? Thank you.

**Comment by sammkj** [comment]
I encountered this problem as well.

**Comment by sammkj** [comment]
in order to make this work, I had to do this ```is_current('about/index.html')``` which seems to me a little bit counter-intuitive.

**Comment by dcanetma** [comment]
Here's a sample using EJS that seems to work.

			<% if(site.data.menu) {%>
				  <ul class="navbar-nav ml-auto">
				  	<% for (link in site.data.menu) { %>
					  	<li class="nav-item <%- is_current(site.data.menu[link]+'/index.html') ? 'active' : '' %>">
					  		<a class="nav-link" href="<%= config.root %><%= site.data.menu[link] %>" title="Go to <%= link %> page"><%= link %></a>
					  	</li>
						<% } %>
				  </ul>
		  <% } %>

**Comment by stevenjoezhang** [comment]
`is_current('')` is always `true`

https://github.com/hexojs/hexo/blob/c0bf22284c0c2e85bcd5c94b11823d86a0072035/lib/plugins/helper/is.js#L3-L20

https://hexo.io/docs/helpers#is-current
