### ISSUE TITLE
May I use `[]` square brackets and `:` colon in article title?

### ISSUE THREAD

**Issue by kuanyui** [hexojs/hexo#1113]
May I use square brackets `[]` or colon `:` in article title?

I often need to write a title like `[Emacs] Write A Major Mode` or `Emacs: Write A Major Mode`, but they will cause error when processing article:

square brackets:

    00:23:03.176 ERROR Process failed: _posts/emacs-write-a-major-mode.md
    JS-YAML: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2015-03-07 15:42:36
        ^

colon:

    JS-YAML: incomplete explicit mapping pair; a key node is missed at line 1, column 14:
    title: Emacs: Write A Major Mode

If use a escape `\` before bracket, it will be rendered as explicitly `\[Emacs\]`

With earlier version Hexo, at least, the later one is acceptable by processor.

    hexo: 3.0.0
    os: Linux 3.11.10-25-desktop linux x64
    http_parser: 1.0
    node: 0.10.29
    v8: 3.14.5.9
    ares: 1.9.0-DEV
    uv: 0.10.27
    zlib: 1.2.3
    modules: 11
    openssl: 1.0.1h

**Comment by celsomiranda** [comment]
Have you tried to write the frontmatter like this:

`title: "[Emacs] Write A Major"`

**Comment by kuanyui** [comment]
Yes, it works! I didn't find this ˊ・w・ˋ Thanks a lot!

**Comment by jr0cket** [comment]
You could use the - character.  So you could have a title in the form Emacs - Write a Major Mode

Thanks

**Comment by nkcoder** [comment]
I have the same problem, thank you!
