### ISSUE TITLE
How to sync articles in different clients

### ISSUE THREAD

**Issue by bejondshao** [hexojs/hexo#1118]
1. init hexo and git in my computerA. generate, deploy. As we know, the generated posts are deployed into github. But source, themes (also like source files) are ignored.
2. init hexo and git in another computer. So now, I can't find my original articles in source (of course), then I create a new article, problem comes. Do generate, deploy, issue will come.

One of my idea is delete the content of .gitignore, and commit all files to github each time I want to sync my files.

Is there any other better way to do this?

Thanks
Bejond

**Comment by niklaus520** [comment]
You can just checkout a new branch named source, then add your origin md file into it, for detail, you can take a look about the Principe of Octopress. Or my way: `https://github.com/niklaus520/niklaus520.github.com`

**Comment by bejondshao** [comment]
谢谢，你的方法很好，And your blog is really awesome!

**Comment by niklaus520** [comment]
哈哈哈哈谢谢夸奖呢！
