### ISSUE TITLE
JS files get changed by the renderer

### ISSUE THREAD

**Issue by DanielBaird** [hexojs/hexo#1119]
The docs imply that js files won't be touched by `hexo generate`, but in hexo 3.0.0 they are sometimes being mangled.

For example if I drop a copy of jQuery into my site's source folder somewhere, this piece of jQuery source:

    // Support: Android<4.1
    // Make sure we trim BOM and NBSP
    rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,

gets altered by `hexo generate` to become:

    // Support: Android<4.1 0="" make="" sure="" we="" trim="" bom="" ...(it continues)

It looks like the angle bracket in the comment is being treated as some kind of XML tag.

There is a workaround by adding

    skip_render:
    - '**/*.js'

to the `_config.yml` file, but this is nevertheless a bug.

**Comment by leesei** [comment]
It is a feature to process everything in `source/`
source code are not supposed to be in `source/`, see `code_dir` in `_config.yaml`.

**Comment by DanielBaird** [comment]
Okay so everything in `_source` gets processed.  In that case this issue is really a doc update request.  There's a line in the Setup section describing the `_source` folder that says:

> Renderable files (e.g. Markdown, HTML) will be processed and put into the public folder, while other files will simply be copied

Should it say something more like "Any text files (Markdown, HTML, source code, etc) will be processed..."?  Are binary files like jpgs in `_source` also processed?

**Comment by leesei** [comment]
The update will be noted.

You can also use `skip_render` in Hexo 3.
`skip_render: */*.js`

**Comment by leesei** [comment]
#1591

**Comment by Xuanwo** [comment]
And in Hexo 3.2-bete, you can use exclude option.
