### ISSUE TITLE
Database load failed

### ISSUE THREAD

**Issue by willin** [hexojs/hexo#1120]
```
> hexo serve
ERROR Database load failed. Deleting database.
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
```

```
> hexo g
ERROR Database load failed. Deleting database.
......
```

Hexo V3.0.0
io.js V1.5.1

`db.json` exist, app can be visited normally. but what's the error for and what does it mean?

**Comment by Xuanwo** [comment]
try `hexo clean`?

**Comment by celsomiranda** [comment]
I can reproduce it with the latest io.js, but not with node 0.12.1.

**Comment by willin** [comment]
nothing wrong in debug mode

**Comment by naokiy** [comment]
I found a bug in warehouse v1.0.1.

It may be related with your problem.

Please see https://github.com/tommy351/warehouse/pull/5 .
