### ISSUE TITLE
生成路径的问题，导致css，js无法加载

### ISSUE THREAD

**Issue by Rudy-Zhang** [hexojs/hexo#1121]
我使用 
> hexo init blog

新建了子目录下的工程。
修改_config.yml中的配置
> url: http://http://rudy-zhang.github.io//blog/
root: /blog/

这样在生成的public文件夹中使用浏览器直接打开index.html，其中的链接，请求的路径都是不对的。缺少了上一层的路径.
主页是
> file:///E:/HexoProject/blog/public/index.html

css的请求是：
> file:///E:/blog/css/style.css Failed to load resource: net::ERR_FILE_NOT_FOUND

在localhost和 http://rudy-zhang.github.io/blog 里面能够正常打开页面，但是绑定了域名之后出现了同样的问题。

请问这样是否合理，怎么解决？

**Comment by Xuanwo** [comment]
` http://http://rudy-zhang.github.io//blog/`

你这个= =，感觉写成` http://rudy-zhang.github.io/blog/`更加合理？

**Comment by Rudy-Zhang** [comment]
不好意思，这个是因为我试着修改了这个路径很多次，误加了一个'/'，但实际上删掉并没有解决问题，使用 http://rudy-zhang.github.io/blog 可以打开，但是绑定域名后，使用 http://rudy-zhang.me 无法加载css

**Comment by Xuanwo** [comment]
这个涉及到CNAME的问题= =，观察一下浏览器的出错信息，你很容易就能发现：
![image](https://cloud.githubusercontent.com/assets/5351546/6746552/2bcdf182-cf05-11e4-9368-840fd6028ff2.png)

CNAME实际上只会把`rudy-zhang.github.io`替换成`rudy-zhang.me`，后面的`\blog`并没有。
所以，我觉得合理的配置应当是这样的：
```
url: http://rudy-zhang.me/
root: /
```
试试看吧- -，我也不清楚会发生什么。。

**Comment by Rudy-Zhang** [comment]
谢谢！我用这样的方法解决了我的问题。但是还是有个问题不太明白，
> CNAME实际上只会把rudy-zhang.github.io替换成rudy-zhang.me，后面的\blog并没有

指的是我配置的CNAME文件，对吧？
我在绑定域名的时候把`rudy-zhang.me`绑定到`rudy-zhang.github.io`，也使用CNAME
我以为整个过程是，`rudy-zhang.me`翻译成`rudy-zhang.github.io`，然后剩下的就像不绑定域名一样了。
请问github这个CNAME文件，主要起什么作用？是怎么个过程？能不能稍微给我解释一下，多谢了

**Comment by Xuanwo** [comment]
默默上自己在知乎的回答
http://www.zhihu.com/question/26609475/answer/35596060

捂脸，撤。

问题解决可以close了，这些东西可以私下里交流。

**Comment by yiyiiii** [comment]
你好 ，楼主解决了吗？第一次配置，也出现了加载不出css的问题

**Comment by TonyRenHK** [comment]
楼主怎么解决的？![image](https://user-images.githubusercontent.com/9688136/46063331-19b42f80-c19f-11e8-8296-dc386a93c6fe.png)
