### ISSUE TITLE
A gitter room?

### ISSUE THREAD

**Issue by icylogic** [hexojs/hexo#1122]
[gitter.im](https://gitter.im) might help new users and developers communicate better.

**Comment by Xuanwo** [comment]
@tommy351

**Comment by tommy351** [comment]
We do have a gitter room. But I don't use it so far.
https://gitter.im/hexojs/hexo

**Comment by icylogic** [comment]
@tommy351 I'm sorry that I didn't search for it since I haven't found it in README ...
