### ISSUE TITLE
Tagcloud font-size error

### ISSUE THREAD

**Issue by willin** [hexojs/hexo#1123]
```html
<div class="widget tagcloud">
      <a href="/tags/Event/" style="font-size: NaNpx;">Event</a>
      <a href="/tags/Life/" style="font-size: NaNpx;">Life</a>
      <a href="/tags/Pet/" style="font-size: NaNpx;">Pet</a>
</div>
```

located:  `hexo/lib/plugins/helper/tagcloud.js`  line `219`

Hexo V3.0.0

**Comment by naokiy** [comment]
I found a problem that occurs when every tags has the same level.

I think that, when you post new article with some of tags, you can get the correct tagcloud.
