### ISSUE TITLE
我是新手，请问这个是什么问题？

### ISSUE THREAD

**Issue by cattigel** [hexojs/hexo#1127]
系统是win7-64bit，尝试好多次安装都这样。

Your environment has been set up for using Node.js 0.12.0 (x64) and npm.

C:\Users\Melody>npm install hexo -g
npm WARN optional dep failed, continuing fsevents@0.3.5
npm WARN optional dep failed, continuing fsevents@0.3.0
\

> dtrace-provider@0.4.0 install C:\Users\Melody\AppData\Roaming\npm\node_modules
\hexo\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

C:\Users\Melody\AppData\Roaming\npm\hexo -> C:\Users\Melody\AppData\Roaming\npm\
node_modules\hexo\bin\hexo
hexo@3.0.0 C:\Users\Melody\AppData\Roaming\npm\node_modules\hexo
├── hexo-front-matter@0.2.2
├── pretty-hrtime@1.0.0
├── abbrev@1.0.5
├── archy@1.0.0
├── titlecase@1.0.2
├── text-table@0.2.0
├── hexo-i18n@0.2.1 (sprintf-js@1.0.2)
├── bluebird@2.9.14

**Comment by Harvesty** [comment]
win7-32 同问。

**Comment by tommy351** [comment]
This is just a warning. It doesn't matter.

**Comment by Harvesty** [comment]
npm install -g cnpm --registry=https://registry.npm.taobao.org
这样就没有警告了。
C:\Users\lfs>npm install -g cnpm --registry=https://registry.npm.taobao.org
C:\Users\lfs\AppData\Roaming\npm\cnpm -> C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm
C:\Users\lfs\AppData\Roaming\npm\cnpm-web -> C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm-web
C:\Users\lfs\AppData\Roaming\npm\cnpm-user -> C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm-user
C:\Users\lfs\AppData\Roaming\npm\cnpm-sync -> C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm-sync
C:\Users\lfs\AppData\Roaming\npm\cnpm-search -> C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm-search
C:\Users\lfs\AppData\Roaming\npm\cnpm-check -> C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm-check
C:\Users\lfs\AppData\Roaming\npm\cnpm-doc -> C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm-doc
cnpm@3.0.0 C:\Users\lfs\AppData\Roaming\npm\node_modules\cnpm
├── auto-correct@1.0.0
├── giturl@0.0.3
├── commander@2.6.0
├── open@0.0.5
├── bagpipe@0.3.5
├── colors@1.0.3
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── debug@2.1.3 (ms@0.7.0)
├── npm-request@0.0.4 (urllib@0.5.11)
├── urllib@2.3.1 (native-or-bluebird@1.1.2, default-user-agent@0.0.1, media-typer@0.3.0, humanize-ms@1.0.1, iconv-lit
e@0.4.7, digest-header@0.0.1)
├── pangyp@2.1.0 (which@1.0.9, osenv@0.1.0, graceful-fs@3.0.6, rimraf@2.2.8, semver@4.2.2, nopt@3.0.1, mkdirp@0.5.0,
npmlog@1.0.0, fstream@1.0.4, tar@1.0.3, glob@4.3.5, minimatch@2.0.4, request@2.51.0)
└── npm@2.7.3

**Comment by yanzhenyu** [comment]
me too

**Comment by Harvesty** [comment]
好像是fsevents是Mac下操作文件用的，Win下不需要，所以Win用户可忽略。
不知这样理解对不对？
