### ISSUE TITLE
Removing "from around the web" in the docs

### ISSUE THREAD

**Issue by motleydev** [hexojs/hexo#1128]
This one is more of a personal pref/marketing thing. When viewing the docs I find the "from around the web" links really distracting and almost off-putting. Not sure if you're intending to keep them for the general web exposure but here's a link of how to remove it if you don't want it on there, either. https://modassicmarketing.com/remove-turn-off-the-disquis-around-the-web-discovery-links/

**Comment by revelt** [comment]
+1. Unless of course it's monetisation thing. By the way, Adblock + Ghostly wipes out all those banners, I didn't even knew they existed before you commented ;)

**Comment by motleydev** [comment]
Alas, I will likely need to go that route... Darn that money stuff.

**Comment by leesei** [comment]
I suppose those are from Discuss.
