### ISSUE TITLE
Duplicated child categories

### ISSUE THREAD

**Issue by naokiy** [hexojs/hexo#1132]
I found a bug in post setCategories.

If there were two posts categorized like below,

```yaml
category:
- foo
- bar
```

then hexo create two categories named 'bar'.

  * foo ( 2 posts )
    * bar ( 1 post )
    * bar ( 1 post )

**Comment by joysboy** [comment]
I have the same problem

**Comment by ppoffice** [comment]
Same problem, too.

**Comment by hanxiao** [comment]
Same problem for both english and chinese, seems language-independent.

**Comment by naokiy** [comment]
This problem is language-independent.

For detail, please see #1134.
