### ISSUE TITLE
HTTP request failed

### ISSUE THREAD

**Issue by shrimpma** [hexojs/hexo#1135]
hexo g -d  部署是出现一下错误

error: The requested URL returned error: 403 Forbidden while accessing https://github.com/shrimpma/shrimpma.github.io.git/info/refs

fatal: HTTP request failed

备注：github 帐号正确

**Comment by Xuanwo** [comment]
把`_config.yml`贴出来看看？
我猜你的repo设置不对，应该是：`https://github.com/shrimpma/shrimpma.github.io.git`

**Comment by shrimpma** [comment]
非常感谢回复
_config.ym 是默认的配置文件，只是修改了末尾的部署配置项
 
# Deployment
     68 ## Docs: http://hexo.io/docs/deployment.html
     69 deploy:
     70   type: git
     71   repo: https://github.com/shrimpma/shrimpma.github.io.git
     72   branch: master

**Comment by shrimpma** [comment]
已解决 
repository: git@github.com:shrimpma/shrimpma.github.io.git

**Comment by Nanue1** [comment]
请问楼主 怎么修改的repository  找了好久了 我的问题和你的一样

**Comment by Rozzon** [comment]
> 已解决 repository: [git@github.com](mailto:git@github.com):shrimpma/shrimpma.github.io.git

same problem
your method words!
thanks
