### ISSUE TITLE
Hexo generate stuck when a markdown file contains "------" character

### ISSUE THREAD

**Issue by Draveness** [hexojs/hexo#1137]
You can try it with add these to your markdown file

	--------------------------------------
	|        | eval | toString | hasZero |
	--------------------------------------
	|   Int  |      |          |         |   
	--------------------------------------
	|   Add  |      |          |         |
	--------------------------------------
	| Negate |      |          |         |
	--------------------------------------

My two file with this kind of character makes the hexo stuck

**Comment by Draveness** [comment]
@rexdf maybe, it is the "-" character causes the problem.

**Comment by rexdf** [comment]
是的，我猜的也是-号，应该是里面哪里的js的正则表达式写的有点儿问题。总之，我好像遇到过很多nodejs的正则问题。

总之js处理字符好像不是那么得心应手的。特别是hexo里面各种插件添加之后，各个插件参差不齐。

**Comment by Draveness** [comment]
早知道你也是中国人, 我还打毛线英文....我因为这个搞了快10个小时了

**Comment by rexdf** [comment]
呵呵
我是在试探着换到hexo，结果发现问题一堆，顺便上来发个issue。你定位到根源了吗？我似乎不大想搞js，也不知道怎么调试，问题我怀疑在插件里面。 10个小时又不算啥，等人家修复，等一个星期算正常的吧。

**Comment by rexdf** [comment]
https://github.com/hexojs/hexo-renderer-marked/blob/master/lib/renderer.js#L38

Maybe the problem is here.

**Comment by rexdf** [comment]
如果你注释掉第三行也许就好了

**Comment by Draveness** [comment]
我不是一个js开发者..所以我并不知道..我还好, 只有两篇blog不能发.

**Comment by rexdf** [comment]
我觉得octopress还不错啊，现在出3.0了，编程rails式的命令行了。hexo出现不能表达的特定字符组合(而且不是恶意构造的)，这说明这种玩意根本不值得用啊

**Comment by leesei** [comment]
Probably hightlight.js issue.
[#1124 `plain` and `auto_detect` option](https://github.com/hexojs/hexo/issues/1124)

Please open new issue if problem persists with latest build.
