### ISSUE TITLE
Tags wiped after publish

### ISSUE THREAD

**Issue by ricardojmendez** [hexojs/hexo#1139]
Just noticed this behavior:

- hexo new draft TestDraft
- Edit the article to add tags and some text
- hexo publish TestDraft

The tags will have been removed from the resulting article.

Environment:

hexo: 3.0.0
os: Darwin 14.1.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l

**Comment by steckerhalter** [comment]
I noticed the same thing with 3.0.0
I suddenly wondered why my tags were missing on the published site (for like the last 4 posts) and it occurred to me that all the tags had been removed from the markdown when I was using `publish` after having switched to 3.0.0

**Comment by ricardojmendez** [comment]
This issue persists on 3.0.1

**Comment by naokiy** [comment]
I met same trouble.

I modified scaffold file like below to fix it.

```markdown:scaffolds/post.md
title: {{ title }}
date: {{ date }}
tags:{% for tag in tags %}
  - {{tag}}{% endfor %}
---

```
