### ISSUE TITLE
{{{}}}、{{> partials }}

### ISSUE THREAD

**Issue by loveLibra** [hexojs/hexo#1140]
hexo server cannot start，tags like the title cannot be compiled...U can take a test。 I am waiting for your answer

**Comment by revelt** [comment]
hi mate, please be more specific. I'm running latest Hexo and it's all smashing

**Comment by loveLibra** [comment]
@revelt my hexo version is 2.8.3....I create a easy example just add content：{{}}....run hexo server，throw error:SyntaxError:unexpected token ;I don‘t know why...
Tip: when add a keyname to {{}},just like {{key}},nothing wrong happened

**Comment by revelt** [comment]
@loveLibra something's not right at your setup.
In your case I'd:
1) backup everything (copy folder)
2) if you don't use nvm, uninstall node and npm, install nvm.
3) install latest hexo
4) manually port config.yml settings (some things changed on v.3)
5) port the content, test using default theme
6) switch theme to yours, test again
(I actually did this when v.3 release came out)

by the way, I hope you don't type "run hexo server"? The correct command is "hexo server".

**Comment by loveLibra** [comment]
@revelt  thks for your help, I will try them.In addition, “run hexo server”, I mean, “run command ---hexo server” ,sorry for unclear expression >_<!!!

**Comment by leesei** [comment]
So a ``{{}}`` without variable is causing error?
Did you tried latest build?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
