### ISSUE TITLE
hexo list fails with 'process out of memory' (v3.0.0)

### ISSUE THREAD

**Issue by philcryer** [hexojs/hexo#1141]
I'm running my Hexo site in 2.x, and it has over 500 posts that I migrated in from Jekyll. I updated to 3.0.0, but it fails to generate, hanging part way through. I've uninstalled/reinstalled hexo-cli to be sure I had only the most recent. I can init a new site and see it running under server, but if I put my _posts in it will hang on the generation and I have to kill it (debug shows nothing wrong).

So I tried creating a new site, this seems strange

```
$ hexo init foo
INFO  Copying data to ~/devel/foo
INFO  You are almost done! Don't forget to run 'npm install' before you start blogging with Hexo!

$ cd foo

$ npm install

$ hexo -v
hexo: 3.0.0
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l

$ hexo list
Usage: hexo list <type>

Description:
List the information of the site.

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    59015 abort      hexo list
```

FWIW, I'm running a MacBook Pro with 16G RAM

```
$ uname -a
Darwin macbook-mac.local 14.3.0 Darwin Kernel Version 14.3.0: Tue Mar 10 20:10:46 PDT 2015; root:xnu-2782.20.44.1.1~1/RELEASE_X86_64 x86_64
```

**Comment by philcryer** [comment]
Yikes, it looks like there are other generate issues (https://github.com/hexojs/hexo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+generate) so that could be my generate issue, but still why do I get this error:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    59015 abort      hexo list
```

**Comment by philcryer** [comment]
I think I have too many posts for hexo. Thanks

**Comment by naokiy** [comment]
I think it is a bug of v3.0.0 and v3.0.1.

Please check https://github.com/hexojs/hexo/pull/1209 .
