### ISSUE TITLE
About variable "page.excerpt" 

### ISSUE THREAD

**Issue by Hill1942** [hexojs/hexo#1143]
when I try to get the value of `page.excerpt` by <%= page.excerpt %>, there's nothing out.

So where to define `page.excerpt`?

**Comment by jorgt** [comment]
Same issue with posts. `post.excerpt` is always available but always empty.

**Comment by bvodola** [comment]
Use a html comment with the word "more" to mark the excerpt of your post, like this:

```
title: post title
---
This part is the excerpt, get it with the <%- post.excerpt %>
<!-- more --> 
This is the rest of the post. You can get it with <%- post.more %>
```

All the text after the `<!-- more -->` is only displayed when you view the page of the post.

Font: https://groups.google.com/forum/#!topic/hexo/cdbCM0lb9A0

**Comment by felipesousa** [comment]
@bvodola thanks brother, you help me! thanks

**Comment by 0326** [comment]
it works! thanks@bvodola

**Comment by psychicalcoder** [comment]
@bvodola thanks
I've been trying to solve this problem for hours QAQ

**Comment by connor11528** [comment]
I am also having an error rendering the post.excerpt. I specified more in my blog posts but when I look at the source, excerpt is always set to an empty string, despite the more html comment. This is the code I am using to grab the excerpt that does not render it. 

I am using 
 - "hexo": "^3.3.8"
- "hexo-renderer-ejs": "^0.1.0"
- "hexo-renderer-marked": "^0.2.4"

```
            <% site.posts.each(function(post, i){ %>
                <div class='notification is-danger post'>
                    
                    <a href="<%- url_for(post.path) %>" class='underline-link' style='padding-bottom: 8px;'>
                        <%= post.title %>
                    </a>
                    <p class='padding-bottom-10'>
                    <% post.tags.each(function(tag){ %>
                        <span class="tag"><%= tag.name %></span>
                    <% }); %>
                    </p>
                    <p>Excerpt: <%- post.excerpt %></p>
                    <p>
                      <%= date(post.date, config.date_format) %> 
                    </p>
                </div>
            <% }); %>
```
