### ISSUE TITLE
访问地址如果带参数返回的 Content-Type 有问题

### ISSUE THREAD

**Issue by JuoCode** [hexojs/hexo#1149]
原始地址： http://doma.in/2015/my_post/

添加参数以后：http://doma.in/2015/my_post/?source=xxx，
此时查看 response 发现 `Content-Type: application/octet-stream`，导致浏览器下载文件

**Comment by Xuanwo** [comment]
静态文件也能带参数？。。

**Comment by JuoCode** [comment]
可以带呀，只是个URL而已

**Comment by Xuanwo** [comment]
感觉并不是hexo的问题，大概跟github那边的设置有关

**Comment by JuoCode** [comment]
跟 Github 没关系吧，博客在我们自己的服务器上

**Comment by Nerom** [comment]
服务器是动态还是静态？静态的好像默认处理就是下载，这个应该是和服务器有关的

**Comment by JuoCode** [comment]
服务就是 `hexo server` 起来的

**Comment by Xuanwo** [comment]
Closed for not using `hexo-server` as prduction environment. Use apache or nginx instead.
