### ISSUE TITLE
本地更新过的页面，上传到Heroku时会被识别成没有改变

### ISSUE THREAD

**Issue by tongda** [hexojs/hexo#1153]
在本地对标签作了修改，本地`hexo server`也能看到更新，但是执行`hexo d -g`上传到在heroku后，就看不到标签，对应标签的页面也没有更新。

感觉好像是对比页面是否修改上传的逻辑有些问题，有人遇到过类似情况么？

**Comment by Xuanwo** [comment]
先`hexo clean`试试看

**Comment by tongda** [comment]
`hexo clean`过了，本地`hexo server`看都是好的，但是部署上去，页面就是不对。感觉可能git同步的问题，有些文件没有识别出已修改。那些tag是我后加上去的，会不会是这个原因？

**Comment by Xuanwo** [comment]
什么叫本地对标签进行了修改？你直接修改了HTML页面？

**Comment by tongda** [comment]
就是一个post没加tag，我写完就传上去了，然后我发现没加标签，就加上了一个tag。

运行`hexo generate`之后，`hexo server`可以看到那个标签，也可以打开标签的页面。

但是，运行`hexo deploy`，在网站上就找不到标签了。

**Comment by Xuanwo** [comment]
重置一下heroku然后看看效果呢？
我没有用过heroku，不知道具体的情况，但是感觉并不是git的问题。

**Comment by Xuanwo** [comment]
Hello, any update?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.

**Comment by reverland** [comment]
@xuanWo i think it may just because the cache of the browser. And just experieced some latency today with gitcafe tiday
