### ISSUE TITLE
Overriding permalink in front-matter

### ISSUE THREAD

**Issue by mariusk** [hexojs/hexo#1158]
I'm trying to override the permalink for individual posts in the "front-matter" but I'm not having much luck. Is the feature actually supported, and if so what is the proper configuration to have it working? Any pointers?

**Comment by Xuanwo** [comment]
your can place it the special dictory

**Comment by gymgle** [comment]
@Xuanwo The permalink in 3.0 is not valid, is it?

**Comment by Xuanwo** [comment]
I don't know, I never used the permalink before~

**Comment by gymgle** [comment]
@mariusk Hexo `3.0.1` is released, overriding permalink in front-matter works! Try the new version.

Thanks @Xuanwo

**Comment by luss613** [comment]
I'm using the version 3.0.1, this bug still here.

**Comment by prigazzi** [comment]
This is still happening to me on 3.1.1
Documentation is not clear on how to use this feature.

**Comment by dhpollack** [comment]
I am having this problem as well, I'm not sure this issue should be closed @Xuanwo

**Comment by carlhopf** [comment]
here's a quick hack which fixes the issue, allowing for a custom property called 'permalink_rule' in the front-matter of each post to override the global permalink https://github.com/carlhopf/hexo/commit/8b9c7e6196507aa72cbfcc928f4995ab8245aadb

but this needs further testing - for example what should happen if two posts try to use the same permalink?

**Comment by kynetiv** [comment]
Similarly to @carlhopf's fix, here's a [gist](https://gist.github.com/kynetiv/b27da64adaa1341750aafc4271764831) of a fix for allowing a post to provide a permalink with the help of a couple [filters](https://hexo.io/api/filter.html).
