### ISSUE TITLE
3.0 bug：二级分类显示有误

### ISSUE THREAD

**Issue by victorwoo** [hexojs/hexo#1159]
两篇文章都是

    categories :
    - foo
    - bar

结果首页的 Categories 这个 widget 渲染出来是这样（两个 bar 没有被归纳到同一个分类中）：
![qq 20150330102733](https://cloud.githubusercontent.com/assets/173351/6889397/f179bd48-d6c7-11e4-9aa0-07f55e06bfff.png)

而在 2.x 版中是正常的。

**Comment by Xuanwo** [comment]
我自己测试了一下，不管是：
```
categories :
- foo
- bar
```
还是：
```
categories : [foo, bar]
```
都会出现这样的问题。

@tommy351

**Comment by naokiy** [comment]
I cannot read Chinese.
But I think It seems to be the same problem #1132.
it was already fixed in 3.0.1.

**Comment by Xuanwo** [comment]
Let's me have a test.
