### ISSUE TITLE
How to except html files in source

### ISSUE THREAD

**Issue by gejiawen** [hexojs/hexo#1160]
I wanna put some slides in my blog, these slides are html files. Hexo 3.x.x will rendered them all the same, this is not the way i want.

So, I'm expecting how to except files in source folder?

Temporarily, I put my slide html files into `themes/theme-name/source`, but this is ugly. :disappointed: 

@tommy351

**Comment by Xuanwo** [comment]
skip_render

**Comment by Xuanwo** [comment]
https://github.com/hexojs/hexo/issues/1146#issuecomment-88380140

(⊙v⊙)嗯，总算研究出来了~
