### ISSUE TITLE
Hexo分类和标签的路径怎么设置成英文

### ISSUE THREAD

**Issue by Eurry** [hexojs/hexo#1162]
Hexo分类和标签的路径怎么设置成英文？？

比如说我点分类“Linux操作系统”后的路径是：
http://localhost:4000/categories/Linux操作系统
我想设置成英文的URL，可以像 permalink 的 id自动生成，或者能不能给每个分类设置个英文的别名，只用于URL。
因为我的主机不支持中文字符的URL，一直报404。
可以到 http://www.eurry.net/ 
看看，一点分类就报404

**Comment by gejiawen** [comment]
以前纯属个人猜测，

你可以修改`{theme-name}/_config.yml`中关于链接的内容，比如，

```yml
menu:
  首页: { id: index, url: / }
  归档: { id: archives, url: /archives }
  分类: { id: categories, url: /categories }
  标签: { id: tags, url: /tags }
  阅读: { id: reading, url: /reading }
  实验室: {id: labs, url: /labs }
  关于: { id: about, url: /about }
```

然后在模版中，

```ejs
<% for(var key in theme.menu) { %>
    <li id="nav-<%- theme.menu[key]['id'] %>">
        <a href="<%- theme.menu[key]['url'] %>"><%= key %></a></li>
<% } %>
```

**Comment by PlatypusPro** [comment]
似乎在`_config.yml`的`# Category & Tag`一项下面的`tag_map`和`category_map`下面这样写就行了吧
```
# Category & Tag
default_category: uncategorized
category_map: 
	Linux操作系统: Linux-OS
	中文分类: 英文分类
tag_map:
	中文标签: 英文标签
```

**Comment by Eurry** [comment]
真的，这样设置一下就可以了，谢谢楼上

**Comment by NewbMiao** [comment]
为什么我试了不行呢，hexo3.1.1，mac

**Comment by w138789** [comment]
看这个文件_config.yml的编码是不是UTF-8的,要设为这个编码才行

**Comment by DeppWang** [comment]
PlatypusPro 解决了我的问题，感谢
