### ISSUE TITLE
iojs instead of nodejs

### ISSUE THREAD

**Issue by lifehome** [hexojs/hexo#1163]
想請問一下可以用 iojs 替代 nodejs 的嗎？

**Comment by Xuanwo** [comment]
我猜是可以的，因为hexo有在iojs上进行测试。

**Comment by Xuanwo** [comment]
你好，请问你在iojs上使用成功了么？

**Comment by lifehome** [comment]
一半半吧…？因為我不太懂怎樣deploy locally，而hexo也没怎寫過如何配搭forever的用法，所以放棄了…

不過大致的前期測試都通過的。(iojs v1.6.3)

**Comment by lifehome** [comment]
@Xuanwo  請問 iojs 有 forever 的教程嗎？

**Comment by Xuanwo** [comment]
Closed for no more update.
