### ISSUE TITLE
adding custom http headers in development

### ISSUE THREAD

**Issue by timkuijsten** [hexojs/hexo#1167]
I'd like to insert a custom http header (namely a certain [CSP](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives) policy).

Is this already possible? At first sight I can only see https://github.com/hexojs/hexo-server/blob/master/lib/middlewares/header.js which makes me think it's currently not possible to add some headers in development dynamically.

**Comment by Xuanwo** [comment]
Do you mean meta? You can modify the `header.ejs` in your theme's flie.

**Comment by timkuijsten** [comment]
No not meta, an HTTP-header used with `hexo server`.

**Comment by Xuanwo** [comment]
modify the `hexo-server` by yourself maybe helpful

**Comment by timkuijsten** [comment]
You have any point where I could start? Not https://github.com/hexojs/hexo-server/blob/master/lib/middlewares/header.js is it?

**Comment by Nerom** [comment]
http header  is related to the server you use

**Comment by tommy351** [comment]
Write a `server_middleware` filter.
http://hexo.io/api/filter.html#server_middleware

**Comment by timkuijsten** [comment]
@nerom I understand. In production I use nginx with a `Content-Security-Policy: default-src 'self';` header. In development I would like reproduce this header and see if the theme is compatible with it.

**Comment by timkuijsten** [comment]
@tommy351 interesting, I will try this.

**Comment by Nerom** [comment]
get it
