### ISSUE TITLE
hexo 3.0 Generate

### ISSUE THREAD

**Issue by yinxianwei** [hexojs/hexo#1168]
md info is:

    typedef NS_ENUM(NSInteger, UIModalTransitionStyle) {    
    UIModalTransitionStyleCoverVertical = 0,//默认   
    UIModalTransitionStyleFlipHorizontal,//旋转   
    UIModalTransitionStyleCrossDissolve,//淡入   
    UIModalTransitionStylePartialCurl NS_ENUM_AVAILABLE_IOS(3_2),//翻页   
    };

$ hexo g
`No reaction`

md info change:

    (NSInteger, UIModalTransitionStyle) {    
    UIModalTransitionStyleCoverVertical = 0,//默认   
    UIModalTransitionStyleFlipHorizontal,//旋转   
    UIModalTransitionStyleCrossDissolve,//淡入   
    UIModalTransitionStylePartialCurl NS_ENUM_AVAILABLE_IOS(3_2),//翻页   
    };

$ hexo g
is ok!

typedef NS_ENUM is not a problem?

**Comment by yinxianwei** [comment]
用了别人说的方法`{% raw %}typedef NS_ENUM{% endraw %}`这样也可以。   
不过这在3.0之前是不用包裹的，并且 generate的时候没有任何错误提示，就是一直无响应。

**Comment by Xuanwo** [comment]
反正新版本`----`和`____`都有各种奇奇怪怪的问题- -，看看能不能修复吧

**Comment by Xuanwo** [comment]
3.1.1之后貌似修复了，关掉`auto_detect`试试
