### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by grasses** [hexojs/hexo#1169]
Version 3.0.0 have deploy bug.

I once use version 2.8.3, and now recover system, now Version 3.0.0 can not deploy.

Can generate, but can not deploy,  without any error info.

**Comment by Nerom** [comment]
I have not met this problem, But did you update the dployer either?

**Comment by Xuanwo** [comment]
我觉得- -，你需要好好的阅读一下wiki中关于升级至hexo3.0的内容。

**Comment by grasses** [comment]
No, I try it again, install everything follow http://hexo.io/news/

my git no error, can push.

dployer installed.

my package.json is:
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.0.0"
  },
  "dependencies": {
    "hexo": "^3.0.0",
    "hexo-deployer-heroku": "0.0.3",
    "hexo-deployer-openshift": "0.0.1",
    "hexo-deployer-rsync": "0.0.2",
    "hexo-generator-archive": "^0.1.1",
    "hexo-generator-category": "^0.1.1",
    "hexo-generator-index": "^0.1.0",
    "hexo-generator-tag": "^0.1.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-stylus": "^0.2.0",
    "hexo-server": "^0.1.2"
  }

**Comment by Xuanwo** [comment]
唯独没有安装`hexo-deployer-git`么= =

**Comment by grasses** [comment]
安装了，东西都有。

![screen shot 2015-04-03 at 20 18 07](https://cloud.githubusercontent.com/assets/5513110/6982072/084916d4-da3f-11e4-9206-d0e669925f2f.png)
![screen shot 2015-04-03 at 20 18 19](https://cloud.githubusercontent.com/assets/5513110/6982074/084c3328-da3f-11e4-8bc3-2bbb88cde1c9.png)
![screen shot 2015-04-03 at 20 20 49](https://cloud.githubusercontent.com/assets/5513110/6982073/084bd158-da3f-11e4-9b25-169801ba4063.png)

**Comment by Xuanwo** [comment]
![](https://cloud.githubusercontent.com/assets/5513110/6982074/084c3328-da3f-11e4-8bc3-2bbb88cde1c9.png)

你没有空格。。

**Comment by grasses** [comment]
no...有空格就报错....我也是无言以对。

**Comment by grasses** [comment]
可以了。。好鬼畜。no reason...

**Comment by Xuanwo** [comment]
搞定了就Close吧
