### ISSUE TITLE
how to run Hexo 3.0 on Ubuntu server with Apache?

### ISSUE THREAD

**Issue by allengaller** [hexojs/hexo#1170]
hello, I think the maintainer speak Chinese? so...

您好，　国内github慢，　如果希望在自己的server上跑Hexo 3.0怎么设置(我仔细看了官网文档没看到)？
总不能一直是hexo server吧？

感激不尽！

**Comment by Xuanwo** [comment]
实际上，只需要将生成的静态文件摆在/www/html静态目录，然后设置一下nginx或者apache反代就可以了。

**Comment by leesei** [comment]
`hexo server` is intended for live preview and not for deployment
`hexo generate` will generate the static HTML files for deployment.
`hexo deploy` will deploy the generated file according to the deployer plugins configured.
