### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by Huang77** [hexojs/hexo#1173]
when I do the "nom install' in the target folder, it  is stuck at the following for a long long time...
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/ejs/-/ejs-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/mime/-/mime-1.3.4.tgz

is this totally the problem of network?? or some problems else??

**Comment by leesei** [comment]
Network problem, please close this issue.

**Comment by Xuanwo** [comment]
Thanks GFW.
Please close the issue, and find a way to download packages.

**Comment by Xuanwo** [comment]
Hello, do you still have the problem?
