### ISSUE TITLE
The function `find` of the warehouse doesn't work

### ISSUE THREAD

**Issue by LouisBarranqueiro** [hexojs/hexo#1174]
Hi. i'm using Hexo v3.0.0 and the function ```find``` of the warehouse doesn't work. I have an error when i'm using it.
``` javascript
<% site.categories.find({'name': item.name}).posts.each(function(post) { %>

Cannot call method 'each' of undefined
```
But when i'm using the function ```findOne```, it works. Am i using correctly the warehouse ```find``` function or is it a bug? There was a documentation of the warehouse API on the previous version of Hexo but not available actually...

**Comment by tommy351** [comment]
The `find` method returns an collection of categories. You can't get the posts from it directly.

**Comment by LouisBarranqueiro** [comment]
Ok thank you for your answer. Could you re-publish the documentation for the warehouse API? please. It would be very helpful :)
