### ISSUE TITLE
`hexo server` fails to update content after a while (3.0.0)

### ISSUE THREAD

**Issue by steckerhalter** [hexojs/hexo#1175]
When I work on a post or page after a few minutes a browser refresh does not update the content anymore. Any new changes I make to the file are not reflected and I need to kill the server and start it again to pick up the changes (which only works for a few minutes again)

**Comment by Xuanwo** [comment]
I have the same problem.

**Comment by steckerhalter** [comment]
I have updated to 3.1.1 and still get this issue. I tried switching node versions, removed the modules and did a clean install but it still fails to update the draft I'm working on. Any ideas?

**Comment by JamesPan** [comment]
I catch the same problem these days. Several days ago, I build a docker image with hexo 3.0.1 and it can update contents. 

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.0.1"
  },
  "dependencies": {
    "hexo": "^3.0.0",
    "hexo-generator-archive": "^0.1.0",
    "hexo-generator-category": "^0.1.0",
    "hexo-generator-index": "^0.1.0",
    "hexo-generator-tag": "^0.1.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-stylus": "^0.2.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-server": "^0.1.2",
    "hexo-generator-sitemap": "~1.0.1",
    "hexo-generator-feed": "~1.0.1",
    "hexo-deployer-git": "0.0.4"
  }
}
```

On my Mac I tried hexo 3.0.1 3.1.0 3.1.1 and it doesn't work.

**Comment by steckerhalter** [comment]
@JamesPan So do you think it's related to the OS? What was the docker image based on?

**Comment by JamesPan** [comment]
@steckerhalter ubuntu 14.04. I am not really sure, but the hero-fs module related on fsevents, which is os x only

**Comment by steckerhalter** [comment]
@JamesPan ok, I'm having the issue on Debian Linux btw.

**Comment by JamesPan** [comment]
@steckerhalter I found a really weird situation. My hexo blog was in ~/Sites/blog, and it can't update content. But when I moved the directory to ~/, it can update content like it used to be.

I don't know why this happens, maybe you can try.

**Comment by steckerhalter** [comment]
@JamesPan I experimented a bit (renamed the folder etc.) and could make it update the content once over a longer period. Then it fell back to just update for like one minute or something. Quite weird.

**Comment by morris821028** [comment]
@steckerhalter 
I agree with you. When my blog has 700+ articles, updating the content in latest articles will make `hexo server` lock in several minutes, and I can't view website on chrome or firefox.


```
Yang@MORRIS /d/morris821028.github
$ hexo -v
hexo: 3.1.1
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
```

**Comment by CodeFalling** [comment]
My hexo blog is just in `~/blog`,not work.
```
hexo -v
hexo-cli: 0.1.8
os: Linux 2.6.32-042stab108.8 linux ia32
http_parser: 2.0
node: 0.10.36
v8: 3.14.5.10
ares: 1.9.1
uv: 0.10.34
zlib: 1.2.3
modules: 11
openssl: 1.0.1e-fips
```

**Comment by CodeFalling** [comment]
I tried `hexo generate --watch`,when I update a post,there is nothing except `INFO  Generated: css/main.css`

**Comment by CodeFalling** [comment]
Also,`hexo server --DEBUG` print `DEBUG Updated: source/_posts/balbala.org` at the first time I update file.Then get `DEBUG Unchanged: source/_posts/balbala.org` every time I redo it.

**Comment by steckerhalter** [comment]
I thought it's time to investigate this, so for me what happens is that Hexo detects the same sha hash  even though the file has been changed. The code where this happens is here: https://github.com/hexojs/hexo/blob/master/lib/box/index.js#L216

Now I just need to find out why the file that obviously **has been changed** is returning the same hash in hexo.

**Comment by steckerhalter** [comment]
there is some transform in there (whatever that is for) and the problem seems to be that it's not executed at all in some cases:

https://github.com/hexojs/hexo/blob/master/lib/box/shasum_stream.js#L16

**Comment by steckerhalter** [comment]
so the hash is not updated... if I'm understanding this correctly

**Comment by steckerhalter** [comment]
I'm not able to find the solution. It's producing always the same SHA hash. I suppose the bug is somewhere in the nodejs stream interface. I still have no idea why _transform is not executed as it should

**Comment by steckerhalter** [comment]
The hash is just wrong. And then it always gets this same wrong hash no matter how the actual hash of the file is.

**Comment by steckerhalter** [comment]
The funny hash is `da39a3ee5e6b4b0d3255bfef95601890afd80709`. I have no idea where it gets that from since the file never has that. Hashing is broken in hexo for some reason (maybe on Linux only?). I resorted to make an exception for the specific hash since it always means the file has been updated :santa:

**Comment by Xuanwo** [comment]
@sergiolepore How about `xxhash`? try hexo 3.2-beta, thanks.

**Comment by sergiolepore** [comment]
@Xuanwo sorry?

**Comment by Xuanwo** [comment]
@sergiolepore well, I mean we use an another hash tool, this change may resolve the problem, and I hope you can have a try. Sorry for my miss leading.

**Comment by sergiolepore** [comment]
@Xuanwo I still don't get it... Are you confusing me with @steckerhalter? :confused:

**Comment by steckerhalter** [comment]
@Xuanwo I think it's better now in the beta. I still saw some cases where it didn't update and that was mostly when the change was a small one and it didn't seem to get picked up, so there might be a new issue creeping up :)

**Comment by Xuanwo** [comment]
@sergiolepore yes .. :sob:

**Comment by Xiamu-ssr** [comment]
> I tried `hexo generate --watch`,when I update a post,there is nothing except `INFO Generated: css/main.css`

this work for me.
my status: 

-   wsl2 
-   ubuntu18.04
-   docker

when i use command `hexo generate -w` and i update one of my post , i get 

> INFO  Hexo is watching for file changes. Press Ctrl+C to exit.
INFO  Generated: atom.xml
INFO  Generated: 2023/04/09/test2-image-tese/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2023/04/index.html
INFO  Generated: archives/2023/index.html
INFO  Generated: index.html

i know hexo maybe get update so i use command `hexo s --debug` last, i get my web updated!!
i stop it, i want to know how to let hexo success update resource real time
so i use `hexo s --debug` again, and then i modify one of my post, i got

> 08:01:24.095 INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
08:01:24.106 DEBUG Database saved
08:01:59.645 DEBUG Processed: _posts/test1.md
08:01:59.749 DEBUG Rendering post: /root/BK/blog/source/_posts/test1.md
08:01:59.768 DEBUG Generator: asset
08:01:59.769 DEBUG Generator: page
08:01:59.769 DEBUG Generator: post
08:01:59.770 DEBUG Generator: atom
08:01:59.785 DEBUG Generator: archive
08:01:59.787 DEBUG Generator: category
08:01:59.787 DEBUG Generator: index
08:01:59.791 DEBUG Generator: tag
08:02:01.260 DEBUG Rendering HTML index: index.html

and in localhost link i see my web is updated.
that save my day!
thanks! although this method doesn't seem to work for you.
