### ISSUE TITLE
permalink: 

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo#1176]
permalink: :title.html
 permalink_defaults: 
永久地址这样写,就不行,如何实现这样写
permalink: :title.html/
 permalink_defaults: 
这样写可以. 差一个/

**Comment by Xuanwo** [comment]
所以，你想表达什么= =

permalink貌似应当以`/`结尾，这个是窝测试之后的结论

**Comment by Xuanwo** [comment]
Closed for no more update.
