### ISSUE TITLE
Is there a way to get posts by author?

### ISSUE THREAD

**Issue by fanxb** [hexojs/hexo#1177]
Hello, I have updated something about a post given a specific author through this issue (https://github.com/hexojs/hexo/issues/673). However, I have another question, how to get those posts published by a specific author? Is there a way to get?

**Comment by tommy351** [comment]
For example, you can get posts in theme templates:

``` js
site.posts.find({
  author: '...'
})
```

**Comment by fanxb** [comment]
Thanks!

**Comment by fanxb** [comment]
Hi, Tommy, another question. Is there any other paras that could be used in 'site.posts.find({})', such as `categories, tags...`? ( `author` is ok. )
PS: I couldn't find any information in `/docs`.

**Comment by tommy351** [comment]
Sorry I haven't update the documentation for Warehouse yet. You can get posts of specified categories/tags by:

``` js
site.categories/tags.findOne({name: 'foo'}).posts
```
