### ISSUE TITLE
Add hexojs core committers (form a hexojs team?)

### ISSUE THREAD

**Issue by steckerhalter** [hexojs/hexo#1178]
As hexo is a really nice framework it would be important (I think) to add core committers that help to develop hexojs so in case one person is blocked another person can take over and fix bugs etc. It probably would also help the project to thrive (an example I have in mind is `Vagrant` which was accelerated a lot when Mitchell decided to give other people core commit rights).

I'm just proposing to think about this (I lack the JS skills and time, so you can count me out anyway :)

**Comment by Nerom** [comment]
up!!!

**Comment by tommy351** [comment]
:+1:

**Comment by naokiy** [comment]
+1

**Comment by celsomiranda** [comment]
I agree with this, but the project should have some guidelines on where it's moving in the future, so we don't get sidetracked.

**Comment by steckerhalter** [comment]
I must say that hexo is pretty advanced compared to - let's say jekyll. I don't see many things "lacking". Of course improvement is always possible and guidelines would surely help to keep the focus.

I'd like to point out that trust is a core issue usually in development teams. First you need to grant trust with the danger of getting disappointed, but that's part of the game. If you do not start on a trust-basis nobody will ever really be able to unlock their full potential.

So looking at the hexo stats: @tommy351 has put a lot of work into this project and I believe that he knows best how to coordinate this matter.

If I can be of any assistance in it, then please let me know.

**Comment by celsomiranda** [comment]
I agree 100%.

**Comment by Nerom** [comment]
I am now trying to read the code (^_^)

**Comment by tommy351** [comment]
Currently we have a [contribution guide](http://hexo.io/docs/contributing.html) in the documentation. Anything else needed?

I'm working on my school project and may have less time to maintain Hexo. If you'd like to become a core contributor, please let me know.

**Comment by Xuanwo** [comment]
Well, I want to be a core contributor. But I think I need sometime to know more about nodejs, maybe I can start from manage the issues.

**Comment by Nerom** [comment]
If could , I'm **IN** !

**Comment by Voidly** [comment]
I'm interested in **hexo**.I've just write a small project using **nodejs**, I want to join you.

**Comment by lzjqsdd** [comment]
I like hexo very much,and I have edit some files for myself,happy to join this project!

**Comment by Voidly** [comment]
@tommy351 I've read the  contribution guide,please let me in.

**Comment by lzjqsdd** [comment]
@tommy351 If could,please let me in,And interest will drives me much,I want hexo be better!

**Comment by tommy351** [comment]
@Voidly @lzjqsdd I have sent the invitation.

**Comment by lzjqsdd** [comment]
ok,i will check it tomorrow,good night!

在 2015-04-13 01:12:41，"Tommy Chen" <notifications@github.com> 写道：


@Voidly@lzjqsdd I have sent the invitation.

**Comment by iissnan** [comment]
Great proposal. Good to see that Hexo has such a open mind. Cheers.

**Comment by chrisjlee** [comment]
+1

**Comment by tommy351** [comment]
@chrisjlee Invited

**Comment by FrankBian** [comment]
up :+1:

**Comment by NoahDragon** [comment]
We are still open and welcome any one who would like to join Hexo community.

**Comment by steckerhalter** [comment]
you can close this if you want

**Comment by stevenjoezhang** [comment]
I will close this issue, as the Hexo maintenance team continues to have new members joining. Thank you all for your collective efforts and contributions to the open source community!
