### ISSUE TITLE
超链接失效

### ISSUE THREAD

**Issue by wongzigii** [hexojs/hexo#1179]
CNAME记录 指向我的二级域名 [blog.wongzigii.com](http://blog.wongzigii.com)
另外两个是Github的A记录
以下是我的域名解析：

![2015-04-06 7 11 40](https://cloud.githubusercontent.com/assets/7384288/7003679/403b6df4-dc91-11e4-85dd-b2e997d137d3.png)

但是当我点击最近文章的链接，链接失效打不开显示Github 404 页面。

奇怪的是，我在本地Server中一切正常。

**Comment by Xuanwo** [comment]
CNAME那条记录删掉，完毕。

**Comment by wongzigii** [comment]
@Xuanwo 删除后仍然显示404 
[http://blog.wongzigii.com/2015/04/06/Hello-World/](http://blog.wongzigii.com/2015/04/06/Hello-World/)

**Comment by Xuanwo** [comment]
把`@`改成`blog`

**Comment by wongzigii** [comment]
还是不行  :(

**Comment by Xuanwo** [comment]
![image](https://cloud.githubusercontent.com/assets/5351546/7005437/8d64d052-dcaa-11e4-88b4-0d726e49cc16.png)
我把你的大写改成小写之后。。。。。。

**Comment by wongzigii** [comment]
:+1:
