### ISSUE TITLE
如何正确地更新版本？

### ISSUE THREAD

**Issue by imhentai** [hexojs/hexo#1181]
从3.0.0-3.0.1该如何操作呢
是跟2.x-3.0一样重新安装一遍吗？
后面的那些插件也要重新安装么...感觉挺繁琐的，求介绍最简单的姿势

**Comment by imhentai** [comment]
按照2.x-3.0的方法重新安装了一遍...
每次升级都要这样吗....感觉有点麻烦啊，有没有一键升级的方法...

**Comment by tommy351** [comment]
Just one command:

``` bash
$ npm update hexo
```

**Comment by imhentai** [comment]
== 嗯，官方文档没看见这条命令呢。

**Comment by leesei** [comment]
這個是npm 基本，跟hexo 無關呢
