### ISSUE TITLE
部署时卡顿在 hexo g 上,等了好久,还是没反应

### ISSUE THREAD

**Issue by susuyan** [hexojs/hexo#1184]
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Hexo version: \u001b[35m3.0.0\u001b[39m","time":"2015-04-08T02:47:45.982Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Working directory: \u001b[35m~/hexo/\u001b[39m","time":"2015-04-08T02:47:45.988Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Config loaded: \u001b[35m~/hexo/_config.yml\u001b[39m","time":"2015-04-08T02:47:46.096Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-deployer-git\u001b[39m","time":"2015-04-08T02:47:46.221Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-archive\u001b[39m","time":"2015-04-08T02:47:46.497Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-category\u001b[39m","time":"2015-04-08T02:47:46.497Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-index\u001b[39m","time":"2015-04-08T02:47:46.497Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-tag\u001b[39m","time":"2015-04-08T02:47:46.497Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-ejs\u001b[39m","time":"2015-04-08T02:47:46.497Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-marked\u001b[39m","time":"2015-04-08T02:47:46.498Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-stylus\u001b[39m","time":"2015-04-08T02:47:46.498Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-server\u001b[39m","time":"2015-04-08T02:47:46.498Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":843,"level":20,"msg":"Database saved","time":"2015-04-08T02:47:46.503Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Hexo version: \u001b[35m3.0.0\u001b[39m","time":"2015-04-08T02:49:25.473Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Working directory: \u001b[35m~/hexo/\u001b[39m","time":"2015-04-08T02:49:25.478Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Config loaded: \u001b[35m~/hexo/_config.yml\u001b[39m","time":"2015-04-08T02:49:25.585Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-deployer-git\u001b[39m","time":"2015-04-08T02:49:25.715Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-archive\u001b[39m","time":"2015-04-08T02:49:25.715Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-category\u001b[39m","time":"2015-04-08T02:49:25.975Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-tag\u001b[39m","time":"2015-04-08T02:49:25.976Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-index\u001b[39m","time":"2015-04-08T02:49:25.976Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-marked\u001b[39m","time":"2015-04-08T02:49:25.976Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-ejs\u001b[39m","time":"2015-04-08T02:49:25.976Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-stylus\u001b[39m","time":"2015-04-08T02:49:25.976Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-server\u001b[39m","time":"2015-04-08T02:49:25.976Z","v":0}
{"name":"hexo","hostname":"sanmy","pid":850,"level":20,"msg":"Database saved","time":"2015-04-08T02:49:25.982Z","v":0}

**Comment by iqiancheng** [comment]
run `` hexo clean `` before

**Comment by susuyan** [comment]
还是不可以,我在输 hexo g , hexo s , hexo d 这几个命令的时候,就是卡顿那不动没反应,刚开始用的时候没什么问题,最近这些天才出现这种问题

**Comment by Xuanwo** [comment]
按照最近讨论的一些帖子，你检查一下是不是自己文章里面有很多`----`这样的符号或者有超长的代码块。

**Comment by susuyan** [comment]
嗯,的确,我文章里有较多代码块,那该怎么解决,接下来

**Comment by Xuanwo** [comment]
https://github.com/hexojs/hexo/issues/1148#issuecomment-88437004

**Comment by susuyan** [comment]
Thanks , 就是这个文章里的东西问题

**Comment by Xuanwo** [comment]
(⊙o⊙)…，解决了就close吧~
