### ISSUE TITLE
Hexo generate is very slowly

### ISSUE THREAD

**Issue by MengJueM** [hexojs/hexo#1187]
Backgrounds:
- 4 articles inside _posts
- win 7 (AMD64)
- 8 GB RAM
- i5 CPU

Run `hexo generate` will be stuck on blank command window for almost 2 minutes, and there is no any log output too.

But checking the output after `hexo generate` is done, I can see the generate time is normal without any issue:

```
INFO  64 files generatd in 1.24 s
```

**Comment by Xuanwo** [comment]
目前得出的结论是因为highlight挂掉了- -，只要去除自己代码中`----`以及很长的单行代码就能解决

**Comment by wzpan** [comment]
You may take a look at this solution: [Speed Up the Rendering Process of hexo 3](http://hahack.com/codes/hexo-3-speed-up/)
