### ISSUE TITLE
Cannot find module...

### ISSUE THREAD

**Issue by allengaller** [hexojs/hexo#1188]
Hi Hexo

My Hexo works find on my Ubuntu, but when I use any Hexo command on Mac with the SAME project, this keeps showing up:

{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

But Hexo still works...

Allen

**Comment by Xuanwo** [comment]
并没有遇到过- -，全新安装一次hexo试试看？

**Comment by leesei** [comment]
See [#1326 Mac `--no-optional`](https://github.com/hexojs/hexo/issues/1326)
