### ISSUE TITLE
How to customize post URL

### ISSUE THREAD

**Issue by allengaller** [hexojs/hexo#1189]
Hi Hexo

I just go through all the doc of Hexo, still can not find about:

how to user permalink and not using the Date as URL path?

For example:
Now I have this post:
http://0.0.0.0:4000/2015/04/10/php-res/
and the post:
title: "PHP Resources"
date: 2015-04-10 16:46:12
permalink: php-res
tags:
- res
categories:
- php
---

BUT I want have this URL:
http://0.0.0.0:4000/php/php-res/

I really have no idea how to do it, after I read all the doc...

Please help.

Thanks.

Allen

**Comment by Nerom** [comment]
in `_config.yml` change the `permalink` value

**Comment by allengaller** [comment]
@Nerom like this:

permalink: :category/:title

I just tried, but it doesn't work.

Any idea?

**Comment by Xuanwo** [comment]
try`permalink: :category/:title/`
I don't know, it seems like that the feature is broken in new version

**Comment by Xuanwo** [comment]
我后来测试了一下，成功了！

正确的配置为：`permalink: :category/:title/`

最后的效果为：
![image](https://cloud.githubusercontent.com/assets/5351546/7092559/6cd862b6-dfe5-11e4-8ff6-07fb87e2933a.png)

**Comment by allengaller** [comment]
@Xuanwo It works! Thanks!
Mine is http://0.0.0.0:4000/mobile/ios/ios-res/, and it works just fine!
