### ISSUE TITLE
What's the code for English in language settings?

### ISSUE THREAD

**Issue by allengaller** [hexojs/hexo#1190]
I see Chinese is zh-hans, what about english?
I already tried en-US, doesn't work.

**Comment by Xuanwo** [comment]
dafault?

**Comment by allengaller** [comment]
dafault means Simplified Chinese in Hexo... 
@Xuanwo
I also tried en, donesn't work.

**Comment by laughinging** [comment]
Hi, you should change to:
language: default
@allengaller

**Comment by tommy351** [comment]
There's no default language in Hexo. It's depend on the theme you are using.

**Comment by t1nkerduck** [comment]
Is there an answer to this?  Also looking for the English code for language: in the _config file.  Language code strings really should be documented on hexo's website.

**Comment by MichaelJCole** [comment]
Get the theme.  Look in the `languages` folder.  Every .yml file is a language option.  Set `language` in `_config.yml` to the language you prefer.
