### ISSUE TITLE
pacman主题语法不能高亮

### ISSUE THREAD

**Issue by neo-v** [hexojs/hexo#1191]
页面code代码语法不能高亮。修改了配色也是一样。没有效果，完全灰色的。
只有缩进和line number。
是我配置出了问题吗？求教。谢谢

**Comment by Xuanwo** [comment]
这个应该反馈到pacman主题的库中~

**Comment by wuchong** [comment]
检查下你的使用姿势

1 代码高亮要用 \``` 包围代码块，而不是 tab
2. 高亮某种语言请用 \```cpp 指定语言

**Comment by neo-v** [comment]
@wuchong 我用的是{% ...%}的方法。
```cpp举个例子？谢谢

**Comment by neo-v** [comment]
@Xuanwo 谢谢。是true

**Comment by neo-v** [comment]
@wuchong 谢谢。我用的是{%..%}的方法
```cpp能举个例子吗。

**Comment by xingoxu** [comment]
@Xuanwo @wuchong 相同的问题，
![20150417083359](https://cloud.githubusercontent.com/assets/8542907/7194141/98da7858-e4dc-11e4-8f7c-74f7961e89b6.png)
出来的结果却是https://blog.xingoxu.com/2015-04/Algorithm-Homework-6-30.html
没有格式，只有缩进与line number

**Comment by xingoxu** [comment]
看了一下，style.css里面没有.highlight的样式，是编译的时候没编译进去还是？

**Comment by wuchong** [comment]
pacman不支持3.0，你可以尝试下jacman

发自我的 iPhone

**Comment by lzjqsdd** [comment]
这个主题在代码中是有分析代码高亮的，默认配置文件中没有，在主题的_config.yml最后加上：
highlight:
enable: true

**Comment by lzjqsdd** [comment]
另外，hexo的_config.yml中的highlight中的enable也要设置为true；

**Comment by xingoxu** [comment]
@lzjqsdd 有效，但既然pacman不支持3.0决定尝试试试jacman，非常感谢

**Comment by Nerom** [comment]
@xingoxu pacman支持3.0的吧，我现在用的就是，木有问题的

**Comment by leesei** [comment]
pacman 問題請報pacman, 沒有問題請關掉。

**Comment by tashanzhishi** [comment]
lzjqsdd说的不错，要在pacman中的_config.yml后面加入
highlight:
enable: true

**Comment by Markliang1994** [comment]
本地高亮，github不高亮 怎么破？

**Comment by JonyFang** [comment]
pacman 代码高亮测试出现没有边框的问题 
![image](https://cloud.githubusercontent.com/assets/12381169/14950928/0fdc8de2-1088-11e6-965f-f1b50beb07de.png)

**Comment by leesei** [comment]
pacman 問題請報pacman
