### ISSUE TITLE
新弄了一个主题求官网收录😄

### ISSUE THREAD

**Issue by jaywcjlove** [hexojs/hexo#1193]
GitHub：[hexoThemeKacper](https://github.com/jaywcjlove/hexoThemeKacper)  
主题预览：[JSLite.io](http://JSLite.io)

**Comment by leesei** [comment]
Thanks.
Please follow the instruction [here](http://hexo.io/docs/themes.html#Publishing) and submit a PR.

**Comment by jaywcjlove** [comment]
Thanks. Ready to Pull requests 😄

**Comment by Xuanwo** [comment]
I saw your PR had been merged, so ,please close this issues, thanks~

**Comment by Nerom** [comment]
already added

**Comment by Nerom** [comment]
already added
