### ISSUE TITLE
Some JavaScript assets are being rendered as pages

### ISSUE THREAD

**Issue by ntrrgc** [hexojs/hexo#1194]
Create a public JavaScript asset in `source`, e.g: `source/demo/test.js` with the following content:

    var elem = '<output/>'

If you access the resource in hexo (e.g. `http://localhost:4000/demo/test.js`) this is the code you will find:

    var elem = '<output/>'
    </output>

Which is clearly wrong. `.js` files should never be rendered as pages (and thus mangled on HTML tags). After inspecting Hexo's code I have found there is a `skip_render` setting to tell Hexo what files should not be rendered but it is empty by default.

As a workaround I have added the following to my `_config.yml`:

    skip_render:
     - '**/*.js'

**Comment by leesei** [comment]
See #1119 and #1146.
