### ISSUE TITLE
How to use i18n?

### ISSUE THREAD

**Issue by ntrrgc** [hexojs/hexo#1195]
I have read http://hexo.io/docs/localization.html and followed the steps mentioned: 
- Add a list of languages, being the first the default one.
- Create a `themes/<my theme>languages` folder.
- Create a `themes/<my theme>languages/<my lang>.yml` file with a strings dictionary.
- Use `__()` for translations.

Yet it looks like it is not enough. No language folders are created when I run `hexo generate` and `__()` calls return untranslated strings. No errors are shown in the console either. What am I missing?

**Comment by ntrrgc** [comment]
I was placing the `__()` calls in the wrong objects. Now they work, although language folders are still not being created and I don't know how to write a translated post. Is it explained anywhere?

**Comment by Xuanwo** [comment]
@ntrrgc take a look at https://github.com/hexojs/site
