### ISSUE TITLE
如何调整Hexo语言为英文?

### ISSUE THREAD

**Issue by allengaller** [hexojs/hexo#1198]
Hexo, hi

我已经在配置文件中尝试了default, en, en-UA 均无法实现英文显示

**Comment by Xuanwo** [comment]
我去看了一下你的博客，使用的主题是https://github.com/iissnan/hexo-theme-next吧？
根据作者发布的[wiki](https://github.com/iissnan/hexo-theme-next/wiki/%E8%AE%BE%E7%BD%AE%E8%AF%AD%E8%A8%80)，只要设置为default即可。

*这种问题其实跟Hexo并没有什么关系- -，是跟主题相关的。*
