### ISSUE TITLE
Blockquote rendered incorrectly

### ISSUE THREAD

**Issue by tparvi** [hexojs/hexo#1199]
I just installed the latest version (3.0.1) into a fresh directory and wrote the following into the default Hello world post:

    {% blockquote %}
    Testing
    {% endblockquote %}

The blockquote seems to produce strange results. Example: http://imgur.com/MLWVaxb (red rectangle is just there to point out the issue). Large font and text is horizontally aligned. Is this how it should look with the default template?

**Comment by tommy351** [comment]
It's depend on the theme. Blockquote displays like this in the default theme.

**Comment by tparvi** [comment]
Ok. Initially I had pretty long quote and it looked funny when font size was large and everything was horizontally aligned. I'm closing this since that is the way theme displays them.
