### ISSUE TITLE
请问什么时候支持下org-mode？

### ISSUE THREAD

**Issue by dreamer-yzy** [hexojs/hexo#1200]
用Emacs写org-mode生成的markdown文件与hexo deploy时有非常大的出入，比如table，在hexo里显示完全不正常，请问下有没有打算支持下org-mode？

**Comment by Xuanwo** [comment]
这并不是知不知处org-mode的问题- -，table的支持一直有问题。。。

**Comment by hcoona** [comment]
可以用 org-mode 生成出来 html 放在 _post 里

**Comment by hcoona** [comment]
或者自己写 renderer，来自动生成……这个貌似比较难，我正在看怎么支持 asciidoc

**Comment by CodeFalling** [comment]
我写了个支持orgmode的renderer.可以试试
https://github.com/CodeFalling/hexo-renderer-org

**Comment by Xuanwo** [comment]
@CodeFalling 已经合并到site了~

**Comment by leesei** [comment]
@CodeFalling  :+1: 
先關閉了。
