### ISSUE TITLE
Processing markdown URLs with parentheses

### ISSUE THREAD

**Issue by Hunter-Github** [hexojs/hexo#1205]
I have an URL like this: http://example.com/3(12).pdf . How do I cite it?

GitHub's Markdown engine processes the following example [correctly](http://example.com/3(12).pdf)

     [example](http://example.com/3(12).pdf)

...but understandably [chokes](http://example.com/312).pdf) at the following:

     [example](http://example.com/312).pdf)

Hexo doesn't generate the first example in the correct way.

What are the workarounds? (perhaps with asset-tags etc.)

**Comment by tommy351** [comment]
Maybe you can try the `link` tag.
http://hexo.io/docs/tag-plugins.html#Link

**Comment by celsomiranda** [comment]
@Hunter-Github, you can try using `hexo-renderer-markdown-it` instead of the default `hexo-renderer-marked` (Shameless plug). 

Be sure to read the documentation and set it up for your needs.

**Comment by Hunter-Github** [comment]
@tommy351 - `link` tag works for the general (unmatched ) ) case , however @celsomiranda 's drop-in replacement doesn't require extra mental strain for the (matched parentheses), and is a bit more intuitive.
