### ISSUE TITLE
is_post() always return true when permalink is `:title/`

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1206]
http://hexo.io/docs/helpers.html#is_post

I believe `is_post()` should return true only if we are at a page rendered from `source`.

But if we set  
```yaml
permalink: :title/
```
then the regex in `is_post()`(lib/plugins/helper/is.js#L40-58) is [`/[^\/]+\//`](http://jex.im/regulex/#!embed=false&flags=&re=%5B%5E%5C%2F%5D%2B%5C%2F)
which yields true for practically all URLs with trailing `/` (including `/tags/foo`).

Is this a bug or by design?

**Comment by iissnan** [comment]
It should be a bug.

**Comment by maroun-baydoun** [comment]
Having similar issue. I used the ```is_post()``` helper function in my layout to change some styling, but all the generated html files were treated as if ```is_post()``` is true, even home page, categories page...

**Comment by leesei** [comment]
This should be fixed by commit 62f521b.
