### ISSUE TITLE
hexo初始化后npm install出错。

### ISSUE THREAD

**Issue by geekrainy** [hexojs/hexo#1208]
npm ERR! fetch failed https://registry.npm.taobao.org/nunjucks/download/nunjucks
-1.3.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 404

**Comment by Xuanwo** [comment]
大概。。你不应该用taobao的源？

**Comment by geekrainy** [comment]
我换用cnpm的源也是一样的问题，可以安装hexo，但就是初始化后安装依赖模块出错。

**Comment by Xuanwo** [comment]
https://github.com/npm/npm/issues/7797

可能是hexo的某些模块不支持高版本的nodejs，试试v10看看呢？或者用iojs看看？
网上关于这个问题的反馈基本上就两种，第一是版本问题，第二是代理问题。

**Comment by geekrainy** [comment]
试过了，使用10.36版node也出错，使用iojs也是出错。*——*

**Comment by geekrainy** [comment]
已解决，无关版本和代理，应该是官方源的问题，现在已OK。
