### ISSUE TITLE
BUG: _config.yml 中的 marked 配置无效，从源码角度发现

### ISSUE THREAD

**Issue by bubkoo** [hexojs/hexo#1216]
首先，在 [node_module/hexo/lib/hexo/post.js](https://github.com/hexojs/hexo/blob/master/lib/hexo/post.js#L309) 文件的 [309](https://github.com/hexojs/hexo/blob/master/lib/hexo/post.js#L309) 行有如下代码：

```javascript
    var options = data.markdown || {};
    if (!config.highlight.enable) options.highlight = null;

    // Render with markdown or other renderer
    return ctx.render.render({
      text: data.content,
      path: source,
      engine: data.engine,
      toString: true,
      onRenderEnd: tagFilter
    }, options);
```

我对上面代码的理解是，从文件的元数据 `data` 中获取到 markdown 渲染时需要的 `options`，这个 `options` 应该是从 `_config.yml` 文件中的 `marked` 配置节与内部默认的选项 merge 之后得到的。

然后，我来说说为什么 `marked` 这个配置无效了。

在 `Box` 中对 `source` 文件夹中的文件进行处理时相关代码是 [node_module/hexo/lib/plugins/processor/post.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/post.js#L61)，在这里有一个方法 [`processPost`](https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/post.js#L61)，该函数对文件的元数据进行了详细的分析，最后插入或更新到 `db.json` 中。但是，就是在这个函数中，没有将
`marked` 配置项保存，导致该配置项在上面的方法中获取不到。

解决方案：

1、在 [`processPost`](https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/post.js#L61) 方法中添加如下代码：

```javascript
data.markdown = config.marked;
```

2、`options` 直接从 `config` 中读取，不需要从文件的元数据 `data` 中获取，因为这个配置项大家是共享的，没必要都保存在文件的元数据中。

**这个 Bug 是经过我调试后发现，如果分析错误，请作者(@tommy351)指出我的疏忽指出。**

**Comment by bubkoo** [comment]
ping...

**Comment by tommy351** [comment]
This is not a bug. `data.markdown` is file-specific markdown settings.

**Comment by bubkoo** [comment]
So, when and where the config section `marked` in the  `_config.yml` file be used.

**Comment by tommy351** [comment]
`config.marked` is used in renderer.
https://github.com/hexojs/hexo-renderer-marked/blob/master/lib/renderer.js#L55

**Comment by bubkoo** [comment]
I get it.

close #1216
