### ISSUE TITLE
npm WARN optional dep failed, continuing fsevents@0.3.5

### ISSUE THREAD

**Issue by darwinairola** [hexojs/hexo#1219]
When I execute "npm install -g hexo-cli," I see the following warning on Windows 8.1, 64bit: npm WARN optional dep failed, continuing fsevents@0.3.5.

I also see this warning when I do a "npm install" in a newly initialized website.

**Comment by naokiy** [comment]
I think this is problem of 'fsevents' package.
According to the issue of fsevents, we can ignore it. 

please check this ... https://github.com/strongloop/fsevents/issues/37 .

**Comment by unstephenk** [comment]
I'm getting this error too.

**Comment by tommy351** [comment]
It's just a warning. It doesn't matter.

**Comment by xiyouMc** [comment]
Its just a warning .

**Comment by Tbeating** [comment]
bad!  but I can't use hexo

**Comment by NoahDragon** [comment]
@Tbeating Could you please open a new issue to elaborate the problem?
