### ISSUE TITLE
请问tagcloud的orderby都有哪些参数？

### ISSUE THREAD

**Issue by heartnn** [hexojs/hexo#1220]
除了默认的name和random，有无可能按照使用频率来排序。

**Comment by bubkoo** [comment]
从哪里得来使用频率的数据？貌似不可以。

**Comment by heartnn** [comment]
因为发现可以在tagcloud中显示标签大小，越常用的标签越大，另外原来有一个网友做的插件是可以实现最长使用的多少个标签排列。

**Comment by Xuanwo** [comment]
就是按照这个标签的文章数排序，可以的。

**Comment by tommy351** [comment]
Try `length`. It means the number of posts.

**Comment by bubkoo** [comment]
标签大小是通过标签数量确定的

**Comment by heartnn** [comment]
我是这样写的
<%- tagcloud(site.tags, {amount: 30, orderby: length}) %>
但是会报错，语法有问题吗？

提示length is not defined

**Comment by heartnn** [comment]
<%- tagcloud(site.tags, {amount: '30', orderby: 'length', order: '-1'}) %>

这样写完后生成的html中font size显示NaNpx，不知道是哪里错了

**Comment by naokiy** [comment]
If each tag that are shown in tag cloud has same count of items, font-size will be broken.
This is a known bug. (But the fixation is not released yet.) 

Please check #1123 and #1202 . And make sure your case is matched to this bug.

**Comment by heartnn** [comment]
感谢，明白怎么回事了，请关闭这条issue吧。
