### ISSUE TITLE
Provide an option to disable code highlighting auto-detect lacking `lang`

### ISSUE THREAD

**Issue by hcoona** [hexojs/hexo#1224]
Hi Sir,

I want an option to disable auto code highlighting, because I want the default behavior is not to highlight my quote blocks in my migrated articles. They are previously written in markdown language in Jekyll. The default behavior changed. I have to modify each blocks to add 'lang=plain' to avoid wrong highlighting. This block me from switching to the great hexo.

Thanks!

**Comment by tommy351** [comment]
Edit `_config.yml`.

``` yaml
highlight:
  enable: false
```

http://hexo.io/docs/configuration.html#Writing

**Comment by hcoona** [comment]
Hi @tommy351 ,

Thanks for your answer. However I think it means not to highlight any blocks, that's not what I want.

I want to control the default behavior if there is no `lang` assigned to a code block. Currently hexo would make it auto-detect. I want to make it do not auto-detect and just make it `plain`.

Thanks.

**Comment by tommy351** [comment]
I see. Hexo doesn't provide this option so far.

**Comment by hcoona** [comment]
I modified the title to make it clearer.

**Comment by tommy351** [comment]
Would be great to have this feature. Highlight.js is slow in auto detection.

**Comment by hcoona** [comment]
Please consider to make it with high priority :)
It's not hard to add this option. Thanks!

**Comment by iissnan** [comment]
Seems users need to add `auto_detect: true` to `_config.yml` manually when upgrading to 3.1.1, or else this option will be off by default.

**Comment by leesei** [comment]
Try using `plain`
<pre>
```plain
```
</pre>
