### ISSUE TITLE
hexo server almost can't open on MAC 10.10, only see the title display...

### ISSUE THREAD

**Issue by lin2280778** [hexojs/hexo#1225]
I have MC OSX 10.10 yosemite
installed hero using homebrew, everything is fine and I can run sodu hexo server, and it shows Hexo is running at http://0.0.0.0:4000/.
when I try http://0.0.0.0:4000/ or localhost:4000 in safari, it displays only the title of website.
and I use hero server -l to see log. here is it, then it stops here forever....
GET / 200 70.652 ms - -
GET /css/style.css 200 918.672 ms - -
GET /js/script.js 200 7.822 ms - -
GET /fancybox/jquery.fancybox.pack.js 200 9.203 ms - -
GET /fancybox/jquery.fancybox.css 200 10.589 ms - -
GET /css/images/banner.jpg 200 13.708 ms - -
GET /css/fonts/fontawesome-webfont.woff?v= 200 4.647 ms - -
GET / 200 15.021 ms - -
GET /css/style.css 200 223.977 ms - -
GET /fancybox/jquery.fancybox.css 200 6.166 ms - -
GET /js/script.js 200 5.102 ms - -
GET /fancybox/jquery.fancybox.pack.js 200 7.150 ms - -

**Comment by leesei** [comment]
Can you post your repo?

**Comment by lin2280778** [comment]
it's the connection problem to google font.    fixed by using proxy.   thanks
