### ISSUE TITLE
Hexo renders code incorrectly

### ISSUE THREAD

**Issue by donniev** [hexojs/hexo#1230]
blog.vawter.com (Generators and promises).

Runs text and code together ignoring end of code block.

Renders fine in Webstorm, MacDown, Bitbucket but not in hexo.
Code:
http://pastebin.com/Q9vaHXf8

**Comment by tommy351** [comment]
![screenshot-localhost 4000 2015-04-26 12-52-08](https://cloud.githubusercontent.com/assets/411425/7335940/20b35b54-ec13-11e4-87ae-ff1bd7002518.png)

It works properly on Hexo 3.0.1.

**Comment by donniev** [comment]
Indeed it does. Thank you for your help.
