### ISSUE TITLE
update 3.0.1

### ISSUE THREAD

**Issue by pengloo53** [hexojs/hexo#1231]
![2015-04-26 13 03 52](https://cloud.githubusercontent.com/assets/5508125/7336053/d2134f74-ec1a-11e4-9599-15ebad60d834.png)

why always show me this message? 

My system: OS X 10.10

**Comment by Xuanwo** [comment]
reinstall hexo may be helpful

**Comment by pengloo53** [comment]
I hava reinstalled many times ,  it still show me that message , but hexo can work just report that message.

**Comment by leesei** [comment]
Remove 'node_modules' and `npm install hexo --no-optional`
#1326
