### ISSUE TITLE
[Feature]Add option to force regenerate

### ISSUE THREAD

**Issue by hcoona** [hexojs/hexo#1233]
Hi Sir,

I'd like an option to indicate force site regeneration. Sometimes I upgrade a new version of renderer plugins, this would lead to regenerate all related posts. However the command `hexo g` would not regenerate them now.

**Comment by tommy351** [comment]
You mean something like `--force` flag?

**Comment by hcoona** [comment]
Exactly. I don't want to delete the `public` folder and then run `hexo g` by manual.

**Comment by hcoona** [comment]
Greate!
