### ISSUE TITLE
Helper is_post() not validating for permalink with language

### ISSUE THREAD

**Issue by ahaasler** [hexojs/hexo#1236]
Hi,

I was testing a theme I'm making with multilingual support and I realized that the helper `is_post()` is not working properly when the post's permalink contains `:lang`.

I've seen this behavior with `:lang/:category/:title/`.

I'm already fixing it in a fork and I'll send a pull request when it's properly tested. This issue has been opened to keep things tidy and well tracked.

Thanks!

**Comment by Xuanwo** [comment]
@ahaasler  It looks like to be fixed by https://github.com/hexojs/hexo/commit/62f521b32b7e750d88a8e3207278c0f5b1c14fdf

**Comment by ahaasler** [comment]
That's correct, the helper has resolved this with the help from the post generator.
