### ISSUE TITLE
[Question]Does the date shown in posts display in UTC time?

### ISSUE THREAD

**Issue by hcoona** [hexojs/hexo#1239]
I write a post with date set to `2015-04-28 00:00:00`, and then `hexo g`. The post is shown that the date is `2015-04-27` however. Is it mean that it is using UTC time? How to adjust it with timezone?

**Comment by tommy351** [comment]
Modify `_config.yml`.

``` yaml
timezone: UTC
```

**Comment by hcoona** [comment]
I checked the `_config.yml`, the timezone is already set to Asia/Hong_Kong.
`timezone: "Asia/Hong_Kong"`

**Comment by leesei** [comment]
I have the same timezone setting and I cannot reproduce the issue.

**Comment by Xuanwo** [comment]
Closed for invalid.
