### ISSUE TITLE
关于scaffolds

### ISSUE THREAD

**Issue by InfoGeeker** [hexojs/hexo#1240]
问下，怎么在scaffolds下的模板文件中获取post的地址, 比如我要写一个

 (转载文章请注明原文出处 XXX的博客) 

XXX的博客是超链接到本文的链接，有获取本文链接的参数吗 ？

**Comment by tommy351** [comment]
不可能在 scaffold 中獲取連結，你可以寫在主題裡

**Comment by InfoGeeker** [comment]
@tommy351 在主题中用什么参数获取？

**Comment by tommy351** [comment]
http://hexo.io/docs/variables.html
