### ISSUE TITLE
[Feature]Add default value in front matter when creating new post

### ISSUE THREAD

**Issue by hcoona** [hexojs/hexo#1241]
I want the date field be auto-generated when creating new post via `hexo new post post-name`.

**Comment by celsomiranda** [comment]
It should be. What's the contents of `post.md` inside the `scaffolds` folder?

I normally call `hexo new post "Post Name" ` from the command line and it does auto populate the date value.

**Comment by Xuanwo** [comment]
you can modify your scaffolds

**Comment by hcoona** [comment]
Date time should be current time with in locales according to the config,
which cannot be assigned in a static template.

2015-05-15 10:04 GMT+08:00 漩涡 <notifications@github.com>:
