### ISSUE TITLE
关于日期的判定问题

### ISSUE THREAD

**Issue by geekrainy** [hexojs/hexo#1243]
已设置
```
timezone: Asia/Shanghai
```
文档说明没有设置会使用电脑时区，但这两种情况都导致文章日期不对。仍旧使用UTC标准时间来判定日期。00.00-08.00之前的文章会归为前一天。

**Comment by tgmerge** [comment]
遇到了相同的问题，不过不是Hexo的，而是主题（NexT）的。

我在NexT主题那里开了issue：https://github.com/iissnan/hexo-theme-next/issues/181 ，说不定有帮助？

**Comment by Xuanwo** [comment]
Any update?

**Comment by iissnan** [comment]
Fixed. Please close this issue. 

Thanks.

**Comment by Xuanwo** [comment]
@iissnan nice work for Next~
