### ISSUE TITLE
a warning (or error message?) in iojs-v1.8.1

### ISSUE THREAD

**Issue by gejiawen** [hexojs/hexo#1253]
there is a warning(error?) message when execute hexo command, as follow image,

![image](https://cloud.githubusercontent.com/assets/1721331/7451033/31f3b76c-f27e-11e4-8293-219bb5cfed5c.png)

the environment is,

![image](https://cloud.githubusercontent.com/assets/1721331/7451058/8eb6824a-f27e-11e4-837f-103fbee1027a.png)

**Comment by Xuanwo** [comment]
If you can use hexo normally, let it go.
