### ISSUE TITLE
3.0 deploy的老问题 - ERROR Deployer not found: git

### ISSUE THREAD

**Issue by thekaka** [hexojs/hexo#1255]
1. 已经用了 npm install hexo-deployer-git
2. github修改为git
3. 已经注意空格问题
4. git安装无误

仍然报错 ERROR Deployer not found: git

	
	# Deployment
	## Docs: http://hexo.io/docs/deployment.html
	deploy:
 	  type: git
  	  repository: git@github.com:thekaka/thekaka.github.io.git
  	  branch: master

**Comment by Xuanwo** [comment]
`npm install hexo-deployer-git --save`

**Comment by iqiancheng** [comment]
```
npm install hexo-deployer-git --save
```

**Comment by thekaka** [comment]
THX!

Problem fixed.
