### ISSUE TITLE
hexo deploy error: spawn git ENOENT

### ISSUE THREAD

**Issue by 4disland** [hexojs/hexo#1256]
Error details:
![default](https://cloud.githubusercontent.com/assets/6065941/7492579/dadf0e18-f42b-11e4-8fcd-d81c8820e077.PNG)
and my _config.yml:
deploy:
  type: git
  repo: https://github.com/4disland/4disland.github.io.git
  branch: master

**Comment by Xuanwo** [comment]
检查一下你的Git设置
