### ISSUE TITLE
No layout : index.html

### ISSUE THREAD

**Issue by FrankBian** [hexojs/hexo#1261]
I run the command as below : 

    hexo generate
    hexo server

and then nothing to show after I open it in localhost:4000 , the terminal info is : 

    WARN No layout :  index.html

How can I fix it ?  I'm a new to it

**Comment by hellomiao** [comment]
perhaps hexo clean and hexo d -g

**Comment by leesei** [comment]
Any updates?

**Comment by EvanCarroll** [comment]
Having this problem too...

**Comment by leesei** [comment]
See #1550
