### ISSUE TITLE
node-gyp rebuild

### ISSUE THREAD

**Issue by c3113** [hexojs/hexo#1262]
> fsevents@0.3.6 install /usr/local/lib/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

在安装的时候只执行到这里，不再向下执行了

**Comment by leesei** [comment]
Are you using Mac?
If so, also try [`--no-optional`](https://github.com/hexojs/hexo/issues/1326) for the npm install.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
