### ISSUE TITLE
URIError：URI malformed 

### ISSUE THREAD

**Issue by codingbubble** [hexojs/hexo#1264]
昨天还是好的，今天突然出现了这个，完全没有头绪如何解决！
![](http://ww2.sinaimg.cn/large/0067jhJ4gw1erzi5nln7aj30i60ei0wh.jpg)

**Comment by Xuanwo** [comment]
google了一下，大概是GBK编码的问题？

**Comment by leesei** [comment]
Please open new issue if problem persists.
