### ISSUE TITLE
In china,i can't visit http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js how can i do?

### ISSUE THREAD

**Issue by yanliqing** [hexojs/hexo#1265]
when i upgrade hexo ,there is something wrong with my website. 
Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js

**Comment by herro-chen** [comment]
http://cdn.bootcss.com/jquery/2.0.3/jquery.min.js

**Comment by yanliqing** [comment]
@herro-chen 你的意思是我直接本地改然后发布？

**Comment by herro-chen** [comment]
是的

**Comment by Xuanwo** [comment]
用一个国内的CDN就可以

**Comment by yanliqing** [comment]
@herro-chen 好麻烦

**Comment by yanliqing** [comment]
@herro-chen 在哪里改？直接在html改generate之后又变成原来的地址了，这个地址是配在哪里的？

**Comment by yanliqing** [comment]
@herro-chen 找到了

**Comment by iamlucky** [comment]
方便一下像我一样的新手:
用关键字grep一下jquery.min.js，可以发现用到的几个地方替换一下国内CDN
