### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by LucasZheng** [hexojs/hexo#1267]
When I run `hexo server`, the console has no error. But when I navigate to 'http://localhost:4000', the console reports below errors:
    Unhandled rejection Error
        at new Parser (/Users/lucas/github_lucas/blog/node_modules/hexo-renderer-less/node_modules/less/lib/less/parser.js:333:27)
        at Hexo.<anonymous> (/Users/lucaszheng/github_lucas/blog/node_modules/hexo-renderer-less/index.js:11:16)
        ......
I had updated hexo to 3.0.0. How to fix this issue?

**Comment by Xuanwo** [comment]
updae hexo to 3.1.1, and run `npm update`, the `hexo-renderer-less` may be ou of date.

**Comment by leesei** [comment]
Any update?

**Comment by LucasZheng** [comment]
I had replaced another theme which support hexo 3.0.0, it's no problem now.

**Comment by leesei** [comment]
Great

**Comment by johnsington** [comment]
Hey LucasZheng, I am running across the same issue when I switch to a new theme 'hexo-jade-barebone'. How were you able to fix the problem?

**Comment by LucasZheng** [comment]
Hey @johnsington, I just replaced a new theme of [pacman](https://github.com/A-limon/pacman), you can try it if you like.
