### ISSUE TITLE
使用ftpsync只能上传文件夹不能上传所有的文件

### ISSUE THREAD

**Issue by Witype** [hexojs/hexo#1269]
在使用ftpsync的时候，只上传文件夹而没有上传文件。
文件夹内都是空的。

**Comment by Nerom** [comment]
verbose设置成true，输出内容是什么呢，记得把你账号内容删掉 发自网易邮箱大师 在2015年05月15日 11:53 ，WiType716写道： 在使用ftpsync的时候，只上传文件夹而没有上传文件。 文件夹内都是空的。 — Reply to this email directly or view it on GitHub.

**Comment by Witype** [comment]
错误提示为：
Error: read ECONNRESET
    at exports._errnoException(util.js.746:11)
    at TCP.onread(net.js:559:26)

**Comment by Witype** [comment]
上传的进度一直卡着
Remove:
[ '/logreport/no_delete' ]

Consolidation complete.

Committing
-------------------------------------------------------------
- /fonts/icon-feather/icomoon.ttf uploaded successfuly
- /fonts/icon-feather/icomoon.woff uploaded successfuly

**Comment by Xuanwo** [comment]
检查一下FTP权限呢？

**Comment by Xuanwo** [comment]
@Witype Fixed?

**Comment by Xuanwo** [comment]
This issue was moved to hexojs/hexo-deployer-ftpsync#9
