### ISSUE TITLE
can't use a layout if theme is set to false

### ISSUE THREAD

**Issue by PJL101** [hexojs/hexo#1271]
Hi,

I can't seem to make hexo recognise a layout when theming is set to false. Is there an example of how hexo is supposed to work when theme: false

**Comment by leesei** [comment]
Where do you set `theme: false`?
I can't remember such option.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.

**Comment by PJL101** [comment]
Sorry for the delay in replying.

The setting is from: https://hexo.io/docs/configuration.html Under extensions.
