### ISSUE TITLE
use $: hexo g d  can't deploy to server sometimes 

### ISSUE THREAD

**Issue by hongqi** [hexojs/hexo#1272]
rt

**Comment by leesei** [comment]
Will it be network issue?
Do you have a log?

**Comment by Gracker** [comment]
@gaoj ➜  blog  hexo d
INFO  Deploying: git
INFO  Clearing .deploy folder...
INFO  Copying files from public folder...
On branch master
nothing to commit, working directory clean

一直卡在这里，删除.deploy和.cache都没用。。。我是macos 10.11

**Comment by leesei** [comment]
Try running generate first.
```sh
hexo generate
hexo deploy
```

Also can you post your config for deploy?

**Comment by Gracker** [comment]
deploy:
  type: git
  repository: git@github.com:Gracker/Gracker.github.io.git
  branch: master

It still has problem after running generate first:
......
......
create mode 100644 tags/index.html

**Comment by if2e** [comment]
I have the same problem.

**Comment by ch0588** [comment]
I have the same problem.on Mac OS X,when I deploy it stop on "nothing to commit, working directory clean"

**Comment by leesei** [comment]
Did you try `hexo clean` first?

#1272

**Comment by Xuanwo** [comment]
@hongqi Hello, problem still exits?

**Comment by Gracker** [comment]
It‘s OK now!

**Comment by Xuanwo** [comment]
Closed for problem resloved.

**Comment by AntonioShi** [comment]
> It‘s OK now!

please, i have the same problem now.it's terrible.i am upset,could you tell me what should i do?
