### ISSUE TITLE
Question: Change date to English

### ISSUE THREAD

**Issue by FahmiRaazali** [hexojs/hexo#1273]
![language](https://cloud.githubusercontent.com/assets/4865771/7656030/7f556868-fb5a-11e4-8f25-c880818d7bd6.png)

I am working in Cambodia right now. 

I am trying to create simple website with hexo written in English.
When I use "hexo server" the preview of the article is just fine.
But the date is not display in english.

According to google translate the language is in Burmese.
How do I change it to english?

Thank you for helping.

**Comment by Xuanwo** [comment]
modify the language of `_config.yml`
make it looks like `language: en`, the value depend on your theme.
