### ISSUE TITLE
 搭建完github.io访问http://ruijun.github.io出现404错误，页面出现下面这些信息

### ISSUE THREAD

**Issue by ruijun** [hexojs/hexo#1275]
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

怎样解决呢？

**Comment by Xuanwo** [comment]
https://github.com/ruijun/ruijun.github.io
连html页面都没有- -，自然直接返回404 了，你按照教程重新操作吧

**Comment by ruijun** [comment]
@Xuanwo 原来我在搭建的过程中漏了一些步骤了：npm install    hexo g  
现在可以了
