### ISSUE TITLE
使用markdown 语法写文章的一个问题

### ISSUE THREAD

**Issue by tmacychen** [hexojs/hexo#1276]
在一般的markdown的编辑器中，在输入的过程中插入一句代码是这样的```$ git commit```,可以看到能够显示为代码：
- - -
![20150516185221](https://cloud.githubusercontent.com/assets/3626913/7665849/bd2ba844-fbfc-11e4-9221-11a1bdbc8b8c.png)
- - - 
但是在hexo生成的网页中显示错误，hexo将这一句代码认为是代码段的起始，所以另起一行显示：
- - - 
![20150516185125](https://cloud.githubusercontent.com/assets/3626913/7665850/bf93f8c0-fbfc-11e4-945e-44e4a9c86bb3.png)
- - - 
请教解决方法，谢谢

**Comment by Xuanwo** [comment]
单行代码使用``ADBCDEF``

**Comment by tmacychen** [comment]
Thanks
