### ISSUE TITLE
hexo可以实现判断某个分类么？

### ISSUE THREAD

**Issue by naog** [hexojs/hexo#1278]
例如wordpress的is_category()函数可以实现这样的效果：如果是分类A，则显示一段与A相关的简介。
hexo的is_category()辅助函数可以实现么？

**Comment by wudong** [comment]
http://hexo.io/docs/helpers.html#is_category

**Comment by naog** [comment]
hexo的`is_category()`只能判断是否是分类归档页面，而不能判断是某个分类（分类A/分类B）的页面。

**Comment by tommy351** [comment]
You can use `page.category` to get the category name.

**Comment by note4** [comment]
这段代码可以在文章页模板使用，也可以在各列表使用


用分类名称`name`判断，将`像素教程`替换为特定分类名称

```
<% post.categories.forEach(category => { %>
	<% if (category.name == '像素教程') { %>
		这是像素教程的内容
	<% } %>
<% }); %>
```


more:  [Hexo 笔记 | 像素教程 1px.run](https://1px.run/hexo/)
