### ISSUE TITLE
How to exclude certain file types (by extension) in post asset directories from being copied into `public`?

### ISSUE THREAD

**Issue by Hunter-Github** [hexojs/hexo#1279]
There are some kinds of intermediate files that shouldn't be copied into the `public` directory. How can I configure the engine to ignore them?

**Comment by Xuanwo** [comment]
use `skip_render`

you can see my solution:
https://github.com/hexojs/hexo/issues/1146#issuecomment-88380140

**Comment by Hunter-Github** [comment]
The following line doesn't work and crashes the YAML parser:

      skip_render:*/*.dot

**Comment by Xuanwo** [comment]
space
