### ISSUE TITLE
怎样实现hexo d时自动生成CNAME文件？

### ISSUE THREAD

**Issue by CocaCola183** [hexojs/hexo#1283]
把hexo部署到github上并配置域名访问时，需要在项目目录下添加一个CNAME文件，现在我的做法是，`hexo d`，然后打开github上的CocaCola183.github.io项目，手动添加一个CNAME文件，每次deploy都要这么做一遍，请问有什么方法可以实现自动添加呢？

**Comment by bubkoo** [comment]
直接放在 `source` 目录下就可以了，每次都会自动复制过去

**Comment by CocaCola183** [comment]
@bubkoo 非常感谢您的回答，解决了我的问题
