### ISSUE TITLE
如果页面上有table的话，会在前面添加很多br

### ISSUE THREAD

**Issue by dsky1990** [hexojs/hexo#1284]
源码是这样的
![image](https://cloud.githubusercontent.com/assets/1579516/7696933/53c51b34-fe35-11e4-87c4-8391e7ddcdba.png)
但是页面上会出现很多br标签
![image](https://cloud.githubusercontent.com/assets/1579516/7696923/2d359d90-fe35-11e4-9610-ec3606b9d2cb.png)

**Comment by island205** [comment]
+1

**Comment by Xuanwo** [comment]
没看懂- -

**Comment by leesei** [comment]
#1388
