### ISSUE TITLE
Hexo installation fails. OS X 10.9.5.

### ISSUE THREAD

**Issue by Bozh** [hexojs/hexo#1285]
Hi, I've installed all the prerequisite tools but when I input `npm install -g hexo-cli` the following error messages occur:

```
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "hexo-cli"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! path /usr/local/lib/node_modules/hexo-cli
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/hexo-cli' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/hexo-cli' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Bert/npm-debug.log
```

I tried the next step to init a folder, but my terminal says that `hexo: command not found`. 
I'm using `OS X 10.9.5 (Mavericks)`, `git 2.2.1`, `node v0.12.3`, `npm v2.9.1`, `Xcode 6.1`, `CLTools 6.2.0.0.1.1424975374`. Any input will be much appreciated!

**Comment by mlapointe** [comment]
Read your error above:
"Please try running again as root/Administrator"

You need to run the install command again with 'sudo' like so:

$ sudo npm install -g hexo-cli

**Comment by Bozh** [comment]
Hi Mike,
      Thanks for your reply. I’ve already tried that but the problem remains.

**Comment by mlapointe** [comment]
It may help to try node v0.12.0

Node upgrades tend to break things

**Comment by Xuanwo** [comment]
Hexo was pass all the test in node 0.12.4, so the hexo has little posible to have problem.

Maybe you can try this:
https://github.com/npm/npm/issues/6873#issuecomment-66294046

It seems like an issue of npm.
Maybe remove the while nodejs and reinstall it will be helpful.

**Comment by leesei** [comment]
Also try [`--no-optional`](https://github.com/hexojs/hexo/issues/1326) for the npm install.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.

**Comment by Bozh** [comment]
Sorry I was forced to use Windows for the past several months, so I am not able to update my latest try on my Mac. I tried just now, and it magically worked... Sorry for not bringing any new information and the late reply, and thanks again for all your help!
