### ISSUE TITLE
Customize root of blog error in index.html

### ISSUE THREAD

**Issue by wwssllabcd** [hexojs/hexo#1286]
If I used "root: /blog/" in _congig.yml
the generate code of intex.html as fallow
--------------   generate code of intex.html  ------------

	<body>
		<div id="container">
		<div id="wrap">
		<header id="header">
		<div id="banner"></div>
		<div id="header-outer" class="outer">
			<div id="header-title" class="inner">
			<h1 id="logo-wrap">
				<a href="/" id="logo">My Blog title</a>
			</h1>
------------
the question is :

	"  <a href="/" id="logo">My Blog title</a>  " 
should not be "/" 
It should be 

	"  <a href="/blog" id="logo">My Blog title</a>  "  ?

-------------------------- environment --------------
hexo: 3.0.1
os: Windows_NT 6.1.7601 win32 ia32
http_parser: 2.3
node: 0.12.3
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

**Comment by leesei** [comment]
I cannot reproduce the issue.
That theme are you using?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
