### ISSUE TITLE
TOC table have duplicate item number 

### ISSUE THREAD

**Issue by wwssllabcd** [hexojs/hexo#1287]
I modify themes file at  \themes\landscape\layout_partial\article.ejs
and insert some code into article.ejs like this

```
<div class="article-entry" itemprop="articleBody">
    <% if (post.excerpt && index){ %>
        <%- post.excerpt %>
        <% if (theme.excerpt_link){ %>
        <p class="article-more-link">
            <a href="<%- url_for(post.path) %>#more"><%= theme.excerpt_link %></a>
        </p>
        <% } %>
    <% } else { %>
        <% if(post.toc == true){ %>
            <div id="toc" class="toc-article">
                <%- toc(post.content) %>
            </div>
        <% } %>

    <%- post.content %>
<% } %>
</div>
```

but i get duplicate item number like this 
http://wwssllabcd.github.io/blog/2014/12/22/how-to-install-hexo-on-window/

**Comment by wwssllabcd** [comment]
I modify themes file at  \themes\landscape\layout_partial\article.ejs
and insert some code into article.ejs like this

	<div class="article-entry" itemprop="articleBody">
		<% if (post.excerpt && index){ %>
			<%- post.excerpt %>
			<% if (theme.excerpt_link){ %>
			<p class="article-more-link">
				<a href="<%- url_for(post.path) %>#more"><%= theme.excerpt_link %></a>
			</p>
			<% } %>
		<% } else { %>
			<% if(post.toc == true){ %>
				<div id="toc" class="toc-article">
					<%- toc(post.content) %>
				</div>
			<% } %>
		
		<%- post.content %>
	<% } %>
	</div>
		
but i get duplicate file number like this 
http://wwssllabcd.github.io/blog/2014/12/22/how-to-install-hexo-on-window/

**Comment by Xuanwo** [comment]
@wwssllabcd try `<%- toc(str, false) %> ? 
ref: https://hexo.io/zh-cn/docs/helpers.html#toc
`

**Comment by wwssllabcd** [comment]
I think your answer is right 
but it's not work for me, i don't know why
anyway, thanks xuanwo, 

ref:
https://hexo.io/zh-tw/docs/helpers.html#toc
