### ISSUE TITLE
How does one override the search_form helper plugin?

### ISSUE THREAD

**Issue by chrisjlee** [hexojs/hexo#1288]
I would like to update the template and add additional HTML elements in the search_form helper. Also, the classes [prepend a "-input"](https://github.com/hexojs/hexo/blob/749c91a66977aa9365721e81beed77a0a6d50b89/lib/plugins/helper/search_form.js#L13) which isn't ideal for my case.

How does one override the search_form helper plugin?

**Comment by chrisjlee** [comment]
Anyone have any ideas?

**Comment by Xuanwo** [comment]
write it by yourself.

**Comment by chrisjlee** [comment]
Alright. Sorry just was curious where to start or if there are any examples.
