### ISSUE TITLE
hexo deploy把原来的东西都删掉了

### ISSUE THREAD

**Issue by lili21** [hexojs/hexo#1291]
repo上有之前写好的文章，？？
有什么解决方案吗

**Comment by Xuanwo** [comment]
`hexo d -g`

**Comment by lili21** [comment]
我换了一台电脑，这台电脑上是没有文章信息的，hexo d -g有啥用。

**Comment by Xuanwo** [comment]
要是没有Markdown文件的话，原来的东西肯定没有了。
试试看能不能把HTML转换成Markdown吧。

*以后一定要记得把源文件另外开分支或者开一个库保存= =*

**Comment by lili21** [comment]
这种东西应该写在文档或 wiki里吧，不然怎么知道是这样的后果。换电脑还是很正常的吧。
