### ISSUE TITLE
请教：render错误

### ISSUE THREAD

**Issue by haaaiiimmm** [hexojs/hexo#1292]
Template render error: unexpected token: % 
正文中有很多{{  }}  
和{%  %}

请问如何解决这个问题？

**Comment by haaaiiimmm** [comment]
自己解决了= = ！

在markdown中，用这个包裹内容。

{% raw -%}
内容。。。
{%- endraw %}

**Comment by shawlang** [comment]
怎么我用{%raw%}{%endraw%}包裹了内容 也不行呢？难道是版本原因？我HEXO版本是 3.1.1

**Comment by Xuanwo** [comment]
...

**Comment by lumixraku** [comment]
Good!
