### ISSUE TITLE
无法使用forever 或 pm2 后台运行hexo

### ISSUE THREAD

**Issue by joeseesun** [hexojs/hexo#1293]
无法使用forever 或 pm2 后台运行hexo,求解决方案

**Comment by Xuanwo** [comment]
`hexo s &`

**Comment by leesei** [comment]
Please close this issue.

**Comment by haobingwang** [comment]
forever start app.js

var exec = require('child_process').exec;
exec("hexo server",function(){});

**Comment by holyen** [comment]
mark

**Comment by holyen** [comment]
how to start hexo when centos reboot. @haobingwang

**Comment by x1911** [comment]
@haobingwang   
a good solution, but it dosent work in windows OS
