### ISSUE TITLE
Option in inline css with css helper

### ISSUE THREAD

**Issue by bjankord** [hexojs/hexo#1295]
Currently I'm using Jekyll and switching over to Hexo, I've been really surprised with how easy the transition was. One feature I had working in my jekyll site was the ability inline raw css the head element of my page for [critical css](http://www.filamentgroup.com/lab/performance-rwd.html).

Looking through hexo, it looks like the best place to do this is in the [css helper](https://github.com/hexojs/hexo/blob/43b9b6b50e9e75d2fc9fb755358f3dffb3e56e12/lib/plugins/helper/css.js). It would be nice to pass in an option to let the helper know you don't want to output a link element to a css file, but rather, output the raw css of the file referenced.

Something like:

```
<%- css('style.css','inline') %>
// outputs raw css in style element
<style>
.foo {
  color: #f00;
}
</style>
```

**Comment by curbengh** [comment]
[`htmlTag()`](https://github.com/hexojs/hexo-util#htmltagtag-attrs-text-escape) can help, though you need a new custom helper to utilize it in theme layout.
