### ISSUE TITLE
Pagination cannot be disabled

### ISSUE THREAD

**Issue by steckerhalter** [hexojs/hexo#1297]
According to http://hexo.io/docs/configuration.html#Pagination it should be possible to turn off pagination by setting `per_page` to 0 (which worked before v.3.0)

I looked at the code and it looks like:

```js
hexo.config.index_generator = assign({
  per_page: hexo.config.per_page || 10
}, hexo.config.index_generator);
```

since `0` is falsy it will always take `10`

**Comment by borisschapira** [comment]
Fix proposed to https://github.com/hexojs/hexo-generator-index, where this code belong.

**Comment by steckerhalter** [comment]
thanks for fixing it there... if I remember correctly I grepped through the node_modules and found more than one occurrences with the same code so I think it would have to be fixed in a few other places as well

**Comment by borisschapira** [comment]
@steckerhalter I've tested the correction on both generators, works fine. Let's roll a pull request :+1:

**Comment by steckerhalter** [comment]
@borisschapira great! thanks a bunch
