### ISSUE TITLE
Apache2 returns 404.html for page and page.path variables 

### ISSUE THREAD

**Issue by newgeekorder** [hexojs/hexo#1299]
Locally with hexo server, the hexo public page uses great 
However when deployed to apache2 `page.path` and `page` all return 404.html 

thoughts?

**Comment by leesei** [comment]
How did you deploy to Apache?
Try `hexo generate` and copy the `public/` to `htdocs`.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
