### ISSUE TITLE
Expose code highlight extend point to use other highlight tools.

### ISSUE THREAD

**Issue by hackwaly** [hexojs/hexo#1300]
I'd like to use CodeMirror or other static analyze tools for generate semantic code highlight.
Other users may prefer prism.js over highlight.js.

**Comment by borisschapira** [comment]
What's stopping you from adding one of these library to your theme ?

**Comment by hackwaly** [comment]
Actually I've made it by "adding one of these library to my theme". see [here](http://hackwaly.com/2015/hello-world/). But It's ugly hack I think. 

I've tried that highlight it by use codemirror on server side. But many things need care. Scripts in theme or plugin doesn't have a good hook point to replace hexo's builtin code highlight generation.  Maybe monkey patch the highlight method in `hexo-util` module is a good choose. But it's hard to do it.

**Comment by borisschapira** [comment]
Server-side highlight may be good because it doesn't depend on JavaScript at all, transforming your source code into valid HTML code, but client-side is fine too : it does not alter your source code, making it easier to index by search engine. Also, copy-paste is easier for your visitors.

I think we could debate on that, but as you may have already understand, I'm rather found of client-side code hightlighting myself.

**Comment by hackwaly** [comment]
Client side highlight is almost good.
I just want to point that server side highlight has an advantage is that it can offer highlight feature to some browser that does not support Javascript.
So in my idea, server side is a fallback method.

**Comment by tommy351** [comment]
Maybe we can add another filter named `highlight` and make use of it.

**Comment by borisschapira** [comment]
If you use the Markdown-It renderer, you can decorate it with the `markdown-it-highlightjs` plugin, and your code will be higlighted by HighlightJS server-side.

I've proposed a Pull-Request : https://github.com/celsomiranda/hexo-renderer-markdown-it/pull/15

**Comment by leesei** [comment]
It is pretty easy to integrate Google Prettify (suggested by @liuzc https://github.com/hexojs/hexo/issues/1718#issuecomment-173838633)
[Hexo优化之使用Google Prettify高亮代码 | 柳志超博客](https://liuzhichao.com/2016/hexo-use-prettify-to-highlight-code.html)

**Comment by Jamling** [comment]
@hackwaly I had meet the same problem as yours. I think it's good idea for highlighting at front-end.
It's more freely, and I wrote a plugin name hexo-filter-highlight to do this. It may resolve your problem

**Comment by stevenjoezhang** [comment]
I'm closing this issue. Please join the discussion here #4010 :)
