### ISSUE TITLE
產生的 /tags/index.html 裡面沒有列出被使用的 tag

### ISSUE THREAD

**Issue by zhengda** [hexojs/hexo#1303]
有用 hexo new page "tags" 產生 /tags/index.md ，並在 .md 裡加上 type: "tags"
寫的文章裡有使用 tag。
hexo d -g 後產生出的文章結尾有正確顯示 tag ，可是 /tags/index.html 裡沒有顯示所用的 tag 。

```bash
node -v
v0.12.4

npm -v
2.10.1

hexo -v
hexo-cli: 0.1.6
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by tanvirraj** [comment]
can you write your question in english , so that many people can help you

**Comment by Xuanwo** [comment]
你并不需要这样手动生成tags，你只需要在使用tags的文章中添加
```
tags: [xxx, yyy]
```
然后其他的事情交给Hexo来处理就可以了。

**Comment by tommy351** [comment]
@Xuanwo is right. Add `tags` in posts and Hexo will handle it for you. If you want to display a tag list, you can use `list_tags` in the theme.
http://hexo.io/docs/helpers.html#list_tags

**Comment by leesei** [comment]
Your theme have to support tags layout for displaying all tags.
Or you can modify it using to helper functions.

Not a Hexo core issue, please close.
