### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by tanvirraj** [hexojs/hexo#1304]
when i trying to install in mac OX 10.8 
it doesn't install , don't know what the problem 
![screen shot 2015-05-30 at 11 56 59 pm](https://cloud.githubusercontent.com/assets/3768120/7898647/1cf16ada-0728-11e5-87cd-8d284f105df5.png)

**Comment by borisschapira** [comment]
Seems like a [node-gyp related known issue](https://github.com/TooTallNate/node-gyp/issues/454). You should find some help there.

**Comment by leesei** [comment]
Also try [`--no-optional`](https://github.com/hexojs/hexo/issues/1326) for the npm install.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
