### ISSUE TITLE
hexo启动服务访问 cannot get

### ISSUE THREAD

**Issue by liboyue23** [hexojs/hexo#1309]
根据教程一路做下来，最后启动服务：hexo server，访问浏览器出现 cannot get
![image](https://cloud.githubusercontent.com/assets/11264082/7952636/5480c94e-09eb-11e5-8d78-fad343b04a3b.png)
求大神们帮忙指点啊，这个地方卡了好几天了

**Comment by Xuanwo** [comment]
你有没有进行`npm install`?

**Comment by liboyue23** [comment]
必须install了，安装教程步骤一步步来的，最后服务也启动了

**Comment by astraylinux** [comment]
hexo init
npm install

这两步要连在一起，我之前也是这个问题，是没有执行"npm install"

**Comment by liboyue23** [comment]
已经解决好问题了，依次执行如下命令就行：
npm install hexo-cli -g
hexo init blog
cd blog
npm install
hexo server

**Comment by wangxj** [comment]
感谢liboyue23 ，这个问题已经解决。

**Comment by zhuziyi1989** [comment]
感谢liboyue23/astraylinux  ，问题已经解决。

**Comment by kaiziwangzi** [comment]
当_posts下面没有任何文件时，也会出现此问题，怎么解决

**Comment by Xuanwo** [comment]
@kaiziwangzi  那就创建一个文件

**Comment by kaiziwangzi** [comment]
@Xuanwo 谢谢，暂时只找到这个方案

**Comment by maboloshi** [comment]
其实`npm install` 是按`package.json`里的内容初始化编译环境 
每次`-- save` 一个本地包 都会把包信息写入到`package.json`
方便换的地方(如换个电脑神马的) 直接使用`npm install` 快速初始化编译环境
当然前提 `nodejs` `git` 还是要手工装的

**Comment by kaiziwangzi** [comment]
thanks😁😁

在 2017年2月8日 下午10:47，沙漠之子 <notifications@github.com>写道：

**Comment by LisPerfect** [comment]
@liboyue23 谢谢

**Comment by LiuYangChao** [comment]
感谢liboyue23 ，这个问题已经解决。

**Comment by JERE-MIAH** [comment]
iboyue23, 我的主题在命令之后消失了...变成了默认的layout...
