### ISSUE TITLE
Not to delete other non-hexo directory when do generation

### ISSUE THREAD

**Issue by wudong** [hexojs/hexo#1310]
I have a Hexo generated site and inside it along within the hexo target directory (`/public` ) there is a directory called app (`/public/app`) which contains content that are not generated by hexo. 

The problem I have now is that this directory (`/public/app`) 's content will be deleted whenever I run `hexo generate`. Is there any configuration to prevent this from happening?

**Comment by borisschapira** [comment]
@wudong If you put your folder in `/source`, it will be automaticaly copied to `/public` every time hexe generate.

**Comment by wudong** [comment]
I understand that. but for me the content of `/public/app` is generated by other gulp task, whose source doesn't really feel fit inside hexo's directory.

**Comment by tommy351** [comment]
It's impossible currently. Hexo doesn't know what files should be deleted unless it saves the last generation results.

**Comment by borisschapira** [comment]
@wudong can't your gulp task write to `source` instead of `public` ? Problem's solved !

**Comment by wudong** [comment]
wouldn't it be a nice feature to have? make it much easier to integrate with other stuff. maybe an option in the site config?

@borisschapira Don't really want to mess the source dir with generated code, which shouldn't be in version control as well.

**Comment by arlair** [comment]
I also ran into this where it is deleting gz files I created. Nginx can serve pre-compressed files instead of doing it on the fly.
