### ISSUE TITLE
hexo deploy无效

### ISSUE THREAD

**Issue by liboyue23** [hexojs/hexo#1312]
使用hexo d 命令,出现如下现象，是不是少安装东西了？
![image](https://cloud.githubusercontent.com/assets/11264082/7975786/bcdd2780-0aa4-11e5-848d-65d353e81611.png)

**Comment by Xuanwo** [comment]
这是因为当前目录不是一个有效的Hexo目录。
你是不是刚升级到3？建议看一下https://github.com/hexojs/hexo/wiki/Breaking-Changes-in-Hexo-3.0

**Comment by astraylinux** [comment]
试试 npm install hexo-deployer-git

**Comment by liboyue23** [comment]
好了，问题已经解决了，hexo在使用的时候有好多坑！总结如下：
npm install hexo-cli -g
hexo init blog
cd blog
npm install
hexo server

_config.yml:
deploy:
  type: git
  repository: https://github.com/liboyue23/my-hexo.git
  branch: gh-pages

npm install hexo-deployer-git --save
