### ISSUE TITLE
Markdown renderers, comments and breaklines

### ISSUE THREAD

**Issue by borisschapira** [hexojs/hexo#1313]
I tried the two main markdown renderers "Makdown-It" and "Marked". Both failed on this code, inserting a breakline inside the second comment (more than 71 caracters).

    ```js
    // aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa a a a
    // aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa a a a a a
    ```

**Comment by tommy351** [comment]
![2015-06-05 14 16 56](https://cloud.githubusercontent.com/assets/411425/8000460/8ca6eef4-0b8d-11e5-9514-a642ec17d09a.PNG)

It displays well on the default theme.

**Comment by borisschapira** [comment]
Good idea, I've starting anew from the default configuration and found the guilty plugin.
Moves issue there : celsomiranda/hexo-beautify#2

**Comment by borisschapira** [comment]
Issue can be closed.
