### ISSUE TITLE
关于hexo clean

### ISSUE THREAD

**Issue by lcyan** [hexojs/hexo#1314]
### 关于hexo clean 几个问题

1. 问下什么场景下执行`hexo clean`
2. 新建一篇文章是不是只需要执行`hexo d -g` 就可以了,还需要执行`hexo clean`吗?
3. `hexo clean` 后文章下面多说的评论内容就没有了.

**Comment by Xuanwo** [comment]
1. 修改了CSS之类的文件之后，需要执行clean，来清除缓存
2. 新建文章只需要`hexo new`或者直接新建md文件即可，`hexo d -g`是渲染并上传的命令
3. 多说评论采用JS的方法调用，跟`hexo clean`无关
