### ISSUE TITLE
为什么 hexo d 之后 Blog 不更新。

### ISSUE THREAD

**Issue by wangzhenyujiang** [hexojs/hexo#1315]
hexo d 之后启动 hexo server 发现是更新了的，说明部署成功了，但是当访问 gicafe 的时候还是没有更新。而且发现 gitcafe 上的仓库也已经有了新的文章了，但是为什么页面不变呢？

**Comment by Xuanwo** [comment]
因为要`hexo d -g`

**Comment by Xuanwo** [comment]
如果只是页面不变的话，你多刷新几次，缓存更新之后就可以了。

**Comment by JamesPan** [comment]
gitcafe 有时候的延迟还挺严重的，建议同时部署到 gitcafe 和github 上面，可以做个比较

**Comment by chitanda** [comment]
目测是gitcafe的问题。我也遇到了这个问题。github秒更新，cafe大概要一个小时的延迟

**Comment by Gabriel1225** [comment]
可以尝试一下在 hexo deploy -g 之前先使用hexo clean清空缓存

**Comment by 1139195320** [comment]
我的新页面上传成功，在远程仓库可以看到，但是直接访问新增的页面就是404，有没有大佬遇到过同样的问题呀？求指点。
