### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by Johnwhite-leaf** [hexojs/hexo#1317]
I wish hexo can add multiple language feature like [hexo.io](http://hexo.io) in the future. It is very usefull that people can switch language in every webpage anytime. I also want to know how to add this feature to my webside now. Thank you very much! BTW: Hexo is wonderfull.

**Comment by diessica** [comment]
You mean a native feature in the framework? Cause I guess there is a plugin for that...

**Comment by tommy351** [comment]
Hexo is capable for a multiple language site. hexo.io is built with Hexo completely.
https://github.com/hexojs/site

**Comment by Johnwhite-leaf** [comment]
Dear Tommy:
    Thank you for your reply!
    I kown Hexo is capable for that. I have tried to read the codes from https://github.com/hexojs/site. But I am just a beginer. it's a little difficult  for me to transplant this feature to the theme[jacman]( https://github.com/wuchong/jacman) I like now. What I wish is I can simplely set a config value to build a multiple language site. Or you can tell me something about the key point of how multiple language feature works. I would like to contribute this feature for hexo. If you like.

**Comment by Xuanwo** [comment]
https://github.com/hexojs/site/tree/master/source

you can see the dictory named of `zh-cn`&`zh-tw`, you can place your file in them as in source. Then you just need to add a link at homepage for visitors.

will, I'm a beginer too, if something wrong, please forgive me = =

**Comment by FrankBian** [comment]
hah
Helping each other is very fun !


Best Regards,
Frank Bian

**Comment by Jamling** [comment]
@Johnwhite-leaf 
For advance, you can install [hexo-generator-i18n](https://github.com/Jamling/hexo-generator-i18n)
For basic, you can use [Nova](https://github.com/Jamling/hexo-theme-nova) theme for your blog.
Preview: http://ieclipse.cn
