### ISSUE TITLE
mac上deploy时CNAME由大写变小写了

### ISSUE THREAD

**Issue by atomicink** [hexojs/hexo#1319]
mac对大小写不敏感，deploy时CNAME变成了cname，导致github pages无法识别个人域名。
我试着在deployer.js里加了一句 ``git('mv', 'cname', 'CNAME')`` 后貌似好了，不过感觉有些不妥。
希望开发者可以判断系统环境以及存不存在cname，在push到github时强制CNAME大写。

**Comment by Xuanwo** [comment]
`git config core.ignorecase false`

**Comment by atomicink** [comment]
ignorecase会把CNAME和cname都传上去的

**Comment by Xuanwo** [comment]
你把cname删了呀- -
