### ISSUE TITLE
search_form helper should accept a template value

### ISSUE THREAD

**Issue by chrisjlee** [hexojs/hexo#1321]
Search form helper should allow hook to override template:

https://github.com/hexojs/hexo/blob/2ad148ca49639ded9bbd0817492ab08b689c3430/lib/plugins/helper/search_form.js

**Comment by tommy351** [comment]
What not write the custom template in the theme?

**Comment by chrisjlee** [comment]
Ah. Didn't know one can do that. How does one do that?

**Comment by tommy351** [comment]
https://github.com/hexojs/hexo-theme-light/blob/master/layout/_widget/search.ejs

**Comment by chrisjlee** [comment]
Thanks. Tommy
