### ISSUE TITLE
如何备份source里面的内容

### ISSUE THREAD

**Issue by liboyue23** [hexojs/hexo#1322]
我们都知道，hexo d 是将public里面的内容传到github上，但是根目录下的配置文件以及source里面写的文章还有CNAME等个性化文件没有上传，那么如果本地磁盘损坏或者文件丢失该怎么办？如何备份source的内容？￼￼￼

**Comment by FrankBian** [comment]
可以把hexo的文件夹也备份到github上


Best Regards,
Frank Bian

**Comment by liboyue23** [comment]
如何备份到github上呢？手动拷贝一份传到新的repo？

**Comment by FrankBian** [comment]
不需要吧  hexo作为master分支   blog文件deploy到 gh-page分支  
相当于Github page 那样

当然你也可以搞个新的repo用来备份hexo文件夹

Best Regards,
Frank Bian

**Comment by Xuanwo** [comment]
再开一个新的分支，起名为blog什么的，你可以参考一下我的处理：
https://github.com/Xuanwo/xuanwo.github.io
