### ISSUE TITLE
How to provide download address in my blog? The .rar file is in my laptop.如何在blog里提供下载文件？

### ISSUE THREAD

**Issue by tinynugget** [hexojs/hexo#1323]
Well, I have a .rar file and I want to put it on my homepage, so that others could download it. Do I just need to use <a href="address">download</a> this code?  Dose the "address" is the path of my file in my laptop?

**Comment by tinynugget** [comment]
Well,

**Comment by tommy351** [comment]
Upload your file to the internet or no one can't download the files from your laptop.

**Comment by tinynugget** [comment]
Thanks, I think I could share files on baidu cloud and add the reference to href. Do you guys have other suggestions？

--
Best regards,

Wu Zhihao(吴志豪)
Undergraduate
Department of Electronic Engineering
Shanghai Jiao Tong University
No.800 Dongchuan Road,Shanghai,P.R.China
Email: Mike_mc@163.com

**Comment by Xuanwo** [comment]
挺好的，只要别拿Github当成下载站就行= =

**Comment by tinynugget** [comment]
^_^thanks！

--
Best regards,

Wu Zhihao(吴志豪)
Undergraduate
Department of Electronic Engineering
Shanghai Jiao Tong University
No.800 Dongchuan Road,Shanghai,P.R.China
Email: Mike_mc@163.com
