### ISSUE TITLE
本地预览正常，提交到GitHub提示404

### ISSUE THREAD

**Issue by 70kg** [hexojs/hexo#1324]
GitHub显示提交成功，希望可以解答一下，谢谢

**Comment by Xuanwo** [comment]
刚才试了，访问正常。
首次提交会慢一些，多等一会儿就好。

**Comment by gydmercy** [comment]
之前我的一个页面提交上去变成了404，去github上看明明已经提交上去了。后来仔细一看本地文件夹为大写的，提交上去变成小写了，不知道为什么。删掉重新提交一次就正常了。

**Comment by Xuanwo** [comment]
@gydmercy 貌似会出现忽略大小写的情况
