### ISSUE TITLE
when i run "hexo d" ,  i receive repository: https://gitcafe.com

### ISSUE THREAD

**Issue by worldligang** [hexojs/hexo#1327]
hexo d
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
JS-YAML: bad indentation of a mapping entry at line 72, column 13:
      repository: https://gitcafe.com/CodeHud/co ... 

who can help me ?

**Comment by Xuanwo** [comment]
line 72, column 13

what's that ,can you tell me.

**Comment by leesei** [comment]
Is the issue fixed?
Can you post your config?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
