### ISSUE TITLE
deploy能成功，但是不是部署的.deloy目录，而是根目录

### ISSUE THREAD

**Issue by shengxinjing** [hexojs/hexo#1332]
deploy能成功，但是不是部署的.deloy目录，而是根目录
求解啊倒是github两个项目一模一样。。没有部署.deploy目录

**Comment by Xuanwo** [comment]
大兄弟啊，你的表达能力。。。

重新hexo init一个目录吧

**Comment by shengxinjing** [comment]
..就是deploy的不是生成的.deploy_git目录啊，而是项目的根目录

**Comment by Xuanwo** [comment]
你是不是修改过这个？。。

```
# Directory
source_dir: source
public_dir: public
```

最快的解决方案是重新`hexo init`

**Comment by shengxinjing** [comment]
没改过。。默认的配置。。我试下

**Comment by shengxinjing** [comment]
生成的文件都没问题，本地预览也没问题。。就是deploy把根目录给部署了。。蛋疼

**Comment by Xuanwo** [comment]
你怎么deploy的？该不会是自己`git push`的吧？

**Comment by shengxinjing** [comment]
..hexo d..用的命令。。
deploy:
  type: git 
  repository: git@github.com:shengxinjing/shengxinjing.github.io.git #你的GitHub Pages仓库
  branch: master 

这是配置

**Comment by Xuanwo** [comment]
这样吧- -，你把自己修改过的文件全都复制出来，然后新建一个文件夹进行`hexo init`，然后装好插件，重新`hexo deploy`。我隐约有些怀疑是不是把根目录变成了git目录= =。

**Comment by shengxinjing** [comment]
根目录不能是git目录吗囧

**Comment by Xuanwo** [comment]
可以啊- -，但是你不能放在同一个分支里面啊。。。

**Comment by shengxinjing** [comment]
必须不在一个分支啊，我部署到另外一个项目里的，结果吧根目录部过去了

**Comment by Xuanwo** [comment]
首先- -，你需要把.com那个库删掉= =

**Comment by Xuanwo** [comment]
然后你删掉.deploy_git文件夹，重新hexo d

**Comment by ge-ce** [comment]
你多试几次 ，从头 hexo init ，慢慢就明白了。。。
我现在就是都在一个项目里，不同的分支
master: 空
gh-pages: hexo d 的内容
blog: 根目录下文件

**Comment by leesei** [comment]
Please close this issue now that OP have a [correct site](http://shengxinjing/shengxinjing.github.io)

**Comment by landerqi** [comment]
##### `repository` 应该换成 `repo` 吧
