### ISSUE TITLE
gfm task/TODO list 无法渲染

### ISSUE THREAD

**Issue by CubeSugar** [hexojs/hexo#1335]
gfm特性 即使用`- [ ]` or `- [x]`做task list，但是hexo渲染成了普通list，有解决方案么？

**Comment by Xuanwo** [comment]
并没有，这个要看Hexo引用的Marked

**Comment by CubeSugar** [comment]
@Xuanwo 在_config中配置
```
marked: 
    gfm: true
```

也还是没法支持这个特性，另一个markdown-it的渲染引擎效果也不理想，还有其他支持比较全面的md渲染引擎么？

**Comment by Xuanwo** [comment]
https://github.com/github/markup/issues/208

你将会看到一段长长的历史= =

**Comment by CubeSugar** [comment]
@Xuanwo 
在这段历史里 https://github.com/github/markup/issues/208 task list终于在广大群众＋1声中被Github加入到特性中了XD https://github.com/blog/1825-task-lists-in-all-markdown-documents

其实想想blog里的task list经常用来当作清单，渲染成checkbox，不论readonly还是disable，都是挺怪异的，只是markdown写起来方便些。

暂时找了一种替代方法是，保存一个snip作为list item，随用随插：
```
<input type='checkbox' onclick='return false;' checked> bla bla
```

**Comment by wangzhe0417** [comment]
请问这个问题解决了吗？
我也遇见了同样的问题

**Comment by Xuanwo** [comment]
@wangzhe0417 不支持不叫做问题。

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo-renderer-marked/pull/32 supported.

**Comment by yanhao852565720** [comment]
同样遇到了此问题。

**Comment by AiMo-Hux** [comment]
<input type='checkbox' onclick='return false;' checked> bla bla

**Comment by AiMo-Hux** [comment]
<input type='checkbox' onclick='return false;' checked /> bla bla
