### ISSUE TITLE
怎么显示emoji表情？

### ISSUE THREAD

**Issue by ge-ce** [hexojs/hexo#1336]
貌似默认不支持emoji显示？

查到有个插件，但是针对旧版本的，现在也不能用了，就算能用也好麻烦。。。

在jekyll 中就可以直接用，hexo中可以吗？怎么做？

文档好少啊😓

**Comment by Xuanwo** [comment]
自己添加相应的字体就好，引用之

**Comment by ge-ce** [comment]
能不能具体点，刚接触不懂 ……

**Comment by leesei** [comment]
See https://github.com/sergiolepore/hexo-tag-emojis/issues/9.
Not Hexo issue.

**Comment by Eamonnzhang** [comment]
这个hexo-tag-emojis已经过时

**Comment by ixiusama** [comment]
只支持 hexo v2 对 v3 没有进行支持
