### ISSUE TITLE
Nested pages

### ISSUE THREAD

**Issue by vedovato** [hexojs/hexo#1337]
Yo, there's a way to create nested pages like **services/service-1**?
I'm trying Hexo for a entire site, not a blog.

**Comment by Xuanwo** [comment]
try to put .md files in /source/services/service-1?

**Comment by leesei** [comment]
That should work, any update?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.

**Comment by horak** [comment]
I'm trying for the same, tried nesting them as you'd expect. It doesn't automatically generate the correct structure within public. It does generate a new `index.html` file in my sub-directory though, it just doesn't link any of the containing `.md` files. Any ideas?
