### ISSUE TITLE
language selector

### ISSUE THREAD

**Issue by bsr203** [hexojs/hexo#1338]
Hi,

for the `navy` theme, lang_select.js has following code, where `zh-cn` is the main language. Can we avoid this hardcoding and use the value from _config. I like to set `en` as my default languge and don't want prefix like `/en/index.html`
```
function changeLang(){
    var lang = this.value;
    var canonical = this.dataset.canonical;
    if (lang === 'zh-cn') lang = '';
    if (lang) lang += '/';

    location.href = '/' + lang + canonical;
  }
```

thanks.

**Comment by tommy351** [comment]
The `en` is always the default language.
https://github.com/hexojs/site/blob/master/themes/navy/source/js/lang_select.js

**Comment by bsr203** [comment]
thanks tommy.
