### ISSUE TITLE
Problems when generating site

### ISSUE THREAD

**Issue by vedovato** [hexojs/hexo#1339]
Yo, when i type hexo generate, everything goes right but Hexo arent generating my main index.html file. What may be wrong?

**Comment by vedovato** [comment]
S#it, now when i type hexo server, i cant get /. It says Cannot GET /. Any idea?

**Comment by Xuanwo** [comment]
`npm install`?

**Comment by vedovato** [comment]
well, it didnt works .. To get it compiling again i needed to copy my
project files into a  new hexo project and then compile then.



Att,
*Andrei Vedovato Alves*
Desenvolvedor web

*www.andreivedovato.com <http://www.andreivedovato.com> *
*CL:* 19 99329-2025
*SK:* dvedovato

**Comment by borisschapira** [comment]
Seems to me that your projects is not well installed. Have you tried deleting the node_modules forlder and then running `npm install` again ?

**Comment by vedovato** [comment]
When I decided to move my template into a new hexo project everything gone
right but then when I generated that site again, my index file was gone....
Then I moved again into a new project and all gone ok... In all that
projects I ran npm install....

But that's not a problem anymore everything is ok guys

Att,
Andrei Vedovato
CL: 19 99510-6793
SK: dvedovato

**Comment by Xuanwo** [comment]
Every new hexo project needs `npm install`

**Comment by vedovato** [comment]
Thank you guys!
