### ISSUE TITLE
使用作业部落的编辑器编辑，hexo g 出错

### ISSUE THREAD

**Issue by sunzcdev** [hexojs/hexo#1340]
JS-YAML: can not read a block mapping entry; a multiline key may not be an impli
cit key at line 4, column 1:

我判断可能是作业部落的编辑器出来的格式hexo不支持造成的。第四行有---，而生成的文件却没有，不知道谁还遇到过

**Comment by Xuanwo** [comment]
一般来说，是你漏掉了`:`之后的空格

**Comment by leesei** [comment]
Validate YAML with [Online YAML Parser](http://yaml-online-parser.appspot.com/)
