### ISSUE TITLE
如何阻止hexo自动编译？

### ISSUE THREAD

**Issue by WuHuaJi0** [hexojs/hexo#1344]
我们知道 hexo会将source里的文件，编译为HTML文件，并发布到public文件夹里。

那我想在站点里放一个「纯的」HTML，也就是说，我在source目录下放一个HTML文件：
```
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	
</body>
</html>
```
这个文件在hexo g 之后，发布到public的文件就变成了，变成了在hexo主题大框架下的HTML，（也就是自动加上了一些样式和主题的内容）。

我的问题是，有时候我想要纯的HTML文件，如何阻止hexo对我的文件编译呢？

不知道我说清楚没有：）

**Comment by WuHuaJi0** [comment]
https://github.com/hexojs/hexo/issues/158 
似乎这里有了一些解释，我先来试试看：）

**Comment by Xuanwo** [comment]
skip_render

**Comment by WuHuaJi0** [comment]
https://github.com/hexojs/hexo/issues/1146#issuecomment-88380140
这是个可以解决的办法
