### ISSUE TITLE
/blog/categories/ leads to 404

### ISSUE THREAD

**Issue by mcepl** [hexojs/hexo#1346]
When I look at generated `categories/` subdirectories I see:
```
matej@mitmanek: blog$ ls public/categories/
android  blogging   church    culture    faith   google    Uncategorized
atompub  bugTriage  computer  ecumenism  Fedora  politics
matej@mitmanek: blog$ 
```
Which means that when i go to `/blog/categories/` I get an error (with Apache `httpd-2.2.15-39.el6` on CentOS/RHEL-6) Error 404 "Cannot GET /blog/categories/ "

Couldn't `hexo` be persuaded to generate `index.html` files in the particular subdirectories as well, please?

**Comment by Xuanwo** [comment]
create a floder `categories` and put a index.md in it.

**Comment by mcepl** [comment]
> create a floder categories

where? `source/categories/index.md`?

**Comment by iissnan** [comment]
Hi @mcepl. It seems you are using [NexT](https://github.com/iissnan/hexo-theme-next) theme. If yes, you need to create a page for categories:

```
hexo new page categories
```

Then, Open the `source/categories/index.md` and change `type` to `categories`.

**Comment by mcepl** [comment]
Yes, that's it. Thanks.
