### ISSUE TITLE
Bug {#}

### ISSUE THREAD

**Issue by pengloo53** [hexojs/hexo#1348]
当我在文章中写入`{#}`时，hexo generate就会报错。

![2015-06-22 23 29 18](https://cloud.githubusercontent.com/assets/5508125/8285622/161f7988-1937-11e5-8abf-cfd751f7e45d.png)

![2015-06-22 23 29 37](https://cloud.githubusercontent.com/assets/5508125/8285623/183b7974-1937-11e5-89d4-41b24de9461f.png)

**Comment by Xuanwo** [comment]
可能是swig的语法

**Comment by chenyangcun** [comment]
我也发现了，我输入了这个{#variable}， 这个怎么解决？

**Comment by Xuanwo** [comment]
用{%raw%}{%endraw%}包裹起来试试？

**Comment by chenyangcun** [comment]
{%raw%}{#variable}{%endraw%}  这样也不行

**Comment by Xuanwo** [comment]
加个空格，或者单独{%raw%}#{%endraw%} 这样吧，要不然就是需要转义

**Comment by chenyangcun** [comment]
恩，加了空格，可以生成了
