### ISSUE TITLE
hexo version 显示版本号的问题

### ISSUE THREAD

**Issue by panxianhai** [hexojs/hexo#1349]
先是结果如下，并没有hexo的版本号，只有hexo-cli的版本。
hexo-cli: 0.1.7
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

**Comment by panxianhai** [comment]
发现了，hexo init 并且npm install之后才能看到具体的版本。

**Comment by suencc** [comment]
非常感谢，我也遇到同样问题
