### ISSUE TITLE
执行 hexo -s 时出错,错误信息如下

### ISSUE THREAD

**Issue by emacsist** [hexojs/hexo#1351]
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Hexo version: \u001b[35m3.1.1\u001b[39m","time":"2015-06-23T16:39:02.948Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Working directory: \u001b[35m~/Documents/git/emacsist/\u001b[39m","time":"2015-06-23T16:39:02.951Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Config loaded: \u001b[35m~/Documents/git/emacsist/_config.yml\u001b[39m","time":"2015-06-23T16:39:03.128Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-deployer-git\u001b[39m","time":"2015-06-23T16:39:03.297Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-archive\u001b[39m","time":"2015-06-23T16:39:03.300Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-category\u001b[39m","time":"2015-06-23T16:39:03.303Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-index\u001b[39m","time":"2015-06-23T16:39:03.307Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-generator-tag\u001b[39m","time":"2015-06-23T16:39:03.311Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-ejs\u001b[39m","time":"2015-06-23T16:39:03.323Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-marked\u001b[39m","time":"2015-06-23T16:39:03.403Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-renderer-stylus\u001b[39m","time":"2015-06-23T16:39:03.529Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Plugin loaded: \u001b[35mhexo-server\u001b[39m","time":"2015-06-23T16:39:03.636Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":60,"err":{"message":"ENOENT, open '/Users/yangzhiyong/Documents/git/emacsist/Hexo-Github-Pages搭建个人Blog.md'","name":"Error","stack":"Error: ENOENT, open '/Users/yangzhiyong/Documents/git/emacsist/Hexo-Github-Pages搭建个人Blog.md'","code":"ENOENT"},"msg":"Something's wrong. Maybe you can find the solution here: \u001b[4mhttp://hexo.io/docs/troubleshooting.html\u001b[24m","time":"2015-06-23T16:39:03.638Z","v":0}
{"name":"hexo","hostname":"yangzhiyongdeMacBook-Pro.local","pid":72050,"level":20,"msg":"Database saved","time":"2015-06-23T16:39:03.641Z","v":0}

好像没有具体什么原因及建议呀. 我到 http://hexo.io/docs/troubleshooting.html 里也没有看到想要的解决办法,只好求助于这里了. 请问下如何解决 ?希望能在debug信息里提供更有参考意义的信息,

**Comment by emacsist** [comment]
SyntaxError: Unexpected token ILLEGAL. 

只是报这个, 但却没有指明是哪个 md 文件,哪一行.

**Comment by Xuanwo** [comment]
ENOENT一般是没找到文件或路径，包括因为权限问题没找到的情况。

**Comment by leesei** [comment]
有更新嗎?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
