### ISSUE TITLE
怎样修改默认归档URL格式

### ISSUE THREAD

**Issue by qsnow6** [hexojs/hexo#1352]
**默认情况下文章归档的路径是这样的**
http://localhost:4000/archives**/2015/06/**
如果要修改为这样:
http://localhost:4000/archives**/201506/**

在哪里可以设置。即：取消多个目录，合并为一个目录。

示例：
这个路径是文章归档下
![catch 06-25-11-44-43](https://cloud.githubusercontent.com/assets/4144227/8346481/d217aabc-1b2f-11e5-9dd6-4a982ef591f2.jpg)

**Comment by Xuanwo** [comment]
permalink: :year/:month/:day/:title/

**Comment by qsnow6** [comment]
这个是博客文章的路径，我指的是文章归档的URL，如下图：




328134421@qq.com
 
发件人： 漩涡
发送时间： 2015-06-25 11:40
收件人： hexojs/hexo
抄送： qsnow6
主题： Re: [hexo] 怎样修改默认归档URL格式 (#1352)
permalink: :year/:month/:day/:title/

**Comment by tommy351** [comment]
You can modify the `archive_dir` setting.

**Comment by Xuanwo** [comment]
@tommy351 modify the `achieve_dir` only change the achieves dir, can't make `achieves/2015/06` come into `achieves/201506`

**Comment by leesei** [comment]
@qsnow6 Archive path is generated by https://github.com/hexojs/hexo-generator-archive
Maybe you can extend it or fork it.

**Comment by Xuanwo** [comment]
Closed for no more update.
