### ISSUE TITLE
..

### ISSUE THREAD

**Issue by iparanoid** [hexojs/hexo#1354]

**Comment by iparanoid** [comment]
详细描述一下
设备 New Moto X
系统 Android 5.1
环境 微信 6.2

第一步 
扫描http://notes.iissnan.com/2015/angularjs-application-unit-testing-getting-stated/的二维码
如下图正常显示
![image](https://cloud.githubusercontent.com/assets/6026988/8357131/cfb3ffd0-1b8b-11e5-9a9d-2df57f4266bc.png)

第二步
将网页分享到朋友圈
![image](https://cloud.githubusercontent.com/assets/6026988/8357151/e9ec57b2-1b8b-11e5-85bf-2ac72590163a.png)

第三步
在朋友圈动态中 打开分享的链接
如下图
![image](https://cloud.githubusercontent.com/assets/6026988/8357167/01a3ff54-1b8c-11e5-92b9-5fd3d2dc8a33.png)

PS：同样的流程 分享 http://notes.iissnan.com/ 没有任何问题
        只是在分享“文章页”时会出现被重排的现象
求解决方案 谢谢

**Comment by Xuanwo** [comment]
恩？

**Comment by Xuanwo** [comment]
请更新更详细的信息，否则这个issues就关闭了

**Comment by leesei** [comment]
Please close this issue.
