### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by taylor009** [hexojs/hexo#1355]
I'm new to using hexo and I can't figure out how exactly to edit the home page?

**Comment by Xuanwo** [comment]
edit the home page?
what's your want?
modify the html/css or edit the content?

**Comment by taylor009** [comment]
I wanted to know  how to edit the bome page

**Comment by Xuanwo** [comment]
you can edit it by create/edit/delete your md files in source

**Comment by leesei** [comment]
You mean index page/front page? That's done by the theme.
You choose a theme and then customize it.
