### ISSUE TITLE
i want to add cname with deploy

### ISSUE THREAD

**Issue by keeleys** [hexojs/hexo#1357]
if i want to add CNAME,
but deploy or generate will delete all file and replace its,
how can i move cname with generate or  deploy.

**Comment by Xuanwo** [comment]
啥意思？

**Comment by keeleys** [comment]
thanks ,move CNAME file to source dir to solve it.

**Comment by bennyn** [comment]
@keeleys How do you manage to keep the `CNAME` file in the root of your repository when publishing? I put it in "source/CNAME" but then it also appears in "source/CNAME" when publishing the static HTML bundle.

**Comment by bennyn** [comment]
Ok, I found it. It needs to be in "themes/your-theme/source" and not in "source" (where the "_posts" are).
