### ISSUE TITLE
How to disable comment in a Page / post

### ISSUE THREAD

**Issue by bearpaw** [hexojs/hexo#1358]
I don't want the 'Comment' section in some pages and posts.

**Comment by Xuanwo** [comment]
depend on your theme, you can change the post's layout or create a new layout without comment.

**Comment by leesei** [comment]
Put `comment: false` in front matter.
https://hexo.io/docs/front-matter.html#Settings_&_Their_Default_Values

**Comment by kba977** [comment]
typos `comments: false` @leesei
