### ISSUE TITLE
3.1.1 Cannot read property 'lineno' of null

### ISSUE THREAD

**Issue by morris821028** [hexojs/hexo#1360]
with hexo-math inline block.

```
{% math \frac{|ax + by + c|}{\sqrt{a^{2}+b^{2}}} %}
```

I get Error message below
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do
cs/troubleshooting.html
TypeError: Cannot read property 'lineno' of null
    at NunjucksTag._parseArgs (c:\Users\x\Desktop\blog\node_modules\hexo\lib\
extend\tag.js:84:40)
    at NunjucksTag.parse (c:\Users\x\Desktop\blog\node_modules\hexo\lib\exten
d\tag.js:69:19)
    at Object.extend.parseStatement (c:\Users\x\Desktop\blog\node_modules\hex
o\node_modules\nunjucks\src\parser.js:540:36)
....
```

I solved it by
```
$ \frac{|ax + by + c|}{\sqrt{a^{2}+b^{2}}} $
```

migrate 2.x.x to 3.x is hard work ? I have many posts which also have these parsing, render problem.

**Comment by morris821028** [comment]
Because `Hexo 3, we use Nunjucks for rendering. The behavior may be different from Swig.`, inline tag plugin need to void `{{` or `}}` as a tag argument.

just `hexo-math` plugin & latex syntax cause this problem.

**Comment by leesei** [comment]
https://github.com/akfish/hexo-math#migrating-to-200
You HAVE to change syntax.

Otherwise, see #1510.
