### ISSUE TITLE
Search Engine URL have wrong

### ISSUE THREAD

**Issue by MayKiller** [hexojs/hexo#1364]
```
<div id="search-form-wrap" class="">
  <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form">
    <input type="search" name="q" results="0" class="search-form-input" placeholder="Search">
    <button type="submit" class="search-form-submit"></button>
    <input type="hidden" name="q" value="site:xxx">
  </form>
</div>
```
`//google.com/search`
It is not working.
and change to 
`https://www.google.com/search`
It is working.

in default theme landspace

**Comment by Xuanwo** [comment]
which browser do you use?
`//google.com/search` will use https if https is available

**Comment by MayKiller** [comment]
@Xuanwo 问题不在于 `//` 而是缺少 www
 
浏览器使用 Chrome, 缺少 `www` 的跳转URL为 : `http://google.com/search?q=Github`

- - -

可能是我本地网络问题? http://google.com 没有 301 到 https://www.google.com?

**Comment by MayKiller** [comment]
已经确定是本地网络问题

打扰了...
