### ISSUE TITLE
Feature request - disable hello world

### ISSUE THREAD

**Issue by cyberwombat** [hexojs/hexo#1365]
When I run the server with `hexo serve` it always has the hello world post in it. Is there ia way to not have that so I can see my real blog posts?

**Comment by timeshout** [comment]
To clarify. This resides in the hexo cli package and gets deployed to git unless I stop server, clean, generate and deploy again.

**Comment by arlair** [comment]
Delete hello-world.md from your source/_posts directory?

**Comment by cyberwombat** [comment]
its build in to the core as part of the cli package. its impossible to delete without forking.

**Comment by arlair** [comment]
Sure, but I think the idea is that there is default page to help people new to Hexo with some simple getting started instructions and to make sure your setup is working.

After you run the cli, you delete the page and add your own pages.

WordPress has a similar feature I believe:

https://wordpress.org/support/topic/how-to-get-rid-of-the-hello-world-welcome-to-wordpress-message

**Comment by cyberwombat** [comment]
But unlike WP you can't delete the page. Ever. Granted it doesnt go live on deploy but its pretty annoying when you are wanting to make sure your site looks the way you want and that thing is there. For example I myself have added front matter data to my posts (icons, custom excerpt, etc) but I cant touch the hello world post so it just shows as broken images on my blog. Since there is a default theme it seems that the hello world should go in there. When I am ready to do my own then I should be able to start with a clean slate no?

**Comment by arlair** [comment]
I deleted a hello-world.md from the _posts directory just now and ran hexo server and I don't see any Hello World page when I browse the site. It doesn't appear to get regenerated or anything, so I'm not sure what you mean. But good luck :)

**Comment by cyberwombat** [comment]
https://github.com/hexojs/hexo-cli/tree/master/assets/source/_posts

**Comment by arlair** [comment]
Yes, the Hexo CLI (Command Line Interface) creates a project for you to modify. This generated project you can do whatever you like with. You can check into your own repository, or however else you might like to handle keeping track of your blogs data. Creating the project (hexo init) is a one time command.

The Hello World post is just a sample and can be deleted, just like any post you might add yourself and decide later you no longer require.

The only other option I can think of is that you want a parameter for 'hexo init <blog name>' to not create the hello-world.md file.

**Comment by cyberwombat** [comment]
I guess it is so. I dont' remember initalizing the blog and was struggling to find the hello world which was not in my posts folder. Yet as I run the server now it's gone so not sure what flow I was using. Thank you for your patience. I will close this issue now until/unless I can recreate the original issue I had.
