### ISSUE TITLE
the issues caused by brace 

### ISSUE THREAD

**Issue by WymanY** [hexojs/hexo#1369]
if i have a brace in my code 
`iamgeAspectRect = {{37.563884156729145, 0}, {224.87223168654171, 300}}, imageView ={{37.5, 183.5}, {300, 300}}`
but the hexo throw exception in the terminal
![error](http://m2.img.srcdd.com/farm4/d/2015/0704/15/9D173956EA5185FCA99AAA851952D12B_B500_900_500_328.png)
After  I delete the brace ![delete brace](http://m3.img.srcdd.com/farm4/d/2015/0704/15/80E227C10BBC7B561F6E7DB009F57549_B500_900_500_140.png)
But if I delete the brace,there was no error. Idon't know how to solve it

**Comment by Xuanwo** [comment]
use swig tag
{%raw%}{%endraw%}

**Comment by WymanY** [comment]
thks，I solve it.
