### ISSUE TITLE
style.css can't be served

### ISSUE THREAD

**Issue by bejondshao** [hexojs/hexo#1373]
hexo 3.1.1
bejondshao.github.io

package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.0",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-tag": "^0.1.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-stylus": "^0.2.3",
    "hexo-server": "^0.1.2"
  }
}

**Comment by bejondshao** [comment]
https://github.com/bejondshao/bejondshao.github.io

there's no style.css in /css folder. I don't know why it is not generated

**Comment by bejondshao** [comment]
_config.yml

# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: Bejond Shao
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://bejondshao.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: landscape

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:bejondshao/bejondshao.github.io.git
  branch: master


there's sytle.css in /public/css folder. But no in /css folder

**Comment by Xuanwo** [comment]
modify your dependencies:
```
"dependencies": {
    "hexo": "^3.1.0",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-tag": "^0.1.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-stylus": "^0.2.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-server": "^0.1.2"
  }
```

**Comment by bejondshao** [comment]
Hi @Xuanwo ,"hexo-renderer-marked": "^0.2.3", is changed by me trying to solve the issue. The default is ^0.2.4. I also tried, but still no css.

I don't know why after generate, css file is not copied to /css folder

**Comment by bejondshao** [comment]
bejond@bejond:~/source/other/bejondshao.github.io/blog$ hexo g
INFO  Files loaded in 244 ms
INFO  Generated: js/script.js
INFO  Generated: fancybox/jquery.fancybox.pack.js
INFO  Generated: fancybox/jquery.fancybox.js
INFO  Generated: fancybox/jquery.fancybox.css
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.js
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.css
INFO  Generated: fancybox/helpers/jquery.fancybox-media.js
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.js
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.css
INFO  Generated: fancybox/helpers/fancybox_buttons.png
INFO  Generated: fancybox/fancybox_sprite@2x.png
INFO  Generated: fancybox/fancybox_sprite.png
INFO  Generated: fancybox/fancybox_overlay.png
INFO  Generated: fancybox/fancybox_loading@2x.gif
INFO  Generated: fancybox/fancybox_loading.gif
INFO  Generated: fancybox/blank.gif
INFO  Generated: css/style.css
INFO  Generated: css/images/banner.jpg
INFO  Generated: css/fonts/fontawesome-webfont.woff
INFO  Generated: css/fonts/fontawesome-webfont.ttf
INFO  Generated: css/fonts/fontawesome-webfont.svg
INFO  Generated: css/fonts/fontawesome-webfont.eot
INFO  Generated: css/fonts/FontAwesome.otf
INFO  Generated: 2015/07/01/hello-world/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2015/index.html
INFO  Generated: archives/2015/07/index.html
INFO  Generated: index.html
INFO  28 files generated in 466 ms

**Comment by Xuanwo** [comment]
```
there's sytle.css in /public/css folder. But no in /css folder
```

It's OK, all files in public will be uploaded to github

**Comment by bejondshao** [comment]
That's weird. You can see my github repo doesn't have the file. It seems it uploads non-public folder files.

**Comment by Xuanwo** [comment]
```
INFO Generated: css/style.css
```
try delpoy again? It confused me that hexo didi't deploy the css file individual。

**Comment by bejondshao** [comment]
Hi @Xuanwo , yes. The log is copied from terminal. style.css is generated to public folder, I can tell. But "hexo d" doesn't commit content of /public folder

**Comment by Xuanwo** [comment]
`hexo d` just commit files in .deploy_git.
Well, I get the problem, you need to install this:
`npm install hexo-deployer-git --save`.
I'm not sure I spell it write, please check it by yourself~

**Comment by bejondshao** [comment]
yes, I've also installed it already but still

**Comment by Xuanwo** [comment]
delete the `.deploy_git` and `pbulic`, and run `hexo d -g` again?

**Comment by bejondshao** [comment]
@Xuanwo , .deploy_git/css/ really has sytle.css file

**Comment by Xuanwo** [comment]
Maybe the git did't track the css file?
Does git work well on your computer?

**Comment by bejondshao** [comment]
@Xuanwo , Thank you. It's my mistake. I ignore .css file. Sorry about that.

**Comment by bejondshao** [comment]
I'm closing this issue
