### ISSUE TITLE
tag plugin 使用錯誤, 卻沒有編譯錯誤

### ISSUE THREAD

**Issue by kkc** [hexojs/hexo#1380]
如果tag plugin的結尾錯誤, 如下
{% codeblock %}
alert('Hello World!');
{% codeblock %}

應該是要把後面那個改成{% endcodeblock %}才能編譯成功,
但是希望能夠有編譯錯誤, 而不是一片空白, 這樣很難知道哪裡寫錯

**Comment by Xuanwo** [comment]
这得问swig- -

**Comment by kkc** [comment]
swig嗎? 好的我去找找～

**Comment by tommy351** [comment]
Actually Hexo uses Nunjucks for tag plugins in 3.0 which provided similar syntax as Swig and async rendering.

**Comment by Xuanwo** [comment]
@kkc Hello, any update?

**Comment by kkc** [comment]
@Xuanwo I didn't investigate it cause I saw it is [no longer maintained] (https://github.com/paularmstrong/swig/issues/628)

**Comment by leesei** [comment]
I do see `Template render error` if I used the wrong tag.
