### ISSUE TITLE
tag和catalog的生成方式

### ISSUE THREAD

**Issue by deciia** [hexojs/hexo#1383]
coding上用hexo发现的一个问题，中文目录和标签404错误。
https://coding.net/u/coding/p/Coding-Feedback/topic/38480
是否可以改进生成方式，目录和标签页面面为index.html，目录和标签名作为网页的title显示。

**Comment by Xuanwo** [comment]
这并不是Hexo的问题，不支持中文路径是Coding那边的系统环境问题吧

**Comment by deciia** [comment]
嗯，hexo有办法对目录或标签作中英文本地化，或者生成的机制还有调整的可能么。

**Comment by Xuanwo** [comment]
隐约记得有个插件可以把中文转成英文来着，你找找看吧，生成机制不太可能改

**Comment by deciia** [comment]
目录和标签全部用英文的，但是中文环境下会使用Language那个文件进行转化。

**Comment by deciia** [comment]
好吧，大概看了一下没找到，可以帮我留心一下么。
deciia@qq.com :)
