### ISSUE TITLE
3.1.1 hexo generate 之后，浏览器打开locoalhost:4000显示Cannot GET /，hexo deploy之后也没有显示

### ISSUE THREAD

**Issue by muwan** [hexojs/hexo#1384]
昨天刚安装，并且安装了以下模块
`npm install hexo-server --save`
`npm install hexo-deployer-git --save`
`npm install hexo-generator-feed@1 --save`
`npm install hexo-generator-sitemap@1 --save`
生成静态页面后，本地预览显示Cannot GET /
把内容部署到github后也没有什么显示。
麻烦指教一下，谢谢了！

**Comment by Xuanwo** [comment]
你执行了npm install么？

**Comment by muwan** [comment]
好像只执行了hexo init \xxxx\xx
我重新试一下

**Comment by muwan** [comment]
执行了hexo init之后，我当时不是执行的npm install执行的是
`npm install hexo-deployer-git --save`

**Comment by Xuanwo** [comment]
![image](https://cloud.githubusercontent.com/assets/5351546/8614632/0cbadc94-271e-11e5-9eb6-72a6cf1d0558.png)
你要在这个目录里面进行`npm install`

**Comment by muwan** [comment]
多谢了，问题已经解决
安装到使用过程出现如下几个问题：
npm install --unsafe-perm -g hexo安装不了，
解决方法
`sudo npm install -g hexo`

3.1.1hexo init /xxx/xxxxx/目录 安装的时候，接下来需要npm install

在部署之前需要安装这些
`npm install hexo-server --save`
`npm install hexo-deployer-git --save`
`npm install hexo-generator-feed@1 --save`
`npm install hexo-generator-sitemap@1 --save`

**Comment by Xuanwo** [comment]
@muwan 现在推荐使用hexo-cli管理。
`npm install hexo-cli -g`

**Comment by allengaller** [comment]
干净的执行了
npm install hexo --save
npm install hexo-server --save

还是不行，一直是Cannot GET /
