### ISSUE TITLE
Fatal Error: use wrong file as layout template file!

### ISSUE THREAD

**Issue by creeperyang** [hexojs/hexo#1386]
When I run `hexo generate`, the result surprise me! 

**All generated html files are with the same static content(and in my situation, same js code).** After retry several times and get the same error, I try to solve the error.

Finally I locate the same static content, I found it is from my custom theme's source dir:
```shell
xxxxx/themes/material/source/_mdl/layout/layout.js
```

Wow, it **shocked** me! Why hexo adopt `xxxxx/themes/material/source/_mdl/layout/layout.js` as the layout template instead of `xxx/themes/material/layout/layout.ejs`?

After I delete the `xxxxx/themes/material/source/_mdl/layout/layout.js`, the `hexo`  finally generated successfully.

Hexo version info: 

```shell
hexo: 3.1.1
os: Linux 3.13.0-54-generic linux x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by leesei** [comment]
This seems to be a theme issue instead of hexo core issue.

**Comment by creeperyang** [comment]
Better late than never. :joy:(spend time recalling).

The situation is that I wrote my custom theme, and `Hexo` locate layout file incorrectly:

 Delete `xxx/themes/material/source/_mdl/layout/layout.js` and `Hexo` get `xxx/themes/material/layout/layout.ejs` layout file correctly.

Anyway thanks for reply.
