### ISSUE TITLE
this.url should point to directory and not index.html?

### ISSUE THREAD

**Issue by arlair** [hexojs/hexo#1387]
Hi, I noticed that the open graph code uses this.url and so for the URL:

https://hexo.io/docs/

you will get:

```
<meta property="og:url" content="https://hexo.io/docs/index.html">
```

and

```
<link rel="canonical" href="https://hexo.io/docs/index.html">
```

shouldn't these be pointing to https://hexo.io/docs/

**Comment by arlair** [comment]
I think it should be this.permalink.

**Comment by arlair** [comment]
Oh, permalinks don't work for something like the default home page root index.html file.

**Comment by mef** [comment]
Any plan to have this one solved?

Permalinks are correct for blog articles, but have extraneous `index.html` for pages...

**Comment by adamflorin** [comment]
+1

Force-appending `index.html` to page permalinks feels very '90s throwback. The user should have the option to remove!

**Comment by NoahDragon** [comment]
@mef it's on 4.0 roadmap.
