### ISSUE TITLE
似乎hexo对表格支持不好。

### ISSUE THREAD

**Issue by sharkrice** [hexojs/hexo#1388]
# 渲染前：

表格显示测试：

`<table border="1" cellpadding="1" cellspacing="0"> 
  <tbody> 
   <tr> 
    <td>width</td> 
    <td>设置<em><strong>layout viewport</strong></em>&nbsp; 的宽度，为一个正整数，或字符串"width-device"</td> 
   </tr> 
   <tr> 
    <td>initial-scale</td> 
    <td>设置页面的初始缩放值，为一个数字，可以带小数</td> 
   </tr> 
   <tr> 
    <td>minimum-scale</td> 
    <td>允许用户的最小缩放值，为一个数字，可以带小数</td> 
   </tr> 
   <tr> 
    <td>maximum-scale</td> 
    <td>允许用户的最大缩放值，为一个数字，可以带小数</td> 
   </tr> 
   <tr> 
    <td>height</td> 
    <td>设置<em><strong>layout viewport</strong></em>&nbsp; 的高度，这个属性对我们并不重要，很少使用</td> 
   </tr> 
   <tr> 
    <td>user-scalable</td> 
    <td>是否允许用户进行缩放，值为"no"或"yes", no 代表不允许，yes代表允许</td> 
   </tr> 
  </tbody> 
 </table>`
# 渲染后：

```
<div class="article-entry" itemprop="articleBody">
<p>表格显示测试：</p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<table border="1" cellpadding="1" cellspacing="0">
    <tbody>
        <tr>
            <td>width</td>
            <td>设置<em><strong>layout viewport</strong></em>&nbsp; 的宽度，为一个正整数，或字符串”width-device”</td>
        </tr>
        <tr>
            <td>initial-scale</td>
            <td>设置页面的初始缩放值，为一个数字，可以带小数</td>
        </tr>
        <tr>
            <td>minimum-scale</td>
            <td>允许用户的最小缩放值，为一个数字，可以带小数</td>
        </tr>
        <tr>
            <td>maximum-scale</td>
            <td>允许用户的最大缩放值，为一个数字，可以带小数</td>
        </tr>
        <tr>
            <td>height</td>
            <td>设置<em><strong>layout viewport</strong></em>&nbsp; 的高度，这个属性对我们并不重要，很少使用</td>
        </tr>
        <tr>
            <td>user-scalable</td>
            <td>是否允许用户进行缩放，值为”no”或”yes”, no 代表不允许，yes代表允许</td>
        </tr>
    </tbody>
</table>

</div>
```

这么多个<br /> 渲染出来有一大段空白，太难看了。

你可以看这个[http://sharkrice.github.io/2015/07/14/hello-world/]

**Comment by Xuanwo** [comment]
参数|描述
---|---|---
width|	设置layout viewport  的宽度，为一个正整数，或字符串"width-device"
initial-scale|	设置页面的初始缩放值，为一个数字，可以带小数
minimum-scale|	允许用户的最小缩放值，为一个数字，可以带小数
maximum-scale|	允许用户的最大缩放值，为一个数字，可以带小数
height|	设置layout viewport  的高度，这个属性对我们并不重要，很少使用
user-scalable|	是否允许用户进行缩放，值为"no"或"yes", no 代表不允许，yes代表允许

建议还是用Markdown的语法，目前Hexo会渲染出很多<br>，作者正在解决中。
上面的表格源代码是：
```
参数|描述
---|---|---
width|	设置layout viewport  的宽度，为一个正整数，或字符串"width-device"
initial-scale|	设置页面的初始缩放值，为一个数字，可以带小数
minimum-scale|	允许用户的最小缩放值，为一个数字，可以带小数
maximum-scale|	允许用户的最大缩放值，为一个数字，可以带小数
height|	设置layout viewport  的高度，这个属性对我们并不重要，很少使用
user-scalable|	是否允许用户进行缩放，值为"no"或"yes", no 代表不允许，yes代表允许
```

**Comment by cikichen** [comment]
原来是hexo的bug，我从wp迁移过来后发现我的文章凡是有表格的都有一大段空白，还以为是我的md的问题，目前是否有解决方案呢？

**Comment by Xuanwo** [comment]
修复中

**Comment by bianle** [comment]
@Xuanwo 的方法可行，但是遇到表格内容中含有竖线的转义不起作用
如：

参数|描述
---|---
aa\|bb| cc

源码：
```
参数|描述
---|---
aa\|bb| cc
```

**Comment by Alsiso** [comment]
此问题已经修复了吗？ 为什么问题被关闭了？

**Comment by Xuanwo** [comment]
@Alsiso Sorry，操作失误

**Comment by wanggnim** [comment]
这说来说去也没说清楚,hexo支持表格的bug究竟修复了没有

**Comment by telnetning** [comment]
3.1.1，没有修复

**Comment by Xuanwo** [comment]
@sharkrice , 我使用你给出的例子在完全新建的Hexo目录中测试，没有发现有多余的空行。

我插入的代码如下：
```
<table border="1" cellpadding="1" cellspacing="0"> <tbody> <tr> <td>width</td> <td>设置<em><strong>layout viewport</strong></em>&nbsp; 的宽度，为一个正整数，或字符串"width-device"</td> </tr> <tr> <td>initial-scale</td> <td>设置页面的初始缩放值，为一个数字，可以带小数</td> </tr> <tr> <td>minimum-scale</td> <td>允许用户的最小缩放值，为一个数字，可以带小数</td> </tr> <tr> <td>maximum-scale</td> <td>允许用户的最大缩放值，为一个数字，可以带小数</td> </tr> <tr> <td>height</td> <td>设置<em><strong>layout viewport</strong></em>&nbsp; 的高度，这个属性对我们并不重要，很少使用</td> </tr> <tr> <td>user-scalable</td> <td>是否允许用户进行缩放，值为"no"或"yes", no 代表不允许，yes代表允许</td> </tr> </tbody> </table>
```

![image](https://cloud.githubusercontent.com/assets/5351546/12314354/4e15104e-baab-11e5-8bbd-9b9823c0dbce.png)

![image](https://cloud.githubusercontent.com/assets/5351546/12314362/625cc056-baab-11e5-897e-fc6f6aa3bb2f.png)

**Comment by likev** [comment]
这个问题也困扰我了两天，希望早点修复。

**Comment by brentybh** [comment]
因为 table 要加上 table class 所以不能直接用 markdown

**Comment by brentybh** [comment]
解决办法就是压缩成一行

**Comment by verymuch** [comment]
请问这个问题还没有解决吗？ 压缩成一行可编辑性太差啦

**Comment by Knight-JNXU** [comment]
现在已经 hexo 3.2.2 这个bug还是没有修复

**Comment by xu-song** [comment]
+1  这是个很难修复的bug？

**Comment by fja0kl** [comment]
Me,too

**Comment by YopheeHsin** [comment]
用了 {% raw %} {% endraw %} 包html table

**Comment by HarborZeng** [comment]
> 用了 {% raw %} {% endraw %} 包html table

666，我也在官网看到过这个，但是没想到用在这里，很佩服您
