### ISSUE TITLE
hexo server prints out the help message

### ISSUE THREAD

**Issue by drhayes** [hexojs/hexo#1390]
When I run `hexo server` inside an already existing repository that I've worked on before I get the help message:

```
[~/src/drhayes.io (master) ⚡] ➔  hexo server
Usage: hexo <command>

Commands:
  help     Get help on Hexo.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```

I've run `npm rm -g hexo` and `npm install -g hexo` to re-install, just in case I had an old version but that didn't fix it.

Here's the output from `hexo version` in case you need it:

    hexo-cli: 0.1.7
    os: Darwin 14.3.0 darwin x64
    http_parser: 2.3
    node: 0.12.2
    v8: 3.28.73
    uv: 1.4.2-node1
    zlib: 1.2.8
    modules: 14
    openssl: 1.0.1m

EDIT: `hexo generate` does the same thing. Looks like none of my commands are working right now.

**Comment by leesei** [comment]
You should `npm -g hexo-cli`.
`hexo` should not be installed globally, do `npm uninstall -g hexo`.
Go to your hexo site folder and `npm install hexo --save`.

But for a existing repo have you run `npm install` after clone? That should have installed `hexo` to the repo folder.

**Comment by drhayes** [comment]
Thank you for your help. I'm assuming you meant `npm install -g hexo-cli` in that first sentence?

Here are the steps I ran, just to be sure:

1. `npm uninstall -g hexo`
2. `npm uninstall -g hexo-cli`
3. `npm install -g hexo-cli`
4. `npm install --save hexo`

Running `hexo server` produces the same effect as before.

Yes, this is an existing repository in which running `hexo server` worked four months ago: http://github.com/drhayes/drhayes.io

**Comment by leesei** [comment]
Hexo split out `server` as a separate module.
Also `optimize` is causing install error.
It is recommended for you to read the latest setup guide for the updated `package.json` and `_config.yml`, or `hexo init` a new site to check the settings.
Or you could check [my repo](https://github.com/leesei/leesei.github.io).

**Comment by drhayes** [comment]
Thank you! That fixed me up! :+1:
