### ISSUE TITLE
question: how to avoid root index.html?

### ISSUE THREAD

**Issue by ghost23** [hexojs/hexo#1393]
Hi,

is it possible to prevent hexo from generating a root /index.html? I have not put an index.md in the source root folder, but still there is a root /index.html being generated.

Thanks.

**Comment by Xuanwo** [comment]
skip_render

**Comment by ghost23** [comment]
I tried that. I put / in skip_render, but that didn't work. What would I need to put in?

**Comment by chrisjlee** [comment]
AFAIK skip_render is either true or false.

**Comment by leesei** [comment]
Did you installed `generator-index`?
