### ISSUE TITLE
Add "Last-Modified" Date to HTTP Response Headers for Server (for Live.js)

### ISSUE THREAD

**Issue by Ziflin** [hexojs/hexo#1394]
Is it possible/easy to add a file's "Last-Modified" date/time to the HTTP response headers when using 'hexo server'?  I would like to be able to use [Live.js](http://livejs.com) for very easy live-reloading and it seems to require a change to the HTTP Response for either "Last-Modified" or "Etag" to detect a change to the page/file.

**Comment by leesei** [comment]
Have you tried [hexojs/hexo-livereload](https://github.com/hexojs/hexo-livereload) or [hexojs/hexo-browsersync](https://github.com/hexojs/hexo-browsersync)?

**Comment by Ziflin** [comment]
Yes, both seemed to have issues of some sort.  Livereload seems dead and browsersync has a noticeable startup delay and bloat.
