### ISSUE TITLE
why I can't use TOC in hexo 3.1.1

### ISSUE THREAD

**Issue by youthy** [hexojs/hexo#1395]
I follow the steps in this [blog](http://kuangqi.me/tricks/enable-table-of-contents-on-hexo/)
but the result is my posts are like this ![](http://7jppvr.com1.z0.glb.clouddn.com/123.jpg).
even I revert the article.ejs,it can't roll back. I do it successfully when I use hexo the version in 2.X.
can anyone tell me how to use TOC?

**Comment by justincalleja** [comment]
I am using [hexo-toc](https://github.com/bubkoo/hexo-toc).

Simply include: `<!-- toc -->` in .md file where you want the toc to be generated. I'm using hexo 3.1.1 and it seems to be working fine.

**Comment by youthy** [comment]
hi.When I use hexo-toc,it seems not work well.Can you tell me where I make mistakes?
the post is
```
title: test
date: 2015-07-20 10:10:16
tags:test1
toc:true
---

<!-- toc -->

###title1

hahaha

###title2 

hahaha

###title3

balabala
```

then no toc generated.
![](http://7jppvr.com1.z0.glb.clouddn.com/下载%20(1).jpg)

**Comment by justincalleja** [comment]
I don't think you need `toc:true` in meta data at top of file.

IIRC, all I did to get hexo-toc to work was to install it `npm install hexo-toc --save` and include it in .md files: `<!-- toc -->`.

Did you perhaps forget to install it?

**Comment by youthy** [comment]
I finally find the mistake.I just write bad form of title.It should be `### title` not `###title`.
thks for you help.

**Comment by youthy** [comment]
but why the old method which use article.ejs can't work out?

**Comment by justincalleja** [comment]
:+1:  no idea re toc() in .ejs. It's a helper function which Hexo needs to expose if you're going to use it in a template file.

I find the plugin to be a better solution as I prefer not having a TOC when the post is short enough.
