### ISSUE TITLE
{% %}  parsing error

### ISSUE THREAD

**Issue by zhourongyu** [hexojs/hexo#1400]
`{% %}` is used in template for python or other.  When it appears(quote from official documentation
)：

    {% autoescaping false %}
    autoescaping is disableed here
    {{ will_not_be_escaped }}{% endautoescape %}    

hexo server throw the error:
    FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html

**Comment by Xuanwo** [comment]
Thanks.
