### ISSUE TITLE
Relative urls are incorrectly generated since Hexo 3.1.0

### ISSUE THREAD

**Issue by LouisBarranqueiro** [hexojs/hexo#1401]
Since Hexo 3.1.0, relative url are incorrectly generated. On home page, links of all posts are : `year/month/day/index.html` instead of `year/month/day/title-of-the-post/index.html`. I use <%- url_for(post.path) %> to generate it. With Hexo 3.0.1, it works fine.  
Here is my package.json (dependencies) :  

``` js
"dependencies": {
    "hexo": "3.0.1",
    "hexo-deployer-git": "0.0.4",
    "hexo-deployer-heroku": "0.0.3",
    "hexo-generator-archive": "^0.1.0",
    "hexo-generator-category": "^0.1.0",
    "hexo-generator-feed": "^1.0.1",
    "hexo-generator-index": "0.1.2",
    "hexo-generator-tag": "^0.1.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-stylus": "^0.2.0",
    "hexo-server": "^0.1.2",
    "hexo-util": "^0.1.6"
  }
```

**Comment by Xuanwo** [comment]
@LouisBarranqueiro I use `url_for(post.link)` which works fine.
