### ISSUE TITLE
No momentum page scrolling on mobile?

### ISSUE THREAD

**Issue by ws-stage** [hexojs/hexo#1402]
When browsing the hexo site on iOS, flick/momentum scroll doesn't work.

Is this a problem with parts of hexo, or just a bug in the site?

I ask because I've just started looking at hexo of mobile is kind of critical.

**Comment by leesei** [comment]
I suppose that is a feature of the theme you choose?

**Comment by Xuanwo** [comment]
Closed for no more update.
