### ISSUE TITLE
markdown bug when phasing post include '%{%k}'

### ISSUE THREAD

**Issue by reee** [hexojs/hexo#1404]
the full post cause the error is:

<pre>
layout: post
title: "在centos 6上安装freeradius并启用流量限制"
date: 2013-01-04 16:00
tags:
 - Linux
 - Freeradius
---
freeradius，根据wikipedia的介绍，是一个高度模块化，而且高性能的RADIUS套件，是一个普遍应用的认证+计费后端。作为一个卖VPN的奸商，无疑配置好一个freeradius服务器来认证是一个省力省事的事情。

## 安装freeradius
直接通过yum安装即可：

	#Centos 5下请安装freeradius2
	yum install freeradius
然后为freeradius创建数据库，您也可以利用/etc/raddb/sql/mysql下的admin.sql来创建数据库并新建用户：

	 mysql -uroot -p
	CREATE DATABASE radius;
	GRANT ALL ON radius.* TO radius@localhost IDENTIFIED BY "radpass";
	exit
并且导入相应的表结构：

	cd /etc/raddb/sql/mysql
	mysql -uroot -p radius < schema.sql.sql

## 相关配置
为freeradius启用sql支持：

	vim /etc/raddb/radiusd.conf
	#取消掉	 $INCLUDE sql.conf	和	$INCLUDE sql/mysql/counter.conf 前的注释。
修改default site（我们要用到的）的属性：
	/etc/raddb/sites-enabled/default
	#找到authorize {}模块，注释掉files（159行），去掉sql前的#号（166行）
	#找到accounting {}模块，注释掉radutmp(385行),注释掉去掉sql前面的#号(395行)。
	#如果需要修改同时在线数和固定IP地址，请自行阅读剩下的配置文件
修改sql连接设置：
	vi /etc/raddb/sql.conf
	#您需要关注的有：
	#设置数据库类型
	database = "mysql"
	#加载对应的驱动
	driver = "rlm_sql_${database}"
	#mysql 服务器地址
    server = "localhost"
    #mysql用户名
	login = "radius"
	#对应的密码
    password = "radpass"
	#剩下的则是一些表名称的指定，自己看情况修改就行了。
然后需要允许认证客户端连接。默认freeradius只允许本地客户端发起认证，这里假设有一台提供VPN服务的服务器名字是red，ip为1.2.3.4，设置的共享密码为asdf1234，其中IP必须为客户端IP，shortname是可以随意设置的，客户端连接的时候会被要求提供secret：

	vi /etc/raddb/clients.conf
在尾巴加上：

	client 1.2.3.4 {
			secret          = asdf1234
			shortname       = red
	}

## 配置流量统计功能
添加流量统计器：

	vim /etc/raddb/sql/mysql/counter.conf
添加一个以月为单位的流量计算器，这里除以1048576是将流量以Mb计算：

sqlcounter monthlytrafficcounter {
  counter-name = Monthly-Traffic
  check-name = Max-Monthly-Traffic
  reply-name = Monthly-Traffic-Limit
  sqlmod-inst = sql
  key = User-Name
  reset = monthly
  query = "SELECT cast(SUM(cast(acctinputoctets as decimal)/1048576 +cast(acctoutputoctets as decimal)/1048576)as signed) FROM radacct WHERE UserName='%{%k}' AND UNIX_TIMESTAMP(AcctStartTime) > '%b'"
}

添加字典

	vim /etc/raddb/dictionary
添加下面两行

	ATTRIBUTE Max-Monthly-Traffic 3003 integer
	ATTRIBUTE Monthly-Traffic-Limit 3004 integer
启用Traffic Counter

	vim /etc/raddb/sites-enabled/default
在authorize里添加monthlytrafficcounter(上面添加的流量统计器)，像下面这样

	authorize {
		...
		monthlytrafficcounter
	}
剩下就是修改用户权限了，这里直接[抄一个过来](http://wangyan.org/blog/freeradius-pptp-l2tp-html.html)：

	# 添加用户test，密码test，注意是在radchec表
	INSERT INTO radcheck (username,attribute,op,VALUE) VALUES ('test','Cleartext-Password',':=','test');
	 
	# 将用户test加入VIP1用户组
	INSERT INTO radusergroup (username,groupname) VALUES ('test','VIP1');
	 
	# 限制同时登陆人数，注意是在radgroupcheck表
	INSERT INTO radgroupcheck (groupname,attribute,op,VALUE) VALUES ('VIP1','Simultaneous-Use',':=','3');
	 
	# 添加NAS
	INSERT INTO radius.nas VALUES ('1','192.168.8.129','Toky', 'other', NULL ,'linodecn.net',NULL ,NULL ,'RADIUS Client');
	 
	# 其他（选做）
	INSERT INTO radgroupreply (groupname,attribute,op,VALUE) VALUES ('VIP1','Auth-Type',':=','Local');
	INSERT INTO radgroupreply (groupname,attribute,op,VALUE) VALUES ('VIP1','Service-Type',':=','Framed-User');
	INSERT INTO radgroupreply (groupname,attribute,op,VALUE) VALUES ('VIP1','Framed-Protocol',':=','PPP');
	INSERT INTO radgroupreply (groupname,attribute,op,VALUE) VALUES ('VIP1','Framed-MTU',':=','1500');
	INSERT INTO radgroupreply (groupname,attribute,op,VALUE) VALUES ('VIP1','Framed-Compression',':=','Van-Jacobson-TCP-IP');
</pre>

i run into this error:
Template render error: unknown block tag: k

**Comment by leesei** [comment]
Use backtick:
<pre>
```
{%k}
```
</pre>
or [`{% raw %}` block](https://hexo.io/docs/troubleshooting.html#Escape_Contents)
