### ISSUE TITLE
If hexo have possible optimizing for professional photoing publishing?

### ISSUE THREAD

**Issue by Renlong-Yin** [hexojs/hexo#1407]
As an professional fine art photographer, the great mass of (90%) working post would be `Photoing`, as well as 10% articles. Photo Publishing have dissimilar process feature from Text Posting, including the dispensable title, date & lower directory, but demand reliable organization. The other way around, above feathers are normally necessary in Text and Code Posting.

I am wandering If there have solution for Photo Posting independent in publishing from Hexo normal Post? Such as when command `hexo new photo`, there will publish a post **without** `class=post-header` (only including `class=post-body`)?

The name of this theme is [NexT](https://github.com/iissnan/hexo-theme-next/), and post layout folder located in `/blog/themes/next/layout/_macro`

**Comment by Xuanwo** [comment]
Yes, you just need to modify your theme

**Comment by Renlong-Yin** [comment]
Some problem occured to create html structure based on `post.swig`.

While input `hexo new post <title>` and `hexo g`, will they resolve `/theme/layout/post.swig`? Is that all right?

If the answer is yes, while input homologous command `hexo new pic <title>`, they should resolve `/theme/layout/pic.swig`. But unfortunately, the result is negative. They resolve `/theme/layout/post.swig` instead of `/theme/layout/pic.swig`, which made me pretty confused. Could you tell me which file be read and generated while input `hexo new [layout] <title>`? Can I make some track on it?

**Comment by tommy351** [comment]
You should set `layout: pic` in your post and add a corresponding layout file in the theme.

**Comment by Renlong-Yin** [comment]
I created file `pic.swig` under `/theme/layout` and another `pic.swig` under `/theme/layout/_macro/`, the file structure based on original theme [NexT](https://github.com/iissnan/hexo-theme-next/); Added `pic.md` under `blog/scaffolds`. I wander the processing is correct?

Actually, I need both default `layout: post` and new created `layout: pic`.

**Comment by leesei** [comment]
That is the idea. But you have to properly implement `pic.swig` to render your photos.

What's meant by:
> I need both default `layout: post` and new created `layout: pic`

Remember you cannot specify two layout for a single post.
