### ISSUE TITLE
cheerio converts all tag names to lowercase

### ISSUE THREAD

**Issue by WolfgangKluge** [hexojs/hexo#1408]
You use [cheeriojs/cheerio](https://github.com/cheeriojs/cheerio) several times - please use option `xmlMode` to prevent cheerio from lowercasing all tag names (and attributes).

The problem is not in HTML files, but in XML files (and SVG-files) I want to provide as assets.

**Comment by leesei** [comment]
@tommy351 Any concerns for using `xmlMode`?
