### ISSUE TITLE
Emoji doesn't work

### ISSUE THREAD

**Issue by JavaProgrammerLB** [hexojs/hexo#1409]
I used a emoji tag ": pig : ",what I want is :pig:,but i get only the String;I used the emoji in the true synate ;what's the matter ,how can i use emoji in hexo?

**Comment by leesei** [comment]
This is not supported by Hexo.
A tag plugin can provide this feature.

**Comment by JavaProgrammerLB** [comment]
Besides, l am still the new guy;What is the  process to dev this plugin?
Can you give me some suggestion?

**Comment by chrisjlee** [comment]
@JavaProgrammerLB I'm still learning too. But I would start looking at the plugin folder. The guys here have written some existing plugins. https://github.com/hexojs/hexo/tree/master/lib/plugins
