### ISSUE TITLE
Provide complex Taxonomy support like Hugo

### ISSUE THREAD

**Issue by OdinsHat** [hexojs/hexo#1411]
The static site generator Hugo provides much more flexibility than simply "tags" and "categories". You can see the full description and power it provides at [their site](http://gohugo.io/taxonomies/overview/).

This would be great in the following examples to hold related posts/pages:
* **Series**: "My Journey to Python Series" with several blog posts.
* **Projects**: "Hexo Project" or "My Arduino Project". each having several pages or posts.
* **Actor, Director, Film**: For complex catalogue sites rather than blogs. Enabling people to create multiple related and cross-referenced taxanomies.

You can see how Hugo have done it at [their site](http://gohugo.io/taxonomies/overview/). I suggest looking there for inspiration. I'd love to see this as part of Hexo. I've also attached an example:

![screen shot 2015-07-25 at 14 01 34](https://cloud.githubusercontent.com/assets/1061673/8889534/c34d5db6-32d5-11e5-949c-4f83401536cf.png)

**Comment by leesei** [comment]
See #828
