### ISSUE TITLE
Display error with `|` in table

### ISSUE THREAD

**Issue by kid1412z** [hexojs/hexo#1412]
Display error with `|` in table

**Comment by kid1412z** [comment]
hexo: 3.0.1
os: Darwin 14.4.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

**Comment by Xuanwo** [comment]
use `&brvbar;` instead of `|`.
`|` has special meaning in table with markdown.
