### ISSUE TITLE
安装Hexo时出警告

### ISSUE THREAD

**Issue by wwff** [hexojs/hexo#1414]
![warn](https://cloud.githubusercontent.com/assets/12774603/8905390/81f9a72e-3498-11e5-8d1d-000d1b9cd838.jpg)

在执行npm install -g hexo-cli出了警告，谢谢您的解答帮助

**Comment by wizardbyron** [comment]
全局更新一下你的npm所有包试试

**Comment by wwff** [comment]
好的，谢谢

**Comment by markmamian** [comment]
我也一样，更新npm是输入nam update吗，还是不行

**Comment by luodaoyi** [comment]
在国内的话推荐用淘宝的镜像：
```
npm install hexo-cli -g --registry=https://registry.npm.taobao.org
npm install --registry=https://registry.npm.taobao.org
```

**Comment by wizardbyron** [comment]
npm update -g
