### ISSUE TITLE
Possible error in helper relative_url.js

### ISSUE THREAD

**Issue by ghost23** [hexojs/hexo#1416]
Hi,

i was having an issue with the generation of relative links in my paginations. I think, this line:

https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/relative_url.js#L23

is wrong, it says:

`if (outLength > 1 && !out[outLength - 1] && !out[outLength] - 2){`

I think it should be (at the end, outLength -2):

`if (outLength > 1 && !out[outLength - 1] && !out[outLength - 2]){`

If I change that, my pagination works correctly.

**Comment by cgmartin** [comment]
Looks like this is fixed in `master` but hasn't been published for a release version yet (current 3.1.1)
