### ISSUE TITLE
区块内的文字无法自动换行

### ISSUE THREAD

**Issue by wangyufeng0615** [hexojs/hexo#1418]
![qq 20150729185519](https://cloud.githubusercontent.com/assets/7182112/8955932/b92e27f6-3623-11e5-8f5b-01b447c94fd4.png)

是指markdown中文字前有TAB所表现出的这种区块。

不知道是不是主题的问题，主题是jacman。

**Comment by Xuanwo** [comment]
理论上来讲，是主题问题

**Comment by leesei** [comment]
Please port your sample md.

**Comment by Xuanwo** [comment]
更新一下jacman试试，印象中，我记得主题开发者开过issues修复过这个问题

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
