### ISSUE TITLE
why img tag require an absolute url for image path

### ISSUE THREAD

**Issue by LouisBarranqueiro** [hexojs/hexo#1420]
Why img tag require an absolute urls for image path. The path regex is : `((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)`

Is there a reason to this like display images in a RSS client for example? because it not user-friendly.

**Comment by pythondetective** [comment]
I am having trouble with this too I do not know why?

**Comment by LouisBarranqueiro** [comment]
great :D

**Comment by NoahDragon** [comment]
@LouisBarranqueiro does the issue still persist in the latest version?
