### ISSUE TITLE
jade模板下category	不起作用

### ISSUE THREAD

**Issue by noodlefighter** [hexojs/hexo#1422]
```
each c in site.categories.toArray()
  p c.category
```

渲染出一堆`<p></p>`

hexo 3.11
hexo-renderer-jade@0.1.0

**Comment by leesei** [comment]
You can use `debug.log()` to dump the `site` object.

https://github.com/hexojs/hexo/commit/a50719b9c2871e5d3141919172436419fdae1580

**Comment by noodlefighter** [comment]
@leesei 我将环境重新安装了一遍。。问题解决了。。莫名其妙的。
