### ISSUE TITLE
img label do not work well

### ISSUE THREAD

**Issue by noodlefighter** [hexojs/hexo#1426]
file`/_post/test.md`,`/_post/test/test.gif`
I need to show image with `width=100`.
like:`{% img /test/test.gif 100 %}`

THEN i try to use relative path...
```
{% img test.gif 100 %}
{% img \test.gif 100 %}

![image](test.gif)
![image](\test.gif)

{% img {% asset_path test.gif %} 100 %}
```
but..
generated:
```
<a href="null"><img class="test.gif 100"></a>
<a href="null"><img class="\test.gif 100"></a>
<p><a href="test.gif"><img src="test.gif" alt="image"></a><br><a href="\test.gif"><img src="\test.gif" alt="image"></a></p>
<a href="null"><img class="{% asset_path test.gif"></a> 100 %}
```

**Comment by mrSummerSun** [comment]
It might be 
![img](/img.gif)

**Comment by mrSummerSun** [comment]
`![img] (/imgpath/img.gif) `

**Comment by Xuanwo** [comment]
your can insert it with html

**Comment by leesei** [comment]
Does @mrSummerSun's code fix the issue?

**Comment by noodlefighter** [comment]
@mrSummerSun @leesei 
i think it is a bug.
`{% img \test.gif 100 %}` should be equivalent to `{% img /test/test.gif 100 %}`

the ouput like `<a href="null"><img class="\test.gif 100"></a>`is certainly something wrong.

**Comment by leesei** [comment]
Are you aware that `\` is different from `/` in URL?
Are you using [`post_asset_folder`](https://hexo.io/docs/asset-folders.html)?

Here's how I work with asset without using `post_asset_folder`:
- create a folder `asset/` in `source`
- use `{% img /asset/test.jpg %}` or `![image](/asset/test.jpg)` to embed the image

Also note that tags cannot be nested, `{% img {% asset_path test.gif %} 100 %}` will never work.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
