### ISSUE TITLE
can not use "$" in title

### ISSUE THREAD

**Issue by marguerite** [hexojs/hexo#1427]
Hi,

I'm writing a post named "reseach on $1 value changes in rpm's %postun stage when reinstallation"...I'm not trolling, it's really a case...

then even I "\\$1" it is still ignored...

**Comment by leesei** [comment]
Please provide more info.
You have problem creating the post or generating the page?

**Comment by marguerite** [comment]
create the page…the xxxx.md stuff. the title in the post is okay

**Comment by leesei** [comment]
What platform are you using. Most shell will interpret `$` character.
I have no problem with slash escape or single quote:
```sh
hexo n "Show me the \$abc" #OR
hexo n 'Show me the $abc'
INFO  Created: ./source/_posts/show-me-the-abc.md
```

This is expected as `$` is not a save character for naming file so it is deleted.

**Comment by marguerite** [comment]
if it is intended，I am okay with that
