### ISSUE TITLE
同时deploy到gitcafe和github的问题。

### ISSUE THREAD

**Issue by youthy** [hexojs/hexo#1431]
```
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    git@github.com:youthy/youthy.github.io.git,master
    git@gitcafe.com:youthy/youthy.git,gitcafe-pages
```
我的写法是这样，如果让其中任意一个注释掉都能成功，但是两个同时在的话会报错
> error: src refspec master:master git@gitcafe.com does not match any.
error: 无法推送一些引用到 'git@github.com:youthy/youthy.github.io.git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html

如果将以上形式写为
```
 repo: 
    github: https://github.com/youthy/youthy.github.io.git,master
    gitcafe: https://gitcafe.com/youthy/youthy.git,gitcafe-pages
```
就可以成功，但是需要每次都输入两个地方的密码很麻烦。

**Comment by leesei** [comment]
Does this work?

```
repo: 
    github: git@github.com:youthy/youthy.github.io.git,master
    gitcafe: git@gitcafe.com:youthy/youthy.git,gitcafe-pages
```

**Comment by youthy** [comment]
yeah, it works!
thks~~
额，谢谢，你应该是国人 -_-

**Comment by leesei** [comment]
額.對
