### ISSUE TITLE
Nothing happens after 'hexo init blog'

### ISSUE THREAD

**Issue by imcaffrey** [hexojs/hexo#1433]
Nothing happens after 'hexo init blog'

The problem Im facing is that after I `typed hexo init blog` in my terminal, nothing happens.

No response in the terminal and there is no dir named blog.

What was going wrong here?

Thanks

**Comment by imcaffrey** [comment]
Finally I solved this by changing the first line in the `/usr/local/bin/hexo` file.

It was originally like this : `#!/usr/bin/env node`

I changed the node into nodejs

and it's working.

**Comment by hhgz9527** [comment]
Thanks!   @imcaffrey

**Comment by imcaffrey** [comment]
oops that I forgot to close this.
I reinstalled nodejs as the nodejs.org asked on my ubuntu and since then this problem doesn't occur anymore.
