### ISSUE TITLE
hexo generates no html

### ISSUE THREAD

**Issue by Pooria-H** [hexojs/hexo#1434]
First I ran "hexo migrate wordpress <source>" command, Files imported to "source" folder allright.
Then I ran "hexo generate", Files from "source" folder copied to "public" folder with no changes! (still markdown files and no html).

Shouldn't it generate html files or i'm missing something?
I should mention there is no index file as homepage so i can preview my site.

**Comment by leesei** [comment]
Post your `package.json` and did you run `npm install` to install the renderer plugin?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
