### ISSUE TITLE
I'd like to run one Hexo for my entire site, including a blog on a subdomain.

### ISSUE THREAD

**Issue by bnb** [hexojs/hexo#1435]
Hey there.

I'd like to know if it's possible to run one Hexo installation for a TLD and a subdomain of that TLD. I want to import my vanilla HTML file at http://bnb.im to Hexo as the index, but also have my blog at http://blog.bnb.im with the same Hexo instance. Can this be done easily?

Thanks.

**Comment by Xuanwo** [comment]
Have no idea.
But you can do it by two different hexo instances, just need to write a sh to reduce the operations.

**Comment by leesei** [comment]
I think you mean two hexo site?
Hexo instance is only used for static page generation. It is unrelated to how you deploy the site.

As to you question, the answer is *yes*.
You have two sets of static sites, you just have to configure `_config.yml` and your web server correctly.
