### ISSUE TITLE
文章在首页显示时，不显示目录

### ISSUE THREAD

**Issue by wangyufeng0615** [hexojs/hexo#1436]
自动生成的文章目录挺漂亮的，但是但首页就不显示，需要点开文章才能显示。但实际上，无论在首页还是点开，看的都是全文。

可以在让文章在首页时就显示目录吗？

**Comment by iissnan** [comment]
这看起来是主题相关的问题。在你所使用的主题那提 issue 更容易得到解决。

**Comment by Xuanwo** [comment]
自己修改主题吧，如果不知道到怎么修改，建议去对应的主题寻求帮助
