### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by jounglovely** [hexojs/hexo#1438]
各位，这几天用Hexo generate命令生成静态文件时，总是会出现如下错误：
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EIO, read
    at Error (native)
请问这是怎么回事？

**Comment by Xuanwo** [comment]
apparently EIO can occur when trying to write to a disconnected console device.

**Comment by jounglovely** [comment]
I have solved this problem,maybe caused by some damaged theme files. Because I found some files couldn't be opened, then I deleted and cloned them again. finally everything got be ok.
Thks a lot.
