### ISSUE TITLE
hexo server not working

### ISSUE THREAD

**Issue by RackerJack** [hexojs/hexo#1442]
hi

i have migrated from a different server installed hexo-cli globally 
used npm install on the directory but when i try to use `hexo server` it seems like hexo-cli doesnt know what i mean

```
bash-4.1$ hexo server
Usage: hexo <command>

Commands:
  help     Get help on Hexo.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --safe    Disable all plugins and scripts
  --silent  Hide output on console
```
For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

**Comment by Xuanwo** [comment]
`npm install hexo-server --save`

**Comment by RackerJack** [comment]
```
[ node@srv0a.exnet.systems /srv/node/dumbquot.es-2345 ]$> npm install hexo-server --save
hexo-server@0.1.2 node_modules/hexo-server
├── object-assign@2.1.1
├── open@0.0.5
├── mime@1.3.4
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── bluebird@2.9.34
├── morgan@1.6.1 (basic-auth@1.0.3, depd@1.0.1, on-headers@1.0.0, on-finished@2.3.0, debug@2.2.0)
├── connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@0.4.0)
├── compression@1.5.2 (bytes@2.1.0, vary@1.0.1, on-headers@1.0.0, compressible@2.0.5, debug@2.2.0, accepts@1.2.12)
└── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
[ node@srv0a.exnet.systems /srv/node/dumbquot.es-2345 ]$> hexo server
Usage: hexo <command>

Commands:
  help     Get help on Hexo.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```

**Comment by Xuanwo** [comment]
https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0

It seems like your are not in a hexo floder

**Comment by philippkeller** [comment]
I have the same problem. I did everything in https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0 and I even did a complete uninstall:

    for package in `ls node_modules`; do npm uninstall $package; done;

but when I run `hexo server` I see the same output as @RackerJack

**Comment by LumpyChen** [comment]
@philippkeller 
+1
I think it's not simple path problem,
Since I ran the binary file directly from the project `node_modules` and got the same consequence.
There might be some compatible errors with server dependencies.

**Comment by kenspirit** [comment]
@LumpyChen Looks like I am having the same case with you.  But I haven't found out which sentence yet.

**Comment by kenspirit** [comment]
looks like it's the plugins line

**Comment by LumpyChen** [comment]
@kenspirit 
Yep plugins line
The problem is that the plugin line in `_config.yml` causes `hexo-cli` to ignore the whole project...

**Comment by xiaohk** [comment]
Any solutions?

**Comment by txd159** [comment]
In hexo **_config.yml** , `hexo-server` must be included if uncomment the parameter `plugins` . Hexo server is considered as a plugin
```
plugins:
- hexo-server
- any-other-plugin
```

**Comment by abusedmedia** [comment]
Still having issues. 
Adding hexo-server in plugins, the server runs but got a template render error, while removing the whole plugins def in _config.yml everything works as expected.

**Comment by gztchan** [comment]
@abusedmedia @xiaohk @philippkeller 

Here is the bullet.

Step 1, make sure `package.json` has the following:

```json
{
  "hexo": {
    "version": "3.6.0"
  }
}
```

Step 2, add `hexo-server` into plugins

```yml
plugins:
  - hexo-server
```

**Comment by liadbiz** [comment]
Same issue here. My hexo version is 3.6.0,  and my solution:

step 1: 

```bash
npm instal hexo-server --save
```

step 2:

add such lines to `_config.yml`

```
plugins:
  - hexo-server
```

Things will be right then.

If you found your `hexo d` do not work then, you can solve it by:

step 1:

```bash
npm install hexo-deployer-git --save
``` 

step 2:

add such lines to `_config.yml`

```bash
plugins:
  - hexo-server
  - hexo-deployer-git
```

I think such things sould be mentioned in the doc, but actually not now.

**Comment by sayoojsamuel** [comment]
> In hexo **_config.yml** , `hexo-server` must be included if uncomment the parameter `plugins` . Hexo server is considered as a plugin
> 
> ```
> plugins:
> - hexo-server
> - any-other-plugin
> ```



> In hexo **_config.yml** , `hexo-server` must be included if uncomment the parameter `plugins` . Hexo server is considered as a plugin
> 
> ```
> plugins:
> - hexo-server
> - any-other-plugin
> ```
Worked for me.  Thanks a lot!

**Comment by sayoojsamuel** [comment]
> In hexo **_config.yml** , `hexo-server` must be included if uncomment the parameter `plugins` . Hexo server is considered as a plugin
> 
> ```
> plugins:
> - hexo-server
> - any-other-plugin
> ```
Worked for me!  Thanks a lot

**Comment by godIsAProgrammer** [comment]
> In hexo **_config.yml** , `hexo-server` must be included if uncomment the parameter `plugins` . Hexo server is considered as a plugin
> 
> ```
> plugins:
> - hexo-server
> - any-other-plugin
> ```

it's work for me Thanks.

**Comment by guoyaohua** [comment]
This problem is caused by wrong "_config.yml", so please check your "_config.yml" find if there are some mistake such like Error indenting code.
