### ISSUE TITLE
执行npm install hexo-deployer-git --save 后无法使用hexo

### ISSUE THREAD

**Issue by Arnold-Hu** [hexojs/hexo#1446]
系统是 ubuntu14.04

> arnold-hu@arnoldhu-K43SV:~/personal-webpage$ nvm --version
> 0.25.4
> arnold-hu@arnoldhu-K43SV:~/personal-webpage$ nvm ls
>        v0.12.7
> node -> stable (-> v0.12.7) (default)
> stable -> 0.12 (-> v0.12.7) (default)
> iojs -> iojs- (-> N/A) (default)

正在搭建博客的时候，运行了npm install hexo-deployer-git --save想实现对git的支持，然后下完之后就出现了下面的情况
> arnold-hu@arnoldhu-K43SV:~/personal-webpage$ hexo
> /usr/bin/env: node: 没有那个文件或目录

不知道该如何解决，曾经试过重新装但还是会出现

**Comment by Xuanwo** [comment]
`npm install hexo-cli -g`

**Comment by leesei** [comment]
你的node 根本不見了， 貌似nvm 你的安裝有問題

**Comment by Arnold-Hu** [comment]
我后面看了一下，是要先输入
`$ nvm use 0.12`
才能够使用hexo，有没有办法可以不用每次用之前都输入这个，求教@Xuanwo@leesei

**Comment by Xuanwo** [comment]
`nvm alias default 0.12.0`
