### ISSUE TITLE
{%20} in the url inside parens cause FATAL error

### ISSUE THREAD

**Issue by sxw2k** [hexojs/hexo#1447]
For Example:
When I write this in the markdown:
```
[postcircumfix { }](http://doc.perl6.org/routine/{%20}#postcircumfix_{_}) 
```
then use "hexo g" but faild with multi blanks after this:
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
![snip20150813_2](https://cloud.githubusercontent.com/assets/6223240/9231071/97c22156-4115-11e5-8c3f-1b14fe4f2ee2.png)

after i remove the left  { or all all of them, that's ok.

**Comment by Xuanwo** [comment]
so don't ues it in links

**Comment by leesei** [comment]
{%20} is parsed by Nunjucks and caused the error

### Use link tag

```
{% link "postcircumfix { }" http://doc.perl6.org/routine/{%20}#postcircumfix_{_} %}
```

### URLEncode all the way

```
[postcircumfix { }](http://doc.perl6.org/routine/%7B%20%7D%23postcircumfix_%7B_%7D)
```

Also see [Make Nunjucks in posts optional · Issue #1510](https://github.com/hexojs/hexo/issues/1510)

**Comment by sxw2k** [comment]
Wonderful, Thanks
