### ISSUE TITLE
使用hexo g生成文章的问题

### ISSUE THREAD

**Issue by yutiya** [hexojs/hexo#1448]
```
- 取得数组单个元素的长度:`length=${#array_name[n]}`
```

只要在文章的markdown文件中使用这样的格式，再使用hexo g命令生成html就会出现问题

![](http://yutiya.github.io/images/hexo/bug/1.png)

**Comment by Xuanwo** [comment]
用{%raw%}{%endraw%}包裹吧

**Comment by yutiya** [comment]
```
- 取得数组单个元素的长度:```length=${#array_name[n]}```
```
这样是可以的，我只是不知道为什么会出错而已

**Comment by Xuanwo** [comment]
特殊字符吧，可能被当成参数了
