### ISSUE TITLE
Markdown渲染部分异常

### ISSUE THREAD

**Issue by XueSeason** [hexojs/hexo#1449]
运行环境：
```
hexo: 3.1.1
os: Darwin 14.4.0 darwin x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
```

Markdown标题语法
```
# 这是 H1 
```
无法渲染。依旧显示带有＃符号的标题。

**Comment by leesei** [comment]
你可以公開你的repo 嗎?
有成功過看到網頁嗎?

**Comment by XueSeason** [comment]
repo地址：https://gitcafe.com/XueSeason/XueSeason
线上地址：http://xnix.me

**Comment by Xuanwo** [comment]
正确的格式是`# 标题`，这个空格不能少

**Comment by XueSeason** [comment]
OK，这个空格我一直没有注意过。在过去的一年里，我使用Mou、Github、Ghost以及老版本的Hexo的过程中，没有空格都是可以正常渲染的。看来以后要改变这个毛病了。

**Comment by Xuanwo** [comment]
#真的吗

亲测没有空格无法渲染

**Comment by XueSeason** [comment]
https://github.com/XueSeason/MarkdownPost/blob/master/_posts/Node-js中的一个坑.md

可以参考下这个链接，曾经一篇丑文的备份。我过去一年里没用空格，确实没遇到问题。
不过还是谢谢你的回答，以后还是改下md的习惯。

**Comment by Xuanwo** [comment]
Sorry，确实是没有调查没有发言权。
不过Markdown还是推荐使用`# 标题`的表示。
