### ISSUE TITLE
Common CSS/JS for Multilingual Blogs

### ISSUE THREAD

**Issue by mspanish** [hexojs/hexo#1450]
Hey I found the best way for me to truly get a multilingual blog is to use some .bat files to run separate blogs for each language - (I can share my files if anybody wants to know how you can do this) - the CSS and JS files for all of the sites are the same though - how can I adjust hexo to add the JS and CSS to a folder that I specify, then use that folder and NOT the blogs's root folder for the /css and /js folders?

I hope I am making myself clear, as it can be a bit confusing!  For example, I have these blogs:

http://monstercoding.com/blog_en/
http://monstercoding.com/blog_es/
http://monstercoding/com/blog_it/

And I want the CSS and JS files for these blogs to reside in the root CSS and JS folders (or another root folder, like /common_blog/  - and NOT in the actual blog's subfolders, as this is really redundant.

Thanks in advance!

**Comment by mspanish** [comment]
I hacked up a solution by hard coding the CSS and JS paths directly into the EJS template. I have to use my bat file to move those files to the appropriate location for the first blog and delete the folders for all of the other blogs. It feels like an awful waste of temp file space as well as time in hexo generation but I can't see another way to do this right now. Bottom line is that multilingual blog generation hexode right now is a completely hacked up affair, there is certainly a better way to do all of this!

**Comment by stevenjoezhang** [comment]
Hello, we are studying how to modify the generator plug-in to generate multi-language blogs without running separate blogs for each language. Please join the discussion here: https://github.com/hexojs/hexo/issues/1125
Thanks!
