### ISSUE TITLE
<!--more--> cannot work in almost all themes

### ISSUE THREAD

**Issue by conndots** [hexojs/hexo#1451]
hexo version is 3.1.1.  
I've changed many themes. All posts have  tags but in the index page, all contents including the tag is shown.

**Comment by conndots** [comment]
The  tag is left, too.

**Comment by conndots** [comment]
![](http://7xiub6.com1.z0.glb.clouddn.com/self/temp屏幕快照%202015-08-16%20上午10.31.10.png)

**Comment by Xuanwo** [comment]
在前后多留一个空行试试？
看源代码中你的被错误地包裹了

**Comment by Xuanwo** [comment]
any update?

**Comment by calvinchoy** [comment]
Tried up manually add the fix. Still not working, do I have to clear some pre-compiled files first?
