### ISSUE TITLE
can't generate index.html in categories folder and  tags folder

### ISSUE THREAD

**Issue by fyales** [hexojs/hexo#1456]
I make tags folder and categories folder .But Hexo can't generate index.html in categories folder and tags folder ,but it generate index.html in archives folder ,I don't know why.
This is the _config.yml in Hexo
```xml
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
```
I use the Next theme,Here is _config.yml.
```xml
menu:
  home: /
  categories: /categories
  #about: /about
  archives: /archives
  tags: /tags
  #commonweal: /404.html
```
Thanks.

**Comment by leesei** [comment]
The generators only generate meta, but not the HTML page.
It is the responsibility of the theme to render the HTML.

**Comment by finelord** [comment]
@leesei, right. But you should let generator know what theme's pages to generate. By default, custom tags and categories pages doesn't render. 

@fyales, to enable categories and tags pages, just copy the 'categories' and 'tags' folder from your theme's _source foler into your site's source folder.

**Comment by MinweiShen** [comment]
According to the documentation, I think you need to manually generate that index page for tags.
1. go to your hexo folder
2. hexo new page tags
3. in the tags.md, add type: "tags"
4. if you don't want to have comments on that page, also add comments: false

It is the same for categories. The documentation is [here](http://theme-next.iissnan.com/theme-settings.html#categories-page)

**Comment by leesei** [comment]
@finelord As per @MinweiShen's comment, it's better to refer to the documentation of a theme which supports tags and categories index.
See also [wzpan/hexo-theme-freemind](https://github.com/wzpan/hexo-theme-freemind)

**Comment by Hearen** [comment]
As @MinweiShen pointed out, the steps 3 is quite essential. Thanks for your guys.

**Comment by eternj** [comment]
You helped me 10 years later. Thanks!

> According to the documentation, I think you need to manually generate that index page for tags.
> 
>     1. go to your hexo folder
> 
>     2. hexo new page tags
> 
>     3. in the tags.md, add type: "tags"
> 
>     4. if you don't want to have comments on that page, also add comments: false
> 
> 
> It is the same for categories. The documentation is [here](http://theme-next.iissnan.com/theme-settings.html#categories-page)
