### ISSUE TITLE
Update one article, and call filter for all articles.

### ISSUE THREAD

**Issue by morris821028** [hexojs/hexo#1457]
I build hexo default environment, and copy 5 `hello-word.md`, name `hello-world.md`, `hello-world2.md`, etc. Then, I inject this code into `blog\node_modules\hexo-renderer-ejs`

```
hexo.extend.filter.register("after_render:html", function(src, data) {
  console.log('WTF after_render');
  console.log(data);
  return src;
});
```

use `hexo server -l` to show the debug information.
- modify content of  `hello-world.md`
- `hello-world.md` -  `hello-world4.md` will be refreshed.

It wastes lots of CPU and memory resource when hundreds of articles in blog.

How to implements auto inject tag plugin javascript source, if use `hexo.extend.filter.register` to test tag exists in a article then inject javascript or css source, it will need time complexity O(N).

**Comment by tomap** [comment]
Hi,

I just checked, and I don't see that happening
Here is my package.json:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.7.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-server": "^0.3.3"
  }
}
```

Maybe that was true for older versions of hexo?

Can you retest with a more recent version of hexo? of can we close this issue?
