### ISSUE TITLE
Automatic redirect to url with protocol

### ISSUE THREAD

**Issue by Chiliec** [hexojs/hexo#1459]
When I set site url in config (`url:`) with https protocol, I expect automatic redirect to it when user go over http protocol.

**Comment by Chiliec** [comment]
I've resolved this desire in theme and purpose PR for default Hexo theme https://github.com/hexojs/hexo-theme-landscape/pull/38

**Comment by Xuanwo** [comment]
not everyone use this theme want to use https.

**Comment by Chiliec** [comment]
No, I think you don't understand. It works only if user set url in config with https :)

**Comment by Chiliec** [comment]
For more accurately, it works only if user came to site with protocol different from the specified in config.

**Comment by Xuanwo** [comment]
Well, I'll make it open for the society to determine whether it shoud be added.
Sorry for my casually close.

**Comment by NoahDragon** [comment]
I like the approach. As the PR is for hexo theme, I will close the issue here. Feel free to reopen it if you feel it is necessary.
