### ISSUE TITLE
Code rendered wrongly?

### ISSUE THREAD

**Issue by jerryling315** [hexojs/hexo#1460]
title: Iptables as jumper for Shadowsocks
date: 2015-08-20 11:19:39
tags:
    - Shadowsocks
    - Iptables
    - GFW
---
# 如何使用Iptables设置Shadowsocks跳板
电信已经弄得我们无数人想吐了. 在这里给能用Google搜索到这篇文章的人写一下如何架设一台可以用来做类似vxTrans业务的转发服务器.

# 教程

## Get a Linux Prepared
一下命令部分需要su权限
我自己用了一台运行Debian缩减版的Raspberry Pi 2, 所有Linux应该都是可以的.
打开配置文件``` /etc/sysctl.conf```
删掉```net.ipv4.ip_forward=1```前的```#```使之可以转发ipv4的流量.
运行 ```sysctl -p /etc/sysctl.conf``` 使之生效

(如有必要请安装iptables)

## 配置网络拓补结构

架设有如下外网至这台服务器的网络拓补:

- 外网:168.187.23.189 最外层路由器:192.168.1.1
 - 子路由器192.168.1.3,192.168.1.4
      - 子路由器192.168.1.3下 网段为192.168.2.2-192.168.2.255
       - 我们的服务器192.168.2.3

首先要确保使用的端口可以从最外层服务器一路转发至192.168.2.3在这里比如我们使用4444端口.
那么 外部访问168.187.23.189的4444端口=>192.168.1.3:4444=>192.168.2.3:4444.

这里架设目标shadowsocks服务器x.x.x.x使用的8388端口作为接受

## 配置Iptables

在服务器内新建一个Shell脚本文件, 比如叫, ss.sh

```
#!/usr/bin/sh

iptables -F
iptables -X
iptables -Z

iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

iptables -A INPUT -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --dport 4444 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT

iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -j MASQUERADE #绕过两层路由器的假面设置
iptables -t nat -A POSTROUTING -s 192.168.2.0/24 -j MASQUERADE #绕过两层路由器的假面设置

iptables -t nat -i eth0 -A PREROUTING -p tcp --dport 4444 -j DNAT --to-destination x.x.x.x:8388
iptables -t nat -i eth0 -A PREROUTING -p udp --dport 4444 -j DNAT --to-destination x.x.x.x:8388
iptables -t nat -A POSTROUTING -p tcp -d x.x.x.x --dport 8388 -j SNAT --to-source 168.187.23.189
iptables -t nat -A POSTROUTING -p udp -d x.x.x.x --dport 8388 -j SNAT --to-source 168.187.23.189
```

运行这个脚本 ```sudo sh ss.sh```
 
above is what my original code rendered looks like

below is how it looks on the website
![image](https://cloud.githubusercontent.com/assets/5306213/9375534/69f5076e-4734-11e5-87b5-f6744a27d462.png)

**Comment by jerryling315** [comment]
http://pasted.co/01d8383f  the original text

**Comment by Xuanwo** [comment]
单行代码请使用
```
`Code`
```
来包裹
