### ISSUE TITLE
如何制作主题

### ISSUE THREAD

**Issue by uruir** [hexojs/hexo#1461]
看主题列表里，有好多很赞的主题，请问有制作主题的入门教程么。

**Comment by angelathewebdev** [comment]
从修改其他主题开始学吧，教程好像没有看到。主题跟wordpress差不多的，比那个还简单一些。自己看看guides和API就行了

**Comment by uruir** [comment]
@angelathewebdev 文档都写得太简单了啊，看了也不明白。而且以前也没做过wordpress，主题修改的话，之前有改过pacman。可是改容易，写出一个新主题难啊，就想在这问问有教程没，或是制作主题的学习路线也行。

**Comment by angelathewebdev** [comment]
制作主题难在出页面设计，主题自身提供的功能一般很少而且很统一（比如说评论，你最多搞一个新浪微博的评论）；功能自身没有多大的区别。
我之所以推荐你从修改现有主题开始是因为页面上的结构本身不需要有太大的变动，基本上拷贝一个主题重写它的CSS就行了。
