### ISSUE TITLE
Import (and render) one markdown file into another

### ISSUE THREAD

**Issue by simonwjackson** [hexojs/hexo#1464]
Is it possible to import (and render) one markdown file into another?
I have a markdown formatted table that i want to include on multiple pages. This is content related (not theme related) but i couldnt find anything in the documentation that allows for this.

``` yaml
title: "Fancy Title"
date: 2015-08-01 02:00:00

---

Some fancy text here about something

{% markdown_partial /path/to/file %}

Some other text here..
```

**Comment by NoahDragon** [comment]
I think it could use a theme template instead, or build a tag plugin.
