### ISSUE TITLE
Site 404

### ISSUE THREAD

**Issue by angelathewebdev** [hexojs/hexo#1465]
How can I modify the router to handle 404 behaviour? I would rather see a 404 page or redirect to home page rather than display a `Cannot GET` message

**Comment by Xuanwo** [comment]
add 404.html in source

**Comment by Chiliec** [comment]
@Xuanwo How about generate 404.html by Hexo?

**Comment by Xuanwo** [comment]
put a 404.md

**Comment by Chiliec** [comment]
Maybe it should be included in Hexo?

**Comment by Xuanwo** [comment]
I don't think it should be added to hexo.

**Comment by FrankBian** [comment]
Hi guys,

这边帮朋友在windows上面 用hexo搭个blog，现在遇到了这样的问题 ：
前些日子装了node.js git 把环境都装好了，最后 hexo server也运行起来了！
刚才又hexo server准备run的时候，提示 node command not found!!!

我该如何处理这个问题 ，搜索到答案是 使用nvm指定node的版本 ~ 
但是我又发现 nvm不支持windows ~ 现在这个nodejs是我直接下的安装包安装的 ~

PS:我自己用的rmbp，所以一时半会儿竟然不知道如何处理这个了 ~ 

知道的朋友请指条明路~ 谢谢


Best Regards,
Frank Bian

**Comment by Xuanwo** [comment]
@FrankBian 请开启新的issue，Mac建议使用Homebrew安装相关环境。

**Comment by ksaitor** [comment]
So, after adding 404 to the `source`, should Hexo automagically render that page when route does not exist? Or additional nginx/apache configuration is expected to be added?

**Comment by NoahDragon** [comment]
@ksaitor if adding the 404.md, Hexo will render it based on the layout setting.
