### ISSUE TITLE
How to deploy to github pages by push

### ISSUE THREAD

**Issue by windkomo** [hexojs/hexo#1468]
Hi, I'm a new hexo user.

As I understand it, deploying a hexo blog to github pages is simply copying static files generated by hexo from source markdown to a github repository.

In this case, source markdown, config, etc is not versioned, only static files are.

Is it possible to version only source code and have it automatically deployed as static files on git push ?

Thanks

**Comment by Xuanwo** [comment]
your can use travis-CI

**Comment by Chiliec** [comment]
Hi! It's very simple, see comments in my [.travis.yml](https://github.com/Chiliec/babin.info/blob/master/.travis.yml), for example.

**Comment by windkomo** [comment]
@Chiliec Here's what I did : 
- I created a repo named {user_name}.github.io
- I initialized a hexo blog in this repo (md, config files)
- I put your .travis.yml at the repo root and changed all user info with mine
- I pushed on the new repo
- Travis-CI tells me my build is ok and executed your script

Is this ok ? I don't see changes to my github pages yet (maybe the update takes a long time ?).

Thanks for your help.

**Comment by Chiliec** [comment]
No, github pages update executes very quickly. Point 2 step 3 `Add an Environment Variable` is very important for autodeploy to github from travis-ci. Read it carefully. After this step do any update in your master branch.

**Comment by windkomo** [comment]
@Chiliec Which scopes should my personal access token have ?

**Comment by Chiliec** [comment]
Scopes by default would be enough.

**Comment by windkomo** [comment]
@Chiliec This has created a gh-pages branch on my {username}.github.io repository.
Is this intended ?

**Comment by Chiliec** [comment]
Yes, I see your site [windkomo.github.io](http://windkomo.github.io) and now any push to master-branch will be lead to automatic generate static site in gh-pages branch and site will be updated.

**Comment by windkomo** [comment]
@Chiliec Problem is windkomo.github.io is my old site with sources (from last week) that aren't even here anymore.
It does not seem to get updated with my new sources.

**Comment by Chiliec** [comment]
Travis-ci works fine, I see commit. Maybe anything with options of repository? 
 https://github.com/windkomo/windkomo.github.io/settings, section GitHub Pages.

**Comment by Chiliec** [comment]
Try to set gh-pages in default branch.

**Comment by windkomo** [comment]
@Chiliec It seems there is an issue with a theme submodule I'm using and that makes the build fail.
I'll remove the theme for the moment.
The build is now ok but I'm seeing a 404 at windkomo.github.io.

**Comment by Chiliec** [comment]
I read docs in https://pages.github.com/ and it seems that with *username*.github.io 
conversely need use master-branch to store generated-files :(
Also you can try to add CNAME file to gh-pages branch with windkomo.github.io

**Comment by windkomo** [comment]
I just did that but it's not working  :(

**Comment by windkomo** [comment]
I created another repo named blog where I put the source code, and another named username.github.io where I put generated sources (with hexo deploy) and it's working fine.

**Comment by Chiliec** [comment]
:+1:
