### ISSUE TITLE
当标题存在 <script>，模板中的toc函数不能正常工作

### ISSUE THREAD

**Issue by daifee** [hexojs/hexo#1469]
**错误表现：**

文章小标题存在`<script>`，模板的`toc`函数不能正常工作

模板文件：
<img width="580" alt="qq20150825-4 2x" src="https://cloud.githubusercontent.com/assets/5410503/9459510/d59d58d8-4b2e-11e5-8ea4-592720fc6497.png">

md内容：
<img width="447" alt="qq20150825-2 2x" src="https://cloud.githubusercontent.com/assets/5410503/9459520/fa376012-4b2e-11e5-8d51-ce1b8445a93a.png">

生成的HTML：
<img width="1167" alt="qq20150825-1 2x" src="https://cloud.githubusercontent.com/assets/5410503/9459527/16babeaa-4b2f-11e5-9a1b-36ccc5e24829.png">
## 将`<script>`改为`<h4>`却正常工作

<img width="600" alt="qq20150825-3 2x" src="https://cloud.githubusercontent.com/assets/5410503/9459601/1926c43a-4b30-11e5-8263-b4b52a09d473.png">

**Comment by Xuanwo** [comment]
把尖角括号全都转义吧
