### ISSUE TITLE
hexo shows "ERROR Error: Cannot find module 'cuid'"

### ISSUE THREAD

**Issue by nju04zq** [hexojs/hexo#1471]
hexo version
----
hexo@3.1.1 /usr/local/lib/node_modules/hexo

Error detail
----
    [04:29 PM]mac_user:blog $hexo
    ERROR Error: Cannot find module 'cuid'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        ...
        at Module.load (module.js:355:32)
    Unhandled rejection TypeError: Cannot read property 'then' of undefined
        at /usr/local/lib/node_modules/hexo/node_modules/hexo-cli/lib/index.js:82:21
        at tryCatcher (/usr/local/lib/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)

cuid already installed
----
    [04:29 PM]mac_user:blog $ls node_modules/
    cuid                    hexo-generator-index    hexo-renderer-stylus
    hexo                    hexo-generator-tag      hexo-server
    hexo-generator-archive  hexo-renderer-ejs
    hexo-generator-category hexo-renderer-marked
    [04:29 PM]mac_user:blog $
    [04:30 PM]mac_user:blog $ls -l
    total 16
    -rw-r--r--   1 mac_user  staff  1477 Aug 25 16:28 _config.yml
    drwxr-xr-x  13 mac_user  staff   442 Aug 25 16:29 node_modules
    -rw-r--r--   1 mac_user  staff   442 Aug 25 16:28 package.json
    drwxr-xr-x   5 mac_user  staff   170 Aug 25 16:11 scaffolds
    drwxr-xr-x   3 mac_user  staff   102 Aug 25 16:11 source
    drwxr-xr-x   3 mac_user  staff   102 Aug 25 16:11 themes
    [04:30 PM]mac_user:blog $

command "hexo version"
----
    [04:30 PM]mac_user:blog $cd ..
    [04:30 PM]mac_user:project $hexo version
    hexo-cli: 0.1.8
    os: Darwin 14.1.0 darwin x64
    http_parser: 2.3
    node: 0.12.7
    v8: 3.28.71.19
    uv: 1.6.1
    zlib: 1.2.8
    modules: 14
    openssl: 1.0.1p
    [04:30 PM]mac_user:project $

**Comment by kingwrcy** [comment]
same problem,except you can execute `hexo version` command but i can not run any command.

**Comment by lephones** [comment]
`hexo version`  can executed in other dir.

**Comment by kingwrcy** [comment]
see [here](https://github.com/ericelliott/cuid/issues/42)

1.rm -rf node_modules/guid
2.replace package.json cuid version from 1.3.0 to 1.2.4
3.npm install

**Comment by tommy351** [comment]
I have specify the cuid version in warehouse. This problem should be fixed now.
https://github.com/tommy351/warehouse/commit/2f9f07cacb6483d3c3594df5234f3851d3c31456

**Comment by nju04zq** [comment]
Now everything seems like OK. Actually I didn't do any thing except redo those steps 4 hours later...
Seems like cuid version not changed, and no need to copy it to local hexo environment.

    [08:47 AM]mac-user:blog $cat /usr/local/lib/node_modules/cuid/package.json
    {
      "name": "cuid",
      "version": "1.3.0",
      "description": "Collision-resistant ids optimized for horizontal scaling  and performance. For node and browsers.",
      ...

    [08:53 AM]mac-user:blog $ls node_modules/
    hexo                    hexo-generator-index    hexo-renderer-marked
    hexo-generator-archive  hexo-generator-tag      hexo-renderer-stylus
    hexo-generator-category hexo-renderer-ejs       hexo-server
    [08:53 AM]mac-user:blog $

And now for "hexo version", it shows "hexo" instead of "hexo-cli"

    [08:53 AM]mac-user:blog $hexo version
    hexo: 3.1.1
    os: Darwin 14.1.0 darwin x64
    http_parser: 2.3
    node: 0.12.7
    v8: 3.28.71.19
    uv: 1.6.1
    zlib: 1.2.8
    modules: 14
    openssl: 1.0.1p
    [08:53 AM]mac-user:blog $
