### ISSUE TITLE
url_for() works incorrectly if config.root is set

### ISSUE THREAD

**Issue by tridays** [hexojs/hexo#1474]
I modified the file in `/_config.yml`.

```
root: /hexo/
```

Then I used func. url_for() but got a wrong result.

```
<a class="nav-link" href="<%- url_for(theme.link) %>">link</a>
```

generate

```
<a class="nav-link" href="/link">link</a>
```

And the root path has gone.

**Comment by h404bi** [comment]
This has been fixed, but hexo isn't updated yet. see #1406 
You can temporarily replace the `url_for.js` file.

**Comment by leesei** [comment]
https://github.com/hexojs/hexo-renderer-marked/commit/8e3dc69f40f836e53ffda3e1a8bf6d5dd7dd502a is reverted in
