### ISSUE TITLE
iojs跑不起来

### ISSUE THREAD

**Issue by willin** [hexojs/hexo#1477]
```
[1]    5346 segmentation fault  hexo
```

iojs v3.1和v3.2

**Comment by Xuanwo** [comment]
3.1.1版本在iojs 2.0.2下测试通过了，但是3.2下是失败的。
https://travis-ci.org/hexojs/hexo/jobs/63314912
https://travis-ci.org/hexojs/hexo/jobs/77809348

可能确实存在兼容性问题

**Comment by dopcn** [comment]
今天升级了node 4.0.0，同样出现
```
[1]    52731 segmentation fault  hexo
```

node  可以降级么？

**Comment by callmewhy** [comment]
node 从 0.12 升级 4.0 之后遇到 `segmentation fault` 的问题可以本地执行 `npm rebuild` 试试=。=

**Comment by Xuanwo** [comment]
@willin 执行rebuild之后可以了么？

**Comment by leesei** [comment]
我轉了用node 5 一切正常，應該可以close 幾個node-latest 的issue

**Comment by Xuanwo** [comment]
@leesei Node 5 一切正常，我目前的博客就是跑在Node 5上的。

**Comment by Xuanwo** [comment]
Closed for no more update.
