### ISSUE TITLE
HEXO DEPLOY 时不断 Error: Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by threezj** [hexojs/hexo#1478]
windows  git2.5
但我 key 已经设置正常了啊
ssh -T git@github.com 连接正常

**Comment by Xuanwo** [comment]
切换到https看看有没有问题

**Comment by LBTINGLB** [comment]
你好 我遇到了同样的问题。。换成https也没用

**Comment by Xuanwo** [comment]
不清楚问题出在哪里，从头配置一下SSH吧，建议检查一下自己的publickey是否确实有效。

**Comment by LBTINGLB** [comment]
你好，我已经检查过 public key,确认连接git有效。请问还有别的地方可能出错吗？ 
谢谢！

Best rgrds
Haocheng LIU

**Comment by Xuanwo** [comment]
换成https之后把`deployer_git`文件夹删除，重新`hexo deploy`。
这样的话需要输入用户名密码，看一下能否正常提交。

**Comment by LBTINGLB** [comment]
谢谢！

Best rgrds
Haocheng LIU

**Comment by heicx** [comment]
@Xuanwo 可行

**Comment by MakeBigNews** [comment]
@Xuanwo 可行。谢谢。

**Comment by lgbwust** [comment]
@Xuanwo 在另一台电脑上可以deploy，换笔记本就出现了Error: Permission denied (publickey). fatal: Could not read from remote repository.，ssh -T git@github.com 连接正常，不知道问题出在什么地方

**Comment by Xuanwo** [comment]
@lgbwust 问题应该就是处在public key吧，换一个新的密钥试试看呢

**Comment by lgbwust** [comment]
@Xuanwo 谢谢，问题已解决，不是key的问题，我换了一个git版本就可以用了

**Comment by zhuziyi1989** [comment]
额，搞了一晚上，为啥切换到https 就可以了，而其他项目都能用SSH方式，真诡异。

**Comment by bin1994** [comment]
http://xiaobin.me/2016/05/31/github&coding-ssh/

**Comment by RanchoCooper** [comment]
加上branch就可以用ssh了, 不需要每次都输入账号密码
```
  type: git
  repository: git@name.github.com:name/name.github.io.git
  branch: master
```

**Comment by bin1994** [comment]
http://xiaobin.me/2016/05/31/github-coding-ssh/

**Comment by shs19890608** [comment]
我也遇到了类似的问题，用https地址可以，ssh地址Permission denied.
重新生成ssh key并用ssh -T git@github.com 连接正常还是不行.
最后在 git bash 窗口(不是 cmd)运行 hexo d 就可以了.

**Comment by XiaoWanLINJU** [comment]
我换成https之后还是不行，出现问题是the requested URL returned error: 403

**Comment by lzx1413** [comment]
亲测使用gitbash部署可以解决问题

**Comment by XiaoWanLINJU** [comment]
后续情况是：我有两个github账户，本地的key链接的是另一个账户。情况就是用SSH 链接是通的，但是链接到部署的账户就失败。后来发现SSH 显示的用户名和我部署的账户用户名不一致，才发现这个问题。

**Comment by jluo80** [comment]
我的情况是刚要deploy，然后提示输入用户名和密码，输入完说denied，所以我怀疑我输错了，然后搞了一晚上，差点就想把public key换了。结果改用git shell 来运行hexo deploy，问题解决了。

**Comment by jinyonglner** [comment]
@shs19890608  这个可以

**Comment by haovincent2016** [comment]
@shs19890608 可行

**Comment by dajavu** [comment]
@Xuanwo   这么切换到https，具体怎么操作

**Comment by adymilk** [comment]
如果你确定你的sshKey是没问题的，并且你是Mac或ubuntu系统遇到的这个问题，那么极有可能是权限问题。你不妨切换到root权限去再去试试

**Comment by bgdizzy** [comment]
同样用https解决了，ssh死活不行

**Comment by pq1949** [comment]
不用改https也可以的 试试  ```ssh-add ~/.ssh/id_rsa  ```   这个命令执行后就可以了

**Comment by qiutaohanse** [comment]
ssh的话在git bash里hexo d就没问题了，要不然弹不出输入密码的界面

**Comment by zdRan** [comment]
我的办法，重新生成一下 ssh 的公钥，然后把github上的公钥删除一下，重新添加一下，就能用了

**Comment by danzhewuju** [comment]
> 不用改https也可以的 试试 `ssh-add ~/.ssh/id_rsa ` 这个命令执行后就可以了

我MAC 用你的方法解决了

**Comment by niceSong** [comment]
这个问题可能是由于命令`sudo hexo d`导致的，`rm -rf .deploy_git`后，使用`hexo d`即可，不要加`sudo`。
hexo生成的网页页面都在`.deploy_git`中，实际上是在`.deploy_git`文件中`sudo git push`失败了，你可以去`.deploy_git`文件中测试，`sudo git push`会失败，但`git push`则可以成功，所以不加sudo试试。[Permission denied (publickey)](https://docs.github.com/cn/free-pro-team@latest/github/authenticating-to-github/error-permission-denied-publickey)

**Comment by Darrenzzy** [comment]
用https 方式需要 在个人设置中添加一个token ：https://github.com/settings/tokens 

新建一个，只会生成一次token，记下来，在push时候，填完用户名，在填刚刚的token，即可。

git remote -v
可以看到自己拉的仓库是不是https的方式。
