### ISSUE TITLE
Plugin for transliterate URLs

### ISSUE THREAD

**Issue by chiliec** [hexojs/hexo#1479]
Hey, guys!
I want to write plugin for transliterate urls (#506) and begin it in https://github.com/Chiliec/hexo-transliterator/blob/master/index.js. 
I can write `post.slug = translit(post.slug);`, but this way works only for posts and pages. Please prompt me how I can rewrite links for categories and tags? Is it possible?

**Comment by Chiliec** [comment]
I can write `post.slug = translit(post.slug);`, but it works only for posts and pages. But how to rewrite links for categories and tags?

**Comment by Xuanwo** [comment]
Maybe we need to modify the content of md files.

And I'm confused by this feature.
What will happen if I own files like `你好，世界.md` and `Hello, world.md` (after tansliterating, they are the same) ?

**Comment by Chiliec** [comment]
You're right, in this case both posts be linked to one. But nothing critical.

**Comment by Xuanwo** [comment]
Alright, when you are ready, pull your request, I will merge it in plugin list.

And I advice a tip to explain the state like https://github.com/hexojs/hexo/issues/1479#issuecomment-163663040 .

**Comment by leesei** [comment]
See `hexo/lib/models/category.js` (similarly for tag)
```js
  Category.virtual('path').get(function() {
    var catDir = ctx.config.category_dir;
    if (catDir === '/') catDir = '';
    if (catDir.length && catDir[catDir.length - 1] !== '/') catDir += '/';

    return catDir + this.slug + '/';
  });
```

**Comment by stevenjoezhang** [comment]
Any updates on this thread?
