### ISSUE TITLE
无法将“hexo”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。

### ISSUE THREAD

**Issue by Colbert337** [hexojs/hexo#1481]
E:\0.0 personal work\hexo> hexo init
无法将“hexo”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼
写，如果包括路径，请确保路径正确，然后重试。
所在位置 行:1 字符: 5
+ hexo <<<<  init
    + CategoryInfo          : ObjectNotFound: (hexo:String) [], CommandNotFoun
   dException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Xuanwo** [comment]
安装了hexo-cli了么？

**Comment by Xuanwo** [comment]
这个是powershell么？你没有把nodejs加入到pth中去吧？

**Comment by Colbert337** [comment]
已经解决了：）是我的环境变量没添加nodejs

**Comment by JackZhouMine** [comment]
你好，今天我遇到这样的问题，网上只有这个了。也没说姐姐姐办法，请问你们是如何是弄好的？

**Comment by Runfa-Zhang** [comment]
###我解决了 
https://www.jianshu.com/p/2cf69d72f435

> 你好，今天我遇到这样的问题，网上只有这个了。也没说姐姐姐办法，请问你们是如何是弄好的？
