### ISSUE TITLE
Home directory, tilde, is not handle correctly if set to `public_dir`

### ISSUE THREAD

**Issue by albertnetymk** [hexojs/hexo#1482]
Set `public_dir` to `~/public` in `_config.yml` could cause hexo to generate `~/public` relative the directory where `_config.yml` is, instead of the public directory in current user's home directory.

**Comment by Xuanwo** [comment]
all the dir is based on `_config.yml`, in other word, it's a feature.

**Comment by albertnetymk** [comment]
OK, since `/home/<username>` is handled properly, I thought the support for `~` is left due to mistakes.
