### ISSUE TITLE
circular structure for model definition

### ISSUE THREAD

**Issue by nihgwu** [hexojs/hexo#1484]
i'm trying to develop a plugin for hexo, i need to fetch the posts and then send them to the client in JSON, here is the demo code:
``` js
var posts = hexo.model('Post').toArray()
var data  = JSON.stringify(posts)
```
and i got the error `Converting circular structure to JSON`

that's caused by the model definitions, as for a `Post` for example:
`post[i].tags.data[i].posts[i].tags.data[i].posts[i] `
and the same case for `posts[i].categories`

i think the `posts` shouldn't be a virtual property for `Tag` and `Category` but a method.
or for capacity, we can simply delete the posts and length properties for `Post's` virtual property `tags` and `categories`

**Comment by petergoes** [comment]
+1 I have the same issue.
I can't read the contents of `page.categories`

This code:
```swig
{% for mycategory in page.categories %}
	{{ mycategory }}
{% endfor %}
```
results in this error: `Unhandled rejection TypeError: Converting circular structure to JSON`

**Comment by leesei** [comment]
I use [util.inspect()](http://devdocs.io/node/util#util_util_inspect_object_options) on the object.
Also check the `log()`, `inspect()` helpers.

https://github.com/hexojs/hexo/commit/a50719b9c2871e5d3141919172436419fdae1580

**Comment by nihgwu** [comment]
We need to use the data directly, not just print to the console
I restructured the data now
https://github.com/nihgwu/hexo-hey/blob/master/src/api/api.js#L30-L45

**Comment by leesei** [comment]
@nihgwu Thanks for your work. I would also suggest processing `page` before use.

**Comment by leesei** [comment]
@nihgwu I checked the FAQ and there is a `toArray()` fuction
Would it actually resolve your issue in the first place?

https://hexo.io/docs/troubleshooting.html#Iterate_Data_Model_on_Jade_or_Swig
