### ISSUE TITLE
Script that can update data

### ISSUE THREAD

**Issue by StephenCleary** [hexojs/hexo#1486]
I want to have a script in my custom theme that will run once to evaluate all pages and posts and then save some metadata for each page and post.

For example, trying to add a custom `id` attribute to the `index.html` page:

```
var util = require('util');
hexo.on('generateBefore', function () {
  var pages = hexo.locals.get('pages');
  // Attempt 1
  pages.find({path: 'index.html'}).update({id: 'index'});
  // Attempt 2
  pages.each(function (page) {
    if (page.path === 'index.html') page.id = 'index';
  });
  // Doesn't seem to save.
  hexo.database.save();
});
```

I'm a bit lost, though, since the whole data layer (warehouse) seems undocumented.

**Comment by leesei** [comment]
The repo for Warehouse is [tommy351/warehouse](https://github.com/tommy351/warehouse).
Indeed it lacked documentations.
