### ISSUE TITLE
HEXO deploy 后显示不成功,github上没有更新，本地deploy_git目录文件已修改。提交很多次都无法成功，尝试删除本地deploy_git目录，重新deploy提交，github文件修改成功。这个是什么原因？ 

### ISSUE THREAD

**Issue by shiqin** [hexojs/hexo#1487]
![image](https://cloud.githubusercontent.com/assets/7497929/9709509/75b7ee3e-555f-11e5-8e57-76ca6f4d03bd.png)

删除deploy_git后hexo d提交成功：
![image](https://cloud.githubusercontent.com/assets/7497929/9709542/1da54948-5560-11e5-9ab9-8ad4b949e5db.png)

**Comment by Xuanwo** [comment]
并没有显示不成功啊，不是nothing to commit 么。

如果是修改了CSS之类的资源，需要先执行hexo clean。
