### ISSUE TITLE
Is is possible to set home page as one of the pages in source folder?

### ISSUE THREAD

**Issue by gleb-svechnikov** [hexojs/hexo#1488]
I know about solution with exclude_generator
```
root: /
archive_dir: blog

# Extensions
exclude_generator:
- index
```
However such solution doesn't work for me.

I would like to point hexo to one of the pages as a home page.
I've imported blog from Wordress and it was possibility to pick either Post or Page for homepage, is it possible in Hexo?

**Comment by Xuanwo** [comment]
modify your layout may be useful
