### ISSUE TITLE
Are configurations required in deployment?

### ISSUE THREAD

**Issue by dsdeiz** [hexojs/hexo#1489]
I'm trying to use hexojs/hexo-deployer-rsync and was wondering if it's possible to just do `hexo deploy --host ... --user ...`. Don't want to put some credentials in the `_config.yml` file. Thanks!

**Comment by Xuanwo** [comment]
config your deploy setting

**Comment by dsdeiz** [comment]
Sorry, can you provide an example? I was also looking at hexojs/hexo-deployer-ftpsync and it looks like both `user` and `pass` needs to be on `_config.yml`. I'll be putting the source of my hexo website in github as a public repo.

**Comment by Chiliec** [comment]
How you want to deploy FROM Github? It not able to do it. Store your deploy settings where site will be deploying.

**Comment by dsdeiz** [comment]
Ah sorry what I meant is that I'll be deploying this to my server but I'll be storing the codes (which includes `_config.yml`) here in github.

**Comment by Xuanwo** [comment]
maybe this will be helpful: https://github.com/hexojs/hexo-deployer-rsync

**Comment by dsdeiz** [comment]
Hi, yeah, if you take a look at my original post, hexojs/hexo-deployer-rsync is the one I wanted to use but it looks like you need to include in the configuration file the host, user, and port. Wouldn't this make your server vulnerable exposing these info?

**Comment by Xuanwo** [comment]
you don't need to use github to control your blog's version.
you can use other service to make it, create a private repo will sovle this problem.

but it's a wonderful idea that encode your config information for sefety, I will take a look.

**Comment by dsdeiz** [comment]
Sweet, thanks!
