### ISSUE TITLE
Static, rendered homepage instead of blog

### ISSUE THREAD

**Issue by simonh1000** [hexojs/hexo#1491]
I have read (https://github.com/hexojs/hexo/issues/654) but the instructions no longer work it seems. But my question is slightly different.

How can I have a page that is rendered by Hexo (i.e. with the themes headers and footer etc) from markdown but set as the home (landing) page with the blog element put in a directory `/blog`

**Comment by Ehesp** [comment]
Exact same question ^^

**Comment by gleb-svechnikov** [comment]
You need to create index.md file with static content in your source folder. Also for latest version of Hexo(^3.1.1) you'll need to **remove hexo-generator-index** from dependencies in package.json.

**Comment by dnosker** [comment]
This worked perfectly for me.
Perhaps this could be closed.

**Comment by ChongTang** [comment]
@dnosker Hi, how do you make the custom homepage work? I removed the hexo-generator-index dependency from package.json, and added index.md in source folder. But I got some errors from theme's .ejs files when I run "hexo generate" command. I guess it might the theme's problem. I tried several different theme, but got the same problem. Which theme are you using? Thanks!

**Comment by leesei** [comment]
@ChongTang Did you **uninstall** hexo-generator-index?
`npm uninstall --save hexo-generator-index`

**Comment by johot** [comment]
I got this working after finding this issue. To clarify:

* Do an `npm uninstall --save hexo-generator-index`
* Att an `index.md` file to the root of your `source` folder.

Now the index page will behave like a normal page so you can for example in your `index.ejs` file have:
`<%- page.content %>`

Hope this helps :)

**Comment by knafteN** [comment]
I just initialized a fresh hexo app and followed the steps provided by @johot.
The generated /public/index.html looks okay, but when I start the server via `hexo server` it will redirect me to `localhost:4000/blog` which does not exist.
Any ideas?

**Comment by NoahDragon** [comment]
@knafteN Please check the config, maybe you have set the default url to blog.

BTW, if a closed issue doesn't answer your question, please create a new issue and link to the closed one. Thanks.

**Comment by johot** [comment]
In my `_config.yml` I have set root to: `/` and also added this:

```
index_generator:
  path: '/blog'
  per_page: 10
  order_by: -date
```
And finally in the `source` folder (the root) I have added an `index.md` file, I did not need to change it's permalink or anything.

Maybe you set your root wrong @knafteN ?

**Comment by knafteN** [comment]
@johot @NoahDragon I tried both, but still no luck. So I opened up a new issue and pushed my stuff into a public repository so you guys can check #2663

**Comment by srl295** [comment]
I wish I found this issue when i started my blog in 2015.  Anyway, just to add another tip, if you had created a static subpage (like me) you can use [hexo-generator-alias](https://github.com/hexojs/hexo-generator-alias) to redirect it to the homepage:

```yaml
alias:
  about/index.html: index.html
```
