### ISSUE TITLE
some punctuations are not displayed correctly. -- is changed to —, ' is changed to ‘ , " is changed to “

### ISSUE THREAD

**Issue by suexcxine** [hexojs/hexo#1492]
This is really annoying,
How can I fix this behavior?
Do I need some configuration?

This site don't have this problem:
https://www.zybuluo.com/mdeditor

**Comment by leesei** [comment]
It's `marked`'s config.
https://github.com/chjj/marked#smartypants

I'm looking for way to set it in `_config.yml`.

**Comment by suexcxine** [comment]
thank you.solved.
