### ISSUE TITLE
Hexo is unavailable for Nodejs 4.0.0

### ISSUE THREAD

**Issue by gejiawen** [hexojs/hexo#1493]
some error message like this

```
[1]    4586 segmentation fault  hexo -v
```

**Comment by zilong-thu** [comment]
I also encountered this problem. 

Just update node.js from 0.12.7 to 4.0.0, and when I run command like `hexo g`, an error will prompt:

```
$ hexo g
Segmentation fault: 11
```
Watching for solutions.

**Comment by Ehesp** [comment]
Yup same issue - any hexo command.

**Comment by tommy351** [comment]
Maybe you can try this:

```
npm rebuild
```

https://github.com/nodejs/node/issues/2763

**Comment by Ehesp** [comment]
Thanks, this ^^ fixed it for me!

**Comment by zilong-thu** [comment]
`npm rebuild` also worked for me: blog could be generated and deployed as expected, but some errors are thrown, shown as follows:

```
$ hexo s
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

**Comment by gejiawen** [comment]
run `npm rebuild` completed, but it do not work.

**Comment by Daocheng** [comment]
try
<code>npm install hexo --no-optional </code>
to fix
<code>{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }</code>

**Comment by xumeng** [comment]
`npm rebuild` had error, At last, I remake my blog directory and copy the origin files, All is ok.

**Comment by FrankFan** [comment]
### 总结一下

环境
node v4.0.0
npm  v3.4.1
出现`segmentation fault`错误，

1.执行 `npm rebuild`
得到如下报错：
```bash
hexo_blog git:(mac) hexo -v
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
hexo: 3.1.1
os: Darwin 15.0.0 darwin x64
http_parser: 2.5.0
node: 4.0.0
v8: 4.5.103.30
uv: 1.7.3
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 46
openssl: 1.0.2d
```

2.执行`sudo npm install hexo --no-optional`后即可解决：

```bash
hexo_blog git:(mac) hexo -v
hexo: 3.1.1
os: Darwin 15.0.0 darwin x64
http_parser: 2.5.0
node: 4.0.0
v8: 4.5.103.30
uv: 1.7.3
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 46
openssl: 1.0.2d
```
