### ISSUE TITLE
limit number of spawned processes

### ISSUE THREAD

**Issue by mcepl** [hexojs/hexo#1494]
When running `hexo generate` I get always on stderr:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
If I run `hexo generate --debug`` I get also a lot of `Processed` lines. When looking at `top` in other term window, it seems to me that the problem is that when using [hexo-renderer-restructuredtext](https://gitlab.com/mcepl/hexo-renderer-restructuredtext) I spawn a Python process for each document processed and my system runs of number of allowed processes.  Would it be somehow possible to limit the number of concurrently processed documents?

**Comment by mcepl** [comment]
Perhaps https://github.com/coopernurse/node-pool could help, but I don't know where to hook it.

**Comment by mcepl** [comment]
Hmm, this is probably wrong explanation ... even when I decrease number of posts to very low number, still the error happens again.
Using
```
hexo-cli: 0.1.4
os: Linux 3.10.0-314.el7.x86_64 linux x64
http_parser: 2.0
node: 0.10.36
v8: 3.14.5.10
ares: 1.10.0
uv: 0.10.34
zlib: 1.2.7
modules: 11
openssl: 1.0.1e-fips
```

**Comment by leesei** [comment]
This *MAY* improve performance but not tested.
Closing for now.
