### ISSUE TITLE
Front-matter date option disable

### ISSUE THREAD

**Issue by gleb-svechnikov** [hexojs/hexo#1496]
Hello, is there any way to disable date option for specific page? For example: date: false or something.

**Comment by leesei** [comment]
Do you mean post or page?
If you disabled date for a post how do you suppose it to be sorted with other posts?

**Comment by gleb-svechnikov** [comment]
I mean page. I just don't want to show date on the front page of the web site.

**Comment by leesei** [comment]
Is it feasible to modify your theme to hide it for pages?

**Comment by gleb-svechnikov** [comment]
Well for post I still want to show date and for pages not, not sure if it's possible to separate logic for pages and posts. But more consistent idea is to have same logic as for other fields in front matter I mean no default state. Or for example check if date is in false state, return empty string.

**Comment by leesei** [comment]
I retain the view that it is the theme's responsibility to control what is shown and what's not shown.
Hexo core only parse the `.md` as data structure and pass them to the theme. Using different data structure for theme and post implies that all themes will have to change accordingly. It is much more easy to have a specific theme to change it's handling of page timestamp.
