### ISSUE TITLE
{% asset_img sdsaf.img %} not work when post_asset_folder setting disabled

### ISSUE THREAD

**Issue by jk2K** [hexojs/hexo#1497]
When `post_asset_folder` setting is enabled, image can display properly, 
I only occasionally use`{% asset_img XXX.img %}`command, i don't want there are a number of empty asset folder, i can create asset folder manually
`{% asset_img XXX.img %}` can take effect whether `post_asset_folder` setting didn't enable?

**Comment by leesei** [comment]
@tommy351 what do you think of making `asset_*` tags work even `config.post_asset_folder` is disabled?

Those empty folders are indeed annoying, here are two other solution:
- https://github.com/timnew/hexo-console-clean-asset-folder
- add option to disable creation of asset folder

**Comment by stevenjoezhang** [comment]
Closing as not considered part of the current focus.
