### ISSUE TITLE
Tag of draft are displayed in non-draft generate.

### ISSUE THREAD

**Issue by eephyne** [hexojs/hexo#1502]
Hello

I wrote draft with new tag and categories and they are displayed in a non-draft generate public folder.

I tried clean and generate but it's the same.

The tag/categories are here but empty (0 posts).

Is this normal and is it configurable?
I use a lot draft feature and sometimes long before publish and it not quite clean to show ghost tag/categories in the meantime.

**Comment by FreeTymeKiyan** [comment]
I'm also troubled by this problem and don't know why. A temporary fix for me is to move the draft folder to somewhere else and then hexo g. 

Anyone knows how to deal with it?
