### ISSUE TITLE
hexo deploy

### ISSUE THREAD

**Issue by xiaoliuzi** [hexojs/hexo#1503]
Hello everyone, I met the problem below: can someone help me, please?

>PS E:\hexo\blog> hexo deploy
>INFO  Deploying: git
>INFO  Setting up Git deployment...
>events.js:141
      >throw er; // Unhandled 'error' event
      >^

>Error: spawn git ENOENT
    >at exports._errnoException (util.js:837:11)
    >at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    >at onErrorNT (internal/child_process.js:344:16)
    >at doNTCallback2 (node.js:429:9)
    >at process._tickCallback (node.js:343:17)

The version of npm is 2.14.2.

The part  _config.yml is below

  >Docs: http://hexo.io/docs/deployment.html
   > deploy:
    >type: git
    >repository: https://github.com/xiaoliuzi/xiaoliuzi.github.io.git
    >branch: master

and I have tried to execute the command , and I also create another new folder, but it doesn't work.
    npm install hexo-deployer-git --save

Please help me.  Thank you.

**Comment by KavinHan** [comment]
I'm also get this error on my window 10 system.
Subscribe this problem.^^

**Comment by xiaoliuzi** [comment]
@KavinHan Yes, my os is Windows 10,too.

**Comment by xiaoliuzi** [comment]
I have solved it by use this in the _config.yml
`repository: ssh://github.com/xiaoliuzi/xiaoliuzi.github.io.git`

Change `https` to `ssh`

to `hexo deploy`


Reference:

https://github.com/kemayo/sublime-text-git/issues/176


http://stackoverflow.com/questions/6565357/git-push-requires-username-and-password

**Comment by baininghan** [comment]
@xiaoliuzi 我试过了你的方法，没有用处。

**Comment by Xuanwo** [comment]
add git in path

**Comment by xiaoliuzi** [comment]
@baininghan Please show your error message.

**Comment by wzming2000** [comment]
我参考你的方法，成功啦！

**Comment by xiaoliuzi** [comment]
@wzming2000 I'm glad it helped. :)

**Comment by YTceczeng** [comment]
Thank you very much 小六子

**Comment by zongzi531** [comment]
@xiaoliuzi thanks. it's work. :)

**Comment by Jason-Zeng** [comment]
Tank you very much 
win7-64  
repo: ssh://git@github.com/Jason-Zeng/Jason-Zeng.github.io
This method is successful.

**Comment by yinzhijiang** [comment]
thank you

**Comment by zhoutiansheng** [comment]
thank you

**Comment by shooterRao** [comment]
解决了，谢谢@xiaoliuzi

**Comment by yangtao2o** [comment]
解决了，非常感谢
