### ISSUE TITLE
hexo d ERROR Deployer not found: github

### ISSUE THREAD

**Issue by tjxiter** [hexojs/hexo#1505]
MacBook-Pro% hexo d
ERROR Deployer not found: github

mac上部署hexo到github报错

**Comment by younglaker** [comment]
Use git instead of github in deploy type setting in Hexo V3. Therefore you can deploy to other Git repository hosting service, such as coding, gitcafe.

I think the  tutorial you read is old for Hexo V2. I have wrote something new about V3 :
http://laker.me/blog/categories/Hexo/

**Comment by tjxiter** [comment]
你在武汉上得大学？湖北人呀？
我用pelican搭建好了，没用hexo了。

**Comment by younglaker** [comment]
在武汉读书，非湖北人。
那你可以把这个issue关了。
