### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by KunsLand** [hexojs/hexo#1506]
The local server runs successfully. But when I try to deploy to github, the following error pops:
```
$ hexo deploy
INFO  Deploying: git
INFO  Clearing .deploy folder...
INFO  Copying files from public folder...
Assertion failed: item->nowildcard_len <= item->len && item->prefix <= item->len, file pathspec.c, line 317

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Assertion failed: item->nowildcard_len <= item->len && item->prefix <= item->len, file pathspec.c, line 317

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

    at ChildProcess.<anonymous> (f:\blogs\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:42:17)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

Any idea?

**Comment by KunsLand** [comment]
I figured it out myself. All because my OS is Windows 10. I restarted my system and reinstalled the latest version of git-bash. Then all problems are gone!

**Comment by csuldw** [comment]
![image](https://cloud.githubusercontent.com/assets/12168831/14009751/0b810fac-f1ca-11e5-87d6-b0f83cea629b.png

**Comment by KunsLand** [comment]
Delete the .git file folder and init a new repository. The problem, for me, is caused by incorrect deployment. I pushed the gh-page branch to github by myself. That is necessary for the common static pages but not for the Hexo blogs. The hexo deployment command will automatically push the gh-page branch to github and upadate the blog pages.

Hope that help for guys who made the mistakes as I did.
