### ISSUE TITLE
github support table, but hexo didn't support

### ISSUE THREAD

**Issue by wanggnim** [hexojs/hexo#1507]
All features of GitHub Flavored Markdown are supported. You can even use most Octopress plugins in Hexo.

but, i trid ,i semms not support well, see[my github](https://github.com/wanggnim/blog-website/blob/master/source/categories/jvm7/class%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F.md) and [my blog](http://www.gnim.wang/categories/jvm7/class%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F.html) , and search in page "常量池11种表结构", you will see diffrence

**Comment by amobiz** [comment]
I had the same problem, but found a workaround by adding empty table headers:

|   |   |
|---|---|
|c1|c2|

**Comment by Xuanwo** [comment]
Hexo need a title
```
xx|xx
---|---
a|b
```

xx|xx
---|---
a|b

**Comment by leesei** [comment]
Also see #1388
