### ISSUE TITLE
My sshkey work fine,but when i deploy hexo, it tell that Permission denied and could not read remote repo

### ISSUE THREAD

**Issue by doesnta** [hexojs/hexo#1511]
ssh setting was fine.
```java
$ ssh -T git@github.com
Enter passphrase for key '/c/Users/dell/.ssh/id_rsa':
Hi doesnta! You've successfully authenticated, but GitHub does not provide shell access.
```
and i try git push,it work,too.

but my ssh key using the port 22,i try ro change it to 443,but useless,some problem.

 when i deploy the hexo ,it come out the wrong message:

```java
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

my _config.xml
```java
deploy:
  type: git
  repo:  git@github.com:doesnta/doesnta.github.io.git
  branch: master
```

I also add the remote url in the .deploy.git/git/config,useless~~~

```java
[remote "origin"]
	url = git@github.com:doesnta/doesnta@github.io.git
	fetch = +refs/heads/*:refs/remotes/github/*
```

**Comment by doesnta** [comment]
hoping someone will help me ,thinks~~~

**Comment by doesnta** [comment]
I find the answer ，it's the git bug。change the git to the lower edition，it solve the problem
learn more :<http://www.cognize.me/2015/08/22/msysgiterror/>

hope the following guy get this message！！！！love you all！！！！

**Comment by cxytomo** [comment]
@doesnta file is already deleted
