### ISSUE TITLE
Error in post.js file

### ISSUE THREAD

**Issue by Gtskk** [hexojs/hexo#1513]
I found a error in line 153 of [https://github.com/hexojs/hexo/blob/master/lib/models/post.js](https://github.com/hexojs/hexo/blob/master/lib/models/post.js) file:
```javascript
var ref = PostCategory.findOne({post_id: id, tag_id: cat});
```

I think `tag_id` should be changed to `category_id`.

I have created a pull request in [https://github.com/hexojs/hexo/pull/1512](https://github.com/hexojs/hexo/pull/1512)

Hope it helps.

**Comment by leesei** [comment]
Can you also help if there is a test case corresponding to this issue?

**Comment by leesei** [comment]
Merged
