### ISSUE TITLE
I can't deploy hexo to the githubpage

### ISSUE THREAD

**Issue by yuluo-ding** [hexojs/hexo#1514]
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do                                                      cs/troubleshooting.html
Error: Permission denied (publickey).
fatal: Could not read from remote repository.
```
I have added the pubkey in the github. But when i deploy ,something wrong happended

**Comment by evindu** [comment]
me too

**Comment by leesei** [comment]
Please double check with the instructions here:
[Generating SSH keys - User Documentation](https://help.github.com/articles/generating-ssh-keys/)
