### ISSUE TITLE
something wrong with deploy hexo on heroku

### ISSUE THREAD

**Issue by Mark1002** [hexojs/hexo#1516]
after i enter "hexo deploy", my terminal appears some error message:

FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: source.replace is not a function
    at Object.exports.parse (/Users/Mark1002/markblog/node_modules/hexo-deployer-heroku/node_modules/swig/lib/parser.js:438:19)

**Comment by ahaasler** [comment]
Amazon EC2 failed yesterday, is this still happening?

**Comment by leesei** [comment]
Please open new issue if the problem persists
