### ISSUE TITLE
How about supporting multi category and multi tag 

### ISSUE THREAD

**Issue by tim-hub** [hexojs/hexo#1520]
I thinks it is cool, especially multi tags in one post

**Comment by mattwoolnough** [comment]
Have you tried listing tags like this?
```
tags:
- Script
- Javascript
```

**Comment by leesei** [comment]
Use the above array syntax for multiple tags.
We don't support multiple categories, using the array syntax will create a hierarchy of categories.

[Front-matter | Hexo](https://hexo.io/docs/front-matter.html#Categories_&_Tags)

**Comment by oycfreedom** [comment]
Wow, @mattwoolnough it worked! 
tags: 
- tag1
- tag2
