### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by evindu** [hexojs/hexo#1521]
![运行数据截图]( http://i3.tietuku.com/59ccf146fdc83f5e.png)

my     config.yml 
deploy:
  type: git
  repo: git@github.com:evindu/evindu.github.io.git
  branch: master

**Comment by leesei** [comment]
Did you setup your SSH key and added it to your GitHub account?
[Generating SSH keys - User Documentation](https://help.github.com/articles/generating-ssh-keys/)
