### ISSUE TITLE
Customized og:image meta field

### ISSUE THREAD

**Issue by blaesus** [hexojs/hexo#1525]
I am trying to implement a functionality, where an author writes something like

```
title: Hello World
thumbnail: hello.png
--------
Stuff
```

and in the generated HTML, the `<head>` has

```
<meta property="og:image" content="http://example.com/hello.png"
```

I've implemented this by modifying `node_modules/hexo/lib/plugins/helper/open_graph.js`, specifically,

by changing

```
var images =  options.image || options.images || page.photos || [];
```

to

```
var images =  page.thumbnail || options.image || options.images || page.photos || [];
```

I wonder if there are smarter ways to do this.

Thank you!

**Comment by thdotnet** [comment]
any news about that?

**Comment by andyshuhsin** [comment]
@thdotnet None that I know of, unfortunately.

**Comment by connor11528** [comment]
Yes this would be a good feature. I am curious about how to add custom open graph data for articles. Currently when I share my article it not looking so hot 🔥

**Comment by krausekai** [comment]
Reopening this suggestion!

**Comment by jimmy2822** [comment]
When adding a new post attribute, open_graph still can't be automatically working in right way.

**Comment by SukkaW** [comment]
https://hexo.io/docs/helpers#open-graph

From hexo docs I can see there is an `image` options for open_graph helper, so I am closing this issue now.
