### ISSUE TITLE
Homepage + blog at /blog

### ISSUE THREAD

**Issue by nickbuddendotcom** [hexojs/hexo#1527]
Hi All,

Sorry if this has been answered already somewhere - I've looked through the Hexo docs and the GitHub issues and I can't seem to find it. I want to create a site which has:

* A static homepage
* A blog at http://mysite.com/blog

I've read https://github.com/hexojs/hexo/issues/654 and I understand how to create a static homepage - what I don't understand is how to create a list of blog posts at `/blog`.

How can this be done?

Thanks!

**Comment by nickbuddendotcom** [comment]
For anyone looking at this in the future:

`hexo new blog "blog"`

Then in `blog/index.md`:

```
title: blog
layout: blog
---
```

Then create `blog.jade` in the layout folder of your theme.

**Comment by ChongTang** [comment]
@nickbuddendotcom 
Is that 
``` hexo init blog "blog"```?
What is `hexo new`?
