### ISSUE TITLE
markdown 支持不全

### ISSUE THREAD

**Issue by evindu** [hexojs/hexo#1528]
**标题的# 号无法支持**  
![tu0](http://i13.tietuku.com/81a3b10375256e16.png)

**还有这个 点 的位置为什么会偏离**

![tu1](http://i13.tietuku.com/df30302dfb85cbf1.png)
![tu2](https://cloud.githubusercontent.com/assets/7939349/10263750/c40eeb10-6a2b-11e5-9d15-c2e0209d5985.png)

**Comment by Xuanwo** [comment]
1. 标题中需要用'#'的自行转义，因为'#'在Markdown里面是有意义的字符
1. 这个点为什么会偏离，就要看你的主题以及你的Markdown源文件怎么写的了
