### ISSUE TITLE
error when hexo generate a huge post

### ISSUE THREAD

**Issue by hoavo** [hexojs/hexo#1529]
I run hexo generate for 10k post is success BUT when run 100k post, get error:

<--- Last few GCs --->

  154158 ms: Scavenge 1396.0 (1456.9) -> 1396.0 (1456.9) MB, 2.2 / 0 ms (+ 2.5 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  155926 ms: Mark-sweep 1396.0 (1456.9) -> 1395.7 (1456.9) MB, 1767.8 / 0 ms (+ 4.0 ms in 2 steps since start of marking, biggest step 2.5 ms) [last resort gc].
  157695 ms: Mark-sweep 1395.7 (1456.9) -> 1395.7 (1456.9) MB, 1768.6 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3c4f9b737339 <JS Object>
    1: create [native v8natives.js:~754] [pc=0xe524da5ed32](this=0x3c4f9b736b61 <JS Function Object %28SharedFunctionInfo 0x3c4f9b736ad1%29>,am=0xfbf68c641c1 <an Object with map 0x38ed38065c9>,aC=0x3c4f9b704131 <undefined)
    2: arguments adaptor frame: 1->2
    3: constructor(aka ReadStream) [fs.js:~1619] [pc=0xe524f70a03b] (this=0xfbf68c64259 <a ReadStream with map 0xd32b01355e9>,path=0xfbf68c...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6

**Comment by leesei** [comment]
Did you try the solution [here](https://github.com/hexojs/hexo/issues/1735)?
