### ISSUE TITLE
加了空格,deploy仍然没有反应

### ISSUE THREAD

**Issue by greying** [hexojs/hexo#1531]
加了空格,deploy仍然没有反应

**Comment by greying** [comment]
以前的评论看了很多,还是没有解决,不知为何?

**Comment by greying** [comment]
deploy: 
  git: github 
  repo: https://github.com/greying/greying.github.io.git 
  branch: master

**Comment by greying** [comment]
can anybody help me?

**Comment by greying** [comment]
have entered the space in the _config.yml, then "hexo generate" is ok, but"hexo deploy", no response, what the hell? I tried 2 days, it still doesn't work!!!....
I even want quit the Hexo, help me OK?

**Comment by lslsby** [comment]
npm install hexo-deployer-git 试试！

发自我的 iPhone

**Comment by greying** [comment]
@lslsby 这个已经试过了,依旧无效

**Comment by leobbb** [comment]
hexo d 之后输出是什么？输出为空？

**Comment by greying** [comment]
@leobbb 输出为空，然后出现$,让我输入命令

**Comment by leesei** [comment]
`hexo generate` 有看見`public/`嗎?

**Comment by younglaker** [comment]
格式应该是这样吧？

    deploy:
      type: git

**Comment by leesei** [comment]
對， 請參考
https://github.com/hexojs/hexo-deployer-git

**Comment by greying** [comment]
@younglaker 
@leesei 
谢谢大家,始终弄不出来,等Hexo更适合菜鸟了,我再玩玩吧!

**Comment by greying** [comment]
最后试了一下,成功了!
deploy:
  type: git
  repository: git@github.com:greying/greying.github.io.git
  branch: master

**Comment by younglaker** [comment]
@greying 

这是我折腾Hexo3的一些心得，供参考： http://laker.me/blog/categories/Hexo/
欢迎交流~

**Comment by greying** [comment]
@younglaker 实在是谢谢！帮助真的很大！！！

**Comment by leesei** [comment]
@younglaker  [這裡](http://laker.me/blog/2015/09/28/15_0928_hexo_to_coding/)說道"Hexo不支持同时多个托管仓库"
你有跟著這個格式配置嗎?
```yaml
deploy:
  type: git
  message: [message]
  repo: 
    github: <repository url>,[branch]
    gitcafe: <repository url>,[branch]
```

**Comment by greying** [comment]
@leesei 已经弄好了！就是那个格式

**Comment by leesei** [comment]
行, 你一開始用的是舊版本config

我回是想提醒一下@younglaker 更新文檔
可能他測的時候功能還未完善

**Comment by younglaker** [comment]
@leesei 感谢，已修正~

BTW：是“她” (*^__^*)

**Comment by akreturn** [comment]
@greying  我出现和你一样的问题，但是我修改了repository的形式还是不行

**Comment by greying** [comment]
@akreturn 看评论，后来我那个方法成功了

**Comment by kookob** [comment]
type冒号后面要加空格。
还有一个地方就是deploy下面type、repository、branch这几个前面也要加空格。
加上之后，hexo deploy就成功了。
