### ISSUE TITLE
list_tags 插入标签列表方法，如何实现按照标签出现次数排序

### ISSUE THREAD

**Issue by luciy** [hexojs/hexo#1533]
<%- list_tags(site.tags, { orderby: 'name'}) %>    这个文档中只给出orderby按照 name 排序  我想按照标签出现次数排序，需要怎么传参。

**Comment by Xuanwo** [comment]
重载list_tags

**Comment by luciy** [comment]
重载？

**Comment by Xuanwo** [comment]
大致上是这么个概念，helper只是实现了部分功能，如果想实现你的需求的话，就要自己实现了
