### ISSUE TITLE
Duplicate categories

### ISSUE THREAD

**Issue by perry-mitchell** [hexojs/hexo#1542]
I transferred my site from wordpress to hexo, and I'm getting duplicate categories:
<img width="761" alt="screen shot 2015-10-11 at 11 54 10 am" src="https://cloud.githubusercontent.com/assets/3869469/10416088/d16c1240-700e-11e5-8b8b-eeead9d0e011.png">

These categories are present in db.json, and can be seen with `parent` fields - This is, I'm guessing, why there are duplicates being presented. I've checked over my posts and there doesn't seem to be any parent specification, eg:
```
title: 'A load balanced website using PHP FPM, Nginx, MySQL and Varnish (Part 1)'
tags:
  - nginx
  - varnish
  - wordpress
id: 79
categories:
  - MySQL
  - PHP
  - Programming
  - Software
date: 2013-07-01 08:23:21
---
```

I also don't have any categories directory or category map, so I don't know how Hexo is generating this list.

Hexo info:
```
hexo: 3.1.1
os: Darwin 15.0.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by leesei** [comment]
This issue was moved to hexojs/hexo-migrator-wordpress#10
