### ISSUE TITLE
plain codeblock的行数不正确

### ISSUE THREAD

**Issue by Zplutor** [hexojs/hexo#1543]
_config.yml中highlight的auto_detect设置成false，.md中输入以下codeblock：

{% codeblock %}

	0:002> kb = 0095f168
	ChildEBP RetAddr  Args to Child              
	（略）
	0095f364 00000000 0095f37c 0095f39c 0095f37c ntdll!KiUserExceptionDispatcher+0xf
	
{% endcodeblock %}

得到的结果是这样的：
![image](https://cloud.githubusercontent.com/assets/1822051/10417268/17b8c64a-7068-11e5-829c-6e1032df0505.png)

这个应该怎么解决？

**Comment by Xuanwo** [comment]
你是不是混合使用了两种Markdown代码格式？{% codeblock %}和四个空格一起用了？

**Comment by Zplutor** [comment]
是混合使用了。但我去掉了空格只保留{% codeblock %}之后，结果还是一样。

**Comment by Xuanwo** [comment]
建议你使用三个`来包裹自己的代码试试看

**Comment by Zplutor** [comment]
@Xuanwo 使用```问题依旧。

**Comment by Xuanwo** [comment]
这篇文章的MD源码贴出来看看呢？就是那段有问题文字的前后。

**Comment by Zplutor** [comment]
这个调用栈最终到达了KiUserExceptionDispatcher，也就是我们要找的栈帧。为什么要找KiUserExceptionDispatcher的栈帧呢？这是因为在Windows下所有异常都是通过KiUserExceptionDispatcher这个函数抛出来的，这个函数具有两个类型分别为PEXCEPTION_RECORD和PCONTEXT的参数，分别指向异常信息以及异常发生时的线程环境信息。

既然找到了KiUserExceptionDispatcher的栈帧，那么可以换用kb命令，显示出它的参数列表：

{% codeblock %}

	0:002> kb = 0095f168
	ChildEBP RetAddr  Args to Child              
	（略）
	0095f364 00000000 0095f37c 0095f39c 0095f37c ntdll!KiUserExceptionDispatcher+0xf
	
{% endcodeblock %}
	
可知PEXCEPTION_RECORD的值是0095f37c，PCONTEXT的值是0095f39c。

WinDbg提供了.exr命令来显示PEXCEPTION_RECORD的内容，如下所示：

**Comment by Zplutor** [comment]
在Mou里面源码显示如下：
![image](https://cloud.githubusercontent.com/assets/1822051/10460249/15eed9cc-7206-11e5-8d37-137149406d5a.png)

**Comment by Xuanwo** [comment]
0:002> kb = 0095f168
ChildEBP RetAddr  Args to Child              
（略）
0095f364 00000000 0095f37c 0095f39c 0095f37c ntdll!KiUserExceptionDispatcher+0xf

直接用```包裹上面一段，不要用任何缩进

**Comment by Zplutor** [comment]
我试了这种方法还是不行呢。
![image](https://cloud.githubusercontent.com/assets/1822051/10490102/d487a3e8-72d1-11e5-8883-a8a221e4981b.png)

结果显示如下：
![image](https://cloud.githubusercontent.com/assets/1822051/10490138/04bf31c0-72d2-11e5-801b-c7d3ba439773.png)

**Comment by Xuanwo** [comment]
什么鬼，加上一个`plain`或者`java`啥的试试呢？

**Comment by Zplutor** [comment]
只有plain的codeblock才有问题啊，指定了其它语言都是正常的。
![image](https://cloud.githubusercontent.com/assets/1822051/10505486/84dc5bf8-7340-11e5-8e2d-cfebbb6ffb25.png)

结果显示如下：
![image](https://cloud.githubusercontent.com/assets/1822051/10505514/bf130dbc-7340-11e5-8b7e-39c9d4957eb1.png)

**Comment by Xuanwo** [comment]
那我只能理解为plain不会做任何高亮以及添加行号了。。

**Comment by Zplutor** [comment]
这个是bug吧

**Comment by Xuanwo** [comment]
@Zplutor 添加行号是hljs做的事情，指定plain的话，hljs不会渲染

你强行指定：
```
highlight:
  enable: true
  line_number: true
```
试试看

**Comment by Zplutor** [comment]
已经设置过这几个属性了，没有效果。下面是_config.yml的内容：

	# Hexo Configuration
	## Docs: http://hexo.io/docs/configuration.html
	## Source: https://github.com/hexojs/hexo/

	# Site
	title: Zplutor's
	subtitle:
	description:
	author: Zplutor
	language: zh-CN
	timezone:

	# URL
	## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
	url: http://zplutor.github.io
	root: /
	permalink: :year/:month/:day/:title/
	permalink_defaults:

	# Directory
	source_dir: source
	public_dir: public
	tag_dir: tags
	archive_dir: archives
	category_dir: categories
	code_dir: downloads/code
	i18n_dir: :lang
	skip_render:

	# Writing
	new_post_name: :title.md # File name of new posts
	default_layout: post
	titlecase: false # Transform title into titlecase
	external_link: true # Open external links in new tab
	filename_case: 0
	render_drafts: false
	post_asset_folder: true
	relative_link: false
	future: true
	highlight:
	  enable: true
	  line_number: true
	  auto_detect: false

	# Category & Tag
	default_category: uncategorized
	category_map:
	tag_map:

	# Date / Time format
	## Hexo uses Moment.js to parse and display date
	## You can customize the date format as defined in
	## http://momentjs.com/docs/#/displaying/format/
	date_format: YYYY-MM-DD
	time_format: HH:mm:ss

	# Pagination
	## Set per_page to 0 to disable pagination
	per_page: 10
	pagination_dir: page

	# Extensions
	## Plugins: http://hexo.io/plugins/
	## Themes: http://hexo.io/themes/
	plugins:
	- hexo-generator-sitemap

	theme: light

	# Deployment
	## Docs: http://hexo.io/docs/deployment.html
	deploy:
	  type: git
	  repo: https://github.com/Zplutor/zplutor.github.io
	  
	feed:
	  type: atom
	  path: atom.xml
	  limit: 0

**Comment by Xuanwo** [comment]
ref: https://github.com/hexojs/hexo/pull/1538

你可尝试一下这个：
```
  {% codeblock [line_number:(true|false)] %}
    code snippet
  {% endcodeblock %}
```

**Comment by leesei** [comment]
[Line numbers — highlight.js 9.0.0 documentation](http://highlightjs.readthedocs.org/en/latest/line-numbers.html)

It seems line numbers were not added by highlight.js.
I've yet to find the one adding them.
renderer-marked used `highlight` from `hexo-utl`.

```js
var util = require('hexo-util');
var highlight = util.highlight;
```

**Comment by Zplutor** [comment]
我的hexo是从npm上安装的，更新之后还是识别不了line_number选项，可能还没带上这个修改。
我要先研究下怎么从源代码编译hexo。

**Comment by q852217956** [comment]
刚刚解决了这个问题√

https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js#L25
 在这前面加上`data.value = data.value.replace(/&#10;/g, "\n");`就可以了。
本机上文件位置在`博客文件夹/node_modules/hexo-util/lib/highlight.js`我的系统是OS X。

如果不是[highlight.js](https://highlightjs.org)所列出的语言就不会被处理，`plain`并不在其中，只是hexo将`plain`判定为不处理高亮而已。只有处理过的字符串换行是`\n`，没有被处理的是HTML风格的换行符`&#10;`，替换掉就好了。

**Comment by leesei** [comment]
謝謝提供資料
"\n" (0xA, 10d) 昰*nux 的換行, Windows 用的是"\n\r" ([0xA, 0xC], [10d, 13d])
[Newline - Wikiwand](https://www.wikiwand.com/en/Newline)

不過我建議是配置一下highlight.js, 讓它normailize 內容再由hexo-util 加行號
未知是否可行

**Comment by leesei** [comment]
I have problem reproducing this issue, can anyone provide me with a test case?
Maybe we did fixed it somehow, so please also check your package version `npm ls --depth 0` if you are having this issue.

**Comment by leesei** [comment]
These are fixed on 3.2beta: http://leesei.github.io/hexo-vanilla-site/2016/02/23/1543/
So wait for the next release.

**Comment by q852217956** [comment]
目前的hexo3.1.1中使用`plain`或者highlight.js里未列出的语法就会导致行号不正确显示，比如
\`\`\` plain
line 1
line 2
line 3
\`\`\`
而且渲染出的代码块在不同屏幕尺寸下的字号是固定的。不过看起来3.2beta中已经解决了。

**Comment by leesei** [comment]
3.2 released

**Comment by frapples** [comment]
这个bug没有解决吧。我在最新的3.3.5上面依旧有这个问题，没有设置或设置为plain行号会只显示一个1.
