### ISSUE TITLE
Improved `render_drafts` behaviour

### ISSUE THREAD

**Issue by clkao** [hexojs/hexo#1545]
Currently when `render_drafts` is defined, drafts are simply rendered as regular posts.

Perhaps we can render the permalink of the draft, but not include the post in any other index or archive pages.  In this case you can share the link to the draft for others to review before actually publishing it.  There can also be some custom css class showing the post is actually still in draft.

**Comment by Xuanwo** [comment]
How about put them in specific directory and render them as pages?

**Comment by lucaskatayama** [comment]
+1
Just made this question in [StackOverflow](http://stackoverflow.com/questions/36107177/publish-hexo-drafts-without-being-listed-as-posts)

**Comment by tomekwi** [comment]
> we can render the permalink of the draft, but not include the post in any other index or archive pages.

I couldn’t agree more with this idea! Asking others to review a post draft is definitely a common practice – and I don’t think any blogger wants their draft posts to appear on public listings. IMO what @clkao suggests is the most reasonable behavior for drafts.

> How about put them in specific directory and render them as pages?

To be honest, this seems like a viable workaround but not a proper solution to me.
