### ISSUE TITLE
WARN  No layout

### ISSUE THREAD

**Issue by appernetic** [hexojs/hexo#1550]
Hi,
my first test with Hexo!

I installed and tested with default settings. It worked with no problem. Now I  changed theme from default to hexoThemKacper and got this:

hexo generate
INFO  Files loaded in 459 ms
WARN  No layout: tags/tags/index.html
WARN  No layout: tags/category.html
WARN  No layout: tags/category/index.html
WARN  No layout: tags/about/index.html
WARN  No layout: tags/API/index.html
WARN  No layout: 2015/10/15/hello-world/index.html
WARN  No layout: 2015/10/15/My-New-Post/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2015/index.html
WARN  No layout: archives/2015/10/index.html
WARN  No layout: index.html

I have tried hexo clean and hexo d -g but no luck.

Could it be that I have installed the module Hexo Server? I did that after the first installation, but did not checked that it worked after that and before changing theme...

If that is the problem how do I uninstall a plugin?

**Comment by leesei** [comment]
Please post your `package.json`.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.

**Comment by EvanCarroll** [comment]
```text
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.0",
    "hexo-admin": "^1.1.1",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-tag": "^0.1.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-server": "^0.1.2"
  }
}
```

**Comment by EvanCarroll** [comment]
@appernetic you find a solution?

**Comment by Xuanwo** [comment]
First of all, you need make sure you have correct theme.

**Comment by gringolalia** [comment]
Also with this problem. Following the steps of [this tutorial](https://www.sitepoint.com/project-documentation-hexo/), I created a `default.swig` layout in the source folder of a theme called `documentation`, then specified `theme: documentation` in `_config.yml`.  Builds fine with default `landscape` theme.

Newbie question, sorry.
