### ISSUE TITLE
Bug:代码段包含{{}}不能不正确解析

### ISSUE THREAD

**Issue by wedojava** [hexojs/hexo#1552]
要解析必须得用  \`\`\`  来括起来，有时候只是很短的像用   \`  来括起来作为行内代码表示会报错的。

**Comment by akar1nchan** [comment]
我也發現了

**Comment by akar1nchan** [comment]
為什麼連<pre></pre>都報錯了

**Comment by leesei** [comment]
Use [`{% raw %}` block](https://hexo.io/docs/troubleshooting.html#Escape_Contents)
