### ISSUE TITLE
"npm install -g hexo-cli" failed (Windows-64bits)

### ISSUE THREAD

**Issue by yazoo1222** [hexojs/hexo#1554]
$ npn install -g hexo-cli
npm WARN optional dep failed, continuing fsevents@1.0.2
C:\Program Files\nodejs\node_global\hexo -> C:\Program Files\nodejs\node_global\node_modules\hexo-cli\bin\hexo
hexo-cli@0.1.8 C:\Program Files\nodejs\node_global\node_modules\hexo-cli
├── abbrev@1.0.7
├── minimist@1.2.0
├── bluebird@2.10.2
├── tildify@1.1.2 (os-homedir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── hexo-fs@0.1.4 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, chokidar@1.2.0)

after that ,I have tried "hexo init",finding that the hexo didn't install.
what should I do???

**Comment by leesei** [comment]
Did you add `C:\Program Files\nodejs\node_global\` to your `PATH`?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
