### ISSUE TITLE
How to save an array of objects to posts?

### ISSUE THREAD

**Issue by vitto** [hexojs/hexo#1556]
Hi, I'm trying to understand how to save an array of objects to posts, but I'm not sure what should be the right workflow I should do to let it works as I expect.

Basically, I need to parse the comment contents of `less/sass` widgets I have inside a folder, I've parsed them inside an array of objects like this, and I'd like to generate a style guide for them.

```
var widgetFiles = [{
    slug: 'slug-name',
    name: 'Hello world',
    type: 'Category name',
    text: 'This is the description of the element,
    html: '<divclass="button"><divclass="button__child">hello</div></div>',
    file: './test/subfolder/test.less',
    layout: 'post',
    engine: 'ejs'
},{
    ...
},{
    and so on...
}];
```

This is how I prepared my code inside `node`, but I'm not sure what I should do now to create the static site:

```
hexo = new Hexo(process.cwd(), {
    debug: true,
    config: '_config.yml'
});

hexo.init().then(function(){
    var widgetFile = widgetFiles[0];

    hexo.render.render({text: widgetFile.text}, widgetFile).then(function(result){
        console.log(result);
    });
});
```

Should I use `hexo.post.publish` api to continue?

I've searched in the issues some indication without success, I hope this it the right place to post this answer!

thanks for help!

**Comment by jahbini** [comment]
I am trying "essentially" the same thing.  Stuff did not work unless the post had a `content:` element, which would likely be your `html:` element

Then it started generating proper `.md` files
