### ISSUE TITLE
hexo deploy后404

### ISSUE THREAD

**Issue by alivebao** [hexojs/hexo#1559]
链接：https://github.com/alivebao/alivebao.github.io
麻烦帮忙看看什么原因
谢谢

**Comment by Since1990** [comment]
好久以前弄的hexo，基本忘记完了。看你的错误，应该是没有上传成功。
问题可能出在两个地方：
1..SSHkey是否生成成功了（这个可能性更大）
2.hexo部署出错

你说的问题可以参考以下两个地址：
http://zipperary.com/2013/05/28/hexo-guide-2/
https://xuanwo.org/2014/08/14/hexo-usual-problem/

其他的问题可以参考：
https://github.com/hexojs/hexo/issues/1263
http://blog.csdn.net/wx_962464/article/details/44786929

看到你的My Blog，发现仓库的文件夹数量不够，肯定是上传失败，上传成功之后的文件夹有很多你可以看我的。https://github.com/Since1990/Since1990.github.io

真的忘记差不多了，希望能够帮助你了，
