### ISSUE TITLE
How to use the value of config file in the post?  如何在文章中引用_config.yml 文件中的值？

### ISSUE THREAD

**Issue by leobbb** [hexojs/hexo#1560]
Forgave me about my bad english.

If I set a value like this in file _config.yml:

```
cus_url: example.someadmain.com
```

Can I use the value (example.someadmain.com)  in md file by cus_url? 
If can, and how to do that? 

like: <% config.cus_url %>  or {% asset_path *** %}  ?

**Comment by Xuanwo** [comment]
<% config.cus_url %> && {{ config.cus_url }}
