### ISSUE TITLE
wrong image file name convertion when there are spaces in file name

### ISSUE THREAD

**Issue by dracodoc** [hexojs/hexo#1562]
I have a image file with spaces in name (they are generated from knitr automatically so it's unpractical for me to remove the space manually every time). I put the image file under the post asset folder, use this to refer the image in markdown file:

    ![plot of chunk Basic Module Detector Alert](Basic Module Detector Alert-1.png) 

After post generation, the html is referring the image like this:

    <img src="Basic Module Detector Alert-1.png" alt="plot of chunk Basic Module Detector Alert"> 

But the image file in public folder was renamed with all spaces replaced by `%20`, thus the image cannot be displayed.

Either the image file should not be renamed, or the html should use renamed file name.

**Comment by Xuanwo** [comment]
I think we should use renamed filename in html.

**Comment by leesei** [comment]
On my test on Linux, file was not renamed in `public` and can be accessed with `src` with space in link.

That said, we should urlescape links anyway.

**Comment by leesei** [comment]
Use `{% asset_img "spaced asset" "spaced title" %}` to access spaced asset.
