### ISSUE TITLE
html tags replaced in post.excerpt 

### ISSUE THREAD

**Issue by pozitron57** [hexojs/hexo#1563]
Hi there, thank you for the work on Hexo!

I have an issue: `page.excerpt` gives me `&lt;p&gt;` instead of `<p>`. How can I solve it? I tried hexo-renderer-markdown-it and default renderer hexo-renderer-marked with no difference.

As a very ugly workaround I added 

    data.excerpt = data.excerpt.replace(/<.*?>/g,''); 

to `node_modules/hexo/lib/plugins/filter/after_post_render/excerpt.js`. It deletes all html tags, but at least my excerpts are readable.

**Comment by Xuanwo** [comment]
if you want to have `<p>` in your post, you can use `{{% raw %}}` and `{{% endraw %}}`

**Comment by pozitron57** [comment]
Thanks for your comment, it motivated me to review my problem. It came out that I didn't know difference between `<%= post.excerpt %>` and `<%- page.excerpt %>`. 

I used the first and was getting `&lt;p&gt;` instead of `<p>`.

Now I use the latter and everything works fine.
