### ISSUE TITLE
skip_render doesn't work

### ISSUE THREAD

**Issue by pozitron57** [hexojs/hexo#1565]
Hi there,

Hexo renders any file in `source` directory. `skip_render` doesn't work for me, and after some searching I can say that it doesn't work not only for me. Even the code files in default code directory `downloads/code` getting rendered by Hexo which cause errors.

If I set `code_dir: _downloads/code` then it will not be rendered, and `{% include_code %}` works fine. But it will not be copied to `public`, so link `view raw` will lead to non-existing file.

Why `skip_render` doesn't work? Are there other ways to solve the problem?

**Comment by Xuanwo** [comment]
https://github.com/hexojs/hexo/issues/1146#issuecomment-88380140 any help?

**Comment by pozitron57** [comment]
Sorry, what exactly is proposed there? I didn't notice anything (probably due to my poor Chinese) except for setting 

    skip_render: 'test/*.html'

But I've already tried it in various forms several times; it doesn't work for me for some reason, and I'd like to know the reason it doesn't work.

**Comment by Xuanwo** [comment]
try `skip_render: _downloads/**`

**Comment by Hozuki** [comment]
@Xuanwo 目前我的配置：

```
skip_render:
  - 404.html
  - code/**
```

不过这在我的情况中并没有什么用。所有的 HTML 文件*是*没有被处理，但是所有 JavaScript 文件仍然被当做 EJS 给render了一下。我的 JavaScript 代码注释中有类似 `{{x:Number}}` 这样的类型注释，而 EJS 解释器认为这是个变量引用而报错。（定位错误原因就用了几小时，整个模板查了一遍，最后受不了了在nunjucks里加了一个详细输出才找到这个问题。）

在2.8.3版本中，这些 JavaScript 代码处理时没有报错。

所以 `skip_render` 似乎对除了 HTML 以外的文件并没有多大用？

**Comment by Xuanwo** [comment]
@Hozuki 这种情况，你可以单独`*.js`尝试一下
上一次我测试的时候好像还是可以，有空的时候我再去看看`skip_render`的实现吧，可能哪里写搓了

**Comment by Hozuki** [comment]
@Xuanwo 实践表明还是不行，可能只是跳过了 generator-marked，或者调用 generator-ejs 时的参数出了问题吧。

**Comment by pozitron57** [comment]
@Xuanwo , no luck with it. `skip_render` is just ignored.

**Comment by pozitron57** [comment]
Finally I discovered that if I put any directory to `themes/wixo/source` (I use theme wixo) instead of `source` it will not be rendered but just copied to `public` as desired! 

Moreover, I managed to make the link `view raw` work. I created directory `code` in `themes/wixo/source` and set in `_config.yml`:

    code_dir: ../themes/wixo/source/code

Also in `node_modules/hexo/lib/plugins/tag/include_code.js` I changed 

    caption = '<span>' + title + '</span><a href="' + ctx.config.root + codeDir + path + '">View raw</a>';

to

    caption = '<span>' + title + '</span><a href="' + '/code/' + path + '">View raw</a>';

Now any code from `themes/wixo/source/code` is rendered without any errors and it can be downloaded by the default link `view raw` generated by {% include_code %} tag. Maybe it is not very straightforward behavior of Hexo, but my problem is resolved. Thanks to everyone for help!

**Comment by Xuanwo** [comment]
@Hozuki 冒昧问下，你的code文件夹在什么地方？

**Comment by Hozuki** [comment]
@Xuanwo 在 `source` 下。
![pic](https://cloud.githubusercontent.com/assets/7345875/10750819/ec35eea4-7cb4-11e5-8e07-7882e70c5b59.jpg)

**Comment by Macxim** [comment]
Sorry but `skip_render` still doesn't work for me.
In my _config.yml, I have : 
```yml
skip_render:
- node_modules/**/*
- css/**/*
- js/**/*
- gulpfile.js
- package.json
```
All these files are located in `themes/mytheme/source/`.
I don't want these files to render nor to be copied in `public/`.
Is there something I missed?

**Comment by pozitron57** [comment]
@Macxim 

If you don't want them to be neither rendered nor copied, try to give a name starting with underscore to the directory with this files (e.g. `_directory`).

**Comment by Xuanwo** [comment]
@Macxim put them in `source` instead of `themes/mytheme/source/`

**Comment by Macxim** [comment]
Thank you guys, I ended up putting them in another folder. :+1:

**Comment by fish-404** [comment]
I try to add a Tiddly Wiki HTML file (which contains a lots of `{{ }}` ) to skip. If I skip the whole folder like the doc[^1] write, it doesn't work. If I skip this HTML single file, it works.

file path: `source/mypage/page.html`

``` yml
# doesn't work and hexo g return error
skip_render: "mypage/**/*"

# success
skip_render: "mypage/page.html"
```
[^1]: [Configuration | Hexo](https://hexo.io/docs/configuration#Directory)
