### ISSUE TITLE
hexo clean后找不到之前的文章了

### ISSUE THREAD

**Issue by atbj505** [hexojs/hexo#1567]
我在执行了 `hexo clean`后重新 `hexo generare`，`hexo deploy`到github上，发现之前的文章都没有了,这之间的过程都没有报错，而且本地post文件夹下也都有之前文章，不知道问题出在哪了

**Comment by luodaoyi** [comment]
source文件夹里面的还有没有md文件

**Comment by atbj505** [comment]
@luodaoyi  还有只是页面上没有了

**Comment by Xuanwo** [comment]
删除`db.json`以及`.deployer_git`之后重新生成试试看

**Comment by atbj505** [comment]
@Xuanwo  你好，刚才按照你说的方法试了下，也还是不行。

**Comment by Xuanwo** [comment]
先检查一下`public`文件夹中是否有对应的文章

**Comment by atbj505** [comment]
@Xuanwo `public`下面只有今年十月的一篇文章了

**Comment by Xuanwo** [comment]
你的md文件在`_post`目录下么？

**Comment by atbj505** [comment]
恩`_post`下面所有的文章都在，`public `下面却只有10月的文章

**Comment by Xuanwo** [comment]
拷贝所有的文件到一个新的hexo目录下，重新hexo init之类的

**Comment by atbj505** [comment]
恩 我重新`init`了一下就好了，多谢
