### ISSUE TITLE
win10系统hexo s以后http://localhost:4000打不开本地服务器

### ISSUE THREAD

**Issue by luodaoyi** [hexojs/hexo#1568]
不知道为啥

![状态图](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028220324.png)
![hexo版本](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028220014.png)
![打不开](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028220422.png)
![打不开](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028220226.png)
![打不开](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028220209.png)
![系统版本](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028224406.png)

**Comment by luodaoyi** [comment]
#hosts文件
![hosts文件](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028224540.png)

**Comment by luodaoyi** [comment]
部署的时候出现这个问题 
![截图](http://s.luodaoyi.com/QQ%E6%88%AA%E5%9B%BE20151028230952.png)

**Comment by Xuanwo** [comment]
初步判断是hexo与nodejs 4的兼容性问题- -

**Comment by iissnan** [comment]
应该不是 兼容性问题，因为我在 Windows 10 下可正常使用 Hexo （Node.js）版本是 4。报 `source.replace` 出错，很有可能是解析 `source` 的时候出错了。试试检查下文章（*.md）是否有可疑的问题。

最简单的方式，将你当前 `source` 目录下的所有 `md` 文件剪切到别的地方，然后新建一篇简单的 post，快速验证下是否是文章的问题。

**Comment by luodaoyi** [comment]
首页都不出来 我在MAC下各种正常

**Comment by luodaoyi** [comment]
重新建了新文档只执行
```
hexo init
hexo install
hexo s
```
问题依旧依然是 无法显示此页面

**Comment by Xuanwo** [comment]
`hexo install`? 你是打错了还是确实输错了命令？

**Comment by Xuanwo** [comment]
@luodaoyi https://github.com/hexojs/hexo/issues/1568#issuecomment-152747244 这个回复里面的`hexo install` 是你打错了么？

**Comment by ccc013** [comment]
@luodaoyi 你好，我想问下你有没有解决这个问题，因为我用的也是win10系统，在运行hexo s这个命令后，输入localhost:4000，或者是http://0.0.0.0:4000/，也是显示无法显示网页的。

**Comment by houzi-** [comment]
@ccc013其实你可以尝试换一下端口

**Comment by williamstar** [comment]
@luodaoyi @ccc013  我也遇到这个问题，我是这样解决的。 hexo s -p 3600   换一个3600的端口号就可以了，如果0.0.0.0不可以就用127.0.0.1

**Comment by qiumuch** [comment]
github改成git

https改成http

**Comment by fych** [comment]
@williamstar 谢谢你，你解决了困扰我很久的问题，果然换了一下端口号就好了。
@iissnan ，我想问一下你不需要换端口号都可以吗，我试了好久，只有更换端口号才能解决这个问题。hexo在win10上好奇怪。

**Comment by Xuanwo** [comment]
@fych 肯定不是win10的问题，可能你本地占用了这个端口之类的

**Comment by iissnan** [comment]
@fych 我这边没有问题。

**Comment by JackyLauwj** [comment]
@Xuanwo @iissnan @williamstar @luodaoyi 
![default](https://cloud.githubusercontent.com/assets/20140964/17273991/80cab356-56fd-11e6-8794-e8e07e562174.PNG)
哈喽各位，我自己鼓捣hexo很长时间了，每次出错我都是删了本地文件同时把github上的也删了。
按照google上能看的方法都看了，我对照各个方法都试过还是有两个问题解决不了。
问题一：如图所示我启动本地服务还是打不开本地端口
[问题二：](jackylauwi.com)jackylauwi.com     这是我的博客网站，不管怎么上传同步更换主题，一直是这个老样子。这个根本就跟hexo没有关系，一直是github负责修改的，但是我安装hexo这些半天了还是解决不了

**Comment by skjgithub950423** [comment]
我也是同样的问题 你解决了么？

**Comment by skjgithub950423** [comment]
@JackyLauwj

**Comment by JackyLauwj** [comment]
@skjgithub950423 没有啊，不知道问题出在哪里。。。。。

**Comment by skjgithub950423** [comment]
用ie试一下，我的用ie打开就好了

**Comment by JackyLauwj** [comment]
@skjgithub950423
还有就是我现在的博客地址Jackylauwj.com绑定了GitHub。我把hexo也安装了，主题也都换了。但页面还是那样子———GitHub Page。我如果只是想把博客做成这个样子根本连hexo都用不到，我把ssh key也和本地绑定了，实在没办法了。。。。。。

**Comment by Xuanwo** [comment]
你能不能先把代理关了？

**Comment by JackyLauwj** [comment]
@Xuanwo
那个端口地址打不打开不重要，问题我的博客现在只显示GitHub Page的。。。到底哪里出了问题。

**Comment by jm0477** [comment]
@williamstar 正解，我也碰到这个问题了， win10系统，默认4000打不开。关掉防火墙也不行，换个端口就行了。。

**Comment by 1PxUp** [comment]
如果用了代理，关掉试试，比如Shadowsocks. 我遇到的情况是chrome打不开,ie可以打开。

**Comment by meiyuesheng** [comment]
感谢@williamstar ，是默认端口被占用，查看了下发现是Foxit阅读器的一个进程，默认端口被占用也不报错，建议作者给个提示。

**Comment by leiyunhe** [comment]
@williamstar 感谢感谢。换了个端口可以了。

**Comment by 1162436661** [comment]
我的关掉也没有用，我的firefox一直显示：Firefox 无法建立到 localhost:4000 服务器的连接，切换端口都没有用，请问你们怎么解决的

**Comment by guili618** [comment]
感谢@williamstar，win7下面用先用netstat -aon|findstr "4000"看了下，hexo的服务没有启动之前，确实4000端口已经被占用了，用 hexo s -p 端口号 解决了，谢谢

**Comment by daohewang** [comment]
hexo clear之后本来正常运行的localhost:4000服务器就失效了，求解

**Comment by heliuphy** [comment]
真的换下端口接好了~！非常感谢

**Comment by gaotingqi** [comment]
换了端口也不行呀，检查了一下**4000**端口就是被hexo用着呢，*该如何解决？*

**Comment by Andywang089** [comment]
Git中Ctrl + C是stop的快捷键，不要使用Ctrl + C或Ctrl + V的快捷键，用右键。

**Comment by Andywang089** [comment]
hexo s 后如果使用 Ctrl + C和Ctrl + V到浏览器访问肯定会无法访问，因为Ctrl + C会停止 server。
Git中Ctrl + C是stop的快捷键，不要使用Ctrl + C或Ctrl + V的快捷键，用右键。

**Comment by sonichuang** [comment]
> Git中Ctrl + C是stop的快捷键，不要使用Ctrl + C或Ctrl + V的快捷键，用右键。
是的，我也是打不开http://localhost:4000/， 在hexo s后不使用Ctrl + C就可以打开。但是现在问题是那个git bash怎么关闭呢？如果不用Ctrl + C他一直在运行当中，这个怎么解决？

**Comment by sumqzm** [comment]
我是在阿里云的服务器上部署的hexo，hexo server启动成功了，端口也没被占用，换了端口也还是打不开本地网页，很是郁闷啊。。。

**Comment by heliuphy** [comment]
> 我是在阿里云的服务器上部署的hexo，hexo server启动成功了，端口也没被占用，换了端口也还是打不开本地网页，很是郁闷啊。。。

@sumqzm 是不是防火墙没开端口？

**Comment by sumqzm** [comment]
@heliuphy 已经开放了啊 我用“firewall-cmd --zone=public --list-ports”查看，显示“80/tcp 4000/tcp” 应该是这两个端口都开放了。

**Comment by zhaoxinkun** [comment]
兄弟们，说一下，不是端口问题，4000端口打不开是因为你是从git窗口里复制的http://localhost:4000/地址，你只要复制就自动关闭服务了，你把地址手打上去，就是输入hexo s之后，不要进行复制操作，直接去浏览器里自己输入地址打开就行了
