### ISSUE TITLE
hexo内容中"#标题一",无法识别,加空格后可以识别

### ISSUE THREAD

**Issue by Jackroyal** [hexojs/hexo#1570]
之前写标题的时候,都是"#标题"这种写法,hexo可以正常识别,
现在必须写成"# 标题",要多加一个空格,这样就导致之前写的博客的标题全都不能识别了.
这是我这边出bug了吗?还是hexo修改了规则?
之前我用的是hexo 2.8,现在升级3.0了
而且,升级3.0后,刚开始也是可以识别不要空格的写法,但是现在又不能识别了

**Comment by luodaoyi** [comment]
你的语法不严谨

**Comment by Xuanwo** [comment]
推荐`# 标题`的写法

**Comment by Enolak** [comment]
语法的问题

**Comment by Jackroyal** [comment]
额,看来之前看的教程不规范,所以语法不严谨.
而且,最近还发现,貌似标题前面要加一个换行,不然,标题还是认不出来
