### ISSUE TITLE
404跳转问题

### ISSUE THREAD

**Issue by allenjin** [hexojs/hexo#1573]
我是通过hexo server运行，在source目录下添加404.html，当输入无效链接时，并不跳转到404页面，而是在浏览器显示cannot GET 的错误，如何进行设置404？

**Comment by luodaoyi** [comment]
添加到主题的source目录下面试试看

**Comment by allenjin** [comment]
都添加过没效果。

**Comment by Xuanwo** [comment]
如果是正式部署，建议apache以及nginx之类的服务器套件，hexo自带的server是设计目的是为了调试用，并不支持很多功能特性

**Comment by allenjin** [comment]
谢谢提醒，通过nginx来访问生成的静态页面可以解决问题。
