### ISSUE TITLE
为什么设置了theme，开始访问github pages时，主题失效

### ISSUE THREAD

**Issue by qingsong-xu** [hexojs/hexo#1574]
我是采用hexo + github 搭建的，设置了主题（采用hexo的默认主题），使用hexo server 访问本地服务时，一切正常，可是部署到XXX.github.io后，访问次网址时，文字内容存在，但是杂乱无章，没有主题（背景一片空白）

**Comment by Xuanwo** [comment]
检查一下自己的网址等设置是否正确

**Comment by qingsong-xu** [comment]
已经解决了，的确是网址设置有问题。thank you.

**Comment by timberjackyeye** [comment]
给后来者一些更详细的提示
在你_config.yml文件中有个 url: 要写成
url: https://你的github名字.github.io/你的github名字.github.io
我这么做了后才能把themes加载进去
