### ISSUE TITLE
Highlight.js classes

### ISSUE THREAD

**Issue by amejiarosario** [hexojs/hexo#1575]
Why [hexo.util.highlight](https://github.com/hexojs/hexo-util/blob/ee32f57fe27a55da36af67a5d0cda274ee868022/lib/highlight.js#L57)  doesn't keep the default class so we can leverage [all the styles for highlight.js made by the community](https://github.com/isagalaev/highlight.js/tree/master/src/styles)?

**Comment by Xuanwo** [comment]
maybe we can provide an option for people to use.

**Comment by pimskie** [comment]
+1 Now it's very hard to change the style of the code highlighting.

**Comment by apeipo** [comment]
+1 now it's total different with highlight.js
