### ISSUE TITLE
无法正确编译静态文件？

### ISSUE THREAD

**Issue by Tk-archer** [hexojs/hexo#1576]
是这样的
我在尝试写hexo主题时，用bower引入了material-design-lite
目录结构如下
![1egbl61 n qloij3z3 ns 7](https://cloud.githubusercontent.com/assets/5762459/10885929/b50aab62-81ba-11e5-9053-2063d604764c.png)

然后hexo s或者g的结果却是
MDL 的js文件被编译到index中
变成这样....
![1_ k ai 2mg_v9f gshwe5](https://cloud.githubusercontent.com/assets/5762459/10886016/243f1e28-81bb-11e5-9ddc-104adaadd25e.png)
这是怎么一回事？

**Comment by Xuanwo** [comment]
@Tk-archer 我也不是非常清楚- -你的layout是怎么写的？
