### ISSUE TITLE
post.excerpt与post.content中的链接

### ISSUE THREAD

**Issue by nshen** [hexojs/hexo#1577]
发现excerpt中的链接是在本页打开，content中的链接是在blank里打开？
是这样的吗？

content	解析后的文章内容
excerpt	解析后的文章摘要

**Comment by Xuanwo** [comment]
是

**Comment by nshen** [comment]
怎么才能把excerpt中的链接也加上blank呢？不然用户点击外部链接直接就跳转走掉了：（

**Comment by Xuanwo** [comment]
插入HTML代码吧- -
