### ISSUE TITLE
能不能对 .html 不处理

### ISSUE THREAD

**Issue by guoshuang** [hexojs/hexo#158]
和 #148 一样的问题

前几天的版本 对 source 中的 .htm .html 不处理，可以写一些自己的页面
今天升级以后就不行了 —.htm .html 文件都会被当成 .md 处理

我觉得只处理 .md 文件就好，其它 copy 到 public 就行了。

**Comment by asdf2014** [comment]
是呀，根目录下 想放一些 自己写的 html/md 文件，各种乱编译了，，skip_render是针对 source_dir的，更目录 就不好弄了~~~

**Comment by asdf2014** [comment]
貌似 skip_render不支持 直接写 `*.html`可以不用正则表达式，直接写完全的文件名就可以了：）
```bash
skip_render:
 - google1a26b0b2267d26d7.html
```
