### ISSUE TITLE
Hexo部署到GitHub，提交文件不完整，缺失index.html等

### ISSUE THREAD

**Issue by cbbing** [hexojs/hexo#1583]
执行后，
```
hexo clean
hexo g
hexo d
```
github上的文件与public文件夹下的不对应。

![Image of Hexo](http://7xo67b.com1.z0.glb.clouddn.com/issue_bug_hexo.png)

为什么public文件夹中的 **“2015”，“archives”，“index.html"** 无法上传到github？

下面是部署输出：
```
bogon:Hexo cbb$ hexo d
INFO  Deploying: git
INFO  Clearing .deploy folder...
INFO  Copying files from public folder...
[master ebdeef7] Site updated: 2015-11-09 10:35:18
 29 files changed, 1397 insertions(+), 4640 deletions(-)
 delete mode 100644 css/fonts/FontAwesome.otf
 delete mode 100644 css/fonts/fontawesome-webfont.eot
 delete mode 100644 css/fonts/fontawesome-webfont.svg
 delete mode 100644 css/fonts/fontawesome-webfont.ttf
 delete mode 100644 css/fonts/fontawesome-webfont.woff
 create mode 100644 css/grids-responsive-min.css
 delete mode 100644 css/images/banner.jpg
 rename {fancybox => css}/jquery.fancybox.css (90%)
 create mode 100644 css/normalize.css
 create mode 100644 css/pure-min.css
 rewrite css/style.css (90%)
 delete mode 100644 fancybox/fancybox_loading.gif
 delete mode 100644 fancybox/fancybox_loading@2x.gif
 delete mode 100644 fancybox/helpers/fancybox_buttons.png
 delete mode 100644 fancybox/helpers/jquery.fancybox-buttons.css
 delete mode 100644 fancybox/helpers/jquery.fancybox-buttons.js
 delete mode 100644 fancybox/helpers/jquery.fancybox-media.js
 delete mode 100644 fancybox/helpers/jquery.fancybox-thumbs.css
 delete mode 100644 fancybox/helpers/jquery.fancybox-thumbs.js
 delete mode 100644 fancybox/jquery.fancybox.js
 delete mode 100644 fancybox/jquery.fancybox.pack.js
 create mode 100644 fonts/icomoon.eot
 create mode 100644 fonts/icomoon.svg
 create mode 100644 fonts/icomoon.ttf
 create mode 100644 fonts/icomoon.woff
 create mode 100644 js/fancybox.pack.js
 create mode 100644 js/jquery.min.js
 delete mode 100644 js/script.js
 create mode 100644 js/totop.js
To https://github.com/cbbing/cbbing.github.io.git
   9feef74..ebdeef7  master -> master
Branch master set up to track remote branch master from https://github.com/cbbing/cbbing.github.io.git.
INFO  Deploy done: git
bogon:Hexo cbb$ 
```
 
hexo配置：
```
bogon:Hexo cbb$ hexo version
hexo: 3.1.1
os: Darwin 15.0.0 darwin x64
http_parser: 2.5.0
node: 4.2.2
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
```

**Comment by Lyken17** [comment]
请教一下你hexo的_config.xml是怎么设置的，我这里hexo deploy部署不了。

**Comment by jianwwpro** [comment]
我也是部署不了，配置了github地址
deploy:
 71   type:github
 72   repository:git@github.com:user/blog.git

**Comment by Xuanwo** [comment]
@jianwwpro 注意yml格式，英文冒号后面要有一个空格

**Comment by Xuanwo** [comment]
@cbbing 未能重现你的问题，你可以将`deployer_git`那个文件夹删掉重新生成试试看

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest version.

**Comment by PangPangPangPangPang** [comment]
我也遇到了这个问题
 deploy:
  type: git
  repo: git@github.com:PangPangPangPangPang/PangPangPangPangPang.github.io.git
  branch: master
只能部署这些
![7628e114-c6f3-41eb-b050-156c92e92153](https://cloud.githubusercontent.com/assets/8207475/12031705/4b57d304-ae4a-11e5-81a1-c33cd623893c.png)

**Comment by Xuanwo** [comment]
@PangPangPangPangPang 你用的主题是什么？看上去你没有生成主页，检查一下是否正确进行了安装。

**Comment by heqingbao** [comment]
@cbbing 默认生成的.gitignore里面忽略掉了*public/*目录 .

**Comment by cbbing** [comment]
@heqingbao 去掉了.gitignore中的public，还是不行。我现在是用sourcetree手动把public同步上去，用的也还行。

**Comment by heqingbao** [comment]
@cbbing 不要手动同步public里面的内容，在**站点配置文件**里面配置好deploy后，使用`hexo deploy`同步public里面的内容。

在源码工程中，public内容是自动生成的，所以ignore掉了。

我现在的做法是pages是一个独立的responsity，里面只有public目录里面的内容（`hexo deploy`自动同步的），另一个responsity专门用来保存源码。你也可以在一个responsity里面通过分支来做。

https://github.com/heqingbao/blog
https://github.com/heqingbao/heqingbao.github.io

**Comment by leesei** [comment]
@heqingbao 
用branch 就可以省一個repo
source: https://github.com/leesei/leesei.github.io
HTML: https://github.com/leesei/leesei.github.io/tree/master (其他repo就是`gh-pages` branch`)

**Comment by heqingbao** [comment]
嗯，对的。

2016年2月22日星期一，leesei <notifications@github.com> 写道：

**Comment by tjuzl** [comment]
出现无法 `html` 文件的问题的可能原因是没有自动启用插件，具体解决方案请看[这篇博客](http://blog.tangxiaozhu.com/p/45374067/)的最后。

**Comment by Changzw** [comment]
1. 到 hexo 项目 root 目录
2. cd .deploy_git
3. git ls-files --others -i --exclude-standard，查看git 版本控制中有没有你这个文件
4. 如果有 这个 index.html
5. 实例

eg 我的是  tags 页面丢失 404 

使用 3 得到 tags/... 没有被git 管理

```shell
git add -f tags
git commit 
```

>[参考](https://stackoverflow.com/a/15931542/6103118)
