### ISSUE TITLE
关于{% %}这个标记引发的bug问题

### ISSUE THREAD

**Issue by qinyuanpei** [hexojs/hexo#1584]
我自己编写了一个插件[https://github.com/qinyuanpei/hexo-tag-cloudmusic](https://github.com/qinyuanpei/hexo-tag-cloudmusic)，可以利用这个标记生成网易云音乐的widget结构，但是当我试图在文章中使用{% %}对这个插件的用途进行解释的时候，每次生成页面都会报错，我猜测是程序会对所有的这样的{% %}的字符进行处理，即使我使用了代码块或者是双引号，我删除文章中的这个后就正常了。请问作者是这样吗？

**Comment by Xuanwo** [comment]
是

**Comment by leesei** [comment]
Nunjucks intercepted {% %} to support block tags.
Use [`{% raw %}` block](https://hexo.io/docs/troubleshooting.html#Escape_Contents) to override it.

**Comment by qinyuanpei** [comment]
看来我的猜测还是比较准的啊，找时间把这个插件继续完善下！

**Comment by reverland** [comment]
直接html也行。。。

**Comment by qinyuanpei** [comment]
直接写HTML太长太麻烦
