### ISSUE TITLE
generate命令可否支持輸出到指定路徑？

### ISSUE THREAD

**Issue by eimsteim** [hexojs/hexo#1585]
我查看了hexo generate help，結果發現并沒有這樣的參數，以至於我無法指定生成public目錄的路徑，或者動態指定public目錄的名稱，希望可以在generate命令中加上這樣的參數，謝謝！

**Comment by leesei** [comment]
Try changing:
`public_dir: public`

**Comment by eimsteim** [comment]
get it, thx!
