### ISSUE TITLE
How to add another directory when hexo deploy?

### ISSUE THREAD

**Issue by Logicxcz** [hexojs/hexo#1587]
Is ony the public directory will be deployed? 
How to add another directory when hexo deploy?

**Comment by leesei** [comment]
You can put files in `source/` and they will be copied to `public/`.
Hexo only deploys `public/`.

**Comment by Xuanwo** [comment]
@Logicxcz 
Hello, problem solved?

**Comment by rbkpro** [comment]
How to make it don't apply the actual theme?
Cz I have a sperate folder "about" have a sperate CSS and JS files
