### ISSUE TITLE
Migrating from jekyll to hexo

### ISSUE THREAD

**Issue by reverland** [hexojs/hexo#1589]
Hi, I'm just migrating from jekyll to hexo. 

 `new_post_name` and `permalink`  to

      permalink: :category/:year/:month/:day/:title/
      new_post_name: :year-:month-:day-:title.md # File name of new posts

However, many of my `*.md` files are like this:

    2014-06-13-.md

The permalink will become:

    2015/11/13/2014-06-13.html

Thats not what i want, it should be as jekyll will give.

    /2014/06/13/

So I changed the [hexo-util/lib/permalink.js(L28)](https://github.com/hexojs/hexo-util/blob/cb685f19ecb5ba9ee48109049b21a21cd3da7dee/lib/permalink.js#L28) to 

     return '(.*?)';

so I can get permalink like 

    http://xxx.org/life/2014/12/24//

which won't break previous urls when I use jekyll

    http://xxx.org/life/2014/12/24/

I don't know if it is a considerable idea to allow "" slug so that it won't regard the whole filename as title. 

ps: The hexo server is slow and takes lots of memory and cpu before it really start. I find similar issues but don't dive into it much.

**Comment by reverland** [comment]
And there are only 10 items show on pages for achieve/each category/each tag   and no pagination (According to the doc, it should have...)for default landscape theme. did I miss something?

**Comment by reverland** [comment]
发现链接都是这个形式的看上去很不舒服
　
　　　http://xxx.org/life/2014/12/24//

我想试着在生成permalink的时候做个判断

一切都运行良好，可还是很多页面的disqus评论消失了，也不知道为什么。即使按照之前的url输入依然消失掉。不知道其他从jekyll迁移过来的人有什么指教没

**Comment by reverland** [comment]
I added [helper/url_for](]https://github.com/hexojs/hexo/blob/d035d19ccd221f6815634c2d6d2aaa59b959839f/lib/plugins/helper/url_for.js#L6):

    path = path.replace(/\/{2,}/g, '/');

before　

　var data = url.parse(path);

so the link

    http://xxx.org/life/2014/12/24//

will be

    http://xxx.org/life/2014/12/24/

now

**Comment by reverland** [comment]
however, in the git version of  [helper/url_for](https://github.com/hexojs/hexo/blob/d035d19ccd221f6815634c2d6d2aaa59b959839f/lib/plugins/helper/url_for.js#L6),

the last post's problem has been fixed already...

**Comment by Xuanwo** [comment]
@reverland, yeee, look like I merge the pr to fix this.....
So, is there any problem?

**Comment by reverland** [comment]
@Xuanwo 

https://github.com/hexojs/hexo-util/issues/7

我理解错什么了么？

**Comment by Xuanwo** [comment]
*好像是我理解错了- -，但我记得我合并过一个修改链接最后多一个斜杠的PR啊。。*

```
permalink: :category/:year/:month/:day
new_post_name: :year-:month-:day.md # File name of new posts
```
This will be OK?

**Comment by reverland** [comment]
@Xuanwo 抱歉。。。是另外的问题，双斜杠那个我改过发现git里已经改了。。。

是最开始post描述的迁移问题。文件名像这样

    2015-11-29-.md

但在permalink和post_name里指定包含title了。

**Comment by reverland** [comment]
斜杠没问题了，抱歉，我是奇怪hexojs/hexo-util#7里的正则。。。

**Comment by Xuanwo** [comment]
这个- -，我想作者也没有考虑没有标题的情况。。。

**Comment by reverland** [comment]
@Xuanwo 嗯。。。无关紧要，我本地改了就是。。。
