### ISSUE TITLE
Filters are not working

### ISSUE THREAD

**Issue by kqkq** [hexojs/hexo#1590]
In official documents https://hexo.io/api/filter.html#after_post_render

Following code is used to add a link on twitter account.

```
hexo.extend.filter.register('after_post_render', function(data){
  data.content = data.content.replace(/@(\d+)/, '<a href="http://twitter.com/$1">#$1</a>');
  return data;
});
```

I save the code in a js file and place it in scripts directory. After clean & re-generate, nothing happened.

**Comment by kqkq** [comment]
Sorry my mistake...CLOSED.

**Comment by skryvets** [comment]
It would be nice if you post a solution to the problem as other people may face it as well...
