### ISSUE TITLE
Space before fenced code

### ISSUE THREAD

**Issue by xerosanyam** [hexojs/hexo#1592]
I am using fenced code block to put code in my posts, but a lot of space is getting inserted.
However, if I use {% codeblock %} the space goes.
The problem in using {% codeblock %} is that the markdown preview doesn't render it properly. 
Any suggestions on how to reduce space in fenced markdown ?
I am adding image for reference. 1st one is with {% codeblock %}, second one is with backtick fenced block(`bash ....`)
![screenshot from 2015-11-16 12 01 03](https://cloud.githubusercontent.com/assets/3167278/11176189/95a62930-8c60-11e5-9c90-ce725d744ece.png)

**Comment by reverland** [comment]
Have you tried to press F12, and check the css of the `pre` element that contains line numbers?

I guess, may be not spaces being inserted, but just in your theme. There is a padding-right for the `pre` element there.

**Comment by Xuanwo** [comment]
@xerosanyam , Can you provide the link to your post?

**Comment by leesei** [comment]
http://leesei.github.io/hexo-vanilla-site/2016/02/23/1592/

This occurs in list.

**Comment by alvesjtiago** [comment]
@xerosanyam @Xuanwo @leesei I was investigating this bug and the issue seems to be related to the markdown render (https://github.com/evilstreak/markdown-js/issues/208). It shouldn't be adding an extra ```<p>``` tag to the ```<li>``` element. Fixing this issue should prevent the extra space on the backtick fenced block.

**Comment by NoahDragon** [comment]
@alvesjtiago Thanks for pointing this out. Maybe we could try other markdown engine instead.

**Comment by stevenjoezhang** [comment]
The maintainers of markdown-js did not respond to this issue: https://github.com/evilstreak/markdown-js/issues/208
I suggest using other renderers instead, e.g. hexo-renderer-marked
