### ISSUE TITLE
关于文章ID的一些问题和建议

### ISSUE THREAD

**Issue by tangkunyin** [hexojs/hexo#1595]
这个post id每次重新生成文章时（hexo g）都会变化。引发的问题是如果用这个id作为第三方平台的唯一标识，那就会出问题。比如我用搜狐畅言做评论，这篇文章id变动后，评论就没了。你可以想一下，如果用户将此网页收藏了，但是重新生成后，链接就变了，用户保存的收藏就没了。
建议此处的id用时间戳表示。发布时的时间是可控的，等有时间我会考虑优化这块，不知大家怎么想....

**Comment by Xuanwo** [comment]
所以不要用post id，我记得第三方平台本身就可以用时间戳作为参数

**Comment by tangkunyin** [comment]
对。最后我还是通过自定义模板解决这个了。如果内置上时间戳属性，就完美了

**Comment by Xuanwo** [comment]
恩？时间戳不是自己给的么？post本身就是时间这个属性的~

**Comment by zhaoyao91** [comment]
还是建议提供一个简单易用的固定id功能。非常重要。
