### ISSUE TITLE
Twice before_post_render when rendering

### ISSUE THREAD

**Issue by m80126colin** [hexojs/hexo#1596]
As title, I try to append a number X before my post's title by using filter but I found that X appears **twice** before my title. Is there something wrong?

**Comment by reverland** [comment]
Maybe you can talk more about how can you do that in detail.

I'd like to dive deeper in Hexo when I try to customize something to accommodate to my previous jekyll configurations. However, there are not clear docs except tons of js code......

I hope there will be some one write more about how it works for there are still some problem, I failed, and many others failed neither when they want to tweak it more

**Comment by m80126colin** [comment]
Since I just wrote a `filter` of `before_post_render`, I'll try my best to trace how it works.
