### ISSUE TITLE
How to Query DB in a plugin?

### ISSUE THREAD

**Issue by robertwalsh0** [hexojs/hexo#1600]
I'm trying to create a plugin for Hexo and it's in the scripts folder. I'm trying to write tests for it as I develop it with jasmine-node. How do I make db queries in my spec file? For instance, I don't have the `site` variable available and writing `require('site')` doesn't solve the problem.

**Comment by Xuanwo** [comment]
read this https://hexo.io/api/locals.html may be helpful~
