### ISSUE TITLE
每次npm install都出现错误，不知道什么原因。

### ISSUE THREAD

**Issue by HeliosWu** [hexojs/hexo#1603]
Helios_PC@Helios MINGW64 /f/github/de
$ hexo init
INFO  Copying data to F:\github\de
INFO  You are almost done! Don't forget to run 'npm install' before you start blogging with Hexo!

Helios_PC@Helios MINGW64 /f/github/de
$ npm install
npm WARN optional dep failed, continuing fsevents@1.0.5 //每次npm install都出现这个
npm WARN optional dep failed, continuing fsevents@0.3.8 //每次npm install都出现这个
//每次npm install，还出现下面我看不懂的。
> dtrace-provider@0.6.0 install F:\github\de\node_modules\hexo\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

hexo-generator-index@0.1.3 node_modules\hexo-generator-index
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-generator-archive@0.1.3 node_modules\hexo-generator-archive
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-generator-tag@0.1.2 node_modules\hexo-generator-tag
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-generator-category@0.1.3 node_modules\hexo-generator-category
├── object-assign@2.1.1
└── hexo-pagination@0.0.2 (utils-merge@1.0.0)

hexo-renderer-ejs@0.1.0 node_modules\hexo-renderer-ejs
├── lodash@2.4.2
└── ejs@1.0.0

hexo-server@0.1.2 node_modules\hexo-server
├── object-assign@2.1.1
├── open@0.0.5
├── mime@1.3.4
├── bluebird@2.10.2
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── morgan@1.6.1 (on-headers@1.0.1, basic-auth@1.0.3, depd@1.0.1, on-finished@2.3.0, debug@2.2.0)
├── connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@0.4.0)
├── compression@1.6.0 (bytes@2.1.0, on-headers@1.0.1, vary@1.1.0, debug@2.2.0, compressible@2.0.6, accepts@1.3.0)
└── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)

hexo-renderer-stylus@0.3.0 node_modules\hexo-renderer-stylus
├── stylus@0.52.4 (css-parse@1.7.0, debug@2.2.0, sax@0.5.8, mkdirp@0.5.1, source-map@0.1.43, glob@3.2.11)
└── nib@1.1.0 (stylus@0.49.3)

hexo-renderer-marked@0.2.5 node_modules\hexo-renderer-marked
├── object-assign@2.1.1
├── marked@0.3.5
├── strip-indent@1.0.1 (get-stdin@4.0.1)
└── hexo-util@0.1.7 (ent@2.2.0, bluebird@2.10.2, highlight.js@8.9.1)

hexo@3.1.1 node_modules\hexo
├── hexo-front-matter@0.2.2
├── pretty-hrtime@1.0.1
├── abbrev@1.0.7
├── titlecase@1.0.2
├── archy@1.0.0
├── text-table@0.2.0
├── tildify@1.1.2 (os-homedir@1.0.1)
├── strip-indent@1.0.1 (get-stdin@4.0.1)
├── chalk@1.1.1 (ansi-styles@2.1.0, escape-string-regexp@1.0.3, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── hexo-i18n@0.2.1 (sprintf-js@1.0.3)
├── moment-timezone@0.3.1
├── bluebird@2.10.2
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── through2@1.1.1 (xtend@4.0.1, readable-stream@1.1.13)
├── swig-extras@0.0.1 (markdown@0.5.0)
├── warehouse@1.0.3 (graceful-fs@4.1.2, cuid@1.2.5, JSONStream@1.0.7)
├── js-yaml@3.4.3 (esprima@2.7.0, argparse@1.0.3)
├── moment@2.10.6
├── nunjucks@1.3.4 (optimist@0.6.1, chokidar@0.12.6)
├── swig@1.4.2 (optimist@0.6.1, uglify-js@2.4.24)
├── hexo-cli@0.1.9 (minimist@1.2.0, bluebird@3.0.5)
├── bunyan@1.5.1 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.6.0)
├── cheerio@0.19.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.0.0, htmlparser2@3.8.3)
├── hexo-util@0.1.7 (ent@2.2.0, highlight.js@8.9.1)
├── lodash@3.10.1
└── hexo-fs@0.1.5 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, bluebird@3.0.5, chokidar@1.3.0)

调试信息：
21:31:01.545 DEBUG Hexo version: 3.1.1
21:31:01.569 DEBUG Working directory: F:\github\de\
21:31:02.039 DEBUG Updating package.json
21:31:02.084 DEBUG Config loaded: F:\github\de\_config.yml
21:31:02.132 DEBUG Script loaded: themes\landscape\scripts\fancybox.js
21:31:02.146 DEBUG Plugin loaded: hexo-generator-category
21:31:02.161 DEBUG Plugin loaded: hexo-generator-archive
21:31:02.177 DEBUG Plugin loaded: hexo-generator-index
21:31:02.242 DEBUG Plugin loaded: hexo-renderer-ejs
21:31:02.257 DEBUG Plugin loaded: hexo-generator-tag
21:31:03.002 DEBUG Plugin loaded: hexo-renderer-stylus
21:31:03.310 DEBUG Plugin loaded: hexo-renderer-marked
21:31:04.039 DEBUG Plugin loaded: hexo-server
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  server    Start the server.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
21:31:04.095 DEBUG Database saved
版本信息：
$ hexo version
hexo: 3.1.1
os: Windows_NT 10.0.10240 win32 x64
http_parser: 2.5.0
node: 4.2.2
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d

**Comment by reverland** [comment]
只是警告吧，好像没什么影响

**Comment by Xuanwo** [comment]
warning无所谓的，不想看到的话可以`npm install --no-optional`
