### ISSUE TITLE
如何让tag显示时不排序？

### ISSUE THREAD

**Issue by vimer** [hexojs/hexo#1606]
如何按照设定的tag顺序显示，而不是按照字母排序

**Comment by reverland** [comment]
在显示到主题中时重新排序可以么。。。

**Comment by vimer** [comment]
@reverland 不知道hexo有没有什么变量可以控制这个顺序的

**Comment by reverland** [comment]
@vimer 不知道你是不是这个意思

https://github.com/hexojs/hexo/blob/534102e6992bfb4df975a724846993617edcf988/lib/plugins/helper/list_tags.js#L23

**Comment by vimer** [comment]
@reverland 是的，所以我要禁用这个排序

**Comment by reverland** [comment]
@vimer 注释掉。。。真快

**Comment by vimer** [comment]
@reverland  恩 目前方法看来只能注释掉了

**Comment by reverland** [comment]
@vimer 不只。。。我没空细看

https://github.com/hexojs/hexo/blob/534102e6992bfb4df975a724846993617edcf988/test/scripts/helpers/list_tags.js#L107

**Comment by vimer** [comment]
@reverland 我的意思只能通过改动源码解决，最好作者能加个变量来控制下。

**Comment by reverland** [comment]
@vimer https://hexo.io/zh-cn/docs/helpers.html#list_tags 我想是有api的

只是没想到英文的文档这么简略。。。竟然比中文简略一直没发现。。。

**Comment by vimer** [comment]
@reverland  good，thx ！
