### ISSUE TITLE
Post level permalink does not override site config

### ISSUE THREAD

**Issue by dsolovay** [hexojs/hexo#1608]
The post permalink does not override the _config.yml setting, but rather replaces the :title element. For example, suppose the setting in _config.yml is this:

```
permalink: :year/:month/:day/:title/
```

And suppose you want to change this for certain posts to year/month/title.html.  If you set the post permalink to a value like this:

```
permalink: /2015/11/some-title/
```

You will end up with a post with this URL:

   /2015/11/25/2015/11/some-title/

hexo -version info:  

```
hexo: 3.1.1
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.4 
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by dpaquette** [comment]
I am seeing the same behavior

**Comment by pozitron57** [comment]
Have the same problem! :+1:

**Comment by churchs19** [comment]
Me too.

**Comment by kynetiv** [comment]
Same issue here. I wonder how the migrator plugins handle this.

**Comment by dsolovay** [comment]
Will look at fixing this as part of https://24pullrequests.com/.  Leaving a comment to un-stale it.
