### ISSUE TITLE
Throw an error when execute "hexo g"

### ISSUE THREAD

**Issue by malcolmyu** [hexojs/hexo#1609]
Hexo throws an error in this [line](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/list_categories.js#L34), it seems like that `categories` has been recognize as a plain array, and the argument of `Array.find` must be a function.

**Comment by Xuanwo** [comment]
your md ?

**Comment by malcolmyu** [comment]
@Xuanwo 问题可能出在 `post.categories`，我获得的这个对象是一个原生数组，而按照[这一行](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/list_categories.js#L34)的操作，它的 `find` 方法和 `sort` 方法传的参数都不符合原生数组方法的要求，所以我怀疑 hexo 提供给主题的这个 categories 可能是一个加工过的数组。

**Comment by Xuanwo** [comment]
这不是一个数组，就我看的一些代码来看，应该是一个No-SQL数据的一个model的样子

**Comment by malcolmyu** [comment]
@Xuanwo 对，确实很像一个model，所以不清楚是什么原因导致 list_categories.js 这个文件中获得一个原生数组，从而导致 `categories` 无法被正常解析。

**Comment by malcolmyu** [comment]
@Xuanwo，我md的header如下所示：

    title: 协程与事件循环
    date: 2015-11-18
    categories: [技术研究]
    tags: [协程, yield, event loop]
    toc: true

之前一直这么写的，也没有遇到什么问题。

**Comment by Xuanwo** [comment]
我的`categories`一直只给一个参数，不用中括号包裹来着- -

你的Hexo版本是？

**Comment by malcolmyu** [comment]
3.11 ……我发现只给一个参数还是会报同样的错误

**Comment by Xuanwo** [comment]
这不科学啊，你的主题是啥啊？

**Comment by malcolmyu** [comment]
这个[主题](https://github.com/ppoffice/hexo-theme-alex)，它是[这么](https://github.com/ppoffice/hexo-theme-alex/blob/master/layout/_partial/post/category.ejs)传递 `categories` 的。

**Comment by Xuanwo** [comment]
你把中括号去掉看看还会不会报错呢？印象中这个主题是不支持多分类&子分类的。

**Comment by malcolmyu** [comment]
依然报同样的错误……在 list_categories.js 里我获取的还是一个数组……说起来 `post.categories` 是怎么生成的

**Comment by Xuanwo** [comment]
使用同样的主题建立一个的Hexo博客，如果不出错说明MD文档有问题，如果还是出错，我们再来找找Hexo或主题的问题，如何？

**Comment by malcolmyu** [comment]
=。=我解决了……是因为我不小心把一篇博文直接丢到source里了，没有放到_post路径下

**Comment by Xuanwo** [comment]
soga = =

**Comment by shanlanCoding** [comment]
> =。=我解决了……是因为我不小心把文章博文直接丢到source里了，没有放到_post路径下

巧了，我也是。。。。
