### ISSUE TITLE
Bug: Hexo treats layout.less as a template layout

### ISSUE THREAD

**Issue by johnnyshields** [hexojs/hexo#1610]
Try using this template:

https://github.com/widatama/hexo-jade-barebone

Since it's Jade, there's no `layout.jade` and instead it uses `base.jade` (given quirks of how jade works)

HOWEVER, the renderer falls back to rendering `source/stylesheets/_layout/layout.less` as the webpage, which is strange.

Renaming the less file fixes the issue.

**Comment by Xuanwo** [comment]
https://github.com/widatama/hexo-jade-starter

look like author update it again, you can have a try now
