### ISSUE TITLE
Post assets not rendered until refresh

### ISSUE THREAD

**Issue by myyc** [hexojs/hexo#1611]
For whatever reason it seems like even after generating (even using `-w`) images in posts show up as "broken" until I refresh the post page. The `img src` fields are the same in both cases.

`post_asset_folder` is enabled.

```
hexo: 3.1.1
os: Linux 3.2.0-4-amd64 linux x64
http_parser: 2.5.0
node: 4.2.2
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 55.1
modules: 46
openssl: 1.0.2d
```

**Comment by myyc** [comment]
On further inspection, turns out that, as expected, loading the post throws an exception:

`GET http://blahblah/2015/11/27/blah.svg 404 (Not Found)`

Refreshing gets rid of it. This doesn't depend on themes.

**Comment by Xuanwo** [comment]
Can you tell me the way you use hexo? In `hexo s` ?

**Comment by myyc** [comment]
Turns out the problem was due to PJAX and the theme I was using (carbon) – maybe it affects the default one as well though. Not sure what exactly caused the issue but I fixed it by removing the PJAX lines, and the dependency ... I don't really need it.

It didn't just affected `hexo s` but the static files as well.

**Comment by Xuanwo** [comment]
Got it, pjax cause it?

**Comment by leesei** [comment]
@myyc Do you have a repo that can reproduce this?
