### ISSUE TITLE
不理解为什么每次运行hexo都卡得要死要活的

### ISSUE THREAD

**Issue by reverland** [hexojs/hexo#1613]
每次generate的时候都会卡得要死要活的。jekyll虽然可能会慢些，但不致于这么卡。。。

```bash
┌─[reverland@reverland-R478-R429] - [~/blog] - [2015-11-29 11:57:07]
└─[0] <git:(master b6ad765✱✈) > hexo g
INFO  Files loaded in 1.02 min
INFO  443 files generated in 43 s
```

每次server的时候也是卡好久才有反应，不管有没有`server -s`，现在已经到了python -m SimpleHTTPServer也不愿意直接hexo server。。。

**Comment by Xuanwo** [comment]
```
INFO  Files loaded in 42 s
INFO  731 files generated in 25 s
```

你可能需要把`auto_detect`设为`false`

**Comment by reverland** [comment]
@Xuanwo  已关闭！！！

┌─[reverland@reverland-R478-R429] - [~/blog] - [2015-11-30 12:51:45]
└─[0] <git:(master b6ad765✱✈) > cat _config.yml|grep auto
  auto_detect: false

额。。。我感觉是内存小了。。。

不过话说generate下占用接近800M内存也是。。。

**Comment by Xuanwo** [comment]
是嘛- -，我都是用travis CI跑的，所以并不能理解generate各种痛苦。。。
也有可能是你的主题比较复杂，生成起来比较困难。。

**Comment by reverland** [comment]
next主题，是比较复杂吧。

内存占用太吓人了，不知道是不是因为想实现增量更新、快速生成什么的。

倒更希望虽然会慢些，但能一边干着其他事情一边慢慢生成着，起码还能看到屏幕上一直有反馈。现在是CPU和内存占用卡得什么都干不了。。。特么终端还没反应(指在开启debug的情形下)

我在考虑，有空试着看看有哪些黑科技可以剥离掉，把内存占用降下来。。。。。。

**Comment by reverland** [comment]
ps： travis CI跑的话，部署再搞个私钥？

**Comment by Xuanwo** [comment]
@reverland 我也是NexT主题啊- -

我可以强行宣传一下自己的文章： [使用Travis CI自动部署Hexo](https://xuanwo.org/2015/02/07/Travis-CI-Hexo-Autodeploy/)

**Comment by reverland** [comment]
@Xuanwo 嗯。。。有空顺手把https也加上。。。

**Comment by Xuanwo** [comment]
所言极是，2333
