### ISSUE TITLE
Include template files into articles / pages

### ISSUE THREAD

**Issue by webcultist** [hexojs/hexo#1614]
Is there a way to include template partials directly into a post file? 
I'd like to have kind of a component library, where I can reuse parts of the site in different posts. Would be great!

**Comment by Xuanwo** [comment]
your can create a new layout and put your lib in it, so every post using this layout will have the lib

**Comment by webcultist** [comment]
Yeah, that's a possible way, but it makes it hard to combine various parts in one page / post. 
When I used jekyll, it was possible to include files with the normal include tags.

It's ok, if it is not possible. Just wanted to ask if there is a way to archive this in the .md files.
Currently I use swig for my project (if this matters somehow).

But thank you for your answer =)

**Comment by Xuanwo** [comment]
I marked it as a feature to include files (as plain text?) into post.

And for now , my way is to use `{{%raw%}}` tags
