### ISSUE TITLE
deploy problem

### ISSUE THREAD

**Issue by gabygoole** [hexojs/hexo#1615]
After I install hexo-deployer-git,I edit the `<config.yml>`.I set set the message default to `<Site updated: {{ now("YYYY-MM-DD HH:mm:ss") }}>`. After I generate it, I deploy it.It told me:I lack a colon  at last.Then I add the colon.I deploy,everything is ok.I wonder if your official doc is wrong?

**Comment by gabygoole** [comment]
after edit is _config.yml
after default is :Site updated: {{ now("YYYY-MM-DD HH:mm:ss") }}

**Comment by Xuanwo** [comment]
~~It's hard for me to understand what are you saying.~~
*Well, I get the idea- -, you don't need to add a new comment, you can modify your comment at any time.*

**Comment by Xuanwo** [comment]
So, What's your deploy config now? Just paste it, or I don't know where problem is.

**Comment by leesei** [comment]
@gabygoole Can you post you deployer config?

**Comment by gabygoole** [comment]
I delete the <Site updated: {{ now("YYYY-MM-DD HH:mm:ss") }}>,everything is
ok

**Comment by Xuanwo** [comment]
Closed for problem resloved.
