### ISSUE TITLE
Consider more jekyll-like permalink behavior with posts

### ISSUE THREAD

**Issue by mshick** [hexojs/hexo#1617]
The current system has a major flaw as I see it. By using the full filename as the token `:title` (which I would also say is a bad name for the variable) it makes it impossible to have sane urls, and to have two posts with the same title since the `_posts` directory is basically flat.

Jekyll deals with this pretty well by requiring a date in the filename, which is stripped out and used as a basic date in case none is provided in the frontmatter. The other nice fact is I can name multiple posts "my-puppy" because their filenames won't collide, ie, `2015-11-30-my-puppy.md`, `2015-12-01-my-puppy.md`. 

The basic [Jekyll slug-generation algorithm](http://jekyllrb.com/docs/permalinks/) is as follows:
1. ONLY handle files within `_posts` that follow the pattern `YYYY-MM-DD-my-puppy`.
2. Use the date from the filename if none is provided in the frontmatter for sorting, etc.
3. Use the non-date material as the default `:title` token for all permalink generation, `my-puppy` above.
4. Slugify the non-date material, present as the `:slug` token, leaves only numbers, letters, and hyphens.
5. Obey a frontmatter variable `slug` to override the default slug above.

**Comment by Xuanwo** [comment]
Well, it's a break change for all hexo user, we should have more careful thinking.
Anyone who has idea can share here.

**Comment by kvz** [comment]
I think I got this to work using these two configuration values:

```yml
permalink: blog/:year/:month/:title/ # note that I left out `/:day` here
new_post_name: :year-:month-:day-:title.md # File name of new posts
```

**Comment by kvz** [comment]
Actually, this duplicates the date in the permalink :/ sorry for celebrating too early

**Comment by stevenjoezhang** [comment]
How about using `:name` instead of `:title`?

**Comment by stevenjoezhang** [comment]
Use `:name` instead of `:title`

**Comment by SukkaW** [comment]
> Use `:name` instead of `:title`

@stevenjoezhang Hexo's document hasn't mentioned it yet, though I have already open an issue at `hexojs/site` for this.
