### ISSUE TITLE
关于i18n插件和deploy的问题

### ISSUE THREAD

**Issue by ay27** [hexojs/hexo#1618]
目前我打算使用i18n插件，为我的网站做国际化支持。在某主题的header.ejs文件中，我需要为不同的语言定义不同的tab button，如下图：
![image](https://cloud.githubusercontent.com/assets/3942031/11560822/30206610-99fe-11e5-9824-385e7cd89631.png)
针对每一个tab button，我的做法如下：

```
<a href="<%- url_for(__('urll.'+ i.toLowerCase())) %>"><%= __(i.toLowerCase()) %></a></li>
```

其中，**链接和显示的文字都是用函数__()在语言文件中寻找对应的字符串进行替换。**
目前这种做法在本地跑hexo server是完全符合我的需求，确实生成了对应语言版本的页面，而且tab button的链接也是正常的。
但是，**当我deploy到github page时，发现并没有对应语言的页面，所有页面的tab button都是默认语言，并没有生成对应语言的版本。**
我不清楚为什么本地预览的页面与部署的页面会不一样？！
非常期待问题的解决方案！

**Comment by Xuanwo** [comment]
我觉得问题可能出在这个函数上面，我对Hexo的i18n这个方面不是非常清楚，最实际的例子是[Hexo的官网](https://hexo.io/)，你可以看看它的实现： https://github.com/hexojs/site/tree/master/themes/navy

**Comment by ay27** [comment]
万分感谢！
我先试试看

**Comment by ay27** [comment]
@Xuanwo 问题尚未解决。
hexo官网是用swig做模板，我使用的是ejs模板，对比后发现没有太多可以参考的地方。而这个函数在我本地预览时确实工作正常，即使预览正常，查看public目录下生成的html文件，仍然生成错误。请问hexo server预览时对应文件目录是哪里呢？
最后实在没办法，用了一个很脏的办法，就是直接做了一个新的english版的layout模板，把手中的问题解决了。
目前唯一的猜测是`__()` 这个函数可能使用到了某些预定义的变量，这些变量在本地预览时和生成html时的值不一样，从而造成预览和发布的效果不一样。

**Comment by Xuanwo** [comment]
@ay27 Hexo对语言的支持是通过修改`page.lang`变量实现的，然后`page.lang`会使用language文件夹下的对应语言，我的理解大概是这样，你可以参考一下同样基于ejs的[freemind](https://github.com/wzpan/hexo-theme-freemind)

**Comment by Zekeair** [comment]
@ay27 我最近也遇到hexo国际化的问题。我即使是在`hexo server`下也不正常，所有用到`__()`函数的地方都替换成了`_config.yml`中设置语言列表的第一个值`zh-CN`对应的显示。不知道是不是我浏览器的设置问题，尝试过切换为英文界面。

而我的个人理解是，在`hexo generate`或者`hexo deploy`之后，hexo已经将所有的模板页面都渲染为了静态的html页面，包括html中的文字内容，github page只是一个静态的服务器，既然html中的内容已经是固定的，当然不会更具你浏览器的语言变换显示。hexo官网的做法是创建了对应的翻译目录，通过人为切换到对应的语言目录。

还有，你添加的english版的layout是通过自动切换还是手动选择调取的？可否说明一下。

**Comment by ay27** [comment]
@zekeair 你说**“既然html中的内容已经是固定的，当然不会更具你浏览器的语言变换显示”**，我也是这么理解的，然而现实结果是：hexo server与deploy是不一样的。我都感觉很奇怪，想不清楚为什么。

我目前添加了english版的layout是手动选择的，因为layout.ejs是模板生成的入口，为了做出不同的语言页面，我修改了layout.ejs的内容，使其仅有一行include body的代码，而原来的layout.ejs内容同时放入了layout_cn和layout_en中，分别对应不同的语言。同时，在编辑网页内容的md文件时，必须在front-matter中显式申明是使用了layout_cn还是layout_en模板。另外，在存放md文件的source目录下，按照这样的结构放置文件：

    .
    ├── cn
    │   └── index.md
    └── en
        └── index.md

**Comment by zekeair** [comment]
@ay27 了解你的做法了。这样做你网站的index页面只能静态的显示为一种语言，导航的语言显示只能根据文章的front-matter的设置才会变换。

我能理解hexo server和deploy不一样。hexo server作为服务器版本，其中资源的表现形式并不是静态的，应该是遵循了RESTful的规范的，所以它可以动态的显示语言，因为__()和_p()是在你通过URL访问资源的时候才转换为具体的显示文本。这也是为什么你找不到hexo server生成的静态文件的原因了。

但是我的问题是即使在hexo server形式下，依然只显示一种语言。一直不知道为什么。我的_config.yml中language设置如下：
```yaml
language:
- zh-CN
- en
```
但不管我如何切换浏览器的语言设置，我的页面永远只显示language下排在第一的语言。

**Comment by ay27** [comment]
@zekeair 我理解你的疑惑了。我最初只是把英文版面的md文件放入了source/en/目录，在请求该目录下的页面时，自动就替换成了对应的语言。。。

**Comment by Jamling** [comment]
@ay27 @zekeair 2 我曾也遇到过类似的问题，后来我自己写了个[hexo-generator-i18n](https://github.com/Jamling/hexo-generator-i18n)插件，成功地解决了这个问题。

**Comment by Yugnaynehc** [comment]
I have encountered this problem, and I guess this may be the cache matter. 

In my theme's 'layout,ejs' file, I find that hader is inserted by:
<%- partial('_partial/header', null, {cache: !config.relative_link}) %>
When I delete the paramter 'cache', everything goes well again. And I find something about this in the bottom of the official guidance: https://hexo.io/zh-cn/docs/templates.html

Wish this help to you.
