### ISSUE TITLE
access is_post() in the context before_post_render

### ISSUE THREAD

**Issue by sunblognuke** [hexojs/hexo#1620]
I would like to build a filter, which will insert  the copyright in the bottom of content. 

However, the current theme will expand content with copyright in the home page or post detail page. 

I don't would like to show copyright in the home page so I just want to check it is_post in my filter below. Or is there any way to make the same filter feature? Thanks a lot.

```
// Add a tail to every post from tail.md
// Great for adding copyright info

var fs = require('fs');

hexo.extend.filter.register('before_post_render', function(data){
    if(data.copyright == false) return data;
    // I want it like that : if(!is_post() || data.copyright == false) return data;

    var file_content = fs.readFileSync('copyright.md');
    if(file_content && data.content.length > 50) 
    {
        data.content += '\n' + file_content;
        var permalink = '\n本文永久链接：' + data.permalink;
        data.content += permalink;
    }
    return data;
});
```

**Comment by Xuanwo** [comment]
I hope this will be helpful: https://github.com/Xuanwo/xuanwo.github.io/commit/55899004321da831d01ca1111f5f7bf26fcfefd7#diff-d5e58be1cdc773389a489ecdede5e1d0R104

**Comment by sunblognuke** [comment]
it looks nice but done in the template way but not the data filter. I would like to do it in the event - before_post_render. Thanks again :)

**Comment by pzxbc** [comment]
I find another way for this. you can check the value of data.layout to make sure it's a post

**Comment by sunblognuke** [comment]
@pzxbc it doesn't work because all data.layout s are returned "post" here. thx again.

**Comment by leesei** [comment]
@sunblognuke  I don't think you need to filter out `index`, only post data will trigger post filter.
