### ISSUE TITLE
Let user override the slug in frontmatter

### ISSUE THREAD

**Issue by andyhall** [hexojs/hexo#1623]
It would be hugely useful if the user can define a `slug` in a post's yaml, and have it override the filename as the slug for that particular post.

Reason: In my case, I'm converting a wordpress site to hexo, where some of the slugs contain characters that can't be used in OSX filenames. So the only way I can work around this is to define the slugs inside a file, rather than as filenames. 

In the general case, I imagine this will also be useful to people who want to reuse the same slug for different posts on different dates, or for users who prefer to use a particular scheme for their filenames, etc.

Note: this change is also mentioned #1617, but I'd like to request it regardless of whether any other jekyll-style changes are made.

**Comment by leesei** [comment]
Since the slug is used for generating the url and url must be unique.
Allowing slug in frontmatter have the risk of url conflict.
There is no solution given the flat file structure of Hexo.

**Comment by andyhall** [comment]
@leesei Hexo already supports using frontmatter in URLs (with `:id`), and non-flat file structures (by using `:name` instead of `:title`).

As such, it's already easy to create url conflicts, and I don't think this suggestion makes it any easier.

**Comment by kvz** [comment]
As mentioned in #1617, unless I misinterpret this issue, I think I got this to work using these two configuration values:

```yml
permalink: blog/:year/:month/:title/ # note that I left out `/:day` here
new_post_name: :year-:month-:day-:title.md # File name of new posts
```

**Comment by kvz** [comment]
Actually, this duplicates the date in the permalink :/ sorry for celebrating too early

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo/issues/3464#event-3464510149
