### ISSUE TITLE
how to new a folder within more than one post

### ISSUE THREAD

**Issue by cighao** [hexojs/hexo#1626]
I want to new a folder and there will be more than one post in it. At the same time, I hope that these posts will not appear in the achieve and on my website there will a button linked to those posts in the new folder. What should I do? Thanks!

**Comment by Xuanwo** [comment]
just create a diectory in `source` with md files, and you can access them by `yousite.com/test/a.html`

**Comment by cighao** [comment]
If there are more than one md files in it, how can I make a catalog for them .

**Comment by Xuanwo** [comment]
What do you mean about `catalog` ? The same as `categories`?

**Comment by Xuanwo** [comment]
In this verison, we do this like:  https://github.com/hexojs/site/blob/master/source/_data/sidebar.yml

**Comment by flashlab** [comment]
@Xuanwo Could you explain more specifically about your solution? Thanks;) Currently, I have to modify `source_dir` and `public_dir`, execute generation again followed by merging two publish folder manually.

**Comment by Xuanwo** [comment]
@flashlab 
Every md files in `source_dir` will be generated, for example, there are two files in `source/abc` like:

```
source/abc/a.md
source/abc/b.md
```

after generate, you can read there articles with

```
example.com/abc/a.html
example.com/abc/b.html
```

so that, you can new a folder within more than one post.
**And these file will not be included in tags and categories.**

**Comment by flashlab** [comment]
@Xuanwo GOTCHA! So here comes the problem, there'll be no **home page** for subfolder articles which can't be accessed by hyperlinks or prev/next button. OR. maybe it's not a bad news:joy:

**Comment by Xuanwo** [comment]
And you can add a homepage for them in layout, but it's too difficult.
So I push it to roadmap, and maybe it will be added as a new feature~
