### ISSUE TITLE
npm命令不对劲呀...

### ISSUE THREAD

**Issue by imhentai** [hexojs/hexo#1628]
![qq 20151207221914](https://cloud.githubusercontent.com/assets/8164505/11629046/a8cdba2e-9d30-11e5-84a3-9ac66876c473.png)
![qq 20151207221929](https://cloud.githubusercontent.com/assets/8164505/11629047/a8fc96d2-9d30-11e5-9198-6965c598f130.png)

就这样一直刷....最后安装失败

**Comment by Xuanwo** [comment]
看不懂- -，是不是网络问题，开个代理或者使用淘宝源试试看呢

**Comment by imhentai** [comment]
今天虽然还是这样一直刷些莫名其妙的东西...但是最后安装成功了
所有的npm命令都是如此，git和hexo正常，不管它了==反正平时也用不上，就安装的时候需要
