### ISSUE TITLE
Add `---` before front matter

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1629]
Github can render front matter bounded by `---` _pair_ in a table:
https://github.com/philipwalton/solved-by-flexbox/blob/master/demos/grids.md

We can add `---` prefix in `scaffolds/*` <strike>and make sure hexo-front-matter can support it</strike>.

[hexojs/hexo-front-matter](https://github.com/hexojs/hexo-front-matter) already support it.

**Comment by Xuanwo** [comment]
Looks good to me, we can read out post both in github and our site, instead of like this:

![image](https://cloud.githubusercontent.com/assets/5351546/11646077/32b90496-9d95-11e5-93ca-98e42ced5a99.png)

> I will take sometime to transfer all my post into this way

**Comment by leesei** [comment]
See https://github.com/hexojs/hexo-starter/pull/1.

For existing repo, use (in your site folder):
```sh
sed -i '1 i ---' scaffolds/* source/_posts/*
```
*Commit before using this command so you can rollback if anything goes wrong,*

**Comment by Xuanwo** [comment]
I use regex to do this, and works fine~

**Comment by Xuanwo** [comment]
Done.

**Comment by leesei** [comment]
I would like to add `---` to files in https://github.com/hexojs/site/

**Comment by curbengh** [comment]
@leesei which page? https://hexo.io/docs/front-matter already shows `---` pair.

**Comment by leesei** [comment]
I suppose someone have implemented the suggestion then.

**Comment by YoshinoriN** [comment]
@curbengh @leesei 
I did it https://github.com/hexojs/site/pull/931
This issue closable :)
