### ISSUE TITLE
Better report malformed config

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1631]
YAML is quite strict in its format and Hexo does not report YAML parsing error properly.
We should catch parsing error early, log and abort the operation.

https://github.com/hexojs/hexo-deployer-git/issues/15
https://github.com/hexojs/hexo/issues/1263
https://github.com/hexojs/hexo/issues/11

**Comment by Xuanwo** [comment]
The same idea.

**Comment by leesei** [comment]
Related #1632

**Comment by leesei** [comment]
Track in #1771
