### ISSUE TITLE
Dump config with `--dump-config`

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1632]
Dump hexo.config and theme.config.
Allows use to check how Hexo interprets their config.

**Comment by leesei** [comment]
Note:
Take a look at overriding theme config while we're at it.
https://github.com/hexojs/hexo/issues/1330#issuecomment-121588238

**Comment by Xuanwo** [comment]
> I remember there is a commit that change the way into merge: https://github.com/hexojs/hexo/commit/61941e79a8fc94b1e9bd0698d1b635e7c34d7ca4

And I used to see there is a way to add info brfore someone want to Open a new issue, but I don't know how to setup it, do you have any idea?

**Comment by Xuanwo** [comment]
Well ,I got it, we can modify this file: https://github.com/hexojs/hexo/blob/master/CONTRIBUTING.md

But I'm afraid it meaningless for new user of github.

**Comment by leesei** [comment]
Ha, even I didn't read the CONTRIBUTING document myself.

The error prompt I mentioned is this one:
https://github.com/hexojs/hexo/blob/master/lib/hexo/index.js#L417-L423
Users do often see this prompt and check the troubleshooting page.

**Comment by leesei** [comment]
`hexo config` landed since 3.0
https://github.com/hexojs/hexo/commit/d5de106231d2a2bfb713b6f6136031500daa05dc

But theme config was not handled.

**Comment by stevenjoezhang** [comment]
> But theme config was not handled

`theme_config` made it possible
```
hexo config theme_config.scheme Muse
```
