### ISSUE TITLE
What is skip_render supposed to do?

### ISSUE THREAD

**Issue by andyhall** [hexojs/hexo#1633]
When I set `skip_render` to a glob that matches files in my source, they still get copied into the output and served by the server.

Moreover, I can specify config like:
```
skip_render:
 - '*.html'
 - '*.md'
 - '*'
 - '**/*'
```
and it has no apparent effect at all. `hexo generate` and `hexo server` both behave exactly like normal.

Does this configuration do anything? What is the intended use?

**Comment by Xuanwo** [comment]
skip_render just copy them instead of render them, so you can put html in source

**Comment by andyhall** [comment]
Ahhh, got it, thanks.
