### ISSUE TITLE
Mac npm and hexo not found

### ISSUE THREAD

**Issue by xiejiachen** [hexojs/hexo#1634]
Actually, I have runned it on my mac. And have done sync with github. And also it can be viewed online by my macbook.

However, if I just have a break, such as 10 minutes. While I prepare to back to my job. 
Open terminal and input
hexo or npm

It response 
-bash: hexo: command not found
-bash: npm: command not found

And hence, I must re-install step by step, it is really annoying me you know.

Is there any others faced same situation with me?

**Comment by Xuanwo** [comment]
Maybe you can use homebrew to install nodejs

**Comment by xiejiachen** [comment]
I tried it.
And just now I tried it again.
And I found only if i quit terminal, and open it again
hexo: command not found

**Comment by xiejiachen** [comment]
brew install node
npm install -g hexo-cli
nas10-240-87-228:~ Timone$ hexo
Usage: hexo <command>

 it seems worked.
However, after I quit terminal and open it again.
command not found

**Comment by xiejiachen** [comment]
重新试了一下，用brew安装解决了

**Comment by haxwn** [comment]
重新brew安装还不行..
