### ISSUE TITLE
The date of article

### ISSUE THREAD

**Issue by tigerRose** [hexojs/hexo#1635]
Hello, when I run 'hexo g' and 'hexo d', I found that the date of my article is wrong in my github pages, 

It is  2015-6-14 in xxx.md, and the date of last edited with this file if 2015-11-29, but in github pages, the date is 2015-12-8,   please tell me how to fix this, thanks.

**Comment by Xuanwo** [comment]
set the correct time in `timezone:`,  which you can find help here: https://hexo.io/docs/configuration.html

**Comment by tigerRose** [comment]
I set the timezone in _config.yml: timezone: Asia/Chongqing  and generate again, but it doesn't work for me.

**Comment by Xuanwo** [comment]
paste one of your md here

**Comment by tigerRose** [comment]
It is the begin of my md.
 1 title: "python-ConfigParser"
  2 data: 2015-06-14
  3 categories: python # 分类
  4 tags: [python,ConfigParser]
  5 ---

My githup's dir is https://github.com/tigerRose/tigerRose.github.io. Thanks.

**Comment by Xuanwo** [comment]
`date: 2015-06-14` instead of `data: 2015-06-14`

**Comment by tigerRose** [comment]
That's the problem. Thanks a lot
