### ISSUE TITLE
Can this support markdown syntax in markdown?

### ISSUE THREAD

**Issue by sphenginx** [hexojs/hexo#1636]
I hope it can appear this:

![markdown](https://cloud.githubusercontent.com/assets/1829395/11676268/d51413c6-9e6b-11e5-84b5-fcbfe3658708.png)

My computer markdown editor haroopad support that syntax , but when I generate blog with `hexo generate`, it does not appear, Can u fix that?

Forgive my poor english……

**Comment by Xuanwo** [comment]
Just use them in this way：

    ```
    your code here
    ```

**Comment by sphenginx** [comment]
ha. I had tried with that, it seems like does not work on github pages（the latest hexo generate）:sob:……

**Comment by Xuanwo** [comment]
```cat
    cat -v test.txt >te.txt
    ```

Remove the `cat` and try again? I use this way to include my code without error.

**Comment by Xuanwo** [comment]
Well, I read your problem again, I find I mistake something.
Do you mean you want to show markdown contnet in pages?
---
You can do this in this way

    {% raw %}
    ```
    this is the code
    ```
    {% endraw %}

**Comment by sphenginx** [comment]
Well, how to use that? like this:

![raw.png](http://sphenginx.github.io/images/bug/raw.png)


but, when hexo generate that,  it likes:
![html.png](http://sphenginx.github.io/images/bug/html.png)

The code disapper. :sos:

**Comment by Xuanwo** [comment]
do them in this way : https://github.com/hexojs/site/blame/master/source/docs/tag-plugins.md#L135-L139

**Comment by sphenginx** [comment]
Thanks. It works on  [My blog website](http://sphenginx.github.io/2015/12/07/markdown/) , but does not work on [github markdown](https://github.com/sphenginx/hexo/blob/master/source/_posts/markdown.md) :+1:
