### ISSUE TITLE
How can I archive posts by day?

### ISSUE THREAD

**Issue by regrex** [hexojs/hexo#1639]
I want to use hexo to build a weekly of my group. We will publish many posts in a day. Hexo archive posts by month or year. How can I archive posts by day?

**Comment by Xuanwo** [comment]
archive pages are just html, you can modify your theme to create them, and use `{% set post.year = date(post.date, 'YYYY') %}` to get the different data.

**Comment by Xuanwo** [comment]
fixed by https://github.com/hexojs/hexo-generator-archive/pull/2 , you can install the latest version and set `daily` to `true`.
