### ISSUE TITLE
index.html is deleted when all posts are deleted? 

### ISSUE THREAD

**Issue by webcultist** [hexojs/hexo#1641]
Hat a strange behavior. I use Hexo without "posts". I have a folder with "pages" where the static pages are lying. I had a _posts folder with example posts from an example project. 
After cleaning up my installation and deleting all the posts, just keeping the pages (e.g. products.md etc.), my root index.html got lost. It's has been deleted by hexo. After creating any .md file in the _posts folder, the index.html has been recreated again. 
I fixed my missing index.html now with a index.md and an index permalink, but what's wrong in my understanding? Why are post files are necessary for creating the default index.html? 

Greetings and thanks!

**Comment by Xuanwo** [comment]
just add an `index.md` in source.
