### ISSUE TITLE
首页文章列表不显示文章

### ISSUE THREAD

**Issue by yeziahehe** [hexojs/hexo#1644]
通过Travis CI进行自动化构建之后，pull到本地后，没有配置hexo的环境，直接在source/_post文件下新建了xx.md，push之后，首页列表中没有文章，但是归档和分类中都有，求解？
[homepage](http://blog.coryphaei.com/)

[归档](http://blog.coryphaei.com/archives/)

[分类](http://blog.coryphaei.com/categories/)

**Comment by Xuanwo** [comment]
What's this? https://github.com/Coryphaei/coryphaei.github.io/blob/blog/_config.yml#L15

**Comment by yeziahehe** [comment]
目测和这个没关系的。我已修改了，还是不可以的。

**Comment by yeziahehe** [comment]
我试过用`$ hexo new `，push这样是没问题的。

**Comment by Xuanwo** [comment]
并不会， `hexo new`和直接新建md文件本质上是一样的。

**Comment by yeziahehe** [comment]
是的，我现在又操作了一次，文章出来了，不知道原因。

**Comment by yeziahehe** [comment]
我修改了下date，文章就出来了。之前是11:00:00。

**Comment by yeziahehe** [comment]
我现在知道问题所在了，首页只能显示一篇文章，这个是什么引起的？
