### ISSUE TITLE
main page only show lastest article

### ISSUE THREAD

**Issue by yeziahehe** [hexojs/hexo#1646]
I use Travis CI to auto build blog, but when I push to branch blog, main page only show one lastest article and not show page number, but tags show all, I don't know why?
[This is my blog](http://blog.coryphaei.com)

**Comment by yeziahehe** [comment]
https://github.com/iissnan/hexo-theme-next/issues/482
https://github.com/iissnan/hexo-theme-next/issues/535
https://github.com/iissnan/hexo-theme-next/issues/490
目测是next主题的问题

**Comment by yeziahehe** [comment]
找到问题所在是next主题的问题。
目前的解决方案是
```
hexo clean
hexo g
hexo g
hexo d
```
渲染两遍首页就能正常显示了。

**Comment by LeoiOS** [comment]
Thank you very much!

**Comment by aimer1124** [comment]
I have the same issue ,and use twice generate,then the issue disappear..
