### ISSUE TITLE
关于Wordpress迁移时，生成文件名的中文名字问题。

### ISSUE THREAD

**Issue by dengshilong** [hexojs/hexo#1650]
从Wordpress迁移过来时，生成的文件名会出现如下例子
e8-af-ad-e8-a8-80-e7-89-b9-e6-80-a7-e8-bf-98-e6-98-af-e6-9c-89-e5-bf-85-e8-a6-81-e5-ad-a6-e4-b9-a0-e7-9a-84.md
e8-bd-af-e8-bf-9e-e6-8e-a5-e5-92-8c-e7-a1-ac-e8-bf-9e-e6-8e-a5.md
e8-bf-bd-e8-b8-aaquery-too-complex-not-enough-stack-e9-94-99-e8-af-af.md
我想这是将URL转化过来的结果，因为URL中，中文是UTF-8编码。这里之所以有问题是因为这样的文件名生成的URL和以前在Wordpress中不一样，这样之前在搜索引擎索引的文章就不能访问了，因为URL变了。
目前我的解决办法是写了一个Python脚本，然后从文件内容的title部分提取出文件名，代码如下：
```
import os,sys

def getTitle(firstLine):
    strs = ':'.join(firstLine.split(':')[1:])
    strs = strs.replace("'", '') 
    strs = strs.strip()
    title = '-'.join(strs.split(' '))
    return title
if __name__ == "__main__":
    dirName = sys.argv[1]
    for root,dirs,fileNames in os.walk(dirName):
        for fileName in fileNames:
            print fileName 
            print root
            fileName = os.path.join(root, fileName)
            f = open(fileName)
            firstLine = f.readline()
            title = getTitle(firstLine)
            print title
            content = firstLine + f.read()
            f.close()
            newname = title + '.md'
            print newname
            os.rename(fileName, os.path.join(root,newname))
```
是否有其它解决办法？

**Comment by Xuanwo** [comment]
Moved to https://github.com/hexojs/hexo-migrator-wordpress/issues/12

**Comment by Xuanwo** [comment]
@dengshilong 可以参考 https://github.com/hexojs/hexo-migrator-wordpress/issues/12#issuecomment-216968661
