### ISSUE TITLE
Template render error: unexpected token: /

### ISSUE THREAD

**Issue by dengshilong** [hexojs/hexo#1651]
This is cause by the '{{' problem. I solve it by change the hexo-migrator-wordpress plugin,
add a function to replace '{{' to '{ {'
```
function replaceTwoBrace(str){
    str = str.replace(/{{/g, '{ {');
    return str;
};
```
add `content = replaceTwoBrace(content);` before `content = tomd(content).replace(/\r\n/g, '\n');`
I with this can save other guy's time.

**Comment by Xuanwo** [comment]
Closed for merged.
