### ISSUE TITLE
Help user to troubleshoot

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1653]
The current [error prompt](https://github.com/hexojs/hexo/blob/master/lib/hexo/index.js#L417-L423) just points user to [troubleshooting](http://hexo.io/docs/troubleshooting.html) page.

We could come up with a flow to better help the user troubleshoot:
- let them verify config with `hexo --dump-config` #1632
- educate user to use `hexo <command> --debug` when reporting issue
- Better error message #1771
- send error log to http://termbin.com/ or other service? (require user consent)
- ...

**Comment by Xuanwo** [comment]
I'm second.
