### ISSUE TITLE
0.0.0.0 is not addressable, use 127.0.0.0 by default

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1657]
The change is in hexojs/hexo-server, but this breaks the feature of allowing other machines to visit the site via hexo-server (which I think is good).
We have to change all the documents in hexojs/site to reflect this change.
Also add workaround (specifying the ip) to maintain current behavior.

See https://github.com/hexojs/hexo-server/pull/14 and https://github.com/jekyll/jekyll/issues/3048 for the discussion.

**Comment by Xuanwo** [comment]
I find it better to merge https://github.com/hexojs/hexo-server/pull/14 into master. 

- As use `hexo server` bring more trouble likes https://github.com/hexojs/hexo/issues/1149 but less benefits. 
- Making `hexo server` a clearer position which differs from `nginx` or `apache` is better for the development of hexo-server.

And we should update docs of `hexo-server` to educate people not to use `hexo-server` for production.

**Comment by leesei** [comment]
I totally agree that hexojs/hexo-server#14 will be in, but not without or before the corresponding docs update.

**Comment by Xuanwo** [comment]
Firstly, let's have a discussion in the society. 
If dicided to do so, we can begin to do the work of docs, and I can do to zh-cn part.

**Comment by leesei** [comment]
https://github.com/hexojs/hexo-server/commit/4103a759e406ed4d9cda123ae6afe8a77f8f9432 changed the display of `hexo-server`
We will stick with `0.0.0.0` as default.
