### ISSUE TITLE
prefer better error for missing theme

### ISSUE THREAD

**Issue by tomByrer** [hexojs/hexo#1658]
Steps to reproduce:
1. delete `/themes/landscape`, and add another theme
2. forget to edit or save `_config.yml`  :fearful:
3. `> hexo generate`
```bash
E:\client\Tim\hexo\minos> hexo generate
INFO  Files loaded in 345 ms
WARN  No layout: 2015/11/11/easter-island/index.html
WARN  No layout: 2015/11/11/easter-island/index.html
INFO  Generated: 2015/11/11/easter-island/index.html
...
```
4. site won't run

"ERROR Can't find theme in `_config.yml`" would be a better report IMHO.

**Comment by Xuanwo** [comment]
I second, ref: https://github.com/hexojs/hexo/issues/1640#issuecomment-163679821

**Comment by leesei** [comment]
Tracked in #1771
