### ISSUE TITLE
I get a bad title-link when I config root option in _config.yml file

### ISSUE THREAD

**Issue by wwssllabcd** [hexojs/hexo#1659]
when i set 

```
root: /blog/
```

in _config.yml file , i get a wrong title-link
so I check source code, then I found

```
<h1 id="logo-wrap">
        <a href="/" id="logo">My Blog Title </a>
</h1>
```

It should be "<a href="/blog" when I set root: /blog/ optiopn
so, I modify "header.ejs" line:6
from 

```
 <a href="<%- url_for() %>" id="logo"><%= config.title %></a>
```

to 

```
 <a href="<%- url_for() %>blog" id="logo"><%= config.title %></a>
```

It is good for me 
did I do wrong when config _config.yml?

**Comment by Xuanwo** [comment]
If your website is in a subdirectory (such as http://example.org/blog) set url to `http://example.org/blog` and set root to `/blog/`.
