### ISSUE TITLE
分类URL设置：http://xx.io/categories/node  -->  http://xx.io/node

### ISSUE THREAD

**Issue by denglj** [hexojs/hexo#1665]
**不需要 generator-alias 那种效果**，需要实际访问地址就直接是子分类的目录。
应该需要在public目录下生成 node文件夹，并生成index.html才可以，如何做到呢？
谢谢！

**Comment by Xuanwo** [comment]
```
category_dir: /
```

**Comment by Xuanwo** [comment]
CLosed for sloved, please create new issue if had other problem.
