### ISSUE TITLE
目前有什么好的标签整理方法么？

### ISSUE THREAD

**Issue by netcan** [hexojs/hexo#1669]
文章多了，想批量整理文章分类/标签。

**Comment by Xuanwo** [comment]
貌似没有，这个应该是看平时自己的习惯吧- -

或许Hexo可以提供一个插件用来对文章执行批量操作

**Comment by amobiz** [comment]
用文書處理工具搜尋、置換？

**Comment by Xuanwo** [comment]
@amobiz  是的，使用Sublime之类编辑器的批量处理

**Comment by amobiz** [comment]
@Xuanwo 抱歉沒有指名對象並說明清楚。我其實是在回答 @netcan，詢問他是否能接受使用文書處理工具進行搜尋、置換的方式，來整理分類、標籤。不過您的回答更清楚，相信能讓 @netcan 更明白。

**Comment by netcan** [comment]
恩，可以是可以。。

**Comment by amobiz** [comment]
不過有專用的工具確實比較方便， @netcan 有沒有什麼想法？工具應該提供什麼樣的功能、界面等。說出來看看，說不定有人願意幫忙寫工具。

**Comment by Xuanwo** [comment]
我觉得这个功能还是值得考虑的，可以作为一个插件提供。

**This issues is about to develop a plugin which can control all the tags and categories in a simple way.**

**Comment by netcan** [comment]
@amobiz 我的想法是，默认列出文章列表，附带标签/分类方便更改，也可以按照标签/分类列出该标签下文章列表，方便添加、移除文章。。有考虑要做（Qt），最近要考试就停了。。可能要拖一段时间了。。

**Comment by amobiz** [comment]
嗯，可以考慮從這裡下手：
https://github.com/jaredly/hexo-admin

**Comment by netcan** [comment]
恩，hexo-admin可视化工具也可以，像以前wordpress就有方便的管理标签/分类插件。。

**Comment by amobiz** [comment]
譬如這個：
Admin Management Xtended
https://wordpress.org/plugins/admin-management-xtended/

**Comment by yansheng836** [comment]
About category maybe this plugin with help you :<https://github.com/xu-song/hexo-auto-category>.
