### ISSUE TITLE
文章在插入table标签时，会在表格上方生成表格行数+1行的<br>

### ISSUE THREAD

**Issue by wenqiangtxc** [hexojs/hexo#1673]
![1](http://7xpiue.com1.z0.glb.clouddn.com/hexo1.png)

![2](http://7xpiue.com1.z0.glb.clouddn.com/hexo2.png)

只有我是这样吗？

**Comment by Xuanwo** [comment]
这是已知BUG，ref: https://github.com/hexojs/hexo/issues/1388

**Comment by YopheeHsin** [comment]
用了 {% raw %} {% endraw %} 包html table
