### ISSUE TITLE
If I want to use 2 different url for my blog, how to write the config?

### ISSUE THREAD

**Issue by masquevil** [hexojs/hexo#1676]
If I want to use both "blog.domin.com" and "www.domin.com/blog/" as my blog url, how can I write the config ":root" ?

**Comment by Xuanwo** [comment]
Deploy them to different repo.

**Comment by Xuanwo** [comment]
And I don't support this.
The search engine will think the two sites are copying from each other which will lead to lower page rank. If you want visitor use two url, you can set a redirecting.
