### ISSUE TITLE
atom.xml文件报错，utf8

### ISSUE THREAD

**Issue by hkongm** [hexojs/hexo#1678]
This page contains the following errors:

error on line 645 at column 35: Input is not proper UTF-8, indicate encoding !
Bytes: 0x10 0x56 0x69 0x65
Below is a rendering of the page up to the first error.

找到相应行列是个`<p>`，很怪异

浏览器和客户端无法正常订阅

**Comment by Xuanwo** [comment]
把链接或者页面内容贴出来。

**Comment by hkongm** [comment]
http://caichao.me/atom.xml
here

**Comment by Xuanwo** [comment]
你用1.0.2之类的老版本生成试试看呢，顺带提一下，你这个主题链接有问题啊- -，在非主页的情况下链接都是404

**Comment by hkongm** [comment]
惊了，本地起server是好的啊。。。我看看。。。

**Comment by hkongm** [comment]
@Xuanwo 帮忙看下 http://caichao.me/atom.xml
```
This page contains the following errors:

error on line 574 at column 35: Input is not proper UTF-8, indicate encoding !
Bytes: 0x10 0x56 0x69 0x65
Below is a rendering of the page up to the first error.
```

**Comment by Xuanwo** [comment]
@hkongm 我也不懂啊- -，还这没遇到过这种情况，你可以在本地测试一下

1. 重新创建一个新的库，使用默认主题，看看xml是否正常，不正常说明插件有问题，重装或更新一下
1. 重新创建一个新的库，使用自己写的主题，看看xml是否正常，不正常说明主题有问题- -
1. 重新创建一个新的库，自己的主题，自己的内容，看看xml是否正常，不正常说明文章内容有问题- -

**Comment by hkongm** [comment]
好吧。。。谢谢了

**Comment by Xuanwo** [comment]
所以结果是啥？。。

**Comment by hkongm** [comment]
结果是，没试出来。。。

**Comment by 2shou** [comment]
我也遇到这个问题了，有官方的fix么？ @Xuanwo
