### ISSUE TITLE
如何让列表按照published排序而不是updated？

### ISSUE THREAD

**Issue by hkongm** [hexojs/hexo#1679]
如何让列表按照published排序而不是updated？

**Comment by Xuanwo** [comment]
恩？目前文章是按照在yml信息中指定的date进行排列的，如果没有date信息就是按照updated排列。

**Comment by hkongm** [comment]
已经指定了date啊
对了，我用了自己写的主题，跟这个有关系么？在换主题前是好的。
我仔细对比了默认主题和自己主题的config，没看到这个选项。

**Comment by Xuanwo** [comment]
不懂你的主题怎么写的，爱莫能助

**Comment by leesei** [comment]
主題可以先sort post再顯示
