### ISSUE TITLE
Post model should provide a way to modify _content

### ISSUE THREAD

**Issue by TylerYang** [hexojs/hexo#1682]
Hi guys, I am trying to create a hexo md editor, and looking for a way to update post. Seems in `hexo/lib/models/post.js`, I cannot find a way to update the content. 

Am I missing something or that means I have to use `fs` module to manipulate the md file by myself? 

How about add an `update` enhancement?

**Comment by leesei** [comment]
You can refer to how https://github.com/jaredly/hexo-admin and https://github.com/jaredly/hexo-admin do it for now.

**Comment by stevenjoezhang** [comment]
And this one: https://github.com/zhuzhuyule/HexoEditor

**Comment by SukkaW** [comment]
If you are looking for a way to modify `_content`, `after_post_render` filter is what you should look at.
