### ISSUE TITLE
markdown 渲染 ``` 时容易出错

### ISSUE THREAD

**Issue by czzshr** [hexojs/hexo#1684]
最近写博客时遇到的一个问题：

当我在博客中写下如下内容时，
\`\`\`
test
\`\`\` 
test2

我希望的效果是这样的，
```
test
```
test

然而实际效果却是结构错乱，你可以在hexo中试着渲染一下试试。

最后我花了很长很长很长很长时间终于发现问题了：
原来我在第二个 \`\`\` 后面多加了一个空格。。当时我的内心是崩溃的。

相信有不少人可能遇到和我同样的问题，建议修复一下~

**Comment by Xuanwo** [comment]
修复啥- -，静态渲染不能自作聪明。

**Comment by czzshr** [comment]
这倒不是自作聪明，用户可能误操作的。。

比如说，我在写博文时，用Mou来做markdown格式对照，即使加了空格，渲染出来格式也是完全正常的。但是用hexo渲染过后发现格式完全错乱，这时可能就会话很长时间才能找出问题所在。。

**Comment by jackycute** [comment]
我記得 hexo 是用 marked 渲染的
要不要看一下是不是 marked 的問題

**Comment by Xuanwo** [comment]
Hexo的渲染引擎并不是自己实现的- -，去对应的引擎那边的库交issue吧
