### ISSUE TITLE
How to change Default Front-matter when using `hexo n`

### ISSUE THREAD

**Issue by youngzhu** [hexojs/hexo#1685]
When using `hexo n` to new a blog, its default Front-matter like this :
```
title: xx
date: 2016-01-02 11:38:22
tags:
```

I want to add an element ,for example `categories`,like this :
```
title: xx
date: 2016-01-02 11:38:22
categories:
tags:
```

What can I do?
Any suggestion?
Thanks.

**Comment by Xuanwo** [comment]
modify the file in `scaffolds`

**Comment by youngzhu** [comment]
It works. Thanks.
