### ISSUE TITLE
how to set the git to auto fill the username, I already try the method on the web

### ISSUE THREAD

**Issue by woshichuanqilz** [hexojs/hexo#1686]
I exe `git remote -v` in the root of the project and the .deploy_git folder, all the **origin** is set as the `ssh`
URL but every time I run hexo d -g, I also need to type in username and password, why's that?

**Comment by woshichuanqilz** [comment]
I get this msg when I exe `hexo d`, 
```
Username for 'https://github.com': woshichuanqilz
Password for 'https://woshichuanqilz@github.com':
```

**Comment by Xuanwo** [comment]
set your ssh key.
