### ISSUE TITLE
Support for nofollow links

### ISSUE THREAD

**Issue by mzachh** [hexojs/hexo#1687]
Hi,

is there a way to use no follow links, like 

```
<a href="http://..." rel="nofollow">linktext</a>
```

I could not find it in the docs.

thanks

**Comment by Xuanwo** [comment]
insert them will html code.

**Comment by liuzc** [comment]
Hi,please try this plugin: https://github.com/liuzc/hexo-autonofollow

**Comment by mzachh** [comment]
@Xuanwo, according my tests, "nofollow" will be removed, even if I declare it in the html code.

@liuzc, thanks for the great plugin, I am testing it and it looks good so far.

**Comment by leesei** [comment]
@liuzc thx for the plugin, care to add it to the [plugin index](https://hexo.io/docs/plugins.html#Publishing)?
