### ISSUE TITLE
The proper way to upgrade the hexo

### ISSUE THREAD

**Issue by lazywei** [hexojs/hexo#1689]
Hi,

I'm wondering what is the proper way to upgrade the hexo?
For example, I would need to upgrade the `hexo-cli` first through `npm install -g hexo-cli@latest`.
Then what about the existed site? Do I have to upgrade each of the components (e.g. `hexo-server`) manually?

Thanks.

**Comment by Xuanwo** [comment]
just run `npm install`, the `package.json` in the latest `hexo-cli` will update by the society and you don't need to worry about this.

**Comment by Xuanwo** [comment]
And for the components you use, your can modify the `package.json` in this way `"xxx": "~0.2.0"` and only change them when breaking change happen.

**Comment by Xuanwo** [comment]
Closed for no more update.
