### ISSUE TITLE
建议添加获取 contextPath 的表达式

### ISSUE THREAD

**Issue by czzshr** [hexojs/hexo#1691]
建议添加获取 contextPath 的表达式，比如在JSP中获取contextPath是 `${pageContext.request.contextPath}`

有了这个表达式我们就可以实现如下的功能：
1. 通过 `![](${pageContext.request.contextPath}/img/xxx.jpg)` 来引用图片，这样在我把图片部署到github上之前，我就可以通过 `hexo s`在本地预览  img文件夹下被引用的图片。
2. 更换域名之后，不需要重新更改那些引用了 img文件下的图片的博文了。

我之前google上搜索过了，但是没有发现hexo 有类似的表达式，所以建议hexo 添加这个表达式~
还是说hexo 早已经有这种表达式了只是我没发现？请不吝赐教。

**Comment by Xuanwo** [comment]
`![](/img/xxx.jpg)`本身就可以引用img文件夹下的图片啊
