### ISSUE TITLE
hexo能在markdown中插入一段html代码不被渲染么？(´･_･`)

### ISSUE THREAD

**Issue by netcan** [hexojs/hexo#1692]
hexo能在markdown中插入一段html代码不被渲染么？(´･_･`)

**Comment by Xuanwo** [comment]
{% raw %}
your html
{% endraw %}

**Comment by netcan** [comment]
一直这么干的，不行还是会在raw里插入内容。。图等下上传

**Comment by netcan** [comment]
不好意思，插入内容是js的锅。。源代码没事。。
