### ISSUE TITLE
Redundant category exists after changing the capitalization

### ISSUE THREAD

**Issue by eaglesky** [hexojs/hexo#1693]
How to reproduce the problem:

1. hexo new post blablabla

2. Make the category of the post "Blog building".

3. hexo clean; hexo generate; hexo server

4. Change "Blog building" to "Blog Building".

5. In the "all categories" page you will notice that both "Blog Building" and "Blog building" exist. And the latter one is empty.

6. Try to remove the redundant one by doing: hexo clean; hexo generate; hexo server again. 

7. "Blog building" is still there! 

The strange thing is that though "Blog building" will not exist in the db.json after doing "hexo clean" and "hexo generate",  when you run "hexo server" it will reappear in db.json. I cleaned the cache of my browser but it didn't help. I have to remove "Blog building" from my post and run "hexo clean" and "hexo generate" to remove the two categories. Any idea what might cause this problem?

Thanks!

**Comment by Xuanwo** [comment]
it looks like the cache of server

**Comment by eaglesky** [comment]
@Xuanwo Do you know how to clean it?

**Comment by Xuanwo** [comment]
maybe restart your compute. I never user hexo-server, so I have not idea,
sorry.

Yalun Qin <notifications@github.com>于2016年1月4日周一 上午2:50写道：

**Comment by leesei** [comment]
`rm db.json` at your Hexo site directory.
Note: this file is only used for `hexo server`, the generated (and hence deployed) site won't be affected.

`hexo clean` should have deleted it but there is a bug.
