### ISSUE TITLE
Helpers should output snippets in HTML5

### ISSUE THREAD

**Issue by Imyssed** [hexojs/hexo#1695]
Some helpers are still using the old HTML standards,not in HTML5.
For instance:
```html
<%- css('style.css') %>
<!--Output-->
<link rel="stylesheet" href="/style.css" type="text/css">

<%- js('script.js') %>
<!--Output-->
<script type="text/javascript" src="/script.js"></script>
```
Specifying `type` attributes in these tags isn't necessary as HTML5 implies `text/css` and `text/javascript` as defaults. This can be safely done even for older browsers.

**Comment by Xuanwo** [comment]
Closed for pr merged.
