### ISSUE TITLE
Fatal nunjucks error on files containing {{ , regardless of skip_render

### ISSUE THREAD

**Issue by andyhall** [hexojs/hexo#1698]
To reproduce:

```sh
hexo init blog
cd blog
npm install
echo '{{' >> source/tmp.md
nano _config.yml  # add tmp.md to "skip_render"
hexo generate
```

Result: hexo dies with `Template render error` even though the file shouldn't be rendered.

**Comment by Xuanwo** [comment]
Yes, `{{` will make nunjucks try to deal it with a `{{ % %}}` string.
And the way for now is add a space or use `{{ % raw %}}` and `{{ % endraw %}}` .

**Comment by andyhall** [comment]
Thanks. But to confirm, it shouldn't be trying to render the file at all, right?

**Comment by Xuanwo** [comment]
Yes, it will throw out an error.

**Comment by leesei** [comment]
I successfully used `skip_render` on `1698.md`.

See 
https://github.com/leesei/hexo-vanilla-site/blob/master/source/1698.md
and 
http://leesei.github.io/hexo-vanilla-site/1698.md

**Comment by leesei** [comment]
Note I'm using 3.2beta. So wait for the next release

**Comment by andyhall** [comment]
Sounds good. It reproduces for me in 3.1, but I'll revisit once I upgrade.

**Comment by leesei** [comment]
3.2 released
