### ISSUE TITLE
Will executate `hexo d -g` effect another terminal's editing? 

### ISSUE THREAD

**Issue by woshichuanqilz** [hexojs/hexo#1699]
for example I open two terminal to at the same hexo directory.
One for editing and another for exec `hexo d -g` timely, will this effect the editing in another terminal?

**Comment by Xuanwo** [comment]
The files may not update and may result in the file lock problem.
And actually, I don't know what will happen, you can have a try.

**Comment by leesei** [comment]
`hexo g` read from `source/` and write to `public/`
`hexo d` read from `public/` and write to `.deploy_git/`

If you are editing the md in `source/` then no.
