### ISSUE TITLE
Is it possible to set the font of the page? 

### ISSUE THREAD

**Issue by woshichuanqilz** [hexojs/hexo#1700]
I check the `_config.yml`, and haven't find the related setting about the font?
I search in the *theme* folder and get too much things about font 

Can I set it in the *theme* ? 

![82](https://cloud.githubusercontent.com/assets/11295355/12164122/0e032bec-b54e-11e5-91da-57c50cfcd061.png)

**Comment by Xuanwo** [comment]
it's depend on your theme. And it's better to ask this question in your theme's issues.

**Comment by PhiLhoSoft** [comment]
font-awesome is used to display icons, it is unrelated to the looks of your text.
To control the font of your pages, you must edit the CSS file (or the files used to generate them, eg. the .styl ones) of the theme you use.
You have to know CSS to do this properly... In general, you provide a list of fonts that can be found on the user's computer, like `Arial, Verdana, Helvetica, sans-serif`.
If you want to use a more specific font, to be downloaded by your visitors, it takes even more CSS trickery...
