### ISSUE TITLE
如何才能真正不处理HTML文件？

### ISSUE THREAD

**Issue by yumemor** [hexojs/hexo#1702]
看了 [#148](https://github.com/hexojs/hexo/issues/148) 和 [#158](https://github.com/hexojs/hexo/issues/158) 都没有找到答案

有人说可以使用：
```
layout:false
```
这种方法还是会处理html文件，但是不会添加布局，会默认添加 头尾

在source文件夹下面的.html也会被处理，能不能设置只处理.md文件呢？

其实我想要的效果就是 在.html/.md 里面写什么，页面就出来什么，别给我添加头尾 ，

原谅我不懂hexo的工作原理，看了几遍都没找到方法，谢谢了！

**Comment by Xuanwo** [comment]
可以尝试一下`skip_render`

**Comment by yumemor** [comment]
已经解决了，感谢
