### ISSUE TITLE
{{site.title}} site.title is undifined?

### ISSUE THREAD

**Issue by lichee** [hexojs/hexo#1707]
in .md files,{{site.title}} site.title is undifined?
how can i get the var that i defined in _config.yml or _data?
i had read hexo.io/docs for many times ,but doesn't work.

**Comment by Xuanwo** [comment]
Yes, `{{site.title}}` just used in yml files.

**Comment by tommy351** [comment]
It's only used in theme.

**Comment by Xuanwo** [comment]
Closed for solved.

**Comment by lichee** [comment]
so...i couldn't use it in my _posts ，right?

**Comment by Xuanwo** [comment]
Yes.
