### ISSUE TITLE
怎么在多个文章间相互跳转

### ISSUE THREAD

**Issue by xiewenlongs** [hexojs/hexo#1709]
我想在文章A中做一个锚点， 在文章B中插入一个链接跳到文章A的锚点。

现在我的做法是： 

1. 在文章A中制作锚点
```
     <a name="Anchor"/> 
```
2. 在文章B中插入跳转
```
[文章A](2016/01/10/article#Anchor)
```

觉得这种做法不太好，硬编码了YYYY/MM/DD,  请问有别的方法吗?

**Comment by Xuanwo** [comment]
目前Hexo对这方面的支持还不算好，可以通过修改`permalink: :year/:month/:day/:title/`为`permalink: :title/` 来部分解决这个问题。

**Comment by leesei** [comment]
https://hexo.io/docs/tag-plugins.html#Include_Posts

But I haven't tried it.

**Comment by PeichengLiu** [comment]
问题+1。这个功能很重要！
