### ISSUE TITLE
Hexo messes up CMD text color

### ISSUE THREAD

**Issue by AWulkan** [hexojs/hexo#1711]
When using some commands Hexo will change the color of my text in the command prompt. The problem is that it never changes the color back again. Look at the example below where it changes the text color from orange to red.

![CMD TEXT CHANGE](http://i.imgur.com/kNf4dp2.png)

Are there any ways to prevent this? It's a bit annoying.

**Comment by Xuanwo** [comment]
Moved to https://github.com/hexojs/hexo-cli/issues/10
