### ISSUE TITLE
我想更换一个主题，直接clone了一个新主题，然后修改_config.yml配置文件

### ISSUE THREAD

**Issue by laohubuchiyu** [hexojs/hexo#1712]
貌似这样不行
重新generate的时候会报错

WARN  No layout: 2016/01/14/db_design/index.html

求解决办法

**Comment by Xuanwo** [comment]
No layout ，可能是没有主题，建议检查一下主题名和你的设置是否一致

**Comment by laohubuchiyu** [comment]
真是这样的。⊙﹏⊙b汗，用的那个主题的文档名字写错了。
