### ISSUE TITLE
How to create custom directory in Hexo?

### ISSUE THREAD

**Issue by tn** [hexojs/hexo#1715]
I want create custom directory with html content which will not compiled by Hexo

Like this:

```
mysite.com/
  scaffolds/
  source/
    _data/
    _posts/
    CUSTOM_FOLDER/
      example.html
      index.html
    ...
  ...
```

Currently Hexo remove my files from custom folder after `hexo generate`.

How to do that? And how to add this folder to public folder? Thanks

**Comment by tn** [comment]
My apologies. I found solution via `skip_render`.

**Comment by clownvary** [comment]
@tn how do u do,i read the doc,but not find answer.

**Comment by 5SMNOONMS5** [comment]
I have same issue, want to know how to create a custom folder
