### ISSUE TITLE
语言类型相同的代码块只有第一个被高亮

### ISSUE THREAD

**Issue by sumy7** [hexojs/hexo#1718]
感觉和 #1710 是相同的问题。标记为相同语言的代码块，只有第一个能被高亮。
如：

    ```java
    System.out.println("Hello World");
    ```

    巴拉巴拉小魔仙

    ```java
    // java codeblock 2
    ```
第一个代码块render出来html的class为`highlight java`，第二个class是`highlight`。
包括使用`{% codeblock lang:java %}` 和两种情况混合使用。
请问这是什么原因？

**Comment by liuzc** [comment]
你可以尝试使用Google Prettify: https://liuzhichao.com/2016/hexo-use-prettify-to-highlight-code.html

**Comment by netcan** [comment]
好像出在特定语句就会不高亮。。

**Comment by leesei** [comment]
關掉代码高亮选项有問題可以參考 https://github.com/hexojs/hexo/pull/1811

**Comment by sumy7** [comment]
按照 #1710 中提到的方法，更新了highlight.js之后，又将所有未高亮的代码检查了一遍。发现未高亮的代码中存在不能识别的字符，导致highlight.js无法识别语言，比如多种语言混合使用，一些语法错误等。 

至此高亮问题基本解决了。也不能算是一个bug了:joy:。。。
