### ISSUE TITLE
更新hexo,成功了,但是hexo deploy/generate 命令都用不了,显示没有

### ISSUE THREAD

**Issue by ConanMTHu** [hexojs/hexo#1719]
~/Hexo ❯❯❯ hexo -v
hexo-cli: 0.1.9
os: Darwin 15.3.0 darwin x64
http_parser: 2.5.0
node: 4.2.3
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
~/Hexo ❯❯❯ hexo deploy
Usage: hexo <command>

Commands:
  help     Get help on Hexo.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

这是什么情况呀?

**Comment by Xuanwo** [comment]
可能是因为当前目录不是Hexo目录，需要先执行`hexo init`

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest version.

**Comment by septsikefeier** [comment]
这是什么问题啊

**Comment by dingyan7** [comment]
Same issue here...
