### ISSUE TITLE
inline highlight  error

### ISSUE THREAD

**Issue by tangleithu** [hexojs/hexo#1727]
Hexo's highlight does not support for inline code while Github Favored Markdown(GFM) does.

For example 

This statement ```printf("hello world!")``` works fine in github, However, error got using Hexo.

source: 
<pre>
this statement ```printf("hello world!")``` works file in github.
</pre>

**Comment by tangleithu** [comment]
Jekyll works fine, too.

**Comment by leesei** [comment]
Hexo is using one quote for inline code.

**Comment by tl3shi** [comment]
那就别在首页宣称~ 

```
Markdown Support
All features of GitHub Flavored Markdown are supported. You can even use most Octopress plugins in Hexo.
```
