### ISSUE TITLE
new page with recent posts

### ISSUE THREAD

**Issue by ritzton** [hexojs/hexo#1729]
Hello,

I am using Hexo with Hueman theme and I would like to create a new page with the X last post and without the layout. I would like this page to create an iframe script that can be inserted in another website.
How can I do this ?

Thank you for your help.

**Comment by drduan** [comment]
maybe you should go to hueman's github issue for help

**Comment by leesei** [comment]
I haven't written a theme layout.
But I suppose you can get X last posts by filtering `locals.posts`. You can refer to the theme's code for applying layout to the data.
