### ISSUE TITLE
hexo deploy fails

### ISSUE THREAD

**Issue by klangwiedergabe** [hexojs/hexo#1731]
<img width="569" alt="screen shot 2016-01-29 at 12 32 44 am" src="https://cloud.githubusercontent.com/assets/1858040/12666458/de6c7d60-c61f-11e5-9733-f0e9e8460871.png">

**Comment by drduan** [comment]
you can try  check your git command  is ready ,first  try use git --version

**Comment by klangwiedergabe** [comment]
this is my version 
git version 2.5.4 (Apple Git-61)

I have no idea what it means? what can I do? :)
thanks

**Comment by drduan** [comment]
and  your reposity  site is wrong ,it's not github。。。。。

**Comment by greg-js** [comment]
@klangwiedergabe Use the [heroku deployer](https://hexo.io/docs/deployment.html#Heroku)

**Comment by klangwiedergabe** [comment]
sorry guys my repo was actually wrong as @drduan said. I just close this or I deleted?
