### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ifgyong** [hexojs/hexo#1733]
MacBook:ifgyong.github.io fgy$ hexo -v
[Error: Module version mismatch. Expected 46, got 47.]
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
hexo: 3.1.1
os: Darwin 15.3.0 darwin x64
http_parser: 2.5.0
node: 4.2.4
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e

I try npm unstall hexo then `npm install hexo --no-optional --save`,but it don`t work for me.

**Comment by ifgyong** [comment]
update npm like `sudo npm i -g npm`,then `npm install hexo --no-optional --save`,it works for me.

**Comment by leggetter** [comment]
Related https://github.com/hexojs/hexo/issues/1742#issuecomment-238649006
