### ISSUE TITLE
Branch master set up to track remote branch master from git@github.com:ifgyong/ifgyong.github.io.git.

### ISSUE THREAD

**Issue by ifgyong** [hexojs/hexo#1734]
hexo d  显示成功 还提示了`Branch master set up to track remote branch master from git@github.com:ifgyong/ifgyong.github.io.git.` 但是在网站上面内容没有更新的。
本地分支是hexo 远程master，在本地的hexo部署到远程master上面不成功，但是在第一个太创建这个博客的电脑上可以。

**Comment by ifgyong** [comment]
没有谁遇见过这个问题吗？

**Comment by leesei** [comment]
你人手在第二台機手動git push 可以嗎?

**Comment by ifgyong** [comment]
可以啊，把文件和hexo 编译文件放在不同分支。push得时候，把源文件锁在分支推上去就好了。

**Comment by Xuanwo** [comment]
估计是两地的`.deployer_git`文件夹内的git历史不一样，产生了冲突。
建议写个push脚本，先pull再push。

**Comment by Xuanwo** [comment]
@leesei We should add this status in git deployer.

**Comment by leesei** [comment]
我不太清楚怎樣reproduce, 你
@ifgyong 你這是能重現的嗎? 還是cache 問題?
我自己會刪除`.deploy_git/` 再deploy (會清空pages 的commit history)

人手clone pages 到`.deploy_git/` 再deploy 如何?
`cd .deploy_git/; git log` 其實有更新嗎?

**Comment by zhangqiangoffice** [comment]
我也遇到了同样的问题，我在example.github.io库中新建了hexo和master两个分支，hexo分支存放的是hexo的源码，master分支存放静态页面。但是，我在第二台电脑上clone下来hexo分支，并写了一篇博客，然后执行hexo g -d，结果github上的master分支变成了本地hexo分支的代码，现在example.github.io网址也不能访问了，简直一头雾水。。。

**Comment by NoahDragon** [comment]
Same issue https://github.com/hexojs/hexo/issues/2570

**Comment by jazhLeo** [comment]
@zhangqiangoffice 删除掉 .deploy_git 文件夹，然后 hexo clean ,hexo g -d 就好了

**Comment by lihp2014** [comment]
+1 同样的问题...删除了 .deploy_git 文件夹，然后 hexo clean ,hexo g -d ，线上还是没有更新- -

**Comment by lihp2014** [comment]
O__O "…-1 上述问题解决了....删除了 .deploy_git 文件夹，然后 hexo clean ,hexo g -d ，是我本地的缓存没清...

**Comment by 54laowang** [comment]
+1 同样的问题...删除了 .deploy_git 文件夹，然后 hexo clean ,hexo g -d ,搞定了，谢谢！

**Comment by AAPONLANG** [comment]
我试过了上述的方法了，还是不行，我使用的是两台电脑，家里的和公司的，之前一直是家里的电脑编辑写文章，push没啥问题，但是在公司down下原来的代码后，写一篇文章，使用hexo d 就出问题了，'master' set up to track remote branch 'master' from ，请问有人遇到过这问题吗

**Comment by xieyezi** [comment]
@zhangqiangoffice ：请问你当时是怎么解决这个问题的哦？

**Comment by xieyezi** [comment]
@zhangqiangoffice :我听他们的，把.deploy_git 文件删除之后，重新hexo clean,  hexo g, hexo d 。 但是线上文章还是没更新

**Comment by tian0o0** [comment]
> @zhangqiangoffice :我听他们的，把.deploy_git 文件删除之后，重新hexo clean, hexo g, hexo d 。 但是线上文章还是没更新

我也遇到了这个问题，请问你解决了吗？

**Comment by xieyezi** [comment]
@tian0o0 没有解决啊

**Comment by HysenChan** [comment]
hexo clean
hexo g -d

**Comment by EvenLjj** [comment]
> @zhangqiangoffice :我听他们的，把.deploy_git 文件删除之后，重新hexo clean, hexo g, hexo d 。 但是线上文章还是没更新

我把git -config设置好了，hexo clean, hexo g, hexo d就OK了

**Comment by YiCheeee** [comment]
删除.deploy_git 文件夹重新hexo d即可

**Comment by BeihaiTianming** [comment]
> 删除.deploy_git 文件夹重新hexo d即可

还是不行

**Comment by harder-er** [comment]
有哪位大佬解决了吗

**Comment by Attack825** [comment]
我把config有地方重新设置，hexo d 就好了

**Comment by zkrun** [comment]
是不是分支错了，我这的情况就是分支的问题

**Comment by cyc0916** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    hexojs/hexo  一年前的东西了lol但还是谢谢 我当时也是修改分支解决的:D2022-12-26
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                air7367
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        12/26/2022 13:40
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [hexojs/hexo] Branch master set up to track remote branch master from ***@***.***:ifgyong/ifgyong.github.io.git. (#1734)
        
      
    
  
  

是不是分支错了，我这的情况就是分支的问题



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Xuanwo** [comment]
Please don't bump already closed old issue, locking now.
