### ISSUE TITLE
Out of memory while generating a huge blog

### ISSUE THREAD

**Issue by ubenzer** [hexojs/hexo#1735]
I imported my Wordpress blog with ~750 posts to default setup of hexo. I got the following error:

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`
  
In file `/Users/ub/.nvm/versions/node/v5.3.0/lib/node_modules/hexo-cli/bin/hexo` changing `#!/usr/bin/env node` to `#!/usr/bin/env node --max_old_space_size=8192` worked.

It would be great, if there is a way to give memory limit without editing the source.

**Comment by lprajus2007** [comment]
the default memory for nodejs is 514mb. There shouldn't be any issue with setting a higher max_old_space_size afaik

**Comment by leesei** [comment]
We've added this to `troubleshooting.md`.
Since not every user encounters this use case, I don't think we should make it the default.

But we may look into why hexo is using so much memory during generation.
We need a large test post set, will create new issue for that.
