### ISSUE TITLE
How to set up Hexo in a subfolder of an existing Jekyll-powered GitHub pages website

### ISSUE THREAD

**Issue by fusion809** [hexojs/hexo#1738]
Hi,

I have a Jekyll-powered GitHub pages website (https://fusion809.github.io) and I would like to deploy my Hexo site (source: https://github.com/fusion809/hexo) in the "hexo" subfolder of the website (i.e., https://fusion809.github.io/hexo). To be clear I want all the remainder of the website, other than this subfolder, to be still powered by Jekyll. All guides on deployment with GitHub pages I have been able to find by a Google Search were about setting up a whole new GitHub pages website that is entirely (and not just a subfolder of it, like I want) powered by Hexo. 

Thanks for your time,
Brenton

**Comment by t3chguy** [comment]
/hexo is a subfolder, hexo.fusion809.github.io would be a subdomain.

**Comment by fusion809** [comment]
@t3chguy OK, so I got the terminology wrong, what I want is my Hexo site in a subfolder of my Jekyll site then. How do I accomplish this?

**Comment by t3chguy** [comment]
I don't use any deployment methods, I pointed it out in the hope that it will aid your search

**Comment by fusion809** [comment]
OK, well thanks, I did find one similar issue #1081, the problem is that I'm not sure if leesei meant gh-pages branch of the username.github.io repo or the blog repo.

**Comment by leesei** [comment]
I've updated my reply.
I think you have to write script to automate the process if you choose option 2 of deployment, `git-deployer` does not support pushing to specific folder (it treats the generated pages as a repo).

**Comment by LaureKamalandua** [comment]
It would  be helpful if someone could provide more insight in this, since I'm running into an equal issue. 
I'm deploying Hexo to my Express application and need it to run from a subdirectory site/blog/ on the same port (3000).

**Comment by leesei** [comment]
@LaureKamalandua Refer to option 2 of deployment [here](https://github.com/hexojs/hexo/issues/1081#issuecomment-121851703).
`hexo generate` and server the `public/` created by Hexo with your Express app.

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest version.
