### ISSUE TITLE
Why the `tags` page show `404 not found` 

### ISSUE THREAD

**Issue by woshichuanqilz** [hexojs/hexo#1739]
[my blog tags link](http://woshichuanqilz.github.io/tags/)

the content of the only one post is like this.  And I use the `next` theme

![02~05_14-31-39.png](http://7xpvdr.com1.z0.glb.clouddn.com/02~05_14-31-39.png)

**Comment by pod4g** [comment]
哥们儿，加个好友呗。关于tag页有问题需要请教你。qq:455322185
