### ISSUE TITLE
Hexo deploy 导致项目历史被清空

### ISSUE THREAD

**Issue by Arondight** [hexojs/hexo#1740]
直观一点的话请看hexo deploy 导致的[提交历史](https://github.com/Arondight/arondight.github.io/commits/master)。
我大致模拟还原一下吧：
```shell
$ pwd
~/user/xxx.github.io
$ cd ..
$ rm -rf xxx.github.io
$ git clone ......./xxx.github.io
$ cd xxx.github.io
$ hexo g
$ hexo d
```
假设xxx.github.io 项目有两个分支，分支master 为网站，分支source 为markdown 文件等，项目默认为source 分支，hexo 管理master 分支。经过上面的操作，**会导致master 分支被全部清空，刚才的提交称为根提交**。
我觉得这是个很不可理解的BUG，您可以参照[这个项目](https://github.com/Arondight/arondight.github.io)来对应xxx.github.io 的情况。
```shell
$ git --version
git version 2.7.0
$ hexo --version
hexo-cli: 0.1.9
os: Linux 4.4.1-2-ARCH linux x64
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
```

**Comment by Xuanwo** [comment]
我是这样处理的： https://github.com/Xuanwo/xuanwo.github.io/blob/blog/.travis.yml#L21

目前的逻辑是：除非`.deploy_git`下已经存在一个库，否则deployer都会进行强制提交。

不知道您有没有更好地处理方法？

**Comment by Arondight** [comment]
谢谢您的回复，抛开技术从可行性上我是这么想的：

1. 目前可以知道项目库的路径
+ 可以知道要推的分支

这样的话很自然的会想到如果一个库存在则尝试pull 再commit 然后push，如果库不存在则尝试clone。

我是这样想的，不知道有没有可行性，和技术手段上是否容易实习

**Comment by Xuanwo** [comment]
可以考虑一下，不过大家看起来都很忙- -，不知道谁能腾出手来修正一下deploy的工作历程。

我先标记一下吧~

**Comment by Arondight** [comment]
嗯，谢谢您的回复和关注，祝您新年快乐。

**Comment by Xuanwo** [comment]
你也是~

秦凡东 <notifications@github.com>于2016年2月5日周五 下午8:12写道：

**Comment by Arondight** [comment]
最后我和跟你一样先[这样](https://github.com/Arondight/arondight.github.io/commit/32f0a7c0aaebcd32868f4f01d2325b7a633e2151)凑合用了  \_(:з」∠)_

**Comment by leesei** [comment]
我個人不太管gh-pages repo 的history
不過跟據@Xuanwo 的思路可以把
`git clone <gh-pages repo> .deploy_git`
加到你`source` branch 的`package.json` 的`scripts.postinstall` 下

**Comment by leesei** [comment]
如果deployer-git 多於一個repo 總會有問題的
我覺得這可以放到deployer-git 的README 會比較好

**Comment by leesei** [comment]
Added https://github.com/hexojs/hexo-deployer-git/blob/master/README.md#how-it-works
