### ISSUE TITLE
How to add a link that link to an ID within this article?

### ISSUE THREAD

**Issue by MegaThomas** [hexojs/hexo#1741]
When I write `[blah](#id)`, it always generates `<a href="/#id">blah</a>`. How can I get rid of that `/` before `#id`?

**Comment by ktalo** [comment]
How about writing it in plain HTML: `<a href="#id">blah</a>` ? I mean it's ok to have html fragments in between the markdown parts. 

`<a href="#id">blah</a>`

**Comment by Xuanwo** [comment]
use HTML

**Comment by MegaThomas** [comment]
It works. Thanks a lot.

**Comment by leesei** [comment]
On 3.2beta the link is fine:
http://leesei.github.io/hexo-vanilla-site/2016/02/22/1741/

**Comment by Xuanwo** [comment]
Closed for sloved.
