### ISSUE TITLE
 Module version mismatch

### ISSUE THREAD

**Issue by auszone** [hexojs/hexo#1742]
[Error: Module version mismatch. Expected 47, got 44.]
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
These error messages pop out everytime I invoke a hexo command.

**Comment by tommy351** [comment]
Try to remove node_modules and run npm install again.

**Comment by auszone** [comment]
@tommy351 I did, but it does not work.

**Comment by twiceyuan** [comment]
I also have the same problem.

**Comment by twiceyuan** [comment]
update: I solved it by #1733

**Comment by leesei** [comment]
Use `npm install --no-optional`

**Comment by leggetter** [comment]
I was also getting this but with the error:

> [Error: Module version mismatch. Expected 46, got 47.]

It seems there was a mismatch between one of:

1. The `hexo` in `node_modules/.bin`
2. The `hexo in `/usr/local/bin/hexo`
3. The globally installed `hexo` which may well have been the one from 2.

My solution was:

```sh
npm uninstall -g hexo-cli
rm /usr/local/bin/hexo
rm -rf node_modules
npm install
npm install -g hexo-cli
```

**Comment by dukegod** [comment]
@leggetter thanks, it words for me

**Comment by liujinlongxa** [comment]
@leggetter thanks

**Comment by Clearives** [comment]
@leggetter thanks, it works for me

**Comment by nadihsu** [comment]
@leggetter Thanks! ;)
