### ISSUE TITLE
How to add pagination to custom page?

### ISSUE THREAD

**Issue by eventhough** [hexojs/hexo#1743]
Hi,

I've created a custom page called `/blog` that I am treating like the `archives` page. The problem is, `page.prev_link` and `page.next_link` are only available on the `index` and `archives` page. How do I add these to a custom page?

Pagination doesn't work on custom pages - is there any way we can get pagination to work wherever we want?

Or if it's easier, can we set the `archives` page to a different route in config?

**Comment by ktalo** [comment]
Try this in _config.yml to have archives generated as /blog
`archive_dir: blog`

**Comment by eventhough** [comment]
@ktalo It worked! Thanks so much.
