### ISSUE TITLE
昨天一下子把hexo的文件都删掉了，再装报错

### ISSUE THREAD

**Issue by maoxiangyu** [hexojs/hexo#1745]
如下怎么解决：
npm WARN install:ansi@0.3.0 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-1e022d08' -> '/usr/local/lib/node_modules/hexo-cli/node_modules/fsevents/node_modules/ansi'
npm WARN install:ansi-regex@2.0.0 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-regex-c295664a' -> '/usr/local/lib/node_modules/hexo-cli/node_modules/fsevents/node_modules/ansi-regex'
........(省略一大堆以上格式的warn)
cli/node_modules/fsevents/node_modules/xtend'
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
/usr/local/lib
└── hexo-cli@1.0.1

**Comment by drduan** [comment]
换一个文件夹 hexo装错地方了吧
