### ISSUE TITLE
文件名含有#会出错

### ISSUE THREAD

**Issue by michaelHL** [hexojs/hexo#1748]
比如在`/source/_posts`下新建一个名为`C#教程.md`的文件, 
文章信息为:

```

---
title: C#教程
date: 2016-02-15 12:19:02
tags: C#
comments: true

---
```

在本地调试的时候发现:
- 地址变成了`http://localhost:4000/2016/02/15/C/#教程/`, 显示内容为`Cannot GET /2016/02/15/C/`
- 把地址改为`http://localhost:4000/2016/02/15/C#教程/`, 则会自动切回`http://localhost:4000/2016/02/15/C/#教程/`, 浏览器: `Chrome 48.0.2564.109 m`
- 把地址改为`http://localhost:4000/2016/02/15/C%23教程/`, 则网页正常打开, 内容正常显示
- 点击标签页里面的C#，地址变成了`http://localhost:4000/tags/C/`, 也就是说`C#`标签变成了`C`

---

Hexo版本:

```
hexo-cli: 1.0.1
os: Windows_NT 6.1.7601 win32 ia32
http_parser: 2.6.1
node: 5.6.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f
```

**Comment by lisx** [comment]
#号前面加转意符 \ 应该就可以了.

**Comment by michaelHL** [comment]
@lisx 
仍然打不开, 且标题显示为`\#`, 也就是说标题修改成什么它就显示成什么, 然而地址栏里面显示的仍然是
`http://localhost:4000/2016/02/15/C/#教程/`

**Comment by leesei** [comment]
你趕急用的話用`c-sharp` 為你的label
特別字符處理可能比較複雜
