### ISSUE TITLE
求助：hexo deploy报403错误

### ISSUE THREAD

**Issue by kathe-jing** [hexojs/hexo#1750]
hexo deploy报如下的错误：
error: RPC failed; result=22, HTTP code = 403
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: error: RPC failed; result=22, HTTP code = 403
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

    at ChildProcess.<anonymous> (/home/zengjing/Hexo/blog/node_modules/hexo-deployer-git/node_modules/hexo-util/lib/spawn.js:37:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)

求大神帮忙解决~！

**Comment by leesei** [comment]
你密碼正確嗎?
https://help.github.com/articles/set-up-git/

`hexo generate` 後人手push `public/`到你的repo 試試

**Comment by kathe-jing** [comment]
@leesei  密码是对的

**Comment by Xuanwo** [comment]
你的`config.yml`中 deploy相关配置贴出来看看呢？

**Comment by kathe-jing** [comment]
@Xuanwo  
deploy:
  type: git
  repository: https://github.com/kathe-jing/kathe-jing.github.io.git
  branch: master

**Comment by kathe-jing** [comment]
@leesei  手动push还是报之前的403错误

**Comment by kathe-jing** [comment]
@leesei 我从仓库上clone下来，再push是ok的，但是在hexo生成的.deploy_git目录下pull也是可以的，但是push就是不行，403错误，用户名密码肯定是对的。

**Comment by kathe-jing** [comment]
@leesei  @Xuanwo 找到原因了，公司代理把上传代码权限禁止了，多谢了~！

**Comment by Xuanwo** [comment]
Closed for fixed.
