### ISSUE TITLE
can't read from db.json

### ISSUE THREAD

**Issue by LaureKamalandua** [hexojs/hexo#1752]
There aren't clear notes in the documentation where the database config is stored for Hexo.
In addition, which information can be used to connect to it. 
It isn't visible when checking the dependencies. Could someone clarify this matter.

**Comment by greg-js** [comment]
The database used in hexo is [warehouse](https://github.com/tommy351/warehouse). 

I'm not sure what you mean by connecting to the database? If you want to write a plugin and hook into it, you will automatically have access to it if you follow [the docs](https://hexo.io/docs/plugins.html). Or if you want to select posts from the db in your templates, check the layout files in your theme for how it's done (and in [Variables](https://hexo.io/docs/variables.html) and [Templates](https://hexo.io/docs/templates.html)).

**Comment by LaureKamalandua** [comment]
Thank for clearing that up. That clarifies a lot.
