### ISSUE TITLE
cannot install on my windows mechine...

### ISSUE THREAD

**Issue by chantisnake** [hexojs/hexo#1754]
It is weird, It works well on my surface, but not my XPS15:
![capture](https://cloud.githubusercontent.com/assets/10100995/13095412/8883e504-d4df-11e5-9b6a-fef40c193589.PNG)

**Comment by chantisnake** [comment]
manually adding the dir to path works, but this is weird. My node is installed together with VS(I think)

**Comment by leesei** [comment]
VS provides a console with PATH already set.
You have to set PATH manually if you use other console.
