### ISSUE TITLE
Offer a way to skip tags plugin totally during editing

### ISSUE THREAD

**Issue by jusfeel** [hexojs/hexo#1755]
For html+handlebars, it be great if I can skip all that tags processing and still keep markdown processing. The template engine currently fails at those `{{`,`}}`,`#` characters when try to process the template.

Some code snippet like this would fail and it's not really workable to use `raw` either ( have to use html entities for all the arrow brackets, too much.)
```
<div class="container">
  <h1>Works</h1>
  <ul class="row-fluid block-grid-4">
  {{#each model as |w index|}}
    <li>
      <h5>{{w.title}}</h5>
      <p>Owner: {{w.owner}}</p>
      <p>{{#link-to "work" w.id}}<img class="img-responsive img-rounded" src={{w.image}} alt={{w.title}}>{{/link-to}}</p>
    </li>
  {{/each}}
  </ul>
</div>
```

**Comment by leesei** [comment]
The feature request aside, there's no problem rendering the code snippet:
http://leesei.github.io/hexo-vanilla-site/2016/02/23/1755/

**Comment by leesei** [comment]
Making Nunjuck optional is tracked in #1510.

**Comment by jusfeel** [comment]
Somehow, the line number column becomes merged into only one row ( "1" only) on my end. The rest is ok. 

How did you show the line number correctly? Or better if I can hide the line number?

**Comment by leesei** [comment]
#1543 From the thread highlight tagged in 1 line only is because our line splitting is on *nix new line character only

You can disable line number with config:
```yaml
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
```

**Comment by leesei** [comment]
Can you send me the file? I have problem reproducing #1543 even with Windows endline.
Anyway this issue shall be closed.

**Comment by jusfeel** [comment]
Works after turning off line_number.
Attached the file I was working on ( the code at line 109 )





--


王 昊
Hao WANG
86 186 0086 9737
为学日益 为道日损
http://blog.jusfeel.cn



  

在 2016-02-23 15:58:23，"leesei" <notifications@github.com> 写道：


Closed #1755.

**Comment by leesei** [comment]
Can you post it on Gist?
Also your `npm ls --depth 0`.
Thanks.

**Comment by jusfeel** [comment]
https://gist.github.com/jusfeel/206e89bca9cbaf933fe5#template

I didn't edit the other parts. It was from a wordpress post.
