### ISSUE TITLE
Issues Enhancement : add a ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#1759]
@tommy351 @leesei 

Due to this update : https://github.com/blog/2111-issue-and-pull-request-templates , now we can add a template for issues.
May we can find a way to make people provide more useful information.

**Comment by Xuanwo** [comment]
Generally, we need information below:
- users' hexo version
- node version
- `config.yml`(with site's and theme's)

### For BUG

We need:
- BUG description
- the way to reproduce

### For question

just push question

### For feature request

just push feature request

> About language
English will be better, and we accept Chinese(both in simplified and traditional) too.

**Comment by leesei** [comment]
@Xuanwo I edited the info needed

**Comment by Xuanwo** [comment]
@leesei Maybe we can provide a script for user to print the info?

**Comment by leesei** [comment]
Besides #1632. the other commands are stated above.

**Comment by stevenjoezhang** [comment]
Added in https://github.com/hexojs/hexo/pull/3600

**Comment by Xuanwo** [comment]
Closed for https://github.com/hexojs/hexo/pull/3600 merged.
