### ISSUE TITLE
hexo has no method "init"

### ISSUE THREAD

**Issue by LaureKamalandua** [hexojs/hexo#1762]
The objective is to run the hexo server using forever process management tool

// created app.js file at blog/app.js
require('hexo').init({command: 'server'});

// executed forever app.js from the directory 
(function (exports, require, module, __filename, __dirname) { require('hexo').init({command: 'server'});
                                                                                                                          ^
TypeError: require(...).init is not a function
    at Object.<anonymous> (X:\node\laurekamalandua.com\blog\app.js:1:79)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by Xuanwo** [comment]
you need to do https://github.com/hexojs/hexo-cli/blob/0.1.9/lib/index.js#L74 first.

**Comment by leesei** [comment]
Admittedly we don't have enough documentation for Hexo module. PRs are welcome.

Do check these code to learn how Hexo should be used.
https://github.com/hexojs/hexo-cli/blob/0.1.9/lib/index.js#L73-L77
https://github.com/hexojs/hexo/blob/master/test/scripts/hexo/hexo.js

```js
var Hexo = require('hexo');
var hexo = new Hexo(null, options);
hexo.then((args) => hexo.call('server'));
```

**Comment by LaureKamalandua** [comment]
me: opens issue to declare there are problems with forever integration
developer: closes ticket stating "open an issue when you have a problem integrating with forever"

Thanks. The support is really great on this one guys. Perhaps I'll better shop around at other blogging frameworks to ensure support is to be met.

**Comment by leesei** [comment]
Do you aware that your issue is due to your misuse of API?

**Comment by LaureKamalandua** [comment]
If someone can not clearly point out mistakes and provide a practical example or good explanation, then you should not expect the API to be used appropriately. The examples on https://hexo.io/api/ are not practical.

**Comment by leesei** [comment]
If you don't understand the error message and the difference between 
```js
var Hexo = require('hexo');
var hexo = new Hexo(process.cwd(), options);
hexo.then((args) => hexo.call('server'));
```
and
```js
require('hexo').init({command: 'server'});
```
then you probably are not ready to code in JavaScript.

**Comment by LaureKamalandua** [comment]
You are probably not ready to properly document your code. Because 6 replies further you still can't answer my question in regards to integration with forever. Case closed.

**Comment by anyexinglu** [comment]
把app.js里的代码改成：

var Hexo = require('hexo');

hexo = new Hexo(process.cwd(), {});
hexo.init().then(function () {
  hexo.call('server', {});
});

然后blog> forever app.js 即可！
