### ISSUE TITLE
Question: How to display full blog posts instead of excerpts?

### ISSUE THREAD

**Issue by thevangelist** [hexojs/hexo#1768]
I'd like to have a single browseable page instead of needing to open every blog post one by one. How do I achieve this?

**Comment by leesei** [comment]
Hexo by default show paginated full posts.
You have to manually use `<!-- more -->` to make it show excerpts.

For single page showing all posts, disable [Pagination](https://hexo.io/docs/configuration.html#Pagination).

**Comment by iansinnott** [comment]
Just a heads up, the usage of `<!-- more -->` not seem to be present in the documentation linked above.
