### ISSUE TITLE
怎么生成rss啊？ 文档里也没有提到

### ISSUE THREAD

**Issue by acforu** [hexojs/hexo#177]

**Comment by heessf** [comment]
安装插件的时候一定要加`--save`参数，不然谁用谁知道

**Comment by gardenyuen** [comment]
@acforu 我也是看不到

**Comment by heessf** [comment]
http://heessf.github.io/2015/06/11/install-hexo-rss-and-stiemap-plugins/

2015-06-29 21:32 GMT+08:00 gardenyuen <notifications@github.com>:

**Comment by JanzTam** [comment]
擦，当初就是漏了 `--save`参数，然后一直折腾都不行，加了之后就好了
