### ISSUE TITLE
Static Generator Problems

### ISSUE THREAD

**Issue by santoshsankar** [hexojs/hexo#1770]
I am having an issue where when I generate my site, the links break. I'm unsure where this is breaking down. Some details:

- Index: ˜/santosh/public/index.html
- There's a post called I'm Back which is im-back.md but the static link is to file:///im-back/
- There's a page called About which is /About/index.md but the static link is to file:///About/

Note that everything works ok with the hexo server on. Only issue, which might be linked, conceptually, is that image embedding doesn't work when post_asset_folder: true.

Any help would be appreciated -- thanks in advance!

**Comment by leesei** [comment]
You have to run a HTTP server to serve `public/`.
Use Node's [http-server](https://www.npmjs.com/package/http-server) or [equivalents] (https://www.npmjs.com/search?q=http+server)
