### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1771]
It helps the user identify and fix errors if we 
- throw sensible errors
- print warnings more verbosely.

Do comment if you found some area that needs improving.

---

**EDIT** I have a WIP branch here:
https://github.com/leesei/hexo/commits/better-error-message

To use this branch:

```
npm i leesei/hexo#better-error-message
```

**Comment by leesei** [comment]
#### slug not found

Hexo fails silently upon this:
https://github.com/hexojs/hexo/issues/1562
https://github.com/hexojs/hexo/issues/1594

**Comment by leesei** [comment]
#### `_config.yaml`

YAML is quite strict in its format and Hexo does not report YAML parsing error properly.
We should catch parsing error early, log and abort the operation.

https://github.com/hexojs/hexo-deployer-git/issues/15
https://github.com/hexojs/hexo/issues/1263
https://github.com/hexojs/hexo/issues/11

add resource like [Online YAML Parser](http://yaml-online-parser.appspot.com/)

**Comment by leesei** [comment]
#### Missing theme

#1658

**Comment by leesei** [comment]
#### Better trace of invalid tag

Currently the stack track (in grey, which is hard to read) is logged
However the file causing the error and the erroneous tag are not mentioned

Try adding this to any file in `_post`:
```
{% codeblock %}
alert('Hello World!');
{% codeblock %}
```

**Comment by tomByrer** [comment]
Thank you for looking into these.

**Comment by modkzs** [comment]
The error message that hexo s or g print is very bad. It doesn't mention which file, row and columns that cause generating failure. So every time I have to spend long time finding what error is

**Comment by leesei** [comment]
I have a WIP branch here:
https://github.com/leesei/hexo/commits/better-error-message

**Comment by leesei** [comment]
#### Stack trace color

Currently the stack track is logged in grey, which is hard to read

> Done, see https://github.com/hexojs/hexo-log/pull/1

**Comment by nickdesaulniers** [comment]
did this ever get merged?  Seeing an unknown tag error, and while I can grep for the tag, a readable error message rather than a stack trace that listed the source file would be :100:

**Comment by leesei** [comment]
ping @tommy351, please merge the PR for hexo-log first.

**Comment by NoahDragon** [comment]
Both changes are merged, thank you. 
https://github.com/hexojs/hexo-log/pull/1
https://github.com/hexojs/hexo-cli/pull/13
