### ISSUE TITLE
gitcafe变成github了。

### ISSUE THREAD

**Issue by imhentai** [hexojs/hexo#1772]
我是用gitcafe pages部署hexo的
而且把源码放在master分支上

今天重新部署的时候，输入git push
提示我输入用户名和密码。。。而且是github网站的，可是我用hexo d 是正常部署在gitcafe啊

![qq 20160223230903](https://cloud.githubusercontent.com/assets/8164505/13255862/2516e198-da83-11e5-9032-efab3552044f.png)

访问路径也不对，竟然是hexojs/hexo-starter
这是啥情况。。。迷糊了

**Comment by Jeffrey95** [comment]
gitcafe默认的分支是：`gitcafe-pages`
估计你是直接从github上clone下来的，而没有更改push的远程分支，所以会push到hexojs/hexo-starter
你可以用`git branch - a`来查看远程分支。
如果是这个问题的话，你把远程分支改成你gitcafe的项目再push试试看？

**Comment by leesei** [comment]
應該是`git remote -v`
github clone 下來就是github 的
可以人手加gitcafe 的url 及set tracking branch
不過從gitcafe clone 一次比較簡單

**Comment by imhentai** [comment]
修改了git的config文件，好了。
