### ISSUE TITLE
url_for is returning the wrong url

### ISSUE THREAD

**Issue by JBaczuk** [hexojs/hexo#1773]
I created a new page which added a folder to the source folder called about.  The about folder contains an index folder with assets, and an index.md file.  When I run hexo server, url_for(path) in the header.ejs file on the homepage returns /index.html.  But, when I run hexo generate, url_for(path) on the homepage returns /about/index.html.  I tested this by adding <p><%- url_for(path) %></p> to header.ejs right under the comment that logs message_isHome to the console.

**Comment by jeffa00** [comment]
I have a possibly related issue.

I've added the following to my header.ejs file (my own custom layout):

``` html
<!-- <%- path %> -->
<!-- <%- url %> -->
<!-- <%- page.path %> -->
<!-- <%- page.title %> -->
```

When I run hexo server I get:
``` html
<!-- contact/index.html -->
<!--  /contact -->
<!-- contact/index.html -->
<!-- Contact -->
```

When I run hexo generate here's what I get:

``` html
<!-- about-us/index.html
<!--  /about-us -->
<!-- about-us/index.html -->
<!-- About Us -->
```

This is what I get for **every** page, not just the contact page.

It's like the page variable isn't being updated for each page when generate is run.

**Comment by stevenjoezhang** [comment]
This may be related to `partial` and cache
