### ISSUE TITLE
Subdirectory not working properly

### ISSUE THREAD

**Issue by PurplePenguin4102** [hexojs/hexo#1775]
A freshly installed blog: http://jhray.com/blog

notice that archives guides you to http://jhray.com/archives instead of http://jhray.com/blog/archives

I set the _config.yml to 
`# Site
title: Hexo
subtitle:
description:
author: Joey Ray
language: default
timezone:

`# URL
`## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jhray.com/blog
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
`
when I inspected public/index.html the href on the archive link was ser to '/' instead of '/blog/'

**Comment by Xuanwo** [comment]
Yes, I reproduced it.
It used to be OK, some commit may break it, let me see.

**Comment by Xuanwo** [comment]
It confused me that they lokk good from code:

https://github.com/hexojs/hexo/blob/ef6e15d0c8be73c42620b5fccb626d3b55094cf4/lib/plugins/helper/url_for.js#L32

https://github.com/hexojs/hexo-theme-landscape/blob/master/layout/_partial/header.ejs#L9-L11

**Comment by PurplePenguin4102** [comment]
A similar thing was happening with the flexy theme. From reading url_for.js, my guess is that

if (data.protocol)

is returning false instead of true for some reason. That or options.relative isn't set.

**Comment by Xuanwo** [comment]
`data.protocol` is just to check is there `http` or `https` in url, I think not here.

**Comment by Xuanwo** [comment]
@PurplePenguin4102 Hello, this problem was fixed in hexo 3.2beta. You can install it by `npm install hexo@beta --save`

And I make a fault that, the code in github is latest, but our environment is still in 3.1.1. = =

**Comment by leesei** [comment]
@PurplePenguin4102 3.2 may have other issue, that's why it's not yet pushed to npm. Use with care.

@Xuanwo You can use `hexojs/hexo` in `package.json`. But I have hexo cloned separately to be able to run test on it.

**Comment by PurplePenguin4102** [comment]
yeah no worries, thanks guys :) Awesome that there was already a fix :+1:

**Comment by Xuanwo** [comment]
@leesei OK, I got it~

**Comment by RohanGautam** [comment]
I still had this issue. I had to use my main github page(`username.github.io`) for it to work. Literally the same issue as this on hexo 4.2.0! Let me know if there's anything that can be done

**Comment by muyi110** [comment]
> I still had this issue. I had to use my main github page(`username.github.io`) for it to work. Literally the same issue as this on hexo 4.2.0! Let me know if there's anything that can be done

I had this issue too.

**Comment by dimaslanjaka** [comment]
Same problem here `hexo@6.3.0`

![image](https://user-images.githubusercontent.com/12471057/194115426-f0e76276-ac1d-43c0-a7d8-96183c4423f2.png)
![image](https://user-images.githubusercontent.com/12471057/194115479-469d2ca7-7674-4b74-93be-9e2152dab0f8.png)

**Comment by dimaslanjaka** [comment]
https://github.com/hexojs/hexo/issues/5086
