### ISSUE TITLE
issue on hexo reinstalling

### ISSUE THREAD

**Issue by xiongyu1988** [hexojs/hexo#1778]
Hi 

I have got this issue when I try to reinstall hexo (for deleting, I simply deleted previous hexo folder).

I got this following issue notice.

> E:\hexoBlog>npm install -g hexo-cli
> npm WARN optional dep failed, continuing fsevents@1.0.8
> 
> > spawn-sync@1.0.15 postinstall C:\Users\xiongyu1988\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\hexo-util\node_modules\cross-spawn\node_modules\spawn-sync
> > node postinstall
> 
> \
> > dtrace-provider@0.6.0 install C:\Users\xiongyu1988\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\hexo-log\node_modules\bunyan\node_modules\dtrace-provider
> > node scripts/install.js
> 
> 
> > hexo-util@0.5.3 postinstall C:\Users\xiongyu1988\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\hexo-util
> > npm run build:highlight
> 
> 
> > hexo-util@0.5.3 build:highlight C:\Users\xiongyu1988\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\hexo-util
> > node scripts/build_highlight_alias.js > highlight_alias.json
> 
> C:\Users\xiongyu1988\AppData\Roaming\npm\hexo -> C:\Users\xiongyu1988\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo
> hexo-cli@1.0.1 C:\Users\xiongyu1988\AppData\Roaming\npm\node_modules\hexo-cli
> ├── object-assign@4.0.1
> ├── abbrev@1.0.7
> ├── minimist@1.2.0
> ├── tildify@1.1.2 (os-homedir@1.0.1)
> ├── bluebird@3.3.1
> ├── chalk@1.1.1 (escape-string-regexp@1.0.5, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0, ansi-styles@2.2.0)
> ├── hexo-fs@0.1.5 (escape-string-regexp@1.0.5, graceful-fs@4.1.3, chokidar@1.4.2)
> ├── hexo-log@0.1.2 (bunyan@1.7.0)
> └── hexo-util@0.5.3 (striptags@2.1.1, html-entities@1.2.0, camel-case@1.2.2, cross-spawn@2.1.5, highlight.js@9.2.0)

Any ideas? Thanks!

**Comment by Xuanwo** [comment]
It just a warning, you can miss it or use `npm install hexl-cli -g --no-optional`.
From your log, it looks like you have install hexo correctlly.

**Comment by xiongyu1988** [comment]
thanks!
