### ISSUE TITLE
Feature Request: Centralized client-side scripts management

### ISSUE THREAD

**Issue by akfish** [hexojs/hexo#1780]
## Motivation

Themes and plugins usually need to work in conjunction with client scripts. 

In current versions, injecting client scripts from plugins is not trivial and involves modifying theme source code or generated html. This is error-prone since custom code is injected without any verification. 

It is also hard to resolve dependencies. For example, popular libraries like `jQuery` could easily be required by themes and multiple plugins at the same time. There is no way to prevent rendered HTML from having multiple `<script>` tags referencing multiple `jQuery` versions and breaking some or even all of the plugins.
### Workflow
1. Themes use `require` helper to reference scripts
2. Plugins use `hexo.extend.client` to reference/inject scripts
3. Hexo builds a dependency tree and checks for conflict
4. Hexo generates routes for local scripts
5. Insert `<script>` tags in proper places in generated HTML
### Add `require(module, [version], [opts])` helper

In theme layouts, instead of:

``` ejs
<script src="jQuery.js"></script>
```

Do:

``` ejs
<%- require('jQuery', '2.2.1', { source: "npm" }) %>
```

Or:

``` ejs
<%- require('jQuery@2.2.1', { source: "bower" }) %>
```

Or:

``` ejs
<%- require('jQuery', '2.2.1', { source: "//code.jquery.com/jquery-1.12.0.min.js" }) %>
```

Version number should follow the same format as node.js's [dependency version range](https://docs.npmjs.com/files/package.json#dependencies).

Script source is specified in `opts.source` field. Valid sources can be:
- npm
- bower
- url
- relative path
### Add `hexo.extend.client` extension point

In plugin script:

``` js
hexo.extend.client.register("fancy_plugin", function(require) {
  // External
  require('jQuery', '2.2.1', { source: 'npm' });
  // Internal
  require('./client/inject.js', { layout: ['archives', 'posts'] });
});
```

`opts.layout` field specifies in which layout to inject client scripts.
### Add filter `"require_script"`

This filter is used for loading script.

``` js
hexo.extend.filter.register("require_script", function(module, version, opts) {
  // Should support promise
  // Don't handle
  return null;
  // External scripts, no routes will be generated. Return url for script tag's src field
  return { url: someOptionalTransformToTheUrl() }
  // Local scripts that should be hosted
  return { content: stringOrStreamOrPromise() }
});
```
### Add filter `"transform_scripts"`

This filter is for other plugins to consume.

``` js
hexo.extend.filter.register("transform_scripts", function(script_routes) {
  // Example: uglify each scripts
  return script_routes.map(function(script) {
    return {
      path: script.path,
      content: uglify(script.content)
    }
  }
  // Example: generate a bundle
  return {
    path: "bundle.js",
    content: makeBundle(script_routes);
  }
}
```
## Migration Strategy

This should be an opt-in features. Though the higher the adaption rate is, the better for its benefit to show.
Hexo should:
1. Check explicit usage of `<script>` tags in:
   a. theme's layout file content
   b. content generated by plugins that will be used as raw HTML
2. Prompt warning messages

**Comment by akfish** [comment]
Partially implemented in [hexo-inject](https://github.com/akfish/hexo-inject)

**Comment by stevenjoezhang** [comment]
Does this meet your requirements: #4047
