### ISSUE TITLE
f6407dc breaks `hexo g`

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#1781]
Hexo version: latest code in github
Node version: 5.4, 5.5, 5.6

Build log:
- https://travis-ci.org/Xuanwo/xuanwo.github.io/builds/111970006 (All right in 3.2.beta-2)
- https://travis-ci.org/Xuanwo/xuanwo.github.io/builds/111968667 (5.4.1)
- https://travis-ci.org/Xuanwo/xuanwo.github.io/builds/111968667 (5.6.0)

@tommy351 @leesei

**Comment by leesei** [comment]
I merged `mark` for codeblock tag today.
But I've been using master branch to build leesei/hexo-vanilla-site and its okay.

**Comment by leesei** [comment]
@tommy351 I think we should also use `hexo g --debug && hexo d` for hexo.io, then we won't corrupt the site incidentally.

**Comment by leesei** [comment]
By doing regression of the [commits](https://github.com/hexojs/hexo/commits/master), I found 
its f6407dc946c2a686731b2480ee6ed0b37f54c5f1 that causes the error.

```sh
10861  2016-02-27 00:21  npm i https://github.com/hexojs/hexo\#58971dc460c79debbb68f93a98911660d5585fc3
10863  2016-02-27 00:22  hexo cl && hexo g --debug # success
10864  2016-02-27 00:23  npm i https://github.com/hexojs/hexo\#f6407dc946c2a686731b2480ee6ed0b37f54c5f1
10865  2016-02-27 00:24  hexo cl && hexo g --debug # fail
```

That commit is beyond my current understanding, @tommy351 please have a look.

**Comment by stevenjoezhang** [comment]
This Issue should have been fixed
