### ISSUE TITLE
[求助]hexo 3.1.1.1 同时deploy 到github 和gitcafe 失败

### ISSUE THREAD

**Issue by QiJunHu** [hexojs/hexo#1782]
```
deploy:
   type: git
   repo: 
     git@github.com:QiJunHu/QiJunHu.github.io.git 
     git@gitcafe.com:QiJunHu/QiJunHu.git,gitcafe-pages
```
clean 和generate 都ok ,就是deploy 时失败
错误信息：

> fatal: remote error:
>    is not a valid repository name
>   Email support@github.com for help
> FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
> Error: fatal: remote error:
>    is not a valid repository name
>   Email support@github.com for help
> 
>     at ChildProcess.<anonymous> (D:\Users\HexoBlog\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:37:17)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at ChildProcess.cp.emit (D:\Users\HexoBlog\node_modules\hexo-deployer-git\node_modules\hexo-util\node_modules\cross-spawn\node_modules\cross-spawn-async\lib\enoent.js:37:29)
>     at maybeClose (internal/child_process.js:821:16)
>     at Socket.<anonymous> (internal/child_process.js:319:11)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at Pipe._onclose (net.js:469:12)

**Comment by Xuanwo** [comment]
注意正确的格式：
```
deploy:
  type: git
  message: [message]
  repo: 
    github: <repository url>,[branch]
    gitcafe: <repository url>,[branch]
```

**Comment by yannweb** [comment]
3.2.2 还是有这个问题

**Comment by Eugene1024** [comment]
have  you solved this problem ? I  meet the  same situtation, I was at a  mess, I  googled it but  I  didn't find  the  answer

**Comment by NoahDragon** [comment]
@Eugene1024 Please post your config file.
