### ISSUE TITLE
Deprecate highlight auto-detect config

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1786]
Auto-detect is slow and may crash on specific input.
It is no longer recommended in Heo 3.2, original discussion in #1627
Now that:
- default setting is `false`
- `util.highlight()` default to `plain` if no `lang` is provided

I think we can deprecate auto-detect config and give a warning if it is defined.

**Comment by stevenjoezhang** [comment]
This option is required by highlight.js 10 and therefore cannot be removed. Related documents have been updated.

https://github.com/hexojs/hexo-util/pull/196#pullrequestreview-400359127
