### ISSUE TITLE
url_for @ hexo version 3.2.0

### ISSUE THREAD

**Issue by samwhelp** [hexojs/hexo#1788]
hexo version 3.2.0

when config.root = "/a/b/c/";

then url_for("/archives") ==> "/a/b/c/archives"

it is supposed to be 

url_for("/archives") ==> "/archives"
url_for("archives") ==> "/a/b/c/archives"

**just my opinion, url_for may act differently.**

> https://developer.mozilla.org/en-US/Learn/Understanding_URLs
# 

I write some test [here](https://github.com/samwhelp/hexo-test-url_for).
- [url_for.js](https://github.com/samwhelp/hexo-test-url_for/blob/master/url_for.js) <=> fix version
- url_for.3.2.0.js <=> [hexo 3.2.0](https://github.com/hexojs/hexo/blob/3.2.0/lib/plugins/helper/url_for.js)

**Comment by leesei** [comment]
Results here:
https://gist.github.com/leesei/2eff3a6d899f76dbf2e6

I don't agree on the case url_for("/archives") ==> "/archives", I think the current behavior is correct.
But your test did show some edge case for `url_for()`.

**Comment by ppoffice** [comment]
@samwhelp +1
