### ISSUE TITLE
Why the hexo style for blockquote is not compatible with others markdown styles

### ISSUE THREAD

**Issue by anticpp** [hexojs/hexo#1789]
Blockquotes should be like this:

> This is 
> blockquotes

But in hexo style, it comes to be center aligned.

**Comment by anticpp** [comment]
# like this

![tmp3c5ef44a](https://cloud.githubusercontent.com/assets/5907797/13421018/1a920c0a-dfc6-11e5-9014-e6d3991bee56.png)

**Comment by leesei** [comment]
This is controlled by the theme.
You can use another theme or change its style.
