### ISSUE TITLE
有什么办法可以便捷的在多个主题间切换吗？

### ISSUE THREAD

**Issue by ge-ce** [hexojs/hexo#1790]
如题。难道只能一个主题就在github上面建一个仓库吗，这样自己写的博文就得复制好几份，能不能多个主题共享博客内容，通过链接等一键切换过去？

**Comment by leesei** [comment]
1. the page is generated with the theme
2. `source/` + `theme/` => `public/` (=> is `hexo g`)
3. you can do  
  `source/` + `theme/1` => `public1/`  
  `source/` + `theme/2` => `public2/`

**Comment by ge-ce** [comment]
什么意思，这个在哪里改？

**Comment by leesei** [comment]
意思是你多放兩個theme 到`theme/`, 改`_config.yml`再generate
這是否共享博客内容?

**Comment by ShinoharaYuri** [comment]
嗯… 其实可以考虑多repository
比如 1 2 3 4
这样访问的时候就是
用户名.github.io/1/
用户名.github.io/2/
用户名.github.io/3/
用户名.github.io/4/
切换的话还是直接普通链接切换

**Comment by ge-ce** [comment]
@leesei 
我知道这样，但是这样每次generate都会覆盖掉吧，而且deploy之前都要把git url改一下。。。

**Comment by ge-ce** [comment]
@ShinoharaYuri 
我就是这个意思的，问题是每个 repository 在本地都要一个文件夹，每写一篇文章都要在每个文件夹中复制一份，并且分别 deploy。。。

**Comment by leesei** [comment]
@ge-ce 你的use case 是比較獨特的, 應該不會放到hexo core

你可以`source` 一個repo, `source`以外+每個theme n 個repo
用symlink link `source`到該n 個repo 再跑n次generate, n次deploy
可以寫script 把n次generate, n次deploy 自動化

**Comment by ge-ce** [comment]
好吧，似乎并没有比较简单的方法。。

**Comment by ShinoharaYuri** [comment]
軟鏈接呢？

**Comment by Haocen** [comment]
@ge-ce 自己写个脚本定时同步 _source 文件夹不就完事了。

**Comment by Haocen** [comment]
@ge-ce 各位朋友， Hexo 是一个静态博客系统，有很多自身的限制，如果你们需要诸如一键切换主题，按来访者浏览器语言显示博客界面等功能，请考虑如 WordPress 之类的博客系统。
