### ISSUE TITLE
Precompiled renderer will not trigger `after_render` filter

### ISSUE THREAD

**Issue by akfish** [hexojs/hexo#1791]
Precompilation bypasses `render.render` method:
https://github.com/hexojs/hexo/blob/master/lib/theme/view.js#L106
Which executes `after_render` filter:
https://github.com/hexojs/hexo/blob/master/lib/hexo/render.js#L69

This will cause inconsistent results for plugins that consume `after_render` filter.

**Comment by leesei** [comment]
Since the file has not changed, there's no need to render.
Isn't the modifications committed to the rendered HTML?

**Comment by akfish** [comment]
A plugin could modify rendered results from `after_render` filter. With current precompilation workflow, `after_render` will never be called. This means the *expected modifications* will never happen.
