### ISSUE TITLE
Code parsing converts space into `true`

### ISSUE THREAD

**Issue by bxshi** [hexojs/hexo#1798]
The problem occurred when I created a `Python` code snippet, an example document is 

```
title: test
date: 2016-03-01 18:18:59
tags:
---

{% codeblock lang:python %}
def func(abc):
	return abc + 1
{% endcodeblock %}
```

This page will be rendered into 

```
1 def func(abc):
2 truereturn abc + 1
```

which apparently outputs `true` instead of space. Would you mind give me a hint that which part will probably cause this problem? Thanks!

**Comment by leesei** [comment]
Cannot reproduce.
Try changing theme and post your highlight config.
