### ISSUE TITLE
hexo deploy 执行无反应

### ISSUE THREAD

**Issue by akreturn** [hexojs/hexo#1799]
ssh 配置
![image](https://cloud.githubusercontent.com/assets/11769007/13449423/55c291fa-e066-11e5-9ee7-06c2623f3a49.png)
配置文件
![image](https://cloud.githubusercontent.com/assets/11769007/13449439/6c4b0c04-e066-11e5-9992-32cc55bbd7a0.png)

插件也全都安装了
![image](https://cloud.githubusercontent.com/assets/11769007/13449450/86235384-e066-11e5-9c10-9d7d81eea7db.png)

但执行hexo deploy依然没有反应
![image](https://cloud.githubusercontent.com/assets/11769007/13449458/962051b0-e066-11e5-9609-d65b967bf360.png)

请问该怎么解决，只能删掉重头再来？

**Comment by akreturn** [comment]
问题已经解决，不是空格，不是ssh ，不是部署插件没装（当然不装就可能真有问题了），当我发现问题的时候，我惊到了，下巴都掉地上了。那么解决方法是
 之前我打开gitbash 是通过 桌面的快捷方式打开的。如果更换到 你的hexo 目录下面，在右键githbas 执行 hexo deploy 居然可以了

**Comment by pangjian** [comment]
I have the same problem.

**Comment by akreturn** [comment]
@pangjian  Then you solve it?

**Comment by Xuanwo** [comment]
所以- -，安装git的时候请选择添加到path

**Comment by pangjian** [comment]
@akreturn No,I have update hexo to 3.2, then another problem appears.

**Comment by Xuanwo** [comment]
Closed for invaild.
