### ISSUE TITLE
After Updated v 3.2.0,  it came across some errors

### ISSUE THREAD

**Issue by ShomyLiu** [hexojs/hexo#1800]
Yesteday I updated hexo using `npm update`. However, when I  run `hexo d`, it shows:
```
ERROR Deployer not found: git
```
.
Besides, when I run `hexo s` or `hexo server` , It doesn't work at all.

**Comment by youxiachai** [comment]
you should
```
npm install hexo-deployer-git --save
```

**Comment by akreturn** [comment]
@youxiachai  
![image](https://cloud.githubusercontent.com/assets/11769007/13449630/64ca2bd4-e068-11e5-8fbf-1f5db29ed790.png)  what's wrong?

**Comment by youxiachai** [comment]
@akreturn  windows use cywin? already install git command ?

why not use native windows node?

**Comment by akreturn** [comment]
@youxiachai  i used gitbash

**Comment by akreturn** [comment]
@youxiachai   is already successful

**Comment by ShomyLiu** [comment]
@youxiachai  I have already run the command
```
npm install hexo-deployer-git --save
``` 
and it has been installed well. But it doesn't work. When I switch a blogfile of `hexo v3.1.1`，It is ok

**Comment by leesei** [comment]
@ShomyLiu please close issue if you fixed it

**Comment by ShomyLiu** [comment]
@leesei  Sorry, It doesnot work well. So I plan to use the `3.1.1`  again  temporarily.
