### ISSUE TITLE
npm install -g hexo  error

### ISSUE THREAD

**Issue by kinky2015** [hexojs/hexo#1801]
when hexo installed ,this happen to ** "_npm WARN optional Skipping failed optional dependency /chokidar/fsevents:npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.8**_". why ? how to  solve?

**Comment by youxiachai** [comment]
you should use
```
npm install -g hexo-cli
```

**Comment by kinky2015** [comment]
![qq 20160302112612](https://cloud.githubusercontent.com/assets/16065394/13449780/b04ebd30-e069-11e5-982d-8baffcb0ed9a.png)

**Comment by youxiachai** [comment]
fsevents ? 

you can see

https://github.com/hexojs/hexo/issues/1219

It's just a warning. It doesn't matter.!

**Comment by kinky2015** [comment]
@youxiachai   

 thanks!
