### ISSUE TITLE
How to set jsfiddle size ?

### ISSUE THREAD

**Issue by iPonyo** [hexojs/hexo#1814]
HI ! I want to set jsfiddle size, but it did't work. Please help me ! Thanks ! Hexo version 3.1.1.
{% jsfiddle ccWP7 100 600 %}

**Comment by leesei** [comment]
https://hexo.io/docs/tag-plugins.html#jsFiddle

You need to specify skin in the third position. 
The syntax should be:
```
{% jsfiddle shorttag [tabs [skin [width [height]]]] %}
```

**Comment by iPonyo** [comment]
Yes ! It works ! Thanks !
