### ISSUE TITLE
Facebook instant article support

### ISSUE THREAD

**Issue by iamchathu** [hexojs/hexo#1816]
https://developers.facebook.com/docs/instant-articles 

Is there any plan for this?

**Comment by geniusgordon** [comment]
+1

**Comment by geniustanley** [comment]
+1

**Comment by yubinbai** [comment]
<3

**Comment by mkozhukharenko** [comment]
+1

**Comment by stevenjoezhang** [comment]
Is it a feature request of hexo-generator-feed
https://developers.facebook.com/docs/instant-articles/publishing/setup-rss-feed

https://github.com/onlinemad/hexo-generator-fbia
