### ISSUE TITLE
hexo s的访问地址

### ISSUE THREAD

**Issue by tiexo** [hexojs/hexo#1817]
这个问题一度困扰我很长时间....
以前运行hexo s后，按照提示访问0.0.0.0:4000就可以预览

某天突然变成：您访问的网页出错了
各种重装都试过无效就放弃了。。。

前几天，偶然尝试用localhost:4000竟然可以访问了。。。
可是面板上依然显示的是0.0.0.0:4000，并且这个地址是不能访问的

![qq 20160308141750](https://cloud.githubusercontent.com/assets/8164505/13593802/9fbe70f8-e539-11e5-9377-88b94db3575f.jpg)

这是什么原因？

**Comment by Xuanwo** [comment]
给你参考： http://www.cnblogs.com/hnrainll/archive/2011/10/13/2210101.html

所以127.0.0.1和localhost都是可以的。

**Comment by mpc2008cn** [comment]
你ping 0.0.0.0应该是失败的，ping localhost没问题吧。。我也这样，一般都用localhost，我ping
127.0.0.1都是失败的，因为自己的工作机开启了wifi共享😂

**Comment by leesei** [comment]
Update hexo-server to 2.0 and it will display "0.0.0.0" as "localhost"
https://github.com/hexojs/hexo-server/commit/4103a759e406ed4d9cda123ae6afe8a77f8f9432
