### ISSUE TITLE
hexo not support flow chart?

### ISSUE THREAD

**Issue by apophise** [hexojs/hexo#1819]
like this :+1: 

```flow
st=>start: Malloc
e=>end: End
op1=>operation: 123
cond=>condition: 321
cond1=>condition: 123
cond2=>condition: 321
op2=>operation: 333
op3=>operation: 22
op4=>operation: 11

st->cond
cond(yes)->cond1
cond(no)->op1->cond1
cond1(yes)->op2
cond1(no)->cond2
cond2(yes)->op4->e
cond2(no)->op3->e
op2->e
```

hexo thought it is a code maintain, not flow chart！

so  hexo is not support  flow chart?

**Comment by morris821028** [comment]
I think that you can implement custom tag to do that.

* https://github.com/akfish/hexo-diagram
* https://github.com/oohcoder/hexo-tag-plantuml
