### ISSUE TITLE
Sugest for scss and sass renderer

### ISSUE THREAD

**Issue by shark-oxi** [hexojs/hexo#1820]
Hello,

I'm not sure but if I don't say a mistake there is no official Hexo plugin for render sass and scss.
But there is some unofficial plugin for : 
+ sass : [npm](https://www.npmjs.com/package/hexo-renderer-sass), [github](https://github.com/knksmith57/hexo-renderer-sass)
+ scss : [npm](https://www.npmjs.com/package/hexo-renderer-scss), [github](https://github.com/o2team/hexo-renderer-scss)

So what about : 
+ officialy forking them in a next version
+ talk about them on official hexo doc
+ create an official hexo wiki about fan plugin
+ just add them to the [plugin](https://hexo.io/plugins) page

You're doing a nice job ;)

**Comment by leesei** [comment]
The way to do is to submit a PR to https://github.com/hexojs/site/blob/master/source/_data/plugins.yml

https://hexo.io/docs/contributing.html#Updating-Documentation

**Comment by shark-oxi** [comment]
Thanks,

I made a pull request
