### ISSUE TITLE
When the Url end with "*.conf", the page will be  wrong!

### ISSUE THREAD

**Issue by fairyeye** [hexojs/hexo#1822]
> http://fairyeye.github.io
> http://fairyeye.github.io/2015/11/19/2015-11-19-where-is-my-vsftpd.conf?

I guess the string about "*.conf" is a keyword，so the page will be wrong like this to output html code.

Have anyone can tell me how to solve it except modify my url ? Thanks.

**Comment by leesei** [comment]
Try adding this to `_config.yml`:
```yaml
skip_render:
- *.conf
```

**Comment by fairyeye** [comment]
So,except rename my post title,haven't any other ways to solve it?

**Comment by gboudreau** [comment]
You can keep your current URL by hard-coding the permalink in the post' front-matter.
So rename the file as suggested by @leesei, then add this in the post' front-matter:

    permalink: 2015/11/19/2015-11-19-where-is-my-vsftpd.conf

**Comment by leesei** [comment]
@gboudreau Thanks for the tip.

**Comment by fairyeye** [comment]
@gboudreau  I get it. Thanks.
