### ISSUE TITLE
deploy到github的问题

### ISSUE THREAD

**Issue by Zohner** [hexojs/hexo#1825]
配置里只写了git的res地址，执行deploy时是用什么用户名和密码呢，我发布报错了，看说明是用户名对应错了，因为我有两个github帐号，不知道本机默认的帐号信息保存在哪，怎么修改

**Comment by tiexo** [comment]
#配置使用git仓库的人员姓名  
git config --global user.name "Your Name Comes Here"  
  
#配置使用git仓库的人员email  
git config --global user.email you@yourdomain.example.com

**Comment by Zohner** [comment]
@tiexo 不用密码？

**Comment by Haocen** [comment]
@Zohner 如果你配置了没有密码锁住密钥对，就可以不用密码。
如果不清楚怎么弄，请去看 git 相关的使用手册：
> https://git-scm.com/docs/git-push
这和 hexo 以及 next 主题没有关系。

**Comment by leesei** [comment]
Deploy只是調用了`git push`, 請參考github 配置教學
https://help.github.com/articles/set-up-git/

**Comment by Zohner** [comment]
@leesei 那可以用SSH么

**Comment by Haocen** [comment]
@leesei 链接里有关 git push 的部分讲得很清楚了。为什么不愿意看一下？

**Comment by Zohner** [comment]
@Haocen 好的，谢谢
