### ISSUE TITLE
ignore files in source folder

### ISSUE THREAD

**Issue by imasood** [hexojs/hexo#1826]
hi, when i generate my hexo i want ignore some folders in source folder.
is there any way for ignore that folder?
thanks

**Comment by gboudreau** [comment]
In `_config.yml`:

This will copy those into public, but will not try to parse them (they will be copied as-is):
```yml
skip_render:
  - assets/**
  - mywot8dec18d4bc2a02af24a5.html
```

This will not copy the specified files/folders into public:
```yml
exclude:
  - tmp/**/*
 ```

**Comment by imasood** [comment]
doesn't work.
which config file?
config in hexo root? or in my theme folder?

**Comment by gboudreau** [comment]
In Hexo root.
Make sure you run `hexo clean` when you excludes new files; `hexo generate` doesn't remove excluded files from the `public` folder.

**Comment by imasood** [comment]
yeah, i run `hexo clean` and after `hexo generate`, but not work.
i have a `lib` folder in source folder my theme and i wrote bottom code for excluding. is that correct?
```
exclude:
 - lib
```

**Comment by gboudreau** [comment]
You need to specify:

    exclude:
      - lib/**

**Comment by imasood** [comment]
not work.
there isn't any `exclude` option in configuration of documentation.
are you sure?

**Comment by gboudreau** [comment]
https://hexo.io/news/2016/02/28/hexo-3-2-released/#Include-exclude-source-files

**Comment by gboudreau** [comment]
Oh, I just noticed you you're trying to exclude a folder in your theme folder, not your source folder (the site content). Not sure the exclude config option applies to that.

**Comment by imasood** [comment]
yeah. this option is strange and there isn't good document for that.
i can move lib folder to parent folder for excluding.
thanks for your helping
