### ISSUE TITLE
hexo deploy到git问题

### ISSUE THREAD

**Issue by wuchangfeng** [hexojs/hexo#1830]
本地编辑完成文章，hexo g，hexo d，明明编辑了内容，但是却显示没有更新内容，deploy出去自然页面刷新也不能看到最新的文章。个人发现，文章只要是复制的，就发布出去。为什么呢？

**Comment by Xuanwo** [comment]
不是很懂你的意思

**Comment by wuchangfeng** [comment]
@Xuanwo 就是不能发表文章。我发现大量从别的文章复制过来，然后hexo g，hexo d，发不出去。后来检查了一下，应该是MD语法的原因。

**Comment by Xuanwo** [comment]
Closed for sloved.
