### ISSUE TITLE
hexo默认的hello-world文章比我自定义生成的第一篇文章日期更晚的问题

### ISSUE THREAD

**Issue by xiaowen8916** [hexojs/hexo#1834]
搭好hexo各项环境，发一篇first-post.md，生成并部署到：
http://shiqiwen.com
后发现hello-world文章居然比我后来发的first-post文章日期更晚？？？！！！
是配置还是哪出了问题，求教！
项目发布源文件：
https://github.com/xiaowen8916/xiaowen8916.github.io/tree/develop

**Comment by tiexo** [comment]
文章时间是以hexo n的时候为准的，而不是hexo d
至于为什么会出现这种现象，是因为你的hello world没有定义时间吗？
![20160314214352](https://cloud.githubusercontent.com/assets/8164505/13746394/428d275e-ea2e-11e5-8e4c-c1e461fa971b.jpg)
你给它添加一个比first post早的时间应该就行了吧
![qq 20160314214138](https://cloud.githubusercontent.com/assets/8164505/13746364/100c68ee-ea2e-11e5-9221-68af57fd6b10.jpg)

**Comment by Xuanwo** [comment]
Hello world默认没有添加date属性，所以文章时间就是生成时间。
