### ISSUE TITLE
运行npm install -g hexo-cli 失败

### ISSUE THREAD

**Issue by franktianyirenjian** [hexojs/hexo#1836]
一、我的理解是安装了Xcode就等于安装了Git,如果不是请指正；
因此我直接下载安装的node.js；
然后打开终端输入：npm install -g hero-cli。
出现以下两个警告：
＃警告一：npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/hexo-cli

警告二： nam WARN checkPermissions Missing write access to /usr/local/lib/node_modules

并且其中一个错误提示到：npm ERR! Please try running this command again as root/Administrator.

二、**好吧，那我用sudo试试；**
加上sudo结果如下：
 sudo npm install  -g hexo-cli
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
/usr/local/lib
└── hexo-cli@1.0.1 
官方文档也没告诉我们npm成功会出现什么画面呢？
好吧，那不管成没成反正警告和错误提示消失啦，
那就准备下一步吧；
三、输入：hero init；
又是两个警告：
INFO  Cloning hexo-starter to ~/
fatal: destination path '/Users/chenbaichuan' already exists and is not an empty directory.
WARN  git clone failed. Copying data instead
WARN  Failed to install dependencies. Please run 'npm install' manually!
我生怕是我偷懒造成的，所以就回去按着官方文档：
我用xcode－select--install下载了：command line tools（这个和终端什么区别，我傻傻分不清楚，不过还是下载了）。
我安装了Homebrew，Homebrew安装成功后，我运行：brew install git，安装了git；
然后我又试了试nvm安装node.js，可惜没反应。
只好作罢，这些做完后，反过来再用：sudo npm install  -g hero-cli试试，
结果还是和原来一样。
请帮我分析下，我错在了哪里？

**Comment by amobiz** [comment]
這是因為 hexo 需要全域安裝，而 npm 的預設安裝卻是位於需要管理者權限的目錄下。
建議可以參考 npm 官方的說明，將 npm 安裝全域工具的目錄，更改到個人目錄下：

[Fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory)

**Comment by Xuanwo** [comment]
用sudo安装并没有问题，关键是这个：
```
fatal: destination path '/Users/chenbaichuan' already exists and is not an empty directory.
```

你需要在一个空文件夹中执行`hexo init`，然后再`npm install`即可。

**Comment by franktianyirenjian** [comment]
非常感谢，问题都已经解决了。
```python
并且已经分享解决过程：franktianyirenjian.github.io
```

**Comment by wuzhentao** [comment]
怎么解决的？

**Comment by franktianyirenjian** [comment]
加sudo

wuzhentao <notifications@github.com>编写：

**Comment by xjswift** [comment]
怎么解决求教

**Comment by hizoubin** [comment]
建议不要用sudo 这是权限问题，推荐npm官方的解决方案https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by yusmile** [comment]
@franktianyirenjian 请问你是在什么操作系统下使用sudo的？
