### ISSUE TITLE
hexo文章置顶

### ISSUE THREAD

**Issue by wuchangfeng** [hexojs/hexo#1838]
hexo怎么将文章置顶,跟随选主题有关系吗？

**Comment by Xuanwo** [comment]
Hexo没有内置这个功能，需要主题支持

**Comment by wuchangfeng** [comment]
@Xuanwo 十分感谢

**Comment by wuchangfeng** [comment]
@Xuanwo 我看您的博客风格挺漂亮的，自定义了next主题吗？请问改动的是哪些呢？

**Comment by Xuanwo** [comment]
@wuchangfeng 改动比较多- -，我也不太记得了，你可以参考： https://github.com/Xuanwo/xuanwo.github.io/tree/blog/themes/next

**Comment by Xuanwo** [comment]
@wuchangfeng 改动比较多- -，我也不太记得了，你可以参考： https://github.com/Xuanwo/xuanwo.github.io/tree/blog/themes/next

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
