### ISSUE TITLE
why server command unrecognizable

### ISSUE THREAD

**Issue by edagarli** [hexojs/hexo#1839]
justhacker:edagarli.github.io justhacker$ hexo server

Usage: hexo <command>

Commands:

clean Removed generated files and cache.

config Get or set configurations.

deploy Deploy your website.

generate Generate static files.

help Get help on a command.

init Create a new Hexo folder.

list List the information of the site

migrate Migrate your site from other system to Hexo.

new Create a new post.

publish Moves a draft post from _drafts to _posts folder.

render Render files with renderer plugins.

version Display version information.

Global Options:

--config Specify config file instead of using _config.yml

--cwd Specify the CWD

--debug Display all verbose messages in the terminal

--draft Display draft posts

--safe Disable all plugins and scripts

--silent Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information

or you can check the docs: http://hexo.io/docs/

**Comment by greg-js** [comment]
Are you sure you created a hexo blog first (using `hexo init`) and ran `npm install`? Also, you must run the `hexo server` command in a blog's directory (the one that has the `package.json` and `_config.yml`) or a subdirectory thereof.

**Comment by jimthedev** [comment]
I was also having this problem with an old hexo blog. Seems like re-initing and copying things over fixed it. Guessing it was a migration issue.

**Comment by leesei** [comment]
Please open new issue if the problem persists.
