### ISSUE TITLE
Hexo installed - In the frontend I only see Index from CMS and nothing else - where does the

### ISSUE THREAD

**Issue by AlexL777** [hexojs/hexo#1842]
Hello Developers,

something I'm completely wrong. I Hexo installed on Centos server and PHP 5.4. In the frontend under http://projekte.alexl.eu/cms/hexo I only see the index of this CMS and provide directories and files.

But such appears to me the template. Or do I have to install something. It is not clear how Node.js should be displayed in the browser. Can you please do all you time and help me.

Thanks in advance.

**Comment by morris821028** [comment]
After executing `hexo generate`, static html files will produce in `/blog/public/`. Then, you can get `http://projekte.alexl.eu/cms/hexo/public` as your blog home page.

I think that you only use `hexo server` to blog post content.

https://hexo.io/docs/generating.html

**Comment by AlexL777** [comment]
One question I have and that CSS does not load as you can see below http://projekte.alexl.eu/cms/hexo/public. Do I need something or why is it that way.

**Comment by morris821028** [comment]
In `/blog/_config.yml`

```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://projekte.alexl.eu/
root: /cms/hexo/public/
```

**Comment by AlexL777** [comment]
Thank you, great, it worked! 

Must fear that appears to me under **/cms/hexo** the index of files and directories in the browser.

Will there be any safety problems?

**Comment by andre-pt** [comment]
the "deployable" part of the project is only the content of the `public` directory.

In other words, you should copy only the content of the `public` directory to your webserver

**Comment by AlexL777** [comment]
Thanks for your answer. I can understand that. Now it has worked for me. I have a little expanded the menu and added new pages. 

I also put a Bootstrap Theme. There's really many of them. I like that.

Yet I would like to integrate Disqus comments and have to look like that is to make. Whether it is at all possible with Disqus ??!

**Comment by leesei** [comment]
Many theme have Disqus support, e.g. codeland, freemind.
