### ISSUE TITLE
How to require a module in theme?

### ISSUE THREAD

**Issue by sabrinaluo** [hexojs/hexo#1843]
Hi,
I'm trying to use some external util modules when develop the hexo-theme, I wonder if it is possible to require some other modules and how? Thanks in advance. :)

**Comment by leesei** [comment]
Put in `source/`, see https://github.com/hexojs/hexo-theme-landscape/source

If you only use the external module for development, use npm devDependencies.

**Comment by leesei** [comment]
@sabrinaluo edited
