### ISSUE TITLE
Does the directory /public rights apache:apache or root:root have - I do not understand

### ISSUE THREAD

**Issue by AlexL777** [hexojs/hexo#1845]
Hello Developers,

I'm still a Linux newbie and have a question. Does the directory **/public** and its contents the rights **apache:apache** or **root:root** have?

I have everything to root:root, what I can see in Filezilla. If I'm going down http://projekte.alexl.eu/cms/hexo/public/tags in frontend, again I see only the index with the tags. It should be different.

How can I fix it?

Thanks in advance.

**Comment by leesei** [comment]
The tag index page requires theme support.

**Comment by leesei** [comment]
Please open new issue if the problem persists.
