### ISSUE TITLE
ERROR Deployer not found: git when using hexo-generator-sitemap

### ISSUE THREAD

**Issue by panlei7** [hexojs/hexo#1848]
如果我使用sitemap，其中需要在站点配置文件中添加：
```
plugins:
- hexo-generator-sitemap
```
然后执行
```
hexo deploy
```
出现
```
ERROR Deployer not found: git
```

如果我把它注释掉，就没有问题，这是怎么回事？
```
#plugins:
#- hexo-generator-sitemap
```

**Comment by Xuanwo** [comment]
你已经安装好`hexo-deployer-git`了么？

**Comment by panlei7** [comment]
已经安装好`hexo-deployer-git`，如果没有在站点配置文件添加hexo-generator-sitemap时是完全没问题的

**Comment by WangXiZhu** [comment]
我也发现在_config.yml中添加plugins下面，添加关于hexo的有问题

**Comment by jingxinxin** [comment]
同样遇到这样的问题 貌似和 字符 - 有关系

**Comment by leesei** [comment]
Validate YAML with [Online YAML Parser](http://yaml-online-parser.appspot.com/)

**Comment by panlei7** [comment]
@leesei 什么意思？

**Comment by panlei7** [comment]
我知道了，原来根本不用添加这个语句，直接写
sitemap:
  path: sitemap.xml
就可以了。网上很多教程误导了我。

**Comment by kkc** [comment]
最近也採中這個雷，如果去定義 plugins ，就必須把所有使用到的 plugin 加進去

**Comment by leesei** [comment]
You either *DO NOT* define `plugins` and let Hexo search for them or define *ALL* the plugins you used.

**Comment by kkc** [comment]
@leesei sorry, where can I find this statement at document? I thought that is important for users.

**Comment by leesei** [comment]
Mmm, it is not in the docs. Let's open a ticket to track it.

**Comment by kkc** [comment]
@leesei thanks a lot! 👍
