### ISSUE TITLE
Can't deloyment, 

### ISSUE THREAD

**Issue by Gavin-Gong** [hexojs/hexo#1849]
I type `hexo d` in git , then show some errors. 
``` 
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\node_modules\hexo-cli\bin\hexo'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by WangXiZhu** [comment]
npm update

**Comment by Gavin-Gong** [comment]
@WangXiZhu Thx for your answer, but don't work.

**Comment by Gavin-Gong** [comment]
solved it

**Comment by wuyuehua** [comment]
@Gavin-Gong 请问你是怎么解决的？我也遇到了这个问题。

**Comment by Gavin-Gong** [comment]
@wuyuehua Sorry 没太注意过程, 所以我也不是很清楚, 你可以试试在目标文件夹Git Bash Here 再安装所需的东西, 如果用Node的命名行窗口安装的话,路径和Git Bash安装的可能有点不一样.

**Comment by weaming** [comment]
```
如果用Node的命名行窗口安装的话,路径和Git Bash安装的可能有点不一样.
```
用cmd就好了。。。我擦，Git bash 设置了什么奇怪的环境变量？？

**Comment by helloqingfeng** [comment]
我是把这个文件夹（node_modules\hexo-cli）给复制到git安装目录下之后就好了
![360 20170225011336132](https://cloud.githubusercontent.com/assets/9712785/23313437/b06030f6-faf8-11e6-8200-1e48c8ab267b.jpg)
