### ISSUE TITLE
Hexo deploy doesn't work.

### ISSUE THREAD

**Issue by muwan** [hexojs/hexo#1851]
我重新安装了hexo，然后把原来备份的_config.yml、source、themes覆盖在现在的文件夹，并且重新添加了ssh key，deploy的时候出错。
代码如下：

```
error: open(".viminfo"): Permission denied
error: unable to index file .viminfo
fatal: adding files failed
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
```

**Comment by Xuanwo** [comment]
Please skip the `.viminfo`

**Comment by leesei** [comment]
Where is the `.viminfo` causing the error?

**Comment by hebaoying** [comment]
I encountered almost the same issue: 
hexo generate and hexo server runs well, but cannot succeed in hexo deploy. i got this:

error: open(".lesshst"): Permission denied
error: unable to index file .lesshst
fatal: adding files failed

i try to skip the .lesshst file by `touch. lesshst `, but does not help. BTW, there's no file called .lesshst.

**Comment by hebaoying** [comment]
Here's the version number;

hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 16.1.0 darwin x64
http_parser: 2.5.2
node: 4.4.5

v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

**Comment by NoahDragon** [comment]
@hebaoying 在Hexo的config里面添加 

```yml
exclude:
    - .lesshst
```
