### ISSUE TITLE
I have the following issue on OS X 10.11.4, how to fix it?Thanks~

### ISSUE THREAD

**Issue by 24suixinsuoyu** [hexojs/hexo#1852]
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
hexo-cli: 1.0.1
os: Darwin 15.4.0 darwin x64
http_parser: 2.5.2
node: 4.4.1
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g

**Comment by yugai** [comment]
me  too

**Comment by yugai** [comment]
被这个问题 困扰了好多天了。  希望能够解决一下。  是不是Mac上才有这个问题的？

**Comment by 24suixinsuoyu** [comment]
不是，还是安装的问题。你试试先卸载再重新安装，安装的时候注意命令要全面一些，加上sudo, --no-optional之类的再试试

**Comment by yugai** [comment]
谢谢。  按照你说的 重装方法。 成功了。  但是我还是很奇怪， 为什么我重装就能修复呢。  我安装的不流程没有问题啊。  这是不是bug

**Comment by 24suixinsuoyu** [comment]
我也不太清楚，可能是第一次装的时候个别组件没装上吧

**Comment by normalhh** [comment]
@24suixinsuoyu thx, I uninstalled hexo, then I run "sudo npm install hexo --no-optional -g", it works!

**Comment by 24suixinsuoyu** [comment]
yes, it refers to the system-permissions.
