### ISSUE TITLE
一个很奇怪的路径问题

### ISSUE THREAD

**Issue by jingxinxin** [hexojs/hexo#1853]
> url: http://51201314.me/jacks
root: /jacks/
permalink: :lang/:year/:month/:day/:title/
permalink_defaults:

我的站点配置是子目录， 结果在配置avatar: /images/avatar.png 和配置多说分享duoshuo_share: true
点击分享后的超链接  
和通过hexo-asset-image应用

！ 【】 （index/*****.jpg）  
图片引用的超链接地址  
均会出现  http://51201314.me/jacks/jacks/************             两个jacks的现象，导致引用出错

把多说去掉改成 jiathis: true 超链接会正确，但是 分享引用的文字是乱码~~~
我试着查看了page.permalink的值  也是有两个jacks，想问问这个值是怎么拼接的，有解决的方法吗，谢谢了

另外多说热门评论，出现两个一样的，一个超链接正确，一个超链接不正确 两个jacks~~~~求大神伸只手~~

**Comment by Xuanwo** [comment]
你的Hexo版本是？

**Comment by jingxinxin** [comment]
hexo: 3.2.0

hexo-cli: 1.0.1

**Comment by jingxinxin** [comment]
@Xuanwo url拼接的相对路径是在什么地方，应该是拼接的原因，现在多说分享，一直有问题~能帮忙分析一下么

**Comment by Xuanwo** [comment]
不懂多说

**Comment by jingxinxin** [comment]
@Xuanwo 我已经自己解决了，问题可以关闭了
