### ISSUE TITLE
Ignore dot file/folder in "layout/*"

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1855]
It seems Hexo 3.2 breaks [ignoring files](https://hexo.io/docs/themes.html), causing
`TypeError: Cannot read property 'compile' of undefined`.
See #1807, #1793 and many others.

> **source**
> Source folder. Place your assets (e.g. CSS and JavaScript files) here. Hexo ignores hidden files and files or folders prefixed with _ (underscore).
1. ignoring files are processed and causes error  
   
   ``` sh
   touch themes/landscape/layout/.DS_Store  
   touch themes/landscape/layout/.gitkeep
   ```
2. ignoring files in source with `layout/` in path get processed #1793
   since it matched the pattern in `hexo/lib/theme/processors/view.js`
   (I tried to fix but failed)
   
   ``` sh
   touch themes/landscape/source/_css/layout/_sidebar.scss
   ```

---

**Workaround 1**: don't name any folder `layout` in theme (need code change)
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/224#issuecomment-219365465

**Workaround 2**: downgrade to 3.1.1 :cry: 
https://github.com/hexojs/hexo/issues/1793#issuecomment-213907822

**Comment by buildAll** [comment]
I deleted all the .DS_Store files in my hexo project folder but I still got the same 'compile'  issue.

The "hexo generate" command works after I switch to the version 3.1.1 of Hexo.

**Comment by w0rd-driven** [comment]
To reproduce the problem, you need a .DS_Store file in the theme's layout folder (layout/.DS_Store), or at least that's how I was able to reproduce it in the theme I use.

In line 98 of `hexo/lib/theme/view.js`, `var renderer = render.getRenderer(pathFn.extname(this.path));` tries to get the renderer for .DS_Store, as DS_Store is the file extension, and `renderer` returns as undefined.

One way to stop it would be to check `typeof renderer !== 'undefined'` but another would be to stop dot files or other ignores from even being processed upstream.

**Comment by leesei** [comment]
#1851 `.viminfo` also cause error during deploy

**Comment by leesei** [comment]
#1850 `.gitkeep` also cause compile error

**Comment by AlexKasaku** [comment]
This also appears to occur if there is a folder named "layout" within the theme, besides the standard layout folder. I have a theme with a layout folder within assets, which was causing `*.scss` files to get picked up and then create this error.

**Comment by leesei** [comment]
#1793 files with `_` prefix

**Comment by Xuanwo** [comment]
And in Mac OS X, it's a big problem that Mac OS X will create `.DS_store` in floders.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo/pull/1910
