### ISSUE TITLE
hexo是否支持博客内容搜索？

### ISSUE THREAD

**Issue by escarp** [hexojs/hexo#1861]
比如我写了很多文章，是否支持关键字搜索本博客内的文章？我现在的博客是iteye，用了很多年了，但是现在这网站官方貌似不准备维护了，不少bug官方一直不修，受不了所以准备用hexo建个个人博客，但是不知道hexo以后能否实我想要的功能：
1，站内搜索
2，代码高亮
3，批量上传图片
4，图片自动添加水印（最好能自定义）
5，后台能导出pdf或其他格式的文件
6，支持附加流量统计的配置，比如友盟统计，百度统计（我最喜欢的雅虎统计下个月就要被阿里巴巴关闭了。。）

**Comment by Xuanwo** [comment]
Hexo是一个静态博客，所有的动态功能都需要第三方实现。

**Comment by escarp** [comment]
不知hexo的开发者们能否考虑在以后的开发中加入这些动态功能，如果博客文章少还好说，但是像我这样把所有笔记都写在博客上的用户，非常需求这样的功能。wordpress感觉有点臃肿，是想体验下node.js的便捷与速度。

**Comment by youxiachai** [comment]
@escarp 你可以用搜索的站内搜索功能啊.....

再说了..一个静态生成博客器..怎么加你说得动态功能啊....顶多自己定制一些js Widgets

**Comment by tiexo** [comment]
1、2、6都有主题自带
剩下的345就木有了

**Comment by escarp** [comment]
@youxiachai 好的，多谢建议

**Comment by escarp** [comment]
@tiexo 好的，多谢
