### ISSUE TITLE
Files have too long paths to be copy to other folder.

### ISSUE THREAD

**Issue by obserthinker** [hexojs/hexo#1862]
Hexo it easy to use and I like it. But there is a little feature might be added to it. Once a site is initialized, it cannot be moved as there would be a prompt tell me that some files have too long paths to move. 
Besides, I use Onedrive, and even I initialize a site under the root of Onedrive folder, the Onedrive will exit for the same reason. If there a way to solve this problem?

**Comment by leesei** [comment]
1. I DO think it can be move to somewhere where the path is not too long. This is a problem of NTFS, the file system Windows is using.
2. What Hexo generates should be files with safe file name. Did you use `hexo new` for new post? It seems to be an issue of Onedrive.
