### ISSUE TITLE
Hexo deploy: source.replace not function error

### ISSUE THREAD

**Issue by carolynyoo** [hexojs/hexo#1863]
Hi, having the same issue as #1810 when trying to deploy. 

FATAL source.replace is not a function
TypeError: source.replace is not a function
    at Object.exports.parse (/Users/../hexo/node_modules/swig/lib/parser.js:438:19)

**Comment by leesei** [comment]
Can you try my branch https://github.com/leesei/hexo/tree/better-error-message too see which file caused the error?
`npm i leesei/hexo#better-error-message`

**Comment by leesei** [comment]
Attach the file causing the error if possible, thanks.

**Comment by carolynyoo** [comment]
I started in a fresh directory and it's working now, you can close. thanks
