### ISSUE TITLE
You should configure deployment settings in _config.yml first!  Available deployer plugins:   git

### ISSUE THREAD

**Issue by xunlongdingxue** [hexojs/hexo#1864]
I have set up with the command  npm install hexo-deployer-git --save
and hexo clean  and hexo generate and hexo deploy and yml`s content 
is

 theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
type: git
repository: git@github.com:xunlongdingxue/xunlongdingxue.github.io.git 

but when deploy the teminal give the message
You should configure deployment settings in _config.yml first!  Available deployer plugins:   git
what should I do to solve the problem?

**Comment by leesei** [comment]
You have to modify the `deploy` blog in `_config.yml`.
Which part do you not understand?

Here's the Chinese doc:
https://hexo.io/zh-cn/docs/deployment.html

**Comment by leesei** [comment]
Please open new issue if the problem persists.

**Comment by uiolee** [comment]
Because you didn't configure the `deploy` settings correctly

**Comment by uiolee** [comment]
![Image](https://github.com/user-attachments/assets/08dd15c0-cb44-4754-b3f5-c31e57df0039)

https://hexo.io/docs/one-command-deployment

**Comment by uiolee** [comment]
https://hexo.io/docs/one-command-deployment#Git

![Image](https://github.com/user-attachments/assets/8e28b4b7-f6d5-4582-a803-eafc0d2f1094)

![Image](https://github.com/user-attachments/assets/b74d54f7-eb79-4f1c-bf9a-b72dbe62af35)
