### ISSUE TITLE
Generate Error when permalink is set to :title.html

### ISSUE THREAD

**Issue by flyaway1217** [hexojs/hexo#1869]
There is some problems when I set the permalink to :title.html in _config.yml.
If I run the command "hexo generate", I got:
FATAL EISDIR: illegal operation on a directory, open '/Users/flyaway/Dropbox/Blog/public/machine-learning/Gradient-Descent.html'
Error: EISDIR: illegal operation on a directory, open '/Users/flyaway/Dropbox/Blog/public/machine-learning/Gradient-Descent.html'

It seems that hexo will generate folders according to the permalink. When I set permalink to :title.html, hexo will generate folders with name title.html, and this folder name will confuse other packages.
The folders in public/machine-learning is:
![image](https://cloud.githubusercontent.com/assets/1570846/14232633/e3377be6-f9e2-11e5-9226-0369f17908b6.png)

If I change permalink to :title/ in _config.yml, hexo works fine.

I still want my posts with title.html, how can I fix this ?

**Comment by NoahDragon** [comment]
I don't think hexo support it so far.

**Comment by YaoKaiLun** [comment]
cd _post

**Comment by stevenjoezhang** [comment]
Testing has shown that this issue has been fixed in the new version of Hexo.
I'm closing this issue. Please re-open if it is still outstanding.
