### ISSUE TITLE
hexo的NexT主题右边栏中RSS位置不对

### ISSUE THREAD

**Issue by Jrui2015** [hexojs/hexo#1870]
您好，我发现hexo主题右边栏中的RSS图标还有Github图标链接等位置不对，稍微偏左了，我想通过CSS调整稍微靠右一点，请问如何1次修改让之后每次hexo generate都受影响呢？我只在NexT主题文件夹下找到了style文件，并没有找到css文件

**Comment by nick-ChenZe** [comment]
主题文件下`source`目录里有对应组件的`css`，修改完后把`public`文件下的`main.css`删了重新`generate`

**Comment by Jrui2015** [comment]
谢谢您！
