### ISSUE TITLE
Windows 7: bash: hexo: command not found

### ISSUE THREAD

**Issue by tanchao90** [hexojs/hexo#1871]
I have installed **git , nodejs and hexo** according to the docs.

But there are the following message  when I run 'hexo init' in bash.

> $ hexo init
bash: hexo: command not found

But I can run **node hexo** in the hexo  directory (C:\Users\my_username\AppData\Roaming\npm\node_modules\hexo-cli\bin).
> $ node hexo
Usage: hexo <command>
Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.

Here is a WARN in the process of installing hexo:
> npm WARN optional dep failed, continuing fsevents@1.0.11

How to deal with this problem? Can someone help me?

**Comment by Xuanwo** [comment]
Did you install `hexo-cli` with option `-g`?

**Comment by tanchao90** [comment]
Yes, I executed the command: npm install -g hexo-cli

**Comment by tanchao90** [comment]
I did not successful on my home PC last night.
And I also did not successful on my office PC this  afternoon.

But I re executed  `npm install -g hexo-cli` in cmd on my home PC just now.
And then I can use `hexo init` in cmd.

So What happened? Restart computer?

**Comment by tanchao90** [comment]
My office PC is ok when I reinstalled Git and nodejs。
So if someone encounter this problem, you can try **reinstall Git and nodejs.**

**Comment by chansonzhang** [comment]
when I right click "git bash here", It will report "bash: npm: command not found"
however, when I run git bash from start menu，the npm command is all ok.
