### ISSUE TITLE
How do I generate(using cli) multiple posts under one page as hexojs/site did?

### ISSUE THREAD

**Issue by Kaijun** [hexojs/hexo#1873]
As the structure in hexojs/site ([docs](https://github.com/hexojs/site/tree/master/source/docs) or [api](https://github.com/hexojs/site/tree/master/source/api) folder), there're multiple posts under one page folder.

How were they generated? automatically by using cli or just manually actually.

I've tried 

```
hexo new page test post   ------   // generated /source/post/index.md

hexo new page test post   ------   // generated /source/test-post/index.md
```

none of them work.

And one more question: **Is there any approach to get all the posts under one page directory**?

**Comment by leesei** [comment]
They are not standard Hexo, you can see https://github.com/hexojs/site/tree/master/scripts for how Hexo is extended to handle the folders beside `source/_posts`.
The theme also need to support this extension.
