### ISSUE TITLE
hexo怎么实现简单的markdown文本图文混排？

### ISSUE THREAD

**Issue by jinnchen** [hexojs/hexo#1876]
如题

**Comment by tiexo** [comment]
自己下个md编辑器呗，我用的马克飞象

**Comment by leesei** [comment]
For pure Markdown, you can use HTML in Markdown to style your picture and elements.
With Hexo, you can use Tag plugin that accepts class/CSS or that can generate them for you.

**Comment by Xuanwo** [comment]
Closed for no more discussion.
