### ISSUE TITLE
大家都使用了哪些插件？

### ISSUE THREAD

**Issue by tiexo** [hexojs/hexo#1877]
感觉hexo插件方面的讨论和信息很少...官网上一大堆，都搞不清楚每个是干嘛的
具体效果如何

譬如很多都是压缩和优化的
- hexo-critical-css
- hexo-clean-css
- hexo-beautify
- hexo-html-minifier

对于hexo来说是否有必要？
和主题会不会不兼容呢。

**Comment by Xuanwo** [comment]
Just RTFM.

233，开个玩笑。下面我简单的阐述一下我的想法：

- 插件系统开放出来就是为了提供可能性，所以我们不会去判断Hexo是否必要，只要有人开发了Hexo的插件并提交了PR，我们在简单的审核之后就会合并到主干。
- 我们不会去判断一个插件和主题是否兼容，说到底，谁的主题才是标准呢？谁的插件又是判断兼容性的标准呢？

不过这个问题是好问题，有空的话，我们可能会清理掉一些已经不再适用于当前Hexo版本的插件。
以上。

**Comment by tiexo** [comment]
@Xuanwo 嗯嗯，这个我懂
只是看这方面的讨论很少...没想到大家都不感兴趣诶

**Comment by Alibner** [comment]
没什么涉猎，感觉插件都不知道在哪里配置~~~

**Comment by hkongm** [comment]
FEED插件。。。总是坏。。。非法字符

**Comment by zhansingsong** [comment]
分享插件：https://github.com/zhansingsong/iShare.js，大家可以体验一下，专为个人blog定制
