### ISSUE TITLE
JS file in root source directory will be edited after hexo generates.

### ISSUE THREAD

**Issue by panzhitian** [hexojs/hexo#1879]
I place a javascript file in the root source directory (../source/js/src/duoshuo/embed.js) and I find the script is added a equal sign, however, if I place it in the source directory of the theme (../themes/next/source/js/src/duoshuo/embed.js), the file will be same as the original one.

https://raw.githubusercontent.com/panzhitian/duoshuo/https/embed.js

**Comment by leesei** [comment]
Try adding this block to your `_config.yml`
```yaml
skip_render:
  - '**/*.js'
```

**Comment by panzhitian** [comment]
Thanks. #1146
