### ISSUE TITLE
Auto restart hexo server

### ISSUE THREAD

**Issue by tusharmath** [hexojs/hexo#188]
Is there a way to automatically restart the hexo server? I have to do it manually every time I make changes.

**Comment by albertnetymk** [comment]
On editing content of blog post, `hexo server` is enough to have this `edit-refresh-check` cycle. However, for changing parameters in `_config.yml`, e.g. `per_page`, I have to rerun `hexo generate`. `hexo generate --watch` doesn't seem to pick up the change in `_config.yml`.
