### ISSUE TITLE
如何在源代码开头处添加注释（How to add a comment at the beginning of the source code）

### ISSUE THREAD

**Issue by ManaStuDent** [hexojs/hexo#1880]
我想在我的博客源代码 最上面 显示的添加几行注释，请问该如何实现，应当在那里添加内容？
I would like to add a few lines of notes on the top of my blog's source code,where should I to add content?

例如：
for example:

html
****
head
body

如何在博客源码中显示加粗内容。
How to display the blod content in the blog source.

**Comment by uolcano** [comment]
hope this can help you: https://hexo.io/docs/tag-plugins.html#Code-Block

**Comment by leesei** [comment]
You can also modify the layout in theme.
