### ISSUE TITLE
automated index to remixlab GitHub repositories

### ISSUE THREAD

**Issue by nakednous** [hexojs/hexo#1882]
Hi,
(sorry to ask this here)

I'm trying to migrate my octopress-besed blog to hexo and was wondering how to generate an automated index to my GitHub repositories as it's done [here](http://nakednous.github.io/github.html) (where I simply hacked another jekyll-based blog without getting to know all of the details), provided that I have the [js script](https://github.com/nakednous/nakednous.github.io/blob/master/javascripts/github.js).

Should I write a hexo plugin for that? Any advice is more than welcome!

**Comment by leesei** [comment]
The script's link is missing.
And you can implement a migrator for generating site from source other than files in `source/`.
https://github.com/hexojs?utf8=%E2%9C%93&query=migrator

We would be glad to add your migrator to our plugins page once it's finished.
BTW, I also have gathered two repo listing layouts:
- https://github.com/leesei/repos-list
- https://github.com/leesei/repos-grid
They are both using GitHub API to query a hardcoded user.

**Comment by nakednous** [comment]
Thanks for getting back to me. I updated the script's link. I'll check the migrator once I come back home (in a few days).

**Comment by leesei** [comment]
BTW, migrators takes 3rd source and output files in `_posts`, not sure if it fits your scenario
Hexo also supports [custom script](https://hexo.io/docs/plugins.html#Script) ([source](https://github.com/hexojs/hexo/blob/master/lib/hexo/load_plugins.js#L63-L87)) and [data files](https://hexo.io/docs/data-files.html). You have to modify your theme to use data files.
