### ISSUE TITLE
hexo生成的代码块能不能添加复制到剪贴板功能？

### ISSUE THREAD

**Issue by gitlyc** [hexojs/hexo#1885]
就像iteye.com中的代码块可以点击复制按钮复制一样，手动选择复制会复制到代码的行号啊。

**Comment by Xuanwo** [comment]
这是主题的Feature。

gitlyc <notifications@github.com>于2016年4月14日周四 上午9:24写道：

**Comment by gitlyc** [comment]
got it，3ks！

**Comment by gitlyc** [comment]
got it ，thanks！
