### ISSUE TITLE
无法安装……

### ISSUE THREAD

**Issue by ShinoharaYuri** [hexojs/hexo#1892]
INFO  Install dependencies
    npm WARN prefer global marked@0.3.5 should be installed with -g
    > dtrace-provider@0.6.0 install /home/pi/Nya/node_modules/dtrace-provider
    > node scripts/install.js
    WARN  Failed to install dependencies. Please run 'npm install' manually!

npm install

    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11

**Comment by leesei** [comment]
warning 可以不理

**Comment by leesei** [comment]
Also try [`--no-optional`](https://github.com/hexojs/hexo/issues/1326) for the npm install for dtrace issue on OSX.
