### ISSUE TITLE
如何在网址中显示中文？

### ISSUE THREAD

**Issue by panw3i** [hexojs/hexo#1893]
包含中文的网址都被转成这样了  -9d-a5-e5-88-92-e5-ad-97-e7-a

**Comment by leesei** [comment]
![screenshot-2016-04-17-013813](https://cloud.githubusercontent.com/assets/544400/14582620/26da16d8-043d-11e6-8c6d-888bdf02f3ff.png)

When coping the URL from the browser it becames:
http://localhost:4000/hexo-vanilla-site/2016/04/17/%E4%B8%AD%E6%96%87/

This is expected as URL should contain URL-safe ASCII characters.

**Comment by Xuanwo** [comment]
Depends on web browser.
