### ISSUE TITLE
更新hexo3.2版本后，生成静态页面报错。

### ISSUE THREAD

**Issue by oxcz** [hexojs/hexo#1895]
错误提示是：
```
ERROR Process failed: layout/_scripts/bootstrap/.gitkeep
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\view.js:104:22)
    at View (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._resolveCallback (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:423:57)
    at Promise._settlePromiseFromHandler (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:514:17)
    at Promise._settlePromise (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:628:18)
    at D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\我的文档\GitHub\blog\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
我没看到提问是否有特殊的格式，

**Comment by oxcz** [comment]
在google搜索，结果并不是很多。

**Comment by leesei** [comment]
1. 刪除`layout/_scripts/bootstrap/.gitkeep` 試試
2. 傳`hexo generate --debug` 的log

**Comment by oxcz** [comment]
@leesei 1成功，没有报错。
请问，定位在blog、文件夹进行`npm install hexo-cli -g`
操作，对hexo是否有影响呢，更新hexo是不是直接用npm update命令就可以了。

**Comment by oxcz** [comment]
01:08:19.220 DEBUG Hexo version: 3.2.0
01:08:19.229 DEBUG Working directory: D:\我的文档\GitHub\blog\
01:08:20.447 DEBUG Config loaded: D:\我的文档\GitHub\blog\_config.yml
01:08:20.628 DEBUG Plugin loaded: hexo-generator-baidu-sitemap
01:08:21.037 DEBUG Plugin loaded: hexo-deployer-ftpsync
01:08:21.048 DEBUG Plugin loaded: hexo-generator-archive
01:08:21.057 DEBUG Plugin loaded: hexo-generator-index
01:08:21.139 DEBUG Plugin loaded: hexo-generator-feed
01:08:21.146 DEBUG Plugin loaded: hexo-generator-category
01:08:21.153 DEBUG Plugin loaded: hexo-renderer-ejs
01:08:21.165 DEBUG Plugin loaded: hexo-generator-sitemap
01:08:21.171 DEBUG Plugin loaded: hexo-generator-tag
01:08:21.293 DEBUG Plugin loaded: hexo-renderer-marked
01:08:21.299 DEBUG Plugin loaded: hexo-renderer-stylus
01:08:21.304 DEBUG Script loaded: themes\next\scripts\filters\sticky.js
01:08:21.308 DEBUG Script loaded: themes\next\scripts\merge-configs.js
01:08:21.311 DEBUG Script loaded: themes\next\scripts\tags\full-image.js
01:08:21.316 DEBUG Script loaded: themes\next\scripts\tags\center-quote.js
01:08:21.321 DEBUG Script loaded: themes\next\scripts\tags\group-pictures.js
01:08:21.519 DEBUG Plugin loaded: hexo-server
01:08:21.526 DEBUG Loading database.
01:08:21.722 INFO  Start processing
01:08:21.881 DEBUG Processed: 404.html
01:08:21.930 DEBUG Processed: favicon.ico
01:08:21.934 DEBUG Processed: robots.txt
01:08:22.003 DEBUG Processed: _posts/C语言学习笔记.md
01:08:22.009 DEBUG Processed: _posts/Linux常用命令.md
01:08:22.014 DEBUG Processed: _posts/【大雪冷饮】禁摩限电，究竟谁不讲规矩？.md
01:08:22.027 DEBUG Processed: _posts/如何整理自己的生活.md
01:08:22.034 DEBUG Processed: _posts/寒假调研活动有感.md
01:08:22.039 DEBUG Processed: _posts/电子设备的选择.md
01:08:22.057 DEBUG Processed: _posts/联通免流的学习.md
01:08:22.061 DEBUG Processed: _posts/记录最低生活话费.md
01:08:22.068 DEBUG Processed: _posts/近期生活.md
01:08:22.072 DEBUG Processed: _posts/选择hexo最为博客最后的归宿.md
01:08:22.079 DEBUG Processed: about/index.md
01:08:22.083 DEBUG Processed: categories/index.md
01:08:22.148 DEBUG Processed: tags/index.md
01:08:22.152 DEBUG Processed: images/17136-7f8ab5b4213927bb.jpg
01:08:22.157 DEBUG Processed: images/17136-ce82af076e1fd719.jpg
01:08:22.163 DEBUG Processed: images/54817fa90001654403370200.jpg
01:08:22.168 DEBUG Processed: images/avatar.jpg
01:08:22.244 DEBUG Processed: images/17136-c90b2419e21c3376.jpg
01:08:22.349 DEBUG Processed: source/css/main.styl
01:08:22.353 DEBUG Processed: source/images/cc-by-nc-nd.svg
01:08:22.357 DEBUG Processed: source/images/cc-by-nc-sa.svg
01:08:22.363 DEBUG Processed: source/images/cc-by-nc.svg
01:08:22.368 DEBUG Processed: source/images/cc-by-nd.svg
01:08:22.372 DEBUG Processed: source/images/cc-by-sa.svg
01:08:22.378 DEBUG Processed: source/images/cc-by.svg
01:08:22.383 DEBUG Processed: source/images/cc-zero.svg
01:08:22.388 DEBUG Processed: source/images/loading.gif
01:08:22.395 DEBUG Processed: source/images/placeholder.gif
01:08:22.399 DEBUG Processed: source/images/quote-l.svg
01:08:22.404 DEBUG Processed: source/images/quote-r.svg
01:08:22.411 DEBUG Processed: source/images/searchicon.png
01:08:22.500 DEBUG Theme config loaded.
01:08:22.546 DEBUG Processed: _config.yml
01:08:22.681 DEBUG Processed: source/js/src/affix.js
01:08:22.684 DEBUG Processed: source/js/src/motion.js
01:08:22.688 DEBUG Processed: source/js/src/bootstrap.js
01:08:22.694 DEBUG Processed: source/js/src/utils.js
01:08:22.698 DEBUG Processed: source/js/src/hook-duoshuo.js
01:08:22.704 DEBUG Processed: source/vendors/fastclick/LICENSE
01:08:22.712 DEBUG Processed: source/vendors/fastclick/README.md
01:08:22.718 DEBUG Processed: source/vendors/fastclick/bower.json
01:08:22.723 DEBUG Processed: source/vendors/font-awesome/HELP-US-OUT.txt
01:08:22.730 DEBUG Processed: source/vendors/font-awesome/bower.json
01:08:22.734 DEBUG Processed: source/js/src/scrollspy.js
01:08:22.739 DEBUG Processed: source/vendors/jquery_lazyload/bower.json
01:08:22.745 DEBUG Processed: source/vendors/jquery_lazyload/CONTRIBUTING.md
01:08:22.752 DEBUG Processed: source/vendors/jquery_lazyload/README.md
01:08:22.758 DEBUG Processed: source/vendors/jquery_lazyload/jquery.lazyload.js
01:08:23.184 DEBUG Processed: layout/_layout.swig
01:08:23.238 DEBUG Processed: layout/archive.swig
01:08:23.255 DEBUG Processed: layout/category.swig
01:08:23.261 DEBUG Processed: layout/index.swig
01:08:23.266 DEBUG Processed: layout/page.swig
01:08:23.271 DEBUG Processed: layout/post.swig
01:08:23.279 DEBUG Processed: layout/tag.swig
01:08:23.304 DEBUG Processed: languages/de.yml
01:08:23.307 DEBUG Processed: languages/default.yml
01:08:23.314 DEBUG Processed: languages/fr-FR.yml
01:08:23.321 DEBUG Processed: languages/en.yml
01:08:23.329 DEBUG Processed: languages/pt.yml
01:08:23.334 DEBUG Processed: languages/ru.yml
01:08:23.338 DEBUG Processed: languages/zh-Hans.yml
01:08:23.346 DEBUG Processed: languages/zh-hk.yml
01:08:23.351 DEBUG Processed: languages/zh-tw.yml
01:08:23.356 DEBUG Processed: source/vendors/jquery_lazyload/jquery.scrollstop.js
01:08:23.366 DEBUG Processed: source/vendors/velocity/velocity.min.js
01:08:23.371 DEBUG Processed: source/vendors/velocity/velocity.ui.min.js
01:08:23.379 DEBUG Processed: source/vendors/velocity/bower.json
01:08:23.385 DEBUG Processed: source/vendors/velocity/velocity.ui.js
01:08:23.390 DEBUG Processed: source/vendors/jquery/index.js
01:08:23.551 DEBUG Processed: layout/_macro/post-collapse.swig
01:08:23.554 DEBUG Processed: layout/_macro/post.swig
01:08:23.558 DEBUG Processed: layout/_macro/sidebar.swig
01:08:23.566 DEBUG Processed: layout/_partials/comments.swig
01:08:23.574 DEBUG Processed: layout/_partials/duoshuo-hot-articles.swig
01:08:23.584 DEBUG Processed: layout/_partials/footer.swig
01:08:23.589 DEBUG Processed: layout/_partials/head.swig
01:08:23.613 DEBUG Processed: layout/_partials/header.swig
01:08:23.637 DEBUG Processed: layout/_partials/pagination.swig
01:08:23.648 DEBUG Processed: layout/_partials/search.swig
01:08:23.662 DEBUG Processed: layout/_scripts/commons.swig
01:08:23.673 DEBUG Processed: layout/_scripts/boostrap.swig
01:08:23.681 DEBUG Processed: layout/_scripts/vendors.swig
01:08:23.698 DEBUG Processed: source/vendors/fancybox/source/blank.gif
01:08:23.702 DEBUG Processed: source/vendors/fancybox/source/fancybox_loading.gif
01:08:23.711 DEBUG Processed: source/vendors/fancybox/source/fancybox_loading@2x.gif
01:08:23.716 DEBUG Processed: source/vendors/fancybox/source/fancybox_overlay.png
01:08:23.722 DEBUG Processed: source/vendors/fancybox/source/fancybox_sprite.png
01:08:23.731 DEBUG Processed: source/vendors/fancybox/source/fancybox_sprite@2x.png
01:08:23.741 DEBUG Processed: source/vendors/fancybox/source/jquery.fancybox.css
01:08:23.757 DEBUG Processed: source/vendors/fancybox/source/jquery.fancybox.js
01:08:23.769 DEBUG Processed: source/js/src/schemes/pisces.js
01:08:23.784 DEBUG Processed: source/vendors/font-awesome/css/font-awesome.css
01:08:23.802 DEBUG Processed: source/vendors/fancybox/source/jquery.fancybox.pack.js
01:08:23.816 DEBUG Processed: source/vendors/font-awesome/css/font-awesome.css.map
01:08:23.829 DEBUG Processed: source/vendors/fastclick/lib/fastclick.js
01:08:23.833 DEBUG Processed: source/vendors/font-awesome/css/font-awesome.min.css
01:08:23.837 DEBUG Processed: source/vendors/fastclick/lib/fastclick.min.js
01:08:23.847 DEBUG Processed: source/vendors/font-awesome/fonts/fontawesome-webfont.woff2
01:08:23.868 DEBUG Processed: layout/_scripts/schemes/muse.swig
01:08:23.871 DEBUG Processed: layout/_scripts/schemes/mist.swig
01:08:23.891 ERROR Process failed: layout/_scripts/bootstrap/.gitkeep
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\view.js:104:22)
    at View (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\我的文档\GitHub\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._resolveCallback (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:423:57)
    at Promise._settlePromiseFromHandler (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:514:17)
    at Promise._settlePromise (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\promise.js:628:18)
    at D:\我的文档\GitHub\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\我的文档\GitHub\blog\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
01:08:23.985 DEBUG Processed: source/vendors/ua-parser-js/dist/ua-parser.min.js
01:08:23.994 DEBUG Processed: source/vendors/ua-parser-js/dist/ua-parser.pack.js
01:08:24.008 DEBUG Processed: source/vendors/font-awesome/fonts/FontAwesome.otf
01:08:24.014 DEBUG Processed: source/vendors/font-awesome/fonts/fontawesome-webfont.woff
01:08:24.020 DEBUG Processed: source/vendors/font-awesome/fonts/fontawesome-webfont.eot
01:08:24.040 DEBUG Processed: layout/_partials/search/swiftype.swig
01:08:24.044 DEBUG Processed: layout/_partials/search/tinysou.swig
01:08:24.048 DEBUG Processed: layout/_partials/share/duoshuo_share.swig
01:08:24.054 DEBUG Processed: layout/_partials/share/jiathis.swig
01:08:24.060 DEBUG Processed: layout/_scripts/pages/post-details.swig
01:08:24.068 DEBUG Processed: layout/_scripts/schemes/pisces.swig
01:08:24.073 DEBUG Processed: layout/_scripts/third-party/analytics.swig
01:08:24.083 DEBUG Processed: layout/_scripts/third-party/baidushare.swig
01:08:24.087 DEBUG Processed: layout/_scripts/third-party/comments.swig
01:08:24.096 DEBUG Processed: layout/_scripts/third-party/tinysou.swig
01:08:24.102 DEBUG Processed: layout/_scripts/third-party/lean-analytics.swig
01:08:24.110 DEBUG Processed: layout/_scripts/third-party/mathjax.swig
01:08:24.134 DEBUG Processed: source/vendors/velocity/velocity.js
01:08:24.137 DEBUG Processed: source/vendors/fancybox/source/helpers/jquery.fancybox-buttons.js
01:08:24.146 DEBUG Processed: source/vendors/fancybox/source/helpers/fancybox_buttons.png
01:08:24.152 DEBUG Processed: source/vendors/fancybox/source/helpers/jquery.fancybox-buttons.css
01:08:24.157 DEBUG Processed: source/vendors/font-awesome/fonts/fontawesome-webfont.ttf
01:08:24.164 DEBUG Processed: source/vendors/fancybox/source/helpers/jquery.fancybox-thumbs.css
01:08:24.170 DEBUG Processed: source/vendors/fancybox/source/helpers/jquery.fancybox-media.js
01:08:24.176 DEBUG Processed: source/vendors/fancybox/source/helpers/jquery.fancybox-thumbs.js
01:08:24.197 DEBUG Processed: layout/_scripts/third-party/analytics/tencent-analytics.swig
01:08:24.201 DEBUG Processed: layout/_scripts/third-party/analytics/google-analytics.swig
01:08:24.207 DEBUG Processed: layout/_scripts/third-party/analytics/facebook-sdk.swig
01:08:24.214 DEBUG Processed: layout/_scripts/third-party/analytics/baidu-analytics.swig
01:08:24.219 DEBUG Processed: layout/_scripts/third-party/comments/disqus.swig
01:08:24.226 DEBUG Processed: layout/_scripts/third-party/comments/duoshuo.swig
01:08:24.234 DEBUG Processed: source/vendors/font-awesome/fonts/fontawesome-webfont.svg
01:08:24.318 DEBUG Processed: layout/_scripts/bootstrap111/.gitkeep
01:08:24.737 DEBUG Generator: page
01:08:24.739 DEBUG Generator: post
01:08:24.745 DEBUG Generator: baidusitemap
01:08:24.752 DEBUG Generator: archive
01:08:24.755 DEBUG Generator: index
01:08:24.761 DEBUG Generator: feed
01:08:24.765 DEBUG Generator: category
01:08:24.769 DEBUG Generator: sitemap
01:08:24.773 DEBUG Generator: tag
01:08:24.815 DEBUG Generator: asset
01:08:24.865 INFO  Files loaded in 3.34 s
01:08:24.895 DEBUG Rendering page: 404.html
01:08:25.616 DEBUG Rendering page: about/index.html
01:08:25.681 DEBUG Rendering page: tags/index.html
01:08:25.745 DEBUG Rendering page: categories/index.html
01:08:25.796 DEBUG Rendering post: Ubuntu-common-commands/index.html
01:08:25.895 DEBUG Rendering post: C-language-learning-notes/index.html
01:08:26.004 DEBUG Rendering post: not-about-the-rules/index.html
01:08:26.065 DEBUG Rendering post: recent-life/index.html
01:08:26.135 DEBUG Rendering post: dianyan-ganshou/index.html
01:08:26.194 DEBUG Rendering post: china-unicom-free-streaming-learning/index.html
01:08:26.262 DEBUG Rendering post: Selection-of-electronic-equipment/index.html
01:08:26.322 DEBUG Rendering post: How-to-organize-life/index.html
01:08:26.379 DEBUG Rendering post: life-cost-record/index.html
01:08:26.443 DEBUG Rendering post: hexo-blog-website/index.html
01:08:26.515 DEBUG Rendering archive: archives/index.html
01:08:26.662 DEBUG Rendering archive: archives/2016/index.html
01:08:26.782 DEBUG Rendering archive: archives/2016/01/index.html
01:08:26.863 DEBUG Rendering archive: archives/2016/02/index.html
01:08:26.939 DEBUG Rendering archive: archives/2016/04/index.html
01:08:27.021 DEBUG Rendering index: index.html
01:08:27.157 DEBUG Rendering category: categories/学习笔记/index.html
01:08:27.225 DEBUG Rendering category: categories/小生活/index.html
01:08:27.308 DEBUG Rendering category: categories/无责任转载/index.html
01:08:27.362 DEBUG Rendering category: categories/技术文档/index.html
01:08:27.416 DEBUG Rendering tag: tags/C语言/index.html
01:08:27.474 DEBUG Rendering tag: tags/编程/index.html
01:08:27.536 DEBUG Rendering tag: tags/生活/index.html
01:08:27.622 DEBUG Rendering tag: tags/整理/index.html
01:08:27.685 DEBUG Rendering tag: tags/断舍离/index.html
01:08:27.745 DEBUG Rendering tag: tags/法律/index.html
01:08:27.850 DEBUG Rendering tag: tags/转载/index.html
01:08:27.923 DEBUG Rendering tag: tags/实践/index.html
01:08:27.985 DEBUG Rendering tag: tags/感受/index.html
01:08:28.050 DEBUG Rendering tag: tags/手机/index.html
01:08:28.130 DEBUG Rendering tag: tags/电脑/index.html
01:08:28.199 DEBUG Rendering tag: tags/选择/index.html
01:08:28.266 DEBUG Rendering tag: tags/免流/index.html
01:08:28.326 DEBUG Rendering tag: tags/笔记/index.html
01:08:28.421 DEBUG Rendering tag: tags/Ubuntu/index.html
01:08:28.477 DEBUG Rendering tag: tags/常用命令/index.html
01:08:28.529 DEBUG Rendering tag: tags/记录学习/index.html
01:08:28.586 DEBUG Rendering tag: tags/记录/index.html
01:08:28.651 DEBUG Rendering tag: tags/思考/index.html
01:08:28.707 DEBUG Rendering tag: tags/hexo/index.html
01:08:28.758 DEBUG Rendering tag: tags/博客/index.html
01:08:28.822 DEBUG Rendering tag: tags/经历/index.html
01:08:28.874 DEBUG Rendering tag: tags/网购/index.html``

**Comment by leesei** [comment]
`npm install -g` 是全域安裝, 跟你當前所在路徑無關
在hexo site (`_config.yml` 及`package.json` 的資料夾)下
`npm outdated` 查看及`npm update -S` 更新
可參考npm 文檔

**Comment by leesei** [comment]
See #1855
