### ISSUE TITLE
Can deploy git ways upload source files at the same time ?

### ISSUE THREAD

**Issue by HackToday** [hexojs/hexo#1899]
Is there anyway to 

https://hexo.io/zh-cn/docs/deployment.html

it said can use git to deploy, but I found it only(my test)

https://github.com/HackToday/MyBlog

include related html files. 

How can I use one way to have both source files and deploy files existed ?

Since I want to make sure all source(markdown) files upload to github at the same time.

**Comment by leesei** [comment]
This is the expected behavior, deployer only deploy generated site.
Also GitHub will render`gh-pages` branch (not `master`) for repos other than `user.github.io`
Create new branch check in you source code there via 'git push origin/source'

See 
https://github.com/leesei/hexo-vanilla-site/tree/master
https://github.com/leesei/hexo-vanilla-site/tree/gh-pages

**Comment by HackToday** [comment]
@leesei  do you mean I need to use separate branch to maintain the source code ?

master branch is for hexo deployer usage ?


I did not get very clear point from above comments. Thanks

**Comment by leesei** [comment]
> do you mean I need to use separate branch to maintain the source code ?
Yes

> master branch is for hexo deployer usage ?
`master` is where you post md source and run Hexo commands
set `branch` field of git deployer to `gh-pages`

**Comment by HackToday** [comment]
hi @leesei  I followed you above suggestion, it could not work

check this https://github.com/HackToday/MyBlog/tree/gh-pages

only the first page blog can be deploy, then after that, I created several blogs,

```
root@7caab5747d55:/usr/share/nginx/html/source# ls -l _posts/
total 16
-rw-r--r-- 1 root root 82 Apr 25 08:30 Fourth-test.md
-rw-r--r-- 1 root root 60 Apr 25 08:18 Second-test-work.md
-rw-r--r-- 1 root root 54 Apr 25 08:24 Third-test.md
-rw-r--r-- 1 root root 58 Apr 25 08:06 This-is-a-post.md
```

But the hexo deploy would not update gh-pages branch anymore.


Could you tell me what's the issue here ?

**Comment by HackToday** [comment]
ping @tommy351 and @leesei

**Comment by leesei** [comment]
Didn't see a package.json on your master.
https://github.com/leesei/leesei.github.io

Put deployment aside, verify you get a correct site by `hexo g` first.
Did you see any error?

**Comment by HackToday** [comment]
hi @leesei  I think we have some gaps in info
First I have package.json on my hexo server, let me show you

```

```

**Comment by HackToday** [comment]
@leesei  Or do we have any official link for such configuration which seems not easy to setup an easy site

**Comment by leesei** [comment]
Back to your original question, checking in the source to git is not part of Hexo's feature.
deployer-git helps you check in the generated files to a branch.
Checking in your source to another branch is basic git usage. You better consult other git tutorials.
https://try.github.io/
https://help.github.com/articles/good-resources-for-learning-git-and-github/

**Comment by HackToday** [comment]
Thanks @leesei  I found that the above `hexo g` is needed for `hexo deploy` as those are for generate static files, I did not run that after create new blogs, that's why the reason I did find `hexo deploy` update branch files

**Comment by xianshenglu** [comment]
you can check my repo for a demo: https://github.com/xianshenglu/blog. The source is at master branch while _public/_ is at gh-pages branch.
