### ISSUE TITLE
Highlight bug on c++ when  construct with param is a function call

### ISSUE THREAD

**Issue by LFsWang** [hexojs/hexo#1902]
``` cpp
#include<iostream> //cpp
using namespace std;
mt19937 mt(rd());//broken
//abc aa(aa());    //broken as well
```

view
![image](https://cloud.githubusercontent.com/assets/7088579/14681589/4d698bac-0754-11e6-9b4f-309185a8f1ea.png)

``` cpp
#include<iostream> //cpp
using namespace std;
mt19937 mt;
me.seed(rd()); //fine
```

view
![image](https://cloud.githubusercontent.com/assets/7088579/14681608/672ccd88-0754-11e6-9b51-f4ebbcedd7df.png)

```
hexo: 3.2.0
hexo-cli: 1.0.1
os: Windows_NT 10.0.10586 win32 x64
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
```

hexo g --debug
http://pastebin.com/akR3RrBk

**Comment by leesei** [comment]
Upstream issue
https://tonicdev.com/leesei/highlightjs-test
Please report in highlight.js repo
