### ISSUE TITLE
如何得到更加详尽的的tags信息 How to get more specific info of tags?

### ISSUE THREAD

**Issue by Kaijun** [hexojs/hexo#1903]
尝试了 site.tags, 但是得到的信息很有限, 只有length, tag名字, id, 等字段

有没有可以办法可以得到更加详细的信息? 比如 tag被引用的次数, tag链接之类的?

就和list_tags()这个helper渲染的list里的各种参数一样?

**Comment by Kaijun** [comment]
比如说 jekyll 的 site.tags 会返回 tag size, tag对应的posts 等等, 非常详尽, 反观hexo的 site.tags 里面只有名字和id等

**Comment by Kaijun** [comment]
通过log(site.tags)查到是Query对象, 又稍微看了下源码引用了`warehouse`库, 查了[手册](http://tommy351.github.io/warehouse/Query.html) 发现可以得到所有的东西拉!

**Comment by Xuanwo** [comment]
抱歉，现在开发者们都比较忙- -，如果你不介意的话，可以给我们的Doc提交PR

**Comment by Kaijun** [comment]
okkk 可以可以
