### ISSUE TITLE
How do I split a post up into several smaller markdown files?

### ISSUE THREAD

**Issue by fusion809** [hexojs/hexo#1904]
Hi,

On Jekyll if I wanted to split a post up into several smaller markdown files (as they are easier to review and proof-read) I would merely include these smaller markdown files into the main post file using Liquid tags by something like:

``` md
{% include_relative post-part01.md %}

{% include_relative post-part02.md %}

{% include_relative post-part03.md %}
...
{% include_relative post-partn.md %}
```

where `n` is the number of markdown files I had split the post into. Is something like this possible with Hexo? My understanding of EJS templates is minimal, but based on available documentation I cannot see a way of doing this with this particular templating engine. 

Thanks for your time,
Brenton

**Comment by taoalpha** [comment]
In case it may help others, here I paste the code I sent to @fusion809 to create a customized tag plugin for include markdown file:
```
// index.js
var fs   = require('fs'),
  path = require('path'),
  marked = require('marked');
// marked is the markdown converter I choose to use, you can use whatever fits your need.

/**
 * Include markdown tag
 *
 * Syntax:
 *   {% include_md path/to/file %}
 */

var mdTag= function(args, content){
	var render = hexo.render, sourceDir = hexo.source_dir,	arg = args.join(' ');
	
        // add the .md (if you prefer adding the .md youself, can just comment this line.
	arg += ".md";

	var filepath = path.join(sourceDir, arg);
	
	// Exit if the source file doesn't exist
       // return the path for debugging
	if (!fs.existsSync(local)) return filepath;
	
	var data = {};
	data.content = fs.readFileSync(local, 'utf8');
	
	return marked(data.content)
};

// register the "include_md" tag to hexo
hexo.extend.tag.register('include_md', mdTag);
```

You can use this by making a customized hexo plugin youself, like a hexo-tag-md. If I have time, I may create one with more powerful features :)

**Comment by NoahDragon** [comment]
@taoalpha have you created a plugin for it?

**Comment by tea3** [comment]
@fusion809 
@taoalpha 
@NoahDragon 

I published the following plugin. Please use it if you like. 
https://github.com/tea3/hexo-include-markdown

**Comment by NoahDragon** [comment]
@tea3 Great, thank you.

**Comment by bennycode** [comment]
If you want to include Markdown files in your Markdown files, you can also use my plugin which supports texts and code blocks:
- https://github.com/bennycode/hexo-insert-markdown
