### ISSUE TITLE
navy主题支持多说吗？

### ISSUE THREAD

**Issue by barryzxy** [hexojs/hexo#1906]
最近看了 hexojs使用的是navy主题，试着修改为多说平台，不行啊，有人这么用吗？

**Comment by Xuanwo** [comment]
只要在合适的地方加上script即可。

**Comment by barryzxy** [comment]
是将主题中 comment.swig中内容替换掉就可以了，还是要有其他修改?

**Comment by Xuanwo** [comment]
原理上来讲的话，应该是需要修改两处：

一个是调用多说的JS，一个是要生成多说的窗体。
