### ISSUE TITLE
hexo的md语法与github的md语法不通用么？

### ISSUE THREAD

**Issue by pod4g** [hexojs/hexo#1907]
原先我在github的wiki上写博客。现在迁移到了hexo，主题使用的是next，把在wiki上写的md完全迁移到了hexo（没有任何区别，完全是复制粘贴的），为什么显示会有一些差别（有些甚至显示错误）？

[github wiki上的一篇博客](https://github.com/pod4g/tool/wiki/webpack%E5%92%8Cbrowserify%E7%94%A8%E6%B3%95)

![github wiki上的一篇博客](http://7xt9n8.com2.z0.glb.clouddn.com/github.png)

[复制到hexo变成了这样](http://www.liyanshan.com/2016/04/12/webpack%E5%92%8Cbrowserify%E7%94%A8%E6%B3%95/)

![复制到hexo变成了这样](http://7xt9n8.com2.z0.glb.clouddn.com/hexo.png)

可以看到两者的代码引用部分是有区别的，github上是正确的，但是在hexo就出错了，把代码引用的 ``` 都显示出来了，请问这是怎么回事？？？

**Comment by Xuanwo** [comment]
是的，Hexo内置的MD渲染引擎不支持
```
 ``` npm install -g webpack ```
```

这样的写法。

**Comment by pod4g** [comment]
谢谢 @Xuanwo ，还有一个问题，也不支持 ```javascript ```  这种的么？

**Comment by Xuanwo** [comment]
可以使用这种方式：
```
   ```ruby
   xxxx
   ````
```

**Comment by Alex1990** [comment]
@pod4g 行内代码，你可以这样：
<code>\`npm install -g webpack\`</code>

这种写法请看下 Markdown 语法：

- https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
- https://daringfireball.net/projects/markdown/syntax#code

你另外的问题，Hexo 是支持<code>\`\`\`javascript</code>或<code>\`\`\`js</code>这种语法的。

**Comment by pod4g** [comment]
谢谢 @Alex1990 and @Xuanwo

**Comment by Xuanwo** [comment]
Closed for solved
