### ISSUE TITLE
翻页按钮出了点问题

### ISSUE THREAD

**Issue by Chaniel** [hexojs/hexo#1914]
发现翻页按钮变成了这个样子：

« __('prev')
__('next') »

**Comment by Xuanwo** [comment]
请提供更多信息，比如Hexo版本，主题等。

**Comment by Chaniel** [comment]
hexo-cli: 1.0.1
os: Darwin 14.1.1 darwin x64
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e


##  themes/landscape

**Comment by Chaniel** [comment]
http://calmops.com/

**Comment by Xuanwo** [comment]
Maybe I found the problem, let me check it with the developeer.

**Comment by navyxie** [comment]
@Chaniel @Xuanwo 这个问题在pr:[修复分页prev_text和next_text显示的bug](https://github.com/hexojs/hexo-theme-landscape/pull/67)已经修复了。

**Comment by Xuanwo** [comment]
@Chaniel 你可以尝试一下更新主题landscape

**Comment by Chaniel** [comment]
@navyxie 看到你更新了，谢谢，不过好像你没加引号。
我加了引号后可以了。你回头再加一下吧。
https://github.com/hexojs/hexo-theme-landscape/blob/master/layout/_partial/archive.ejs
```
 <%- paginator({
      prev_text: "prev_text",
      next_text: "next_text"
    }) %>
```

**Comment by Chaniel** [comment]
或者改成这样
```
<%- paginator({
      prev_text: "prev",
      next_text: "next"
    }) %>
```

**Comment by navyxie** [comment]
@Chaniel  不需要加引号的哦（因为是模板变量），加了以后翻页按钮的文字显示就是引号内的字符串了。 我也是用landscape主题，效果看[这里](http://www.navyxie.com/)。

**Comment by Chaniel** [comment]
哦，那是我弄错了，刚开始我直接按照你的代码改了那一个文件，启动报错，刚才又将landscape全部克隆下来，启动没问题。谢谢！
