### ISSUE TITLE
Hexo-cli only has 3 options

### ISSUE THREAD

**Issue by ralucas** [hexojs/hexo#1917]
I just updated my hexo-cli and now have only three options: help, init, and version.  Any ideas?

**Comment by Xuanwo** [comment]
Maybe you should run hexo-cli in a Hexo floder ?

**Comment by ralucas** [comment]
Yes, I just updated hexo globally, so it was causing an issue.  Had to update the package.json, trash node_modules and reinstall.  It's working now.  Are there how to update docs anywhere?
