### ISSUE TITLE
skip_render, include and exclude for theme configuration

### ISSUE THREAD

**Issue by qkevinto** [hexojs/hexo#1920]
It would be awesome if we could use `skip_render`, `include` and `exclude` configs within the context of a theme, in the theme's `_config.yml`.

For example, I'm building a theme that uses JSPM and SystemJS for handling JavaScript, which creates a `jspm_packages` folder and for the time being I have to keep it outside of the theme, in the root Hexo `source` folder because there are third party files in that folder (for example .css or .html) which gets rendered by various Hexo plugins, so I have to use `skip_render`.  Now because I have to keep those dependencies outside of the theme folder, it is no longer self-contained and doesn't make the theme very portable.

Another example is, I use a library within this theme called [lodash-es](https://github.com/lodash/lodash/tree/4.11.1-es) which contains JavaScript files with an `_`, like `_DataView.js` and these won't get included in the build because the filename begins with `_`, and in this case the `include` becomes very handy within the context of the theme.

**Comment by mamboer** [comment]
need these features too

**Comment by popomore** [comment]
Nedded +1

It seems that theme is another processor in https://github.com/hexojs/hexo/blob/master/lib/theme/processors/source.js#L29

**Comment by meredrica** [comment]
I also have this issue.
I use bower to pull in some foreign css files. right now i have no easy way to mark that folder as ignored
