### ISSUE TITLE
rsync部署出错 

### ISSUE THREAD

**Issue by ferristale** [hexojs/hexo#1923]
Error: dup() in/out/err failed
    rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: error in rsync protocol data stream (code 12) at io.c(610) [sender=3.0.8]

        at ChildProcess.<anonymous> (D:\Hexo\node_modules\hexo-deployer-rsync\node_modules\hexo-util\lib\spawn.js:42:17)
        at emitTwo (events.js:87:13)
        at ChildProcess.emit (events.js:172:7)
        at maybeClose (internal/child_process.js:827:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

--
VPS: centos6 with xinetd rsync
本地：win10 with cwrsync4.10

**Comment by ferristale** [comment]
centos6

**Comment by hushuangpu** [comment]
楼主解决没有？我的也是这个情况啊

**Comment by ferristale** [comment]
估計是rsync的問題，我換ubuntu可以上傳

**Comment by hushuangpu** [comment]
我也遇到了，ubuntu上也是用rsync，正常，换到windows就不正常了。

胡双朴
________________________________
发件人: ferristale<mailto:notifications@github.com>
发送时间: ‎2016/‎5/‎7 23:37
收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [hexojs/hexo] rsync部署出错  (#1923)

估計是rsync的問題，我換ubuntu可以上傳

---

**Comment by ferristale** [comment]
你的是WIn10嗎？我估計是它不能支持WIn10

**Comment by hushuangpu** [comment]
不会的，我成功过，以前，后来我重置系统，再安装hexo之后就不行了

胡双朴
________________________________
发件人: ferristale<mailto:notifications@github.com>
发送时间: ‎2016/‎5/‎8 11:32
收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [hexojs/hexo] rsync部署出错  (#1923)

你的是WIn10嗎？我估計是它不能支持WIn10

---

**Comment by ferristale** [comment]
那我就不明白了，或許是版本問題？

2016-05-08 12:34 GMT+08:00 hushuangpu <notifications@github.com>:

**Comment by Xuanwo** [comment]
不用Hexo的插件，直接rsync同步可以成功么？

**Comment by ferristale** [comment]
​沒有試過，如果直接同步的話還要做其他配置。既然Ubuntu​能同步，那就不折騰了

2016-05-08 15:26 GMT+08:00 漩涡 <notifications@github.com>:

**Comment by hushuangpu** [comment]
可以的，我试过

胡双朴
________________________________
发件人: 漩涡<mailto:notifications@github.com>
发送时间: ‎2016/‎5/‎8 15:26
收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [hexojs/hexo] rsync部署出错  (#1923)

不用Hexo的插件，直接rsync同步可以成功么？

---

**Comment by hushuangpu** [comment]
人生重在折腾嘛

胡双朴
________________________________
发件人: ferristale<mailto:notifications@github.com>
发送时间: ‎2016/‎5/‎8 15:42
收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [hexojs/hexo] rsync部署出错  (#1923)

​沒有試過，如果直接同步的話還要做其他配置。既然Ubuntu​能同步，那就不折騰了

2016-05-08 15:26 GMT+08:00 漩涡 <notifications@github.com>:

> 不用Hexo的插件，直接rsync同步可以成功么？
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexojs/hexo/issues/1923#issuecomment-217700191>
>


---

**Comment by ferristale** [comment]
放下这个才可以更好的折腾别的啊==

2016-05-08 20:56 GMT+08:00 hushuangpu <notifications@github.com>:

**Comment by hushuangpu** [comment]
所以这个应该是rsync有问题，但是之前为什么就可以，困惑。😂

胡双朴
________________________________
发件人: ferristale<mailto:notifications@github.com>
发送时间: ‎2016/‎5/‎9 10:33
收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [hexojs/hexo] rsync部署出错  (#1923)

放下这个才可以更好的折腾别的啊==

2016-05-08 20:56 GMT+08:00 hushuangpu <notifications@github.com>:

> 人生重在折腾嘛
>
> 胡双朴
> ________________________________
> 发件人: ferristale<mailto:notifications@github.com>
> 发送时间: ‎2016/‎5/‎8 15:42
> 收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
> 抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:
> comment@noreply.github.com>
> 主题: Re: [hexojs/hexo] rsync部署出错 (#1923)
>
> ​沒有試過，如果直接同步的話還要做其他配置。既然Ubuntu​能同步，那就不折騰了
>
> 2016-05-08 15:26 GMT+08:00 漩涡 <notifications@github.com>:
>
> > 不用Hexo的插件，直接rsync同步可以成功么？
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hexojs/hexo/issues/1923#issuecomment-217700191>
> >
>
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/hexojs/hexo/issues/1923#issuecomment-217701758
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexojs/hexo/issues/1923#issuecomment-217716771>
>


---

**Comment by Xuanwo** [comment]
估计win下的rsync实现有些问题，基本无解啊，好多软件到了win下工作都不太正常。

**Comment by AiWuxt** [comment]
同样遇到了这个问题，还是没有解决办法吗

**Comment by hushuangpu** [comment]
目前没有，你可以把public文件夹内的内容全部手动上传到服务器，注意访问权限就行。

胡双朴
________________________________
发件人: Wu Xiaotao<mailto:notifications@github.com>
发送时间: ‎2016/‎5/‎26 18:56
收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [hexojs/hexo] rsync部署出错  (#1923)

同样遇到了这个问题，还是没有解决办法吗

---

**Comment by sosize** [comment]
现在有人解决了吗，windows10就有这个问题，单独rsync正常，就是使用hexo有这个问题。搜不到答案

**Comment by hushuangpu** [comment]
现在我是直接吧public文件夹里面的传到服务器了

胡双朴
________________________________
发件人: zhu<mailto:notifications@github.com>
发送时间: ‎2016/‎8/‎8 20:06
收件人: hexojs/hexo<mailto:hexo@noreply.github.com>
抄送: hushuangpu<mailto:pxezhsp@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [hexojs/hexo] rsync部署出错 (#1923)

现在有人解决了吗，windows10就有这个问题，单独rsync正常，就是使用hexo有这个问题。搜不到答案

---

**Comment by lw604217818** [comment]
rsync的port就用默认设置22就好了
