### ISSUE TITLE
not compatible with Node.js v6.0.0

### ISSUE THREAD

**Issue by yyqian** [hexojs/hexo#1924]
got the warning message after updating to Node.js v6.0.0:

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x14e6288c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x3813fb39f6c4] (this=0x33bac39e2fc9 <an Object with map 0x26958f17be1>#1#,module=0x2d1f7a148a19 <a Module with map 0x26958f181b9>#2#,filename=0x2d1f7a1489e1 <String[141]: /Users/yyqian/Tools/nvm/versions/node/v6.0.0/lib/node_modules/hexo-cli/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node>)
    2: load [module.js:456] [pc=0x3813fb338e72] (this=0x2d1f7a148a19 <a Module with map 0x26958f181b9>#2#,filename=0x2d1f7a1489e1 <String[141]: /Users/yyqian/Tools/nvm/versions/node/v6.0.0/lib/node_modules/hexo-cli/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x3813fb33899d] (this=0x14e628804189 <undefined>,module=0x2d1f7a148a19 <a Module with map 0x26958f181b9>#2#,filename=0x2d1f7a1489e1 <String[141]: /Users/yyqian/Tools/nvm/versions/node/v6.0.0/lib/node_modules/h 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: node::DTraceProvider::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x3813fb20961b
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```

**Comment by pod4g** [comment]
I have the same problem...
#1939

**Comment by deltacat** [comment]
same issue, nodejs 6.2.0, hexo 3.2.0, hexo-cli 1.0.1

>$ hexo clean
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

>==== JS stack trace =========================================

>Security context: 0x1bacaf1c9e59 <JS Object>#0#
    1: .node [module.js:568] [pc=0x3abffd79e664] (this=0x163bf9cea921 <an Object with map 0x382a44318161>#1#,module=0x106bd7a4c69 <a Module with map 0x382a44318739>#2#,filename=0x106bd7a4bd9 <String[114]: /Users/dengtao/Documents/blog/myhexo/node_modules/hexo-generator-feed/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:~449] [pc=0x3abffda1b2b6] (this=0x106bd7a4c69 <a Module with map 0x382a44318739>#2#,filename=0x106bd7a4bd9 <String[114]: /Users/dengtao/Documents/blog/myhexo/node_modules/hexo-generator-feed/node_modules/fsevents/build/Release/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:417] [pc=0x3abffd73921d] (this=0x1bacaf104189 <undefined>,module=0x106bd7a4c69 <a Module with map 0x382a44318739>#2#,filename=0x106bd7a4bd9 <String[114]: /Users/dengtao/Documents/blog/myhexo/node_modules/hexo-generator-feed/node_modules/fsevents/build/Release/fse.node>)
 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x3abffd60961b
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

**Comment by leesei** [comment]
Are you all using OSX?

**Comment by KingBright** [comment]
@leesei I have the same problem and yes I am using OSX.

**Comment by yyqian** [comment]
@leesei yes, OS X

**Comment by hkongm** [comment]
same OSX

**Comment by leesei** [comment]
Try reinstall/rebuild https://github.com/hexojs/hexo/issues/1939#issuecomment-226368455

**Comment by aleung** [comment]
I tried to uninstall then re-install:

```
$ npm uninstall hexo-cli -g
$ npm install hexo-cli -g --no-optional
```

No error was reported during installation. But still have error on running `hexo`:

```
$ hexo version
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0xb99460c9e31 <JS Object>#0#
    1: .node [module.js:583] [pc=0x2b2bc86e6aa4] (this=0x3101b8cde2d1 <an Object with map 0x1e28c561b8b9>#1#,module=0x63d806a7081 <a Module with map 0x1e28c561c8e1>#2#,filename=0x63d806a4171 <String[107]: /Users/leoliang/Projects/blog/node_modules/hexo-generator-feed/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:~464] [pc=0x2b2bc87d2d56] (this=0x63d806a7081 <a Module with map 0x1e28c561c8e1>#2#,filename=0x63d806a4171 <String[107]: /Users/leoliang/Projects/blog/node_modules/hexo-generator-feed/node_modules/fsevents/build/Release/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:432] [pc=0x2b2bc853b57d] (this=0xb9946004189 <undefined>,module=0x63d806a7081 <a Module with map 0x1e28c561c8e1>#2#,filename=0x63d806a4171 <String[107]: /Users/leoliang/Projects/blog/node_modules/hexo-generator-feed/node_modules/fsevents/build/Release/fse.node>)
    4: _load [module.js:424] [pc=0x2b2bc8531262] (this=0x3101b8cde289 <JS Function Module (SharedFunctionInfo 0x3101b8c2dc39)>#3#,request=0x10d07b89fba1 <String[19]: ./build/Release/fse>,parent=0x63d8069e0d1 <a Module with map 0x1e28c561c8e1>#4#,isMain=0xb9946004299 <false>)
    5: require [module.js:~480] [pc=0x2b2bc85b3e4b] (this=0x63d8069e0d1 <a Module with map 0x1e28c561c8e1>#4#,path=0x10d07b89fba1 <String[19]: ./build/Release/fse>)
    6: require(aka require) [internal/module.js:20] [pc=0x2b2bc85442c6] (this=0xb9946004189 <undefined>,path=0x10d07b89fba1 <String[19]: ./build/Release/fse>)
    7: /* anonymous */ [/Users/leoliang/Projects/blog/node_modules/hexo-generator-feed/node_modules/fsevents/fsevents.js:9] [pc=0x2b2bc886fc1f] (this=0x63d8069e121 <an Object with map 0x25d3e3c07ac1>#5#,exports=0x63d8069e121 <an Object with map 0x25d3e3c07ac1>#5#,require=0x63d806a2499 <JS Function require (SharedFunctionInfo 0x3101b8c5f7c1)>#6#,module=0x63d8069e0d1 <a Module with map 0x1e28c561c8e1>#4#,__filename=0x63d8069ba61 <String[96]: /Users/leoliang/Projects/blog/node_modules/hexo-generator-feed/node_modules/fsevents/fsevents.js>,__dirname=0x63d806a2431 <String[84]: /Users/leoliang/Projects/blog/node_modules/hexo-generator-feed/node_modules/fsevents>)
... too long, cutted ...
```

Version information:

> hexo: 3.2.0
> hexo-cli: 1.0.2
> os: Darwin 15.6.0 darwin x64
> http_parser: 2.7.0
> node: 6.4.0
> v8: 5.0.71.60
> uv: 1.9.1
> zlib: 1.2.8
> ares: 1.10.1-DEV
> icu: 57.1
> modules: 48
> openssl: 1.0.2h

**Comment by aleung** [comment]
The error isn't about `Module version mismatch`, so solution in #1939 doesn't help.

**Comment by aleung** [comment]
Run `npm update` to update hexo to v 3.2.2, issue is gone.
