### ISSUE TITLE
为何出现404

### ISSUE THREAD

**Issue by zachary05** [hexojs/hexo#1928]
localhost可以访问

在repo里添加了CNAME后，hexo d -g 之后网址就404了并且repo里的CNAME不见了

请问什么原因？

https://github.com/zachary05/zachary05.github.io

**Comment by zachary05** [comment]
在repo里创建CNAME并且download zip到本地,将CNAME文件拷贝到hexo目录下public中，经过测试成功

**Comment by carl0schen** [comment]
When hexo generate and deploy, if your local folder does not have CNAME file, it will be delete.
You can create CNAME file under the the source folder.
Path:
1. /your-hexo-blog-folder/source/
or
2. /your-hexo-blog-folder/themes/your-theme/source/

**Comment by carl0schen** [comment]
When hexo generate and deploy, if your local folder does not have CNAME file, it will be delete.
You can create CNAME file under the the source folder.
Path:
1. /your-hexo-blog-folder/source/
or
2. /your-hexo-blog-folder/themes/your-theme/source/
