### ISSUE TITLE
Cannot install hexo with msysgit in win7

### ISSUE THREAD

**Issue by kmahyyg** [hexojs/hexo#1934]
Yyg@ZGC-20150529XKO MINGW32 /e/yyg/server/github/kmahyyg.github.io (master)
$ npm install -g hexo-cli

Yyg@ZGC-20150529XKO MINGW32 /e/yyg/server/github/kmahyyg.github.io (master)
$ npm install -g hexo-cli
C:\Users\Yyg\AppData\Roaming\npm\hexo -> C:\Users\Yyg\AppData\Roaming\npm\node_m                                              odules\hexo-cli\bin\hexo

> dtrace-provider@0.6.0 install C:\Users\Yyg\AppData\Roaming\npm\node_modules\he                                              xo-cli\node_modules\dtrace-provider
> node scripts/install.js

> spawn-sync@1.0.15 postinstall C:\Users\Yyg\AppData\Roaming\npm\node_modules\he                                              xo-cli\node_modules\spawn-sync
> node postinstall

> hexo-util@0.5.3 postinstall C:\Users\Yyg\AppData\Roaming\npm\node_modules\hexo                                              -cli\node_modules\hexo-util
> npm run build:highlight

> hexo-util@0.5.3 build:highlight C:\Users\Yyg\AppData\Roaming\npm\node_modules\                                              hexo-cli\node_modules\hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

C:\Users\Yyg\AppData\Roaming\npm
`-- hexo-cli@1.0.1
  +-- abbrev@1.0.7
  +-- bluebird@3.3.5
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.0.0
  | +-- strip-ansi@3.0.1
  | `-- supports-color@2.0.0
  +-- hexo-fs@0.1.5
  | +-- chokidar@1.4.3
  | | +-- anymatch@1.3.0
  | | | +-- arrify@1.0.1
  | | | `-- micromatch@2.3.8
  | | |   +-- arr-diff@2.0.0
  | | |   | `-- arr-flatten@1.0.1
  | | |   +-- array-unique@0.2.1
  | | |   +-- braces@1.8.4
  | | |   | +-- expand-range@1.8.1
  | | |   | | `-- fill-range@2.2.3
  | | |   | |   +-- is-number@2.1.0
  | | |   | |   +-- isobject@2.1.0
  | | |   | |   +-- randomatic@1.1.5
  | | |   | |   `-- repeat-string@1.5.4
  | | |   | +-- preserve@0.2.0
  | | |   | `-- repeat-element@1.1.2
  | | |   +-- expand-brackets@0.1.5
  | | |   | `-- is-posix-bracket@0.1.1
  | | |   +-- extglob@0.3.2
  | | |   +-- filename-regex@2.0.0
  | | |   +-- kind-of@3.0.2
  | | |   | `-- is-buffer@1.1.3
  | | |   +-- normalize-path@2.0.1
  | | |   +-- object.omit@2.0.0
  | | |   | +-- for-own@0.1.4
  | | |   | | `-- for-in@0.1.5
  | | |   | `-- is-extendable@0.1.1
  | | |   +-- parse-glob@3.0.4
  | | |   | +-- glob-base@0.3.0
  | | |   | `-- is-dotfile@1.0.2
  | | |   `-- regex-cache@0.4.3
  | | |     +-- is-equal-shallow@0.1.3
  | | |     `-- is-primitive@2.0.0
  | | +-- async-each@1.0.0
  | | +-- glob-parent@2.0.0
  | | +-- inherits@2.0.1
  | | +-- is-binary-path@1.0.1
  | | | `-- binary-extensions@1.4.0
  | | +-- is-glob@2.0.1
  | | | `-- is-extglob@1.0.0
  | | +-- path-is-absolute@1.0.0
  | | `-- readdirp@2.0.0
  | |   +-- minimatch@2.0.10
  | |   | `-- brace-expansion@1.1.3
  | |   |   +-- balanced-match@0.3.0
  | |   |   `-- concat-map@0.0.1
  | |   `-- readable-stream@2.1.2
  | |     +-- core-util-is@1.0.2
  | |     +-- isarray@1.0.0
  | |     +-- process-nextick-args@1.0.6
  | |     +-- string_decoder@0.10.31
  | |     `-- util-deprecate@1.0.2
  | `-- graceful-fs@4.1.3
  +-- hexo-log@0.1.2
  | `-- bunyan@1.8.1
  |   +-- dtrace-provider@0.6.0
  |   | `-- nan@2.3.2
  |   +-- moment@2.13.0
  |   +-- mv@2.1.1
  |   | +-- mkdirp@0.5.1
  |   | | `-- minimist@0.0.8
  |   | +-- ncp@2.0.0
  |   | `-- rimraf@2.4.5
  |   |   `-- glob@6.0.4
  |   |     +-- inflight@1.0.4
  |   |     | `-- wrappy@1.0.1
  |   |     `-- once@1.3.3
  |   `-- safe-json-stringify@1.0.3
  +-- hexo-util@0.5.3
  | +-- camel-case@1.2.2
  | | +-- sentence-case@1.1.3
  | | | `-- lower-case@1.1.3
  | | `-- upper-case@1.1.3
  | +-- cross-spawn@2.2.3
  | | +-- cross-spawn-async@2.2.2
  | | | +-- lru-cache@4.0.1
  | | | | +-- pseudomap@1.0.2
  | | | | `-- yallist@2.0.0
  | | | `-- which@1.2.4
  | | |   +-- is-absolute@0.1.7
  | | |   | `-- is-relative@0.1.3
  | | |   `-- isexe@1.1.2
  | | `-- spawn-sync@1.0.15
  | |   +-- concat-stream@1.5.1
  | |   | +-- readable-stream@2.0.6
  | |   | `-- typedarray@0.0.6
  | |   `-- os-shim@0.1.3
  | +-- highlight.js@9.3.0
  | +-- html-entities@1.2.0
  | `-- striptags@2.1.1
  +-- minimist@1.2.0
  +-- object-assign@4.0.1
  `-- tildify@1.2.0
    `-- os-homedir@1.0.1

npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevent                                              s:
npm WARN notsup Not compatible with your operating system or architecture: fseve                                              nts@1.0.12

Yyg@ZGC-20150529XKO MINGW32 /e/yyg/server/github/kmahyyg.github.io (master)
$

How Can I Do?

**Comment by Calinou** [comment]
I don't see any errors in your installation log, only warnings. Hexo should work just fine.

Also, please encode code and logs in triple backticks (```).

**Comment by kmahyyg** [comment]
Sorry,it won't work.It noticed me "installation aborted."
Then When i input "hexo init".

It cannot find hexo.

Help,Thx.

-written in gmail

2016-04-30 22:01 GMT+08:00 Calinou <notifications@github.com>:

> I don't see any errors in your installation log, only warnings. Hexo
> should work just fine.
>
> Also, please encode code and logs in triple backticks (```).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexojs/hexo/issues/1934#issuecomment-215964969>
>



-- 
Send From My Google Mail

Contact Me:

Twitter:@PotatoOnline
Facebook:Find"Yang Yuguang" (yang.yuguang.73@facebook.com)
QQ:920337808
Tencent Microblog:@kmahyyg @lyxyjg
G+:kmahyygyyg@gmail.com
