### ISSUE TITLE
Generating an index of posts using Jade

### ISSUE THREAD

**Issue by Calinou** [hexojs/hexo#1935]
I have this:

``` jade
extends base

block title
  = page.title + " — " + page.subtitle

block content
  .jumbotron
    .container
      h1!= page.title
      h2!= page.subtitle
  .container
    each post in site.posts
      article!= post.title
```

The last line causes the error. How would I generate an index of all posts using Jade? I've looked at EJS examples and they also use `post.title`.

I removed [hexo-generator-index](https://github.com/hexojs/hexo-generator-index) and I'm now trying to do it by hand because it doesn't seem to be possible to move the index to a non-root URL (I want a static page at /, and a blog at /blog).

**Comment by mentos1386** [comment]
you found a solution? I have the "same" problem. Cant access posts in site.posts. If i do `each post in site.posts` it makes # of items but variable `post` is null
