### ISSUE TITLE
重复的代码高亮处理

### ISSUE THREAD

**Issue by Qusic** [hexojs/hexo#1938]
https://github.com/hexojs/hexo-renderer-marked/blob/master/lib/renderer.js#L41-L47
https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/before_post_render/backtick_code_block.js

这里我觉得可以把 backtick_code_block 这个 filter 去掉。
代码高亮本来作为 renderer 的任务就很合适，其次，post 不一定是 markdown 格式，但是 before_post_render 里目前对于代码块的处理完全是针对 markdown 的，其它模版可能会有不同的格式。
另外，高亮配置也要在不同的地方都读取和判断显得比较不优雅。https://github.com/hexojs/hexo-renderer-marked/issues/26

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo-renderer-marked/pull/134
