### ISSUE TITLE
Error: Console `help` has not been registered yet! after npm update

### ISSUE THREAD

**Issue by tim-hub** [hexojs/hexo#1940]
node_modules/hexo/lib/hexo/index.js:194:14

...

After I `sudo npm update`

**Comment by klangwiedergabe** [comment]
this is not letting deploy, someone pls??

**Comment by leesei** [comment]
You should install `hexo-cli` globally, `hexo` locally and run `hexo` in the site folder.
It's recommended to use `hexo init` with latest `hexo-cli` for upgrade.
