### ISSUE TITLE
hexo支持Permalinks忽略目录结构吗?

### ISSUE THREAD

**Issue by ghuiii** [hexojs/hexo#1944]
问题是这样的:
  我想把我的文章以年建立子目录来管理:
    _post/2015/hello.md
     _post/2015/hello1.md
    _post/2016/test.md

但是我想让hexo在生成Permalinks时忽略中间的目录结构(2015,2016这些),这个目录结构只是方便我在本地管理源文章,不想让它影响生成的永久链接.
请问,怎么配置一下可以实现

**Comment by Xuanwo** [comment]
可以的，修改`permalink: :year/:month/:day/:title/`为`permalink: :title/`即可

**Comment by ghuiii** [comment]
嗯这样可以, 另外再问一下 hexo 支持多级目录创建文章吗 ? 比如这样 :`hexo new post 2016/05/xx.md'  希望能在 _post/2016/05下生成 xx.md文章.现在试的是不行

**Comment by Xuanwo** [comment]
不支持，而且你这种需求直接copy文档过去速度更快。

**Comment by ghuiii** [comment]
好吧,明白,之前在用hugo,hugo这些都是可以的

**Comment by Xuanwo** [comment]
嗯
