### ISSUE TITLE
<p> tag get created when adding an image. 

### ISSUE THREAD

**Issue by arslangolic** [hexojs/hexo#1946]
Hexo puts images inside the `<p>` tag when you write articles. Is there a way to get around this because it becomes a problem when you want to build a theme. I can't style paragraphs correctly without altering the images.

**Comment by Cuvinisme** [comment]
Wrote some js code to remove the p wrapper. 

`// Removes <p> wrapper that gets inserted around images
	$('p img').each(function() {
		// Make this code do what you want.
    $(this).unwrap();
	});	`
