### ISSUE TITLE
next主题中添加侧边栏社交链接的图标问题

### ISSUE THREAD

**Issue by justforgit** [hexojs/hexo#1950]
在添加侧边栏社交链接的图标过程中，我知道github的可以这样配置： GitHub: github

那么请问：

    如果我想添加segmentfult的图标social_icons中应该怎么配置？如果没有sf的icon，那么是否可以自定义？

**Comment by Xuanwo** [comment]
请到 https://github.com/iissnan/hexo-theme-next/issues 提问，在这里你可能得不到你想要的信息。

**Comment by iissnan** [comment]
@justforgit 请参看[文档](http://localhost:3001/theme-settings.html#author-sites)

**Comment by Xuanwo** [comment]
@iissnan 你这个怎么是指向127.0.0.1的呀？

**Comment by iissnan** [comment]
:sweat: 复制错了
