### ISSUE TITLE
Use different url in _config.yml for development vs deployment

### ISSUE THREAD

**Issue by mcdanielisaac** [hexojs/hexo#1955]
Just a thought, it would be great if there were a way to specify a url for development purposes (usually localhost) and another for deployment. 

`hexo server` would have to generate files using the the dev url while `hexo deploy` would need to regenerate using the live url.

Probably `hexo generate` would also have a flag to force one or the other

**Comment by stevenjoezhang** [comment]
There is a discussion about it: #1672
I'm closing this issue. Please join the discussion there :)
