### ISSUE TITLE
请问 有没有详细细致的文档

### ISSUE THREAD

**Issue by Rainboylvx** [hexojs/hexo#1956]
看源代码真的很累,3个星期了,代码的注释很少,加上nodejs的调试不好用,希望能有一个详细的讲一下hexo的框架的文档

**Comment by Xuanwo** [comment]
这确实是一个需要做的工作。

**Comment by me10zyl** [comment]
[https://hexo.io/zh-cn/api/](https://hexo.io/zh-cn/api/) ，根据实际需求从这里入手。
