### ISSUE TITLE
一个不影响正常使用的error

### ISSUE THREAD

**Issue by jm1231** [hexojs/hexo#1959]
不管是`hexo g`还是 `hexo s`还是 `hexo d`，都会报下面这个错，但是不影响正常功能。

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

**Comment by carl0schen** [comment]
Same as #1922 .

**Comment by jm1231** [comment]
@carl0schen it didn't solve my problem

**Comment by Xuanwo** [comment]
`npm install hexo --no-optional --save`

**Comment by heronlyj** [comment]
`$ npm uninstall hexo-cli -g`
`$ npm install hexo-cli -g`

[resolve-hexo-DTraceProviderBindings-MODULE-NOT-FOUND](http://kikoroc.com/2016/05/04/resolve-hexo-DTraceProviderBindings-MODULE-NOT-FOUND.html)

**Comment by aircjm** [comment]
npm install hexo --no-optional --save can solve MODULE-NOT-FOUND problem

**Comment by trashG** [comment]
Both "reinstall" and "add '--save'" dont work.
But
`$ sudo npm install dtrace-provider`
it works for me.
