### ISSUE TITLE
请问怎样给网站添加一个图标呢，标签页上显示的那种。

### ISSUE THREAD

**Issue by Mlearn** [hexojs/hexo#1965]
第一次搭建网站，默认搭建完成之后打开网站，图标是空白，很难看。
想要设置一个自己喜欢的图标，不知道在哪里怎么做。请教。

**Comment by Xuanwo** [comment]
设置favicon即可

**Comment by doooonoooob** [comment]
那个东西叫 favicon.ico上传一张名为favicon.ico到根目录就可以了
