### ISSUE TITLE
多余的'default' 被插入了config.language队列中

### ISSUE THREAD

**Issue by zyzyz** [hexojs/hexo#1967]
在lib/theme/index.js中

``` js
24  var languages = ctx.config.language;
25
26  if (!Array.isArray(languages)) {
27    languages = [languages];
28  }
29
30  languages.push('default');
```

如果说原config里设置的language为一个，或是留空，第30行的代码是把default推进一个本地Array里。
但是当原config里设置的language是多个，第30行的代码会把default推进ctx.config.language中

---

假如_config.yml里是这样设置的

```
language: en
```

我在其他地方获取ctx.config.language结果为
en

假如_config.yml里是这样设置的

```
language: 
  - en
  - zh-cn
```

我在其他地方获取ctx.config.language结果为
[en, zh-cn, default]

这是有意的还是bug？

**Comment by Jamling** [comment]
呵呵，所以我每次都把default给删除掉

**Comment by Xuanwo** [comment]
应该确实是一个BUG

**Comment by stevenjoezhang** [comment]
There is a discussion about it https://github.com/hexojs/hexo/issues/1125
I'm closing this issue. Please join the discussion there :)
