### ISSUE TITLE
static file cache

### ISSUE THREAD

**Issue by Everley1993** [hexojs/hexo#1968]
when i put a picture in hexo_project/source/my_pic.png and access it via http://host/my_pic.png, the response doesn't contain any http header about cache
the reponse header is as below:

``` txt
Connection:keep-alive
Content-Type:image/png
Date:Sat, 21 May 2016 14:56:38 GMT
Server:nginx/1.4.6 (Ubuntu)
Transfer-Encoding:chunked
X-Powered-By:Hexo
```

i run hexo by `hexo server -p 2368` and proxy by nginx.

``` txt
    location / {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:2368;
    }
```

is it my problem? or does hexo need to take static file cache into consideration ?

**Comment by NoahDragon** [comment]
Are you looking for the Cache-Control?

![image](https://cloud.githubusercontent.com/assets/5704064/18965436/40bb811e-864b-11e6-88cf-b08a24f23870.png)
