### ISSUE TITLE
new_post_name 中如何用下划线分隔日期和标题

### ISSUE THREAD

**Issue by seisman** [hexojs/hexo#1970]
想要文件名格式为 `2010-03-20_this-is-tilt.md`。

尝试将 `new_post_name` 设置为如下几个值都不行：
1. `:year-:month-:day_:title.md` => `2016-05-undefinedtest.md`
2. `:year-:month-:{day}_:title.md` => `2016-05-:{day}_test.md`
3. `:year-:month-:day\_:title.md` => `_posts/2016-05-22\_test.md`

请问是否有解决办法？

**Comment by bestony** [comment]
开发记录

1. 需要给 slugize 添加一个 options  https://github.com/hexojs/hexo-util/blob/ea43fba3635c50f566ea18ceff2fe7d3e87f90d4/lib/slugize.js#L9
2.  给几个 [Model] 调用的 接口添加一个新的参数
3. 给 default config 添加上相关参数

**Comment by stevenjoezhang** [comment]
测试显示 Hexo 4.2.0 中，设置
```
new_post_name: :year-:month-:day_:title.md
```
符合预期。
