### ISSUE TITLE
Blog entries in a subfolder, custom home page

### ISSUE THREAD

**Issue by pronvit** [hexojs/hexo#1971]
Is it possible to have all blog entries in a subfolder, that is, blog to be just a part of a site, and /index.html just a custom page? I can configure permalinks, tags, pages, etc. to be generate in, for example, /blog subfolder. But blog index is still hardcoded to be /index.html, right?

If that's not currently possible, can you point me to where I should start looking to change it in the code?

**Comment by pronvit** [comment]
It seems the only change I had to make is in hexo-generator-index/lib/generator.js on line 10 from '' to, for example, 'blog'. And then create /index.html just as a normal page. Maybe this can be made a configuration option?

**Comment by zyzyz** [comment]
You can just change the "url" and "root" in config to put all your blog into one subfolder.

Or you can create a .md file into your favorite folder with specific layout placed in your theme, but at the cost of losing accessibility of properties related to pagination(for hexo will still treat it as an PAGE).

For full customization, you have to write your own generator(maybe with new local variables calculated by yourself) and register it into hexo.

**Comment by pronvit** [comment]
@zyzyz If I change `root`, then entire hexo-generated site will be in that folder, while I want just the blog in a subfolder. Basically, I want to use hexo not just for blogging but for my entire site (to share templates, etc.), and I need home page to be just a normal page, not blog index.

Anyway, my change in ` hexo-generator-index/lib/generator.js` seems to work - pagination and everything work as expected.

**Comment by Xuanwo** [comment]
@pronvit you can try to change the post permalink

**Comment by martindsouza** [comment]
@pronvit can you post the specific changes you made in `hexo-generator-index/lib/generator.js` I'm having the same issue. Thanks.

**Comment by martindsouza** [comment]
For others to be clear on the change @pronvit made. in `hexo-generator-index/lib/generator.js` change `return pagination('', posts, {` to `return pagination('blog', posts, {`

You will then need to run `hexo generate` then restart the `hexo server` (if already started)

**Comment by rgfindl** [comment]
I've created a PR that adds a config option to the `hexo-generator-index` package.  https://github.com/hexojs/hexo-generator-index/pull/7

**Comment by davidmtobias** [comment]
Thanks @rgfindl, that works like a charm. A tiny modification in `hexo-generator-index` package that increases Hexo functionality a lot.

**Comment by NoahDragon** [comment]
@pronvit @davidmtobias npm package has updated accordingly. New version is 0.2.1.
