### ISSUE TITLE
Monorepo with Lerna

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#1972]
Hexo is comprised of many repos.
It's quite troublesome to set up the development environment and keep all of them updated upon release.

Many projects are now using the monorepo approach.
Lerna is a tool for managing such repo.
[Lerna · A tool for managing JavaScript projects with multiple packages.](https://lerna.js.org)

**Comment by stevenjoezhang** [comment]
See also https://github.com/orgs/hexojs/teams/core/discussions/1
