### ISSUE TITLE
name.github.io无法访问

### ISSUE THREAD

**Issue by jssyjam** [hexojs/hexo#1974]
使用 name.github.io不是默认访问首页了，没有做过改动
使用 name.github.io/index.html可以访问，不知道什么原因

**Comment by doooonoooob** [comment]
是https://jssyjam.github.io/ 吗？刚刚试了一下，可以访问呀

**Comment by owlslab** [comment]
今天也发现无法访问了，加index.html也不行

**Comment by suyuTech** [comment]
我在想是不是你本地修改过之后hexo server -i localhost也是无法访问的，重新生成再试一下
