### ISSUE TITLE
how to access helper function in generator?

### ISSUE THREAD

**Issue by Jamling** [hexojs/hexo#1975]
I have a script in my theme, the script include some helper function and a generate

``` js
hexo.extend.helper.register('func1', function(options){
//...
});
hexo.extend.helper.register('func2', function(options){
//...
});
hexo.extend.generator.register('generate1', function(locals, options){
  this.func1(); // will throw Type Error : this.func1 is not function.
});
```

And another question: the how to pass options to generator?
@tommy351 
請問，如上所示的腳本程式，註冊的輔助函數，該如何在generator中或console插件中調用呢？謝謝~

**Comment by Xuanwo** [comment]
印象中插件并不能调用helper函数

**Comment by Jamling** [comment]
@Xuanwo 可以调用，不过不能像正常的方法那么调用。

**Comment by Xuanwo** [comment]
不过为什么要在generator或者console中调用呢？可以大致地跟我描述一下使用场景么？

**Comment by Jamling** [comment]
@Xuanwo 详见[hexo-generator-i18n](https://github.com/Jamling/hexo-generator-i18n)。
比如对config.language的处理，在主题中，调用辅助方法`get_langs`将'default'语言去掉。后来将i18n写成了generator插件，然后期望能够直接调用`get_langs`。才发现调用不了。 后面不得不将`get_langs`逻辑重写为一个普通方法供插件调用。

**Comment by Xuanwo** [comment]
`default`这个事情应该是一个BUG，后续会把这个修复掉。目前来讲，似乎错误的push进去了一个`default`。

**Comment by Jamling** [comment]
下面是一个generator中调用helper的示例。
```js
var hs = this.extend.helper.list();
var gh_opt = hs['gh_opts'];
pages.forEach(function(item){
      var gh = gh_opt.call(_self, item);
      if (gh.type === 'get_contents'){
...
...
```
调用方式比较特特殊一些，而且gh_opt helper方法，不能再调用其它helper方法，不然报错。
