### ISSUE TITLE
怎样将首页改成入口式的页面，而不是默认的文章概览？

### ISSUE THREAD

**Issue by S-X-ShaX** [hexojs/hexo#1977]
有没有办法将首页调整为显示简单几个信息和一个链接，点击链接可以进入文章概览页？现在默认首页就是page的第一页，上面显示的是文章。有没有办法把首页改成其他形式？

**Comment by lzjqsdd** [comment]
意思是把sitamap或者归档页作为首页？

**Comment by S-X-ShaX** [comment]
不是，我是想建立一个自定义内容的主页，之后通过这个页面进入原来那个文章概览页

On Wed, May 25, 2016, 08:50 lzjqsdd <notifications@github.com> wrote:

> 意思是把sitamap或者归档页作为首页？
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexojs/hexo/issues/1977#issuecomment-221444369>
>
-- 

请叫我喵 | S-X-ShaX
A Dreamer,
From Inbox by Gmail.

**Comment by lzjqsdd** [comment]
自定义主题就可以

**Comment by xinnyu** [comment]
@lzjqsdd 请问怎么将归档设为首页。。

**Comment by NoahDragon** [comment]
@xinnyu 请参考https://hexo.io/themes/ 中的主题，一般首页都是特殊的归档页。
