### ISSUE TITLE
博客的文件名不能用中文么？为甚么我的显示出来就是Unbenannt

### ISSUE THREAD

**Issue by lp380490944** [hexojs/hexo#1979]

**Comment by lzjqsdd** [comment]
hexo new postname.md，这个命令创建的，是可以的。
_config.yml中文章链接用的格式是 permalink: :year/:month/:day/:title/
主题我用的是Next

**Comment by lp380490944** [comment]
是的，我的已经好了，命令行创建的是可以的。还是谢谢！
