### ISSUE TITLE
求助：单引号显示异常

### ISSUE THREAD

**Issue by lam0114** [hexojs/hexo#1981]
我用的英文单引号，比如 'Welcome' to Hexo! ，
显示在浏览器中就变成了
‘Welcome’ to Hexo! ，单引号变成中文的了。

和用的什么主题貌似没关系，因为我在本地hexo init blog，然后改的hello world，在浏览器查看时就不对，英文变中文单引号了。

这是为什么？求助，谢谢！

**Comment by swj1442291549** [comment]
我也有这个问题，似乎英文下的单引号和双引号都变成了中文的

**Comment by heidyhe** [comment]
有同样的问题：我用的英文单引号和双引号在hexo g生成的html文件中都变成中文符号，请问能什么时候修复吗？

**Comment by swj1442291549** [comment]
我看了一下，渲染的 rendered font 是 “Microsoft YaHei”。而 CSS 中的字体似乎都是 macOS 上独有的，导致浏览器使用才做系统的默认字体。而 “Microsoft YaHei” 对于引号的处理就是全角的。所以我改了一下 CSS 强制换了一个 font-family，就解决了

**Comment by snaketears** [comment]
单纯更改CSS字体无法解决此问题，我看了下，生成html引号就已经被替换成中文引号了。
似乎使用{% raw %}可解决此问题，但是我又不想每篇文章都加入和markdown语法无关地代码，请问这个问题还有其他方式解决吗？

**Comment by Xuanwo** [comment]
字体fallback的问题吧？
你们用Arial之类的试试看。

**Comment by bitmingw** [comment]
straight quotation mark 经过 hexo generate 之后就会变成 curly quotation mark, 和用什么主题没有关系。这种隐含的转换对 [yilia](https://github.com/litten/hexo-theme-yilia) 这种用微软雅黑字体的主题影响很显著。

**Comment by snaketears** [comment]
@bitmingw 请问有办法可以解决么？因为我的文档中夹杂了大量双引号，文档翻阅着实难看。

**Comment by bitmingw** [comment]
@snaketears 这个问题只对部分字体影响比较大，像我用的 [Lato](https://www.google.com/fonts/specimen/Lato) 系字体就没有明显的区别。如果是 code 必须要维持原先的引号那就必须得把它包裹起来了。

**Comment by lam0114** [comment]
感觉我的问题比较奇怪，写的时候用的 'app' 这种，渲染之后就变成了 ’app’， 都变成了右引号，现在只能把引号删掉不用了。我用默认的主题试过，也是这个样子。
请问有谁知道原因么？

**Comment by lam0114** [comment]
@swj1442291549 请问你改用的是什么字体？谢谢

**Comment by swj1442291549** [comment]
我使用Arial，但这只是让引号看起来是英文的，实际上还是中文的引号， @snaketears 已经指出了这一点。换字体指标不治本。

**Comment by snaketears** [comment]
@tommy351 关注，个人觉得这是一个BUG。暂时只能通过{% raw %}解决。

**Comment by tommy351** [comment]
如果用的是 marked renderer 的話，可以試試看關掉 smartypants？

```
marked:
  smartypants: false
```

**Comment by snaketears** [comment]
@tommy351 感谢，问题已经解决。

**Comment by lam0114** [comment]
@tommy351 十分感谢，问题已解决。

**Comment by counter2015** [comment]
@tommy351 我也遇到了相同的问题，感谢！

**Comment by liuqinh2s** [comment]
the same issue: [462](https://github.com/theme-next/hexo-theme-next/issues/462)

**Comment by forliuyifei** [comment]
> 如果用的是 marked renderer 的話，可以試試看關掉 smartypants？
> 
> ```yaml
> marked:
>   smartypants: false
> ```

还是没解决😥

**Comment by SukkaW** [comment]
@forliuyifei Hexo 3.x is no longer supported. Please upgrade to latest Hexo 4.2.1.
