### ISSUE TITLE
how to generate attributes for the css helper

### ISSUE THREAD

**Issue by sdole** [hexojs/hexo#1982]
Hello, I have the following css tag in plain html. I need to use the [css](https://hexo.io/docs/helpers.html#css) helper to generate it. How to add the media query attributes in the css helper?

`<link rel="stylesheet" media="only screen and (min-width: 768px)" type="text/css" href="screen-min-width-767.css"/>`

**Comment by chrisjlee** [comment]
Did you review the helper here already? https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/css.js

**Comment by sdole** [comment]
according to that file, it does not support media attributes... did i get that right?

**Comment by chrisjlee** [comment]
Yeah you're write. that is correct. Looks like the output will always contain a style. Maybe roll a different csshelper. or modify this one.
