### ISSUE TITLE
hexo init can't find module

### ISSUE THREAD

**Issue by tiexo** [hexojs/hexo#1984]
我按照官网教程，先后安装了
- node-v4.4.4-x64
- Git-2.8.3-64-bit

接着输入

```
$ npm install hexo-cli -g
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a bu   ild toolchain, use it instead!
npm WARN optional dep failed, continuing fsevents@1.0.12

> dtrace-provider@0.6.0 install C:\program files\nodejs\node global\node_modules   \hexo-cli\node_modules\hexo-log\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js


> spawn-sync@1.0.15 postinstall C:\program files\nodejs\node global\node_modules   \hexo-cli\node_modules\hexo-util\node_modules\cross-spawn\node_modules\spawn-syn   c
> node postinstall


> hexo-util@0.5.3 postinstall C:\program files\nodejs\node global\node_modules\h   exo-cli\node_modules\hexo-util
> npm run build:highlight


> hexo-util@0.5.3 build:highlight C:\program files\nodejs\node global\node_modul   es\hexo-cli\node_modules\hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

C:\program files\nodejs\node global\hexo -> C:\program files\nodejs\node global\   node_modules\hexo-cli\bin\hexo
hexo-cli@1.0.1 C:\program files\nodejs\node global\node_modules\hexo-cli
├── object-assign@4.1.0
├── abbrev@1.0.7
├── minimist@1.2.0
├── tildify@1.2.0 (os-homedir@1.0.1)
├── bluebird@3.4.0
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2   .2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── hexo-log@0.1.2 (bunyan@1.8.1)
├── hexo-fs@0.1.5 (escape-string-regexp@1.0.5, graceful-fs@4.1.4, chokidar@1.5.1   )
└── hexo-util@0.5.3 (striptags@2.1.1, html-entities@1.2.0, camel-case@1.2.2, hig   hlight.js@9.4.0, cross-spawn@2.2.3)

```

总感觉和以前安装的提示不一样。。。
而且出现问题了

```
$ hexo init
bash: hexo: command not found

```

实际上这是我刚刚折腾半天系统变量PATH后，提示这个
原来是提示这样的

![20160526155401](https://cloud.githubusercontent.com/assets/8164505/15568527/f50a60c2-235e-11e6-801e-1c1e005f5dd5.png)

一直说在git目录下找不到node_modules
搜索了都说是系统变量的原因...各种折腾还是没解决

求指点。

**Comment by Xuanwo** [comment]
为什么你的node_modules在git目录下？
参考一下我的教程： https://xuanwo.org/2015/03/26/hexo-intor/

**Comment by felipesousa** [comment]
@tiexo You can see test using `[sudo] hexo init`, maybe work, anything you can speak with me.

**Comment by tiexo** [comment]
@Xuanwo 
我今天又试了下，还是提示： Cannot find module 'C:\Program Files\Git\node_modules\hexo-cli\bin\hexo'
我看了这个路径下面是没有node_modules文件夹，郁闷了
我是直接下载nodejs和git安装的啊，以前也没遇到这个问题

**Comment by tiexo** [comment]
@felipesousa i'm windows

**Comment by Acris** [comment]
use `winpty hexo.cmd init`

**Comment by helloqingfeng** [comment]
这个你可以在系统盘用户目录文件下找到这个文件夹：node_modules\hexo-cli，然后你复制到git安装目录下就好了。

缺少什么，就给他补什么。
![360 20170225012451291](https://cloud.githubusercontent.com/assets/9712785/23313566/36171336-faf9-11e6-8dca-926993d2bceb.jpg)

![360 20170225011336132](https://cloud.githubusercontent.com/assets/9712785/23313526/068e89d2-faf9-11e6-98c9-ffee38c264a1.jpg)

**Comment by panli1990** [comment]
@helloqingfeng  也是遇到这个问题，用你的方法真的解决了！因为之前分别下载安装后没有出现这个问题，后来处于别的原因卸载后又重新安装，然后出现这个问题，请问您知道具体是因为什么这个文件夹的位置会发生错误吗？

**Comment by BlueHakuta** [comment]
@helloqingfeng  超级感谢！！有用！
