### ISSUE TITLE
插入本地图片的问题

### ISSUE THREAD

**Issue by Archmee** [hexojs/hexo#1988]
我之前在默认的source目录下新建了images文件夹存放我所有博客中要用的图片。因为每次新建博客后还要找编辑器打开很麻烦，所以就在config文件中把source_dir指向了另一个markdown编辑器保存的目录，并且把source目录内的内容都拷贝过来了，但是现在问题来了，hexo g这条命令执行的时候，它没有把我的images下面图片拷贝到public下面的images下面去，所以导致生成的博客看不到图片，请问这个在不使用图片托管库的情况下怎么解决

如果还把images文件夹放到原来的source目录但话，那我更改的source_dir的指向就变得没有意义不是吗。。。

**Comment by lzjqsdd** [comment]
因为你现在image目录不在git仓库下，而生成文件是读取md文件渲染成html放到public下了。

**Comment by lzjqsdd** [comment]
可以把文件还放到hexo目录下，你编辑器用的目录下建立一个软连接到hexo博客的image文件下。

**Comment by Archmee** [comment]
@lzjqsdd 实证可行，thanks，但是第二个问题来了
为了让博客存放的url在/blog/下面，刚才我更改了配置文件中url和roo， 成功之后，我想改回原来的没有/blog/的路径，更改配置文件后，发现运行hexo server后，还是默认跳转到/blog/，我必须要在localhost:4000/后加上index.html才能访问主页，反正只要是访问一级域名的时候都要跳转到 /blog/下面

这让我很迷惑～

**Comment by lzjqsdd** [comment]
如果您的网站存放在子目录中，例如 http://yoursite.com/blog，则请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。

**Comment by Archmee** [comment]
@lzjqsdd 哦，我的意思是，现在我像改回原来顶级域名下比如http://site.com/，然后配置也改了，但是它现在总是会跳到我前面设置的http://site.com/blog/下面去，现在我打开本地服务器，必须在http://site.com/后面加上index.html 😂你知道是什么原因导致的吗，会不会是Ngix保存了什么设置，让它跳转的

**Comment by lzjqsdd** [comment]
建议hexo clean清除cache试试

**Comment by Archmee** [comment]
虽然并没有解决问题，但是换浏览器就可以了，所以估计是浏览器缓存什么的问题，和Hexo无关，但还是谢谢了
