### ISSUE TITLE
How to target=“_blank” in .md?

### ISSUE THREAD

**Issue by JaneWardSandy** [hexojs/hexo#1989]
Hexo version 3.2.0
Is there a way to create a link in markdown that opens in a new window?
If not, what syntax do you recommend to do this.
I think it should be an option.

I don't want to use JavaScript to automatic add `target="_blank"`

**Comment by chrisjlee** [comment]
Issues should be related to hexo and not markdown. I'm closing this issue.

Also, did you try googling some answers? I found a couple:

http://stackoverflow.com/questions/4425198/markdown-target-blank
