### ISSUE TITLE
远程部署后格式错误

### ISSUE THREAD

**Issue by NaughtBoy** [hexojs/hexo#1990]
你好，我使用的是next主题，然后执行 hexo s 部署在本地的时候是可以正常显示的，但是执行 hexo d 部署到Github上面的时候就不行了，相关网页：http://naughtboy.github.io/blog/ 。

**Comment by Xuanwo** [comment]
子目录设置不正确，root需要设置为`/blog/`

**Comment by NaughtBoy** [comment]
@Xuanwo 请问子目录是指本地hexo的子目录还是Github的子目录？我的本地目录结构是：E:\blog，Github地址是这个：https://github.com/NaughtBoy/blog/tree/gh-pages

**Comment by lzjqsdd** [comment]
_config.yml中root选项把/改为/blog/

**Comment by NaughtBoy** [comment]
好了，谢谢您~
