### ISSUE TITLE
双系统情况?

### ISSUE THREAD

**Issue by RanchoCooper** [hexojs/hexo#1991]
之前在windows环境下维护的博客, 博客所在的硬盘分区没变, 只是现在工作大多在linux系统上, 挂载了windows分区之后, 在那个博客根目录能直接使用hexo么

**Comment by lzjqsdd** [comment]
hexo环境需要你在linux重新安装。

**Comment by leesei** [comment]
先確認你在用的module 都有save 都`package.json`
刪除 `node_modules` 再在linux `npm install` 就可以

**Comment by RanchoCooper** [comment]
在linux下更新了一篇博文, 然后发现所有的文章时间都变成今天了...
Windows下clean后重新生成时间是对的, 但是Linux下不管用

**Comment by leesei** [comment]
文章时间 應該由front-matter 的`date`生成
不然會看檔案create/modification time 
你的文章有這個field 嗎?

**Comment by RanchoCooper** [comment]
谢谢帮助, 看了下文档的date用法, 手动加上date后暴力解决了...
我感觉是因为NTFS和ETX分别记录了文档的create time和modify time
(可是为啥linux下文章目录显示的是modify time....)
