### ISSUE TITLE
I want to create a Windows App for Hexo!

### ISSUE THREAD

**Issue by arthurvsmith** [hexojs/hexo#1994]
Hey guys!

I really like Hexo and I'm using it on my website [http://pixxelgames.github.io/](http://pixxelgames.github.io/)
I thought about creating a Hexo Windows App with modern user interface for easier adding posts, managing website or editing.
I would like to help this project(and my favourity static page generator) and create such App for you(for FREE!)

If you are interested, please contact me at: varthurdev(at)gmail(dot)com

**Comment by Xuanwo** [comment]
Looks good to me, due to Hexo's MIT licence, you can do what anything that obey the licence.
And I'm looking forward for this app!
