### ISSUE TITLE
Is it possible to add custom page title and description in category pages?

### ISSUE THREAD

**Issue by uiuxer** [hexojs/hexo#1995]
Hello,

I have to add custom page title and description in every category pages for SEO purpose. Here is my website http://www.uiuxer.com right now it is in Jekyll. It is possible to add custom page title and description in Jekyll. I am moving my website from Jekyll to Hexo. But, I don't know how to do this in Hexo and got stuck.

So please let me know, Is there any possible way to do this?

**Comment by Jamling** [comment]
add deseition in front-matter and append it to your heme

**Comment by uiuxer** [comment]
@Jamling we can add description in the pages we create. But, I want add title and description of category which are generated after adding category in the post.
Like, if I add coding category like below in the post then "Coding" category will get generated.
`categories:
- Coding`
I want to add title and description for that category. Is that possible?

**Comment by Jamling** [comment]
@uiuxer yes~ you can do this.
- add category.yml in _data, the key is category name, the value is category desc.
```yaml
Coding: My Coding Life
```
- write your helper to access category data via `hexo.site.data.category[Coding]`
