### ISSUE TITLE
在自定义的标签插件中如何修改文章的内容

### ISSUE THREAD

**Issue by seff** [hexojs/hexo#1996]
我想实现一个标签插件，它不仅仅在渲染完成后返回一段代码片段，我还想同时修改文章其它部分的内容。在标签的注册函数中，不论我修改 `this.content` 还是 `this._content` 都不能在最后渲染结果中生效，哪位有好的建议？

**Comment by Xuanwo** [comment]
同时修改其它部分的内容似乎并不能做到，你可能需要重载渲染时候的一些函数。

**Comment by seff** [comment]
已MarkdownIt变通实现
