### ISSUE TITLE
Programatically add pages?

### ISSUE THREAD

**Issue by nickbuddendotcom** [hexojs/hexo#1998]
Hey Guys,

I'm trying to programatically copy/duplicate pages from one language directory into another. Let me try to explain with an example:

```
/source
  /example/index.md
  /example-2/index.md
  /example-3/index.md
  /zh-Hant
    /example/index.md
    /example-2/index.md
```

So we've got English-language files in the `source` folder, and we've got _some_ Chinese-language in `source/zh-Hant`, however some pages don't have Chinese translations (here `example-3.md` is _not_ available in `source/zh-Hant`).

What we want to do is programatically generate/render the English-language page at the route `/zh-Hant/example-3` since there isn't a Chinese translated version of this page available. So, we're looking for a resulting build that looks like this:

```
/build/
  /example/index.html
  /example-2/index.html
  /example-3/index.html
  /zh-Hant
    /example/index.html
    /example-2/index.html
    /example-3/index.html // => English language page, copied to this route from /example-2/index.html
```

I've been trying to do this most of the day, but haven't figured out how to make it work. Would anyone be able to point me in the right direction? What's the best way to accomplish this?

**Comment by nickbuddendotcom** [comment]
I've gotten this far enough that I can set a route any time there's a secondary-language page missing, and fill that route with dummy content. What I can't figure out how to do (not for lack of trying) is my page into that route, with `page.lang` changed.

At this point I just need to be able to pass a page object to a function, which returns rendered HTML using one of my theme's layouts. Is there a function somewhere like `var renderedHTML = someFunction(myPageData, 'myLayout');`, which I just can't seem to find?

**Comment by nickbuddendotcom** [comment]
No matter what I do, `view.render` when called from a generator or filter always has all helpers/global variables undefined. So far I can't find any way to programatically render a page template into a route...

If there were any documentation or resources out there on programatically rendering a page into a view of your theme, from a generator or filter, would be very appreciative if someone could point me in the direction...

**Comment by Jamling** [comment]
Well, you can install `hexo-generator-i18n` plugin to do this work, just set it will generate page/post from the 1st language to 2nd, 3rd……language.
And here is an example [ieclipse.cn](http://ieclipse.cn)
