### ISSUE TITLE
hexo: command not found  (on Mac OSX El Capitan) 

### ISSUE THREAD

**Issue by monkeysandwine** [hexojs/hexo#2002]
**Tried to install Hexo without and with sudo, but did not work:**

**Pre-Requisites**

git --version
git version 2.8.1

node -v
v6.2.1

npm version
{ npm: '3.9.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }

**Installing Hexo**

human:~ human2$ npm install -g hexo-cli
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
/Users/human2/.npm-packages/bin/hexo -> /Users/human2/.npm-packages/lib/node_modules/hexo-cli/bin/hexo
/Users/human2/.npm-packages/lib
└── hexo-cli@1.0.1 

human:~ human2$ hexo
-bash: hexo: command not found
human:~ human2$ sudo npm install -g hexo-cli
Password:
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
/Users/human2/.npm-packages/bin/hexo -> /Users/human2/.npm-packages/lib/node_modules/hexo-cli/bin/hexo
/Users/human2/.npm-packages/lib
└── hexo-cli@1.0.1 

**human:~ human2$ hexo
-bash: hexo: command not found**

**Checking on npm:**

human:~ human2$ npm

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/human2/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.9.3 /usr/local/lib/node_modules/npm

**Any idea what is the issue?**

Bruno

**Comment by Xuanwo** [comment]
Use node 5.x and try again?

**Comment by haxwn** [comment]
?
