### ISSUE TITLE
关于分享服务https的问题

### ISSUE THREAD

**Issue by HellForGate** [hexojs/hexo#2008]
Mixed Content: The page at 'url' was loaded over HTTPS, but requested an insecure script 'http://bdimg.share.baidu.com/static/api/js/share.js?cdnversion=407260'. This request has been blocked; the content must be served over 
请问下这个https的问题怎么解决

**Comment by Xuanwo** [comment]
- 停用百度分享
- `share.js`保存在本地，使得它可以通过HTTPS加载

**Comment by Xuanwo** [comment]
Closed for sloved.
