### ISSUE TITLE
hexo有没有搜索blog的插件？

### ISSUE THREAD

**Issue by pod4g** [hexojs/hexo#2009]
如题

**Comment by lengxing** [comment]
http://www.tuicool.com/articles/RZjEbeE
 Swiftype 搜索组件介绍 貌似这个可以吧，具体没用过

**Comment by lengxing** [comment]
http://www.jianshu.com/p/739bf1305e66  或者参考一下这个

**Comment by tiexo** [comment]
http://www.tiexo.cn/update-6-4-7/
基于hexo-generator-json-content的本地搜索，效果很好
