### ISSUE TITLE
win10环境下 默认配置 hexo server 启动后无法打开blog

### ISSUE THREAD

**Issue by onlyoneice** [hexojs/hexo#2014]
使用默认配置，在执行hexo server后 提示

```
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
```

在浏览器中访问一直打不开？

**Comment by Xuanwo** [comment]
打不开是怎么样一个打不开？主题配置正确了么？进行generate了么？

**Comment by dannywu19910524** [comment]
没有hexo server这个指令怎么办

**Comment by Xuanwo** [comment]
@dannywu19910524 安装它

**Comment by kaneren** [comment]
换一个端口，`hexo s -p 3600`，登录[http://localhost:3600/](url)

**Comment by fengguoqing** [comment]
修改端口是可以解决问题，但是如何修改默认的4000？

**Comment by yangg** [comment]
之前同事有个 福昕阅读器默认开了4000端口，可以在配置里关掉。

**Comment by xuelinglong** [comment]
我的是localhost:4000拒绝连接请求，hexo s -p 3600也是拒绝连接请求，怎么办？

**Comment by NoahDragon** [comment]
@xuelinglong 请检查下防火墙配置。

**Comment by Echochenvv** [comment]
我的也是，我的博客repo到github上，local打不开，github也打不开，404
