### ISSUE TITLE
'hexo' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by wicever** [hexojs/hexo#2015]
npm install -g cnpm --registry=https://registry.npm.taobao.org

...

 | +-- request@2.72.0
  | | +-- aws-sign2@0.6.0
  | | +-- aws4@1.3.2
  | | | `-- lru-cache@4.0.1
  | | |   +-- pseudomap@1.0.2
  | | |   `-- yallist@2.0.0
  | | +-- bl@1.1.2
  | | | `-- readable-stream@2.0.6
  | | |   +-- core-util-is@1.0.2
  | | |   +-- isarray@1.0.0
  | | |   +-- process-nextick-args@1.0.6
  | | |   +-- string_decoder@0.10.31
  | | |   `-- util-deprecate@1.0.2
  | | +-- caseless@0.11.0
  | | +-- combined-stream@1.0.5
  | | | `-- delayed-stream@1.0.0
  | | +-- extend@3.0.0
  | | +-- forever-agent@0.6.1
  | | +-- form-data@1.0.0-rc4
  | | | `-- async@1.5.2
  | | +-- har-validator@2.0.6
  | | | +-- chalk@1.1.3
  | | | | +-- ansi-styles@2.2.1
  | | | | +-- escape-string-regexp@1.0.5
  | | | | +-- has-ansi@2.0.0
  | | | | `-- supports-color@2.0.0
  | | | +-- commander@2.9.0
  | | | | `-- graceful-readlink@1.0.1
  | | | +-- is-my-json-valid@2.13.1
  | | | | +-- generate-function@2.0.0
  | | | | +-- generate-object-property@1.2.0
  | | | | | `-- is-property@1.0.2
  | | | | +-- jsonpointer@2.0.0
  | | | | `-- xtend@4.0.1
  | | | `-- pinkie-promise@2.0.1
  | | |   `-- pinkie@2.0.4
  | | +-- hawk@3.1.3
  | | | +-- boom@2.10.1
  | | | +-- cryptiles@2.0.5
  | | | +-- hoek@2.16.3
  | | | `-- sntp@1.0.9
  | | +-- http-signature@1.1.1
  | | | +-- assert-plus@0.2.0
  | | | +-- jsprim@1.2.2
  | | | | +-- extsprintf@1.0.2
  | | | | +-- json-schema@0.2.2
  | | | | `-- verror@1.3.6
  | | | `-- sshpk@1.7.4
  | | |   +-- asn1@0.2.3
  | | |   +-- dashdash@1.13.0
  | | |   | `-- assert-plus@1.0.0
  | | |   +-- ecc-jsbn@0.1.1
  | | |   +-- jodid25519@1.0.2
  | | |   +-- jsbn@0.1.0
  | | |   `-- tweetnacl@0.14.3
  | | +-- is-typedarray@1.0.0
  | | +-- isstream@0.1.2
  | | +-- json-stringify-safe@5.0.1
  | | +-- mime-types@2.1.10
  | | | `-- mime-db@1.22.0
  | | +-- node-uuid@1.4.7
  | | +-- oauth-sign@0.8.1
  | | +-- qs@6.1.0
  | | +-- stringstream@0.0.5
  | | +-- tough-cookie@2.2.2
  | | `-- tunnel-agent@0.4.2
  | +-- retry@0.9.0
  | +-- rimraf@2.5.2
  | +-- semver@5.1.0
  | +-- sha@2.0.1
  | +-- slide@1.1.6
  | +-- sorted-object@2.0.0
  | +-- strip-ansi@3.0.1
  | +-- tar@2.2.1
  | | `-- block-stream@0.0.8
  | +-- text-table@0.2.0
  | +-- uid-number@0.0.6
  | +-- umask@1.1.0
  | +-- unique-filename@1.1.0
  | | `-- unique-slug@2.0.0
  | +-- unpipe@1.0.0
  | +-- validate-npm-package-license@3.0.1
  | | +-- spdx-correct@1.0.2
  | | | `-- spdx-license-ids@1.2.0
  | | `-- spdx-expression-parse@1.0.2
  | |   +-- spdx-exceptions@1.0.4
  | |   `-- spdx-license-ids@1.2.0
  | +-- validate-npm-package-name@2.2.2
  | | `-- builtins@0.0.7
  | +-- which@1.2.9
  | | `-- isexe@1.1.2
  | +-- wrappy@1.0.1
  | `-- write-file-atomic@1.1.4
  +-- npm-request@0.0.4
  | `-- urllib@0.5.11
  |   +-- debug@0.7.4
  |   `-- default-user-agent@0.0.1
  +-- npminstall@1.10.1
  | +-- await-event@1.0.0
  | +-- binary-mirror-config@1.1.0
  | +-- bytes@2.3.0
  | +-- chalk@1.1.3
  | | +-- ansi-styles@2.2.1
  | | +-- escape-string-regexp@1.0.5
  | | +-- has-ansi@2.0.0
  | | | `-- ansi-regex@2.0.0
  | | +-- strip-ansi@3.0.1
  | | `-- supports-color@2.0.0
  | +-- cmd-shim@2.0.2
  | | `-- graceful-fs@4.1.4
  | +-- co@4.6.0
  | +-- co-fs-extra@1.2.1
  | | +-- co-from-stream@0.0.0
  | | | `-- co-read@0.0.1
  | | +-- fs-extra@0.26.7
  | | | +-- jsonfile@2.3.1
  | | | +-- klaw@1.3.0
  | | | `-- path-is-absolute@1.0.0
  | | `-- thunkify-wrap@1.0.4
  | |   `-- enable@1.3.2
  | +-- co-parallel@1.0.0
  | | `-- co-thread@0.0.1
  | +-- destroy@1.0.4
  | +-- minimist@1.2.0
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | +-- mz@2.4.0
  | | +-- any-promise@1.3.0
  | | +-- object-assign@4.1.0
  | | `-- thenify-all@1.6.0
  | |   `-- thenify@3.2.0
  | +-- node-gyp@3.3.1
  | | +-- fstream@1.0.10
  | | +-- glob@4.5.3
  | | | +-- inflight@1.0.5
  | | | | `-- wrappy@1.0.2
  | | | +-- minimatch@2.0.10
  | | | | `-- brace-expansion@1.1.5
  | | | |   +-- balanced-match@0.4.1
  | | | |   `-- concat-map@0.0.1
  | | | `-- once@1.3.3
  | | +-- minimatch@1.0.0
  | | | `-- sigmund@1.0.1
  | | +-- nopt@3.0.6
  | | | `-- abbrev@1.0.9
  | | +-- npmlog@2.0.4
  | | | +-- ansi@0.3.1
  | | | +-- are-we-there-yet@1.1.2
  | | | | +-- delegates@1.0.0
  | | | | `-- readable-stream@2.1.4
  | | | |   +-- buffer-shims@1.0.0
  | | | |   +-- core-util-is@1.0.2
  | | | |   +-- isarray@1.0.0
  | | | |   +-- process-nextick-args@1.0.7
  | | | |   +-- string_decoder@0.10.31
  | | | |   `-- util-deprecate@1.0.2
  | | | `-- gauge@1.2.7
  | | |   +-- has-unicode@2.0.0
  | | |   +-- lodash.pad@4.4.0
  | | |   | +-- lodash._baseslice@4.0.0
  | | |   | +-- lodash._basetostring@4.12.0
  | | |   | `-- lodash.tostring@4.1.3
  | | |   +-- lodash.padend@4.5.0
  | | |   `-- lodash.padstart@4.5.0
  | | +-- osenv@0.1.3
  | | | +-- os-homedir@1.0.1
  | | | `-- os-tmpdir@1.0.1
  | | +-- path-array@1.0.1
  | | | `-- array-index@1.0.0
  | | |   `-- es6-symbol@3.1.0
  | | |     +-- d@0.1.1
  | | |     `-- es5-ext@0.10.11
  | | |       +-- es6-iterator@2.0.0
  | | |       `-- es6-symbol@3.0.2
  | | +-- request@2.72.0
  | | | +-- aws-sign2@0.6.0
  | | | +-- aws4@1.4.1
  | | | +-- bl@1.1.2
  | | | | `-- readable-stream@2.0.6
  | | | +-- caseless@0.11.0
  | | | +-- combined-stream@1.0.5
  | | | | `-- delayed-stream@1.0.0
  | | | +-- extend@3.0.0
  | | | +-- forever-agent@0.6.1
  | | | +-- form-data@1.0.0-rc4
  | | | | `-- async@1.5.2
  | | | +-- har-validator@2.0.6
  | | | | +-- commander@2.9.0
  | | | | +-- is-my-json-valid@2.13.1
  | | | | | +-- generate-function@2.0.0
  | | | | | +-- generate-object-property@1.2.0
  | | | | | | `-- is-property@1.0.2
  | | | | | +-- jsonpointer@2.0.0
  | | | | | `-- xtend@4.0.1
  | | | | `-- pinkie-promise@2.0.1
  | | | |   `-- pinkie@2.0.4
  | | | +-- hawk@3.1.3
  | | | | +-- boom@2.10.1
  | | | | +-- cryptiles@2.0.5
  | | | | +-- hoek@2.16.3
  | | | | `-- sntp@1.0.9
  | | | +-- http-signature@1.1.1
  | | | | +-- assert-plus@0.2.0
  | | | | +-- jsprim@1.2.2
  | | | | | +-- extsprintf@1.0.2
  | | | | | +-- json-schema@0.2.2
  | | | | | `-- verror@1.3.6
  | | | | `-- sshpk@1.8.3
  | | | |   +-- asn1@0.2.3
  | | | |   +-- assert-plus@1.0.0
  | | | |   +-- dashdash@1.14.0
  | | | |   | `-- assert-plus@1.0.0
  | | | |   +-- ecc-jsbn@0.1.1
  | | | |   +-- getpass@0.1.6
  | | | |   | `-- assert-plus@1.0.0
  | | | |   +-- jodid25519@1.0.2
  | | | |   +-- jsbn@0.1.0
  | | | |   `-- tweetnacl@0.13.3
  | | | +-- is-typedarray@1.0.0
  | | | +-- isstream@0.1.2
  | | | +-- json-stringify-safe@5.0.1
  | | | +-- mime-types@2.1.11
  | | | | `-- mime-db@1.23.0
  | | | +-- oauth-sign@0.8.2
  | | | +-- qs@6.1.0
  | | | +-- stringstream@0.0.5
  | | | +-- tough-cookie@2.2.2
  | | | `-- tunnel-agent@0.4.3
  | | `-- which@1.2.10
  | |   `-- isexe@1.1.2
  | +-- node-uuid@1.4.7
  | +-- npm-package-arg@4.1.1
  | | `-- hosted-git-info@2.1.5
  | +-- rimraf@2.5.2
  | | `-- glob@7.0.5
  | |   +-- fs.realpath@1.0.0
  | |   `-- minimatch@3.0.2
  | +-- runscript@1.1.0
  | +-- semver@5.1.0
  | +-- tar@2.2.1
  | | +-- block-stream@0.0.9
  | | `-- inherits@2.0.1
  | +-- urllib@2.9.1
  | | +-- any-promise@1.2.0
  | | +-- default-user-agent@1.0.0
  | | `-- statuses@1.2.1
  | +-- utility@1.7.1
  | | +-- copy-to@2.0.1
  | | `-- escape-html@1.0.3
  | `-- uuid@2.0.2
  +-- open@0.0.5
  `-- urllib@2.10.0
    +-- any-promise@1.2.0
    +-- default-user-agent@1.0.0
    | `-- os-name@1.0.3
    |   +-- osx-release@1.1.0
    |   `-- win-release@1.1.1
    +-- digest-header@0.0.1
    | `-- utility@0.1.11
    |   `-- address@1.0.0
    +-- humanize-ms@1.0.2
    +-- iconv-lite@0.4.13
    +-- media-typer@0.3.0
    `-- statuses@1.3.0

C:\Users\Songjw>hexo -v
'hexo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Songjw>hexo init "f:\Hexo"
'hexo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Songjw>hexo init hexo
'hexo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

F:\>hexo init Hexo
'hexo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

执行按照命令后，结束后无法使用hexo命令，感觉hexo就没安装上。求助~

**Comment by Xuanwo** [comment]
你就安装了一个cnpm，为什么能用hexo = =

**Comment by lzjqsdd** [comment]
cnpm 只是国内的npm镜像，hexo并没有安装，npm install hexo-cli -g来安装

**Comment by wengyulin** [comment]
@Xuanwo    我npm install hexo-cli -g来安装了,也是报楼主那个错误为什么

**Comment by cheetahlou** [comment]
如果更改过npm的安装路径，检查环境变量中npm的路径是否正确
