### ISSUE TITLE
for help about submenu

### ISSUE THREAD

**Issue by kklt007** [hexojs/hexo#2018]
Hi Sir/Madam:
    How to write the "_config.yml" file can I make a item in my menu have a drop-down submenu like the picture?
    Thanks for your help.
    Best wishes
![picture](https://cloud.githubusercontent.com/assets/7539438/16307461/eac11fd4-3993-11e6-9b79-8c488153bef8.png)

**Comment by Jamling** [comment]
这个需要主题支持。
或者你自己修改主题
It need `theme` to support it, if there is no theme, you may need to edit the theme to support it.
