### ISSUE TITLE
"No Title" or "Cannot GET" after uploaded md file to server by FTP

### ISSUE THREAD

**Issue by bi-kai** [hexojs/hexo#2023]
upload md  file to linux server by FTP, the page is gone, only shows "No Title" or "Cannot GET".
the page shows again after edited it with vi.
How can it shows correctly by FTP?

**Comment by bi-kai** [comment]
anyone can help?

**Comment by Xuanwo** [comment]
Looks strange.
Do you use the hexo tool or just ftp?

**Comment by bi-kai** [comment]
@Xuanwo , i am using ftp client, send md from win to centos.
hexo render correctly after vi the md file while `hexo s` is on, or `hexo s` again.
what is hexo tool, can it help?

**Comment by Xuanwo** [comment]
May be the encoding error, both use utf-8?

**Comment by Xuanwo** [comment]
Are you use hexo-server on the server?
If so, please generate the page at local, and deploy the public files to server, than use Nginx or Apache to provide service.

**Comment by bi-kai** [comment]
@Xuanwo let me check the encoding tomorrow.
I moved the files in `public` to other folder and rewrited by nginx as a formal blog;
I also hold `hexo s`, so other guys in my group can preview their articles on line by upload mds throught FTP.
i am changing the theme at times, it's no easy to let every one update theme frequently.
On the other hand, many back-end devs not familiar with nodejs.

**Comment by Xuanwo** [comment]
@bi-kai For your kind of use, the best example is the [Hexo](https://hexo.io) which edited by many user and updated at any time some made a new push or change the theme. 
I don't think use ftp is a good idea. Back-end devs must familiar with git, right? In this way, they just need to write code and push them to server. What you should do is set up the CI environment.

**Comment by bi-kai** [comment]
@Xuanwo ok, it seems a little more complicated, i'll try.

**Comment by fletchto99** [comment]
@bi-kai Were you able to solve this issue? I'm also having this issue while using hexo server (with my docker container): https://github.com/fletchto99/hexo-dev-docker

My flow is as follows:

1. The docker container is running hexo server, watching for draft posts
2. I make changes to a file locally, say `drafts/2019/test.md`
3. The file is uploaded on the server to `fake/path/hexo/source/_drafts/2019/test.md`
4. The first upload renders fine.
5. I make changes to `test.md` and upload via SFTP to the same location and I get:

![screen shot 2019-01-30 at 1 48 02 am](https://user-images.githubusercontent.com/718681/51969217-196bbf80-2431-11e9-83af-9ee70bec4e90.png)

/cc @Xuanwo for visibility
