### ISSUE TITLE
Cannot parse hash character "#"  for makedown head correctly

### ISSUE THREAD

**Issue by kiwenlau** [hexojs/hexo#2025]
I reinstalled all npm modules by using following **package.json** file:

```
{
    "name": "hexo-site",
    "version": "0.0.0",
    "private": true,
    "hexo": {
        "version": "3.1.1"
    },
    "dependencies": {
        "hexo-asset-image": "0.0.2",
        "hexo": "3.1.1",
        "hexo-deployer-git": "0.0.4",
        "hexo-generator-archive": "0.1.3",
        "hexo-generator-baidu-sitemap": "0.1.2",
        "hexo-generator-sitemap": "1.0.1",
        "hexo-generator-index": "0.1.3",
        "hexo-generator-feed": "1.0.2",
        "hexo-generator-category": "0.1.3",
        "hexo-renderer-ejs": "0.1.0",
        "hexo-renderer-marked": "0.2.5",
        "hexo-generator-tag": "0.1.2",
        "hexo-server": "0.1.2",
        "hexo-renderer-stylus": "0.2.3"
    }
}
```

Then I find that hexo can not parse hash character "#"  for makedown head correctly.  The fond size doesn't change, and the "#" remains in the html file...

markdown:

```
##Chapter


####Section 1


####Section 2 
```

result web page:

![result](https://cloud.githubusercontent.com/assets/10240841/16440904/06ef4a70-3e01-11e6-9e39-4de02d7cd595.png)

**Comment by pidov** [comment]
Hi,

First things first: It's called markdown, not makedown ;)

And you need a space character after the "#" in order for it to be parsed properly.

**Comment by kiwenlau** [comment]
@pidov Thanks. It works when I add a space after "#"

However, It had no problem before I reinstall all npm modules. Why does it change?

It's a lot of work to add space after every "#"...

**Comment by pidov** [comment]
I'm pretty sure that's the correct syntax. I haven't used hexo at all, I just have used markdown for various projects. I had to always have space after the "#" for it to be parsed.

**Comment by kiwenlau** [comment]
Thx. 

I think Hexo support the incorrect syntax, and there should be some problem with it.

**Comment by leesei** [comment]
Markdown header DO need a space after #.

http://daringfireball.net/projects/markdown/syntax#header
https://guides.github.com/features/mastering-markdown/#example-headers

**Comment by kiwenlau** [comment]
I understand that markdown need a space after #.

But the problem is:

It works well without space before;

After I reinstall all npm modules, it can not work well...

**Comment by leesei** [comment]
Maybe you're using some outdated dependencies in your original setup.
Please consider this as a bug *fixed*, not a bug *introduced*.
