### ISSUE TITLE
3.2.2版本 hexo d后没有反应，总是提示 avaliilable deployer plugins 

### ISSUE THREAD

**Issue by allida881** [hexojs/hexo#2028]
本地查看ok , yml文件中也已经配置：
![image](https://cloud.githubusercontent.com/assets/17398618/16538271/5c7fa130-4052-11e6-9e55-17e7a6517f65.png)

部署之前，已执行命令 npm install hexo-deployer-git --save
但是执行 hexo d后，还是提示：
![image](https://cloud.githubusercontent.com/assets/17398618/16538266/283bedde-4052-11e6-8041-2453e57b9607.png)

不知是什么原因造成的？

**Comment by Xuanwo** [comment]
你把yml配置以文字形式贴出来，不要放图

**Comment by allida881** [comment]
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Allida's Blog      #博客名
subtitle: 雪忆, 如雪般单纯, 冷静思考.  #博客副标题
description:          #网站描述, 用于爬虫抓取的关键词
author: Allida  li    #作者名称
email: lidan3602881@sina.com  #作者邮箱
language: zh-CN 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
type: git
repo: https://github.com/allida881/allida881.github.io.git
branch: master

**Comment by allida881** [comment]
# Site
title: Allida's Blog      #博客名
subtitle: 学习总结  思考感悟.  #博客副标题
description:          #网站描述, 用于爬虫抓取的关键词
author: Allida  li    #作者名称
email: lidan3602881@sina.com  #作者邮箱
language: zh-CN 

 #  URL
 #   If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

 #  Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

 #  Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

 #  Category & Tag
default_category: uncategorized
category_map:
tag_map:

 #  Date / Time format
 #  Hexo uses Moment.js to parse and display date
 #  You can customize the date format as defined in
 #  http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

 #  Pagination
 #  Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

 #  Extensions
 #  Plugins: https://hexo.io/plugins/
 #  Themes: https://hexo.io/themes/
theme: landscape

 #  Deployment
 #  Docs: https://hexo.io/docs/deployment.html
deploy:
type: git
repo: https://github.com/allida881/allida881.github.io.git
branch: master

**Comment by allida881** [comment]
这是yml里面全部的内容

**Comment by Xuanwo** [comment]
```
type: git
repo: https://github.com/allida881/allida881.github.io.git
branch: master
```

这里的内容加两个空格的缩进试试看

**Comment by allida881** [comment]
浏览器输入：localhost:4000 页面提示：Cannot GET /

**Comment by Xuanwo** [comment]
那个是server的问题，我们一个一个来。

Deploy的问题已经修复了？

**Comment by allida881** [comment]
我下午整的实在没办法，就换了个硬盘地址存储，重新来了一遍。第一次hexo d 时，提示：
fatal: Could not read from remote repository.Please make sure you have the correct access rights.and the repository exists.
找不到repo地址，然后我改成：
repo:  http://github.com/allida881/allida881.github.io.git (貌似这里不能写成 https 是http，上午写错了，其它的都一样)

hexo d 时，就提示输入用户名 密码，部署就成功了。
我好奇怪，网上看了很多教程，都是提示： repo:  git@github.com:allida881/allida881.github.io.git  然后我设置了就是没反应，换成http  居然ok了。想不通。

**Comment by Xuanwo** [comment]
使用git的形式需要配置ssh-key

**Comment by allida881** [comment]
ssh-key 配置了，最开始就是安装完git后，先配置的ssh-key 测试是否和github 连接成功，使用ssh -T git@github.com ,测试了，显示：
HI,allida881! you've successfully authenticated,but GitHub does not provide shell access
这个应该是提示连接上了吧？不懂，就是按照网上教程来的

**Comment by allida881** [comment]
ssh-key 配置了，最开始就是安装完git后，先配置的ssh-key 测试是否和github 连接成功，使用ssh -T git@github.com ,测试了，显示：
HI,allida881! you've successfully authenticated,but GitHub does not provide shell access
这个应该是提示连接上了吧？不懂，都是按照网上教程来的

**Comment by Xuanwo** [comment]
然后你需要把原来的那个`.deploy`文件夹删掉，因为里面有原来的git信息。

**Comment by allida881** [comment]
这个.deploy文件夹在哪呀？

**Comment by allida881** [comment]
是指git文件夹下面的吗？还是hexo文件夹下面的？之前hexo文件夹建在F盘，下午在D盘重建了hexo文件夹，重新来了一遍，您是指要把原来的在F盘的hexo文件夹整体删除吗？

**Comment by Xuanwo** [comment]
具体的名字我忘记了，应该有deploy字样，在hexo目录下。
