### ISSUE TITLE
Local hexo not found in /

### ISSUE THREAD

**Issue by T-bug** [hexojs/hexo#2032]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v5.7.0
```

Your site `_config.yml`
```
# Hexo Configuration
...
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.1.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug

## For question

just push question
安装完成之后 初始化的时候提示这个
ERROR Local hexo not found in /
ERROR Try running: 'npm install hexo --save'

## For feature request

just push feature request

**Comment by Xuanwo** [comment]
Do `npm install` please.

**Comment by T-bug** [comment]
`npm install` 之后 还是不行 还是有这个提示，应该怎么办

**Comment by T-bug** [comment]
![111](https://cloud.githubusercontent.com/assets/16621824/16613089/fc499732-439c-11e6-9ae4-9665ea07fb97.jpg)

**Comment by Xuanwo** [comment]
你确定你的操作流程对么？
npm install hexo-cli -g
hexo init
npm install

丁浩 <notifications@github.com>于2016年7月6日 周三 17:14写道：

> [image: 111]
> <https://cloud.githubusercontent.com/assets/16621824/16613089/fc499732-439c-11e6-9ae4-9665ea07fb97.jpg>
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/hexojs/hexo/issues/2032#issuecomment-230719818>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFGoevQ7twsTvhkZD6ZHJWL9bLaEoKVqks5qS3HbgaJpZM4JE_I9>
> .
>
-- 
Best Regards
Xuanwo

**Comment by T-bug** [comment]
npm install hexo-cli -g
这个ok
![first](https://cloud.githubusercontent.com/assets/16621824/16687635/6c86fb60-454c-11e6-80df-4f816660760d.jpg)
hexo init
这个开始出问题
![second](https://cloud.githubusercontent.com/assets/16621824/16687643/83d25e4a-454c-11e6-968f-f97d91fced4d.jpg)
npm install
报错
![third](https://cloud.githubusercontent.com/assets/16621824/16687658/920c33be-454c-11e6-974a-c84dfd6715e4.jpg)
请问是命令输入不正确还是哪里的问题？
