### ISSUE TITLE
how to add updated datetime in blog 

### ISSUE THREAD

**Issue by yyz20002008** [hexojs/hexo#2038]
> before you submit your issue, please delete all the example code in template
## Environment Info

Node version(`node -v`)
V0.12.0

how to add updated datetime in blog 
您好 请问如何添加一个博客更新时间，不仅仅有一个发布时间

**Comment by Xuanwo** [comment]
修改主题layout。

**Comment by yyz20002008** [comment]
请问是在layout的哪里加？不好意思问这个基础问题，刚入门，请不吝赐教

**Comment by Xuanwo** [comment]
取决于不同的主题和主题模板引擎，大体上就是在生成文章的地方加上，比如： https://github.com/Xuanwo/xuanwo.github.io/blob/blog/themes/lifegoeson/layout/_macro/post.swig#L59
