### ISSUE TITLE
It shows OK in debug but 404 online

### ISSUE THREAD

**Issue by magic3584** [hexojs/hexo#2047]
On **blog** folder I **git init** and **add remote** with my github repo including **all files**.

[https://github.com/magic3584/blog](url).

It shows OK in debug(hexo s --debug) but 404 online.

[https://magic3584.github.io/](url)

**Comment by Xuanwo** [comment]
Works now.

**Comment by magic3584** [comment]
你好，还是不行啊 @Xuanwo

**Comment by Xuanwo** [comment]
不知道你是怎么操作的，我评论的时候是可以访问的。

**Comment by Xuanwo** [comment]
而且你这个主页没有生成啊，有一些子页面可以正常渲染出来： https://magic3584.github.io/about/
你是不是什么插件没有安装？

**Comment by magic3584** [comment]
最开始正常以后我在blog的目录下git init并且上传到github另一个repo后github.io地址就打不开。我然后在blog下重新hexo init 和npm install，然后hexo s --debug本地可以显示了，但是github.io还是打不开。
请问如果我想备份blog在换个机器的情况下，这个备份的流程是怎么样的了？试了好几遍了都不行。

**Comment by Xuanwo** [comment]
资源文件和生成的文件分开管理，你需要把.deployer.git 文件夹过滤

**Comment by magic3584** [comment]
什么都没有装，那个about是hexo n page "about"添加进去测试的。
为什么 [https://magic3584.github.io/about/]() 可以但是 [https://magic3584.github.io/]() 404呢？

**Comment by Xuanwo** [comment]
贴配置文件。

**Comment by magic3584** [comment]
刚才上传的时候.gitignore里已经自动生成有
```
.DS_Store
Thumbs.db
db.json
*.log
node_modules/
public/
.deploy*/
```
我在git init后就发现_config.yml里面的参数都还原默认了。我重新把deploy的部分都部署好后
`npm install hexo-deployer-git --save`、
`hexo clean`、`
hexo d -g`，然后提示我**Not a git repository**

**Comment by magic3584** [comment]
要不麻烦您具体说下怎么分开管理，然后我再照着试试
