### ISSUE TITLE
如何生成不含html扩展名的页面

### ISSUE THREAD

**Issue by zongren** [hexojs/hexo#2051]
Gitlab支持自定义域名添加TLS证书，但是有一个步骤是验证域名所有权，通过打开指定的链接（如http://example/.well-known/acme-challenge/7aFDkn9JVOXKeWleiVgUfzr-G5tTgiFNUB4xHhG7Jq8），输出指定的内容（bvlSeyJiWzestsXGP60SHmYhzBKHtfzh4XUZ4Ts8yHk.Pd1PI7gRddQn94AtjdVO0PKecPR3vdLhSySPNCUfxJg），按照下图的写法，生成的文件包含html扩展到致验证失败，请问怎么解决
<img width="709" alt="screen_capture" src="https://cloud.githubusercontent.com/assets/4525819/17012822/e1593e3a-4f4c-11e6-97cc-75471b6a3337.png">
<img width="398" alt="screen_capture_two" src="https://cloud.githubusercontent.com/assets/4525819/17012827/f3201242-4f4c-11e6-9d31-d3a203413543.png">

**Comment by Xuanwo** [comment]
[skip_render](https://hexo.io/docs/configuration.html#Directory)

**Comment by zongren** [comment]
skip_render的话，permalink属性就不会生效，我需要permalink，因为手动创建的文件夹不会出现在public中（因为文件夹是隐藏文件？）
<img width="385" alt="screen_capture_three" src="https://cloud.githubusercontent.com/assets/4525819/17013324/4bc73b8e-4f50-11e6-8240-5bd724e380ab.png">
<img width="386" alt="screen_capture_four" src="https://cloud.githubusercontent.com/assets/4525819/17013328/5108f68c-4f50-11e6-902e-552278f71b24.png">

**Comment by Xuanwo** [comment]
不要放在隐藏文件夹里面，跟baidu验证一样放在根目录不好么

**Comment by zongren** [comment]
这是letsencrypt指定的规则，我也改不了，目前的解决办法是新建一个repository，然后使用其它博客生成工具生成临时的博客，验证之后再把CNAME改回来，有点麻烦，所以想问一下有没有解决办法。

**Comment by Xuanwo** [comment]
你可以放在`<your theme>/source`文件夹下试试，别的就暂时无解了。

**Comment by zongren** [comment]
使用[https://github.com/lakenen/hexo-processor-static](https://github.com/lakenen/hexo-processor-static)插件可以解决这个问题。
