### ISSUE TITLE
Question about the workflow

### ISSUE THREAD

**Issue by xiasun** [hexojs/hexo#2055]
Hi,
I have tried to install and deploy a hexo blog on github. 

I noticed that what I have deployed on github is a static website, the source code itself is not involved like Jekyll, if I want to new another post, i have to do that locally on my machine.

Is this correct?
If yes, Is there a solution for me to do post on another machine?

Thank you so much!

**Comment by greg-js** [comment]
You can backup your blog to github or some private repo on bitbucket, gitlab, ... Then git clone the repo on your other machine, and set up the deployment again. I deploy from different machines without any issues, but you do need to remember to keep it synced. One way of doing that might be to make a `deploy` script in your `package.json` so an `npm deploy` pushes your changes to a repo and then does `hexo deploy`. If you always deploy like that, the repo will stay current so you can easily pull in changes and write new posts on different machines.
