### ISSUE TITLE
Local Hexo not found (although it is there) on Windows

### ISSUE THREAD

**Issue by georgeedwards** [hexojs/hexo#2058]
## Environment Info

Node version: `v4.4.7`
Windows 10 Pro
## For BUG
- BUG description:

I am trying to test an open-source repo, which I successfully used with my mac, but now on my Windows machine, I am getting the error:

```
>hexo server
ERROR Local hexo not found in ~\Source\Repos\meteor-docs
ERROR Try running: 'npm install hexo --save' 
```

I have tried running the suggested command, and I can see the `hexo` directory in my `node_modules` file, yet I still get this error?

Steps to Reproduce:
1. `git clone https://github.com/meteor/docs`
2. `cd docs`
3. `git submodule update --init`
4. `npm install`
5. `npm start`

**Comment by patrick-motard** [comment]
I'm also having the same issue.

**Comment by xinglsh6937** [comment]
same problem, same steps works well on mac, but not on ubuntu and centos.

**Comment by jpparent** [comment]
Same here on Windows 8.1. Hexo worked fine before updating Hexo to 3.3.9 (I think it was at 3.2.0 before).
