### ISSUE TITLE
command not found: hexo

### ISSUE THREAD

**Issue by wind4869** [hexojs/hexo#206]
今天更新了一下nvm，之后又更新了hexo，结果再使用hexo的时候出现：`command not found: hexo`的提示，可能是什么原因导致的呢？我用的操作系统是linux-mint14。

**Comment by licong** [comment]
一情况是没有指定node的版本所致。可以使用下面命令解决：
# nvm ls
v0.10.35
# nvm use 0.10.35
Now using node v0.10.35
# nvm alias default 0.10.35
default -> 0.10.35 (-> v0.10.35)

**Comment by gaotongfei** [comment]
@licong 谢谢

**Comment by yun313350095** [comment]
个人推荐,使用全局安装
```
sudo npm install hexo-cli -g
```

**Comment by JLHwung** [comment]
> sudo npm install hexo-cli -g

Do not use `sudo` to install `hexo-cli`, see https://github.com/hexojs/hexo/issues/2785#issuecomment-338391933

**Comment by yun313350095** [comment]
@JLHwung 
Thanks , Changing file permissions should be the best method!
