### ISSUE TITLE
Hexo Tag Plugins/Helpers in Swig/Nunjucks layout

### ISSUE THREAD

**Issue by k-funk** [hexojs/hexo#2060]
I want to put a codeblock (among other tags) in a layout, but Tag Plugins only seem to work in the `/source/` files. If I put `{% codeblock %} alert('Hello World!'); {% endcodeblock %}` into `/themes/mytheme/layout/page.swig`, I get an error of 

```
ERROR Process failed: layout/page.swig
Error: Unexpected tag "codeblock"
```

Is this correct? Can I really not use the Hexo tags in my layouts?

**Comment by Jamling** [comment]
The tag plugin is used in source (.md) only
The helper plugin used in theme layouts

**Comment by bijoor** [comment]
To use the builtin helpers with swig or nunjucks , use ```{{ helper() }}``` and not ```{% helper() %}``` 

BTW I was not able to get them to work in the source folder with the nunjucks renderer. I can however use it in the theme.
