### ISSUE TITLE
在amazon aws 上 hexo d 发布到github 时, 两个putty窗口链接同一个服务实例，其中一个同步git失败。

### ISSUE THREAD

**Issue by zhishengzhang** [hexojs/hexo#2062]
测试git能否链接。
1：ssh -T git@github.com 

其中一个putty窗口会出现问题 Permission denied (publickey)，另一个会成功，
Hi zhishengzhang! You've successfully authenticated, but GitHub does not provide shell access.

2：hexo d
 这样就会导致，在发布hexo博客时，肯定忽悠一个失败一个成功，难道是因为生成github ssh key 时，同一个服务实例，不同putty窗口生成的秘钥有关系吗？

**Comment by Xuanwo** [comment]
可能跟密钥有关系，你手动ssh-add 对应的密钥试试看。

**Comment by zhishengzhang** [comment]
谢谢 @Xuanwo ，已经解决，并不是ssh-add的问题；比如我要连接 ssh -T git@github.com,因为我在用Amazon aws 云服务并不是root 用户，是ec2-user用户，认证时，他会默认读取root用户的 /etc/ssh/ssh_config的配置信息。所以只要在~/.ssh 下新建一个config信息，就ok了。
