### ISSUE TITLE
markdown can't access the theme variable in posts

### ISSUE THREAD

**Issue by jaycelq** [hexojs/hexo#2065]
I define a variable in _config.yml
```
static_url: xxxxxx
```

In markdown, I use `{{theme.static_url}}` to access it, but it's always empty.

Am I doing something wrong? Or how to access theme variable in markdown.

**Comment by Xuanwo** [comment]
Just can't.

**Comment by jaycelq** [comment]
My purpose is like the issue #1908 

What's your meaning by modifying the theme?

Does hexo have plan to support it? If I put all my static files in cdn, once I changed the cdn address, I need to change all md files.  Does hexo has a solution to my issue?
