### ISSUE TITLE
I perform hexo command is the tip

### ISSUE THREAD

**Issue by sunzhanxing** [hexojs/hexo#2067]
sunzhanxingdeMacBook-Pro:~ sunzhanxing$ hexo init blog
FATAL EISDIR, read
Error: EISDIR, read

**Comment by sunzhanxing** [comment]
Who can help me？

**Comment by Xuanwo** [comment]
http://stackoverflow.com/questions/20417118/using-node-js-i-get-error-eisdir-read

Just create a new directory and run `hexo init`
