### ISSUE TITLE
主题layout下的各个文件，是如何被使用的？

### ISSUE THREAD

**Issue by bi-kai** [hexojs/hexo#2069]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v4.4.7
```

## For question
1、我想制作主题，但是没有理清theme下layout中的各个文件是如何被使用的：
![image](https://cloud.githubusercontent.com/assets/15070379/17265224/d4d6d940-561f-11e6-839e-4c6c3aec3307.png)
layout根目录下的各个文件，有的文件被删除了，也不影响主题的展示，能否说明下，哪个页面会使用哪个ejs文件？

2、source下也可以放一些页面相关的文件，比如自定义的页面，404、about等，甚至可以放样式脚本等资源文件，为什么不规定全部放到theme下呢，这样不会显得凌乱么？

**Comment by Xuanwo** [comment]
你可以参考： https://xuanwo.org/2016/06/29/new-blog-new-life/

不做硬性规定的原因很简单： Take care of your own shit.
