### ISSUE TITLE
无法安装新版本？？

### ISSUE THREAD

**Issue by tangkunyin** [hexojs/hexo#2071]
如题，`npm install -g hexo-cli`，理论上应该是安装最新版本吧，我这试了很多次，一直是1.0.x版本，虽然不影响使用，但是为什么呢？

![hexo-version](https://cloud.githubusercontent.com/assets/4197468/17270846/de6ec61e-569e-11e6-8234-ac77187b23ba.png)

**Comment by chentsulin** [comment]
`v1.0.2` is the latest version of `hexo-cli`. Please see: https://github.com/hexojs/hexo-cli/blob/master/package.json#L3
