### ISSUE TITLE
hexo error 

### ISSUE THREAD

**Issue by Gpia** [hexojs/hexo#2072]
error log:

---

{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
FATAL Cannot find module 'Documents/work/blog/blog/node_modules/feed'
Error: Cannot find module 'Documents/work/blog/blog/node_modules/feed'

---

How can I do with?

**Comment by Xuanwo** [comment]
Just install it.

**Comment by Gpia** [comment]
It can run after I removed the "plugins" config item in file _config.yml, but it still tells me "{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }".
