### ISSUE TITLE
Blog is already posted to the github, but the website totally haven't changed.

### ISSUE THREAD

**Issue by otsukaresama** [hexojs/hexo#2073]
## Environment Info

Node version(`node -v`)
```
hexo: 3.1.1
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

Your site `_config.yml`
```
# Hexo Configuration

```

Plugin version(`npm ls --depth 0`)
```
├── bunyan@1.5.1 extraneous
├── chalk@1.1.1 extraneous
├──  extraneous error: ENOENT: no such file or directory, open '/Users/baoruiqi/blog/node_modules/fsevents/package.json
├── hexo@3.1.1
├── hexo-deployer-git@0.0.3
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.1.3
├── hexo-generator-tag@0.1.2
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.7
├── hexo-renderer-stylus@0.2.3
├── hexo-server@0.1.3
├── swig@1.4.2 extraneous
├── tildify@1.1.2 extraneous
└── warehouse@1.0.3 extraneous
```

## For question

It has been several months since I last used hexo to post a blog. This time, after i finished a blog, each time I type a hexo command I got the info:

"fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version."

With the blog already being posted to the github, It turns out that there is nothing changed on the website.

**Comment by Xuanwo** [comment]
Remove the `.deployer_git` and generate & deploy again.
