### ISSUE TITLE
How do you nest Block Tags?

### ISSUE THREAD

**Issue by georgeedwards** [hexojs/hexo#2074]
## Questions

If you are creating custom tags, e.g. :  

```
  hexo.extend.tag.register('shouldShow', function (args, content) {
    var result = marked(content);
    var front_end = hexo.locals.get('front_end');
    if (front_end == "true") {
      return null;
    }
    else {
      return result;
    }
  }, { ends: true });
```

Which just decides (based on a site variable) whether or not to display a chunk of code. Then you have another  tag, e.g. 

```
  hexo.extend.tag.register('codeBlock', function (args, content) {
    return marked(content);
  }, { ends: true });
```

Which just renders a code block, but if you have something like:

```
{% shouldShow %}
    {% codeBlock %}
         //some content
    {% endcodeBlock %}
{% endshouldShow %}
```

Then the codeBlock tag ceases working, how can you make multiple tag's logic work when stacked/nested?

**Comment by bmitchinson** [comment]
Wondering about this myself
