### ISSUE TITLE
如何获取某一个标签下的文章列表？

### ISSUE THREAD

**Issue by wkyo** [hexojs/hexo#2077]
RT

已知“文章（标签）”有如下：A(vim, portage)， B(gentoo, kde)， C(kde, vim, python)。
请问怎么获取到标签vim下的所有文章？
构建形如[post1, post02, post03 ...]的数组。

**Comment by Xuanwo** [comment]
一种比较简单粗暴的方法就是遍历所有的文章，然后有vim这个标签的就push到数组里面。
如果你的需求仅仅只是创建一个tags页面的话，推荐使用Hexo自带的函数`list_tags()`
