### ISSUE TITLE
why can't I use table grammar in hexo-tranquilpeak?

### ISSUE THREAD

**Issue by TangTangWan** [hexojs/hexo#2081]
## Environment Info

Node version(`node -v`)

```
v6.3.1
```

Plugin version(`npm ls --depth 0`)

```
hexo-site@0.0.0 /root/blog
├── hexo@3.2.2
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```
## For BUG

I want to edit a table in my post. The original character goes like this:
![image](https://cloud.githubusercontent.com/assets/12480665/17456921/2aa4df84-5c1a-11e6-9f25-b1e2cb442779.png)
It can be presented nicely in my local markdown editor., howerver it is presented like this in hexo:
![image](https://cloud.githubusercontent.com/assets/12480665/17456928/63936522-5c1a-11e6-9c3d-5658c3a16f98.png)
Could you please help me? Do you have any idea about what goes wrong?

**Comment by NoahDragon** [comment]
I think it caused by the code snippet in the first column.
