### ISSUE TITLE
标签没有区别大小写

### ISSUE THREAD

**Issue by dukegod** [hexojs/hexo#2083]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v5.0.0
```

Your site `_config.yml`
```
# Hexo Configuration
...
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.1.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For BUG

标签没有区别大小写。以前我有一个css的标签，后来改为CSS，在重新发布。github的仓库中还是css这个标签，没有CSS这个新的标签。怎么解决？

是不是需要重新删除这个项目，重新发布一般?

**Comment by Xuanwo** [comment]
可以试试`hexo clean`，或者把`.deployer_git`完全删除后再试

**Comment by dukegod** [comment]
@Xuanwo 是把public里面的内容都删除了，然后重新上传。感觉这样太麻烦了，是不是可以想想怎么优化

**Comment by Xuanwo** [comment]
Git默认不区分文件大小写，你可以修改`git config core.ignorecase false`
这个配置可以考虑添加到插件中。
