### ISSUE TITLE
code block scrolling on the mobile

### ISSUE THREAD

**Issue by Coffee0127** [hexojs/hexo#2085]
## Env
* hexo: 3.2.2
* theme: landscape <default>

## For question
I used the ``` to wrap the code as below, here is an online website https://coffee0127.github.io/blog/2016/08/09/hexo-configuration/
```
<div class="article-entry" itemprop="articleBody">
  <% if (post.excerpt && index){ %>
    <%- post.excerpt %>
    <% if (theme.excerpt_link){ %>
      <p class="article-more-link">
        <a href="<%- url_for(post.path) %>#more"><%= theme.excerpt_link %></a>
      </p>
    <% } %>
  <% } else { %>
    <%- post.content %>
  <% } %>
</div>
```
It's fine to using the scroll bar on the PC, but on the mobile is not so intuitive.
![aa44d6d7-173e-421d-a6ab-7ff30ed9b825](https://cloud.githubusercontent.com/assets/4252888/17523448/319c527a-5e8d-11e6-8899-b938d3a36568.jpg)

Did I miss something?
Could you please kindly give me a direction? thanks~
------
程式碼在行動裝置上，必須滑動程式碼區塊的頂端或底端才可滑動，而不是直接在程式碼區塊內滑動即可。

請問是否有哪邊可以做設定呢? 謝謝~

**Comment by carl0schen** [comment]
我用LG G3 Android 6.0 Firefox 48，到你的網站測試滑動程式碼，在程式碼區塊內隨便都可以正常滑動。我自己用Light主題也沒遇到問題。

**Comment by Coffee0127** [comment]
@carl0schen 我是 iPhone 6，iOS 8.2 的 safari 及 Chrome 47.0.2526.107，另外剛剛也有載了 Firefox 5.0，測試結果都仍需在頂端或底端才可以正常滑動。

**Comment by carl0schen** [comment]
@Coffee0127 猜想是不是因為iOS強制使用WebKit，是本身排版引擎造成的問題？明天再去公司用iPad試試，這問題可能要請教開發者如何解決了。

**Comment by carl0schen** [comment]
@Coffee0127 剛請兩位同事測試過你的網站和我自己的網站，iPhone6s Plus和iPhone 6s都是iOS 9.3.4 Safari，在程式碼區塊內都可以正常滑動。

**Comment by Coffee0127** [comment]
@carl0schen 我再找看看是否 iOS8 裝置也會跟我有一樣問題，感謝您的回覆 :)

**Comment by Jamling** [comment]
@Coffee0127 針對行動設備不方便滾動的問題，可以通過CSS媒體查詢來設置代碼塊在行動設備上不滾動來解決。參考我的博文：http://www.ieclipse.cn/tags/Hexo/

**Comment by Coffee0127** [comment]
@Jamling @carl0schen 今天發現程式碼區塊如圖所示
![before](https://cloud.githubusercontent.com/assets/4252888/17585565/1d114c3a-5fef-11e6-9e57-83295f801fe7.jpg)
`<pre>` 裡面包的是 `<div>`，因此我將其替換為 `<span><br/>`，iOS8 裝置就正常了XD

具體程式碼如下
```
  // fix the backtick code block generate <div> leads to iOS8 cannot scrolling
  $('td.code').each(function(index, element) {
    var content = $(element).html();
    content = content
      .replace(/<div class="line">/g, '<span class="line">')
      .replace(/<\/div>/g, '</span><br/>');
    $(element).html(content);
  });
```

thank you~
