### ISSUE TITLE
hexo server not working in win10 bash shell

### ISSUE THREAD

**Issue by Fengxq2014** [hexojs/hexo#2087]
##Node version(`node -v`)
```
v4.4.7
```

## For BUG

- hexo server not working in win10 bash shell
- log with hexo <command> --debug
---
04:07:46.874 DEBUG Hexo version: 3.2.2
04:07:46.878 DEBUG Working directory: /mnt/f/git/fengxq2014.github.io/
04:07:47.270 DEBUG Config loaded: /mnt/f/git/fengxq2014.github.io/_config.yml
04:07:47.678 DEBUG Plugin loaded: hexo-server
04:07:48.407 DEBUG Plugin loaded: hexo-deployer-git
04:07:48.415 DEBUG Script loaded: themes/next/scripts/tags/full-image.js
04:07:48.415 DEBUG Script loaded: themes/next/scripts/tags/center-quote.js
04:07:48.417 DEBUG Script loaded: themes/next/scripts/tags/group-pictures.js
04:07:48.418 DEBUG Script loaded: themes/next/scripts/merge-configs.js
04:07:48.433 DEBUG Loading database.
04:07:48.593 INFO  Start processing
04:07:48.687 DEBUG Processed: 404.html
04:07:48.687 DEBUG Processed: baidu_verify_43n6mDcyQp.html
04:07:48.689 DEBUG Processed: CNAME
04:07:48.690 DEBUG Processed: favicon.ico
04:07:48.736 DEBUG Processed: categories/index.md
04:07:48.737 DEBUG Processed: search/index.md
04:07:48.738 DEBUG Processed: tags/index.md
04:07:48.739 DEBUG Processed: about/index.md
04:07:48.784 DEBUG Processed: _posts/Node入门.md
04:07:48.833 DEBUG Theme config loaded.
04:07:48.834 DEBUG Processed: _config.yml
04:07:48.936 DEBUG Processed: source/css/main.styl
04:07:48.937 DEBUG Processed: source/images/cc-by-nc-nd.svg
04:07:48.938 DEBUG Processed: source/images/cc-by-nc-sa.svg
04:07:48.938 DEBUG Processed: source/images/cc-by-nc.svg
04:07:48.939 DEBUG Processed: source/images/cc-by-nd.svg
04:07:48.939 DEBUG Processed: source/images/cc-by-sa.svg
04:07:48.939 DEBUG Processed: source/images/cc-zero.svg
04:07:48.939 DEBUG Processed: source/images/quote-l.svg
04:07:48.940 DEBUG Processed: source/images/searchicon.png
04:07:48.940 DEBUG Processed: source/images/placeholder.gif
04:07:48.940 DEBUG Processed: source/images/cc-by.svg
04:07:48.941 DEBUG Processed: source/images/loading.gif
04:07:48.941 DEBUG Processed: source/images/quote-r.svg
04:07:48.972 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: watch /mnt/f/git/fengxq2014.github.io/source/ EPERM
    at exports._errnoException (util.js:873:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
04:07:49.013 DEBUG Processed: languages/en.yml
04:07:49.014 DEBUG Processed: languages/fr-FR.yml
04:07:49.014 DEBUG Processed: languages/pt.yml
04:07:49.014 DEBUG Processed: languages/default.yml
04:07:49.014 DEBUG Processed: languages/de.yml
04:07:49.184 DEBUG Processed: layout/category.swig
04:07:49.184 DEBUG Processed: layout/_layout.swig
04:07:49.185 DEBUG Processed: layout/index.swig
04:07:49.185 DEBUG Processed: layout/post.swig
04:07:49.185 DEBUG Processed: layout/tag.swig
04:07:49.185 DEBUG Processed: layout/page.swig
04:07:49.185 DEBUG Processed: layout/archive.swig
04:07:49.189 DEBUG Processed: languages/ja.yml
04:07:49.189 DEBUG Processed: languages/zh-tw.yml
04:07:49.189 DEBUG Processed: languages/ru.yml
04:07:49.189 DEBUG Processed: languages/zh-Hans.yml
04:07:49.190 DEBUG Processed: languages/zh-hk.yml
04:07:49.198 DEBUG Processed: source/vendors/font-awesome/bower.json
04:07:49.198 DEBUG Processed: source/vendors/font-awesome/HELP-US-OUT.txt
04:07:49.199 DEBUG Processed: source/vendors/fastclick/README.md
04:07:49.199 DEBUG Processed: source/vendors/fastclick/bower.json
04:07:49.200 DEBUG Processed: source/vendors/jquery_lazyload/CONTRIBUTING.md
04:07:49.201 DEBUG Processed: source/vendors/jquery_lazyload/README.md
04:07:49.204 DEBUG Processed: source/vendors/jquery_lazyload/bower.json
04:07:49.204 DEBUG Processed: source/vendors/jquery_lazyload/jquery.lazyload.js
04:07:49.205 DEBUG Processed: source/vendors/fastclick/LICENSE
04:07:49.206 DEBUG Processed: source/js/src/hook-duoshuo.js
04:07:49.207 DEBUG Processed: source/js/src/motion.js
04:07:49.208 DEBUG Processed: source/vendors/jquery_lazyload/jquery.scrollstop.js
04:07:49.208 DEBUG Processed: source/js/src/scrollspy.js
04:07:49.209 DEBUG Processed: source/js/src/utils.js
04:07:49.211 DEBUG Processed: source/vendors/velocity/bower.json
04:07:49.212 DEBUG Processed: source/js/src/affix.js
04:07:49.213 DEBUG Processed: source/vendors/velocity/velocity.min.js
04:07:49.213 DEBUG Processed: source/vendors/velocity/velocity.ui.js
04:07:49.215 DEBUG Processed: source/js/src/bootstrap.js
04:07:49.216 DEBUG Processed: source/vendors/velocity/velocity.ui.min.js
04:07:49.238 DEBUG Processed: source/vendors/jquery/index.js
04:07:49.289 DEBUG Processed: layout/_macro/post-collapse.swig
04:07:49.292 DEBUG Processed: layout/_macro/reward.swig
04:07:49.292 DEBUG Processed: layout/_macro/sidebar.swig
04:07:49.293 DEBUG Processed: layout/_scripts/baidu-push.swig
04:07:49.293 DEBUG Processed: layout/_scripts/boostrap.swig
04:07:49.293 DEBUG Processed: layout/_partials/duoshuo-hot-articles.swig
04:07:49.293 DEBUG Processed: layout/_scripts/vendors.swig
04:07:49.293 DEBUG Processed: layout/_macro/post.swig
04:07:49.293 DEBUG Processed: layout/_partials/head.swig
04:07:49.294 DEBUG Processed: layout/_partials/footer.swig
04:07:49.294 DEBUG Processed: layout/_partials/pagination.swig
04:07:49.294 DEBUG Processed: layout/_partials/header.swig
04:07:49.294 DEBUG Processed: layout/_partials/search.swig
04:07:49.295 DEBUG Processed: layout/_partials/comments.swig
04:07:49.295 DEBUG Processed: layout/_scripts/commons.swig
04:07:49.295 DEBUG Database saved
04:07:49.296 FATAL watch /mnt/f/git/fengxq2014.github.io/source/ EPERM
Error: watch /mnt/f/git/fengxq2014.github.io/source/ EPERM
    at exports._errnoException (util.js:873:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/mnt/f/git/fengxq2014.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by yodahuang** [comment]
That might be cased by file system watching is not implemented currently, see [this issue](https://github.com/Microsoft/BashOnWindows/issues/216)for details.

By the way, how can you even see this error? On my bash on Windows, it jest tells me that `local hexo not found` and I can't even run `hexo server`

**Comment by Fengxq2014** [comment]
I just use `nvm` to install node,and use hexo

**Comment by skirunman** [comment]
Having the exact same issue on Windows 10 with Node v4.4.7. Using git bash.

**Comment by skirunman** [comment]
I was able to run on Windows 10 by passing the static flag to the server.
`hexo server -s`

**Comment by heyheyforhello** [comment]
@skirunman 
your solution works!!! thanks very much

**Comment by Fengxq2014** [comment]
@skirunman , your solution works!!!

**Comment by djensen47** [comment]
So, this is not really a solution, it's a temporary workaround. I realize the root issue is with Bash for Windows. I do know that `supervisor` works on Bash for Windows. Would there be a possibility of another workaround or fix?

**Comment by Fengxq2014** [comment]
waiting for Microsoft to fix it

**Comment by Fengxq2014** [comment]
This should now work in Windows 10 Insider builds >= 14942
