### ISSUE TITLE
site locale sometimes fr?

### ISSUE THREAD

**Issue by ekremkaraca** [hexojs/hexo#2089]
## Environment Info

``` shell
➜  hexo-site git:(master) ✗ node -v                               
v6.3.1
➜  hexo-site git:(master) ✗ npm -v                                
3.10.3
```

Your site `_config.yml`

```
# Hexo Configuration
## default config
```

Your theme `_config.yml`

```
# Hexo Configuration
## o da default
...
```

Plugin version(`npm ls --depth 0`)

```
## o bile deafult amk
```
## For question

Yesterday, I made fresh install of hexo, then I run `hexo server` and opened site and I saw site interface is French. I setup language var to `en` on config file. After restart, it became English. Then, today when I first started `hexo server`, it became French again (although language var on config var is still `en`). For my local environment, I'm using Ubuntu 16.04 with English language with some Turkish locale definitions seen below:

``` shell
➜  hexo-site git:(master) ✗ locale 
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=tr_TR.UTF-8
LC_TIME=tr_TR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=tr_TR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=tr_TR.UTF-8
LC_NAME=tr_TR.UTF-8
LC_ADDRESS=tr_TR.UTF-8
LC_TELEPHONE=tr_TR.UTF-8
LC_MEASUREMENT=tr_TR.UTF-8
LC_IDENTIFICATION=tr_TR.UTF-8
LC_ALL=
```

I wonder what is wrong.

**Comment by NoahDragon** [comment]
https://github.com/wzpan/hexo-theme-freemind/issues/51
I got the similar issue, simply remove the language yml file will solve the problem.
