### ISSUE TITLE
how to replace the url in all MD files in one shot?

### ISSUE THREAD

**Issue by dslztx** [hexojs/hexo#2091]
I use third-party service to store my pictures which are referenced in my MD files using the absolute urls,for example,"http://www.example.com/1.jpg" in which "wwww.example.com" is the root url the service provider provides.

How could I replace the root url within all MD files in one shot if I get another different root url someday?
Or could anyone tell me if there exists a global variable I can use,so I only need to change the value of variable in the future?

Thanks very much.

**Comment by hatched** [comment]
I'm not sure if there is anything build into hexo but I would use a shell script with `sed`. This question on SO outlines everything that you'd need to know: http://stackoverflow.com/questions/10445934/change-multiple-files

sed: https://www.gnu.org/software/sed/manual/sed.html

**Comment by dslztx** [comment]
I have thought of the solution you provides,but I want to find some built-in tools to finish my job.
Thank you very much anyway for your quick answer!
@hatched
