### ISSUE TITLE
电脑恢复出厂设置，hexo重新安装

### ISSUE THREAD

**Issue by xinpan2** [hexojs/hexo#2092]
没有做任何的备份，我之前的博客中有134篇文章，md文件全部没有了，如果我继续安装hexo发表文章，那么就会更新为只有1篇文章么？

**Comment by heymind** [comment]
会的，包括主题之类的也会被覆盖掉。理想的方案可以写个脚本将博客里的文章再转为md文件....但效果不好说。

**Comment by xinpan2** [comment]
问题解决， 我的解决方法是手动复制以前网站上的博客，然后再init网站。以后大家记得备份好！！！文章很重要！！！！最要利用可以自动备份的软件，多几分准备！！
