### ISSUE TITLE
hexo deploy部署到github上，不起作用，没有报错。

### ISSUE THREAD

**Issue by yzfdjzwl** [hexojs/hexo#2096]
本地可以浏览
网上说的很多方法都解决不了。
把配置文件删除掉或者乱改deploy部分的内容，仍然不会报错。
不知道是哪个地方出现了问题。

**Comment by renld** [comment]
我也是这样...本地可以加载但是不能愉快的deploy
[暂时这样解决发布问题](http://renld.cn/2016/08/17/GitLearn/)

**Comment by Loveforkeeps** [comment]
注意YML配置文件的格式,你们的deploy选项的:后面有没有空格
