### ISSUE TITLE
Hexo本地正常，部署到网站上部分功能无法加载

### ISSUE THREAD

**Issue by Yukizzz** [hexojs/hexo#2097]
我的[博客](https://yukizzz.github.io/)本地预览的时候一切功能正常，但是部署到网站上后，页面下方的多说评论加载不出来，而且下面的分享按钮也无法跳转。
检查源代码一切正常，但是就是加载不出来，请问要如何解决呢？

**Comment by Yukizzz** [comment]
额事实证明只是多说抽风了，什么都没改评论内容就突然可以加载出来了，但是页面下方的分享按钮还是无法正常跳转，点击任何一个分享图标都是跳到当前页面顶端而已，但是在本地是可以正确跳转到相应页面的。求教这是为什么，难道又是xx抽风23333？

**Comment by Xuanwo** [comment]
检查一下JS有没有正确加载

**Comment by HappyAdu** [comment]
不知道怎么，疑似自己在github直接加了一个reademe文件。博客就加载不出来内容了。JS报错等等。本地就可以，不知道怎么弄。求指教。
Failed to load resource: the server responded with a status of 404 (Not Found)
![image](https://cloud.githubusercontent.com/assets/18397775/20038714/6ebe83c2-a473-11e6-837b-9602ca241820.png)

出来是这样的空白
![image](https://cloud.githubusercontent.com/assets/18397775/20038728/95f750d6-a473-11e6-9f22-3f16960491b8.png)

**Comment by yycsrkl** [comment]
我也曾遇到这样的问题，没有找到原因，但好在是我的博客没多少东西，所以就全部删掉重新来了一遍。建议你从目录结构上找找原因。

**Comment by HappyAdu** [comment]
好吧，看来只有重新来一遍了

**Comment by NoahDragon** [comment]
@HappyAdu 你的是因为NexT主题，更新到最新版本即可修复~
iissnan/hexo-theme-next#1214

**Comment by jetyu** [comment]
@HappyAdu  @yycsrkl  解决办法在这里：不用重新更新。。。
https://jetyu.github.io/2016/11/04/20161104/

**Comment by yycsrkl** [comment]
@jetyu 去看了一下，如果方法有效的话，那就确实是路径的问题，可是造成这种状况的原因是什么呢？如果下次还发生这种状况，难道再把lib改成source?

**Comment by jetyu** [comment]
@yycsrkl GitHub Pages的锅。。。。

**Comment by yycsrkl** [comment]
@jetyu okay got it

**Comment by 8bun** [comment]
请问有好的解决方案吗？

**Comment by kaaier** [comment]
本地正常，deploy之后网站没有渲染效果，想问下到底是什么原因啊。。。。。。。。！尝试了各种解决方法

**Comment by 8bun** [comment]
没办法就重新搭一个吧，我也是这样做的

**Comment by BRAN-D** [comment]
> 本地正常，deploy之后网站没有渲染效果，想问下到底是什么原因啊。。。。。。。。！尝试了各种解决方法

我也是没有渲染，请问你解决了吗

**Comment by 8bun** [comment]
您好，邮件已收到，如果有什么问题，我会尽快回复。
