### ISSUE TITLE
No _draft folder in source package.

### ISSUE THREAD

**Issue by drashti4** [hexojs/hexo#2099]
node -v -> v0.10.25

I have setup hexo in my ubuntu 14.04 

$ hexo init <folder>
$ cd <folder>
$ npm install

all command run without failure.
But There is no draft folder in my source  folder.Which is mention in https://hexo.io/docs/setup.html.And I have one more folder while intializing hexo that is node_module

├── _config.yml
├── package.json
├── scaffolds
├── source
|   ├── _drafts
|   └── _posts
└── themes

**Comment by yangyuji12** [comment]
I have met the same problem, sad
