### ISSUE TITLE
Install problems.

### ISSUE THREAD

**Issue by Drakenhart** [hexojs/hexo#2104]
I try to follow the guidelines and get errors. I try to fix it as per the documentation and get more errors. At this point my frustration levels are very high and I need a simple walk through.

I have uninstalled and reinstalled things over and over and over again, and at this point am concerned that there may be settings that didn't get reset? I don't know enough to be sure.

STEPS:

Installed Git defaults (set it to run in bash and not path).
install node.js
tried to install hexo - it error'd out
looked up in the documentation
ran powershell as admin
updated the version of npm to 3.10.*
tried to reinstall hexo in cmd line
two warnings appeared:
**npm warn optional skipping failed optional dependency
 /hexo-cli/chokidar/fsevents:**
**npm warn notsup not compatible with your operating system or architecture: fsevents@1.0.14**

Note, my level of Newb is "I can't decipher this."

Background: I haven't touched a command line since early 1999 (and that was to learn how to ftp into my web server) and all the "beginner" stuff I find just confuses me more. I'm more of a designer then a coder, and programing (I did early DOS programming in the 80's as a kid but that's it).

Note, I'm a single parent w/no time to devote hours to this. I was looking for something "simple" to install and ran into error walls from the start.

I'm about to say screw it, and just use notepad, old school style, because there is nothing SIMPLE to setting up ANY static site generators. I have tried Jekyll, Hugo, Metalsmith, and Hexo. I opted for Hexo because it's based in a language I'm learning.

I feel like I am drowning when all I want to do is get a tool to do site designs that saves me time (don't want to do the coding long hand), offers something simpler then wordpress, and saves my wrists and sanity.

**Comment by NoahDragon** [comment]
The warning is okay.
