### ISSUE TITLE
multi-line comment highlight 区块注释高亮问题

### ISSUE THREAD

**Issue by hefengxian** [hexojs/hexo#2110]
## Hexo version(`hexo -v`)

```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Linux 4.4.0-34-generic linux x64
http_parser: 2.7.0
node: 5.12.0
v8: 4.6.85.32
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2h
```

区块注释代码高亮依然有问题，高亮的时候只是对区块注释第一行做了处理，后面的都没有处理到，看到这个Issue

 [Is this a bug of util.highlight ? ](https://github.com/hexojs/hexo/issues/774) 
#774

里面说3.0会解决的，好像我都用3.2.2了还是有问题

![2016-08-23 15-52-19](https://cloud.githubusercontent.com/assets/4338497/17884266/f2117e10-6949-11e6-8735-c9c39f48b2d2.png)

**Comment by Jamling** [comment]
试试hexo-filter-highlight插件

**Comment by ibufu** [comment]
```
hexo: 3.3.7
hexo-cli: 1.0.2
os: Linux 4.8.0-56-generic linux x64
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```
还是有问题
