### ISSUE TITLE
Mac 下hexo 配置完成之后 为什么在localhost:4000中打不开

### ISSUE THREAD

**Issue by jsonhu** [hexojs/hexo#2112]
按照网上的文章和hexo官方的文档来下载hexo和配置hexo,等到执行hexo s的时候,在chome中打开http://localhost:4000/的时候打不开,在网上查了一些原因,说有可能是端口被占用了,hexo s -p 5000换了端口还是不行, 是因为mac电脑的问题吗,哪位大神能告诉我一下

**Comment by perixiaowan** [comment]
你执行命令之后，提供执行后提示的详细信息？ 如果查看端口， 可以用 netstat -ntpl 查看下是否被占用？如占用了该端口，需要kill下，如没有占用，在查看hexo是否在运行，可以使用ps -ef | grep 'hexo' 查下

**Comment by jihan1098114** [comment]
我也遇到这个问题了，是因为4000端口被占用，你换个端口号试试hexo s -p <port>
