### ISSUE TITLE
hexo执行clean 以及deploy时报错提示 operation not permitted

### ISSUE THREAD

**Issue by gzponline** [hexojs/hexo#2113]
我想换一个icon，换完就报错，请问是icon的问题吗 ，我想要怎么解决，之前一直正常使用
![image](https://cloud.githubusercontent.com/assets/12186221/17926196/9e4bdf6c-6a22-11e6-9635-89f4be6935e6.png)

**Comment by perixiaowan** [comment]
你的icon放在哪里的呢？

**Comment by gzpgzpgzp** [comment]
source里面

**Comment by hefengxian** [comment]
我觉得可能是你把文件放在C盘根目录的缘故，你放到当前的用户目录下面去或者其他的盘试试

**Comment by gzpgzpgzp** [comment]
ok了   我也不知道为什么  过一段时间就好了

**Comment by gzpgzpgzp** [comment]
谢谢了  我也不知道怎么回事  过几天就好了
