### ISSUE TITLE
Latex 的渲染问题

### ISSUE THREAD

**Issue by ydeng11** [hexojs/hexo#2115]
$ \frac{1}{\sqrt{2\pi}} e^{\frac{(-y)^2}{2}} + \frac{1}{\sqrt{2\pi}} e^{-{\frac{{(-y)}^2}{2}}} $

我使用的是next主题，开启了Mathjax的服务。用的是单个$号在表达式两侧。

在文章中一切都没有问题除了上门这一行公式，在生成静态文件时，系统报错无法继续生成，应该是渲染公式的问题。
我查了很多，都提了下划线会变成em的问题。但是我这一行没有下划线，所有实在不明白。我已经测试过了，这个tex的表达式是正确的，如下所示。谢谢大家！
![](http://oc82vc8fw.bkt.clouddn.com/2016/08/25/CodeCogsEqn.gif)

**Comment by ShixiangWan** [comment]
我也遇到了这个问题：MathType转出来的公式会有“多余”的括号{}。

你上面公式，换成下面的就可以成功在Hexo上渲染（区别在于{(-y)}^2换成了(-y)^2）：
`
$ \frac{1}{\sqrt{2\pi}} e^{\frac{(-y)^2}{2}} + \frac{1}{\sqrt{2\pi}} e^{-{\frac{(-y)^2}{2}}} $
`
