### ISSUE TITLE
文章能根据年份产生目录吗

### ISSUE THREAD

**Issue by xwartz** [hexojs/hexo#2119]
`source/_posts/` 目录下的 `md` 文章都只能是一级的，能按年份来多生成一级目录吗

**Comment by uanheng** [comment]
可以，有插件，貌似

2016年8月28日 下午11:35，"xwartz" <notifications@github.com>写道：

**Comment by perixiaowan** [comment]
直接在配置文件config.yml里，配置即可


发自 网易邮箱大师
在2016年08月28日 23:36，Sheng Yuan 写道:
可以，有插件，貌似

2016年8月28日 下午11:35，"xwartz" <notifications@github.com>写道：

**Comment by xwartz** [comment]
@perixiaowan 

@uanheng 
请问要怎么配置呢，在文档上好像没有看到 https://hexo.io/zh-cn/docs/configuration.html#目录

**Comment by perixiaowan** [comment]
能看到我添加的图片吗？试试图片选中的那句。


发自 网易邮箱大师
在2016年08月29日 00:47，xwartz 写道:

@perixiaowan

@uanheng
请问要怎么配置呢，在文档上好像没有看到 https://hexo.io/zh-cn/docs/configuration.html#目录

**Comment by perixiaowan** [comment]
不好意思，之前用手机邮箱发的，以为图片可以显示呢，我再给你发一次，你按照图示试一下。
![126673360](https://cloud.githubusercontent.com/assets/7885334/18038113/09716806-6dc6-11e6-8da8-e8cdbb96fcdc.jpg)

**Comment by xwartz** [comment]
@perixiaowan  
这个只会让文章的地址变成这样的结构，但是本地的所有 markdown 文件还是只在 `source/_posts/` 目录下，并不会按照年月日产生目录结构。

**Comment by perixiaowan** [comment]
不知道你试了么？然后不行？我的是这样做，并且使用hexo new ‘文章名’ 是可以生产对应的年月日目录，如果你没有试，要不要先试一试？如果试了还不行，我再帮你看看是不是其他原因。

**Comment by perixiaowan** [comment]
不好意思啊，我少些了一句 你还需要添加下面一句配置
new_post_name: :year/:month/:day/:title.md # File name of new posts

**Comment by xwartz** [comment]
@perixiaowan  

谢谢，可以了。

我原来设置了 new_post_name: :year-:month-:title.md # File name of new posts

然后一直生成不了目录结构，原来是斜杠才行...

**Comment by perixiaowan** [comment]
好的，不客气：）

**Comment by welpher** [comment]
Thank you! It works for me.
