### ISSUE TITLE
What's the usage of relative_link? 

### ISSUE THREAD

**Issue by aleung** [hexojs/hexo#2126]
I set `relative_link` to either `true` or `false`, didn't see difference in rendered output.

I have my site `root` set to `/blog/`. Inside a blog post, I want to link to another post by URL `/2016/08/30/post-name/`. Now it's rendered as `http://yoursite.com/2016/08/30/post-name/`, which is incorrect because missing `blog`. I expect it to be `http://yoursite.com/blog/2016/08/30/post-name/`. How could I do?

**Comment by NoahDragon** [comment]
In your case you should set the root to /.
