### ISSUE TITLE
hexo不支持markdown的参考文献式的连接吗？

### ISSUE THREAD

**Issue by niceczj** [hexojs/hexo#2127]
如题，hexo能实现以下参考链接吗？

I get 10 times more traffic from [Google](http://google.com/) than from
[Yahoo](http://search.yahoo.com/) or [MSN](http://search.msn.com/).

**Comment by sabrinaluo** [comment]
参考文献式的链接跟markdown解析成html有关
[hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) 
[marked](https://github.com/chjj/marked) 最终取决于这个库解析的html
