### ISSUE TITLE
how to use hexo dependencies module in theme?

### ISSUE THREAD

**Issue by Jamling** [hexojs/hexo#2128]
I wrote a theme for hexo, it dependent on `lodash` and `cheerio` module. I found hexo 3.0 dependent on the two modules also. So I want to use the hexo dependencies instead

``` js
// require ('lodash');
require ('../../../node_modules/hexo/node_modules/lodash');
```

the code under `script` of theme
And meet an error by other users (hexo 3.0).
`Error: Cannot find module '../../../node_modules/hexo/node_modules/lodash'`

More info: [https://github.com/Jamling/hexo-theme-nova/issues/9](https://github.com/Jamling/hexo-theme-nova/issues/9) 

I's my code right? If not, please tell me how to require hexo dependencies in theme script? Thank you~

**Comment by NoahDragon** [comment]
I think you can use lodash directly, as it is a dependency of Hexo.

**Comment by timpulver** [comment]
But what’s the best way to use libraries installed with npm in a theme?
E.g. [fuse.min.js](https://github.com/krisk/Fuse) (`node_modules/fuse.js/src/fuse.min.js`)

**Comment by LouiseMcMahon** [comment]
if you create a file in your scripts folder you can then declare any modules as globals (dont use var)
'''
h2p = require('html2plaintext');
'''

Then you can access it as you would normally after you had required it. It's not the greatest solution as it pollutes the global space but it's the best I have found.
