### ISSUE TITLE
V4 with Vue SSR

### ISSUE THREAD

**Issue by mamboer** [hexojs/hexo#2131]
## V4 with Vue 2.0 server side rendering

Swig is dead, nunjucks is old-fashioned, Vue is hot and supporting SSR in 2.0 .

Hope to see Hexo be in love with Vue 2.0 .

**Comment by wildplant** [comment]
I need extend feature, can vue2.0 ssr support?

**Comment by NoahDragon** [comment]
I have discussed this with an Vue fan. The conclusion is Hexo couldn't do much with Vue, except the theme.
