### ISSUE TITLE
【For help】deploy命令没有反应是怎么回事？("hexo deploy" don't run)

### ISSUE THREAD

**Issue by Lauric** [hexojs/hexo#2132]
C:\Users\lenovo\Documents\GitHub> hexo deploy
C:\Users\lenovo\Documents\GitHub>

**Comment by Lauric** [comment]
还有输入 hexo generate后显示的内容都是空的
C:\Users\lenovo\Documents\GitHub> hexo generate
INFO  Start processing
INFO  Files loaded in 2.37 s
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: fancybox/fancybox_loading.gif
INFO  Generated: fancybox/blank.gif
INFO  Generated: fancybox/fancybox_overlay.png
INFO  Generated: fancybox/fancybox_sprite.png
INFO  Generated: fancybox/fancybox_loading@2x.gif
INFO  Generated: fancybox/jquery.fancybox.css
INFO  Generated: fancybox/fancybox_sprite@2x.png
INFO  Generated: archives/2016/index.html
INFO  Generated: archives/2016/09/index.html
INFO  Generated: fancybox/jquery.fancybox.js
INFO  Generated: fancybox/jquery.fancybox.pack.js
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.css
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.css
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.js
INFO  Generated: fancybox/helpers/jquery.fancybox-media.js
INFO  Generated: js/script.js
INFO  Generated: css/fonts/fontawesome-webfont.eot
INFO  Generated: css/style.css
INFO  Generated: fancybox/helpers/fancybox_buttons.png
INFO  Generated: css/fonts/fontawesome-webfont.woff
INFO  Generated: css/fonts/FontAwesome.otf
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.js
INFO  Generated: css/images/banner.jpg
INFO  Generated: css/fonts/fontawesome-webfont.ttf
INFO  Generated: css/fonts/fontawesome-webfont.svg
INFO  Generated: 2016/09/03/hello-world/index.html
INFO  28 files generated in 7.28 s

**Comment by stackOverMind** [comment]
首先你要配置 deploy 这一项
比如：
```
deploy:
  type: git
  repo: git@github.com:WildDogTeam/WildDogTeam.github.io.git
```

## 有一点非常重要，冒号后面有个空格，这个很坑
