### ISSUE TITLE
post settings

### ISSUE THREAD

**Issue by johntom** [hexojs/hexo#2135]
Hi.
Is there a way to add fields to the post headings form? I'd like to add and thumnail image to display with post along with an author.
I use the corporate theme from http://hexotest.computerlab.io/ where you can see how the make use of the thumnail.
Thanks,
John
in the md file

```
title: Notes On Creating A Hexo Theme 
date: 2016-01-02
tags:
- Programming
- Design
category: Hexo
lede: "Information about developing a Hexo theme, including common gotchas that we ran into.  This posts covers setting up a hexo development environment, and the seperation of theme and content."
thumbnail: https://s3.amazonaws.com/ptsteadman-images/hexo.png

---
```

**Comment by NoahDragon** [comment]
You could access the new front matter field in the theme layouts.
