### ISSUE TITLE
请问默认是否有在首页不展开文章全部内容这个参数？

### ISSUE THREAD

**Issue by 2ue** [hexojs/hexo#2136]
首页加载的时候，第一页的全部文章都是完全展示的，这样个人觉得不利于首屏的快速浏览，请问默认配置里是否有可以使得文章在首页只显示一部分内容的参数么？

**Comment by xuelangZF** [comment]
`<--more-->`

**Comment by 2ue** [comment]
more这个参数是在每个post页面都要添加么？还是说统一在config里面配置呢？应该如何使用呢？

**Comment by xuelangZF** [comment]
官方文档有详细说明，建议你看下

**Comment by sabrinaluo** [comment]
这个取决于你使用的主题是否支持自动截断，比如你可以参考这个http://blog.hiitea.xyz 并不需要在每篇文章都加 `<--more-->`

自动截断功能在这里实现
https://github.com/sabrinaluo/hexo-theme-normcore/blob/85a21b662d3fbffbe379fe8636b32e86508322be/layout/_partial/excerpt.ejs

**Comment by 2ue** [comment]
明白了，这个功能需要我自己开发是吧？

**Comment by NoahDragon** [comment]
只需在你需要分断的地方加`<!-- more -->`即可。
