### ISSUE TITLE
请问在styl文件中能否访问到post里的设置的参数，如果可以应该怎访问呢？

### ISSUE THREAD

**Issue by 2ue** [hexojs/hexo#2138]
我在每个文章页面要根据一些post里面的参数自定义设置一些样式，那么我应该如何在.styl文件中读取post里面的参数呢？比如title

**Comment by 2ue** [comment]
我在hexo的默认主题中看到了hexo-config('title')的引用方式，这个是获取到了默认配置里面的参数，但是我现在需要获取文章里面的参数

**Comment by NoahDragon** [comment]
我觉得可以通过template（ejs，swig）判断post的参数来选择style。
