### ISSUE TITLE
本地启动服务在首页page.title获取不到(实际在首页使用它来作为的条件判断)，但是deploy到github上所有的都是获取到了第一篇post的title

### ISSUE THREAD

**Issue by 2ue** [hexojs/hexo#2143]
header.ejs

``` js
<% if (page.title){ %>
    <% if (page.backgroundImg){ %>
    <div id="banner-post-user" style="background: url(/css/images/<%- page.backgroundImg %>) center #000; "></div>
    <%} else { %>
    <div id="banner-post-dflt"></div>
    <% } %>
  <%} else { %>
    <div id="banner"></div>
  <% } %>
```

代码如此，我是相当在主页和在文章页banner显示得不一样，然后就用了page.title或昨天见判断
最开始用的post.title最为条件判断，但是在本地generate是后抛错，提示post未定义

**Comment by Xuanwo** [comment]
没看懂你在说什么，麻烦使用英文或者中文重新描述一遍

**Comment by 2ue** [comment]
我把hexo的默认主题copy了一份，在这个基础上进行修改。

我在首页使用page.title作为条件判断，在解析出来和我预期的一样：首页page.title解析为空，文章详情页page.title解析为文章的title。但是当我generate后push到github上后，访问的效果却不是我预期的：page.title全部都解析成了第一篇post的title.

最开始，我使用post.title来作为判断，但是在本地generate的时候抛错，提示post未定义，但是在其他页面(其他默认的.ejs文件的post.title是能正常解析的)

**Comment by NoahDragon** [comment]
@2ue 看网站似乎这个issue已经解决了，可否关闭？
