### ISSUE TITLE
if page.raw's content is more than 1800 Simplified Chinese word, garbled will apear

### ISSUE THREAD

**Issue by edeity** [hexojs/hexo#2149]
following is my code

``` jade
doctype html
html
    head
        meta(http-equiv="Content-Type", content="text/html; charset=utf-8")
    body
        main#content-main.section
            div= page.raw
```

and if `page.raw`'s content is more than 1800 Simplified Chinese word(not sure, about 2000);

Garbled will appear;

but english word is ok(even more one hundred thousand)

**Comment by edeity** [comment]
i just found that is not the error of `hexo-renderer-marked`

following is my code

```jade
doctype html
html
    head
        meta(http-equiv="Content-Type", content="text/html; charset=utf-8")
    body
        main#content-main.section
            div= page.raw
```

and if `page.raw`'s content is more than 1800 Simplified Chinese word(not sure, about 2000); 

Garbled will appear;

but english word is ok(even more one hundred thousand)

**Comment by eclipselu** [comment]
I'm having this issue too.

**Comment by edeity** [comment]
I delete the files and reinstall all the code, including `hexo-server` && `hexo-cli`

Just run `hexo init xxx` to build a new project and copy the theme && article;

Thanks god, things goes well;

**Comment by edeity** [comment]
I think I found the reason:
when i install the plugin `hexo-browsersync`, then the error appear(if you use jade template);
Hope help others; [browsersync plugin not work well with jade](https://github.com/hexojs/hexo-browsersync/issues/13)
