### ISSUE TITLE
Image as a link

### ISSUE THREAD

**Issue by veramartins** [hexojs/hexo#2150]
With asset folders, how can we do something like this, using the tag plugins:
`<a href="http://www.example.com"> <img src="image.jpg"> </a>`

Here's an example that works in most markdown editors, but not in hexo:

This code here: `[![Foo](http://www.google.com.au/images/nav_logo7.png)](http://google.com.au/)`

Renders this:
[![Alt_name](http://www.google.com.au/images/nav_logo7.png)](http://google.com.au/)

**Comment by veramartins** [comment]
I've been looking for a solution to this, but I can't hack it on my own. This is standard markdown and [babelmark shows](http://johnmacfarlane.net/babelmark2/?text=%5B!%5BFoo%5D(http%3A%2F%2Fwww.google.com.au%2Fimages%2Fnav_logo7.png)%5D(http%3A%2F%2Fgoogle.com.au%2F)) that almost every flavor of markdown does it well.

Is there any way I can help with this? I can kinda read the source code for hexo, but I'm not really sure what to change.

**Comment by menehune23** [comment]
Thankfully I found this workaround: https://alexdrenea.com/2016/04/28/hexo-image-hacking/

Though this REALLY needs to be addressed. It's a basic feature that should be supported, especially in pure markdown.

**Comment by veramartins** [comment]
Thanks, the workaround kinda works, but everything has to be defined in HTML, so it defeats the purpose of Hexo. The page you mentioned does point to where the error might lie:

```
$(this).find('img').each(function(){
	if ($(this).parent().hasClass('fancybox')) {
```

> So it looks that for every img tag that does not have a “fancybox” parent, this script will add a wrapper to make it fancybox. I tried disabling the fancybox from the theme but this script is still there.

Can we get some help here?

**Comment by menehune23** [comment]
I ended up doing a small bit of custom js:

    // Add 'image-link' class to all <a> tags surrounding <img> tags
    $('img').parents('a').addClass('image-link');

And the css:

    .image-link {
        display: table
        margin: auto
    }

    .image-link img {
        display: table-cell
    }

My selector is actually more descriptive than just `'img'` but you can adjust to whatever you need.

**Comment by veramartins** [comment]
I bet this issue is felt by more people (hence the ugly fixes). This really needs to be baked into hexo. Having that said, can you help me with your code? I would love to use this temporary fix, but I'm a total newb and don't know where to put it.

**Comment by menehune23** [comment]
I've got a custom theme and have it in a JavaScript file that my theme loads. But the simplest solution might be to edit one of the existing theme templates (like `layout.ejs` and put it in a `script` tag there. (Don't forget to wrap the code in a `$(document).ready()` call, which is typical for jquery)

**Comment by seaoak** [comment]
@veramartins If you use the theme "landscape" (the default theme of Hexo), you can quickly fix this issue by removing lines L88-L107 from your `themes/landscape/source/js/script.js`
https://github.com/hexojs/hexo-theme-landscape/blob/master/source/js/script.js#L88-L107

**Comment by jeffheaton** [comment]
Agreed this totally needs to be fixed.  Many of the hacks above do not work anymore, still trying to find the best hack for my situation.

**Comment by vascomartinho** [comment]
@NoahDragon 
It says in the main page (hexo.io) "All features of GitHub Flavored Markdown are supported". So, this is not an feature **request**, it's a bug, or at most, a missing feature.
Proof this is standard GitHub Markdown:
https://github.com/gabrieloshiro/github-markdown-playground/wiki#images-with-links
(also, OP's example works)

I fear the feature-request tag might have placed this issue in the back burner, where it does not belong. Can we get the ball rolling here?

**Comment by stevenjoezhang** [comment]
Image as a link is supported by markdown renderer:
```md
[![Foo](http://www.google.com.au/images/nav_logo7.png)](http://google.com.au/)
```
If fancybox causes the link to fail, this should be a bug of Hexo theme, not Hexo itself.

**Comment by veramartins** [comment]
I see where you're coming from, you're saying fancybox is causing the error, not the markdown renderer. Hear me out, though:

Hexo is neither a theme nor a markdown renderer. It's a SSG which comprises a lot of moving parts, and right now (and for the last 3+ years) hexo is just not working the way it should.

If you still think I'm not making a solid point, I'm ok with it, because I know my limitations, maybe I'm just seeing this the wrong way. In that case, could you please open an issue about this the proper way?
Thank you for looking at this issue, I have had my site with images separate from links for the last 3 years, but I still want to work in hexo.

**Comment by stevenjoezhang** [comment]
Thanks for your trust in Hexo. Sorry to hear that the markdown renderer is causing trouble for your writing for years. However, as you said
> Hexo is neither a theme nor a markdown renderer.

Sure, markdown rendering is done by Hexo renderer, not Hexo itself. May I ask which renderer and Hexo theme are you using? This will help us reproduce the bug. Thank you :)
