### ISSUE TITLE
-bash: hexo: command not found 问题....

### ISSUE THREAD

**Issue by haxwn** [hexojs/hexo#2152]
haxwn-2:Hexo Onein$ npm -v
3.10.3
haxwn-2:Hexo Onein$ node -v
v6.5.0
haxwn-2:Hexo Onein$ git --version
git version 2.10.0

haxwn-2:Hexo Onein$ npm install hexo -g
npm WARN deprecated swig@1.4.2: This package is no longer maintained
/usr/local/Cellar/node/6.5.0/libexec/npm/bin/hexo -> /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/hexo/bin/hexo

> dtrace-provider@0.6.0 install /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/hexo/node_modules/dtrace-provider
> node scripts/install.js

> fsevents@1.0.14 install /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/hexo/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/hexo/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> hexo-util@0.6.0 postinstall /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/hexo/node_modules/hexo-util
> npm run build:highlight

> hexo-util@0.6.0 build:highlight /usr/local/Cellar/node/6.5.0/libexec/npm/lib/node_modules/hexo/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

/usr/local/Cellar/node/6.5.0/libexec/npm/lib

以上是安装成功的信息,并且配置了环境变量

haxwn-2:Hexo Onein$ export PATH=/usr/local/npm/bin:$PATH
haxwn-2:Hexo Onein$ export PATH=/usr/local/node/bin:$PATH
haxwn-2:Hexo Onein$ source ~/.nvm/nvm.sh

但是结果 还是:
haxwn-2:My Blogs Onein$ hexo init <Onein>
-bash: syntax error near unexpected token `newline'
haxwn-2:My Blogs Onein$ hexo init
-bash: hexo: command not found

help me....

**Comment by haxwn** [comment]
还是打开了吧.. 一边在这找着一边儿等着....

**Comment by haxwn** [comment]
搞了两天,终于hexo的不再提示command not found 了  感谢我自己

**Comment by gaoyve** [comment]
请问楼主是如何解决的呢？
我也是这个问题...

**Comment by haxwn** [comment]
我装了nvm 然后用nvm装的

**Comment by zhangaoqiang** [comment]
npm install hexo-cli -g

**Comment by haxwn** [comment]
谢谢,已经搞定了


Original Message
Sender:占高强notifications@github.com
Recipient:hexojs/hexohexo@noreply.github.com
Cc:Oneinhaxwn@11bnb.com; State changestate_change@noreply.github.com
Date:Tuesday, Nov 1, 2016 14:31
Subject:Re: [hexojs/hexo] -bash: hexo: command not found 问题.... (#2152)


npm install hexo-cli -g

**Comment by haxwn** [comment]
我是先装的nvm 然后再装npm install hexo-cli -g


Original Message
Sender:Gerrynotifications@github.com
Recipient:hexojs/hexohexo@noreply.github.com
Cc:Oneinhaxwn@11bnb.com; State changestate_change@noreply.github.com
Date:Thursday, Sep 15, 2016 03:04
Subject:Re: [hexojs/hexo] -bash: hexo: command not found 问题.... (#2152)


请问楼主是如何解决的呢？
 我也是这个问题...

**Comment by yanlee26** [comment]
还有别的好办法 吗

**Comment by haxwn** [comment]
木有啦，我是先装了nvm才装成功的。你可以参考下我写的过程
 http://onein.cf/2016/09/25/index/#more
------------------ Original ------------------

**Comment by accfcx** [comment]
可以试一试先改成淘宝的npm源
npm install -g cnpm --registry=https://registry.npm.taobao.org
然后再把教程中的npm用cnpm替换。原blog如下[http://chitanda.me/2015/06/11/tips-for-setup-hexo/](url)
