### ISSUE TITLE
Sorting posts in archive.ejs

### ISSUE THREAD

**Issue by oryan** [hexojs/hexo#2153]
I've tried searching through the documentation to no avail.

How would one sort the posts in reverse?

My theme has this:

```
<% page.posts.each(function(post, i){ %>
    <%- partial('archive-post', {post: post }) %>
 <% }) %>
```

I've tried a few things including this:

```
<%- partial('archive-post', {post: post, orderby: "date", order: -1 }) %>
```

and also this:

```
<% page.posts.sort('date', -1).each(function(post, i){ %>
    <%- partial('archive-post', {post: post }) %>
 <% }) %>
```

Any ideas on how I can sort my posts so that the oldest is always the first in the list?

**Comment by oryan** [comment]
This seems to work.
```
<% page.posts.sort('date', 1).each(function(post, i){ %>
    <%- partial('archive-post', {post: post }) %>
 <% }) %>
```

It would be awesome if you could explain the way these types of functions work in the documentation. It's currently pretty difficult to figure out how basic theming functions work.

**Comment by soulteary** [comment]
Maybe you should add date prefix for each posts, if you won't like date prefix in permalink, you can use alias rewrite it.

The template will used to render each posts, i don't think it's good idea, if you sorting post in template and you have a lot of posts.

**Comment by oryan** [comment]
@soulteary I'm sorry, I'm afraid I don't understand what you are suggesting.

My issue has nothing to do with generating permalinks, aliases, or rendering posts.

**Comment by tommy351** [comment]
Hexo uses [warehouse](http://tommy351.github.io/warehouse/) for data modeling.

You can see [here](https://zespia.tw/warehouse/Query.html) for available query methods.
