### ISSUE TITLE
当js文件从source复制到public的时候，有奇怪的代码添加在文件中

### ISSUE THREAD

**Issue by NoahDragon** [hexojs/hexo#2155]
为了使BaiduShare支持Https，我将[BaiduShare](https://github.com/hrwhisper/baiduShare)的文件夹拷贝到source文档下。但当其中的js文件被拷贝到public文档中后，例如share.js，文件末尾会添加如下代码，从而造成js加载失败。

    t.run=p,i()});</0&&(t||(t=d,s.currentpath&&(t=s.currentpath.split(">

起先是以为安装的hexo-all-minify插件造成的问题，但发现禁用插件后，此问题仍然存在。

**Comment by soulteary** [comment]
我有过类似的需求，个人是写了一个插件hack了generate过程，对于特定目录的文件不进行渲染处理。

可参考: https://github.com/soulteary/hexo-extend-plugin

**Comment by NoahDragon** [comment]
@soulteary 谢谢，可否赐教如何使用？

**Comment by soulteary** [comment]
https://github.com/soulteary/hexo-extend-plugin/blob/master/patch/hexo/lib/plugins/generator/page.js#L12

自行修改路径，不处理某些路径文件，或者对某些文件路径的某些文件作特殊处理即可。

**Comment by NoahDragon** [comment]
@soulteary 感谢！
