### ISSUE TITLE
failed to load resource in hexo.js

### ISSUE THREAD

**Issue by LalindaSampath** [hexojs/hexo#2163]
I'm using HexoJS to create a blog. The blog I cretated using Hexo runs perfectly on localhost. My Hexo version is 3.2.2

I was able to generate the static files using hexo generate. Even though there are css files and JS files generated, they are not properly linked to the index.html. By exploring the code of index.html I found out that all the root path of all CSS, JS and Images files are wrong.
Can anyone help me to fix this issue?
![hexo](https://cloud.githubusercontent.com/assets/8786867/18522232/e29c17a8-7acc-11e6-99e0-c20c99e6ff1c.PNG)

**Comment by NoahDragon** [comment]
Could you please paste your _config.yml file? I assume the root path is wrong.

**Comment by LalindaSampath** [comment]
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Blog | Lalinda Sampath Dias
subtitle:
description:
author: Lalinda Sampath Dias
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

**Comment by NoahDragon** [comment]
Have you run `hexo generate`?

**Comment by LalindaSampath** [comment]
Yes, I did. Is there anything wrong in the _config.yml or the hexo version i'm using?

**Comment by NoahDragon** [comment]
When I directly opened the index.html from the public folder, I got the same loading failure messages. However, if I opened via  http://localhost:4000, everything works fine. I don't if this the case in your scenario.

**Comment by LalindaSampath** [comment]
It works fine when I opened via http://localhost:4000. My problem is why it showing those loading failure messages when opened the index.html from the public folder.

**Comment by NoahDragon** [comment]
Because the path is not interpreted correctly. On the server, the index.html use its relative path to retrieve the files, the relative path will be interpreted based on server setting. When opening the index file directly, there is no information about which folder should be used to locate the "/javascript/jquery.js", then it uses the system setting. That's what you see "C:/".

**Comment by LalindaSampath** [comment]
If I'm going to publish the blog I have to use  files inside the public folder. If paths cannot interpreted correctly, I have to change the paths one by one in each html file in public folder before publishing the blog. isn't it?
So, what's the point of using hexo to create blogs just to run on localhost?

**Comment by NoahDragon** [comment]
The localhost is used for preview the website. When you publish your website, it should be on a server, then the path will be interpreted correctly. What you saw on http://localhost:4000 will be same when you published your website.

**Comment by LalindaSampath** [comment]
Ok, thanks then

**Comment by ZoltinZyc** [comment]
说的是尼玛币
