### ISSUE TITLE
OutOfMemory with 3000 docs

### ISSUE THREAD

**Issue by JLKM** [hexojs/hexo#2165]
1. Having made a lot of `hexo g`'s with 100-200 docs without problems at all, I ran into a wall yesterday when trying to run a full scale hexo generation with 3000 docs.

```
$ hexo g
INFO  Start processing
INFO  Files loaded in 6.02 min
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

2. In order to avoid a 514 MB in node.js I followed the advice from [#1735](https://github.com/hexojs/hexo/issues/1735) and made the follwing changes:

```
File: C:\Users\Name\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo

Changed: #!/usr/bin/env node
To: #!/usr/bin/env node --max_old_space_size=8192

Same result:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

```

3. Then I increased memory to 12 GB:
```
File: C:\Users\Name\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo

Changed: #!/usr/bin/env node --max_old_space_size=8192
To: #!/usr/bin/env node --max_old_space_size=12288

Error again - but new prompt:
FATAL ERROR: Scavenger: semi-space copy Allocation failed - process out of memory

```

4. My laptop has only 16GB of RAM, but I put my money on the swap-file and allocated 32GB RAM to node.js/Hexo:
```
File: C:\Users\Name\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo

Changed: #!/usr/bin/env node --max_old_space_size=12288
To: #!/usr/bin/env node --max_old_space_size=32768

Same error-prompt as in 1 and 2.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

```

Worth noting:
- I get no other errors - like f.ex. the template-error in [#1763)](https://github.com/hexojs/hexo/issues/1763)

Possible culprits:
- Hexo
- Node [tranquilpeak #274](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/274)
- [V8](https://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/) - need for `–max-new-space-size=XXXX`
- My Hexo-cli setup/version - please look below

_Any advice would be most appreciated_

*My setup:*

| Name | Version |
|:------ | --------:|
| Windows | 10 |
| Node.js | 6.3.1 |
| Hexo | 3.2.2 |
| Theme | Hueman |

My full hexo-cli package.json for scrutenizing:
```
{
  "_args": [
    [
      "hexo-cli",
      ""
    ]
  ],
  "_from": "hexo-cli@latest",
  "_id": "hexo-cli@1.0.2",
  "_inCache": true,
  "_installable": true,
  "_location": "/hexo-cli",
  "_nodeVersion": "4.3.0",
  "_npmOperationalInternal": {
    "host": "packages-16-east.internal.npmjs.com",
    "tmp": "tmp/hexo-cli-1.0.2.tgz_1465818839377_0.7479208533186466"
  },
  "_npmUser": {
    "email": "tommy351@gmail.com",
    "name": "tommy351"
  },
  "_npmVersion": "3.7.1",
  "_phantomChildren": {},
  "_requested": {
    "name": "hexo-cli",
    "raw": "hexo-cli",
    "rawSpec": "",
    "scope": null,
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/hexo-cli/-/hexo-cli-1.0.2.tgz",
  "_shasum": "8ebcae88cac29254f1e9ac07f8a9f07399a8a1ae",
  "_shrinkwrap": null,
  "_spec": "hexo-cli",
  "_where": "",
  "author": {
    "email": "tommy351@gmail.com",
    "name": "Tommy Chen",
    "url": "http://zespia.tw"
  },
  "bin": {
    "hexo": "./bin/hexo"
  },
  "bugs": {
    "url": "https://github.com/hexojs/hexo-cli/issues"
  },
  "dependencies": {
    "abbrev": "^1.0.7",
    "bluebird": "^3.4.0",
    "chalk": "^1.1.3",
    "hexo-fs": "^0.1.5",
    "hexo-log": "^0.1.2",
    "hexo-util": "^0.6.0",
    "minimist": "^1.2.0",
    "object-assign": "^4.1.0",
    "tildify": "^1.2.0"
  },
  "description": "Command line interface for Hexo",
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-as-promised": "^5.3.0",
    "eslint": "^2.12.0",
    "eslint-config-hexo": "^1.0.3",
    "hexo-renderer-marked": "^0.2.10",
    "istanbul": "^0.4.3",
    "jscs": "^3.0.4",
    "jscs-preset-hexo": "^1.0.1",
    "mocha": "^2.5.3",
    "proxyquire": "^1.7.9",
    "rewire": "^2.5.1",
    "sinon": "^1.17.4"
  },
  "directories": {
    "bin": "./bin",
    "lib": "./lib"
  },
  "dist": {
    "shasum": "8ebcae88cac29254f1e9ac07f8a9f07399a8a1ae",
    "tarball": "https://registry.npmjs.org/hexo-cli/-/hexo-cli-1.0.2.tgz"
  },
  "gitHead": "fb567e2d1e32929c4183ab4fcf1a5645fb646eb2",
  "homepage": "https://hexo.io/",
  "keywords": [
    "website",
    "blog",
    "cms",
    "framework",
    "hexo",
    "cli"
  ],
  "license": "MIT",
  "main": "lib/hexo",
  "maintainers": [
    {
      "email": "tommy351@gmail.com",
      "name": "tommy351"
    }
  ],
  "name": "hexo-cli",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/hexojs/hexo-cli.git"
  },
  "scripts": {
    "eslint": "eslint .",
    "jscs": "jscs .",
    "test": "mocha test/index.js",
    "test-cov": "istanbul cover --print both _mocha -- test/index.js"
  },
  "version": "1.0.2"
}
```

**Comment by soulteary** [comment]
i also got` heap out of memory` error when i generate more than 1000 docs.
i solve it by [fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory](http://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory)

i think this issue related to both node and hexo.

if you've dump the struct of post object, you'll see a huge object, i guess if you disable some plugin and features, you can solve it.

**Comment by JLKM** [comment]
## Still not able to generate more than approx. 1200 posts

Thank you for your  advice.

- Deleted `"hexo-generator-search": "^1.0.2"` and `"hexo-generator-json-content": "^2.2.0"` from hexo package.json, but it only speeded generation up with a few seconds. It didn't make generation of more documents possible fr me.

- Followed these [recommendations](http://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory), which mentions a number of parameters capable of expanding hexo generator. I've tested them all with not so much luck. Still wonder, how the suggestions in this doc helped you out...

I soon realised that it's much easier to put the parameters directly into the [command-prompt](https://github.com/foreverjs/forever/issues/398), and the result didn't differ from putting the parameters into:

`C:\Users\Username\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo`.

#### Lessons learned from the parameters

1. --max_old_space_size=12288 --stack_size=12288

Did make it possible for me to generate about 1200 posts - opposed to a few hundreds with hexo g and no parameters. At this time I need to generate 3000 posts, but attempts to generate more than approx. 1200 posts resulted in various error (see below).

2. --optimize_for_size

Did increase the number of generations with a couple of hundreds when running hexo g with f.ex. --max_old_space_size=8192. But the parameter was not able to move the maximum number of successfully generated posts.

3. --max_executable_size=12288

Also tested with 8192, 4096 and 2048. None of the different values made any observable difference.

4. --max_new_space_size=XXXX

No help according to your source. So I didn't test that one.

#### The error-collection

1. FATAL ERROR: CALL\_AND\_RETRY\_LAST Allocation failed - JavaScript heap out of memory

The most common error in my test.

2. FATAL ERROR: Scavenger: semi-space copy Allocation failed - process out of memory.

Usually turned up when fairly close to the upper limit (but on the wrong side).

3. FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory

Only encountered once, when the upper limit was really close.

4. /c/Users/Name/AppData/Roaming/npm/hexo: line 14:  3640 Segmentation fault      node "$basedir/node_modules/hexo-cli/bin/hexo" "$@"

Showed up on one occation, when upper limit was even closer (<10 docs). This one is somewhat weird, since the referred file has not 14 lines but only 5 (see below).

```
1. #!/usr/bin/env node
2.
3. 'use strict';
4.
5. require('../lib/hexo')();
```

#### Themes
According to my tests, the themes are not to blame for the upper limit as such. Swithing themes apparently moves the upper limit of posts about 100 or 200 up or down. This is likely caused by the various amount of html needed for the different designs. In my case Icarus had the highest upper limit. Hueman ended in the middle, and the lowest amount of possible generated posts was experienced with bootstrap-blog.


#### Downgrade

After this (several days of nightmare) I went all in and downgraded to Hexo 3.1.1 - as suggested in [#1831](https://github.com/hexojs/hexo/issues/1831).

Hexo package.json was changed to:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "3.1.1",

... etc. ...
  }
}
```
The following npm install resulted in a lot of warnings:
```
npm WARN deprecated nunjucks@1.3.4: potential XSS vulnerability in autoescape mode, and with escape filter was fixed in v2.4.3
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /nunjucks/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
```

And the following hexo g with parameters not only ended in an error message. I went totally bananas returning some of the following error-lines for each entry:
```
ERROR Process failed: _posts/209B3447F4562503C1257DE10041CC6A.md
Error: Category `2013` has already existed!

at D:\vscode\hexo\Odense\tredjesite\node_modules\hexo\lib\models\category.js:71:13
at tryCatcher (D:\vscode\hexo\Odense\tredjesite\node_modules\warehouse\node_modules\bluebird\js\main\util.js:26:23)
at D:\vscode\hexo\Odense\tredjesite\node_modules\warehouse\node_modules\bluebird\js\main\method.js:15:34
at D:\vscode\hexo\Odense\tredjesite\node_modules\warehouse\lib\model.js:193:12
```

#### Upgrade
Finally I took the opposite approach and upgraded my Hexo `^3.2.0` to `3.2.2` - in order to test the absolute latest version.

Unfortunately this wasn't enough to move the upper limit, either.

---

Please, anyone, make clear once and for all, that Hexo doesn't have an unbreakable upper limit of approx. 1000 posts. And please also show exactly how to get around this limit.

**Comment by soulteary** [comment]
hold on, i'll check my config, it may helpful to you. i've generated approx. 1000+ post last month.

**Comment by soulteary** [comment]
@JLKM https://github.com/soulteary/hexo-blog/issues/1

**Comment by JLKM** [comment]
Thank you for your handful of advice. Unfortunately still no luck - at least with Hexo.

Here my comments one after one:
0. Made a test on Linux. The Linux setup has only 1 GB of RAM. Hexo generate crashed with 857 documents (take a look belo). But hexo g made it to the end with 500. This is not at all enough documents, though.

```
857 docs
# hexo clean
INFO  Deleted database.
# hexo g
INFO  Start processing
INFO  Files loaded in 15 min

<--- Last few GCs --->

 4143980 ms: Scavenge 549.4 (716.6) -> 549.3 (716.6) MB, 1345.7 / 0 ms [allocation failure].
 4144034 ms: Scavenge 549.4 (716.6) -> 549.3 (716.6) MB, 50.1 / 0 ms [allocation failure].
 4144089 ms: Scavenge 549.3 (716.6) -> 549.3 (716.6) MB, 55.5 / 0 ms [allocation failure].
 4144121 ms: Scavenge 549.6 (716.6) -> 549.5 (716.6) MB, 6.2 / 0 ms [allocation failure].
 4144129 ms: Scavenge 549.6 (716.6) -> 549.6 (716.6) MB, 6.0 / 0 ms [allocation failure].

<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: Scavenger: semi-space copy
 Allocation failed - process out of memory
Aborted

*****

**Back to Windows:**

1.	Testet double run of hexo g with 1500 docs - and no clean in between. Still no luck. See log below:
```
$ hexo g "node --stack_size=12288 --max-old-space-size=12288"
INFO  Start processing
INFO  Files loaded in 5.73 min
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

$ hexo g "node --stack_size=12288 --max-old-space-size=12288"
INFO  Start processing
INFO  Files loaded in 5.75 min
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

2. Got your plugin up and running the html-generation. Both on Node 6.3.1 and the shining new 6.6.0. Same confusing result with 1800 docs (on 16 GB RAM) and this hexo-cli/bin-setting:
`#!/usr/bin/env node --max_old_space_size=8192 --optimize_for_size --max_executable_size=8192 --stack_size=8192`

And these commands:
```
$ ./node_modules/.bin/hexo g

INFO  Start processing
INFO  Files loaded in 2.55 min
[hexo-extend-plugin@generate] convert dir list done: _posts
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**The rest:**

3.	Yes I might give it a shot on a cloud service with lot of RAM. On the other hand. Not being able to generate a few thousand docs with 16 GB RAM seems basicaly wrong.

4.	Hugo sounds like an interesting alternative - all the more with it's built-in taxonomies. But Hexo still matches my needs better at this moment, so I prefer to stick with this one.

You mention in [Hexo #2165](https://github.com/hexojs/hexo/issues/2165), that you have been able to generate 1000+ docs with Hexo last month. So have I (but not so many more than that)!

The challenge is, that I need to crete Hexo-sites with 3000-10.000 docs. Have you been able to do that? 

If yes: How did you succeed, and did you use Hexo or your own plugin?

**Comment by JLKM** [comment]
### Have given up generating more than 1000 docs at a time in Hexo

You can read more about Su Yang's and my [resultless efforts](https://github.com/soulteary/hexo-blog/issues/1) to solve this.

Options left in my view at this time:
1. Hugo (but not so many well-designed themes to choose from)
2. Node 7.X with better memory-handling
3. Hexo-fix.
4. Insanely amounts of RAM (>16 GB)

**Comment by JLKM** [comment]
After lots of failed tests with generation of thousands of docs in Windows with 16 GB RAM, I made the same tests on a Linux setup - also with 16 GB RAM.
With high hopes. But they were not fulfilled.

Created a user on Digitalocean and made an installation with Ubuntu 16.04, Node.js 6.6 and Hexo.

Then I ran a handful of tests with 2995 docs and then with 2007 docs.
*hexo g* No luck.
*hexo generate "node --max_old_space_size=12288 --optimize_for_size --max_executable_size=12288 --stack_size=12288"* No luck
*hexo generate "node --max_old_space_size=8196 --optimize_for_size --max_executable_size=8196 --stack_size=8196"* No luck

Exactly the same error each and every time (written by hand):
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: node::Abort() [hexo]
2: 0x10dc06c [hexo]
3: v8::Utils::ReportApiFailure(char const*, char const*) [hexo]
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [hexo]
5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [hexo]
6: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [hexo]
7: 0x1a78d1c092a7
Aborted (core dumped)
```
This is really frustrating.
Does anyone have a clue?

**Comment by JLKM** [comment]
Noone deserves to waste as many days, as I did, trying to tweak Hexo into generating more than 1200 docs. Nothing indicates, that it's possible at this time.
Really look forward to a solution for this issue on this otherwise great SSG.
A piece of advice, if you need this feature now: Hugo: 11.980 docs in 4 minutes and 40 seconds.

**Comment by Fantasy9527** [comment]
@hank583746309  目前我也碰到了同样的问题,文章数量在1040左右,已经开始出现同样的问题了
不知道大家是怎么解决这个问题的?

**Comment by smoke-indica** [comment]
Hexo generate debug outputs fine, final output 'Killed' & nothing output to public folder. 1 core, 1GB RAM VPS. hexo-server over generate?

**Comment by anthonyrussano** [comment]
I was able to generate over 3,000 files with 8gb of ram

I used the following:

`node --max-old-space-size=8192 node_modules/hexo-cli/bin/hexo gen -c 1 -dw`

**Comment by githubbbie** [comment]
Ok, trying on 33103 files and getting fail at 16 gb

```
#!/usr/bin/env node --max_old_space_size=16384
```

in ```node_modules/hexo-cli/bin/hexo```

**Comment by anthonyrussano** [comment]
here is the current workflow step I'm using in my github actions: 

    - name: Build site
      env:
        NODE_OPTIONS: --max-old-space-size=5168
      run: |
        npm install
        node_modules/hexo/bin/hexo gen -c 1
