### ISSUE TITLE
post的permalink不能使用 :year/:month/:day/:title/ 这些变量(不支持?)

### ISSUE THREAD

**Issue by ichenkaihua** [hexojs/hexo#2166]
node: v6.5.0
hexo: v3.2.2

_config.yaml

```
permalink: :year/:month/:day/:title/
```

source/_posts/testpost.md

```
---
title: testpost
date: 2016-09-17 07:06:55
permalink: :year/:month/:day/:title.html
tags:
---
```

最终生成的url是:

```
http://127.0.0.1:4000/2016/09/17/:year/:month/:day/:title.html/
```

**Comment by NoahDragon** [comment]
post中的front matters是不需要放permalink的。

**Comment by ichenkaihua** [comment]
@NoahDragon 我是从jekyll迁移过来的,历史原因,我那些文章有两种固定链接(一个是xxx.html,一个是/xxx),现在的碰到的问题是如何保持原有的链接不变

**Comment by NoahDragon** [comment]
@ichenkaihua 据我所知，好像Hexo目前无法支持两种固定链接。可以通过配置server的301，来讲其中一个URL的请求转移的另一个。
