### ISSUE TITLE
在hexo g执行完毕后自动执行其他脚本

### ISSUE THREAD

**Issue by imfenghuang** [hexojs/hexo#2168]
应该通过那个api来扩展呢？
我是想把构建生成的部分文件复制到其他文件夹下面

当然 如果有方法是在构建时，自动把css js img等资源文件存放大不同目录就更好了

请问大家有什么好的思路吗

**Comment by soulteary** [comment]
```before_exit```

**Comment by ayugioh2003** [comment]
樓上提供的，看起來應該是最直接的方法

我自己是另外寫 `bash` 腳本，將 `hexo g`、`cp /images /otherplaces`（複製圖片）、`hexo d`、`git push` 等等語法都包在一起，就能一起執行
