### ISSUE TITLE
categories page empty

### ISSUE THREAD

**Issue by phicarre** [hexojs/hexo#2170]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v4.5.0
```

Your site `_config.yml`
```
# Hexo Configuration
...
```

Your theme `_config.yml`
Lanscape
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.1.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug

## For question

just push question
Categories page empty

## For feature request

just push feature request

**Comment by phicarre** [comment]
1) I created a page with the command: hexo new page categories
2) In source/categories/index.md, I added type: categories in the front matter
3) In the _config.yml of the theme, I added in the menu: Categories: /categories
but my page is always empty !
What is missing ?

**Comment by NoahDragon** [comment]
Have you add categories in your post front matters?

```markdown
---
layout: post
title: Why Sun is the center of our solar system
date: '2014-07-02 22:44:44 -0400'
comments: true
categories:
  - Solar System
  - Javascript
  - Simulation
---
```

**Comment by phicarre** [comment]
yes but like that:
`categories: Javascript`

**Comment by NoahDragon** [comment]
Sorry, may I ask why you need to create categories folder and page?

My theme is FreeMind, it requires to create those to set up categories.

I also tried landscape theme, it works fine on my machine.

**Comment by phicarre** [comment]
Because I want to access to the categories from the menu. It's my choice !
Hexo doc says to modify _config.yml of the theme and to create folder in source folder.

**Comment by NoahDragon** [comment]
I just tested on the Landscape theme, I think it is not support category page. Because this is not an issue about hexo, but it's theme. I will move the issue to there.

**Comment by xitengfei** [comment]
I'm using icarus theme, and there is a layout file "categories.ejs" in the this theme directory, so I can create categories page by simply "hexo new page categories" and then change the layout of this page to 'categories'.
