### ISSUE TITLE
Allow scaffold to specify location of page.

### ISSUE THREAD

**Issue by Ziflin** [hexojs/hexo#2172]
I was hoping to be able to create a scaffold say for a "photo" and issue the command: 
`hexo new photo My Cool Photo`
And I'd like these to be placed in the `source/photos` directory.  It would be nice if the scaffold could specify the location in the front matter. Something like:
`location: photos`
It currently defaults everything to be a post which is not what I'm after as they would show up in the index/etc.  This could be a nice way to allow enumeration of things such as all the photos/etc.

Or was there some other way to do this already that I missed?

**Comment by stevenjoezhang** [comment]
There is a discussion about it: #1675
I'm closing this issue. Please join the discussion there :)
