### ISSUE TITLE
求助，hexo d -g 的时候提示我没有xcode权限，然后按照提示操作之后，仍然推送失败。连接不到index.html??

### ISSUE THREAD

**Issue by mengLLLL** [hexojs/hexo#2173]
Error: EACCES: permission denied, unlink '/Users/Desktop/blog/test/.deploy_git/archives/index.html'
    at Error (native)

一会说连接不到main.css一会是连接不到index.html，很奇怪啊，一切出错都是xcode更新之后……

**Comment by soulteary** [comment]
```permission denied```, 无访问权限，可以[参考命令](http://www.soulteary.com/2015/05/31/npm-on-macosx.html)，修改文件授权试试看。

```
sudo chown -R `whoami`:staff /Users/Desktop/blog/
```

**Comment by mengLLLL** [comment]
好像是xcode的问题，更新之后就不能推了，xcode难道要配置吗？我开始配置的时候就没有动过xcode

**Comment by NoahDragon** [comment]
如果近期更新过xcode，可能需要打开xcode去同意下新的用户协议。
