### ISSUE TITLE
INDEX file has empty lines

### ISSUE THREAD

**Issue by mCapricornus** [hexojs/hexo#2174]
## Problem decription
So I configured Hexo and NexT theme, and after
``` bash
hexo g
```
All the generated index.html (like index.html, about/index.html and archives/2016/09/index.html) have strange empty lines inside, which is not expected.
> Visit [this site](https://github.com/mCapricornus/mcapricornus.github.io/blob/master/index.html) to see the content of my index.html file, with a lot of strange empty lines in it.

I don't know whether it's [*Hexo*](http://hexo.io/) or [*NexT theme*](http://theme-next.iissnan.com/) that is responsible for this.
Thanks if you could help me!

**Comment by NoahDragon** [comment]
That empty spaces seems normal, as browsers will not show them.

You also could use https://github.com/unhealthy/hexo-all-minifier plugin to remove those empty lines, and shrink html file size to optimize the access speed.
