### ISSUE TITLE
How to modify size of asset_img

### ISSUE THREAD

**Issue by xiasun** [hexojs/hexo#2175]
I am trying to modify the size of image inside asset directory like this:
`{% asset_img example.jpg This is an example image %}`
I know using `img` tag is okay but that way how can I refer to the relative link of asset directory?
Thanks!

**Comment by unnamed42** [comment]
`asset_img` has no options about image size. Use raw html instead.

Now assume `asset` folder is placed under the root of your site,
```html
<img src="/asset/[your_image]" width="[width]" height="[height]" alt="[alternative_text]" title="[title]">
```

**Comment by xiasun** [comment]
Thanks!
