### ISSUE TITLE
theme use swig template memory leaks

### ISSUE THREAD

**Issue by magicdawn** [hexojs/hexo#2178]
As the title presents, I found the swig style template always got memory leaks.

Example:
- A little theme for self use: https://github.com/magicdawn/hexo-theme-neat/ 
- the most stared hexo theme: https://github.com/iissnan/hexo-theme-next
- the 2nd most stared hexo theme: https://github.com/litten/hexo-theme-yilia

neat & next use swig, and leaks, with cpu 100%+
yilia use ejs use 160MB+ memory, so far so good

About the leak of neat, I found it several month ago, see https://cnodejs.org/topic/5743f7c4754d17df1e44d97d , and I tried to find what happens in hexo & swig. Looks like I did not get there. 

So I guess replace swig with ejs will save my little theme, and report the problem here. Thanks

**Comment by NoahDragon** [comment]
Thank you. So far the swig is not maintained by its author (https://github.com/paularmstrong/swig), we couldn't do much about it. I personally suggest to use ejs for more clear syntax :).

**Comment by stevenjoezhang** [comment]
This issue can be closed due to https://github.com/hexojs/hexo/pull/2949 and https://github.com/hexojs/hexo/pull/2903
