### ISSUE TITLE
不在自己电脑写博客时（即无hexo环境），有没有啥一键解决方案？

### ISSUE THREAD

**Issue by senlinmuvs** [hexojs/hexo#2180]
如题。
这种需求还是很常见的，比如出差在外时，火车飞机上时。
我自己想来想去最方便的只能是在博客部属服务器上加个简单的后台系统，然后把hexo的环境也搬上去。
有没有啥更方便的奇技淫巧没有？

**Comment by tiexo** [comment]
通过Coding提供的WebIDE来使用Hexo
https://www.tiexo.cn/coding-webide/

**Comment by NoahDragon** [comment]
可通过配置Travis Ci或者其他Ci来实现，推荐以下教程：

https://xuanwo.org/2015/02/07/Travis-CI-Hexo-Autodeploy/

**Comment by senlinmuvs** [comment]
谢谢上面两位
我打算用@tiexo的办法，在外直接浏览器里搞定最方便。

**Comment by NoahDragon** [comment]
还有一种方法是使用Hexo-Admin插件，不过需要自建服务器。

**Comment by NoahDragon** [comment]
如果还有其它问题，可以reopen这个issue.
