### ISSUE TITLE
hexo deploy doesn't work

### ISSUE THREAD

**Issue by VictorZhang2014** [hexojs/hexo#2181]
This is the hexo information I installed 
```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 16.0.0 darwin x64
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
```

nvm --version
0.32.0

node --version
v4.5.0

This is Deploy infos
```
deploy:
  type:git
  repo:https://github.com/VictorZhang2014/victorzhang.github.io.git
  branch:master
```

I didn't know why this command `hexo deploy` doesn't work. Can someone help me ? Any help is appreciated!

**Comment by perixiaowan** [comment]
试试改成下面这种形式呢？

deploy:
  type: git
  repo: git@github.com:perixiaowan/perixiaowan.github.io.git
  branch: master

**Comment by perixiaowan** [comment]
try this method as belowing

deploy:
  type: git
  repo: git@github.com:perixiaowan/perixiaowan.github.io.git
  branch: master

**Comment by VictorZhang2014** [comment]
thank you @perixiaowan I found that a blank is needed
