### ISSUE TITLE
couldn't use Markdown todo list feature

### ISSUE THREAD

**Issue by zhangtianle** [hexojs/hexo#2182]
when I use hexo, and the next theme to write my blog , but the Markdown`- [ ] TODO`  feature dosen't work.  
#### expect like this:
- [ ] tode  

#### but the result is: 
` [ ] todo` 

Could you tell me what causes it, Thank you!

**Comment by NoahDragon** [comment]
Already an issue on marked module https://github.com/chjj/marked/issues/107

Right now, they still haven't implement it yet. The bypass way is to use Unicode to show the checkbox: ☐ , ☑, and ☒.

**Comment by zhangtianle** [comment]
Got it! Thank you very much!

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo-renderer-marked/pull/32 Supported.
