### ISSUE TITLE
希望自定預設的 open graph 圖片

### ISSUE THREAD

**Issue by livekn** [hexojs/hexo#2184]
現時 hexo 如果在文章沒有圖片時，og:image 就不會顯示圖片。如果我希望可以先自定一張預設圖片，文章沒有圖片或者首頁時就自動使用它，可以怎樣做呢？

又，我有嘗試自己寫 scripts 使用 [filter](https://hexo.io/api/filter.html) 解決，hexo.extend.filter.register 似乎 type 怎麼輸入都是無法取得 open graph 那些程式碼，只能取得文章的內容，應該怎樣做，才可以透過 scripts 去修改 og:image 呢？

謝謝

**Comment by ayugioh2003** [comment]
同樣想問這個問題

**Comment by NoahDragon** [comment]
#1525 通过修改`node_modules/hexo/lib/plugins/helper/open_graph.js`来实现的，不知对你的实现是否有帮助。

**Comment by ayugioh2003** [comment]
@NoahDragon  謝謝你 ~

我有注意到這篇，但不曉得和我想要的效果相不相同
我還是先試看看好了，不行的話再來找其他方法
謝謝你 ~

**Comment by livekn** [comment]
@NoahDragon 這並不是一個很好的方法，因為如果對 hexo 進行更新，這個 patch 就有可能會被 overwrite；又或者有多於一台電腦寫 blog 的話，每台電腦都要各自 patch 才能發佈。
比較好的方法似乎是官方支持，或者可以透過 user 的 script 或 plugin 處理。
