### ISSUE TITLE
comment窗口无法加载

### ISSUE THREAD

**Issue by razygon** [hexojs/hexo#2185]
在2个yml文件中均有添加disqus_shortname, theme下得那个是disqus: myname。
网页中有出现评论的小图标，点击后会到页面底部，但是并没有comment窗口出现，请问我还需要其他设置吗？

**Comment by NoahDragon** [comment]
请问你的post的front matters里有没有设置comment: true？

**Comment by razygon** [comment]
之前没有，添加后表现是一样的，点击图标到页面底部，但没有评论窗口

**Comment by razygon** [comment]
知道问题了
 theme下的yml文件 ##并没有把后面的文字comment掉，而是传承了disqus name，导致我的disqus_shortname 很大一串其实是错的。。。
