### ISSUE TITLE
Cannot GET /about/. Why there is no /about page?

### ISSUE THREAD

**Issue by wzup** [hexojs/hexo#2186]
Why do I see this? How to make it work?

![localhost_4000_about_ - google chrome 2016-09-30 13 46 47](https://cloud.githubusercontent.com/assets/3880497/18982078/0c506c3e-8716-11e6-8ff3-198b9afaf7bf.png)

I enabled this theme https://github.com/raytaylorlin/hexo-theme-raytaylorism on top of the default hexo app. I've just changed this option in my `\mysite\_config.yml`:

```
theme: raytaylorism
```

There is a `/about` link in the header but it doesn't follow anywhere, `Cannot GET /about/`:

![localhost_4000 - google chrome 2016-09-30 14 01 25](https://cloud.githubusercontent.com/assets/3880497/18982147/7e4fea76-8716-11e6-85f3-f00941be6d1a.png)

How do I make it work? Your docs do not cover the issue. They actually do not make clear a lot of questions

**Comment by NoahDragon** [comment]
On your local host, you won't see the 404 returns, so that's why the message.

You have to create an "about" folder under your "source" directory.

![cn source about at master noahdragon cn](https://cloud.githubusercontent.com/assets/5704064/18991258/5c6ac2fe-86e5-11e6-9cf8-4aef0f8bac01.png)
