### ISSUE TITLE
hexo server serve different files than hexo generate?

### ISSUE THREAD

**Issue by Emp3r** [hexojs/hexo#2190]
Seems like `hexo server` and `hexo generate` takes totally different approach to generate files when it comes to page properties. For example when I use any of these in my sidebar widgets:
```
<%- page.title %>
<%- page.layout %>
<%- page.path %>
```

It works well with files served by `hexo server` - those variables are different for each page and that's correct. But it is messed up in generated files in _/public_ folder, because these variables has evaluated to **the same value for every page** (same as the last generated page, or maybe the first).

When I upload all my files from _/public_ to production server, it's not the same as locally served files. Please, is there any way to get the files like `hexo server` serves?

Although I found comment about the same problem in [issue 1773](https://github.com/hexojs/hexo/issues/1773), I didn't find any solution.

**Comment by NoahDragon** [comment]
Have you tried `hexo clean` and then `hexo generate`? Normally this will clean the caches.

**Comment by Emp3r** [comment]
Yes, many times actually. 

But I figured it out! It was because in order to get `page` object in a partial, it has to be given as parameter to any called partial, like `<%- partial('_partial/sidebar', {page: page }) %>`. Otherwise it somehow work while local serving (maybe because `hexo server` generate and serve files according to actual http request?), but it doesn't work the same when generating all files at once.

Thanks and sorry for being dumb, you can close this issue.

**Comment by NoahDragon** [comment]
Great, glad figured it out.
