### ISSUE TITLE
hexo g error but hexo s works ok.  about page.posts.each()

### ISSUE THREAD

**Issue by yuzai** [hexojs/hexo#2192]
I am writing a theme,  in tag.ejs, I use page.posts.each()，when I use hexo s , it worked. but when I use hexo g to generate, it says that page.posts.each() is not defined. here is the log:
Unhandled rejection TypeError: G:\hexo\themes\showonne\layout\tag.ejs:2
    1| <% console.log(page) %>
 >> 2| <% page.posts.each(function(post){
    3|   console.log('hello')
    4| }) %>
    5|
Cannot read property 'each' of undefined

I use this page.posts.each()  in category.ejs . archive.ejs and tag.ejs, it all worked when hexo s. but when I hexo g, it errors only in tag.ejs. 
I am really confused, why I use hexo s , it can work, but if I hexo g, it reports an error?

**Comment by NoahDragon** [comment]
`hexo s` takes the cached files.

Some pages in Hexo do not have posts property, like index. So it is better to check if it is index before access posts attribute.

**Comment by yuzai** [comment]
thank you. It is really helpful.
check it before use it, I didn't pay attention to it before.
Now the fact is when I hexo d, the page worked well like when I hexo s. I have cleaned with hexo clean, although when I use hexo g, it throws an error, but when I hexo d it, it worked. maybe this error is not very important.
anyway,thank you!

**Comment by NoahDragon** [comment]
Thanks for the feedback. The error will prevent rendering that part. It still outputs something, but not the way expected.
