### ISSUE TITLE
Don't delete existing git repository

### ISSUE THREAD

**Issue by marvinhagemeister** [hexojs/hexo#2193]
When you run `hexo init` inside the current folder, hexo will nuke the existing `.git` folder and `package.json`. Hexo's cli shouldn't lead to data loss. I'd be nice if hexo could abort and throw a warning or something like that. Just found this out the hard way :rage:

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo-cli/issues/12 

It is already a feature request on Hexo CLI.
