### ISSUE TITLE
在bash中用npm install -g hexo-cli安装时报错

### ISSUE THREAD

**Issue by CalvinoShaw** [hexojs/hexo#2194]
npm WARN onload-script failed to require onload script npm-autoinit/autoinit
npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:455:15)
npm WARN onload-script     at Function.Module._load (module.js:403:25)
npm WARN onload-script     at Module.require (module.js:483:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\javasoft\nodejs\node_modules\npm\lib\npm.js:199:11)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\npm.js:304:16
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:81:7
npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:80:13
npm WARN onload-script     at f (D:\javasoft\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
npm WARN onload-script  { Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:455:15)
npm WARN onload-script     at Function.Module._load (module.js:403:25)
npm WARN onload-script     at Module.require (module.js:483:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\javasoft\nodejs\node_modules\npm\lib\npm.js:199:11)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\npm.js:304:16
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:81:7
npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:80:13
npm WARN onload-script     at f (D:\javasoft\nodejs\node_modules\npm\node_modules\once\once.js:17:25) code: 'MODULE_NOT_FOUND' }
npm WARN onload-script failed to require onload script npm-autoinit/autoinit
npm WARN onload-script Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:455:15)
npm WARN onload-script     at Function.Module._load (module.js:403:25)
npm WARN onload-script     at Module.require (module.js:483:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\javasoft\nodejs\node_modules\npm\lib\npm.js:199:11)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\npm.js:304:16
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:81:7
npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:80:13
npm WARN onload-script     at f (D:\javasoft\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
npm WARN onload-script  { Error: Cannot find module 'npm-autoinit/autoinit'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:455:15)
npm WARN onload-script     at Function.Module._load (module.js:403:25)
npm WARN onload-script     at Module.require (module.js:483:17)
npm WARN onload-script     at require (internal/module.js:20:19)
npm WARN onload-script     at cb (D:\javasoft\nodejs\node_modules\npm\lib\npm.js:199:11)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\npm.js:304:16
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:81:7
npm WARN onload-script     at Array.forEach (native)
npm WARN onload-script     at D:\javasoft\nodejs\node_modules\npm\lib\config\core.js:80:13
npm WARN onload-script     at f (D:\javasoft\nodejs\node_modules\npm\node_modules\once\once.js:17:25) code: 'MODULE_NOT_FOUND' }

**Comment by NoahDragon** [comment]
https://github.com/npm/npm/issues/12600

Try `npm config delete onload-script npm-autoinit/autoinit`

**Comment by CalvinoShaw** [comment]
@NoahDragon thanks! it worked.

**Comment by NoahDragon** [comment]
Great.
