### ISSUE TITLE
How to combine findOne with categories and tags?

### ISSUE THREAD

**Issue by timpulver** [hexojs/hexo#2195]
I would like to list all posts with tag «featured» and category «project». How can I do this?
What I have so far:

```
site.tags.findOne({name: 'featured'}).posts.sort('date', -1).each(function(post, index) {%>
      <%- partial('_partial/project-excerpt', {item: post}) %>
  <% })%>
```

Now only this part is missing: `site.categories.findOne({name: 'project'})`, but how to combine them?

**Comment by NoahDragon** [comment]
Correct me if I'm wrong.

You can use Set to approach it.

``` javascript
var tagPosts = new Set(site.tags.findOne({name: 'featured'}).posts)
var categoryPosts = new Set(site.categories.findOne({name: 'project'}).posts)

var posts = new Set([...tagPosts].filter(x => categoryPosts.has(x)));
```

**Comment by timpulver** [comment]
Thanks for your quick response! 

Is there a better way than wrapping every line of code in `<%- ->` inside my .ejs-template?

**Comment by NoahDragon** [comment]
Not a problem.

You can wrap them as a block, like:
``` ejs
<%
var tagPosts = new Set(site.tags.findOne({name: 'featured'}).posts)
var categoryPosts = new Set(site.categories.findOne({name: 'project'}).posts)

var posts = new Set([...tagPosts].filter(x => categoryPosts.has(x)));
%>
```

**Comment by BDomantas** [comment]
This is a bit off topic, but where can I find all of those functions like findOne and etc.? They're not in hexo docs

**Comment by NoahDragon** [comment]
@BDomantas Those are usually methods from dependencies, not defined by Hexo. You can google it first, or use Object.getOwnPropertyNames() to list all methods under an object.

**Comment by NoahDragon** [comment]
If there is no question about this issue, I will close it.

Please feel free to reopen it any time.

**Comment by timpulver** [comment]
@NoahDragon I tried your solution, but `Set` was not defined. This may be off-topic, but how can I use ES6-functions like `Set` with *hexo*?

I ended up using:

```
<%
  // find all posts with category: "items" and tag: "featured"
  site.tags.findOne( { name: 'featured' } )
    .posts.sort( 'date', -1 )
    .each(
      function(post, index) {
        post.categories.each( function(category) {
          if(category.name === 'items') {
%>
            <%- partial('_partial/index/featured-item', {post: post}) %>
<%
          }
        });
      }
    );
%>
```

**Comment by NoahDragon** [comment]
@timpulver Hmmm, good point. I never tried it in ejs. So I post a question to them, hope we could get answers from there. https://github.com/mde/ejs/issues/215

**Comment by NoahDragon** [comment]
Based on the reply from mde/ejs#215 , ejs 2.0 above supports the es6.

I have requested to upgrade the ejs version in Hexo-renderer-ejs.
https://github.com/hexojs/hexo-renderer-ejs/issues/6

**Comment by timpulver** [comment]
Thanks @NoahDragon, that’s great!

**Comment by Turqueso** [comment]
is there a way to do this with pug?
