### ISSUE TITLE
Disable tags sorting

### ISSUE THREAD

**Issue by omid** [hexojs/hexo#2196]
Hi,

There isn't any way to disable sorting of tags (and maybe categories!)
There should be a way to do this!

Regards.

**Comment by NoahDragon** [comment]
It should be an issue for the categories and tags generators.

**Comment by omid** [comment]
So? :-)

Is it an external tool then? But it is included in the project.

**Comment by NoahDragon** [comment]
It is a plugin for Hexo, pre-installed with it.

The sorting behavior can also be controlled by theme. For the theme im using, the tags and cates are not sorted.
