### ISSUE TITLE
Get list of posts through API

### ISSUE THREAD

**Issue by giacomocerquone** [hexojs/hexo#2197]
## Environment Info

Node version(`node -v`)
```
v6.1.0
```

Plugin version(`npm ls --depth 0`)
```
+-- hexo@3.2.2
+-- hexo-browsersync@0.2.0
+-- hexo-deployer-git@0.0.4
+-- hexo-front-matter-excerpt@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.0
+-- hexo-generator-search@1.0.2
+-- hexo-generator-tag@0.1.2
+-- hexo-renderer-ejs@0.1.1
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
`-- hexo-server@0.1.3
```

Hi, looking for a way to get all the posts of a blog I found these two:

```
var Hexo = require('hexo');
var hexo = new Hexo(process.cwd(), {});

hexo.init().then(function(){
  var post = hexo.locals.get('posts');
  console.log(post);
});
```

```
var Hexo = require('hexo');
var hexo = new Hexo(process.cwd(), {});

hexo.init().then(function(){
  var post = hexo.model('Post').toArray();
  console.log(post);
});
```

But both of them return an empty square brackets. Of course there are about fifteen posts inside the source/_posts folder so why is this happening? How can I solve this problem?

Thank you very much.

**Comment by NoahDragon** [comment]
https://hexo.io/api/index.html

Where the initialize only load the config and plugins, you have to call Load to load source folder.

**Comment by giacomocerquone** [comment]
Very good, I stupidly missed that point.
One thing, why I find online this hexo.model but can't find it in the docs? What is it exactly? 

Thank you again

**Comment by NoahDragon** [comment]
You're welcome.

It is probably the deprecated API. I use Hexo from 3.x, and it is my first time saw it.

**Comment by giacomocerquone** [comment]
Very well. in fact if you take a look at this you'll see that the guy of hexo-admin updated their app to use the hexo v.3 api and you can find in it a lot of hexo.model...
https://github.com/jaredly/hexo-admin/blob/master/api.js

**Comment by NoahDragon** [comment]
Thanks for your feedback. I think I still have a lot to learn about the Hexo.

We are glad and appreciating any kinds of usage and contribution to Hexo. Looking forward to your app.

I will close this issue. If you think it still is not solved, please reopen it.
