### ISSUE TITLE
回车就是换行和预览不一致异常问题

### ISSUE THREAD

**Issue by XuBovey** [hexojs/hexo#2200]
代码如下：
```
# testCode

12312无空格
123123两个空格  
12312312三个空格   

123123123
```

预览如下：
# testCode
12312无空格 123123两个空格
12312312三个空格

123123123

---

执行以下命令后
`hexo g`
`hexo s`

http://localhost:4000/网页打开
结果显示：
# testCode

12312无空格
123123两个空格
12312312三个空格

123123123

---

编码：UTF-8
行尾序列：LF，CRLF都一样
编辑器：VS CODE
记得刚开始很正常的，后来不知道怎么回事就不正常了。
请问有没有什么解决思路。
使用travis自动部署，结果也是这样回车就是换行。

**Comment by NoahDragon** [comment]
是否将GFM设置为True了？

**Comment by XuBovey** [comment]
3ks
解决了，_comfig.yml中增加了如下代码就好了，估计默认值时 true或者不知道什么时候做了其他操作影响了这个值:
```
marked
  gfm: false
```
