### ISSUE TITLE
two images next to each other

### ISSUE THREAD

**Issue by phicarre** [hexojs/hexo#2208]
> before you submit your issue, please delete all the example code in template
## Environment Info

Node version(`node -v`)

```
v4.5.0
```

Your site `_config.yml`

```
# Hexo Configuration
...
```

Your theme `_config.yml`

```
# Hexo Configuration
...
landscape
```

Plugin version(`npm ls --depth 0`)

```

```
## For BUG
- BUG description
- the way to reproduce
- log with hexo <command> --debug
## For question

How to place two images next to each other ?
`![image1](link1)]![image2](link2)` doesn't work for me .
## For feature request

just push feature request

**Comment by NoahDragon** [comment]
You could turn off the fancybox. Or explicitly using the <img> tag to insert pictures.

**Comment by phicarre** [comment]
I used the tag like this :{% img path1 %}{% img path2 %} but the second image is below.

**Comment by NoahDragon** [comment]
Here is what I did to suppress fancybox:

```html
<img class="nofancybox" src="/img/top1.png" style="display: inline; border-style: none;">
```

The nofancybox is a style which resets all fancybox styles.

**Comment by phicarre** [comment]
Ok but it is an html solution, not an Hexo solution ...

**Comment by NoahDragon** [comment]
As stated above, turn off the fancybox is the Hexo solution. 

In order to keep fancybox on and change the images style, the html solution is a shortcut.
