### ISSUE TITLE
如何在markdown中引用config.yml定义的变量

### ISSUE THREAD

**Issue by peachyy** [hexojs/hexo#2209]
环境:
`$ hexo version
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.5.0
node: 4.2.2
`
比如图片资源在另外一台机器上，我想把这个资源的URL用变量的形式来设置，因为可能有更换机器，这样就不用到处修改代码了。

**Comment by NoahDragon** [comment]
可以使用config.variable来取得config中variable的值。

**Comment by peachyy** [comment]
@NoahDragon  没有明白怎么使用 可以举个例子吗

**Comment by xovel** [comment]
楼上说的是在主题根目录下的配置文件中，事先定义好变量，然后在页面模板中直接使用config.xxx进行访问即可。

比如要访问博客站点名称，直接使用`config.title`即可访问在定义好的title值了。


> 根目录下的配置文件在解析后全部会放进全局对象`config`里面，按需进行访问即可。

----

个人建议请在主题下的配置文件中进行设置。

在主题下的`config.yml`中添加这样一条：

```yml
userDefineURL: http://www.abc.com/xxx.txt
```

那么，在**页面模板**中，使用`theme.userDefineURL`就可以访问到`http://www.abc.com/xxx.txt`这个值了。

> 同样的，主题配置文件在解析过后会放进`theme`对象中。

**Comment by NoahDragon** [comment]
请问是否解决？如未解决可重开此issue。

**Comment by tea9** [comment]
请问怎么直接在文章中获取根目录_config.yml中的变量

**Comment by tea9** [comment]
![image](https://user-images.githubusercontent.com/39117901/54667611-ba205680-4b27-11e9-837a-978c27a2c441.png)
直接这么使用吗 好像没有解析

**Comment by lovelyJason** [comment]
> ![image](https://user-images.githubusercontent.com/39117901/54667611-ba205680-4b27-11e9-837a-978c27a2c441.png) 直接这么使用吗 好像没有解析

那个人说的是在模板引擎的文件当中，比如这个布局的某某.ejs才能获取变量；据我所知道， md文件中是获取不到的，你们聊的不在一个话题上。

最近我也在寻求此方案

**Comment by lovelyJason** [comment]
> 请问怎么直接在文章中获取根目录_config.yml中的变量

<img width="932" alt="image" src="https://user-images.githubusercontent.com/50656459/235826484-7ba019b0-259a-4fc8-abc2-be40721982fd.png">

这个， 如出一辙

**Comment by stevenjoezhang** [comment]
你可以手动写一个插件：
```
hexo.extend.tag.register('config', function(args) {
    return hexo.theme.config.userDefineURL;
});
```
然后在 Markdown 文章中这么用
```
## 环境变量

{% config %}
```

**Comment by NicknamedCoco** [comment]
> 你可以手动写一个插件：
> 
> ```
> hexo.extend.tag.register('config', function(args) {
>     return hexo.theme.config.userDefineURL;
> });
> ```
> 
> 然后在 Markdown 文章中这么用
> 
> ```
> ## 环境变量
> 
> {% config %}
> ```

不管用啊，我在根目录创建了一个script目录，写了一个js文件，文件里写的你的js代码，然后文章里显示不出来

**Comment by NicknamedCoco** [comment]
> 你可以手动写一个插件：
> 
> ```
> hexo.extend.tag.register('config', function(args) {
>     return hexo.theme.config.userDefineURL;
> });
> ```
> 
> 然后在 Markdown 文章中这么用
> 
> ```
> ## 环境变量
> 
> {% config %}
> ```

我拿到了，但是怎么在markdown的标签内使用呢，，，
图库中的图片不是有自己的域名嘛，我想把图片url前面一段域名弄成变量，这样以后换域名的话，
文章中引用的图片就全部换好地址了，不然域名一换，就要一个文章一个文章去修改图片的url

**Comment by NicknamedCoco** [comment]
> 你可以手动写一个插件：
> 
> ```
> hexo.extend.tag.register('config', function(args) {
>     return hexo.theme.config.userDefineURL;
> });
> ```
> 
> 然后在 Markdown 文章中这么用
> 
> ```
> ## 环境变量
> 
> {% config %}
> ```

我拿到了，但是怎么在markdown的标签内使用呢，，，
图库中的图片不是有自己的域名嘛，我想把图片url前面一段域名弄成变量，这样以后换域名的话，
文章中引用的图片就全部换好地址了，不然域名一换，就要一个文章一个文章去修改图片的url

**Comment by stevenjoezhang** [comment]
那就类似于这样：
```js
hexo.extend.tag.register('tuku', function(args) {
    return `<img src="${hexo.theme.config.userDefineURL}{args[0]}">`;
});
```
然后在 Markdown 文章中这么用
```md
## 环境变量

{% tuku a.jpg %}
```
