### ISSUE TITLE
能否将hexo部署到百度BAE？

### ISSUE THREAD

**Issue by zippera** [hexojs/hexo#221]
百度BAE提供免费的空间，速度也没的说，支持帮顶域名，支持git和svn，是否可以部署到bae，求方法，谢谢。

**Comment by zqhZY** [comment]
可以只push public目录到bae：
http://someth.duapp.com/2016/08/02/%E9%83%A8%E7%BD%B2Hexo%E5%BA%94%E7%94%A8%E5%88%B0BAE/

**Comment by netpi** [comment]
最近试了下 部署过去之后 确实快  [放弃github pages,把hexo博客部署到百度BAE吧](http://www.netpi.me/code/hexo-bae-configure/)
