### ISSUE TITLE
Multiple configuration files.

### ISSUE THREAD

**Issue by Lindsor** [hexojs/hexo#2210]
Can you make it possible to load multiple configuration files.

For example in jekyll we would run

```shell
jekyll --config=_config.yml,_config2.yml serve
```

Which would pull all the configurations from the first file and then the second (so the seond file would take precedence).

**Comment by PirtleShell** [comment]
I agree that this is a good idea.

We could change the config path logic from [this line](https://github.com/hexojs/hexo/blob/master/lib/hexo/index.js#L56). When `args.config === true` we could send it to a module that returns this same filepath when only one config is present, but writes a composite config file if multiple options are found.

I'd like to help with this if we think it's a good idea?

**Comment by NoahDragon** [comment]
Thanks to @PirtleShell, the feature has been implemented. #2211
