### ISSUE TITLE
Question: Have blog inside folder, but still have index homepage

### ISSUE THREAD

**Issue by cesarvarela** [hexojs/hexo#2214]
I want my generated site to look like this:

```
/index.html
/blog/post-1.html
/blog/post-2.html
```

Is it possible?

**Comment by cesarvarela** [comment]
Thanks, I decided to not use hero after all.

**Comment by NoahDragon** [comment]
https://github.com/yscoder/hexo-theme-indigo/issues/97

Confirmed in other issues that Hexo cannot create title.html via `hexo new`. However, manually created folder and title.md file can produce title.html file.
