### ISSUE TITLE
Keep URL public post structure by title, ignore subfolders within _posts? 

### ISSUE THREAD

**Issue by vincentntang** [hexojs/hexo#2215]
I managed the content of my hexo posts on sublime text.

The problem I'm having right now is I cannot keep all my posts under just __posts_ because it gets too confusing. Ideally I want subfolders, like this

![](http://i.imgur.com/Ljd9KbJ.png)

However, I do not want my URL to change based on this added subfolder. Because I might move content in folders around in __posts_ later on which will change my links

E.G.

![](https://i.imgur.com/J8xo95l.png)

I don't want this highlighted portion of my URL

How can i avoid this

**Comment by NoahDragon** [comment]
Can you paste the permalink setting in your _config.yml?

**Comment by AnacondaPython** [comment]
Not really sure what controls the permalink under root config.yml

This is what I have on my settings at the moment:

![](http://i.imgur.com/m3UAsvh.png)

**Comment by timpulver** [comment]
Same problem for me. I have different post types (projects, artists, …) and need to get a little bit more order into my _posts folder.

Perfect outcome:

`hexo new project "Test Project"` creates `_posts/projects/test-project.md`
`hexo new artist "Test Artist"` creates `_posts/artists/test-artist.md`

The newly created posts should still use their categories for the permalink and not the folder they are in.

**Comment by psi-4ward** [comment]
https://github.com/hexojs/hexo/issues/1675#issuecomment-283218250

**Comment by seaoak** [comment]
You can use a directive `:layout` in `_config.yml` as follows:

```yaml
new_post_name: :layout/:title.md
```

Once you make a new file `project.md` in your `scaffolds` folder,
`hexo new project test001` command generates `source/_posts/project/test001.md`.
Regardless of the folder, the permalink of the post follows `permalink:` setting in your `_config.yml`.

For example, the URL of this post is `http://example.com/2017/03/02/test001/` if your setting is as follows:

```yaml
permalink: :year/:month/:day/:title/
```

Of course any categories and tags can be set to the post optionally.

**Comment by rabas007** [comment]
@NoahDragon - 

> A workaround would be to add a variable in front matter, and then use it in the permalink.

Your solution partly works.
I have subfolders in my _posts:
- china
- japan
- vietnam

For each .md file I added:
`titleInLink: USA` 

but the resulting URL / slug is... `domain.com/USA/china/post.md` and  `domain.com/USA/vietnam/post.md`

How to get rid of the "folders names" (such as china, japan, vietnam) in my URL / slug?

**Comment by yqs112358** [comment]
So... After so many years is there any official solution that can be set in `_config.yaml`? 🤔

Another problem is, why `:titile` contains the directory-structure where the `.md` in? It is a strange logic. 
A better design should be:

`/source/_posts/dir1/dir2/title.md`
convert to ↓
`:directory` is `dir1/dir2/`
`:title` is `title.md`
`:path` is `dir1/dir2/title.md`
