### ISSUE TITLE
Hexo middleware are not working on ubuntu 14.04 but same working on windows

### ISSUE THREAD

**Issue by SatioO** [hexojs/hexo#2216]
I have created new file called index.js and written below code and tried to execute it. but same code worked for me on windows but not for ubuntu.

hexo.extend.filter.register('server_middleware', function(app) {
  console.log(app);
});

**Comment by NoahDragon** [comment]
Have you check if the nodejs version is the same on both ubuntu and windows?

**Comment by SatioO** [comment]
Yes, on windows I am having v6.5.0 and on ubuntu, its v6.7.0
