### ISSUE TITLE
azure deployment

### ISSUE THREAD

**Issue by thdotnet** [hexojs/hexo#2217]
Hi guys, I'm trying to code a plugin to enable deployment to azure blob storage (equivalent of s3 for amazon). However, I'm getting an error: ERROR Deployer not found .

Besides the following line, is there any other configuration step, to enable my plugin?

hexo.extend.deployer.register('azure', require('./lib/hexo-azure-blob-deployer'));

**Comment by NoahDragon** [comment]
Have you try add the following into your _config.yml?

```yml
deploy:
  type: azure
```

**Comment by thdotnet** [comment]
@NoahDragon yes,

**Comment by NoahDragon** [comment]
Base on the code https://github.com/hexojs/hexo/blob/5234c4a85dc6cd418e9a1c169e43de169cf98e95/lib/plugins/console/deploy.js#L49 , it should work, unless it doesn't list in the config file.

**Comment by thdotnet** [comment]
I'll try to put more information, maybe it will be easier to identify the problem. I've created a new plugin call foo just to test the deployer extension as follows:

index.js (plugin)

hexo.extend.deployer.register('foo', require('./lib/foo'));

foo.js (plugin code)

module.exports = function(args) {

	var log = this.log;
	
	log.info("foo");
};

package.json

{
  "name": "hexo-foo",
  "version": "1.0.0",
  "main": "index.js"
}


_config.yml (just the deployment section)

deploy:
  type: foo

**Comment by thdotnet** [comment]
Any tips?
