### ISSUE TITLE
after_toc_render?

### ISSUE THREAD

**Issue by flashlab** [hexojs/hexo#2218]
Hello everyone,
Is there any way to manipulate TOC contents after render just like `after_post_render` did? Maybe the toc is the last part that we can't control though themes :smirk:

**Comment by NoahDragon** [comment]
IMHO, I didn't see any specific reasons that we need it. Any manipulations for rendered TOC could be done after post rendered.

**Comment by Neveryu** [comment]
yes , I think so.

**Comment by flashlab** [comment]
While plugin`hexo-blog-encrypt` obscure the main contents, I also wish to encrypt the TOC. To achieve this, It'll be better to have a interface manipulating TOC after render. @NoahDragon

**Comment by NoahDragon** [comment]
I have posted an issue to the plugin, hopefully, they could have some solution. 

https://github.com/MikeCoder/hexo-blog-encrypt/issues/6

**Comment by MikeCoder** [comment]
I will work on that tomorrow. Hope I can find some solutions.

**Comment by MikeCoder** [comment]
Upgrade plugin to v1.1.7 and see [https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc](https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc)

**Comment by NoahDragon** [comment]
Thank you @MikeCoder ! Awesome!

@flashlab Does Mike's solution meet your need?

**Comment by flashlab** [comment]
Thank you guys :smile: really appreciated

**Comment by MikeCoder** [comment]
Why not a star?  *(just kidding) *
