### ISSUE TITLE
Inline pdf icon break paragraph into two parts. 

### ISSUE THREAD

**Issue by Explorare** [hexojs/hexo#2220]
![2016-10-24-160005-001](https://cloud.githubusercontent.com/assets/5090766/19637815/6ffbd822-9a03-11e6-9036-8bade2bc430d.png)

If I insert a pdf link, hexo will insert a little icon after it. But that icon is rendered in a new line. 
It seems that the icon is rendered by fancybox. So when hexo rendering pdf link, a `no-fanxybox` tag should also append with it. How to fix it?

[Apostrophe, Quotation Marks and Prime Symbols | HentaiCollection](https://hencolle.com/2016/10/24/apostrophes_mess/)

**Comment by NoahDragon** [comment]
What I did is to create a css style for no fancybox img and applied it explicitly. E.g. `<img class="nofancybox" src="/img/top1.png" style="display: inline; border-style: none;">`

**Comment by Explorare** [comment]
@NoahDragon Thanks for your help. I've found that this icon was added by a Chrome extension [Docs Online Viewer](http://dov.parishod.com/), which could open up supported docs on Google Docs. The url to this image is `chrome-extension://gmpljdlgcdkljlppaekciacdmdlhfeon/images/beside-link-icon.svg`. I'm wondering if it worth to be fixed.

**Comment by NoahDragon** [comment]
You are welcome. Thanks for the info. :)
