### ISSUE TITLE
Question : how to disable the post after publish?

### ISSUE THREAD

**Issue by thyeun** [hexojs/hexo#2222]
OS : ubuntu 16.04
Hexo : 3.2.2

i have a question regarding disable the post after publish?

Meaning that not deleted the post, but just in the post with something like the below,

``` markdown
---
title: Welcome to Note Styles
categories: Style
tags: style
publish: false
---
```

when the publish are true, than it will publish and can be see, and when it go to false, than the post still remain inside the "post" folder but nobody can see it whenever visit the hexo site.

so, how can i do that?

**Comment by NoahDragon** [comment]
You could try to use the [draft](https://hexo.io/docs/writing.html#Drafts).

**Comment by thyeun** [comment]
@NoahDragon, not like that, that one is before i publish it, what i mean is, i have a "welcome" post and already publish it, but after a few day, i dont want to publish it.

how to do that?

**Comment by NoahDragon** [comment]
You can move the md file out the _post folder and put into _draft folder.

**Comment by thyeun** [comment]
@NoahDragon beside that, any better way? do hexo possible to have this, remain the md file inside _post folder and only modify the content with just "true" or "false" as an disable or enable the publish.

**Comment by NoahDragon** [comment]
I don't think so. Probably you could add an event to exclude those files with "publish: false" before generate. Or some one could write a plugin for it.

**Comment by thyeun** [comment]
@NoahDragon ok, thanks
