### ISSUE TITLE
Error: EPERM: operation not permitted on sudo npm install hexo-cli -g

### ISSUE THREAD

**Issue by CallMeSirLiu** [hexojs/hexo#2225]
## Environment Info

Systme version
```
mac os ei capitan 10.11.6
```

Node version
```
v4.4.5
```

## Error
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hexo-cli" "-g"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /tmp/npm-59898-4efacc4b
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir '/tmp/npm-59898-4efacc4b'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, mkdir '/tmp/npm-59898-4efacc4b']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/tmp/npm-59898-4efacc4b',
npm ERR!   parent: 'hexo-cli' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/liujia/npm-debug.log

## tmp dir
drwxrwxrwt@  3 root  wheel   102 10 18 09:26 tmp
Should I change the dir's username?

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo/issues/2223

Could the solution above solve your issue?

**Comment by CallMeSirLiu** [comment]
I've updated my MacOs operating system to solve the issue because there's something wrong with my system.
