### ISSUE TITLE
Superfluous getting-started step?

### ISSUE THREAD

**Issue by gaggle** [hexojs/hexo#2229]
Manual states:
```
npm install hexo-cli -g
hexo init blog
cd blog
npm install
hexo server
```

But dependencies are installed during the `init blog` command, is it not? Is there a reason to run the `npm install` command?

**Comment by NoahDragon** [comment]
I think `npm install` could be skipped, as `hexo init` does the job ([ref](https://github.com/hexojs/hexo-cli/blob/master/lib/console/init.js#L49)). However, it will only run as `npm install --production`.
