### ISSUE TITLE
Pug based theme doesn't work when there is a file named layout.pug

### ISSUE THREAD

**Issue by shelldweller** [hexojs/hexo#2230]
When a pug based theme contains file named `layout.pug` hexo theme loader never loads `index.pug`, `page.pug`, `post.pug` etc as described [here](https://hexo.io/docs/templates.html). The only loaded template is `layout`.

Renaming `layout.pug` (e.g. to `base.pug`) solves the issue and all templates are loaded correctly.

**Comment by shelldweller** [comment]
It's not bug it's a feature. The special pages should not inherit from `layout.pug`. Either one of the following would work:

**Keep special pages as partials.**
Their content will be inserted into `layout.pug` as `body` variable. For example:

```pug
//- layout.pug
doctype html
html
  body
    div !{body}
```
```pug
//- post.pug
h1= page.title
div !{page.content}
```

**Special pages inherit from base template.**
For example:
```pug
//- base.pug (cannot be called layout.pug)
doctype html
html
  body
    block body
```
```pug
//- post.pug
extends base.pug
h1= page.title
block body
  div !{page.content}
```

**Comment by NoahDragon** [comment]
Thanks for the solution.
