### ISSUE TITLE
Remove index from URL

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#2232]
Hello all,
I am new to Hexo, how can I remove index.html from the URL? 
`<link rel="canonical" href="<%= config.url %>/<%= page.path %><% } %>">`

**That renders:**
`http://localhost:4000/about/index.html`

I just want to have `http://localhost:4000/about`
## Thank you

Hexo version: 3.2.2
NodeJS version: 5.0.0

**Comment by NoahDragon** [comment]
Just to clarify, you are expecting to be `http://localhost:4000/about.html` or `http://localhost:4000/about/` ?

**Comment by ntot** [comment]
Hello,
Thanks for the reply.

I would like all of my URL to have the index.html removed so they would look like:\

```
http://localhost:4000/about/
http://localhost:4000/contact/
http://localhost:4000/blog/test-post

```
Thanks in advance.

**Comment by NoahDragon** [comment]
Current Hexo 3.x already does so.

 You can just use `http://localhost:4000/about/` instead of `http://localhost:4000/about/index.html`, they are equivalent.

**Comment by ntot** [comment]
No this is not what I mean sorry.

If I add `<%= page.path %>` in my layout.ejs file it will output the following when I visit the about page: `http://localhost:4000/about/index.html` the actual URL in the browser is /about that's good and perfect but I want to remove **index.html** from `<%= page.path %>`

**Comment by NoahDragon** [comment]
Here is a solution using replace function.

` <%- url_for(page.path).replace(/index\.html$/, '') %>`

**Comment by ntot** [comment]
YES!! thank you so much this worked!! Many many thanks for the help :)

**Comment by NoahDragon** [comment]
You are welcome!

**Comment by popomore** [comment]
> Current Hexo 3.x already does so.
>
> You can just use http://localhost:4000/about/ instead of http://localhost:4000/about/index.html, they are equivalent.

@NoahDragon hi, is it enable by default, I just generate `about.html` only, there is no `about/index.html`

**Comment by NoahDragon** [comment]
@popomore if you using `hexo new page "about"`, it will generate the `about/index.html`.

**Comment by popomore** [comment]
I just want `about.md` that can be requested by `/about` not `/about.html`.

**Comment by NoahDragon** [comment]
@popomore sorry, my mistake, Hexo will generate `about/index.md`. 
You could manually create `about.md` and add the link to your pages. This will also work.

**Comment by popomore** [comment]
Do you have any example for that. I don't know what configure should be, it
don't work in my case. I see hexo/site also don't generate.
Abner Chou <notifications@github.com>于2017年1月14日 周六03:12写道：
