### ISSUE TITLE
How to route 404 with server running?

### ISSUE THREAD

**Issue by macphersonj** [hexojs/hexo#2234]
Hey

How would one set up the 404 page to show on while hexo server is running? Right now it gives an error message "Cannot GET /dkawldw/", but I want to simulate real behaviour.

**Comment by NoahDragon** [comment]
I know it is not the best solution, but what I did is deploying to the server and then test it, because the 404 doesn't occur very often.

**Comment by NoahDragon** [comment]
You can type ` http://localhost:4000/404.html` to view the 404 page.
