### ISSUE TITLE
Fatal parse error with this code: \1{2}{3}

### ISSUE THREAD

**Issue by xovel** [hexojs/hexo#2236]
While I typed a code like `\1{#2}{3}`, it caused a fatal error.

I just want to use some MathJax HTML Color, the syntax is `\color{yellow}{text}`. When I change the color `yellow` to `#rgb`, the error come up immediately.

So I just created a new post, written these code:

```
---
title: 123456
tags: []
categories: []
date: 2016-11-03 16:32:05
---

\1{2}{3}
```

BUT, when I changed it to:

```
---
title: 123456
tags: []
categories: []
date: 2016-11-03 16:32:05
---

\1{#2}{3}
```

**IT BREAK DOWN**

![](http://ww2.sinaimg.cn/large/79be2309gw1f9f140kci2j20it0oqwfg.jpg)

------
My env: 

- hexo `3.2.0`
- hexo-cli `1.0.1`
- os: win7 64
- node `4.4.3`

**Comment by xovel** [comment]
![](http://ww2.sinaimg.cn/large/79be2309gw1f9f140kci2j20it0oqwfg.jpg)

**Comment by NoahDragon** [comment]
可否试下
```markdown
{% rawblock %}
\1{#2}{3}
{% endrawblock %}
```

**Comment by xovel** [comment]
@NoahDragon  一样的。依然会出错。

**Comment by NoahDragon** [comment]
不好意思，我记错syntax了，应该是
```
{% raw %}
{% endraw %}
```

**Comment by xovel** [comment]
@NoahDragon 是的，我也发现了。用这种方式可以解决当前的问题。3Q~

~~然而依然未能找出为什么会出现这样的错误~~

**Comment by NoahDragon** [comment]
主要是两个方面转义都有可能出错，markdown和Theme render（swig等）。一般转义出错都可以用Raw Block解决。
