### ISSUE TITLE
关于vendors文件夹里面的js文件和css文件404

### ISSUE THREAD

**Issue by Sonnyzoom** [hexojs/hexo#2238]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v5.7.0
```
Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.1.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For question

本地public文件夹里面的vendors文件夹正常，hexo s --debug本地正常。但是我hexo d 后，在浏览器的的控制台却发现vendors文件夹里面的文件各种404，像?v=x.x.x这种就找不到，导致页面文件404，页面空白，大牛请问咋回事？急啊

![图片](http://ofp4swv4i.bkt.clouddn.com/issues.png)

**Comment by NoahDragon** [comment]
看下服务器上的Vendors文件夹是否正常？

**Comment by CrazyBoyQiang** [comment]
问题解决了吗？同样的问题

**Comment by Sonnyzoom** [comment]
@NoahDragon 服务器上的文件是正常的，我把.deploy_git文件夹删掉重新部署过。但是在浏览器打开的时候
![图片](http://ofp4swv4i.bkt.clouddn.com/issues2.png)
里面是空的。这是怎么回事呢？

**Comment by Sonnyzoom** [comment]
@CrazyBoyQiang 没呢。昨晚想发布新文章的时候就发现打不开网页了。你的是怎么出现的呢？

**Comment by Sonnyzoom** [comment]
@CrazyBoyQiang 没呢。昨晚想发布新文章的时候就发现打不开网页了。你的是怎么出现的呢？

**Comment by yanshengjia** [comment]
同样的问题，昨天下午出现的这个问题，vendors文件夹下的部分js和css无法访问。

目前试了很多方法都没解决。

**Comment by CrazyBoyQiang** [comment]
我也是昨天下午出现的问题，我本地是正常的，就是发布文章的时候出现的

**Comment by Sonnyzoom** [comment]
都是昨天出现的问题？我本地也是正常的，部署到服务器就不行了。是Hexo的问题还是github的问题？

**Comment by yanshengjia** [comment]
不知道，目测是Hexo的问题。

可能是调用的外部js跪了。

**Comment by zhongwuzw** [comment]
同样的问题，部署到github上，vendors目录下的第三方库都报404.

**Comment by Sonnyzoom** [comment]
@zhongwuzw 是昨天遇到的么？原来这么多人遇到啊，还以为只我是一个人呢。看来是坐等官方答复了

**Comment by CrazyBoyQiang** [comment]
找到解决方案了。。 @BBBOND @monsterLin @SpadeRoy 根据作者的提示 @iissnan ，首先修改source/vendors为source/lib，然后修改_config.yml， 将 _internal: vendors修改为_internal:lib 然后修改next底下所有引用source/vendors路径为source/lib。这些地方可以通过文件查找找出来。主要集中在这几个文件中。1. Hexo\themes\next.bowerrc 2. Hexo\themes\next.gitignore 3. Hexo\themes\next.javascript_ignore 4. Hexo\themes\next\bower.json 。修改完毕后，刷新重新g一遍就ok啦。

**Comment by CrazyBoyQiang** [comment]
本人亲测，经过上面的改动就可以了，至于为什么，不知道，有知道的可以告诉我一下

**Comment by CrazyBoyQiang** [comment]
大部队在这里 https://github.com/iissnan/hexo-theme-next/issues/1214

**Comment by Sonnyzoom** [comment]
@CrazyBoyQiang 好的，马上试试~谢谢你

**Comment by Sonnyzoom** [comment]
真的可以了

**Comment by yhhwpp** [comment]
#1214 已经解决

**Comment by NoahDragon** [comment]
很奇怪，我也用NexT部署到到Github，未发现此问题。不过解决就好！

**Comment by CrazyBoyQiang** [comment]
Next新版已经修复了

**Comment by liuli1735** [comment]
用了最新版，依然有这个问题～
