### ISSUE TITLE
关于hexo 在本地好使，传到github 上js css 404 解决方案！！！

### ISSUE THREAD

**Issue by imkratos** [hexojs/hexo#2239]
已经在next主题那里回答了，传送门
[issues#1220](https://github.com/iissnan/hexo-theme-next/issues/1220)

**Comment by NoahDragon** [comment]
👍

**Comment by NoahDragon** [comment]
最简解决方案，下载最新版本的NexT。

iissnan/hexo-theme-next#1214

鉴于同类问题过多，重新open。

**Comment by jetyu** [comment]
https://jetyu.github.io/2016/11/04/20161104/   vendors 改为 libs

**Comment by NoahDragon** [comment]
鉴于此类问题已经不多，关闭此issue。
