### ISSUE TITLE
vendors目录下文件全部404

### ISSUE THREAD

**Issue by gnaixx** [hexojs/hexo#2240]
hexo s 本地是可以正常的显示页面
push 到github后 vendors下所有文件都加载不了了 全面404
页面也就显示不正常了

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo/issues/2239
https://github.com/hexojs/hexo/issues/2238
https://github.com/hexojs/hexo/issues/2235

这是NexT主题的问题，更新最新版本即可修复。
