### ISSUE TITLE
hexo d 成功后网站不能加载部分js文件

### ISSUE THREAD

**Issue by yuanjunli** [hexojs/hexo#2241]
hexo  c
hexo g
hexo s
本地运行blog正常，但是部署到github后，会有些文件加载不到：
hexo g 运行正常。
下面是我的[blog](http:///yuanjunli.github.io)

**Comment by Lnybb** [comment]
遇到同样的问题

**Comment by yuanjunli** [comment]
貌似vendors文件夹的都访问不了，你是怎么出现这个问题的。

**Comment by yuanjunli** [comment]
重装hexo也解决不了。github 仓库是有wndors文件的。

**Comment by Lnybb** [comment]
我用了一个可以加载本地图片的插件**hexo-asset-image**，然后我手动在_post文件夹下新建了一个文档，但是没有新建配套的图片文件夹，一般我是通过命令创建新的文档，然后会自动生成文档以及配套文件的，然后我就**hexo -d**了，然后就加载不出来了，但是**hexo -s**是可以在本地看到的

**Comment by yuanjunli** [comment]
@Lnybb 倒腾后，我重装都无效，我最后把hexo文件夹移出原来的文件夹，再hexo d github就奇迹般的能运行了。你可以试试。

**Comment by NoahDragon** [comment]
#2239
#2238
#2235 
#2240

是NexT主题的问题，更新最新版本可修复。
