### ISSUE TITLE
Failed to load resource. /vendor folder cannot be loaded

### ISSUE THREAD

**Issue by deadcoder0904** [hexojs/hexo#2242]
## Environment Info

Node version(`node -v`)
```
v5.7.0
```

Your site `_config.yml`
```
# Hexo Configuration
url: http://akshaykadam.me/
root: /test/
theme: cactus-dark
```

Site located [here](http://akshaykadam.me/test/). Checkout the console :frowning_face: 

The problem is it doesn't load `/vendor/` folder at all on Github Pages.
I've set it up right & gh-pages branch contains all locations perfectly.
I have tried too much to debug it, as it works locally & doesn't work on gh-pages

[Here is my compiled code](https://github.com/deadcoder0904/test)

**Comment by NoahDragon** [comment]
It's NexT theme's issue. Update to the latest NexT version will fix it.

**Comment by deadcoder0904** [comment]
Added this line,

_config.yml
```
vendors:
   _internal: lib
```

still doesn't generate `lib` folder instead of `vendor`

**Comment by deadcoder0904** [comment]
I created an automation script to get the job done.
Just have to change the name of `vendor` folder. Thank u :smile:

**Comment by andrealmar** [comment]
this happened with one of my customers website. I've just changed the name of the vendor folder to something else. It worked. Very weird though...

**Comment by NoahDragon** [comment]
@andrealmar It caused by the Jekyll update recently https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3 , which will ignore vendor folder automatically.

**Comment by andrealmar** [comment]
@NoahDragon thanks for the explanation
