### ISSUE TITLE
hexo 本地渲染一切正常，传到 github 上 js css 404，更换主题无法解决

### ISSUE THREAD

**Issue by piguyangyang** [hexojs/hexo#2244]
Node version(`node -v`)
```
v6.9.1
```

Your site `_config.yml`
```
# Hexo Configuration
...
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://piguyangyang.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```

Plugin version(`npm ls --depth 0`)
```
+-- hexo@3.2.2
+-- hexo-deployer-git@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-sass@0.2.0
+-- hexo-renderer-stylus@0.3.1
`-- hexo-server@0.2.0
```

## For question

hexo 本地渲染一切正常，传到 github 上 js 404，更换主题无法解决

**Comment by NoahDragon** [comment]
是用NexT主题么？

**Comment by piguyangyang** [comment]
我先后用了landscape, next, dairy 三个主题，都是相同的结果，网上找到的同类解决方法都是有关 next 的更新

**Comment by Neveryu** [comment]
@piguyangyang  https://github.com/iissnan/hexo-theme-next/issues/1220

**Comment by NoahDragon** [comment]
能否截下developer tools里的errors？

![image](https://cloud.githubusercontent.com/assets/5704064/20054544/5111bf00-a4ab-11e6-81b7-2809d1d158da.png)

**Comment by piguyangyang** [comment]
![github-error](https://cloud.githubusercontent.com/assets/19728084/20087435/513c1a6c-a5b3-11e6-9f30-cdb90ab9605e.png)

**Comment by piguyangyang** [comment]
我看了我 repo 中都已经有了这些文件了

**Comment by caozhengi** [comment]
我也出现了同样的问题

**Comment by NoahDragon** [comment]
是github page的设置问题。要使用username.github.io作为URL，必须创建一个名为username.github.io的repo。

![image](https://cloud.githubusercontent.com/assets/5704064/20098240/e0d944e8-a580-11e6-90b0-eb1edc49cdb8.png)

我看见你只创建了个Username的repo，所以其指向的页面为https://piguyangyang.github.io/piguyangyang/

而https://piguyangyang.github.io/并不存在。

**Comment by piguyangyang** [comment]
谢谢了，是我没看清楚文档，导致一直很迷惑。

**Comment by IamGabrielWu** [comment]
谢谢 很赞。 擦，必须google搜索中文才能看到这个解决方案。

**Comment by index-null** [comment]
补充一下,有可能是因为在主题配置的yml文件下修改了url(例如一开始误以为这个url是跳转到我github主页的url)导致访问路径出错,改回成下面这个默认的就行
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://username.github.io/
