### ISSUE TITLE
How to use functions from node_modules in theme/layout/*.ejs?

### ISSUE THREAD

**Issue by pozitron57** [hexojs/hexo#2247]
I have a general question about how to use functions from `node_modules` in `theme/layout/*.ejs` file.

To give an example: I installed [https://github.com/andyhu/node-transliteration](node-transliteration) and can use it in the `node_modules` folder, e.g. I add

    var transliteration = require('transliteration');
    var transliterate = transliteration.transliterate;

and then in hexo-renderer-markdown-it I can use something like `var slug = transliterate(sluggo(title));`, but only in the `node_modules` folder. The question is: how can I use it in `theme/layout/*.ejs` files? To be more precise, I'd like to do something like

    <% site.categories.each(function(cat){ %>
        <%= transliterate(cat.name) %>
    <% }); %>

**Comment by NoahDragon** [comment]
You can register to helper:
https://hexo.io/api/helper.html

**Comment by pozitron57** [comment]
Perfect, thanks! Exactly what I needed. 

PS for the record: I added

    var transliteration = require('transliteration');
    var transliterate = transliteration.transliterate;
    helper.register('transliterate', function(text){
        return transliterate(text);
    });

to `node_modules/hexo/lib/plugins/helper/index.js` and now I can use `<% transliterate('any text, русский текст') %>` in `theme/layout/*.ejs` files.
