### ISSUE TITLE
win10下全新环境npm安装一直失败

### ISSUE THREAD

**Issue by imbajin** [hexojs/hexo#2249]
> 之前在win7是正常的.从没有在npm install就卡住不动了

## Environment Info

Node version(`node -v`)
> 
- os:Win10 Redstone1 pro-version 
- node:v4.4.4
- npm:2.15.1
- git: 2.7.2.windows.1

## For BUG
不管是用官方的$ npm install hexo-cli -g
还是后来查其它失败人的$ npm install hexo --save
还是加上unsafe参数,都不行.

```shell
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl                              i.js" "install" "hexo" "--save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! shasum check failed for C:\Users\it189\AppData\Local\Temp\npm-10588-431                              616bc\registry.npmjs.org\js-yaml\-\js-yaml-3.6.1.tgz
npm ERR! Expected: 6e5fe67d8b205ce4d22fad05b7781e8dadcc4b30
npm ERR! Actual:   1bf793fd383328e9e43546e82a7b6674381edd45
npm ERR! From:     https://registry.npmjs.org/js-yaml/-/js-yaml-3.6.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Hexo_rec\npm-debug.log

```

## For question
debug.log太长,需要可以再补充

**Comment by NoahDragon** [comment]
是Win10 bash shell下么？
好像win10 bash shell有个bug，不知道修复了没。

**Comment by imbajin** [comment]
> @NoahDragon  谢谢回复,是git的bash呢. 然后后来尝试了n次不知道怎么又装上去了.网络原因?

但是中间有一些ERROR 跟 fatal 我很担忧,这样会不会以后跑起来又各种报错,
```shell
-->提示的错误跟警告:npm WARN optional dep failed, continuing fsevents@1.0.15
error: RPC failed; result=56, HTTP code = 200    #这个感觉是github网络原因么?我开了vpn了已经
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

----
#下面是我测试的版本信息,貌似又没有问题,但是总是很虚,问下需要把环境重装么
#目前hexo s -o 可以
$ hexo -v
hexo-cli: 1.0.2
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.5.2
node: 4.4.4
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

```

再就是问下:以前我搭建好了hexo的环境blog,现在换了pc,想快速恢复到之前的hexo环境.
 
直接从coding/github上clone整个blog文件么?  还是直接把之前的json文件跟yml文件跟theme文件下下来呢?
有没有issue也是这样换了环境快速恢复之前的帖子呢.

> whatever,再次感谢你的帮助.

**Comment by NoahDragon** [comment]
npm的警告不太清楚。

重新搭建Hexo环境只需要把Hexo的文件夹拷贝过去就好了。安装hexo-cli后，在目录下run `npm i`，应该就没问题了。如果你用vagrant，这个file可以帮你搭建起hexo运行环境https://github.com/NoahDragon/Vagrantfile/blob/master/4.hexo/Vagrantfile

**Comment by ranjiewwen** [comment]
我也遇到了同样的问题，在pc上是win7的没问题，晚上换成笔记本win10的就是这个问题

**Comment by NoahDragon** [comment]
@ranjiewwen 基本上是node和windows系统间的问题。建议不要保存node_module文件，每到一个新环境都`npm i`一遍。

**Comment by ranjiewwen** [comment]
我换成jekyll了

**Comment by kuroboshi007** [comment]
我npm install的时候也出现过这样的问题，也是win10也能检测出版本，之后挂了vpn再npm install后就好了。不过你挂了vpn没检查出来我就不知道了...

**Comment by ayuLiao** [comment]
我也遇到了同样的问题，弄了一天，解决了，环境win10，一开始VPN使用香港的线路，npm install hexo -g会卡在跟题主一样的地方，然后将VPN换成了美国的，同样方式安装，安装成功，可以常规的操作hexo，安装成功后无法git，要在博客的根目录，注意是博客的根目录下安装npm install hexo-deployer-git -save，不然会报错，这样hexo在我的win10下就可以正常工作了

**Comment by JLHwung** [comment]
@NoahDragon Should we document the installation process for Chinese mainland users? Like npm registry settings or proxy settings.

**Comment by NoahDragon** [comment]
@NoahDragon Agree.
