### ISSUE TITLE
'>' 不支持吗？

### ISSUE THREAD

**Issue by xu6148152** [hexojs/hexo#2250]
``Markdown``中``>``可以表示引用。我在``Hexo``中使用这个标记，效果却是它包含的文字居中？

比如:
>a

但在``Hexo``中a直接是居中的，前面的阴影效果也没有了。是我写的有问题？还是不支持？

谢谢！

**Comment by NoahDragon** [comment]
支持啊，可能是样式将引用居中了吧？

**Comment by xu6148152** [comment]
@NoahDragon 我用的是默认样式，没修改过。好神奇。

**Comment by xu6148152** [comment]
是主题的问题。换主题就好了。closed!
