### ISSUE TITLE
构建得静态网页没有样式

### ISSUE THREAD

**Issue by 3water** [hexojs/hexo#2251]
##  操作系统
win10

## node.js版本
v6.9.1

## hexo版本
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j

## npm版本
3.10.8

**Comment by NoahDragon** [comment]
和这个https://github.com/hexojs/hexo/issues/2244 issue类似？

**Comment by 3water** [comment]
打开localhost：4040是有样式的，但是“hexo g”生成的public文件再浏览器打开就没有样式，而且打开速度很慢。

**Comment by NoahDragon** [comment]
这是因为文件直接打开，会有路径问题。

localhost上看到的结果，一般是最终样式。

**Comment by 3water** [comment]
谢谢，是自己二逼了。
