### ISSUE TITLE
_config.yml does not overwrite themes _config.yml

### ISSUE THREAD

**Issue by guileen** [hexojs/hexo#2253]
I use submodule to add theme, and I need to change the theme configuration. I overwrite it at root _config.yml, but it does not works, then I modify at themes _config.yml, it works.

hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.3.0
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h

**Comment by guileen** [comment]
I found #757 has make this feature. But there is no document for it.

**Comment by NoahDragon** [comment]
It is reverse way, theme config overwrite root config.

**Comment by jmlntw** [comment]
I think that root config should overwrite theme config. So we can define the theme in root config without modifying the theme. It will be useful if you install the theme as a Git submodule.

**Comment by NoahDragon** [comment]
@jmlntw True, I encountered the same issue. What my solution is:
1. remove submodule,
2. fork the theme on my own repo.

Using theme config to overwrite the root config is more logic (specific cases suppress generic cases), and also reduces the complexity when debugging.
