### ISSUE TITLE
网页只有样式不显示文字，但在本地 hexo d 查看没有任何问题。

### ISSUE THREAD

**Issue by yuansuye** [hexojs/hexo#2254]
>![](http://odxw2uear.bkt.clouddn.com/site-style-1.png)
# 网址：https://yinchangli.me

**Comment by NoahDragon** [comment]
是NexT主题的问题
![image](https://cloud.githubusercontent.com/assets/5704064/20200053/cfb462e4-a77c-11e6-83ae-0187dee63add.png)
自11月以来，jekyll更新后，Github在Deploy的时候自动屏蔽Vendor文件夹。

**Comment by yuansuye** [comment]
恩恩，知道了，已经通过修改vendor为lib解决。
