### ISSUE TITLE
How to make a theme support custom partial

### ISSUE THREAD

**Issue by guileen** [hexojs/hexo#2255]
I need to make my theme support add some custom content in the post template. 

How can I make my theme template include partial template from the site folder?

**Comment by NoahDragon** [comment]
It depends on what template you are using.

For EJS:
``` ejs
 <%- partial('PATH_TO_CUSTOM_TEMP/CUSTOM_TEMP') %>
```

**Comment by NoahDragon** [comment]
Let's say you have following folder hierarchy.

Hexo
|---Source
|---Theme
     |---SomeTheme
          |---Source
          |---Layout
               |---partial
                    |---custom.ejs
               |---index.ejs

To include custom.ejs in the index.ejs, you can write the following into index.ejs:
```
<%- partial('partial/custom') %>
```
