### ISSUE TITLE
如何在文章间设置链接？

### ISSUE THREAD

**Issue by cxgreat2014** [hexojs/hexo#2257]
譬如说在文章1中我想插入文章2的链接，我该怎么做？

**Comment by cxgreat2014** [comment]
我在segmentfault上找到了这个：https://segmentfault.com/q/1010000006210048 和知乎上找到了这个：https://www.zhihu.com/question/48490384 但是都不能解决问题，官方难道没有这个功能吗？

**Comment by cxgreat2014** [comment]
求助

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo/issues/2176 中提到可用post link tag plugin。

**Comment by cxgreat2014** [comment]
thanks~!

**Comment by anxiaoyi** [comment]
@NoahDragon post link 在一段中多次使用 post link，只有第一个得到了渲染，剩下的都没有被渲染，依然是这种样式:

```
{% post_link helloworld %}
```
