### ISSUE TITLE
Link to a category page from a markdown post?

### ISSUE THREAD

**Issue by daiyi** [hexojs/hexo#2259]
How do I link to a category page from within a markdown post? Basically I am looking for [include posts](https://hexo.io/docs/tag-plugins.html#Include-Posts) tag plugin for category pages.

For example, if I want to render the "recipies" category link, e.g. `example.com/blog/categories/recipies/`, can I use something like `{% category_link recipies %}` within a post.md file to produce the correct relative category link? 

I know I can just hardlink `[recipies](/blog/categories/recipies/)`, but I'd like to do it in a way that doesn't break all my links if I decide to rename my root directory (in this example it is `/blog/`).

**Comment by stevenjoezhang** [comment]
This issue is expected to be solved by the `url_for` tag plugin:

https://github.com/hexojs/hexo/issues/4749

usage:

```
{% url_for /categories/recipies/ %}
```
`url_for` will prepend a root directory to the URL automatically
