### ISSUE TITLE
hexo 搭建博客 本地没问题 push到git以后，打开文章404

### ISSUE THREAD

**Issue by adgad2** [hexojs/hexo#2260]
可以打开主页，分类也可以点，但是打开文章就会出现404，即使想新建文章也是这样。
不找到是什么问题？
库地址： https://github.com/adgad2/adgad2.github.io
域名：mrone.top
Google了很久也没找到解决方法，不知道是怎么回事？

更换主题也无法解决，问题好像初始于安装 baidusitemap，莫名其妙就打不开了。

**Comment by NoahDragon** [comment]
https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
添加.nojekyll应该可以解决此问题。
