### ISSUE TITLE
Another layout? 

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#2263]
Hello all, 
I wanted to have another layout file for my template that does not include a header and footer. I have a page called test.md and set the layout to false,  but when I view the page it's literally a blank template with no HTML. 

So just to clarify,  how can I have a template that does not have a header and footer? So layout.ejs is the full design template and maybe a new layout file called layout_black.ejs that does not include any headers or footers. 

Thank you in advance.

**Comment by NoahDragon** [comment]
If you have the layout_balck.ejs that not include any headers or footer, to use it, you can set the layout to layout_black in the post/page front matter.

```yml
layout: layout_black
```

**Comment by ntot** [comment]
Hi thanks for the quick reply.  I tried that but it still uses layout.ejs and not layout_black.ejs

**Comment by NoahDragon** [comment]
Could you please run `hexo g --debug` to see if the layout_balck has been used?
