### ISSUE TITLE
hexo在本地可以访问，在github上网站都无法打开了

### ISSUE THREAD

**Issue by basebase** [hexojs/hexo#2264]
昨天跟新文章在本地测试可以访问，然后hexo d到了github后网站无法打开了
一直就是个空白页，github也没有给我发送错误邮件，发送邮件是否需要配置，怎么配置呢？

**Comment by Neveryu** [comment]
@basebase 可否给一个线上地址看一下

**Comment by basebase** [comment]
@Neveryu 你好访问： basebase.github.io

**Comment by bluejfox** [comment]
我的也是一样，https://bluejfox.github.io/
看了一下浏览器的控制台，一些第三方文件(jquery等)无法加载（404）
另外在本地运行hexo generate的时候会有错误出现。
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)

**Comment by NoahDragon** [comment]
https://github.com/iissnan/hexo-theme-next/issues/1214 这个issue里有详细解答。

**Comment by basebase** [comment]
@bluejfox 我看到控制台无法加载类库，昨天也看到过楼上的帖子之后就解决了
