### ISSUE TITLE
Got Error when execute hexo-cli command.

### ISSUE THREAD

**Issue by bluejfox** [hexojs/hexo#2268]
When I execute hexo --version on iterm. I got below error:
Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

My hexo version:
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j

**Comment by NoahDragon** [comment]
Could you please try to reinstall Hexo?

**Comment by bluejfox** [comment]
I got the same error when I reinstalled hexo.

**Comment by NoahDragon** [comment]
How about `npm rebuild`? 

Here is a reference http://stackoverflow.com/questions/15584529/module-version-mismatch-expected-11-got-1

**Comment by bluejfox** [comment]
Many thanks.Rebuild dtrace-provider module can solve this problem.

**Comment by NoahDragon** [comment]
Great, glad you solved it.
