### ISSUE TITLE
Different subfolders in source / different post-types?

### ISSUE THREAD

**Issue by timpulver** [hexojs/hexo#2269]
Hi,

is it possible to have multiple source subfolders in the source folder?
I would like to create a project by using:

```
hexo new project "Project1"
```

Which would generate:

```
source/_projects/Project1.md
```

Besides I need a folder for artists, generating a new one with:

```
hexo new artist "Harald"
```

should create:

```
source/_artists/Harald.md
```

Hope this is possible!?

Cheers,
Tim

**Comment by NoahDragon** [comment]
Maybe some [plugins](https://hexo.io/plugins/) already support such behavior, I'm not sure.

**Comment by timpulver** [comment]
I had a look, but didn’t find any.
