### ISSUE TITLE
deploy to github css not found with gh-pages

### ISSUE THREAD

**Issue by EasonWang01** [hexojs/hexo#2272]
I thought this problem cause by the default resource route will point to the dns name,but in github gh-pages the dns will append the repo name.

how to solve this? thanks for reply.
<img width="1280" alt="2016-11-17 2 23 30" src="https://cloud.githubusercontent.com/assets/11001914/20378493/79644ada-acd1-11e6-83c6-a591a49a6f82.png">

**Comment by EasonWang01** [comment]
add this in config will work.
```
url: http://yoursite.com/blog
root: /blog
```

**Comment by epogrebnyak** [comment]
For some reason /blog vs /blog/ had a difference for me.
