### ISSUE TITLE
开启了post_asset_folder后如何在文章中插入带有class的图片呢？

### ISSUE THREAD

**Issue by cxgreat2014** [hexojs/hexo#2275]
`{% img class名称 图片绝对路径 %}`这样可以插入绝对路径的带有class的图片
`{% asset_img 图片文件名 [title] %}`这样可以插入文章资源目录下的图片，
那么，如何插入文章资源目录下的图片还让它带class呢？

**Comment by NoahDragon** [comment]
难道不是`{% asset_img class名称 图片文件名 [title] %}`么？

**Comment by cxgreat2014** [comment]
不起作用，图片不显示

**Comment by cxgreat2014** [comment]
准确的说是这个标签都被过滤掉了

**Comment by cxgreat2014** [comment]
算了，我直接把那些要加class的文件单独放到一个文件夹了。。😂

**Comment by NoahDragon** [comment]
我觉得这应该是一个Enhancement。

**Comment by larrxu** [comment]
+1

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo/pull/2790
