### ISSUE TITLE
建议在配置文件中设置分类

### ISSUE THREAD

**Issue by bruceyu1994** [hexojs/hexo#2276]
建议在配置文件中可以设置所有分类和标签，而在每篇文章中通过类似数组下标的形式引用分类，如果想要将某个分类改一下名字，只需要修改配置文件即可，而无需将每篇文章都进行修改，这样工作量太大了

**Comment by NoahDragon** [comment]
的确是挺麻烦的。在配置文件中添加数十上百的分类和标签，也挺麻烦的……
