### ISSUE TITLE
有没有好的办法能够把.Rmd文件较好地部署到博客中？

### ISSUE THREAD

**Issue by swordspoet** [hexojs/hexo#2277]
我最近在R studio中写了一个文档，后缀名是.Rmd，HEXO可以支持将IPython Notebook嵌入到博客中来，有什么好的办法能够支持R studio呢？

**Comment by NoahDragon** [comment]
ipython支持么？

**Comment by weidongzhou1994** [comment]
请问，有好的解决方法了吗？？
