### ISSUE TITLE
markdown解析格式问题

### ISSUE THREAD

**Issue by lslvxy** [hexojs/hexo#2279]
同一段md代码在主题内解析的格式不一样
以下是md内容

```js
[npm 文档](https://docs.npmjs.com/) 
和 
[CLI 命令行文档](https://docs.npmjs.com/#cli) 
是非常不错地的学习资料，但需要通过浏览器访问，这并不是很方便。因而可以通过命令行快速获取所有
```

正常的解析结果应该是
```js
npm 文档 和 CLI 命令行文档 是非常不错地的学习资料，但需要通过浏览器访问，这并不是很方便。因而可以通过命令行快速获取所有
```

但是通过`hexo s`启动服务后页面解析结果为

```js
npm 文档
和
CLI 命令行文档
是非常不错地的学习资料，但需要通过浏览器访问，这并不是很方便。因而可以通过命令行快速获取所有
```
就是说md文档中的换行符也给解析了。
在github中的解析结果为

[npm 文档](https://docs.npmjs.com/)
和
[CLI 命令行文档](https://docs.npmjs.com/#cli)
是非常不错地的学习资料，但需要通过浏览器访问，这并不是很方便。
因而可以通过命令行快速获取所有

**Comment by NoahDragon** [comment]
这是由于设置了Github flavored markdown.
在设置中加入如下代码：
```yml
marked:
  gfm: false
```
