### ISSUE TITLE
How to handle page 404 on my hexo server?

### ISSUE THREAD

**Issue by simonbruneaud** [hexojs/hexo#2280]
Hi, I want to deploy hexo server (not static file) in my own server.
But I have no idea how to handle page 404 not found
(I didn't see how to do this in the hexo docs)

**I tried to create a 404 page:**
`hexo new page 404`

**Config 404 page:**
```
title: 404 Not Found
toc: false
comments: false
layout: 404
type: 404
permalink: /404
subtitle: This article does not exist...
---
```

**Path of 404 file**
```
/root
  /source
    /404
      /index.md
```

I can access this 404 page with **localhost:4000/404.html**  
or (on docker) - **192.168.99.100:4000/404.html**
But redirection does not work : **localhost:4000/azeae** - **192.168.99.100:4000/azeae**

**Comment by NoahDragon** [comment]
Because the 404 should be in the root folder, directly create a `404.md` under `source` folder would be a solution.

**Comment by simonbruneaud** [comment]
Ok I'll try it, I just have to create that 404.md, is my frontmatter syntax ok?

**Comment by NoahDragon** [comment]
I don't see any problem there. Just for your reference, my front matter is following:
```yml
---
layout: page
title: 404 Page Not Found
comments: false
---
```
