### ISSUE TITLE
hexo d 不能运行

### ISSUE THREAD

**Issue by liangpu597** [hexojs/hexo#2282]
以前都可以，今天好像把什么插件给删除了。
hexo d 没有反应
没有报任何错 直接进入命令行模式

而hexo server本地预览正常
尝试了hexo init 后还是不行，请问，这是怎么回事？
谢谢！

**Comment by NoahDragon** [comment]
是不是把[hexo-deployer-git](https://github.com/hexojs/hexo-deployer-git) 删除了？

**Comment by liangpu597** [comment]
不知道，我hexo init 了几次，重新配置，现在好了。谢谢哈！

2016-11-25 23:54 GMT+08:00 Abner Chou <notifications@github.com>:

**Comment by NoahDragon** [comment]
好的，不客气。
