### ISSUE TITLE
能否让achive比page显示更多文章？

### ISSUE THREAD

**Issue by cxgreat2014** [hexojs/hexo#2284]
归档页面和index page每页显示的文章数量都是一样的，能否把这两个分离开来，让archive页面显示的文章数量也可以自定义呢？

**Comment by NoahDragon** [comment]
同求此方法~

**Comment by cxgreat2014** [comment]
@NoahDragon 目前我找到的唯一一种方法是手动合并，首先以index想要显示的数量生成一份，再以archive的数量生成一份，再拿archive生成的那份的archive目录覆盖掉index的那份的目录=_=。。。虽然也可以实现，但实在是折腾得很

**Comment by tiexo** [comment]
在_config.yml里面自定义一条：
```
# hexo-generator-archive
archive_generator:
  per_page: 30
 
```
