### ISSUE TITLE
一篇文章总字符数过多会出现乱码是什么问题?

### ISSUE THREAD

**Issue by leer0911** [hexojs/hexo#2285]
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.5.2
node: 4.4.7
v8: 4.5.103.36
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

![image](https://cloud.githubusercontent.com/assets/8563549/20655448/7c9e2bdc-b55d-11e6-98f6-4ea27c2e9e64.png)

**Comment by NoahDragon** [comment]
好像是hexo server上才有的问题，在deploy一般没有问题。
https://github.com/hexojs/hexo-server/issues/23

**Comment by tanchao90** [comment]
遇到同样的问题，折腾好久都没找到原因，谷歌后发现果然是这个问题，找了一个大文本去测试，立马重现。

话说又什么解决办法吗？

**Comment by NoahDragon** [comment]
@tanchao90 目前还没有fix，只能是大文件不要使用hexo server来查看。
