### ISSUE TITLE
Category Yearly Archive

### ISSUE THREAD

**Issue by pierrehenri220** [hexojs/hexo#2286]
Good day all,

I played with hexo locally, really impressive tools 👍  I'm looking for advises please.
I'm trying to keep my urls and my issue is how do you handle an archive like this one please:
* /news/category/year/index.html ?

I tried various ways but I got stuck. I faced two issues:

1. Keeping a parent / root directory. In my case news is not a category (might be)
I don't know how do you handle a hierarchy with a generator, I mean something like multiblogs / subcategories 

2. Generating category yearly archives
About this one if I do a mashup of hexo-generator-archive and hexo-generator-category it's possible ? Something like hexo-generator-category-yearly

Thank you for your time, I would appreciate any ideas

蛙220

**Comment by NoahDragon** [comment]
Does the following issue answers your question?
https://github.com/hexojs/hexo/issues/2119

**Comment by grenouille220** [comment]
@NoahDragon Yes it answers, it's not the kind of solution I was thinking about.
With the " - " solution, I would use for example tags like news2016foo or something like that in the permalink settings. This would generate a bunch of root folders and then using rewrite rules on the server I could achieve it. Not that sexy.

I discover something great while testing. the category are 'classification'. 
So I set something like:
~~~
category:
    - news
    - 20XX
    - foo
~~~

I can cover the following ouputs:
* /news/
* /news/20XX/
* /news/20XX/foo

I only miss /news/foo. Is there an easy way to generate it ?
What I did is if i set the tag "foo" in the post and "news" as tag directory in the config.yaml, it would work but only for the folder news which is good anyway for my case in the current project. So it's good for now only.
The 'easiest' I found for now is:

config.yaml:
~~~
tag_dir: news
category_dir: / 
~~~

post.md:
~~~
---
title: Happy New Year
category:
    - news
    - 2016
    - office
tag:
    - office
    - event
    - party
---
~~~

Cheers
