### ISSUE TITLE
部署到nginx缺失样式

### ISSUE THREAD

**Issue by lhtdeg** [hexojs/hexo#2287]
我是在centos服务器上通过git hook控制hexo g的。
使用hexo s显示正常
<img width="1358" alt="qq20161130-0 2x" src="https://cloud.githubusercontent.com/assets/7857624/20758288/4955cb88-b754-11e6-8523-1bbfc1c4584a.png">
但是将nginx的目录设置到/public目录，并开启服务的时候，显示不正常。请问是什么原因？
<img width="765" alt="qq20161130-1 2x" src="https://cloud.githubusercontent.com/assets/7857624/20758321/6039e1ae-b754-11e6-9ba3-8df0f26c6ed3.png">

**Comment by NoahDragon** [comment]
我觉得还是路径上的问题，我也用nginx，并无此问题。
顺带一提，我也是用这个主题 :）

**Comment by lhtdeg** [comment]
问题解决了，原因是设置nginx配置文件的时候设置的是location的root路径，将root路径改放到server下显示正常。
作为Android开发者，对Material Design的主题没有抵抗力~XD
