### ISSUE TITLE
Repository language barrier

### ISSUE THREAD

**Issue by AWulkan** [hexojs/hexo#2289]
Am I the only one here who finds it highly confusing and difficult to understand what's going on in this repo? People are opening and closing issues in different languages and half of us don't know what the other half is working on.

Is there any way to solve this problem (except for Google translate, which is terrible)? It feels like it's fragmenting the community and slowing down progress.

What do you all think about this? Have you found a good way of solving the issue?

**Comment by NoahDragon** [comment]
We highly recommend and encourage using English as default language while submitting issues. However, this is not controllable. 

If you find a solved issue that in another language, please feel free to leave comments for translation. I'm happy to help if the language is Chinese. :)

**Comment by AWulkan** [comment]
@NoahDragon Ok, but my point was that there's a lot of open issues and it's very difficult to get a grasp on what's being worked on, or what people are having problems with. I don't know if I'm trying to figure out a solution for something that someone else has already started working on. It's a very inefficient way of working.

Anyway, I guess there's no good solution to this since the ones that don't speak English probably don't know the language. Because if they could, they would.

I'll close this issue since it's not leading anywhere. Maybe we could at least ad a text in the repository readme file stating that English is the preferred language?

**Comment by NoahDragon** [comment]
@AWulkan Really appreciate your suggestion. As the Readme already written in English, which implies our preferred language. If you feel it is necessary to add into Readme, please feel free to create a PR for it.
