### ISSUE TITLE
如何修改，增加doc里面的内容

### ISSUE THREAD

**Issue by eboxmaker** [hexojs/hexo#2292]
如何修改，增加doc里面的内容，我想在doc里面添加我自己的文件，都需要修改哪里？
有没有详细的过程或者步骤

**Comment by NoahDragon** [comment]
不是很明白，请问Doc是指什么？

**Comment by eboxmaker** [comment]
我会弄了~~~，就是增加些markdown文件和相应的sidebar
http://www.eboxmaker.com/

**Comment by eboxmaker** [comment]
thanks

**Comment by NoahDragon** [comment]
👍 弄好了就好~
