### ISSUE TITLE
Deprecated dependencies (swig & minimatch)

### ISSUE THREAD

**Issue by AWulkan** [hexojs/hexo#2295]
## Environment Info

Node version(`node -v`)
```
v6.9.1
```

When doing a `hexo init mywebsite` it warns about two outdated dependencies:
```
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

This should probably be looked into since both of these dependencies are HEAVILY outdated.

**Comment by NoahDragon** [comment]
I could update those sem versions in package.json, but sadly I don't have permission to publish to npm.

**Comment by tianp** [comment]
```minimatch``` is already updated to ```v3.0.0``` in master so the ```minimatch``` npm warn will be gone in next publish I suppose.

Also I think you guys need to move on from ```swig``` since it's no longer maintained. What do you think?

**Comment by NoahDragon** [comment]
@tianp Agree.
