### ISSUE TITLE
关于hexo中代码块的问题

### ISSUE THREAD

**Issue by wlwlxgg** [hexojs/hexo#2296]
有的时候代码太长，能否固定文章中代码的行数，然后用滚动条去看剩下的部分

**Comment by NoahDragon** [comment]
这个似乎可以通过CSS样式来调节~

**Comment by BruceLpc** [comment]
在markdown 中，代码块用 三个 ```  包起来 ，hexo g命令生成时会报如下错误：
YAMLException: end of the stream or a document separator is expected at line 10, column 1:
    ```javascript
    ^

**Comment by BruceLpc** [comment]
在markdown 中，代码块用 三个```包起来 ，hexo g命令生成时会报如下错误： YAMLException: end of the stream or a document separator is expected at line 10, column 1
