### ISSUE TITLE
关于页无法插入图片

### ISSUE THREAD

**Issue by jiangxiaoqiang** [hexojs/hexo#2298]
这里是dolphin的部落格，若此分享能够作为您的参考，是我的荣幸。

{% asset_img qrcode.jpg 微信扫码关注%} ----在关于页面里插入一张微信公众号图片

在关于页的文件夹下存在qrcode.jpg的图片，但是生成的页面未显示图片。

**Comment by NoahDragon** [comment]
asset似乎只支持post，不支持page。

https://github.com/hexojs/hexo/blob/5234c4a85dc6cd418e9a1c169e43de169cf98e95/lib/plugins/tag/asset_img.js#L18

**Comment by jiangxiaoqiang** [comment]
@NoahDragon 直接使用markdown图片引用的相对路径来解决，没有使用asset。好在问题解决了，谢谢你
