### ISSUE TITLE
How can i add a about.ejs for /aboout

### ISSUE THREAD

**Issue by C1tas** [hexojs/hexo#2300]
i add about.ejs in theme/mytheme/layout/ but hexo won't compile it 

我增加了一个 about.ejs 在 theme/mytheme/layout 但是hexo不会去编译这个ejs文件 对应到/about这个路由

**Comment by NoahDragon** [comment]
需要在front matter里添加

``` yml
layout: about
```

**Comment by C1tas** [comment]
非常感谢
