### ISSUE TITLE
post_assert_folder bug

### ISSUE THREAD

**Issue by wanguanglu** [hexojs/hexo#2301]
if we set post_asset_folder to ture in _config.yml
```
post_asset_folder: true
```
and when we insert link to files in the folder.

it will display well in web page of the post. but it won't display well in the homepage.
the url link to target is wrong.

for example,  in [my homepage](http://www.wanguanglu.com).
there is a image, it's link is
http://www.wanguanglu.com/1480764149609_5.png
which is wrong.

but in the [post page](http://www.wanguanglu.com/2016/12/04/baiduyun-sync/)
the link to the image is 
http://www.wanguanglu.com/2016/12/04/baiduyun-sync/1480764149609_5.png
which is right

**Comment by NoahDragon** [comment]
assert not support on pages. Could use img tag instead.

https://hexo.io/docs/tag-plugins.html#Image

**Comment by wanguanglu** [comment]
yes, i fixed it. it's my fault. 
thankyou
