### ISSUE TITLE
_post 文件底下 .git文件丢失 上传后 发现 文章页 404

### ISSUE THREAD

**Issue by BZbyr** [hexojs/hexo#2303]
_post 文件底下 .git文件丢失 上传后 发现 文章页 404
发现 github上 储存文章哪里没有更新 这样的问题该怎么解决。。。

**Comment by NoahDragon** [comment]
在配置文件里，添加：
``` yml
include:
  - .git
```

如果你是使用hexo-git-deployer插件，请获取最新版本。因为旧版本有个bug，无法push隐藏文件。

**Comment by BZbyr** [comment]
yes
