### ISSUE TITLE
Remove Nodejs 0.12 for Travis-CI and Appveyor

### ISSUE THREAD

**Issue by NoahDragon** [hexojs/hexo#2304]
I think Hexo should move forward, and relax some backward compatibility.

Eventually, we should only focus on the Nodejs stable and latest LTS build. Although 0.12 is a stable version, it will soon stop supported. 

An additional suggestion is to re-write Hexo in ES2015 standard or maybe TypeScript.

**Comment by JLHwung** [comment]
[lebab](https://github.com/lebab/lebab) will help when re-writting hexo in ES2015.

**Comment by NoahDragon** [comment]
@JLHwung Great tool!
