### ISSUE TITLE
No extension files are rendered as empty

### ISSUE THREAD

**Issue by noraj1337** [hexojs/hexo#2307]
## Environment Info

Node version(`node -v`)
```
v7.2.0
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 /home/noraj/Dev/hexo_rawsec
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.0
├── hexo-generator-json-content@2.2.0
├── hexo-generator-tag@0.2.0
├── hexo-i18n@0.2.1
├── hexo-pagination@0.1.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-less@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-sass@0.2.0
├── hexo-renderer-scss@1.0.2
├── hexo-renderer-stylus@0.3.1
├── hexo-server@0.2.0
└── hexo-tag-bootstrap@0.0.8
```

## For BUG

- BUG description
I host my hexo site on gh-pages. I have a `CNAME` and a `README` file in my sources folder. They have no extension so before they were left as they were during the rendering (simple text). But now (I don't know since when) file with no extention are rendered as void, so my two files are rendered as empty.

- the way to reproduce
hexo g

**Comment by NoahDragon** [comment]
I couldn't reproduce the issue. Mine works fine.

**Comment by noraj1337** [comment]
It is still hapenning for me.

**Comment by NoahDragon** [comment]
Based on my understanding the file without extension couldn't be rendered, as the renderer needs the specific file extension.

**Comment by noraj1337** [comment]
@NoahDragon : yes but before they were left as is, just copied, and now they are nulled/voided.

**Comment by NoahDragon** [comment]
May I ask what OS are you using? If it is windows, it hides the known extension by default.

**Comment by noraj1337** [comment]
@NoahDragon : I use Manjaro (ArchLinux Based).

**Comment by noraj1337** [comment]
Here the full process to reproduce the bug :  https://asciinema.org/a/3egc3k1w2ize13derfzc4wtz7

**Comment by noraj1337** [comment]
Seems I can't reproduce.
