### ISSUE TITLE
紧急求助，不能deploy了！

### ISSUE THREAD

**Issue by zippera** [hexojs/hexo#231]
hexo generate
hexo deploy
之后，一直出现这个，等多久都不动。github上的repository中一点变化都没有。
![qq20130706093557](https://f.cloud.github.com/assets/1762779/756062/565bb162-e5de-11e2-8f72-a54beaa276c0.png)

删除.deploy后，再执行上述命令，如下，不动了。
![qq20130706094341](https://f.cloud.github.com/assets/1762779/756064/73514a02-e5de-11e2-8c4f-08df673b2390.png)

**Comment by enjoyhot** [comment]
在hexo g发生unexpected end of comment的报错，不知为什么，查了一下格式，unix格式，结尾也没错，郁闷。

**Comment by liujb** [comment]
我勒个去 这个问题还没解决吗？

**Comment by csuldw** [comment]
怎么解决？？？？

**Comment by brizer** [comment]
同问，哥哥们，怎么解决这个问题，有答案的么？

**Comment by zning1994** [comment]
不是被墙的原因吗

**Comment by Xuanwo** [comment]
自备梯子。
