### ISSUE TITLE
do you render on sever side for seo ?

### ISSUE THREAD

**Issue by jpca999** [hexojs/hexo#2311]
I want to use it for seo purposes also.

**Comment by NoahDragon** [comment]
As far as I know, Hexo doesn't support rendering on server side.

**Comment by jhabdas** [comment]
Oof. That's a huge problem. In fact, if Hexo is to contend with Hugo or Jekyll it's critical it support Isomorphic rendering:

https://habd.as/telltale-signs-your-react-app-isnt-seo-friendly/

**Comment by jhabdas** [comment]
If Hexo is truly a "static site generator", it has to support SSR be definition. Here's a simple way to test SEO issues: https://habd.as/telltale-signs-your-react-app-isnt-seo-friendly/#identify-seo-issues

**Comment by jpca999** [comment]
@jhabdas  i need yes or no answer.

**Comment by jhabdas** [comment]
@jpca999 Static sites are rendered on the server and are better for SEO - and the Web in general - as the sites they generate, by default, are a bundle of flat files most any user agent, browser or scraper can understand. Once the flat files are generated, drop them on a configured web server and your done.

So, assuming Hexo is an SSG, the answer is yes. The caveat to using Hexo is the Node ecosystem and its oftentimes unpredictable shifts. If you're just getting started you'll want to choose an SSG that you feel is well-supported and will be around for a while. For those just getting started with static sites I recommend Jekyll as it's been around for years, has a mature plugin ecosystem, is actively maintained and enjoys GitHub pages support out of the box.

**Comment by jhabdas** [comment]
Once you get a handle of Jekyll I suggest experimenting with Hugo, here's why: https://habd.as/choose-hugo-over-jekyll/
