### ISSUE TITLE
using cmd,type hexo d, Error: Permission denied (publickey).

### ISSUE THREAD

**Issue by ccccccmd** [hexojs/hexo#2312]
using cmd   , type `hexo d` , error occurs:

`Error: Permission denied (publickey).
fatal: Could not read from remote repository.`

but using git bash ,everything is ok.

**Comment by NoahDragon** [comment]
The ssh key doesn't add to cmd environment.

Using ssh-add to add the key.
``` bash
ssh-add ~/.ssh/id_rsa
```

**Comment by ccccccmd** [comment]
我检查了，已经添加好了，cmd下‘hexo d’前面都正常，就在push的时候报错。

手动在 ‘cmd push’其他仓储没问题。

奇怪了。

![](http://ww1.sinaimg.cn/large/ec649803gw1fari51xjexj20m90gowif.jpg)

**Comment by lzjqsdd** [comment]
参考下ssh设置
[https://help.github.com/articles/generating-an-ssh-key/](url)

**Comment by ccccccmd** [comment]
都ok的，cmd  下 输入`git push` 也能成功，

但是在cmd下 `hexo d`的 `push` 就是不行

**Comment by NoahDragon** [comment]
Could you please paste the configuration for the git deployer?

**Comment by ccccccmd** [comment]
> deploy: 
  type: git
  repo: git@github.com:ccccccmd/ccccccmd.github.io.git
  branch: master
  message: "update blog"

**Comment by xibuka** [comment]
I got the same issue with you. 
I have fixed it when I add the output of my `~/.ssh/id_rsa.pub` to [https://github.com/settings/ssh](https://github.com/settings/ssh)
you can also check ：[https://xuanwo.org/2015/02/07/generate-a-ssh-key/](https://xuanwo.org/2015/02/07/generate-a-ssh-key/)

**Comment by koww** [comment]
I got the same issue and I'm using my private Git repo host. I can ssh access my host and clone and push from cmd, but hexo d could not work. Any idea which part is wrong?
