### ISSUE TITLE
Hexo for multiple sites

### ISSUE THREAD

**Issue by mrttl** [hexojs/hexo#2320]
Hello all,
I am new to Hexo, I have aroud 15 client sites and personal sites that I would like to convert into Hexo.
What is the best way to work with multiple sites in Hexo? I am new to Node as well, but I saw for each site I had a note_modules folder, so if I have 20 sites I would also need 20 node_modules sites as well? Or can I just have one node folder and the rest link to it?

I hope I made sense.
Thanks in advance and keep up the amazing work!

**Comment by NoahDragon** [comment]
What I did is creating multiple folders for different sites. I don't know if there is better way to do so.

**Comment by mrttl** [comment]
Hi NoahDragon,
Thank you for the quick reply. Could you share how you have your projects in Hexo? It would be much appreciated.

**Comment by NoahDragon** [comment]
I have two domains: one is `abnerchou.me`, and another is `legofan.cc`. So I created two folders for each of them, and initial the Hexo in the folder respectively.  Upon that, I also created a bash script to push/deploy both sites simultaneously. 

Hope this could help.

**Comment by mrttl** [comment]
oh I see, now I understand, I thought you had a shared node_modules folder. Thanks for the reply and help.

**Comment by NoahDragon** [comment]
No problem.

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo/issues/2090 In this issue, @dotmagic using grunt or gulp to maintain node-modules folder outside of the Hexo directory.
