### ISSUE TITLE
hexo-apollo主题启动的时候左下角出现/ally/accessiblity-menu.js？

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo#2326]
### 问题描述

具体效果请参看一下[网站地址][1]，加载网页的时候左下角会弹出/ally/accessiblity-menu.js。

### 配置环境

debain8 + nodejs4.2.6 + npm3.5.2 + hexo: 3.2.2 + hexo-cli: 1.0.2

### 问题补充

[apollo主题地址][2]，安装完全按照README安装的，采用的也是最新主题。ps:其他采用apollo主题的网站，[比如这个网站][3]并没有出现这种情况。

```
npm install --save hexo-renderer-jade hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive
git clone https://github.com/pinggod/hexo-theme-apollo.git themes/apollo
```

我怀疑是hexo-renderer-jade的问题，所以就remove了hexo-renderer-jade以后，网站完全无法访问，访问的话会返回下面的内容。
```
extends partial/layout block container include mixins/post +posts() block pagination include mixins/paginator +home() block copyright include partial/copyright
```

其他主题比如landscape并没有出现这种问题，请问这是什么原因导致的？

  [1]: https://alpsem.github.io
  [2]: https://github.com/pinggod/hexo-theme-apollo
  [3]: http://andrewliu.in/

**Comment by NoahDragon** [comment]
感觉是mathjax问题。
![image](https://cloud.githubusercontent.com/assets/5704064/21455914/10578b82-c8f2-11e6-8523-b3fb4a92d962.png)

**Comment by Dreyer** [comment]
I'm getting this issue on a fresh install of Hexo using the apollo theme. What exactly is it I'm missing. My page is blank HTML page except for the message:

```
extends partial/layout block container include mixins/post +posts() block pagination include mixins/paginator +home() block copyright include partial/copyright
```

**Comment by NoahDragon** [comment]
@Dreyer have you installed the jade renderer? https://github.com/hexojs/hexo-renderer-jade

**Comment by Dreyer** [comment]
@NoahDragon, I tried installing `hexo-renderer-jade` and ran `clean`, `generate` and `serve` and it still displays the same message.

This is the `package.json` I currently have:

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.6"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-sftp": "^0.1.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-migrator-wordpress": "^0.1.2",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-jade": "^0.4.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-scss": "^1.0.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

**Comment by NoahDragon** [comment]
@Dreyer a temp solution is to lock version number for `hexo-renderer-jade` to "0.3.0".

**Comment by NoahDragon** [comment]
@Dreyer please get hexo-renderer-jade 0.4.1, this issue should be fixed. https://github.com/hexojs/hexo-renderer-jade/pull/11

**Comment by Dreyer** [comment]
I'm going to fork the `hexo-theme-apollo` and migrate the codebase from Jade to Pug. It might be better to move forward with latest libraries than be stuck with old ones until other library maintainers improve the backward compatibility with Jade.

**Comment by Doragd** [comment]
就是mathjax的问题，换一个就好了
我使用的是https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
在apollo\layout\partial\scripts.jade 里面 
改成
script(async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML" )

**Comment by JLHwung** [comment]
> hexo-apollo主题启动的时候左下角出现/ally/accessiblity-menu.js

It a feature of MathJAX displaying various message on the left-bottom corner, see http://docs.mathjax.org/en/latest/options/hub.html and search for `messageStyle`.

If you would like to disable the message, here is a configuration example
```pug
script(type="text/x-mathjax-config").
    MathJax.Hub.Config({
        messageStyle: "none"
      });
script(async src="//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML" integrity="sha384-crwIf/BuaWM9rM65iM+dWFldgQ1Un8jWZMuh3puxb8TOY9+linwLoI7ZHZT+aekW" crossorigin="anonymous")
```

You can also check https://github.com/JLHwung/hexo-theme-apollo/commit/7cd1c5e60d6a04745e7f9cdb8b9fd6af9fde5036 for disabling MathJax messages.
