### ISSUE TITLE
3q

### ISSUE THREAD

**Issue by Lli123** [hexojs/hexo#2327]
$ hexo --debug
12:01:59.272 DEBUG Hexo version: 3.2.2
12:01:59.276 DEBUG Working directory: E:\li\blog\hexo\b\
12:01:59.562 DEBUG Config loaded: E:\li\blog\hexo\b\_config.yml
12:01:59.586 DEBUG Plugin loaded: hexo-deployer-git
12:01:59.595 DEBUG Plugin loaded: hexo-generator-archive
12:01:59.598 DEBUG Plugin loaded: hexo-generator-category
12:01:59.602 DEBUG Plugin loaded: hexo-generator-index
12:01:59.604 DEBUG Plugin loaded: hexo-generator-tag
12:01:59.611 DEBUG Plugin loaded: hexo-renderer-ejs
12:01:59.620 DEBUG Plugin loaded: hexo-renderer-marked
12:01:59.623 DEBUG Plugin loaded: hexo-renderer-stylus
12:01:59.751 DEBUG Plugin loaded: hexo-server
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  server    Start the server.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
12:01:59.763 DEBUG Database saved

**Comment by NoahDragon** [comment]
Could you please elaborate?
