### ISSUE TITLE
表格内的|（竖线）显示

### ISSUE THREAD

**Issue by z2x** [hexojs/hexo#2331]
在表格中添加竖线，我的文件在typora，sublime+markdownpreview的两种编译方式均正常，但在hexo中使用双斜线，&#124;都不能正常显示。

**Comment by NoahDragon** [comment]
能否贴出源文件呢？

**Comment by z2x** [comment]
下面是表格内容，问题在表格第三行第二列。

| 运算符            | 用法        | 描述                                       |
| -------------- | --------- | ---------------------------------------- |
| 按位与（ AND）      | `a & b`   | 对于每一个比特位，只有两个操作数相应的比特位都是1时，结果才为1，否则为0。   |
| 按位或（OR）        |  `a|b`    | 对于每一个比特位，当两个操作数相应的比特位至少有一个1时，结果为1，否则为0。  |
| 按位异或（XOR）      | `a ^ b`   | 对于每一个比特位，当两个操作数相应的比特位有且只有一个1时，结果为1，否则为0。 |
| 按位非（NOT）       | `~ a`     | 反转操作数的比特位，即0变成1，1变成0。                    |
| 左移（Left shift） | `a << b`  | 将 `a` 的二进制形式向左移 `b` (< 32) 比特位，右边用0填充。   |
| 有符号右移          | `a >> b`  | 将 a 的二进制表示向右移` b `(< 32) 位，保留符号位（即正负号标记）。 |
| 无符号右移          | `a >>> b` | 将 a 的二进制表示向右移` b `(< 32) 位，丢弃被移出的位，并使用 0 在左侧填充。 |

**Comment by NoahDragon** [comment]
可以使用`raw` tag
```

| 运算符            | 用法        | 描述                                       |
| -------------- | --------- | ---------------------------------------- |
| 按位与（ AND）      | `a & b`   | 对于每一个比特位，只有两个操作数相应的比特位都是1时，结果才为1，否则为0。   |
| 按位或（OR）        |  `{%raw%}a|b{%endraw%}`    | 对于每一个比特位，当两个操作数相应的比特位至少有一个1时，结果为1，否则为0。  |
| 按位异或（XOR）      | `a ^ b`   | 对于每一个比特位，当两个操作数相应的比特位有且只有一个1时，结果为1，否则为0。 |
| 按位非（NOT）       | `~ a`     | 反转操作数的比特位，即0变成1，1变成0。                    |
| 左移（Left shift） | `a << b`  | 将 `a` 的二进制形式向左移 `b` (< 32) 比特位，右边用0填充。   |
| 有符号右移          | `a >> b`  | 将 a 的二进制表示向右移` b `(< 32) 位，保留符号位（即正负号标记）。 |
| 无符号右移          | `a >>> b` | 将 a 的二进制表示向右移` b `(< 32) 位，丢弃被移出的位，并使用 0 在左侧填充。 |
```

**Comment by z2x** [comment]
问题解决了，谢谢。

**Comment by NoahDragon** [comment]
https://github.com/gitlabhq/gitlabhq/issues/1238

用`&#124;`代替`|`也可以。
