### ISSUE TITLE
安装出现错误

### ISSUE THREAD

**Issue by guozhenqiang** [hexojs/hexo#2332]
> before you submit your issue, please delete all the example code in template

在Ubantu中安装完git和node后，安装hexo出现图中的错误。
![hexo](https://cloud.githubusercontent.com/assets/9622421/21478843/82981faa-cb8a-11e6-8d0b-393e77311db7.png)
![Uploading hexo.png…]()

怎么解决啊！

**Comment by NoahDragon** [comment]
似乎是权限问题。加`sudo`试下。

**Comment by guozhenqiang** [comment]
不行啊，我在超级用户下操作的 ，加了sudo还是提示上图中的错误。

**Comment by NoahDragon** [comment]
其实Hexo以及npm的使用不需要root权限的。而且权限问题很难找出原因，因为他人无法重现。最根本的解决办法就是连Nodejs都删了，完全重装一遍。

**Comment by CoderMudy** [comment]
我也是遇到了这个问题，然后我又换了一个电脑，也是同样的问题，怎么解决呢？node 版本v7.3.0
npm版本3.10.10

**Comment by Tomoya-Hoo** [comment]
Try: sudo apt-get install nodejs-legacy 
然后再安装hexo

**Comment by mindthink** [comment]
应该是npm配置的问题，我按照官网解决方法解决了。[fnpm](https://docs.npmjs.com/getting-started/fixing-npm-permissions)
