### ISSUE TITLE
表格如何设置不均分？

### ISSUE THREAD

**Issue by madordie** [hexojs/hexo#2336]
现在我使用的是 `|`这样的语法做了一个表，之后发现其均分超级丑。。

想请教大大有没有参数设置列的宽度？

**Comment by madordie** [comment]
是的，我查了查貌似并不能直接使用markdown的语法用|<---->|---->这样的语法去布局，只能使用html的标签？

**Comment by NoahDragon** [comment]
有可能，Hexo用的是Marked作为Markdown渲染引擎，如果它们不支持，也只能用Html标记来解决了。
https://github.com/chjj/marked

**Comment by madordie** [comment]
@NoahDragon OK , 3Q 👍
