### ISSUE TITLE
安装出错... 连加了#的注释都报错

### ISSUE THREAD

**Issue by Ciefdx** [hexojs/hexo#2337]
![1](https://cloud.githubusercontent.com/assets/24788408/21575360/a3479d9e-cf44-11e6-83d6-07e694ff428a.jpg)

node -v 6.9.2
Windows7 x64
hexo-v也报如图的错误
重装来重装去 不明白配置里报这样的错误是什么鬼
现在怒气值是满的

**Comment by Ciefdx** [comment]
![zhushi](https://cloud.githubusercontent.com/assets/24788408/21575372/2ee843b2-cf45-11e6-9562-625f6e6f388f.jpg)
看了下问题解答,冒号加了引号不报错了  但是这个注释报错是wtf

**Comment by NoahDragon** [comment]
应该是Yaml解析出错，有时候一个空格的区别就会造成yaml无法识别。

**Comment by Ciefdx** [comment]
@NoahDragon 我已经解决了...
在注释的上一行,冒号后面加个空格就可以..
Yaml是个奇妙的东西

**Comment by NoahDragon** [comment]
可能以后Hexo应该检测_config.yaml格式后再运行，至少用户友好的提示。
