### ISSUE TITLE
ES6 renderer

### ISSUE THREAD

**Issue by jhia** [hexojs/hexo#2338]
Is there a way instead of using Webpack to transpile _ES6_ to _ES5_? I think using Babel and Hexo module, npm scripts and also task runners.
But the point is, what about a renderer with fully support for Babel?
I know there is [hexo-renderer-babel](https://github.com/townewgokgok/hexo-renderer-babel) which is great ❤️ , but is not very robust with some things like async/await, and adding polyfills is another thing too.
Thx Hexo!

**Comment by NoahDragon** [comment]
[hexo-renderer-babel](https://github.com/townewgokgok/hexo-renderer-babel)  is using Babel 4.7(now 6.0+), I think at that point it does not support async/await syntax. You could modify the line in its package.json https://github.com/townewgokgok/hexo-renderer-babel/blob/master/package.json#L24 to `"babel": "^6.0.0"`, which will use the latest babel and support all babel features.

**Comment by jhia** [comment]
@NoahDragon Thank you 😄👍

**Comment by NoahDragon** [comment]
Glad to help you. Please feel free to reopen it if the issue remains.
