### ISSUE TITLE
请问有没有添加类似 livereload 功能的计划呢？

### ISSUE THREAD

**Issue by HaloWang** [hexojs/hexo#2341]
比如 [gulp-livereload](https://www.npmjs.com/package/gulp-livereload)，监听 `MY_HEXO_PATH/source/_posts/*.md` ，如有变更，刷新界面

**Comment by NoahDragon** [comment]
可以使用 `hexo d --watch` https://hexo.io/docs/commands.html#generate

**Comment by HaloWang** [comment]
Thanks
