### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yyz20002008** [hexojs/hexo#2342]
I haven't updated hexo since july, 2016.
Today when I want to update blog, I found  git doesn't recognize hexo command.
So I was trying to re-install hexo.
But got errores below:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 

![error-1](https://cloud.githubusercontent.com/assets/1105915/21666009/1e971bfc-d2bd-11e6-85f2-be22bc6da42f.png)

And I have used MSI to install Node.js, nothing change better.

Does anyone can give some ideas?

**Comment by NoahDragon** [comment]
What do you mean "git doesn't recogize Hexo command"? Which Hexo command you used?

The warning is okay, you could just ignore it.

**Comment by yyz20002008** [comment]
Hexo g or hexo d

**Comment by NoahDragon** [comment]
`hexo g` is generating the site files, which doesn't call `git` command. However, if you set deployer using git, then `hexo d` will use `git` command to deploy the site.

**Comment by yyz20002008** [comment]
yes, I know. To deploy, we should hexo g and hexo d then. If we see ""git doesn't recognize hexo command", I can not do any hexo action to deply my websites. Originally hexo worked to deploy my websites, but I don't know why it doesn't right now. Perhaps I wrongly delete something? How can I recover? I thought I should run NPM again, but NPM doesn't work as well. That's why I come to ask help. Because I have modified config (Changing Theme, adding posts), I want to know how can I re-install with no impacting about my current post or config setting about my website? Thank you

**Comment by yyz20002008** [comment]
Screenshoe has been updated, anyone know what's wrong?

**Comment by NoahDragon** [comment]
Have you run `npm install` or `hexo init`?
