### ISSUE TITLE
如何进行小版本更新？

### ISSUE THREAD

**Issue by AlynxZhou** [hexojs/hexo#2344]
比如我用的是3.2.0，想更新到3.2.2，不是重新部署，是在当前基础上更新到新版本，或者有些hexo的依赖更新了，该用什么命令去更新呢？查找了文档似乎并没有这方面的资料。

## Environment Info

Node version(`node -v`)
```
v4.4.6
```

**Comment by NoahDragon** [comment]
应该直接运行`npm update`即可，可用`hexo -v`查看版本号。
