### ISSUE TITLE
如何解决hexo主题的图床、google字体、CDN等影响网页加载速度特慢的问题

### ISSUE THREAD

**Issue by jasoncheng911** [hexojs/hexo#2345]

**Comment by NoahDragon** [comment]
关于网站的加载速度，影响因素比较多，首先要看地域，请问是在什么地方加载网页比较慢呢？其次域名解析DNS，网站的域名是正确的解析。再次，网站所在服务器的访问速度。最后才是网页的加载速度。

**Comment by jasoncheng911** [comment]
@NoahDragon 地域？湖北宜昌。需要说明的是：我用的是TKL主题，我用hexo默认主题和其他主题都很快。TKL主题首页加载，和点击每篇文章跳转的时候都很慢。起先我以为是我用https://...github.io域名解析的慢，于是我就重新CNAME了一个万网的域名(我的博客地址 yuancheng91.top )，但还是慢，我在github上进TKL主题楼主的demo特别快(TKL主题的demo地址  http://go.kieran.top/)，但我在他的issues中提问一直都不回复，我很苦恼所以就来这里问了，网上有很多方法说是google字体导致网页加载慢，可我的TKL主题的字体本身就是useso的，而且我用chrome的网页检查工具，发现pending的链接都是http://fonts.useso.com/css......偶然还有几个cdn...啥的，这些后面都显示加载了30秒左右。

**Comment by NoahDragon** [comment]
我尝试了下，确实速度很慢。建议到[主题Repo](https://github.com/SuperKieran/TKL)去发issue，Hexo对于加载速度也是无能为力。

![image](https://cloud.githubusercontent.com/assets/5704064/21645725/4ba63dd2-d261-11e6-9b0c-9b66bfafcd09.png)
