### ISSUE TITLE
Hexo setup: fine with hexo server, generated static files are missing layout

### ISSUE THREAD

**Issue by velvetyxoxo** [hexojs/hexo#2349]
`hexo server` displays the default landscape theme correctly at `http://localhost:4000`. `hexo generate` runs without errors. However, the resulting static files look like this:

https://velvetyxoxo.github.io/dp9/

Nothing has been changed in the `_config.yml` except what was needed for deployment. Any ideas what I am missing?

**Comment by NoahDragon** [comment]
The blog root url is https://velvetyxoxo.github.io/dp9/ , but the style sheet is from https://velvetyxoxo.github.io/css/ , which root url is https://velvetyxoxo.github.io/ .  You could modify it in the _config.yml. https://hexo.io/docs/configuration.html#URL

**Comment by velvetyxoxo** [comment]
Thanks, that's it!
