### ISSUE TITLE
博客园无法迁移到hexo3.2.2

### ISSUE THREAD

**Issue by Wensibob** [hexojs/hexo#2351]
官方的文档中并没有说明从博客园迁移到hexo的步骤，从[网上](https://www.npmjs.com/package/hexo-migrator-cnblogs)看到，有组织为何这个插件，但是在时间比较久了，现在hexo已经来到了3.2.2，所以使用这个插件的时候无效<br>
```
undefined migrator plugin is not installed.
Installed migrator plugins:
For more help, you can check the online docs: http://hexo.io/
```
不知道还有没有人怎么知道如何从博客园迁移到hexo，难道需要一篇一篇敲吗😭

**Comment by NoahDragon** [comment]
目前似乎是没有相应的插件。
