### ISSUE TITLE
new post error.

### ISSUE THREAD

**Issue by shizhongyu** [hexojs/hexo#2353]
![_20170112122145](https://cloud.githubusercontent.com/assets/13025541/21876879/d2b9141e-d8c1-11e6-86aa-17f6aa7076b7.png)

**Comment by NoahDragon** [comment]
It's an error from config file. Could you please paste the _config.yml?

**Comment by shizhongyu** [comment]
![_20170113102911](https://cloud.githubusercontent.com/assets/13025541/21916379/28e2a7ce-d97b-11e6-80ba-b965f31bf040.png)

**Comment by NoahDragon** [comment]
There is something wrong with your repo line, but I couldn't tell what's wrong based on the image.

**Comment by cbronson** [comment]
@shizhongyu Have you tried the HTTP URL rather than SSH?

**Comment by shizhongyu** [comment]
@cbronson @NoahDragon  谢谢你们， 整好了。

**Comment by NoahDragon** [comment]
Glad you figure it out! 👍
