### ISSUE TITLE
Custom helper function in template

### ISSUE THREAD

**Issue by Mevrael** [hexojs/hexo#2357]
Hi, I am using hexo with swig.

How can I define a custom helpers so I could call them from swig?

**Comment by Mevrael** [comment]
Ok, found it in src, strange that such core simple function is not documented

Create `scripts/index.js` and:

```javascript
hexo.extend.helper.register('name', function() {
  return '';
});
```

and name() is now available from HTML template.

However, callback does not receive any data. How can I access `site.data` for example?

**Comment by NoahDragon** [comment]
Here is document about helper: https://hexo.io/api/helper.html

What kind of data would you like to access?

You could pass in the info you would like to process to the helper:
```
<%- name('user name') %>
```
