### ISSUE TITLE
Can i create a new layout ?

### ISSUE THREAD

**Issue by Khangeldy** [hexojs/hexo#2359]
Can i create new layout. New portfolio layout. Example `hexo new portfolio project`. IF it possible then how?

**Comment by NoahDragon** [comment]
Definitely, you could get more info from https://hexo.io/docs/templates.html#Layouts

**Comment by Khangeldy** [comment]
@NoahDragon I mean save both posts and portfolio items. Not replacing blog with portfolio.

**Comment by NoahDragon** [comment]
Yes, hexo by default has two layout: post and page.

You could add your own layout file under the scaffolds folder, let's say the portfolio. Then when you run `hexo new portfolio something`, hexo will create a page named "something" with the layout of portfolio. If you would like to create a post, using the `hexo new post somepost` works as usual.
