### ISSUE TITLE
Split markdown files? 

### ISSUE THREAD

**Issue by mrttl** [hexojs/hexo#2360]
Hello,
I am redoing my site in Hexo, its a design magazine, so heavy on images and content. I never liked markdown as I find it very limiting when it comes to styling. Is there a way in Hexo to split or include content into the post.ejs template?

I like the idea of front matter variables as I can style them in the template and place them where I like, but since the` <%- page.content %>` tag includes the long markdown file from the _page folder, it gives me little design possibilities.

So, can Hexo include paragraphs of text some how that can be placed where I like in my post.ejs template?

I found a similar design to show what am trying to do...

![b2957f4dcf5b836b81980aa0a0512339](https://cloud.githubusercontent.com/assets/24640131/21999826/43735cd2-dc3c-11e6-92a7-c197f12de121.jpg)

I hope I made sense and thanks in advance for any help.

**Comment by NoahDragon** [comment]
It is possible to do it via the layouts. https://hexo.io/docs/templates.html#Layouts

**Comment by mrttl** [comment]
Thank you @NoahDragon , But helpers are more for little bits of code and not long paragraphs of content? I am still new to Hexo, but I was wondering if I could somehow have a "custom field" for a certain area of my post template? Say a lot of HTML... Know what I mean?

**Comment by NoahDragon** [comment]
I see, have you thought about to put them all in the front matters?

Like:

```
---
Title:
Article:
    - "Product 1":
        - "Product 1"
        - "Image 1"
---
```

Actually,  the [theme page](https://github.com/hexojs/site/blob/master/source/plugins/index.md) I stated above is built upon a [yaml file](https://github.com/hexojs/site/blob/master/source/_data/themes.yml) which placed in `_data` folder.  Hope this could give you some inspiration.

**Comment by mrttl** [comment]
Ahh thank you! Front matter is what I was looking for! Thanks a million @NoahDragon
