### ISSUE TITLE
how to run `hexo s` with pm2?

### ISSUE THREAD

**Issue by bi-kai** [hexojs/hexo#2362]
Does hexo work with pm2?
how to run `hexo s` with pm2?

**Comment by NoahDragon** [comment]
Have you tried `pm2 start hexo -- s`?

**Comment by bi-kai** [comment]
pm2 start hexo -- s
[PM2] Starting D:\NODE\ANZHUANG\NODE_GLOBAL\HEXO.CMD in fork_mode (1 instance)
[PM2] Done.
[PM2][ERROR] script not found : D:\node\www\hexo_pro\s
script not found : D:\node\www\hexo_pro\s

还是不行啊！

**Comment by bi-kai** [comment]
@NoahDragon does it need another startup js or shell?

**Comment by NoahDragon** [comment]
I tried the same command, works fine on my machine.

**Comment by bi-kai** [comment]
@NoahDragon It works in linux, but not in windows.

**Comment by NoahDragon** [comment]
@bi-kai You are right. I just tested, it occurs on Win10 Chrome.

**Comment by alipiry** [comment]
If you try $ pm2 start hexo -- server 
it'll work.

**Comment by alipiry** [comment]
Try `pm2 start hexo -- start`.
It'll work.

**Comment by scue** [comment]
This is my solution:

Edit `package.json` file, add scripts configs:

```json
  "scripts": {
    "start": "pm2 start --name blog hexo -- s",
    "stop": "pm2 stop blog",
    "delete": "pm2 delete blog",
    "status": "pm2 status blog",
    "restart": "pm2 restart blog"
  },
```

and you can run `yarn start` to start your hexo blog, and `yarn stop` to stop it, and the same to `yarn restart`, `yarn delete` and `yarn status`. Enjoy! ;-)
