### ISSUE TITLE
about 关于页面 markdown 渲染问题

### ISSUE THREAD

**Issue by BZbyr** [hexojs/hexo#2364]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v5.7.0
```

Your site `_config.yml`
```
# Hexo Configuration
...
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.1.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug

## For question

about页面 markdown 页面 - 没有解析成黑点

还有就是在首页怎么才能显示文章只显示几行

## For feature request

just push feature request

**Comment by NoahDragon** [comment]
只显示文章简介可以使用`<!--more-->`加在markdown文章中。
能否贴下about markdown的文件呢？

**Comment by BZbyr** [comment]
啊 这是两个问题，

问题一： 在about页面 markdown 中的 - 解析不出黑点 

问题二：文章简介每次只显示300字 不用自己手动去加了 需要怎么去修改

**Comment by Rekols** [comment]
Please us english.
