### ISSUE TITLE
请问Hexo是否只能本地生成静态页面,部署静态文件到GithubPages

### ISSUE THREAD

**Issue by chinleo** [hexojs/hexo#2365]
Github支持Jekyll直接部署源代码的,不过Jekyll基于Ruby,在windows平台not easy,同时本人更熟悉一些Node.js所以看到Hexo时感觉很棒.
所以想问下当前版本是不是不可以直接部署源代码到GithubPages?并且想询问下是否可以实现兼容Jekyll的功能?
I'm a newbie.Thx.

**Comment by NoahDragon** [comment]
可以使用https://github.com/hexojs/hexo-deployer-git 来直接deploy到所有的gitish repoes。

**Comment by chinleo** [comment]
@NoahDragon 我想我没有描述清楚我的问题.是这样的:Hexo部署完成之后,Github是根据repo中的源代码生成站点页面的,还是Hexo部署之前已经将页面生成了然后发送到repo的?我看了一些基于Hexo的Page,其repo中文件是生成之后的静态页面.
Thx.

**Comment by NoahDragon** [comment]
是Hexo生成后Push到Github Repo的。Hexo不是Github原生的静态网页生成器，所以无法像Jekyll般由github生成。
