### ISSUE TITLE
How to replace the hexo domain name with a new one?

### ISSUE THREAD

**Issue by kintsuicris** [hexojs/hexo#2366]
Because my current domain name of the hexo blog will be expired soon, I want to replace it with another domain name I have purchased before.

However, though I tried to change the domain name in config file and deployed hexo, it didn't work.

Could you tell me how the replace the old domain?

Thank you!

**Comment by NoahDragon** [comment]
Have you tried `hexo clean && hexo g`? Probably it has been cached.

**Comment by kintsuicris** [comment]
Hi @NoahDragon , I tried, but still cannot make it. 
Actually, I just change the domain name in the _config.yml file, is that enough or what should I need to do?
When I go to my new domain name, it shows:
> Forbidden
> You don't have permission to access / on this server.
> Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by NoahDragon** [comment]
From Hexo side, to switch a domain, you only need to modify the config file.

Could you please check if your DNS set properly?
