### ISSUE TITLE
mathjax 公式渲染问题

### ISSUE THREAD

**Issue by jeffkzhao** [hexojs/hexo#2367]
一般的公式渲染都没有问题，可是对于下面这个公式：
`$$\left( \boldsymbol{A}^\mathrm{T} \right)_{i, j} = \boldsymbol{A}_{j,i}$$`
就无法渲染，直接显示为：`$$\left( \boldsymbol{A}^\mathrm{T} \right){i, j} = \boldsymbol{A}{j,i}$$`

仔细观察发现下划线都被自动去掉，那么肯定无法渲染显示。如果我将公式中最后一部份`_{j,i}`替换为`_i`就能正常渲染，经过测试只要最后加上一对`{}`就会出现同样的问题。
这种错误在采用多个themes(jacman,landscape-plus,next)均会出现，并且情况是一致的。
上述公式可以在自建页面引用mathjax库可以正常渲染显示，在mathjax.org官网demo在线展示也可正常显示。

**Comment by NoahDragon** [comment]
将MathJax代码放在<% raw %><% endraw %>之间。

**Comment by jeffkzhao** [comment]
谢谢@NoahDragon. issue`Bug:marked 和 Mathjax冲突 #524`提到了详细的解决方法，请参考该issue。

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo/issues/524 Reference the issue here.
