### ISSUE TITLE
Change date format in Hexo?

### ISSUE THREAD

**Issue by mrttl** [hexojs/hexo#2368]
Is there another way of displaying when an article was published? So not **12-06-2016** but rather **Yesterday** or **5 months ago**. I was looking the [http://momentjs.com/](url) site but not sure how to implement the **Relative Time** option.

Thank you.

**Comment by NoahDragon** [comment]
You could use the `moment` helper: https://hexo.io/docs/helpers.html#moment

**Comment by mrttl** [comment]
Perfect! Thank you...
