### ISSUE TITLE
hexo 命令报错

### ISSUE THREAD

**Issue by foreverwang** [hexojs/hexo#2372]
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
这么多人有这个问题 作者解决一下呗 神烦

**Comment by NoahDragon** [comment]
这个是npm安装的问题，把node_modules文件夹删掉，然后重新`npm install`试下。

**Comment by foreverwang** [comment]
3Q
