### ISSUE TITLE
How to process single YAML file into specific output directory?

### ISSUE THREAD

**Issue by copygirl** [hexojs/hexo#2373]
I currently have a file `source/_data/donations.yaml`, and would like to make changes to said file whenever I see a donation coming through, regenerate the site, and have it output into `public/donate/donations.js`. I'm not sure whether this is anywhere close to the intended way of doing things, as API documentation is very sparse - it doesn't even mention models at all! I've been fiddling around with Hexo's processors and models but can't make sense of them (or should I make a renderer instead?). Any help or pointers in the right direction would be appreciated.

**Comment by NoahDragon** [comment]
I feel Hexo is not the best approach for this situation. Hexo is mainly for static content. For your situation, I would recommend to using some CMS, like WordPress.

**Comment by copygirl** [comment]
Now, with some time to clear up my head, I suppose since the donation handling code is on the Express server side of things, I could simply add a route to serve the donation data from that end instead of Hexo's. I guess Hexo is going to stay this mysterious black box for me, then.

**Comment by copygirl** [comment]
Now, with some time to clear up my head, I suppose since the donation handling code is on the Express server side of things, I could simply add a route to serve the donation data from that end instead of Hexo's. I guess Hexo is going to stay this mysterious black box for me, then.
