### ISSUE TITLE
ftpsync的方式部署到云服务器报错

### ISSUE THREAD

**Issue by liangqiseu** [hexojs/hexo#2374]
$ hexo g -d
INFO  Start processing
INFO  Files loaded in 436 ms
INFO  0 files generated in 679 ms
INFO  Deploying: ftpsync
Setup
Setup complete.

Collecting
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 123.207.127.178:21
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

我希望用ftpsync的方式部署到我自己的云服务器，报了以上错误，我查阅了一些资料，似乎是服务器的ftp拒绝了。
1. 部署的时候没有其他ftp工具连入服务器；
2. 服务器端用的是apache， 之前手动ftp上传过public里的内容，当前我已经能正常访问我的网页；
3. /var/www/html/的权限是777；
4. 我在服务器上也安装了nodejs；
4. 我的配置如下：
deploy:
  type: ftpsync
  host: 123.207.127.178
  user: ubuntu
  pass: ******
  remote: /var/www/html/
  port: 21
  ignore:
  connections: 1
  verbose: false

**Comment by NoahDragon** [comment]
能否设置`verbose: true`，然后贴下输出呢？

**Comment by liangqiseu** [comment]
以下设置verbose: true后的完整打印：
$ hexo g -d
INFO  Start processing
INFO  Files loaded in 334 ms
INFO  Generated: index.html
INFO  1 files generated in 325 ms
INFO  Deploying: ftpsync
Setup
-------------------------------------------------------------
Settings:
{ local: 'D:\\blog\\public\\',
  host: '123.207.127.178',
  port: 21,
  remote: '/var/www/html/',
  user: 'ubuntu',
  pass: '******',
  connections: 1,
  ignore: [] }

Setup complete.

Collecting
-------------------------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 123.207.127.178:21
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

我怀疑是腾讯云禁止使用ftp上传文件。

**Comment by NoahDragon** [comment]
我认为腾讯云应该可以开ftp。不知是否解决了呢？

**Comment by SUPERPANDA-ORANGE** [comment]
请问这个问题解决了吗,我在部署的时候也遇到了相同的问题,感觉无从下手

**Comment by YangLin1998** [comment]
+1

**Comment by huqifeng** [comment]
+1
