### ISSUE TITLE
How to do text replace with a filter?

### ISSUE THREAD

**Issue by lucnap** [hexojs/hexo#2377]
This code does not work. It generate the static site but no text replace is done.
I execute this script with node myScript.js
Where is my error?

```javascript
var Hexo = require('hexo');
var hexo = new Hexo(process.cwd(), {});

hexo.init().then(function () {

    hexo.extend.filter.register('after_post_render', function(data){
      data.content = data.content.replace(/@(\d+)/, '<a href="http://twitter.com/$1">#$1</a>');
      return data;
    });

    hexo.call('generate', {}).then(function(){
        return hexo.exit();
    }).catch(function(err){
        return hexo.exit(err);
    });
});
```

**Comment by Talljoe** [comment]
I can't comment on the correctness of the code, but I have an feeling your regex is incorrect. `@(\d+)` will only match twitter handles composed entirely of numbers (e.g. `@3982`). I think you want `@(\w+)`.

**Comment by lucnap** [comment]
Yes Talljoe you are right and I changed the regex as you suggested but that was only part of the problem.
I discovered that if "hexo server" is running and you execute "generate", the "after_post_render" filter is executed and the content replace correctly works but the data.content with new data is ignored by hexo.

I think it is a clear bug.
