### ISSUE TITLE
Solar_Hijri_calendar

### ISSUE THREAD

**Issue by ghaseminya** [hexojs/hexo#2381]
Hi
Is it possible to change calendar to Solar_Hijri_calendar in blog and archive and for all sub pages and posts?
thanks

**Comment by NoahDragon** [comment]
Yes, it is possible. You could write a filter to do such conversion.

**Comment by ghaseminya** [comment]
Thanks for attention
With this link http://momentjs.com/docs/#/plugins/jalaali/
I install moment-jalaali with :
`npm install moment-jalaali
`
and in hexo project folder
${ProjectFolder}/node_modules/hexo/lib/plugins/helper/date.js
i changed line
`var moment = require('moment-timeline');`
to
var moment = `require('moment-jalaali');`
in this file: 
and change date_format: jYYYY/jM/jD in _config.yml
but no change had affected?
Did these change true?

**Comment by NoahDragon** [comment]
You changed the helper, but I think you need the filter.  The helper only works in the layout files.

**Comment by ghaseminya** [comment]
https://github.com/ppoffice/hexo-theme-icarus/issues/237

**Comment by NoahDragon** [comment]
Glad it solved! Thanks for sharing.
