### ISSUE TITLE
Remove archives route

### ISSUE THREAD

**Issue by joinjoohny** [hexojs/hexo#2382]
How can I remove `/archives` route ?

**Comment by NoahDragon** [comment]
What do you mean to remove it? Could you please elaborate?

**Comment by joinjoohny** [comment]
I want to this page has not been in my site  `/archives` , but by default it is.
I can do redirect of this page, it is a bad solution.
Thx!

**Comment by niahoo** [comment]
You can add a value in the front matter :

```
----
title: "aaa a a a a "
hidden: true
----
```

And in your archive template, filter the posts : 

````ejs
<% page.posts.each(function(post){ %>
  <% if(post.indexhide && (typeof showhide == 'undefined' || !showhide )) {
    // the page is hidden
  } else {%>
    <%- partial('article', {post: post, index: true}) %>
  <% } %>
<% }) %>
```
