### ISSUE TITLE
Prevent a page to be published

### ISSUE THREAD

**Issue by niahoo** [hexojs/hexo#2383]
Hi !

I would like to use page content in my archive page, on top of the posts lists.

This is what I do, I include a post content. I like it because I can write my content in markdown or asciidoc.

```ejs
<% if (typeof archive_text_id !== 'undefined'){
  var query_text_content = site.pages.find({id: archive_text_id})
  if (query_text_content.length) { %>
    <%- query_text_content.data[0].content %>
  <% }
} %>
```

But I would like the page not to be accessible by itself. How can I set a page not to be generated ?

Thanks !

**Comment by NoahDragon** [comment]
I think you could put the page under a `_data` folder. Like: 
https://github.com/hexojs/site/tree/master/source/_data
