### ISSUE TITLE
Change Permalinks to Jalaali calendar instead Georgian calendar

### ISSUE THREAD

**Issue by ghaseminya** [hexojs/hexo#2385]
Hi
Is it possible to change post address from Georgian year and month to Jalaali year and month?
localhost:4000/2017/01/31/
to
localhost:4000/1395/11/12/
 I use moment-jalaali with this installation command in root of hexo blog 
`npm install moment-jalaali`
in my forked theme [hexo-theme-icarus_rtl_jalaali](https://github.com/ghaseminya/hexo-theme-icarus_rtl_jalaali).
now how can i change permalinks?

**Comment by NoahDragon** [comment]
You could add your own permalink filter to replace the default. 
https://hexo.io/api/filter.html#post-permalink
https://github.com/hexojs/hexo/blob/5234c4a85dc6cd418e9a1c169e43de169cf98e95/lib/plugins/filter/post_permalink.js

**Comment by ghaseminya** [comment]
Yes, It is work.
Some changes needed in post_permalink.js
Is it good to create new pull with this capability or fork it and change?

**Comment by NoahDragon** [comment]
I would recommend creating the filter as a plugin, instead of modifying the default Hexo logic.

Some filter plugin examples:
https://github.com/xcatliu/hexo-filter-date-from-git
https://github.com/zhenyong/hexo-filter-file-link
https://github.com/bubkoo/hexo-filter-sequence

**Comment by ghaseminya** [comment]
Great ok, I create a plugin with a short tutorial...
A problem occurred!!! all things is good about changing permalinks, but in Archive links it not work truely and when i call http://localhost:4000/archive/1395/11/
I get this message:
Cannot GET /archive/1395/11/
but in topic permalinks work fine:
http://localhost:4000/1395/11/12/opensource/
work fine.
I search all js in lib/plugins/filter/post but couldn't found solution.

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo-generator-archive/blob/master/lib/generator.js#L42

In the archive generator, the date is from post, so if the date in the post is set to Jalaali calendar correctly, it should work as well.

**Comment by ghaseminya** [comment]
Yes..
Your sentence is true but not work until some other change!!!
I changed
https://github.com/hexojs/hexo-generator-archive/blob/master/lib/generator.js#L42
https://github.com/hexojs/hexo-generator-archive/blob/master/lib/generator.js#L43
to this:
   ```
 var year = moment(date).format('jYYYY');
    var month = moment(date).format('jM'); 
```
At this time its work fine.
Now how can i create new filter plugin?This new plugin need some change in hexo-generator-archive, in fact for apply jalaali calendar in Hexo we need some change in Hexo and some change in hexo-generator-archive.
