### ISSUE TITLE
在64位WIN7系统下安装HEXO出现错误

### ISSUE THREAD

**Issue by yusmile** [hexojs/hexo#2387]
我是在64位WIN7系统下安装的：
1.安装Git
到[官网]https://git-scm.com/download/win)下载 Git，一路默认选项安装。使用的是Git-2.11.0.3-64-bit
2.安装Node.js
到官网下载 Node.js，保持默认设置即可，一路Next。使用的是node-v6.2.0-x64
3.安装Hexo
Git 和 Node.js 都安装好后,首先创建一个用于存放博客文件的文件夹(比如取名 hexo），然后进入 hexo 文件夹，下面开始安装并使用 Hexo。右键选择Git Bash Here，弹出Git Bash窗口；执行命令：
npm install hexo-cli -g
**出现两个错误**
npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
![](http://upload-images.jianshu.io/upload_images/4542536-6145c6bd23de90dd.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
**这是怎么回事呢？有没前辈能帮忙看下？**

**Comment by yusmile** [comment]
@NoahDragon 我试过sudo npm install hexo-cli -g?
输入命令后，出现提示
>bash: sudo: command not found

**Comment by DexHunter** [comment]
我查了一下，fsevent應該跟windows安裝沒什麽關係，這是mac-os的，[source](https://www.npmjs.com/package/fsevents),而且也衹是報warn,不是fatal的話就可以繼續安裝

**Comment by NoahDragon** [comment]
这两个只是警告，并非错误，试下`hexo init`是否能正常运行？

**Comment by yusmile** [comment]
@DexHunter 难怪我一直找不到sudo的win文章，谢谢你的回复

**Comment by yusmile** [comment]
@DexHunter 难怪我一直找不到sudo的win文章，谢谢你的回复

**Comment by yusmile** [comment]
@NoahDragon 运行`hexo init`后，出现这样的提示![](http://upload-images.jianshu.io/upload_images/4542536-649bf148e7116548.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by yusmile** [comment]
再运行`npm install`， * ***这里还出现了两个错误提示，折腾了两天也还是暂时还无法解决：***
![](http://upload-images.jianshu.io/upload_images/4542536-da30a7f42a0130b8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by NoahDragon** [comment]
已经安装成功了，一切正常。

**Comment by yusmile** [comment]
@NoahDragon 谢谢
