### ISSUE TITLE
too much whitespace while inserting html table

### ISSUE THREAD

**Issue by KangbingZhao** [hexojs/hexo#2391]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v5.7.0
```

Your site `_config.yml`
```
default
```

Your theme `_config.yml`
```
defaul theme, default configuration
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 F:web\hexo_test
+-- hexo@3.2.2
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
`-- hexo-server@0.2.0
```

## For BUG

I edit my *.md file in sublime, while inserting table in a post like this:
```
---
title: test_post
date: 2017-02-02 16:48:31
tags:
---
test start
<table>
	<tr>
		<td>d1</td>
		<td>d2</td>
	</tr>
</table>
end!
``` 
I found that too much whitespace was produced before the table, just like this:
![image](https://cloud.githubusercontent.com/assets/4462766/22597897/77c014ec-ea6c-11e6-816c-cabfe8b9aed2.png)

If I edit my file like this:
```
---
title: test_post
date: 2017-02-02 16:48:31
tags:
---
test start
<table><tr><td>d1</td><td>d2</td></tr></table>
end!
```
the post is produced properly:
![image](https://cloud.githubusercontent.com/assets/4462766/22598051/10ab4f82-ea6d-11e6-8d5e-27d63c98d90f.png)

I don't konw it's hexo's bug or my own fault, and is there any way to keep the code easy to read and rendered properly?  <br>Thanks.

**Comment by NoahDragon** [comment]
It is a known marked.js issue. Please use markdown table structure instead of HTML tags.

**Comment by KangbingZhao** [comment]
Thanks

**Comment by MoiCoquille** [comment]
Try the following, it fixed the problem for me:

{% raw %}
html tags & content
{% endraw %}

**Comment by zhuimiao** [comment]
http://tool.oschina.net/jscompress?type=2
html table compressed into a row
it work for me
