### ISSUE TITLE
github pages的首页只能显示默认的hello word的内容

### ISSUE THREAD

**Issue by Simmon12** [hexojs/hexo#2392]
新写的文章无法显示到博客上，在_posts文件夹中也有新写文章的的md文件，但是在public里面就只有原来默认的hello word.html,在我的GitHub pages上也只是显示hello word 里的内容，为什么会这样？难道我的首页只能发一篇文章吗？

**Comment by NoahDragon** [comment]
Please reference to this issue https://github.com/hexojs/hexo/issues/2378
