### ISSUE TITLE
Category and About 404 Can't found

### ISSUE THREAD

**Issue by Simmon12** [hexojs/hexo#2396]
yilia 主题下我在 _config.yml 中设置的菜单有 Home,Archive,Category,About,可是只有Home和Archive点进去才有内容，Category和About都错Can't found

**Comment by ahonn** [comment]
并不是在 `_config.yml` 中设置就可以的，你需要确保站点根目录下的 `source/Category` 与 `source/About` 目录存在。

 你可以通过 `hexo new page xxxx` 自动生成。
