### ISSUE TITLE
/lib/plugins/helper/open_graph.js缺少对title字段的html特殊字符的转码处理

### ISSUE THREAD

**Issue by machao** [hexojs/hexo#2397]
/lib/plugins/helper/open_graph.js
如果title字段中包含 半角双引号，会导致输出的html代码语法错误：

title: this is "test" page title

生成：

<meta property="og:title" content="this is "test" page title">

**Comment by NoahDragon** [comment]
建议写成：`title: 'this is "test" page title'`

**Comment by machao** [comment]
单引号包裹不起作用。
文档：
title: 'Druid连接池"违反协议"异常的处理'
编译结果：
< meta property="og:title" content="Druid连接池"违反协议"异常的处理" >

类似的描述字段在输出meta信息的时候，就做了html字符替换。title字段为啥不处理？

**Comment by NoahDragon** [comment]
使用转义字符可以么？`	%22`
