### ISSUE TITLE
Blockquote tags can't handle names or sources with commas in them??

### ISSUE THREAD

**Issue by mvxt** [hexojs/hexo#2398]
## Environment Info
Node version(`node -v`)
```
[22:36:34] mikeyvxt:shrewdcitizen git:(master) $ node -v
v7.5.0
```
Your site `_config.yml`
```
# default
```
Your theme `_config.yml`
```
# Hipaper default
```

Plugin version(`npm ls --depth 0`)
```
[22:36:29] mikeyvxt:shrewdcitizen git:(master) $ npm ls --depth 0
hexo-site@0.0.0 /home/mikeyvxt/workspace/shrewdcitizen
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```

## For ISSUE
_**Summary**_
- Blockquotes get mangled if I try to cite a source that contains commas. Sources are cut off prematurely, probably because of delimitation by comma. See below examples.

_**Examples**_
_Source Code_
{% blockquote Abraham Lincoln, "Debate at Ottawa, Illinois (August 21, 1858)" %}
Public sentiment is everything. With public sentiment, nothing can fail; without it nothing can succeed. Consequently he who molds public sentiment, goes deeper than he who enacts statutes or pronounces decisions. He makes statutes and decisions possible or impossible to be executed.
{% endblockquote %}

_Output_
![screenshot from 2017-02-08 22-45-47](https://cloud.githubusercontent.com/assets/2441695/22770838/7fa3838c-ee50-11e6-860d-12854ad04e06.png)

_Source Code_
{% blockquote Mohandas Gandi, Interview with Charles Petrasch (Published in The Labour Monthly, Vol. 14, April 1932, №4 pp. 217–224) %}
My weapon is ‘non-co-operation.’ No one can thrive without the collaboration, willing or forced, of the people.
{% endblockquote %}

_Output_
![screenshot from 2017-02-08 22-46-03](https://cloud.githubusercontent.com/assets/2441695/22770860/b24e097e-ee50-11e6-86bb-559eaf6b2d6b.png)

_**Steps to Reproduce**_
Generate a blockquote, and add a source with commas in it. It looks like the Blockquote tag system is delimiting by commas.

**Comment by NoahDragon** [comment]
This definitely needs to improve. Currently, removing the comma is a temp solution.

**Comment by mvxt** [comment]
Okay, do you have a timeline of if/when it will be fixed? I'm not great with javascript, but if this is a simple and quick fix, you can just point me to the general area of code where blockquote tags are handled and I can fix it/make a pull request.

Thanks for your time

**Comment by seaoak** [comment]
I think this issue is caused by `hexo/lib/plugins/tag/blockquote.js:9`    
https://github.com/hexojs/hexo/blob/master/lib/plugins/tag/blockquote.js#L9

A regular expression `rAuthorTitle` allows a string as a title when the string does not contain any comma (or a substring before a comma).
https://github.com/hexojs/hexo/blob/master/lib/plugins/tag/blockquote.js#L41-L44

To fix quickly, modify `rAuthorTitle` as `/([^,]+),\s*(.+)/`

**Comment by mvxt** [comment]
Can confirm @seaoak's solution works locally on my blog. Thanks a lot!

![screenshot from 2017-02-16 21-21-08](https://cloud.githubusercontent.com/assets/2441695/23052353/da91e980-f48d-11e6-907e-5bdad56b6f5f.png)
