### ISSUE TITLE
为什么 hexo init <Folder>这步的时候卡住不执行了呢？

### ISSUE THREAD

**Issue by WithToken** [hexojs/hexo#2401]
## Environment Info

Node version(`node -v`)
```
v7.5.0
```

## For question

在执行hexo init <Folder>时候，卡在了
$ hexo init WJ-blog
INFO  Cloning hexo-starter to ~/WJ-blog
Cloning into '/Users/guowujiang/WJ-blog'...
remote: Counting objects: 53, done.
remote: Total 53 (delta 0), reused 0 (delta 0), pack-reused 53
Unpacking objects: 100% (53/53), done.
Submodule 'themes/landscape' (https://github.com/hexojs/hexo-theme-landscape.git) registered for path 'themes/landscape'
Cloning into '/Users/guowujiang/WJ-blog/themes/landscape'...
Submodule path 'themes/landscape': checked out 'decdc2d9956776cbe95420ae94bac87e22468d38'
INFO  Install dependencies
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
> dtrace-provider@0.8.0 install /Users/guowujiang/WJ-blog/node_modules/dtrace-provider
> node scripts/install.js
往下不执行了。该如何处理呢？

I'm a newbie.Thx.

**Comment by WithToken** [comment]
@NoahDragon

**Comment by NoahDragon** [comment]
在WJ-blog下运行`hexo init`，还会同样卡主么？

**Comment by WithToken** [comment]
解决了！万分感谢。

**Comment by NoahDragon** [comment]
👍

**Comment by My-oreos-are-only-for-me** [comment]
我的在本目录下hexo init还是会卡主怎么办，用Git bash也是一样会卡主，不能执行下去。

INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git

只有这一行，执行不下去了

**Comment by whiteS18** [comment]
和楼上一样，hexo init 文件夹 和 cd 文件夹  hexo init 都会卡再第一行。
我的配置：
D:\>node -v
v12.18.4

D:\>npm -v
6.14.8

D:\>hexo -v
hexo-cli: 4.2.0
os: Windows_NT 10.0.19041 win32 x64
node: 12.18.4
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.1.2
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0


卡在这里:
D:\blog>hexo init
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git

**Comment by My-oreos-are-only-for-me** [comment]
> 我的在本目录下hexo init还是会卡主怎么办，用Git bash也是一样会卡主，不能执行下去。
> 
> INFO克隆hexo-starter https://github.com/hexojs/hexo-starter.git
> 
> 只有这一行，执行不下去了

我好了，其实只是网络不好，改一下延时就好了，或者换一个网络。

**Comment by YaoGul** [comment]
我不管是用管理员模式还是cmd都是卡在下面就不动了
INFO Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
