### ISSUE TITLE
new theme

### ISSUE THREAD

**Issue by ghaseminya** [hexojs/hexo#2405]
Hi
How to add my new theme to https://hexo.io/themes/?
https://github.com/ghaseminya/hexo-theme-icarus_rtl_jalaali

Thanks.

**Comment by NoahDragon** [comment]
You could add your theme into the following file:
https://github.com/hexojs/site/blob/master/source/_data/themes.yml

**Comment by ghaseminya** [comment]
thanks,
I add it.

**Comment by ghaseminya** [comment]
create a pull request on it!

**Comment by ghaseminya** [comment]
https://hexo.io/themes/ 404 error

**Comment by NoahDragon** [comment]
I have noticed this error, and reverted your PR. Please create another PR with the screen snapshot.
