### ISSUE TITLE
updated值如何自动获取？

### ISSUE THREAD

**Issue by Cn-Rice** [hexojs/hexo#2408]
`Front-matter`中的预先定义参数中有**updated**这一参数，请问如何获取？

能否添加文章的**最后修改时间**？

[https://hexo.io/zh-cn/docs/front-matter.html](url)

**Comment by sabrinaluo** [comment]
`page.updated`
如果没有设置，默认为对应`.md`文件修改时间

**Comment by Mine-MuYan** [comment]
直接修改创建文件时自动生成的日期就行了。
![image](https://cloud.githubusercontent.com/assets/23254569/23012074/5c616fe6-f45f-11e6-8c9c-43a96c96240e.png)
