### ISSUE TITLE
手机中修改_config.yml文件后hexo g严重报错

### ISSUE THREAD

**Issue by xiaoqiang520** [hexojs/hexo#2409]
**我在ROOT后的手机上安装了，HEXO 后 `hexo g`     `hexo s`      都成功能正常访问本地了，只是我想换主题，用sudo权限编辑了 _config.yml  （此文件在data/data/com.termux/files/home 系统文件目录下）后，出来 `hexo g`  时出错了，在切换回去也不行，一直报这个错误，请看图**
![qq 20170216211055](https://cloud.githubusercontent.com/assets/24207016/23022554/6d76602a-f48c-11e6-9ecb-5e1bca0bb78b.jpg)

**Comment by NoahDragon** [comment]
权限问题，可以搜索nodejs permission denied。
