### ISSUE TITLE
WIN10全新安装报错。

### ISSUE THREAD

**Issue by 382572** [hexojs/hexo#2420]
win10 64位系统
Git-2.12.0-64-bit.exe
node-v7.6.0-x64.msi

C:\Users\rain_\AppData\Roaming\npm
`-- hexo-cli@1.0.2
  +-- abbrev@1.1.0
  +-- bluebird@3.4.7
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.1.1
  | +-- strip-ansi@3.0.1
  | `-- supports-color@2.0.0
  +-- hexo-fs@0.1.6
  | +-- chokidar@1.6.1
  | | +-- anymatch@1.3.0
  | | | +-- arrify@1.0.1
  | | | `-- micromatch@2.3.11
  | | |   +-- arr-diff@2.0.0
  | | |   | `-- arr-flatten@1.0.1
  | | |   +-- array-unique@0.2.1
  | | |   +-- braces@1.8.5
  | | |   | +-- expand-range@1.8.2
  | | |   | | `-- fill-range@2.2.3
  | | |   | |   +-- is-number@2.1.0
  | | |   | |   +-- isobject@2.1.0
  | | |   | |   +-- randomatic@1.1.6
  | | |   | |   `-- repeat-string@1.6.1
  | | |   | +-- preserve@0.2.0
  | | |   | `-- repeat-element@1.1.2
  | | |   +-- expand-brackets@0.1.5
  | | |   | `-- is-posix-bracket@0.1.1
  | | |   +-- extglob@0.3.2
  | | |   +-- filename-regex@2.0.0
  | | |   +-- kind-of@3.1.0
  | | |   | `-- is-buffer@1.1.4
  | | |   +-- normalize-path@2.0.1
  | | |   +-- object.omit@2.0.1
  | | |   | +-- for-own@0.1.5
  | | |   | | `-- for-in@1.0.1
  | | |   | `-- is-extendable@0.1.1
  | | |   +-- parse-glob@3.0.4
  | | |   | +-- glob-base@0.3.0
  | | |   | `-- is-dotfile@1.0.2
  | | |   `-- regex-cache@0.4.3
  | | |     +-- is-equal-shallow@0.1.3
  | | |     `-- is-primitive@2.0.0
  | | +-- async-each@1.0.1
  | | +-- glob-parent@2.0.0
  | | +-- inherits@2.0.3
  | | +-- is-binary-path@1.0.1
  | | | `-- binary-extensions@1.8.0
  | | +-- is-glob@2.0.1
  | | | `-- is-extglob@1.0.0
  | | +-- path-is-absolute@1.0.1
  | | `-- readdirp@2.1.0
  | |   +-- minimatch@3.0.3
  | |   | `-- brace-expansion@1.1.6
  | |   |   +-- balanced-match@0.4.2
  | |   |   `-- concat-map@0.0.1
  | |   +-- readable-stream@2.2.3
  | |   | +-- buffer-shims@1.0.0
  | |   | +-- core-util-is@1.0.2
  | |   | +-- isarray@1.0.0
  | |   | +-- process-nextick-args@1.0.7
  | |   | +-- string_decoder@0.10.31
  | |   | `-- util-deprecate@1.0.2
  | |   `-- set-immediate-shim@1.0.1
  | `-- graceful-fs@4.1.11
  +-- hexo-log@0.1.2
  | `-- bunyan@1.8.5
  |   +-- dtrace-provider@0.8.0
  |   | `-- nan@2.5.1
  |   +-- moment@2.17.1
  |   +-- mv@2.1.1
  |   | +-- mkdirp@0.5.1
  |   | | `-- minimist@0.0.8
  |   | +-- ncp@2.0.0
  |   | `-- rimraf@2.4.5
  |   |   `-- glob@6.0.4
  |   |     +-- inflight@1.0.6
  |   |     | `-- wrappy@1.0.2
  |   |     `-- once@1.4.0
  |   `-- safe-json-stringify@1.0.3
  +-- hexo-util@0.6.0
  | +-- camel-case@3.0.0
  | | +-- no-case@2.3.1
  | | | `-- lower-case@1.1.4
  | | `-- upper-case@1.1.3
  | +-- cross-spawn@4.0.2
  | | +-- lru-cache@4.0.2
  | | | +-- pseudomap@1.0.2
  | | | `-- yallist@2.0.0
  | | `-- which@1.2.12
  | |   `-- isexe@1.1.2
  | +-- highlight.js@9.9.0
  | +-- html-entities@1.2.0
  | `-- striptags@2.2.1
  +-- minimist@1.2.0
  +-- object-assign@4.1.1
  `-- tildify@1.2.0
    `-- os-homedir@1.0.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\he                                                          xo-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                          1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}

**Comment by NoahDragon** [comment]
没有报错，只是警告而已。
