### ISSUE TITLE
请问如何提交插件库

### ISSUE THREAD

**Issue by cometlj** [hexojs/hexo#2422]
请问如何向 https://hexo.io/plugins/ 提交写好的插件？还是官方会自动收集？谢谢

**Comment by jhabdas** [comment]
尝试询问StackOverflow

**Comment by cometlj** [comment]
@jhabdas thanks

**Comment by unnamed42** [comment]
fork 一份 https://github.com/hexojs/site
然后往 `source/_data/plugins.yml` 里面添加你自己的插件的信息，具体内容可以参照已有插件
然后发起 pull request

**Comment by cometlj** [comment]
@unnamed42 谢谢

**Comment by NoahDragon** [comment]
@unnamed42 的方法是正解
