### ISSUE TITLE
relative_link: true Menu not working

### ISSUE THREAD

**Issue by Mossfeldt** [hexojs/hexo#2424]
I have a strange problem with the links generated for "tags" and "archive" ... , they all point to / .
In my theme/_config.yml the menu items are all set like tags: /tags and so on,  the pages is created under sources/
Generation is ok, I can access the pages /tags /archives /categories by entering respective name in the adressbar of my browser. But all icons point to "" in the html code.

**Comment by NoahDragon** [comment]
I think this issue is related to your theme.
