### ISSUE TITLE
Dynamic routing (kinda)

### ISSUE THREAD

**Issue by AlmightyBaka** [hexojs/hexo#2425]
I was looking into using Hexo, but after reading all the docs I couldn't find anything on how to add dynamic routing, which I absolutely need. For example, let's say we have 2 pages, `post1` and `post2`. Is there any way to make an url of `post1/post2` return both post in one page, or is there no way to do that in Hexo?

**Comment by VarDking** [comment]
Hexo is not for Dynamic site.

**Comment by AlmightyBaka** [comment]
Well I guessed so :P Which sucks, because otherwise I like it a lot. Is there no way to expand it to make what I want or I'm better off starting from scratch?

**Comment by NoahDragon** [comment]
Sorry, Hexo is designed to generate the static website.
