### ISSUE TITLE
Ask a question about the hexo plugin？

### ISSUE THREAD

**Issue by XuanmiaoG** [hexojs/hexo#2429]
Ask a question about the hexo plugin

How to make a plug-in, in generate, in each page to add a JS script (multi line), I hope to give the code

**Comment by iamchathu** [comment]
Hi
I developed a Hexo tag plugin to embed Apster
But currently, it needs developers to add js script to head
Is there way to do it in plugin itself to embed the js in to head

**Comment by NoahDragon** [comment]
@iamchathu yes, you could consider using the helper, or embed the js directly to the theme.
