### ISSUE TITLE
修改 source_dir 后资源文件在 public_dir 中消失

### ISSUE THREAD

**Issue by raychow** [hexojs/hexo#2430]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v7.7.1
```

Your site `_config.yml`
```
# Hexo Configuration
source_dir: /source
...
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 /hexo
+-- hexo@3.2.2
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.0
+-- hexo-generator-sitemap@1.1.2
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
`-- hexo-server@0.2.0
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug

在 hexo/hexo/lib/theme/processors/source.js 的 exports.pattern 中，匹配的模式被写死成了 'source/'，导致如果 source_dir 不是 source/ 开头，就不会被此 processor 处理。

应将这里的 'source/' 改成 config.source_dir。

## For question

just push question

## For feature request

just push feature request

**Comment by stevenjoezhang** [comment]
其实并没有问题，这里的 `exports.pattern` 匹配的是主题目录下的 `source/`，例如 `hexo/themes/next/source`；而不是 Hexo 本身的 `source_dir`，例如 `hexo/source/`。
