### ISSUE TITLE
hexo deploy all my root files instead of public folder

### ISSUE THREAD

**Issue by jianghaifor** [hexojs/hexo#2433]
When I deployed my hexo to Github, it seems that I uploaded all my folders except "public"folders to Github,here is my repo:
https://github.com/jianghaifor/jianghaifor.github.io

**Comment by NoahDragon** [comment]
Looks like you have resolved it. :)

**Comment by jianghaifor** [comment]
thx~(๐•̆ ·̭ •̆๐)

**Comment by qzlinqian** [comment]
So how did you solve it? I'm facing the same problem. Thanks!
