### ISSUE TITLE
如何给文章添加封面

### ISSUE THREAD

**Issue by Meitimu** [hexojs/hexo#2442]
如题

**Comment by wuhuanhost** [comment]
自定义主题~

**Comment by ZhaoC** [comment]
可以下载 https://hexo.io/themes/ 推荐的主题，感觉都挺赞的。你可以下载到你的theme folder， 然后修改掉 '_config.yml' 里的 'theme: you_theme_name' . 这样创建文章的时候有预留处可以添加你的文章封面了。
