### ISSUE TITLE
Site search?

### ISSUE THREAD

**Issue by mrttl** [hexojs/hexo#2444]
Hello,

What is the best way to search using Hexo? I have a site with a lot of articles and wanted to add a site search. I know you can use Google search but is there an easy way of getting my own site search? I don´t need an ajax search or anything.

Thank you.

**Comment by snowluliang** [comment]
search in your blog?

**Comment by mrttl** [comment]
yes for my own search.

**Comment by snowluliang** [comment]
in your **theme** file,have the **__config_.xnl**  ,in this file have the  **local search** ,edit **true**

**Comment by mrttl** [comment]
And this will allow me to have site search so people can search for articles on my site? Thanks

**Comment by snowluliang** [comment]
you can try .my theme is **NexT**[see here](http://theme-next.iissnan.com/third-party-services.html)

**Comment by NoahDragon** [comment]
It could be supported by theme or plugin.

**Comment by mrttl** [comment]
Oh cool thank you Noah, do you know of any themes that support it?

**Comment by snowluliang** [comment]
[here](https://hexo.io/themes/)

**Comment by NoahDragon** [comment]
@mrttl you could try the https://github.com/PaicHyperionDev/hexo-generator-search
