### ISSUE TITLE
total beginner to Hexo/blogs

### ISSUE THREAD

**Issue by joha0033** [hexojs/hexo#2445]
Hey, I just downloaded atom as my text editor, and have a template generated from Hexo for a blog site. I'm trying to manipulate the sites content, but I'm not having any luck. 

I've tried to do some research and everything I've found is either over my head at this point, or not working. 

I have the program open, and my first piece I want to change is the "hexo" title on the logo anchor.

I'm not having any luck with editing it in any markdown, or index.html pages I've found. 

I CAN edit the "My first post". Am I approaching this wrong? Do I need to write my own index.html page or something??

**Comment by mrttl** [comment]
Hi joha0033 and welcome to Hexo. Firstly, all posts you write in Hexo sit in the _posts folder, if you want to create a new post you can create a new post with Atom (create new file) or via the command line `hexo new post xxxxx` xxxxx being the name of your post. Then to edit your temple, you would need to open up the layouts folder and then you would see the templates you need to edit.

To be honest, the default theme that comes installed with Hexo is complex for someone new to Hexo, if you use EJS take a look at this minimal theme, it has the bare basics to start with: https://github.com/nadymain/hexo-theme-nadymain/tree/master/layout and if you use Jade (pug) the port is also available: https://github.com/nadymain/hexo-theme-nadymainjade

Just remember that template files like EJS or Jade get compiled HTML when you run the command `hexo generate` and will be saved in a folder called: `public`. 

Any further questions or issue just write back.

**Comment by joha0033** [comment]
So awesome man. Thank you. I do have a couple more q's. I'm off my ass now,
and will be back on the computer tomorrow or Monday. Amazing I got an
actual email from some one. You're awesome.

- fixing to start a web development course in April, trying to get a head
start here. Your editor is great so far. Thank you!

**Comment by mrttl** [comment]
Good stuff, post back with any questions anytime!
