### ISSUE TITLE
Auto collapsing and Code Line Numbering...

### ISSUE THREAD

**Issue by jiapei100** [hexojs/hexo#2447]
## Environment Info

Node version(`node -v`)
```
7.7.2
```

Your site `_config.yml`
```
http://longervision.github.io
```

Your theme `_config.yml`
```
light
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 .....
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```

Questions:
Have a look at my github blog first: [https://longervision.github.io/](https://longervision.github.io/)

1) I wonder how to make each blog collapse automatically?

2) And how to let those code line number shown in sequence? I mean, for each blog, although there are several pieces of codes, but with a sequential line number, instead of starting from "1" for every piece of code?

Thank you very much...
Pei

**Comment by NoahDragon** [comment]
1. You could use the  excerpt.
2. I don't think there is a way to do so in Markdown.
