### ISSUE TITLE
Bug: config.root appears twice in permalinks

### ISSUE THREAD

**Issue by daiyi** [hexojs/hexo#2449]
I have a `root` set in my `_config.yaml` and I noticed the permalinks being generated have the root represented twice:

> http://website.com/root/root/2017/03/12/a-blog-post

should be

> http://website.com/root/2017/03/12/a-blog-post

I'm pretty sure this is a config issue, but it's such a simple setup I can't figure out what's wrong. )': Help!

relevant parts of `_config.yml`:
```
url: http://website.com/root
root: /root/
permalink: :year/:month/:day/:title/
permalink_defaults:

relative_link: false
```
(let me know if you need more)

**Comment by NoahDragon** [comment]
Where the `_config.yaml` file located? In the `/` or `/root/` folder?

**Comment by daiyi** [comment]
The config is located in the `/` folder. 

I'm using github pages to host my project, and github pages automatically serves your project at <project-name> subdirectory of your domain. So for example, I've created a repo called "root" which is my hexo project. It's served at `daiyi.github.io/root`. I use the config in the original post, which causes the issue originally outlined. What's the correct way to configure it?

**Comment by NoahDragon** [comment]
Is it really necessary to put Hexo into a subdirectory? If not, I think you could set the `root: /root/` to `root: /`. Other settings remain the same. Hope this could fix your issue

**Comment by daiyi** [comment]
oh! that makes all of the sense. thanks a lot!
