### ISSUE TITLE
静态页面编译时中文的问题

### ISSUE THREAD

**Issue by mutoe** [hexojs/hexo#2450]
渲染时将 markdown 中含有中文的部分都转码成 unicode 了, 感觉这样对 seo 就没有支持了
![default](https://cloud.githubusercontent.com/assets/9391981/23871632/3517f6f6-0866-11e7-9356-c39e20211782.png)

对于这个产生的另外一个问题 使用 `hexo-generator-searchdb` 插件时, 产生的 search.xml 文件里中文也被转化为 unicode 了, 导致搜索中文时找不到结果.
![default](https://cloud.githubusercontent.com/assets/9391981/23871726/96b9b9da-0866-11e7-8711-42997b83ebe0.png)

不知道这是什么原因产生的, 要解决的话有什么思路吗

**Comment by NoahDragon** [comment]
不知道是不是安装了什么插件。我的页面并没有转码的现象。

**Comment by mutoe** [comment]
用的next主题, 看了其他用next主题的也没有出现这种情况, 这是我依赖的插件
``` json
"hexo": {
  "version": "3.2.2"
},
"dependencies": {
  "hexo": "^3.2.0",
  "hexo-asset-image": "^0.0.2",
  "hexo-browsersync": "^0.2.0",
  "hexo-deployer-git": "^0.2.0",
  "hexo-generator-archive": "^0.1.4",
  "hexo-generator-baidu-sitemap": "^0.1.2",
  "hexo-generator-category": "^0.1.3",
  "hexo-generator-feed": "^1.2.0",
  "hexo-generator-index": "^0.2.0",
  "hexo-generator-searchdb": "^1.0.3",
  "hexo-generator-sitemap": "^1.1.2",
  "hexo-generator-tag": "^0.2.0",
  "hexo-renderer-ejs": "^0.2.0",
  "hexo-renderer-marked": "^0.2.10",
  "hexo-renderer-stylus": "^0.3.1",
  "hexo-server": "^0.2.0"
}
```
感觉也没有什么插件能影响到呀, 难道是编译环境的问题?

**Comment by NoahDragon** [comment]
编译环境应该没有问题。插件也看不出有问题的地方。是个别页面有这样的问题，还是所有页面？

**Comment by mutoe** [comment]
所有页面, 这是我项目的地址 [http://blog.mutoe.com](http://blog.mutoe.com)
您可以参考 [search.xml](http://blog.mutoe.com/search.xml) 这个 或者右键查看源代码

**Comment by NoahDragon** [comment]
感觉不是Hexo的问题，会不会和文本编辑器存储编码格式有关？

**Comment by mutoe** [comment]
经过重新安装hexo , 一步一步安装插件, 重建博客, 找到问题了
这个插件 `"hexo-asset-image": "^0.0.2",`
要求将`_config.yml` 中的 `post_asset_folder: false` 设置为 true, 这本身没什么问题
**但是当我加载图片时, 编译时就会将所有文件中文转化为unicode, 去除图片又会正常.**

这个bug是不是应该在 hexo-asset-image 这个插件的issue里面提交?

**Comment by mutoe** [comment]
我在这里找到了答案 https://github.com/CodeFalling/hexo-asset-image/issues/12
但那并似乎解决不了我的问题, 还是谢谢你了 @NoahDragon

**Comment by NoahDragon** [comment]
很高兴你找到了问题所在。
