### ISSUE TITLE
Comment instead of Kommentare ??? 

### ISSUE THREAD

**Issue by jiapei100** [hexojs/hexo#2452]
## Environment Info

Node version(`node -v`)
```
7.7.2
```

Your site `_config.yml`
```
http://longervision.github.io
```

Your theme `_config.yml`
```
light
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 .....
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```

Questions:
Have a look at my github blog first: [https://longervision.github.io/](https://longervision.github.io/)

How can I add **Comment**??? Currently, under any of my blogs shows **Kommentare** ????

Thank you very much...
Pei

**Comment by NoahDragon** [comment]
It depends on your theme. I suggest you use the Hexo-NexT theme which support multiple comment system.  http://theme-next.iissnan.com/
