### ISSUE TITLE
open_graph / og:image not created

### ISSUE THREAD

**Issue by kirkcameron** [hexojs/hexo#2454]
version: hexo 3.3.2

when using 
`hexo server`
og:image meta tags are rendered properly

when using
`hexo generate`
og:image meta tags are not rendered at all

❗️ if og:image does not exist, facebook does not show article-photos anymore, which is really bad ❗️ 

---------
more ideas about og:image:

it would be good to add 
og:image:secure_url 
to open_graph.js as it is wanted from facebook if the website is running with https:

❗️ as far as i can see, og:image is missing in the open_graph test case. ❗️ 

from my point of view open_graph (for images) should work in this order:
- use a picture, if it is configured in front-matter (can be photos, thumbnail, opengraph_pictures, whatever - somebody needs to decide what is the best name)
- if no photo is configured in frontmatter - use all photos, which are used within the body (works with hexo s)
- if post/page does not contain a photo use config.logo (or similar)

at the end it is important, that at least some picture is connected to the post/page via og:image ... could be even a hexo-logo as a final fallback.

**Comment by NoahDragon** [comment]
I believe this has already fixed in https://github.com/hexojs/hexo/pull/2348 , but not in the npm repo.

**Comment by kirkcameron** [comment]
hi noah, have you read the issue description?
this is not fixed at all!
(!) the problem is the different behavior of hexo g and hexo s (!)

**Comment by NoahDragon** [comment]
@kirkcameron Sorry, I missed that part. Fortunately, https://github.com/hexojs/hexo/issues/2451 raises the similar issue and we are currently investigating, hope it could fix both. 

If you feel we close your issue incorrectly, please reopen it without hesitate. As I saw you create a new issue with more details, I suggest keep this one remain close and move discuss to the new one #2503 .

**Comment by kirkcameron** [comment]
great, thank you!

Reinhard Krämer
