### ISSUE TITLE
npm install -g hexo-cli

### ISSUE THREAD

**Issue by cyoncan** [hexojs/hexo#2457]
Node version(`node -v`)
```
v6.10.0
```
OS
```
Ubuntu 16.04.2 LTS \n \l
```
## For question
 ✘ daemon@ubuntu  ~  sudo npm install -g hexo-cli
[sudo] password for daemon: 
/usr/bin/hexo -> /usr/lib/node_modules/hexo-cli/bin/hexo
/usr/lib
└─┬ hexo-cli@1.0.2 
  └─┬ hexo-log@0.1.2
    └─┬ bunyan@1.8.8
      └── moment@2.18.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/hexo-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
Why is this warning?

**Comment by linyonglee** [comment]
I meet the same problem with manjalor OS.

**Comment by AlexZ33** [comment]
I meet the same problem with Win10

**Comment by cyoncan** [comment]
Please ignore the Waring and It will not affect , I'm using hexo for my blog no problem .

**Comment by NoahDragon** [comment]
Those warnings are from npm, not Hexo. Basically, they are saying some dependencies are not installed due to some reasons.
