### ISSUE TITLE
hexo install wrong

### ISSUE THREAD

**Issue by feng9152** [hexojs/hexo#2460]
`bogon:~ chenjunfeng$ npm install -g hexo
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "hexo"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.24.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chenjunfeng/npm-debug.log`

**Comment by ILYG** [comment]
try to change npm mirror with:
`npm config set registry https://registry.npm.taobao.org`
and install hexo .

**Comment by NoahDragon** [comment]
As the message said, it's an issue with npm itself. Hexo couldn't do much about it.
