### ISSUE TITLE
hexo install error

### ISSUE THREAD

**Issue by AlexZ33** [hexojs/hexo#2463]
$ npm install -g hexo-cli

npm WARN gentlyRm not removing d:\Program Files (x86)\Nodist\bin\hexo.cmd as it wasn't installed by d:\Program Files (x86)\Nodist\bin\node_modules\hexo-cli
npm WARN gentlyRm not removing d:\Program Files (x86)\Nodist\bin\hexo as it wasn't installed by d:\Program Files (x86)\Nodist\bin\node_modules\hexo-cli
d:\Program Files (x86)\Nodist\bin\hexo -> d:\Program Files (x86)\Nodist\bin\node_modules\hexo-cli\bin\hexo
d:\Program Files (x86)\Nodist\bin
`-- hexo-cli@1.0.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\hexo-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"                                                                                    x64"})

cant understand ....?anyone can help?

**Comment by NoahDragon** [comment]
It's only warning. No error.
