### ISSUE TITLE
hexo插件制作问题

### ISSUE THREAD

**Issue by xuanmiaog** [hexojs/hexo#2464]
需要在每个页面中加入一段脚本，使用了
hexo.extend.filter.register中的'before_post_render'，但只是在每篇文章中加入了这段脚本，怎么办？

**Comment by NoahDragon** [comment]
不是很理解，能详细说明下么？

**Comment by unnamed42** [comment]
你可以注册到`after_render:html`事件试试，此时你在函数中看到的是渲染完成之后的html, 对所有页面有效
