### ISSUE TITLE
Http request via helper

### ISSUE THREAD

**Issue by DMXL** [hexojs/hexo#2467]
Wonder if it's possible to send http requests inside hexo helpers. The following is a simple example using the given [http request](https://github.com/request/request) package (I believe it's hexo's default dependency) to send GET request to the Github API. Any thoughts on why this is not working (or how to unit test it) inside one of those template files?

``` javascript
/**
 * GetRepos
 * @description Get github public repos of the given author.
 * @example
 *     getRepos(author);
 */

hexo.extend.helper.register('getRepos', function (author) {
    const ROOT_URL = 'https://api.github.com';
    let request = require('request');
    let url = ROOT_URL + '/users/' + author + '/repos';

    request(url, function (error, response, body) {
        return response;
    })
});
```

**Comment by NoahDragon** [comment]
I think helper support the http request, but in an async way. Therefore, before the request returns any information, the rendering process has finished.

**Comment by sugoidesune** [comment]
How do you make the request synchronous?

**Comment by tcrowe** [comment]
Hey guys the helper must be sync because most template engines are synchronous. Use node's `child_process.execSync` combined with `curl` or equivalent. That should work.

**Comment by sugoidesune** [comment]
I now used the sync-request package. Works in production and since its only once during generating its fine aswell.
https://www.npmjs.com/package/sync-request
