### ISSUE TITLE
我Pull  返回 不支持主题

### ISSUE THREAD

**Issue by AlianBlank** [hexojs/hexo#2480]
主题来源：
https://github.com/vuejs/cn.vuejs.org 
响应邮件如下：

The page build completed successfully, but returned the following warning:

You are attempting to use a Jekyll theme, "vue", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by NoahDragon** [comment]
请详细描述下是如何发布Hexo页面的？

**Comment by AlianBlank** [comment]
请问 应该怎么发布页面  ,我在本地 运行时正常的. 需要依次执行哪些命令,才能成功发布到github pages

**Comment by NoahDragon** [comment]
安装https://github.com/hexojs/hexo-deployer-git，按照说明将要发布的地址添加到_config.yml中。
