### ISSUE TITLE
How to disable the auto-hyperlink for a url?

### ISSUE THREAD

**Issue by zhaiqianfeng** [hexojs/hexo#2482]
If my post contain a url such as"http://localhost",the url in the generated html will be wrapped a hyperlink such as <a href="http://localhost">http://localhost</a>.

How to disable?
Please help me. Thanks.

**Comment by NoahDragon** [comment]
You could change http://localhost to wrap with back-tick ` .

`http://localhost`

**Comment by zhaiqianfeng** [comment]
If so,hexo will generate the "code" tag.
Is there any other methods?
@NoahDragon

**Comment by NoahDragon** [comment]
Here have more trick ways to disable auto link: https://gist.github.com/alexpeattie/4729247

In Hexo, you could also create helper or filter to handle the link.

**Comment by NoahDragon** [comment]
https://github.com/chjj/marked/issues/882#issuecomment-291029431 proposed a solution. I think we could add it to the hexo-renderer-markdown plugin.

Close this issue and move it to the corresponding repo.

**Comment by NoahDragon** [comment]
The feature has added to hexo-renderer-marked 0.3.0 https://github.com/hexojs/hexo-renderer-marked/pull/34
