### ISSUE TITLE
New post.md files

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#2483]
Hello,
I use a lot of frontmatter variables in my posts, is there a way of having my posts split into two markdown files per post? One for variables and one for content? So blog.md has a .md file for content and one for variables? I am using **Asset Folders** if that helps. Can Hexo use anything else other than markdown to store data?

Thank you.

**Comment by NoahDragon** [comment]
Yes, it is possible to separate them. You could reference the Hexo.io site: https://github.com/hexojs/site/tree/master/source/_data

For the [plugins](https://hexo.io/plugins/) and [themes](https://hexo.io/themes/) pages, all the data are from the source/_data folder.

**Comment by ntot** [comment]
Thank you NoahDragon, I just started with Hexo. So I have 12 posts in my _post folder and they have a lot of front matter so I would create a .yml per post? Is that correct? I will also look at the site source.

**Comment by NoahDragon** [comment]
If those 12 posts share some common front matters setting, you could put into one yml file. 

.yml and .md file could put into one folder (if this is what mix means).

**Comment by mrttl** [comment]
Thank you very much NoahDragon! I will try it out.
