### ISSUE TITLE
hexo g报错，请教是否文章长度有限制？

### ISSUE THREAD

**Issue by iterryzhao** [hexojs/hexo#2484]
hexo g正常是能够生成文件顺利通过的

但是新弄了一篇长篇文章之后，hexo g报错。还请高手帮忙看看，谢谢。

版本信息：
hexo 3.2.2
node v6.10.1

错误信息：

> FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html Template render error: (unknown path) SyntaxError: Invalid or unexpected token at Object.exports.prettifyError (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/lib.js:34:15) at new_cls.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:469:27) at new_cls.renderString (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:327:21) at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:66:9 at Promise._execute (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/debuggability.js:300:9) at Promise._resolveFromExecutor (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:483:18) at new Promise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:79:10) at Tag.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:64:10) at Object.tagFilter [as onRenderEnd] (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/post.js:253:16) at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/render.js:65:19 at tryCatcher (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:693:18) at Async._drainQueue (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:133:16) at Async._drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:143:10) at Immediate.Async.drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:17:14) at runCallback (timers.js:666:20) at tryOnImmediate (timers.js:639:5) at processImmediate [as _immediateCallback] (timers.js:611:5) FATAL (unknown path) SyntaxError: Invalid or unexpected token Template render error: (unknown path) SyntaxError: Invalid or unexpected token at Object.exports.prettifyError (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/lib.js:34:15) at new_cls.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:469:27) at new_cls.renderString (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:327:21) at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:66:9 at Promise._execute (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/debuggability.js:300:9) at Promise._resolveFromExecutor (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:483:18) at new Promise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:79:10) at Tag.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:64:10) at Object.tagFilter [as onRenderEnd] (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/post.js:253:16) at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/render.js:65:19 at tryCatcher (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:693:18) at Async._drainQueue (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:133:16) at Async._drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:143:10) at Immediate.Async.drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:17:14) at runCallback (timers.js:666:20) at tryOnImmediate (timers.js:639:5) at processImmediate [as _immediateCallback] (timers.js:611:5)

**Comment by NoahDragon** [comment]
可否分享下md文件？

**Comment by iterryzhao** [comment]
@NoahDragon 见附件

[Secrets-of-the-Millionaire-Mind-1.md.zip](https://github.com/hexojs/hexo/files/893543/Secrets-of-the-Millionaire-Mind-1.md.zip)

**Comment by NoahDragon** [comment]
不是文件长造成的问题，是因为文件中存在无法识别的字符：
![image](https://cloud.githubusercontent.com/assets/5704064/24675395/f7fd6b6e-194c-11e7-9dca-774c44a53b43.png)
将这些移除后就可以了。

更改后文件如下（同时也更改了些markdown的格式）：
[modifiedFile.zip](https://github.com/hexojs/hexo/files/894301/modifiedFile.zip)

**Comment by iterryzhao** [comment]
@NoahDragon 感谢！
请问这个是用工具检查出来的吗？O(∩_∩)O谢谢

**Comment by NoahDragon** [comment]
Visual Studio Code大概过一遍就看到了，还是很明显的。
