### ISSUE TITLE
Windows end-line issue in 3.3.0

### ISSUE THREAD

**Issue by jourdain** [hexojs/hexo#2485]
## Bug on unix system

```
$ npm install
├─┬ hexo@3.3.0 
│ ├─┬ hexo-cli@1.0.2 
│ ├── hexo-front-matter@0.2.3 
│ ├─┬ hexo-fs@0.1.6 
│ ├─┬ hexo-i18n@0.2.1 
│ ├─┬ hexo-log@0.1.2 
│ ├─┬ hexo-util@0.6.0 
├─┬ hexo-deployer-git@0.1.0 
│ └─┬ hexo-util@0.5.3 
├─┬ hexo-generator-archive@0.1.4 
│ ├─┬ hexo-pagination@0.0.2 
├─┬ hexo-generator-feed@1.2.0 
├── hexo-generator-sitemap@1.1.2 
├─┬ hexo-renderer-jade@0.3.0 
├─┬ hexo-renderer-marked@0.2.11 
├─┬ hexo-renderer-stylus@0.3.3 
├─┬ hexo-server@0.2.0 

$ ./node_modules/.bin/hexo generate
env: node\r: No such file or directory
```

Changing the line ending to Unix in ` ./node_modules/.bin/hexo` solved the problem.

**Comment by jourdain** [comment]
The file in the repo is fine. I'm guessing, the issue came from the publication to npm by @NoahDragon. Probably some wrong setup on git on Windows for [CRLF](https://help.github.com/articles/dealing-with-line-endings/).

I think our Windows user have their environment setup with `git config --global core.autocrlf false`

Otherwise, great project, I love it!!!

**Comment by NoahDragon** [comment]
@jourdain thank you. I didn't notice the config. I will fix it, and re-publish.

**Comment by jourdain** [comment]
Thanks for the great work... 
I noticed it, as it broke all our product documentation when it picked up the new version of hexo. ;-)

**Comment by jourdain** [comment]
It seems that our Windows user have `core.autocrlf=true`. Sorry...

**Comment by NoahDragon** [comment]
Sorry for the inconvenience. Publish 3.3.1. Please get the latest version, and kindly info if it is working.

**Comment by NoahDragon** [comment]
NPM really should avoid such issue by following the git global config, which is check-out as windows style and check-in as unix ending. 

https://github.com/npm/npm/issues/12371

**Comment by jourdain** [comment]
Yep. Waiting for my travis to get back to let you know...

**Comment by jourdain** [comment]
Ok giving up on travis... Tried locally and everything is fine now. Thanks!

**Comment by NoahDragon** [comment]
Great glad it is working! Thanks for letting us know.
