### ISSUE TITLE
Delete .deploy_git folder, github commit history lost

### ISSUE THREAD

**Issue by mirrorhanyu** [hexojs/hexo#2486]
误删.deploy_git文件夹 然后使用hexo deploy部署 导致github commits丢失之前的所有history 
请问有什么办法恢复吗

**Comment by NoahDragon** [comment]
hexo-deploy-git 每次deploy是force push，所以每次commit history都会丢失。最好将source和page放在不同的branch里。

**Comment by mirrorhanyu** [comment]
make sense, thanks
