### ISSUE TITLE
BUG？ 谷歌Search Console上的抓取错误，null并404报错？

### ISSUE THREAD

**Issue by Hscpro** [hexojs/hexo#2487]
Your site `_config.yml` (Optional):
```php
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.hscbook.com/
root: /
permalink: article/:title/
permalink_defaults:
```

正常地址：https://www.hscbook.com/article/hexo-install/
谷歌蜘蛛获取的地址：https://www.hscbook.com/article/hexo-install/null
 Sitemap：https://www.hscbook.com/sitemap.xml

谷歌Search Console上的抓取错误，所有链接地址结尾都被加上了null 并报404
而实际地址是没有加上null，谷歌相关文章表示是因为地址上有空格，我检查了源码并没有发现

**Comment by NoahDragon** [comment]
请再观察一段时间，可能google正好收录了一次错误的配置，如果以后不再出现，就应该不是网页生成的问题。

**Comment by Hscpro** [comment]
非常感谢，但是这是我在本地测试后的第一次上传。域名也是刚注册的。
![20170406112818](https://cloud.githubusercontent.com/assets/13926044/24736733/653bebb8-1abc-11e7-9c28-9cd0c098f4d1.png)
![20170406112845](https://cloud.githubusercontent.com/assets/13926044/24736737/6bbbaa1e-1abc-11e7-96d3-a4e02198bf35.png)
@NoahDragon

**Comment by Hscpro** [comment]
是的，这正是困扰我觉得奇怪的地方。

**Comment by Hscpro** [comment]
最新的一次错误是在昨天，谷歌显示问题依然存在
![20170408155027](https://cloud.githubusercontent.com/assets/13926044/24826904/49dec512-1c73-11e7-8f4f-8e7bce9ab86e.png)

**Comment by NoahDragon** [comment]
你需要选中它们，并标记为已修复。否则google的clawer会每次都访问这些不存在的页面。
