### ISSUE TITLE
npm install -g hexo-cli错误

### ISSUE THREAD

**Issue by icecream9** [hexojs/hexo#2489]
## Environment Info

Node version(`node -v`):v7.8.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG
/root/.nvm/versions/node/v7.8.0/bin/hexo -> /root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/bin/hexo

> dtrace-provider@0.8.1 install /root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/dtrace-provider
> node scripts/install.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/dtrace-provider/scripts/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

> hexo-util@0.6.0 postinstall /root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util
> npm run build:highlight

npm ERR! Error: EACCES, readdir '/root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util'
npm ERR!  { [Error: EACCES, readdir '/root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.19.0-33-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:highlight"
npm ERR! cwd /root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, readdir '/root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/.nvm/versions/node/v7.8.0/lib/node_modules/hexo-cli/node_modules/hexo-util/npm-debug.log
npm ERR! not ok code 0
/root/.nvm/versions/node/v7.8.0/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/hexo-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 (node_modules/hexo-cli/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 8
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/root/.nvm/versions/node/v7.8.0/bin/node" "/root/.nvm/versions/node/v7.8.0/bin/npm" "install" "-g" "hexo-cli"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 3

npm ERR! hexo-util@0.6.0 postinstall: `npm run build:highlight`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.0 postinstall script 'npm run build:highlight'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:highlight
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-04-06T03_29_17_026Z-debug.log

**Comment by NoahDragon** [comment]
Please try if `sudo npm install -g hexo-cli` works?
