### ISSUE TITLE
Please report issues in english :)

### ISSUE THREAD

**Issue by xseignard** [hexojs/hexo#249]
Hello,
I'm using hexo for my blog and I really enjoying it, and I'd like to contribute it back, but I can't since I don't understand the language you're using :) (I think it's chinese, right?)

Regards and great work,

Xavier

**Comment by arlair** [comment]
For those who have Chrome, there is a translate option in the right click (in Windows) menu which is fairly easy to do. It is quicker than copy and pasting for those that have it. Being a native English speaker, I obviously prefer English though ;)

**Comment by Xuanwo** [comment]
Closed for no more update, with google translate, this will not be problem.
