### ISSUE TITLE
the amount option of list_posts function not working correctly

### ISSUE THREAD

**Issue by zongren** [hexojs/hexo#2490]
## Environment Info

Node version(`node -v`):6.10.1

Hexo and Plugin version(`npm ls --depth 0`): 
+-- fontmin@0.9.6 extraneous
+-- hexo@3.2.2
+-- hexo-algoliasearch@0.2.1
+-- hexo-footnotes@1.0.1
+-- hexo-front-matter-excerpt@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.0
+-- hexo-generator-sitemap@1.1.2
+-- hexo-generator-tag@0.2.0
+-- hexo-generator-tile@0.0.15
+-- hexo-html-minifier@0.0.1
+-- hexo-processor-static@1.0.0
+-- hexo-renderer-ejs@0.3.0
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.1
+-- hexo-server@0.2.0
+-- microtime@2.1.2 extraneous
`-- underscore@1.8.3 extraneous

## For BUG

I use the `list_posts` in the following way,it still generates only 6 posts
```
<%- list_posts({"order":-1,"class":"article-header","amount":0}) %>
```

**Comment by NoahDragon** [comment]
Could you provide the step/data to reproduce this issue?
