### ISSUE TITLE
能否解决渲染mathjax公式问题

### ISSUE THREAD

**Issue by EncodeTS** [hexojs/hexo#2493]
现在会默认把公式里的下划线给渲染出<em>标记，网上很多博客提到这个问题，但是解决方案都不完美
如：
http://lukang.me/2014/mathjax-for-hexo.html
http://shomy.top/2016/10/22/hexo-markdown-mathjax/

**Comment by NoahDragon** [comment]
还有一种方法似乎文章中都没有提及，就是Raw tag https://hexo.io/docs/tag-plugins.html#Raw

这个问题完全是由于两种标记语言使用了相同的符号造成的，如果语言本身不修改，外围任何的解决方法都是暂时的。

**Comment by EncodeTS** [comment]
Raw tag对付行内公式貌似仍旧是不好用啊

**Comment by Zhang21** [comment]
我参考的这篇文章：https://ranmaosong.github.io/2017/11/29/hexo-support-mathjax/
