### ISSUE TITLE
hexo init <folder> error

### ISSUE THREAD

**Issue by hanhanyy** [hexojs/hexo#2496]
syntax error near unexpected token `newline'

**Comment by NoahDragon** [comment]
Please paste the whole error output.

**Comment by ai-heng** [comment]
I met the same issue and couldn't find the answer yet.
the title and the first comment just the whole error output.
because when i input "$ hexo init <folder>"
it output "bash:syntax error near unexpected token `newline'"

**Comment by NoahDragon** [comment]
@ai-heng seems like it is something related to the folder name. `< >` symbol is not allowed in bash.

http://stackoverflow.com/questions/5134399/bash-syntax-error-near-unexpected-token-newline

**Comment by ai-heng** [comment]
@NoahDragon Yes,that's truly the reason for me,now it has worked,thanks.
