### ISSUE TITLE
Feature Request:  copy a post to clipboard (with style and image)

### ISSUE THREAD

**Issue by suredream** [hexojs/hexo#2500]
Is that easy to add a icon for each post to 'copy to clipboard (with styles and images).

Will be super useful to copy the post to wechat,  zhihu, ..... etc.

**Comment by NoahDragon** [comment]
This could be a feature done by theme builder.

**Comment by NoahDragon** [comment]
How about the niche tool created by @barretlee? https://github.com/hexojs/hexo/issues/2183
http://md.barretlee.com/
