### ISSUE TITLE
generate --draft support

### ISSUE THREAD

**Issue by psi-4ward** [hexojs/hexo#2501]
Would be nice to be able to generate the contents of `/public` including the drafts.
Useful for _staging_ environments and reviews.

**Comment by NoahDragon** [comment]
I think render command is what you are looking for: https://hexo.io/docs/commands.html#render

It will render certain files, and output to html.

**Comment by psi-4ward** [comment]
Correct, it renders a certain file, not _everything_. So I need more a `generate --draft` like `serve --draft`

**Comment by NoahDragon** [comment]
After re-read the document, it is already supported. Please feel free to reopen if you still have question.

https://hexo.io/docs/writing.html#Drafts

    Drafts are not displayed by default. You can add the --draft option when running Hexo or enable the render_drafts setting in _config.yml to render drafts.

**Comment by psi-4ward** [comment]
Thanks for your answer but `publish` is not my use case.
I need to deploy the website including all drafts to a staging environment where some _higher leveled_ editors can review the drafts.
