### ISSUE TITLE
An error when rendering

### ISSUE THREAD

**Issue by sydney0zq** [hexojs/hexo#2502]
## Environment Info

Node version(`node -v`): v7.2.1

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 /Users/zhou/Public/sydney
├── hexo@3.3.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@2.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-jade@0.3.0
├── hexo-renderer-markdown-it@3.4.1
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.0

## For BUG

1. Cannot render some file, a weird BUG

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/zhou/Public/sydney/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/zhou/Public/sydney/node_modules/nunjucks/src/environment.js:469:27)
...
FATAL (unknown path)
  SyntaxError: Invalid or unexpected token
Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/zhou/Public/sydney/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/zhou/Public/sydney/node_modules/nunjucks/src/environment.js:469:27)
...
```

2. Some md file causes this, and I finally found some string causes it.

> 
> ` ` `
> Events  Gable
> ` ` `(This three \` should be in sequence)

Such this can cause this issue.

## For question

I am too tired to use HEXO. It is really annoying.

**Comment by sydney0zq** [comment]
And I found 
\```
s  G
\```
can also make it.

**Comment by NoahDragon** [comment]
Based on my understanding, the errors are caused by something else. Can I confirm that if you remove those line of text, the errors will go away?
