### ISSUE TITLE
{ Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by moreoronce** [hexojs/hexo#2506]
still suffered 

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
```

i've tried all the two solution above this issue

npm uninstall hexo-cli -g
npm install hexo-cli -g

and

npm install hexo --opential

but all of this two doesn't work

I used macbook air and the npm version is 4.2.0 and node version is v7.8.0

the error message i got is

{ Error: Cannot find module './build/Release/DTraceProviderBindings' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' } { Error: Cannot find module './build/default/DTraceProviderBindings' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' } { Error: Cannot find module './build/Debug/DTraceProviderBindings' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/usr/local/lib/node_modules/hexo-cli/node_modules/bunyan/lib/bunyan.js:79:18) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' } { Error: Cannot find module './build/Release/DTraceProviderBindings' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/dtrace-provider/dtrace-provider.js:17:23) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/bunyan/lib/bunyan.js:79:18) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/hexo-log/lib/log.js:3:14) at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' } { Error: Cannot find module './build/default/DTraceProviderBindings' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/dtrace-provider/dtrace-provider.js:17:23) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/bunyan/lib/bunyan.js:79:18) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/hexo-log/lib/log.js:3:14) at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' } { Error: Cannot find module './build/Debug/DTraceProviderBindings' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/dtrace-provider/dtrace-provider.js:17:23) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/bunyan/lib/bunyan.js:79:18) at Module._compile (module.js:571:32) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/moreoronce/Dropbox/Documents/Daily/node_modules/hexo-log/lib/log.js:3:14) at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' }

Are there any other solution?

**Comment by NoahDragon** [comment]
Have you tried `npm install hexo-cli --no-optional`?

**Comment by moreoronce** [comment]
@NoahDragon i've tried this command to install hexo. But after that when i inputed the hexo command, the shell told me command can not found.

**Comment by NoahDragon** [comment]
Does the `hexo init` working?

What's the nodejs version and npm version?

**Comment by moreoronce** [comment]
@NoahDragon no， `hexo init` doesn't work.

my nodejs' version is V7.8.0 and the npm's version is 4.2.0

**Comment by NoahDragon** [comment]
This issue looks like related to nodejs prefix. http://stackoverflow.com/questions/15054388/global-node-modules-not-installing-correctly-command-not-found

Or the npm directory is not set in PATH variable. http://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found

If the above two do not fix the issue, I probably need more info to investigate the issue, like what's your OS, have you installed other global package via npm?

**Comment by nicholascloud** [comment]
Did some digging. This happens when the system python is 3.x.

https://github.com/trentm/node-bunyan/issues/216

I set my system python to 2.7.13, uninstalled hexo-cli and all local hexo packages, then reinstalled with `npm install -g hexo-cli -O && npm install -O` and dtrace built successfully.

**Comment by buoge** [comment]
I uninstall hexo ,change my mac python vertion from 3.6 to 2.7 , and run ` npm install -g hexo-cli`  dtrace built successfully!  thanks @nicholascloud !

**Comment by JLHwung** [comment]
I come across this issues several times. Could we rewrite hexo-log so that it does not use bunyan anymore? As dtrace-provider is an optional dependencies of bunyan and I guess we haven't use any related routines.

**Comment by NoahDragon** [comment]
@JLHwung You are right. If we could only opt-out the DTrace-provider in bunyan, we can solve this issue once for all. Probably create a hexo-bunyan, without the DTrace-provider as an optional.

**Comment by kyasbal-1994** [comment]
In my case, `npm install hexo-cli --no-optional` was not working. However, `npm rebuild` could solve this problem.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-bunyan/pull/1
