### ISSUE TITLE
css/js file url goes wrong when served with proxypass in a sub directory

### ISSUE THREAD

**Issue by wlx65003** [hexojs/hexo#2509]
I served hexo at `localhost:4000`
And I proxypass all request in `example.com/blog` to `localhost:4000`
Then problem occurs.
All js/css file is 404 beacuse they are requesting `example.com/css/*` and `example.com/js/*`
It should be `example.com/blog/(css/js)/*`
Sure I can redirect all `example.com/(css/js)` request to `example.com/blog/(css/js)`.
But is there a more elegant way such as providing a configuration option?

**Comment by NoahDragon** [comment]
In the config file, the following two lines have to be modified accordingly.

```
url: http://example.com/blog/
root: /
```

**Comment by wlx65003** [comment]
I've modified these lines, but problem still exists.
That's my config file:
```
url: https://d-star.xyz/blog/
root: /
```
You could take a look at my site.

**Comment by NoahDragon** [comment]
Sorry, my mistake. The root should be `root: /blog/`

**Comment by wlx65003** [comment]
Then it redirect url from `example.com/blog` to `example.com/blogblog/`, 404.
And if I visit `example.com/blog/`, it throws an exception `Cannot GET // `

**Comment by NoahDragon** [comment]
Then I think in the config file: `url: https://d-star.xyz/blog` remove the trail slash.

**Comment by wlx65003** [comment]
The same `Cannot GET //`
```
url: https://d-star.xyz/blog
root: /blog/
```

**Comment by NoahDragon** [comment]
It's really wired. Could you please give the last try:

```yml
url: https://d-star.xyz
root: /blog/
```

If it still fails, I don't think there is anything Hexo could do for now.

**Comment by wlx65003** [comment]
Still `Cannot GET //`.
Okay, thanks a lot.

**Comment by NoahDragon** [comment]
It seems work on my local environment. By using the above setting, I got the following url: `/test/css/style.css`

![image](https://cloud.githubusercontent.com/assets/5704064/25013055/4c30888e-2040-11e7-91ae-82d3b03f2757.png)

Another thing I forgot to mention, please make sure to clean the cache before generating: `hexo clean && hexo g`.

Probably, you could take a look at the proxy setting.

**Comment by wlx65003** [comment]
I modified my proxy like this:
```
Proxypass /blog http://localhost:4000/blog/
ProxypassReverse /blog http://localhost:4000/blog/
```
And it works with
```
url: https://d-star.xyz
root: /blog/
```
Thanks a lot!
