### ISSUE TITLE
hexo init fail

### ISSUE THREAD

**Issue by eif-xu** [hexojs/hexo#2514]
![](http://i2.muimg.com/567571/5003ac11093f2ffd.png)
# win8.1环境
hexo init  命令显示无法找到hexo.

**Comment by NoahDragon** [comment]
请查看下`C:\Users\xu\AppData\Roaming\npm`是否在环境PATH中？

**Comment by eif-xu** [comment]
已添加，已解决。

**Comment by WangChangQin** [comment]
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 (node_modules\dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.1 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\tools\\node\\node.exe" "E:\\tools\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "hexo" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! hexo-util@0.6.0 postinstall: `npm run build:highlight`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hexo-util@0.6.0 postinstall script 'npm run build:highlight'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:highlight
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\blog\npm-debug.log
`
我的问题好像一样，也是报错

**Comment by NoahDragon** [comment]
@eif-xu 不是同一个问题。请查看用户权限。http://stackoverflow.com/questions/30744964/what-does-the-elifecycle-node-js-error-mean
