### ISSUE TITLE
Hexo hanges while generating.

### ISSUE THREAD

**Issue by Ziflin** [hexojs/hexo#2516]
While trying to run: `hexo generate --debug` Hexo hangs after the final file is "Processed" and uses 100% CPU and never completes. As I do not see a log for the start of the next action after things are "Processed" I can't tell what is actually causing it to hang. 

Is there some way to get additional debug information or does anyone have a guess as to how to track this down? It seems to be before any files are generated in the public folder. I have made very few changes since it was last generating correctly.

## Environment Info

Node version(`node -v`): *v6.10.2*

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 /home/dcox/git/aroundhomediy.com
hexo@3.2.2
hexo-clean-css@0.0.2
hexo-generator-archive@0.1.4
hexo-generator-category@0.1.3
hexo-generator-index@0.2.0
hexo-generator-tag@0.2.0
hexo-html-minifier@0.0.1
hexo-renderer-bourbon@1.0.4
hexo-renderer-ejs@0.2.0
hexo-renderer-marked@0.2.11
hexo-server@0.2.0
hexo-uglify@0.0.3
hexo-util@0.6.0
image-size@0.5.0

**Comment by NoahDragon** [comment]
Does it always hang when run `hexo g`?

**Comment by Ziflin** [comment]
It appears the issue is with the `html-minifier` plugin choking on some badly formatted HTML output. I'm not sure if there is a way to debug this any faster though?

**Comment by NoahDragon** [comment]
@Ziflin I don't think there is a better way so far. You are right, the debug info should also output in plugins. Right now, There is no plugins have respected the `--debug` flag.
