### ISSUE TITLE
how convert hexo blog date and time to jalali?

### ISSUE THREAD

**Issue by monala** [hexojs/hexo#2517]
I can't find a way to convert momentjs of hexo to jalali. How I cant convert the date to jalali calendar date ?

**Comment by NoahDragon** [comment]
I think you have to create a filter for your purpose.

https://github.com/hexojs/hexo/issues/2385

**Comment by monala** [comment]
Well, I don't want to change permalinks!
I saw the filter doc page, and now the question is what is the directory for created filter file? I create a folder in my theme folder contains the filter file and this is the code 
`var moment = require('moment-jalaali');

hexo.extend.filter.register('jalaali', function (date) {
    return moment(date).format('jYYYY/jM/jD'); // You can change the date format
});
hexo.extend.filter.register('jalaaliyear', function (date) {
    return moment(date).format('jYYYY'); // You can change the date format
});
`
but it didnt work!

**Comment by NoahDragon** [comment]
The `scripts` folder should be created under the main Hexo/Theme folder. Like: 
https://github.com/hexojs/site/tree/master/scripts
https://github.com/iissnan/hexo-theme-next/tree/master/scripts

Then you could call the filter in your theme files.

**Comment by monala** [comment]
for Jalali calendar as @NoahDragon  said I create scripts directory in my theme and this is a helper for Jalali
`'use strict';

var moment = require('moment-jalaali');

hexo.extend.helper.register('jalaali', function (date) {
    return moment(date).format('jYYYY/jM/jD'); // You can change the date format
});
hexo.extend.helper.register('jalaaliyear', function (date) {
    return moment(date).format('jYYYY'); // You can change the date format
});`
and I use it with this in this way in my posts : `<%- jalaali(item.date) %>`
