### ISSUE TITLE
generate Read More

### ISSUE THREAD

**Issue by demeiyan** [hexojs/hexo#2524]
## Environment Info

Node version(`node -v`):
v7.9.0
Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question
My blogs can not generate Read More when they show on index`s page. Could they show abstract on the index page and generate Read More  automatically . I want to know how to deploy. Thanks for your help!

**Comment by NoahDragon** [comment]
You could add 
```
<!--more-->
```
into the post. It will create a read more link if the theme supports.

**Comment by demeiyan** [comment]
I know add  could generate Read More but I want to  know how to modify configuration file that hexo can generate Read More automatically when run "hexo d -g" . If not ,never mind.

**Comment by NoahDragon** [comment]
I'm not sure if I clearly understand your question. When you say `automatically`, do you mean to generate an abstract based on your post content?

**Comment by egoist** [comment]
This could/should be done by the theme you use, not Hexo I guess.

**Comment by enkr1** [comment]
Now after 7 years, is it possible to have "Read More" (`<!--more-->`) automatically set in config?
