### ISSUE TITLE
Plugin page search?

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#2525]
Hi, on the [https://hexo.io/plugins/](url) page, how did you create the search? I am looking for a simple search for Hexo, I use EJS so didn't understand where all the files for the search are.

Thank you.

**Comment by NoahDragon** [comment]
You could take a look at the code here https://github.com/hexojs/site/blob/master/themes/navy/layout/plugins.swig

Hope this will help you.

**Comment by ntot** [comment]
ah and then copy all of the search code from JS folder? How does it load the data? Sorry for this question.

**Comment by NoahDragon** [comment]
The data is from the `/source/_data/` folder.

https://github.com/hexojs/site/tree/master/source/_data

**Comment by ntot** [comment]
Thank you so much! I will play around with it.  Maybe Hexo version 4 could have a basic search ;) it's the only thing missing from this amazing system.
