### ISSUE TITLE
使用hexo命令报错

### ISSUE THREAD

**Issue by mcuking** [hexojs/hexo#2528]
系统macos 10.12.4
已安装xcode  command line tools
按着官网步骤设置如下：
```
$sudo npm install hexo-cli -g
$hexo init blog
$cd blog
$npm install
```
然后再执行任何hexo命令都提示如下：
（退出当前blog文件后可以进行一些操作，比如hexo -v）
（已经使用过 npm install hexo --no-optional，也删除过博客文件夹的node_modules，重新npm install，都解决不了问题）
```
mcukingdom007deMacBook-Pro:Blogs mcukingdom007$ hexo server
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/mcukingdom007/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/mcukingdom007/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node
  Expected in: flat namespace

Abort trap: 6
```
![image](https://cloud.githubusercontent.com/assets/22924912/25265618/83d45e76-26a0-11e7-8fed-5b1cf5a99a82.png)

**Comment by NoahDragon** [comment]
这个问题是npm和node的安装问题。谷歌上有人建议彻底重装node和npm，不知道你是否尝试了？

**Comment by mcuking** [comment]
我昨晚彻底重新装了node，现在用nvm管理node版本，问题解决了。
但现在又有个问题，我在配置文件里设置的branch: master
可是hexo deploy后确是在github仓库重新创建了一个分支gh-pages
我希望能部署到master，因为GitHub Pages默认展示的是master分支上的内容，请问该怎么办呢？
![image](https://cloud.githubusercontent.com/assets/22924912/25300683/95a132f8-2747-11e7-8b16-fdb345ea7ecc.png)

**Comment by mcuking** [comment]
我已经在GitHub上将pages服务默认分支改为gh-pages了，我只是好奇为啥hexo配置文件里分支写的是master，而却没有部署到master分支呢？

**Comment by mcuking** [comment]
repo设置成https协议就可以push到远程的master分支了，而用ssh就不行，好奇怪～

**Comment by NoahDragon** [comment]
因为ssh协议需要配置ssh key。
