### ISSUE TITLE
How to support multitag search

### ISSUE THREAD

**Issue by MrMorning** [hexojs/hexo#2530]
## Environment Info
Mint 18.1 serena with x86_64 Linux 4.4.0-66-generic
Node version(`node -v`): v6.10.1
## For feature request
I've added some tags such as :  
tags: [Algorithm, NetworkFlow, MinCut]
Now I'd like to search for some article with tag "Algorithm" **and** "NetworkFlow";
What should I do to support this feature in my blog?
Is there any plugins?

**Comment by mrttl** [comment]
There are some plugins for search using 3rd party plugins, you can also use Google Custom Search or this great plugin: [https://github.com/zhouhao/Hexo-Tipue-Search-Json](url) it searches for tags and posts but not pages. If you are good with JS I am sure you can add pages too. Hope this helps.

**Comment by MrMorning** [comment]
@mrttl 
I just installed the plugin you mentioned, but i dont know how to do tag search. Could you give me some usage?
However, thank you very much.

**Comment by mrttl** [comment]
Did you add all of the code? What happens when you do a search?
