### ISSUE TITLE
hexo主题首页文章列表排序问题？

### ISSUE THREAD

**Issue by geekwill** [hexojs/hexo#2537]
为什么我的主题首页文章列表排序是乱的？文章都有指定date。

文章头部

![wechatimg40](https://cloud.githubusercontent.com/assets/23651539/25478514/f4094abc-2b73-11e7-9e04-134384cf6ef0.jpeg)

主题内的列表循环

![wechatimg39](https://cloud.githubusercontent.com/assets/23651539/25478528/fc18bcc4-2b73-11e7-97ec-9c42473fde1b.jpeg)

最终效果为什么是乱的，就是没按照文章的date进行倒序排序啊？还需要配置什么吗？官网关于主题的文档真心没多少。
![wechatimg41](https://cloud.githubusercontent.com/assets/23651539/25478533/04b1602a-2b74-11e7-8545-d64866b3e540.jpeg)

为什么不是最新的文章在最上边啊，难道还需要自己处理？那该怎么处理啊，用的ejs模板。

**Comment by NoahDragon** [comment]
不知道这个是不是和上个版本的一个PR有关#2262，修复将在下个版本中。

同时在生成网站时，最好先清理下cache `hexo clean && hexo g`。

**Comment by geekwill** [comment]
我在使用时，习惯性的会先hexo clean的，好像没用的
![wechatimg42](https://cloud.githubusercontent.com/assets/23651539/25512959/1cfee770-2c04-11e7-8c1c-dc5fe9eafa82.jpeg)
以上是我的hexo版本。
@NoahDragon

**Comment by NoahDragon** [comment]
我无法重现排序问题，可否分享下出问题的源代码？

**Comment by geekwill** [comment]
已解决，我重新init项目结构并重新构建主题目录，将其代码拷贝，可以解决，虽然我有改变主题的样式，但是文章列表的循环代码不变，自此我也没发现有什么书写错误的地方。源码https://github.com/geekwill/concise 在这里，你可查看我16年的commit记录，看可否重现排序问题。

**Comment by NoahDragon** [comment]
@geekwill 好的，这个issue先关闭了，如果还有问题可重开。
