### ISSUE TITLE
excerpt and more cam differ from content

### ISSUE THREAD

**Issue by sy1vain** [hexojs/hexo#2538]
The contents of the `excerpt` and `more` can differ from `content` on render.

This is caused by the `excerpt` filter being run too early.

Easiest reproducible example:
- create new hexo project
- `hero serve` and open served project
- all external links open in new tab
- add `<!--more-->` tag to hello-world.md
- refresh served project
- all external links **do not** open in new tab

`external_link` filter (and possible others) are run after the `except` filter and only change the `content` and not the `excerpt` and `more`. So the content gets modified after the split.

hexo: 3.3.1
hexo-cli: 1.0.2
node: 6.10.0

**Comment by NoahDragon** [comment]
I have verified and reproduced this issue. I think simply swap the order of `external_link` and `except` could fix it.

**Comment by NoahDragon** [comment]
I have created a PR to fix this #2539

**Comment by NoahDragon** [comment]
The fix will merge into next build. Thanks for submitting the issue. 😄

**Comment by sy1vain** [comment]
But if you add a custom filter (say, in a theme) what is the order it is processed? Is it then still the last step? Shouldn't the default be to have it execute last. In that case we can give it a priority if `Number.MAX_SAFE_INTEGER`

**Comment by NoahDragon** [comment]
If you add a custom filter, the process order is hexo filters then custom filters. As the external_link is handled by hexo filters, so it should be fine if add custom filters.

**Comment by sy1vain** [comment]
Thanks for clearing that up!
