### ISSUE TITLE
hexo init时报错

### ISSUE THREAD

**Issue by lilopusic** [hexojs/hexo#2540]
执行完npm install -g hexo-cli之后，进入新建的文件夹（路径为E:\blog），执行hexo init,报错如下（）：
ERROR Local hexo not found in E:\
ERROR Try running: 'npm install hexo --save'

**Comment by NoahDragon** [comment]
如果你的Hexo版本是3.3.1，这个issue已经在https://github.com/hexojs/hexo/pull/2520 修复了。

`hexo init`可以用 `npm install` 代替。

**Comment by NoahDragon** [comment]
Hexo已更新到3.3.5，请查看此问题是否还存在。

**Comment by NoahDragon** [comment]
这个问题还在，请使用`hexo init <folder name>`作为替代。

**Comment by NoahDragon** [comment]
是否在E:下有package.json和node_modules？如果有请删除后再在E:\blog下运行`hexo init`

**Comment by lilopusic** [comment]
确实是这样，删除之后成功了,我之前都没看到。。谢谢:-)

**Comment by Crazier-qi** [comment]
hexo init后遇到问题
![image](https://user-images.githubusercontent.com/16120478/28489537-c6abb024-6ef7-11e7-9257-da9dbeb67f27.png)

**Comment by lilopusic** [comment]
这个问题和我的问题不一样，而且这是已经关闭了的issue，你可以新开一个问题。
另外从图片上看是你访问GitHub出了问题，而不是hexo的问题。 @Crazier-qi

**Comment by linzhenq** [comment]
@Crazier-qi我也遇到你这样的问题，请问你是如何解决的

**Comment by Crazier-qi** [comment]
我是因为git配置了多账户，.ssh目录下的config文件出错，因此连接github出错，你可以先运行 ssh git
@github.com看看你的github和是否可以正常访问，如果可以的话再确认下git clone用的是https协议还是ssh协议。应该就没问题了。

**Comment by NHTcoding** [comment]
hexo init时报错，如下：
```
hutaodeMacBook-Pro:MyFiles hutao$ hexo init WeBlogs
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
fatal: 'git@github.com/hexojs/hexo-starter.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
WARN  git clone failed. Copying data instead
FATAL {
  err: [Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/hexo-cli/assets'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'scandir',
    path: '/usr/local/lib/node_modules/hexo-cli/assets'
  }
} Something's wrong. Maybe you can find the solution here: %s http://hexo.io/docs/troubleshooting.html
```

hexo的版本是4.2.0。git可以正常连接github.com。求问这是个什么问题。

**Comment by NHTcoding** [comment]
hexo init时报错，如下：
```
hutaodeMacBook-Pro:MyFiles hutao$ hexo init WeBlogs
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
fatal: 'git@github.com/hexojs/hexo-starter.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
WARN  git clone failed. Copying data instead
FATAL {
  err: [Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/hexo-cli/assets'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'scandir',
    path: '/usr/local/lib/node_modules/hexo-cli/assets'
  }
} Something's wrong. Maybe you can find the solution here: %s http://hexo.io/docs/troubleshooting.html
```

hexo的版本是4.2.0。git可以正常连接github.com。求问这是个什么问题。

**Comment by wuke1234** [comment]
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Unknown error

WARN  git clone failed. Copying data instead
FATAL {
  err: [Error: EPERM: operation not permitted, mkdir 'D:\'] {
    errno: -4048,
    code: 'EPERM',
    syscall: 'mkdir',
    path: 'D:\\'
  }
} Something's wrong. Maybe you can find the solution here: %s http://hexo.io/docs/troubleshooting.html
