### ISSUE TITLE
使用回车换行，那如何写长段落呢？一个几百字的长段落写在一行也不利于维护吧 ！

### ISSUE THREAD

**Issue by twesix** [hexojs/hexo#2541]
## Environment Info

Node version(`node -v`):
v7.7.1

Your site `_config.yml` (Optional):
```
marked:
  gfm: true
  breaks: false
```

hexo默认开启了gfm，那么如果我有些段落非常长，需要放到不止一行来方便维护的话，就必须关闭
gfm的回车作为换行的功能，但是现在关不掉啊。我已经在站点的配置文件_config.yml中加上了相应的

```
marked:
  gfm: true
  breaks: false
```

但是没有用

**Comment by NoahDragon** [comment]
我的没有这个问题，请确认是否使用的是默认的markdown renderer。
