### ISSUE TITLE
The logic of the tutorial is not clear

### ISSUE THREAD

**Issue by yakiler** [hexojs/hexo#2544]
I think your tutorial is more like an API,Because it does not guide me to step by step to complete a normal blog。It always skips some important content, which makes me feel no connection before and after。Unfortunately, I have not been able to complete a correct blog。Hope you have the opportunity to see and give me a help。Thank you! If it is Chinese tutorial better。

**Comment by NoahDragon** [comment]
There are several Chinese tutorials, simply Baidu or Google it will retrieve a bunch of. Here is a list I know:
https://hexo.io/zh-cn/docs/
https://segmentfault.com/p/1210000008725508/read
http://www.jianshu.com/p/465830080ea9?utm_campaign=maleskine&utm_content=note&utm_medium=reader_share&utm_source=weibo
