### ISSUE TITLE
kept saying Local hexo not found that should npm install hexo --save

### ISSUE THREAD

**Issue by Roron0a** [hexojs/hexo#2546]
## Environment Info
Ubutun VPS 

Node version(`node -v`):4.4.4

Hexo and Plugin version(`npm ls --depth 0`): 

hexo-site@0.0.0 /root/hexo
├── hexo@3.3.5
├── hexo-deployer-git@0.2.0
├── hexo-deployer-heroku@0.1.1
├── hexo-deployer-openshift@0.1.1
├── hexo-deployer-rsync@0.1.3
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.0

`hexo init` works but when I configured the `_config.yml` file and run `hexo d` or `hexo s` 
it gave me that 
`ERROR Local hexo not found in ~/hexo
ERROR Try running: 'npm install hexo --save'
`

I have searched all over the net and none of the solutions worked for me 

it works on my LOCAL server but not my VPS 

any help ?

**Comment by NoahDragon** [comment]
Could you please check if there is `package.json` under `~` folder?

**Comment by Roron0a** [comment]
@NoahDragon then it throws not have `server` nor `generate` command 
```
hexo d
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```
any thought?

**Comment by NoahDragon** [comment]
That's caused by the package dependencies are missing. I try to reproduce the scenario, but failed. Did you run the `hexo init` under `~` directory?

**Comment by Roron0a** [comment]
@NoahDragon yes I run it many times but just not working in VPS but working properly on my computer .

**Comment by NoahDragon** [comment]
I'm not sure if running the `hexo init` under `~` is the problem. What I usually did is created a specific folder then run the `hexo init` inside it. I don't have *nix OS right now, so couldn't test the case.

However, under Windows, there is a similar issue #2540 , which run `hexo init` under `E:\`. It causes the same issue.

**Comment by Roron0a** [comment]
@NoahDragon I created another folder under `~` but still not working
never mind It works on my computer and I have set up a personal blog with github pages 
that's all I want 
thanks for helping .

**Comment by wmira** [comment]
I just had this issue on Digital ocean. The init does not complete and hexo isnt not installed on the folder. You need to add a swap: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
