### ISSUE TITLE
hexo d命令后,没有报错,但是GitHub发来邮件提示Page build failure,博客页面也没有更新

### ISSUE THREAD

**Issue by MrLrf** [hexojs/hexo#2548]
## Environment Info

Node version(`node -v`):v4.4.3

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

我的hexo的源文件更新在同一个项目的source分支下,长时间没有使用hexo之后,突然写了一篇,在部署的时候没有提示错误,但是GitHub发来这样一封邮件,然后博客的文章也没有更新.
![](http://i.imgur.com/e5lFlDt.jpg)

**Comment by NoahDragon** [comment]
就如邮件中所说，将`.deploy_git` submodule 从deploy branch里删除即可。

**Comment by MrLrf** [comment]
@NoahDragon 我删除了使用hexo g命令之后他就又出来了啊,然后hexo d还是不行

**Comment by NoahDragon** [comment]
请将`.deploy_git`添加到.gitignore 文件中，这样git add/push都不会添加它
