### ISSUE TITLE
hexo deploy 报错 

### ISSUE THREAD

**Issue by ToSeven** [hexojs/hexo#2549]
![1](https://cloud.githubusercontent.com/assets/14891443/25659246/717b3acc-3039-11e7-923a-7824832ccfa6.PNG)
![2](https://cloud.githubusercontent.com/assets/14891443/25659253/7acb2178-3039-11e7-97c7-02b86dc560d8.PNG)
![4](https://cloud.githubusercontent.com/assets/14891443/25659258/7ed02520-3039-11e7-872f-9859be90e19f.PNG)
输入hexo 命令后报错如下
![5](https://cloud.githubusercontent.com/assets/14891443/25659261/80ba0acc-3039-11e7-8893-bc577b717db5.PNG)
改用git bash 也不行 求解！

**Comment by NoahDragon** [comment]
git repo url换成https://github.com/ToSeven/ToSeven.github.io.git 试试？

**Comment by ToSeven** [comment]
试过都不行 配置过ssh并且测试连接成功了 但还是报错

**Comment by NoahDragon** [comment]
换成https报什么错误呢？

**Comment by ToSeven** [comment]
![23](https://cloud.githubusercontent.com/assets/14891443/25777830/e6d6b4c8-331c-11e7-8547-46906d65be48.PNG)
![9](https://cloud.githubusercontent.com/assets/14891443/25777831/ee62f9ae-331c-11e7-8d0d-5409387b6fb5.PNG)
最后实在不行我用 git push 提交的文件。。。。。

**Comment by NoahDragon** [comment]
http://stackoverflow.com/questions/6565357/git-push-requires-username-and-password 

``` bash
git remote set-url origin git@github.com:username/repo.git
```

是否可以解决？

**Comment by ToSeven** [comment]
还是不行啊 ssh测试也连接得上但就是不行 我怀疑是不是在第一次hexo d时用的以前的ssh私钥 然后后来我把它删了 重新建立个新的ssh
![45](https://cloud.githubusercontent.com/assets/14891443/25837576/13c7abe0-34c1-11e7-9ea6-b3e135d74912.PNG)
![90](https://cloud.githubusercontent.com/assets/14891443/25837587/1d62047a-34c1-11e7-83a5-0e5dcd469e60.PNG)
![70](https://cloud.githubusercontent.com/assets/14891443/25837600/29744b92-34c1-11e7-8f3d-db3217247112.PNG)
![24](https://cloud.githubusercontent.com/assets/14891443/25837603/2c3b558c-34c1-11e7-811e-0cffbc6d2b67.PNG)

**Comment by loatheb** [comment]
1. 先删除本地的 `.git` 文件夹，然后 `hexo d` 试一下
2. 如果不行，删除 `.deploy_git` ，然后重新 `hexo d`

**Comment by NoahDragon** [comment]
可否设置ssh不用passphrase的？git-deployer目前不支持用户输入的。

**Comment by ToSeven** [comment]
@NoahDragon 那为什么我以前用https时输入用户名和密码时可以成功 然后我搜索了下别人说有可能我的git版本太高的原因 我都试试吧  即使没有弄好 但还是谢谢你一直帮我解答

**Comment by ToSeven** [comment]
@lebarde  不行啊

**Comment by lebarde** [comment]
? Sorry I don't speak asian languages!

**Comment by WuJonah** [comment]
我之前也是这样，后来把私钥删除了重新生成一个就可以用了。 你可以试试。
