### ISSUE TITLE
Themes Page 404 Error

### ISSUE THREAD

**Issue by Doug-Luce** [hexojs/hexo#2550]
## For BUG

 1. The link to http://hexo.io/themes/ is giving a 404 error. 
 2. Visit the address at https://hexo.io/themes/ to reproduce this error.

**Comment by NoahDragon** [comment]
Thanks for the feedback. I will take a look at it.

**Comment by Doug-Luce** [comment]
No problem.

**Comment by NoahDragon** [comment]
The YMAL format is wrong. The issue should resolve in a few mins after CI runs.
