### ISSUE TITLE
init fail

### ISSUE THREAD

**Issue by holyen** [hexojs/hexo#2552]
## Environment Info

Node version(`node -v`):
v6.10.1
Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question
npm install in centos 7

## For feature request

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by holyen** [comment]
hexo server

ERROR Local hexo not found in ~/blog
ERROR Try running: 'npm install hexo --save'

**Comment by NoahDragon** [comment]
Is your issue similar to https://github.com/hexojs/hexo/issues/2546 ?

**Comment by wmira** [comment]
this has happened to me and this is because the init process did not complete. I added swap on my digital ocean droplet and that solved the issue:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
