### ISSUE TITLE
Translating homepage

### ISSUE THREAD

**Issue by lucapel** [hexojs/hexo#2554]

**Comment by NoahDragon** [comment]
Please add more details about the issue.

**Comment by lucapel** [comment]
See more details above.

**Comment by NoahDragon** [comment]
The question is a bit broad. I think an example is a good tutorial. You could pick one on the hexo plugins page (https://hexo.io/plugins/) as an sample, and start from there.

**Comment by lucapel** [comment]
If I'm not mistaking, if I act like you said I need to build a plugin separated from my site, publish it on npm and isntall it as I do with other plugins via npm install. That could be fine, I'll have a look.

But my question was not intending to be broad: I need to have some JS functions available to all layouts, where can I place them? I need to be able to call them within my theme layouts. Where can I put them? Is there a way other than building a plugin?

**Comment by NoahDragon** [comment]
Here is an example if you would like to extend Hexo locally. https://github.com/hexojs/site/tree/master/scripts

Create the `scripts` folder and you could start from there.

**Comment by lucapel** [comment]
That's exactly what I was looking for, thanks man.
