### ISSUE TITLE
Hexo doesn't generate my Google Analytics tag

### ISSUE THREAD

**Issue by KaitoKid** [hexojs/hexo#2555]
I added the tag for GAnalytics in my **theme's** `config.yml`
```yml
# Google Analytics Tracking ID
google_analytics: UA-myactualid
```

I have `google-analytics.ejs` located under `/layout/_partial` in my theme
```javascript
<% if (theme.google_analytics){ %>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '<%= theme.google_analytics %>', 'auto');
        ga('send', 'pageview');
    </script>
<% } %>
```

In my `head.ejs` I added the following lines:
```yml
  <!-- Google Analytics -->
  <% partial('google-analytics') %>
```

After running `hexo clean` and `hexo generate --debug` I can see the line 
```yml
Processed: layout/_partial/google-analytics.ejs
```

---
I can see the `<!-- Google Analytics -->` part in my website's HTML, but the GAnalytics block is missing.

In the mean time, I changed `if (theme.google_analytics)` to `if (true)` and hardcoded the tag in.

**Comment by NoahDragon** [comment]
Have you tried ` <% partial('_partial/google-analytics') %>`

**Comment by Band-Aid** [comment]
I know this is an old case but I ran in to the same issue. Just in case anyone else runs in to this, the fix was to add a '-' right after %

`<% partial('_partial/google-analytics') %>`

`<%- partial('_partial/google-analytics') %>`
