### ISSUE TITLE
How to println all category

### ISSUE THREAD

**Issue by anxiaoyi** [hexojs/hexo#2559]
Both

```xml
<% site.categories.forEach(function(category) { %>
    <%- category %>
<% }); %>
```

and

```xml
<% site.categories.forEach(function(category) { %>
    <%= category %>
<% }); %>
```

are not correct. 

And what's the type of `site`, what's the type of `site.categories`, where can i find the **avaliable API documentation** for the `site.categories` object, why the  official wesite doesn't give anything information about these questions ?

**Comment by NoahDragon** [comment]
Please view the usage in the indigo theme https://github.com/yscoder/hexo-theme-indigo/blob/card/layout/categories.ejs
