### ISSUE TITLE
External theme

### ISSUE THREAD

**Issue by popomore** [hexojs/hexo#2560]
## Environment Info

Node version(`node -v`): 6.x

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

hexo: 3.3.5

## For feature request

I'm writing a doctools wrapping hexo, I want to put the theme in this tools rather than the doc itself. so the theme path is not with prefix base_dir, but I found most model like [assets](https://github.com/hexojs/hexo/blob/master/lib/models/asset.js#L15)  joined base_dir, and the source will not be found when generate.

Do you have any solution to support it?

**Comment by NoahDragon** [comment]
I don't think we may support this in the near future.
