### ISSUE TITLE
删除全部文章后,执行部署, 终端输出其中一句:delete mode 100644 index.html

### ISSUE THREAD

**Issue by Gaozn** [hexojs/hexo#2561]
RT,求指教.没有文章,不能空白显示吗?

**Comment by NoahDragon** [comment]
可否尝试下此解决方案?  http://stackoverflow.com/questions/10100296/git-commit-deleting-all-files-in-repo

由于这个问题是git deployer的，不应发在Hexo板块下，暂时先关闭。
