### ISSUE TITLE
ubuntu linux npm install -g hexo-cli error

### ISSUE THREAD

**Issue by hahadaxia** [hexojs/hexo#2564]
## Environment Info
npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "hexo-cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zzh/npm-debug.log

## For BUG
now use sudo the bug is
npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

## For question
my ubuntu lts version is 16.04 ，not server version

**Comment by loatheb** [comment]
@hahadaxia I think it's reason about something error with you NPM command permission.checking this page may help you.[https://docs.npmjs.com/troubleshooting/common-errors](https://docs.npmjs.com/troubleshooting/common-errors)
