### ISSUE TITLE
老大 请问一下主页的图片到其他页面显示不了怎么办

### ISSUE THREAD

**Issue by zhoujinhai** [hexojs/hexo#2566]
主页的图片放在主题的source文件下  ``<img` src="img/logo.png">`

**Comment by NoahDragon** [comment]
请问你是讲logo.png放在了theme的source文件夹下还是source/img文件夹下？

**Comment by zhoujinhai** [comment]
放在source/img文件夹下





发自OPPO邮件客户端在 Abner Chou <notifications@github.com>，2017年5月15日 22:52写道：请问你是讲logo.png放在了theme的source文件夹下还是source/img文件夹下？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hexojs/hexo","title":"hexojs/hexo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hexojs/hexo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NoahDragon in #2566: 请问你是讲logo.png放在了theme的source文件夹下还是source/img文件夹下？"}],"action":{"name":"View Issue","url":"https://github.com/hexojs/hexo/issues/2566#issuecomment-301499474"}}}

**Comment by zhoujinhai** [comment]
是主题下的source/img文件





发自OPPO邮件客户端在 Abner Chou <notifications@github.com>，2017年5月15日 22:52写道：请问你是讲logo.png放在了theme的source文件夹下还是source/img文件夹下？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hexojs/hexo","title":"hexojs/hexo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hexojs/hexo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NoahDragon in #2566: 请问你是讲logo.png放在了theme的source文件夹下还是source/img文件夹下？"}],"action":{"name":"View Issue","url":"https://github.com/hexojs/hexo/issues/2566#issuecomment-301499474"}}}

**Comment by NoahDragon** [comment]
能否将问题代码放在一个公开的repo中， 方便重现试验？

**Comment by zhoujinhai** [comment]
https://github.com/zhoujinhai/test

**Comment by NoahDragon** [comment]
刚测试了，没有任何问题，logo.png被放在了public/img下。

**Comment by zhoujinhai** [comment]
但是只能到主页显示 Android 和help页显示不了

**Comment by NoahDragon** [comment]
logo的url不能hard code，因为不同层级的页面访问img的路径不同。
比如 Public目录下访问logo.png，可以通过`img/logo.png`；但Public/help目录下的文件，则需要向上一级`../img/logo.png`。

建议将logo的路径放入theme的_config文件，然后在layout中，使用url-for(theme.logo)来获取正确的相对路径。

**Comment by zhoujinhai** [comment]
好的 谢谢
