### ISSUE TITLE
run hexo module.js:472 

### ISSUE THREAD

**Issue by kinzun** [hexojs/hexo#2569]
## Environment Info

Node version(`node -v`):
7.10.0

Hexo and Plugin version(`npm ls --depth 0`): 

windows cmd exct
``` shell 
PS D:\> hexo -v
hexo-cli: 1.0.2
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.7.0
node: 7.10.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

## For BUG

system ：windows 
git install path : D:\Program Files\Git
nodejs install path: D:\Program Files\nodejs\node_global

Git-bash.exe environment is running

``` shell $ hexo
module.js:472
    throw err;
    ^

Error: Cannot find module 'D:\Program Files\Git\node_modules\hexo-cli\bin\hexo'
```

## For question

but
windows cmd ：run hexo 
ok

``` shell 
which hexo 
/d/Program Files/nodejs/node_global/hexo
```

hexo.cmd 
``` shell
## # @IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\hexo-cli\bin\hexo" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\hexo-cli\bin\hexo" %*
)
```
## For feature request

``` shell 
cp D:\Program Files\nodejs\node_global\node_modules D:\Program Files\Git
```
Back to normal

but
Is this the best solution?
Thank y

**Comment by NoahDragon** [comment]
I think it is something related to npm global installation path. `npm config get prefix` will show it. You also could uninstall the Hexo and reinstall it should fix the issue.
