### ISSUE TITLE
Branch master set up to track remote branch master from 

### ISSUE THREAD

**Issue by mcfly001** [hexojs/hexo#2570]
## Environment Info

Node version(`node -v`): 6.10.2

Your theme `_config.yml` (Optional): spfk

Hexo and Plugin version(`npm ls --depth 0`): 1.0.2

## For BUG

![image](https://cloud.githubusercontent.com/assets/15622880/26146498/fb0eba68-3b22-11e7-9a26-eb9d590ea797.png)

**Comment by NoahDragon** [comment]
Could you please delete the `.deploy_git` folder and redeploy?

**Comment by mcfly001** [comment]
i have try it ,but it's also not work

**Comment by NoahDragon** [comment]
Could you please post the git deploy setting in config file?

**Comment by seaoak** [comment]
@mcfly001 Apparently from your screenshot and your GitHub repository, I think that you might set the repository "zyj-github.io" as your GitHub Pages source.

If it is true, you can change the "url:" field in your `_config.yml` as follows:

```
- url: git@github.com:mcfly001/zyj.github.io.git
---
+ url: git@github.com:mcfly001/zyj-github.io.git
```

Use a hyphen instead of a dot.

**Comment by seaoak** [comment]
Just for the record:

1. A log message "`Branch master set up to track remote branch master from REPO`" shows that a git operation (`git push -u REPO HEAD:master --force`) is successfully completed.  So `hexo -d` command is normally ended.

2. If you will change the name of destination repository and keep its history continuously, you can change the local git repository configuration as follows:

    ```bash
    $ cd .deploy_git
    $ git remote set-url origin git@github.com:USERNAME/NEW-REPO-NAME.git
    ```

    Because GitHub automatically redirects all access to new repository, no error occurs for access to old repository.  But some warning messages may be displayed such as in this case.  To avoid these warning messages, you can use above procedure.

**Comment by mcfly001** [comment]
all of this i have try ,but it's also not work,i will try change the repository

**Comment by NoahDragon** [comment]
@mcfly001 does this issue resolved?

**Comment by mcfly001** [comment]
yes  it's resolved ,but i don't know why

**Comment by NoahDragon** [comment]
@mcfly001 great. I will close this issue for now.
