### ISSUE TITLE
为什么我的博客首页显示的是归档内容，博客地址：icessun.github.io

### ISSUE THREAD

**Issue by icessun** [hexojs/hexo#2572]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by NoahDragon** [comment]
請問使用的何種主題？

**Comment by NoahDragon** [comment]
先Close，由於信息不全。

**Comment by icessun** [comment]
sorry ，是自己的问题，已经解决了

**Comment by NoahDragon** [comment]
@icessun 没事的，有任何问题都可以提issue
