### ISSUE TITLE
Hexo 3.3.6 generate error

### ISSUE THREAD

**Issue by SawyerSun** [hexojs/hexo#2574]
## Environment Info

Node version(`node -v`): v7.10.0

Your site `_config.yml` (Optional):
<img width="425" alt="1" src="https://cloud.githubusercontent.com/assets/13533065/26274337/3b68ea6c-3d7a-11e7-8081-e3981f2ff78e.png">

Your theme `_config.yml` (Optional):   
Next

Hexo and Plugin version(`npm ls --depth 0`): 
⇒  npm ls --depth 0
hexo-site@0.0.0 /Users/sp/oneDrive/blog
├── hexo@3.3.6
├── hexo-deployer-git@0.3.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-search@2.1.1
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.0
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.0
└── hexo-wordcount@2.0.1

npm ERR! invalid: hexo-generator-baidu-sitemap@0.0.8 /Users/sp/oneDrive/blog/node_modules/hexo-generator-baidu-sitemap/node_modules/hexo-generator-baidu-sitemap

## For BUG
Recently, I found some code in markdown get parse error, so i try to update hexo to 3.3.6 to fix it. However, after updating to 3.3.6, I got this error for `hexo g`:
<img width="834" alt="2" src="https://cloud.githubusercontent.com/assets/13533065/26274369/f5582e88-3d7a-11e7-98a8-6eff57ce2288.png">

So, I wonder what is this error?

**Comment by NoahDragon** [comment]
This may relate to #2573, we are investigating it. Please lock Hexo version to 3.2.2 or 3.3.1.

**Comment by Introspelliam** [comment]
I'm sorry to ignore your emails! I don't known why it happened. So I give you the _config.yml. Please help me to solve the problem!
     Thank you!



Inspelliam@163.com
 
From: Abner Chou
Date: 2017-05-21 10:27
To: hexojs/hexo
CC: Subscribed
Subject: Re: [hexojs/hexo] Hexo 3.3.6 generate error (#2574)
This may relate to #2573, we are investigating it. Please lock Hexo version to 3.2.2 or 3.3.1.

**Comment by SawyerSun** [comment]
@NoahDragon followed your  suggestion, I try to lock Hexo version to 3.2.2 or 3.3.1, but the same error occurs again. Only in 3.3.5 version, it can generate files correctly but with code parse error related to #2575.

**Comment by NoahDragon** [comment]
@SawyerSun Thanks for the feedback. Let me take a look.

**Comment by 502647092** [comment]
@NoahDragon 
I look nearest commits and commented on the following code
Then it can run
File: `node_modules\hexo\lib\extend\tag.js`
```
  function escapeContent(str, p1, p2, p3) {
    //assert(!p1 === !p3, '<pre> tag should be coupled: "' + p1 + '" <=> "' + p3 + '"');
    //assert(!rTagCode.test(p2), '<code> tag should not be nested');
    //assert(!rTagPre.test(p2), '<pre> tag should not be nested');
    return '<!--' + placeholder + (cache.push(str) - 1) + '-->';
  }
```

**Comment by NoahDragon** [comment]
@502647092 Yes, this is an issue introduced by latest change. We still investigate and try to find out the best solution.

**Comment by NoahDragon** [comment]
Please get the latest version 3.3.7, and have a try.

**Comment by SawyerSun** [comment]
@NoahDragon I had tried the latest version 3.3.7, but it produced generating error again: template render error:(unknown path) unexpected end of file.

**Comment by NoahDragon** [comment]
@SawyerSun Can you post the full trace? I didn't get such error message.

**Comment by SawyerSun** [comment]
@NoahDragon here are full error message, hope it helps.

sp@spdeMacBook-Pro:~/oneDrive/blog|hexo⚡
⇒  hexo version
hexo: 3.3.7
hexo-cli: 1.0.2
os: Darwin 16.6.0 darwin x64
http_parser: 2.7.0
node: 7.10.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
sp@spdeMacBook-Pro:~/oneDrive/blog|hexo⚡
⇒  hexo g --debug
08:02:42.414 DEBUG Hexo version: 3.3.7
08:02:42.417 DEBUG Working directory: ~/oneDrive/blog/
08:02:42.502 DEBUG Config loaded: ~/oneDrive/blog/_config.yml
08:02:42.567 DEBUG Plugin loaded: hexo-deployer-git
08:02:42.570 DEBUG Plugin loaded: hexo-generator-archive
08:02:42.576 DEBUG Plugin loaded: hexo-generator-baidu-sitemap
08:02:42.578 DEBUG Plugin loaded: hexo-generator-category
08:02:42.582 DEBUG Plugin loaded: hexo-generator-feed
08:02:42.584 DEBUG Plugin loaded: hexo-generator-search
08:02:42.585 DEBUG Plugin loaded: hexo-generator-index
08:02:42.589 DEBUG Plugin loaded: hexo-generator-sitemap
08:02:42.591 DEBUG Plugin loaded: hexo-generator-tag
08:02:42.599 DEBUG Plugin loaded: hexo-renderer-ejs
08:02:42.605 DEBUG Plugin loaded: hexo-renderer-marked
08:02:42.607 DEBUG Plugin loaded: hexo-renderer-stylus
08:02:42.681 DEBUG Plugin loaded: hexo-server
08:02:42.739 DEBUG Plugin loaded: hexo-wordcount
08:02:42.745 DEBUG Script loaded: themes/next/scripts/merge-configs.js
08:02:42.750 DEBUG Script loaded: themes/next/scripts/merge.js
08:02:42.750 DEBUG Script loaded: themes/next/scripts/tags/button.js
08:02:42.751 DEBUG Script loaded: themes/next/scripts/tags/center-quote.js
08:02:42.751 DEBUG Script loaded: themes/next/scripts/tags/exturl.js
08:02:42.752 DEBUG Script loaded: themes/next/scripts/tags/full-image.js
08:02:42.753 DEBUG Script loaded: themes/next/scripts/tags/group-pictures.js
08:02:42.753 DEBUG Script loaded: themes/next/scripts/tags/note.js
08:02:42.756 DEBUG Loading database.
08:02:42.765 INFO  Start processing
08:02:42.829 DEBUG Processed: CNAME
08:02:42.830 DEBUG Processed: favicon.ico
08:02:42.920 DEBUG Processed: images/avatar.jpg
08:02:42.959 DEBUG Processed: images/alipay-reward-image.jpg
08:02:42.959 DEBUG Processed: images/wechat-reward-image.jpg
08:02:42.999 DEBUG Theme config loaded.
08:02:43.001 DEBUG Processed: 404.html
08:02:43.001 DEBUG Processed: _config.yml
08:02:43.002 DEBUG Processed: images/MultiDataSource/result1.png
08:02:43.002 DEBUG Processed: images/MultiDataSource/result2.png
08:02:43.003 DEBUG Processed: images/princeton-algorithms/Percolation1.jpg
08:02:43.004 DEBUG Processed: images/princeton-algorithms/Percolation2.jpg
08:02:43.005 DEBUG Processed: images/princeton-algorithms/Percolation3.jpg
08:02:43.005 DEBUG Processed: images/princeton-algorithms/StackQueue.jpg
08:02:43.019 DEBUG Processed: source/css/main.styl
08:02:43.020 DEBUG Processed: source/images/algolia_logo.svg
08:02:43.020 DEBUG Processed: source/images/avatar.gif
08:02:43.020 DEBUG Processed: source/images/cc-by-nc-nd.svg
08:02:43.021 DEBUG Processed: source/images/cc-by-nc-sa.svg
08:02:43.022 DEBUG Processed: source/images/cc-by-nc.svg
08:02:43.022 DEBUG Processed: source/images/cc-by-nd.svg
08:02:43.022 DEBUG Processed: source/images/cc-by-sa.svg
08:02:43.023 DEBUG Processed: source/images/cc-by.svg
08:02:43.023 DEBUG Processed: source/images/cc-zero.svg
08:02:43.023 DEBUG Processed: source/images/loading.gif
08:02:43.023 DEBUG Processed: source/images/placeholder.gif
08:02:43.025 DEBUG Processed: source/images/quote-l.svg
08:02:43.026 DEBUG Processed: source/images/quote-r.svg
08:02:43.026 DEBUG Processed: source/images/searchicon.png
08:02:43.275 DEBUG Processed: layout/.DS_Store
08:02:43.275 DEBUG Processed: layout/_layout.swig
08:02:43.275 DEBUG Processed: layout/archive.swig
08:02:43.276 DEBUG Processed: layout/category.swig
08:02:43.276 DEBUG Processed: layout/index.swig
08:02:43.276 DEBUG Processed: layout/page.swig
08:02:43.276 DEBUG Processed: layout/post.swig
08:02:43.276 DEBUG Processed: layout/schedule.swig
08:02:43.277 DEBUG Processed: layout/tag.swig
08:02:43.298 DEBUG Processed: about/index.md
08:02:43.304 DEBUG Processed: languages/de.yml
08:02:43.304 DEBUG Processed: languages/default.yml
08:02:43.304 DEBUG Processed: languages/en.yml
08:02:43.304 DEBUG Processed: languages/fr-FR.yml
08:02:43.304 DEBUG Processed: languages/id.yml
08:02:43.304 DEBUG Processed: languages/ja.yml
08:02:43.305 DEBUG Processed: languages/ko.yml
08:02:43.305 DEBUG Processed: languages/pt-BR.yml
08:02:43.305 DEBUG Processed: languages/pt.yml
08:02:43.305 DEBUG Processed: languages/ru.yml
08:02:43.305 DEBUG Processed: languages/zh-Hans.yml
08:02:43.305 DEBUG Processed: languages/zh-hk.yml
08:02:43.305 DEBUG Processed: languages/zh-tw.yml
08:02:43.306 DEBUG Processed: categories/index.md
08:02:43.308 DEBUG Processed: resume/index.md
08:02:43.310 DEBUG Processed: tags/index.md
08:02:43.329 DEBUG Processed: _posts/Autowired-Resource-Inject.md
08:02:43.364 DEBUG Processed: _posts/Hibernate-mapping-enums.md
08:02:43.371 DEBUG Processed: _posts/Spring-Multiple-Datasource.md
08:02:43.372 DEBUG Processed: _posts/IDEA-LanguageLevel.md
08:02:43.375 DEBUG Processed: _posts/Java-synchronized.md
08:02:43.389 DEBUG Processed: _posts/JavaScript-The-Good-Parts.md
08:02:43.394 DEBUG Processed: _posts/Jquery-noConflict.md
08:02:43.402 DEBUG Processed: _posts/Locality-Sensitive-Hashing.md
08:02:43.404 DEBUG Processed: _posts/Lombok.md
08:02:43.408 DEBUG Processed: _posts/Maven-pom.md
08:02:43.410 DEBUG Processed: _posts/Median-of-Two-Sorted-Arrays.md
08:02:43.414 DEBUG Processed: _posts/Observer-Pattern.md
08:02:43.416 DEBUG Processed: _posts/Princeton-Algorithms-Assigment1.md
08:02:43.417 DEBUG Processed: _posts/Regular-Expression-Matching.md
08:02:43.421 DEBUG Processed: _posts/SLF4J.md
08:02:43.422 DEBUG Processed: _posts/Singleton-pattern.md
08:02:43.424 DEBUG Processed: _posts/Thymeleaf-2-xml-error.md
08:02:43.426 DEBUG Processed: _posts/Using-git-branch-manage-hexo-blog.md
08:02:43.429 DEBUG Processed: source/js/src/affix.js
08:02:43.429 DEBUG Processed: source/js/src/algolia-search.js
08:02:43.430 DEBUG Processed: source/js/src/bootstrap.js
08:02:43.430 DEBUG Processed: source/js/src/exturl.js
08:02:43.430 DEBUG Processed: source/js/src/hook-duoshuo.js
08:02:43.430 DEBUG Processed: source/js/src/js.cookie.js
08:02:43.430 DEBUG Processed: source/js/src/motion.js
08:02:43.431 DEBUG Processed: source/js/src/post-details.js
08:02:43.431 DEBUG Processed: source/js/src/scroll-cookie.js
08:02:43.431 DEBUG Processed: source/js/src/scrollspy.js
08:02:43.431 DEBUG Processed: source/js/src/utils.js
08:02:43.431 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.css
08:02:43.432 DEBUG Processed: source/lib/canvas-nest/canvas-nest.min.js
08:02:43.432 DEBUG Processed: source/lib/canvas-ribbon/canvas-ribbon.js
08:02:43.432 DEBUG Processed: source/lib/fastclick/LICENSE
08:02:43.433 DEBUG Processed: source/lib/fastclick/README.md
08:02:43.433 DEBUG Processed: source/lib/fastclick/bower.json
08:02:43.434 DEBUG Processed: source/lib/font-awesome/HELP-US-OUT.txt
08:02:43.434 DEBUG Processed: source/lib/font-awesome/bower.json
08:02:43.436 DEBUG Processed: source/lib/jquery_lazyload/CONTRIBUTING.md
08:02:43.436 DEBUG Processed: source/lib/jquery_lazyload/README.md
08:02:43.436 DEBUG Processed: source/lib/jquery_lazyload/bower.json
08:02:43.436 DEBUG Processed: source/lib/jquery_lazyload/jquery.lazyload.js
08:02:43.437 DEBUG Processed: source/lib/jquery_lazyload/jquery.scrollstop.js
08:02:43.437 DEBUG Processed: source/lib/three/canvas_lines.min.js
08:02:43.437 DEBUG Processed: source/lib/three/canvas_sphere.min.js
08:02:43.437 DEBUG Processed: source/lib/three/three-waves.min.js
08:02:43.438 DEBUG Processed: source/lib/velocity/bower.json
08:02:43.438 DEBUG Processed: source/lib/velocity/velocity.min.js
08:02:43.438 DEBUG Processed: source/lib/velocity/velocity.ui.js
08:02:43.438 DEBUG Processed: source/lib/velocity/velocity.ui.min.js
08:02:43.471 DEBUG Processed: source/lib/jquery/index.js
08:02:43.556 DEBUG Processed: layout/_custom/header.swig
08:02:43.556 DEBUG Processed: layout/_custom/sidebar.swig
08:02:43.556 DEBUG Processed: layout/_macro/post-collapse.swig
08:02:43.556 DEBUG Processed: layout/_macro/post-copyright.swig
08:02:43.556 DEBUG Processed: layout/_macro/post.swig
08:02:43.556 DEBUG Processed: layout/_macro/reward.swig
08:02:43.556 DEBUG Processed: layout/_macro/sidebar.swig
08:02:43.556 DEBUG Processed: layout/_macro/wechat-subscriber.swig
08:02:43.556 DEBUG Processed: layout/_partials/comments.swig
08:02:43.556 DEBUG Processed: layout/_partials/footer.swig
08:02:43.556 DEBUG Processed: layout/_partials/head.swig
08:02:43.556 DEBUG Processed: layout/_partials/header.swig
08:02:43.556 DEBUG Processed: layout/_partials/page-header.swig
08:02:43.556 DEBUG Processed: layout/_partials/pagination.swig
08:02:43.556 DEBUG Processed: layout/_partials/search.swig
08:02:43.557 DEBUG Processed: layout/_scripts/.DS_Store
08:02:43.557 DEBUG Processed: layout/_scripts/boostrap.swig
08:02:43.557 DEBUG Processed: layout/_scripts/commons.swig
08:02:43.557 DEBUG Processed: layout/_scripts/vendors.swig
08:02:43.557 DEBUG Processed: layout/_third-party/duoshuo-hot-articles.swig
08:02:43.557 DEBUG Processed: layout/_third-party/exturl.swig
08:02:43.557 DEBUG Processed: layout/_third-party/mathjax.swig
08:02:43.557 DEBUG Processed: layout/_third-party/schedule.swig
08:02:43.557 DEBUG Processed: layout/_third-party/scroll-cookie.swig
08:02:43.561 DEBUG Processed: source/js/src/schemes/pisces.js
08:02:43.563 DEBUG Processed: source/lib/Han/dist/han.min.css
08:02:43.563 DEBUG Processed: source/lib/Han/dist/han.min.js
08:02:43.564 DEBUG Processed: source/lib/fancybox/source/blank.gif
08:02:43.564 DEBUG Processed: source/lib/fancybox/source/fancybox_loading.gif
08:02:43.564 DEBUG Processed: source/lib/fancybox/source/fancybox_loading@2x.gif
08:02:43.565 DEBUG Processed: source/lib/fancybox/source/fancybox_overlay.png
08:02:43.565 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite.png
08:02:43.565 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite@2x.png
08:02:43.565 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.css
08:02:43.566 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.js
08:02:43.566 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.pack.js
08:02:43.566 DEBUG Processed: source/lib/fastclick/lib/fastclick.js
08:02:43.567 DEBUG Processed: source/lib/fastclick/lib/fastclick.min.js
08:02:43.567 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css
08:02:43.567 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css.map
08:02:43.568 DEBUG Processed: source/lib/font-awesome/css/font-awesome.min.css
08:02:43.568 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.min.js
08:02:43.568 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.pack.js
08:02:43.574 DEBUG Processed: layout/_scripts/schemes/muse.swig
08:02:43.574 DEBUG Processed: layout/_scripts/schemes/mist.swig
08:02:43.575 DEBUG Processed: source/lib/Han/dist/han.css
08:02:43.575 DEBUG Processed: source/lib/Han/dist/han.js
08:02:43.575 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff
08:02:43.575 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff2
08:02:43.575 DEBUG Processed: source/lib/velocity/velocity.js
08:02:43.607 DEBUG Processed: layout/_partials/head/custom-head.swig
08:02:43.607 DEBUG Processed: layout/_partials/head/external-fonts.swig
08:02:43.607 DEBUG Processed: layout/_partials/search/localsearch.swig
08:02:43.608 DEBUG Processed: layout/_partials/search/tinysou.swig
08:02:43.608 DEBUG Processed: layout/_partials/search/swiftype.swig
08:02:43.608 DEBUG Processed: layout/_partials/share/add-this.swig
08:02:43.608 DEBUG Processed: layout/_partials/share/baidushare.swig
08:02:43.608 DEBUG Processed: layout/_partials/share/duoshuo_share.swig
08:02:43.608 DEBUG Processed: layout/_partials/share/jiathis.swig
08:02:43.608 DEBUG Processed: layout/_scripts/pages/post-details.swig
08:02:43.608 DEBUG Processed: layout/_scripts/schemes/pisces.swig
08:02:43.608 DEBUG Processed: layout/_third-party/analytics/application-insights.swig
08:02:43.608 DEBUG Processed: layout/_third-party/analytics/baidu-analytics.swig
08:02:43.608 DEBUG Processed: layout/_third-party/analytics/busuanzi-counter.swig
08:02:43.608 DEBUG Processed: layout/_third-party/analytics/cnzz-analytics.swig
08:02:43.612 DEBUG Processed: layout/_third-party/analytics/facebook-sdk.swig
08:02:43.613 DEBUG Processed: layout/_third-party/analytics/google-analytics.swig
08:02:43.613 DEBUG Processed: layout/_third-party/analytics/index.swig
08:02:43.613 DEBUG Processed: layout/_third-party/analytics/lean-analytics.swig
08:02:43.613 DEBUG Processed: layout/_third-party/analytics/tencent-analytics.swig
08:02:43.613 DEBUG Processed: layout/_third-party/analytics/tencent-mta.swig
08:02:43.613 DEBUG Processed: layout/_third-party/analytics/vkontakte-api.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/changyan.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/disqus.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/duoshuo.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/gentie.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/hypercomments.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/index.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/livere.swig
08:02:43.613 DEBUG Processed: layout/_third-party/comments/youyan.swig
08:02:43.613 DEBUG Processed: layout/_third-party/search/index.swig
08:02:43.613 DEBUG Processed: layout/_third-party/search/localsearch.swig
08:02:43.613 DEBUG Processed: layout/_third-party/search/tinysou.swig
08:02:43.614 DEBUG Processed: layout/_third-party/seo/baidu-push.swig
08:02:43.620 DEBUG Processed: source/lib/Han/dist/font/han-space.otf
08:02:43.620 DEBUG Processed: source/lib/Han/dist/font/han-space.woff
08:02:43.621 DEBUG Processed: source/lib/Han/dist/font/han.otf
08:02:43.621 DEBUG Processed: source/lib/Han/dist/font/han.woff
08:02:43.621 DEBUG Processed: source/lib/fancybox/source/helpers/fancybox_buttons.png
08:02:43.621 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.css
08:02:43.622 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.js
08:02:43.622 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-media.js
08:02:43.622 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.css
08:02:43.622 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.js
08:02:43.622 DEBUG Processed: source/lib/font-awesome/fonts/FontAwesome.otf
08:02:43.623 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.eot
08:02:43.623 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.ttf
08:02:43.626 DEBUG Processed: layout/_third-party/search/algolia-search/assets.swig
08:02:43.627 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.js
08:02:43.628 DEBUG Processed: layout/_third-party/search/algolia-search/dom.swig
08:02:43.628 DEBUG Processed: source/lib/three/three.min.js
08:02:43.629 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.svg
08:02:44.195 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 106, Column 4]
  unexpected token: %
    at Object.exports.prettifyError (/Users/sp/oneDrive/blog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/sp/oneDrive/blog/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/sp/oneDrive/blog/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/sp/oneDrive/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/sp/oneDrive/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/sp/oneDrive/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/sp/oneDrive/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
08:02:44.270 DEBUG Database saved
08:02:44.270 FATAL (unknown path) [Line 106, Column 4]
  unexpected token: %
Template render error: (unknown path) [Line 106, Column 4]
  unexpected token: %
    at Object.exports.prettifyError (/Users/sp/oneDrive/blog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/sp/oneDrive/blog/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/sp/oneDrive/blog/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/sp/oneDrive/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/sp/oneDrive/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/sp/oneDrive/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/sp/oneDrive/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/sp/oneDrive/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by NoahDragon** [comment]
In your post https://github.com/SawyerSun/SawyerSun.github.io/blob/hexo/source/_posts/pom.md , the following syntax is incorrect.

```
{{% code junit4 lang:xml %}
```
should be
```
{% code junit4 lang:xml %}
```

**Comment by SawyerSun** [comment]
@NoahDragon Thank you for devoting so much time to help me solve the problem. It's all my fault that I should have paid more attention to hexo grammar.

**Comment by SawyerSun** [comment]
@NoahDragon it solved. Thank you for devoting so much time to help me solve the problem. It's all my fault that I should have paid more attention to hexo grammar.

**Comment by NoahDragon** [comment]
@SawyerSun No problem. I'll close this issue for now.
