### ISSUE TITLE
Code Block parse error

### ISSUE THREAD

**Issue by SawyerSun** [hexojs/hexo#2575]
## Environment Info

Node version(`node -v`): V7.10.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

exo-site@0.0.0 /Users/sp/oneDrive/blog
├── hexo@3.3.5
├── hexo-deployer-git@0.3.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-search@2.1.1
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.0
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.0
└── hexo-wordcount@2.0.1

## For BUG
I have some code in markdown like this:
<img width="417" alt="1" src="https://cloud.githubusercontent.com/assets/13533065/26276140/eba72e74-3da3-11e7-866e-8f7d9862db31.png">
However, the code will be parsed to :
<img width="650" alt="2" src="https://cloud.githubusercontent.com/assets/13533065/26276142/f76acc20-3da3-11e7-8dd9-27f93f479a69.png">

So, is there any idea to solve it?

**Comment by NoahDragon** [comment]
Have you tried the 3.3.6 version? If it still not fix your issue, please lock the hexo version to 3.2.2. It probably related to a know issue: #2573

**Comment by popomore** [comment]
I don't think it's relative to this issue

@SawyerSun can you give some example to reproduce the bug?

**Comment by NoahDragon** [comment]
similar to https://github.com/hexojs/hexo/issues/2574 issue.
