### ISSUE TITLE
asset_path can not parse in the markdown syntax

### ISSUE THREAD

**Issue by ShawnOY** [hexojs/hexo#2576]
## Environment Info

Node version(`node -v`): 6.10.2

Hexo and Plugin version(`npm ls --depth 0`): 

├── hexo@3.3.6
├── hexo-autonofollow@1.0.1
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.0

## For BUG

```
{% asset_path some-image.jpg %}
```

In pure html,

/2017/05/21/post-name/some-image.jpg

But in markdown syntax

![blahblahblah]({% asset_path some-image.jpg %})

It will be

```
<img src="!--￼1--" alt="blahblahblah">
```

**Comment by NoahDragon** [comment]
I don't think it is a bug. You could add the title attribute to assert image via:
```
{% asset_img slug [title] %}
```
