### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by lopakaka** [hexojs/hexo#258]
C:\Users\昱\Documents\GitHub\myblog [myblog +9 ~0 -0 !]> hexo
hexo : 无法将“hexo”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确
，然后再试一次。
所在位置 行:1 字符: 1
- hexo
- ~~~~
  - CategoryInfo          : ObjectNotFound: (hexo:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

**Comment by echonoff** [comment]
正好今天遇到了， 没有添加path环境变量的关系。。。。

**Comment by Xuanwo** [comment]
要把nodejs加进path
