### ISSUE TITLE
No way to disable line numbers

### ISSUE THREAD

**Issue by Glazy** [hexojs/hexo#2589]
The property `line_number` under `highlight` in `config.yml` seems to have no effect on whether the line numbers actually show - is this a known bug? As of right now I am having to hide them through CSS!

**Comment by NoahDragon** [comment]
I'm using the apollo theme and couldn't reproduce the issue: https://github.com/pinggod/hexo-theme-apollo

**Comment by mkkhedawat** [comment]
Even I had inconsistency with line number highlight config in config.yml. I ended up using prism plugin for hexo - https://github.com/ele828/hexo-prism-plugin . Cleaner and theme support .

Check my blog for demo : https://mkkhedawat.com/Getting-Started-with-ES6-1/

**Comment by herkyl** [comment]
Having the same issue

**Comment by craigphicks** [comment]
I'm using [hexo-theme-bootstrap-blog](http://cgmartin.github.io/hexo-theme-bootstrap-blog/).  Changing to `line_numbers: false` in `config.yml`  worked perfectly after `hexo clean && hexo generate`.

**Comment by fvydjt** [comment]
It's because of hexo cache. Use `hexo clean` to clean cache after you modify the `_config.yml`.
