### ISSUE TITLE
关于不忽略`_``.`等开头的文件的问题

### ISSUE THREAD

**Issue by Hscpro** [hexojs/hexo#2596]
如何不让HEXO不跳过文件也不略过文件？

比如`source`文件夹下有`_redirects`文件 （hexo似乎会自动略过`_``.`等之类开头的文件），编译时要存在于`public`文件夹？

**Comment by NoahDragon** [comment]
使用include在config文件中即可：
https://hexo.io/docs/configuration.html#Include-Exclude-Files-or-Folders
