### ISSUE TITLE
fs.SyncWriteStream is deprecated [Nodejs v8.0]

### ISSUE THREAD

**Issue by Lizhooh** [hexojs/hexo#2598]
I put the nodejs update to v8.0, then hexo at least some functions can not be run.
Can this be solved?

```js
> fs.SyncWriteStream
> (node:57352) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
```

> [nodejs/node#10467](https://github.com/nodejs/node/pull/10467)

**supplement**

name   | version
--- | --- 
nodejs  | v8.0
npm | v5.0
hexo | v3.3.7

**Comment by NoahDragon** [comment]
Already removed in hexo-fs plugin. As this function is never called, the Hexo functions would not be affected.

**Comment by CTBUmyq** [comment]
npm install hexo-fs --save
but on my pc,This command is valid only once.

**Comment by NoahDragon** [comment]
@CTBUmyq what do you mean valid? Any error trace output?

**Comment by yangxy6** [comment]
更新了hexo-fs插件，但是依旧报错

**Comment by JLHwung** [comment]
The hexo specified `hexo-fs` version as `^0.1.5`, however, the hexo-fs fix is landed on `0.2.0`, according to semver. We need to update `hexo-fs` version to `^0.2.0` and release 3.3.8.

**Comment by JLHwung** [comment]
The hexo specified `hexo-fs` version as `^0.1.5`, however, the hexo-fs fix is landed on `0.2.0`, according to semver. We need to update `hexo-fs` version to `^0.2.0` and release 3.3.8.

**Comment by rangerzhou** [comment]
通过npm install hexo-fs --save解决不了的，是因为在hexo-deployer-git中还有一个node_modules/hexo-fs目录，但是hexo-deployer-git官方Github中是没有这个目录的，可能是因为npm源没有更新，所以hexo-deployer-git中有一个旧版本的hexo-fs，注释掉E:\github\blog\node_modules\hexo-deployer-git\node_modules\hexo-fs\lib\fs.js中第718行exports.SyncWriteStream = fs.SyncWriteStream;就行了，或者手动更新hexo-deployer-git。

**Comment by JLHwung** [comment]
@rangerzhou Good catch! Once we release a new version of hexo-deployer-git, you can solve this via `npm upgrade`

@NoahDragon I've update the hexo-deployer-git and hexo-deployer-heroku to use hexo-fs 0.2.x, could you publish these packages? Thank you.

**Comment by NoahDragon** [comment]
@JLHwung Got it, will publish them to NPM later today.

**Comment by JLHwung** [comment]
@NoahDragon Thank you very much.

**Comment by NoahDragon** [comment]
FYI, the following packages may contain the old version of Hexo-fs have been updated.

hexo-deployer-git 0.3.1
hexo-math 3.0.3
hexo-renderer-ejs 0.3.1
hexo-deployer-openshift 0.1.2
hexo-server 0.2.2
hexo-deployer-heroku 0.1.2

**Comment by tiakia** [comment]
some errors:

(node:12576) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  [hexo-math] Using engine 'mathjax'


"hexo": "^3.2.0",
    "hexo-baidu-url-submit": "0.0.5",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-heroku": "^0.1.2",
    "hexo-deployer-openshift": "^0.1.2",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-post-top": "0.0.1",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.3",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2"

**Comment by jdhao** [comment]
I have also met this warning message.  But `npm update` can not update  `hexo-deployer-git`, `hexo-renderer-ejs` and `hexo-server`. I have to uninstall the three packages using `npm uninstall` and reinstall them using `npm install XXX --save`.
