### ISSUE TITLE
change of name cases of tags and categories won't take effect

### ISSUE THREAD

**Issue by jdhao** [hexojs/hexo#2600]
## Environment Info

Node version: v6.10.0

Hexo and Plugin version:
>hexo-site@0.0.0 d:\hexo\blog              
+-- hexo@3.2.2                            
+-- hexo-deployer-git@0.2.0               
+-- hexo-generator-archive@0.1.4          
+-- hexo-generator-category@0.1.3         
+-- hexo-generator-index@0.2.0            
+-- hexo-generator-sitemap@1.1.2          
+-- hexo-generator-tag@0.2.0              
+-- hexo-renderer-ejs@0.2.0               
+-- hexo-renderer-markdown-it@3.4.1       
+-- hexo-renderer-stylus@0.3.1            
+-- hexo-server@0.2.0                     
+-- hexo-tag-kbd@0.0.1                    
+-- markdown-it-abbr@1.0.4 extraneous     
+-- markdown-it-footnote@2.0.0 extraneous 
+-- markdown-it-sub@1.0.0 extraneous      
`-- markdown-it-sup@1.0.0 extraneous      

### BUG description
When you change the case of categories or tags names associated with a post and deploy it to github. The change won't take effect.

### The way to reproduce
I write a post, give it category name "Linux", then use `hexo d -g` to deploy it to github pages, everything works fine. Later, I want to change the case of category name, for example, if I change it to 'linux' or 'LINUX' (whatever as long as **only** the character case changes), clean the current build `hexo clean`, then deploy again using `hexo d -g`.  You will find that this change won't take effect: in the categories or tags page of my blog, the new category or tag name is shown. When you click the new category or tag name, you will not see a list of post linked but get 404 not found error. 

If you only preview the new change using `hexo s -g`, everything works fine: the new change of name case takes effect and works as expected.

I checked the github pages repo after deployment and found that the new change of name case is not reflected on github. Under the folder *categories* or *tags* , old names are still shown. However, in my local machine (a Windows 8.1 computer), in the same folder, the new name is shown. I think this may be the reason but do not know how to solve it.

I have searched the hexo issues and found one about capitalizing issue  #1693. But on my machine, I have set `filename_case` to its default 0. 

### Log with hexo d -g --debug
>hexo d -g --debug
01:38:47.482 DEBUG Hexo version: 3.2.2
01:38:47.482 DEBUG Working directory: d:\hexo\blog\
01:38:47.732 DEBUG Config loaded: d:\hexo\blog\_config.yml
01:38:47.763 DEBUG Plugin loaded: hexo-deployer-git
01:38:47.779 DEBUG Plugin loaded: hexo-generator-category
01:38:47.779 DEBUG Plugin loaded: hexo-generator-archive
01:38:47.779 DEBUG Plugin loaded: hexo-generator-index
01:38:47.794 DEBUG Plugin loaded: hexo-generator-tag
01:38:47.794 DEBUG Plugin loaded: hexo-generator-sitemap
01:38:47.794 DEBUG Plugin loaded: hexo-renderer-ejs
01:38:47.810 DEBUG Plugin loaded: hexo-renderer-markdown-it
01:38:47.810 DEBUG Plugin loaded: hexo-renderer-stylus
01:38:47.951 DEBUG Plugin loaded: hexo-server
01:38:47.951 DEBUG Plugin loaded: hexo-tag-kbd
01:38:47.951 DEBUG Script loaded: themes\next\scripts\merge-configs.js
01:38:47.951 DEBUG Script loaded: themes\next\scripts\tags\button.js
01:38:47.951 DEBUG Script loaded: themes\next\scripts\tags\center-quote.js
01:38:47.966 DEBUG Script loaded: themes\next\scripts\tags\exturl.js
01:38:47.966 DEBUG Script loaded: themes\next\scripts\tags\full-image.js
01:38:47.966 DEBUG Script loaded: themes\next\scripts\tags\group-pictures.js
01:38:47.966 DEBUG Script loaded: themes\next\scripts\tags\note.js
01:38:47.966 DEBUG Loading database.
01:38:47.982 INFO  Start processing
01:38:48.076 DEBUG Processed: robots.txt
01:38:48.263 DEBUG Theme config loaded.
01:38:48.263 DEBUG Processed: _config.yml
01:38:48.279 DEBUG Processed: source/css/main.styl
01:38:48.279 DEBUG Processed: source/images/algolia_logo.svg
01:38:48.279 DEBUG Processed: source/images/aaronscat.jpg
01:38:48.279 DEBUG Processed: source/images/avatar.gif
01:38:48.279 DEBUG Processed: source/images/cc-by-nc-nd.svg
01:38:48.279 DEBUG Processed: source/images/cc-by-nc.svg
01:38:48.279 DEBUG Processed: source/images/cc-by-nc-sa.svg
01:38:48.294 DEBUG Processed: source/images/cc-by-nd.svg
01:38:48.294 DEBUG Processed: source/images/cc-by-sa.svg
01:38:48.294 DEBUG Processed: source/images/cc-by.svg
01:38:48.294 DEBUG Processed: source/images/cc-zero.svg
01:38:48.294 DEBUG Processed: source/images/loading.gif
01:38:48.294 DEBUG Processed: source/images/placeholder.gif
01:38:48.310 DEBUG Processed: source/images/quote-l.svg
01:38:48.310 DEBUG Processed: source/images/quote-r.svg
01:38:48.310 DEBUG Processed: source/images/searchicon.png
01:38:48.372 DEBUG Processed: _drafts/test-mathjax.md
01:38:48.794 DEBUG Processed: layout/_layout.swig
01:38:48.794 DEBUG Processed: layout/archive.swig
01:38:48.794 DEBUG Processed: layout/category.swig
01:38:48.794 DEBUG Processed: layout/index.swig
01:38:48.794 DEBUG Processed: layout/page.swig
01:38:48.794 DEBUG Processed: layout/post.swig
01:38:48.794 DEBUG Processed: layout/schedule.swig
01:38:48.794 DEBUG Processed: layout/tag.swig
01:38:48.826 DEBUG Processed: about/index.md
01:38:48.841 DEBUG Processed: languages/de.yml
01:38:48.841 DEBUG Processed: languages/default.yml
01:38:48.841 DEBUG Processed: languages/en.yml
01:38:48.841 DEBUG Processed: languages/fr-FR.yml
01:38:48.841 DEBUG Processed: languages/id.yml
01:38:48.841 DEBUG Processed: languages/ja.yml
01:38:48.841 DEBUG Processed: languages/ko.yml
01:38:48.841 DEBUG Processed: languages/pt-BR.yml
01:38:48.841 DEBUG Processed: languages/pt.yml
01:38:48.857 DEBUG Processed: languages/ru.yml
01:38:48.857 DEBUG Processed: languages/zh-Hans.yml
01:38:48.857 DEBUG Processed: languages/zh-hk.yml
01:38:48.857 DEBUG Processed: languages/zh-tw.yml
01:38:48.857 DEBUG Processed: categories/index.md
01:38:48.872 DEBUG Processed: tags/index.md
01:38:48.888 DEBUG Processed: _posts/Listary_intro.md
01:38:48.919 DEBUG Processed: _posts/Sublime-Windows-Markdown.md
01:38:48.935 DEBUG Processed: _posts/windows-sublime-usage-related-issue.md
01:38:48.935 DEBUG Processed: _posts/apply-for-hk-visa.md
01:38:48.951 DEBUG Processed: _posts/change-aspect-ratio-in-mpl.md
01:38:48.951 DEBUG Processed: _posts/install-feh-image-viewer-on-centos.md
01:38:48.951 DEBUG Processed: _posts/some_loss_and_explanations.md
01:38:48.951 DEBUG Processed: _posts/transfer-file-android-windows.md
01:38:48.966 DEBUG Processed: _posts/Windows-xelatex-slow.md
01:38:48.966 DEBUG Processed: _posts/guide-on-how-to-use-chinese-with-matplotlib.md
01:38:48.982 DEBUG Processed: _posts/hexo-install-use-issue.md
01:38:48.982 DEBUG Processed: _posts/spring_festival_in_wh.md
01:38:48.982 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.css
01:38:48.997 DEBUG Processed: _posts/my_first_post.md
01:38:48.997 DEBUG Processed: source/lib/fastclick/LICENSE
01:38:48.997 DEBUG Processed: source/lib/fastclick/README.md
01:38:48.997 DEBUG Processed: source/lib/fastclick/bower.json
01:38:48.997 DEBUG Processed: source/lib/canvas-nest/canvas-nest.min.js
01:38:48.997 DEBUG Processed: source/lib/font-awesome/HELP-US-OUT.txt
01:38:48.997 DEBUG Processed: source/lib/font-awesome/bower.json
01:38:48.997 DEBUG Processed: source/lib/jquery_lazyload/CONTRIBUTING.md
01:38:48.997 DEBUG Processed: source/lib/jquery_lazyload/README.md
01:38:48.997 DEBUG Processed: source/lib/jquery_lazyload/bower.json
01:38:49.013 DEBUG Processed: source/lib/jquery_lazyload/jquery.lazyload.js
01:38:49.013 DEBUG Processed: source/lib/jquery_lazyload/jquery.scrollstop.js
01:38:49.013 DEBUG Processed: source/lib/velocity/bower.json
01:38:49.013 DEBUG Processed: source/lib/velocity/velocity.min.js
01:38:49.013 DEBUG Processed: source/lib/velocity/velocity.ui.js
01:38:49.013 DEBUG Processed: source/lib/velocity/velocity.ui.min.js
01:38:49.013 DEBUG Processed: source/js/src/affix.js
01:38:49.013 DEBUG Processed: source/js/src/bootstrap.js
01:38:49.013 DEBUG Processed: source/js/src/algolia-search.js
01:38:49.029 DEBUG Processed: source/js/src/exturl.js
01:38:49.029 DEBUG Processed: source/js/src/hook-duoshuo.js
01:38:49.029 DEBUG Processed: source/js/src/motion.js
01:38:49.029 DEBUG Processed: source/js/src/post-details.js
01:38:49.029 DEBUG Processed: source/js/src/scrollspy.js
01:38:49.029 DEBUG Processed: source/js/src/utils.js
01:38:49.065 DEBUG Processed: source/lib/jquery/index.js
01:38:49.191 DEBUG Processed: layout/_custom/sidebar.swig
01:38:49.191 DEBUG Processed: layout/_custom/header.swig
01:38:49.191 DEBUG Processed: layout/_partials/footer.swig
01:38:49.191 DEBUG Processed: layout/_partials/header.swig
01:38:49.191 DEBUG Processed: layout/_partials/duoshuo-hot-articles.swig
01:38:49.191 DEBUG Processed: layout/_partials/comments.swig
01:38:49.191 DEBUG Processed: layout/_partials/head.swig
01:38:49.191 DEBUG Processed: layout/_partials/page-header.swig
01:38:49.191 DEBUG Processed: layout/_partials/pagination.swig
01:38:49.206 DEBUG Processed: layout/_partials/search.swig
01:38:49.206 DEBUG Processed: layout/_macro/post.swig
01:38:49.206 DEBUG Processed: layout/_macro/post-collapse.swig
01:38:49.206 DEBUG Processed: layout/_macro/reward.swig
01:38:49.206 DEBUG Processed: layout/_macro/sidebar.swig
01:38:49.206 DEBUG Processed: layout/_scripts/baidu-push.swig
01:38:49.206 DEBUG Processed: layout/_macro/wechat-subscriber.swig
01:38:49.206 DEBUG Processed: layout/_scripts/commons.swig
01:38:49.206 DEBUG Processed: layout/_scripts/vendors.swig
01:38:49.206 DEBUG Processed: layout/_scripts/boostrap.swig
01:38:49.222 DEBUG Processed: source/lib/fastclick/lib/fastclick.js
01:38:49.222 DEBUG Processed: source/lib/fastclick/lib/fastclick.min.js
01:38:49.222 DEBUG Processed: source/lib/fancybox/source/blank.gif
01:38:49.222 DEBUG Processed: source/lib/fancybox/source/fancybox_loading.gif
01:38:49.222 DEBUG Processed: source/lib/fancybox/source/fancybox_loading@2x.gif
01:38:49.237 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite.png
01:38:49.237 DEBUG Processed: source/lib/fancybox/source/fancybox_overlay.png
01:38:49.237 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite@2x.png
01:38:49.237 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.css
01:38:49.237 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.js
01:38:49.237 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.pack.js
01:38:49.237 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css
01:38:49.253 DEBUG Processed: source/lib/font-awesome/css/font-awesome.min.css
01:38:49.253 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css.map
01:38:49.253 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.min.js
01:38:49.253 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.pack.js
01:38:49.253 DEBUG Processed: source/js/src/schemes/pisces.js
01:38:49.253 DEBUG Processed: layout/_scripts/schemes/mist.swig
01:38:49.269 DEBUG Processed: layout/_scripts/schemes/muse.swig
01:38:49.269 DEBUG Processed: source/lib/font-awesome/fonts/FontAwesome.otf
01:38:49.269 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.eot
01:38:49.269 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff
01:38:49.269 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff2
01:38:49.269 DEBUG Processed: source/lib/velocity/velocity.js
01:38:49.316 DEBUG Processed: layout/_components/algolia-search/dom.swig
01:38:49.316 DEBUG Processed: layout/_partials/head/custom-head.swig
01:38:49.316 DEBUG Processed: layout/_partials/head/external-fonts.swig
01:38:49.316 DEBUG Processed: layout/_components/algolia-search/assets.swig
01:38:49.316 DEBUG Processed: layout/_partials/search/swiftype.swig
01:38:49.316 DEBUG Processed: layout/_partials/search/tinysou.swig
01:38:49.316 DEBUG Processed: layout/_partials/share/add-this.swig
01:38:49.316 DEBUG Processed: layout/_partials/search/localsearch.swig
01:38:49.316 DEBUG Processed: layout/_partials/share/baidushare.swig
01:38:49.331 DEBUG Processed: layout/_partials/share/duoshuo_share.swig
01:38:49.331 DEBUG Processed: layout/_partials/share/jiathis.swig
01:38:49.331 DEBUG Processed: layout/_scripts/third-party/analytics.swig
01:38:49.331 DEBUG Processed: layout/_scripts/pages/post-details.swig
01:38:49.331 DEBUG Processed: layout/_scripts/third-party/comments.swig
01:38:49.331 DEBUG Processed: layout/_scripts/schemes/pisces.swig
01:38:49.331 DEBUG Processed: layout/_scripts/third-party/localsearch.swig
01:38:49.331 DEBUG Processed: layout/_scripts/third-party/mathjax.swig
01:38:49.331 DEBUG Processed: layout/_scripts/third-party/lean-analytics.swig
01:38:49.331 DEBUG Processed: layout/_scripts/third-party/tinysou.swig
01:38:49.331 DEBUG Processed: layout/_scripts/third-party/schedule.swig
01:38:49.347 DEBUG Processed: source/lib/fancybox/source/helpers/fancybox_buttons.png
01:38:49.347 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.css
01:38:49.347 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.js
01:38:49.347 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.css
01:38:49.347 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-media.js
01:38:49.347 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.js
01:38:49.347 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.ttf
01:38:49.394 DEBUG Processed: layout/_scripts/third-party/analytics/application-insights.swig
01:38:49.394 DEBUG Processed: layout/_scripts/third-party/analytics/baidu-analytics.swig
01:38:49.394 DEBUG Processed: layout/_scripts/third-party/analytics/cnzz-analytics.swig
01:38:49.394 DEBUG Processed: layout/_scripts/third-party/analytics/google-analytics.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/analytics/busuanzi-counter.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/analytics/tencent-mta.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/analytics/vkontakte-api.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/analytics/tencent-analytics.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/comments/duoshuo.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/comments/disqus.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/analytics/facebook-sdk.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/comments/hypercomments.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/comments/youyan.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/comments/gentie.swig
01:38:49.409 DEBUG Processed: layout/_scripts/third-party/comments/livere.swig
01:38:49.409 DEBUG Processed: source/images/riverside_flower.jpg
01:38:49.409 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.js
01:38:49.409 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.svg
01:38:50.503 DEBUG Generator: page
01:38:50.503 DEBUG Generator: post
01:38:50.503 DEBUG Generator: category
01:38:50.503 DEBUG Generator: archive
01:38:50.503 DEBUG Generator: index
01:38:50.503 DEBUG Generator: tag
01:38:50.519 DEBUG Generator: sitemap
01:38:50.519 DEBUG Generator: asset
01:38:50.581 INFO  Files loaded in 2.61 s
01:38:50.644 DEBUG Rendering page: about/index.html
01:38:50.784 DEBUG Rendering page: categories/index.html
01:38:50.862 DEBUG Rendering page: tags/index.html
01:38:50.956 DEBUG Rendering post: 2017/06/03/change-aspect-ratio-in-mpl/index.html
01:38:51.144 DEBUG Rendering post: 2017/05/13/guide-on-how-to-use-chinese-with-matplotlib/index.html
01:38:51.253 DEBUG Rendering post: 2017/05/06/install-feh-image-viewer-on-centos/index.html
01:38:51.362 DEBUG Rendering post: 2017/04/30/apply-for-hk-visa/index.html
01:38:51.441 DEBUG Rendering post: 2017/03/26/transfer-file-android-windows/index.html
01:38:51.550 DEBUG Rendering post: 2017/03/19/windows-sublime-usage-related-issue/index.html
01:38:51.628 DEBUG Rendering post: 2017/03/13/some_loss_and_explanations/index.html
01:38:51.738 DEBUG Rendering post: 2017/03/06/Windows-xelatex-slow/index.html
01:38:51.831 DEBUG Rendering post: 2017/03/04/Sublime-Windows-Markdown/index.html
01:38:51.941 DEBUG Rendering post: 2017/03/01/Listary_intro/index.html
01:38:52.050 DEBUG Rendering post: 2017/02/26/hexo-install-use-issue/index.html
01:38:52.159 DEBUG Rendering post: 2017/02/25/spring_festival_in_wh/index.html
01:38:52.253 DEBUG Rendering post: 2017/02/24/my_first_post/index.html
01:38:52.347 DEBUG Rendering category: categories/Windows/index.html
01:38:52.441 DEBUG Rendering category: categories/生活/index.html
01:38:52.503 DEBUG Rendering category: categories/Python/index.html
01:38:52.597 DEBUG Rendering category: categories/LINUX/index.html
01:38:52.659 DEBUG Rendering category: categories/deep-learning/index.html
01:38:52.738 DEBUG Rendering category: categories/Android/index.html
01:38:52.816 DEBUG Rendering archive: archives/index.html
01:38:52.909 DEBUG Rendering archive: archives/page/2/index.html
01:38:52.988 DEBUG Rendering archive: archives/2017/index.html
01:38:53.066 DEBUG Rendering archive: archives/2017/page/2/index.html
01:38:53.159 DEBUG Rendering archive: archives/2017/02/index.html
01:38:53.222 DEBUG Rendering archive: archives/2017/03/index.html
01:38:53.300 DEBUG Rendering archive: archives/2017/04/index.html
01:38:53.378 DEBUG Rendering archive: archives/2017/05/index.html
01:38:53.456 DEBUG Rendering index: index.html
01:38:53.581 DEBUG Rendering archive: archives/2017/06/index.html
01:38:53.659 DEBUG Rendering index: page/2/index.html
01:38:53.722 DEBUG Rendering tag: tags/tools/index.html
01:38:53.831 DEBUG Rendering tag: tags/Sublime-Text/index.html
01:38:53.910 DEBUG Rendering tag: tags/Markdown/index.html
01:38:53.988 DEBUG Rendering tag: tags/city/index.html
01:38:54.066 DEBUG Rendering tag: tags/Mobike/index.html
01:38:54.128 DEBUG Rendering tag: tags/Matplotlib/index.html
01:38:54.222 DEBUG Rendering tag: tags/LaTeX/index.html
01:38:54.285 DEBUG Rendering tag: tags/font/index.html
01:38:54.378 DEBUG Rendering tag: tags/NexT/index.html
01:38:54.441 DEBUG Rendering tag: tags/Hexo/index.html
01:38:54.519 DEBUG Rendering tag: tags/美食/index.html
01:38:54.597 DEBUG Rendering tag: tags/小说/index.html
01:38:54.675 DEBUG Rendering tag: tags/Github/index.html
01:38:54.878 INFO  Generated: sitemap.xml
01:38:56.628 INFO  Generated: index.html
01:38:56.675 INFO  Generated: categories/index.html
01:38:56.675 INFO  Generated: tags/index.html
01:38:56.675 INFO  Generated: archives/index.html
01:38:56.675 INFO  Generated: about/index.html
01:38:56.675 INFO  Generated: robots.txt
01:38:56.691 INFO  Generated: archives/page/2/index.html
01:38:56.691 INFO  Generated: archives/2017/02/index.html
01:38:56.707 INFO  Generated: images/algolia_logo.svg
01:38:56.707 INFO  Generated: categories/LINUX/index.html
01:38:56.707 INFO  Generated: categories/Python/index.html
01:38:56.707 INFO  Generated: categories/Windows/index.html
01:38:56.707 INFO  Generated: categories/生活/index.html
01:38:56.707 INFO  Generated: archives/2017/03/index.html
01:38:56.707 INFO  Generated: archives/2017/04/index.html
01:38:56.707 INFO  Generated: categories/deep-learning/index.html
01:38:56.707 INFO  Generated: categories/Android/index.html
01:38:56.707 INFO  Generated: tags/tools/index.html
01:38:56.707 INFO  Generated: archives/2017/06/index.html
01:38:56.707 INFO  Generated: tags/Sublime-Text/index.html
01:38:56.707 INFO  Generated: archives/2017/05/index.html
01:38:56.722 INFO  Generated: tags/city/index.html
01:38:56.722 INFO  Generated: tags/LaTeX/index.html
01:38:56.722 INFO  Generated: tags/Matplotlib/index.html
01:38:56.722 INFO  Generated: tags/Mobike/index.html
01:38:56.722 INFO  Generated: tags/Markdown/index.html
01:38:56.722 INFO  Generated: tags/font/index.html
01:38:56.722 INFO  Generated: tags/Hexo/index.html
01:38:56.722 INFO  Generated: tags/NexT/index.html
01:38:56.722 INFO  Generated: tags/美食/index.html
01:38:56.722 INFO  Generated: tags/小说/index.html
01:38:56.722 INFO  Generated: tags/Github/index.html
01:38:56.722 INFO  Generated: images/cc-by-nc-nd.svg
01:38:56.722 INFO  Generated: images/aaronscat.jpg
01:38:56.722 INFO  Generated: images/avatar.gif
01:38:56.722 INFO  Generated: images/cc-by-nc.svg
01:38:56.738 INFO  Generated: images/cc-by-sa.svg
01:38:56.738 INFO  Generated: images/cc-by-nd.svg
01:38:56.738 INFO  Generated: images/loading.gif
01:38:56.738 INFO  Generated: images/cc-by-nc-sa.svg
01:38:56.738 INFO  Generated: images/cc-by.svg
01:38:56.738 INFO  Generated: images/quote-r.svg
01:38:56.738 INFO  Generated: images/placeholder.gif
01:38:56.738 INFO  Generated: archives/2017/index.html
01:38:56.738 INFO  Generated: images/quote-l.svg
01:38:56.738 INFO  Generated: images/searchicon.png
01:38:56.738 INFO  Generated: images/cc-zero.svg
01:38:56.753 INFO  Generated: page/2/index.html
01:38:56.753 INFO  Generated: lib/fastclick/LICENSE
01:38:56.753 INFO  Generated: archives/2017/page/2/index.html
01:38:56.753 INFO  Generated: lib/jquery_lazyload/CONTRIBUTING.html
01:38:56.753 INFO  Generated: lib/canvas-nest/canvas-nest.min.js
01:38:56.769 INFO  Generated: lib/velocity/bower.json
01:38:56.769 INFO  Generated: lib/algolia-instant-search/instantsearch.min.css
01:38:56.769 INFO  Generated: lib/font-awesome/bower.json
01:38:56.769 INFO  Generated: lib/fastclick/bower.json
01:38:56.769 INFO  Generated: lib/fastclick/README.html
01:38:56.785 INFO  Generated: lib/jquery_lazyload/README.html
01:38:56.785 INFO  Generated: lib/jquery_lazyload/bower.json
01:38:56.785 INFO  Generated: lib/jquery_lazyload/jquery.lazyload.js
01:38:56.785 INFO  Generated: lib/jquery_lazyload/jquery.scrollstop.js
01:38:56.785 INFO  Generated: lib/velocity/velocity.ui.min.js
01:38:56.785 INFO  Generated: css/main.css
01:38:56.785 INFO  Generated: lib/jquery/index.js
01:38:56.785 INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.woff
01:38:56.785 INFO  Generated: lib/font-awesome/HELP-US-OUT.txt
01:38:56.800 INFO  Generated: lib/velocity/velocity.ui.js
01:38:56.800 INFO  Generated: lib/algolia-instant-search/instantsearch.min.js
01:38:56.800 INFO  Generated: lib/velocity/velocity.min.js
01:38:56.800 INFO  Generated: lib/velocity/velocity.js
01:38:56.800 INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.eot
01:38:56.800 INFO  Generated: lib/font-awesome/fonts/FontAwesome.otf
01:38:56.800 INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.woff2
01:38:56.800 INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.svg
01:38:56.800 INFO  Generated: 2017/05/13/guide-on-how-to-use-chinese-with-matplotlib/index.html
01:38:56.800 INFO  Generated: lib/fancybox/source/helpers/fancybox_buttons.png
01:38:56.800 INFO  Generated: 2017/04/30/apply-for-hk-visa/index.html
01:38:56.816 INFO  Generated: 2017/06/03/change-aspect-ratio-in-mpl/index.html
01:38:56.816 INFO  Generated: 2017/03/26/transfer-file-android-windows/index.html
01:38:56.816 INFO  Generated: 2017/05/06/install-feh-image-viewer-on-centos/index.html
01:38:56.816 INFO  Generated: lib/fancybox/source/blank.gif
01:38:56.816 INFO  Generated: lib/font-awesome/css/font-awesome.css.map
01:38:56.816 INFO  Generated: 2017/03/19/windows-sublime-usage-related-issue/index.html
01:38:56.816 INFO  Generated: 2017/03/13/some_loss_and_explanations/index.html
01:38:56.816 INFO  Generated: 2017/03/04/Sublime-Windows-Markdown/index.html
01:38:56.816 INFO  Generated: js/src/affix.js
01:38:56.816 INFO  Generated: 2017/03/06/Windows-xelatex-slow/index.html
01:38:56.816 INFO  Generated: lib/ua-parser-js/dist/ua-parser.pack.js
01:38:56.816 INFO  Generated: 2017/02/26/hexo-install-use-issue/index.html
01:38:56.816 INFO  Generated: 2017/02/25/spring_festival_in_wh/index.html
01:38:56.832 INFO  Generated: 2017/03/01/Listary_intro/index.html
01:38:56.832 INFO  Generated: 2017/02/24/my_first_post/index.html
01:38:56.832 INFO  Generated: lib/fancybox/source/fancybox_loading.gif
01:38:56.832 INFO  Generated: lib/fancybox/source/fancybox_sprite.png
01:38:56.832 INFO  Generated: lib/fancybox/source/fancybox_loading@2x.gif
01:38:56.832 INFO  Generated: lib/fancybox/source/fancybox_sprite@2x.png
01:38:56.832 INFO  Generated: lib/fancybox/source/fancybox_overlay.png
01:38:56.832 INFO  Generated: js/src/bootstrap.js
01:38:56.832 INFO  Generated: js/src/motion.js
01:38:56.832 INFO  Generated: js/src/algolia-search.js
01:38:56.832 INFO  Generated: lib/fastclick/lib/fastclick.min.js
01:38:56.832 INFO  Generated: lib/fancybox/source/jquery.fancybox.css
01:38:56.832 INFO  Generated: js/src/hook-duoshuo.js
01:38:56.832 INFO  Generated: lib/ua-parser-js/dist/ua-parser.min.js
01:38:56.847 INFO  Generated: js/src/scrollspy.js
01:38:56.847 INFO  Generated: lib/fancybox/source/helpers/jquery.fancybox-buttons.css
01:38:56.847 INFO  Generated: js/src/post-details.js
01:38:56.847 INFO  Generated: images/riverside_flower.jpg
01:38:56.847 INFO  Generated: js/src/exturl.js
01:38:56.847 INFO  Generated: js/src/utils.js
01:38:56.847 INFO  Generated: lib/fancybox/source/helpers/jquery.fancybox-media.js
01:38:56.847 INFO  Generated: lib/fancybox/source/helpers/jquery.fancybox-buttons.js
01:38:56.847 INFO  Generated: lib/fancybox/source/helpers/jquery.fancybox-thumbs.js
01:38:56.847 INFO  Generated: lib/fancybox/source/helpers/jquery.fancybox-thumbs.css
01:38:56.847 INFO  Generated: lib/fastclick/lib/fastclick.js
01:38:56.847 INFO  Generated: lib/font-awesome/css/font-awesome.css
01:38:56.847 INFO  Generated: lib/font-awesome/css/font-awesome.min.css
01:38:56.847 INFO  Generated: lib/fancybox/source/jquery.fancybox.js
01:38:56.863 INFO  Generated: lib/fancybox/source/jquery.fancybox.pack.js
01:38:56.863 INFO  Generated: lib/font-awesome/fonts/fontawesome-webfont.ttf
01:38:56.863 INFO  Generated: js/src/schemes/pisces.js
01:38:56.863 INFO  122 files generated in 6.28 s
01:38:56.863 INFO  Deploying: git
01:38:56.863 INFO  Clearing .deploy_git folder...
01:38:56.925 INFO  Copying files from public folder...
[master 3bfb826] Site updated: 2017-06-09 09:38:56
 7 files changed, 18 insertions(+), 18 deletions(-)
Branch master set up to track remote branch master from https://github.com/jdhao/jdhao.github.io.
To https://github.com/jdhao/jdhao.github.io
   14ee672..3bfb826  HEAD -> master
01:39:05.991 INFO  Deploy done: git
01:39:06.053 DEBUG Database saved

**Comment by NoahDragon** [comment]
The different output of `hexo g` and `hexo server` is a known issue that we are trying to fix.

I believe the case issue is caused by git: https://stackoverflow.com/questions/3011625/git-mv-and-only-change-case-of-directory . In a case-insensitive environment, git won't pick up the case change. You could try the solution provided in the link.

**Comment by jdhao** [comment]
For later reference, the reason is indeed that git ignores the change of name cases. A workaround is to change the category or tag name to other names, deploy it to github. Change the name back to your desired name and deploy again.
