### ISSUE TITLE
can not install success on centos

### ISSUE THREAD

**Issue by rouroulee** [hexojs/hexo#2603]
## Environment Info

Node version(`node -v`):
v8.1.0 & v6.11.0 
Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
npm v3.10.10
## For BUG

npm-debug.log
## For question

can not install success

**Comment by rouroulee** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/liyanwei/.nvm/versions/node/v6.11.0/bin/node',
1 verbose cli   '/usr/liyanwei/.nvm/versions/node/v6.11.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:highlight' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose stack Error: ENOENT: no such file or directory, open '/usr/hexo-blog/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /usr/hexo-blog
6 error Linux 4.10.5-1.el6.elrepo.x86_64
7 error argv "/usr/liyanwei/.nvm/versions/node/v6.11.0/bin/node" "/usr/liyanwei/.nvm/versions/node/v6.11.0/bin/npm" "run" "build:highlight"
8 error node v6.11.0
9 error npm  v3.10.10
10 error path /usr/hexo-blog/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/usr/hexo-blog/package.json'
15 error enoent ENOENT: no such file or directory, open '/usr/hexo-blog/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

**Comment by NoahDragon** [comment]
have you run `hexo init` or `npm install`?
