### ISSUE TITLE
更新主题后出现问题怎么办

### ISSUE THREAD

**Issue by TonyDemon** [hexojs/hexo#2608]
Wangye@DESKTOP-ULP79OM MINGW64 /d/hexo/blog
$ cd themes/yilia

Wangye@DESKTOP-ULP79OM MINGW64 /d/hexo/blog/themes/yilia (master)
$ git pull
Already up-to-date.

Wangye@DESKTOP-ULP79OM MINGW64 /d/hexo/blog/themes/yilia (master)
$ hexo g
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

**Comment by NoahDragon** [comment]
Please run `hexo g` under `/d/hexo/blog` folder.
