### ISSUE TITLE
Permalink not including root

### ISSUE THREAD

**Issue by miqmago** [hexojs/hexo#2610]
## Environment Info

Node version(`node -v`): 7.8.9

Your site `_config.yml` (Optional):

```yml
root: /blog/
url: http://127.0.0.1:4000/       # Note: don't forget to modify the CNAME file to your url
permalink: :title-:abbrlink/
permalink_defaults:
```

Your theme `_config.yml` (Optional): 
Nothing relevant

Hexo and Plugin version(`npm ls --depth 0`): 

```
├── bootstrap@3.3.7
├── dialog-polyfill@0.4.7
├── gulp@3.9.1
├── gulp-connect-php@1.0.1
├── hexo@3.3.7
├── hexo-abbrlink@2.0.4
├── hexo-autonofollow@1.0.1
├── hexo-browsersync@0.2.0
├── hexo-deployer-git@0.1.0
├── hexo-filter-cleanup@1.0.7
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-seo-friendly-sitemap@0.0.20
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-markdown-it@3.4.1
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.0
├── hexo-toc@1.0.8
├── jquery@3.2.1
├── marked@0.3.6
├── md-date-time-picker@2.3.0
├── moment@2.18.1
└── showdown@1.7.1
```

## For BUG

I've placed `<%= page.permalink %>` in `post.ejs` and the result is `http://127.0.0.1:4000/El-meu-primer-post-ada5698b/`

This link is not working as root is `/blog/`. Also `<%= config.url + config.root + (page.path||'').replace('index.html', '') %>` produces `http://127.0.0.1:4000/blog/El-meu-primer-post-ada5698b/` which is ok.

I've tried to change `permalink` directive in `_config.yml` to include `:root` with no success. Also this change breaks the links in home page. `index.ejs`:

```ejs
<% page.posts.each(function(post){ %>
<div class="post-preview">

    <a href="<%- config.root %><%- post.path %>">
```

Am I missing something?

**Comment by NoahDragon** [comment]
The url should include the root path: `http://127.0.0.1:4000/blog/`

The new config file has mentioned this in comment:
![image](https://user-images.githubusercontent.com/5704064/27134108-8644add4-50e2-11e7-84e0-86d8af21f20a.png)

**Comment by miqmago** [comment]
@NoahDragon thanks

> The url should include the root path: `http://127.0.0.1:4000/blog`

So what I guess is that `_config.yml` should be:

```yml
url: http://127.0.0.1:4000/blog
root: /
```

In this case, why is `root` parameter for? Just for curiosity...

**Comment by NoahDragon** [comment]
@miqmago Good question. I will have a look.

**Comment by sKawashima** [comment]
Maybe, it will be used to deploy.
I think that this is important BUG.
