### ISSUE TITLE
本地预览正常为最新版本，上传到github后，线上浏览发现还是原来版本。github上面的文件已经替换

### ISSUE THREAD

**Issue by allenYetu211** [hexojs/hexo#2611]
![image](https://user-images.githubusercontent.com/17957079/27111228-5ef5e76c-50e1-11e7-8ee4-098e114fd98f.png)

以上为本地版本，最新发布的文章。

![image](https://user-images.githubusercontent.com/17957079/27111396-6cc188d2-50e2-11e7-92e1-fa18abb7f33e.png)

这里为线上版本，我已经将代码发布到了github里面。

![image](https://user-images.githubusercontent.com/17957079/27111422-8b128174-50e2-11e7-9bbd-1cdf36092192.png)

请问一下这是为什么，我替换文件后，显示的却还是上一个版本的内容。 #

**Comment by NoahDragon** [comment]
可能是网络或浏览器cache所致。
