### ISSUE TITLE
install hexo-cli global. still not use in other disks.

### ISSUE THREAD

**Issue by zhenizhui** [hexojs/hexo#2613]
## Environment Info

Operating system
Win10

Node version(`node -v`):
v4.4.7

Npm version(`npm-v`):
3.10.6

## For BUG

I use `cnpm` to install `hexo-cli` and `hexo` global.

But when I enter D disks, start to `hexo init blog`, 

and the eror happens: I can't init my hexo blog in D disks but it works in C disks!

So, I wonder what is happening?

thx.

![error](https://user-images.githubusercontent.com/13503884/27169447-8303ee32-51dc-11e7-807d-017b6f187b5a.jpg)

**Comment by NoahDragon** [comment]
I didn't use mingw, but powershell and cmd works well on my Win machine.

**Comment by zhenizhui** [comment]
@NoahDragon hello, thank for you replay.It's very strange for me because this worked well several months ago! 

eh...

I try my best to find out what has happened. :)
