### ISSUE TITLE
the serial number of the article repeated

### ISSUE THREAD

**Issue by shadow000902** [hexojs/hexo#2615]
## Environment Info
![image](https://user-images.githubusercontent.com/3152878/27284369-f7095776-552a-11e7-99db-382a370d709b.png)

## For BUG
 1. set serial number for an article, and set read-more button
![image](https://user-images.githubusercontent.com/3152878/27284484-8dd34bf8-552b-11e7-97ee-0aad3db7050a.png)

## For question
Seeing in the pictures, the first serial number was been repeated.
![image](https://user-images.githubusercontent.com/3152878/27284580-f160b0e8-552b-11e7-83a8-3b6a49cc32a0.png)
![image](https://user-images.githubusercontent.com/3152878/27284659-50aa5838-552c-11e7-8a95-df4f3cadbdb8.png)

## For feature request
Can you fix this please? Thank you~

**Comment by NoahDragon** [comment]
Have you tried the solution here? https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list

add intend before `<!--more-->`.

**Comment by shadow000902** [comment]
Thank you, it works
i did this in the article, but did not did to ``<!--more-->``
