### ISSUE TITLE
Programmatically Generate Pages from JSON

### ISSUE THREAD

**Issue by bhu1st** [hexojs/hexo#2617]
I've a list of web pages defined in JSON file like this: 

 ```
     {
		"pages": [{
			"title": "Welcome",
			"content": "<WELCOME CONTENT>",
			"tags": "tags meta",
			"description": "description meta"
		}, {
			"title": "Contact Us",
			"content": "<CONTACT US CONTENT>",
			"tags": "tags meta",
			"description": "description meta"
		}]	
	}

```
How can I programatically generate pages from this JSON file during `hexo generate`? List of web pages can vary based on website.

**Comment by NoahDragon** [comment]
IMHO, why not write a script to parse this json into several markdown files?

**Comment by bhu1st** [comment]
@NoahDragon This is not only one website, I'm working on multiple websites each having similar JSON files that describes the list of web pages. Trying to find out if it's possible with hexo to generate all pages during generate script run. Basically, what I'm trying to achieve is feed similar JSON file as an input to hexo and generate websites as a result.

**Comment by NoahDragon** [comment]
I don't think hexo generator could do the job. Maybe you could take a look at the migrator. https://www.npmjs.com/package/hexo-migrator-rss
