### ISSUE TITLE
Does not show correctly when code block in list.

### ISSUE THREAD

**Issue by magic3584** [hexojs/hexo#2620]
## Environment Info

Node version(`node -v`): v7.2.0
Theme: Next.Muse
Hexo and Plugin version(`npm ls --depth 0`): 

hexo-site@0.0.0 /Users/wang/Documents/wang/blog
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0

## For BUG

It should show as:
### Title 1
some text here

1. step 1

    ``` ruby
    sudo dpkg -i chrome.deb
    sudo apt-get install -f
    ```   
     
2. step 2

     ``` ruby
     sudo apt-get install gdebi
     ```  
    
    Install with gdebi
    

### Title 2

but it was
![1](https://user-images.githubusercontent.com/6275110/27462984-32e6f086-57f7-11e7-8f2a-0ad5f095bb8c.png)

**Comment by tea3** [comment]
When I tried, no particular problems occurred. Do your code same with the following code?

```
some text here

1. step 1

    ```
    sudo dpkg -i chrome.deb
    sudo apt-get install -f
    ```

2. step 2

    ```
    sudo apt-get install gdebi
    ```
    install with gdebi
```

![test](https://user-images.githubusercontent.com/15667928/27464254-49abdbd2-5807-11e7-8d57-fb08ccc4d5f1.jpg)

**Comment by magic3584** [comment]
yeah, I did. Please see the source markdown [source_md](https://github.com/magic3584/blog/blob/master/source/_posts/%E9%85%8D%E7%BD%AEUbuntu-17-04.mdl) and the result page [result_page](http://www.lugick.com/2017/06/06/%E9%85%8D%E7%BD%AEUbuntu-17-04/)

**Comment by tea3** [comment]
I am watching the code with iphone. Probably the cause of the problem is that there are 5 spaces in your source_md . Please check your markdown file.

![img_8736](https://user-images.githubusercontent.com/15667928/27505024-82995bbc-58d0-11e7-9f01-c1bb8fa44e7a.PNG)

**Comment by magic3584** [comment]
@tea3 
Sorry to say, the same result.

**Comment by tea3** [comment]
@magic3584 
I checked it with my PC. Delete the space as shown in the image below.

![as](https://user-images.githubusercontent.com/15667928/27521584-af28fd38-5a59-11e7-8669-cf617ca7fe32.jpg)

**Comment by tea3** [comment]
@NoahDragon
If you put a blank line break after the code block, it seems that it can not render well.
Perhaps it is a bug in [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked).

![block](https://user-images.githubusercontent.com/15667928/27521921-c19b27ea-5a5c-11e7-8827-86766fd0c5f0.jpg)

**Comment by magic3584** [comment]
@tea3 
Code block shows well, but the list doesn't now.

**Comment by tea3** [comment]
@magic3584 
If possible, please display me the updated source_md and result_page .

**Comment by magic3584** [comment]
@tea3 
I updated the [source_md](https://github.com/magic3584/blog/blob/master/source/_posts/%E9%85%8D%E7%BD%AEUbuntu-17-04.md) and [result_page](http://www.lugick.com/2017/06/06/%E9%85%8D%E7%BD%AEUbuntu-17-04/).

**Comment by tea3** [comment]
@magic3584 
It seems that you can successfully display it by deleting all the space in the last line below.

```
1. 命令行

    ``` ruby
    sudo dpkg -i chrome.deb
    sudo apt-get install -f
    ```
        
```

This is a rare way of writing, so plug-ins may not be assuming it.

**Comment by magic3584** [comment]
@tea3 
Thanks for your patient and detailed help!

**Comment by NoahDragon** [comment]
@tea3 Thanks for pointing it out, I will check.
