### ISSUE TITLE
use {{ In code block，but <% raw %> <% endraw %>do not help

### ISSUE THREAD

**Issue by micorochio** [hexojs/hexo#2622]
I write "{{" and "}}" in"```" code block

then
```shell
Template render error: (unknown path) [Line 10, Column 60]
  unexpected token: {{
    at Object.exports.prettifyError
```
<% raw %> <% endraw %> do not help in code block

**Comment by NoahDragon** [comment]
<% raw %> <% endraw %> in code block is not working. This is a known issue. We are currently fixing it. 

Currently, you could use url encode `%7B%7B` to represent the `{{`.
