### ISSUE TITLE
source folder  didn't  have _drafts file /source資料夾裡找不到drafts檔案

### ISSUE THREAD

**Issue by 19uni94** [hexojs/hexo#2623]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

Help!
I step by step : 
$ hexo init <folder>
$ cd <folder>
$ npm install

but in source folder didn't  found _drafts folder and script folder
按照步驟操作，結果少了source和drafts檔案

img:
[http://ppt.cc/TxIYr](url)

**Comment by NoahDragon** [comment]
The image is showing the theme folder.

running `hexo new draft` will create _draft folder under source.

**Comment by 19uni94** [comment]
@NoahDragon : thx! i running hexo new draft  in source folder , the source folder didn't create _draft folder , but _post folder  have create  a new  drafts.md file.

how can i solution?

**Comment by 19uni94** [comment]
@NoahDragon  
  
I got it! thx!!!
