### ISSUE TITLE
c# code format highlight abnormal

### ISSUE THREAD

**Issue by yb199478** [hexojs/hexo#2625]
## Environment Info

Node version(`node -v`): v8.0

## For BUG

use hexo，When the class implements multiple interfaces, the code can not be highlighted：

In the .md file, enter the following code:

The code that caused the exception:
``` csharp
class Adaptor : ClassInheritanceTest , ICrossBindingAdaptorType
{
    public string name = "test";
}
```

Normal code: 
``` csharp
class Adaptor : ClassInheritanceTest
{
    public string name = "test";
}
```

![image](https://user-images.githubusercontent.com/12524356/27535822-e00461be-5a9e-11e7-9c12-52b96fb1a0e1.png)

![image](https://user-images.githubusercontent.com/12524356/27535879-12e79f7e-5a9f-11e7-9aff-8c927e446512.png)

**Comment by NoahDragon** [comment]
Hexo uses third-pard highlight plugin called highlightjs. There is really nothing Hexo can do to fix it.
Could you please try another highlight plugin, like https://github.com/ele828/hexo-prism-plugin ?

**Comment by yb199478** [comment]
(isagalaev/highlight.js)[https://github.com/isagalaev/highlight.js] Has fixed this problem, but hexo is not provided within the new version of highlight.js

**Comment by NoahDragon** [comment]
Maybe we could try to update the dependency version, and hope not breaking anything. 😄

**Comment by yb199478** [comment]
thank （≧∇≦）hop not breaking anything～
