### ISSUE TITLE
Hexo only rendering the first one post_link !!!!!

### ISSUE THREAD

**Issue by anxiaoyi** [hexojs/hexo#2628]
When using multiple `{% post_link sample_article %}` in a paragraph, Hexo only render the first one to the correct post link, instead of render all !

当在一个段落中多次使用 `{% post_link sample_article %}` 标签的时候，Hexo 竟然只渲染第一个为正确的链接，其它都没有渲染！

https://github.com/hexojs/hexo/issues/2257

**Comment by stevenjoezhang** [comment]
Can't reproduce in Hexo v4.2.0
