### ISSUE TITLE
Looping through site.tags and returning a result

### ISSUE THREAD

**Issue by krausekai** [hexojs/hexo#2629]
Is it possible to loop through site.tags and display them in a custom menu, instead of using list_tags()?

It seems that to loop through site.tags, it must be casted as an array:
```
<%  for (var i in site.tags.toArray()) { %>	

<%  } %>
```

The problem however, is that **i** cannot seem to return any items from the array.

This works perfectly (without toArray()) for theme.menu, for example.

Which is the correct way to list each item in Hexo for site.tags?

**Comment by tea3** [comment]
@krausekai  
How about this plugin ?
https://github.com/MikeCoder/hexo-tag-cloud

**Comment by krausekai** [comment]
Seems I was rather tired before! list_tags and CSS fixed the issue :)
