### ISSUE TITLE
Ignoring files from processing that are not required.

### ISSUE THREAD

**Issue by bhaskarmelkani** [hexojs/hexo#2632]
**Use Case:** The theme is a independent project/repository. The project has `node_modules` which are installed by the `package.json` in the project.
So hexo by defaults watches all the files inside the `theme` folder and it will process all the files including files in `node_modules`, `.git` folder.
This bloats the `models.Cache` in `db`(`db.json` file)  as it will have entries for every file  that are inside `themes` folder.
I want hexo to ignore these(`node_modules`, `.git`) files. This will reduce the build time as well as it will drastically decrease the size and memory required for in memory db and `db.json` file.

**Proposal:**
1. By default ignore files inside folders like, `node_modules`, `.git`, etc.
2. Add an option in config to provide glob expressions for files to ignore.

For approach 2, I have a [PR#2631](https://github.com/hexojs/hexo/pull/2631) .

**Comment by JLHwung** [comment]
Closed as #2631 is merged.

**Comment by bhaskarmelkani** [comment]
Hey,

I am still waiting for this change to be published to npm. :)

Thanks.

**Comment by NoahDragon** [comment]
@bhaskarmelkani by the end of this week, it should be on the npm. We would like to put another two PR into the new release.

**Comment by bhaskarmelkani** [comment]
That sound perfect. Thanks :)
