### ISSUE TITLE
hexo can't support {{}} in template

### ISSUE THREAD

**Issue by wufenfen** [hexojs/hexo#2634]
## For BUG

 

I got template render error unexpected token : }} in my posts.

Finally, I found the error part. It was "{{}}" in one of my posts. It seems that hexo doesn't support {{}} in template.

**Comment by NoahDragon** [comment]
The reason is that `{{}}` is part of nunjucks, which hexo is using it for tag plugins. Using raw tags could skip renderring nunjucks.

```
{% raw %}
{{}}
{% endraw %}
```
