### ISSUE TITLE
hexo安装不了

### ISSUE THREAD

**Issue by BlogForMe** [hexojs/hexo#2636]
$  npm install -g hexo-cli

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\hexo-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

## Environment Info
$ node -v
v6.11.0

$ npm ls --depth 0
C:\Users\Administrator
+-- hexo@3.3.7
`-- hexo-deployer-git@0.3.0

麻烦看下什么情况

**Comment by NoahDragon** [comment]
只是警告，一切正常。
