### ISSUE TITLE
求大神教教我， 怎么关掉Hexo的邮件提醒，  我的天， 每天我都收到几十条hexo的问题提醒。。。。。

### ISSUE THREAD

**Issue by MJoeyGitHub** [hexojs/hexo#2638]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by popomore** [comment]
右上角有个 watch

**Comment by suhaotian** [comment]
setting 里面取消掉通知和邮箱的关联
