### ISSUE TITLE
插入asset img后，图片下方总会自动插入一空行，如何解决？

### ISSUE THREAD

**Issue by sd44** [hexojs/hexo#2639]
hexo-cli: 1.0.3
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.7.0
node: 8.1.3
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

我的网站：http://sd44.github.com
theme: https://github.com/wzpan/hexo-theme-freemind

**Comment by NoahDragon** [comment]
看了下网站感觉挺正常的，能否截图说明下？

**Comment by sd44** [comment]
感谢您参与开发的hexo ^_^~太好用了。


如我在新文档中使用如下代码：
`
紧贴测试图片上方一行的文字
![](01.jpg ) 
紧贴测试图片下方一行的文字
`

在生成的网页中，有的图片下方会增加一行空行，有的则不会。
会增加空行的网页：http://sd44.github.io/2017/07/07/%E7%A4%BE%E4%BC%9A%E5%AD%A6%E5%93%B2%E5%AD%A6%E7%90%86%E8%AE%BA%E5%B0%8F%E8%AF%8D%E5%85%B8%E2%80%94%E2%80%94%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0/#more

不会增加空行的网页：
http://sd44.github.io/2017/07/07/%E6%91%84%E5%BD%B1%E5%A4%A7%E5%B8%88%E5%8D%B0%E8%B1%A1%EF%BC%88%E5%85%AB%EF%BC%89%E2%80%94%E2%80%94-Stephen-Shore/#more

（测试完后，可将以上链接删除。）

**Comment by NoahDragon** [comment]
很高兴能对Hexo有这么高的评价。

看了下，其实如果有文字的，图片前后都会多加一行的。但不知为何（如下图所示），图片前的那一行并未显示出来。

![image](https://user-images.githubusercontent.com/5704064/27969487-06a03e74-6319-11e7-8d89-b544179a6a43.png)

**Comment by sd44** [comment]
例子一：图片上下均有空行的效果
`<p>测试图片1上方</p>`
`<p><img src="/01.jpg" alt=""> </p>`
`<p>测试图片下方</p>`

例子二：图片上下均无空行的效果
`<p>测试图片2上方<br>`
`<img src="/01.jpg" alt=""><br>测试图片2下方</p>`

例子三：图片上方有空格，下方无空行的效果
`<p>测试图片3上方</p>`
`<p><img src="/01.jpg" alt=""><br>测试图片3下方</p>`

例子四：图片上方无空格，下方有空行的效果
`<p>测试图片4上方<br>`
`<img src="/01.jpg" alt=""> </p>`
`<p>测试图片4下方</p>`

结论：
`如果文字与图片之间无空行，则文字和图片被<p>包括起来，<br>换行。`
`如果文字与图片之间有空行，则文字和图片分别被<p>包括起来，`
`因<br>与<p>的不同，造成不同的效果。`
我不了解html或css，表述不清，抱歉。。。

**Comment by NoahDragon** [comment]
的确，至少应该保证前后格式一致。具体是哪一个部件发生的问题，还需要调查下。

**Comment by sd44** [comment]
谢谢积极关注这个问题 ^_^

根据源代码，我不负责任地猜想下这情况是怎样发生的，希望有用，您可能也早想到了：

感觉hexo像分块来解析全文，生成标记。紧挨着的多个相连非空行，被认为是一个block，用p标签包括起来，用br标签处理上下紧邻两行。

如果不是紧挨着，就各自成p标签。

都是文字的情况下，符合逻辑。
但是插入图片行和文字行混合的情况下，就会导致p和br标签的混乱。


希望有用。。。。我描述能力太差。。也不懂技术。

**Comment by JLHwung** [comment]
Hi sd44, actually I think this is the default behavior of underlying hexo renderer [marked](https://github.com/chjj/marked). You can check the behavior in [this snippet](https://runkit.com/jlhwung/5960f28c23905b0012f13cc4).

I don't think we can have lot of control on the output of `marked` since typically we don't do any smart post-transformation from the renderer. That saying, if any inconsistent HTML transform happens, we might need to raise an issue to marked.
