### ISSUE TITLE
EC2 - sudo: hexo: command not found

### ISSUE THREAD

**Issue by wukong2** [hexojs/hexo#2642]
hi, can help suggest below problem. thanks

[ec2-user@ip-172-31-22-4 blog]$ sudo hexo server -p 80
sudo: hexo: command not found
[ec2-user@ip-172-31-22-4 blog]$ pwd
/home/ec2-user/blog

btw, "hexo server" is good to execute
[ec2-user@ip-172-31-22-4 blog]$ hexo server
(node:6244) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.

---
here is setting up process
1> fresh Linux EC2 instance

sudo yum install git-core
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
nvm install stable
npm install -g hexo-cli

hexo init blog
cd blog
npm install

## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by wukong2** [comment]
some other info...

[ec2-user@ip-172-31-22-4 blog]$ node -v
v8.1.3
[ec2-user@ip-172-31-22-4 blog]$ nvm ls
->       v8.1.3
default -> stable (-> v8.1.3)
node -> stable (-> v8.1.3) (default)
stable -> 8.1 (-> v8.1.3) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.3 (-> N/A)
lts/boron -> v6.11.0 (-> N/A)

**Comment by JLHwung** [comment]
`hexo` is not supposed to start with root privilege. Simply run `hexo server`

`DeprecationWarning: fs.SyncWriteStream is deprecated.` is duplicates with #2598

**Comment by sd44** [comment]
it's about sudo secure_path.

see:
https://superuser.com/questions/927512/how-to-set-path-for-sudo-commands

**Comment by wukong2** [comment]
can't open port 80 without root privilege. hexo server is working fine.

**Comment by JLHwung** [comment]
> can't open port 80 without root privilege.

Non-root process can not bind port < 1000.

hexo server is not supposed to run on production environment. Please use nginx to serve the `public` directory. See https://www.nginx.com/resources/admin-guide/serving-static-content/

**Comment by wukong2** [comment]
@JLHwung thanks bro.
It's not for public.
just play it in EC2... find a solution, share with you
I can install hexo via root privilege, change owner to ec2-user. 
then run  _sudo hexo server -p 80_

**Comment by JLHwung** [comment]
I am glad you solved your issues.
Personally I don't recommend to install node modules on root privilege.

If you insist, check that `sudo echo $PATH` and `echo $PATH` returns same result. If not, try to add it to $PATH.

**Comment by aamehedi** [comment]
> > can't open port 80 without root privilege.
> 
> Non-root process can not bind port < 1000.
> 
> hexo server is not supposed to run on production environment. Please use nginx to serve the `public` directory. See [nginx.com/resources/admin-guide/serving-static-content](https://www.nginx.com/resources/admin-guide/serving-static-content/)

I think this should be documented somewhere.

**Comment by musicin3d** [comment]
Another workaround...

    sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``

This is allows node to listen on port 80. I _think_ it allows node to listen on any port. 

Obviously this is not recommended. Not only is it an invasive system modification that makes it a little less secure, but it also makes it easier to run hexo server in production. BUT in my case, I'm running hexo server with hexo-admin on a private server, and I _really_ want it on port 80.
