### ISSUE TITLE
error setting certificate verify locations

### ISSUE THREAD

**Issue by nickwilde6** [hexojs/hexo#2648]
FATAL fatal: unable to access 'https://github.com/nickwilde6/nickwilde6.github.io.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

请问这个怎么办

**Comment by tea3** [comment]
Do you ask that you can't push for  [nickwilde6/nickwilde6.github.io](https://github.com/nickwilde6/nickwilde6.github.io/) repository ?

**Comment by nickwilde6** [comment]
yes

**Comment by NoahDragon** [comment]
Have you tried manually push to github?

**Comment by tea3** [comment]
@nickwilde6 
Is not the following article useful?
https://stackoverflow.com/questions/38939112/github-push-failed-failed-with-error-fatal-unable-to-access
