### ISSUE TITLE
How to show the author under each article?

### ISSUE THREAD

**Issue by weixingdeng** [hexojs/hexo#2649]
## For question

I want to show the author on each article, just like the categories.

What should I do?

thank you

**Comment by NoahDragon** [comment]
You could modify the theme files to achieve this goal.

**Comment by bennyn** [comment]
This is what I use in my EJS templates to show the author per article:

```ejs
<% if (page.author){ %>
  <p id="header-page-author">Written by <%= page.author %></p>
<% } %>
```
