### ISSUE TITLE
Chrome auto downloads posts when the permalink doesn't end with '/' ot '.html'

### ISSUE THREAD

**Issue by bcol23** [hexojs/hexo#2650]
## Environment Info

Node version(`node -v`): 

> v6.11.0

[site._config.yml.txt](https://github.com/hexojs/hexo/files/1145498/site._config.yml.txt)

[theme._config.yml.txt](https://github.com/hexojs/hexo/files/1145500/theme._config.yml.txt)

Hexo and Plugin version: 

> +-- hexo@3.3.7
> +-- hexo-generator-archive@0.1.4
> +-- hexo-generator-category@0.1.3
> +-- hexo-generator-index@0.2.1
> +-- hexo-generator-tag@0.2.0
> +-- hexo-renderer-ejs@0.2.0
> +-- hexo-renderer-marked@0.2.11
> +-- hexo-renderer-stylus@0.3.3
> `-- hexo-server@0.2.1

## For BUG

 1. BUG description :

When including ":category" int the permalink, like `permalink: :category/:title`, Chrome (59.0.3071.115 (64-bit)_) will auto download the posts if clicking (I've cleared the cache and restarted windows but there's no help), like this

![chrome download](https://user-images.githubusercontent.com/12250696/28172214-4162c938-67eb-11e7-986f-0c526ea7e665.png)

I believe it worked fine yesterday, and now it works only if `permalink: :category/:title.html` or `permalink: :category/:title/`. What's more, I've tested that there's no such problem with https:// and Edge (Win10).

 2. The way to reproduce

Just test this with localhost (sudo hexo s) and with Chrome
[test.zip](https://github.com/hexojs/hexo/files/1145558/test.zip)

 3. Log with hexo <command> --debug

[debug.log.txt](https://github.com/hexojs/hexo/files/1145555/debug.log.txt)

**Comment by NoahDragon** [comment]
This is a known issue. The permalink should end with `/`.

If you would like the html shows in URL, please follow the manual change in https://github.com/hexojs/hexo/issues/2647

**Comment by bcrix** [comment]
I believe it's better if you can make some notices for the third example, thanks
![examples](https://user-images.githubusercontent.com/12250696/28177737-0d10ca3e-67fc-11e7-8103-efcc8d1b55b5.png)

**Comment by NoahDragon** [comment]
I see. I never noticed the document before. Thanks for pointing it out.

**Comment by stevenjoezhang** [comment]
The document is still not updated: https://hexo.io/docs/permalinks
