### ISSUE TITLE
Deploying into a subfolder

### ISSUE THREAD

**Issue by IgnacioCastro** [hexojs/hexo#2654]
Using Hexo 3.3.3, and not using Github Pages, just deploy to a repo and use with Netlify.
I want Hexo to deploy to a "blog" folder on my repo, I tried all the options on the issues tab but I can't make it work. `hexo generate --deploy` just deployes into the root folder of my repo
I can't use gh-pages method as i'm not using Github Pages

**Comment by NoahDragon** [comment]
Hexo couldn't deploy to a folder, it can be deployed to a branch.

**Comment by IgnacioCastro** [comment]
Can I link a branch to a folder???

**Comment by NoahDragon** [comment]
Sorry, I'm not familiar with the Netlify. Could you please contact them regarding this issue?

**Comment by tea3** [comment]
@IgnacioCastro 
I recently tried deploy to Netlify . Generaly , Netlify CI build data of hexo's site with github or gitlab or bitbucket. Also you can upload directly to Netlify with [hexo-deployer-netlify](https://github.com/piktaszuikis/hexo-deployer-netlify) .
