### ISSUE TITLE
localhost:4000 can't access, change port also doesn't work

### ISSUE THREAD

**Issue by cwjie0229** [hexojs/hexo#2655]
## Environment Info

配置
[hexo 配置](http://onnq25vz1.bkt.clouddn.com/111.png)

**Comment by NoahDragon** [comment]
能详细描述下么？

**Comment by cwjie0229** [comment]
今天有个小伙伴问hexo安装的一些问题，我按照平常的步骤来给他远程安装

1、npm install -g hexo

2、hexo init

3、hexo generate

报错：(node:19344) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated

4、hexo server

报错： (node:19344) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated

4步骤之后显示
$ hexo server
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.

解决错误：

npm install hexo-fs --save


运行http://localhost:4000/ 浏览器不显示，以为是端口错误，后来换了端口号，还是不显示


hexo配置
[图片](http://onnq25vz1.bkt.clouddn.com/111.png)

**Comment by JLHwung** [comment]
@NoahDragon I suggest we release 3.3.8 asap. Smaller release brings down the delivery risk.

**Comment by NoahDragon** [comment]
@cwjie0229 请试下下载最新hexo 3.3.8版本，看能否解决问题。

**Comment by zegal-cn** [comment]
> hexo -v
hexo: 3.3.8
hexo-cli: 1.0.3
os: Windows_NT 6.1.7601 win32 ia32
http_parser: 2.7.0
node: 6.11.1
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k

browser didn't responded.

**Comment by NoahDragon** [comment]
@zegal-cn Could you please create a new issue and elaborate?
