### ISSUE TITLE
How to make font greater?

### ISSUE THREAD

**Issue by haicoder** [hexojs/hexo#2660]

**Comment by tea3** [comment]
@haicoder 
Do you want to enlarge characters on pages generated from hexo ? For example in hexo-theme-landscape you can enlarge the letters by editing the following.
https://github.com/hexojs/hexo-theme-landscape/blob/master/source/css/_variables.styl#L31

Please check the `./themes/source` .

**Comment by connor11528** [comment]
You can use css...
```
* {
 font-size: 100px
}
```
Or Cmd plus to make font on your screen bigger

This issue can be closed.
