### ISSUE TITLE
hexo+github blog had a fatal

### ISSUE THREAD

**Issue by Crazier-qi** [hexojs/hexo#2661]
when i code the "npm install " ,had this fatal.

![image](https://user-images.githubusercontent.com/16120478/28489827-d8647718-6efe-11e7-93de-2d71d737d552.png)

when i running the "hexo init",have happend the same problem,

![image](https://user-images.githubusercontent.com/16120478/28489837-13daff06-6eff-11e7-8d0a-ea82baceba00.png)
can anyone tell me what is it?
how can i solve this problems?
thank you for you help.

**Comment by NoahDragon** [comment]
I believe it is caused by git. Could please run `git clone https://github.com/hexojs/hexo-starter.git` to see if it works?

**Comment by Crazier-qi** [comment]
it doesn't work by https，but when i use the protocol ssh,it's useful.

**Comment by NoahDragon** [comment]
Please check the git configurations. 

A temp work around could be to clone the above repo and then run `npm install` inside the folder.
