### ISSUE TITLE
Hosting .md files on a seperate machine from Hexo server

### ISSUE THREAD

**Issue by nickmisasi13** [hexojs/hexo#2662]
## For question

Is there already functionality for the md files that are turned into blog posts to be hosted on a separate server? This might be very niche functionality, but I have been driven to require this feature, and have not really seen anything on it.

**Comment by NoahDragon** [comment]
Correct me if I'm wrong, do you mean to put the source ".md" files on a machine, and the generated ".html" on another one?

**Comment by nickmisasi13** [comment]
I mean to have the Hexo Server, as well as the rendering framework hosted on machine A, and the md blog files sitting on machine B. In the event you request a particular blog page from machine A, it will pull that page from machine B, render the html from the markup, and send the page to the requesting client.

**Comment by NoahDragon** [comment]
I got your point. However, this isn't a static website anymore, it is exactly what dynamic CMS doing, instead of fetching ".md" files, they retrieve data from database.
