### ISSUE TITLE
Custom home page being ignored by hexo server

### ISSUE THREAD

**Issue by knafteN** [hexojs/hexo#2663]
## Environment Info

Node version(`node -v`): 8.2.0

All other files can be seen in repository: https://github.com/knafteN/hexo-with-custom-startpage

## Goal
Having a custom home page and the posts on `/blog`.

## For question
I just initialized a fresh repository with hexo 3.2.0. I deleted the default theme and added a super minimalistic one. My goal is to have the simplest variant of having a custom start page page on `/` and the blog on `/blog`.

I changed the index_generator:
`index_generator:
  path: '/blog'
  per_page: 10
  order_by: -date`

and I added the custom startpage: `/source/index.md`

The generated files in `/public` look ok, but when I start the hexo server, I can't access the root URL `/` I will instantly be redirected to `/blog`. Any ideas how to fix this? Please see the repository I mentioned for further details. Thank you!

**Comment by NoahDragon** [comment]
Have you tried to change the following in config file:
```yaml
index_generator:
  path: ''
  per_page: 10
  order_by: -date
```

**Comment by knafteN** [comment]
@NoahDragon This doesn't work at all. The root URL `localhost:4000` still redirects to `localhost:4000/blog` but both URLs are 404 not found.
In my repository I can at least navigate to  `localhost:4000/blog`

Maybe `git clone https://github.com/knafteN/hexo-with-custom-startpage` and see for yourself
