### ISSUE TITLE
Can't render post with swig code in it correctly

### ISSUE THREAD

**Issue by wangfys** [hexojs/hexo#2664]
I use NexT as theme and I want modify the template to make my blog look better. So I changed the template and write a post to record what I did.
I added the following code in my post in order to show what change I made 
`{% if page.reward and (theme.alipay or theme.wechatpay) %}`

Then I used `hexo s` and got an error. I think maybe it's a funny problem that the renderer try to render this `.md` file and find an `if`. It shows the error message like this:
```
(node:8496) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  parseIf: expected elif, else, or endif, got end of file
    at Object.exports.prettifyError (/home/wangfys/blog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/home/wangfys/blog/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/home/wangfys/blog/node_modules/nunjucks/src/environment.js:327:21)
    at /home/wangfys/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/home/wangfys/blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/wangfys/blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/wangfys/blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/home/wangfys/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/wangfys/blog/node_modules/hexo/lib/hexo/post.js:266:16)
    at /home/wangfys/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/home/wangfys/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/wangfys/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/wangfys/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/wangfys/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/wangfys/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/wangfys/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/wangfys/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/wangfys/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by NoahDragon** [comment]
You didn't use the swig syntax correctly. Please follow the other `if else` sample in the theme template.

**Comment by wangfys** [comment]
This is the original `reward.swig` file in the NexT theme.
```
{% if theme.alipay or theme.wechatpay %}
  <div style="padding: 10px 0; margin: 20px auto; width: 90%; text-align: center;">
    <div>{{ theme.reward_comment }}</div>
    <button id="rewardButton" disable="enable" onclick="var qr = document.getElementById('QR'); if (qr.style.display === 'none') {qr.style.display='block';} else {qr.style.display='none'}">
      <span>赏</span>
    </button>
    <div id="QR" style="display: none;">
      {% if theme.wechatpay %}
        <div id="wechat" style="display: inline-block">
          <img id="wechat_qr" src="{{ theme.wechatpay }}" alt="{{ theme.author }} WeChat Pay"/>
          <p>微信打赏</p>
        </div>
      {% endif %}
      {% if theme.alipay %}
        <div id="alipay" style="display: inline-block">
          <img id="alipay_qr" src="{{ theme.alipay }}" alt="{{ theme.author }} Alipay"/>
          <p>支付宝打赏</p>
        </div>
      {% endif %}
    </div>
  </div>
{% endif %}
```

In fact I only changed the first line like this and all the other lines are the same.
```
{% if page.reward and (theme.alipay or theme.wechatpay) %}
```

Everything works fine before I post the article about how to change the swig file with such a line in the `.md` file
```
`{% if page.reward and (theme.alipay or theme.wechatpay) %}`
```

**Comment by NoahDragon** [comment]
Probably the swig doesn't support bracket. Could you please try the following:

```
{% if page.reward %}
    {% if theme.alipay or theme.wechatpay %}
    {% endif %}
{% endif %}
```

**Comment by wangfys** [comment]
I've tried this once and it works fine. (And it also works fine with brackets. I guess swig support brackets, at least using the renderer provided by Hexo)
And I means almost everything works fine with both `swig` file (the original one and the one I modified).  
The only thing that works incorrectly is when I tried to put a piece of code from a swig file into a code block. I think the renderer should treat this piece of code as common code block (because I use the markdown style to define a code block), but it seems that the renderer treat this piece as a template (and it's only a broken piece, so it failed). I guess the renderer render swig templates before rendering markdown to HTML, so the renderer doesn't know it's a code block.

**Comment by wangfys** [comment]
I think it's similar to such a case:
Some text editor provide an unsafe 'Find and Replace' function. If I want to replace "A" to "AA", these type of editor will keep adding "A" behind the original "A".

I don't know which swig renderer Hexo is using. But I think it's something like this:

The renderer first adds all the articles (in markdown style) to index page. Then it follows the rule of the swig template to add  different css style. After that, it change the markdown style into HTML style. So the code block in the markdown is treated as swig template first, not just some text. Then it throw an error and doesn't have the chance to render the markdown into HTML

**Comment by NoahDragon** [comment]
Because in the markdown file, the tag/filter also uses the swig to render, like the raw tag in my sample. Could you please the Hexo source code, it will be better to investigate?

**Comment by wangfys** [comment]
Thanks a lot for the sample. I didn't notice that you edit the sample at once.

And my friends also help me find another solution from a question on stackoverflow ([how do i insert this code into hexo markdown](https://stackoverflow.com/questions/35441138/how-do-i-insert-this-code-into-a-hexo-markdown)) that use three backticks to define a code block can prevent such errors. It's also a very strange thing that use three backticks can work but using indents or just one backtick failed.

So can this two solutions be added to some where in the documentation? I didn't find solutions in the documentation so I came here to ask. (Such problems are hard to use some key words to search I think. I use 'swig' and 'hexo' as key words and find nothing. But in fact there is similar problems on stackoverflow and also in the issues.)

By the way... I don't quite understand your meaning. Share which part of the Hexo source code? I haven't read the Hexo source code yet (I just guess why this pheonmenon happens) and in fact it's my first time to use Hexo just a few days ago.

**Comment by NoahDragon** [comment]
Sorry for the misunderstanding, the hexo source code, I mean the website source code.
