### ISSUE TITLE
hexo d的时候提示credential-stor指令找不到...

### ISSUE THREAD

**Issue by rakuyoMo** [hexojs/hexo#2666]
## For question

hexo d的时候有个提示，credential-stor is not a git command。最后好像差了一个字母，但是找不到这个怎么修改...

之前也是，但是以前稍微停顿一两秒就可以hexo d成功，今天下午却卡在这里怎么也提交不上去了....不知道和这个报错有没有关系呀。

**Comment by NoahDragon** [comment]
请问是使用hexo deployer git么？可否运行`hexo d --debug`？

**Comment by rakuyoMo** [comment]
> 请问是使用hexo deployer git么？可否运行hexo d --debug？

可以运行，我昨天又尝试了一下使用命令`git config --global help.autocorrect -1`，之后还是会有如下这个警告，但是`hexo d`成功推到git上了。

WARNING: You called a Git command named 'credential-stor', which does not exist.
Continuing under the assumption that you meant 'credential-store'

在运行`hexo d --debug`之后，依然有上面这个警告。

**Comment by NoahDragon** [comment]
很奇怪的问题，我这里无法重现。git deployer也并没有使用credential-*的命令。

不过既然无影响，先关闭此Issue。
