### ISSUE TITLE
hexo中的huno主题下如何为新建page添加文章

### ISSUE THREAD

**Issue by Crazier-qi** [hexojs/hexo#2669]
hexo new name 都会将文章自动新建到source中的 _post 文件夹中在首页显示。
但是我现在新建了一个页面codeReview，想将文章放在这个页面下面应该怎么操作？

**Comment by NoahDragon** [comment]
Is `hexo new codeReview <title>` you are looking for? https://hexo.io/docs/writing.html#Scaffolds

**Comment by Crazier-qi** [comment]
i mean. i had run the command "hexo new page codeReview"so there is a new page named codeReview. and i want to create new article  in the page of codeReview. i don't know how to do that. coz the nomal "hexo new name" would create file in the _post.

**Comment by NoahDragon** [comment]
You could create a codeReview scaffolds under the `source/scaffolds/`. Then run `hexo new codeReview <title>` should work.
