### ISSUE TITLE
修改分享按钮，但是浏览器屏蔽了分享按钮的内容

### ISSUE THREAD

**Issue by KnightMobile** [hexojs/hexo#2671]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question
可以用中文？ 我修改了分享按钮，代码 [HEXO]\themes\landscape\source\js\script.js
下面始于第 54  行
```
      var html = [
        '<style> a {text-decoration:none} </style>',
        '<div id="' + id + '" class="article-share-box">',
            '<input class="article-share-input" value="' + url + '">',
            '<div class="article-share-links">',
              '<a class="article-share-weibo" target="_blank" title="分享到微博" href="http://service.weibo.com/share/share.php?url=' + encodedUrl + '"></a>',
              '<a class="article-share-qzone" target="_blank" title="分享到QQ空间和朋友网" href="https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=' + encodedUrl + '"></a>',
              '<a class="article-share-qq" target="_blank" title="分享给QQ好友或群组" href="http://connect.qq.com/widget/shareqq/index.html?url=' + encodedUrl + '"></a>',
              '<p align="center"><img src="https://api.imjad.cn/qrcode?text=' + encodedUrl + '&logo=&size=200&level=M&bgcolor=%23ffffff&fgcolor=%23000000"></p>',
            '</div>',
        '</div>'
      ].join('');
```
上传到网站有效果，但是 EDGE 浏览器提示说有不安全内容，并且那个”share“按钮点击没反应。只有选择浏览器里选择 ”See all content" 后点击“share”按钮才有反应，弹出的内容是想要的效果。能告诉我怎么做才能让浏览器不屏蔽“share”按钮么？

**分享按钮定制，添加二维码。 https://knightmobile.github.io/ **

**Comment by JLHwung** [comment]
You can check the console in your browser.

> The page at 'https://knightmobile.github.io/' was loaded over HTTPS, but requested an insecure script 'http://apps.bdimg.com/libs/jquery/2.0.3/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

Please include jquery from a https cdn to see if this issue can be reproduced.

**Comment by KnightMobile** [comment]
Wow, really fast, solved

**Comment by JLHwung** [comment]
You are very welcome.

**Comment by KnightMobile** [comment]
thanks, a lot !
