### ISSUE TITLE
hexo d

### ISSUE THREAD

**Issue by dzzxjl** [hexojs/hexo#2673]
hexo hexo d --debug
08:25:59.124 DEBUG Hexo version: 3.3.8
08:25:59.127 DEBUG Working directory: ~/hexo/
08:25:59.231 DEBUG Config loaded: ~/hexo/_config.yml
08:25:59.241 DEBUG Script loaded: themes/landscape/scripts/fancybox.js
08:25:59.243 DEBUG Plugin loaded: hexo-generator-category
08:25:59.244 DEBUG Plugin loaded: hexo-generator-archive
08:25:59.246 DEBUG Plugin loaded: hexo-generator-index
08:25:59.247 DEBUG Plugin loaded: hexo-generator-tag
08:25:59.249 DEBUG Plugin loaded: hexo-renderer-ejs
08:25:59.308 DEBUG Plugin loaded: hexo-server
08:25:59.309 DEBUG Plugin loaded: hexo-renderer-stylus
08:25:59.314 DEBUG Plugin loaded: hexo-renderer-marked
08:25:59.318 DEBUG Database saved

无法提交至git，请问是什么原因

**Comment by NoahDragon** [comment]
是一直卡在这了么？有什么错误信息么？

**Comment by dzzxjl** [comment]
问题已解决，还是_config文件的配置问题，deploy那个地方配置错误，谢谢
