### ISSUE TITLE
How to highlight python code in posts?

### ISSUE THREAD

**Issue by sunjiayu12** [hexojs/hexo#2674]
## For question

Is there a list of supported code highlight in hexo posts? 

I mean, in hello-world post, there is bash code between ` ``` bash ` and ` ``` `

And can I use ` ``` python ` and ` ``` cplusplus ` to highlight python or C++ code? 

Thank you!

**Comment by tiexo** [comment]
language list：https://github.com/isagalaev/highlight.js/tree/master/src/languages
