### ISSUE TITLE
breaked after install hexo-deployer-git

### ISSUE THREAD

**Issue by guotie** [hexojs/hexo#2682]
## Environment Info

Node version(`node -v`): v8.1.2

windows 10

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

 1. BUG description
Before install hexo-deployer-git, everything works ok! After 
```
npm install hexo-deployer-git --save
```
every hexo command return error:
```
> hexo -v
ERROR Local hexo not found in E:\projects\hr\tiege
ERROR Try running: 'npm install hexo --save'
> hexo server
ERROR Local hexo not found in E:\projects\hr\tiege
ERROR Try running: 'npm install hexo --save'
```

 2. The way to reproduce
just after hexo init site,  install the plugin hexo-deployer-git 

 3. Log with hexo <command> --debug
```
> hexo server --debug
03:39:04.780 ERROR Local hexo not found in E:\projects\hr\tiege
03:39:04.780 ERROR Try running: 'npm install hexo --save'
```

**Comment by NoahDragon** [comment]
Have you installed hexo globally?

**Comment by guotie** [comment]
No.

**Comment by NoahDragon** [comment]
You have to use `npm i -g hexo-cli` to install hexo globally.

**Comment by guotie** [comment]
I have install hexo-cli globally.

**Comment by guotie** [comment]
just use following step, this problem can reproduce:

```
npm i g hexo-cli
hexo init blog
cd blog
hexo server
Ctrl + C

npm install hexo-deployer-git --save

```

**Comment by NoahDragon** [comment]
Please run `npm install` again, this will solve the issue. I think the problem is the `hexo init` uses yarn to install dependecies, but  `npm install hexo-deployer-git --save` removes most of them.
