### ISSUE TITLE
tags and categories display have abnormal behaviour when use hexo server

### ISSUE THREAD

**Issue by H-ZeX** [hexojs/hexo#2683]
## Environment Info
hexo: 3.3.8
hexo-cli: 1.0.3
os: Linux 4.10.0-28-generic linux x64
http_parser: 2.7.0
node: 8.2.1
v8: 5.8.283.41
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

Theme:
theme is "clean blog"

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.3.8
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
## For BUG
- I delete the source/tags and source/categories folds, and all tags, categories use in the post
- run `hexo clean` and `hexo g`, `hexo server`
- reflesh localhost:4000
howerver, I can see the tags and categories I had deleted.
when i use `hexo server -s`, it is normal.
and when I `hexo new post xxx`, use new tags, the abnormal behaviour disappear.
i guess that it may because the hexo server don't check whether tags and categories are changed until there are new post used.

**Comment by NoahDragon** [comment]
I believe it may cause by the cache. Normally, the `hexo server` will render all posts on the fly.
