### ISSUE TITLE
Add generated post route to menu

### ISSUE THREAD

**Issue by bhu1st** [hexojs/hexo#2685]
On a migrator plugin I am creating pages with following code.

```
var data = {
  title: "Hello",
  date: "2017-07-27",
  content: "Sample page content",
  layout: 'page'
};
post.create(data, true);
```

How can I dynamically add route to this page in site menu after post.create?

**Comment by tea3** [comment]
@bhu1st 
Do you want to make a menu of site ? Is it impossible to create a menu with hexo after migrate?

**Comment by bhu1st** [comment]
@tea3 Yes, I want to add the link to the page being generated in menu of the site. It is not convenient to go add each pages in menu manually after migrate. Thanks for reply.
