### ISSUE TITLE
Hexo custom generated routes are not included in sitemap

### ISSUE THREAD

**Issue by alexjoverm** [hexojs/hexo#2686]
## Environment Info

Node version(`node -v`):

v7.5.0

Hexo and Plugin version(`npm ls --depth 0`): 

├── hexo@3.2.2
├── hexo-algolia@1.1.0
├── hexo-browsersync@0.2.0
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.0
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-prism-plugin@2.0.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-jade@0.3.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
├── hexo-server@0.2.0
├── hexo-tag-twitter@1.0.0
└── hexo-util@0.6.1

## For BUG

I have some custom generated urls using a generator:

```javascript
hexo.extend.generator.register('serie', function(locals) {
  return formatSeries(locals)
    .map(serie => ({
        path: 'series/' + serie.slug + '/index.html',
        data: serie,
        layout: 'serie'
    }))
})
```

Everything works correctly, except these routes are not added to the sitemap.  What's the problem in here? How can we solve this? I could try to help with a PR if necessary

**Comment by NoahDragon** [comment]
Base on the hexo-generator-sitemap, the sitemap is only based on the posts. Probably, you could modify the sitemap generator to support customized routes.

https://github.com/hexojs/hexo-generator-sitemap/blob/master/lib/generator.js
