### ISSUE TITLE
Computer crash, can not restore the file. Is there any way to get it back?

### ISSUE THREAD

**Issue by alpha87** [hexojs/hexo#2690]
Thanks.

**Comment by tea3** [comment]
@alpha87 
Is the following article helpful ?
http://www.infohq.com/Computer/Recover_From_Windows_System_Crashes.html

**Comment by NoahDragon** [comment]
Is your Hexo website still online and the rss enabled? If so, you could use the migrator tools to download your posts to Hexo again. https://github.com/hexojs/hexo-migrator-rss
