### ISSUE TITLE
CSS doesn't load in GitHub Pages or other Hosting Site

### ISSUE THREAD

**Issue by ondairos** [hexojs/hexo#2691]
Greetings i have used hexo to generate  a new blog. All is working well in my local disk folder when i run it on local host. CSS loads fine i see the Blog as it's meant to be.
When i upload it in GitHub and then start the github page it displays only the HTML and no CSS! I have destroyed the blog 2 times. I have updated the npm and git libraries.
I use windows 10.

Thanks

**Comment by tea3** [comment]
@ondairos 
Can I upload pages again to github? If you can see the data, I think you can investigate the cause.

**Comment by ondairos** [comment]
Yeah it actually is different i fixed it! Thanks for the answer.
