### ISSUE TITLE
Why not add daemon for hexo to avoid load plugin every time?

### ISSUE THREAD

**Issue by cpselvis** [hexojs/hexo#2692]
## For feature request

After execute a command, hexo will exit.
```
    return hexo.call(cmd, args).then(function() {
      return hexo.exit();
    }).catch(function(err) {
      return hexo.exit(err).then(function() {
        // `hexo.exit()` already dumped `err`
        handleError(null);
      });
    });
```

When user type a new command, hexo will load internal and external plugins once again. I think it's not so efficient. Why not add daemon for hexo? If this feature is supported, hexo don't need load plugins each time when user input a command in console.

**Comment by NoahDragon** [comment]
Usually, the users only run Hexo command once if the website has setup and stable. If using the daemon, we were added a new command and requested users to destroy the daemon after each usage.

Although it may be a pain while debugging Hexo, I don't feel the loading speed is unacceptable on my machine.
