### ISSUE TITLE
How to render single page?

### ISSUE THREAD

**Issue by snovey** [hexojs/hexo#2694]
## Environment Info

Node version(`node -v`):8.2.1

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0

## For question

Hi, there.
I am making a theme. and I want to separate tags into a single page.
I create file `tag.ejs` at `theme/my-theme/layout/`, and this template will render path `my-site/tags/some-tag`.
Now, I want to make a tag cloud page, I want to render path `my-site/tags`.
What should I do?

**Comment by tea3** [comment]
@snovey 
[hexo-generator-single-page](https://github.com/dotimpact/hexo-generator-single-page) is useful ? 

### command

```
$ npm install --save git+https://git@github.com/dotimpact/hexo-generator-single-page.git
$ hexo new tag-cloud my-tag-cloud-page
```

### _config.yml

```
single_page:
  - tag-cloud
```

### tag-cloud.ejs

```
<h2>tag cloud</h2>
<% if (page.tags && page.tags.length){ %>
	<ul class="tag-cloud">
		<% page.tags.data.forEach(function(item){ %>
    		<li class="tag-list-item">
    			<a class="tag-list-link" href="/<%- item.path %>">
    				<%- item.name %>
    			</a>
    		</li>
		<% }); %>
	</ul>
<% } %>
```

**Comment by snovey** [comment]
Thank you for your help. It really solves my problem.
But I have a little regret. Because this method needs to config `site.config`, and my target is config it at `theme.config`.
Hope you help me again.

**Comment by snovey** [comment]
Well, yet another question...
Why do you use `page.tag` instead of `site.posts`.
I get `undefined` when trying use `page.tags`.
I don't know much about hexo, sorry for this question.

**Comment by tea3** [comment]
@snovey 
Sory , the content pointed out is correct. It seems that the code was wrong. 

### tag-cloud.ejs

In [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape) seems to work with the following code.

```
<h2>tag cloud</h2>

<% if (site.tags && site.tags.length){ %>
	<ul class="tag-cloud">
		<% site.tags.forEach(function(item){ %>
    		<li class="tag-list-item">
    			<a class="tag-list-link" href="/<%- item.path %>">
    				<%- item.name %>
    			</a>
    		</li>
		<% }); %>
	</ul>
	
	or
	
	<div class="widget-wrap">
	    <h3 class="widget-title"><%= __('tags') %></h3>
	    <div class="widget">
	      <%- list_tags({show_count: theme.show_count}) %>
	    </div>
	</div>
	
<% } %>
```

Also , If you want to use `theme.config` ,  Is the following code useful ?

### fancybox.js

For example , please add code as follow.

[https://github.com/hexojs/hexo-theme-landscape/blob/master/scripts/fancybox.js](https://github.com/hexojs/hexo-theme-landscape/blob/master/scripts/fancybox.js)

```
hexo.extend.filter.register('before_generate', () =>{
  return new Promise( (resolve , reject) => {
    hexo.config.single_page = hexo.theme.config.single_page
    resolve()
  })
})
```

Probably , it is not the correct usage of hexo, but I think it will work.

**Comment by snovey** [comment]
@tea3 
I also think it will work, but may have side effects. I do not intend to use this method.
Thank you.
All right, please close this issue.

**Comment by snovey** [comment]
So sorry.
Things become complicated and I don't test other single pages.
Now, I just config a `tags` page at `site.config`, but it rendered all single page include `about`.
I don't know why, so sad!

**Comment by snovey** [comment]
I guess modify the file name from `my-tag-cloud-page` to `page` lead to this bug

**Comment by snovey** [comment]
I have solved many of them. So close this.
