### ISSUE TITLE
Custom URLs in config.yml

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2697]
My categories correspond to my menu items. In my config.yml I specified for example:

menu:
  - name: phones
  - slug: phones
  - url: /categories/phones

Now how do I "hide/remove/surpress" categories in the URL, so instead of blog.com/categories/phones the menu item directs to blog.com/phones?

**Comment by NoahDragon** [comment]
How about `url: /phones`?

**Comment by rabas007** [comment]
@NoahDragon ... tried that, didnt work. "Cannot GET error". Its because my menu items are built from the categories I assigned to them.
So, category "phones", relates to menu item "phones", when user clicks menu item "phone", he is directed to URL: /categories/phones.

**Comment by connor11528** [comment]
Update your config file, run `hexo clean` and try again. this will rebuild the urls
