### ISSUE TITLE
How to install lastest version on Windows?

### ISSUE THREAD

**Issue by snovey** [hexojs/hexo#2699]
## Environment Info

Platform:
- OS Name: Microsoft Windows 10 Home
- OS Version: 10.0.15063 Build 15063

Node version(`node -v`):
- v6.9.1

Hexo and Plugin version(`npm ls --depth 0`):
- `-- npm@4.6.1

## For BUG

1. Can not install latest version
2. just run `npm install -g hexo-cli` will reproduce it.
then run `npm list --depth=0` will get info:
```powershell
+-- hexo-cli@1.0.3
`-- npm@4.6.1
```
I try run `npm install -g hexo-cli@latest` and get `1.0.3` version.
then uninstall` hexo-cli` , run `npm install -g hexo-cli@3.3.8` and get error message:
```powershell
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: hexo-cli@3.3.8
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.2.1, 0.2.0, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
I think this may be npm mirror problem, is there any other mirror?
What can I do?

**Comment by NoahDragon** [comment]
hexo-cli and hexo are different packages.
The 1.0.3 is the latest version for hexo-cli, which is command line tool for hexo.
