### ISSUE TITLE
some demo websites for themes are wrong

### ISSUE THREAD

**Issue by shurui91** [hexojs/hexo#2702]
When I was searching themes from Hexo's website, I noticed two problems, 
https://hexo.io/themes/index.html

* For a theme called Again, there is no demo/github repo available. 
* For a theme called Aloha, the demo site actually changed its theme to Polar Bear Simple.

**Comment by NoahDragon** [comment]
Thanks for the feedback. The theme list is maintained by users. We will check if there is something we can do about it.
