### ISSUE TITLE
Is Hexo-Inject working with current version of Hexo?

### ISSUE THREAD

**Issue by iamchathu** [hexojs/hexo#2704]
## Environment Info

Node version : 6.11.2

├── hexo@3.3.8
...
├── hexo-inject@1.0.0
...

## For BUG

Does https://github.com/hexojs/hexo-inject project is maintained? 

## For question

I'm working on a plugin which needs js code to be injected to beginning of the head. Since this plugin is a general use plugin I don't need users to put it by changing their theme. So after some search, I found hexo inject plugin and I have used it with my tag plugin and I doesn't inject the code to the beginning of head even when using a fresh install of hexo blog with the default theme. I have submitted an issue there and there is no reply on it. Does that package is working?

https://github.com/hexojs/hexo-inject/issues/3

**Comment by NoahDragon** [comment]
The hexo-inject haven't maintained for a while. I doubt it could work with current version.

**Comment by iamchathu** [comment]
@NoahDragon is there any alternative way to achieve this?

**Comment by connor11528** [comment]
Not sure but this should probably be an issue on that repo or a question on stackoverflow, not an issue here

**Comment by iamchathu** [comment]
@connor11528 I have filed issues there too. I filed it here about the compatibility and the future of it with Hexo. And what should we need to do to improve it. That module is beneficial for creating extended plugins which have dependencies.

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/4047
