### ISSUE TITLE
two `date` have different timezone

### ISSUE THREAD

**Issue by zxbetter** [hexojs/hexo#2705]
my `scaffolds/post.md`

```
---
url_title: {{date.substr(2, 2) + date.substr(5, 2) + date.substr(8, 2) + date.substr(11, 2) + date.substr(14, 2)}}
title: {{ title }}
date: {{ date }}
tags:
category:
---
```

after executing `hexo new "Test"`, `Test.md` has the following content

```
---
url_title: 1708140719
title: Test
date: 2017-08-14 15:19:59
tags:
category:
---
```
why `date` in `url_title` and `date` have different timezone? thx.

**Comment by NoahDragon** [comment]
I could reproduce the issue, but need to check if this is a bug or setting issue.

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/blob/6437ff51869faf1add5cbb1f5411586b61a93fbf/lib/hexo/post.js#L160-L162

The `obj` passed to `yfm.stringify` is like this

```
{
  url_title: 2003260438,
  title: 'Test',
  date: 2020-03-26T04:38:16.000Z,
  tags: null,
  category: null
}
```

type of `url_title` is string, while type of `date` is date.
However, `hexo-front-matter` will automatically convert date to string:
https://github.com/hexojs/hexo-front-matter/blob/69eb7d7a8cd8b564b59aaeb199dc3647eacea4c3/lib/front_matter.js#L153
which caused time zone issues

**Comment by stevenjoezhang** [comment]
My suggestion is not to use `date.substr`
```
url_title: {{ date.getFullYear() + date.getMonth() + date.getDate() }}
```
