### ISSUE TITLE
Change page title for "categories"

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2706]
I changed "category" in URL for my widget into new name "company". Easy.
But how to change it also in page_title tab?
See image...
![page_title](https://user-images.githubusercontent.com/29863525/29307903-f475dd22-81a3-11e7-8492-8e1aa670ef9f.jpg)

**Comment by NoahDragon** [comment]
If you are using the landscape theme, you could change it under the theme language folder.

![image](https://user-images.githubusercontent.com/5704064/29319187-1cbd7568-81a1-11e7-8b82-b220b33b7993.png)

**Comment by rabas007** [comment]
@NoahDragon - that is for URL, right? For URL I have made the change successfully (from "categories" to "companies") in config.yml. I use MaterialFlow theme. Only in page_title tab I cannot change it, I do not know where?

**Comment by NoahDragon** [comment]
You could modify the layout file to change it.
![image](https://user-images.githubusercontent.com/5704064/29331110-6468e7ee-81c9-11e7-9583-61b50a89171c.png)

**Comment by rabas007** [comment]
@NoahDragon - that solved it! Great, thank you! 👍

**Comment by tegalsari** [comment]
@NoahDragon I use landscape theme, how to remove title "category : " in title tab
