### ISSUE TITLE
hexo server launch failed

### ISSUE THREAD

**Issue by dev-techmoe** [hexojs/hexo#2708]
## Environment Info

Node version(`node -v`): v4.2.6

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 /media/sf_WORK/lolicookie-hexo
├── browser-sync@2.18.13 extraneous
├── hexo@3.3.8
├── hexo-asset-image@0.0.3
├── hexo-cli@1.0.3
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-migrator-ghost@0.0.1
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2

## For BUG

 1. BUG description: hexo server launch failed.. it seems some error occored when it is loading node_modules in theme folder.. I'm not a nodejs programmer and I don't know why Hexo need open the node_modules of my themes when I want to launch the built-in server of Hexo...it's so bizarre.
 2. The way to reproduce: I don't know.. sorry
 3. Log with hexo <command> --debug
```
16:19:20.769 DEBUG Hexo version: 3.3.8
16:19:20.771 DEBUG Working directory: /media/sf_WORK/lolicookie-hexo/
16:19:21.653 DEBUG Config loaded: /media/sf_WORK/lolicookie-hexo/_config.yml
16:19:21.774 DEBUG Plugin loaded: hexo-deployer-git
16:19:21.855 DEBUG Plugin loaded: hexo-migrator-ghost
16:19:21.882 DEBUG Plugin loaded: hexo-generator-tag
16:19:21.925 DEBUG Plugin loaded: hexo-generator-category
16:19:21.945 DEBUG Plugin loaded: hexo-generator-feed
16:19:22.313 DEBUG Plugin loaded: hexo-asset-image
16:19:22.318 DEBUG Plugin loaded: hexo-renderer-stylus
16:19:22.356 DEBUG Plugin loaded: hexo-renderer-marked
16:19:22.394 DEBUG Plugin loaded: hexo-renderer-ejs
16:19:22.406 DEBUG Plugin loaded: hexo-generator-index
16:19:22.438 DEBUG Plugin loaded: hexo-generator-archive
16:19:23.187 DEBUG Plugin loaded: hexo-server
16:19:23.198 DEBUG Loading database.
16:19:23.211 INFO  Start processing
16:19:27.682 DEBUG Processed: _posts/.....
16:19:31.418 DEBUG Processed: _posts/.....
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOMEM: not enough memory, open '/media/sf_WORK/lolicookie-hexo/themes/lighthouse_v2/node_modules/request/node_modules/qs/lib/formats.js'
    at Error (native)
```
OS: Ubuntu 16.04.3 LTS in VirtualBox

**Comment by dev-techmoe** [comment]
I'm writing a new theme for my website.. so I can't delete the node_modules folder of my themes now

**Comment by NoahDragon** [comment]
As the message shows `not enough memory`, have you tried to increase the memory for your virtual machine?

**Comment by dev-techmoe** [comment]
@NoahDragon I've tried, but nothing has been solved..

**Comment by TencentIT** [comment]
have a little porblem in the programe
