### ISSUE TITLE
Permalinks are broken when config.relative_link === true

### ISSUE THREAD

**Issue by kolbma** [hexojs/hexo#2709]
The code at
https://github.com/hexojs/hexo/blob/6c0fbd0e97ec171606103ac1c60c0658bab6e882/lib/models/post.js#L61

and above doesn't handle the case if partial_url is a relative url.

config.url: http://www.example.com
config.root: /
config.relative_link: true
config.permalink: :year/:month/:day/:title/
config.permalink_defaults:

Maybe just a missing config.root concatenation?
Why you use here url_for() and in the more or less equal functions from #2105 you simply concatenate path?

**Comment by NoahDragon** [comment]
There is some legacy code where the url_for didn't exist at that time, so it just concatenates the slugs. We recommend using the url_for() to handle slugs, but haven't converted all the code yet.

**Comment by NoahDragon** [comment]
Will the PR fix the issue here? https://github.com/hexojs/hexo/pull/2760#pullrequestreview-63657685
