### ISSUE TITLE
Template render error: (unknown path)

### ISSUE THREAD

**Issue by Summyj** [hexojs/hexo#2710]
I don't know how to solve this problem：

![image](https://user-images.githubusercontent.com/26139198/29393479-7f79ce90-8336-11e7-8dd4-e3a68b7b65bf.png)

I swear I didn't do anything, I haven't modified any files,  It just pops up

**Comment by NoahDragon** [comment]
This error usually causes by the nunjucks syntax, If that possible to share your website repo?
