### ISSUE TITLE
Install hexo error

### ISSUE THREAD

**Issue by zhanwen** [hexojs/hexo#2711]
execute:  npm install -g hexo-cli. then stay here. 
![image](https://user-images.githubusercontent.com/11382789/29404716-5cb8f8da-836e-11e7-837a-e7359801060d.png)

**Comment by NoahDragon** [comment]
Could try to re-install it? So far there is no error output, and couldn't conclude the reason.

**Comment by zhanwen** [comment]
thanks, now, good, I re-install it. last time may network reason.
