### ISSUE TITLE
Develop based on Hexo

### ISSUE THREAD

**Issue by SmartBrave** [hexojs/hexo#2712]
Hello,

I'm a newer in Hexo,now I need to develop a tool based on Hexo with CompanyWeChat(https://work.weixin.qq.com/).

When someone write a blog in Hexo,I want to push it to all member within company automatically. The api of Wechat is easy,but I don't know if someone public a article?

If you konw how to do,please tell me,Thanks a lot! :)

**Comment by NoahDragon** [comment]
As Hexo is a static web page generator. I think you could run a script after it be deployed, like:
```
hexo d && ./script_to_push_notification.sh
```

**Comment by SmartBrave** [comment]
yeah,write a script is easy,but I want to know when the script should be triggered.

I write this tool with golang,maybe there hava a lib to Hexo API?

**Comment by SmartBrave** [comment]
In my thinking,could I push my article to gitlab,then set a gitlab webhook to my server,this server can publish article to Hexo?

Is Hexo only has python api to publish article?

**Comment by NoahDragon** [comment]
Hexo is based on Javascript. In your case, I think you could take a look at the Travis-CI. There is no webhook need to setup. Hexo.io is using the similar approach, push to github, then travis-ci get the latest version and publish to another repo.

**Comment by SmartBrave** [comment]
OK，I'll try,thank you,thank you!
