### ISSUE TITLE
Including .well-known directory

### ISSUE THREAD

**Issue by 9662** [hexojs/hexo#2715]
## Environment Info

Node version(`node -v`): v7.6.0

Your site `_config.yml` (Optional):

(Partial)
```yaml
# Include/Exclude Files/Folders
include:
  - .well-known
```

Hexo and Plugin version(`npm ls --depth 0`): 
```
├── hexo@3.3.8
├── hexo-deployer-git@0.3.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
```

## BUG

The [documentation states](https://hexo.io/docs/configuration.html#Include-Exclude-Files-or-Folders):
> In the config file, set the include/exlude key to make hexo explicitly process or ignore certain files/folders.

### Actual outcome

When using the `include` key with a folder, it does not work. It works only for files.

### Expected outcome

This code should result in the `.well-known` directory (even if empty) being copied to the output folder (e.g., `public`):

```yaml
include:
  - .well-known
```

### Workaround

It is possible to create a dummy file inside the directory and reference that. Even a hidden dummy file works, as in the following example:

```bash
touch .well-known/acme-challenge/.dummy
```

```yaml
# Include/Exclude Files/Folders
include:
  - .well-known/**/.dummy
```

**Comment by NoahDragon** [comment]
This is not an issue with Hexo, as git doesn't track the empty folders. Glad you figure out the workaround.

**Comment by TimDaub** [comment]
Hi 👋 

brave is asking users to add a verification file to their website. I have my website hosted on GitHub pages and I'm experiencing the above described problems. However, the work-around doesn't seem to work.

- I have a txt file that needs to be place to `https://myblog.com/.well-known/file.txt`
- As outlined above, I've added `.well-known/**/.dummy` in `include` in `_config.yaml`
- When I do `hexo clean && hexo deploy` I get the following output:

```
...
INFO  Generated: .well-known/.dummy
...
INFO  Generated: .well-known/brave-rewards-verification.txt
```

So apparently, `hexo clean` or `hexo deploy` are correctly creating the files. However, later when the generated code is being pushed to GitHub, I cannot see the folder and its file. Meaning something is wrong in either `hexo clean` and/or `hexo deploy`

**Comment by RammusXu** [comment]
@TimDaub 
I guess https://github.com/hexojs/hexo-deployer-git is updated some features.
You need to set `ignore_hidden: false` on `deploy:` block.

```
deploy:
  ... 
  ignore_hidden: false
include:
  - .well-known/*
  - .nojekyll
```

**Comment by leimao** [comment]
> @TimDaub I guess https://github.com/hexojs/hexo-deployer-git is updated some features. You need to set `ignore_hidden: false` on `deploy:` block.
> 
> ```
> deploy:
>   ... 
>   ignore_hidden: false
> include:
>   - .well-known/*
>   - .nojekyll
> ```

@RammusXu In this way, will all the other hidden files starting with `_` be deployed as well?

**Comment by leimao** [comment]
> ignore_hidden: false

The answer is no.

**Comment by leimao** [comment]
> > @TimDaub I guess https://github.com/hexojs/hexo-deployer-git is updated some features. You need to set `ignore_hidden: false` on `deploy:` block.
> > ```
> > deploy:
> >   ... 
> >   ignore_hidden: false
> > include:
> >   - .well-known/*
> >   - .nojekyll
> > ```
> 
> @RammusXu In this way, will all the other hidden files starting with `_` be deployed as well?

The answer is no.
