### ISSUE TITLE
ALT text image in frontpage

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2721]
Inside my blogpost I can add image with ALT text like so: 

`![this is the ALT text of an image of a happy couple in the grass](/images/img/couple.jpg)`

But in my blogpost I also have a header image: 

```
title: Hello world
date: 11.11.1111
categories: news
featured_image: /source/images/img/spaceshuttle.jpg
```
---

Question is how to add ALT text for my "spaceshuttle.jpg" image with URL?

I tried: 

`featured_image alt: my first spaceshuttle`

But that did not work.

**Comment by NoahDragon** [comment]
IMHO, this could support through the theme. All front matters variables could be accessed via page.[variable_name] in theme files.

**Comment by rabas007** [comment]
@NoahDragon - solved! thanks, you gave me the solution.
