### ISSUE TITLE
Create Child Page with --path create an md file with no name

### ISSUE THREAD

**Issue by philerck** [hexojs/hexo#2725]
## Environment Info
OS: Windows 10

Node version(`node -v`): v6.9.5

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

hexo@3.3.8
hexo-deployer-git@0.2.0
hexo-generator-archive@0.1.4
hexo-generator-category@0.1.3
hexo-generator-index@0.2.1
hexo-generator-tag@0.2.0
hexo-renderer-ejs@0.2.0
hexo-renderer-marked@0.2.11
hexo-renderer-stylus@0.3.3
hexo-server@0.2.2

## For question

I want to create a child page and try it with `hexo new page test2 --path 'test/test2/'`.
I get a new folder test2 in test but the md file has no name => .md

Is there a solution to get an index.md file in test2 or am I doing something wrong?

**Comment by NoahDragon** [comment]
IMHO, the `hexo new` command doesn't support `--path` argument.

**Comment by philerck** [comment]
@NoahDragon thanks for an answer. 
I thought it works because of this link https://github.com/hexojs/hexo/issues/379

**Comment by NoahDragon** [comment]
The post is really old. I suspect it was supported in the old version, but removed at least in 3.0.

**Comment by philerck** [comment]
Ok, got it. Thanks for your help

**Comment by kbaley** [comment]
`hexo new --help` still shows support for the --path parameter.

It does seem to work but you have to specify the filename explicitly. E.g. `hexo new page test2 --path 'test/test2/index`

**Comment by NoahDragon** [comment]
@kbaley Thanks for point this out. I think we need remove it.
