### ISSUE TITLE
About Permalink

### ISSUE THREAD

**Issue by SmartBrave** [hexojs/hexo#2727]
Hi,

I set the permlink of hexo is:`:year/:month/:day/:id/`,so I can identify any articles by id instead of name.But the id was changed when I use `hexo new article` to publish a new article.It's OK?

**Comment by SmartBrave** [comment]
And is there id change automatically?

**Comment by NoahDragon** [comment]
As the id is auto generated each time. I recommend using the https://github.com/rozbo/hexo-abbrlink instead.

**Comment by SmartBrave** [comment]
I see and try to use it,Thanks!
