### ISSUE TITLE
change my custom domain after deploy

### ISSUE THREAD

**Issue by an15m** [hexojs/hexo#2730]
## Environment Info

Node version(`node -v`):6.10.2

Your site `_config.yml` (Optional):
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://an15m.tk
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```
Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
```
+-- hexo@3.3.8
+-- UNMET DEPENDENCY hexo-baidu-url-submit@0.0.5
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-baidu-sitemap@0.1.2
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.1.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```
## For BUG

 1. BUG description
 everytime I deploy， it delete my CNAME file.
so my custom domain be delete
 2. The way to reproduce
everytime deploy

**Comment by an15m** [comment]
I should manually create a CNAME file in theme/xxxxx/source/

**Comment by logmedate** [comment]
As i know, after each deploy time, custom domain in CNAME in github repo will be disappeared 
Can fix by following this link: https://harrykhang.com/2018/08/15/Customs-domains-for-Hexo-Blog/
The issue will be resolved automatically

**Comment by krisnaxda** [comment]
> As i know, after each deploy time, custom domain in CNAME in github repo will be disappeared
> Can fix by following this link: https://harrykhang.com/2018/08/15/Customs-domains-for-Hexo-Blog/
> The issue will be resolved automatically

the link is dead, can you give me another tutorial sir?
