### ISSUE TITLE
A new demand

### ISSUE THREAD

**Issue by Devinnn** [hexojs/hexo#2731]
Thanks for reading~

Now I am trying to add a new page named 'life'.I would like to make 'life' page to record my life.

So I add new article about life into the '_post' folder.But I don't want these articles appear in index, achieves or etc.That is to say I don't want these articles add to posts.

So what I could do?To add a new folder  named 'life' in source?But how the hexo resolve the files in '_post' folders.

Can you solve this question? Thx~

**Comment by NoahDragon** [comment]
You could create a new page for your purpose: `hexo new page life`.
