### ISSUE TITLE
hexo init error

### ISSUE THREAD

**Issue by tang-yue** [hexojs/hexo#2732]
![error](http://o8gasf88j.bkt.clouddn.com/hexoerr2.png)
how I should solve the problem? Thx!!

**Comment by NoahDragon** [comment]
Look like a connection issue. Have you tried to run the same command under `cmd` instead of `mingw`?

**Comment by tang-yue** [comment]
![error](http://o8gasf88j.bkt.clouddn.com/hexoerr3.png)
when I try to do this according to your advice,I have the problem.
your solution looks like invalid. @NoahDragon

**Comment by NoahDragon** [comment]
It is the same issue as npm couldn't connect to the internet. Maybe you could change another npm mirror. Such as https://npm.taobao.org/ .

**Comment by NoahDragon** [comment]
This is a really weird problem. I'll label it as the question, hope some one has similar issue could help.

**Comment by tang-yue** [comment]
I solve the problem lately. terminal can show error by command line input, such as npm error ,because network connection problem, but this error does not affect hexo initialition. Thx. so you can close the question. @NoahDragon.

**Comment by NoahDragon** [comment]
👍 Glad you find the solution. Closing this.
