### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zekunpika** [hexojs/hexo#2733]
npm ERR! path /usr/local/bin/hexo
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/bin/hexo: ../lib/node_modules/hexo/bin/hexo symlink target is not controlled by npm /usr/local/lib/node_modules/hexo-cli
npm ERR! File exists: /usr/local/bin/hexo
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pika/.npm/_logs/2017-08-28T07_49_23_765Z-debug.log

**Comment by NoahDragon** [comment]
It means you have installed Hexo already, try to uninstall it and re-install again.
