### ISSUE TITLE
hexo generate does not deploy when combining --watch and --deploy

### ISSUE THREAD

**Issue by martijnthe** [hexojs/hexo#2738]
In my use case I want watch and deploy together and run the deploy plugin upon every change.
When using `hexo generate --watch --deploy`, the deploy plugin does not get called.

## Environment Info

Node version(`node -v`):
v8.1.3

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
hexo@^3.2.0

**Comment by martijnthe** [comment]
I took a stab at fixing this issue:
https://github.com/martijnthe/hexo/commit/abe883b2f6401892531ecfd25bb2dbf136e221ce

Let me know if this makes sense.
If it does, I will add test cases too and put up a clean PR.

**Comment by NoahDragon** [comment]
The code is LGTM. However, I'm concerning about the performance if call deployment every time when file is modified. https://github.com/martijnthe/hexo/commit/abe883b2f6401892531ecfd25bb2dbf136e221ce#diff-a341666ecc7785fc1106caabd4357eccR148

Correct me if I'm wrong, I didn't go deep into the code yet.

**Comment by martijnthe** [comment]
> However, I'm concerning about the performance if call deployment every time when file is modified. 

I guess it depends on what the deploy plugin of the user is doing...
In my case the deployer is generating a PDF which is pretty fast.
The PDF generator uses multiple .html/css/images/etc as input and I didn't know how to model having multiple inputs within the Hexo framework.

**Comment by NoahDragon** [comment]
I see. I beleive not many people are using the watch and generate command simultaneously. It is a good feature to add to Hexo. 👍
