### ISSUE TITLE
init，help，version以外的命令失效，一直得到hexo help的结果，查看package.json版本信息没问题

### ISSUE THREAD

**Issue by 123456zzz** [hexojs/hexo#2739]
## Environment Info

Node version(`node -v`):8.4.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional):

Hexo and Plugin version(`npm ls --depth 0`): 3.3.8 3.2.0

## For BUG
 1. init，help，version以外的命令失效，一直得到hexo help的结果，查看package.json 版本信息没问题
 2.  hexo <command> --debug 显示
      events.js:182
      throw er; // Unhandled 'error' event

## For question
之前所有功能都正常，然后提交后就出现这个问题，init了2次之后还是这样，

**Comment by NoahDragon** [comment]
Looks like your issue is similar to https://github.com/hexojs/hexo/issues/2740 .

**Comment by NoahDragon** [comment]
有没有试过使用老版本的hexo呢？

**Comment by NoahDragon** [comment]
此issue还可回复，先Close，减少重复。

**Comment by 123456zzz** [comment]
可能是因为没在 hexo 所在目录执行导致的，thanks.

**Comment by channg** [comment]
```
  "hexo": {
    "version": "3.7.1"
  },
```

package.json 加上这个就好了
