### ISSUE TITLE
What is the proper way to upgrade Hexo? 

### ISSUE THREAD

**Issue by fastzhong** [hexojs/hexo#2740]
## Environment Info

Node version(`node -v`): v6.11.2

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

What is the proper way to upgrade Hexo? 

I tried npm install (https://github.com/hexojs/hexo/issues/1689), it does not work. 

After re-install hexo-cli and npm install, hexo <command> does not work, and always return  Usage message. Should I run hexo init? what happen to my old Hexo files?

**Comment by NoahDragon** [comment]
I think `npm update -g hexo` is what you are looking for to update the hexo version.

Moreover, `hexo init` only works for the empty folder. You could create a vanilla hexo site, then copy the `source` and `theme`  into it, and also the `package.json` (don't forget the change the hexo version inside it).

**Comment by NoahDragon** [comment]
We may need to investigate it, as other people report the similar issue.

Could you provide more information, like the OS, npm version, and etc.?
