### ISSUE TITLE
Overwrite variable in nested layout

### ISSUE THREAD

**Issue by matthewma7** [hexojs/hexo#2745]
## For question

Currently, if I define variables in a `child.ejs` layout like this
```
---
layout: layout
no_footer: true
---
```

and define 
```
---
no_footer: false
---
```
in the default `layout.ejs` file

The variable `no_footer` will be overwritten by the `layout.ejs` to `false`. but I want the value to be `true`. 
So I had to do something like in `layout.ejs` file 
```
<% var no_footer = no_footer || false %>
```
Is this an expected behavior? Should variable in child layout be overwritten by parent layout?

## For feature request
Make child variable overwrite parent variable

**Comment by NoahDragon** [comment]
How about use another name in the front-matter?

**Comment by matthewma7** [comment]
Hi @NoahDragon,

Thank you for looking into this issue.

I used the same variable name to provide a default value on the `layout.ejs`, and when needed overwrite it in `child.ejs` layout. 

Take the `no_footer` for example, I have a code block `<% if(!no_footer) { %>this is the footer<% } %>` inside layout.ejs, so all pages will have footer by default. but for `child.ejs` layout, I want to overwrite the default to true to make all page using the `child.ejs` has no footer.

Hope this explains what I meant to do.

**Comment by NoahDragon** [comment]
I don't have an answer for this, hope anyone could answer this question.

**Comment by matthewma7** [comment]
This is still a question for me.
It seems to me that the front matter for child layout is run before the front matter of the child's parent layout. So the problem is variable on the parent would overwrite variable on the child. (Normally, child overwrite parent is more useful in programming in general)
So, without thinking too deeply into this matter, I am thinking reversing the order of the front matter execution would solve the problem.

**Comment by stevenjoezhang** [comment]
Can you confirm if this is a feature of the Hexo or ejs template engine?
