### ISSUE TITLE
After upgrading hexo to 3.3.9, the HTML inline elements are not resolved in markdown

### ISSUE THREAD

**Issue by cxinixn** [hexojs/hexo#2746]
## Environment Info

Node v6.10.3

hexo 3.3.9

## For BUG
When you upgrade node, the HTML inline elements can be resolved in this version of hexo3.3.9.
Why didn't the HTML inline element be resolved in markdown after node 6.10.3 upgraded hexo to 3.3.9.

**Comment by NoahDragon** [comment]
Could you please provide an example?

**Comment by cxinixn** [comment]
#### Yes, thank you very much for your recovery

Environment Info
node v6.10.3


```
rm -rf node_modules

npm install
```


my hexo is ^3.3.8
when i install the hexo version upgrade to
 3.3.9



package.json

```
{
  "name": "dev-doc",
  "version": "0.0.1",
  "hexo": {
    "version": "3.3.9"
  },
  "scripts": {
    "server": "hexo server",
    "generate": "hexo generate",
    "algolia": "hexo algolia",
    "clean": "hexo clean"
  },
  "dependencies": {
    "hexo": "^3.3.8",
    "hexo-algoliasearch": "^0.2.1",
    "hexo-deployer-git": "^0.3.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-server": "^0.2.0",
    "lunr": "^2.1.1",
    "markdown-it": "^8.2.2",
    "markdown-it-replace-link": "^1.0.0",
    "markdown-it-toc-and-anchor": "^4.1.1"
  },
  "devDependencies": {
    "hexo-cli": "^1.0.3"
  }
}

```

When the hexo upgrade to 3.3.9, in the node 6.10.3 markdown under the a label is not resolved, as shown in Figure


![error 3](https://user-images.githubusercontent.com/20550962/30362107-e91abde4-988c-11e7-81dc-896824b5c7d5.png)


But when I use hexo 3.3.8 markdown can be normal analysis
![normal](https://user-images.githubusercontent.com/20550962/30362415-7997ec7e-988e-11e7-85b8-e59b441e4b54.png)

**Comment by NoahDragon** [comment]
@cxinixn have you figured out the reason?
