### ISSUE TITLE
The post always be renew by using travis ci

### ISSUE THREAD

**Issue by NoviceDuke** [hexojs/hexo#2748]
## Environment Info

Node version(`node -v`): stable

### my .travis.yml

language: node_js

node_js: stable

branches:
  only:
  - test

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

before_install:
- git config --global user.name "NoviceDuke"
- git config --global user.email "duke00360753@gmail.com"

- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:

- yarn install --pure-lockfile
script:
- hexo clean
- hexo generate
after_success:
- git clone https://github.com/NoviceDuke/blog.git .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- git push --quiet --force "https://$token@github.com/NoviceDuke/blog.git"
  master:master

## For question
I use travis ci to auto generate my post , but it always generate all posts , and update all posts
.Even all the old posts will be update.

**Comment by NoahDragon** [comment]
It's caused by Travis doesn't cache the db file. Hexo could do anything about it.
