### ISSUE TITLE
where is the page.year in archive page?

### ISSUE THREAD

**Issue by Devinnn** [hexojs/hexo#2749]
As we can see,we read these.Such as:

![image](https://user-images.githubusercontent.com/19498847/30248309-d77ab60c-9657-11e7-9174-be5341f5b7e7.png)

But,when I use page.year in archive page,I console the page:

![image](https://user-images.githubusercontent.com/19498847/30248332-355f2726-9658-11e7-9d81-bd648da49843.png)

So we can see archive is true,but where is 'page.year'?

**Comment by tea3** [comment]
`year` is in` page`.   For example you can check the value in follow as.

```
page.posts.data[0].date.year()
```

Also , you can output the console in the following way.

```
<% page.posts.each(function(post, i){ %>
    <%- console.log(post.date.year() , post.date.month()) %>
<% }) %>
```
