### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2750]
Hi,

Does anybody know a good **user editor** I can use for inside a "FORM description field"? 

Also, how to use it with HEXO? Compatibility issues?

Something like this...

![editor](https://user-images.githubusercontent.com/29863525/30250774-8ea86f9e-9654-11e7-84aa-2ad1f8132a69.JPG)

**Comment by tea3** [comment]
Will [Disqus](https://help.disqus.com/customer/en/portal/articles/466179-what-is-disqus-) be helpful  ?

**Comment by NoahDragon** [comment]
How about emacs? https://github.com/kuanyui/hexo.el

**Comment by rabas007** [comment]
@NoahDragon - perfect, exactly what I was looking for... thank you... 👍
