### ISSUE TITLE
[DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.

### ISSUE THREAD

**Issue by Dedsecr** [hexojs/hexo#2752]
## Environment Info

Node version(v8.1.3):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo-admin@2.2.1

## For question
After installed Plugin "hexo-admin", I got this.
![image](https://user-images.githubusercontent.com/25794491/30301419-3f73bffc-978d-11e7-92fd-e7597deaa752.png)
And when I used "hexo --debug"
![image](https://user-images.githubusercontent.com/25794491/30301432-57584b60-978d-11e7-99ae-a8ff5db8ab4a.png)

**Comment by Dedsecr** [comment]
![image](https://user-images.githubusercontent.com/25794491/30301661-a4ebd30a-978e-11e7-8a10-a725e11909ff.png)
And this

**Comment by geekrainy** [comment]
Try to upgrade hexo-fs to the new version. https://www.npmjs.com/package/hexo-fs
