### ISSUE TITLE
java transfer hexo command

### ISSUE THREAD

**Issue by noesblog** [hexojs/hexo#2758]
Hello, I would like to make a hexo synchronization on the server java procedures, the java program will automatically call hexo clean, hexo g, hexo d, and other orders, how to use java to call hexo these orders?Thank you！

**Comment by tea3** [comment]
Sorry , I don't know the server java procedures.  For example ,  can the server make enviroment of node.js ? Also , can the server run child process ?

**Comment by noesblog** [comment]
ok,thanks for you!
