### ISSUE TITLE
How do I sort blog posts on the homepage and archive page by update time?

### ISSUE THREAD

**Issue by liqiang311** [hexojs/hexo#2763]
## For question

How do I sort blog posts on the homepage and archive page by update time?

如何在首页和归档页将博文按照更新时间排序？

默认是按照发表时间排序。

**Comment by geekrainy** [comment]
同你使用的主题有关，主题渲染过程中可对文章数据的排序进行指定。

**Comment by liqiang311** [comment]
我使用的是next主题，我在next主题那边提了个issue，被关了，原因是hexo issue，非theme问题。 next issue地址： https://github.com/iissnan/hexo-theme-next/issues/1895

**Comment by geekrainy** [comment]
我将尝试在 NexT 实现该需求，如果我最近有足够的空闲。:)

**Comment by liqiang311** [comment]
谢谢您。

**Comment by ivan-nginx** [comment]
Wow! English language. I don't believe that. :)

**Comment by NoahDragon** [comment]
@ivan-nginx currently the default order is descending order on creating date, however, the theme author could modify the behavior if there is a need for customized order. Although it may be easy to implement in Hexo, we are trying to maintain it as simple as possible. Moreover, Hexo core should only provide the base functions, all extend should be in the plugins, tags, or theme. If there is something in Hexo core blocking people to do so, we definitely need to make the change.

Hope this could answer your concern.

**Comment by huyingjie** [comment]
Is there any update?
