### ISSUE TITLE
Display specific categories for each layout

### ISSUE THREAD

**Issue by front3ndo** [hexojs/hexo#2764]
I have two kinds of layouts: post and product. How can display specific categories for each layout on home page or any other page?
In Jekyll it looks like this (after adding filter):
{% for category in site.categories['post'] %}{% endfor %}
{% for category in site.categories['product'] %} {% endfor %}

**Comment by NoahDragon** [comment]
In Hexo, if you are using ejs, you could add the following into categories layout:
```ejs
<%
  // find all posts with category: "items" and tag: "featured"
  site.tags.findOne( { name: 'featured' } )
    .posts.sort( 'date', -1 )
    .each(
      function(post, index) {
        post.categories.each( function(category) {
          if(category.name === 'items') {
%>
            <%- partial('_partial/index/featured-item', {post: post}) %>
<%
          }
        });
      }
    );
%>
```
https://github.com/hexojs/hexo/issues/2195
