### ISSUE TITLE
hexo list <type> :      zsh: parse error near `\n'

### ISSUE THREAD

**Issue by j4go** [hexojs/hexo#2765]
## Environment Info

Node version(`node -v`): v7.3.0

## For BUG

When I type the command : 
```
hexo list <type> 
```
An error occurred:
zsh: parse error near `\n'
![](http://owmgty089.bkt.clouddn.com/c2dc25d54b8344d3b00117fa7d3fe24c.jpg)

**Comment by NoahDragon** [comment]
The command should be 
```
hexo list post
```
