### ISSUE TITLE
执行hexo d的时候报错

### ISSUE THREAD

**Issue by zhengpq** [hexojs/hexo#2767]
ssh: Could not resolve hostname github.com:zhengpq: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ssh: Could not resolve hostname github.com:zhengpq: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

搭建过程中执行“hexo d”的时候出现上面的报错，但是我可以从本地将创建的仓库拉下来并且修改和推上去都没有问题，但是报错中一直显示无法解析主机名。有没有哪位前辈之前也遇见过这种问题？

**Comment by NoahDragon** [comment]
请贴下配置文件中如何设置的deploy？

**Comment by zhengpq** [comment]
deploy:
  type: git
  repo: ssh://git@github.com:zhengpq/zhengpq.github.io.git
  branch: master

**Comment by NoahDragon** [comment]
测试ssh是否可以连接？
```
ssh -T git@github.com
```

**Comment by zhengpq** [comment]
运行：
$ ssh -T git@github.com
结果：
Hi zhengpq! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by zhengpq** [comment]
是可以连接的，在本地可以直接克隆我在github上面的仓库，如下：
$ git clone git@github.com:zhengpq/zhengpq.github.io.git
Cloning into 'zhengpq.github.io'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 1), reused 6 (delta 1), pack-reused 0
Receiving objects: 100% (6/6), done.
Resolving deltas: 100% (1/1), done.

而且本地修改推上去也没有问题

**Comment by Max-Lee1993** [comment]
@zhengpq 使用hexo命令呀

**Comment by zhengpq** [comment]
运行：
hexo d

结果：
ssh: Could not resolve hostname github.com:zhengpq: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ssh: Could not resolve hostname github.com:zhengpq: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@Max-Lee1993

**Comment by NoahDragon** [comment]
@zhengpq 可否将ssh去掉试一下？
```md
deploy:
  type: git
  repo: git@github.com:zhengpq/zhengpq.github.io.git
  branch: master
```

**Comment by zhengpq** [comment]
成功了！谢谢前辈！
不好意思，前辈，最后再问一个问题，我是根据别人搭建的教程做的，有些人在deploy配置里面加了ssh或者是https，如下面所示，之前这两个我都尝试了，但是都没有成功
deploy:
  type: git
  repo: ssh://git@github.com:zhengpq/zhengpq.github.io.git
  branch: master

或者是：
deploy:
  type: git
  repo: https://git@github.com:zhengpq/zhengpq.github.io.git
  branch: master

为什么去掉ssh之后就能够成功呢？
官方文档给出的配置是：
deploy:
  type: heroku
  repo: <repository url>
  message: [message]

看来是这个地方我没有理解好，但是那些加上了ssh和https的为什么能够运行成功呢？

@NoahDragon

**Comment by NoahDragon** [comment]
主要是格式：
ssh并不需要加`ssh://`在前面的，因为并不是一个网络协议.
而https的格式是`https://github.com/zhengpq/zhengpq.github.io.git`, 而且https只支持开放Repo,私有只能用ssh。

**Comment by shaoxuefei** [comment]
deply 的repo的值换成https的Git仓库clone地址ok了！

**Comment by kid1412621** [comment]
@NoahDragon @zhengpq @Max-Lee1993 @shaoxuefei @bkeepers 
你好，我今天也遇到了同样问题。
配置如下：
``` deploy:
  type: git
  repository: git@github.com:kid1412621/tst.git
  branch: master 
```
报错如下：
![image](https://user-images.githubusercontent.com/26278054/38775033-e25efb9e-40a9-11e8-903c-398ee90a4cc2.png)
---
奇怪的是，我用`ssh -T git@github.com`测试就能连接成功，但是用`git@github.com:kid1412621/tst.git`就报错，说` Could not resolve hostname github.com:kid1412621/tst.git: No such host is known.`。

**Comment by zdRan** [comment]
我也遇到了这个问题，解决办法很简单，重新生成一个ssh公钥，然后把github上的公钥删除了重新添加一下。就能提交了。好像是ssh有个有效期。一旦过期就不能用了。

**Comment by Linkeer365** [comment]
其实你们可以试试用vpn切到别的ip上, 不知道为什么我每次都是这样解决的

**Comment by azl397985856** [comment]
我也遇到了，我的解决方案` 重启Iterm`

**Comment by greenhandzdl** [comment]
我也遇到了，只不过是ssh -T git@github.com被deny，后来把Windows10的指纹换掉（我现在是Windows11）后又行了

**Comment by qiyu-love** [comment]
<img width="698" alt="image" src="https://github.com/hexojs/hexo/assets/109739639/f85daa36-2529-4606-8c1e-77ef88f2eaa6">
有人遇到这个问题吗，mac版，什么方法都试了没用
