### ISSUE TITLE
Article does not recognize the ')'at the end of a link 

### ISSUE THREAD

**Issue by Mondobongoo** [hexojs/hexo#2768]
such as
`[theory](https://en.wikipedia.org/wiki/Loop_(graph_theory))`

I hope it will be shown in the article like this:
theory
But this link will be shown in the article like this:
theory)

')' Is superfluous

I have changed a lot of themes, but found that the problem is not resolved
So I think it is hexo's problem

**Comment by NoahDragon** [comment]
I think could use url encoding to solve this issue:
```
( --> %28
) --> %29
```

**Comment by dqwyy** [comment]
Yeah, url encoding is the solution.

**Comment by Mondobongoo** [comment]
Url encoding is a  solution indeed , but this problem does not appear on other sites.

`[theory](https://en.wikipedia.org/wiki/Loop_(graph_theory))`

I put this line of code into this message board, the display is normal.
[theory](https://en.wikipedia.org/wiki/Loop_(graph_theory))
There is no ')'

So it is a bug needed to solve in the hexo.

**Comment by NoahDragon** [comment]
@Mondobongoo this is caused by markdown format. The following article provides more alternative ways for this issue. https://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses
