### ISSUE TITLE
can not use  post_asset_folder: true to create post

### ISSUE THREAD

**Issue by yuanyuanyuan** [hexojs/hexo#2770]
## Environment Info

Node version(`node -v`):
v6.9.5

Your site `_config.yml` (Optional):

post_asset_folder: true

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.3.7
├── hexo-deployer-git@0.3.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-searchdb@1.0.7
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.1
└── hexo-wordcount@3.0.2

## For BUG

 1. BUG description

I am use the comm to add post： `hexo new post 1 `

my post dir：
├── 1
│   └── 1.jpg
├── 1.md

the log:

FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ENOTDIR: not a directory, open '/public/1.html/1.jpg'
    at Error (native)

 2. The way to reproduce
 3. Log with hexo <command> --debug

I think is not fix 

## For feature request

https://github.com/hexojs/hexo/issues/2134

**Comment by NoahDragon** [comment]
I think you are setting the permalink like `*.html`,  I believe removing the `.html` the tail could fix this issue.
