### ISSUE TITLE
Using lightbox script/plugin in hexo

### ISSUE THREAD

**Issue by cutelittleturtle** [hexojs/hexo#2772]
## Environment Info

Node version(`node -v`):6.10.3

Your site `_config.yml` (Optional): default 

Your theme `_config.yml` (Optional): default

Hexo and Plugin version(`npm ls --depth 0`):
├── hexo@3.3.9
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2

Theme: lanscape, hexo-next

## For question

I am trying to install custom image light boxs such as [baguetteBox](https://github.com/feimosi/baguetteBox.js) and [lightgalleries](https://github.com/sachinchoolur/lightgallery.js) for my blogs.

The themes I am working with are the default landscape and hexo-next.

For both themes the plugins' effects overlay with the current theme's default lightbox effect, say, I have two light box overlaying on top of each other.

The themes come with their own lightbox scripts, so I think that I have to delete them or comment them out. But I am really new to Hexo so I don't really know how to do that (where and what files to edit).

Could someone help? I am asking this because that I might want to replace some other functions in whatever themes I want to use in the future and this is a really good learning opportunity.

Thank you.

The code snippet I have to include the `baguattebox`.

```html
<head>
...
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.min.css">
</head>

<body>
...
<script>
window.addEventListener('load', function() {
  baguetteBox.run('.gallery');
});
</script>
                                                                                                                       
<!-- testing gallery -->
<div class="gallery">
    <a href="img1.jpg" data-caption="Image caption">
            <img src="img1.jpg" alt="First image">
                </a>
    <a href="img2.jpg" data-caption="Image caption">
            <img src="img1.jpg" alt="First image">
                </a>
   <a href="img3.jpg" data-caption="Image caption">
            <img src="img1.jpg" alt="First image">
                </a>
</div>

...
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.js"        async></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.min.js"    async></script>
</body>
```

Related questions (unanswered): [for baguetteBox](https://github.com/feimosi/baguetteBox.js/issues/156), [for lightgalleries](https://github.com/sachinchoolur/lightgallery.js/issues/74)

**Comment by NoahDragon** [comment]
Yes, I think you have modified the theme scripts, or choose a theme doesn't use the lightbox.

**Comment by cutelittleturtle** [comment]
I see. Thank you very much for your comment.
