### ISSUE TITLE
Question/Bug: Why YAML/YML files are parsed and converted to JSON files?

### ISSUE THREAD

**Issue by bhaskarmelkani** [hexojs/hexo#2775]
**Question/Bug: Why YAML/YML files are parsed and converted to JSON files?**

**UseCase**
We have a YAML/YML file in the source directory and when serving/generating (`hexo generate` or `hexo serve`), the file is converted to a JSON file.

**Example**: 
Directory Structure:
```
+ source
    - abc.md
    - test.yaml
```

Output
```
+ public
    - abc.html
    - test.json
```

I guess this not a bug and is done on purpose. As the following code is responsible for the behaviour.
[lib/plugins/renderer/index.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/renderer/index.js#L19)

**Is there a way that we can avoid this, as we have some yml/yaml files in our source and we need them as it is.**

**Comment by NoahDragon** [comment]
You could set the skip to render files or directory in the _config.yml

https://hexo.io/docs/configuration.html#Directory
