### ISSUE TITLE
TOC excluding marks?

### ISSUE THREAD

**Issue by cutelittleturtle** [hexojs/hexo#2777]
## Environment Info

Node version(`node -v`):6.10.3

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.3.9
├── hexo-all-minifier@0.2.6
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-light-gallery@1.0.1
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
├── hexo-tag-cplayer@1.0.0
├── hexo-tag-post-link@1.0.6
├── hexo-tag-soundcloud@1.0.2
└── purify-css@1.2.5

## For question

Is there a way to exclude some `#Header lines` from Hexo's default `toc` functionality?

For example: I have 

```
# Title1
## sub-title1
## sub-title2
#Title2
#Thisisnotatitle  // exclude with some code
#Title2
## sub-title3
## sub-title4
```
After rendering, the table of content will not contain #Thisisnotatitle  .

Thanks.

**Comment by tea3** [comment]
@cutelittleturtle  Why do you want to exlude `#Thisisnotatitle` from toc ?

**Comment by cutelittleturtle** [comment]
Because I want to use the <h2> style to decorate my text.
