### ISSUE TITLE
 hexo d ：give me fatal: could not read Username for 'https://github.com': No error

### ISSUE THREAD

**Issue by zhangxiangqiang** [hexojs/hexo#2778]
$ hexo d
INFO  Deploying: git
INFO  Setting up Git deployment...
Initialized empty Git repository in C:/Users/Administrator/myblog/myblog/.deploy_git/.git/
[master (root-commit) 55c568d] First commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 placeholder
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
warning: LF will be replaced by CRLF in 2017/09/28/hello-world/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/09/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2017/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in css/style.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-buttons.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-buttons.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-media.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-thumbs.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-thumbs.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/jquery.fancybox.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/jquery.fancybox.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/jquery.fancybox.pack.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in js/script.js.
The file will have its original line endings in your working directory.
[master 633348f] Site updated: 2017-09-28 13:00:56
 29 files changed, 5758 insertions(+)
 create mode 100644 2017/09/28/hello-world/index.html
 create mode 100644 archives/2017/09/index.html
 create mode 100644 archives/2017/index.html
 create mode 100644 archives/index.html
 create mode 100644 css/fonts/FontAwesome.otf
 create mode 100644 css/fonts/fontawesome-webfont.eot
 create mode 100644 css/fonts/fontawesome-webfont.svg
 create mode 100644 css/fonts/fontawesome-webfont.ttf
 create mode 100644 css/fonts/fontawesome-webfont.woff
 create mode 100644 css/images/banner.jpg
 create mode 100644 css/style.css
 create mode 100644 fancybox/blank.gif
 create mode 100644 fancybox/fancybox_loading.gif
 create mode 100644 fancybox/fancybox_loading@2x.gif
 create mode 100644 fancybox/fancybox_overlay.png
 create mode 100644 fancybox/fancybox_sprite.png
 create mode 100644 fancybox/fancybox_sprite@2x.png
 create mode 100644 fancybox/helpers/fancybox_buttons.png
 create mode 100644 fancybox/helpers/jquery.fancybox-buttons.css
 create mode 100644 fancybox/helpers/jquery.fancybox-buttons.js
 create mode 100644 fancybox/helpers/jquery.fancybox-media.js
 create mode 100644 fancybox/helpers/jquery.fancybox-thumbs.css
 create mode 100644 fancybox/helpers/jquery.fancybox-thumbs.js
 create mode 100644 fancybox/jquery.fancybox.css
 create mode 100644 fancybox/jquery.fancybox.js
 create mode 100644 fancybox/jquery.fancybox.pack.js
 create mode 100644 index.html
 create mode 100644 js/script.js
 delete mode 100644 placeholder
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (C:\Users\Administrator\myblog\myblog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\Administrator\myblog\myblog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

how can l do?

**Comment by zhangxiangqiang** [comment]
hello, everyone,  l finally solved the problem by replace (https://github.com/zhangxiangqiang/zhangxiangqiang.github.io.git) whith (repo: git@github.com:zhangxiangqiang/zhangxiangqiang.github.io.git)

**Comment by FaradayYin** [comment]
@zhangxiangqiang thank god I see your solution, it took me a few hours trying to solve this problem

**Comment by zazaluMonster** [comment]
@zhangxiangqiang  thanks. 
use command `hexo config deploy.repository git@github.com:[yourgitname]/[yourgitname].github.io.git`

**Comment by Comcx** [comment]
@zazaluMonster Thanks a lot, it works!

**Comment by hcgod** [comment]
> hello, everyone, l finally solved the problem by replace (https://github.com/zhangxiangqiang/zhangxiangqiang.github.io.git) whith (repo: [git@github.com](mailto:git@github.com):zhangxiangqiang/zhangxiangqiang.github.io.git)

replacing by SSH addr. not working for me.

**Comment by hcgod** [comment]
> @zhangxiangqiang thanks.
> use command `hexo config deploy.repository git@github.com:[yourgitname]/[yourgitname].github.io.git`

not working for me, at the latest git version.

**Comment by indig0child** [comment]
> hello, everyone, l finally solved the problem by replace (https://github.com/zhangxiangqiang/zhangxiangqiang.github.io.git) whith (repo: [git@github.com](mailto:git@github.com):zhangxiangqiang/zhangxiangqiang.github.io.git)

Solved my problem, thanks a lot!

**Comment by Polar65** [comment]
someone help me i got this error when run command "hexo d" 

![Code_M0R6U1sYr5](https://github.com/user-attachments/assets/19b7ee9d-e6fe-434e-981b-75ea48ec6702)
