### ISSUE TITLE
How to write markdown in HTML?

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo#2784]
`#` (and `##` and `###`) in md files has the meaning of header 1 (2, 3).

This md header is used by table of content widget.

I want to use a md header that is defined in ejs layout file. 
How to write it in ejs (html) so that it is also used by TOC widget same way as `#`?

`#` equals <%= header %> ?????

**Comment by unnamed42** [comment]
Create an `ends`able tag plugin and wrap your whatever thing in this tag. 
About how to create an `ends`able tag plugin: https://hexo.io/api/tag.html#With-End-Tags
Inside your plugin you can use hexo's renderer API to render your wrapped code.
Renderer usage: https://hexo.io/api/renderer.html
It goes like this in your HTML (assume our new plugin is named `embedded`):
```
{% embedded %}
<!-- our code -->
{% endembedded %}
```
