### ISSUE TITLE
hexo更換主題之後 網頁就會壞掉變成沒主題

### ISSUE THREAD

**Issue by chiehpower** [hexojs/hexo#2786]
不知道為什麼更換主題
只是從landscape換成next
成功的deploy到repository
重新整理網頁之後網頁就壞了...
可以請各位高手幫我看一下是什麼問題嗎?
謝謝!
[](https://chiehpower.github.io/)
repository
[](https://github.com/chiehpower/chiehpower.github.io.git)

**Comment by percy507** [comment]
* 首先，确保你已经把根目录下配置文件（`_config.yml`）中的 theme 字段的值改为了当前使用的主题名
* 然后试试这个：执行 `hexo clean` 命令，并删掉 .deploy_git 文件夹，然后重新生成部署下 `hexo g -d`

**Comment by chiehpower** [comment]
我已經完成了

> 然后试试这个：执行 hexo clean 命令，并删掉 .deploy_git 文件夹，然后重新生成部署下 hexo g -d
也確定有改了當前的主題名稱
但問題依然無法解決...
不知道為什麼會一直壞掉?
想請問一個問題，是否採用的主題要放置於branch?
因為我並沒有創建任何branch
目前只有一個master

**Comment by percy507** [comment]
默认是放在 master 分支的，不需任何改动。

**Comment by chiehpower** [comment]
我現在更換的主題不是默認的，是 next
所以我應該要把next 放在分支?

**Comment by NoahDragon** [comment]
能否分享下你网页的Repo呢，方便查看问题？

**Comment by chiehpower** [comment]
很謝謝您，目前已排除問題！
我先行關閉話題！
