### ISSUE TITLE
404 does not work

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2787]
This issue was documented often here, and I followed all instructions but still it does not work.

I am working in live website and on VPS.

My 404.md looks like this... 
![image](https://user-images.githubusercontent.com/29863525/31275383-4c2a6030-aa97-11e7-8d5d-402a57d0ba21.png)

And this is where I put it...
![404](https://user-images.githubusercontent.com/29863525/31275396-5b012c24-aa97-11e7-8be2-7fa7f7584c30.jpg)

When I go to an error URL like... www.domain.com/kfmwelfmiweifwer3rfjweifj3939
I still get "CANNOT get error", instead of my 404.

How to fix?

**Comment by philerck** [comment]
I have in my htaccess file this: ErrorDocument 404 /404.html and it works for me. Maybe it will help you.

**Comment by rabas007** [comment]
@philerck - I am on a NGINX server.

**Comment by zigagrcar** [comment]
@rabas007 you can define error pages in nginx config file http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page

**Comment by rabas007** [comment]
@zigagrcar - thanks... that solved it for me... :)
