### ISSUE TITLE
the variable (post.photos) is null .

### ISSUE THREAD

**Issue by Lemonreds** [hexojs/hexo#2791]
can't get the photos of post in index page . how to use it correctly !

**Comment by NoahDragon** [comment]
Where did you set the post.photos?

**Comment by Lemonreds** [comment]
i used the function
// site.posts.each(post 
// ....( post.photos is null here 
in index page

**Comment by Lemonreds** [comment]
在index和post页面都获取不到 是我使用错误了么

**Comment by geekrainy** [comment]
use `page.photos` :smiley:

**Comment by Lemonreds** [comment]
such

title: Gallery Post
date: 2013-12-25 00:16:18
photos:
- /assets/wallpaper-2572384.jpg
- /assets/wallpaper-2311325.jpg
- /assets/wallpaper-878514.jpg
- http://placehold.it/350x150.jpg
---
