### ISSUE TITLE
Is there a way to encrypt the whole hexo website?

### ISSUE THREAD

**Issue by xiaopxiaop** [hexojs/hexo#2794]
Node version(node -v): v6.11.3

Your site _config.yml (Optional):

Your theme _config.yml (Optional):

Hexo and Plugin version(npm ls --depth 0):

+-- hexo@3.3.9
+-- hexo-asset-image@0.0.3
+-- hexo-deployer-git@0.3.1
+-- hexo-deployer-heroku@0.1.2
+-- hexo-deployer-openshift@0.1.2
+-- hexo-deployer-rsync@0.1.3
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.2.3
+-- hexo-server@0.2.2
+-- htmlparser@1.7.7
`-- match-words@1.0.0

## For feature request

There are some hexo plugins to encrypt a single post, but what I am looking for is a way to encrypt the whole site without having to encrypt posts one by one.

How can I achieve it? Thanks!

**Comment by NoahDragon** [comment]
Have you tried this https://github.com/MikeCoder/hexo-blog-encrypt ? based on its description, looks like it could encrypt the whole site.

**Comment by xiaopxiaop** [comment]
I didn't try it out, but according to its description, it is needed to make modifications post by post. I don't find in its description that a whole site encryption is supported.
