### ISSUE TITLE
一个奇怪的问题（There has a strange problem）

### ISSUE THREAD

**Issue by Summyj** [hexojs/hexo#2796]
Node version(`node -v`): v6.11.2
Hexo and Plugin version(`npm ls --depth 0`): 

+-- hexo@3.3.8
+-- hexo-blog-encrypt@1.1.12
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-baidu-sitemap@0.1.2
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-helper-live2d@2.0.7
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
`-- hexo-wordcount@3.0.2
## For BUG

description：有人遇到过这个问题吗？描述内容没有显示在页面上，我也没有注释：（Does anyone have this problem? The description was not displayed on the page, but I didn't comment on it: ）

![image](https://user-images.githubusercontent.com/26139198/31549263-3721bc96-b060-11e7-9573-68b80d220848.png)

![image](https://user-images.githubusercontent.com/26139198/31549299-56685d76-b060-11e7-9c3a-d302d1f6538b.png)

可是之前还有的（and the previous one was:）：

![image](https://user-images.githubusercontent.com/26139198/31549358-82421ec8-b060-11e7-8791-6064725c5737.png)

现在却不见了，难道是bug吗？（Now it's gone. Is it a bug?）

可以在我的博客上查看（you can check it on my blog）：http://jmyblog.top/

**Comment by NoahDragon** [comment]
Have you updated the theme recently?

**Comment by Summyj** [comment]
No, I haven't. and my blog's theme is "next"

**Comment by NoahDragon** [comment]
If nothing changes, this shouldn't happen. Could I please take a look at the source code?

**Comment by ky0ncheng** [comment]
Ask theme author.

**Comment by geekrainy** [comment]
Upgrade NexT.
