### ISSUE TITLE
Error pages in Hexo?

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#2799]
Hi,
What is the best way to have 404 error pages in Hexo? I just want to have a template with no header or footer to show the error and with a back button, but when I add a custom layout it still has the site header and footer?

Thanks

**Comment by ky0ncheng** [comment]
https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04

https://www.digitalocean.com/community/tutorials/how-to-create-a-custom-404-page-in-apache

**Comment by NoahDragon** [comment]
You could create a customized layout for error, then create a 404.md file under source folder with the following front-matters:
```
---
title: page not found
layout: error
---
```
