### ISSUE TITLE
可在new page的页面下写多篇文章吗?

### ISSUE THREAD

**Issue by tyrionyu** [hexojs/hexo#2802]
默认在命令行里面输入：
hexo new page "about"

能够在“source/about“的目录下生成一个index.md一篇文章。想在about下写多篇文章可以吗？类似生成一个文章目录一样，能实现吗？

## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by QingShui23** [comment]
可以的。

**Comment by NoahDragon** [comment]
Hexo默认这个是不支持的，一个目录下只能有一篇文章。不过可以手动添加文件到目录下。
