### ISSUE TITLE
Hexo crashes on OSX 10.13 High Sierra

### ISSUE THREAD

**Issue by zanders3** [hexojs/hexo#2803]
## Environment Info

	uname -a
	Darwin Alex-MacBook.lan 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

Node version(`node -v`): v8.7.0

Hexo and Plugin version(`npm ls --depth 0`): 
	hexo-site@3.3.9 /Users/alex/repos/web/zanders3.github.com
	├── hexo-livereload@0.1.0
	├── hexo-renderer-ejs@0.3.1
	├── hexo-renderer-marked@0.3.0
	├── hexo-renderer-stylus@0.3.3
	└── hexo-tag-asset-res@0.1.2

## For BUG

Hexo immediately crashes when I run `hexo` on the command line:

	dyld: lazy symbol binding failed: Symbol not found: _usdt_create_provider
	  Referenced from: /usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node
	  Expected in: flat namespace

	dyld: Symbol not found: _usdt_create_provider
	  Referenced from: /usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node
	  Expected in: flat namespace

	Abort trap: 6

I also tried running `npm install --no-optional`

**Comment by JLHwung** [comment]
You can try with
```
cd /usr/local/lib/node_modules/hexo-cli
npm install hexo-log@0.2.0
```

**Comment by JLHwung** [comment]
@NoahDragon I suggest we release 

hexo 3.4.0
hexo-cli 1.0.4

so that we won't deal with dtrace-provider again.

**Comment by NoahDragon** [comment]
@JLHwung Could you please send me an email to hi@abnerchou.me ? I would like to add you to the npm hexo org, so you also could publish the packages when necessary.

**Comment by JLHwung** [comment]
@NoahDragon Sent email application.

**Comment by JLHwung** [comment]
Please run
```
npm i -g hexo-cli
```
to fix dtrace-provider issues.
