### ISSUE TITLE
How to create a page to show some posts with the home page's style?

### ISSUE THREAD

**Issue by newdee** [hexojs/hexo#2806]
I use the Next's theme, but I don't think it's the problem.
I wanna to create a page to show some posts, but show them like the articles shown on the home page.
So not to create a new menu and link to the categories/new/, because it looks like the categories' page style.

你好，请问下如何新建一个页面用来存放某一类文章，页面样式和主页相同就行，但是如果是通过新建一个菜单然后指向分类目录下的某个地址，显示的风格是分类页面的样式了，如果希望以主页的样式显示这些文章，能看到文章的read more之前的内容，该如何修改？

**Comment by SourceCipher** [comment]
Have same issue, official documentation seems to be very poor

**Comment by ultamatt** [comment]
I also have this question.

**Comment by SourceCipher** [comment]
@ultamatt I sorted that problem by doing the following:

Create new page, for example **Projects**

`hexo new page Projects`

This will create new folder named **Projects** under source folder with _index.md_ file inside.
Open the _index.md_ file which is in the Projects folder and add this:

```
---
layout: projects
title: projects
date: 2017-10-11 00:54:14
---
```

Now this index file redirects your request to the theme's custom file.

Next step is to create _projects.ejs_ file inside your themes folder. In my case is under 

> themes -> myTheme ->layout -> and here is my projects.ejs file

Inside the **projects.ejs** file write something like this:

```
<div class="Index">
   <% site.categories.findOne({name: 'Projects'}).posts.sort('date', -1).each(function(post, i){%>
    <% if (i == 0) { %>
     <li class="first">
    <% } else { %>
    <li>
    <% } %>
    <%- partial('_partial/list-view', { post: post }) %>
    </li>
  <% }) %>
</div>

```

The code above simply checks for the posts tagged with **Projects** name.
You can see it points to the list-view file inside _partial folder.

Create the file _list-view.ejs_ if you don't have one inside _partial folder which is in the same place as your _projects.ejs_ file is and add this:

```
<article class='ListView'>
    <header class="title">
      <% if (post.link){ %>
        <h1>
          <a href="<%= post.link %>"><%= post.title %></a>
        </h1>
      <% } else if (post.title){ %>
        <h1>
          <a href="<%= url_for(post.path) %>"><%= post.title %></a>
        </h1>
      <% } %>
      <%- partial('meta', { post: post }) %>
    </header>
    <div>
      <% if (post.excerpt){ %>
        <%- post.excerpt %>
        <% if (theme.excerpt_link){ %>
          <div class="more-link">
            <a href="<%- url_for(post.path) %>#more"><%= theme.excerpt_link %></a>
          </div>
        <% } %>
      <% } else { %>
        <%- post.content %>
      <% } %>
    </div>
</article>
```

Now add **Projects** link inside your __congig.yml_ to point it to the right files. In my case I have like this:

```
menu:
  Home: /
  Projects: /projects/ <- this will be displayed as Projects and points to the projects folder inside source folder
  Freebies: /freebies/
  Archive: /archives/
  About: /about/
```

And now the last step is to create all the posts you wish to appear inside the projects page.
All the posts are inside the source -> _posts folder and at the top of each post add this:

```
---
title: Hello World
categories:
  - Projects <- this will show that this post needs to appear inside categories page
---
```

It works just fine for me (I haven't published my website yet)..
Now if you create 1 post and add lets say 2 categories **Projects** and **Stuff** and have 2 pages named **Projects** and **Stuff**, then the post will appear inside both of these pages. 

Hope it helps

**Comment by ultamatt** [comment]
This was very very helpful mate. Thank you a lot. 

If you are feeling charitable, can someone point me in the direction of how categories are generated? A bunch of mine are becoming nested for some reason, and to get the proper behavior I had to remove them. I couldn't find anything in the documentation about that.

**Comment by SourceCipher** [comment]
@ultamatt I am not sure about this, but I think every time you add a new category inside the post, it will automatically assign to the category. Lets say you have 1 post with 2 categories: "Bubble-gum" and "Ice-cream" and you adding like this:

```
---
title: Hello World
categories:
  - Projects
---
```

then these categories will show up in your posts (if you display them) and if you have categories page it should show both of them as well. And if you add another post under "Bubble-gum" only, then under your categories should show that you have 2 posts under "Bubble-gum" and 1 under "Ice-creams"

I could be wrong as I don't have category page, nor I display them inside my posts, I just use them to sort to the right pages

**Comment by newdee** [comment]
It doesn't work for me, nothing generate on the new page.And I want to show some articles on one menu but now shown on the home page.
