### ISSUE TITLE
i need help...

### ISSUE THREAD

**Issue by nanqinlang** [hexojs/hexo#2808]
## Environment Info
```js
Node version(`node -v`): 
v8.7.0

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 D:\Linux\Hexo\hexo g\g
+-- hexo@3.3.9
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```
## For BUG
i have change my platform(win / debian), and try to restore it many times, and change hexo's theme to other themes, it all doesn't matter, i'll be crazy aaaaaaaa!!!
![fatal](https://user-images.githubusercontent.com/26526543/31937582-83abf600-b8e7-11e7-8b80-74c2919e12e0.png)

**Comment by tea3** [comment]
@nanqinlang 
This issue seems to be similar [#2397](https://github.com/hexojs/hexo/issues/2379) . Do your markdown files have `categories:` ?

```
---
title: Hello World
tags:
  - program
categories:
  - web
---

Welcome to [Hexo](https://hexo.io/)!
...
```

**Comment by nanqinlang** [comment]
@tea3  
thanks for reply  
i'm certain that my `post.md` files have written catagory.

**Comment by tea3** [comment]
@nanqinlang 
I tried [hexo-theme-cafe](https://github.com/giscafer/hexo-theme-cafe) . but the same problem didn't occur. 

Maybe there is a problem with the posting data.  Please first verify that the same problem occurs with simple markdown file (e.g. `_posts/hello-world.md` only ). Also , please verify similar problems occur with different themes (e.g. [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape)).

**Comment by nanqinlang** [comment]
@tea3  
thanks for reply  
i'll try to check all again.
