### ISSUE TITLE
npm installer runs into Err on ArchLinux

### ISSUE THREAD

**Issue by Siassei** [hexojs/hexo#2811]
The bug was already reported and closed with any action. So, **please try to fix it**!
#2505 
It's a fresh and up to date archlinux installation (with git & Co.) and try to get a blogging software. Hexo locks fine, but if the "easy to use" installer do not run, I will change my decision.
... and the option to use the hexo package from AUR ist not a option, because the last package update was 2015.

**versions**
`
$ node --version
v8.7.0
$ npm --version
5.5.1
`
**Console Output**
`
$root npm install -g hexo-cli
/usr/bin/hexo -> /usr/lib/node_modules/hexo-cli/bin/hexo

> dtrace-provider@0.8.5 install /usr/lib/node_modules/hexo-cli/node_modules/dtrace-provider
> node scripts/install.js

> hexo-util@0.6.1 postinstall /usr/lib/node_modules/hexo-cli/node_modules/hexo-util
> npm run build:highlight

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> hexo-util@0.6.1 build:highlight /usr/lib/node_modules/hexo-cli/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

sh: highlight_alias.json: Keine Berechtigung
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-util@0.6.1 build:highlight: `node scripts/build_highlight_alias.js > highlight_alias.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.1 build:highlight script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! hexo-util@0.6.1 postinstall: `npm run build:highlight`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-24T21_53_10_417Z-debug.log
`

**Comment by ashisherc** [comment]
You want to run the command with sudo for global install. Its an issue with archlinux.

**Comment by demurgos** [comment]
This issue should be solved by [the `0.6.2` version of `hexo-util`](https://github.com/hexojs/hexo-util/releases/tag/0.6.2). This dependency is in the compatible version range for this module. Please try to update your dependencies and check if you still encounter the issue.

@ashisherc You should set proper authorizations on your global node_modules directory and avoir running npm with super user persmissions.

**Comment by ashisherc** [comment]
Oh, thanks. I will do that.
