### ISSUE TITLE
Markdown engine seems not in use, why?

### ISSUE THREAD

**Issue by LookTail** [hexojs/hexo#2812]
## Environment Info

Node version(`node -v`): v6.9.4

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): hexo@3.3.9

## For question

I use `<%- page.content %>` to insert the article into my page, however, no styles are applied to the markdown content, just in the original style of HTML. WHY?

**Comment by tea3** [comment]
@LookTail 
It depends on style of theme.  What do you use the theme ?

**Comment by LookTail** [comment]
@tea3 oh, really? I'm writing my own theme. I thought the Marked would apply some style to the markdown content XD. Thank you for your answer. So I need to write my own style of markdown? Or  there is another solution?

**Comment by tea3** [comment]
@LookTail 
You need to write style for markdown. For example , please see style file in default theme.

https://github.com/hexojs/hexo-theme-landscape/tree/master/source/css
https://github.com/hexojs/hexo-theme-landscape/blob/master/source/css/style.styl

**Comment by LookTail** [comment]
@tea3 Got it! Thank you !
