### ISSUE TITLE
GH006: Protected branch update failed for refs/heads/master

### ISSUE THREAD

**Issue by niaogege** [hexojs/hexo#2817]
Error: remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to a protected branch.
how to resolve this problem?Thanks a lot

**Comment by NoahDragon** [comment]
It is because protected branch doesn't allow force push. Just turn off the protection on that branch, it should work.

**Comment by niaogege** [comment]
Thanks a lot ,under you guidance this problem has resolved !@NoahDragon

**Comment by Hanks10100** [comment]
@niaogege  Is there any way to deploy to a branch without turn off its protection?

**Comment by VitalyArtemiev** [comment]
@Hanks10100 Create a new branch, commit your code to the branch and do a pull request. Someone will have to approve it depending on repo settings.

**Comment by Motaz-Mukhtar** [comment]
> It is because protected branch doesn't allow force push. Just turn off the protection on that branch, it should work.

Thanks You <3

**Comment by rajni16liv** [comment]
> @Hanks10100 Create a new branch, commit your code to the branch and do a pull request. Someone will have to approve it depending on repo settings.

can you tell how to create new branch from master branch?

**Comment by ANHGroup** [comment]
> It is because protected branch doesn't allow force push. Just turn off the protection on that branch, it should work.

thanks

**Comment by yagodorea** [comment]
Hmm I'm having the same problem, and enabling force push isn't solving it.

```
Error: Command failed with exit code 1: git push --tags https://github.com/org/repo HEAD:rc
remote: error: GH006: Protected branch update failed for refs/heads/rc.
```

**Comment by Sumorio** [comment]
好用。删除保护分支的操作就可以了。（在仓库设置中，找到branch分支，删除保护分支；如果你不是仓库的拥有者，则需要拥有者对保护分支进行权限的更改或者允许其他人提交的操作，来保证你可以正常上传文件）
