### ISSUE TITLE
[Question] How to filter a post with its metadata during hexo generation

### ISSUE THREAD

**Issue by huiwang** [hexojs/hexo#2818]
Hello there,

I'd like to create a plugin to filter posts according to its metadata during generation. 
For example, when the post has a date 2017-11-28 and today we are 2017-10-28, I don't want to publish that post.

More context here, my goal is to have a scheduled publishing in hexo with my automated CI pipeline in gitlab. I will create a scheduler in gitlab to run the deployment every day. When a post comes to its publishing day, it will be generatd and deployed. Otherwise, it's only ignored.

Regards,
Hui

**Comment by NoahDragon** [comment]
You could access the metadata in front matters via `page.publish_date` or `post.publish_date` in the filters plugin.
