### ISSUE TITLE
An error occurred while executing the command ‘hexo g’

### ISSUE THREAD

**Issue by QingShui23** [hexojs/hexo#2819]
(node:14880) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  -----------------------------------------------------------
INFO  qiniu state: online
INFO  qiniu sync:  true
INFO  qiniu local dir:  public
INFO  qiniu url:   http://h.4zen.top/
INFO  -----------------------------------------------------------
fs.js:892
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'D:\hexo\public\js'
    at Object.fs.mkdirSync (fs.js:892:18)
    at D:\hexo\node_modules\_hexo-qiniu-sync@1.4.7@hexo-qiniu-sync\cmd.js:15:16
    at FSReqWrap.cb [as oncomplete] (fs.js:313:19)

**Comment by NoahDragon** [comment]
Does the folder `D:\hexo\public\js` exist?
