### ISSUE TITLE
Country and city as category?

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#2825]
Hi,
I wanted to know if it was possible to set a country and city on a post?

**I used this:**
`- [country, Germany] - [city, Berlin]`

This works fine but I want when a user clicks on Germany they will see all the cities as a list under Germany.

**Like so:**

- **Germany**
- Berlin
- Hamburg
- Munich
- Frankfurt

**And then other countries**
- **Spain**
- Barcelona
- Madrid
- Leon
- Sevilla

Many thanks

**Comment by NoahDragon** [comment]
I think you could do the following way:
```
categories:
  - [Germany, Berlin]
  - [Spain, Leon]
```

**Comment by ntot** [comment]
Hi @NoahDragon I tried that also but I wanted when the URL (localhost:4000/news/germany) showed **Germany** the sidebar would should _Berlin_ in the sidebar and when the URL is **Spain** (localhost:4000/news/spain) it shows _Leon_ in the sidebar. Is this possible?

**Comment by NoahDragon** [comment]
@ntot Yes, it is doable. However, you may need to write your own script to derive it. This is a reference issue that discussing how to derive subcategories. https://github.com/hexojs/hexo/issues/2793

**Comment by ntot** [comment]
Thanks @NoahDragon maybe later this will be a part of the hexo core
