### ISSUE TITLE
Categories' directory name changed for no reason, which leads to 404

### ISSUE THREAD

**Issue by PhoenixPan** [hexojs/hexo#2827]
## Environment Info

Node version(`node -v`):
v6.10.0

Your site `_config.yml` (Optional):
Default

Your theme `_config.yml` (Optional): 
Default

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.3.9
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For BUG

Everything works fine locally with `hexo s`, because the folder names under `/public/categories` are just as expected: 

*  General
*  15619-Cloud-Computing
*  LeetCode
*  Linux
*  System-Design

However, when I deploy it with `hexo d`, within my Github repo, I have 

*  **general**
*  15619-Cloud-Computing
*  LeetCode
*  Linux
*  **System-design**

Some say the merge is not case sensitive. So I deleted the folders on Github and deployed again, which should give me `System-Design`, but it was still `System-design`! I search the entire repo, there's no single occurrence of `System-design`. I also didn't configure `category_map` in `_config.yml`. It's either a bug or it must be cached somewhere secretly, in either way I don't think it's good.

Now I have to manually change these two directory's names after each deployment...

## Reproduce
1. I have two posts, with headings: 
```
---
title: News Feed System
categories: System Design
date: 2017-10-09 22:15:03
---
```
```
---
title: 15619 Project1.1 Guide
categories: 15619 Cloud Computing
date: 2017-07-09 17:45:21
---
```
2. Put them under  `_posts\system-design\xxx.md` and `_posts\15619-cloud-computing\xxx.md`, respectively;
3. Run by steps: (1) delete `db.json`, (2) run `hexo clean,` (3) run `hexo g` and then (4) run `hexo s`;
4. Everything seems well locally. But not on my site. For `General` category, I can access through URL `/categories/general/`, I don't know why its lower case (the default URL is and should be`/categories/General/`). As for `System Design`, I can't access even I changed the URL to lower cases.

After this, I found some solutions 
1. Add category_map, I also tried to add "-" in between, but it doesn't work.
2. Use `filename_case: 1`, doesn't work.
3. Some other tricks and combine everything together, doesn't work.

## For question

It feels to me that the categories are not changing at all. Is there a cache or something keeps changing the name back?

## Live demo
https://www.phoenixpan.com/blog/categories/

Source: https://github.com/PhoenixPan/blog

**Comment by NoahDragon** [comment]
I think the reason is that you rename the folder name. Git is not case sensitive by default. You could following the method in https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git to rename a file with case sensitive.
