### ISSUE TITLE
fetchMetadata: sill resolveWithNewModule hexo-cli@1.0.4 checking installable status

### ISSUE THREAD

**Issue by fddlpz** [hexojs/hexo#2828]
Installed when the problem occurs, and then the progress does not move；

**fetchMetadata: sill resolveWithNewModule hexo-cli@1.0.4 checking installable status**

**Comment by kitscode** [comment]
same problem as you, have you found the solution?

**Comment by NoahDragon** [comment]
Have this issue been solved?
