### ISSUE TITLE
hexo installation failed

### ISSUE THREAD

**Issue by Pudge1996** [hexojs/hexo#2831]
iMac:~ pudge$ git --version
git version 2.11.0 (Apple Git-81)
iMac:~ pudge$ node -v
v8.9.0
iMac:~ pudge$ npm -v
5.5.1
iMac:~ pudge$ sudo npm install -g hexo
Password:
npm WARN deprecated swig@1.4.2: This package is no longer maintained
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo/bin/hexo

> fsevents@1.1.2 install /usr/local/lib/node_modules/hexo/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/hexo/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> hexo-util@0.6.1 postinstall /usr/local/lib/node_modules/hexo/node_modules/hexo-util
> npm run build:highlight

> hexo-util@0.6.1 build:highlight /usr/local/lib/node_modules/hexo/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

sh: highlight_alias.json: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-util@0.6.1 build:highlight: `node scripts/build_highlight_alias.js > highlight_alias.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.1 build:highlight script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /Users/pudge/.config │
└──────────────────────────────────────────────────────────┘
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-util@0.6.1 postinstall: `npm run build:highlight`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pudge/.npm/_logs/2017-11-05T03_02_45_986Z-debug.log
iMac:~ pudge$ sudo chown -R $USER:$(id -gn $USER) /Users/pudge/.config
Password:
iMac:~ pudge$

**Comment by JLHwung** [comment]
You can try https://github.com/hexojs/hexo/issues/2785#issuecomment-338391933 for a fix of permission issues.
