### ISSUE TITLE
npm install -g hexo-cli didn't work on my pc ...

### ISSUE THREAD

**Issue by kitscode** [hexojs/hexo#2833]
my node version is v8.9.0
![errors](https://user-images.githubusercontent.com/18380508/32528700-6d5d0824-c46f-11e7-8c51-ab4a1da5f119.png)

**Comment by kitscode** [comment]
Maybe it's the problems of server of internet ... after so many times of trying, at least 30 times, hexo installed successfully.

**Comment by JLHwung** [comment]
Consider use https://npm.taobao.org/ if you are encountering connection timeout with npm registry.
