### ISSUE TITLE
How do i escape colon in hexo.js markdown

### ISSUE THREAD

**Issue by Shashwatsh** [hexojs/hexo#2839]
## For question

i want to escape : from markdown, adding ```\``` didn't escape ```links\:``` 

Environment Info

Node version(`node -v`): v7.4.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

```hexo-site@0.0.0 /Users/shashwat/Shashwat.tech/Shashwat.tech copy
├── hexo@3.3.6
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-pagination@0.1.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.0
```

**Comment by NoahDragon** [comment]
`:` doesn't render in markdown. Why do you need to escape it?

**Comment by Shashwatsh** [comment]
sorry my fault!
