### ISSUE TITLE
og:url contains unnecessary trailing /index.html, using default theme

### ISSUE THREAD

**Issue by jakub-g** [hexojs/hexo#2841]
$ node --version
v8.6.0

hexo-site@0.0.0
├── hexo@3.4.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0

Using default theme (landscape), hexo generates some open graph metadata:

```
<meta property="og:type" content="...">
<meta property="og:title" content="...">
<meta property="og:url" content="https://example.com/blog/title/index.html">
<meta property="og:site_name" content="...">
<meta property="og:description" content="...">
<meta property="og:locale" content="...">
<meta property="og:updated_time" content="...">
```

The `og:url` contains `/index.html` at the end which is not necessary.
I'm not sure where it is coming from though.

The code for open_graphs reads `options.url || this.url`
https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/open_graph.js#L46
`options.url` is not passed from default theme
https://github.com/hexojs/hexo-theme-landscape/blob/master/layout/_partial/head.ejs#L25
but somehow the value is generated, so `this.url` must be injected somewhere.

IMO it would be best to fix the `this.url` wherever it comes from.
A fix I did on my side was passing `options.url` from `head.ejs` but it's a bit of a hack:

```
open_graph({ url: page.permalink, ... }
```

BTW It seems that hexo-cli is not using the latest version of `hexo-theme-landscape`
It seems it's using assets as a git submodule  https://github.com/hexojs/hexo-cli and the reference is a very old one (>1 year)

**Comment by ertrzyiks** [comment]
I have the same problem, but hack with `page.permalink` doesn't work for me - it's empty on home page for example and URL with `/index.html` is used.

I ended up doing:
```
open_graph({ url: url.replace('/index.html', '/'), ... }
```
however I don't like it at all.

**Comment by JLHwung** [comment]
> BTW It seems that hexo-cli is not using the latest version of hexo-theme-landscape
It seems it's using assets as a git submodule https://github.com/hexojs/hexo-cli and the reference is a very old one (>1 year)

Thanks for kind reminder, just updated the theme to the latest version.
