### ISSUE TITLE
Regression between 3.3.0 and 3.4.0: wrong URL of image (using asset_img)

### ISSUE THREAD

**Issue by jakub-g** [hexojs/hexo#2842]
node 8.6.0
hexo-site@0.0.0 c:\git\nublog
├── hexo@3.4.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0

I bumped from 3.3.0 to 3.4.0 and now the images are not working.

I use this syntax

     {% asset_img image.png "Title for the image" %}

and this config, as per the comment states 

```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://example.com/blog
root: /blog/
permalink: :title/
permalink_defaults:
```
and later
```
post_asset_folder: true
```

After upgrading hexo and doing `hexo clean; hexo generate; hexo server` the images path is generated as

     <img src="/blog/blog/article-title/image.png">

instead of

     <img src="/blog/article-title/image.png">

The same happens both on index page and article page.

**Comment by jakub-g** [comment]
Ah well I just had a look over commits

Looks like this should fix it https://github.com/hexojs/hexo/pull/2824 but it was not released yet. Maybe there should be a patch release published?

**Comment by JLHwung** [comment]
3.4.1 is released, thank you for your reminder.
