### ISSUE TITLE
Combining JS/CSS resources?

### ISSUE THREAD

**Issue by gergelyke** [hexojs/hexo#2843]
Hi,

is there an easy way to combine css / js resource on build?

Thanks,
Gergely

**Comment by bhaskarmelkani** [comment]
Hey,

You can give this [plugin](https://github.com/hexojs/hexo-asset-pipeline) a try.

[hexojs/hexo-asset-pipeline](https://github.com/hexojs/hexo-asset-pipeline).

Let me know if you need any help :)

**Comment by NoahDragon** [comment]
What do you mean combining them? uglify them?
