### ISSUE TITLE
TOC. $1 in headings

### ISSUE THREAD

**Issue by aerohub** [hexojs/hexo#2844]
Hi,

the problem is: if I have $1 in headings it is trimmed in generated TOC. 

**Example:**
Heading in source post text `### If I Had $1000000`
becomes `<h3>If I Had $1000000</h3>`
but TOC item looks like this `If I Had 000000`

If I use double $ in heading then the TOC item looks good but generated `<h3>` does not:
Source: `### If I Had $$1000000`
HTML: `<h3>If I Had $$1000000</h3>`
TOC item: `If I Had $1000000`

**Comment by bhaskarmelkani** [comment]
When generating toc(id) from text content of `<h3>`, [slugize](https://github.com/hexojs/hexo-util/blob/master/lib/slugize.js#L19) is removing special characters including `$` from it.

I think there's no harm whitelisting `$` from [here](https://github.com/hexojs/hexo-util/blob/master/lib/slugize.js#L6).

@NoahDragon thoughts ?

**Comment by aerohub** [comment]
@bhaskarmelkani but why it removes only one `$` in case of `$$`?

**Comment by aerohub** [comment]
And one more thing. @bhaskarmelkani, when `$` is placed at the end it works good:

Source: `### If I Had 1000000$`
HTML: `<h3>If I Had 1000000$</h3>`
TOC item: `If I Had 1000000$` with `(href="#if-i-had-1000000$")`

It removes `$` + `digit`

**Comment by bhaskarmelkani** [comment]
Wierd ideally it should remove all `$` and I tried wit my setup it works in that way.

What is your config ?

**Comment by aerohub** [comment]
@bhaskarmelkani I use latest node & npm, Hexo 3.2.2 and modified [Tranquilpeak](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/) theme. I suppose that hexo-toc may conflict with jQuery or any of its plugin. But not sure
