### ISSUE TITLE
Raise warning when calling hexo

### ISSUE THREAD

**Issue by dlmyb** [hexojs/hexo#2847]
`(node:34278) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.`

it seems like some of hexo configs lack update.

BTW, My node version is v8.9.1

**Comment by JLHwung** [comment]
What is the version of `hexo-fs`? You can run by `npm ls hexo-fs`.

**Comment by dlmyb** [comment]
Oops... here it is:

```
npm ls hexo-fs
hexo-site@0.0.0 <hexo-path...>
├─┬ hexo@3.4.0
│ ├─┬ hexo-cli@1.0.4
│ │ └── hexo-fs@0.2.2  deduped
│ └── hexo-fs@0.2.2
└─┬ hexo-abbrlink@2.0.4
  └── hexo-fs@0.1.6
```

**Comment by JLHwung** [comment]
The deprecation warning is from `hexo-fs@0.1.6` used by `hexo-abbrlink`. Please raise an issue on [hexo-abbrlink](https://github.com/rozbo/hexo-abbrlink) to have them upgrading to `hexo-fs@^0.2.0`.
