### ISSUE TITLE
hexo: command not found

### ISSUE THREAD

**Issue by NemoAlex** [hexojs/hexo#285]
OS X 10.7.5
npm install -g hexo
成功后，/usr/local/share/npm/bin 中已经有 hexo
可是 hexo 命令无效

**Comment by eyeA** [comment]
the same issue,have you got it ?waitting.....

**Comment by jinagamvasubabu** [comment]
Still i am facing the same issue,

**Comment by eyeA** [comment]
@jinagamvasubabu  npm install -g hexo-cli ,have a try ang tell me the result,THX...

**Comment by jinagamvasubabu** [comment]
Hi @eyeA ,

I am facing this issue while running any hexo commands.

`ERROR Local hexo not found in ~/vasubabu_blog
ERROR Try running: 'npm install hexo --save'`

Thanks,
Vasubabu

**Comment by debashisgithub** [comment]
Hi,
I am facing this issue while running any hexo command

ERROR Local hexo not found in /var/www/.....
ERROR Try running: 'npm install hexo --save'

OS : ubuntu 16.04.1

Thanks

**Comment by huanjulu** [comment]
hi ， i have shell " npm install -g hexo-cli " , its tips successfuly. and i sm sure that install Node.js . but  i hava the same issus , " hexo: command not found "  . i hava dismiss something ?

**Comment by eyeA** [comment]
@jinagamvasubabu ,I think you should show us the process of your building your project,such as:hexo init ...and so on....This may let all of us find where is the QUESTION.

**Comment by Ycomer** [comment]
First you must sure that you installed Node.js(new version),then "npm install -g hexo"

**Comment by johmarjac** [comment]
I am on Windows and have the same problem?
