### ISSUE TITLE
Command line override configuration

### ISSUE THREAD

**Issue by xuexb** [hexojs/hexo#2852]
## Environment Info

Node version(`node -v`): v9.0.0

Your site `_config.yml` (Optional):

```yaml
cssmin: true
```

## For question

Can I use command-line arguments to overwrite? Such as `hexo generate --cssmin=false` .

Because using `hexo --config other.yml` when my profile is overloaded causes me to maintain multiple profiles.

Thanks~

**Comment by NoahDragon** [comment]
I don't think hexo is going to support this use case.
