### ISSUE TITLE
Hexo fails to parse markdown after a ending tag 

### ISSUE THREAD

**Issue by shubhendusaurabh** [hexojs/hexo#2854]
## Environment Info

Node version(`node -v`):
v8.4.0
Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 /home/shubhu/dev/site
+-- handlebars@4.0.11
+-- hexo@3.3.9
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-migrator-wordpress@0.1.2
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-handlebars@2.0.2
+-- hexo-renderer-pandoc@0.1.1
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
+-- lodash@4.17.4
`-- moment@2.19.2
### my block plugin code 
```js
hexo.extend.tag.register('button', function (args, content) {
  let href = args[0]
  return `<div class="tc"><a class="f6 dark-blue" href="${href}" target="_blank">${content}</a></div>`
}, {ends: true, async: true});
```
### sample markdown
```md
---
title: 'Wet Wipes'
tags:
  - kids
id: 204
categories:
  - Best-Of
date: 2016-12-08 14:29:15
---

## How to choose wet wipes

### Little's Soft Cleansing Baby Wipes


Ideal for gently cleansing and moisturizing your baby's delicate skin during diaper change or for cleaning your baby's face and hands during mealtime, playtime and while travelling
Enriched with the goodness of Aloe Vera and Vitamin E, to ensure that your baby's skin remains soft and moisturized, while the gentle fragrance of the wipes keeps your baby fresh and happy all day long without casuing any irritation
10x16x6 cm


{% button https://www.amazon.in/gp/product/B01GTULH10/ %}Check Price{% endbutton %}

### Aloe Vera Wet Wipes

Enriched with aloe vera and chamomile extract
Enriched with vitamin E extract
Ph balanced and hypoallergenic
Dermatologically safe and paraben and alcohol free
Mild fragrance
Handy pack


{% https://www.amazon.com/Fisher-Price-My-First-Thomas-Friends/dp/B00BQYR0MU %}Check Price{% endbutton %}
```
![screenshot-2017-11-18 10 best remote control cars for 2 3 and 4 year olds](https://user-images.githubusercontent.com/1818387/32980746-5b79afce-cc92-11e7-9730-0afff9889d7d.png)

The bug goes away if I break the endtag on new line
```
{% https://www.amazon.com/Fisher-Price-My-First-Thomas-Friends/dp/B00BQYR0MU %}
Check Price
{% endbutton %}
```

**Comment by NoahDragon** [comment]
You are right the open tag and close tag should on different lines.

**Comment by shubhendusaurabh** [comment]
Why the need to keep ending tag on a different line? IMO their usage should be like HTML tag.

For eg. Wordpress allows enclosing shortcodes on the same line or multi.

**Comment by NoahDragon** [comment]
The tag plugin like injection code into markdown format, there are technical difficulties to identify tag code, markdown syntax, or even plain text. We are welcome any PR to resolve this issue.
