### ISSUE TITLE
Missing and unclear documentation for "ignore" setting.

### ISSUE THREAD

**Issue by darekkay** [hexojs/hexo#2855]
Before PR #2631, we already had those options [documented](https://hexo.io/docs/configuration.html):
- `skip_render`: "Paths not to be rendered"
- `exclude`: "Hexo process will ignore files list under this field"

Now we also have `ignore` (which is a live saver btw!), described here as "Ignore files from processing that are not required.", which is both missing in the official documentation and which sounds pretty similar to `exclude`.

I would like to contribute a PR to complete/fix the docs, but the real difference between `exclude` and `ignore` is not clear to me (other than `exclude` not having worked for the exact use case described in PR #2631, i.e. `theme/node_modules` or `theme/.git`).

**Comment by bhaskarmelkani** [comment]
Hey,

I still have to check `exclude` in detail, but here's my point of view for now.
* `skip_render`: It check whether a file(`md`, `ejs`, `html`) should be rendered to `html` or not.

* `exclude`: I think that it checks files in `source` folder and decides whether to process fils/dirs or not depending on the values of `exclude`, but the files are still read and  their data(hash, modified time...) is stored in `db.json` file. They are just skipped from being processed.

* `ignore`: It is to ignore directories that are not useful in the entire folder including folders like `source`, `theme`. It comes very early when the [`box`](https://hexo.io/api/box.html)  processor reads all the files/dirs. 

> Note, `ignore` ignores directories not files.

**Comment by curbengh** [comment]
https://github.com/hexojs/site/pull/1195
