### ISSUE TITLE
markdown to html，There's a problem with Angle brackets

### ISSUE THREAD

**Issue by kiven517** [hexojs/hexo#2861]
## Environment Info

Node version(`node -v`):
```
$ node -v
v8.9.1
```
Hexo and Plugin version(`npm ls --depth 0`): 
```
$ npm ls --depth 0
hexo-site@0.0.0 D:\workspace\git\Hexo\blog
+-- hexo@3.4.1
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```

## For question

![](http://ono3vb8rf.bkt.clouddn.com/FpAO3pk7bIdqJSSJ-BfkxdUaimI3.png)

As shown in the picture above.
In the Markdown, the Angle brackets need to escape, when I use `\` escape, after using ` hexo s --debug ` start the service, to view the article, is showing `\`.
What can I do to make the page correctly display the contents of the original text?
I hope to give some guidance or advice.
Thank you very much

**Comment by NoahDragon** [comment]
It is caused by the confliction with nunjucks, which used for tag and helper in Hexo.
