### ISSUE TITLE
node-sass: File to import not found or unreadable: ./node_modules/

### ISSUE THREAD

**Issue by jonathanlinat** [hexojs/hexo#2863]
Hi,

This is my project files/folders structure:

```
myproject/
  themes/
    mytheme/
      .node_modules/
      source/
        css/
          mytheme.sass
      _config.yml
      package.json
```

So, I modified my `myproject/themes/mytheme/source/css/mytheme.sass` file in order to import two _node_modules/_ packages:

```
@import "./node_modules/minireset.css/minireset.sass"
@import "./node_modules/components-font-awesome/scss/font-awesome"
```

But when I execute `hexo server` and I navigate through my localhost server, I got this error message in Terminal:

```
Error: File to import not found or unreadable: ./node_modules/minireset.css/minireset.sass.
Error: File to import not found or unreadable: ./node_modules/components-font-awesome/scss/font-awesome.
```

So, how should I import these packages into my main SASS file? I'm using **hexo-renderer-sass**.

Regards.

**Comment by JLHwung** [comment]
This is not related to hexo and issues should be raised on hexo-renderer-sass, see https://github.com/knksmith57/hexo-renderer-sass/pull/38#issuecomment-346514890
