### ISSUE TITLE
xn-- appearing in urls and causing 404

### ISSUE THREAD

**Issue by s10wen** [hexojs/hexo#2864]
Hi, I'm using the landscape theme and noticed I have some 404s such as:

https://s10wen.com/blog/2016/02/18/mcrfred-35-lightning-talks/xn--

I've tried searching the codebase for `xn--` but can't find anything, doing some googling I found: https://www.punycoder.com/ where xn--c1yn36f = `點看` so wondering if there's a character that's causing the issue, but not sure what to search for.

Any ideas please?

**Comment by tomap** [comment]
Could you tell us where those links are created? (from a .md file, .html, ...
```xn--``` is only the start of the IDN (international domain named)
Do you store the sources of your blog on github?

**Comment by s10wen** [comment]
I'm not sure where it's coming from, I'm using the app 'Integrity':
https://itunes.apple.com/gb/app/integrity/id513610341?mt=12

<img width="1066" alt="screen shot 2017-11-22 at 09 07 17" src="https://user-images.githubusercontent.com/1136114/33118775-c450209e-cf64-11e7-857a-0dd4d19cf0aa.png">

This shows the `xn--` 404 links, however, on viewing the source at:
```
https://s10wen.com/blog/2016/02/18/mcrfred-35-lightning-talks/
```

I can't find an instance of `xn--`.

🤔

**Comment by tomap** [comment]
There seem to be no issue with your links:
https://validator.w3.org/checklink?uri=https%3A%2F%2Fs10wen.com&hide_type=all&recursive=on&depth=10&check=Check

**Comment by s10wen** [comment]
@tomap ah, nice link, thanks. Yeah, interesting! Wonder if it's a bug on the app side.
