### ISSUE TITLE
Hexo adds <br> if the post body contains html codes of lists

### ISSUE THREAD

**Issue by huyingjie** [hexojs/hexo#2868]
## Environment Info

Node version(`node -v`):8.5.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): Next

Hexo and Plugin version(`npm ls --depth 0`): 
── hexo@3.4.1
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-searchdb@1.0.8
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-next-list-related-posts@1.0.1
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
## For BUG

I pasted the following code into a post content:

```html
<ol type="1">
	<li>option 1</li>
	<li>option 2</li>
</ol>
```

The source code of post after deploy is 

```html
<ol type="1"><br>   
 <li>option 1</li><br>    
<li>option 2</li><br>
</ol>
```

Hexo automatically adds `<br>` after the lines `<ol>`, `<li>`

I am not sure whether it is a render problem. I checked the source code of `hexo-renderer-marked`. There was no code related to `<br>`

How can I solve this issue?

**Comment by NoahDragon** [comment]
I think this is a known issue in marked render. Have you tried the `hexo-renderer-marked-it`?

**Comment by huyingjie** [comment]
@NoahDragon Do you mean `hexo-renderer-marked`? https://github.com/hexojs/hexo-renderer-marked

It seems works.
