### ISSUE TITLE
how to show post title correctly when html files are used as posts

### ISSUE THREAD

**Issue by huyingjie** [hexojs/hexo#2869]
Steps to reproduce the behavior

1. I have a html file
2. move the html file to `source/_posts` folder
3. run `hexo s`

If we put html files in `_posts` folder, hexo will automatically combine html files and the theme. The content of the html files is now the content of the new posts. 

On the homepage, the titles of the posts generated are "Untitled". When the default `landscape` theme is active, the "recent posts" on the sidebar show the same result. This is not what I wanted. I hope that the titles of the posts are those of original html files. In addition, how to set excerpt, tags, categories, and additional yaml varaibles for this type of posts? How can I achieve this?

**Comment by MegaJ** [comment]
You might have figured this out already, but I believe you have to have front matter in your html files. It won't conform to html spec since you would have to preface, in your document (warning, untested):

myHtmlFile.html
```
---
title: Not Untitled
tags: [tagA, tagB]
customVariable: custom
---

<html>
    <head>
        <meta charset="UTF-8"/>
        <title>Document</title>
    </head>
    <body></body>
</html>
```
