### ISSUE TITLE
fs.SyncWriteStream is deprecated

### ISSUE THREAD

**Issue by Robin-front** [hexojs/hexo#2871]
## Environment Info

(node:35784) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
hexo: 3.3.7
hexo-cli: 1.0.4
os: Darwin 16.7.0 darwin x64
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

**Comment by JLHwung** [comment]
Closed in duplicates of #2752
