### ISSUE TITLE
windows10 系统安装hexo问题

### ISSUE THREAD

**Issue by lisn8271** [hexojs/hexo#2873]
windows系统安装hexo，已经安装好git  和 nodejs，其中nodejs版本为 9.2.0，
装完之后，发现无须安装hexo，nodejs9.2.0安装完之后好像自带hexo
问题：
git bash 中，hexo init blog  输入后，直接卡住了，请问怎么解决呢？
![image](http://images2017.cnblogs.com/blog/1236696/201711/1236696-20171129205631714-432131430.png)

**Comment by 007tom** [comment]
正常，用不了几分钟的。。。耐心点！

**Comment by lisn8271** [comment]
但是等了一下午，都没搞定了。。。。。

**Comment by 007tom** [comment]
删掉blog，重新hexo init试一下

**Comment by MaugerWu** [comment]
文件夹命名尽量不要去使用中文（列如你的 D:\我的文档\...），可以试一下
