### ISSUE TITLE
Can Hexo handle async helpers?

### ISSUE THREAD

**Issue by 9662** [hexojs/hexo#2874]
Node version: `v8.9.1`

Hexo version:
```
├── hexo@3.4.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
```

`scripts/helper-test.js`:

```javascript
'use strict';

function test () {
	return new Promise ( (resolve, reject) => {
		resolve("a test");
	});
}

hexo.extend.helper.register('async', test);
```
`layout/theme/test/template.ejs`:

```ejs
Hello, this is <%= async() %>.
```

## Expected result:

```
Hello, this is a test.
```

## Actual result:

```
Hello, this is [object Promise].
```

See also #960.

**Comment by 9662** [comment]
Ok, searching a bit more, this turns out to be an EJS issue: https://github.com/mde/ejs/issues/262

**Comment by Gerhut** [comment]
try nunjucks

**Comment by 9662** [comment]
After looking into this, I think in general a more sane approach is to do any async tasks before rendering.

**Comment by huiwang** [comment]
@Gerhut could you please provide more details on how nunjucks could help?

**Comment by huiwang** [comment]
@9662 why is it more sane? Did you find a solution for your problem?

**Comment by 9662** [comment]
@huiwang 

> why is it more sane?

Because collecting all the data that you will need to render first, and then doing the actual rendering results in better separation of concerns, as opposed to producing data during render. There might be cases where the rendering itself requires asynchronism so it may still be desirable to be able to render asynchronously, but that is a separate case.

> Did you find a solution for your problem?

Yes, as I recall (don't have that project handy at the moment), I implemented a generator that did the asynchronous bit before the rendering.

**Comment by huiwang** [comment]
Thanks a lot @9662, for your help but it's not clear for me 😩  

> Yes, as I recall (don't have that project handy at the moment), I implemented a generator that did the asynchronous bit before the rendering.

As far as I understand(which might be wrong), the generation stage and rendering stage are not sychronous. This means that we can start rendering without the results made ready by the asynchrounous generator.

**Comment by huiwang** [comment]
@9662 I can confirm that asynchronous tasks started in generator is not blocking regarding redering tasks. My approch is to create a separate command to prepare the needed data for rendering. examples can be found here https://github.com/huiwang/hexo-recommended-posts/blob/master/index.js

**Comment by 9662** [comment]
Hello @huiwang, I haven't tried it, but I think you could try doing your async fetching in a [`before_post_render`](https://hexo.io/api/filter#before-post-render) or [`before_generate`](https://hexo.io/api/filter#before-generate) filter.

**Comment by huiwang** [comment]
The only async support I find is about tag. Happy new year!

**Comment by 9662** [comment]
> The only async support I find is about tag

Looks like filter [supports promises](https://github.com/hexojs/hexo/blob/5234c4a85dc6cd418e9a1c169e43de169cf98e95/lib/extend/filter.js#L58) even though it does not seem to be documented.

**Comment by GARENFEATHER** [comment]
Anyone tried it?

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
