### ISSUE TITLE
my <style> element in markdown is parsed unexpectedly.

### ISSUE THREAD

**Issue by lzl124631x** [hexojs/hexo#2876]
## Environment Info

Node version(`node -v`): v8.9.1

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 C:\Richard\Project\lzl124631x.github.io
+-- hexo@3.4.2
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For question

I have some `<style>` elements in side of my markdown. They are parsed by hexo which results in broken page:

```
<style><br>.droplet {<br>  display: inline-block;<br>  width: 4em;<br>  height: 4em;<br> 
```

Can I disable this behavior?

**Comment by NoahDragon** [comment]
Not sure how this happened. Does it happen recently?

**Comment by lzl124631x** [comment]
@NoahDragon  Yes, it just happened last week.  This is not by design? I'll verify this again later.

**Comment by tcrowe** [comment]
@lzl124631x Would you be able to see if you have any of the `marked:` options set in your `_config.yml` please? https://github.com/hexojs/hexo-renderer-marked#options

Thanks!

**Comment by lzl124631x** [comment]
@tcrowe I downgraded my node version. This is my updated environment.
```
$ npm -v
2.15.11
$ node -v
v4.8.6
$ npm ls --depth 0 | grep hexo
hexo-site@0.0.0 C:\Richard\Project\lzl124631x.github.io
├── hexo@3.4.2
├── hexo-bunyan@1.0.0
├── hexo-front-matter@0.2.3
├── hexo-fs@0.2.2
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-i18n@0.2.1
├── hexo-log@0.2.0
├── hexo-pagination@0.0.2
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
├── hexo-util@0.6.2
```

And the problem is automatically gone.

**Comment by lzl124631x** [comment]
Hi, @NoahDragon @tcrowe Sorry, I met this same problem again.

There is no `marked` config in my `_config.yml`.

[This post](https://github.com/lzl124631x/lzl124631x.github.io/blob/master/_posts/2016-08-14-tweenmax.md) and [this post](https://github.com/lzl124631x/lzl124631x.github.io/blob/master/_posts/2016-07-03-table-border-radius.md) are broken.

**Comment by lzl124631x** [comment]
@NoahDragon @tcrowe soft ping.

**Comment by tcrowe** [comment]
Hey @lzl124631x I did a quick test:

```sh
mkdir style-test
cd style-test
hexo init
# add style code
hexo clean && hexo serve --debug
```

Style code:

```html

<style>
.droplet {
  display: inline-block;
  width: 4em;
  height: 4em;
}
</style>

<div class="droplet">
  droplet class example
</div>
```

This did not yield the result you mentioned.

```text
style-test›npm ls --depth 0
├── hexo@3.5.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

```text
style-test›node -v && npm -v
v8.9.4
5.6.0
```

**Comment by tcrowe** [comment]
<img width="556" alt="screen shot 2018-02-22 at 5 57 29 pm" src="https://user-images.githubusercontent.com/1634015/36572603-f9c32a36-17f9-11e8-8f78-afdbe666ff44.png">

**Comment by tcrowe** [comment]
Landscape theme ⬆️

**Comment by lzl124631x** [comment]
@tcrowe Thanks for your update. I just had a try and still had problem. [This post](https://github.com/lzl124631x/lzl124631x.github.io/blob/master/_posts/2016-08-14-tweenmax.md) can repro this problem. The droplet part worked fine now but the heart part still doesn't work.

[This](http://lzl124631x.github.io/2016/08/14/tweenmax.html) is what I got with Jekyll. You can see the heart is beating. 

![heartbeat](https://user-images.githubusercontent.com/5824517/39164624-276de9fc-4735-11e8-93ca-acb8ac1db296.gif)

But in hexo I got

![image](https://user-images.githubusercontent.com/5824517/39164629-3f3ea238-4735-11e8-8ad0-1287b4a58144.png)

Is that because my markdown is malformatted? 

Oh wait. I found that I have to put an empty line after `<style>...</style>` and before `<span class="heart beating"></span>` in hexo. But in jekyll I don't have to do it. Do you know why?
