### ISSUE TITLE
How to run Hexo Server permanently in Centos 7 und with Virtualhost(Apache)

### ISSUE THREAD

**Issue by AlexL777** [hexojs/hexo#2880]
## Environment Info

Node version(`node -v`): v6.12.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

    ├── hexo@3.4.2
    ├── hexo-generator-archive@0.1.5
    ├── hexo-generator-category@0.1.3
    ├── hexo-generator-index@0.2.1
    ├── hexo-generator-tag@0.2.0
    ├── hexo-renderer-ejs@0.3.1
    ├── hexo-renderer-marked@0.3.0
    ├── hexo-renderer-stylus@0.3.3
    └── hexo-server@0.2.2

## For question

Hello Developers,

how can I run hexo on port 4000 permanently? If I go "hexo server", then the server starts. That's understandable, but I close the console, then the Hexo website is not available.

How can I automatically run the Hexo server on Centos 7?

Thanks in advance.

**Comment by JLHwung** [comment]
`hexo server` is not supposed to be production-ready, please run nginx/apache to serve the `public` folder.

If you insist, see https://kb.iu.edu/d/afnz for tutorial to run any process on the background.
