### ISSUE TITLE
[FEATURE] Add Reveal.js to HEXO

### ISSUE THREAD

**Issue by WrRan** [hexojs/hexo#2882]
## Environment Info

Node version(`node -v`):
v6.11.3

Hexo and Plugin version(not `npm ls --depth 0` but from `package.json`): 
    "hexo": "^3.3.9",
    "hexo-deployer-git": "^0.1.0",
    "hexo-deployer-heroku": "^0.1.1",
    "hexo-deployer-openshift": "^0.1.1",
    "hexo-deployer-rsync": "^0.1.2",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^1.0.2",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-kramed": "^0.1.2",
    "hexo-renderer-stylus": "^0.2.3",
    "hexo-server": "^0.2.0"

## For feature request

[reveal.js](https://revealjs.com/#/) is the HTML presentation framework. Would you add this into HEXO?

**Comment by NoahDragon** [comment]
I think this should be a plugin or theme.

Seems some already made one: https://github.com/wicksome/hexo-slides-reveal
Demo: https://wickso.me/2016/04/12/generic/
