### ISSUE TITLE
click300m延迟问题

### ISSUE THREAD

**Issue by zhangAndonis** [hexojs/hexo#2884]
在移动端click事件生效，点击之后有300m的延迟响应
方法一：不用click，用自定tap：需要下载zepto.js在后面加上一段ji
小案例：$('#box').tap(function(){
			$(this).css('background','yellow')
		})
方法二：引入fastclick库的类
首先引入：https://cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js
小案例：$(function() {
			  FastClick.attach(document.body);
			   $('#box').tap(function(){
			    	$(this).css('background','greenyellow')
			    })
			});

**Comment by NoahDragon** [comment]
这个问题有些超出了Hexo的使用范围，先关闭这个Issue。
