### ISSUE TITLE
change farbox theme（jade） to the hexo theme？

### ISSUE THREAD

**Issue by jerry011235** [hexojs/hexo#2888]
hi,guys,I found a farbox theme which is very simple and beautiful.
Can someone change it to the hexo theme？hope to add [search](https://github.com/PaicHyperionDev/hexo-generator-search) and toc.
demo：http://cais.cai-cai.me/
github：https://github.com/hi-caicai/farbox-theme-cais
Thank you very much!

**Comment by tcrowe** [comment]
Hi @jerry011235 

I don't speak their language. Do you?

Maybe you can post:

---

Hi!

We received a request here:
https://github.com/hexojs/hexo/issues/2888

We would like `hexo-theme-farbox` and to publish with https://hexo.io/docs/themes.html#Publishing

I recommend closing this issue and opening it there with them.

**Comment by jerry011235** [comment]
hey! @tcrowe 
Do you mean I should post “We received a request here……balabala” on [their issues page](https://github.com/hi-caicai/farbox-theme-cais/issues)？

**Comment by tcrowe** [comment]
Yeah, they can:
+ `Settings -> Rename` on github
+ rename in `package.json`
+ theme publishing instructions https://hexo.io/docs/themes.html#Publishing

Then their theme can be in the list 👯  🎉

**Comment by NoahDragon** [comment]
Just an FYI. Actually, it is not hard to convert jade theme into hexo, I recently did one https://github.com/NoahDragon/hexo-theme-react . If you interested to convert it on your own, you could take it as a reference.
