### ISSUE TITLE
Generator / plugin lookup path documentation request

### ISSUE THREAD

**Issue by MegaJ** [hexojs/hexo#2892]
Request that documentation be added for how generators get registered. I'm having a hard time seeing how hexo knows where to look for generators, and how it recognizes them. There's nothing in the root directory's `_config.yml` file that tells me what generators a project is using.

I think hexo looks for everything in the package.json. From the default installation I get from the debug:

```
13:30:55.936 DEBUG Plugin loaded: hexo-generator-archive
13:30:55.939 DEBUG Plugin loaded: hexo-generator-category
13:30:55.942 DEBUG Plugin loaded: hexo-generator-index
13:30:55.945 DEBUG Plugin loaded: hexo-generator-tag
13:30:55.951 DEBUG Plugin loaded: hexo-renderer-ejs
13:30:55.953 DEBUG Plugin loaded: hexo-renderer-stylus
13:30:55.962 DEBUG Plugin loaded: hexo-renderer-marked
13:30:56.084 DEBUG Plugin loaded: hexo-server
```

suggesting everything from project root's package.json's dependencies are considered plugins to hexo.

I've definitely searched for these docs for a while, and there are no tutorials on the web documenting this behavior.

Further, from the `load_plugins.js` file, I see that hexo plugins must start with `hexo-`. Without reading the source, I wouldn't have known.

That being said, are there any recommendations for workflow on writing my own generator? hexo looks for a module in `node_modules` based on `package.json` if I'm reading the code correctly, so I have to make a new repo and pull every time I make a change, or make my changes locally?

**Comment by tcrowe** [comment]
✨  That's part of the beautiful magic inside it, @MegaJ ✨  😉

**Comment by tcrowe** [comment]
It's also discussed here that you can put plugins in `./scripts` or `hexo-*` npm modules https://hexo.io/docs/plugins.html

**Comment by MegaJ** [comment]
@tcrowe Thanks! That plugins page makes things a lot clearer. I had been searching specifically for generators so I missed out on that it was actually a type of plugin. I think just a sentence stating or two on the generators doc, something to the effect of 

`Generators are another type of plugin. See the plugin page for information on how to setup your own plugin directory before proceeding.`

 could help others.

**Comment by tcrowe** [comment]
Yeah @MegaJ I only know because I was trying to figure out how to make hexo open the new stuff I was creating

```js
/**
 * inspired from http://howiefh.github.io/2014/02/07/hexo-note/
 *
 * in the terminal the user can do:
 * hexo new post "My cat likes me"
 *
 * - the file will be opened into the editor
 * - it could be improved by using $EDITOR
 */

hexo.on('new', function(target) {
  require('child_process').spawn('subl', [target.path])
})
```

Then I experimented doing my own stylus renderer and pug. I can't remember how they all get prioritized but there's probably something for that.

**Comment by MegaJ** [comment]
I also realized I was looking at generators in the /api/ path of the website. The information about structuring your directories is in the /docs/ path, as you linked above @tcrowe. Nor does https://hexo.io/api/index.html mention how setting up files/folders to write plugins works.

And thanks for the link, I'll familiarize myself more with the api.
