### ISSUE TITLE
TOC anchors become undefined when using with hexo-toc

### ISSUE THREAD

**Issue by konrumi** [hexojs/hexo#2894]
Hello!

  I've used [hexo-theme-beantech](https://github.com/YenYuHsuan/hexo-theme-beantech) as my theme, which depend on [hexo-toc](https://github.com/bubkoo/hexo-toc). Then I found the anchor of side navigator links become `undefined` .

  hexo-toc makes some changes before the HTML was generated after this [commit](https://github.com/bubkoo/hexo-toc/blob/7c9624c2d3fb7d13ce973cb8de4dc10ff865c089/lib/filter.js#L28). It removes the `id` of `<h1>` and create a new `span` element in the `<h1>` for some reason.

  And in hexo's `/lib/plugins/helper/toc.js` , `id` is still gotten from `<h2>`.

  Sorry to bother you but do you think we could fix this in hexo's toc.js or I should just leave this issue to hexo-toc? m(_ _)m

**Comment by MayankTahil** [comment]
Same issue here. I can't get any anchor links in the generated HTML from Markdown in posts.

**Comment by NoahDragon** [comment]
This issue have fix in https://github.com/hexojs/hexo/pull/2898, will be released in next build.
