### ISSUE TITLE
Nested `a` elements should not be used in TOC

### ISSUE THREAD

**Issue by ahonn** [hexojs/hexo#2896]
## Environment Info
hexo: 3.4.3
hexo-cli: 1.0.3
os: Darwin 17.2.0 darwin x64
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l

## For BUG

In 3.4.3 version, TOC anchors become very strange. Now its structure has become like this:

```html
<li class="toc-item toc-level-2">
  <a class="toc-link" href="#Test">
    <span class="toc-text"></span>
  </a>
  <a href="#Test" class="headerlink" title="Test"></a>
  Test
</li>
```

So, I found the problem appeared in this [commit](https://github.com/hexojs/hexo/commit/6fa2d11ecc4f5e77ce40cd1c2548637d551972fb).

But in [this file](https://github.com/hexojs/hexo/blob/6fa2d11ecc4f5e77ce40cd1c2548637d551972fb/lib/plugins/helper/toc.js), the TOC generated HTML should look like this:

```html
<li class="toc-item toc-level-2">
  <a class="toc-link" href="#Test">
    <span class="toc-text">
      <a href="#Test" class="headerlink" title="Test"></a>
      Test
    </span>
  </a>
</li>
```

I found the key place, nested `a` elements are forbidden in HTML syntax. see [Creating anchor tag inside anchor tag](https://stackoverflow.com/questions/13052598/creating-anchor-tag-inside-anchor-tag).

**I think we should continue to use `$(this).text()`, and then use other ways to escape html entities**

**Comment by heyikang** [comment]
I also met this problem
