### ISSUE TITLE
 is_post() return different 

### ISSUE THREAD

**Issue by ccbu** [hexojs/hexo#2897]
## Environment Info

Node version(`node -v`): v8.9.1
Hexo version(`node -v`): v3.4.3

## For BUG

when "hexo server" to start  local server, the function ''<%- is_post() %>" return true,
but when use "hexo g" to generate html,  the function ''<%- is_post() %>" return false.

for this, we get different result betwen local and online!

**Comment by NoahDragon** [comment]
This is a known issue that `hexo s` has different behavior than `hexo g` while rendering a file. Need time to dig into this.
