### ISSUE TITLE
Config title and page title in browser tab

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2905]
How to have the page.title show in browser tab next to the website title?

This is for a Contact us page, so not posts.

theme/layout/contact-us.ejs (page title is Contact)

I tried following, but that did not work:

```
<title>
        <% if (title) { %>
        <%= title %> |
        <% } %>
        <%= config.title %></title>
<div class="contact-us">
  <h1>Contact us <%= page.title %></h1>
```

**Comment by tcrowe** [comment]
Can you see if this example helps? https://github.com/tcrowe/generator-hexo-theme/blob/master/app/templates/layout-ejs/layout.ejs#L3

**Comment by rabas007** [comment]
@tcrowe - thanks for the quick reply.

Unfortunately not... my `layout.ejs` page is a content-page in itself with title, h1, p, text etc, and the `page` title (in my case "Contact us") should correspond to the `page.title` variable but I cannot get it to show and I dont understand why?

**Comment by rabas007** [comment]
@tcrowe - ah, you inspired me to find the solution... thank you, all good. Solution was in index.md.

**Comment by tcrowe** [comment]
Glad you could get it fixed up @rabas007
