### ISSUE TITLE
add hexo-generator-json-content 后就白屏了还无任何错误提示

### ISSUE THREAD

**Issue by wangyapeng** [hexojs/hexo#2906]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by NoahDragon** [comment]
可否运行下`hexo g --debug`?

**Comment by wangyapeng** [comment]
已经发现问题，并解决了
