### ISSUE TITLE
调查-跨博客的相关文章推荐

### ISSUE THREAD

**Issue by huiwang** [hexojs/hexo#2909]
友情链接是大家常用的增加博客间交流的方法，但这种方法是静止的，非常死板。

我有一个新想法，就是在相关文章推荐的那一栏，不仅推荐自己博客的文章，也推荐其他博客相关的文章。当然，这种做法是相对的，在别人的博客里，别人也会推荐你的文章。这样能更灵活，更有效的增进博客间的联系，也可以帮用户发现更多的优质内容，当然也可以增加博客的流量。

比如说在我[这篇文章](http://hui-wang.info/2017/12/10/%E8%8E%B7%E4%BA%86%E4%B8%80%E7%AD%89%E5%A5%96%E5%8D%B4%E4%BB%8D%E7%84%B6%E5%A4%B1%E8%B4%A5%E7%9A%84%E5%88%9B%E4%B8%9A%E7%BB%8F%E5%8E%86/)的结尾，除了推荐博客内的文章，我还推荐了其他资源。

我不知道，我这个想法，有没有什么现实意义，大家觉得呢？

**Comment by NoahDragon** [comment]
这个有点像evernote里的内容推荐。
可以实现，但是需要有一个网页爬虫和文章相似度算法支持，这可能降慢渲染的速度，而且随着文章数的增加，生成速度会比较慢。

**Comment by huiwang** [comment]
@NoahDragon evernote我没用过，所以不知道里是怎么个情况。我的这个小想法，是想跨博客间的文章推荐，能比友情链接好用点。

我看了你博客了，非常感谢你对hexo社区的贡献，太无私了！这个跨博客推荐的服务，你愿意尝试吗？谢谢！

**Comment by huiwang** [comment]
@NoahDragon 第一个版本开发出来了，[这里](https://hui-wang.info/2017/12/02/%E5%AD%A6%E4%B9%A0%E5%A6%82%E4%BD%95%E5%AD%A6%E4%B9%A0/)和[这里](https://reuixiy.github.io/philosophy/how/2017/11/25/a-catalogue-of-the-internet-s-knowledge.html)已经实现了互联， 能不能给点建议？

https://github.com/huiwang/hexo-recommended-posts

**Comment by huiwang** [comment]
谢谢大家的帮助，调查先到此结束。
