### ISSUE TITLE
How to catch Process failed error using hexo cli or api

### ISSUE THREAD

**Issue by mixj93** [hexojs/hexo#2910]
## Environment Info

Node version(`node -v`): in travis 7.9.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.3.7
├── hexo-deployer-git@0.3.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.1

## For question

I use travis to auto deploy a hexo site. When run `hexo generate`, a `Process failed` error occurs, but the `hexo generate` still exit with 0, so travis did not trigger error. [travis job here](https://travis-ci.org/fenggusub/fenggusub/builds/315851266) How can I catch this `Process failed` error? thx a lot
![image](https://user-images.githubusercontent.com/12998118/34031372-00153188-e1ac-11e7-8114-44835e0f7a2d.png)

![image](https://user-images.githubusercontent.com/12998118/34031393-16a121fa-e1ac-11e7-9c18-91127850717e.png)

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo/pull/2886
It usually doesn't harm the result. We may need a flag to allow hard termination when any error occurs.

**Comment by mixj93** [comment]
This PR is what I need
