### ISSUE TITLE
default_category not work

### ISSUE THREAD

**Issue by monotone** [hexojs/hexo#2912]
## Environment Info

Node version(`node -v`):  v8.7.0

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.3.9
├── hexo-deployer-git@0.0.4
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.1.3
├── hexo-generator-tag@0.1.2
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.1.3

## For BUG

Is `default_category` means my post will in the `default_category` category when I not set `categoies` in Front-Matter.

If it is,  why I can`t see it in my Categores menu.

**Comment by NoahDragon** [comment]
can you find a categories folder under the public?

**Comment by monotone** [comment]
Yes, I found.

But, it not have a sub folder named `default` when I have config like this:
```
# Category & Tag
default_category: default
category_map:
tag_map:
```

**Comment by NoahDragon** [comment]
Could you please share your source code?

**Comment by monotone** [comment]
Which code do you want?

**Comment by bejondshao** [comment]
I met this issue since I started to use Hexo 2 years ago. This issue is still there. Does anyone have the same issue or does anyone's default_category works fine to you?


``{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.2"
  },
  "dependencies": {
    "hexo": "^3.4.2",
    "hexo-admin": "^2.3.0",
    "hexo-baidu-url-submit": "0.0.5",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^2.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-markdown-it-plus": "^1.0.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "markdown-it-emoji": "^1.4.0"
  }
}
