### ISSUE TITLE
How to install hexo blog in a remote repo to local machine?

### ISSUE THREAD

**Issue by aaayumi** [hexojs/hexo#2914]
Hi! I'm using hexo in github page. Mistakingly I deleted my local file in my local machine. I tried to make a new local file again by using ```git clonehttps://github.com/aaayumi/aaayumi.github.io.git```. then I installed ```npm install hexo-cli -g ```.

I could install all necessary files but when I typed  ```hexo deploy```,
it shows,
```
hexo deploy
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```

Is there an way to be able to use hexo blog locally?

**Comment by ramonsantos** [comment]
Hello, @aaayumi !

Probably, the repository ```https://github.com/aaayumi/aaayumi.github.io``` contains the files of your generated site, not the source files that Hexo needs to build your site.

To be sure, type the command ```ls``` (Linux or Mac OS) or ```dir``` (Windows) and post the result here.

**Comment by aaayumi** [comment]
Hello @ramonsantos! Thank you so much for your quick reaction.
I got the following result 

`2017		archives	css		img		search.xml
CNAME		atom.xml	images		index.html	sitemap.xml`

As I just cloned my project from my github repository, I guess I don't have the source files that you mentioned... How can I include it to my new file in my local environment?

Thank you for your help..!!

**Comment by NoahDragon** [comment]
@aaayumi if you lost the source files which created by `hexo init`, the easiest way to rebuild the website is:
1. `hexo init` an empty folder
2. Install `hexo-migrator-rss` plugin
3. `hexo migrate rss http://ayumi-saito.com/atom.xml`

This will recover the posts, however, other customization on theme or Hexo will be lost.

**Comment by aaayumi** [comment]
Thank you for the reply.
I tried to `hexo init` but now I received the following message.
```npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ayumi/.npm/_logs/2017-12-24T12_56_31_309Z-debug.log```

Now it seems that I cannot use `hexo` command.

**Comment by ramonsantos** [comment]
@aaayumi, try run:
 ``` bash
sudo hexo init
```

**Comment by aaayumi** [comment]
I received `sudo: hexo: command not found` in the terminal.

**Comment by JLHwung** [comment]
@aaayumi For permission issues, please see https://github.com/hexojs/hexo/issues/2785#issuecomment-338391933.

**Comment by ramonsantos** [comment]
Please, run:
``` bash
hexo -v
```
and post the result here.

**Comment by aaayumi** [comment]
After trying @JLHwung 's advice, I got the following result by running `hexo -v`

    hexo-cli: 1.0.4
    os: Darwin 17.2.0 darwin x64
    http_parser: 2.7.0
    node: 8.9.2
    v8: 6.1.534.48
    uv: 1.15.0
    zlib: 1.2.11
    ares: 1.10.1-DEV
    modules: 57
    nghttp2: 1.25.0
    openssl: 1.0.2m
    icu: 59.1
    unicode: 9.0
    cldr: 31.0.1
    tz: 2017b
