### ISSUE TITLE
Hexo Github webpage missing theme

### ISSUE THREAD

**Issue by moonspell79** [hexojs/hexo#2917]
Hi,
I have a hexo blog running on my linux machine and want to move to github. I was able to "hexo deploy", but don't see "themes\landscape" folder copied to gitbut, thus webpage is only text - no graphics, etc
What might be wrong?

Thanks.

**Comment by NoahDragon** [comment]
There is no theme folder for the deployed website. Did you update the _config.yml? maybe the url need to change according.
