### ISSUE TITLE
embed html in the post but html is rendered

### ISSUE THREAD

**Issue by huyingjie** [hexojs/hexo#2918]
## Environment Info

Node version(`node -v`): v8.5.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

I have one html file called `selfcontain.html` in the `selfcontain.html` folder.

In a post, I include the following code in the Markdown file:
`<iframe width="200" height="300" src="../dynamicplots/selfcontain.html" frameborder="40"></iframe>`

The html file embeded in the post is rendered. How can I prevent the html file rendered if I want to put it in a post?

![screen shot 2017-12-17 at 11 29 09 pm](https://user-images.githubusercontent.com/4664280/34090694-d49e0642-e386-11e7-9247-67e34ea03a4d.png)

**Comment by NoahDragon** [comment]
Could you please elaborate more about rendering html? The html is rendered from markdown file, if you put html in the post, it should show the html as well. Would you like to show the original markdown content?

**Comment by MegaJ** [comment]
This sounds more like an HTML issue than a hexo issue. If you're using iframes and providing a source, the browser will render the html document sepecified by `src`. If you want to display the code of the html, and still have your html in a separate file, you could use nunjuck's ability to `{% include 'path/to/selfcontain.htm %}'` to copy the contents of that file into your markdown during rendering. I've never tried this with hexo.

**Comment by huyingjie** [comment]
I found the solution.  Adding following codes to the global configure file. I tried this method before, but it did not succeed. I guess I did not write `_drafts` or `_posts` at the beginning of the path.

```
skip_render:
    - _drafts/**/**.js
    - _drafts/**/**.html
    - _posts/**/**.js
    - _posts/**/**.html
```
