### ISSUE TITLE
A known security vulnerabilities in your dependencies.

### ISSUE THREAD

**Issue by BBBOND** [hexojs/hexo#2919]
## Environment Info

Node version(`node -v`):
v9.2.0

Hexo and Plugin version(`npm ls --depth 0`): 
├── emoji@0.3.2
├── hexo@3.4.3
├── hexo-admin@2.3.0
├── hexo-blog-encrypt@1.1.12
├── hexo-deployer-git@0.3.1
├── hexo-filter-sequence@1.0.3
├── hexo-fs@0.2.2
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-restful@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-lazyload-image@1.0.2
├── hexo-renderer-markdown-it@3.4.1
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
└── markdown-it-emoji@1.4.0

## For BUG

![image](https://user-images.githubusercontent.com/9862759/34094646-fa99c64c-e408-11e7-9c86-a29c38b77fea.png)

1. Github show a vulnerability alerts.
2. I push `package-lock.json` to the dependency.

## For question

hexo(3.4.3) --> swig(1.4.2) --> uglify-js(2.4.24)

**Comment by NoahDragon** [comment]
Thanks for point this out. We don't think this vulnerability applies to Hexo, unless using it as a server.

https://github.com/hexojs/hexo/issues/2895
