### ISSUE TITLE
Auto-render the string with "http(s)" in code block into hyperlink while using Disqus. 

### ISSUE THREAD

**Issue by ciphersaw** [hexojs/hexo#2921]
## Environment Info

Theme: NexT v5.1.2

## For BUG

See the reaction when the disqus enable is false or true respectively.

### The disqus enable is fasle

The string with "http(s)" in code block is always normal:

![url_string](https://user-images.githubusercontent.com/17273925/34137690-4687290c-e4a7-11e7-8cc7-2527c9eee6bc.png)

### The disqus enable is true

The string with "http(s)" in code block is normal at first, but it changes into a hyperlink later: 

![url_hyperlink](https://user-images.githubusercontent.com/17273925/34194454-cd273d02-e593-11e7-8337-383dd1f5b2fb.png)

Now we see the corresponding source code, which shows what it should be:

![url_string_source](https://user-images.githubusercontent.com/17273925/34194464-d89608ee-e593-11e7-89d7-9729b4eda83b.png)

But the corresponding element code (in F12) is rendered into a hyperlink type automatically:

![url_hyperlink_source](https://user-images.githubusercontent.com/17273925/34194476-e311e72a-e593-11e7-8cc2-b921703b67a0.png)

Note that the attribute "class" in label <a> equals "vglnk", and finally I find the file "embed.js" from Disqus includes the string "vglnk", too:

![embed_vglnk](https://user-images.githubusercontent.com/17273925/34194490-ecf3abca-e593-11e7-8082-39497403289a.png)

The file "embed.js" is offered as follow:

> [embed.js](https://ciphersaw.disqus.com/embed.js)

Now I only find out the reason but don't know how to eliminate its interference.

**Comment by NoahDragon** [comment]
Could you please try to set the `autolink` to false in `_config.yml`?
https://github.com/hexojs/hexo-renderer-marked

**Comment by ciphersaw** [comment]
Thanks for your solution, but unfortunately it doesn't work as long as I use Disqus.

I suppose the code in "embed.js" from Disqus should be to blame. I only avoid its effect by changing the comment system to LiveRe at present.

**Comment by unnamed42** [comment]
Maybe this helps? https://www.cleversprocket.com/disqus-is-parsing-your-dom-and-adding-affiliate-links/

**Comment by ciphersaw** [comment]
Oh my bro @unnamed42 , it works ! Thank you so much !

The solution is to turn off the option "Affiliate Links" by the path below:

> **Admin -> Edit Settings -> Choose your site -> Advanced**

The illustration is from the [reference link](https://www.cleversprocket.com/disqus-is-parsing-your-dom-and-adding-affiliate-links/) above:

<img width="1043" alt="screen-shot-2017-10-02-at-9 35 36-am-1" src="https://user-images.githubusercontent.com/17273925/34523486-b1a70644-f0d2-11e7-9f53-4eab0cad2e51.png">
