### ISSUE TITLE
post page into the mainpage

### ISSUE THREAD

**Issue by yeniugo** [hexojs/hexo#2922]
## Environment Info

Node version(`node -v`):8.9.3

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

 1. main page
![fireshot capture 1 - - http___localhost_4000_](https://user-images.githubusercontent.com/6367816/34144472-a512eafe-e4cc-11e7-8dd6-81647f77d1a2.png)
![image](https://user-images.githubusercontent.com/6367816/34144485-aea4f74c-e4cc-11e7-8ed9-7b38058a6701.png)
the first image is my main page,and the second image is my file of source file.
 2. 
 3.

**Comment by NoahDragon** [comment]
This relates the theme design. What's the `layout` in the front matters of your markdown files?

**Comment by yeniugo** [comment]
I have solved this problem.Disable the plugs-in of hexo-browsersync will be fine.But I don't know why is that.

**Comment by NoahDragon** [comment]
Wired. Mine don't cause such issue, the only difference is I didn't use folders for those pages. Close the issue for now. Feel free to reopen.
