### ISSUE TITLE
执行到hexo server后，在terminal用links打开localhost提示被拒绝

### ISSUE THREAD

**Issue by eahau** [hexojs/hexo#2924]
![default](https://user-images.githubusercontent.com/23614225/34161430-9c3f2b92-e50b-11e7-8fb6-3af334da716a.PNG)
换过端口也不行。在浏览器访问绑定的域名eahau.wang也是提示拒绝访问，但是可以ping通啊！请问有哪位曾经遇到过吗？如何解决呢？感谢！

**Comment by KeepitReal555** [comment]
我也遇到了,但是我并不能ping通，换了端口也不行。楼主解决了吗？
