### ISSUE TITLE
 Incorrect number of tags and catalogs

### ISSUE THREAD

**Issue by ZengXiangJun** [hexojs/hexo#2925]
## Environment Info

hexo-v 3.4.3  next-v 5.1.3

## For BUG

Incorrect number of tags and catalogs

Manually deleted all file in source/_posts, Then run hexo g,  the number of tags and catalogs 
Still the same as before
![gflcy7p7 3 a1m i om](https://user-images.githubusercontent.com/30788841/34169447-6949ca3c-e522-11e7-89fd-8e20b987bb49.png)

The number of catalogs is alse not correct

Then run hexo clean Delete the public folder and Clear the cache in db.json, like this: 
```
{"meta":{"version":1,"warehouse":"2.2.0"},"models":{"Asset":[],"Cache":[],"Category":[],"Data":[],"Page":[],"Post":[],"PostAsset":[],"PostCategory":[],"PostTag":[],"Tag":[]}}
```
Run hexo g again，Still can not solve the problem

**Comment by NoahDragon** [comment]
Could you please run `hexo clean` then `hexo g`?

**Comment by ZengXiangJun** [comment]
yes , I did it, but it did not work。

**Comment by ZengXiangJun** [comment]
yes,I did it, but it did not work

**Comment by tsanie** [comment]
Same problem here, maybe u need to check if there are some articles in the **_draft**. Those articles' categories will also be calculated.

But I think there should be an option here in the _config.yml, let the user make a choice whether it only calculate the posted articles or not. 😒

**Comment by ZengXiangJun** [comment]
thanks
