### ISSUE TITLE
Different layouts for different posts

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2926]
I am trying to have different layouts for different posts.

How to do?

For example...

source/_posts > title-alpha.md uses layout `alpha`
source/_posts > title-clown.md uses layout `clown`

I know I have to create a custom layout in themes folder... `alpha.ejs` and `clown.ejs`,
and also in .md files to specify `layout: alpha` and `layout: clown`.

But this does not work!
In my config file I have `default_layout: post`, but how can I have multiple layouts at the same time for different posts?

**Comment by YoshinoriN** [comment]
@rabas007 

As far as I know, it's possible by theme customization.
For example.

```ejs
<% if (post.layout === "alpha") { %>
  alpha layout...
<% } else if (post.layout === "crown") { %>
  clown layout...
<% } %>
```

**Comment by rabas007** [comment]
@YoshinoriN - thank you, works perfectly... :)
