### ISSUE TITLE
 in unpopulated submodule '.deploy_git'

### ISSUE THREAD

**Issue by lovechenghao** [hexojs/hexo#2927]
这是怎么解决啊

**Comment by NoahDragon** [comment]
`.deploy_git` is only used for deployment. Don't need to add it to submodule.

**Comment by chairre** [comment]
> `.deploy_git` is only used for deployment. Don't need to add it to submodule.

那怎么做呢？

**Comment by chairre** [comment]
我安装hexo-deployer-git了，还是报错

**Comment by chairre** [comment]
远程仓库不要有 .deploy_git （本地有就行了，用来部署的）
![image](https://github.com/hexojs/hexo/assets/43592730/b6f74bd0-98f8-4353-9e05-4062c709e2c4)
