### ISSUE TITLE
Markdown Table（表格） the last column of the last line（最后一行最后一列）can not be empty（不能为空）

### ISSUE THREAD

**Issue by tingstory** [hexojs/hexo#2928]
## Environment Info
hexo: 3.4.2
theme: next
hexo-cli: 1.0.4
os: Linux 3.10.0-693.5.2.el7.x86_64 linux x64
http_parser: 2.7.1
node: 6.11.3
v8: 5.1.281.107
uv: 1.10.2
zlib: 1.2.7
ares: 1.10.1-DEV
icu: 50.1.2
modules: 48
openssl: 1.0.2k-fips

## For BUG

Markdown Table（表格） the last column of the last line（最后一行最后一列）can not be empty（不能为空）

| 1  | 2  | 3  |
| -- | -- | -- |
| 1  | 2  |     |

如果为空，将会缺失最后一行最后一列。
If empty, the last column of the last line will be missing.

**Comment by NoahDragon** [comment]
It's an issue in marked. https://github.com/chjj/marked/pull/697

https://github.com/hexojs/hexo-renderer-marked/issues/54
