### ISSUE TITLE
Code snippets with and without scroll bars

### ISSUE THREAD

**Issue by royr2** [hexojs/hexo#2930]
## Environment Info

Node version(`node -v`): 8.9.3
Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.4.4
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-scss@1.1.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For question

Certain code snippets inside a post, show with a scroll bar and certain code snippets do not. In all cases the snippet is wrapped in `<pre><code>` tags. Why is this and how can I fix this? 

Any help would be appreciated !

**Comment by tomap** [comment]
I would say that you have an issue with your theme.
Could you send us your theme name (in _config.yml) and the url from where you cloned it?

**Comment by royr2** [comment]
@tomap thanks for your response - sure, the theme is called Even and I cloned it from here: https://github.com/ahonn/hexo-theme-even

**Comment by tcrowe** [comment]
Maybe from here @royr2 https://github.com/ahonn/hexo-theme-even/blob/2a2b7e08cf2f0faa469ed16deb9cf6bd3e806a23/source/css/_partial/_post/_code.scss#L14

It's got `overflow-x` directive a few times in there.

If that works will you come back and close it out please?

**Comment by royr2** [comment]
@tcrowe Thank you good sir - works perfectly. Closing this now...
