### ISSUE TITLE
Can I use data file in _config.yml ?

### ISSUE THREAD

**Issue by LichFaker** [hexojs/hexo#2932]
For example, add `custom.yml` in `source/_data` folder.
```
title: test
url: xxx
```
How use them in _config.yml?

**Comment by NoahDragon** [comment]
The answer is no, the data is loaded after the config file.

**Comment by LichFaker** [comment]
would it be supported?
so that, I can set some password in other file which can be ignored by git, in order to control the code of blog by git and deployed by ftp at the same time. 
And I don't want to expose the detail such as password of my ftp.

**Comment by NoahDragon** [comment]
I don't think we are going to support this. Actually, you could build your own deployment method instead of using the hexo deployer. 

What I did on my site, I use travis-ci to deploy which provide the functionality to encrypt any data using during the CI process.
