### ISSUE TITLE
How to create an hexo page without the theme style ? Thank you! 

### ISSUE THREAD

**Issue by edgarcheverier** [hexojs/hexo#2934]
##  Question
I'm creating a website, and I would like to have one page of the website without the predeterminate style of the theme.

Thank you!

**Comment by unnamed42** [comment]
Specifying `layout: false` in that post's front-matter section, like: 
```
title: test
date: 2018-01-02 21:42:30
layout: false
---
My post content, blahblah
```
But specifying that will **NOT** generate a valid HTML Document (e.g. no `<html>`, `<body>`), only the result of rendered post. If you still want to have valid result, please consult your theme's author, or create  your own one with a blank layout.

**Comment by tomap** [comment]
Or use HTML instead of markdown and add your page to the property skip_render:
```
skip_render:
 - 'assets/404.html'
```

See https://github.com/tomap/tpi2.eu/blob/master/_config.yml#L28
