### ISSUE TITLE
[Discussion] Markdown renderer abstraction

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo#2936]
## Question and/or Feature request

Currently the default markdown renderer for hexo is marked, so a lot of hexo plugin that need a markdown renderer require marked as well as hexo already require by default. But the problem is for people using other markdown renderer supported by hexo as markdown-it, kramdown and pandoc.
For example markdown-it is a great alternative of marked and a lot of javascript project change to use it but for your hexo project [you can have only one markdown renderer](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Getting-Started), so if you use markdown-it you must have uninstalled marked, and so all hexo plugin requiring marked will fail.

So is there a way to provide an abstraction for plugin creator to call the markdown renderer used by hexo independently of which one is used ?

Another more dirty way is to not require marked by default but to require marked in the _config.yml y default, so this will allow to have several markdown renderer installed at the same time and if you are using markdown-it you will be able to tell hexo in the _config.yml to use markdown-it to render posts but marked will also be installed, and poorly designed plugins will be able to require marked.

Is my description clear ? Do not hesitate to ask me some questions.

**Comment by NoahDragon** [comment]
I feel the configuration way is a good approach. But I don't feel this is a major issue, it's only tedious to install/uninstall plugins when switch markdown renders.

**Comment by noraj1337** [comment]
@NoahDragon It's not when switching markdown renderer only. For example I use markdown-it but a plugin I use works only with marked. So either I can't use markdown-it anymore or I can't use the plugin. The config approach will able me to continue using markdown-it and keeping marked installed, so marked will not be used by hexo to render post but only by my plugin that directly require marked.

**Comment by NoahDragon** [comment]
I see. I didn't understand the problem correctly. But if you installed two renderers, one for plugin (A), another for Hexo (B), which one is going to render the md posts? Based on my understanding, B will render the posts, then even we installed A the plugin would still not work.

**Comment by noraj1337** [comment]
Currently hexo doesn't support multiple renderer at the same time. But if the new feature allow user to explicitly tell hexo to use render A (ex: markdown-it), hexo will use renderer A to render markdown posts. New let's say that I'm using a plugin that support only renderer B (ex: marked) to render some extra html tags, I will be able to install renderer B at the same time. Hexo will still know that it has to use renderer A thanks to the config file, and the badly design plugin that is hardcoded for renderer B will use renderer B and so it's not a problem that several renderer are installed at the same time.

**Comment by stevenjoezhang** [comment]
Use `ctx.render.renderSync` method. Here is an example.

https://github.com/hexojs/hexo/blob/5b37990313b0d61f99e50643edf416b491566e4e/lib/plugins/tag/pullquote.js#L14

**Comment by noraj** [comment]
> Use `ctx.render.renderSync` method. Here is an example.
> 
> https://github.com/hexojs/hexo/blob/5b37990313b0d61f99e50643edf416b491566e4e/lib/plugins/tag/pullquote.js#L14

I was thinking of config in `_config.yml` for the end user rather than something for dev eg. plugin makers.

**Comment by stevenjoezhang** [comment]
> But if the new feature allow user to explicitly tell hexo to use render A (ex: markdown-it), hexo will use renderer A to render markdown posts. New let's say that I'm using a plugin that support only renderer B (ex: marked) to render some extra html tags, I will be able to install renderer B at the same time.

In `_config.yml`:
```
plugins:
  - hexo-renderer-markdown-it
  - hexo-server
  - ...
```

In `package.json`:
```
"dependencies": {
  "hexo-renderer-markdown-it": "*",
  "hexo-renderer-marked": "*",
   "hexo-server": "*",
   ...
}
```
