### ISSUE TITLE
可以设置部分类目的文章不在主页显示吗？

### ISSUE THREAD

**Issue by monotone** [hexojs/hexo#2937]
我想设置指定类目的文章才显示在主页上，或者指定某些类目的文章隐藏。

目前有这么个功能吗？

**Comment by xiaozGerry** [comment]
可以循环分类来达到您所要的效果。

```
<% page.posts.each(function(post) { %>
	<% post.categories.map(function(cate){ %>
		<% if(cate.name == "分类名"){ %>
		<% }else{ %>
			//需要显示的文章
		<% } %>
	<% }) %>
<% }) %>
```

这是我使用的方法，不知道是否适用于您...

**Comment by xiaozGerry** [comment]
可以循环分类来达到您所要的效果。

```
<% page.posts.each(function(post) { %>
	<% post.categories.map(function(cate){ %>
		<% if(cate.name == "分类名"){ %>
		<% }else{ %>
			//需要显示的文章
		<% } %>
	<% }) %>
<% }) %>
```

这是我使用的方法，不知道是否适用于您...

**Comment by monotone** [comment]
@xiaozGerry 抱歉我不熟悉这方面的源码，完全不知道这部分该放哪。  看起来是可以通过这种逻辑实现，指定类目的文章不显示的效果。但是这个效果是主页和分类页里都不显示吗？
```
<% page.posts.each(function(post) { %>
	<% post.categories.map(function(cate){ %>
		<% if(cate.name == "要隐藏的文章所属类目"){ %>
                         // 返回不显示
		<% }else{ %>
			// 返回可以显示
		<% } %>
	<% }) %>
<% }) %>
```

（PS，github上都要这么礼貌吗？用“您”）

**Comment by xiaozGerry** [comment]
@monotone 如果想在分类页或存档及标签页同样不显示，仍然需要在循环中加入以上语句，`<% post.categories.map(function(cate){ %>`以用来判断不需要哪个分类显示，不过，唯一有点不爽的是，文章的上下文切换(上一篇，下一篇)，还是会显示该文章。暂时我没想到有何办法解决...（我对hexo也不是特别熟悉）

代码放置的位置，比如模板文件（theme/模板文件/layout下的index.ejs），打开后你就会发现循环`<% page.posts.each(function(post) { %>`

然后在这人循环里添加上我和你说的循环分类及判断即可...

注，如果index.ejs的后缀为*.swig可能会有些不同...你可以试着修改一下...

**Comment by monotone** [comment]
@xiaozGerry thanks first.

上下文切换应该可以在相应的控制显示上下文链接的地方做控制（我猜的）。。。

我才了解到你这个方式是通过theme来做显示控制的。 如果能在hexo本身架构里面，比如对指定类目的md文件直接就不做渲染，是不是更简单？

如果只能通过修改theme来实现，那么我应该去`next`这个theme那边提issue了。

**Comment by monotone** [comment]
我搞不定，对js不熟。 稍微看了下源码，被里面各种闭包弄的一脸懵逼。  

有没有懂的大佬，其实改起来应该不难。就是配置里面加一个类似`skip_categories`这样的配置，然后在对md进行渲染之前检查一分类即可。。
