### ISSUE TITLE
如何自定义页面，并使用/pageName/<% front-matter %>的形式访问？

### ISSUE THREAD

**Issue by xiaozGerry** [hexojs/hexo#2938]
具体点就是写文章时，自定义个`front-matter`，如`author: 用户名`，创建的页面名为`author`，然后文章最后给个查看作者全部文章的链接指向`/author/用户名`？并在这个页面显示`用户名`的所有文章，请问可以实现吗？非常感谢！实在研究不出来了，才来此询问，还望有知道的能够给予解答，非常感谢！

**Comment by unnamed42** [comment]
你这种情况，和根据文章的`category`/`tag`生成归档目录是一样的问题（因为`category`和`tag`也是写在`front-matter`里面的），需要自己写一个插件
可以参考已经有的[hexo-generator-category](https://github.com/hexojs/hexo-generator-category)和[hexo-generator-tag](https://github.com/hexojs/hexo-generator-tag)
至于在文章末尾给出指向这个归档的链接，写个`after_render:html`的filter小插件就行了

**Comment by xiaozGerry** [comment]
@unnamed42 非常感谢！~
