### ISSUE TITLE
swig模板引擎的依赖项 uglify-js@2.4.24有安全漏洞

### ISSUE THREAD

**Issue by FloatingShuYin** [hexojs/hexo#2939]
swig模板引擎的依赖项 uglify-js@2.4.24 有安全漏洞

而swig作者早在2014年停止了维护

建议更换到[swig-templates](https://github.com/node-swig/swig-templates/blob/master/package.json)

**Comment by medmin** [comment]
Here is the translation for maintainers:

One of the dependencies of Swig template engine, uglify-js@2.4.24, has a bug related to security.
The author of swig has ceased to maintain it since 2014.
It's suggested to switch to other template engines.
