### ISSUE TITLE
How to submit the theme I made to the hexo homepage？

### ISSUE THREAD

**Issue by guanpengchn** [hexojs/hexo#2947]
How to submit the theme I made to the hexo homepage？

**Comment by tomap** [comment]
Edit this page:
https://github.com/hexojs/site/blob/e910e8bffac07c8816d37051373b9f69c6091bfe/source/_data/themes.yml

Instructions are here:
https://github.com/hexojs/hexo/blob/master/.github/CONTRIBUTING.md#updating-documentation
