### ISSUE TITLE
hexo d 没有任何输出, 直接结束了操作

### ISSUE THREAD

**Issue by veryitman** [hexojs/hexo#2951]
hexo 版本信息:

`hexo: 3.4.4
hexo-cli: 1.0.4
os: Darwin 17.2.0 darwin x64
http_parser: 2.7.0
node: 9.3.0
v8: 6.2.414.46-node.15
uv: 1.18.0
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c`

hexo g 操作是有屏幕输出的.

但是 hexo d 没有任何输出, 直接就结束掉了.

**Comment by NoahDragon** [comment]
Close as duplicate to #2950
