### ISSUE TITLE
How to filter out the specified number of articles under a certain category on the hexo topic. | hexo主题里怎么过滤出某个分类下的指定数量文章。

### ISSUE THREAD

**Issue by QingShui23** [hexojs/hexo#2956]
How to filter out the specified number of articles under a certain category on the hexo topic？

原文：
hexo主题里怎么过滤出某个分类下的指定数量文章。

**Comment by sabrinaluo** [comment]
有一个Helper函数可以列出所有的分类及对应分类下的文章数量 https://hexo.io/zh-tw/docs/helpers.html#list-categories

但是这个Helper返回的是html 如果你想要一个json，目前好像没有相关的接口，可能要辛苦一点自己parse一下返回的html
https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/list_categories.js

**Comment by Yalhu** [comment]
`list_categories`这个函数怎么用啊？比如，我想获得`ins`分类，`{{ list_categories('ins') }}` 会报错：categories.find is not a function 。
希望可以指导一下 😃  ,谢谢啦！ @sabrinaluo

**Comment by sabrinaluo** [comment]
`list_categories()` 不要加参数返回的是一段html字符串`<ul><li></li></ul>`这样的

如果你想要的是，比如这样 http://sabrinaluo.github.io/tech/categories/AngularJS/
需要修改的则是`theme/layout/archive.xxx`文件
可以参考 https://github.com/sabrinaluo/hexo-theme-replica/blob/master/layout/archive.ejs#L14

这里的`posts`是对应category下的所有文章，如果你想限制数量，可以这样
```
var limit = 5;
for(i=0; i< limit; i++){
// render items
}
```

**Comment by Yalhu** [comment]
我想要更改分类页面，<http://sabrinaluo.github.io/tech/categories/> 。过滤一些，我不想要显示的分类。
不想页面生成后再用脚本隐藏，想在调用list_categories的时候就过滤了。。如果还可以得到过滤后的分类数量。

你网站很好看啊。用的那个主题，是不是自己定制了好多东西？

**Comment by sabrinaluo** [comment]
> 不想页面生成后再用脚本隐藏，想在调用list_categories的时候就过滤了

按照目前暴露出来的API，你需要在调用`list_categories`的时候自行过滤，然后渲染页面。所以是在生成页面之前过滤的，符合你的预期。

https://github.com/sabrinaluo/hexo-theme-replica/blob/master/layout/page.ejs#L12
你需要修改`layout/page`文件中的`if(page.title === 'categories')` 里面的部分，利用`list_categories`返回的html配合正则或者其他字符串处理方法自行过滤

过滤后的分类数量就是上面经过处理后的`<li>`的数量

p.s. 主题是 https://github.com/sabrinaluo/hexo-theme-replica 自己写的
