### ISSUE TITLE
Converting markdown (inc tag plugins) to HTML

### ISSUE THREAD

**Issue by jakeg** [hexojs/hexo#2957]
I'm trying to make a page which lists my custom tags, and explains how to use them and what their output would be.

I thought that `hexo.render.render()` could take Markdown as an input and would render it to HTML, including converting any custom tag plugins I may have added. But this doesn't seem to be the case, and now markdown -> html conversion happens. Here is my usage:

```javascript
const renderInput = `
  # test
  This is in **bold**.
  {% blockquote %}
    Here is my blockquote
  {% endblockquote %}
`
hexo.render.render({ text: renderInput, engine: 'swig' }).then((renderOutput) => {
  return `
    <p>Will render like this:</p>
    ${renderOutput}
  `
})
```

... but this will give the error `Unexpected tag "blockquote"`, and even without the blockquote no Markdown is converted to HTML.

Is there some other method I should be using to do this? Or different usage of this method?

**Comment by jakeg** [comment]
If I change it to be `{ text: renderInput, engine: 'markdown' }` instead of `swig` then Markdown is converted to HTML, but the `{% blockquote %}` tag isn't parsed. How can I get those tags parsed as well?

**Comment by zhuzhuyule** [comment]
u can try to use `filter` ,like this
```js
hexo.extend.filter.register(type, function(){
}, priority);
```

```js
function wantToDo() {
    const renderInput = `
                          # test
                          This is in **bold**.
                          {% blockquote %}
                            Here is my blockquote
                          {% endblockquote %}
                        `
    hexo.render.render({text: renderInput, engine: 'swig'}).then((renderOutput) => {
        return `
                <p>Will render like this:</p>
                ${renderOutput}
               `
    })
}
hexo.extend.filter.register('before_post_render', wantToDo, 5);
```
