### ISSUE TITLE
Using nested quotes in html file

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [hexojs/hexo#2959]
I am using .html file in place of .md file and in it using a div as 

```
<div data-slick='{"dots":true,"arrows":false,"infinite": true,"autoplay": true,"autoplaySpeed": 3000}'>
</div>
```

But it is not taking quotes properly when I inspect element it is considering as quotes closed immediately after open brace.

```
<div data-slick="{" dots":true,"arrows":false,"infinite": true,"autoplay": true,"autoplaySpeed": 3000}">
</div>
```

**Comment by tryshchenko** [comment]
Would internal single quotes work for you?

**Comment by HarshaVardhanPVK** [comment]
No, those are also not working.
