### ISSUE TITLE
***It is a recommend Markdown edit for Hexo !***

### ISSUE THREAD

**Issue by zhuzhuyule** [hexojs/hexo#2960]
### If you used Hexo, [HexoEditor](https://github.com/zhuzhuyule/HexoEditor) will be your choice !

# <div align="center"><a title="Go to homepage" href="https://github.com/zhuzhuyule/HexoEditor"><img align="center" width="56" height="56" src="https://raw.githubusercontent.com/zhuzhuyule/HexoEditor/master/icons/HexoEditor.svg?sanitize=true">  HexoEditor</div></a>
<div align="right">Language: :us:
<a title="Chinese" href="https://raw.githubusercontent.com/zhuzhuyule/HexoEditor/master/doc/cn/README.md">:cn:</a>
<a title="Russian" href="https://raw.githubusercontent.com/zhuzhuyule/HexoEditor/master/doc/ru/README.md">:ru:</a></div>

This is markdown editor for Hexo.

Built with Electron.

Inherit [Moeditor](https://github.com/Moeditor/Moeditor), I want to fix it appropriate to Hexo Blog!

# Features
* HexoEditor 
  * Hexo Post Preview same as in Browser
  * Hexo Tag/Filter/Renderer support
  * Custom tag support
  * Use Hexo `_config.yml` support
    * highlight setting
    * theme tag support
  * --------- v1.1.8 (2017-12-29) ---------
  * Quick New Post in hexo source 
  * Quick Modify File Name (In Hexo Post Edit)  
  * Shortcut Support
  * Editor Line number Show/Hide
  * Auto Show/Hide Scroll
  * Scorll Together/None
* HexoEditor (Inherit [Moeditor](https://github.com/Moeditor/Moeditor))
  * GitHub Flavored Markdown
  * TeX math expressions
  * UML diagrams
  * Code highlight in editor
  * Read/Write/Preview mode
  * Custom font / line height / font size
  * Custom themes
  * Code highlight themes (powered by [highlight.js](https://highlightjs.org/))
  * Auto reload
  * Localization
  * ~~Focus mode~~

### I want add this soft to organization !

**Comment by jakeg** [comment]
Looks great! :) I hope to try it out soon.

I particularly love how you have custom tag support. Are you able to use your knowledge of that to help me with #2957? Thanks!

**Comment by NoahDragon** [comment]
Awesome work, I also have added it to [awesome-hexo](https://github.com/hexojs/awesome-hexo).
