### ISSUE TITLE
Quiet (not silent) log output

### ISSUE THREAD

**Issue by jakeg** [hexojs/hexo#2961]
I have ~1,500 .md files which are being converted to HTML on running `hexo generate`. This ends up with a massive log which looks like this:

```
INFO  Start processing
INFO  Files loaded in 4.94 s
INFO  Generated: blah/a.html
INFO  Generated: blah/b.html
.
.
[~1,500 more lines here!!!]
.
.
INFO  Generated: blah/zzzzz.html
INFO  Generated: blah/zzzzzzzzz.html
INFO  1361 files generated in 21 s
INFO  See you again
```

I'd like to ouput everything apart from the `INFO  Generated: blah/b.html` lines if I run `hexo generate --quiet`.

I *could* run `hexo generate --silent` but then I don't get the useful message about how many files are generated, and much more importantly, I don't get to see any warnings or errors at all! No good at all for a build log.

**Comment by NoahDragon** [comment]
If you are using *Unix system, how about using the redirect command: `hexo generate > output.log` ?

**Comment by jakeg** [comment]
That would still take errors and warnings to `output.log`. I really only want to see errors and warnings, no INFO log items.

**Comment by msamsel** [comment]
I'd love to see such feature in hexo. Just to log errors but no info messages.

**Comment by bennycode** [comment]
It looks like Hexo uses log levels (info, error, debug, etc.). Can the log levels be configured?

I would also like to avoid seeing these lines:

![image](https://user-images.githubusercontent.com/469989/166565588-157e3eb5-03d9-42f9-9b77-42f4777ca27f.png)

**Comment by bennycode** [comment]
After reading the source code (https://github.com/hexojs/hexo-log/tree/v3.0.0#usage & https://github.com/hexojs/hexo/blob/6.1.0/lib/hexo/index.js#L113) I found out that silent mode can be used with: `hexo generate --silent` 🙂
