### ISSUE TITLE
RAM memory on GCP for 3000-4000 blog posts

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#2962]
I am trying to deploy HEXO on Google Cloud Platform with 3000-4000 blog posts.

How much RAM memory do you recommend for me to take for this?

Anybody has experience deploying HEXO blog on Google Cloud Platform and can share a guide?

Thanks.

**Comment by NoahDragon** [comment]
I don't think the static website will consume lots of memory. Have you counted the size of 3000-4000 posts? How much traffic do you expect? Even you have a small memory machine, you still could use CDN to release the load.

**Comment by rabas007** [comment]
@NoahDragon - got it... OK, thanks, I will test it out, ~ 1GB with CDN should work hopefully.
