### ISSUE TITLE
The filter backtick_code_block makes markdown broken.

### ISSUE THREAD

**Issue by fenying** [hexojs/hexo#2969]
The Hexo filter [`backtick_code_block`](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/before_post_render/index.js#L6)makes following markdown code-block work as a fool.

```markdown
Hello

> This is a code-block
> 
> ```json
> {
>   "test": 123
> }
> ```
```

This will be parsed as 

```html
<p>Hello</p>

<blockquote>
<p>This is a code-block</p>
<pre><code class="json">
<span class="line">&gt; {</span><br>
<span class="line">&gt;   "test": 123</span><br>
<span class="line">&gt; }</span><br>
<span class="line">&gt;</span>
</code></pre>
</blockquote>
```

Which looks like

------------------

Hello

> This is a code-block
> ```
> > {
> >   "test": 123
> > }
> >
> ```

------------------

Actually it should be

```html
<p>Hello</p>

<blockquote>
<p>This is a code-block</p>
<pre><code class="json">
<span class="line"> {</span><br>
<span class="line">   "test": 123</span><br>
<span class="line"> }</span>
</code></pre>
</blockquote>
```

------------------

Hello

> This is a code-block
> ```
> {
>   "test": 123
> }
> ```

------------------

**Comment by fenying** [comment]
My personal solution is to remove this filter and rebuild the code view in render. However, I don't know if there is any else module will be affected by removing this filter,

Here is my solution with markdown-it: https://github.com/fenying/hexo-renderer-markdown-it-plus/commit/bc2815cd0ddd54c3ba19be6f48b18c63d6f54a08

**Comment by zhuzhuyule** [comment]
@fenying you can try this:
````
Hello

> This is a code-block
> 
```json
{
   "test": 123
}
```
> Here's a quote

Here's not a quote
````

**Comment by fenying** [comment]
@zhuzhuyule Thank you for replying, but I wouldn't try this solution because it cannot keep compatibilities of syntax and styles, among github and hexo, and other Markdown editor,.

I haven't try it in hexo, since it's shown as following in github:

--------------------------------

Hello

> This is a code-block
> 
```json
{
   "test": 123
}
```
> Here's a quote

Here's not a quote

---------------------------------

**I mean the code-block should be insides quote-block.**

**Comment by zhuzhuyule** [comment]
OK , I know your question, Due to different rendering engines !

**Comment by fenying** [comment]
@zhuzhuyule Emmm, actually, with the default hexo-render-marked it will broken, so does hexo-render-markdown-it. It's not caused by different markdown render, because the detection of code-block is not done by render engine, but by the Hexo built-in filter [backtick_code_block](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/before_post_render/index.js#L6).

Thus, to make markdown render work well, you have to remove or improve the filter [backtick_code_block](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/before_post_render/index.js#L6).

If you just remove it, you'll lose the syntax highlight of code and have to rebuild the highlight yourself.
