### ISSUE TITLE
Error: events.js:137

### ISSUE THREAD

**Issue by stokhos** [hexojs/hexo#2970]
## Environment Info

Node version(`node -v`): v9.4.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.4.4
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-markdown-it@3.4.1
├── hexo-renderer-pug@0.0.5
├── hexo-renderer-sass@0.3.2
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
├── hexo-tag-fontawesome@1.0.0
└── markdown-it-emoji@1.4.0

npm ERR! missing: hawk@3.1.3, required by node-pre-gyp@0.6.39
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.6.39
npm ERR! missing: rimraf@2.6.1, required by node-pre-gyp@0.6.39
npm ERR! missing: tar@2.2.1, required by node-pre-gyp@0.6.39
npm ERR! missing: boom@2.10.1, required by hawk@3.1.3
npm ERR! missing: cryptiles@2.0.5, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by hawk@3.1.3
npm ERR! missing: sntp@1.0.9, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by boom@2.10.1
npm ERR! missing: boom@2.10.1, required by cryptiles@2.0.5
npm ERR! missing: hoek@2.16.3, required by sntp@1.0.9
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.0
npm ERR! missing: readable-stream@2.2.9, required by are-we-there-yet@1.1.4
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: combined-stream@1.0.5, required by request@2.81.0
npm ERR! missing: hawk@3.1.3, required by request@2.81.0
npm ERR! missing: mime-types@2.1.15, required by request@2.81.0
npm ERR! missing: safe-buffer@5.0.1, required by request@2.81.0
npm ERR! missing: delayed-stream@1.0.0, required by combined-stream@1.0.5
npm ERR! missing: combined-stream@1.0.5, required by form-data@2.1.4
npm ERR! missing: mime-types@2.1.15, required by form-data@2.1.4
npm ERR! missing: extsprintf@1.0.2, required by jsprim@1.4.0
npm ERR! missing: extsprintf@1.0.2, required by verror@1.3.6
npm ERR! missing: mime-db@1.27.0, required by mime-types@2.1.15
npm ERR! missing: safe-buffer@5.0.1, required by tunnel-agent@0.6.0
npm ERR! missing: glob@7.1.2, required by rimraf@2.6.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.1.2
npm ERR! missing: inflight@1.0.6, required by glob@7.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: brace-expansion@1.1.7, required by minimatch@3.0.4
npm ERR! missing: balanced-match@0.4.2, required by brace-expansion@1.1.7
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.7
npm ERR! missing: block-stream@0.0.9, required by tar@2.2.1
npm ERR! missing: fstream@1.0.11, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by block-stream@0.0.9
npm ERR! missing: graceful-fs@4.1.11, required by fstream@1.0.11
npm ERR! missing: inherits@2.0.3, required by fstream@1.0.11
npm ERR! missing: mkdirp@0.5.1, required by fstream@1.0.11
npm ERR! missing: rimraf@2.6.1, required by fstream@1.0.11
npm ERR! missing: fstream@1.0.11, required by tar-pack@3.4.0
npm ERR! missing: once@1.4.0, required by tar-pack@3.4.0
npm ERR! missing: readable-stream@2.2.9, required by tar-pack@3.4.0
npm ERR! missing: rimraf@2.6.1, required by tar-pack@3.4.0
npm ERR! missing: tar@2.2.1, required by tar-pack@3.4.0
npm ERR! missing: fstream@1.0.11, required by fstream-ignore@1.0.5
npm ERR! missing: inherits@2.0.3, required by fstream-ignore@1.0.5
npm ERR! missing: minimatch@3.0.4, required by fstream-ignore@1.0.5
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: buffer-shims@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: core-util-is@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.2.9
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: process-nextick-args@1.0.7, required by readable-stream@2.2.9
npm ERR! missing: string_decoder@1.0.1, required by readable-stream@2.2.9
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: safe-buffer@5.0.1, required by string_decoder@1.0.1

## For BUG

hexo d
then I got this error:

INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at Object.exports.spawn (child_process.js:499:9)
    at spawn (/home/stokhos/Stokhos/node_modules/cross-spawn/index.js:17:18)
    at /home/stokhos/Stokhos/node_modules/hexo-util/lib/spawn.js:19:16
    at Promise._execute (/home/stokhos/Stokhos/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/stokhos/Stokhos/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/stokhos/Stokhos/node_modules/bluebird/js/release/promise.js:79:10)
    at promiseSpawn (/home/stokhos/Stokhos/node_modules/hexo-util/lib/spawn.js:18:10)
    at git (/home/stokhos/Stokhos/node_modules/hexo-deployer-git/lib/deployer.js:58:12)
    at push (/home/stokhos/Stokhos/node_modules/hexo-deployer-git/lib/deployer.js:83:12)
    at /home/stokhos/Stokhos/node_modules/hexo-deployer-git/lib/deployer.js:153:12
    at tryCatcher (/home/stokhos/Stokhos/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/stokhos/Stokhos/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/home/stokhos/Stokhos/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/stokhos/Stokhos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/stokhos/Stokhos/node_modules/bluebird/js/release/promise.js:512:31)

06:11:24.273 DEBUG Hexo version: 3.4.4
06:11:24.275 DEBUG Working directory: ~/Stokhos/
06:11:24.330 DEBUG Config loaded: ~/Stokhos/_config.yml
06:11:24.339 DEBUG Plugin loaded: hexo-deployer-git
06:11:24.341 DEBUG Plugin loaded: hexo-generator-archive
06:11:24.344 DEBUG Plugin loaded: hexo-generator-category
06:11:24.345 DEBUG Plugin loaded: hexo-generator-index
06:11:24.347 DEBUG Plugin loaded: hexo-renderer-ejs
06:11:24.349 DEBUG Plugin loaded: hexo-generator-tag
06:11:24.349 DEBUG Plugin loaded: hexo-renderer-markdown-it
06:11:24.483 DEBUG Plugin loaded: hexo-renderer-pug
06:11:24.517 DEBUG Plugin loaded: hexo-renderer-sass
06:11:24.534 DEBUG Plugin loaded: hexo-renderer-stylus
06:11:24.535 DEBUG Plugin loaded: hexo-tag-fontawesome
06:11:24.573 DEBUG Plugin loaded: hexo-server
Usage: hexo <command>

## For question

How can I fix this?

**Comment by cclinet** [comment]
I have the same bug with you since **Today**

**Comment by stokhos** [comment]
@cclinet It worked yesterday, But after an update for my archlinux, I got this error. What about you?

**Comment by stokhos** [comment]
problem has been solved. I'm using archlinux, I think it a archlinux problem.
It works again, after updated haskell-zip-archive-0.3.2-1  libuv-1.19.0-2  pandoc-2.0.6-18,

**Comment by cclinet** [comment]
Yes, After I updated git-2.16.0-1  haskell-zip-archive-0.3.2-1  libuv-1.19.0-2  stack-1.6.3-37
, the problem was solved.
