### ISSUE TITLE
Can I access site.data when in a helper?

### ISSUE THREAD

**Issue by jakeg** [hexojs/hexo#2971]
Say I have `/scripts/blah.js`:
```
/* global hexo */

hexo.extend.helper.register('someMethod', (arg1) => {
  // can I access site.data here?
})
```

Is there a way to access `site.data` in a script file, in particular within a helper method? Or do I need to pass `site.data` into the helper as an argument?

**Comment by LazyKnightX** [comment]
a similar question here: https://github.com/hexojs/hexo/issues/3025
I didn't find some useful information about this in helper section of the document.

**Comment by ertrzyiks** [comment]
Helpers are called with the hexo context as `this`, so it would be:

```
hexo.extend.helper.register('someMethod', (arg1) => {
  console.log(this.site.data)
})
```
