### ISSUE TITLE
Suddenly Deployer not found: git

### ISSUE THREAD

**Issue by lcy362** [hexojs/hexo#2973]
## Environment Info

Node version(`node -v`): v9.4.0

Your site `_config.yml` (Optional): https://github.com/lcy362/blog.source/blob/master/_config.yml

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 3.4.4

## Question

my hexo works just fine until a while ago, at that time I installed hexo-generator-robotstxt as https://www.npmjs.com/package/hexo-generator-robotstxt.

Then I can't deploy to git.

I tried re install hexo-git with npm install hexo-deployer-git --save, but not work

How can I fix this?

**Comment by lcy362** [comment]
I removed this part in the config file, and it works:

```
plugins:
 - hexo-generator-robotstxt
```
it seems I don't need to config used plugins, it can be recognised automatically.  But if I do config this, other plugins will not be loaded.

**Comment by NoahDragon** [comment]
Glad you figure it out.
Close as resolved.
