### ISSUE TITLE
how to debug .pug template file?

### ISSUE THREAD

**Issue by dvulanov** [hexojs/hexo#2974]
I am using pugjs for templating and I would like to debug the rendering of a templates so I can see the variables Hexo injects (site, page, theme...).  What I'm trying to do, but can't figure out, is how to set a breakpoint inside one of my .pug template files

I can attach the chrome devTools debugger via:
`node --inspect-brk node_modules\hexo-cli\bin\hexo generate`

It attaches fine and will run and generate my static site, and I can set breakpoints within the node modules, but I do not know how to set a breakpoint so that I can see how my template files are rendered (i.e. see the variables injected into my template)

I realize that hexo uses the pug renderer I installed and that renderer reads/processes my template file.  However, there has to be a place I can set a breakpoint so I can inspect the rendering of my template.

Any help would be appreciated.

I'm on:
win7
node v8.9.4
hexo v1.0.4

**Comment by demurgos** [comment]
You cannot place breakpoints in pug files (they are not interpreted by Node but by pug).
You could get the variables when pug's render function is called but it's somewhat hard to access (in `node_modules`).

I personally resort to printing the values in the page (by placing `pre #{JSON.stringify(variableToLog)}`) but I'm interested if a better solution is available.

**Comment by dvulanov** [comment]
Thanks for the feedback!  I'll run with this solution until something better comes up.
