### ISSUE TITLE
Pin an article to the top

### ISSUE THREAD

**Issue by yunTerry** [hexojs/hexo#2977]
I wonder how to pin some articles to the top, others still ordered by date

Hope it can be officially supported~

**Comment by johnhorsema** [comment]
just add a property in the frontmatter of your Markdown file, i.e.
```
---
title: Some TItle
date: 2018/01/01 00:00:00
categories:
- Category 1
pinned: true
---
xxx
```

and edit your template file as follows (using jade as example)
```
- page.posts.each(function (item) {
        if post.pinned
                renderPost()
- })
- page.posts.each(function (item) {
        if not post.pinned
                renderPost()
- })
```

**Comment by yunTerry** [comment]
This is a good idea, thank you, and I've also found [another solution](https://github.com/netcan/hexo-generator-index-pin-top)

**Comment by NoahDragon** [comment]
Close as reloved.
