### ISSUE TITLE
the compiled result of 'hexo g' is different with 'hexo s'. Help!

### ISSUE THREAD

**Issue by AlbertXiao1994** [hexojs/hexo#2979]
## Environment Info

**Node version(`node -v`):**
v8.9.0

**Your site `_config.yml`(Optional):**
https://github.com/AlbertXiao1994/albertxiao1994.github.io/blob/hexo/_config.yml

**Your theme `_config.yml` (Optional):**
https://github.com/AlbertXiao1994/albertxiao1994.github.io/blob/hexo/themes/memory/_config.yml

**Hexo and Plugin version(`npm ls --depth 0`):**
hexo-site@0.0.0 D:\Github\blog
+-- hexo@3.4.4
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- UNMET DEPENDENCY hexo-generator-searchdb@^1.0.8
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.1
`-- hexo-symbols-count-time@0.2.0

npm ERR! missing: hexo-generator-searchdb@^1.0.8, required by hexo-site@0.0.0
npm ERR! missing: striptags@2.2.1, required by hexo-util@0.6.3
npm ERR! missing: window-size@0.1.4, required by yargs@3.32.0
npm ERR! missing: source-map@0.1.34, required by uglify-js@2.4.24
npm ERR! missing: yargs@3.5.4, required by uglify-js@2.4.24
npm ERR! missing: camelcase@1.2.1, required by yargs@3.5.4
npm ERR! missing: window-size@0.1.0, required by yargs@3.5.4
npm ERR! missing: wordwrap@0.0.2, required by yargs@3.5.4
npm ERR! missing: ejs@2.5.7, required by hexo-renderer-ejs@0.3.1
npm ERR! missing: depd@1.1.2, required by morgan@1.9.0
npm ERR! missing: depd@1.1.2, required by send@0.16.1

## For question

I use **swig** to write my theme, but I cannot get correct result when I use **'hexo g'**. However, I get what I wanna when I use **'hexo s'**. 
It's obvious there is something bad in **compiling and generating** 'public' folder, while 'hexo s' works well.
How Can I solve it?

**Comment by NoahDragon** [comment]
Close as duplicate. This is a known issue. 
https://github.com/hexojs/hexo/issues/2451

**Comment by dailyrandomphoto** [comment]
partial `header` should not be cached.
https://github.com/AlbertXiao1994/albertxiao1994.github.io/blob/hexo/themes/memory/layout/_layout.swig#L25
```ejs
{{ partial('_partials/header.swig', {}, {cache: theme.cache.enable}) }}
```
see https://github.com/hexojs/hexo/pull/3756#issuecomment-540286802
