### ISSUE TITLE
findOne

### ISSUE THREAD

**Issue by huyingjie** [hexojs/hexo#2983]
I searched online and did not find any documentation for the `findOne` function. Where is the documentation for the function?

```
<% site.categories.findOne({name: "python"}).posts.sort('title', 1).each(function(post) {%>
              <%= post.title %> <br>
            <% })%>
```

If I replace `python` with `web development` or `web-development`. Both of them report error `Cannot read property 'posts' of undefined`

Why does this happen?

**Comment by NoahDragon** [comment]
I think under `web development` category there are no posts available.

**Comment by huyingjie** [comment]
@NoahDragon You are correct.
