### ISSUE TITLE
The home page on github page don't  show my lastest article, but I can see the article if I click the categories or tags.

### ISSUE THREAD

**Issue by xuoutput** [hexojs/hexo#2984]
## Environment Info

Node version(`node -v`):
v6.11.3
Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 
nexT
Hexo and Plugin version(`npm ls --depth 0`): 
$ npm ls --depth 0
hexo-site@0.0.0 D:\blog\xuoutput.github.io
+-- hexo@3.4.4
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
## For question

 The home page on github page don't  show my lastest article, but I can see the article if I click the categories or tags.

## For feature request

There is nothing wrong with it, but when I `hexo new ` a new article and after `hexo g hexo d`,I browse my github page, the home page don't  show my changes. But if I  modify ` _config.yml`, and then `hexo g hexo d`, everything is ok. That is my question.

**Comment by NoahDragon** [comment]
This usually is caused by cache. You could try run `hexo clean` before `hexo g` to clean up the database.

**Comment by jdhao** [comment]
Usually when you deploy your blog to github. It may take several minutes to take effect. If you immediately open your blog website. You will not see the updated post. You can force refresh by using `CTRL + F5` several times. It will work AFAIK.

**Comment by xuoutput** [comment]
I understand，thanks.
