### ISSUE TITLE
Deployer not found: git

### ISSUE THREAD

**Issue by hgDendi** [hexojs/hexo#2989]
Already use npm install hexo-deployer-git --save
but still shows
16:59:57.711 ERROR Deployer not found: git

[_config.yml](https://raw.githubusercontent.com/hgDendi/hgDendi.github.io/master/_config.yml)
deploy:
type: git
repo: https://github.com/hgDendi/hgDendi.github.io.git
branch: master

I use
 npm install hexo-deployer-git --save
 hexo clean
 hexo g
 hexo d
shows:
16:59:57.612 DEBUG Hexo version: 3.4.4
16:59:57.614 DEBUG Working directory: ~/Desktop/hexo/hgDendi.github.io/
16:59:57.702 DEBUG Config loaded: ~/Desktop/hexo/hgDendi.github.io/_config.yml
16:59:57.708 DEBUG Plugin loaded: hexo-generator-cname
16:59:57.711 ERROR Deployer not found: git
16:59:57.714 DEBUG Database saved

**Comment by hgDendi** [comment]
plugins:
  hexo-generator-cname

This is the reason.. Thanks anyway

**Comment by fighting41love** [comment]
Same error. Solved by comment the plugins hexo-math in '_config.yml'.
Thanks!

**Comment by dzf0023** [comment]
if : .hexo deploy get : * ERROR Deployer not found: github * ?
in your blog 
npm install hexo-deployer-git --save
check  _config.yml，change type of deploy  from github to git

author：Ymuyi
url：https://www.jianshu.com/p/f2b32f439b02
source：jianshu
