### ISSUE TITLE
hexo g failure if `{% %}` in an article

### ISSUE THREAD

**Issue by jlshix** [hexojs/hexo#2992]
## Environment Info

`node -v`: 6.10.1
`hexo -v`:
```
hexo: 3.4.4
hexo-cli: 1.0.4
os: Linux 4.4.0-109-generic linux x64
http_parser: 2.7.0
node: 6.10.1
v8: 5.1.281.95
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2k
```
## For BUG

if `{% %}` in article content, then hexo g failure occures.

inline code quote no effect while quoting `{% something %}`.

### examples:

1. inline one " ` "

article content: `{% if someting %}`
hexo g: Template render error: (unknown path)
  parseIf: expected elif, else, or endif, got end of file

2. inline three " ` "

article content: ```{% if someting %}```
hexo g: Template render error: (unknown path)
  parseIf: expected elif, else, or endif, got end of file

3. code block

article content: 
```
{% if someting %}
```
hexo g: no error.

**Comment by NoahDragon** [comment]
This is known issue as it conflicts with nunkjucks. One solution is to use html encoding.

**Comment by tcrowe** [comment]
@jlshix Do you need those characters to be visible in the article? If so maybe you can escape it? `\\{\\% \\%\\}`

**Comment by tcrowe** [comment]
@jlshix I think my previous post will solve it. But if it does not please re-open this and lets take a look at that template. 👍
