### ISSUE TITLE
建立了hexo，但是打不开localhost，即使换了端口也不行

### ISSUE THREAD

**Issue by gaotingqi** [hexojs/hexo#2993]
# 用端口4000,5000,3600都不行，请问各位大神有什么方法吗？
查了一下，4000端口没有被占用，显示下面但是上不去呀
```  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop. ```

**Comment by derrick-null** [comment]
host文件是否配置了localhost的server name？用127.0.0.1访问试试

**Comment by gaotingqi** [comment]
@derrick-null  用127.0.0.1也不行，不过那个localhost的server name 如何配置呢？

**Comment by gaotingqi** [comment]
防火墙的问题，ping`127.0.0.1`显示一般故障，关闭了防火墙就好了！我的天，让我折腾了一上午。
