### ISSUE TITLE
How to order posts by update date?

### ISSUE THREAD

**Issue by huyingjie** [hexojs/hexo#2994]
```
<% site.categories.findOne({name: "python"}).posts.sort('title', 1).each(function(post) {%>
              <%= post.title %> <br>
  <% })%>
```

I knew that I can use `title` in the `posts.sort()` function to sort posts by title, or `date` to sort posts by publish date. I also found the [warehouse related information](https://hexo.io/warehouse/Query.html#sort).

How to sort posts by update date?

**Comment by NoahDragon** [comment]
Have you tried the `post.updated`?

**Comment by huyingjie** [comment]
@NoahDragon Nope. How to use `post.updated`? Documentation said it was a date value, not an array. 

I used `post.updated` as a google keyword and found a post to sort by update date <https://bobbyliujb.github.io/2016/07/12/hello-world/> Will it work?

**Comment by NoahDragon** [comment]
You could use the `post.updated` to replace the `title`:
```
<% site.categories.findOne({name: "python"}).posts.sort('updated').each(function(post) {%>
              <%= post.title %> <br>
  <% })%>
```

**Comment by huyingjie** [comment]
@NoahDragon It works. Thank. you.

**Comment by kkdd0909** [comment]
@NoahDragon - Is it also possible to use findOne with custom post.variables in md files?

For example:
``` 
---
post: layout
title: Hello World
color: black
---
```

and then
`<% post.color.findOne({name: "black"}).posts.sort etc etc`

Basically how to sort posts with custom post.variables?
