### ISSUE TITLE
[bug]code snippet format parse error

### ISSUE THREAD

**Issue by maskleo** [hexojs/hexo#2997]
## Environment Info

Node version(`node -v`):v8.7.0

Your site `_config.yml` (Optional):[there](https://github.com/maskleo/maskleo.github.io/blob/super/_config.yml)

Your theme `_config.yml` (Optional): default

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG
 [md file](https://github.com/maskleo/maskleo.github.io/blob/super/source/_posts/%E6%8B%96%E5%8A%A8%E6%8E%92%E5%BA%8F%E5%90%8E%E5%8F%B0%E9%80%BB%E8%BE%91%E6%80%9D%E8%80%83%E8%BF%87%E7%A8%8B.md) can not be correctly resolved.

expect:
![image](https://files.gitter.im/hexojs/hexo/RWML/blob)
now:
![image](https://files.gitter.im/hexojs/hexo/Wzmh/blob)

**Comment by NoahDragon** [comment]
I believe this is some issue from marked. https://github.com/chjj/marked

**Comment by maskleo** [comment]
Sorry,I'm not good at `NodeJS`.This problem may not be accurately described for me.I think it would be better for you to make the issue.

**Comment by NoahDragon** [comment]
One workaround is using the HTML table, another way is to move the code snippet out the bulletin/list section. 

Hexo only uses the marked api to render the markdown file, couldn't do anything if the issue is in marked.

**Comment by maskleo** [comment]
@NoahDragon   OK,Can you give me a tweaked example?I have tried many times, but its format looks strange.Thanks.I will try to used `Github Pages`  to parse this file.

**Comment by maskleo** [comment]
It looks parsed correctly.
https://maskleo.github.io/pages-test/drag-order-thinking

**Comment by tcrowe** [comment]
@maskleo Is it possible to remove indented list item formatting? e.g. `-` or `1. 2. 3.`

Those are common problems in markdown formatting.

That may help get you more correct formatting on your code examples.

It also looks like markdown tables may help you get even better formatting.

https://www.tablesgenerator.com/markdown_tables
https://packagecontrol.io/packages/Table%20Editor
https://atom.io/packages/markdown-table-editor

Can you let me know if any of that helps?

**Comment by maskleo** [comment]
Thanks,I will try to do that after work. @tcrowe
