### ISSUE TITLE
suggestion: build a forum for ask-for-help

### ISSUE THREAD

**Issue by huyingjie** [hexojs/hexo#2999]
Hugo has a forum (https://discourse.gohugo.io/) for people to ask for help. It can separate the issue section on GitHub and simple ask-for-help questions. 

Could you make one?

**Comment by NoahDragon** [comment]
Yeah, it's good to have one. But I think we may need a dedicated server to host the forum. @tommy351

**Comment by huyingjie** [comment]
@NoahDragon @tommy351 How about [flarum](http://flarum.org/)? It uses PHP and can be hosted on any shared server. The cost will be low.
The downside is that it is the beta version and cannot guarantee to upgrade without errors for each version.

**Comment by NoahDragon** [comment]
Thanks for the suggestion. I also found this https://www.freeflarum.com/ . But it hosts ads.

**Comment by huyingjie** [comment]
@NoahDragon I found that, too. I created a forum for my theme on it. https://arsnippet.freeflarum.com/
Official Hexo forum should possess the ability to control ads. Self-hosted is a good option. There is another forum app, https://github.com/NodeBB/NodeBB

**Comment by tcrowe** [comment]
My preference would be to keep it to github. The gitter has been available but participation is low. My guess would be that participation on a forum would also be low and would also be many duplicates of what is right here on github.

There's a ton of activity on github to keep anyone interested.

I hope you don't mind me adding a dissenting view. 😳

**Comment by huyingjie** [comment]
@tcatche I appreciate your reply and here is my concern.

I don't like GitHub issues. It is very cold and not a good way to build a warm community.I met the situation at least twice that owners of repos closed my problems without answering the questions. 
After the issue is closed, new answers will be rarely created by other people except for owners. Then how can I find the answer to my questions?

There is another extreme, never close issues. The number of issues is overwhelming. People can assign the label to the issues but most people won't create the labels. https://github.com/hexojs/hexo/issues.  The homepage of issues gives a vivid example. If not all questions are assigned labels, using labels to filter issues are not a convenient way to find workable bugs for a potential contributor.

Both Hugo and Hexo are statistic website generators. Hugo's forum can be a good predictor if Hexo builds a similar forum. https://discourse.gohugo.io/ Their forum is very active. The gitter of Hugo is active, too. The gitter is used by developers of Hugo, not for ask-for-help. 

Issue section on Hexo should be dedicated to bugs and feature requests. I hope that Hexo can attract more users and developers, and build a better community.

**Comment by tcatche** [comment]
@huyingjie Seems like you mentioned wrong people...

**Comment by huyingjie** [comment]
@tcatche I am sorry.

**Comment by YoshinoriN** [comment]
I totally agree with @huyingjie

[Discourse](https://www.discourse.org/) is free for opensource forum.
How do you think @NoahDragon ?

**Comment by tomap** [comment]
I see the need for a space to ask questions, but I would prefer not to do it on a forum, at least not one that we are handling ourselves. I would rather suggest to do it on stackoverflow, or open another channel on gitter, and invite people to go there. There is also disqus, attached to the site

**Comment by stevenjoezhang** [comment]
How about using GitHub discussions?
https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/
Demo:
https://github.com/zeit/next.js/discussions

**Comment by dumindu** [comment]
Hi guys,
Any update on this? 

Also with Node 14, many users faced lot of issues and having a forum or a chat channel will be super helpful to reduce duplicate error reporting and to get quicker solutions for the problems like we faced with Node 14.

Thanks

**Comment by SukkaW** [comment]
@dumindu Gitter or Slack would be great. But personally I would prefer a Community.

**Comment by dumindu** [comment]
@SukkaW If we are having a Gitter or Slack channel, users/ the community will be more active than on forums.

**Comment by jiangtj** [comment]
> If we are having a Gitter or Slack channel

@dumindu In fact, we are having a  Gitter, and Discord and Slack are very similar. In addition, we can also chat through Telegram or Google Group.

However, I think it's a little bit more, I prefer to discuss in one place.

https://github.com/hexojs/hexo#more-information
![image](https://user-images.githubusercontent.com/15902347/86103822-d31c0380-baef-11ea-8abd-5cb303144cd3.png)

@SukkaW before @ivan-nginx was active in the next theme, he added some bridge robot, sameroom and t2bot.
- [sameroom](https://sameroom.io/): I feel good, but it does not support Discord
- [t2bot](https://t2bot.io/): sometimes downtime (maybe often ...)

How about this?

**Comment by dumindu** [comment]
Btw having multiple communication channels make the community less active due to active users distribute through multiple channels and none of them makes more active and stable. If we can choose only Slack or Gitter, the community will be more active and will be easier to get a help from others while a help/ discussion needed.

**Comment by stevenjoezhang** [comment]
Welcome to hexo Discussions! https://github.com/hexojs/hexo/discussions
