### ISSUE TITLE
Why I can't access tags and categories page

### ISSUE THREAD

**Issue by junyussh** [hexojs/hexo#3001]
## Environment Info

Node version(`node -v`): 7.5.0

Your site `_config.yml` (Optional): 

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

Today, I adapted a the theme [Clean-blog](https://github.com/junyussh/hexo-theme-graceful) and modified to my style. However, I found that I can't access tags and categories page. Even use the [theme's](https://github.com/junyussh/hexo-theme-graceful) original file.  I don't know what's go wrong.
I've tried the ways in the Internet, still not solving it.
This is my modified theme - [Graceful](https://github.com/junyussh/hexo-theme-graceful).
Please help me solve the problem. I've troubled this for a long time.

Thanks.

**Comment by NoahDragon** [comment]
Have you installed the hexo-generator-categories and tags?

**Comment by junyussh** [comment]
still cannot generate tags and categories

**Comment by NoahDragon** [comment]
Have you tried other theme to see if the categories and tags can be generated?

**Comment by junyussh** [comment]
I can generate tag and category pages in Landscape theme with these packages.
But I can't generate the pages in my theme, it shows some errors on my console.

![ejs ERROR](https://user-images.githubusercontent.com/11587044/35669838-63705c5e-0771-11e8-87b1-c9b767cdb437.png)

**Comment by NoahDragon** [comment]
Fist thing I noticed is the `partial('article-tags', {item: page})`. It should change to `partial('_partial/article-tags', {item: page})`

**Comment by junyussh** [comment]
I think the problem is so complex that I have better to give up.
By the way, Landscape theme can generate tag and categories pages, but the page didn't load the posts.

**Comment by NoahDragon** [comment]
@junyussh Yeah, this is the weird part.  One theme can do and another not.

**Comment by tcrowe** [comment]
@junyussh The best thing to do might be to reference the landscape theme because it's more or less complete:
https://github.com/hexojs/hexo-theme-landscape/blob/e9f5172b0e172cfe38d1875f8a7f13a351d5f92e/layout/_partial/post/tag.ejs

Then you can check if your posts have the correct format for tags and categories:

https://hexo.io/docs/front-matter.html#Settings-amp-Their-Default-Values

```yml
tags:
- tag1
- tag2
categories:
- category1
- category2
```
