### ISSUE TITLE
ES6 syntax support highlighting

### ISSUE THREAD

**Issue by BosenY** [hexojs/hexo#3005]
## Environment Info

Node version(`node -v`): 8.0.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

![image](https://user-images.githubusercontent.com/16064272/35659253-2d746dd8-0740-11e8-9961-eafcc84dbdd5.png)
how to set this type of css.....
## For feature request

I want to make ES6 syntax support highlighting

**Comment by tcrowe** [comment]
It's not clear what you are asking or saying. Can you please clarify, @BosenY ?

**Comment by BosenY** [comment]
Sorry,I found that it is actually a highlightjs issue. Highlightjs has't supported yet ECMAScript 2015 (ES6) syntax. @tcrowe

**Comment by NoahDragon** [comment]
@BosenY If this issue is not related to Hexo, please close it when you have time.
