### ISSUE TITLE
hexo deploy to github cause libressl timeout

### ISSUE THREAD

**Issue by hhao99** [hexojs/hexo#3006]
node version 8.9.4
hexo ^3.2.0
hexo-deployer-git ^0.3.1

I think this problem is on the network, I'm in China and the connection to github.com may reseted by GFW, )-:.
But I deploy it manually, it does work.
Maybe the deployer need upgrade the ssl library.

there is the console output:

blog git:(master) ✗ hexo deploy
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
On branch master
nothing to commit, working tree clean
fatal: unable to connect to githu.com:
githu.com[0: 69.172.201.153]: errno=Operation timed out

FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: unable to connect to githu.com:
githu.com[0: 69.172.201.153]: errno=Operation timed out

    at ChildProcess.<anonymous> (/Users/k9/code/blog/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by NoahDragon** [comment]
I saw the link is `githu.com` not `github.com`.

**Comment by hhao99** [comment]
sorry of the typo, it's ok now
Great thanks.
