### ISSUE TITLE
hexo init - ERR! network 'proxy' but I'm not using proxy

### ISSUE THREAD

**Issue by rafr3** [hexojs/hexo#3008]
I have the same problem but I'm not using proxy.
First, tried to run `hexo init`, when it failed I tried to run `npm install` inside directory manually.
I'm not using proxy, I have access to registry url using any browser.
When I changed the registry from *https* to *http* then `hexo init .` works but that's not solution.
![2018-02-03 20_25_27-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/8841983/35770783-45a2fd64-0922-11e8-9a73-2732017a6bb3.jpg)

## Environment Info

Node version(`node -v`): 8.9.4
NPM version: 5.6.0
hexo-cli@1.0.4

**Comment by NoahDragon** [comment]
As the warning indicated, please check with the network. Make sure the connection to npm is not blocked.

**Comment by rafr3** [comment]
Connection was not blocked. I was able to connect with exactly the same registry url using web browser.
I have uninstalled node & npm few times, cleared npm cache using `--force` mode and finally installed Yarn and when I started to learn how to use it npm started working. I don't know what happened until today.

**Comment by tcrowe** [comment]
Did that last thing you did solve the problem @rafr3 ?

**Comment by rafr3** [comment]
Yes, problem solved.

**Comment by tcrowe** [comment]
Very well! Thanks for the update @rafr3
