### ISSUE TITLE
Suggestion:auto convert local img path to GitHub Pages link

### ISSUE THREAD

**Issue by chenguokai** [hexojs/hexo#3011]
## Environment Info

Node version(`node -v`): v6.11.1

## For feature request

I use GitHub itself to store the images related to my sites , but if I want to preview the images as well as use the post online , I have to edit the img paths before I generate and deploy it. Would you please add this feature as an option ? Thanks in advance.

**Comment by tcrowe** [comment]
Hi @chenguokai can you see if this plugin accomplishes that for you? https://github.com/wizicer/hexo-tag-githubimage/

There are some other github plugins which may do that here: https://hexo.io/plugins/

**Comment by LazyKnightX** [comment]
Please close this issue if it has been solved. @chenguokai
