### ISSUE TITLE
Hexo should load ./ as a plugin

### ISSUE THREAD

**Issue by problem233** [hexojs/hexo#3016]
Sometimes I don't want to make a separate plugin to extend Hexo. If Hexo loads `./` as a plugin, it would be very convient.

I add `./` as a dependency in `package.json` to load `./index.js` for now.

**Comment by problem233** [comment]
算了还是用中文吧 \_(:з)∠)\_

Hexo 不会加载站点文件夹内的 js 文件，即使

**Comment by tcrowe** [comment]
What about adding your plugins into `./scripts`? https://hexo.io/docs/plugins.html#Script

**Comment by problem233** [comment]
Thanks.
