### ISSUE TITLE
Defer parsing of JavaScript, how to do with Hexo?

### ISSUE THREAD

**Issue by MrBRUE** [hexojs/hexo#3017]
Hi, I have decently optimized my static Hexo site. However there is still a lot of JavaScript being loaded during initial page load.  Found that out by putting it through gtmetrix.com.

So question is, is there a module or a property I can use to defer loading of scripts that are not crucial for initial page load? I can see scripts like this being loaded early on:
js/lg-autoplay.min.js
js/query.justifiedGallery.min.js 

And so on. Scripts that are not even critical for the view.

Thanks for any advice!

**Comment by tcrowe** [comment]
Hi @MrBRUE 👋 

Each theme can load scripts a certain way or a helper like this: https://hexo.io/api/helper.html#Example

Another thing you can try is adding `defer` or `async` attributes to the scripts. https://www.w3schools.com/tags/att_script_defer.asp

Another common thing people need is `skip_render` to prevent their custom scripts from being rendered through hexo. https://www.w3schools.com/tags/att_script_defer.asp

If that helps you get to your solution can you let me know and/or close out the issue?

**Comment by MrBRUE** [comment]
Hi, is there a way to auto-add those defer attributes as part of the Hexo build process? Perfect world solution would be some property in the _config.yml. Would certainly prefer that over introducing some extensions that might break with the next update of the template, Hexo, jadda-jadda. You get my point I guess.

**Comment by tcrowe** [comment]
I don't see anything for that in the config manual.

Your best bet to get it done may be to customize the theme. (Easy)

There may be a plugin for it if you search on hexo plugins. (Easy)

Another option is you may be able to override the script helper function with your own plugin. https://hexo.io/api/events.html#ready (medium difficulty)
