### ISSUE TITLE
Video in post.md above the fold

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#3018]
I try to show video in `post.md` above the fold like this...

```

---
layout: post
title: Hello World
author: John
video: https://www.youtube.com/watch?v=Ac17-_fvbUQ
---
Here the content
I love videos
---

```

In my `.ejs` post template I have something like this...

```
 <iframe width="420" height="315"
src="<%- post.video %>">
</iframe> 
```

But it does not work... how to fix it?

**Comment by tcrowe** [comment]
What's the HTML output?

Looks fine here but what about `<%= post.video %>` ?

There's a special URL for YouTube embeded videos. `https://www.youtube.com/embed/[video id]`

**Comment by rabas007** [comment]
@tcrowe - thanks, Tony.

It was the `embed` code I missed... all good now, thanks again!
