### ISSUE TITLE
JS files are wrongly processed as HTML files

### ISSUE THREAD

**Issue by yushijinhun** [hexojs/hexo#3019]
## Environment Info

Node version(`node -v`): v8.9.4

Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 /home/yushijinhun/repos/hexo-test
├── hexo@3.5.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

## For BUG
I initialized a fresh Hexo site with `hexo init`. Then I created a JavaScript file `source/js/test.js`, whose content is:
```javascript
console.log("<test string>");
```

Then I executed `hexo generate`. I expect the rendered JS file to be same as the source. However, the content of the rendered file `public/js/test.js` is:
```javascript
console.log("<test string="">");
</test>
```

Also, I did some research about this and found that, if I directly call `hexo render source/js/test.js`, the output is the same as expected.

**Comment by printempw** [comment]
Successfully reproduced.

![screenshot](https://i.loli.net/2018/02/11/5a7fe2c7b12f0.png)

May the problem be caused by filtering HTML tags on JavaScript files?

**Comment by JLHwung** [comment]
use `skip_render` if you simply want to copy files from source to destination, see #1633.

**Comment by yushijinhun** [comment]
Why the output of `hexo generate` is different from that of `hexo render`? Shouldn't they be the same?

**Comment by NoahDragon** [comment]
@yushijinhun this is an know issue which we haven't figure out the fix yet.
