### ISSUE TITLE
how to use hexo helper in my custom helper?

### ISSUE THREAD

**Issue by LazyKnightX** [hexojs/hexo#3025]
I'm extending hexo and add my custom helper (in `themes/<my-theme-name>/scripts/my_custom_helpers.js`).

I'm trying to use hexo helper "full_date" in my custom helper extending script, but that doesn't work.

```javascript
hexo.extend.helper.register('list_posts_2', listPosts2Helper);

function listPosts2Helper(posts, options) {
  ... some others code

  full_date(someDate, options.date_format); // console output: date_full is not defined
  fullDateHelper(someDate, options.date_format); // console output: fullDateHelper is not defined

  ... some others code
}
```

Should I copy function fullDataHelper from `node_modules/hexo/lib/plugins/helper/date.js` or is there any function I don't know could solve this?

Or if the helper is designed to not depend on others helper, please close this issue.

Thanks for any help.

**Comment by ertrzyiks** [comment]
There is a public method to get a reference to a helper function, so I guess you can use it:
```
hexo.extend.helper.get(name)
```

The helper must be called in the context of hexo, so you can try this:
```
const full_date = hexo.extend.helper.get('full_date').bind(this)
const result = full_date(new Date(),  options.date_format)
```
