### ISSUE TITLE
API: hexo.call('deploy', {}) doesn't throw error, it only logs it in the console.

### ISSUE THREAD

**Issue by quincyyhuang** [hexojs/hexo#3026]
## Environment Info

Node version(`node -v`): v8.9.4

Hexo and Plugin version(`npm ls --depth 0`): 
```
+-- hexo@3.5.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```

### Description

I'm using Hexo's API and it seems that hexo.call() function doesn't throw an error if the deployer doesn't exist, it only logs the error message to the console which prevents the further .catch clause to catch the error. And it even triggers "deployAfter" event even if the deployment fails which I think is not a good behavior. I didn't check other hexo args but I guess the issue is universal.

### Reproduce

```
// test.js

var Hexo = require('hexo')

const hexoRoot = "H:\\projects\\Hexo"

var hexo = new Hexo(hexoRoot, {})

hexo.init().then(() => {
    hexo.call('deploy', {})
    .then(() => {
        console.log('No error is caught.')
    })
    .catch(err => {
        if (err) console.log('Error is caught.')
    })
})

hexo.on('deployAfter', () => {
    console.log('Deploy finished.')
})
```

Result:
```
$ node test.js
ERROR Deployer not found: git           // This ERROR is a message but not an Error in code.
Deploy finished.
No error is caught.
```

**Comment by stevenjoezhang** [comment]
"Deployer not found" is not considered a fatal error. This behavior may be a feature of Hexo, otherwise additional code is required for error handling.
