### ISSUE TITLE
Use `post.categories` in `<% if() %>`

### ISSUE THREAD

**Issue by liurui39660** [hexojs/hexo#3027]
## Environment Info

Node version(`node -v`):
v9.4.0
Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 E:\Blog
+-- hexo@3.5.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-baidu-sitemap@0.1.2
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.1.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-helper-qrcode@1.0.2
+-- hexo-inject@1.0.0
+-- hexo-math@3.0.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-mathjax@0.6.0
+-- hexo-renderer-pandoc@0.2.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For question

I'd like to implement a feature in my theme, it is simple:

```html
<% if (post.categories=="Some Categories") { %>
    do some things
<% } else { %>
    do other things
<% } %>
```

But the code in the `else` part won't be executed, even if the `post.categories` is (or contains, I know the `post.categories` is an array) "Some Categories".

I tried to print the `post.categories` with the code:

```html
<p><%= post.categories %></p>
```

But it only shows `[object Object]`.

What shall I do to?

**Comment by liurui39660** [comment]
I solved this problem myself, I modify the code into:

```html
<% if (post.categories.data[0].name=="Some Categories") { %>
    do some things
<% } else { %>
    do other things
<% } %>
```

**Comment by LazyKnightX** [comment]
Additional hint for people who find this.
You could use `console.log` in [EJS](http://ejs.co/), you'll see object structure in console board.
