### ISSUE TITLE
How to prettify URLs?

### ISSUE THREAD

**Issue by herkyl** [hexojs/hexo#3029]
How do I prettify my URLs, so that www.example.com/foobar.html becomes www.example.com/foobar instead?

I understand that after compiling I am free to serve the HTML files as I wish but is it also possible to achieve URLs without .html during development in the server mode? I am asking because I am porting an existing website to Hexo and this requirement is mandatory for that project.

**Comment by LazyKnightX** [comment]
Use `hexo serv` will serve your website at `localhost:4000` by default and you could access foobar by `/foobar` than `/foobar.html`.

If this is not correct, please add details about `foobar.html`, does it like "{hexo}/source/foobar.html" or "{hexo}/source/_posts/foobar.html"?

**Comment by herkyl** [comment]
I have a template file in `/source/example.jade` like so. When I enter `http://localhost:4000/example` into Chrome it rewrites the URL to `http://localhost:4000/docs/example/`. This results in a 404.

Now when I move the same file to `/source/example/index.jade` the URL works, but I don't want to nest my files like so.

I am quite new to Hexo, maybe it has something to do with the Jade/pug plugin?

**Comment by LazyKnightX** [comment]
Check your `_config.yml` file, there should be parameters named `url` and `root`.
I think your problem goes here.

You could find detail about config file here: https://hexo.io/docs/configuration.html

**Comment by herkyl** [comment]
I don't think that url and root can configure this behaviour. As far as I understand `url` is for defining the actual base url of your site and `root` is used when your website lives in a subdirectory.

**Comment by LazyKnightX** [comment]
Do you mind uploading your blog files and your environment information (node version, system platform, and anything you think need to mention)?
I'm not sure where is your problem if the config file cannot solve.
