### ISSUE TITLE
hexo-new supports sub-folder under source/_post

### ISSUE THREAD

**Issue by laoshaw** [hexojs/hexo#3039]
When I have thousands of blog posts they are all under source/_post, the same directory which is not scale-able and extremely hard to manage, can hexo support subfolders under source/_post? I can manually create sub-folders under _post and it seems hexo honrs that, but it will be better if I can do:

`hexo new "my new blog" -p "my-subfolder-under-posts"`

somehow the -p flag does not work at all with 'hexo new' , tested with 3.5.0

**Comment by baoang** [comment]
涉及到对_post目录下的博文管理的问题，我觉得可能把博文的文件名进行一下规则的命名会好一些，比如命名成`年-月-日-标题`这样的。我自己的是从WP中导出再导入Hexo的，标题是乱码，的确不方便管理。不过有一个[插件](http://timnew.me/blog/2014/08/19/hexo-plug-in-to-rename-the-post-according-to-title-automatically/)可以很好的解决这个问题。

另外，Hexo中提供了几类[Layout](https://hexo.io/docs/writing.html#Layout)，也许把这个功能增强一下会解决你的需要？

**Comment by NoahDragon** [comment]
May I ask where did you find the `-p` parameter for `hexo new`?
