### ISSUE TITLE
Do it have the way for Revisioning (Add a hash to filename)?

### ISSUE THREAD

**Issue by vimcaw** [hexojs/hexo#3042]
I use hexo to make my blog and make a theme updated frequently.
Although I set `no-cache` on `cache-control`, Chrome still caches my site file.
After updating CSS and JS file and deploying, GitHub repo has updated, but my site still uses the old file for a long time.
After I clear cache, it uses the new file, but I can't tell my visitor clear cache every time, right?
I search some info and find Chrome will force cache site file.
One solution is to add the md5 of the file to the filename.
Such as `main?75f329868c94e5df.js`
I search the plugin to do it for a long time but finding nothing can do it.
I try to make a plugin, but [hexo\-fs](https://github.com/hexojs/hexo-fs) can't rename a file.

**Comment by ertrzyiks** [comment]
I'm looking for the same thing. Found [this plugin](https://github.com/hexojs/hexo-asset-pipeline) and it uses `route.set` to generate hashed filenames
https://github.com/hexojs/hexo-asset-pipeline/blob/5b4527b839aca380f61419536f89ac138b9eb357/lib/revision.js#L113

Unfortunately, the plugin doesn't fully work for me (I use the latest hexo version), but it may be a good direction.

**Comment by vimcaw** [comment]
@ertrzyiks 
Thanks! It's exciting plugin!
But it turned my `href` attribute into `\undefined` after I enable it. 
Maybe I can fix this.

**Comment by ertrzyiks** [comment]
@vimcaw yes, it generates '/undefined' for me too. Keep us posted if you manage to use it. I'm going to use some alternative approach (which I don't know yet)

**Comment by vimcaw** [comment]
@ertrzyiks I has found the reason which resulted in the bug, and partly fix this, but it still has some bug about `asset-folders` path.
I believe I can fix it in recent days.

**Comment by vimcaw** [comment]
@ertrzyiks I has fixed this bug: [V1\.4\.2 \- Fixed: Revisioning turn src and href into undefined\. \\r\\n\- O… by vimcaw · Pull Request \#15 · hexojs/hexo\-asset\-pipeline](https://github.com/hexojs/hexo-asset-pipeline/pull/15)

**Comment by ertrzyiks** [comment]
@vimcaw excellent job! I'm only struggling with `background-image` inline styles now. Probably just exclude from revisioning. Thanks for doing this!

**Comment by vimcaw** [comment]
@ertrzyiks It still has some bugs in the relative path and revisioning sequence. A temporary solution is to add error paths to `exclude list`. I will try to fix them when I'm free.

**Comment by vimcaw** [comment]
There are 3 ways to achieve it:
1. [hexo\-asset\-pipeline](https://github.com/hexojs/hexo-asset-pipeline) Revisioning can achieve it.
2. [hexo\-renderer\-webpack](https://github.com/briangonzalez/hexo-renderer-webpack) can use `webpack` to easily achieve it.
3. directly use `webpack` or `gulp` (commend to install at theme folder). first, `webpack` or `gulp` handle the files and output some files, then the themes use the outputed files.
