### ISSUE TITLE
hexo d 报错，无法推送内容到github

### ISSUE THREAD

**Issue by wmhh1129** [hexojs/hexo#3046]
修改了一篇md的内容之后，先在windows cmd上跑了一次 `hexo g && hexo d`，然后报错，然后看issue有人说解决方法是用git bash，但是我换成了git bash之后也无果。求助。
错误如图：
![image](https://user-images.githubusercontent.com/18160036/36627758-7ded6770-1982-11e8-9e1c-20f3638e8d27.png)
_config.yml如图：
![image](https://user-images.githubusercontent.com/18160036/36627764-95ab2dde-1982-11e8-8d38-d7e2981b499a.png)

**Comment by JLHwung** [comment]
see https://github.com/hexojs/hexo/issues/3043#issuecomment-368009045

**Comment by wmhh1129** [comment]
thanks @JLHwung
