### ISSUE TITLE
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

### ISSUE THREAD

**Issue by wxlost** [hexojs/hexo#3048]
![20180225090757](https://user-images.githubusercontent.com/19698455/36636930-729ee3f6-1a0b-11e8-843d-a41c25cec645.png)

系统是centos7 x64
Linux aliyun 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
根据官网教程安装的 Node.js 和git
wget -qO- https://raw.github.com/creationix/nvm/master/install.sh | sh
然后执行安装hexo报错.求解

-----------------
/root/.nvm/versions/node/v9.6.1/bin/hexo -> /root/.nvm/versions/node/v9.6.1/lib/node_modules/hexo-cli/bin/hexo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
-----------------

**Comment by JLHwung** [comment]
You can safely ignore this, see https://github.com/Zulko/eagle.js/issues/35#issuecomment-351092844

**Comment by syusama** [comment]
我也是同样的错误，无法安装hexo
I have the same eeror and cann't insatll hexo,how can I do

**Comment by wxlost** [comment]
@syusama 我后来无视了错误 [我的个人教程](https://blog.wxlost.com/hexo-next.html)
