### ISSUE TITLE
skip-render option doesn't work on yml files

### ISSUE THREAD

**Issue by troyliu0105** [hexojs/hexo#3049]
## Environment Info

Node version(`node -v`): v9.4.0

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.5.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2

## For question
I put a yml file in source folder `.gitlab-ci.yml`, and add skip_render and include option like below
```
skip_render: .gitlab-ci.yml

include:
  - .gitlab-ci.yml
```
But it didn't work well. hexo just copied the file to the `public` folder but also generate a `.gitlab-ci.json` file
<img width="219" alt="screen shot 2018-02-25 at 2 53 02 pm" src="https://user-images.githubusercontent.com/5518286/36638931-a6c1c2d6-1a3b-11e8-81f0-9e80b7db4d3e.png">

Could anyone tell me how to avoid to generate json file? 😭

**Comment by JLHwung** [comment]
I can't reproduce this issue using your config. Could you try `hexo clean && hexo g`?
