### ISSUE TITLE
Change HTML for list_categories and list_tags?

### ISSUE THREAD

**Issue by testareas** [hexojs/hexo#3050]
Hello,
I wanted to ask, when I use: `<%- list_categories([options]) %>` or `<%- list_tags([options]) %>`
Where can I control the HTML output? I want to change it completely, the `style` option is not what I am looking for.

**I want to do something like this:**
~~~~
<ul class="custom_class">
  <li class="custom_class2"><a href="url" class="custom_class3">category1</a></li>
  <li class="custom_class2"><a href="url" class="custom_class3">category2</a></li>
  <li class="custom_class2"><a href="url" class="custom_class3">category3</a></li>
</ul>
~~~~
 I also looked in the categories modules in the node_modules folder, but didn't find the output code :-/

Thank you! :)

**Comment by tcrowe** [comment]
Hi @testareas 👋 

That is an interesting question!

I tried a little experiment here. I assigned the result of those functions into a variable:

```ejs
<%
var catList = list_categories()
%>

<!-- escaped as a string -->
<%=catList%>

<!-- as html -->
<%-catList%>
```

It could, with some difficulty, be modified with string functions.

---

Then I remembered that many things are available within the `site` structure. The `categories` and `tags` are warehouse databases and can be queried. https://hexo.io/api/locals.html

```ejs
<% site.categories.each(function(item) { %>
  name: <%=item.name%><hr>
  id: <%=item._id%><hr>
  slug: <%=item.slug%><hr>
  path: <%=item.path%><hr>
  permalink: <%=item.permalink%><hr>
  posts: <%=typeof item.posts%><hr>
  count: <%=item.length%><hr>
  <br><br>
<% }) %>
```

That seems to be a much more convenient method to work with those things.

Have we solved it?

**Comment by testareas** [comment]
@tcrowe thank you thank you! Not only did you solve my problem but you opened my mind up to new possibilities with the Wearhouse database! You're a genius! Thank you kind sir :)

**Comment by tcrowe** [comment]
Thank you :blush:
