### ISSUE TITLE
hexo deploy error

### ISSUE THREAD

**Issue by tedeum** [hexojs/hexo#3052]
## Environment Info
INFO  [hexo-math] Using engine 'mathjax'
hexo: 3.4.3
hexo-cli: 1.0.4
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

## For BUG
fatal: HttpRequestException encountered.
   ��������ʱ�����
fatal: HttpRequestException encountered.
   ��������ʱ�����
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: HttpRequestException encountered.
   ��������ʱ����
fatal: HttpRequestException encountered.
   ��������ʱ����
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (D:\archive2\code\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (D:\archive2\code\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by csuDavid** [comment]
try it via console:
git config --global credential.helper wincred

**Comment by Guoch0526** [comment]
@csuDavid thanks ！

**Comment by NoahDragon** [comment]
Could you please close if this issue resolved.

**Comment by AndyChungcn** [comment]
@csuDavid Thanks a lot , It worked!!!   this problem confused me a lot.

**Comment by cnscorpions** [comment]
facing the same problem, just resolve it. 
@tedeum for windows, you can download [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.14.0)
