### ISSUE TITLE
[Feature Request] hexo init should add scripts for npm

### ISSUE THREAD

**Issue by michaeljota** [hexojs/hexo#3053]
## Environment Info

Node version(`node -v`): 8.9.4

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
```
+-- hexo@3.5.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-migrator-rss@0.1.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-scss@1.1.0
`-- hexo-server@0.2.2
```

## For feature request

`hexo init` should add scripts in `package.json` such as `start: hexo server` and `generate: hexo generate`.

NPM scripts are standard use, and they should be at least generated.

**Comment by NoahDragon** [comment]
I feel user could add those scripts into package.json easily. 

Moreover, `hexo init` couldn't be written into package.json, as it runs even before the package.json exists.

**Comment by michaeljota** [comment]
I understand that the user could add those, but as a user I expected to had it already.
