### ISSUE TITLE
"hexo d" make a wrong push about pushing all code of another branch to master branch.

### ISSUE THREAD

**Issue by ZhouFyk** [hexojs/hexo#3054]
I  use two branch for my blog: all source code in hexo branch,while static files in master branch.All is well at first.But some problems appear when i write my blog on another machine.

I clone the repo `git clone git@github.com:repo/repo.github.io.git blog`, and `npm install hexo`,`npm install`,and `npm install hexo-deployer-git --save`.All is right.

At last,i use `hexo d`，it runs without error.But my master branch in my repo is wrong.All source code is pushed to master branch, instead of the code in public directory. Maybe like i push local hexo branch code to remote master branch.

What i know about deploy in hexo is that there are some parameters in _config.yml file. And my _config.yml about git is :
```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:repo/repo.github.io.git
  branch: master
```

The document about it is [here](https://hexo.io/docs/deployment.html#Git) and I get no help about my problem.

so can someone help me? Is it something wrong about hexo or my config about git?

append:
i find something when i run `hexo d`：
1. it is right:
`Branch master set up to track remote branch master from git@github.com:repo/repo.github.io.git.`

2. it is wrong:
`Branch hexo set up to track remote branch master from git@github.com:repo/repo.github.io.git.`

so is it a problem about git ?But i have no idea,can someone tell me some infomation about the problem?

**Comment by ZhouFyk** [comment]
i find something when i run `hexo d`：
1. it is right:
`Branch master set up to track remote branch master from git@github.com:repo/repo.github.io.git.`

2. it is wrong:
`Branch hexo set up to track remote branch master from git@github.com:repo/repo.github.io.git.`

so is it a problem about git ?But i have no idea,can someone tell me some infomation about the problem?

**Comment by ZhouFyk** [comment]
ok i got it. when i remove .deploy_git/ .then operate as normal, all is well.

**Comment by limengke123** [comment]
thanks! I fix the same problem following your step.
