### ISSUE TITLE
hexo部署到GitHub上出错，求解决方案！

### ISSUE THREAD

**Issue by darkwebgl** [hexojs/hexo#3055]
把hexo部署到GitHub上时，报错如下，请问如何解决？

*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'username@localhost.(none)')
error: src refspec HEAD does not match any.
error: failed to push some refs to 'https://github.com/username/username.github.io.git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: error: src refspec HEAD does not match any.
error: failed to push some refs to 'https://github.com/username/username.github.io.git'

at ChildProcess.<anonymous> (/Users/username/Desktop/myblog/blog1/node_modules/hexo-util/lib/spawn.js:37:17)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Socket.stream.socket.on (internal/child_process.js:346:11)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by hans1980775481** [comment]
您最终解决了这个问题吗？？

**Comment by stevelannist** [comment]
同问

**Comment by Em1yaSakura** [comment]
同问

**Comment by uiolee** [comment]
the log output had tell you why and how to do.


> Please tell me who you are.
> 
> Run
> 
> git config --global user.email "[you@example.com](mailto:you@example.com)"
> git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
