### ISSUE TITLE
Custom page locals and front-matter defined variables

### ISSUE THREAD

**Issue by garydouble** [hexojs/hexo#3056]
## Environment Info

Node v9.6.1

ejs@2.5.7
hexo@3.5.0
hexo-generator-archive@0.1.5
hexo-generator-category@0.1.3
hexo-generator-index@0.2.1
hexo-generator-tag@0.2.0
hexo-renderer-ejs@0.3.1
hexo-renderer-marked@0.3.2
hexo-renderer-stylus@0.3.3
hexo-server@0.3.1

## Question

Hello lovely people.

I'm trying to sort a new theme out but want to be able to customise certain elements from within the front-matters.

For example, say I have this in my layout file:

    // layout.ejs
    <h1 class="<%- page.customHeaderClass %>"><%= page.title %><h1>

Then for any post or page I'd like to control it using:

    // random-page/index.md
    ---
    title: Something awesome
    ...
    customHeaderClass: fancy-font-1
    ---

I've tried a few things to make this work (including forking the repo and tinkering about) but I can't seem to get it working for my pages.
Is this a limitation with using the warehouse data models? Or is there a setting / plug-in somewhere that will allow me to do this.

So, in a one-liner: **How do I get front-matter defined variables to stick on the page / post objects within theme layouts?**

I'm fairly new to Hexo, but I have to say, so far, the experience has been an extremely positive one and I look forward to diving deeper into it.
Thanks in advance.
Gary D.

**Comment by garydouble** [comment]
OK. So this actually works for posts but not pages. Any chance this is in the pipeline ?

**Comment by tcrowe** [comment]
I worked for me when I tested it like so:

`hexo new page contact`

`source/contact/index.md`

```md
---
title: contact
date: 2018-03-05 19:09:51
customx: five
---
Hi garydouble! 👋
```

`themes/landscape/layout/page.ejs`

```ejs
<%- partial('_partial/article', {post: page, index: false}) %>

<%=(typeof page.customx)%>
<%=page.customx%>
```

And it worked. I got a string type and "five" when I rendered the contact page.

Can you check your source and see if it, indeed, works? Or not!

**Comment by garydouble** [comment]
OK appears to be fine now. Not sure what I did or had done before.

Great work guys, really loving hexo! 
Thanks.

**Comment by Atulin** [comment]
Digging it up, because I seem to have a problem using custom variables...
```md
---
title: Hello World
category: OwO
---
```
used as follows:
```twig
{% for post in site.posts %}

    <article class="post">
        <a href="/post/{{ post.id }}/{{ post.title }}" class="title">
            <h2 class="title">{{ post.title }}</h2>
        </a>
        <hr class="fading text" data-content="{{ post.category }}">
        <div class="excerpt">
            {{ post.excerpt }}
        </div>
        <a href="{{ url_for(post.path) }}" class="read-more">Read More</a>
    </article>

{% endfor %}
```
results in
```
<hr class="fading text" data-content="">
```

```
"hexo": "^3.2.0",
"hexo-generator-archive": "^0.1.4",
"hexo-generator-category": "^0.1.3",
"hexo-generator-index": "^0.2.0",
"hexo-generator-tag": "^0.2.0",
"hexo-renderer-ejs": "^0.2.0",
"hexo-renderer-marked": "^0.2.10",
"hexo-renderer-stylus": "^0.3.1",
"hexo-server": "^0.2.2"
```

**Comment by tcrowe** [comment]
Hey @Atulin :wave:

I am wondering if you can try it with a different variable name. So instead of `category:` please use `xcat:`. Some variables might get written over in the 'processors.'

**Comment by Atulin** [comment]
Ah, it seems that was it. `xcat` solves the issue.

Now I just gotta figure out how the hell pagination works, and I'm set. Thanks!

**Comment by tcrowe** [comment]
You're welcome, @Atulin 👍
