### ISSUE TITLE
Does the image description(图片描述) can't render?

### ISSUE THREAD

**Issue by Zhang21** [hexojs/hexo#3057]
## Environment Info

Node version(`node -v`): v6.11.2

Hexo and Plugin version(`npm ls --depth 0`): 

```
+-- hexo@3.5.0
+-- hexo-deployer-git@0.3.1
+-- hexo-diagram@0.0.10
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-tag@0.2.0
+-- hexo-inject@1.0.0
+-- hexo-math@3.0.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
`-- hexo-wordcount@3.0.2
```

<br/>

## For question

Like this:

```
![mysql栗子](/images/mysql.jgp)
```

 Can't see the description which is mysql栗子 after render the post。

![image111](https://user-images.githubusercontent.com/18358275/36827175-e3117a6a-1d4c-11e8-91a1-dbeb4cf69da6.png)

<br>

the other case :

![image222](https://user-images.githubusercontent.com/18358275/36827228-395e1022-1d4d-11e8-80e9-2f2b38c399e7.png)

**Comment by tcrowe** [comment]
I could not reproduce this bug. I copied and pasted your code but I used a png. (see attached image)
<img width="391" alt="screen shot 2018-03-05 at 5 56 04 pm" src="https://user-images.githubusercontent.com/1634015/37008287-971eda3a-209e-11e8-8834-1ef15cb7c49e.png">

Which theme?

How can I test?

**Comment by Zhang21** [comment]
@tcrowe  The theme is Next. Thanks.

**Comment by Zhang21** [comment]
@tcrowe It have no thing with .jpg or .png images.

**Comment by tcrowe** [comment]
@Zhang21 thank you. I will try that theme soon.

**Comment by tcrowe** [comment]
Hi @Zhang21 I finally figured it out

`{% fullimage /images/mysql.jpg, mysql栗子, mysql栗子 %}`

https://github.com/iissnan/hexo-theme-next/blob/a12fb4408d9e575d871e65e8a8339f3d9f7fa23e/scripts/tags/full-image.js#L2

Can you try that in your post and see if it works?
