### ISSUE TITLE
Organize multiple types of posts

### ISSUE THREAD

**Issue by testareas** [hexojs/hexo#3060]
Hi all :)

I am building a site that will eventually have a lot of posts, so wanted to know if there was a way of having my posts organized in sub folders in the `_posts` folder? So something like this:

**World news**
- World news story 1
- World news story 2
- World news story 3

**Local news**
- Local news story 1
- Local news story 2
- Local news story 3

I know I can do this with categories, but once the site will have a few hundred posts it will be a bit of a nightmare finding and editing posts. Also is it possible to have custom layouts per section? So **World news** posts look different than **Local news** posts and so on?

Many thanks in advance!

**Comment by tcrowe** [comment]
Hello again @testareas ! 👋 

I just tried something like this. (attached image)

<img width="707" alt="screen shot 2018-03-05 at 5 46 20 pm" src="https://user-images.githubusercontent.com/1634015/37008002-54b75fec-209d-11e8-947e-f3c30f5c31e4.png">

So like `source -> posts -> {cat1,cat2} -> *.md files`

And the only thing I can see maybe throwing a wrench in your plans is if that doesn't work well with asset folders feature: https://hexo.io/docs/asset-folders.html

**Comment by testareas** [comment]
Hi again Tony :D Thanks for getting back to me so quick, I was also playing around and yes I do use the asset folders feature as it helps me to organise my files better. If I find a work around I will post here. But thanks again for taking the time to test!

**Comment by testareas** [comment]
Sorry @tcrowe forgot to ask, how would I call posts from sub folders? So in your example, if I wanted to call post from: **cat1** only?

**Comment by tcrowe** [comment]
Here's the answer for layouts:
https://youtu.be/wEwEDYaU_2c

**Comment by tcrowe** [comment]
"how would I call posts ... ?"

What does that mean? Like from querying the data?

**Comment by testareas** [comment]
Sorry call posts in the sense of using: `<% page.posts.each(function(item){ %>` so show and paginate posts from Cat1 folder and then Cat2, so not all together?

**Comment by testareas** [comment]
Thanks for the video link, made me chuckle :D

**Comment by tcrowe** [comment]
lol back to work! Africa can wait!

https://hexo.io/warehouse/Model.html#find

How about `.find({categories:'cat1'}).each...` ?

I don't know if it will work because `categories` is an array. If not `filter` or if statements.

How's that?

**Comment by tcrowe** [comment]
I just don't know if `paginator` can filter by category. You can try though: https://hexo.io/docs/helpers.html#paginator

**Comment by testareas** [comment]
Thanks @tcrowe still new to Hexo but will give it a go! Thanks for the help again!
