### ISSUE TITLE
Cannot deploy the blog

### ISSUE THREAD

**Issue by yjhmelody** [hexojs/hexo#3062]
## Environment Info

Node version(`node -v`):

v9.6.1

Your site `_config.yml` (Optional):

deploy:
  type: git
  repo: https://github.com/yjhmelody/yjhmelody.github.io.git
  branch: master

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

+-- hexo@3.6.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-json-content@3.0.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For question

fatal: HttpRequestException encountered.
   ��������ʱ�����
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: HttpRequestException encountered.
   ��������ʱ����
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (D:\code\my-github\hexo-blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at ChildProcess.cp.emit (D:\code\my-github\hexo-blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

## For feature request

I don't know it's a bug or my wrong config but it worked well several weeks ago.

**Comment by yjhmelody** [comment]
It may be a git config error, so I close the issue.

**Comment by UnclePetros** [comment]
I have exactly the same error.
Git configuration seems to be ok for me.
