### ISSUE TITLE
body is not defined in additional layout – cant show post data

### ISSUE THREAD

**Issue by zilahir** [hexojs/hexo#3063]
## Environment Info

Node version(`node -v`): `v6.11.1`

## For question

I want to have different layout for blogposts. The `md` files gets a `layout blogpost` addition tag. 

Then, in the `layout` folder i have a `blogpost.ejs` file, which loads. This file is empty. How can I get the post into this file? And how can I remove additional partials, that I only want on the home page `/` ? 

I have all my current code in github, with a more detailed desc of my issue. 

https://github.com/zilahir/hexohelp 

Any help would be appreciated!

**Comment by ertrzyiks** [comment]
Can you fix the URL to the Github repo? It shows 404 to me.

**Comment by NoahDragon** [comment]
Same here. Got 404.
