### ISSUE TITLE
Hexo on Debian Stretch

### ISSUE THREAD

**Issue by phicarre** [hexojs/hexo#3066]
hello,
Does Hexo still run for Debian Stretch ?
If yes, which version of node.js shall I install ? setup_9.x ?

**Comment by finetype** [comment]
There's no reason why it shouldn't. I'm on Debian stretch and just used it last night.

I'm using Node 7.8.0, npm 5.7.1, though I had some problem with something (maybe a plugin?) for which switching to yarn resolved the issue.

But this isn't really an issue, and seem inappropriate here. Just try it first. I imagine it should probably work on any modern version of node.

**Comment by phicarre** [comment]
I tried it first ...

curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
apt-get install y node.js

Sorry, it is in french but you can understand the message:
Les paquets suivants contiennent des dépendances non satisfaites :
node-jssip : Dépend: node-websocket mais ne sera pas installé
              Dépend: libjs-jssip (= 0.6.34-5) mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

**Comment by NoahDragon** [comment]
This should relate to nodejs distributions. Please refer the installation page on nodejs.
