### ISSUE TITLE
`generate` fails to update logo image with same name

### ISSUE THREAD

**Issue by finetype** [hexojs/hexo#3067]
## Environment Info

Node version(`node -v`): 7.8.0

Your site `_config.yml` (Optional): code.blog.kylebaker.io

Your theme `_config.yml` (Optional): cactus

Hexo and Plugin version(`npm ls --depth 0`): hexo-cli: 1.1.0, hexo 3.6.0

## BUG

 1. Description: 
Problem with logo images when using `generate`, and probably other images
 2. Reproduce:
Go in to theme folder. rename "logo.png" to "default_logo.png". paste new image. rename to "logo.png".
Locally, live served blog will show the new logo.
run `hexo generate`
public folder will (or may?) still feature old "logo.png" file.
I imagine this is because of some efficiency that doesn't want to update all images every time, and assumes same name = same image. Something like size, or last modified, should also be checked, as opposed to relying on name.

**Comment by finetype** [comment]
I should mention: I resolved this by just changing the logo's name and changing what pointed to it in the config, though I imagine I could also have just deleted 'logo.png' in the public folder forcing it to re-draw a new copy of the image, which would now be the correct one.

**Comment by ertrzyiks** [comment]
I had similar experience with images replacement and what helped me is:
```
hexo clean
```

It removes cache and all generate files, so next `generate` would render your fresh image. Your idea of
> have just deleted 'logo.png' in the public folder
could also work in this case. My blog is small, so fresh generation is super fast for me, that's why I use `clean`.

**Comment by JLHwung** [comment]
The images/fonts should not change often once they are set and that is why it is called static assets. hexo does not track the content hash of the static assets for performance and I/O, you have to use `hexo clean` to remove the public files if you edit the static assets.

**Comment by finetype** [comment]
Hmm. I personally think of this as faulty design.. `hexo generate` only renders assets once, but then never updates them? It's pretty unintuitive behavior, imho. I understand it makes it faster to not track them, but surely conditional diffing could be used to decide whether to re-render any/all assets or not. Couldn't last-modified dates be checked? Then, perhaps, a question could be asked?

If not, maybe something like "generate-full" and "generate-fast" could be used? (as concepts, not saying use those particular long examples per se.)

It's not a dealbreaker, and I'm not a contributor so I won't tell you guys how to design your app, but as a user I just find this to be expectation-breaking. Worst case, I think a couple seconds of rendering time isn't really a big deal compared to silent unintuitive failures like this.
