### ISSUE TITLE
Split categories?

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#3068]
Hi all,

I was wondering if it was possible to split categories? I have a blog and have the following in my .md file:
`category: - [Shoes, Puma]`

Is it possible to output the first category: Shoes in one column and then have Puma in a second column in my HTML? Because if I list categories I get them all mixed up... I hope I made sense...

Thanks in advance.

**Comment by tcrowe** [comment]
Hello @ntot  👋 

We were recently talking about that. Check these:

https://github.com/hexojs/hexo/issues/3050
https://github.com/hexojs/hexo/issues/3060

Also the correct property is `categories` https://github.com/hexojs/hexo/issues/3060

Syntax in the md front-matter:

```yml
categories:
- Sports
- Baseball
tags:
- Injury
- Fight
- Shocking
```

**Comment by ntot** [comment]
Thank you @tcrowe I will follow that discussion :) and see where it leads.
