### ISSUE TITLE
怎么更新hexo的版本？我想升级到2.1

### ISSUE THREAD

**Issue by arthurwoo** [hexojs/hexo#307]
还是npm安装吗？

**Comment by tufu9441** [comment]
我想从3.0升级到3.0.1(mac上使用)，能否指导一下具体的更新版本的操作？

**Comment by leesei** [comment]
@tufu9441 在你有`package.json` 的目錄`npm update` 就可以了
`npm ls --depth=0` 可以檢查dependency 的版本號
