### ISSUE TITLE
How to use fragment_cache correctly?

### ISSUE THREAD

**Issue by ntot** [hexojs/hexo#3071]
Hi all,

My site is growing in regards to post amount so wanted to keep things as fast as possible when it comes to generating my site. I was looking at `fragment_cache`  but the documentation left me a bit lost. I have around 12 includes for my site, how can I made these render quicker? 

Can I just add: `, {}, {cache: true}` after each partial include like this? `<%- partial('_partial/sidebar', {}, {cache: true}) %>` and Hexo will know to cache these includes?

Or do I need to add this to each HTML include?
`<%- fragment_cache('header', function(){  return '<header></header>';}) %>`

Sorry for all the questions... :D and thanks for the help!

**Comment by NoahDragon** [comment]
I know the following syntax should work:
```
<%- fragment_cache('header', function(){ 
                                                                    return partial('_partial/header');
                                                                }) %>
```

**Comment by ntot** [comment]
Thanks @NoahDragon, do I need to have `header` before the function? Can I have it like this:
`<%- fragment_cache(function(){
            return partial('test');
          }) %>`

I wanted to add fragment_cache to all my includes to make the site as optimal as possible.

**Comment by NoahDragon** [comment]
You do need the `header` before the function. It is the cache ID and should be unique.

**Comment by ntot** [comment]
thanks for the reply and explanation @NoahDragon appreciate the help :)
