### ISSUE TITLE
Images with the same name do not refresh if you replace the image

### ISSUE THREAD

**Issue by alanosman** [hexojs/hexo#3074]
Hi, how can I force a Hexo generated page to pick up a newer image without having to change the image name itself.  I find this frustrating especially when I am developing a page with content that includes a lot of revisions to images (like screen shots of GIF previews).

For example, in my markdown doc I have this:
```
![Add user button](add-user-button.png)
```

If I replace that file with an update, I see the old version when I refresh.

I have tried using `hexo clean` but that does not resolve this issue.

Thanks.

**Comment by NoahDragon** [comment]
The browsers also cache the images. Have you tried to clean the browser caches?

**Comment by alanosman** [comment]
@NoahDragon we can't rely on users clearing their cache.  Is there another way to have Hexo force random image names when it generates the output?
