### ISSUE TITLE
Workflow Question

### ISSUE THREAD

**Issue by kiarafrobles** [hexojs/hexo#3075]
## Workflow Question

Because `hexo depoy` uses the master branch to push the public version/directory of the website changes online, the online master branch does not have a full or complete copy of everything I need to run my site from scratch. If I were to say, lose my machine, I only have a compiled master directly to pull from.

I use a separate branch to keep the full version of my website hosted on the repo, but git or GitHub doesn't seem to recognize my `themes` directory. Instead, it shows it empty. 

There's not git ignore file, but I can't figure out whats causing git to ignore the themes directory. Any ideas? Or better ways to manage a workflow between local and hosted versions of hexo.

**Comment by NoahDragon** [comment]
You could take a look the workflow for the [Hexo website](https://hexo.io). We put the source code in https://github.com/hexojs/site and the deploy it to https://github.com/hexojs/hexojs.github.io .

There is also another way that using one repo, but store the source code and deployment into different branch. You could take a look at my site as an example. https://github.com/NoahDragon/en In my case, I use master as source code, and deployed to gh-pages branch.
