### ISSUE TITLE
about all site in cdn

### ISSUE THREAD

**Issue by lluxury** [hexojs/hexo#3076]
我把hexo生成的全站(全部文件)放在了cdn上面,然后发现更新后不能第一时间看到新的页面
cdn的服务商提供了刷新接口,请问刷新哪些文件可以第一时间看到首页的更新
目前只设了根目录下的index.html,无效.

我知道不应该全站放在cdn上面,但我没有自己的服务器,抱歉.

**Comment by NoahDragon** [comment]
这个问题超出了Hexo能解决的范围。建议咨询CDN的提供商。

**Comment by lluxury** [comment]
我的问题是,刷新哪些文件可以看到首页,需要一个文件 list
