### ISSUE TITLE
Generate for production should NOT includes draft assets

### ISSUE THREAD

**Issue by vkyip** [hexojs/hexo#3077]
Hi there, 

When I generate to a production environment with render_draft: false, no drafts were generated but their asset folders are always generated. How do I disable that? Thanks !

**Comment by seff** [comment]
It seems that this bug can be fixed by filtering out the file which locate in _drafts directory. https://github.com/hexojs/hexo/blob/30fcc4f3cc372d25b1870b28b9b715263e621552/lib/plugins/console/generate.js#L130

**Comment by vkyip** [comment]
Thanks seff. I do not know yet how to solve this, so any help would be much appreciated!

**Comment by seff** [comment]
Check this PR

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo/pull/3489
