### ISSUE TITLE
hexo init [folder] got error

### ISSUE THREAD

**Issue by nemo20121221** [hexojs/hexo#3078]
while I try "hexo init blog" command,
I got this error:
![image](https://user-images.githubusercontent.com/32233757/37646318-4b159120-2c64-11e8-9ac5-1185f40daea7.png)
what might be the problem?
and how can I solve it?
OS: centOS6
regards!

**Comment by nemo20121221** [comment]
btw
hexo --version
hexo --help

got the same problem

am I not install it properly?

**Comment by NoahDragon** [comment]
Which node version on your system?

**Comment by nemo20121221** [comment]
problem solved after update node version to V 8.10.0 !
using yum to install node and got a very old version V 0.10.48
@NoahDragon thanks for your time!
