### ISSUE TITLE
DeprecationWarning: fs.SyncWriteStream is deprecated.

### ISSUE THREAD

**Issue by ZrbJava** [hexojs/hexo#3087]

**Comment by ZrbJava** [comment]
这个问题怎么解决

**Comment by ZrbJava** [comment]
把之前的copy下来之后cnpm i 安装依赖之后，hexo s 就报这个错了

**Comment by ZrbJava** [comment]
将之前node_modules删除之后，在cnpm i 安装依赖，之后hexo s 就报 DeprecationWarning: fs.SyncWriteStream is deprecated错，cnpm i hexo-fs --save之后也无效

**Comment by xiazeyu** [comment]
@ZrbJava 
您可以用`npm-check`检查一下，看起来是某些插件依赖没有更新
