### ISSUE TITLE
* in the inline code block cannot be parsed correctly, When * * and ` ` is used together.

### ISSUE THREAD

**Issue by billxc** [hexojs/hexo#3089]
## Environment Info

Node version(`node -v`):
v7.6.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

The default landscape theme

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.6.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-json-content@3.0.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For BUG
![image](https://user-images.githubusercontent.com/5867141/37860891-f3010cd6-2f69-11e8-93e0-51cb3ea39837.png)
![image](https://user-images.githubusercontent.com/5867141/37860893-fa23b5a4-2f69-11e8-8560-84dde56fe4b3.png)
As shown above, the 3 entries all used the * * and \` \` style, and the first two entries are parsed correctly. But in the 3rd entry, there is a * in the code block, and the content is not parsed correctly.

**Comment by JLHwung** [comment]
You can use
```
<i>`Logger*`</i>
```
to workaround.

As seen on this [link](https://marked.js.org/demo/?text=*%60Logger%60*%0A%0A*%60Logger*%60*%0A%0A%3Ci%3E%60Logger*%60%3C%2Fi%3E), it is not a bug of hexo, but a bug in the `marked` renderer. Please raise an issue at https://github.com/markedjs/marked.
