### ISSUE TITLE
请问如何在分类下设置多层级的分类项？

### ISSUE THREAD

**Issue by wdyh01** [hexojs/hexo#3093]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by sesgigikimo** [comment]
I'm looking for this feature also.

**Comment by carl0schen** [comment]
Like this?
https://github.com/hexojs/hexo/issues/848

**Comment by sesgigikimo** [comment]
Thanks, I've enable this feature on my web.
