### ISSUE TITLE
Missing .md files,How do I recover my site?

### ISSUE THREAD

**Issue by s40523119** [hexojs/hexo#3096]
## Environment Info

Node version(`node -v`): 5.6.0

## For question

My hexo files are in my USB.But it is gone......
So, I only have old version hexo file in my disk.
But there is only old .md, I want to recover my .md files ,How do I do?

**Comment by JLHwung** [comment]
There is no way you can recover files on a physically gone USB Flash Drive.

It is sad but please try cloud based storage, i.e. iCloud for your blog sources (.md).
