### ISSUE TITLE
hexo-deployer-git 无法安装

### ISSUE THREAD

**Issue by vipzrx** [hexojs/hexo#3098]
https://github.com/hexojs/hexo-deployer-git/issues/92

C:\bg\test>npm i -S hexo-deployer-git
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

+ hexo-deployer-git@0.3.1
updated 1 package in 15.963s

C:\bg\test>npm list -g --depth 0
C:\Users\kk\AppData\Roaming\npm
+-- cnpm@5.2.0
`-- hexo-cli@1.1.0
这里没有显示 hexo-deployer-git 是没有安装上的意思吗?

C:\bg\test>

## Environment Info

Node version(`node -v`):
C:\bg\test>node -v
v8.10.0

Your site `_config.yml` (Optional):
```
C:\bg\test>tail _config.yml
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:git
  repo:gh:vipzrx/vipzrx.github.io.git
  branch:master
```

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
C:\Users\kk\AppData\Roaming\npm
+-- cnpm@5.2.0
`-- hexo-cli@1.1.0

**Comment by JLHwung** [comment]
`npm list -g` 显示的是全局的 node_modules。

使用以下命令显示 `C:\bg\test` 项目的 node_modules
```bash
cd C:\bg\test
npm list --depth 0
```

**Comment by vipzrx** [comment]
`

C:\t12>npm list --depth 0
hexo-site@0.0.0 C:\t12
+-- hexo@3.6.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2


C:\t12>
node_modules  package.json
`

**Comment by JLHwung** [comment]
```
+-- hexo-deployer-git@0.3.1
```

hexo-deployer-git 已经安装。

**Comment by vipzrx** [comment]
@JLHwung 
https://github.com/hexojs/hexo-deployer-git/issues/92

给 hexo-deployer-git 包issue 挺长时间,没有回复.别人也复现了这个问题.我刚接触hexo, 请先定位下,是我设置问题,还是这个 hexo-deployer-git 插件有问题
谢谢

**Comment by vipzrx** [comment]
我在本地是可以看到生成的站点的
![20180329141629](https://user-images.githubusercontent.com/5094958/38073047-dbc0ff36-335b-11e8-93dc-ef85a5ae51f6.png)

**Comment by vipzrx** [comment]
我开始以为是windows下nodejs的问题,又在virtualbox中安装了debian 测试, 同样是不能部署到github中

网上找到的教程,是早期的. 我也按照hexo-deployer-git readme中的试了,也是不行

我推断是插件还没有和github通讯上,因为没有看到返回github的提示信息

**Comment by JLHwung** [comment]
Closed as duplicates of hexojs/hexo-deployer-git#92.

**Comment by vipzrx** [comment]
kk@H4:~/te$ tree -L 1
@JLHwung 
.
├── _config.yml
├── db.json
├── node_modules
├── package.json
├── package-lock.json
├── public
├── scaffolds
├── source
└── themes

5 directories, 4 files
kk@H4:~/te$

执行 hexo d 之后
也没有生成 .deploy_git 目录

**Comment by xiaotown123** [comment]
@vipzrx 这问题咋样了

**Comment by sunu11** [comment]
我的天，我昨晚上也遇到了，贼难受。。。。
