### ISSUE TITLE
Is it possible that creating the categories named by folder's name under the _post?

### ISSUE THREAD

**Issue by yehuohan** [hexojs/hexo#3099]
## For feature request
Is it possible that creating the categories named by folder's name under the _post?
That feature will make it is easier to create and change category.

**Comment by JLHwung** [comment]
Binding categories to the folder structures is strongly opinionated, thus hexo will not support this feature. If you are interested, you can fork hexo and change the category logic.

I will close the issue for now, feel free to reopen it if you would like discuss on further details.

**Comment by xu-song** [comment]
This feature has been implemented in #3100

**Comment by yehuohan** [comment]
@xu-song 嗯好的，谢谢~~~
