### ISSUE TITLE
[feature request] category auto-generation from path

### ISSUE THREAD

**Issue by xu-song** [hexojs/hexo#3100]
## Feature Request

Is there a plugin which generates `category` automatically from path/directory?

Here is an example. For a post  `source/_post/web/framework/hexo.md`,  I want to generate the following category automatically
```yml
categories:
  - web
  - framework
```

Both directory and category are hierarchical structure. It would be more convenient to define directory than category.

**Comment by xu-song** [comment]
If there is no existing one, I have implement a plugin.

https://github.com/xu-song/hexo-dir2category

It would be very appreciated if you give me some feedback.

**Comment by JLHwung** [comment]
Hexo will not support category folder structure binding in the near future, see https://github.com/hexojs/hexo/issues/3099#issuecomment-377131763.

> https://github.com/xu-song/hexo-auto-category

Great plugin! We recommend you to add the plugin to https://github.com/hexojs/site.

**Comment by xu-song** [comment]
As you say,
> Binding categories to the folder structures is user opinionated.

So there is no need to integrated this plugin to hexo for all users. It is designed for users who favor these features.
