### ISSUE TITLE
Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by Aquarian-Age** [hexojs/hexo#3103]
Cannot read property 'enable' of undefined
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:128:25)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:149:10)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:155:10)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:185:10)
    at returnedFn (/home/xuan/blog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/xuan/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/xuan/blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:30:17)
    at returnedFn (/home/xuan/blog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/xuan/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/xuan/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/xuan/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/xuan/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/xuan/blog/node_modules/bluebird/js/release/async.js:17:14)
---------------------------------------------------
hexo g -debug 显示如下

12:34:18.688 DEBUG Hexo version: 3.5.0
12:34:18.692 DEBUG Working directory: ~/blog/
12:34:18.800 DEBUG Config loaded: ~/blog/_config.yml
12:34:18.835 DEBUG Plugin loaded: hexo-deployer-git
12:34:18.854 DEBUG Plugin loaded: hexo-deployer-heroku
12:34:18.859 DEBUG Plugin loaded: hexo-deployer-rsync
12:34:18.862 DEBUG Plugin loaded: hexo-generator-archive
12:34:18.863 DEBUG Plugin loaded: hexo-generator-category
12:34:18.867 DEBUG Plugin loaded: hexo-generator-feed
12:34:18.867 DEBUG Plugin loaded: hexo-generator-index
12:34:18.868 DEBUG Plugin loaded: hexo-generator-tag
12:34:18.871 DEBUG Plugin loaded: hexo-renderer-ejs
12:34:18.878 DEBUG Plugin loaded: hexo-renderer-marked
12:34:19.145 DEBUG Plugin loaded: hexo-renderer-pug
12:34:19.195 DEBUG Plugin loaded: hexo-renderer-sass
12:34:19.199 DEBUG Plugin loaded: hexo-renderer-stylus
12:34:19.288 DEBUG Plugin loaded: hexo-server
12:34:19.294 DEBUG Script loaded: themes/cafe/scripts/fancybox.js
12:34:19.295 DEBUG Script loaded: themes/cafe/scripts/extend.generator.js
12:34:19.297 DEBUG Loading database.
12:34:19.473 INFO  Start processing
12:34:19.655 DEBUG Processed: _posts/KDE.md
12:34:19.655 DEBUG Processed: _posts/Linux-power-manager-laptop-mode-tools.md
12:34:19.655 DEBUG Processed: _posts/about.md
12:34:19.655 DEBUG Processed: _posts/change-netease-cloud-music-CachedSongs-dir.md
12:34:19.655 DEBUG Processed: _posts/chroot-openSUSE.md
12:34:19.655 DEBUG Processed: _posts/git远程提交错误的解决方法-Linux系统-The-requested-URL-returned-error-403.md
12:34:19.655 DEBUG Processed: _posts/liangzi测试博客.md
12:34:19.656 DEBUG Processed: _posts/linux的gpasswd管理用户属组以及相关目录下软件更新权限问题.md
12:34:19.656 DEBUG Processed: _posts/openSUSE-42-3-实现IP转发且重启不失效.md
12:34:19.658 DEBUG Processed: _posts/openSUSE-42-3-编译gcc4-9-4-安装flameshot.md
12:34:19.659 DEBUG Processed: _posts/proxychain4去插件全局代理浏览器上网.md
12:34:19.659 DEBUG Processed: _posts/share.md
12:34:19.659 DEBUG Processed: _posts/上证指数.md
12:34:19.659 DEBUG Processed: _posts/小语.md
12:34:19.659 DEBUG Processed: _posts/年近四十.md
12:34:19.659 DEBUG Processed: _posts/昨日小语.md
12:34:19.664 DEBUG Processed: source/favicon.ico
12:34:19.740 DEBUG Processed: source/css/style.styl
12:34:19.741 DEBUG Processed: source/fancybox/blank.gif
12:34:19.742 DEBUG Processed: source/fancybox/fancybox_loading.gif
12:34:19.742 DEBUG Processed: source/fancybox/fancybox_loading@2x.gif
12:34:19.745 DEBUG Processed: source/fancybox/fancybox_overlay.png
12:34:19.748 DEBUG Processed: source/fancybox/fancybox_sprite.png
12:34:19.748 DEBUG Processed: source/fancybox/fancybox_sprite@2x.png
12:34:19.748 DEBUG Processed: source/fancybox/jquery.fancybox.css
12:34:19.749 DEBUG Processed: source/fancybox/jquery.fancybox.js
12:34:19.750 DEBUG Processed: source/fancybox/jquery.fancybox.pack.js
12:34:19.750 DEBUG Processed: source/images/fly-to-top.png
12:34:19.750 DEBUG Processed: source/js/elevator.js
12:34:19.751 DEBUG Processed: source/js/is.js
12:34:19.751 DEBUG Processed: source/js/posts.js
12:34:19.751 DEBUG Processed: source/js/script.js
12:34:19.763 DEBUG Processed: source/duoshuo/embed.js
12:34:19.763 DEBUG Processed: source/jquery/jquery.min.js
12:34:19.794 DEBUG Processed: layout/archive.ejs
12:34:19.794 DEBUG Processed: layout/category.ejs
12:34:19.794 DEBUG Processed: layout/index.ejs
12:34:19.794 DEBUG Processed: layout/layout.ejs
12:34:19.795 DEBUG Processed: layout/page.ejs
12:34:19.795 DEBUG Processed: layout/post.ejs
12:34:19.795 DEBUG Processed: layout/tag.ejs
12:34:19.810 DEBUG Processed: languages/default.yml
12:34:19.810 DEBUG Processed: languages/en.yml
12:34:19.810 DEBUG Processed: languages/nl.yml
12:34:19.811 DEBUG Processed: languages/no.yml
12:34:19.811 DEBUG Processed: languages/ru.yml
12:34:19.811 DEBUG Processed: languages/zh-CN.yml
12:34:19.811 DEBUG Processed: languages/zh-TW.yml
12:34:19.812 DEBUG Processed: source/fancybox/helpers/fancybox_buttons.png
12:34:19.812 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-buttons.css
12:34:19.812 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-buttons.js
12:34:19.813 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-media.js
12:34:19.813 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-thumbs.css
12:34:19.813 DEBUG Processed: source/fancybox/helpers/jquery.fancybox-thumbs.js
12:34:19.813 DEBUG Processed: source/themes/screenshots/Cafe.png
12:34:19.818 DEBUG Processed: layout/_scripts/index.ejs
12:34:19.830 DEBUG Processed: source/css/fonts/fontawesome-webfont.woff
12:34:19.830 DEBUG Processed: source/css/fonts/fontawesome-webfont.woff2
12:34:19.869 DEBUG Processed: layout/_partial/after-footer.ejs
12:34:19.869 DEBUG Processed: layout/_partial/archive.ejs
12:34:19.869 DEBUG Processed: layout/_partial/archive-post.ejs
12:34:19.869 DEBUG Processed: layout/_partial/article.ejs
12:34:19.869 DEBUG Processed: layout/_partial/comments.ejs
12:34:19.869 DEBUG Processed: layout/_partial/footer.ejs
12:34:19.870 DEBUG Processed: layout/_partial/google-analytics.ejs
12:34:19.870 DEBUG Processed: layout/_partial/head.ejs
12:34:19.870 DEBUG Processed: layout/_partial/header.ejs
12:34:19.870 DEBUG Processed: layout/_partial/mobile-nav.ejs
12:34:19.872 DEBUG Processed: layout/_partial/random_posts.ejs
12:34:19.872 DEBUG Processed: layout/_partial/widget.ejs
12:34:19.872 DEBUG Processed: layout/_partial/sidebar.ejs
12:34:19.872 DEBUG Processed: layout/_third-part/index.ejs
12:34:19.872 DEBUG Processed: layout/_widget/archive.ejs
12:34:19.872 DEBUG Processed: layout/_widget/category.ejs
12:34:19.872 DEBUG Processed: layout/_widget/friendly_link.ejs
12:34:19.872 DEBUG Processed: layout/_widget/hot_comment_posts.ejs
12:34:19.873 DEBUG Processed: layout/_widget/lastest_comments.ejs
12:34:19.873 DEBUG Processed: layout/_widget/post_content.ejs
12:34:19.874 DEBUG Processed: layout/_widget/recent_posts.ejs
12:34:19.874 DEBUG Processed: layout/_widget/social.ejs
12:34:19.874 DEBUG Processed: layout/_widget/tag.ejs
12:34:19.875 DEBUG Processed: layout/_widget/tagcloud.ejs
12:34:19.875 DEBUG Processed: layout/_widget/wechat.ejs
12:34:19.875 DEBUG Processed: layout/partials/back2top.ejs
12:34:19.875 DEBUG Processed: layout/partials/hot-comment-posts.ejs
12:34:19.876 DEBUG Processed: layout/partials/lastest-comments.ejs
12:34:19.876 DEBUG Processed: layout/partials/pagination.ejs
12:34:19.876 DEBUG Processed: layout/partials/recent-posts.ejs
12:34:19.879 DEBUG Processed: source/css/fonts/FontAwesome.otf
12:34:19.880 DEBUG Processed: source/css/fonts/fontawesome-webfont.eot
12:34:19.880 DEBUG Processed: source/css/fonts/fontawesome-webfont.ttf
12:34:19.882 DEBUG Processed: source/css/images/banner.jpg
12:34:19.895 DEBUG Processed: layout/_partial/post/.directory
12:34:19.895 DEBUG Processed: layout/_partial/post/category.ejs
12:34:19.895 DEBUG Processed: layout/_partial/post/date.ejs
12:34:19.895 DEBUG Processed: layout/_partial/post/duoshuo.ejs
12:34:19.895 DEBUG Processed: layout/_partial/post/gallery.ejs
12:34:19.895 DEBUG Processed: layout/_partial/post/gitment.ejs
12:34:19.895 DEBUG Processed: layout/_partial/post/nav.ejs
12:34:19.896 DEBUG Processed: layout/_partial/post/tag.ejs
12:34:19.896 DEBUG Processed: layout/_partial/post/title.ejs
12:34:19.896 DEBUG Processed: layout/_third-part/comments/changyan.ejs
12:34:19.896 DEBUG Processed: layout/_third-part/comments/disqus.ejs
12:34:19.896 DEBUG Processed: layout/_third-part/comments/duoshuo.ejs
12:34:19.896 DEBUG Processed: layout/_third-part/comments/gitment.ejs
12:34:19.896 DEBUG Processed: layout/_third-part/comments/gentie.ejs
12:34:19.896 DEBUG Processed: layout/_third-part/comments/index.ejs
12:34:19.897 DEBUG Processed: layout/_third-part/comments/youyan.ejs
12:34:19.897 DEBUG Processed: layout/_third-part/mathjax/index.ejs
12:34:19.900 DEBUG Processed: source/css/fonts/fontawesome-webfont.svg
12:34:20.051 DEBUG Generator: page
12:34:20.051 DEBUG Generator: post
12:34:20.052 DEBUG Generator: archive
12:34:20.052 DEBUG Generator: category
12:34:20.052 DEBUG Generator: feed
12:34:20.052 DEBUG Generator: index
12:34:20.052 DEBUG Generator: tag
12:34:20.054 DEBUG Generator: asset
12:34:20.054 DEBUG Generator: random_post
12:34:20.086 INFO  Files loaded in 789 ms
12:34:20.104 DEBUG Rendering post: 2018/03/27/openSUSE-42-3-编译gcc4-9-4-安装flameshot/index.html
12:34:20.313 DEBUG Rendering post: 2018/03/26/openSUSE-42-3-实现IP转发且重启不失效/index.html
12:34:20.381 DEBUG Rendering post: 2018/03/22/git远程提交错误的解决方法-Linux系统-The-requested-URL-returned-error-403/index.html
12:34:20.447 DEBUG Rendering post: 2018/03/16/昨日小语/index.html
12:34:20.478 DEBUG Rendering post: 2018/03/14/linux的gpasswd管理用户属组以及相关目录下软件更新权限问题/index.html
12:34:20.494 DEBUG Rendering post: 2018/02/27/share/index.html
12:34:20.510 DEBUG Rendering post: 2018/02/23/KDE/index.html
12:34:20.525 DEBUG Rendering post: 2018/02/22/change-netease-cloud-music-CachedSongs-dir/index.html
12:34:20.550 DEBUG Rendering post: 2018/02/22/上证指数/index.html
12:34:20.562 DEBUG Rendering post: 2018/02/16/chroot-openSUSE/index.html
12:34:20.578 DEBUG Rendering post: 2018/02/15/小语/index.html
12:34:20.593 DEBUG Rendering post: 2018/02/14/Linux-power-manager-laptop-mode-tools/index.html
12:34:20.623 DEBUG Rendering post: 2018/02/03/年近四十/index.html
12:34:20.637 DEBUG Rendering post: 2018/01/31/about/index.html
12:34:20.651 DEBUG Rendering post: 2018/01/27/proxychain4去插件全局代理浏览器上网/index.html
12:34:20.663 DEBUG Rendering post: 2018/01/25/liangzi测试博客/index.html
12:34:20.681 DEBUG Rendering archive: archives/index.html
12:34:20.722 DEBUG Rendering archive: archives/page/2/index.html
12:34:20.844 DEBUG Rendering archive: archives/2018/index.html
12:34:20.960 DEBUG Rendering archive: archives/2018/page/2/index.html
12:34:20.987 DEBUG Rendering archive: archives/2018/01/index.html
12:34:21.000 DEBUG Rendering archive: archives/2018/02/index.html
12:34:21.037 DEBUG Rendering archive: archives/2018/03/index.html
12:34:21.058 DEBUG Rendering index: index.html
12:34:21.104 DEBUG Rendering index: page/2/index.html
12:34:21.146 DEBUG Rendering index: page/3/index.html
12:34:21.159 DEBUG Rendering tag: tags/openSUSE/index.html
12:34:21.190 DEBUG Rendering tag: tags/硬盘/index.html
12:34:21.201 DEBUG Rendering tag: tags/vpn/index.html
12:34:21.210 DEBUG Rendering tag: tags/网易云音乐/index.html
12:34:21.219 DEBUG Rendering tag: tags/grub/index.html
12:34:21.229 DEBUG Rendering tag: tags/git/index.html
12:34:21.242 DEBUG Rendering tag: tags/sysctl/index.html
12:34:21.252 DEBUG Rendering tag: tags/IP转发/index.html
12:34:21.260 DEBUG Rendering tag: tags/GCC/index.html
12:34:21.268 DEBUG Rendering tag: tags/分享/index.html
12:34:21.276 DEBUG Rendering tag: tags/发现/index.html
12:34:21.285 DEBUG Rendering tag: tags/上证指数/index.html
12:34:21.292 DEBUG Rendering tag: tags/资本投机/index.html
12:34:21.300 DEBUG Rendering tag: tags/小语/index.html
12:34:21.310 DEBUG Rendering tag: tags/闲言碎语/index.html
12:34:21.541 INFO  0 files generated in 1.45 s
12:34:21.574 DEBUG Database saved
-------------------------------------------
请问我改怎么解决呢 谢谢

**Comment by JLHwung** [comment]
Please upgrade `hexo-renderer-ejs` to the latest version and check if can be reproduced:

```
cd ~/blog
npm update hexo-renderer-ejs
```

**Comment by Aquarian-Age** [comment]
@JLHwung 按照你说的方法升级了hexo-renderer-ejs 但是问题依旧 下面是详细信息
---------------------------------------------------------------------------------------------------
六 3月 31|21:53|0:>sudo tune2fs -l $(df -h / |(read; awk '{print $1; exit}'))
tune2fs 1.42.11 (09-Jul-2014)
Filesystem volume name:   <none>
Last mounted on:          /
Filesystem UUID:          2cc2fc0f-1421-456c-8255-4344598a2c5f
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent flex_bg sparse_super large_file huge_file uninit_bg dir_nlink extra_isize
Filesystem flags:         signed_directory_hash 
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              3260416
Block count:              13026048
Reserved block count:     260520
Free blocks:              7454061
Free inodes:              2561196
First block:              0
Block size:               4096
Fragment size:            4096
Reserved GDT blocks:      1020
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8192
Inode blocks per group:   512
Flex block group size:    16
Filesystem created:       Mon Dec 19 07:08:20 2016
Last mount time:          Sat Mar 31 15:39:41 2018
Last write time:          Sat Mar 31 15:39:40 2018
Mount count:              235
Maximum mount count:      -1
Last checked:             Wed Oct 18 13:54:17 2017
Check interval:           0 (<none>)
Lifetime writes:          285 GB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:               256
Required extra isize:     28
Desired extra isize:      28
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      f0a6f456-d819-4fa7-bb05-d82773910fa1
Journal backup:           inode blocks

**Comment by Aquarian-Age** [comment]
我cd ~/blog hexo server发现无法打开网页 下面是详细信息
--------------------------------------------------------------------------------------------------
NFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: /home/xuan/blog/themes/cafe/layout/layout.ejs:14
    12|     <%- partial('_partial/mobile-nav', null, {cache: !config.relative_link}) %>                                   
    13|     <%- partial('partials/back2top', {}) %>                                                                       
 >> 14|     <%- partial('_partial/after-footer') %>                                                                       
    15|   </div>                                                                                                          
    16| </body>                                                                                                           
    17| </html>                                                                                                           

/home/xuan/blog/themes/cafe/layout/_partial/after-footer.ejs:1                                                            
 >> 1| <% include ../_third-part/index.ejs%>                                                                              
    2|  <%- js('js/is.js') %>                                                                                             
    3|                                                                                                                    
    4| <% if (theme.fancybox){ %>                                                                                         

/home/xuan/blog/themes/cafe/layout/_third-part/index.ejs:1                                                                
 >> 1| <% include ./comments/index.ejs %>                                                                                 
    2| <% include ./mathjax/index.ejs %>                                                                                  

/home/xuan/blog/themes/cafe/layout/_third-part/comments/index.ejs:6                                                       
    4| <% include ./youyan.ejs %>                                                                                         
    5|                                                                                       
 >> 6| <% include ./gitment.ejs %>                                                                                        
    7|                                                                                         
    8|                                                                                                                    

/home/xuan/blog/themes/cafe/layout/_third-part/comments/gitment.ejs:2                                                     
    1|                                                                                       
 >> 2| <% if (theme.gitment.enable){ %>                                                                                   
    3|   <link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">                                 
    4|   <script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script> 
    5|   <script>

Cannot read property 'enable' of undefined
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:128:25)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:149:10)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:155:10)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:185:10)
    at returnedFn (/home/xuan/blog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/xuan/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/xuan/blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/xuan/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:30:17)
    at returnedFn (/home/xuan/blog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/xuan/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/xuan/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/xuan/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/xuan/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/xuan/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/xuan/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/xuan/blog/node_modules/bluebird/js/release/async.js:17:14)

**Comment by Aquarian-Age** [comment]
我修改了系统ssh默认端口 是不是和这个有关系呢？
另外在$HOME/.ssh/里面添加了如下文件和内容
---------------------------------------------------------------------------
日 4月 01|07:51|0:>cat ~/.ssh/config 
# ssh to github.com:Aquarian-Age
Host github.com
User xiaoyaoke7630@gmail.com
Hostname ssh.github.com
Port 443
PreferredAuthentications publickey
IdentityFile ~/.ssh/id_rsa

# first_rsa 
Host github.com
User xiaoyaoke7630@sina.com
Hostname ssh.github.com
Port 443
PreferredAuthentications publickey
IdentityFile ~/.ssh/first_rsa

**Comment by JLHwung** [comment]
Here should be the culprit
```
<% if (theme.gitment.enable){ %>
```

The `hexo-theme-cafe` does not guard against undefined `theme.gitment`, thus error is thrown during rendering phrase.

You can add the following lines to `theme/cafe/_config.yml` as a workaround
```
gitment:
  enable: false
```

As this is not a hexo bug, I will close the issue now but we strongly recommend you to raise an issue at https://github.com/giscafer/hexo-theme-cafe. The theme should be expected to work when `theme.gitment` is `undefined`.
