### ISSUE TITLE
Markdown标题不被渲染

### ISSUE THREAD

**Issue by seff** [hexojs/hexo#3104]
## 环境

hexo: 3.7.0
hexo-cli: 1.1.0
os: Darwin 17.5.0 darwin x64
http_parser: 2.7.0
node: 9.9.0
v8: 6.2.414.46-node.22
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c

## BUG

当在段落的开始处插入某个标记（Tag，包括 Hexo 自带的标记）时，Markdown 中的标题（H1~H6）不会被渲染，HTML文件直接输出了原始 Markdown 内容。打开 `--debug` 选项时，不论是在渲染过程中还是访问页面时，都没有任何错误或警告信息输出。

没有发现其它 Markdown 标记不被渲染的情况，已排除主题干扰的原因（使用默认主题问题依旧）。

**Comment by JLHwung** [comment]
Could you give a reproducing markdown snippets?

**Comment by seff** [comment]
[test.txt](https://github.com/hexojs/hexo/files/1866040/test.txt)

已经找到导致问题的原因：当在段首插入一个标记，且文章后面的部分有入手代码块，那么在段首标记和代码块之间的 Markdown 标题均不会被渲染。

@JLHwung

**Comment by seff** [comment]
@JLHwung 希望可以修复，谢谢。

**Comment by seff** [comment]
@JLHwung 内嵌的代码（单反引号）不会导致该问题。
