### ISSUE TITLE
Define a new permalink variable

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#3105]
Two questions...

1) Is it possible to define a new `permalink variable`, for example `author`? If yes, where, how???

2) The following is my set up for blogposts:
/source/_posts/china/post1
/source/_posts/china/post2
/source/_posts/china/post3
/source/_posts/japan/post20
/source/_posts/japan/post21
/source/_posts/vietnam/post98
/source/_posts/vietnam/post99

The question here is: which `permalink variable` is `china` and `japan` and `vietnam` or how to define these in `permalink config`???

[https://hexo.io/docs/permalinks.html](url)

**Comment by xu-song** [comment]
1. You can define `permlink variable` in https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/post_permalink.js#L11 .

2. `title` is the path of file. you can use `title`

**Comment by xu-song** [comment]
@rabas007 
`post_title` is `filename`.
https://hexo.io/docs/permalinks.html
