### ISSUE TITLE
Run javascript code in .md file

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#3120]
I try to run some javascript code (it is an advertisement) inside md file `test-post`.

```
---
layout: post
title: test
description: see if ad runs here
---
Hello world!
{% include partial('advertisements/adv2') %}
Nice advertisement...
```

Then in my `themes/material-flow/layout`... I have this folder:
`advertisements` and inside this folder I have `adv2.ejs` with my javascript code.

It did not work... how to fix this for my purpose?

**Comment by Ashisacat** [comment]
The whole thing is parsed so you won't be able to execute arbitrary code from within a post.

You could, however, amend your theme so that the partial is included within the post?
This is kind of outside of the remit of the core hexo repo though :)
