### ISSUE TITLE
Security dependencies (ejs, marked, uglifyjs, moment)

### ISSUE THREAD

**Issue by connor11528** [hexojs/hexo#3121]
## Environment Info

Node version(`node -v`): v8.3.0

Hexo and Plugin version(`npm ls --depth 0`): 

```
├── hexo@3.7.1
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.1.3
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.1.2
├── hexo-log@0.1.3
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-jade@0.4.1
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-sass@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.1.3
```

## Security

Github is flagging multiple dependencies for security vulnerabilities around DDOS and remote system takeover. Is there a way we can upgrade the dependencies?

Thank you!

![screen shot 2018-04-16 at 6 16 18 am](https://user-images.githubusercontent.com/3578908/38811385-3856a7a6-413e-11e8-9e30-666c2c512edd.png)

**Comment by tcrowe** [comment]
Hi @connor11528 

You can try upgrading all *your* modules to see if that helps. 😅

```sh
npm install --global --no-cache npm-check-updates hexo-cli
ncu -an
npm install
```

Hexo sites run no functionality on the server you deploy to. No DDoS vulnerability is possible from that.

Also, lets say we upgraded them are you sure the newest version isn't flagged as vulnerable too? 😓 

What do you think would be the best solution?

**Comment by Kakise** [comment]
Actually the best solution is, in my point of view, the "if it works, don't touch it". Hexo generates static files so anyone, there is no need to be afraid on vulnerabilities on its dependencies. Just ignore the message with the reason "Vulnerable code is not used" and that's it
