### ISSUE TITLE
求救!!不知為什麼deploy到github pages上後只剩文字，版型主題都不見了><

### ISSUE THREAD

**Issue by pinkpika** [hexojs/hexo#313]
我輸入hexo server
在本機端看網頁是正常，有文字有主題。

但我輸入hexo deploy
上傳到github後
網站就只剩文字了像是css,js失效了一樣
不知該如何解決QQ

_config.yml的設定我是改成

deploy:
  type: github
  repository: https://github.com/我的帳號名/專案名稱.git

對應的網站是
http://我的帳號名.github.io/專案名稱/

**Comment by wadetang** [comment]
能说下怎么设定的吗 我遇到了同样的问题

**Comment by Revetice** [comment]
回樓上, 如果是用gh-page的方式deploy
_config.yml的root要改為你repository的名字
root: /<your_repository>/
