### ISSUE TITLE
YAMLException: the stream contains non-printable characters

### ISSUE THREAD

**Issue by Fantasy9527** [hexojs/hexo#3131]
```
hexo g
```
ERROR Process failed: _posts/Block chain/区块链开发之一切从脚手架truffle开始.md
YAMLException: the stream contains non-printable characters at line 1, column 30:
    title: 区块链开发之一切从脚手架truffle开始
                                 ^
    at generateError (/Users/Fan/workspace/alili.tech/node_modules/_js-yaml@3.11.0@js-yaml/lib/js-yaml/loader.js:165:10)

**Comment by Fantasy9527** [comment]
---
title: 区块链开发之一切从脚手架truffle开始
date: 2018-04-19T19:33:33.000Z
tags: 区块链
---

**Comment by Fantasy9527** [comment]
区块链开发之一切从脚手架truffle开始

**Comment by Fantasy9527** [comment]
莫名其妙的解决了

**Comment by GuoJinyu** [comment]
怎么解决的哥们。。我也遇到了

**Comment by GuoJinyu** [comment]
我也莫名其妙的好了。。

**Comment by GuoJinyu** [comment]
@Fantasy9527 我想我找到原因了，由于vscode的bug，题目里面包含了控制字符导致的。https://github.com/Microsoft/vscode/issues/37114

**Comment by alanamircruz** [comment]
Does somebody fixed this stuff yet ? having the same issue (german speaking region) ?
