### ISSUE TITLE
Do I need a theme to use layouts?

### ISSUE THREAD

**Issue by DougBeney** [hexojs/hexo#3139]
Loving the speed of Hexo! 

As someone that has worked heavily with Jekyll, I like keeping things as simple as possible.

I created a super minimal Hexo setup over here: https://github.com/DougBeney/Bare-Minimum-Hexo-Template

Now, let's say I wanted to add some layouts to that template. Do I absolutely need to setup a theme, or can I create a special layouts folder in the `source/` directory?

**Comment by DougBeney** [comment]
Thanks for the kind response! 

I was not able to get it working by creating `source/theme-doug/layout/layout.ejs`. What happened is that my layout files go rendered as regular pages. Well, I'm using `hexo-renderer-pug` for templates so maybe that is the cause?

Slush looks very cool though! I think I'll give that a shot.

**Comment by tcrowe** [comment]
Ah yes then instead of .ejs you can use .pug for the examples above

**Comment by tcrowe** [comment]
Oh and what I meant by this:

```txt
So you might be able to do:

source/theme-doug/layout/layout.ejs (default)
source/theme-doug/layout/layout1.ejs
source/theme-doug/layout/layout2.ejs
```

Was actually supposed to be something like: `[your site]/themes/[your theme]/layout/`

You get the idea 😅

**Comment by DougBeney** [comment]
Gotcha. Thanks for the help!
