### ISSUE TITLE
Remove `file path` from `:title` `permalink`

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#3140]
In HEXO blog, the permalink `:title` seems to equal `file path` + `filename`. 

So my `_posts` structure is following (with sub-folders `china` and `japan`):

    _posts
        china
            - blogpost-1
            - blogpost-2
            - blogpost-3
        japan
            - post-a
            - post-b
            - post-c

The `permalink` then generates `china/blogpost-1` and `japan-post-c`. My 
`permalink` is defined as `permalink: :title/`.

I need to exclude (eliminate) the `file path` in my `permalink`. And I cannot change my `permalink`, it has to remain `permalink: :title/` (reason is my commenting system requires it this way for unique comments to be posted for unique blogposts). Ofcourse I can stop using `subfolders` but then I have hundreds of posts all together and I cannot make heads or tails out of it anymore. Using `new_post_name` is not an option either (tried that, does not serve my purposes).

Question is how to make `:title` only to be `filename`?
I tried to make changes here (as I guess here lies the solution)... but no luck unfortunately... [/lib/plugins/filter/post_permalink.js][1]

  [1]: https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/post_permalink.js#L11

**Comment by ivan-nginx** [comment]
https://hexo.io/docs/permalinks.html#comment-2657776966

So, in front-matter:
```yml
---
...
permalink: permalink-what-will-appear-in-browser-adress-bar
...
---
```

**Comment by rabas007** [comment]
@ivan-nginx  -  does not work. My comment system does not recognize the `slug`.

**Comment by EqualMa** [comment]
I made a plugin to show permalink as its relative file path:
[hexo-plugin-permalink-pathed-title](https://github.com/EqualMa/hexo-plugin-permalink-pathed-title)
This may solve your issue.

**Comment by skryvets** [comment]
Use `:name` instead of `:title`
