### ISSUE TITLE
Can I do asynchronous processing in after_render?

### ISSUE THREAD

**Issue by maple3142** [hexojs/hexo#3141]
Can I do something is asynchronous in `after_render` hook?
I want to make the following script works without `deasync`.
https://github.com/maple3142/Blog/blob/73332843516f34e2e4a538b936252d54cc4dbbe7/scripts/jax.js

**Comment by stevenjoezhang** [comment]
The answer is yes - you just need to return a Promise object:
https://github.com/stevenjoezhang/hexo-filter-mathjax/blob/master/index.js

**Comment by maple3142** [comment]
@stevenjoezhang Wow, that script is exactly what I want to achieve.
My original workaround: https://github.com/maple3142/Blog/blob/f61b37aeee5421910aaa0a2d9bcef62bf1bc5a61/scripts/jax.js
