### ISSUE TITLE
markdown picture Defect

### ISSUE THREAD

**Issue by yangyunzhao** [hexojs/hexo#3145]
## Environment Info

Node version(`node -v`):V10.0.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 D:\hexo
+-- hexo@3.7.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For feature request

I used Typora which is the best tools for markdown on the windows platform to insert picture.
I just need to drag the picture to Typora，the Typora will **Automatic** generation of code，And Automatically copy files to the same level directory of .md file.
Such as 
```
![hello](assets/hello.png)
```

But I use ``hexo g`` to generate static sites, hexo do not automatic copy of the picture file.
Just as
![image](https://user-images.githubusercontent.com/25679538/39514308-72c236ba-4e29-11e8-8d70-a381eea34e8f.png)
Can you copy it automatically to the corresponding directory?
Thanks a lot!!

**Comment by chen-huaneng** [comment]
> ## Environment Info
> Node version(`node -v`):V10.0.0
> 
> Your site `_config.yml` (Optional):
> 
> Your theme `_config.yml` (Optional):
> 
> Hexo and Plugin version(`npm ls --depth 0`): hexo-site@0.0.0 D:\hexo +-- hexo@3.7.1 +-- hexo-generator-archive@0.1.5 +-- hexo-generator-category@0.1.3 +-- hexo-generator-index@0.2.1 +-- hexo-generator-tag@0.2.0 +-- hexo-renderer-ejs@0.3.1 +-- hexo-renderer-marked@0.3.2 +-- hexo-renderer-stylus@0.3.3 `-- hexo-server@0.2.2
> 
> ## For BUG
> ## For question
> ## For feature request
> I used Typora which is the best tools for markdown on the windows platform to insert picture. I just need to drag the picture to Typora，the Typora will **Automatic** generation of code，And Automatically copy files to the same level directory of .md file. Such as
> 
> ```
> ![hello](assets/hello.png)
> ```
> 
> But I use `hexo g` to generate static sites, hexo do not automatic copy of the picture file. Just as ![image](https://user-images.githubusercontent.com/25679538/39514308-72c236ba-4e29-11e8-8d70-a381eea34e8f.png) Can you copy it automatically to the corresponding directory? Thanks a lot!!

My solution for your question：[Link](https://chen-huaneng.github.io/2023/12/02/2023-12-2-2023-12-03-how-to-write-blog/#%E5%8D%8F%E8%B0%83-hexo-%E5%92%8C-typora-%E6%8F%92%E5%85%A5%E5%9B%BE%E7%89%87%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)

**Comment by yangyunzhao** [comment]
> > ## Environment Info
> > Node version(`node -v`):V10.0.0
> > Your site `_config.yml` (Optional):
> > Your theme `_config.yml` (Optional):
> > Hexo and Plugin version(`npm ls --depth 0`): hexo-site@0.0.0 D:\hexo +-- hexo@3.7.1 +-- hexo-generator-archive@0.1.5 +-- hexo-generator-category@0.1.3 +-- hexo-generator-index@0.2.1 +-- hexo-generator-tag@0.2.0 +-- hexo-renderer-ejs@0.3.1 +-- hexo-renderer-marked@0.3.2 +-- hexo-renderer-stylus@0.3.3 `-- hexo-server@0.2.2
> > ## For BUG
> > ## For question
> > ## For feature request
> > I used Typora which is the best tools for markdown on the windows platform to insert picture. I just need to drag the picture to Typora，the Typora will **Automatic** generation of code，And Automatically copy files to the same level directory of .md file. Such as
> > ```
> > ![hello](assets/hello.png)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I use `hexo g` to generate static sites, hexo do not automatic copy of the picture file. Just as ![image](https://user-images.githubusercontent.com/25679538/39514308-72c236ba-4e29-11e8-8d70-a381eea34e8f.png) Can you copy it automatically to the corresponding directory? Thanks a lot!!
> 
> My solution for your question：[Link](https://chen-huaneng.github.io/2023/12/02/2023-12-2-2023-12-03-how-to-write-blog/#%E5%8D%8F%E8%B0%83-hexo-%E5%92%8C-typora-%E6%8F%92%E5%85%A5%E5%9B%BE%E7%89%87%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)

thanks a lot
