### ISSUE TITLE
How to add an external link?

### ISSUE THREAD

**Issue by phith0n** [hexojs/hexo#3147]
Hi, 
  I wrote an article on social networking site, such as zhihu, I want to add the title and link of the article into my hexo blog. The visitor can just click this link and jump to external website(zhihu), is there a solution for this problem?

**Comment by jdhao** [comment]
Check how to make links on Markdown [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links).

**Comment by phith0n** [comment]
Can I write markdown in my blog index page or article list page ?
Of course I know how to make links in article detail page (using markdown), you don't understand what I mean.

**Comment by jdhao** [comment]
I am not aware that this feature exists in Hexo. If you know html well enough, you can hack it.
