### ISSUE TITLE
【建议】hexo这么好的博客系统，能不能用一个配得上的markdown渲染引擎

### ISSUE THREAD

**Issue by runningbar** [hexojs/hexo#3148]
如题

`hexo`用了一年多了，挺简便的，就一个不尽如人意之处：`markdown`引擎真的不甚好用。

在`macdown`里面写好的文章，换到`hexo`渲染一下，就各种凌乱

1. `mathjax`的支持：我搜到`issue`里面有各种解决方案，但都不完美；也有说是`markdown`和`mathjax`语法冲突本身的问题导致，但是`macdown`里面就没有这种问题啊。

2. 行内`code`的样式：换用了最新版的`hexo`之后，发现行内代码的字体大小被统一调小，而不会再随着标题样式变化，等于说现在标题中无法出现行内代码，否则看上去比正文内容还小。

**Comment by baoang** [comment]
我用的是NexT风格套件，最近因要处理数学公式，也遇到了这样的问题。在解决问题和配置的过程中看了下NexT的模板配置文件中的注释，才发现原来Hexo有多个markdown的渲染引擎，光是官方在plugin页面中发布的就不下三四种。

目前来讲，用到渲染数学公式的，大体有两个代码，一是MathJax，另一个是Katex。在采用这两种代码的时候，我注意到使用Marked、Markdown-it、Markdown-it-Plus、Kramer等跑出来的效果不太一样，不止是反应到数学公式的展现上，还包括类如`[^1]`就是注释、行内加粗、代码片段那个backtick标记是否最后能有个空格等问题上。用Katex的话，某些Markdown的渲染引擎还必须支持到特定的Katex版本。

总之，要能成功的渲染出非普通文本格式的html文件，并不是一件特别轻松的事。当然，Hexo不同与Hugo，后者干脆是独立的且有专门运行的Go程序在处理，事先封包基本上不用考虑什么依赖包的需要，当然也就不需要进行Markdown引擎的选择了，一切都由官方指定。

从[StaticGen的对比](https://www.staticgen.com/)来看，Hexo已经从当初的老二掉了下来，变成老四。也许官方在提供丰富的plugin的同时，也可以在指定固定或官荐插件方面提供给用户更多的信息，比如说，官定内置的Markdown渲染引擎是hexo-renderer-marked，但在哪些情况下，我们推荐使用hexo-renderer-markdown-it？哪些情况下，由于各个开发者不能及时维护，因而目前推荐大家在使用什么功能方面，我们推荐大家使用hexo-renderer-kramer，类似这样的？

**Comment by jdhao** [comment]
There is [a good doc](https://github.com/theme-next/hexo-theme-next/blob/master/docs/MATH.md) about how to use math equation in Hexo NexT. If you haven't checked it, you should check it to see if it meets your needs.

**Comment by BentleyBlanks** [comment]
试一下Katex。本质上是直接翻译成css，加载速度也更快无需重刷，自定义样式也更方便。缺点是语法更规范严格，不过瑕不掩瑜吧。

**Comment by SnailDove** [comment]
@jdhao  hexo generate failed after I did as following:

Firstly, you need to uninstall the original renderer hexo-renderer-marked, and install one of the renderer above:

```
npm un hexo-renderer-marked --save
npm i hexo-renderer-pandoc --save # or hexo-renderer-kramed
```
Secondly, in next/_config.yml, turn on enable of math and choose mathjax as engine.
```
math:
  enable: true
  ...
  engine: mathjax
  #engine: katex
```
Finally, run standard Hexo generate, deploy process or start the server:
```
hexo clean && hexo g -d
# or hexo clean && hexo s
```

**Comment by JackieAnxis** [comment]
@SnailDove Helps me a lot! Thanks.

**Comment by curbengh** [comment]
Hey everyone, I am rewriting hexo-math atm (https://github.com/hexojs/hexo-math/pull/130). It's now implemented as a tag plugin.

```
---
title: test mathjax
date: 2020-01-02 01:02:03
---

{% mathjax %}
\frac{1}{x^2-1}
{% endmathjax %}
```

The advantage of using a tag plugin is that its content is separate from the rest of the markdown content, so they shouldn't conflict with each other.

The PR is ready for testing, just install it by `$ npm install hexo-math@curbengh/hexo-math#overhaul`. If there is no issue, I plan to release it on this weekend. Temporary usage guide is here ([readme.md](https://github.com/hexojs/hexo-math/blob/f98e3a5eb3d166953d071492717539b77fbb64a8/README.md)).
