### ISSUE TITLE
hexo deploy 执行速度奇慢无比

### ISSUE THREAD

**Issue by acgtyrant** [hexojs/hexo#315]
前两次 deploy，均花了15分钟左右；而 Octopress 的话不到一分钟就上传好了。

deploy 方式是 github，repo 的形式为 https。

网速为 2M。

感谢 tommy 大大的辛勤开发。

**Comment by iyannik0215** [comment]
@acgtyrant 亲, 能不能详细说明一下..

**Comment by acgtyrant** [comment]
@iyannik0215 自己查 `git remote` 方面的内容。

**Comment by iyannik0215** [comment]
@acgtyrant 好的～， 不过我现在吧repo: 改成了https链接， 之后正常了。 不明白为什么。

**Comment by acgtyrant** [comment]
在国内链接就是一门玄学。
