### ISSUE TITLE
Migrate travis ci's API from webhook to github apps

### ISSUE THREAD

**Issue by segayuu** [hexojs/hexo#3152]
[travis ci recommended switching to operation with Github apps](https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com).
According to this, it is described that webhook we are currently using will become legacy.

**Comment by segayuu** [comment]
Because I did not know clearly by article alone for the time being, as a result of trying to do with a personal account, it was a paid service even in the public repository as it is now. mmm...

**Comment by JLHwung** [comment]
The migration should be done by the original integrator, i.e. the person who connects travis with hexo GitHub repositories. cc @NoahDragon

**Comment by segayuu** [comment]
I used github app with [segayuu/hexo-plugin-rollup](https://github.com/segayuu/hexo-plugin-rollup).
When doing with a new repository, I think that it is better to do it with github App!

If you are using the .org version, you can not transfer the history etc at the moment, so you can not do a full migration soon.

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/pull/4514
