### ISSUE TITLE
On Windows Helpers(is_home()、is_post()) is normal,but it not work on Linux, it always return false.

### ISSUE THREAD

**Issue by qiulanzhu** [hexojs/hexo#3157]
My env:
[root@****]# hexo -v
INFO  =========================================
INFO    Welcome to use Snippet theme for hexo  
INFO  =========================================
hexo: 3.7.1
hexo-cli: 1.1.0
os: Linux 3.10.0-693.2.2.el7.x86_64 linux x64
http_parser: 2.7.0
node: 8.5.0
v8: 6.0.287.53
uv: 1.14.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

I do like this:
```
<% if(is_post()){ %>
<div class="widget catalog">
    <h3 class="title">title</h3>
</div>
<% } %>

```
On Windows is_post() return turn, but On Linux return false.

Any help will be greatly appreciated.

**Comment by qiulanzhu** [comment]
I find the problem.
If I generate the static file, and agent by nginx, the Helpers(eg. is_home()、is_post()) is not work.
If I generate the static file, and `hexo s`, everything is ok.

**Comment by zhwangart** [comment]
I am using a MacOS system. What should I do?
Write `<%- is_home() %>` returns **true** at `http://localhost:4000/` and then generates **false** in `index.html` in the (`$ hexo g`) file. ???
`$ hexo clean` before executing `$ hexo g`
