### ISSUE TITLE
Can't skip_render the .well_known directory.

### ISSUE THREAD

**Issue by nikhiljha** [hexojs/hexo#3158]
## Environment Info

Node version(`node -v`): v9.6.0

Hexo and Plugin version(`npm ls --depth 0`): 3.7.1

## Thing

I'm using `skip_render: \.well_known/*` so I can have `source/.well_known/dat` copied to `public/.well_known/dat` but it doesn't do that.

**Comment by tcrowe** [comment]
It's a tough one to get the right pattern for that.

I tracked it down to using minimatch https://www.npmjs.com/package/minimatch

So it will render unless *not* matching with that.

Here's where you can goto possibly debug if the pattern is correct or incorrect https://github.com/hexojs/hexo/blob/92827129f37600d5dd2939d28ef46f66db5e23dd/lib/plugins/processor/asset.js#L118

Maybe

```yml
skip_render:
- '.well_known/*'
```

**Comment by nikhiljha** [comment]
```yaml
skip_render:
- '.well_known/*'
```
Doesn't seem to work unfortunately. :(

It's weird because my `keybase.txt` that I don't have in skip_render works fine, but I don't have anything representing the `.well_known` in public.

**Comment by nikhiljha** [comment]
Could it be ignoring things that start with a `.` while checking for things to render?

**Comment by tcrowe** [comment]
What if it needs to be escaped? like `- '\.well_known/*'`

I'll run an experiment soon. This will help me too with my `well_known` dir

**Comment by nikhiljha** [comment]
`'\.well_known/*'` also doesn't work, did you manage to get it to work?
