### ISSUE TITLE
html如何嵌入自定義的css與js

### ISSUE THREAD

**Issue by xeriok18600** [hexojs/hexo#3160]
## Environment Info
Node version(`node -v`): **v8.11.2**

Your site `_config.yml` (Optional):  
**# Hexo Configuration
## Source: https://github.com/hexojs/hexo/

# Site
title: Bobo'Blog
subtitle:
description:
keywords:
author: I-CHE
language: zh-tw
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: bobolee.dainamlon.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Themes: https://hexo.io/themes/
theme: edinburgh

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
    
menu:
  About: /resume/index.html
  Contact: /contact
  Instagram: https://www.instagram.com
  LinkedIn: https://www.linkedin.com
  Facebook: https://www.facebook.com**

Your site theme`config.yml` (Optional):  

**# Google Analytics Tracking ID
google_analytics:

# Default portfolio post
default_cover_image: images/unsplash.jpg
default_post_title: Portfolio Item**

Hexo and Plugin version(`npm ls --depth 0`): 
**+-- hexo@3.7.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2**

## For question

資料夾路徑
 — — _config.yml
 — —  package.json
 — —  scaffolds
 — —  source/ 
 — — — — — — _posts/
 — — — — — — **resume/**
 — — — — — —  — — —  **css/**
 — — — — — —  — — —  **js/**
 — — — — — —  — — —  **index.html**
 — —  themes\

我從blog首頁要進入 resume，畫面就一直轉圈，我獨立開啟resume顯示是ok的 
想問說我套用主題為 edinburgh，如何在 "resume" 使用自己html，並嵌入自定義css.js

<img src="https://i.imgur.com/FtUGmWH.png"></a>

**Comment by baoang** [comment]
会不会同某个js代码未能完全载入有关？
我自己用NexT的主题，出现过addThis的代码加载不出分享按钮，我查过生成的页面中是有addThis的代码的，也未用广告屏蔽的工具，想了半天，应当是与代码未能够完全载入有关，因为偶尔它能显示出分享按钮。

**Comment by xeriok18600** [comment]
@baoang 
我將html裡的css跟js註解掉就可以跑了

**Comment by xeriok18600** [comment]
@baoang 
我覺得有可能，我註解掉一些js的嵌入檔，網頁就顯示出來了，有點懊惱阿 ~
