### ISSUE TITLE
Force Pages to Use Flat Files, Not Directories

### ISSUE THREAD

**Issue by tohuw** [hexojs/hexo#3161]
## Environment Info

Node version(`node -v`): 8.10.0

Your site `_config.yml` (Optional): N/A

Your theme `_config.yml` (Optional): N/A

Hexo and Plugin version(`npm ls --depth 0`): Hexo@3.7.1

When I run `hexo new page test`, it creates a folder "test" and inside an `index.md`. I'd rather it just create a `test.md` instead, similar to how posts are created when you set the permalink to `:title`.

How can I achieve this?

**Comment by tcrowe** [comment]
Hi @tohuw 🤔 

I poked through the source to find how it might be done. Lets try `hexo new page --path flat flat` and see if that works.

Can you let me know?

**Comment by tcrowe** [comment]
It has `--source`, `--path`, and `--layout`

I'm not sure what source is just yet.

**Comment by tcrowe** [comment]
https://github.com/hexojs/hexo/blob/67722e5bf957a31c4e142afb4f296da8ebb43aff/test/scripts/generators/page.js#L42

**Comment by Arcesilas** [comment]
Unfortunately the `--path` option is not documented. It's obviously listed when running `hexo help new`, but the behaviour is a bit confusing.
I may provide a PR on hexojs/site repository.
