### ISSUE TITLE
「hexo: command not found」after 「npm install -g hexo-cli」

### ISSUE THREAD

**Issue by IcyW** [hexojs/hexo#3163]
## Environment Info

Node version(`node -v`): v10.1.0
Npm version: 5.6.0
Nvm version: 0.33.11

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
/usr/local/Cellar/nvm/0.33.11
└── (empty)

## For question

It always showed "hexo: command not found" even if I tried "sudo npm install -g hexo-cli" or "npm install hexo --no-optional" or "npm install hexo --save" or "npm install -g hexo". Maybe there are something wrong with my Mac OS environment.

The last time I tried "sudo npm install -g hexo-cli", the log is as following:

> /Users/XXX/.node/bin/hexo -> /Users/XXX/.node/lib/node_modules/hexo-cli/bin/hexo
> + hexo-cli@1.1.0
> updated 1 package in 19.724s

Could anyone help me? Thanks a lot.

**Comment by tcrowe** [comment]
Hi @IcyW :wave:

Maybe we can try fixing it this way:

```
echo $PATH
which node
which npm
dirname `which npm`

# search for npm linked module 'bin'
dirname `find ~ -perm +0111 -type l -iname "hexo" | grep '/bin/hexo'`
```

Is that particular npm bin hexo path in your `$PATH`?

Sometimes nvm or npm doesn't have this setup correctly.

**Comment by IcyW** [comment]
@tcrowe Millions thanks for your reply!!
And it works!! After I added the hexo path in my $PATH.
Actually, what confused me most is to confirm where my HEXO was installed.

Thanks again.

**Comment by tcrowe** [comment]
Glad you got it running!

This other thing with dtrace happens with us on OSX:
https://hexo.io/docs/troubleshooting.html#Error-with-DTrace-Mac-OS-X

It might work without the errors if you:
```
npm rm hexo-cli -g
npm install hexo-cli@latest --no-cache --no-optional
```

I've got this on my system because I don't even know what the optional packages are for anyway:
```
npm config set optional false -g
```

**Comment by IcyW** [comment]
@tcrowe Thanks!!
The problem was solved yesterday when I tried this way: 

>  removing `node_modules` and using `npm i`

https://github.com/react-community/create-react-native-app/issues/135
