### ISSUE TITLE
error：Received malformed response from registry for undefined. The registry may be down.

### ISSUE THREAD

**Issue by szlwl** [hexojs/hexo#3167]
![image](https://user-images.githubusercontent.com/23445537/40570994-a10f3d9a-60c3-11e8-8792-ea853019b0f9.png)

请问这个是什么错误？

**Comment by OceanChip** [comment]
在命令行里面执行npm install,将依赖性安装起来

**Comment by tcrowe** [comment]
This may be a yarn or npm server problem. Please re-open the issue if the problem is with hexo. Thanks

**Comment by JLHwung** [comment]
If you are in PRC, try the following steps to see if the issue is gone:
```
cd /path/to/your-blog
yarn config set registry https://registry.npm.taobao.org
yarn
```

**Comment by tcrowe** [comment]
Thanks @JLHwung I didn't think of that
