### ISSUE TITLE
总是 npm: command not found

### ISSUE THREAD

**Issue by cqtangsong** [hexojs/hexo#3168]
环境变量path也增加了 但是总是这样  求解答

**Comment by jdhao** [comment]
Are you sure that Node.js is correctly installed? Can you use `npm` command in the command line?

**Comment by tcrowe** [comment]
I'm not sure we can help more unless this is a hexo issue.

You can try:

```sh
which npm
which node
which hexo
echo $PATH
```

Re-open the issue if this is a hexo issue @cqtangsong
