### ISSUE TITLE
Hexo server or hexo generate two kinds of results are not the same

### ISSUE THREAD

**Issue by im** [hexojs/hexo#3171]
The two running results of hexo server or hexo generate are different. Hexo server can get the custom variables in the page. Hexo g can not get the custom variables in the page..

**Comment by tcrowe** [comment]
I'm not sure how to fix. What do you mean custom variables? Like in the top of your markdown? A `renderer` may be needed.

**Comment by YoshinoriN** [comment]
Possibility duplicate #2451

**Comment by stevenjoezhang** [comment]
There is a discussion about it https://github.com/hexojs/hexo/issues/2451
I'm closing this issue. Please join the discussion there :)
