### ISSUE TITLE
hexo server 是没问题 但是无法执行 hexo g

### ISSUE THREAD

**Issue by Darinstu999** [hexojs/hexo#3172]
ERROR /Users/XXXXX/Documents/blog/themes/typing/layout/layout.ejs:18
    16|         <%- body %>
    17|       </div>
 >> 18|       <%- partial('_partial/footer') %>
    19|       <%- partial('_partial/after-footer') %>
    20|     </div>
    21|   </body>

这个问题难道是我clone的theme有问题嘛 但是我本地debug运行的好好的 一generate就报错了 谢谢

**Comment by tcrowe** [comment]
Did you solve it? Is `<%- body %>` inside `_partial/footer.ejs`?

**Comment by Darinstu999** [comment]
Nope, i delete all my files related to this blog and try several times, it just does't work.
