### ISSUE TITLE
date problem

### ISSUE THREAD

**Issue by blackwolfsec** [hexojs/hexo#3175]
## Environment Info

Node version(`node -v`):
v8.11.2

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 E:\test
+-- hexo@3.7.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

date: 2018-15-30 will be generated to 2019-03-30

Steps To Reproduce:
1./source/_posts/hello-world.md
```
---
title: Hello World
date: 2018-15-30
---
```
 2. hexo g && hexo s

**Comment by tcrowe** [comment]
Please try using the full date format. e.g. `date: 2018-04-19 17:17:35`

The helper usually creates it with a date. If you used draft you can add the date field in it.
`hexo new post title`

Get date with JS moment `moment().format('YYYY-MM-DD hh:mm:ss')`

Python formatting string `%Y-%m-%d %X`

Does that solve it?
