### ISSUE TITLE
How to dynamically change language?

### ISSUE THREAD

**Issue by arkceajin** [hexojs/hexo#3176]
I want to know how to dynamically change the language, Just like Hexo home page.

**Comment by tcrowe** [comment]
On that site they're switching between directories:
https://github.com/hexojs/site/tree/master/source

Then doing something complicated in here with the `page.lang`:
https://github.com/hexojs/site/blob/master/scripts/helpers.js

But not actually using this i18n feature:
https://hexo.io/docs/internationalization.html

`i18n_dir: :lang`

---

When you arrive at a solution will you come back here and update us how you get it to work please?

**Comment by arkceajin** [comment]
https://github.com/hexojs/site/blob/master/source/zh-cn/index.jade
I see...directly write the translation as the string, did not use i18n at all.

**Comment by tcrowe** [comment]
Yeah, and I couldn't figure out how this variable was set or changed for the layout https://github.com/hexojs/site/blob/master/themes/navy/layout/layout.swig#L2

**Comment by arkceajin** [comment]
I only found `page.lang` is the first element of `language` defined in the `_config.yml`. was set at:
https://github.com/hexojs/hexo/blob/0b26940f7e0a35f6937b944012468bbf0d844010/lib/plugins/filter/template_locals/i18n.js#L25

**Comment by arkceajin** [comment]
it's confusing me that if `hexo` support defines multi-lang in the config. if cannot switch the language setting, Why only the first one can be used?

**Comment by tcrowe** [comment]
Another user was showing me how they switched language

`http://site/en/page`
`http://site/es/page`
`http://site/zh-cn/page`

Thats it. Just change url.
