### ISSUE TITLE
Can I generate chemical equations with latex?

### ISSUE THREAD

**Issue by EroMonsterSanji** [hexojs/hexo#3179]

**Comment by tcrowe** [comment]
I think so @EroMonsterSanji 

I viewed https://hexo.io/plugins/

There are at least two there:
https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus
https://github.com/iamprasad88/hexo-tag-katex

MathJax with hexo-math https://github.com/akfish/hexo-math

If any of those solve it please come back and update us so others can find this and use hexo for their math and chemistry too.

Thanks

**Comment by joejztang** [comment]
You should be able to do that.
I couldn't remember the name, but you could install some plugins which render latex environment on top of hexo.
but remember, it is flawed, sometimes it will not render perfectly according to your input.
Be prepared.
