### ISSUE TITLE
hexo d 部署卡住

### ISSUE THREAD

**Issue by wangjw219** [hexojs/hexo#3182]
## Environment Info
hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 17.4.0 darwin x64
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

## _config.yml
```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:wangjw219/wangjw219.github.io.git
  branch: master
```

## For question

运行```hexo d```命令，处理文件之后卡住了:
```
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
[master 4b7e049] Site updated: 2018-06-12 08:22:58
 2 files changed, 2 insertions(+), 2 deletions(-)
...
```
运行```hexo d -debug```命令，发现一直循环执行 start processing ：
```
INFO  Start processin
INFO  Files loaded in 27 ms
INFO  0 files generated in 25 ms
INFO  Start processing
INFO  Files loaded in 26 ms
INFO  0 files generated in 59 ms
INFO  Start processing
INFO  Files loaded in 25 ms
INFO  0 files generated in 22 ms
INFO  Start processing
INFO  Files loaded in 36 ms
INFO  0 files generated in 19 ms
INFO  Start processing
INFO  Files loaded in 31 ms
INFO  0 files generated in 22 ms
INFO  Start processing
INFO  Files loaded in 31 ms
INFO  0 files generated in 19 ms
INFO  Start processing
INFO  Files loaded in 29 ms
INFO  0 files generated in 19 ms
INFO  Start processing
```
请问这是什么原因？

**Comment by JavaZWT** [comment]
我也出现这种情况，每天晚上都deploy不上去，早上去公司就可以deploy上去了。。。。。我一度怀疑是网络问题。。。可是我晚上的时候GitHub上其他项目pull和clone速度都是正常的。。。。这是我不能理解的。。

**Comment by ScoJJ** [comment]
请问你解决了吗，我的也是这样，在台式机的mac系统上不行，用我的windows笔记本就能上传。

**Comment by Junior2Ran** [comment]
我也是一样的问题，公司的mac不行，家里的windows也不行

**Comment by asiagood** [comment]
我在家里的Mac 上不行，问题是我没做任何改动上一次部署是10天前，当时一切正常。又哪位朋友解决了这个问题吗？

**Comment by asiagood** [comment]
我是用家里的Mac Book Pro。之前一直是正常的，没做任何改动。今天写了一篇文章之后hexo g -d 发现这个问题。
请问有哪位朋友解决了没？

**Comment by JavaZWT** [comment]
很大部分时间还是deploy不上去，我现在下载了GitHub Desktop，把项目  down  下来，有更新就把public文件夹覆盖更新一份，再通过GitHub Desktop  pull上去。。。。

**Comment by allenfrostline** [comment]
同卡，不知道什么问题

**Comment by LixHu** [comment]
同求解决方案

**Comment by mokeychan** [comment]
有毒

**Comment by mokeychan** [comment]
换了网络环境就好了

**Comment by HeiLiu** [comment]
换了网络并没有什么鸟用啊

**Comment by LixHu** [comment]
我是在一个网络里面死等，等了大概十分钟，自己部署成功了。估计是网络不好。

**Comment by jianjiade** [comment]
同遇到这样的情况，完全没反应，也不知道哪里的问题。

**Comment by HeiLiu** [comment]
折腾了两天，感觉自己没有做什么修改， 自己就好啦，真让人头大，感觉跟中国股市样的

**Comment by Lz1y** [comment]
有朋友解决了吗...MacBook Air同样问题...

**Comment by Lz1y** [comment]
这个哥们说是解决了，但是我的依然无效
http://duanyifu.com/2016/08/23/hexo-deploy-problem/

**Comment by Lz1y** [comment]
楼主命令执行错了...hexo d --debug，搞得我也是循环上传23333，加上代理就好了~

**Comment by LixHu** [comment]
等就好了，不是网络问题就是你代理问题

**Comment by J-zin** [comment]
我也是这个问题  请问解决了么

**Comment by SaneHe** [comment]
我的也是一直这样

**Comment by yolayolayolanda** [comment]
事实上，我关闭代理之后好了。。。。

**Comment by Po1lux** [comment]
我也有这个问题，有时可以部署，有时又不可以，一开始以为是网的问题，换了代理还是不行，安装了这个后，就可以正确部署了
npm install hexo-deployer-git --save

**Comment by jameingh** [comment]
> 我也有这个问题，有时可以部署，有时又不可以，一开始以为是网的问题，换了代理还是不行，安装了这个后，就可以正确部署了
> npm install hexo-deployer-git --save

我装了也不行
我的直接命令运行结束，没有给我一直等等机会
![image](https://user-images.githubusercontent.com/5267037/107172048-52b36e80-69ff-11eb-9770-c4b5ea84ddac.png)

**Comment by huahai2022** [comment]
我把wifi换成手机热点，一下子就上传成功了
