### ISSUE TITLE
多个 Tags 怎么分割？ 

### ISSUE THREAD

**Issue by CheneyWong** [hexojs/hexo#320]
用空格 和 ，分割还是会黏在一起，变成一个tags了。

**Comment by jamiesun** [comment]
tags: [tag1,tag2,tag3] 这样挺好的

**Comment by jackniu81** [comment]
对新手来说，确实不知道YAML。 不过goolge一下就知道了，习惯了就好了。

**Comment by renchuqiao** [comment]
感觉[tag1, tag2, tag3]这样比较直观方便
