### ISSUE TITLE
Theme Alpha-Dust is not support by GitHub Page 

### ISSUE THREAD

**Issue by Zei1031** [hexojs/hexo#3200]
I can't open mt GitHub Page, it keep showing 404. And then GitHub sent me a email which said the theme Alpha-Dust is not support by GitHub Page...

**Comment by tcrowe** [comment]
It redirects over to `www.original-onf.com`

Check this out:
https://github.com/Zei1031/zei1031.github.io/search?q=original-onf&unscoped_q=original-onf

**Comment by tcrowe** [comment]
For reference: https://zei1031.github.io
