### ISSUE TITLE
A bug in displaying homepage about the index.jade

### ISSUE THREAD

**Issue by Jasonhz** [hexojs/hexo#3203]
## Environment Info

Node version(`node -v`): v9.10.1

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): Navy

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 C:\hexo\site
+-- cheerio@1.0.0-rc.2
+-- hexo@3.7.1
+-- hexo-browsersync@0.3.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-jade@0.4.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
+-- lodash@4.17.10
+-- lunr@2.3.0
`-- path@0.12.7

## For BUG
 1. BUG description
Index.jade can not be loaded and displayed when the language is English. When choosing other languages, the index.jade can be viewed.

 2. The way to reproduce
(1), git clone from: https://github.com/hexojs/site
(2), install necessary npm packages such as lunr. Then: hexo s

Image 1, the language is English:
![image](https://user-images.githubusercontent.com/9855204/42128046-8a382554-7cd5-11e8-9ebd-03a21452f4f5.png)

Image 2, the language is not English:
![image](https://user-images.githubusercontent.com/9855204/42128053-a209b940-7cd5-11e8-82d0-05951d274c50.png)

In the first image, there is no source/index.jade 
"ul#intro-feature-list
  li.intro-feature-wrap
    .intro-feature
      .intro-feature-icon
        i.fa.fa-bolt
      h3.intro-feature-title Blazing Fast
      p.intro-feature-desc Node.js brings you incredible generating speed. Hundreds of files take only seconds to build."

But in the second image, you can see source/zh-tw/index.jade:
"ul#intro-feature-list
  li.intro-feature-wrap
    .intro-feature
      .intro-feature-icon
        i.fa.fa-bolt
      h3.intro-feature-title 超級快速
      p.intro-feature-desc Node.js 帶給您超級快的檔案產生速度，上百個檔案只需幾秒就能建立完成。
"

**Comment by tcrowe** [comment]
Did you solve this @Jasonhz? Your example was detailed but I didn't understand how to fix it.

**Comment by Jasonhz** [comment]
Hi @tcrowe , thanks for your reply.
I cannot solve this problem, but I used another solution to show the information in "source/index.jade". The solution is to revise the file "\themes\navy\layout\index.swig" by adding some IF-THEN-ELSE rules, so that some html codes can be displayed in the home page when some conditions are met (e.g., page language is English).
Hope it helps. I am still wondering why "source/index.jade" cannot be loaded while "source/zh-tw/index.jade" can.
