### ISSUE TITLE
Quickstart and Documentation missing "install" command

### ISSUE THREAD

**Issue by putztzu** [hexojs/hexo#3204]
After following the Quickstart in the README.md and stepping through the Install of the Documentation, Hexo still did not launch successfully in the Hexo server.

I found in a 3rd party blog the missing step to run "hexo install" after configuration which then built the Hexo site and only then launched successfully in Hexo server.

**Comment by tcrowe** [comment]
Hey @putztzu :wave:

Maybe you can run another test and tell us which part is wrong. That will help us fix it.

**Comment by tcrowe** [comment]
If you come back to this with a solution @putztzu please re-open the issue or provide a PR. Thanks!
