### ISSUE TITLE
Local hexo not found in /mnt/hexo

### ISSUE THREAD

**Issue by gibck** [hexojs/hexo#3205]
ERROR Local hexo not found in /mnt/hexo
ERROR Try running: 'npm install hexo --save'

Running "npm install hexo --save" command doesn't work either
Every time is to report this error, how to solve

**Comment by tcrowe** [comment]
Can you check `echo $PATH` and `npm config ls -g` then see if that gives us any clues?

**Comment by gibck** [comment]
thanks  !!!
These are my configurations:
root@VM-200-122-ubuntu:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/java/jdk1.8.0_151/bin:/usr/java/jdk1.8.0_151/jre/bin:/usr/local/node-v8.11.3-linux-x64/bin
==========================================================
root@VM-200-122-ubuntu:/# npm config ls -g
; cli configs
global = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v8.11.3 linux x64"

; node bin location = /usr/local/node-v8.11.3-linux-x64/bin/node
; cwd = /
; HOME = /root
; "npm config ls -l" to show all defaults.

root@VM-200-122-ubuntu:/#

**Comment by tcrowe** [comment]
Thanks @gibck 

Is `/mnt/hexo` the hexo repo? It doesn't contain the CLI.

Can you also try this?

```sh
npm install --global hexo-cli
hexo -v
```

Or if you need to put the repos on the VM and use them, maybe for development purposes, you can do like this:

```sh
cd /mnt/hexo && npm link
cd /mnt/hexo-cli && npm link
```

Can you reply back with what you find?

**Comment by gibck** [comment]
thanks, I execute these command statements but reported an error;

`root@VM-200-122-ubuntu:~# npm install --global hexo-cli
/usr/local/node-v8.11.3-linux-x64/bin/hexo -> /usr/local/node-v8.11.3-linux-x64/lib/node_modules/hexo-cli/bin/hexo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ hexo-cli@1.1.0
added 11 packages and updated 1 package in 12.674s
root@VM-200-122-ubuntu:~# hexo -v
module.js:549
    throw err;
    ^
Error: Cannot find module 'hexo-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/hexo/bin/hexo:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
root@VM-200-122-ubuntu:~#`

I replaced the WIN7 system and reinstalled it. It's all right now
before,I installed it on the linux

**Comment by tcrowe** [comment]
@gibck Okay I think you're saying it's working.

Remember if you share a directory from host to guest VM that you should ignore `node_modules`. It must `npm install` on the VM because it compiles OS-specific code.
