### ISSUE TITLE
new theme not appear

### ISSUE THREAD

**Issue by leokingai** [hexojs/hexo#3206]
localhost：4000 seems okay，
but leokingai.github.so  is still the same theme, not updated any changes.

why???

## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by tcrowe** [comment]
Hi @leokingai 

:thinking: Can you goto `./_config.yml` and check `theme: _____` and see if you updated it please?

**Comment by leokingai** [comment]
hey thanks

I try commnd " hexo clearn"-"hexo deploy"

Okay now



steve@leokingdeals.com
 
From: Tony Crowe
Date: 2018-07-06 00:47
To: hexojs/hexo
CC: leokingai; Mention
Subject: Re: [hexojs/hexo] new theme not appear (#3206)
Hi @leokingai
???? Can you goto ./_config.yml and check theme: _____ and see if you updated it please?

**Comment by tcrowe** [comment]
Oh good @leokingai 🎉

Sometimes I need to clean and re-generate too
