### ISSUE TITLE
How to add in a "/" in URL

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#3208]
```
data-slug="<%- [post.title,post.slug] %>"
```
This renders `www.example.com/title,slug`

I need `,` to be `/`, so result is `www.example.com/title/slug` 

How to write? `data-slug="<%- [post.title/post.slug] %>"` does not work.

**Comment by demurgos** [comment]
I don't know what syntax you're using. It just looks like you have an array expression and it gets emitted using `.toString`.
Have you tried simply using `<%- post.title + "/" + post.slug %>`, or something similar (`"<%- post.title  %>/<%- post.slug %>"`).
If it's an expression-based serializer, it should work for simple cases but is not that reliable.

If you can import functions, look up `path.posix.join` or WHATWG urls to properly support URL encoding.
