### ISSUE TITLE
.md inside .md with layout

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo#3213]
I have multiple `.md` files.

Each with a `layout`. 

For example.

`car1.md` 

```
layout: post
car: volvo
year: 1993
```

Then...

`car2.md`

```
layout: post
car: porsche
year: 2017
```

So now I want to join these two `.md` into 1 page. 

So the `page` is like this with layout and CSS styling as per my `layout: post` for EACH of the two `.md` files...

```
volvo
1993

porsche
2017
```

I tried working with this plugin... [https://github.com/tea3/hexo-include-markdown](url)

That works but I cannot apply my `layout: post` to the second `.md` file `car2.md` somehow (it just renders plain content like this `car: porsche year: 2017`). 

How to fix?
Or what other solution I can try for my objective?

**Comment by smeijer** [comment]
OMG, what do I get frustrated by @stale `bot`. If there isn't activity on an issue, it doesn't mean that it ain't an issue anymore. I see it more like people respect that the repo owner can have a busy life, and we don't keep bugging him in a single issue.

**Comment by ngmgit** [comment]
I am looking for a solution to this. Digging  up docs and google didnt help much.

**Comment by smeijer** [comment]
I guess @stale has won.
