### ISSUE TITLE
how to custom categories path?

### ISSUE THREAD

**Issue by wddaff** [hexojs/hexo#3219]
## For question

how to custom categories path? example: change "/categories/aaa/" to "/xxx/aaa/"

**Comment by tcrowe** [comment]
Hi @wddaff 👍 

It might be possible to create a generator for that: https://hexo.io/api/generator

It goes in `./scripts`

Want to try and let me know if it worked?

**Comment by wddaff** [comment]
I try to replace it by nginx sub_filter.
