### ISSUE TITLE
Restoring lost content...

### ISSUE THREAD

**Issue by jesusgn90** [hexojs/hexo#3220]
Hello team, awesome project and I'm using it long time ago!

My problem comes from a deletion of my hexo source files... I have the repository in GitHub which stores the generated static files and my question is if there is a way to restore source files from generated files??

Regards!

**Comment by tomap** [comment]
https://hexo.io/docs/migration.html

If you had a RSS, you could try to leverage hexo RSS migration tools

Otherwise, you are good to restart from the HTML...

But why didn't you use a GitHub repo to store your sources???
If you needed your sources to remain private, then there is vsts

Good luck
