### ISSUE TITLE
Template render error: expected variable end

### ISSUE THREAD

**Issue by joejztang** [hexojs/hexo#3224]
## Environment Info

Node version(`node -v`): v8.10.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

├── hexo@3.7.1
├── hexo-admin@2.3.0
├── hexo-blog-encrypt@2.0.8
├── hexo-cli-extras@1.0.4
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.2
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-search@2.2.5
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-inject@1.0.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-kramed@0.1.4
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2

## For BUG

`hexo g` and then error

here is the debug information

```
[log.txt](https://github.com/hexojs/hexo/files/2246484/log.txt)

```

**Comment by joejztang** [comment]
because of syntax error.......
take-aways: do more `hexo g`

**Comment by jiangzhonglian** [comment]
一般是连续的 {{ 或者 }} 报错，你变成一个，可能是语法的问题

$$\begin{array}{ll} out(N_i, C_{out_j}) = bias(C_{out_j}) + \sum_{{k}=0}^{C_{in}-1} weight(C_{out_j}, k) \star input(N_i, k) \end{array}$$

修改位置：\sum_{{k}=0} => \sum_{k=0}

$$\begin{array}{ll} out(N_i, C_{out_j}) = bias(C_{out_j}) + \sum_{k=0}^{C_{in}-1} weight(C_{out_j}, k) \star input(N_i, k) \end{array}$$
