### ISSUE TITLE
装主题的时候出错，然后一直找不到原因，现在用hexo-cli创建网站都出问题，

### ISSUE THREAD

**Issue by xiaomizhou66** [hexojs/hexo#3231]
λ hexo init xiaomiblog
INFO  Cloning hexo-starter to E:\xiaomiblog
Cloning into 'E:\xiaomiblog'...
remote: Counting objects: 65, done.
remote: Total 65 (delta 0), reused 0 (delta 0), pack-reused 65
Unpacking objects: 100% (65/65), done.
Submodule 'themes/landscape' (https://github.com/hexojs/hexo-theme-landscape.git) registered for path 'themes/landscape'
Cloning into 'E:/xiaomiblog/themes/landscape'...
fatal: unable to access 'https://github.com/hexojs/hexo-theme-landscape.git/': Empty reply from server
fatal: clone of 'https://github.com/hexojs/hexo-theme-landscape.git' into submodule path 'E:/xiaomiblog/themes/landscape' failed
Failed to clone 'themes/landscape'. Retry scheduled
Cloning into 'E:/xiaomiblog/themes/landscape'...
remote: Counting objects: 833, done.
Receiving objects:  26% (220/833), 204.01 KiB | 0 bytes/s

**Comment by demurgos** [comment]
I may try to help you if you translate your issue to English. I know that that some Hexo maintainers support issues in other languages but I am not able to understand it. You may wait for one of them; or provide a description in English so I can give it a try. Thanks :slightly_smiling_face:

**Comment by AtomRun** [comment]
this is chinese i think i can solve his question.

我在你的保存信息里看到了 unable to access，你试试把E:/xiaomiblog  这个文件夹属性里赋予每个用户全部的权限试下

**Comment by AtomRun** [comment]
this is chinese i think i can solve his question.

我在你的保存信息里看到了 unable to access，你试试把E:/xiaomiblog  这个文件夹属性里赋予每个用户全部的权限试下

**Comment by AtomRun** [comment]
this is chinese i think i can solve his question.

我在你的保存信息里看到了 unable to access，你试试把E:/xiaomiblog  这个文件夹属性里赋予每个用户全部的权限试下

**Comment by AtomRun** [comment]
this is chinese i think i can solve his question.

我在你的保存信息里看到了 unable to access，你试试把E:/xiaomiblog  这个文件夹属性里赋予每个用户全部的权限试下

**Comment by AtomRun** [comment]
this is chinese i think i can solve his question.

我在你的保存信息里看到了 unable to access，你试试把E:/xiaomiblog  这个文件夹属性里赋予每个用户全部的权限试下

**Comment by AtomRun** [comment]
this is chinese i think i can solve his question.

我在你的保存信息里看到了 unable to access，你试试把E:/xiaomiblog  这个文件夹属性里赋予每个用户全部的权限试下

**Comment by iayun** [comment]
install -g hexo-cli
直接复制上面命令，执行看看
