### ISSUE TITLE
使用hexo-deployer-ftpsync进行发布时出现错误

### ISSUE THREAD

**Issue by liangxp** [hexojs/hexo#3237]
## Environment Info
Node version(`node -v`):10.X

Your site `_config.yml` (Optional):
`deploy:
  type: ftpsync
  host: XXXX # ftp服务器地址
  user: XXX # ftp用户名
  pass: XXXX # 你的ftp用户密码
  remote: webroot # 你要上传到的地址，例如/wwwroot
  port: 8010 # ftp端口，不同的ftp可能会不一样
  delete: true # 上传本地文件是否删除ftp中的所有文件
  verbose: true # 是否打印调试信息
  ignore_errors: true # 是否忽略错误`

Hexo and Plugin version(`npm ls --depth 0`):  hexo-deployer-ftpsync

## error
`
s.stat failed.
/usr/blog/node_modules/ftpsync/lib/ftpsync.js:360
              dirs = dirs.concat(res.dirs);
                                     ^

TypeError: Cannot read property 'dirs' of undefined
    at /usr/blog/node_modules/ftpsync/lib/ftpsync.js:360:38
    at /usr/blog/node_modules/ftpsync/lib/ftpsync.js:352:20
    at FSReqWrap.oncomplete (fs.js:152:21)

`

**Comment by tcrowe** [comment]
I found this mentioning `ftpsync.local.dirs`: https://github.com/hexojs/hexo-deployer-ftpsync/wiki#ftpsynclocal
