### ISSUE TITLE
完全看不懂

### ISSUE THREAD

**Issue by Meruemono** [hexojs/hexo#3243]
git和node安装之后，教程说了的那些我都没法用。如何把那一串打出来？我放在git的三种exe和node里试了，都不行。nvm是不是要注册，在网站上用编码？我从没用过，太难了，谢谢。

**Comment by AlynxZhou** [comment]
对于没有这些相关基础的人来说，静态博客生成器其实是相当难用并且复杂的，对于你的问题，我建议你选择一些傻瓜化的建站方式，或者是了解一下有关的各种知识。某种程度上来说不论是 Hexo 、Hugo 还是 Jekyll，都不是给新手准备的，而是给对这些有一定了解的程序员准备的。

**Comment by AlynxZhou** [comment]
GitHub 还问买不买的话我建议你还是先用国内的博客服务算了好吧……

**Comment by Meruemono** [comment]
不行啊，不买书我就得天天上网……没有书系统。国内博客没用。

**Comment by Meruemono** [comment]
当然问，我真的没学过，完全不会。

**Comment by Meruemono** [comment]
没时间学。但是我还是要学。以后不掌握一点怎么行，我就从头学吧，我的天，又从头了。

**Comment by JLHwung** [comment]
For general conversation, please chat on [gitter](https://gitter.im/hexojs/hexo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge). The issue is used to track specific fields of hexo.
