### ISSUE TITLE
hexo用不了了

### ISSUE THREAD

**Issue by YuFy1314** [hexojs/hexo#3246]
几天前还在用的, 今天想上去发个文章, 结果我输入完hexo发现:
![](https://user-images.githubusercontent.com/24446694/44827385-7d514880-ac45-11e8-947e-922f6762145e.png)
我并没有卸载hexo之类的插件, 都没有动过它, 现在突然不好使了, 想问问是不是和版本有关系, 该如何解决呢?

**Comment by YuFy1314** [comment]
这个问题解决了, 这个和node版本有关系, 我的node版本太低了, 切换成高版本问题就没了

**Comment by YoshinoriN** [comment]
@YuFy1314 

Sorry, I can't read chinese.
Does `这个问题解决了` word mean the solved ?

If solved, may I close this issue ?

**Comment by tomap** [comment]
According to Google translate, that is what it means. The issue was solved by upgrading nodejs.
