### ISSUE TITLE
Need help on Internationalization (i18n) (Critical)

### ISSUE THREAD

**Issue by hachi1030-Allen** [hexojs/hexo#3247]
## Environment Info

Node version(`node -v`): v8.9.4

Your site `_config.yml` (Optional): Need to confirm with you on this.

Your theme `_config.yml` (Optional): Need to confirm with you on this.

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.7.1
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.2.5
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-njucks@1.0.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.3.3

## For question

I really need some help from you guys on the i18n implementation.

I was trying to follow the blog: [https://bluemix.github.io/en/2017/multilingual-blogging-with-Hexo/](https://bluemix.github.io/en/2017/multilingual-blogging-with-Hexo/)

After modifying the `new_post_name` to :lang/:title.md, I was able to create the md files in the seperate folders. However, there will be generate issue that my blogs are not generated correctly. The error message is something like: `ENOENT no file or directory: path for some image. `.

Please contact me back so that I can demonstrate to you guys on this error.

Also, I need to confirm one thing from you guys. If I enabled the international blogs for both Chinese and English language, do I have to match the articles? Is it possible that only the technical documents that I wrote, I will prepare 2 languages for that, but for others, I just create Chinese ones? The page will render or not?

Please contact back to me via: liu.allen1030@gmail.com as soon as possible. It's really critical for me.

Thanks,

Allen

**Comment by hachi1030-Allen** [comment]
No one checked this? So how can we get support on Hexo if the supporting is so bad? The documentation is really really bad, we definitely cannot follow. It's really critical for me!

**Comment by tcrowe** [comment]
Yeah @hachi1030-Allen it can be very difficult. We need more people to help!

i18n is difficult for everyone and it's not clear the best way to use it. Thankfully hexo is so flexible you can roll your own if the default functionality doesn't work for you.

One project with good i18n is theme-next https://github.com/theme-next/hexo-theme-next

Also fork my project here for very advanced i18n support. I did examples with EN, DE, and ZH-HK. 

https://github.com/tcrowe/learn-plasma
https://fervent-sammet-4b8cc8.netlify.com/en/

**Comment by tomap** [comment]
Did you push the source code of your blog on GitHub? That would help us see and understand your full config

**Comment by hachi1030-Allen** [comment]
@tcrowe 

Hi Tony,

Thanks for the reply. Since it's been a while, I had to use the another blog theme. You can check my needs on the i18n from my current blog: [http://liudeyun.net](http://liudeyun.net).

I checked on your GitHub link for the theme next, but I did not see any sample blog there is having the i18n feature. Please check mine, I had 2 languages for same blog.

I just want to know, assume that I would like to develop my own theme, what is the best practice to implement i18n?

Thanks,

Allen

**Comment by tcrowe** [comment]
Good to hear back @hachi1030-Allen 

Your site looks good. 👍🏼

---

*Assuming unix*

To make an i18n theme add to `./theme/my-theme/_config.yml`

```yml
# main language
language: zh-cn

# all supported languages
languages:
- zh-cn # <---primary at top
- en
```

---

Create languages yaml directory:

`mkdir -p themes/my-theme/languages`

Create yaml for each language i18n texts:

```sh
touch themes/my-theme/languages/zh-cn.yml
touch themes/my-theme/languages/en.yml
```

Edit `./themes/my-theme/languages/zh-cn.yml`

```yml
你好: 你好
```

Edit `themes/my-theme/languages/en.yml`

```yml
你好: hello
```

The key is `你好` so every language must have the same key but different value.

---

Okay! Languages are ready to go. Now lets implement it inside the template:

Edit `./themes/my-theme/layout/index.ejs`

```ejs
<%= __('你好') %>
```

That's it!

Can you try and let me know if it worked?

Here, this will generate a new theme very quickly. https://github.com/tcrowe/generator-hexo-theme

**Comment by hachi1030-Allen** [comment]
@tcrowe 

Hi Tony,

Thanks for the reply!

Looks like quite easy in your instructs, but as far as I learnt, it's not.

Assume that I would like the same effect as in my blog:

![image](https://user-images.githubusercontent.com/32292089/46239906-53b94780-c3d2-11e8-9bbe-cbb8c2b639fb.png)

I can switch the language both in the root page and also blog post page. How can I implement this using the current i18n?

Also, in my current theme, I have to follow the rules in that theme and there is definitely something bad. For my current folder structure, under my **source\_posts** folder, I will have an additional folder named as **zh-cn** to put all my Chinese blogs, that's fine. But if I enable `post_asset_folder: true`, then whenever I created a blog, then I will have a same named folder created. To achieve the internationalization, I have to have a copy of the folders as well in the **zh-cn** folder for Chinese blogs to use the pictures.

And since that theme do not have the **en** folder to put English articles, we just use the default folder which is **source\_posts** to put them, so I cannot use the `hexo new articlename --lang language` to generate blogs into correct folders as well.

That's why I am asking do we have any best practice to achieve this kind of thing?

Thanks,

Allen

**Comment by tcrowe** [comment]
`I can switch the language both in the root page and also blog post page. How can I implement this using the current i18n?`

It's a good idea to dig through each theme you see which has i18n. It goes something like this.

```ejs
<% config.theme.languages(lang => { %>
<div>lang: <%=lang%></div>
<% }) %>
```

If you share the same assets between languages maybe its best to put them in `./source/img/posts/*.png`.

`source_posts to put them, so I cannot use the hexo new articlename --lang language.. That's why I am asking do we have any best practice to achieve this kind of thing?`

It's not clear to me how that should work in hexo or any static site generator. We do need clearer instructions about the i18n capabilities.

One idea I had was to do something like this:

<img width="169" alt="screen shot 2018-09-29 at 12 49 33 pm" src="https://user-images.githubusercontent.com/1634015/46249415-2aa2b200-c3e6-11e8-90cf-229d4b868da7.png">

You said you could not see it but try to look at these again on how to accomplish the `lang/_posts`. Fork it and customize for your needs. At the top right switch languages:

<img width="206" alt="screen shot 2018-09-27 at 8 07 15 pm" src="https://user-images.githubusercontent.com/1634015/46249436-73f30180-c3e6-11e8-8b80-9a777262ec8d.png">

<img width="236" alt="screen shot 2018-09-27 at 8 07 22 pm" src="https://user-images.githubusercontent.com/1634015/46249438-781f1f00-c3e6-11e8-9f28-68b8f025203b.png">


https://github.com/tcrowe/learn-plasma

https://fervent-sammet-4b8cc8.netlify.com/en/

**Comment by tcrowe** [comment]
I like your idea with `hexo new articlename --lang language` on the CLI. I think we should consider including your idea with mine for hexo i18n. Even if it's just a plugin.

**Comment by hachi1030-Allen** [comment]
@tcrowe 

Also, yes, please make it as a feature request, I do think if we are going to use internationalization, we should be able to create blogs directly under correct folder using CLI.

Thanks,

Allen

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/1696
