### ISSUE TITLE
schema.org json-ld file with custom.post.variables

### ISSUE THREAD

**Issue by ghost** [hexojs/hexo#3249]
I am trying to create a `schema.org JSON-LD` file for structured data with my own custom `post.variables`. 

In my `.md` I have these for example:
```
japan_book: Hiroshima revisited
japan_author: Ken Tanaka
```

Then in my `schema.org JSON-LD` file, I have something like this with my `dynamic variables` (for illustration only)...
```
<script type='application/ld+json'>
{
	"@context": "http://schema.org/",
	"@type": "BlogPosting",
		"author": japan_author,
		"book": japan_book,
 },
```

This does not seem to work. How to write `custom.post.variables` in `schema.org` `JSON-LD` file correctly?

**Comment by YoshinoriN** [comment]
@rabas007 

I think may be you can find how to implement JSON+LD base on [this hexo theme](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/669623647898e628acf273df1e29d99a9d1d8b8f/scripts/helpers/json_ld.js)
