### ISSUE TITLE
hexo leancloud problem

### ISSUE THREAD

**Issue by MasonEcnu** [hexojs/hexo#3252]
I am using the Hexo+LeanCloud combination as a blog development and article view count tool. I found the number of views of the article would also be added when I browse the homepage. How do I modify the configuration file?

**Comment by tomap** [comment]
Can you be more specific?
Can you provide a link to your repository and explain what you are trying to achieve? provide links to the piecce of leancloud that you are trying to leverage, ...

Thank you

**Comment by MasonEcnu** [comment]
I have solved this problem, thanks for your reply.
I added codes below:
```
{% if not is_home() %}
    counter.increment("time");
{% endif %}
```
at about line 60 in file: lean-analytics.swig.
It makes the counter increase except in home page.

**Comment by YoshinoriN** [comment]
@MasonEcnu 

May I close it ?
