### ISSUE TITLE
Feature request: Put file and line number in error message when getting a syntax error when generating

### ISSUE THREAD

**Issue by RichardJECooke** [hexojs/hexo#3255]
Sometimes I write a whole lot of Markdown and then eventually save. 

BOOM. Error, but which line, which file?
![untitled](https://user-images.githubusercontent.com/5468805/45221592-3c46dd00-b2b2-11e8-9808-4ad02e83d916.jpg)

Hexo 3.7.0

**Comment by SukkaW** [comment]
During working on #4046, I have noticed tag plugins have formatted `Context Dump` now:

![image](https://user-images.githubusercontent.com/40715044/71644718-fbc16d00-2d07-11ea-9640-bde52ea60cd0.png)

I will mark this issue as solved. If you have encounter any other problem at tracing error of tag plugins, feel free to reopen this issue then.
