### ISSUE TITLE
Help fixing Facebook comments plugin

### ISSUE THREAD

**Issue by RichardJECooke** [hexojs/hexo#3256]
Hi, I'm trying to get the Facebook comments plugin to work.

The original author abandoned the project three years ago. There is one bug that I don't understand Hexo well enough to fix. 

Please will someone take a look and see if they can spot it?
Or direct me to some docs on how to write a plugin, or how to debug Hexo?

The issue is that the plugin helper isn't being registered
```sh
fbcommentshead is not defined
    at eval (eval at compile (/mnt/c/data/hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:27:7)
```

I've forked the plugin, cleaned up the code and readme, and published it to npm.
The code is here: https://github.com/RichardJECooke/hexo-fbcomments/blob/master/index.js

**Comment by RichardJECooke** [comment]
Ok, fixed that error.

Now I get in my theme's `post.ejs` class that `'post'` is not defined` when using `<%- fbcomments(post.permalink) %>`

How do I fix that please?

**Comment by RichardJECooke** [comment]
Ah, fixed that too, should be 'page', not 'post'. Yay, the Facebook comments plugin is working again. Will upload it to npm and change the url in the docs

**Comment by tomap** [comment]
Sorry that no one came to help,  but I guess we can close this issue
