### ISSUE TITLE
hexo d 报错

### ISSUE THREAD

**Issue by Irene6161** [hexojs/hexo#3258]
## 20180214使用hexo部署成功，20180906无法使用，hexo d后报错 For question

> On branch master
> nothing to commit, working tree clean
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

做了如下尝试：

>  ~ sudo npm install hexo-deployer-git --save 
> Password:
> npm WARN deprecated swig@1.4.2: This package is no longer maintained
> npm WARN saveError ENOENT: no such file or directory, open '/Users/irene.liu/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/Users/irene.liu/package.json'
> npm WARN irene.liu No description
> npm WARN irene.liu No repository field.
> npm WARN irene.liu No README data
> npm WARN irene.liu No license field.
> 
> + hexo-deployer-git@0.3.1
> updated 1 package and audited 5787 packages in 5.909s
> found 1 low severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details
> ➜  ~ npm audit fix
> npm ERR! code EAUDITNOPJSON
> npm ERR! audit No package.json found: Cannot audit a project without a package.json

未果，求助～

**Comment by heyuhua1992** [comment]
你用 hexo g 生成静态文件了么？

**Comment by Irene6161** [comment]
@heyuhua1992 生成了，但还是报错。谢谢回复。

找到原因了，是因为我没有在正确的blog文件目录下运行，正确hexo init的blog文件夹被我移动到了iCloud上，所以才不能运行。我等一下整理一下详细的记录。

**Comment by Irene6161** [comment]
# hexo命令不能执行，返回报usage
## 记录一次自怼过程
### 背景
尝试发文使用hexo，但是在此输入命令，都返回usage

## 第一天20180903
### 尝试了所有的命令

> hexo clean
> 生成静态页面
> hexo g
> 本地服务器预览
> hexo s
> 发布到git
> hexo d
> 生成新文章#在source/_post文件夹里面,编辑生成的markdown文件
> hexo new 'post-name'


#### 都返回同样的结果


    ➜ ~ cd blog
    ➜ blog hexo g
    Usage: hexo

    Commands:
    help Get help on a command.
    init Create a new Hexo folder.
    version Display version information.

    Global Options:
    --config Specify config file instead of using _config.yml
    --cwd Specify the CWD
    --debug Display all verbose messages in the terminal
    --draft Display draft posts
    --safe Disable all plugins and scripts
    --silent Hide output on console

    For more help, you can use 'hexo help [command]' for the detailed information
    or you can check the docs: http://hexo.io/docs/

#### 解决方案：继续搜索
- 搜索关键词： hexo命令不能执行，返回usage（Google）
- 没有找到可行建议，修改搜索关键词：hexo 命令usage(google )

找到一个文档[Hexo常见问题解决方案](http://wp.huangshiyang.com/hexo%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)里面描述最接近的应该是这个情况

> Hexo命令失效
> 问题描述：
> 输入命令后出现如下信息：


> ```localhost:~ apple$ hexo new "title"
> Usage: hexo

> Commands:
> help Get help on a command
> init Create a new Hexo folder
> migrate Migrate your site from other system to Hexo
> version Display version information

> Global Options:
> --debug Display all verbose messages in the terminal
> --safe Disable all plugins and scripts

> For more help, you can use hexo help [command] for the detailed information
> or you can check the docs: http://zespia.tw/hexo/docs/

> ```
> 解决方案：

> 检查_config.yml中的内容，特别注意:后面需要有一个空格。
> 检查`package.json’中的内容，注意添加hexo信息用来标识这是一个hexo目录：

> ```{
>   "hexo": {
>     "version": ""
>   }
> }

> ```
如果还是有问题，可以更新hexo之后，在新的文件夹中重新进行hexo init。

## 第二天20180904
#### 试了重新升级hexo。升级后，没有解决。
我没有尝试重新init，因为不确定已有的文件会受到怎么样的影响。

#### 试了npm安装，失败

### 继续搜索 关键词：hexo 发布文章
找到发布姿势，但是回到了最开始的问题，执行所有的问题都返回usage

#### GitHub搜索hexo的repo
进入了一个关注人最多的[hexo](https://github.com/hexojs).issue中再次搜索 hexo/usage.最接近的是这个[hexo g可以正常使用，但是其他例如hexo s就无法使用](https://github.com/hexojs/hexo/issues/2233)
无解，至此有点崩，决定换种方式再试试。

## 第三天20180906
### 在hexo的博客上向成功的博主提问
注册了Disqus账号（又点亮了一个技能），提问博主，没有解决
### 加入Google Group 的Hexo主题提问
提问无人回复
### 找当初帮忙搭建博客的淘宝店主请教
他竟然微信把我删除了
淘宝阿里旺旺留言，一时之间没有回复，回复的时候问题已经解决

### 怼圈发issue提问
终于得到了解决～
非常感谢NBR的解答
@Irene6161

    你在~根目录运行 hexo g... 当然没反应... 相当于你走在大街上,大吼一声: 老婆,饭煮好了没? 你老婆在家是听不见的...
    淘宝... 好歹是解决了... 用钱解决也是诚意... 但每天都用的东西最好还是自己了解一下

        网上搜了好多也没有找到合适的方案。

        详细一些就是自怼搜索姿势的机会呐

看完这段回复，就cd blog操作了一下，还是不成功。
然后起来去接杯水，回来坐到座位上，恍然大悟，想起来之前自己在桌面上创建了一个blog的文件夹，是空的，然后移到了macbook中，而之前的那个blog文件，大概在2月份被我移到了iCloud，因此才会有这个“大喊老婆她听不见”的情况。
至此，困扰了三天的问题得到了解决。

##TL
20180906 30min init
