### ISSUE TITLE
{{ should not be rendered in a post

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo#3259]
## Environment Info

Node version(`node -v`): v10.9.0

Hexo and Plugin version(`npm ls --depth 0`): 

```
├── hexo@3.7.1
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-i18n@0.2.1
├── hexo-multiauthor@0.0.1
├── hexo-pagination@0.1.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-markdown-it@3.4.1
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.3.3
├── hexo-sliding-spoiler@1.1.6
├── hexo-tag-asciinema@0.0.1
└── hexo-tag-bootstrap@0.1.2
```

## For BUG

I think I get this error message an hundred times:

```javascript
Template render error: (unknown path) [Line 69, Column 34]
  unexpected token: }}
    at Object._prettifyError (/home/shark/Dev/hexo_rawsec/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/home/shark/Dev/hexo_rawsec/node_modules/nunjucks/src/environment.js:524:21)
    at Environment.renderString (/home/shark/Dev/hexo_rawsec/node_modules/nunjucks/src/environment.js:362:17)
    at Promise (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/hexo/post.js:230:16)
    at Promise.then.then.result (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

Because I used `{{` or `}}` in my markdown files. Because I'm writing technical stuff about templating languages for example.
This is making the EJS template engine crash.

But instead of trying to compute all files blindly, Hexo should make the EJS engine aware of the markdown context.

I mean if there is `}}` or `%}` ok try to do something with it but if the same pattern is inside markdown inline or fenced block just ignore it, it's not for you silly EJS engine.

Same for other languages (other than markdown) and stuff inside a comment.

The EJS engine is blind, make him some eyes please.

Sometimes even using the `{% raw %}` tag I can't write the code I want to.

An additional mechanism can be to make a switch to turn off EJS parsing 1) globally in _config.yml and 2) locally inside the file frontammeter. 

Not a marked problem. Marked render that as expected.

Related issue: #2030

**Comment by noraj** [comment]
The only workaround that works is to include gist or external file.

**Comment by 9999years** [comment]
I'm having the same issue on `3.8.0`:

I have a file `source/_posts/templates.md` which contains text like so:

    In Go's templates, blocks look like this: `{{block "template name" .}} (content) {{end}}`.

To which Hexo complains:

    FATAL Something's wrong. Maybe you can find the solution here: 
    http://hexo.io/docs/troubleshooting.html
    Nunjucks Error:  [Line 1, Column 60] expected variable end
    =====               Context Dump               =====
    === (line number probably different from source) ===
    1 | <p>In Go's templates, blocks look like this: <code>{{block "template name" .}} (content)
    2 | {{end}}</code>.</p>
    3 |
    =====             Context Dump Ends            =====

In Markdown sources (at least) we shouldn't render Nunjucks within literal blocks. Compare to [John Gruber's introduction to the original Markdown](https://daringfireball.net/projects/markdown/basics), which states that "In a regular paragraph, you can create code span by wrapping text in backtick quotes. Any ampersands (&) and angle brackets (< or >) will automatically be translated into HTML entities. This makes it easy to use Markdown to write about HTML example code" -- even though Markdown supports HTML in the main body copy, the message is clear: text inside back-ticks (either inline as in `` `foo` `` or delimiting a multi-line code block) should not be messed with.

Now, how should we implement this? Perhaps in [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) we could examine the output and manually escape `{{` and `{%` within `<code>` tags, so that they're preserved once Nunjucks processes them; this might be as simple as replacing `{{` with `{% raw %}{{{% endraw %}` and so on.

Any thoughts?

**Comment by noraj** [comment]
This should work with any markdown renderer and not only marked. There should be a way to disable helper (and so nunjucks) via the frontmatter at least (low quality solution) or dynamically recognize that when `{{` are in a markdown code block not to interprete them as nunjucks. Each time I want to write an article about Flask and Jinja2 my article is full of `{{` and `{%` and that make it such a pain because of nunjucks and I don't even use any tag helper in the article. So yeah 1 year later it's still a big problem.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/issues/2622 https://github.com/hexojs/hexo/pull/2593#issuecomment-310879897

I'm thinking of parsing only `{%` in a post and skip `{{`, don't know if it's viable.

**Comment by noraj** [comment]
> I'm thinking of parsing only `{%` in a post and skip `{{`

Why not if nunjucks is used only for tag helpers and tag helpers are using only `{%` but that won't resolve the problem when `{%` appears in code.

> a simple approach is to escape `{{` to `%7B%7B` by default, but it's more of a workaround.

This is not even a workaround, this will work only for the link case.

As I said earlier there are two solutions:

> There should be a way to disable helper (and so nunjucks) via the frontmatter at least

like https://github.com/hexojs/hexo/pull/2593#issuecomment-310879897 suggested.

It is easier to implement but that require users to manually change their frontmatter when they encounter a conflict.

> or dynamically recognize that when `{{` are in a markdown code block not to interpret them as nunjucks.

Actually not detect in markdown but in rendered HTML so it will works with any renderer. This can be done with a regex or a HTML DOM parser to check if `{{` or `{%` is present inside a `<pre>` or a `<code>`. So the workflow would be: markdown --(render)--> HTML --(nunjuncks patched to skip `{{` or `{%`)--> HTML (with herlpers applied). For users, this would be automatic, will not require any change and will be retro-compatible but a little harder to implement.

**Comment by noraj** [comment]
PS : see here all the changes I needed to do to my post to make is pass the nunjucks logic. It cost me one hour. Only to properly escape everything and test and trying to get the output the less ugly possible.

**Comment by noraj** [comment]
@curbengh is it planned to fix this bug that requires breaking changes for 5.0.0 milestone ?
