### ISSUE TITLE
Newbie question: Make ExpressJS the main engine for HEXO

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#3262]
I want to take full advantage of ExpressJS for HEXO and implement:
- `router`
- `bodyparser`, etc. 

How to make ExpressJS the main engine for HEXO to run "inside"? 
Help how to do it please (plugins, modules?)?

**Comment by tomap** [comment]
Hexo is for static sites. Static as in no server side rendering, only serving static files.

I suppose if you really want to use ExpressJS, you should go to https://github.com/hexojs/hexo-server and check how it works. That's the component in charge of running the local debug server using serve-static

**Comment by tcrowe** [comment]
Hey @rabas007 it pretty much uses that underneath but only for development.

Try `hexo serve --debug` to see more information how it serves. Also see hexo server that @tomap linked.
