### ISSUE TITLE
the website deployed is different from the website generated

### ISSUE THREAD

**Issue by Adam1679** [hexojs/hexo#3263]
I use the command: hexo server, then the website in the localhost is normal.
![image](https://user-images.githubusercontent.com/32404962/45671697-b3089380-bb58-11e8-9dde-4a053aa6490c.png)
But after I use command: hexo g -d, I deploy on the github https://github.com/Adam1679/adam.github.io, then the website in http://adam.github.io/ is totally different.
![image](https://user-images.githubusercontent.com/32404962/45671776-ef3bf400-bb58-11e8-86cb-97ae4eb7d636.png)
I don't know why!

**Comment by tcrowe** [comment]
Hey @Adam1679 That's weird!

Can you try something like this?

```sh
# list themes
ls themes

# get config theme
cat _config.yml | grep theme

# clean and re-try
hexo clean && hexo serve --debug
```

**Comment by YoshinoriN** [comment]
@Adam1679 

You have to create `Adam1679.github.io` repository.
http://adam.github.io/ is [other user repository](https://github.com/adam/adam.github.io).

Please see [official document of GitHubPages](https://pages.github.com/)
