### ISSUE TITLE
After I run 'hexo g', my articles are empty

### ISSUE THREAD

**Issue by LibraTang** [hexojs/hexo#3264]
## Environment Info

Node version(`node -v`): v8.11.4

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional):  archer

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

My articles are empty when I run`hexo g`. It happened on my site [libratang.github.io](https://libratang.github.io) .

## For question

When I open my article on my blog, it shows nothing.

**Comment by tcrowe** [comment]
Hey @LibraTang :wave: 

What's the result of this command? `npm ls --depth 0`

It might be an issue with missing renderer plugin.

**Comment by LibraTang** [comment]
The result of the command`npm ls --depth 0`:
```
C:\Users\汤
`-- hexo-deployer-git@0.3.1

npm ERR! extraneous: is-number@4.0.0 C:\Users\汤\node_modules\randomatic\node_modules\is-number
npm ERR! extraneous: kind-of@6.0.2 C:\Users\汤\node_modules\randomatic\node_modules\kind-of
npm ERR! extraneous: node-pre-gyp@0.10.0 C:\Users\汤\node_modules\fsevents\node_modules\node-pre-gyp
npm ERR! extraneous: wordwrap@0.0.2 C:\Users\汤\node_modules\yargs\node_modules\wordwrap
```

**Comment by tcrowe** [comment]
Uh oh 😦 It's missing most of the modules.

It might help if you generate a new project and compare the files. The default package json has many hexo plugins in it. `npm install -g hexo-cli@latest && mkdir my-site && cd my-site && hexo init`

**Comment by LibraTang** [comment]
> Uh oh 😦 It's missing most of the modules.
> 
> It might help if you generate a new project and compare the files. The default package json has many hexo plugins in it. `npm install -g hexo-cli@latest && mkdir my-site && cd my-site && hexo init`

I'll try it. Thank you!
