### ISSUE TITLE
Question: How to include image as link?

### ISSUE THREAD

**Issue by RichardJECooke** [hexojs/hexo#3265]
How you put an image on a page or post that is a hyperlink?  

None of the methods I can find work in Hexo (e.g. https://meta.stackexchange.com/questions/2133/whats-the-recommended-syntax-for-an-image-with-a-link).

**Comment by RichardJECooke** [comment]
This works: 
```[![dog](dog-300x226.png)](http://dog.com)```

**Comment by RichardJECooke** [comment]
Reopening, using url helpers doesn't work, which is very necessary in a blogging platform. 

E.g. 
```
[![ECCR](diagnosis.png)]({% post_link eccr-the-western-cape %}) 
```

Shows the picture, but link is: `http://localhost:4000/cv/!--%EF%BF%BC1--`

**Comment by tcrowe** [comment]
It looks like it might just be a case to drop in the HTML directly.

**Comment by RichardJECooke** [comment]
lol. Of course, thanks.

This works:
```
<a href='{% post_path eccr-the-western-cape-government-health-web-application-for-discharges %}' >![ECCR](6_diagnosis-300x226.png)</a>
```
This should probably be added to the docs though as Google shows it to be a common problem people encounter with Markdown.

**Comment by tcrowe** [comment]
Rich media just isn't the use case for markdown.

I usually just make snippets for any complex thing like this or just convert to HTML. 🤷‍♂️
