### ISSUE TITLE
Fail to install hexo

### ISSUE THREAD

**Issue by Lawliet01** [hexojs/hexo#3268]
I tried to install hexo through terminal by execute the coommand "npm install hexo -g" but I failed.

This is what the error said:

npm WARN deprecated titlecase@1.1.2: no longer maintained
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wuzhiyu/.npm/_logs/2018-09-25T09_37_28_040Z-debug.log

**Comment by ahuigo** [comment]
Permission problem. 
```
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
```
Use `sudo` or *proper user* who has *write permission* of `/usr/local/lib/node_modules` to install it.

**Comment by tcrowe** [comment]
Perhaps to install globally you need `sudo npm install hexo-cli@latest --global`

Alternatively you can run nvm, node, and npm for each user. https://github.com/creationix/nvm

**Comment by RichardJECooke** [comment]
If it is a permission problem you don't need to install globally (in fact, I think this is bad practice).

You can just run `'npm install hexo` then call it like `./node_modules/.bin/hexo init`

**Comment by desenvolvedorIcotrade** [comment]
para mim aparece esta mensagem! npm WARN deprecated titlecase@1.1.2: no longer maintained

**Comment by desenvolvedorIcotrade** [comment]
[    [  https://github.com/desenvolvedorIcotrade/HexoDeployer   ](](https://github.com/desenvolvedorIcotrade/HexoDeployer``))
