### ISSUE TITLE
`hexo generate` not working with `crontab`?

### ISSUE THREAD

**Issue by johnnychen94** [hexojs/hexo#3270]
## Environment Info

Node version(`node -v`): v10.6.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
```text
hexo-site@0.0.0 /home/ubuntu/Projects/my_homepage
├── hexo@3.7.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

## For Question

I use the following code to do automatically depolyment

```bash
# ~/tools/sync_homepage.sh
HOMEPAGE_DIR=~/Projects/my_homepage
cd $HOMEPAGE_DIR
git pull
hexo generate
```

and with `crontab -e`, it's
```bash
50 * * * * ~/tools/sync_homepage.sh
```

I tested this script by manually run `~/tools/sync_homepage.sh`, it successfully pulls and generates html files.

By using crontab

The git pull works, since I find files in `source` folder changed. However, `hexo generate` not working since the html folder is not changed.

Is this a bug? If not, how can I make this work?

**Comment by tcrowe** [comment]
Hey @johnnychen94 it might not have the correct path to hexo. Maybe you can add `$PATH=` to the script or give it absolute paths. e.g. `/root/.nvm/versions/node/v9.11.2/bin/hexo`

To find out try `which hexo` or `which node`

If `hexo` doesn't run on its own that way try `node hexo generate`

Can you try and let me know?

**Comment by johnnychen94** [comment]
This really helps, thanks very much! @tcrowe

I followed your instructions and tried the following ways, and both work

1. add PATH in the `~/tools/sync_homepage.sh` script 
```bash
HOMEPAGE_DIR=~/Projects/my_homepage
PATH=/home/ubuntu/.nvm/versions/node/v10.6.0/bin/:$PATH
cd $HOMEPAGE_DIR
git pull
hexo generate
```

2. use absolute paths
`/home/ubuntu/.nvm/versions/node/v10.6.0/bin/hexo generate`
