### ISSUE TITLE
Front Matter not working

### ISSUE THREAD

**Issue by Chenzk1** [hexojs/hexo#3273]
I use Hexo to build my blog. The origin test.md file works fine in the source/_posts folder. However, when I edit this file like this:
![image](https://user-images.githubusercontent.com/35548458/46133259-a2e86680-c272-11e8-8427-c5c3b2e7a524.png)
The title is gone:
![image](https://user-images.githubusercontent.com/35548458/46133509-489bd580-c273-11e8-94c6-5e0d9379265d.png)

Similarly, when I use "hexo new test1", the front matter will generate automatically and works fine. Once I edit it, it will not work.
The editor I used is Markdown 10 in Windows 10 system.

**Comment by Chenzk1** [comment]
![image](https://user-images.githubusercontent.com/35548458/46131389-176cd680-c26e-11e8-831c-429080864be1.png)
![image](https://user-images.githubusercontent.com/35548458/46131443-353a3b80-c26e-11e8-8a41-1b948de31716.png)

**Comment by tcrowe** [comment]
Hey @Chenzk1 :wave:

I wonder if it has to do with the date format. 🤔

How do we get that date?

+ Shell `date -u +"%Y-%m-%dT%H:%M:%SZ"`
+ JavaScript `(new Date()).toGMTString()`
+ Python `import datetime; datetime.datetime.now().isoformat()`

Can you try and let me know if it worked?

**Comment by tcrowe** [comment]
Also please link to your repo if it exists online

**Comment by Chenzk1** [comment]
> Hey @Chenzk1 👋
> 
> I wonder if it has to do with the date format. 🤔
> 
> How do we get that date?
> 
> * Shell `date -u +"%Y-%m-%dT%H:%M:%SZ"`
> * JavaScript `(new Date()).toGMTString()`
> * Python `import datetime; datetime.datetime.now().isoformat()`
> 
> Can you try and let me know if it worked?

Thanks @tcrowe 
The problem is fixed. And it is my editor(markdown10 and notepad++) that doesn't handle front matter blocks properly. After used VS Code, the problem was gone. 
And I also tried change date format in markdown10 but it doesn't work:
![image](https://user-images.githubusercontent.com/35548458/46251806-5ed2ad00-c490-11e8-8d7c-39e8cc5a848e.png)
I opend the test file in VS Code. It seems markdown10 add some charcters in the start of the file automatically.
![image](https://user-images.githubusercontent.com/35548458/46251832-0bad2a00-c491-11e8-9ef5-673ff6225140.png)

Thanks again!

**Comment by tcrowe** [comment]
You're welcome and thanks for getting back to me about this. 👍🏼
