### ISSUE TITLE
How to order posts by category?

### ISSUE THREAD

**Issue by esappear** [hexojs/hexo#3278]
I've tried two ways.
- sort by key
```
<% page.posts.sort('categories.data[0].name').each(function(post){ %>
    
 <% }) %>
```
- sort by function
```
<% page.posts.sort(function(a, b) {
    return a.categories.data[0].name -  b.categories.data[0].name;
  }).each(function(post){ %>
 <% }) %>
```
However, it seems that Hexo Query Data's `sort` method doesn't support a callback as a parameter.

**Comment by esappear** [comment]
@YoshinoriN 
Actually, I want all my posts to be ordered by category and displayed by pagination, such as 10 posts per page. And all the posts in one page should be divided into categories.
```
# Page 1 (10 posts per page)
Category 1:
    - Post 1
    - Post 2
    - Post 3

Category 2:
    - Post 4
    - Post 5
    - Post 6
    ...

```
I'd like to implement it in generator by passing the category-ordered posts to `pagination`.
```
pagination('categories', locals.posts.sort(config.category_generator.order_by || '-date'), {
    perPage: 10,
    layout: ['category', 'archive', 'index'],
    format: 'page/%d/',
    data: {
      category: null,
    }
  })
```
But I can't make `locals.posts` ordered by category. 
Now my implementation is to use `site.posts.data` and `lodash`'s `orderBy`/`groupBy`  method in `ejs` template files. However, I don't think it is elegance enough. If I could pass the category-ordered posts to `pagination` and read the `page.posts` in template files, it will be better.

**Comment by YoshinoriN** [comment]
Hmm, I have no idea. We want a who more familiar about pagination.

**Comment by tcrowe** [comment]
Good day @esappear :wave:

You can accomplish this by using a `generator` plugin:
https://hexo.io/api/generator

Here's one of the more advanced generators I've made. It will allow you to set what locals show up on any route. So however you need the posts and pages ordered you can set it in the generator.

https://github.com/ethsociety/learn-plasma/blob/f698b7ceef7addd23dd29afa4aa314221c3b964c/scripts/generator-i18n.js
