### ISSUE TITLE
博客文章目录点击标题无法跳转

### ISSUE THREAD

**Issue by ztz12** [hexojs/hexo#3281]
我的一级标题用的是 #
可是无法正常跳转，
![image](https://user-images.githubusercontent.com/26516281/46129414-2e5cfa00-c269-11e8-8aca-fad63cebc688.png)
我的主页http://ztzyif.site/2018/09/20/index/#more

## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by JLHwung** [comment]
Please fill out the issue template and offer more information.
