### ISSUE TITLE
Why did I modify the “sidebar” parameter and still can't see the sidebar after compiling?

### ISSUE THREAD

**Issue by enterhuiche** [hexojs/hexo#3286]
[code.txt](https://github.com/hexojs/hexo/files/2475439/code.txt)

**Comment by YoshinoriN** [comment]
@enterhuiche 
That's setting is not hexo default setting. Maybe [hexo-theme-next](https://github.com/iissnan/hexo-theme-next) problem.
Please ask to [hexo-theme-next once](https://github.com/iissnan/hexo-theme-next).

**Comment by YoshinoriN** [comment]
@enterhuiche 
Please reopen this issue if problem will not solve.
