### ISSUE TITLE
TOC helper: add min_depth

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo#3288]
## Enhancement

On the TOC helper (https://hexo.io/docs/helpers#toc), it would be great to add a `min_depth` option so we are able to set a minimum heading depth of generated toc.

This way we will be able to exclude h1 from the TOC for example.

**Comment by tcrowe** [comment]
What would `min_depth` do?

**Comment by noraj** [comment]
`min_depth` (set a minimum heading depth of generated toc) will do like `max_depth` (set a maximum heading depth of generated toc).
`max_depth` default is 6, so no heading deeper than h6. But it is assumed that the min depth is always 1. So `min_depth` will allow to set a min depth to 2 for example, generating heading for h2 to h6, avoiding to add h1 in the TOC.

**Comment by noraj** [comment]
@tcrowe hexo-tox is using the TOC helper and also https://github.com/bubkoo/hexo-toc/issues/23.

**Comment by noraj** [comment]
hexo-toc has no min depth too https://github.com/bubkoo/hexo-toc/issues/23 because it is using https://github.com/jonschlinkert/markdown-toc that has no min depth too.

**Comment by noraj** [comment]
@tcrowe This is not a duplicate issue at all one is **TOC plugin (in addition of the helper)** the other is **TOC helper: add min_depth*, **plugin** vs **helper**.

https://hexo.io/docs/plugins
https://hexo.io/docs/helpers

**Comment by tcrowe** [comment]
@noraj I see now so that does appear useful to change from h1 to h2

**Comment by gautamz07** [comment]
@noraj , a quick hot fix could be 

`const headingsSelector = [ 'h1' , 'h2', 'h3', 'h4', 'h5', 'h6'].slice(0, headingsMaxDepth).join(',');`

deleting the headings element that you don't require in the above array eg. `h1` , you should fine the file in `node_modules/plugins/helper/toc.js` , though i would agree this is far from ideal ... just a quick hot fix :P
