### ISSUE TITLE
'asset_img' tag has no effect on page

### ISSUE THREAD

**Issue by RuanXinyu** [hexojs/hexo#3292]
I create a about page by `hexo new page about`, and then I add `{% asset_img 2018-10-15-12-53-02.png %}` in `index.md` file, put the image in `about/index/` folder, but there is no effect.

**Comment by tcrowe** [comment]
Hi @RuanXinyu :wave:

I think that `post_asset_folders: true` only works for `hexo new post title` but not for `page`.

However you can try `image_tag` helper:
https://hexo.io/docs/helpers#image-tag

Can you try this and if it works close it out please? We have many open issues so maybe you can help others too!

**Comment by toudidel** [comment]
What about this issue? Still unresolved?

**Comment by stevenjoezhang** [comment]
Hexo has two types of articles: posts and pages. Posts may appear on the homepage and in archive paths, which differ, so using relative links for images in articles might cause errors. Therefore, converting these to fixed links through the post asset feature is very practical. However, for pages, which typically do not appear in the archive, using hardcoded links poses no issue. Modifications to related content would involve changes to Hexo's underlying design, which could be disruptive. Therefore, I will set this feature request as wontfix.

**Comment by RuanXinyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
