### ISSUE TITLE
How can I have multiple feeds (blogs)?

### ISSUE THREAD

**Issue by Navarjun** [hexojs/hexo#3295]
#### feature request

I was wondering if there is a way to add multiple blogs into one web application?
It might sound crazy, so please let me explain…
I want to have a website with a blog feed, a photography feed, and a calligraphy feed, for [example](http://navarjun.com).

All of these 3 feeds are independent of each other. Is there currently a way for Hexo to do this?
Thanks in advance

—-

**Edit**:
Also, I need to paginate all those feeds.

**Comment by YoshinoriN** [comment]
@Navarjun 

I can't come up with better way.
But, [this feature](https://hexo.io/docs/configuration.html#Using-an-Alternate-Config) might help your question.

**Comment by Navarjun** [comment]
@YoshinoriN Thanks for your response!

> Using multiple files combines all the config files and saves the merged settings to _multiconfig.yml. The later values take precedence.

So basically, it won't keep all the pagination options but override them. This feature should be on hexo roadmap, or someone should develop a plugin for this.

Nevertheless, I have started using Jekyll. Jekyll didn't offer this feature out-of-the-box but a plugin [octopress/paginate](https://github.com/octopress/paginate) made it work.

**Comment by tcrowe** [comment]
@Navarjun have you explored the ability to use a plugin?

Maybe one exists:
https://hexo.io/plugins/

If not you can do it without too much hassle:
https://hexo.io/api/rendering

Can you let us know which route you want to take then see if we can close it out please?

**Comment by Navarjun** [comment]
I decided to go with Jekyll. Mostly because of its flexibility.

That being said, I have to admit that I haven't explored hexo ecosystem to the extent that I explored Jekyll.
