### ISSUE TITLE
Fail to install hexo!!!!

### ISSUE THREAD

**Issue by Barret957** [hexojs/hexo#3297]
When I install hexo and do that $ npm install

Then:
npm WARN deprecated titlecase@1.1.2: no longer maintained
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.

> nunjucks@3.1.3 postinstall D:\BLOG\blog\node_modules\nunjucks
> node postinstall-build.js src

'node' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nunjucks@3.1.3 postinstall: `node postinstall-build.js src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nunjucks@3.1.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Barret\AppData\Roaming\npm-cache\_logs\2018-10-19T10_36_08_916Z-debug.log

**Comment by RussellLuo** [comment]
I encountered the same issue, is there anyone can tell me the solution please?

**Comment by Barret957** [comment]
I had solved it， just do that operate these commands under the administrator command line

**Comment by RussellLuo** [comment]
The error I see is as follows:

```
root@GFW:~# npm install -g hexo
npm WARN deprecated titlecase@1.1.2: no longer maintained
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
/root/.npm-packages/bin/hexo -> /root/.npm-packages/lib/node_modules/hexo/bin/hexo

> nunjucks@3.1.3 postinstall /root/.npm-packages/lib/node_modules/hexo/node_modules/nunjucks
> node postinstall-build.js src

module.js:550
    throw err;
    ^

Error: Cannot find module '/root/.npm-packages/lib/node_modules/hexo/node_modules/nunjucks/postinstall-build.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/hexo/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nunjucks@3.1.3 postinstall: `node postinstall-build.js src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nunjucks@3.1.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-21T03_30_50_872Z-debug.log
```

And I have found the solution [here](https://github.com/hexojs/hexo/issues/2505#issuecomment-294123974), it works for me!

**Comment by tcrowe** [comment]
I am unsure why so many people install hexo as a root user but this comes up pretty often.

Windows users can try `npm install --global --ignore-scripts hexo-cli` or in the project `npm install --ignore-scripts hexo`.

**Comment by tcrowe** [comment]
Whenever you guys find the right solution can you let me know and close it out please?
