### ISSUE TITLE
How to contribute to hexo (NOT AN ISSUE)

### ISSUE THREAD

**Issue by gautamz07** [hexojs/hexo#3298]
Hey guys i am new to nodejs and would like to contribute to hexo, i have gone through the contribution documentation HERE(https://hexo.io/docs/contributing) ,  i would like to know , 

- how exactly do you guys debug your node code ? using vscode node debugger ? 

P.S. i am more experienced in building frontend JS plugins , so kindda new to nodejs stuff, hope i can get some help from you guys. 

Thank you.
Gautam.

**Comment by tcrowe** [comment]
Hey @gautamz07 thanks for asking! We need help all the time especially answering questions in the issues.

Every hexo repo should also have `npm test` command. That's the best way to see if it works!

Please join the chat if you can: https://gitter.im/hexojs/hexo

Would it be possible to see if you can successfully solve some issues on here? If so that would be awesome!

**Comment by tcrowe** [comment]
Thanks, my dood @gautamz07

That will give us some opportunities to code and help 🙌

**Comment by tcrowe** [comment]
@gautamz07 Did you find anything interesting to work on?

It would be neat if we had a script to go look through our plugins and themes for 404 pages.
https://github.com/hexojs/site/blob/master/source/_data/plugins.yml
https://github.com/hexojs/site/blob/master/source/_data/themes.yml

Another good idea would be a script which gets the created date of the repo and the last commit date and adds it into those YML files.

This would allow us to have a lot higher quality database of the ecosystem.

Would anything like that interest you?

**Comment by gautamz07** [comment]
@tcrowe sure , that sounds interesting. let have a chat about it. apologies , i just saw your notification.

**Comment by stevenjoezhang** [comment]
> how exactly do you guys debug your node code ? using vscode node debugger ?
> Every hexo repo should have `npm test` command. That's the best way to see if it works!

Indeed, unit testing is a very important way to keep code quality: https://github.com/hexojs/hexo/issues/3984
See also https://github.com/hexojs/hexo/blob/master/.github/CONTRIBUTING.md
