### ISSUE TITLE
How can I insert an article from other link in my homepage list?

### ISSUE THREAD

**Issue by flymysql** [hexojs/hexo#3303]
## For question

How can I insert an article from other link in my homepage list? And I don't need to create a new article to re-render, or if there is a plugin that can do this, then add an external article link to the list of homepage articles?thanks！

**Comment by YoshinoriN** [comment]
@flymysql 

A [hexo-tag-link-preview plugin](https://github.com/minamo173/hexo-tag-link-preview) might help your question, if your another website has ogp meta info.
