### ISSUE TITLE
public无法生成.html页面

### ISSUE THREAD

**Issue by nanmu1206** [hexojs/hexo#3304]
就是安装next主题，初始能显示出来，但是我修改主题时就显示不出来，就本地public生成.html页面都是0kb就是空的。于是我一个一个找，发现有几个true改成false或者FALSE改成TRUE就不能渲染出.html页面

## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by JLHwung** [comment]
Please fill out the issue template and offer more information.
