### ISSUE TITLE
how to skip_render all files start_with "abc"

### ISSUE THREAD

**Issue by xu-song** [hexojs/hexo#3306]
## Environment Info

Node version(`node -v`): v10.3.0

## For question

```
skip_render:
  - **/abc**

```

the above config does not work 

#1146

**Comment by xu-song** [comment]
thanks
where can i find the source code of regular expression?

**Comment by weyusi** [comment]
https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/post.js#L231

https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/common.js#L49-L61

**Comment by xu-song** [comment]
thanks

**Comment by weyusi** [comment]
you may close this if resolved.

**Comment by xu-song** [comment]
It only skip the file.
What about the folder start with `abc`?
