### ISSUE TITLE
如何从3.4.4升级到3.8？

### ISSUE THREAD

**Issue by dijia478** [hexojs/hexo#3307]
![image](https://user-images.githubusercontent.com/30929521/47508999-bb669380-d8a7-11e8-8771-22f3b6c2fecb.png)
如图，我的版本是3.4.4，大半年不玩了，现在突然想写写博客，发现版本有跟新，请问我该怎么更新它呢？

**Comment by YoshinoriN** [comment]
👋 @dijia478 
At first, please change your `package.json` hexo version. 
Example is below.

```yaml
  },
  "dependencies": {
    "hexo": "3.8.0",
```

Second. update hexo using by below command.

```sh
$ npm install
```

At the last. Please check update is success or not `hexo version`.
update is succeeded, if your hexo version is `3.8.0`.
