### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by 1366365447** [hexojs/hexo#3309]
![](http://img.027cgb.com/609450/%E5%9B%BE%E7%89%87/%E6%8D%95%E8%8E%B7.JPG)

**Comment by YoshinoriN** [comment]
@1366365447 
Because, permission error. Maybe some file or directory owner different with current user.
Please do `hexo d -g` command by correctly user.

**Comment by YoshinoriN** [comment]
Btw, sometimes cannot see your screenshot. It's very confusing for other people. 
Please upload or change to text.
