### ISSUE TITLE
Why this error happens?

### ISSUE THREAD

**Issue by dazkarieh** [hexojs/hexo#3311]
xxximac:ian root# hexo clean && hexo d -g
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Start processing
INFO  Files loaded in 5.14 s

<--- Last few GCs --->

[69389:0x104800600]   665523 ms: Scavenge 1292.1 (1438.7) -> 1283.2 (1439.2) MB, 9.6 / 0.0 ms  (average mu = 0.238, current mu = 0.159) allocation failure
[69389:0x104800600]   665583 ms: Scavenge 1296.6 (1439.7) -> 1288.0 (1441.2) MB, 8.0 / 0.0 ms  (average mu = 0.238, current mu = 0.159) allocation failure
[69389:0x104800600]   666470 ms: Mark-sweep 1300.0 (1441.2) -> 1285.9 (1439.2) MB, 856.1 / 0.0 ms  (average mu = 0.268, current mu = 0.297) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x375315841bd]
    1: StubFrame [pc: 0x3753159213d]
Security context: 0xefd8c31e589 <JSObject>
    2: importAssets [0xefdebfe44f1] [/Users/dazkarieh/Public/ian/node_modules/hexo-prism-plugin/src/index.js:~132] [pc=0x37531ea148b](this=0xefdcd388b41 <Hexo map = 0xefd674efa19>,code=0xefd5c2fda89 <Very long string[229539]>,data=0xefda27cca59 <Object map = 0xefd462f7211>)
    3: tryCatcher [0xefdea5b5c99] [/Users/dazkarie...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/bin/node]
 6: v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 7: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
11: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
12: v8::internal::String::IndexOf(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, int) [/usr/local/bin/node]
13: v8::internal::Runtime_StringIndexOfUnchecked(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x375315841bd
Abort trap: 6

**Comment by YoshinoriN** [comment]
> Ineffective mark-compacts near heap limit Allocation failed
This error means Node.js heap size are not enough.
Try to change allocate memory of Node.js.
