### ISSUE TITLE
code in blockquote display error

### ISSUE THREAD

**Issue by tarol** [hexojs/hexo#3318]
## Environment Info

Node version(`node -v`):
v10.7.0
Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.8.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-json-content@3.0.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-pug@0.0.5
+-- hexo-renderer-sass@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
+-- hexo-symbols-count-time@0.4.4
+-- hexo-wordcount@6.0.1
+-- keyword-extractor@0.0.15 extraneous
`-- rimraf@2.6.2
## For BUG

my markdown:
```markdown
> ```js
> class X {
>   #y
>   z() {
>     w()
>     #y() // 会被解析为w()#y
>   }
> }
> ```
```
output html:
![image](https://user-images.githubusercontent.com/6252853/47657952-1280a700-dbcd-11e8-8d07-629b992d9b57.png)
There is a sigil `>` at the start of each line.

**Comment by weyusi** [comment]
you don't want `<` on the output?  :confused:
```js
class X {
  #y
  z() {
    w()
    #y() // 会被解析为w()#y
  }
}
```

**Comment by weyusi** [comment]
related to https://github.com/hexojs/hexo/pull/2321

**Comment by curbengh** [comment]
Duplicate of https://github.com/hexojs/hexo/issues/2969
