### ISSUE TITLE
Tag Plugin for including files using relative paths

### ISSUE THREAD

**Issue by oravecz** [hexojs/hexo#3323]
It seems like the existing plugins for including an external file looks for that file in a specific directory structure. Imagine I have a page `/source/foo/index.md`, and I would like to `include_code` from a path relative to that page.

```md
{% include_code "My Code" lang:js ./my_code.js %}
```
This works if the code is located at `/source/downloads/code/my_code.js`, which uses a fixed path determined by global config data. 

I wrote my own tag plugin based on `include_code.js` to attempt to support relative paths. However, this depends upon the tag plugin knowing the path of the currently processed markdown file.

Is it true that it is not possible to determine the file path of the current file being processed while in the tag? Any way to achieve the import of a file path'd relative to the file being processed?

**Comment by stevenjoezhang** [comment]
Here is an example: https://github.com/theme-next/hexo-theme-next/commit/92a7afccea0af8e3971751471068b4a81af86935
Including files using paths relative to `hexo.source_dir`

**Comment by stevenjoezhang** [comment]
Currently it is not possible to determine the file path of the current file being processed while in the tag.
Please use an absolute path or a path relative to the Hexo root directory.

**Comment by SukkaW** [comment]
> Currently it is not possible to determine the file path of the current file being processed while in the tag.
> Please use an absolute path or a path relative to the Hexo root directory.

There is a related config item called `code_dir` which is for `include_code` to use.
