### ISSUE TITLE
npm install -g hexo-cli

### ISSUE THREAD

**Issue by jzwyz** [hexojs/hexo#3325]
## Environment Info

Node version(`node -v`):
node v9.8.0
npm v5.6.0

Your site `_config.yml` (Optional):
Annie

Your theme `_config.yml` (Optional): 
Annie

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG
1、npm install -g hexo-cli  success
   但是 ！！！
   只能通过 /usr/local/lib/node_modules/node/bin/hexo  使用
   hexo -v  无效，不存在hexo

**Comment by JLHwung** [comment]
Please print your `PATH` environment
```
env | grep PATH
```
