### ISSUE TITLE
"Hexo g" command generated the public folder with html files lost CSS..   

### ISSUE THREAD

**Issue by Adolf-L** [hexojs/hexo#3327]
- **Environment** 
<img width="622" alt="p1" src="https://user-images.githubusercontent.com/10137107/47959748-10807300-e027-11e8-8cf5-8336703a14b7.png">

- **hexo s command testing** 
<img width="1286" alt="p3" src="https://user-images.githubusercontent.com/10137107/47959767-4d4c6a00-e027-11e8-89e2-588783786d2d.png">

- **hexo g comand testing**
 
<img width="415" alt="p2" src="https://user-images.githubusercontent.com/10137107/47959774-7240dd00-e027-11e8-97d0-da1641ef9036.png">

<img width="1360" alt="p4" src="https://user-images.githubusercontent.com/10137107/47959778-98ff1380-e027-11e8-9bb4-d952df826daa.png">

How to fix this problem? thx

**Comment by YoshinoriN** [comment]
It is no problem.
Because, the `index.html` try to refer to local machine's css file.

For example. I opend `index.html` in my local machine.
![issue](https://user-images.githubusercontent.com/11273093/47997224-74e22600-e13e-11e8-86b7-e5653a2dfd3e.png)

My css file path in `index.html` is below.

![issue2](https://user-images.githubusercontent.com/11273093/47997225-74e22600-e13e-11e8-882c-236bce076ae7.png)

On my local machine does not exists above path . So, cannot apply css to html.

It will be fine, if you upload some hosting site or on your web server.

**Comment by tomap** [comment]
Or you can serve the content from your local machine:
* Go to the public folder
* Execute python -m SimpleHTTPServer
It will serve the site at Port 5000

**Comment by Adolf-L** [comment]
@tomap thx  
I execute python -m SimpleHTTPServer **It works**. but I config the "_config.yml" file with Github pages as below. then I executed "hexo d" it still can't  show normally. 

<img width="507" alt="pp1" src="https://user-images.githubusercontent.com/10137107/48043755-3a6e9c80-e1c3-11e8-9a30-5d141ba10a02.png">
- executed ”hexo d“ 
the files of Public folder were uploaded. you can't access it https://github.com/Adolf-L/Testing.git.io
<img width="1163" alt="pp2" src="https://user-images.githubusercontent.com/10137107/48043811-86b9dc80-e1c3-11e8-83e4-d5088b4309ba.png">

- note: css file can be access successful.
<img width="1187" alt="pp3" src="https://user-images.githubusercontent.com/10137107/48043845-bf59b600-e1c3-11e8-9cc2-9b5405c8c4e8.png">
- problem still here: https://adolf-l.github.io/Testing.git.io/
![Uploading pp4.png…]()

**Comment by Adolf-L** [comment]
@tomap  I have solved this problem. Github repo is **second directory** the url setting seems like that!
<img width="839" alt="p1" src="https://user-images.githubusercontent.com/10137107/48066649-20f04380-e209-11e8-9306-a3ad7054335c.png">

**Comment by JLHwung** [comment]
Glad to hear that the problem is solved. @Adolf-L Would you mind revise the documentation on the situation of secondary directory (that is should not end up with `.git` since it is not the url of the website but the git repository).

**Comment by Adolf-L** [comment]
> Glad to hear that the problem is solved. @Adolf-L Would you mind revise the documentation on the situation of secondary directory (that is, it should not end up with `.git` since it is not the url of the website but the git repository).

okay
