### ISSUE TITLE
Extra line break when parsing markdown

### ISSUE THREAD

**Issue by ppwwyyxx** [hexojs/hexo#333]
```
Line One,
Line Two
```

was rendered as a single line.
But now it became two lines..
It caused problems on all my posts..T_T

I noticed that this is actually a feature resulting from #222
but it did cause incompatible problems for me.. maybe an option can be provided for users to choose whether to use github-markdown?
Thanks~

**Comment by jgillich** [comment]
Can this maybe default to false, like literally everywhere else?

**Comment by kflu** [comment]
Where is the documentation about `marked` section as @floriancargoet suggested (it works BTW). I'm not able to find it in [hexo docs](https://hexo.io/docs/configuration.html).

**Comment by floriancargoet** [comment]
@kflu Rendering is handled by plugins. You'll find the documentation on the plugin's page : https://github.com/hexojs/hexo-renderer-marked

**Comment by kflu** [comment]
Thanks for the info! It would be nice to have this mentioned in the main doc for those who are not entirely familiar with the Hexo architecture. Rendering is such an important part to deserve a bit mentioning in the main project:)

**Comment by Trim21** [comment]
Real option name is `markdown` , not `marked`...
It should be 
```yaml
markdown:
  gfm: false
```
append this because this issue is the top google search result...
