### ISSUE TITLE
hexo init,clone failed

### ISSUE THREAD

**Issue by roMxx** [hexojs/hexo#3336]
I want to install hexo. First, I run "npm install hexo-cli -g" and it's ok. Then I run "hexo init". It failed.

INFO  Cloning hexo-starter to G:\Hexo
Cloning into 'G:\Hexo'...
remote: Enumerating objects: 68, done.
remote: Total 68 (delta 0), reused 0 (delta 0), pack-reused 68
Unpacking objects: 100% (68/68), done.
Submodule 'themes/landscape' (https://github.com/hexojs/hexo-theme-landscape.git) registered for path 'themes/landscape'
Cloning into 'G:/Hexo/themes/landscape'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
fatal: early EOFs:  16% (136/846), 28.01 KiB | 0 bytes/s
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
fatal: clone of 'https://github.com/hexojs/hexo-theme-landscape.git' into submodule path 'G:/Hexo/themes/landscape' failed
Failed to clone 'themes/landscape'. Retry scheduled
Cloning into 'G:/Hexo/themes/landscape'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 846 (delta 0), reused 1 (delta 0), pack-reused 841
Receiving objects: 100% (846/846), 2.55 MiB | 10.00 KiB/s, done.
Resolving deltas: 100% (445/445), done.
Submodule path 'themes/landscape': checked out '73a23c51f8487cfcd7c6deec96ccc7543960d350'
Submodule path 'themes/landscape': checked out '73a23c51f8487cfcd7c6deec96ccc7543960d350'
INFO  Install dependencies
npm WARN deprecated titlecase@1.1.2: no longer maintained
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.

> nunjucks@3.1.3 postinstall G:\Hexo\node_modules\nunjucks
> node postinstall-build.js src

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 422 packages from 501 contributors and audited 4700 packages in 42.998s
found 0 vulnerabilities

INFO  Start blogging with Hexo!

**Comment by tomap** [comment]
There are a lot of warning messages and some internal error, but in the end, it worked!
You can go to the hexo folder and type hexo s -o

**Comment by roMxx** [comment]
> There are a lot of warning messages and some internal error, but in the end, it worked!
> You can go to the hexo folder and type hexo s -o

Thank you. Yeah, I tried. But it shows:
$ hexo s -o
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
WARN  No layout: index.html

And the web page is blank.

**Comment by YoshinoriN** [comment]
@roMxx 

The `hexo init` command does clone [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape) ripository.
Today, github had [error](https://status.github.com/messages).

Mayby you could not clone from github caused by that error.
Please try again.  I think maybe it will solve :)

**Comment by roMxx** [comment]
> @roMxx
> 
> The `hexo init` command does clone [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape) ripository.
> Today, github had [error](https://status.github.com/messages).
> 
> Mayby you could not clone from github caused by that error.
> Please try again. I think maybe it will solve :)

OK. Thank you very much.
I have solved this problem.
