### ISSUE TITLE
Win10使用ssh的hexo deploy到github報錯

### ISSUE THREAD

**Issue by gyc880323** [hexojs/hexo#3339]
Macbook是可以正常deploy
但是Win10卻報錯
我已經有重新將原本放在mac上的檔案重新拉過來了
但是一樣噴錯...
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (C:\Users\Chess\Desktop\blog.chessguo.tw\node_modules\hexo-util\lib\spawn.js:37:17)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.cp.emit (C:\Users\Chess\Desktop\blog.chessguo.tw\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
```

---
_config.yml配置如下

```
deploy:
  type: git
  repo: git@github.com:gyc880323/blog.chessguo.tw.git
  branch: gh-pages
```
---
但是單純使用git push卻能正常ssh push上去
麻煩各位大大幫忙了ˊˋ

**Comment by tomap** [comment]
It seems your are missing some rights. Can you try a basic got command? Git fetch ?

**Comment by tomap** [comment]
Yes, to check your credentials

**Comment by gyc880323** [comment]
I think it is Win10 problem...
I already create a new repo and a new hexo file to check ssh deploy, but it still is ERROR
and I don't know why the file `config` in `.deploy_git/.git` is different of mac file

**Comment by YoshinoriN** [comment]
How about use https ?
Like this.

```yaml
deploy:
  type: git
  repo: https://github.com/gyc880323/blog.chessguo.tw.git
  branch: gh-pages
```

**Comment by gyc880323** [comment]
1. Yes, I'm sure my private key is correct.
2. Yes, the key is passphrase. I already try using `hexo d` in CMD, but it cannnot still work...

**Comment by tsplaycool** [comment]
> Sorry sir, my english is not good...
> so I maybe not understand what you mean completely...ˊˋ
> Do you mean using command `git push` in `.deploy_git` folder?

I think your english is queshi not good....

**Comment by Bryce1010** [comment]
So have you figured it out? I'm facing the same problem.

**Comment by Bryce1010** [comment]
I jush solved it. It seems something wrong with my network proxy swith,which make it difficult for my computer to get to github.

**Comment by gyc880323** [comment]
No~
It still doesn't work~
I have no idea. XD

**Comment by kuyeduwu** [comment]
Do you have multiple keys in your `~/.ssh/` directory? You can try to create a config file under the `~/.ssh/` directory with the following content:
```
Host github.com
HostName github.com
PreferredAuthentications publickey
IdentityFile ~/.ssh/YourPrivateKeyFileName
User Yourname
```

Maybe the ssh picked the wrong key file.

**Comment by kuyeduwu** [comment]
In you CMD, try to run `ssh-add ~/.ssh/id_rsa`, then try to deploy again.

Reference: https://github.com/hexojs/hexo/issues/2312

**Comment by gyc880323** [comment]
emmm...
It is always error `Error connecting to agent: No such file or directory`.

**Comment by April-5** [comment]
你的密钥是不是要验证的？还是-P “”？

**Comment by gyc880323** [comment]
是要驗證的 `git push`可正常跳出打密碼的訊息
但`hexo d`並沒有跳出驗證訊息 直接就噴錯了

**Comment by April-5** [comment]
> 是要驗證的 `git push`可正常跳出打密碼的訊息
> 但`hexo d`並沒有跳出驗證訊息 直接就噴錯了

emmmm，rsa的密码置空就好了，hexo-deployer-git自动帮忙输入密码了，很难受。
