### ISSUE TITLE
utcOffset ?? 

### ISSUE THREAD

**Issue by sebs** [hexojs/hexo#3341]
## Bug 

* I created about 20 documents with "hexo new". 
* cop ypasted content from old blogs
* server ran over night 
* next day I restart it, i get the error message 

```
Process failed: _posts/The-seven-lamps-of-software-architecture.md
TypeError: Cannot read property 'utcOffset' of null
```
When I delete this file, it will display the error for the next file in line. 

## Environment Info
Node 9.11.2 - last hexo from npm

**Comment by tomap** [comment]
Can you paste the content of the file? So we can reproduce?

**Comment by sebs** [comment]
its gone ... a guess from me: 

I may be was triggering hexo from a sub folder, probably the build folder. 

Just as a Idea.

**Comment by sebs** [comment]
closed, until I encounter this again?
