### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by mengru19950102** [hexojs/hexo#3342]
When I npm install hexo-cli , it reminds me that 404 not found: hexo@latest

**Comment by gautamz07** [comment]
@mengru19950102  can you try this command ::-

`npm install -g hexo-cli`

**Comment by mengru19950102** [comment]
> @mengru19950102 can you try this command ::-
> 
> `npm install -g hexo-cli`

I has try it, but it still can't work

**Comment by mengru19950102** [comment]
> @mengru19950102 can you try this command ::-

**Comment by mengru19950102** [comment]
> @mengru19950102 can you try this command ::-
> 
> `npm install -g hexo-cli`

I has try it, but it still can't work

**Comment by mengru19950102** [comment]
@gautamz07 
I had try it , but it still can't work.
