### ISSUE TITLE
window安装问题

### ISSUE THREAD

**Issue by vae-Eason** [hexojs/hexo#3344]
$ cnpm install -g hexo
npm WARN deprecated titlecase@1.1.2: no longer maintained
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
C:\Users\Administrator\AppData\Roaming\npm\hexo -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\bin\hexo

> nunjucks@3.1.3 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_modules\nunjucks
> node postinstall-build.js src

'node' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\hexo\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nunjucks@3.1.3 postinstall: `node postinstall-build.js src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nunjucks@3.1.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\.npm\.cache\cnpm\_logs\2018-11-08T09_09_53_790Z-debug.log

**Comment by vae-Eason** [comment]
还是安装问题，git，node都有了

**Comment by gautamz07** [comment]
Can you post your environment details , eg node version ?

**Comment by mengru19950102** [comment]
@vae-Eason  建议换npm试试，cnpm有时候会有些莫名其妙的坑。前面好像有issues提到是权限问题，可以参考下

**Comment by vae-Eason** [comment]
> 您可以发布您的环境详细信息，例如节点版本吗？
![image](https://user-images.githubusercontent.com/36063368/48190360-764d6180-e37d-11e8-87b9-07e2dc817a2e.png)
![image](https://user-images.githubusercontent.com/36063368/48190382-836a5080-e37d-11e8-8eff-56f3bed517cc.png)

**Comment by vae-Eason** [comment]
> @ VAE-陈奕迅 建议换NPM试试，CNPM有时候会有些莫名其妙的坑。前面好像有问题提到是权限问题，可以参考下

我换了两个版本一个是10开头，一个8开头，都不行哈

**Comment by kakarrot0109** [comment]
```

D:\Github\Website>node -v
v10.13.0

D:\Github\Website>npm -v
6.4.1

D:\Github\Website>npm install -g hexo
npm WARN deprecated titlecase@1.1.2: no longer maintained
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
C:\Users\KAKARROT\AppData\Roaming\npm\hexo -> C:\Users\KAKARROT\AppData\Roaming\npm\node_modules\hexo\bin\hexo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\hexo\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hexo@3.8.0
updated 1 package in 4.245s

D:\Github\Website>

```

好烦啊

**Comment by lenvs** [comment]
So，how to solve the problem finally. I have the same problem in mac environment. node version is v11.2.0
and the npm version is 6.4.1 .  i cant find more useful information in google.

**Comment by tomap** [comment]
See https://github.com/mozilla/nunjucks/pull/1169 might be linked

**Comment by lenvs** [comment]
i have solve the problem. in mac you cant install nodejs by brew , it will give you the latest version of nodejs ,not the LTS version . you must download the package from [https://nodejs.org](url)!. get the LTS version! 
![_20181205205238](https://user-images.githubusercontent.com/7955972/49514685-bac21380-f8cf-11e8-802d-babf45c90f9f.png)
and than you will successfully install hexo with no any error!
i dont take a try at windows ! maybe it will worked also!

**Comment by wearetime** [comment]
http://blog.51cto.com/13872978/2318972?source=dra 这个网址教程中有答案
