### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by mengru19950102** [hexojs/hexo#3345]
When I npm install hexo-cli , it reminds me that 404 not found: hexo@latest
![install](https://user-images.githubusercontent.com/7953822/48189732-cfb49100-e37b-11e8-8827-550a484e9ac5.png)

**Comment by YoshinoriN** [comment]
Which node version do you use ?
hexo-cli support higher than 6.9.0

**Comment by mengru19950102** [comment]
@YoshinoriN   node version is 8.12.0

**Comment by JLHwung** [comment]
Could you run
```
npm config get registry
```

**Comment by mengru19950102** [comment]
@JLHwung    npm config is my company's. I test that installing other packages is normal.

**Comment by JLHwung** [comment]
Got that, could you print
```
npm view hexo-cli dist.tarball
```
vs
```
npm view [any-private-package-in-your-company] dist.tarball
```
?

**Comment by mengru19950102** [comment]
@YoshinoriN  The result is different. hexo-cli shows not found. the private package shows the address.  Thanks, that maybe caused by npm config.

**Comment by vae-Eason** [comment]
> Which node version do you use ?
> hexo-cli support higher than 6.9.0
npm 6.4.1可以嘛

**Comment by mengru19950102** [comment]
@vae-Eason  ……

**Comment by YoshinoriN** [comment]
Thank you support @JLHwung 
@mengru19950102 May we close this ?

**Comment by mengru19950102** [comment]
@YoshinoriN  ok, thanks
