### ISSUE TITLE
After hexo g and hexo d, localhost:4000 has updated,but the code in github is't update

### ISSUE THREAD

**Issue by mengru19950102** [hexojs/hexo#3356]
After hexo g and hexo d, localhost:4000 has updated,but the code in github is't update

**Comment by mengru19950102** [comment]
And I config the Deployment, eg:type and repo. But it didn't deploy to github

**Comment by mengru19950102** [comment]
I have solved the question. I suggest that you can show the item more exactly in _config.yml. That should:
`deploy: 
  type: git
  repo: https://github.com/mengru19950102/mengru19950102.github.io.git`
But the model is: 
`type:
deploy: `

**Comment by tomap** [comment]
Ok, nice

**Comment by GeorgeHY** [comment]
> I have solved the question.

The problem is how to solve it, I also encountered the same problem

**Comment by mengru19950102** [comment]
@GeorgeHY  Maybe you config deployment errorly in _config.yml. The correct way is:<br>
deploy: <br>
    type: git<br>
    repo: https://github.com/mengru19950102/mengru19950102.github.io.git<br>
like it.
