### ISSUE TITLE
hexo版本问题

### ISSUE THREAD

**Issue by shunconf** [hexojs/hexo#3357]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by shunconf** [comment]
安装不了新版本，更新不到新版本，官方文档太久，网上看的资料又实现不成功

**Comment by JLHwung** [comment]
Please follow the issue template to give as enough debug information, otherwise it will be closed without further investigation.
