### ISSUE TITLE
win10 gitbash下hexo d进行git push到服务器时ssh rsa密码总是自动赋空。

### ISSUE THREAD

**Issue by April-5** [hexojs/hexo#3371]
## Environment Info

8.9.3(`node -v`):
 
environment： win10， gitbash，ssh

## For BUG

win10 gitbash下hexo d进行git push到服务器时ssh rsa密码总是自动赋空，导致permission denied。
看了下hexo-deployer-git的代码是nodejs这把spawn函数执行git push命令时无法调出交互界面导致？是否考虑修复下，还是说并不是代码的问题？

**Comment by java4candy** [comment]
我是通过生成ssh rsa公私钥时不设置密码进行hexo d的。
