### ISSUE TITLE
src refspec head does match any

### ISSUE THREAD

**Issue by naturefarming** [hexojs/hexo#3372]
When I hexo d,error shown as fellow:
`*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Administrator@CB4U9OHE1TY3N5N.(none)')
error: src refspec HEAD does not match any.
error: failed to push some refs to 'root@123.206.26.121:/var/repo/naturefarm'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: error: src refspec HEAD does not match any.
error: failed to push some refs to 'root@123.206.26.121:/var/repo/naturefarm'

    at ChildProcess.<anonymous> (C:\hexo\node_modules\hexo-util\lib\spawn.js:37:17)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.cp.emit (C:\hexo\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
`
How can i do?

**Comment by tomap** [comment]
This is a git configuration issue

LMGTFY

https://www.google.fr/search?q=git+set+email+and+name&oq=git+set+email+and+name+&aqs=chrome..69i57j0l3.8370j1j4&client=ms-android-huawei&sourceid=chrome-mobile&ie=UTF-8
