### ISSUE TITLE
Cannot load image

### ISSUE THREAD

**Issue by YueYongDev** [hexojs/hexo#3376]
## For question
When I use the link to display the image in markdown like this:
```
![关系图](https://ws3.sinaimg.cn/large/006tNbRwgy1fxo6y63a09j30m80cogo7.jpg)
```
 it cannot be loaded when i run `hexo s`, I check the dom element, as follows: 
```
<img src="" data-echo="https://ws3.sinaimg.cn/large/006tNbRwgy1fxo6y63a09j30m80cogo7.jpg" alt="关系图">
```
I don't know why the "data-echo" attribute appears. Can you give me some help？

**Comment by YoshinoriN** [comment]
@YueYongDev 
I tried to run `hexo s` in my local machine. It works fine & not appears `data-echo` attributes.
So, I think maybe this behavior caused by theme or plugin.

Could you tell me what plugin & theme do you use.

**Comment by YueYongDev** [comment]
I use the theme called ICARUS,here is its url: https://blog.zhangruipeng.me/hexo-theme-icarus/

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=yueyong1030&uid=yueyong1030%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22yueyong1030%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
yueyong1030

yueyong1030@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制

On 11/29/2018 00:01，YoshinoriN<notifications@github.com><mailto:notifications@github.com> wrote：

@YueYongDev<https://github.com/YueYongDev>
I tried to run hexo s in my local machine. It works fine & not appears data-echo attributes.
So, I think maybe this behavior caused by theme or plugin.

Could you tell me what plugin & theme do you use.

**Comment by YoshinoriN** [comment]
And, could you tell me installed packages (In package.json dependencies) ?

**Comment by YueYongDev** [comment]
> And, could you tell me installed packages (In package.json dependencies) ?

ok, here it is:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "canvas-nest.js": "^2.0.3",
    "hexo": "^3.7.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-deployer-git": "^0.3.1",
    "hexo-filter-github-emojis": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.0",
    "hexo-recommended-posts": "^1.0.3",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-marked-lazy": "^1.0.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}
```

**Comment by YoshinoriN** [comment]
`data-echo` attribute seems added by [echojs](https://github.com/toddmotto/echo).
Did you add echojs to your blog ?

**Comment by YueYongDev** [comment]
> `data-echo` attribute seems added by [echojs](https://github.com/toddmotto/echo).
> Did you add echojs to your blog ?

it works, thank you
