### ISSUE TITLE
How do you unregister a filter?

### ISSUE THREAD

**Issue by hellocosmin** [hexojs/hexo#3377]
I need to remove the meta generator filter that Hexo uses to inject a `<meta name="generator" content="Hexo 3.8.0">` tag - I don't want to have that present in my source code.

The documentation isn't very helpful on the matter of [unregistering filters](https://hexo.io/api/filter#Unregister-Filters). What are `type` and `filter`? 

For a concrete example, how would I go about removing the meta generator injection from that gets registered in `after-render:html`, as seen [here](https://github.com/hexojs/hexo/pull/3129/files)?

Thanks!

**Comment by hellocosmin** [comment]
Got it, thank you! :)

**Comment by YoshinoriN** [comment]
FYI

We implemented disable option #3653 
It will contain at Hexo v4.0
