### ISSUE TITLE
markdown语法似乎不支持拓展语法?

### ISSUE THREAD

**Issue by NERvGear27204** [hexojs/hexo#3383]
hexo v:3.8.0
比如说内嵌公式,上标,下标,高亮,图表etc.

**Comment by YoshinoriN** [comment]
Hexo's default markdown render is [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) and it based on [markd](https://github.com/markedjs/marked). It's all.
But, you can use other markdown renderer if you want to use. for example [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it).

**Comment by NERvGear27204** [comment]
Soga,Thanks a lot!
