### ISSUE TITLE
How can I make Hexo fail when partials are missing?

### ISSUE THREAD

**Issue by jakubgs** [hexojs/hexo#3384]
I just noticed that the build succeeds when partials are missing:
```
r > node_modules/.bin/hexo generate
INFO  Start processing
INFO  Files loaded in 919 ms
WARN  Partial partial/shared-partials/partials/header-nav does not exist. (in partial/header.swig)
...(a lot omitted)...
WARN  Partial partial/shared-partials/partials/after_footer does not exist. (in layout.swig)
INFO  Generated: index.html
INFO  3 files generated in 2 s
```
Why is this just a warning? The page generated when partials are missing is broken. How can I make Hexo fail if even one partial is missing?

**Comment by YoshinoriN** [comment]
I don't know why just a warning. It seems since [initial implement](https://github.com/hexojs/hexo/commit/1c2b23725ea983db9949e5a169207c2f0772b0dc#diff-ee8a1cd1cca459a05b11f850db3412a0R14).
IMHO, error or exception are better than warning.  I will try to create PR.

**Comment by jakubgs** [comment]
I did the simplest thing possible - changing the warning into `throw new Error()` - in https://github.com/hexojs/hexo/pull/3413 since there doesn't seem to be much interest in this issue. Please tell me if anything should be changed.
