### ISSUE TITLE
有没有linux 云服务器安装的文档说明呀

### ISSUE THREAD

**Issue by zhangfan-5391621** [hexojs/hexo#3386]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by YoshinoriN** [comment]
It's sorry, if misunderstanding your question. Hexo is provided by Node.js & npm.

Your question of cloud is that like AWS EC2 ?
If yes, you can install hexo after login to EC2 using by ssh.

**Comment by java4candy** [comment]
Linux只需要安装nginx即可部署发布后的博客。
本地电脑配置环境后，将hexo d生成的public文件夹push刀远程仓库，Linux部署ssh公钥后只进行push即可，也可以通过webhook实现。

**Comment by KiritoXF** [comment]
you can just search "hexo linux" in baidu.com and it will show you.

**Comment by amoslovePython** [comment]
我也有相同的疑问，不想吧hexo部署到github上，想部署到云服务器上。
