### ISSUE TITLE
CSS is not working after generate static files

### ISSUE THREAD

**Issue by rgalaz** [hexojs/hexo#3387]
node version: v8.10.0

After doing a "hexo generate" I open the "index.html" by double click (I'm using Firefox browser) it looks like CSS is not working (Just works the HTML). I'm trying to generate the static files to serve a blog by Google cloud using subject-object with a bucket. When I put all the public folder on the bucket the page looks without the CSS as well, here is the page http://www.tukulpan.tk/
Using "hexo server" I can watch everything well. 
I've looked for information on the internet without luck.
I've tried with different themes and I have the same problem.  

Thank you for your help!

**Comment by gurrrung** [comment]
How was this issue resolved?

**Comment by stevenjoezhang** [comment]
Don't double-click to open the html page (the browser will use the file protocol instead of the usual http protocol, the path of static files will not be resolved correctly). Instead, use a web server to serve your website.

**Comment by gurrrung** [comment]
I was a using a theme and even serving on Github pages wasn't working. But my solution I have commented here: https://github.com/adisaktijrs/hexo-theme-minima/issues/24
