### ISSUE TITLE
Hexo Landscape, hide date from post?

### ISSUE THREAD

**Issue by s10wen** [hexojs/hexo#3391]
In my markdown I can write `comments: false` and that hides comments. Would be awesome if you could do the same with `date: false`. I've tried a few things, but can't get it to work.

Wondering if anyone else has done this, or could point me in the right direction please?

**Comment by YoshinoriN** [comment]
@s10wen 
Currently hexo is set date automatically, even if set false to date.

One way, you can define original variable to post by yourself.
I wrote [example. please see](https://github.com/YoshinoriN/hexo-test/commit/5e1a97e7663df2988e08ab3378928f38cd1777cc).

Sorry, I can't came up with ohter way.

**Comment by s10wen** [comment]
Of course! Cheers, arigatou gozaimasu!
