### ISSUE TITLE
新增页面部署成功但是访问页面404

### ISSUE THREAD

**Issue by 1139195320** [hexojs/hexo#3394]
自己的博客，新增页面，本地hexo s访问4000端口页面都是正常的，hexo clean, hexo g, hexo d都执行了，部署成功，在远程仓库可以看到上面后的页面，但是在浏览器中访问，原来的页面是正常的，新的页面始终是404，刷缓存也没用，希望能有朋友指点下，蟹蟹！

**Comment by 1139195320** [comment]
已解决，域名解析的问题。。。

**Comment by Harrypotterrrr** [comment]
> 已解决，域名解析的问题。。。

请问域名解析可以具体一下么？

**Comment by 1139195320** [comment]
> > 已解决，域名解析的问题。。。
> 
> 请问域名解析可以具体一下么？

您好，这个问题已经过去了几个月，具体的我不大记得了，可能是由于项目托管到coding和github两个平台，域名解析的时候需要添加两条CNAME的记录，一条默认的指向coding的博客域名，一条境外的指向github的博客域名，当时可能就是这之中出了问题，您参考下看是否有帮助。
