### ISSUE TITLE
 Global asset folder not working when source dir is changed another path

### ISSUE THREAD

**Issue by xiaomingplus** [hexojs/hexo#3398]
## Environment Info

Node version(`node -v`):v8.12.0

Your site `_config.yml` (Optional): default

Your theme `_config.yml` (Optional): default

Hexo and Plugin version(`npm ls --depth 0`): default

## For BUG

When I changed the config `source` value to `../source`,the source images can't be generated.Here is the config:

```yaml
source_dir: ../source
```

You can run: 

```bash
hexo new test
cd ../source
mkdir images
# copy a example image to images
hexo generate
```

The images folder can not be generated.

**Comment by YoshinoriN** [comment]
@xiaomingplus 
One question. Is it only assets (image) only ? 
There is a possibility that this issue relate #3410

**Comment by xiaomingplus** [comment]
@YoshinoriN not only `image` folder,all assets can't be copied to the public dir.
