### ISSUE TITLE
url_for(page.path) gives wrong path for prev&next page

### ISSUE THREAD

**Issue by HigHwindEx** [hexojs/hexo#3400]
When I used ejs to get the url of prev&next page, I found the path given was wrong. I think it's because I set my blog in a subdirectory. (In fact it's `www.example.com/blog/`)
For example, my prev post lies in `www.example.com/blog/post1.html`. When Hexo renders post 2, `url_for(page.prev.path)` gives `www.example.com/blog//blog/post1.html`, which lead the link to 404.
Though it does work, do I have to use `page.prev.path` directly?

**Comment by YoshinoriN** [comment]
The [`url_for`](https://hexo.io/docs/helpers#url-for) return from root path. How about [`relative_url`](https://hexo.io/docs/helpers#relative-url) ?

If you want to get absolute path, how about `config.root + page.prev.path` ? It will be return `www.example.com/blog/post1.html`

**Comment by HigHwindEx** [comment]
> The [`url_for`](https://hexo.io/docs/helpers#url-for) return from root path. How about [`relative_url`](https://hexo.io/docs/helpers#relative-url) ?
> 
> If you want to get absolute path, how about `config.root + page.prev.path` ? It will be return `www.example.com/blog/post1.html`

Thanks a lot, dear YoshinoriN.

I think it will be better if Hexo solves this small problem, because the doc of Hexo [recommends](https://hexo.io/docs/variables#Page-Variables) using function `url_for(page.path)`.

**Comment by SukkaW** [comment]
In #3701 full_url_for helper is added toHexo and will be released with Hexo v4. Use full_url_for helper after Hexo v4 if you need to get absolute path.
