### ISSUE TITLE
执行 hexo d 没有任何输出,发现 githup 代码没有提交

### ISSUE THREAD

**Issue by hjmJhon** [hexojs/hexo#3402]
after excute hexo d, no any outputs.  there is _config_yml:
Deployment
Docs: https://hexo.io/docs/deployment.html
deploy: https://github.com/hjmJhon/hjmjhon.githup.io.git
type: git
branch: master

**Comment by bolunzhang** [comment]
1. I think there might be a typo in the repository name. hjmjhon.githu**p**.io.git or hjmjhon.githu**b**.io.git?
2. Make sure you have hexo-deployer-git installed. It should appear in your `package.json` file.

[document](https://hexo.io/docs/deployment.html)

**Comment by hjmJhon** [comment]
thank you very much ! I discory the bug I made.

**Comment by YoshinoriN** [comment]
May we close ?
