### ISSUE TITLE
贴Java代码片上去，换行渲染异常

### ISSUE THREAD

**Issue by zmosquito** [hexojs/hexo#3403]
就贴了一段Java代码片上去，然后前面的空格就全部被true代替了，怎么解决啊

**Comment by momocow** [comment]
也許你需要更多的描述來得到更多的幫助, 例如你使用的主題和插件，你需求的文本和錯誤的文本。

試著使用以下語法看看是否得到解決：
`{% codeblock %}` https://hexo.io/zh-tw/docs/tag-plugins.html#Code-Block
`{% raw %}` https://hexo.io/zh-tw/docs/tag-plugins.html#Raw
