### ISSUE TITLE
No Amazon Linux AMI Support.

### ISSUE THREAD

**Issue by MichaelPanPRC** [hexojs/hexo#3406]
## Environment Info
Node version(`node -v`):v10.15.0
`cat /etc/system-release`:Amazon Linux AMI release 2018.03
## For BUG
When `npm install -g hexo-cli`, it goes with two warnings
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
And when visiting with IP or domain, browser shows 403.

**Comment by YoshinoriN** [comment]
These warning are not hexo problem and they are not affect to hexo.

Also 403 error is not hexo problem.  It's permission error of web server. Please see [MDN doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403).

**Comment by tcrowe** [comment]
`fsevents` warnings come from [chokidar](/paulmillr/chokidar) module when `npm config set optional false` is set.

That part doesn't cause a lot of problems.

@MichaelPanPRC Can you provide more information what you're doing when you see 403 error? 🤗

**Comment by jodumont** [comment]
@MichaelPanPRC if you only run Hexo in your VM and don't plan more;
may I recommend you to run nodejs and hexo through [Docker](https://hub.docker.com/_/node) with [ECS](
https://aws.amazon.com/getting-started/tutorials/deploy-docker-containers/?nc2=type_a) it will be more cost effective and less maintenance for you.
