### ISSUE TITLE
How can we support mhchem ？

### ISSUE THREAD

**Issue by chem1024** [hexojs/hexo#3407]
Mathjax has a third-party plugin mhchem, can it be supported? I can't display the chemical equation properly
$\ce{CO2 + C -> 2 CO}$

**Comment by unnamed42** [comment]
according to [official website](https://mhchem.github.io/MathJax-mhchem/]):
```
<script type="text/x-mathjax-config">
MathJax.Ajax.config.path["mhchem"] =
  "https://cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.0";
MathJax.Hub.Config({
  TeX: {
    extensions: ["[mhchem]/mhchem.js"]
  }
});
</script>
```
Consult your theme author to add these into `<head>` section, or insert it into your markdown file.

**Comment by tcrowe** [comment]
It's possibly configurable in the `./_config.yml` too: https://github.com/hexojs/hexo-math#config

**Comment by tcrowe** [comment]
@chem1024 If you get it working can you let us know and close it out please?

**Comment by chem1024** [comment]
> @ chem1024如果你有工作可以告诉我们并关闭它吗？

I use NexT theme, it support mhchem now. thx.
