### ISSUE TITLE
没有theme，也没有任何样式。hexo s在本地的是正常的

### ISSUE THREAD

**Issue by sallyslove** [hexojs/hexo#3412]
## Environment Info
win64 
Node version(`node -v`):
$ node -v
v8.10.0

Your site `_config.yml` (Optional):
deploy:
  type:git
  repo:git@github.com:sallyslove/sallyslove.github.io.git
  branch:master

Your theme `_config.yml` (Optional): 
没改，就是default的

Hexo and Plugin version(`npm ls --depth 0`): 
$ npm ls --depth 0
hexo-site@0.0.0 C:\Lynn\private\hexo-blog
+-- hexo@3.8.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2

## For Questions
跟着教程做了一些，hexo s没有任何问题，hexo d也没有报错。local起来的server是正常的，deploy之后的明显没有deploy上去，新加的post也没有出来。没有任何theme和样式
全程没有明显的错误。chrome开发者模式也没有错误，不知道哪里不对了。
$ hexo deploy --debug
09:06:34.471 DEBUG Writing database to C:\Lynn\private\hexo-blog/db.json
09:06:34.501 DEBUG Hexo version: 3.8.0
09:06:34.501 DEBUG Working directory: C:\Lynn\private\hexo-blog\
09:06:34.801 DEBUG Config loaded: C:\Lynn\private\hexo-blog\_config.yml
09:06:34.871 DEBUG Plugin loaded: hexo-deployer-git
09:06:34.881 DEBUG Plugin loaded: hexo-generator-archive
09:06:34.881 DEBUG Plugin loaded: hexo-generator-index
09:06:34.891 DEBUG Plugin loaded: hexo-generator-category
09:06:34.891 DEBUG Plugin loaded: hexo-generator-tag
09:06:34.901 DEBUG Plugin loaded: hexo-renderer-ejs
09:06:34.901 DEBUG Plugin loaded: hexo-renderer-marked
09:06:34.911 DEBUG Plugin loaded: hexo-renderer-stylus
09:06:35.031 DEBUG Plugin loaded: hexo-server
09:06:35.031 DEBUG Script loaded: themes\landscape\scripts\fancybox.js
09:06:35.041 DEBUG Database saved

**Comment by nottvlike** [comment]
_config.yml 里的 url, root 没改吧

**Comment by sallyslove** [comment]
目录是hexo init 生成的，改成这样了：
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://sallyslove.github.io/hexo-blog
root: /hexo-blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

本地的目录是：/c/Lynn/private/hexo-blog

访问的链接是：https://sallyslove.github.io/
https://sallyslove.github.io/hexo_blog 直接报404了。

**Comment by sallyslove** [comment]
有这几个warning：
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

没有报错

**Comment by sallyslove** [comment]
I have no .deploy_git after deploy. Is it right?

**Comment by sallyslove** [comment]
wrong configuration in config file. close the issue

**Comment by Davidzhangyuanhan** [comment]
您好 我出现相同的问题 怎么解决的呢？

**Comment by sallyslove** [comment]
你好，我后来是部署的config的地方，少一个空格。你看看是不是configuration文件有问题。

**Comment by Davidzhangyuanhan** [comment]
> 你好，我后来是部署的config的地方，少一个空格。你看看是不是configuration文件有问题。

谢谢，我已经解决的，我是自己的域名有点问题，域名得和你的用户名完全一样才行。
