### ISSUE TITLE
can't find <blog>_config.yml

### ISSUE THREAD

**Issue by 19uni94** [hexojs/hexo#3416]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

Ｉcan't find path blog    _config.yml ,  i don't no what  blog was happened, bcuz  i can't  update my blog for two years. 
so plz help me to find blog   _config.yml  

thx!!!

**Comment by gautamz07** [comment]
You should find the config file in the root of your hexo blog.

![capture](https://user-images.githubusercontent.com/5736301/51038433-43238a80-15d9-11e9-8097-700c0fa53ca5.JPG)

**Comment by YoshinoriN** [comment]
@java4candy @gautamz07  Thank you very much for support 😄 

@19uni94 May we close it?
