### ISSUE TITLE
hexo g不能将.gitlab-ci.yml生成到public目录

### ISSUE THREAD

**Issue by java4candy** [hexojs/hexo#3417]
使用最新版本的hexo 3.8利用gitlab.com的CI/CD构建静态博客pages时，hexo d不能将.gitlab-ci.yml生成到public目录，使得每次push后需要手动在仓库添加yml文件。

**Comment by momocow** [comment]
> Source folder. Place your assets (e.g. CSS and JavaScript files) here. Hexo ignores hidden files and files or folders prefixed with _ (underscore).
> https://hexo.io/docs/themes#source

文檔的敘述是藏在這個地方, 請慢用!

畢竟這個文件也跟博客內容無關,
真的有需求, 自己寫個插件監聽 `generateAfter` 事件, 搬移這個檔案吧。
https://hexo.io/api/events#generateAfter

**Comment by java4candy** [comment]
> > Source folder. Place your assets (e.g. CSS and JavaScript files) here. Hexo ignores hidden files and files or folders prefixed with _ (underscore).
> > https://hexo.io/docs/themes#source
> 
> 文檔的敘述是藏在這個地方, 請慢用!
> 
> 畢竟這個文件也跟博客內容無關,
> 真的有需求, 自己寫個插件監聽 `generateAfter` 事件, 搬移這個檔案吧。
> https://hexo.io/api/events#generateAfter

我将.gitlab-ci.yml放在D:\hexo-blog\themes\next\source或者D:\hexo-blog或者D:\hexo-blog\source，都不能生成到public目录。

**Comment by momocow** [comment]
> Hexo ignores **hidden files** and files or folders prefixed with _ (underscore).

@java4candy `.` 開頭的檔名也被當作是隱藏檔了, 這是 Linux 系統上的慣例, 所以 Hexo 忽略了它。

另外, Hexo 主要是用來處理與 Blog 文本相關的文件, CI 設定檔這一類的文件建議是自己另外寫個建構腳本, 在 `hexo g` 之後處理。

舉個例子, 在你 `package.json` 中加入 build 腳本 (如下所示), 並改用 `npm run build` 建構博客。
```json
{
  "scripts": {
    "build": "hexo g && shx cp D:\\hexo-blog\\.gitlab-ci.yml D:\\hexo-blog\\public\\.gitlab-ci.yml"
  }
}
```
示例中使用了 `shx` 依賴, 透過 `npm i shx -D` 安裝為開發依賴。
