### ISSUE TITLE
.md files can not compile “{{a>b?a = b}}”

### ISSUE THREAD

**Issue by huangyijan** [hexojs/hexo#3418]
## Environment Info

Node version(`node -v`): 9.3.0

Your site `_config.yml` (Optional): 

Your theme `_config.yml` (Optional):  next

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG
.md files can not compile sentence like “{{a>b?a = b}}” ![](https://raw.githubusercontent.com/huangyijan/ImageRepository/master/Image/1535186223(1).jpg)"

**Comment by YoshinoriN** [comment]
Please try to use [raw helpre](https://hexo.io/docs/tag-plugins#Raw).

```ejs
{% raw %}
content
{% endraw %}
```

**Comment by huangyijan** [comment]
right
