### ISSUE TITLE
video post

### ISSUE THREAD

**Issue by ivanjimenez** [hexojs/hexo#342]
Hi!

 How can post a video to a post. Could be a link to Gdocs or youtube.

Thanks!

**Comment by nickdesaulniers** [comment]
How about if we prefer to host our video content as part of the static content, and not on sites like youtube or vimeo?

**Comment by NoahDragon** [comment]
@nickdesaulniers have you taken a look at the following plugins?
https://github.com/stephenmkbrady/hexo-tag-html5
https://github.com/NextMoe/hexo-tag-dplayer
