### ISSUE TITLE
 pna.nextTick is not a function

### ISSUE THREAD

**Issue by MrOxygen** [hexojs/hexo#3420]
## Environment Info

Node version(`$ 6.5.0-next.0`):

## For BUG

when i want to install hexo,it reported the same error:

$ npm install hexo-cli -g                                                        
npm ERR! pna.nextTick is not a function                                          
npm ERR! pna.nextTick is not a function                                                                                                                           npm ERR! A complete log of this run can be found in:                             
npm ERR!     C:\Users\yangq\AppData\Roaming\npm-cache\_logs\2019-01-17T10_58_26_ 461Z-debug.log
--

**Comment by tomap** [comment]
Also, the minimum node js version is 6.9 

You should update your node installation to at least 10, to be safe
