### ISSUE TITLE
Feature request: add options argument to js helper

### ISSUE THREAD

**Issue by YoshinoriN** [hexojs/hexo#3426]
## Proposal

I want to apply `async` [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Attributes) to `<script>` tag using by [js-helper](https://hexo.io/docs/helpers#js)

**Comment by SukkaW** [comment]
The issue is the subset of #3687 and is fixed in #3681. Newest version of Hexo already has this feature.
