### ISSUE TITLE
hexo的生成过程

### ISSUE THREAD

**Issue by Mengbuxiu** [hexojs/hexo#3432]
Hexo生成静态页面的是基于MarkDown文件生成吗？是否能在网站上实时输入并更新呢？能够自己填充更多的页面吗？

**Comment by Liam0205** [comment]
Yes, the static pages are generated from markdown files. You could try CI.

**Comment by Mengbuxiu** [comment]
> Yes, the static pages are generated from markdown files. You could try CI.

fine.How do I add my customized page？

**Comment by YoshinoriN** [comment]
@Mengbuxiu 

You can make customized layout by yourself.
For example, by hexo-theme-landscape [has seven template](https://github.com/hexojs/hexo-theme-landscape/tree/acc0b08ff703c31568052d1a539ef9de7e26a307/layout).

You can specify which layout do you use by each post.

```
---
layout: post   //specify which layout do you use
title: "example"
date: 2018-11-13 19:02:46
---
```
