### ISSUE TITLE
Cannot GET / after hexo clean

### ISSUE THREAD

**Issue by ocipap** [hexojs/hexo#3433]
After hexo clean, Can not create index.html under the public folder.

**Comment by IcyW** [comment]
same

**Comment by manuelalbaladejo** [comment]
Same here.

**Comment by YoshinoriN** [comment]
@ocipap @IcyW @manuelalbaladejo 
Did you execute `hexo generate` after `hexo clean`?

**Comment by ChaseCarlson** [comment]
Same here

**Comment by uiolee** [comment]
If there is a problem, please provide more information
