### ISSUE TITLE
【question】How to deploy hexo on my personal server instead of github? 

### ISSUE THREAD

**Issue by amoslovePython** [hexojs/hexo#3435]
## For question

How to deploy hexo on my personal server instead of github? 
怎么把hexo部署到个人服务器上，而不是默认部署到github上呢 ?

**Comment by Westlifers** [comment]
Would u mind telling me how? Im working on this recently

**Comment by amosnothing** [comment]
> Would u mind telling me how? Im working on this recently

https://hexo.io/zh-cn/docs/one-command-deployment
