### ISSUE TITLE
The post custom permalink is nexpected

### ISSUE THREAD

**Issue by drrrMikado** [hexojs/hexo#3442]
## Environment Info

Node version(`node -v`): `V11.8.0`

Your site `_config.yml` (Optional): 
```yaml
new_post_name: :year-:month-:day-:title.md # File name of new posts
# permalink: :year/:month/:day/:post_title/
# permalink: :post_title
```

Hexo and Plugin version(`npm ls --depth 0`): 
```
+-- hexo@3.8.0
+-- hexo-deployer-git@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+--renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.3.3
npm ERR! peer dep missing: eslint@>= 4.12.1, required by babel-eslint@10.0.1
--
```

## For BUG
In my post.md, It set `permalink: first-blog`, and I exec `hexo server`, I got a url `http://localhost:4000/2019/01/26/first-blog/`. But I want to get `http://localhost:4000/first-blog/`.
What do I have to do to get the results I want?
Thanks.

**Comment by YoshinoriN** [comment]
> It set `permalink: first-blog`

What do you mean by that? Would you tell me detail?

**Comment by drrrMikado** [comment]
Thanks for you reply.
It’s my problem, my description is not clear.
I want an md document to have a permalink. In [Front-matter](https://hexo.io/docs/front-matter), I don't find info about post permalink.

For example, I have a `2019-01-31-first-blog.md`, is there any way to get `http://localhost:4000/first-blog`(`localhost` is just an example) to point to `2019-01-31-first-blog.md`?

**Comment by YoshinoriN** [comment]
@drrrMikado 

If default permalink is `:title/` and it's okay with you. I have a solution.

`_config.yml`

```yaml
root: /
permalink: :title/
permalink_defaults:
```

A post Font-matter.

```
---
title: "This is a test"
date: 2019-01-31 20:44:31
permalink: first-blog
---
```

Hexo has cache in `db.json`. Please delete it if not works well.

Example is [https://github.com/YoshinoriN/hexo-test/commit/19882dcdebe649e7c54fa1303b8bf8fb1f5790b8](here).

----

But, If default permalink is not `:title/` the Front-matter's permalink seems not override correctly.
I thinks hexo team shold investigate this matter.

**Comment by drrrMikado** [comment]
Thanks. It's work for me.
