### ISSUE TITLE
[BUG]hexo ERROR Asset render failed: lib/needsharebutton/needsharebutton.css

### ISSUE THREAD

**Issue by lingjiameng** [hexojs/hexo#3443]
## BUG

hexo ERROR Asset render failed: lib/needsharebutton/needsharebutton.css

打开next主题needmoreshare2后，分享链接不生效
生成的sharebutton的css文件为空 
不过整体仍是可运行的
日志如下：
[debug.log](https://github.com/hexojs/hexo/files/2817352/debug.log)

**Comment by tcrowe** [comment]
Related post: https://github.com/theme-next/hexo-filter-optimize/issues/4

**Comment by tcrowe** [comment]
@lingjiameng Can you try to upgrade theme next to latest version? It may be fixed. https://github.com/theme-next/hexo-theme-next
