### ISSUE TITLE
移动端菜单问题

### ISSUE THREAD

**Issue by DearDewey** [hexojs/hexo#3444]
## Environment Info

Node version(`node -v`):
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 8.2.1
v8: 5.8.283.41
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

Your site `_config.yml` (Optional):
# Category & Tag
default_category: uncategorized
category_map:
tag_map:
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: landscape
deploy:
type: git
repository: https://github.com/DearDewey/museum.github.io.git
branch: master

Your theme `_config.yml` (Optional): 
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
excerpt_link: Read More
fancybox: true
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
index_widgets:
archive_type: 'monthly'
show_count: false
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.8.0
+-- hexo-deployer-git@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.3.3

## For BUG

问题设备：华为P10
Hexo主题：默认主题
问题1：移动端打开Hexo的网址（https://hexo.io/zh-cn/），点击左上角的菜单按钮，弹出菜单，页面可以上下左右拖动（Chrome的模拟器也会如此）；
问题2：移动端打开自己生成的网址(childhoodmuseum.shop)，无法打开左上角菜单（所有配置均为默认）
![tim 20190201102746](https://user-images.githubusercontent.com/47207107/52099032-6061dc80-260c-11e9-98f5-0d6966654847.png)

**Comment by tcrowe** [comment]
@hexojs/core I wonder if instead of "non-english" tag we can tag with lang-zh-cn, lang-ja, lang-kr, lang-fr. I can make a bot for that using [franc](https://github.com/wooorm/franc).

**Comment by tcrowe** [comment]
@DearDewey This theme? https://github.com/hexojs/hexo-theme-landscape

**Comment by DearDewey** [comment]
@tcrowe Yes,This theme

**Comment by tcrowe** [comment]
I put it in a small, mobile, view so the menu shows up.

<img width="542" alt="screen shot 2019-02-13 at 12 46 45 pm" src="https://user-images.githubusercontent.com/1634015/52739136-7917ae00-2f8d-11e9-9ee3-58f5d9381ab2.png">

If I click the menu it comes out from the left.

<img width="404" alt="screen shot 2019-02-13 at 12 46 51 pm" src="https://user-images.githubusercontent.com/1634015/52739184-96e51300-2f8d-11e9-9371-1c11379180be.png">

---

What can we look at next, @DearDewey ?

**Comment by DearDewey** [comment]
@tcrowe The problem was solved,Thank you!

**Comment by tcrowe** [comment]
Thank you @DearDewey 👋
