### ISSUE TITLE
Mac 使用npm安装hexo缺少权限问题

### ISSUE THREAD

**Issue by odeinjul** [hexojs/hexo#3447]
##  安装时显示Missing write access to /usr/local/lib/node_modules
已解决 建议在官方教程的`npm install -g hexo-cli`前加上一个sudo

**Comment by tcrowe** [comment]
@joshuawsr Maybe `node` & `npm` are installed as root user?

**Comment by stevenjoezhang** [comment]
If `node` and `npm` is installed through Homebrew, you should have full access to `/usr/local/lib/node_modules`, and no `sudo` required. Using `chown` may make it work again.
