### ISSUE TITLE
Error: Spawn failed at ChildProcess.<anonymous> 

### ISSUE THREAD

**Issue by TianLiPa** [hexojs/hexo#3449]
BUG:
node -v: v10.15.1
_config.yml:
# Hexo Configuration
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/TianLiPa/tianlipa.github.io
  branch: master
  message: 
When I use hexo deploy:
On branch master
nothing to commit, working directory clean
fatal: unable to access 'https://github.com/TianLiPa/tianlipa.github.io/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Spawn failed
    at ChildProcess.<anonymous> (D:\Hexo\Hexo\node_modules\hexo-util\lib\spawn.js:52:19)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.cp.emit (D:\Hexo\Hexo\node_modules\cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

**Comment by tcrowe** [comment]
Hi @TianLiPa :wave:

Can you try this please?

`repo: git@github.com/TianLiPa/tianlipa.github.io.git`

**Comment by TianLiPa** [comment]
@tcrowe
Now it became this:
fatal: 'git@github.com/TianLiPa/tianlipa.github.io.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[41mFATAL[49m Something's wrong. Maybe you can find the solution here: [4mhttp://hexo.io/docs/troubleshooting.html[24m
[33mError: Spawn failed
    at ChildProcess.<anonymous> (D:\Hexo\Hexo\node_modules\hexo-util\lib\spawn.js:52:19)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.cp.emit (D:\Hexo\Hexo\node_modules\cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)[39m

**Comment by tcrowe** [comment]
There's a few things which might fix this error, @TianLiPa.

Can you please upgrade these apps?
+ git
+ openssl
+ ssh
+ curl

Another thing that could help would be to make sure git can access your SSH key, the key is added to the ssh-agent, and maybe check if the key is added into github SSH keys.

Can you check those things and msg me back please? Thanks! 🤗

**Comment by TianLiPa** [comment]
> 有一些东西可以解决这个错误，@ TianLiPa。
> 
> 你能升级这些应用程序吗？
> 
> * 混帐
> * OpenSSL的
> * SSH
> * 卷曲
> 
> 另一件可能有用的事情是确保git可以访问你的SSH密钥，密钥被添加到ssh-agent，也许可以检查密钥是否被添加到github SSH密钥中。
> 
> 你能检查一下这些东西并给我回信吗？谢谢！🤗

Thanks a lot and I solved the problem.
I used this: repo: https://TianLiPa:{MY GITHUB PASSWORD}@github.com/TianLiPa/tianlipa.github.io.git and it is all right now.

**Comment by tcrowe** [comment]
![👍🏻](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)
