### ISSUE TITLE
A problem with {% asset_image slug  [title] %}

### ISSUE THREAD

**Issue by lisuisheng** [hexojs/hexo#3450]
I have met a problem with {% asset_image slug [title] %}.
`{% asset_img MVC和MVVM的基本原理图.png MVC和MVVM的基本原理图 %}`

when I use `hexo g` to generate my blog,  I met a wrong path here.
 `<img class="img-ajax" src="/blog/img/loading.gif" data-src="/blog/blog/2019/02/13/mvc&&mvvm/MVC和MVVM的基本原理图.png" alt="mvc和mvvm">`

it should be like this.
` <img class="img-ajax" src="/blog/img/loading.gif" data-src="/blog/2019/02/13/mvc&&mvvm/MVC和MVVM的基本原理图.png" alt="mvc和mvvm">`

**Comment by YoshinoriN** [comment]
@lisuisheng 
I will try to investigate. Would you tell me detail?

* `post_asset_folder` setting (in `_config.yml`) is `true` or `false`?
* Where you stored png file?
* Which version do you use?

**Comment by lisuisheng** [comment]
> @lisuisheng
> I will try to investigate. Would you tell me detail?
> 
> * `post_asset_folder` setting (in `_config.yml`) is `true` or `false`?
> * Where you stored png file?
> * Which version do you use?
1. I have set it true.
![image](https://user-images.githubusercontent.com/19186819/52845378-ee2be480-3141-11e9-9d92-9fb167af5420.png)

2. My png file are stored in /blog/source/_posts/[article title]/xxx.png

3. The Node version I use is v8.9.4 with npm v5.6.0. hexo version is 3.8.0.

**Comment by YoshinoriN** [comment]
@lisuisheng 
Sorry so late reply. Hmm... I can't reproduce it... 🤔 
How about this?

```md
![MVC和MVVM的基本原理图.png](MVC和MVVM的基本原理图.png)
```

I think this is maybe the same as `{% asset_img MVC和MVVM的基本原理图.png MVC和MVVM的基本原理图 %}`
