### ISSUE TITLE
error ENOSYS: function not implemented, symlink '../atob/bin/atob.js'

### ISSUE THREAD

**Issue by fireguy** [hexojs/hexo#3451]
## Environment Info

Node version(`node -v`):10.15.1

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
9042 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
9043 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
9045 verbose stack Error: ENOSYS: function not implemented, symlink '../atob/bin/atob.js' -> '/media/slfu/8898-2E14/github/fireguy.github.io/node_modules/.bin/atob'
9046 verbose cwd /media/slfu/8898-2E14/github/fireguy.github.io
9047 verbose Linux 4.15.0-45-generic
9048 verbose argv "/home/slfu/.nvm/versions/node/v10.15.1/bin/node" "/home/slfu/.nvm/versions/node/v10.15.1/bin/npm" "install"
9049 verbose node v10.15.1
9050 verbose npm  v6.4.1
9051 error path ../atob/bin/atob.js
9052 error code ENOSYS
9053 error errno -38
9054 error syscall symlink
9055 error ENOSYS: function not implemented, symlink '../atob/bin/atob.js' -> '/media/slfu/8898-2E14/github/fireguy.github.io/node_modules/.bin/atob'
9056 verbose exit [ -38, true ]
## For question

9042 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
9043 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
9044 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
9045 verbose stack Error: ENOSYS: function not implemented, symlink '../atob/bin/atob.js' -> '/media/slfu/8898-2E14/github/fireguy.github.io/node_modules/.bin/atob'
9046 verbose cwd /media/slfu/8898-2E14/github/fireguy.github.io
9047 verbose Linux 4.15.0-45-generic
9048 verbose argv "/home/slfu/.nvm/versions/node/v10.15.1/bin/node" "/home/slfu/.nvm/versions/node/v10.15.1/bin/npm" "install"
9049 verbose node v10.15.1
9050 verbose npm  v6.4.1
9051 error path ../atob/bin/atob.js
9052 error code ENOSYS
9053 error errno -38
9054 error syscall symlink
9055 error ENOSYS: function not implemented, symlink '../atob/bin/atob.js' -> '/media/slfu/8898-2E14/github/fireguy.github.io/node_modules/.bin/atob'
9056 verbose exit [ -38, true ]

**Comment by YoshinoriN** [comment]
This is not hexo issue.
Please check your symboliclink about this line.

```
../atob/bin/atob.js' -> '/media/slfu/8898-2E14/github/fireguy.github.io/node_modules/.bin/atob'
```

**Comment by tcrowe** [comment]
`atob` is in a few of our modules:

<img width="916" alt="screen shot 2019-02-13 at 12 55 38 pm" src="https://user-images.githubusercontent.com/1634015/52739721-baf52400-2f8e-11e9-927b-cf6afc4a8172.png">

`npm` is trying to link it's CLI but it cannot.

This device `/media/slfu/8898-2E14` may not support symlinks.

`ENOSYS: function not implemented, symlink '../atob/bin/atob.js' -> '/media/slfu/8898-2E14/github/fireguy.github.io/node_modules/.bin/atob'`

**Comment by tcrowe** [comment]
A note for JS coders searching: You don't need `atob` in node. Use `Buffer.from("KCDNocKwIM2cypYgzaHCsCk=", "base64").toString("utf8")`
