### ISSUE TITLE
post without "hexo new post" but "archive" cannot recognize list

### ISSUE THREAD

**Issue by HenryPaik1** [hexojs/hexo#3453]
I just create a `*.md doc` in my `_post` directory but the problem is that archive index don't reflect them.
archive index.html only work by "hexo new post" command.

How could I update archive index(align with actual post list)?

**Comment by tcrowe** [comment]
Hi @HenryPaik1 :wave:

Sometimes if there are many changes it can help to reset the cache:

```sh
hexo clean
hexo server --debug
```

Can you try this and see if it's fixed?

**Comment by HenryPaik1** [comment]
Unfortunately, It doesn't work.
I have posted about 30 articles, half of which are created directly(it means I directly put them(~.md) into `post_ dir`, instead of using `hexo new post`), but `archive>index.html ` do not recognize them.

Would you advise me to fix it?

**Comment by tcrowe** [comment]
It's an odd notation you're using. What kind of operating system do you use? 🤔

If I create a hexo blog from `hexo init` I get this type of structure:

<img width="497" alt="screen shot 2019-02-14 at 7 26 30 pm" src="https://user-images.githubusercontent.com/1634015/52830593-a0a26f80-308e-11e9-8798-65b350a44732.png">

<img width="227" alt="screen shot 2019-02-14 at 7 28 11 pm" src="https://user-images.githubusercontent.com/1634015/52830609-b44dd600-308e-11e9-9029-c559ed4d493c.png">

In your posts above you put the posts directory as `_post` and `post_`. It is exactly `_posts` though.

If that is correct you can check if your MD files have the correct "front-matter" at the top.
https://hexo.io/docs/front-matter

```yaml
---
title: Hello World
date: 2013/7/13 20:46:25
---
```

Would you be able to check on those things and let me know if you can get it working, @HenryPaik1 ?

**Comment by HenryPaik1** [comment]
Oh, my mistake--notation `_posts`, you are right.

I just checked things which you said and there seems to be no problem:
1) `hexo init`(same as my current blog_dir structure)
![3](https://user-images.githubusercontent.com/42961175/52891973-ea47a300-31d1-11e9-8924-8a88e1733c68.png)

![4](https://user-images.githubusercontent.com/42961175/52891997-16632400-31d2-11e9-963f-582805ea1504.png)
---
2) current one
![1](https://user-images.githubusercontent.com/42961175/52892061-8f627b80-31d2-11e9-9dae-d50753ce6f08.png)

![2](https://user-images.githubusercontent.com/42961175/52892064-92f60280-31d2-11e9-8be1-3633acd7ee64.png)
---

3) front-matter
![5](https://user-images.githubusercontent.com/42961175/52892080-a99c5980-31d2-11e9-83db-26e6bbfc9b27.png)
