### ISSUE TITLE
Helper for root url?

### ISSUE THREAD

**Issue by pnhuyduy** [hexojs/hexo#3456]
Hi, Is there any Helper that return the `root` url? Like localhost:4000/blog

**Comment by tcrowe** [comment]
Hi @pnhuyduy :wave:

Can you try this `url_for(...)` helper and let me know if it worked? https://hexo.io/docs/helpers#url-for

**Comment by pnhuyduy** [comment]
Hi @tcatche,
Thanks for your response, but I realized `url_for` is not what i looking for. My intention is how to get the `root` url in article by using the `{% %}` syntax.

**Comment by tcrowe** [comment]
@pnhuyduy Oh I see. Then you need `config.root`.

You can access anything in `./_config.yml` via `config.property` or `./themes/my-theme/_config.yml` via `theme.property`.

Is that the thing you were looking for?

**Comment by pnhuyduy** [comment]
Well not really. I tried `{% config.root %}` in `.md` file but it's not working.

**Comment by tcrowe** [comment]
You can use those variables in the templates. If you need helpers in the markdown there are tag plugins. If a tag plugin does not give you the variable you want the next step is create a plugin.

https://hexo.io/docs/tag-plugins
