### ISSUE TITLE
Provide a way to unregister a tag

### ISSUE THREAD

**Issue by kolokolit** [hexojs/hexo#3457]
Looking through the code, I’ve noticed that there’s a way to unregister a filter, but there’s no way to unregister a tag. Is it possible to add one?

**Use case:** I want to add a tag for adding YouTube videos in my theme, but don’t want to use more obscure name just because there’s a default tag (`youtube`) in place. I would’ve preferred to have a way to unregister default tag and add my own in its place.

**Comment by SukkaW** [comment]
Should be fixed in #4046
