### ISSUE TITLE
Image galleries?

### ISSUE THREAD

**Issue by sprugman** [hexojs/hexo#346]
Hi,

I'm evaluating using hexo for a project that is pretty heavy with image galleries. How does it deal with that issue? I guess my ideal would be something like:

 - I can have a "gallery" page type
 - I can have a gallery of galleries at the top of the structure
 - I can dump a bunch of images of whatever sizes into a folder in it
 - hexo will take care of processing the images into thumbnails and full-size(s) according to some settings in a config file somewhere (probably downscaling only)
 - on my gallery html page, I add whatever image viewer I want and hexo will take care of converting the list of files to a JSON object that's consumed by the slideshow plugin
- or, I can use some kind of template just to show the images or thumbnails statically on the page.

Is this possible/easy? If not are there any static site generators that are good at this?

**Comment by leesei** [comment]
I do agree that this is a theme feature, not a Hexo core feature.
Hexo just process the files and hand data structures to the theme. It's the theme that's responsible for the rendering.

What Hexo can do is possible reserve some field in the data structure for 'gallery' layout. But the theme could probably parse those given the page's content.

**Comment by Xuanwo** [comment]
Not core feature, closed.
