### ISSUE TITLE
Tell issue creators to use Speed OSS to add reward to Github Issues

### ISSUE THREAD

**Issue by daljeetv** [hexojs/hexo#3462]
Add this text to ISSUE_TEMPLATE.md:

`ADD A REWARD using [Speed](speedoss.com) to SOLVE this issue QUICKLY and SUPPORT this project.`

**Comment by tomap** [comment]
Hum, could you elaborate?
Why would we need that?

**Comment by daljeetv** [comment]
It's a good way to tell people who are filing issues to add a monetary reward to them. This way you as contributors can get some sort of financial support for your work.

**Comment by daljeetv** [comment]
@YoshinoriN @tomap thank you for considering. Consider checking it out speedoss.com. Would love your guys feedback and I think it would be a great way to help support the contributors of this repo!

**Comment by tomap** [comment]
@daljeetv, what is your relation with speedoss ? 
Why not use Patreon or https://en.liberapay.com ?
And why do that in the first place? 
Does the project need funding?

**Comment by SukkaW** [comment]
`speedoss.com` is no longer a valid.

Since Hexo is already using IssueHunt, we should close it now.
