### ISSUE TITLE
add a custom page but acting like home page

### ISSUE THREAD

**Issue by roastduckcd** [hexojs/hexo#3463]
## Environment Info

Node version(`node -v`):v11.7.0

Your site `_config.yml` (Optional):

# Directory
source_dir: source        
public_dir: public        
tag_dir: tags             
archive_dir: archives     
category_dir: categories  
code_dir: downloads/code  
i18n_dir: :lang           
skip_render:  
           
Your theme `_config.yml` (Optional): 

menu:
  home: / || home
  gossip: /gossip/ || coffee
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404 || heartbeat
  about: /about/ || user

# Enable/Disable menu icons / item badges.
menu_settings:
  icons: true
  badges: false

## For question

hi, i add a custom  page `gossip`. and i want it acting like home page but only show posts in `categories/gossip`. Now I'm stucked in getting posts in the specified category `gossip`.

Q1:  i change the gossip path to `categories/gossip`, but it only shows some post links. can this page be customized to show some page excerpt?

Q2: if Q1 can not be done, is there a way to get posts in a specified category? i'm cosidering code like below. But it will get all posts.

```
{% import '_macro/post.swig' as post_template %}

<div class="category-gossip-page">

    <div class="category-gossip">
       
      ####### a variable like category.posts?  or function ?#######
      {% for post in site.posts %}
        {{ post_template.render(post, true) }}
      {% endfor %}

    {% include '_partials/pagination.swig' %}
    </div>
</div>
```

**Comment by YoshinoriN** [comment]
@roastduckcd 
Hi 👋 

You can make customized layout by yourself.
For example, hexo-theme-landscape [has seven templates](https://github.com/hexojs/hexo-theme-landscape/tree/acc0b08ff703c31568052d1a539ef9de7e26a307/layout).

You can specify which layout do you use by each post.

```
---
layout: gossip //specify which layout do you use
title: "example"
date: 2018-11-13 19:02:46
---
```

I'm sorry if I misunderstand. Thanks :)

**Comment by roastduckcd** [comment]
@YoshinoriN 
I'm actually using the layout `page.swig` and include my own `gossip.swig`.  But I had no idea of how to get posts in the specified category `gossip`. Anyway, thank you so much ^_^

**Comment by YoshinoriN** [comment]
@roastduckcd 
May we close this? If you have more question, I'm going to try to answer of your question.

**Comment by roastduckcd** [comment]
issue closed. It turns out that I need to modify `category.swig` file.
* change `post-collapse.swig` to `post.swig`
* add a few `if` sentenses 
Thanks!
