### ISSUE TITLE
[question] How to make certain pages behave like posts?

### ISSUE THREAD

**Issue by FernandoHurtado** [hexojs/hexo#3468]
I have certain pages (under the projects section) that I want to behave like posts (without actually being posts) in the sense that they should have table of contents and tags. I know I could just edit post.ejs but I just need the pages under /projects/ to have this layout.

  ##Thanks!

Here's the repo:
https://github.com/FernandoHurtado/purtechnikon

**Comment by tcrowe** [comment]
Hey @FernandoHurtado 😸 

Did you arrive at a solution? If so, what was it?

Some things I usually do are putting `*.md` or `*.html` pages in directories and hexo automatically knows how to render it.

**Comment by tcrowe** [comment]
Combined with front-matter: https://hexo.io/docs/front-matter

**Comment by FernandoHurtado** [comment]
> Did you arrive at a solution? If so, what was it?
> Some things I usually do are putting `*.md` or `*.html` pages in directories and hexo automatically knows how to render it.

hey @tcrowe , I haven't found a solution :( . Basically what I'm asking is how to make hexo know to render pages under the /projects/ directory like it does posts. 

For example, https://purtechnikon.com/projects/Journal-julia/ doesn't have an index on the side and a share button and stuff as opposed to https://purtechnikon.com/2019/02/25/Exploring-the-limits-of-Turing-Computability/ , which is formatted more properly for texts.

**Comment by YoshinoriN** [comment]
Hi 👋

You can specify which layout do you use by each posts or pages using by [Front-matter](https://hexo.io/docs/front-matter) layout variable.
For example, hexo-theme-landscape [has seven templates](https://github.com/hexojs/hexo-theme-landscape/tree/acc0b08ff703c31568052d1a539ef9de7e26a307/layout).

So, I think you should create `*.md` file in your `_source/project` directory & specify `layout`.

Example

```
// _source/project/index.md file

---
layout: post //specify which layout do you use
title: "example"
date: 2018-11-13 19:02:46
---
```

I'm sorry if I misunderstand. Thanks :)

**Comment by FernandoHurtado** [comment]
@YoshinoriN 
Hi! I tried setting layout to post and [it really only changed how the title looks](https://purtechnikon.com/projects/turing/): 
It still doesn't generate the table of contents or sharing buttons :( 

I checked the other layouts and none of them work either. This is my layouts folder: 
https://github.com/FernandoHurtado/purtechnikon/tree/master/themes/cactus-PT/layout

**Comment by YoshinoriN** [comment]
@FernandoHurtado 
I tried to customize your theme, but it's difficult for me...
We need an expert who is knowledgeable in layout customize.

**Comment by stevenjoezhang** [comment]
There is a discussion about it https://github.com/hexojs/hexo/issues/1067
