### ISSUE TITLE
Display content based on total number of posts

### ISSUE THREAD

**Issue by waylonrobert** [hexojs/hexo#3472]
How do I display content only when X number of posts are on the site?

For example, I want to display a link that says "More Posts" when the total number of posts is greater than 5.

Any ideas on how to achieve this?

**Comment by tcrowe** [comment]
Hey @waylonrobert 👋 

You might want to check into pagination: https://hexo.io/docs/configuration#Pagination

If you're making a template you can use `<%-paginator()%>` (EJS example) function:
https://hexo.io/docs/helpers#paginator

**Comment by waylonrobert** [comment]
Hi @tcrowe! 

Thanks for the reply. I gave pagination a try, but didn't get what I wanted (can you do if statements on paginator - doesn't seem like it). 

I discovered `page.total` in some sample hexo themes. I tried using `post.total` initially, but it failed when I tried `post.total`. The page renders when you use `page.total`, but it doesn't actually work. In the example below, if I have more than 4 posts, it doesn't display the View More link:

Here is my code:
`<% if (page.total > 4) { %>
    <p>
      <a href="<%- url_for('writing') %>" title="View more blog posts">
        View More
      </a>
    </p>
    <% } %>`

Any other thoughts?

**Comment by YoshinoriN** [comment]
@waylonrobert 
Would you try to use `site.posts.length > 4` instead of `page.total > 4`?

**Comment by waylonrobert** [comment]
Thanks so much @YoshinoriN! That worked nicely.
