### ISSUE TITLE
Empty a.headerlink on all titles

### ISSUE THREAD

**Issue by Buzut** [hexojs/hexo#3474]
## Environment Info

Node v10.11.0

Hexo and Plugin version:
├── hexo@3.8.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@4.1.0
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-server@0.3.3
├── hexo-yam@1.0.4
├── imagemin-cli@4.0.0
└── imagemin-webp@5.0.0 

## BUG

As said in the title, content generation places en empty link in all `<hn>` tags. It's completely useless. Could there be an option to disable or customize it?

For instance, it could be usefull to provide an anchor so that this link is actually clickable.

<a href="https://ibb.co/0F2r0ZM" target="_blank"><img src="https://i.ibb.co/0F2r0ZM/Capture-d-e-cran-2019-03-01-a-10-57-09.png" alt="Capture-d-e-cran-2019-03-01-a-10-57-09" border="0"></a>

**Comment by YoshinoriN** [comment]
This empty link is generated by theme. For example, your screenshot theme is [navy](https://github.com/hexojs/site/tree/master/themes/navy).
Maybe it's generated by [here](https://github.com/hexojs/site/blob/e7b12f2f3da2f8f43618e6994668a77bb1ba14d2/scripts/helpers.js#L115).

**Comment by Buzut** [comment]
Hi!
Sorry for the late answer. The thing is, I have a custom theme developped from scratch and still get these empty links.
Exemple: https://buzut.net/

I can assure you, nothing in my theme generates this.

**Comment by Sicaa** [comment]
Hi!
Sorry to bring this up, just landed here because I had the same problem.
This is not generated by the theme used. I've found out that it is generated by the [hexo-renderer-marked plugin](https://github.com/tomap/hexo-renderer-marked).
This behavior can be disabled by setting the `headerIds` option to false in `_config.yml`.
Just like that:
```
marked:
  headerIds: false
```
Hope this helps!

**Comment by Buzut** [comment]
Thank you for pointing this out. Might be useful for anyone facing the same issue.
Indeed it now works, but it wasn't the case with previous versions. 

Thankfully, it's now all good 💯
