### ISSUE TITLE
小标题内容是’jquery‘时，导致无法显示页面的问题

### ISSUE THREAD

**Issue by haledc** [hexojs/hexo#3476]
## Environment Info

Node version(`node -v`): 10.15.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): next

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 D:\MySpace\Blog
+-- hexo@3.8.0
+-- hexo-algolia@1.3.1
+-- hexo-deployer-git@1.0.0
+-- hexo-deployer-heroku@0.1.2
+-- hexo-deployer-openshift@0.1.2
+-- hexo-deployer-rsync@0.1.3
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
`-- hexo-symbols-count-time@0.4.4

next主题的版本号是：6.4.0
## For question

在小标题的中设置内容为jquery时，导致整个页面无法显示，我使用的是NexT.Gemini主体，不仅文章无法显示，左边的导航栏也无法显示，只有页面底部的网站说明可以显示出来。没有报错。一开始不知道什么原因，后来逐一排查，删减文章内容，发现了这个问题，最后解决了这个问题。我把jquery 改成了jQuery后，页面显示正常了。不知道这算不算是一个bug。查看了下issue，好像没有发现这个问题。所以提了这个issue。

## For feature request

![jquery1](https://user-images.githubusercontent.com/30280995/53972245-6120ed80-4139-11e9-9dec-b77c12432c62.png)
![id jquery1](https://user-images.githubusercontent.com/30280995/53972267-6a11bf00-4139-11e9-8810-30c639cfca3b.png)
![bank1](https://user-images.githubusercontent.com/30280995/53972714-4d29bb80-413a-11e9-87ba-8d643d6288d9.png)
![bank](https://user-images.githubusercontent.com/30280995/53972485-ddb3cc00-4139-11e9-8179-bbaf05456652.png)
![jquery2](https://user-images.githubusercontent.com/30280995/53972290-76961780-4139-11e9-9e42-26f1b6c1e42b.png)
![id jquery2](https://user-images.githubusercontent.com/30280995/53972336-8ada1480-4139-11e9-97b2-183e4078fa37.png)

**Comment by YoshinoriN** [comment]
Would you please ask to [hexo-theme-next](https://github.com/theme-next/hexo-theme-next/issues)?

I can't reproduce it. I [tried to reproduce](https://github.com/YoshinoriN/hexo-test/commit/fc9bc3ace7c6ce03fc020719cb086a68d9b9c40b). (theme is landscape) But, result is seems fine.

![3476](https://user-images.githubusercontent.com/11273093/54283783-10e6d700-45e2-11e9-91c4-d05205518d2e.jpg)

**Comment by haledc** [comment]
@YoshinoriN  thanks! I'm sure the problem is caused by next theme.
