### ISSUE TITLE
Copy unnecessary asset folders for unpublished posts

### ISSUE THREAD

**Issue by DaemondShu** [hexojs/hexo#3478]
## Problem
Hexo supports a good feature to copy assets for one post by set `post_asset_folder: true` in config.yml.
But it will always do copying even if `page.published=false`. It wastes space of public path. 

## Reproduce
A case is shown below:
- the post directory structure:
![image](https://user-images.githubusercontent.com/8073161/54068854-077d0800-428c-11e9-8fb4-99308d9550e9.png)

- and set article.md to unpublished
```
---
title: article
published: false
---

test asset
![](new_article/2019-03-07-17-02-03.png)
```
- After generate, the article page is not generated(it's OK), but the image has been copied to build path(It's not good). 
![image](https://user-images.githubusercontent.com/8073161/54068830-b40aba00-428b-11e9-9bdb-0eaec8d7848f.png)

## Question
1. Is it a bug? 
2. Is there another way to avoid copying assets referenced by nothing?  
I have tried moving to draft and setting exclude path. They worked but are not convenient if I often switch the publish state.

## Environment Info
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 17.5.0 darwin x64
node: 11.10.1
v8: 7.0.276.38-node.17
uv: 1.26.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1a
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0

**Comment by tomap** [comment]
Hi, I looked into the code, and the solution might be simple, you might just need to add a few "published == false" in conditions here https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/post.js#L142
(and possibly on other places)

Are you able to do a PR?

**Comment by MonkeyDAsce** [comment]
Thanks a lot for your prompt reply. 
I will try and push a PR if it works.

**Comment by MonkeyDAsce** [comment]
> Hi, I looked into the code, and the solution might be simple, you might just need to add a few "published == false" in conditions here https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/post.js#L142
> (and possibly on other places)
> 
> Are you able to do a PR?

I did a PR.  
And the solution considers skipping unpublished assets and deleting them if exist.
