### ISSUE TITLE
标签数量显示有误

### ISSUE THREAD

**Issue by kinglyq** [hexojs/hexo#3480]
一共5个标签，但是页面就是显示为6个，进入标签页面明明下面只有**5**个标签的链接，但是却
显示**目前共计 6 个标签** 。(hexo c    &    hexo g 已经n次了)
![tags](https://user-images.githubusercontent.com/46125957/54072732-d1ef1380-42b9-11e9-8f35-9c864242e698.png)

**Comment by YoshinoriN** [comment]
`hexo c` command does not exist. Please try `hexo clean`.
