### ISSUE TITLE
ejs中单引号渲染问题

### ISSUE THREAD

**Issue by zeplios** [hexojs/hexo#3481]
## Environment Info

Node version(`node -v`):

v10.15.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

hexo-site@0.0.0 C:\Users\xxxxxxx
+-- hexo@3.8.0
+-- hexo-browsersync@0.3.0
+-- hexo-deployer-git@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.3.3

## For BUG

我在使用Shuffle.js的时候，需要在ejs中定义下面的元素：

    <div data-groups='["illustration"]'>...</div>

但是，在浏览器中查看源码，得到的却是：

    <div data-groups="[" illustration"]"="">...</div>

似乎单引号会被渲染成双引号，而里层的双引号会被进一步处理，最终得到一个奇怪的输出

谢谢

**Comment by stevenjoezhang** [comment]
双引号应该可以用 HTML 的 `&quot;` 转义
