### ISSUE TITLE
写一个  if (is_post()) 在 localhost:4000 的 post 页面正常显示，deploy 后完全不显示

### ISSUE THREAD

**Issue by zhwangart** [hexojs/hexo#3483]
添加不蒜子计数器，写 `if (is_post())` 在 localhost:4000 的 post 页面正常显示，deploy 到 github 上则完全不显示，这是什么问题？代码如下：
``` ejs
<% if (is_post()) { %>
  <div><i class="fe fe-bookmark"></i> <span id="busuanzi_value_page_pv"></span></div>
<%} %>
```

**Comment by YoshinoriN** [comment]
Would you please try to delete `db.json` before `hexo generate`.
Or do `hexo clean`

> [Data Not Updated](https://hexo.io/docs/troubleshooting#Data-Not-Updated)

**Comment by zhwangart** [comment]
多次执行 `hexo clean` 命令，并不起作用...

**Comment by YoshinoriN** [comment]
Duplicate #2897

**Comment by YoshinoriN** [comment]
Would you please check this comment.
And please try to confirm `{cache:true}`?  

> https://github.com/hexojs/hexo/issues/2503#issuecomment-364626648

Thanks :)

**Comment by zhwangart** [comment]
> @YoshinoriN 

Thank you very much for your help, but I am still confused. My theme is [ocean](https://github.com/zhwangart/hexo-theme-ocean), the problem in `_partial/post/busuanzi.ejs`, code:
``` ejs
<ul class="list-inline">
  <% if (is_home()) { %>
    <li><i class="fe fe-bar-chart"></i> <span id="busuanzi_value_site_pv"></span></li>
  <%} %>
    <li><i class="fe fe-smile-alt"></i> <span id="busuanzi_value_site_uv"></span></li>
  <% if (is_post()) { %>
    <li><i class="fe fe-bookmark"></i> <span id="busuanzi_value_page_pv"></span></li>
  <%} %>
</ul>
```
The localhost:4000 home page is displayed normally, `if (is_home())` kick in, render out html:
``` html
<ul class="list-inline">
    <li><i class="fe fe-bar-chart"></i> <span id="busuanzi_value_site_pv">9934130</span></li>
    <li><i class="fe fe-smile-alt"></i> <span id="busuanzi_value_site_uv">604750</span></li>
</ul>
```
After the deploy, `if (is_home())` seems to disappear, the instance page: https://zhwangart.github.io
Execute the `hexo clean` command multiple times and upgrade the hexo version to 3.8.0

**Comment by YoshinoriN** [comment]
@zhwangart 
Hmm... It's strange 🤔 

I can't reproduce it... Please see belows. It seems collectly.

* [is_home](https://github.com/YoshinoriN/hexo-test/blob/28a35d307d0116bff20de39dcf7f18e6ce938cdf/public/index.html#L519)
* [is_post](https://github.com/YoshinoriN/hexo-test/blob/28a35d307d0116bff20de39dcf7f18e6ce938cdf/public/2019/03/14/issue-3485/index.html#L119)

**Comment by zhwangart** [comment]
> @zhwangart
> Hmm... It's strange 🤔
> 
> I can't reproduce it... Please see below. It seems correct.
> 
> * [is_home](https://github.com/YoshinoriN/hexo-test/blob/28a35d307d0116bff20de39dcf7f18e6ce938cdf/public/index.html#L519)
> * [is_post](https://github.com/YoshinoriN/hexo-test/blob/28a35d307d0116bff20de39dcf7f18e6ce938cdf/public/2019/03/14/issue-3485/index.html#L119)

I have not solved this bug, Could it be because of the hexo version?

**Comment by stevenjoezhang** [comment]
The discussion of `cache` continues here: #3738
