### ISSUE TITLE
Cant use hexo-theme-doc!! WARN No layout: index.html

### ISSUE THREAD

**Issue by KonstantinosMich91** [hexojs/hexo#3484]
I tried all the steps to get this theme. the solution to the issue #139 didnt help
-By Github:

1.git clone https://github.com/zalando-incubator/hexo-theme-doc.git themes/doc
2.update config -> themes: doc
-Long Way:
1. npm install hexo-theme-doc --save
2. npm install hexo-renderer-ejs hexo-renderer-marked --save
3. updated the config file -> themes: ../node_modules/hexo-theme-doc

Actual Behavior
-INFO Start processing
-INFO Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
-WARN No layout: index.html

Steps to Reproduce the Problem
hexo init
npm install
npm install hexo-theme-doc --save
update the _condig.yml -> themes: ../node_modules/hexo-theme-doc
getting blank screen.
Specifications
NodeJS Version: v9.11.1
NPM Version: 6.5.0
OS:
Hexo Version: 3.8.0
##My dependencies

"hexo": "^3.8.0",
"hexo-generator-archive": "^0.1.5",
"hexo-generator-category": "^0.1.3",
"hexo-generator-index": "^0.2.1",
"hexo-generator-tag": "^0.2.0",
"hexo-renderer-ejs": "^0.3.1",
"hexo-renderer-marked": "^0.3.2",
"hexo-renderer-stylus": "^0.3.3",
"hexo-server": "^0.3.3",
"hexo-theme-doc": "^1.0.0-rc.1"

**Comment by stevenjoezhang** [comment]
Please ask the maintainers of hexo-theme-doc for help, thanks!
