### ISSUE TITLE
Is there a way to get all the site posts include posts in page file?

### ISSUE THREAD

**Issue by 85Ryan** [hexojs/hexo#3487]
## Environment Info

Node version(`node -v`): v10.15.1

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
    ├── hexo@3.8.0
    ├── hexo-browsersync@0.3.0
    ├── hexo-deployer-git@1.0.0
    ├── hexo-generator-archive@0.1.5
    ├── hexo-generator-category@0.1.3
    ├── hexo-generator-feed@1.2.2
    ├── hexo-generator-sitemap@1.2.0
    ├── hexo-generator-tag@0.2.0
    ├── hexo-renderer-ejs@0.3.1
    ├── hexo-renderer-marked@0.3.2
    ├── hexo-renderer-stylus@0.3.3
    ├── hexo-server@0.3.3
    ├── lodash@4.17.11
    └── lunr@2.3.6

## For question

In my site, there are some posts in the page file, I want to show all the posts( include the posts in the `/source/_posts` and the page file) in the index page, but the `site.posts` only get the posts in the `/source/_posts` file, so is there a way to get all of them?

**Comment by YoshinoriN** [comment]
As you may know, `site.pages` variable has pages data.

> https://hexo.io/docs/variables#Site-Variables

But, I don't know how to get `site.posts` & `site.pages` as the same time.

**Comment by YoshinoriN** [comment]
I think maybe below plugin might help you :)

> https://github.com/alexbruno/hexo-generator-json-content
