### ISSUE TITLE
How to get your IMOOC password?

### ISSUE THREAD

**Issue by Foelle** [hexojs/hexo#3488]
## For question

I can't find the [慕课网2018](https://pan.baidu.com/share/init?surl=vscbnpyXmt5w5-WAZxmYmQ#list/path=%2F&parentPath=%2F%E4%B8%8D%E6%AD%BB%E9%B8%9F%E5%88%86%E4%BA%AB%2F%E6%95%99%E7%A8%8B%E5%88%86%E4%BA%AB) password.Could you please tell me the password?I find it in [your blog](https://blogs.zjrson.cn/2018/12/04/imooc%E8%A7%86%E9%A2%91%E9%93%BE%E6%8E%A5/).Thank u.

**Comment by Foelle** [comment]
> ## For question
> I can't find the [慕课网2018](https://pan.baidu.com/share/init?surl=vscbnpyXmt5w5-WAZxmYmQ#list/path=%2F&parentPath=%2F%E4%B8%8D%E6%AD%BB%E9%B8%9F%E5%88%86%E4%BA%AB%2F%E6%95%99%E7%A8%8B%E5%88%86%E4%BA%AB) password.Could you please tell me the password?I find it in [your blog](https://blogs.zjrson.cn/2018/12/04/imooc%E8%A7%86%E9%A2%91%E9%93%BE%E6%8E%A5/).Thank u.

**Comment by tomap** [comment]
It looks like "not an hexo issue"?

**Comment by Foelle** [comment]
> It looks like "not an hexo issue"?

sorry. I see. It was my fault. I will close it.
