### ISSUE TITLE
centos 无法安装 hexo ; 环境基本配置完成；

### ISSUE THREAD

**Issue by WEIYOULIANGFENG** [hexojs/hexo#3493]
[root@iZr567sp4k4sjxZ ~]# npm install hexo-cli -g
/root/nodejs/bin/hexo -> /root/nodejs/lib/node_modules/hexo-cli/bin/hexo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ hexo-cli@1.1.0

**Comment by YoshinoriN** [comment]
It's just a warning. 
The fsevents package is an optional dependency.

> https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by WEIYOULIANGFENG** [comment]
> 
> 
> It's just a warning.
> The fsevents package is an optional dependency.
> 
> > https://docs.npmjs.com/files/package.json#optionaldependencies

感谢您的回答；
问题已经解决，由于一个空 npm 配置文件的 存在，导致 我 的  hexo 命令 ，需要 通过准确的命令路径才可以使用

**Comment by weyusi** [comment]
Use `npm install -g hexo-cli --prod` to skip installation of fsevents dep.

**Comment by weyusi** [comment]
@WEIYOULIANGFENG reported issue has been resolved.
