### ISSUE TITLE
"https://hexo.io/themes/" can not show theme preview images

### ISSUE THREAD

**Issue by xumeng** [hexojs/hexo#3496]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

The website "https://hexo.io/themes/" can not show theme preview images

**Comment by YoshinoriN** [comment]
@xumeng 
Already recovered.
Thank you for your report :)
