### ISSUE TITLE
Post not rendering after being uploaded via FTP

### ISSUE THREAD

**Issue by fletchto99** [hexojs/hexo#3498]
## Environment Info

Running in this container: [fletchto99/hexo-dev-docker](https://github.com/fletchto99/hexo-dev-docker)
Node version(`node -v`): `v10.15.3`
Hexo and Plugin version(`npm ls --depth 0`): 

```
+-- hexo@3.8.0
+-- hexo-algoliasearch@0.3.0
+-- hexo-auto-canonical@0.1.1
+-- hexo-deployer-rsync@0.1.3
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-seo-friendly-sitemap@0.0.22
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
+-- hexo-sliding-spoiler@1.1.6
`-- hexo-wordcount@6.0.1
```

## Bug Info

As seen in #2023 I'm unable to view my post after uploading it via FTP to my server. The server is running a [docker container with hexo](https://github.com/fletchto99/hexo-dev-docker) to render the posts.

My flow is as follows:

1. The docker container is [running hexo server](https://github.com/fletchto99/hexo-dev-docker/blob/master/setup/bootstrap.sh#L42-L44), watching for draft posts
2. I make changes to a file locally, say `drafts/2019/test.md`
3. The file is uploaded on the server to `fake/path/hexo/source/_drafts/2019/test.md`
4. The first upload renders fine.
5. I make changes to `test.md` and upload via SFTP to the same location and I get:

![screen shot 2019-01-30 at 1 48 02 am](https://user-images.githubusercontent.com/718681/51969217-196bbf80-2431-11e9-83af-9ee70bec4e90.png)

I'm wondering if the generation of the page is occurring too quickly such that the full file hasn't been uploaded completely? Honestly, I'm at a bit of a loss with this one.

Here are the logs upon an upload & invalid rendering of a post:

```
05:09:38.512 DEBUG Processed: _drafts/2019/march/tomorrowland.md
05:09:38.648 DEBUG Generator: page
05:09:38.649 DEBUG Generator: post
05:09:38.649 DEBUG Generator: feed
05:09:38.649 DEBUG Generator: archive
05:09:38.649 DEBUG Generator: category
05:09:38.649 DEBUG Generator: index
05:09:38.649 DEBUG Generator: tag
05:09:38.649 DEBUG Generator: spoiler_asset
05:09:38.649 DEBUG Generator: asset
05:09:38.654 DEBUG Generator: sitemap
05:09:43.882 DEBUG Rendering post: 2019/march/tomorrowland/index.html
[0mGET /2019/march/tomorrowland/ [32m200 [0m17.540 ms - -[0m
[0mGET /css/spoiler.css [32m200 [0m0.399 ms - -[0m
[0mGET /js/spoiler.js [32m200 [0m0.372 ms - -[0m
[0mGET /assets/css/style-a4kfaxqbal8iv7u8tdflwmgsj2orolc3fszmxw8owigx2em0vgapluvpfmez.min.css [32m200 [0m2.292 ms - -[0m
[0mGET /assets/js/script-tbnkzfomhwarieaylsovgeklwfoxitfei8ogir1nbxguvhfxyo6pm4ibrosu.min.js [32m200 [0m2.366 ms - -[0m
[0mGET /assets/fonts/fontawesome-webfont.woff2?v=4.7.0 [32m200 [0m0.356 ms - -[0m
[0mGET /assets/js/script-tbnkzfomhwarieaylsovgeklwfoxitfei8ogir1nbxguvhfxyo6pm4ibrosu.min.js [32m200 [0m2.366 ms - -[0m
[0mGET /assets/fonts/fontawesome-webfont.woff2?v=4.7.0 [32m200 [0m0.356 ms - -[0m
```

**Comment by tcrowe** [comment]
@fletchto99 Did you ever come up with a solution for this?

**Comment by fletchto99** [comment]
@tcrowe Unfortunately I haven't. I'm not too sure what else to look into for debugging. I was wondering if it was perhaps the encoding but I validated the encoding was correct, both on my client and also once on the server. I haven't blogged recently and have been quite busy so I haven't had a chance to play with this any more than I did before this issue.

I'll see if I can get around to some more testing this coming weekend.

**Comment by tcrowe** [comment]
Yeah it's not a trivial example to deal with. There is also this problem I run into sometimes where the file synchronization to Docker or VirtualBox isn't as expected. On top of that node and [chokidar](https://github.com/paulmillr/chokidar) file watchers are not always functional across the systems as you expect.
