### ISSUE TITLE
any api for ONLY getting all the titles/excerpts? 

### ISSUE THREAD

**Issue by mr-m0nst3r** [hexojs/hexo#3499]
## Environment Info

Node version(`node -v`):`v6.14.3`

Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 /www/sites/m0nst3r.me_hexo
├── hexo@3.8.0
├── hexo-admin@2.3.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-search@2.4.0
├── hexo-generator-searchdb@1.0.8
├── hexo-generator-tag@0.2.0
├── hexo-migrator-image@1.0.5
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.3.3
```

## For BUG

I'm using hexo-admin plugin, so I could write and post online.
The problem is already posted, but no luck from the author: https://github.com/jaredly/hexo-admin/issues/152
Simply put: It's time consuming to load all the post data, I think just `excerpt` will be good for the `list` page. But hexo-admin is using `hexo.model("post")` to get all posts. And I can't find api for only get title or excerpt.
I'm totally new to nodejs dev, but I tried to add a `title.js` in hexo's `lib/model` which is copied from `post.js`, and replaced all the Post to Title, then change the `api.js` in `hexo-admin` so it's calling `hexo.model("Title")`, but after login, it's empty on the list post page.

This may be a problem that may involve two parties, I'm not so sure it's good to post here. Sorry if it's not.
But would you like to offer some suggestions or plugins for the problem I met?

Thank you.
Pls help.

**Comment by tcrowe** [comment]
There are a bunch of things you can use from the themes. e.g. `site.*` and `page.*`
 
https://hexo.io/docs/variables

You know how each of your posts has `title:`, `date:` and etc? You can access those, or create your own, and access them via `page.title`, `page.date` and etc.

Can you try adding that into your theme and see if it helps?

**Comment by tcrowe** [comment]
There are other ways to access all the data via plugins. It's all there on the docs.
