### ISSUE TITLE
上传内容以后页面一直是404？

### ISSUE THREAD

**Issue by JackieLuo** [hexojs/hexo#350]
我改好了设置
hexo generate
hexo deploy
传到github上的只有.deploy文件夹里的内容，这样是对的吗？
在localhost显示是正常的，传上去就一直404，有人帮我看下吗？谢谢！
https://github.com/JackieLuo/JackieLuo

**Comment by metogo** [comment]
实在是不会了 一直404
https://github.com/metogo/metogo.github.io/ 
求教下 ！！感谢

**Comment by holdlg** [comment]
我也遇到了，上传了文件夹，访问url都正确，报 404 原来是我的文件夹名字开头是“_" 下划线。改掉就可以访问。

**Comment by thinkerchan** [comment]
至今还404....

**Comment by Xuanwo** [comment]
@thinkerchan 你的分支错了- -，页面文件要放在master分支

**Comment by thinkerchan** [comment]
@Xuanwo  可是这里有一个人的是 https://github.com/pakchoidora/pakchoidora/tree/gh-pages 可以这么访问的啊 T_T

**Comment by Xuanwo** [comment]
@thinkerchan 你要区分个人主页和项目主页的区别= =

**Comment by thinkerchan** [comment]
@Xuanwo 大神求助，我小白一只，怎么区分个人主页和项目主页？有分支和没分支吗

**Comment by Xuanwo** [comment]
@thinkerchan `yourname.github.io`形式的库，会解析master分支；而别的名字的库，会解析gh-pages分支，以`yourname.github.io/库名`的形式访问。

**Comment by JustinLee-Exoplanet** [comment]
我开始也是提交到gh-pages分支上去，一直不能访问，后来切换到master上就能访问了（将repo默认设置成master，hexo本地deploy里面branch也设置为mater，deploy下），如果yourname.github.io后面再跟上库名访问，感觉怪怪的~~

**Comment by brittyu** [comment]
同gh-pages 然后切换到master就可以了@JustinLee-Exoplanet

**Comment by sunpingji** [comment]
我创建了sunpingji.github.io repo 在master分支下 过了好久还是404 求解答

**Comment by Xuanwo** [comment]
@sunpingji 建议你看下http://xuanwo.org/2015/03/26/hexo-intor/

**Comment by weaming** [comment]
@holdlg 
原来如此，我也怀疑是这个
>我也遇到了，上传了文件夹，访问url都正确，报 404 原来是我的文件夹名字开头是“_" 下划线。改掉就可以访问。

**Comment by GHdeng** [comment]
https://github.com/GHdeng/GHdeng.github.io 还是404

**Comment by gjBlog** [comment]
请教一下，我的上传了半天了还是404，https://github.com/gjBlog/gjBlog

**Comment by sdqdChen** [comment]
求助，同样是404，弄了好久，https://github.com/sdqdChen/chen.github.io，帮忙看下，谢谢

**Comment by brittyu** [comment]
@sdqdChen 你的项目名称写错了，改成 sdqdChen.github.io 吧

**Comment by sdqdChen** [comment]
@brittyu 谢谢，确实是这个问题，，终于弄的差不多了

**Comment by tikdik** [comment]
我也一直404，配置啥的都正确，后面进入设置发现要开通必须验证邮箱，邮箱验证完成后就提示可以通过域名访问博客了

**Comment by henrytien** [comment]
我的本地预览没有问题，尝试解决了，依然是404，可以帮我看看吗，谢谢^^ https://github.com/henrytien/berlinthu.github.io

**Comment by chenyangguang** [comment]
[https://github.com/chenyangguang/chenyangguang.github.io](url) 也是奇怪了，已经解析到我的阿里云域名了。 gitvim.com 但是， 还是404呀。没看到问题是出在什么地方了。都是按官方的文档来的。对了我的是hexo

**Comment by shadowbroke** [comment]
求救，项目地址：https://github.com/shadowbroke/shol.github.io.git，也是遇到404问题，按照楼上的分析自己弄了很久都没有弄成功，感谢大神指导！

**Comment by JaneSu** [comment]
原来很多人遇到这个问题啊
我的问题好像和大家遇到的不一样，我最开始是在自己的笔记本上建的博客，上传和发布都没有问题，然后我想在公司的电脑也发布博客，但是所有的弄好之后，公司的电脑本地预览没有问题，只是一发布就是404，只能用笔记本重新发布才能好。求问这是什么原因？
这是博客文件：https://github.com/JaneSu/JaneSu.github.io
这是备份/同步的文件：https://github.com/JaneSu/blog
这是我在sf的问题描述：https://segmentfault.com/q/1010000009148486

**Comment by wuxiaochen** [comment]
https://github.com/wuxiaochen/wuxiaochen.github.io求解，老是404

**Comment by wuxiaochen** [comment]
求解，老是404                  
https://github.com/wuxiaochen/wuxiaochen.github.io

**Comment by ceiba-w** [comment]
@wuxiaochen 
master加个CNAME试试？

**Comment by zoezou2015** [comment]
我也有同样的问题，
hexo generate
hexo deploy
传到github上的有在本地编辑的文章，
在localhost显示是正常的，但是无法打开线上的，一直是404，有人帮我看下吗？谢谢！
链接如下： https://github.com/zoezou2015/zoezou2015.github.io

**Comment by IndianOldTurtledove** [comment]
@ceiba-w 妈了个逼的, 搞了一下午404, 搞半天hexo d不会把CNAME文件传上去, 传上去就好了.........

**Comment by ceiba-w** [comment]
@IndianOldTurtledove 请注意文明

**Comment by IndianOldTurtledove** [comment]
@ceiba-w 老铁，爱你❤

**Comment by sallenhandong** [comment]
一样的问题按着改了 还是404 
https://github.com/sallenhandong/sallenhandong.github.io

http://www.sallenhandong.github.io http404
https 无法连接服务器

**Comment by BigTreei** [comment]
东西都弄好了  hexo的   可以正常浏览，发布文章    但下午 hexo d -g 之后就一直访问404页面  至今仍然这样  求解，

bigtreei.github.io  这是博客
https://github.com/BigTreei/bigtreei.github.io  这是库   

我试着添加 CNAME   cname里写的是 bigtreei.github.io   但依然不能正常访问  依然404   
我就想知道出现这个问题的愿意所在  
求大神解答 么么哒

**Comment by JaneSu** [comment]
@BigTreei 
CNAME是用来放独立域名的地方，所以你写bigtreei.github.io没有用

另外你可以在本地执行：
```
hexo g
hexo s
```
看看在本地能不能预览，如果本地都不可以，那就是你的文件有问题

**Comment by sw926** [comment]
说说我的情况吧，我是用一个新的账号建了一个空白的Github Pages项目，然后把自己的账号添加到项目里面，用自己的账号初始化项目，之后访问就一直404，配置是完全没有问题的。
我的解决方法就是用项目的拥有者账号提交一次commit，就可以了。具体操作就是在_config.yml把repo改为使用https，然后
```
hexo clean
hexo d
```
部署过程中会要求输入用户名和密码，记得输入项目拥有者的用户名密码，部署成功后页面就能正常显示了。

**Comment by Jiiiiiin** [comment]
参考 http://jiiiiiin.cn/2018/01/20/%E4%BD%BF%E7%94%A8Hexo%E6%90%AD%E9%85%8DGithub%20Pages%E6%9D%A5%E5%81%9A%E7%AC%94%E8%AE%B0%E6%9C%AC/
(ಡωಡ)hiahiahia 

_Sent from my HUAWEI MHA-AL00 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ding2425** [comment]
原来https://github.com/ding2425/ding2425.github.io    ding2425两处的名字需要一样的！！！！！

**Comment by ym13349140** [comment]
感谢~~已解决404，原来真的xxx.github.io这里的xxx必须跟自己的github账号名称一致才可以，折腾了半天总算可以了

**Comment by angelkiki** [comment]
上傳以後一直是404怎麼辦!!
https://angelkiki.github.io/kiki-wed

**Comment by xiehf319** [comment]
请大拿帮忙 看下我的怎么回事  https://github.com/xiehf319/xiehf319.github.io  也是404

**Comment by AHAOAHA** [comment]
我来分享一下我的经验吧，在我第一次搭建的时候，在本地查看页面是没有问题的，但是部署上github之后就一直是404，最后发现，在下载完hexo之后，没有执行npm install，重新执行npm install之后重新生成并部署服务器，15min之后即可正常访问，在这里我使用的是cnpm因为在国内使用npm很慢

**Comment by songyule** [comment]
> @thinkerchan `yourname.github.io`形式的库，会解析master分支；而别的名字的库，会解析gh-pages分支，以`yourname.github.io/库名`的形式访问。

yourname.github.io/other.gihub.io 可以成功访问，有办法直接设置成 other.github.io直接访问吗

**Comment by ziqiwang777** [comment]
https://github.com/ziqiwang777/ziqiwang777.github.io
你好，我在本地查看没有问题，但是部署上之后就无法找到页面，https://github.com/ziqiwang777/ziqiwang777.github.io，麻烦大家帮忙看下了，谢谢！

**Comment by ziqiwang777** [comment]
https://github.com/ziqiwang777/ziqiwang777.github.io
你好，我在本地查看没有问题，但是部署上之后就无法找到页面，麻烦大家帮忙看下了，谢谢！

**Comment by jacinzhang** [comment]
```
1. hexo clean
2. hexo g -d
```
work for me

**Comment by zhang-stone** [comment]
参考
https://docs.github.com/cn/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
我的是发布源分支不对, 改成master, 就好了
1. 在 GitHub 上，导航到站点的仓库。
2. 在仓库名称下，单击  Settings（设置）。
3. 在“GitHub Pages”下，使用 Source（源）下拉菜单选择发布源。

**Comment by cocoin25** [comment]
还有种情况是_config.yml文件出错，具体错误github会发送到邮箱

**Comment by haitau** [comment]
也遇到了404问题，因为之前用  xxxxx.github.io 部署是没问题的。出问题是在使用了自己的域名 。
所以检查了两个地方，一个是在repo的setting 里面，重新 设置 了一下个人域名 。并自动 在 repo下生成了CNNAME文件 。
另外就是在hexo根目录下的_config.yml, 检查url值是否是对应的个人域名。
之后 hexo clean  ,  hexo g -d 。就可以正常访问，不再404了。

**Comment by kun126** [comment]
> 参考 https://docs.github.com/cn/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site 我的是发布源分支不对, 改成master, 就好了
> 
> 1. 在 GitHub 上，导航到站点的仓库。
> 2. 在仓库名称下，单击  Settings（设置）。
> 3. 在“GitHub Pages”下，使用 Source（源）下拉菜单选择发布源。



请问一下我的pages下面没有source那些选项要怎么把它调出来呢，本地4000没问题但是github.io是404T_T
<img width="1185" alt="Screenshot 2023-02-21 at 14 32 37" src="https://user-images.githubusercontent.com/52029467/220358500-d337642d-0a6f-4137-a5fd-f3efb898dda2.png">

**Comment by Xuanwo** [comment]
请创建一个新 Issue，而不是回复一个已经关闭很久的 Issue
