### ISSUE TITLE
Homepage for sub folder

### ISSUE THREAD

**Issue by exotfboy** [hexojs/hexo#3500]
_config.yaml:

```
permalink: /:title/
```

And the folder structure:

```
source
    _posts
        01
            index.md
            hello.md
        02
            index.md
            world.md
        about.md
```

Now, I can access the file like this:

```
/01/hello/
/01/index/
/about
```

But the `/01/` will return a `404` error.

I wonder if it is possible to return `/01/index.md` or `/01/index.ejs` when request `/01` ?

**Comment by gautamz07** [comment]
@exotfboy i think you might have to edit ```new_post_name``` in the config file.

[documentation](https://hexo.io/docs/configuration)

**Comment by tcrowe** [comment]
@exotfboy That will work if you take the markdown files out of `_posts` and put it `01` and `02` in `source`.
