### ISSUE TITLE
这种报错的原因是什么，该怎么解决？

### ISSUE THREAD

**Issue by WEIYOULIANGFENG** [hexojs/hexo#3501]
[root@iZr567sp4k4sjxZ ~]# npm install -g hexo-cli
npm http GET https://registry.npmjs.org/hexo-cli
npm http GET https://registry.npmjs.org/hexo-cli
npm http GET https://registry.npmjs.org/hexo-cli
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:221:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:211:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! command "/usr/local/node/0.10.24/bin/node" "/usr/local/node/0.10.24/bin/npm" "install" "-g" "hexo-cli"
npm ERR! cwd /root
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
[root@iZr567sp4k4sjxZ ~]# node -v
v0.10.24
[root@iZr567sp4k4sjxZ ~]# npm -v
1.3.21
[root@iZr567sp4k4sjxZ ~]#

**Comment by tomap** [comment]
Your current version on code is 0.10.24
The first supported version is 6.x
You should install at least the minimum supported version for it to work.
Go to nodejs.org to install it.
Of to the documentation of hexo https://hexo.io for more help
