### ISSUE TITLE
点击博客标题进入正文，正文是空白的完全不能显示，只能在侧框显示出目录

### ISSUE THREAD

**Issue by Ayzjijiji** [hexojs/hexo#3504]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): next

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG：
我的博客在首页能够显示出正文，点击阅读全文进入正文的时候就完全不能显示正文，一片空白，只有目录在侧框出现，求助~

**Comment by tomap** [comment]
Hi, we need more context to help you, your package.json _config.yml, your theme name, ...

**Comment by 8bun** [comment]
请问楼主解决了吗？
