### ISSUE TITLE
TypeError: (name || "").toLowerCase is not a function

### ISSUE THREAD

**Issue by Lizhooh** [hexojs/hexo#3505]
## Environment Info

```bash
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 10.8.0
v8: 6.7.288.49-node.19
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

I use react as the renderer.

```js
    "classnames": "^2.2.6",
    "hexo": "^3.8.0",
    "hexo-autoprefixer": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-react": "^1.1.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "0.2",
    "moment": "^2.24.0",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "read-yaml": "^1.1.0",
```

## For BUG

```js
title: Python 大数据分析（工具篇）
date: 2018-02-09 21:48:37
categories:
    - Python
tags:
    - Python
    - 大数据
    - 学习笔记
---
```

如果添加 date，就会报这个错误，另外 name 的值是 `8`。怎么解决？

If you add date, this error will be reported, and the value of name is `8`. How to deal with it?

![image](https://user-images.githubusercontent.com/19299088/55123772-cd8e7b80-513e-11e9-90ad-d9614e3604e5.png)

https://github.com/moment/moment-timezone/issues/736

**Comment by tomap** [comment]
https://hexo-theme-minidyne-demo.netlify.com/2018/02/09/python%20大数据分析（工具篇）/

https://github.com/tomap/hexo-theme-minidyne-demo/commit/21d8064716bb0db53d0b5f5f66bab9e313039fed

I just did a test. And it worked

Could you provide your package.json and your config.yml, and your theme, and theme's config.

Do you have a GitHub repo with your blog?

**Comment by Lizhooh** [comment]
@tomap Thank. 

I know what's going on, I wrote the wrong value of timezone in _config.yml.

![20190330185208](https://user-images.githubusercontent.com/19299088/55275176-4c410f80-531d-11e9-9493-c2b48e9f81fd.png)

This issue has been fixed.
