### ISSUE TITLE
怎样查看我安装了哪些插件？

### ISSUE THREAD

**Issue by chhLab** [hexojs/hexo#3507]
### **How can I get the list of plugins I have installed?**

**Comment by tomap** [comment]
The answer to your question was part of the text displayed when you created this issue.

Either go in package.json, all hexo-* dependencies or devdependencies are hexo plugins

Or run npm ls --depth 0

Why do you want to know?

**Comment by chhLab** [comment]
thanks for your answer. please forgive me for not paying attention to the text φ(゜▽゜*)♪
