### ISSUE TITLE
Drop NodeJs 6 support & Require NodeJs >= 8.6

### ISSUE THREAD

**Issue by tomap** [hexojs/hexo#3508]
This year, at the end of April, nodejs 6 will be 'End of Life'
We are starting to see project dropping support for nodejs 6. and as a consequence, we will need to drop that support also if we want to update our dependencies.

See https://github.com/hexojs/hexo-server/pull/85 as a first example

We should decide if we are ok with doing so, because once we start, we'll have to update in cascade most projects

We should also plan to communicate (blog post) on this

Maybe that could also be a trigger for Hexo v4 #2492 

What do you think?

**Comment by YoshinoriN** [comment]
IMHO, current v4 loadmap has many tasks.
We should narrow down a issue for v4 task & should drop Node.js v6 support.

**Comment by SukkaW** [comment]
Finally. NodeJS v6 comes to EOL. It is the time!

**Comment by YoshinoriN** [comment]
@NoahDragon 
Would you please give us advice?

**Comment by tomap** [comment]
I believe we should proceed with the removal of node 6
When done, we should publish a new major version of each component

I'm just worried about hexo itself, as we were planning lots of new stuff for version 4, 
and version 4 might just be caused by the removal of node 6

**Comment by weyusi** [comment]
@tomap 
you mean the hexo version should be bumped to v4 in light of dropping of node 6?

personally I wouldn't mind if minor version bump instead (i.e. v3.9.0). I know it's not a good versioning practice and it would break Node 6 users with hexo `^3.8.0`. For those users, they can either upgrade Node or force version `3.8.0`, meaning the breaking change can be easily fixed.

**Comment by tomap** [comment]
I do not have a clear preference....
Both alternatives make sense to me. Either be more flexible with semantic versioning, or move v4 issues to v5 to make space for dropping node6

**Comment by weyusi** [comment]
If there are only two buttons, I would press on "minor version". Dropping node in a minor version is not that bad; nunjucks added node version requirement (from `*`) in a [_patch_ version](https://github.com/mozilla/nunjucks/compare/323dabe..c2de0e4), and only caused #3380 in hexo, which was easily worked around.

**Comment by YoshinoriN** [comment]
> Alternatively, bump to v4, change roadmap to v5.

IMHO this idea is better than minor version up. But, I think the biggest issue is "who decides this matter?".

**Comment by tomap** [comment]
It is becoming a matter of security.
Few security vulnerabilities are poping up and the only way to fix them is to update and loose nodejs 6 compatibility

I would go with the solution of @YoshinoriN  => bump to v4 = end of nodejs 6
bump to v5 = current v4 roadmap

**Comment by weyusi** [comment]
v4 -> v5 seem safer.

On node requirement, I would like to suggest ` "node": ">= 8.6.0"`. [node.green](https://node.green/) shows node 8.2 doesn't support some js features (that some deps require), while 8.6 & 8.9 have features parity.

**Comment by YoshinoriN** [comment]
OK...

## Conclusion

* Drop Node.js v6
    * Bump to Hexo v4.0
* Current Hexo v4.0 roadmap slide to v5.0

## TBD

* Node.js require version is `>=8.0` or `>=8.6`
    * I agree with @weyusi (`>=8.6`)
* Release schedule

## Others

@hexojs/core

Do you have any suggestion?
And would you please some comment or emoji reactions?

**Comment by segayuu** [comment]
I confirmed that the number of people agreeing using the emoticon response reached the majority of the @hexojs/core team except @YoshinoriN 😊

**Comment by SukkaW** [comment]
If you guys want to drop NodeJS 6 support, then #3328 should be considered.

**Comment by YoshinoriN** [comment]
Thanks @SukkaW :)

Dear all
I will set target Node version is v8.6. Is it OK?

**Comment by tcrowe** [comment]
I think it's fine to drop node v6. I can see that some people want to make contributions but the unit tests can sometimes fail because es6 features.

I might ask that we consider completing hexo v4 roadmap tasks, if they still make sense, for hexo v4 and not push them to hexo v5. I will try to help too.

---

Thanks for everyone who added to the discussion! 🤗

**Comment by YoshinoriN** [comment]
I created [v4.0.0 loadmap](https://github.com/hexojs/hexo/milestone/24) & changed #2492 issue title.

**Comment by weyusi** [comment]
@YoshinoriN 
can you also create a Project as well, to track other repos? Too bad Milestone [can't track](https://github.com/dear-github/dear-github/issues/93) multiple repos.

**Comment by YoshinoriN** [comment]
@weyusi 
It's a nice idea :) 
But, It seems I can't. Maybe it requires owner permission. (I'm member permission)

> [Project board permissions for an organization](https://help.github.com/en/articles/project-board-permissions-for-an-organization)

**Comment by curbengh** [comment]
I think most of the essential plugins have already dropped node 6 by now, just not yet npm-published. So, hexo v4 is more or less ready, unless there are some pending issues.

If there is any pending issue, the following are the ones I can think of:
1. https://github.com/hexojs/hexo-math/pull/94
2. https://github.com/hexojs/hexo-theme-landscape/pull/139

In relation to https://github.com/orgs/hexojs/teams/core/discussions/5, I think plugins should be released right after hexo@4, meaning hexo should be the first to introduce breaking change.

**Comment by YoshinoriN** [comment]
IMHO we publish [these plugins](https://github.com/hexojs/hexo/blob/9b8704758a708f9af6e752c92ecd024458ab0929/package.json#L43-L48) before release hexo v4. It's better these new versions should include hexo v4.

**Comment by curbengh** [comment]
I see what you mean. Those plugins, in addition to [these plugins](https://github.com/hexojs/hexo-starter/blob/bc3c31767bdbf0d9be2b24014ab8beb19c2acb50/package.json#L10-L17) (of hexo-starter) should be published before hexo@4. Other non-essential plugins can be released before or after hexo@4.

**Comment by curbengh** [comment]
Since hexo-util@1 and hexo-renderer-marked@2 have been released, we're almost ready for Hexo 4.

PRs I think should be included in v4:
[ ] https://github.com/hexojs/hexo/pull/3235
[ ] https://github.com/hexojs/hexo/pull/3668
[ ] https://github.com/hexojs/hexo/pull/3672
[ ] https://github.com/hexojs/hexo/pull/3680

**Comment by curbengh** [comment]
I create v4 PR https://github.com/hexojs/hexo/pull/3695 with a checklist of deps to be updated.
