### ISSUE TITLE
There is a problem creating a new article after modifying _config.yml

### ISSUE THREAD

**Issue by WindLo** [hexojs/hexo#3510]
I changed "**new_post_name: :title.md**" to "**new_post_name: ::year-:month-:day-:title.md**",and then a error arose when I executed "**hexo new "My first post"**".

The error is "FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ENOENT: no such file or directory, open 'D:\Hexo\source\_posts\:2019-03-30-My-first-post.md'"

So what is wrong with this?thanks.

**Comment by YoshinoriN** [comment]
Maybe typo.
Not `::year-:month-:day-:title.md`. `:year-:month-:day-:title.md` is correct.
