### ISSUE TITLE
Cannot GET/ if plugins are installed in _config.yml

### ISSUE THREAD

**Issue by fabionebbia** [hexojs/hexo#3511]
I tried to install a plugin so I added
`plugins:`
     `  - hexo-server`
     ` - hexo-other-plugin`
to my `_config.yml` file.

The problem is that when I run `hexo server` the webpage says "Cannot GET /".
Everything is fine if I delete plugins line from the `_config.yml` file, but this way I can't install new plugins.

**Comment by YoshinoriN** [comment]
Hexo plugins are provide npm packages.
Please see npm install document.

> https://docs.npmjs.com/cli/install.html

For example `hexo-server` installation command is `npm install hexo-server --save`
