### ISSUE TITLE
安装hexo时  npm出现上面错误 请问怎么解决？

### ISSUE THREAD

**Issue by RQSA** [hexojs/hexo#3512]
`C:\Users\Syucong丶>npm install hexo-cli -g
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Syucong丶\AppData\Roaming\npm-cache\_logs\2019-03-31T12_29_42_933Z-debug.log
`
安装hexo时  npm出现上面错误 请问怎么解决？

**Comment by YoshinoriN** [comment]
Please try `npm cache clean --force`
