### ISSUE TITLE
hexo init error

### ISSUE THREAD

**Issue by makersmelx** [hexojs/hexo#3515]
## Environment Info

Windows 10

Node version： 10.7.0

Hexo and Plugin version: 1.1.0

## Command
npm install hexo-cli -g
hexo init

## Problem
'hexo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。(command not found)

After I add /hexo/bin to the PATH, it still appears as above.

**Comment by WindLo** [comment]
Have you installed git? And try again in Git Bash after installation. Maybe it will work.
