### ISSUE TITLE
Custom site.variables

### ISSUE THREAD

**Issue by kkdd0909** [hexojs/hexo#3517]
I aim to summarize all post.variables in one place, in a widget.

Lets say I have three posts:

```
layout: post
title: Hello World
animal: bear
``` 

Another `.md` file:
```
layout: post
title: Hello Earth
animal: cow
``` 

Another `.md` file:
```
layout: post
title: Hello Plant
animal: mouse
``` 

From all the above three posts, how can I extract/summarize in a widget all entries for `post.animal`?
So only front-end output like this list:
```
- bear
- cow
- mouse
```

Or better, how to make custom site.variables to use in posts?

**Comment by YoshinoriN** [comment]
@kkdd0909 
How about this?

```ejs
<%
    const x = site.posts.filter(post => post.animal!== undefined);
    x.forEach((e) => console.log(e.animal));
%>
```

**Comment by kkdd0909** [comment]
@YoshinoriN - thanks, that solves it! :)
