### ISSUE TITLE
Count all posts with custom post.variable

### ISSUE THREAD

**Issue by kkdd0909** [hexojs/hexo#3518]
My `custom.post.variable` is `fruit`.
So my `.md` files have:

``` 
title: food
fruit: apple
``` 

and

```
title: more food
fruit: banana
``` 

and

```
title: still more food
fruit: banana
``` 

and

```
title: try some food
fruit: banana
``` 

and

```
title: enjoy food
fruit: apple
``` 

How to count all posts with `fruit: apple`?

**Comment by YoshinoriN** [comment]
@kkdd0909 
Hello :) How about this?

```ejs
<%
    const x = site.posts.filter(post => post.fruit === 'apple');
    console.log(x.length);
%>
```

**Comment by kkdd0909** [comment]
@YoshinoriN 

Hi! Thanks a lot!

If I add another `post.variable` in my `.md` files, such as:

``` 
color: black
```
and
```
color: red
```

Using your solution, how would I:
- count all posts for `each fruit` separately
- count all posts for  `each color` separately

Thank you again for your great help.

**Comment by YoshinoriN** [comment]
@kkdd0909 
I beleve, may be this is answer :) 
```ejs
<%
    const hasColorPosts = site.posts.filter(post => post.color !== undefined);
    const colorBlack = hasColorPosts.filter(post => post.color === 'black')
    const colorRed = hasColorPosts.filter(post => post.color === 'red')
    console.log(colorBlack.length);
    console.log(colorRed.length);
%>
```

Please don't hesitate to ask me if you have any questions.
Thanks :)

**Comment by kkdd0909** [comment]
Hmm... 

I have to apologise because I think I created a confusing question.

I make it better here, sorry again.

So my `.md` files:

```
---
layout: post
title: Hello
color: purple
fruit: banana
```
and

```
---
layout: post
title: Hola amigos!
color: red
fruit: apple
```
and
```
---
layout: post
title: Bonjour
color: purple
fruit: banana
```
and
```
---
layout: post
title: Sayonara
color: red
fruit: mango
```

So in my `.md` files, I can define ANY color and ANY fruit.

I just want to count ALL posts that have the SAME color. Or the SAME fruit.

It will be very long and complicated to define each `type` of `color` or each `type` of `fruit` in the code to make the count (filter).

So I try to make it efficient with this objective:
> Count ALL posts that has the SAME color (or count ALL posts that has the SAME fruit).
And not make definition of each color or each type of fruit because I can have 1000 colors and 1000 fruits... :(

Sorry again for confusion and I hope you can help, you already gave me good approach for solution.

**Comment by YoshinoriN** [comment]
@kkdd0909 
I'm not familiar with JavaScript. But I think maybe this is one of answer.

```ejs
<%
  const hasColorPosts = site.posts.filter(post => post.color!== undefined).map(x => x.color);
  const group = hasColorPosts.reduce((result, current) => {
    const element = result.find((p) => p.name === current);
    if (element) {
      element.count++;
    } else {
      result.push({
        name: current,
        count: 1
      });
    }
    return result;
  }, []);
  console.log(group);
  //Example of result [ { name: 'test2', count: 2 }, { name: 'test1', count: 1 } ]
%>
```

**Comment by kkdd0909** [comment]
@YoshinoriN - perfect, thank you very much! that solves my problem... :)

**Comment by YoshinoriN** [comment]
@kkdd0909 
May we close this?
Thanks :)

**Comment by kkdd0909** [comment]
@YoshinoriN - yes, please, all good... :)
