### ISSUE TITLE
I found a bad link of theme

### ISSUE THREAD

**Issue by ufan0** [hexojs/hexo#3520]
I found a bad link of theme in https://hexo.io/themes/ ，the name is `Raytaylorism`，
its homepage is a spam website.

**Comment by YoshinoriN** [comment]
@ufan0 
Thanks for the report. I made an issue to the theme owner.
And PR for a new link. Please wait for approval :)

**Comment by YoshinoriN** [comment]
@ufan0 
Fixed. Thanks :)
