### ISSUE TITLE
Generating from external source

### ISSUE THREAD

**Issue by JonathanHolvey** [hexojs/hexo#3521]
I want to use Hexo as the generator for a static site I'm building, however, I'd like to feed the source content to Hexo from an external headless CMS, rather than a folder of Markdown files.

Looking at the Hexo API documentation, I can see it uses a `box` object to load the files from the source folder, but  it doesn't look like this box is part of the plugin API.

What would be the best way of pulling content from an external source? I've considered using `generateBefore` event to populate the required Markdown files before the site is generated, but this seems a little clunky.

**Comment by YoshinoriN** [comment]
@JonathanHolvey 
How about migration feature?
> https://hexo.io/docs/migration

I think maybe RSS migrator is better way If you had a RSS.
