### ISSUE TITLE
coney主题不显示头像

### ISSUE THREAD

**Issue by Gangyuanyuan** [hexojs/hexo#3524]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

Your package.json `package.json`: 

## For question
刚安装好时默认头像也不显示

**Comment by gautamz07** [comment]
@Gangyuanyuan what do you mean by avatar ?
