### ISSUE TITLE
hexo next出现大量空白

### ISSUE THREAD

**Issue by 8bun** [hexojs/hexo#3525]
我本来想为我的next博客添加相册功能的，按照网上教程严格做了一遍后，我的博客出现了大量的空白，网上很多的都说是source/文件夹下的文件没有改成lib的原因，可是我的对应位置的文件夹名称就是lib，而且经过F12进行查看网页源代码，没有任何的错误信息。我不知什么原因，会不会是我添加相册功能之前添加的鼠标点击爆炸效果还有动态背景发生了冲突啊》》》可是查看网页源代码没有任何报错信息，而且我点击我的侧边栏，是可以跳转到相应的菜单URL的，而且奇怪的是也显示大量空白，我的博客是https://8bun.github.io，就是这样的：
![image](https://user-images.githubusercontent.com/37058967/55895182-35889b80-5bee-11e9-86d9-a7bde4d0ce6f.png)

**Comment by 8bun** [comment]
哪位大神知道啊，搭建了好久的博客，现在不想放弃重做啊》》》

**Comment by Doslin** [comment]
## 同求，我今天也遇到这种情况了 
我的hexo的版本 
```
[root@VM_0_9_centos hexo]# hexo version
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 3.10.0-862.el7.x86_64 linux x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

**Comment by Doslin** [comment]
@8bun 你解决了吗，我自己的错误是
``` fancyBox: true

**Comment by 8bun** [comment]
最近没有去理他，请问你是修改哪里的fancybox啊

**Comment by Doslin** [comment]
我得错误/blog/themes/next/_config.yml   中的fancyboxs标签置为true了
修改后
 `# Fancybox. There is support for old version 2 and new version 3.
# Choose only one variant, do not need to install both.
# To install 2.x: https://github.com/theme-next/theme-next-fa''''ncybox
# To install 3.x: https://github.com/theme-next/theme-next-fancybox3
fancybox: false
`

**Comment by 8bun** [comment]
然后你有改其他地方的东西吗

**Comment by Doslin** [comment]
没有

**Comment by 8bun** [comment]
但是我还是不行

**Comment by 8bun** [comment]
你可以发一下你的config文件内容吗？

**Comment by Doslin** [comment]
这里也不好发，推荐你去我的项目看  看我的hexo分支

**Comment by Doslin** [comment]
[这个](https://github.com/Doslin/doslin.github.io/tree/Hexo/themes/next)

**Comment by hxhb** [comment]
> 最近没有去理他，请问你是修改哪里的fancybox啊

遇到了同样的问题，你解决了吗？
