### ISSUE TITLE
run at localhost:4000.it dose not work well with to much article, but after deploy it works well

### ISSUE THREAD

**Issue by tal007** [hexojs/hexo#3526]
run at localhost:4000.it dosen't worw well with to much article, but after deploy it works weel

when at localshot:4000 , i see the source code, it shows like this
![image](https://user-images.githubusercontent.com/25813059/55969296-1eaa7d80-5cb0-11e9-95f7-b88c97c0a181.png)

![image](https://user-images.githubusercontent.com/25813059/55969452-67623680-5cb0-11e9-9f47-9e7c4add9820.png)

and when i deploy
![image](https://user-images.githubusercontent.com/25813059/55969498-78ab4300-5cb0-11e9-98c9-48aaa3946093.png)

it's OK in the end
![image](https://user-images.githubusercontent.com/25813059/55969528-89f44f80-5cb0-11e9-9380-98353a0c75e2.png)

SO, what can i do?

**Comment by gautamz07** [comment]
@tal007 , do you use UTF-8 encoding ?

**Comment by tal007** [comment]
> @tal007 , do you use UTF-8 encoding ?

**Comment by tal007** [comment]
@gautamz07 I think it's UTF-8,but i'm not sure.I just not work well at localhost.In localhost, where i can set the encoding?

**Comment by gautamz07** [comment]
see if you have the meta tag:

`<meta charset="UTF-8">`

**Comment by tal007** [comment]
@gautamz07 Of course.
![image](https://user-images.githubusercontent.com/25813059/56702929-2ac71e00-6739-11e9-8bc3-690736042c78.png)

this is the code of upload.

and where i can set the encoding when it dose not upload. There is not a `index.html` in the project. 
can is set in config.yml

to be honest, it is work well when i first use hexo building my blog, but when i change the theme of my blog, it shows this problem, i don't know what's wrong whit it. so i set a new problem, use the same theme [melody](https://github.com/Molunerfinn/hexo-theme-melody), i copy some of my article to the new project, it shows the same problem.So dose next-theme.they all have the same problem, the article all shows in the home page, without read more. I don't know if here wrong.

the first theme [jsimple](https://github.com/tangkunyin/hexo-theme-jsimple) just shows the main information of the article.
