### ISSUE TITLE
How about adding one function on commiting message?

### ISSUE THREAD

**Issue by AgentEric** [hexojs/hexo#3528]
I want to request one **new function**.Since most of our users are using Hexo in building blog into github pages,how about supplying a new function to ***commit messages*** to git pages similar to "git commit" when we delpoy our contents.
Considering about the one who doesn't need it, we could add a switch like: ""***delpoy_message: false***".
Thank all your work~

**Comment by tomap** [comment]
Hi,

Could you be more specific?
When would you like to see a "commit message" ?
When you deploy?
To Github?
then your  request should be here: https://github.com/hexojs/hexo-deployer-git

**Comment by AgentEric** [comment]
> Hi,
> 
> Could you be more specific?
> When would you like to see a "commit message" ?
> When you deploy?
> To Github?
> then your request should be here: https://github.com/hexojs/hexo-deployer-git

Oh Yeah.Definitely.Thank you .I'll  copy this request to the issue :https://github.com/hexojs/hexo-deployer-git

**Comment by tcrowe** [comment]
The message is customizable from the options. I'm not sure if that helps:

https://github.com/hexojs/hexo-deployer-git#options

Let us know if you fixed it, @AgentEric !

**Comment by tcrowe** [comment]
Oh and deploy event here: https://hexo.io/api/events
