### ISSUE TITLE
hexo安装完后很多命令无效的

### ISSUE THREAD

**Issue by watership** [hexojs/hexo#353]
localhost:~ apple$ hexo new "title"
Usage: hexo <command>

Commands:
  help      Get help on a command
  init      Create a new Hexo folder
  migrate   Migrate your site from other system to Hexo
  version   Display version information

Global Options:
  --debug   Display all verbose messages in the terminal
  --safe    Disable all plugins and scripts

For more help, you can use `hexo help [command]` for the detailed information
or you can check the docs: http://zespia.tw/hexo/docs/

大部分命令都这样显示，都无效了，怎么回事啊？

**Comment by LeoCui** [comment]
你试试在先切到你新建的那个hexo的folder里再执行这些命令，应该就行了
我的就是这样解决的

**Comment by bocaia** [comment]
我的输入hexo generate出现这个怎么回事

FATAL EACCES: permission denied, open '/hexo/package.json'
Error: EACCES: permission denied, open '/hexo/package.json'
    at Error (native)

**Comment by icessun** [comment]
@bocaia 是不是缺少了依赖
