### ISSUE TITLE
代码块中带<>会被渲染成html标签

### ISSUE THREAD

**Issue by ZhangCrystal** [hexojs/hexo#3532]
## For BUG
markdown代码块如下：
<img width="1114" alt="WeChat8d5d7a88b3631eafe07f2e2a90539736" src="https://user-images.githubusercontent.com/19789670/56111494-c5319f80-5f8a-11e9-866f-7f34980718f4.png">

但是渲染的时候会把带<>的部分渲染成HTML标签,导致代码显示不全
<img width="928" alt="WeChat821bf42b8e18b7b7644eac6722513bf9" src="https://user-images.githubusercontent.com/19789670/56111525-dc708d00-5f8a-11e9-9f53-4052c89a0fe4.png">

**Comment by gautamz07** [comment]
@ZhangCrystal unable to reproduce this issue , can you you post more details like hexo version etc. ?

what happens when you paste just `<U>Completion !<U>`
