### ISSUE TITLE
Chinese quote disaster

### ISSUE THREAD

**Issue by torappinfo** [hexojs/hexo#3535]
The markdown engine used in hexo is too complicated. For no reasons, it tries to convert all double/single quotes to Chinese quotes, even in code blocks. 

If someone wants chinese quotes, they can type them. All Chinese input methods support that. 

We cannot predict how users use markdown/html tags. So please do not make decisions for users, use a simpler markdown converter.

Thanks a lot.

**Comment by torappinfo** [comment]
It's totally a mess when using tab, four spaces, back-quote or <code> tag. Sometimes, quotes are converted to Chinese quotes, sometime not, sometimes to html code like "&quote;".
Why not keep as it is? It is simpler, more robust and faster.

**Comment by torappinfo** [comment]
When unicode is used in markdown, I am not the only one made mad by hexo quote disaster.

**Comment by tcrowe** [comment]
I never really noticed it. Luckily it's configurable!

https://github.com/hexojs/hexo-renderer-marked#options

`./_config.yml`

```yaml
marked:
  smartypants: false
```

I'm guessing by "smartypants" they meant "annoy @torappinfo by stealing his pants." 😈
