### ISSUE TITLE
_config.yml文件title和description匹配有问题

### ISSUE THREAD

**Issue by worldhomtel** [hexojs/hexo#3536]
## Environment Info

Your site `_config.yml` 

## For BUG

在`_config.yml`文件中修改`title`和`description`部分，在生成的`index.html`文件中却将其中的`title`部分呈现出来，而为显示配置文件中的`description`部分

**Comment by weyusi** [comment]
attach your _config.yml, the post's .md and the resulting index.html. Tell us which line(s) of index.html has issue and what is the expected behavior.

**Comment by worldhomtel** [comment]
_config.yml
`# Site
title: WorldHomtel
subtitle: 网罗全网精品民宿
description: 只要说出您的要求，帮您全网找民宿
keywords: 东南亚民宿,Airbnb,东京民宿宿,大阪民宿,首尔民宿,泰国民宿
author: SunHigh
language: zh-CN
timezone:
content: Hello`

index.html
`    <meta charset="utf-8">
    <meta name="keywords" content="东南亚民宿,Airbnb,东京民宿宿,大阪民宿,首尔民宿,泰国民宿">
    <meta name="description" content="WorldHomtel">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="renderer" content="webkit|ie-stand|ie-comp">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>WorldHomtel</title>
    <link rel="icon" type="image/png" href="/favicon.png">`

My description is "只要说出您的要求，帮您全网找民宿",but in the 'index.html' it show "WorldHomtel"

**Comment by weyusi** [comment]
Works for me:
```html
<head><meta name="generator" content="Hexo 3.8.0">
<meta charset="utf-8">
  <title>WorldHomtel</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="只要说出您的要求，帮您全网找民宿">
<meta name="keywords" content="东南亚民宿,Airbnb,东京民宿宿,大阪民宿,首尔民宿,泰国民宿">
<meta property="og:type" content="website">
<meta property="og:title" content="WorldHomtel">
<meta property="og:url" content="https://weyusi.github.io/hexo-testing/index.html">
<meta property="og:site_name" content="WorldHomtel">
<meta property="og:description" content="只要说出您的要求，帮您全网找民宿">
<meta property="og:locale" content="zh-CN">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="WorldHomtel">
<meta name="twitter:description" content="只要说出您的要求，帮您全网找民宿">
<link rel="icon" href="/favicon.ico">
</head>
```

Can you attach the whole `<head>`? Use ``` to format them nicely in the comment.
also attach the `layout/_partial/head.ejs` of the installed theme, output of the command `npm ls --depth 0` and content of `package.json` (the last two are already requested when you create this issue).

**Comment by weyusi** [comment]
@worldhomtel 
any update?
