### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by bmwz110** [hexojs/hexo#3547]
运行hexo g出现了以下问题：
⚠️bmwz110.github.io is my hexo root directory(这个文件夹就是我的hexo项目根目录)
⚠️No problem occurred after running 2 months ago（2个月前运行hexo g和d没有出现问题）
⬇️error:⬇️
bmwz110.github.io lc$ hexo g
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

🙏Thanks for anyone

**Comment by gautamz07** [comment]
@bmwz110 you are running `hexo g` where exactly ? if i'am not mistaken thats something you wanna run on your local machine ? and then push the files to your github repo ..

**Comment by bmwz110** [comment]
> @bmwz110 you are running `hexo g` where exactly ? if i'am not mistaken thats something you wanna run on your local machine ? and then push the files to your github repo ..

yes, I running hexo g in the bmwz110.github.io folder, but it prompts an error like I described.

now I want to update the same as before, just running hexo g and hexo d, finish! Not modify the file and use 'add' and 'push' it to github repo.

**Comment by bmwz110** [comment]
I find my answer: add     theme: next    in the root folder _config.yml beneath # Site.

**Comment by tcrowe** [comment]
Thank you for telling us about the fix. 👍🏻
