### ISSUE TITLE
Question for help

### ISSUE THREAD

**Issue by sukai-cheng** [hexojs/hexo#3549]
![image](https://user-images.githubusercontent.com/35868545/57702108-f091d200-768f-11e9-91e1-07f3e6d3de72.png)

**Comment by sukai-cheng** [comment]
The hexo has installed, but there has exsisted error ... I don't know how to resolve it...

**Comment by gautamz07** [comment]
@sukai-cheng whats your node version 

`node -v` ?

**Comment by sukai-cheng** [comment]
> @sukai-cheng whats your node version
> 
> `node -v` ?
thank you for your reply, my node version is v10.15.3

**Comment by gautamz07** [comment]
@sukai-cheng it says you don't have permission , i believe your using `linux` , can you try `sudo` command before `npm` ? or run the command `npm install -g hexo cli` as an admin ?
