### ISSUE TITLE
关于hexo的配置：post_asset_folder 问题

### ISSUE THREAD

**Issue by thinkycx** [hexojs/hexo#3551]
已经参考了官方文档：https://hexo.io/zh-cn/docs/asset-folders
如果需要使用相对目录访问图片，打开_config.yml中的配置：post_asset_folder即可。

但是这样的话，每个md都会生成一个文件夹。可否把这些文件夹都放到当前目录下的一个img文件夹下呢？这样没有很多文件夹，也很简洁了。

结构比如：
```
_posts/1-filename.md
_posts/2-filename.md
_posts/img/1-filename/1.png
_posts/img/2-filename/.png
```
```
1.md内容：
![](img/1-filename/1.png)
```

但是测试之后，发现这样引用不会把图片显示出来。请问应该如何配置呢？谢谢。

**Comment by stevenjoezhang** [comment]
使用 asset_img tag 即可 https://hexo.io/zh-cn/docs/tag-plugins.html#引用资源
