### ISSUE TITLE
ERROR _.reduce is not a function when doing「hexo s」

### ISSUE THREAD

**Issue by omnibingo** [hexojs/hexo#3552]
the log is like：

INFO  Deleted database.
03:07:48.816 DEBUG Writing database to /Users/bingo/Dropbox/saving/say.cool/db.json
03:07:48.834 DEBUG Hexo version: 3.8.0
03:07:48.835 DEBUG Working directory: ~/Dropbox/saving/say.cool/
03:07:48.914 DEBUG Config loaded: ~/Dropbox/saving/say.cool/_config.yml
03:07:48.948 DEBUG Plugin loaded: hexo-deployer-git
03:07:48.950 DEBUG Plugin loaded: hexo-generator-category
03:07:48.952 DEBUG Plugin loaded: hexo-generator-archive
03:07:48.953 DEBUG Plugin loaded: hexo-generator-index
03:07:49.000 DEBUG Plugin loaded: hexo-generator-json-content
03:07:49.003 DEBUG Plugin loaded: hexo-generator-search
03:07:49.004 DEBUG Plugin loaded: hexo-generator-tag
03:07:49.041 DEBUG Plugin loaded: hexo-helper-live2d
03:07:49.175 DEBUG Plugin loaded: hexo-inject
03:07:49.179 DEBUG Plugin loaded: hexo-renderer-ejs
03:07:49.227 DEBUG Plugin loaded: hexo-renderer-less
03:07:49.238 DEBUG Plugin loaded: hexo-renderer-marked
03:07:49.239 DEBUG Plugin loaded: hexo-renderer-stylus
03:07:49.285 DEBUG Plugin loaded: hexo-server
03:07:49.286 DEBUG Plugin loaded: hexo-wordcount
03:07:49.291 DEBUG Script loaded: themes/next/scripts/merge-configs.js
03:07:49.292 DEBUG Script loaded: themes/next/scripts/tags/button.js
03:07:49.292 DEBUG Script loaded: themes/next/scripts/tags/center-quote.js
03:07:49.292 DEBUG Script loaded: themes/next/scripts/tags/exturl.js
03:07:49.293 DEBUG Script loaded: themes/next/scripts/tags/full-image.js
03:07:49.293 DEBUG Script loaded: themes/next/scripts/tags/label.js
03:07:49.293 DEBUG Script loaded: themes/next/scripts/tags/lazy-image.js
03:07:49.294 DEBUG Script loaded: themes/next/scripts/tags/note.js
03:07:49.294 DEBUG Script loaded: themes/next/scripts/tags/tabs.js
03:07:49.295 DEBUG Script loaded: themes/next/scripts/tags/group-pictures.js
03:07:49.297 DEBUG Script loaded: themes/next/scripts/merge.js
03:07:49.298 DEBUG [hexo-inject] firing inject_ready
03:07:49.309 DEBUG Loading database.
03:07:49.318 INFO  Start processing
03:07:49.383 DEBUG Processed: CNAME.rtf
03:07:49.403 DEBUG Processed: favicon.ico
03:07:49.450 DEBUG Processed: coolthing/index.jpg
03:07:49.496 DEBUG Processed: old.md
03:07:49.517 DEBUG Processed: source/css/main.styl
03:07:49.518 DEBUG Processed: source/images/algolia_logo.svg
03:07:49.518 DEBUG Processed: source/images/avatar.gif
03:07:49.518 DEBUG Processed: source/images/cc-by-nc-nd.svg
03:07:49.519 DEBUG Processed: source/images/cc-by-nc-sa.svg
03:07:49.519 DEBUG Processed: source/images/cc-by-nc.svg
03:07:49.520 DEBUG Processed: source/images/cc-by-nd.svg
03:07:49.520 DEBUG Processed: source/images/cc-by-sa.svg
03:07:49.520 DEBUG Processed: source/images/cc-by.svg
03:07:49.520 DEBUG Processed: source/images/cc-zero.svg
03:07:49.521 DEBUG Processed: source/images/loading.gif
03:07:49.521 DEBUG Processed: source/images/placeholder.gif
03:07:49.521 DEBUG Processed: source/images/quote-l.svg
03:07:49.521 DEBUG Processed: source/images/quote-r.svg
03:07:49.521 DEBUG Processed: source/images/searchicon.png
03:07:49.564 DEBUG Processed: _posts/AGMXSeries.md
03:07:49.565 DEBUG Processed: book/index.md
03:07:49.566 DEBUG Processed: _posts/AGMXUniverse.md
03:07:49.567 DEBUG Processed: coolthing/如何打造一台你心目中的好手机？.md
03:07:49.569 DEBUG Processed: _posts/AppleFantasy.md
03:07:49.570 DEBUG Processed: coolthing/是的，我从同花顺离职了.md
03:07:49.572 DEBUG Processed: _posts/CutTheCrap.md
03:07:49.572 DEBUG Processed: prediction/index.md
03:07:49.577 DEBUG Processed: _posts/MIX2.md
03:07:49.577 DEBUG Processed: video/index.md
03:07:49.578 DEBUG Processed: _posts/CatiSpecker.md
03:07:49.579 DEBUG Processed: _posts/NK650Modify.md
03:07:49.580 DEBUG Processed: _posts/NubiaZ7minis.md
03:07:49.581 DEBUG Processed: _posts/NutsFantasy.md
03:07:49.583 DEBUG Processed: _posts/Radiooo.md
03:07:49.584 DEBUG Processed: _posts/RokidPebble.md
03:07:49.590 DEBUG Processed: _posts/TianHuangPing.md
03:07:49.591 DEBUG Processed: _posts/WolfberryIsland.md
03:07:49.592 DEBUG Processed: _posts/hire.md
03:07:49.593 DEBUG Processed: _posts/helloear.md
03:07:49.594 DEBUG Processed: _posts/theHHKB.md
03:07:49.595 DEBUG Processed: _posts/them.md
03:07:49.596 DEBUG Processed: _posts/vivo X5 Max 真的“薄过头”了吗？.md
03:07:49.597 DEBUG Processed: _posts/vivo X5 Pro：她的“美”，你看懂了么？.md
03:07:49.598 DEBUG Processed: _posts/vivo X5 试音「雨下一整晚」.md
03:07:49.599 DEBUG Processed: _posts/vivox20.md
03:07:49.601 DEBUG Processed: _posts/“大于等于三”理论的又一位中枪者---Fineck智能颈环产品评说.md
03:07:49.604 DEBUG Processed: _posts/为什么需要一台Win板儿？.md
03:07:49.605 DEBUG Processed: _posts/久违的电视，你还好吗？—TCL 4k游戏电视体验分享.md
03:07:49.606 DEBUG Processed: _posts/产品狗的一天到底是怎样的？.md
03:07:49.606 DEBUG Processed: _posts/共享充电宝，听完这5分钟才算懂.md
03:07:49.607 DEBUG Processed: _posts/同花顺，你看世界的另一扇窗.md
03:07:49.620 DEBUG Processed: _posts/坚果的幻想.md
03:07:49.621 DEBUG Processed: _posts/如何打造一台你心目中的好手机？.md
03:07:49.622 DEBUG Processed: _posts/当我们聊起HTC，我们聊些什么？.md
03:07:49.623 DEBUG Processed: _posts/手机市场的夏夜盘点.md
03:07:49.624 DEBUG Processed: _posts/教你分分钟变成音乐玩家 ---独家即兴伴奏快速教程.md
03:07:49.625 DEBUG Processed: _posts/坚果Pro闲聊.md
03:07:49.626 DEBUG Processed: _posts/是的，我从同花顺离职了.md
03:07:49.628 DEBUG Processed: _posts/每日说库日历.md
03:07:49.630 DEBUG Processed: _posts/百雀羚，一个年代的失落.md
03:07:49.630 DEBUG Processed: _posts/超越苹果的最佳时间窗口？---三星S6 Edge初评.md
03:07:49.631 DEBUG Processed: _posts/锤子眼前的“弱水三千”.md
03:07:49.823 DEBUG Processed: layout/_layout.swig
03:07:49.823 DEBUG Processed: layout/archive.swig
03:07:49.823 DEBUG Processed: layout/category.swig
03:07:49.823 DEBUG Processed: layout/index.swig
03:07:49.823 DEBUG Processed: layout/page.swig
03:07:49.823 DEBUG Processed: layout/schedule.swig
03:07:49.823 DEBUG Processed: layout/post.swig
03:07:49.823 DEBUG Processed: layout/tag.swig
03:07:49.825 DEBUG Theme config loaded.
03:07:49.828 DEBUG Processed: _posts/业界疲态下的顶峰，vivo Xplay3S使用随笔.md
03:07:49.828 DEBUG Processed: coolthing/如何从零开始，一手完成一部App宣传片.md
03:07:49.829 DEBUG Processed: languages/de.yml
03:07:49.829 DEBUG Processed: languages/en.yml
03:07:49.829 DEBUG Processed: languages/default.yml
03:07:49.829 DEBUG Processed: languages/id.yml
03:07:49.829 DEBUG Processed: languages/fr-FR.yml
03:07:49.829 DEBUG Processed: languages/ja.yml
03:07:49.829 DEBUG Processed: languages/ko.yml
03:07:49.829 DEBUG Processed: languages/pt-BR.yml
03:07:49.829 DEBUG Processed: languages/pt.yml
03:07:49.829 DEBUG Processed: languages/ru.yml
03:07:49.829 DEBUG Processed: languages/zh-Hans.yml
03:07:49.830 DEBUG Processed: languages/zh-hk.yml
03:07:49.830 DEBUG Processed: languages/zh-tw.yml
03:07:49.830 DEBUG Processed: _config.yml
03:07:49.831 DEBUG Processed: _posts/关于平衡独轮车你可能关心的二三事.md
03:07:49.831 DEBUG Processed: coolthing/让电动透出极客味儿---小牛N1S都市版体验.md
03:07:49.832 DEBUG Processed: _posts/在那“走向帝国”的路上---华为荣耀6 Plus评说.md
03:07:49.833 DEBUG Processed: _posts/如何从零开始，一手完成一部App宣传片.md
03:07:49.833 DEBUG Processed: _posts/维沃深思 --- Thinking in vivo.md
03:07:49.833 DEBUG Processed: _posts/让电动透出极客味儿---小牛N1S都市版体验.md
03:07:49.838 DEBUG Processed: source/js/src/affix.js
03:07:49.838 DEBUG Processed: source/js/src/algolia-search.js
03:07:49.839 DEBUG Processed: source/js/src/bootstrap.js
03:07:49.839 DEBUG Processed: source/js/src/exturl.js
03:07:49.839 DEBUG Processed: source/js/src/hook-duoshuo.js
03:07:49.840 DEBUG Processed: source/js/src/js.cookie.js
03:07:49.840 DEBUG Processed: source/js/src/motion.js
03:07:49.840 DEBUG Processed: source/js/src/post-details.js
03:07:49.840 DEBUG Processed: source/js/src/scroll-cookie.js
03:07:49.841 DEBUG Processed: source/js/src/scrollspy.js
03:07:49.841 DEBUG Processed: source/js/src/utils.js
03:07:49.841 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.css
03:07:49.842 DEBUG Processed: source/lib/canvas-nest/canvas-nest.min.js
03:07:49.842 DEBUG Processed: source/lib/canvas-ribbon/canvas-ribbon.js
03:07:49.842 DEBUG Processed: source/lib/fastclick/LICENSE
03:07:49.843 DEBUG Processed: source/lib/fastclick/README.md
03:07:49.843 DEBUG Processed: source/lib/fastclick/bower.json
03:07:49.844 DEBUG Processed: source/lib/font-awesome/HELP-US-OUT.txt
03:07:49.844 DEBUG Processed: source/lib/font-awesome/bower.json
03:07:49.845 DEBUG Processed: source/lib/jquery_lazyload/CONTRIBUTING.md
03:07:49.845 DEBUG Processed: source/lib/jquery_lazyload/README.md
03:07:49.845 DEBUG Processed: source/lib/jquery_lazyload/bower.json
03:07:49.845 DEBUG Processed: source/lib/jquery_lazyload/jquery.lazyload.js
03:07:49.846 DEBUG Processed: source/lib/jquery_lazyload/jquery.scrollstop.js
03:07:49.846 DEBUG Processed: source/lib/pace/pace-theme-barber-shop.min.css
03:07:49.846 DEBUG Processed: source/lib/pace/pace-theme-big-counter.min.css
03:07:49.847 DEBUG Processed: source/lib/pace/pace-theme-bounce.min.css
03:07:49.847 DEBUG Processed: source/lib/pace/pace-theme-center-atom.min.css
03:07:49.848 DEBUG Processed: source/lib/pace/pace-theme-center-circle.min.css
03:07:49.848 DEBUG Processed: source/lib/pace/pace-theme-center-radar.min.css
03:07:49.848 DEBUG Processed: source/lib/pace/pace-theme-center-simple.min.css
03:07:49.849 DEBUG Processed: source/lib/pace/pace-theme-corner-indicator.min.css
03:07:49.849 DEBUG Processed: source/lib/pace/pace-theme-fill-left.min.css
03:07:49.850 DEBUG Processed: source/lib/pace/pace-theme-flash.min.css
03:07:49.850 DEBUG Processed: source/lib/pace/pace-theme-loading-bar.min.css
03:07:49.851 DEBUG Processed: source/lib/pace/pace-theme-mac-osx.min.css
03:07:49.851 DEBUG Processed: source/lib/pace/pace-theme-minimal.min.css
03:07:49.852 DEBUG Processed: source/lib/pace/pace.min.js
03:07:49.853 DEBUG Processed: source/lib/three/canvas_lines.min.js
03:07:49.853 DEBUG Processed: source/lib/three/canvas_sphere.min.js
03:07:49.854 DEBUG Processed: source/lib/three/three-waves.min.js
03:07:49.854 DEBUG Processed: source/lib/velocity/bower.json
03:07:49.855 DEBUG Processed: source/lib/velocity/velocity.min.js
03:07:49.855 DEBUG Processed: source/lib/velocity/velocity.ui.js
03:07:49.855 DEBUG Processed: source/lib/velocity/velocity.ui.min.js
03:07:49.873 DEBUG Processed: calendar/index.md
03:07:49.942 DEBUG Processed: layout/_custom/header.swig
03:07:49.942 DEBUG Processed: layout/_custom/sidebar.swig
03:07:49.942 DEBUG Processed: layout/_macro/post-collapse.swig
03:07:49.942 DEBUG Processed: layout/_macro/post-copyright.swig
03:07:49.942 DEBUG Processed: layout/_macro/reward.swig
03:07:49.942 DEBUG Processed: layout/_macro/wechat-subscriber.swig
03:07:49.942 DEBUG Processed: layout/_partials/footer.swig
03:07:49.943 DEBUG Processed: layout/_macro/sidebar.swig
03:07:49.943 DEBUG Processed: layout/_partials/head.swig
03:07:49.943 DEBUG Processed: layout/_partials/comments.swig
03:07:49.943 DEBUG Processed: layout/_partials/page-header.swig
03:07:49.943 DEBUG Processed: layout/_partials/pagination.swig
03:07:49.943 DEBUG Processed: layout/_partials/header.swig
03:07:49.943 DEBUG Processed: layout/_partials/search.swig
03:07:49.943 DEBUG Processed: layout/_scripts/boostrap.swig
03:07:49.943 DEBUG Processed: layout/_scripts/commons.swig
03:07:49.943 DEBUG Processed: layout/_scripts/vendors.swig
03:07:49.943 DEBUG Processed: layout/_third-party/duoshuo-hot-articles.swig
03:07:49.943 DEBUG Processed: layout/_third-party/exturl.swig
03:07:49.944 DEBUG Processed: layout/_third-party/mathjax.swig
03:07:49.944 DEBUG Processed: layout/_third-party/schedule.swig
03:07:49.944 DEBUG Processed: layout/_third-party/rating.swig
03:07:49.944 DEBUG Processed: layout/_third-party/scroll-cookie.swig
03:07:49.950 DEBUG Processed: source/lib/Han/dist/han.css
03:07:49.950 DEBUG Processed: source/lib/Han/dist/han.min.js
03:07:49.951 DEBUG Processed: source/js/src/schemes/pisces.js
03:07:49.951 DEBUG Processed: source/lib/fancybox/source/blank.gif
03:07:49.951 DEBUG Processed: source/lib/fancybox/source/fancybox_loading.gif
03:07:49.952 DEBUG Processed: source/lib/fancybox/source/fancybox_loading@2x.gif
03:07:49.952 DEBUG Processed: source/lib/fancybox/source/fancybox_overlay.png
03:07:49.953 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite.png
03:07:49.953 DEBUG Processed: source/lib/fancybox/source/fancybox_sprite@2x.png
03:07:49.954 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.css
03:07:49.954 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.pack.js
03:07:49.954 DEBUG Processed: source/lib/fastclick/lib/fastclick.js
03:07:49.955 DEBUG Processed: source/lib/fastclick/lib/fastclick.min.js
03:07:49.955 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css
03:07:49.955 DEBUG Processed: source/lib/font-awesome/css/font-awesome.css.map
03:07:49.955 DEBUG Processed: source/lib/font-awesome/css/font-awesome.min.css
03:07:49.955 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.min.js
03:07:49.956 DEBUG Processed: source/lib/ua-parser-js/dist/ua-parser.pack.js
03:07:49.964 DEBUG Processed: layout/_scripts/schemes/muse.swig
03:07:49.964 DEBUG Processed: layout/_scripts/schemes/mist.swig
03:07:49.965 DEBUG Processed: source/lib/Han/dist/han.js
03:07:49.965 DEBUG Processed: source/lib/Han/dist/han.min.css
03:07:49.966 DEBUG Processed: source/lib/fancybox/source/jquery.fancybox.js
03:07:49.966 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff
03:07:49.966 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.woff2
03:07:49.966 DEBUG Processed: source/lib/jquery/index.js
03:07:49.966 DEBUG Processed: source/lib/velocity/velocity.js
03:07:50.014 DEBUG Processed: layout/_macro/post.swig
03:07:50.015 DEBUG Processed: layout/_partials/head/custom-head.swig
03:07:50.015 DEBUG Processed: layout/_partials/search/localsearch.swig
03:07:50.015 DEBUG Processed: layout/_partials/head/external-fonts.swig
03:07:50.015 DEBUG Processed: layout/_partials/search/swiftype.swig
03:07:50.015 DEBUG Processed: layout/_partials/search/tinysou.swig
03:07:50.015 DEBUG Processed: layout/_partials/share/duoshuo_share.swig
03:07:50.015 DEBUG Processed: layout/_partials/share/jiathis.swig
03:07:50.015 DEBUG Processed: layout/_partials/share/add-this.swig
03:07:50.015 DEBUG Processed: layout/_partials/share/baidushare.swig
03:07:50.015 DEBUG Processed: layout/_scripts/pages/post-details.swig
03:07:50.015 DEBUG Processed: layout/_third-party/analytics/baidu-analytics.swig
03:07:50.015 DEBUG Processed: layout/_third-party/analytics/busuanzi-counter.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/application-insights.swig
03:07:50.016 DEBUG Processed: layout/_scripts/schemes/gemini.swig
03:07:50.016 DEBUG Processed: layout/_scripts/schemes/pisces.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/index.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/lean-analytics.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/facebook-sdk.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/google-analytics.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/cnzz-analytics.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/tencent-analytics.swig
03:07:50.016 DEBUG Processed: layout/_third-party/comments/changyan.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/tencent-mta.swig
03:07:50.016 DEBUG Processed: layout/_third-party/analytics/vkontakte-api.swig
03:07:50.016 DEBUG Processed: layout/_third-party/comments/disqus.swig
03:07:50.016 DEBUG Processed: layout/_third-party/comments/hypercomments.swig
03:07:50.016 DEBUG Processed: layout/_third-party/comments/index.swig
03:07:50.017 DEBUG Processed: layout/_third-party/comments/youyan.swig
03:07:50.017 DEBUG Processed: layout/_third-party/comments/livere.swig
03:07:50.017 DEBUG Processed: layout/_third-party/comments/duoshuo.swig
03:07:50.017 DEBUG Processed: layout/_third-party/search/index.swig
03:07:50.017 DEBUG Processed: layout/_third-party/seo/baidu-push.swig
03:07:50.017 DEBUG Processed: layout/_third-party/search/tinysou.swig
03:07:50.028 DEBUG Processed: source/lib/Han/dist/font/han-space.otf
03:07:50.028 DEBUG Processed: source/lib/Han/dist/font/han-space.woff
03:07:50.029 DEBUG Processed: source/lib/Han/dist/font/han.otf
03:07:50.029 DEBUG Processed: source/lib/Han/dist/font/han.woff
03:07:50.029 DEBUG Processed: source/lib/fancybox/source/helpers/fancybox_buttons.png
03:07:50.029 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.css
03:07:50.030 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-buttons.js
03:07:50.030 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-media.js
03:07:50.030 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.css
03:07:50.030 DEBUG Processed: source/lib/fancybox/source/helpers/jquery.fancybox-thumbs.js
03:07:50.030 DEBUG Processed: source/lib/font-awesome/fonts/FontAwesome.otf
03:07:50.030 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.ttf
03:07:50.033 DEBUG Processed: layout/_third-party/search/localsearch.swig
03:07:50.033 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.eot
03:07:50.037 DEBUG Processed: layout/_third-party/search/algolia-search/assets.swig
03:07:50.037 DEBUG Processed: layout/_third-party/search/algolia-search/dom.swig
03:07:50.039 DEBUG Processed: source/lib/algolia-instant-search/instantsearch.min.js
03:07:50.042 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.svg
03:07:50.042 DEBUG Processed: source/lib/three/three.min.js
03:07:50.597 FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html

TypeError: _.reduce is not a function
    at initialize.exports.find (/Users/bingo/Dropbox/saving/say.cool/node_modules/cheerio/lib/api/traversing.js:15:17)
    at initialize.module.exports (/Users/bingo/Dropbox/saving/say.cool/node_modules/cheerio/lib/cheerio.js:86:18)
    at new initialize (/Users/bingo/Dropbox/saving/say.cool/node_modules/cheerio/lib/static.js:29:20)
    at initialize (/Users/bingo/Dropbox/saving/say.cool/node_modules/cheerio/lib/static.js:26:14)
    at Hexo.hexoMetaGeneratorInject (/Users/bingo/Dropbox/saving/say.cool/node_modules/hexo/lib/plugins/filter/meta_generator.js:10:9)
    at Hexo.tryCatcher (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.each.filter (/Users/bingo/Dropbox/saving/say.cool/node_modules/hexo/lib/extend/filter.js:63:65)
    at tryCatcher (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/bingo/Dropbox/saving/say.cool/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
03:07:50.623 DEBUG Database saved

is that something wrong with my /node_modules ?

**Comment by omnibingo** [comment]
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 16.6.0 darwin x64
node: 12.2.0
v8: 7.4.288.21-node.17
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.38.0
napi: 4
llhttp: 1.1.3
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1

**Comment by gautamz07** [comment]
@omnibingo what is the command you ran ? what exactly are you trying to do ?

**Comment by omnibingo** [comment]
> @omnibingo what is the command you ran ? what exactly are you trying to do ?

I was just trying to post an article...

I ran："hexo server" just to have a quick look...

**Comment by gautamz07** [comment]
and then you got the above errors ?

Can you run `npm install` and then `hexo server` ?
