### ISSUE TITLE
Issue: Invalid grammar for citing articles from websites

### ISSUE THREAD

**Issue by LourisXu** [hexojs/hexo#3553]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):
v10.15.0

Your package.json `package.json`: 
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-imagemin": "^5.0.3",
    "gulp-minify-css": "^1.2.4",
    "gulp-uglify": "^3.0.1",
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-github-emojis": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-reference": "^1.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-tag-dplayer": "^0.3.3",
    "hexo-tag-echarts3": "^1.1.2"
  },
  "devDependencies": {
    "gulp": "^4.0.0",
    "gulp-cache": "^1.1.0",
    "imagemin-pngquant": "^7.0.0"
  }
}

## For question

[The document of hexo](https://hexo.io/docs/tag-plugins) shows that the syntax , " {% post_link filename [optional text] %} ", can cite other pages in my blog. However, it doesn't work！

Description of the tag plugin:
---
You can ignore permalink and folder information, like languages and dates, when using this tag.

For instance: {% post_link how-to-bake-a-cake %}.

This will work as long as the filename of the post is how-to-bake-a-cake.md, even if the post is located at source/posts/2015-02-my-family-holiday and has permalink 2018/en/how-to-bake-a-cake.

You can customize the text to display, instead of displaying the post’s title. Using post_path inside Markdown syntax []() is not supported.

For instance:

Display title of the post.

{% post_link 2018-10-19-hexo-3-8-released %}

Display custom text.

{% post_link 2018-10-19-hexo-3-8-released 'Link to a post' %}

**Comment by tcrowe** [comment]
Hello @LourisXu did you find the solution?

What is the name of the file you are trying to use `post_link`? e.g. `./source/_posts/one.md`

What is the target file? e.g. `./source/_posts/two.md`

**Comment by LourisXu** [comment]
.source/xxx/one.md
.sourxe/yyy/two.md

**Comment by tcrowe** [comment]
@LourisXu Thank you. I think this tag is looking only in `./source/_posts`. Can you confirm?

**Comment by LourisXu** [comment]
Oh, yeah.
It does work!
Did I misunderstand the description of the tag plugin ? 
It doesn't seem to link files in the subdirectory of post！That will be wonderful if it can do so.

**Comment by tcrowe** [comment]
Maybe you can use the `asset` tag if you have post assets turned on.

https://hexo.io/docs/tag-plugins#Include-Assets

```
{% asset_path slug %}
{% asset_img slug [title] %}
{% asset_link slug [title] %}
```

**Comment by tcrowe** [comment]
(Oops, I meant to add more)

https://hexo.io/docs/configuration#Writing

`post_asset_folder` in the `./config.yml`

---

Then, if you have a need for a tag outside of the posts, like in `./source/products/one.md` maybe you can make a tag there?

Custom scripts go into `./scripts`

```
mkdir scripts
touch scripts/page-link-tag.js
```

Use this for an example: https://github.com/hexojs/hexo/blob/master/lib/plugins/tag/post_link.js

The API will be different: https://hexo.io/api/tag

Instead of `Post` replace with `Page`. Maybe your script will look similar to this:

```js
hexo.extend.tag.register("page_link", function(args, content){
  return "tag output"; // ??
});
```

---

If you try any of the ideas will you let me know?

**Comment by gautamz07** [comment]
@tcrowe  just curious whats the point of having posts in products folder when hexo will only showcase the posts from the `./source/_post` folder ?

**Comment by tcrowe** [comment]
I don't know, @gautamz07, but maybe an experiment.  🤷‍♂
