### ISSUE TITLE
Can I use "hexo-blog-client" as my software name?

### ISSUE THREAD

**Issue by Xonlystar** [hexojs/hexo#3554]
I developed a software to manage hexo blog using electronic, but there was a problem with the release, Can I use this name `hexo-blog-client`?
![深度截图_选择区域_20190521001412](https://user-images.githubusercontent.com/19361551/58036356-7ebcfb00-7b5d-11e9-958e-b9403d710e83.png)

**Comment by tcrowe** [comment]
Hi @Xonlystar I'm adding some information about this:

https://github.com/Xonlystar/hexo-blog-client

https://blog.onlystar.site/2018/10/21/hexoblogclient-shi-yong-zhi-nan/

**Comment by Xonlystar** [comment]
Can you provide a screenshot of the name that I can use?, because they need this!
![image](https://user-images.githubusercontent.com/19361551/58220165-622ce880-7d40-11e9-8e78-e091e10d7686.png)

This is my issue of releasing app: [feat: add 'hexo-blog-client' app #1067](https://github.com/electron/apps/pull/1067)
