### ISSUE TITLE
Use toc() to link undefined

### ISSUE THREAD

**Issue by wanghaijuan** [hexojs/hexo#3557]
## Environment Info
Node: 8.11.3
Hexo:  3.8.0
Hexo-toc: 1.0.8

## For BUG
Error calling method（ ```<%- toc(page.content, { "class": "toc-nav" }) %> ``` ）link address. Now its structure has become like this:

```
<ol class="toc-nav">
    <li class="toc-nav-item toc-nav-level-3">
         <a class="toc-nav-link" href="#undefined">
            <span class="toc-nav-number">1.</span> 
            <span class="toc-nav-text">HTML片段展示</span>
         </a>
    </li>
 </ol>
```

**Comment by tcrowe** [comment]
For reference this is the part which creates the `href`:
https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/toc.js#L57

This produces the `id`:
https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/toc.js#L33

**Comment by YoshinoriN** [comment]
I will try to update [the example](https://hexo.io/docs/helpers#toc).

**Comment by gautamz07** [comment]
@YoshinoriN , do you guys close issues on here or does the bot detect and close issue..

**Comment by YoshinoriN** [comment]
@gautamz07 
Thank you for following :)

I think it's better to wait for @wanghaijuan replay.
On the other hand, it's better to update the example.

**Comment by wanghaijuan** [comment]
I don't know why this bug happened，and I pulled the new one again.

**Comment by tcrowe** [comment]
@wanghaijuan  Why did you close it?

---

Also related is this recent PR which changed the `toc` https://github.com/hexojs/hexo/pull/3404
