### ISSUE TITLE
node_modules cannot be found in /hexo-cli 使用hexo命令时弹出chalk不能在hexo-cli/lib/modules下找到

### ISSUE THREAD

**Issue by Bertrachtung** [hexojs/hexo#3559]
## Environment Info

Node version:v12.3.1

Hexo and Plugin version: hexo-cli 1.1.0

## For BUG

On latest MacOs and running in the native terminal. After following all the steps in the documents and when I wanna to use the $hexo command, it returns that a module called 'chalk' can't be found. So I just install it manually by $npm. However, another module seems to be lost too. So I tried to reinstall hexo-cli again but it didn't work. 

Luckily, when I brew the hexo files, I found a folder called 'Hexo' in my usr/local/lib/node_modules, just next to the 'Hexo-cli', and there are a lot of files in the /hexo/node_modules, so I just copied all of them and paste them in the node_modules folder under hexo-cli, and it works. 

## For question

I'm quite confused about this problem though it seems have been issued and I'm afraid of some other mistakes might happen after I using this method...

**Comment by gautamz07** [comment]
@Bertrachtung how did you install hexo ? from start to finish .. can you describe the installation process ?

**Comment by Bertrachtung** [comment]
> @Bertrachtung how did you install hexo ? from start to finish .. can you describe the installation process ?

By using the normal command of "npm install -g hexo-cli"

**Comment by Bertrachtung** [comment]
@gautamz07 By using the command line "$npm install -g hexo-cli" on my terminal tool. NO ERROR was displayed and some warnings that seem to be irrelative.

**Comment by gautamz07** [comment]
@YoshinoriN is't the `npm install` command missing from [HERE](https://github.com/hexojs/hexo#quick-start)  ?

@Bertrachtung can you try the below steps after the: `npm install -g hexo-cli`.

`$ hexo init <folder>`
`$ cd <folder>`
`$ npm install`

After `npm install` is complete run :

`$ hexo serve`
