### ISSUE TITLE
提一个问题：如何完美地转载别人的文章

### ISSUE THREAD

**Issue by weidongzhou1994** [hexojs/hexo#3561]
hexo博客貌似没有直接转载的选项，看到一篇好文章，如何完美的转载到自己的博客里面呢？

**Comment by stevenjoezhang** [comment]
向原作者获得许可。

**Comment by YoshinoriN** [comment]
I don't know for sure about this issue. But seems not related Hexo. Please re-open this issue if you have more question.

@stevenjoezhang 
Thanks as well !!
