### ISSUE TITLE
代码块+图片块解析错误！

### ISSUE THREAD

**Issue by siaimes** [hexojs/hexo#3564]
[https://github.com/theme-next/hexo-theme-next/issues/857](https://github.com/theme-next/hexo-theme-next/issues/857)

**Comment by weyusi** [comment]
```
![2](3.jpg)
```
`[2]` is rendered as `<span class="caption">2</span>`, which might be intended.

Alternatively, you can use `{% img '3.jpg' '2' %}`.

For embedding code, are you trying to make it appear like this (display backticks),

\`\`\`
1
\`\`\`

Or (code highlighting),

```
1
```

**Comment by weyusi** [comment]
if you're using hexo-theme-next, can you remove the following lines,
https://github.com/theme-next/hexo-theme-next/blob/c106425c7794bd137d89d64c2a7e5365505727c2/source/js/utils.js#L32-L34

Some themes have following lines in their gallery.js:
```js

if (alt){
  $(this).after('<span class="caption">' + alt + '</span>');
}
```

**Comment by siaimes** [comment]
> ```
> ![2](3.jpg)
> ```
> 
> `[2]` is rendered as `<span class="caption">2</span>`, which might be intended. (Edt: I searched around, the caption is added by theme's javascript, not hexo nor hexo-renderer-marked.)
> 
> Alternatively, you can use `{% img '3.jpg' '2' %}`.
> 
> For embedding code, are you trying to make it appear like this (display backticks),
> 
> ```
> 1
> ```
> 
> Or (code highlighting),
> 
> ```
> 1
> ```

我的理解是是，这个[2]是在图片无法加载的时候才会代替图片显示出来的，而不是和图片一起显示。所以不太理解你说的有意这样做呢？

**Comment by weyusi** [comment]
yes, that [2] is not supposed to be displayed as a caption. But most theme with fancybox function add caption to all `<img>`, that's why [2] is displayed alongside with the image.

Meaning, theme adds the caption ([2] in this case), not hexo.

What is the current theme you're using (give me the link)? I show you how to remove the caption.

**Comment by siaimes** [comment]
> yes, that [2] is not supposed to be displayed as a caption. But most theme with fancybox function add caption to all `<img>`, that's why [2] is displayed alongside with the image.
> 
> Meaning, theme adds the caption ([2] in this case), not hexo.
> 
> What is the current theme you're using (give me the link)? I show you how to remove the caption.

I think this problem is not caused by the theme, I have downloaded the new hexo, and tested it, this phenomenon will also exist. Note that not all images will be like this, but only when the code block is placed above the image.

**Comment by weyusi** [comment]
I tried (backtick is displayed as single quote here),
```
'''
code block
'''
![another thing](https://postimgs.org/img/logo.png)
'''
another code block
'''
```

and I got
![caption](https://user-images.githubusercontent.com/43627182/61203932-f5741000-a72a-11e9-9b10-690e89b3e4c5.png)

I commented out the following lines from theme,
```js
if (alt){
  $(this).after('<span class="caption">' + alt + '</span>');
}
```

**Comment by siaimes** [comment]
> I tried (backtick is displayed as single quote here),
> 
> ```
> '''
> code block
> '''
> ![another thing](https://postimgs.org/img/logo.png)
> '''
> another code block
> '''
> ```
> 
> and I got
> ![caption](https://user-images.githubusercontent.com/43627182/61203932-f5741000-a72a-11e9-9b10-690e89b3e4c5.png)
> 
> I commented out the following lines from theme,
> 
> ```js
> if (alt){
>   $(this).after('<span class="caption">' + alt + '</span>');
> }
> ```

Will there be a prompt when the image cannot be loaded after commented out this?

**Comment by weyusi** [comment]
Continuation of https://github.com/theme-next/hexo-theme-next/issues/857#issuecomment-511884981
> The bug is caused by `hexo-renderer-pandoc` and has nothing to do with theme NexT.
> Try:
> 
> ```
> npm uninstall hexo-renderer-pandoc --save
> npm install hexo-renderer-marked --save
> ```

@siaimes 
Is your blog depends on hexo-renderer-pandoc additional features (other than markdown)? 

Sorry, I missed your [upload](https://github.com/siaimes/test). You can set the repo to private and grant read-only access to me.

**Comment by YoshinoriN** [comment]
https://github.com/wzpan/hexo-renderer-pandoc/issues/34

**Comment by siaimes** [comment]
Ok, I know what to do. Thank you guys for answering my questions, thank you very much.
