### ISSUE TITLE
Reference error in helper

### ISSUE THREAD

**Issue by LunaticMuch** [hexojs/hexo#3565]
Hi,

I am trying to extend my hexo theme with an helper to generate a menu/submenu based on a a JSON file. For the test I just included JSON as a var into the help.
When I make any command, even `hexo clean` I get the following error

`ReferenceError: $ is not defined
    at /......../theme/scripts/navbar.ejs:27:3
`

I cannot figure out how to solve the problem. The line failing is calling 
`var menu=$('#menu');' at the end of the helper:

```javascript
	var Data={
		"menu": 
		   [
			  {"name": "Home", "link": "0", "sub": null},
			  {"name": "England", "link": "1", "sub": 
				 [
					{"name": "Arsenal","link": "0-0", "sub": null},
					{"name": "Liverpool","link": "0-1", "sub": null},
					{"name": "Manchester United","link": "0-2", "sub": null}
				 ]
			  },
			  {"name": "Spain", "link": "2", "sub": 
				 [
					{"name": "Barcelona","link": "2-0", "sub": null},
					{"name": "Real Madrid","link": "2-1", "sub": null}
				 ]
			   },        
			   {"name": "Germany", "link": "3","sub": 
				 [
					{"name": "Bayern Munich","link": "3-1", "sub": null},
					{"name": "Borrusia Dortmund","link": "3-2", "sub": null}
				 ]
			   }
		   ]
	 }

	 $(function () {     
		function parseMenu(ul, menu) {
		for (var i=0;i<menu.length;i++) {
			var li=$(ul).append('<li><a href="'+menu[i].link+'">'+menu[i].name+'</a></li>');
			if (menu[i].sub!=null) {
				var subul=$('<ul id="submenu'+menu[i].link+'"></ul>');
				$(li).append(subul);
				parseMenu($(subul), menu[i].sub);
			}
		}
	}
	
	var menu=$('#menu');
	parseMenu(menu, JSON.menu);
	 });

	hexo.extend.helper.register("navbar", parseMenu(menu,Data.menu) );
```

Any idea how to solve it? Thanks a lot

**Comment by tcrowe** [comment]
If you need to use something like a jQuery on the server side you can try [cheerio](https://github.com/cheeriojs/cheerio).

The `./scripts/*` run on the server so it needs to be valid nodejs code. 👍

**Comment by tcrowe** [comment]
What was the solution, @LunaticMuch ?

**Comment by LunaticMuch** [comment]
Yes, I solved it. Just put a double loop with an if in my template. Thanks!

**Comment by tcrowe** [comment]
Cool, thanks @LunaticMuch 👍
