### ISSUE TITLE
Every file will update modifed time when 'hexo generate' if  auto_category is true.

### ISSUE THREAD

**Issue by zzploveyou** [hexojs/hexo#3566]
node v8.10.0

 `_config.yml`:

```
auto_category:
  enable: true
  depth: 2
```

'hexo generate' will update modified time of every file even when content has not changed.

**Comment by zzploveyou** [comment]
package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo-auto-category": "^0.1.6",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}
```

**Comment by YoshinoriN** [comment]
@zzploveyou 
Hi. `hexo-auto-category` is not an official plugin. Would you please ask plugin owner?

**Comment by wylu** [comment]
Same problem here. When using `Travis CI` clone the source code to generate and deploy, the time of all files will be changed which can using command stat to see. So, it seems if not set the "updated" in front-matter, Hexo will use the last modification time of the file as default, which is not really the last modification time.

**Comment by tomap** [comment]
Here is the link => https://github.com/xu-song/hexo-auto-category/issues
However, hexo uses the last update date of the file if not "last update" is set in front-matter
I feel it is not the right behavior, but you can modify the plugin to rely on creation date

**Comment by tcrowe** [comment]
It gives a warning that each file is changed: https://github.com/xu-song/hexo-auto-category#warning

@zzploveyou @wylu Can you confirm if that was the cause?
