### ISSUE TITLE
关于字符转义

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#3568]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

Your package.json `package.json`: 

## For feature request

遇到问题 例如这个 表格的时候
![image](https://user-images.githubusercontent.com/16351105/58748438-7cd33000-84ab-11e9-884c-7de496c23058.png)

因为[p|u:] 中 '|' 会被识别成表格符号，所以使用了转义字符 \|
但是hexo渲染到博客去 还是会识别成表格符号
![image](https://user-images.githubusercontent.com/16351105/58748450-bc9a1780-84ab-11e9-99e9-d20e30da8637.png)

请问该如何解决

**Comment by stevenjoezhang** [comment]
见 https://github.com/hexojs/hexo-renderer-marked/issues/138
marked 的问题，Hexo 无法解决
