### ISSUE TITLE
Cannot display XML Close Tag in Code Block

### ISSUE THREAD

**Issue by Febers** [hexojs/hexo#3574]
## Environment Info

Node version

v10.15.3

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

+-- ajv@5.0.0
+-- eslint@5.16.0
+-- hexo@3.8.0
+-- hexo-asset-image@0.0.3
+-- hexo-deployer-git@1.0.0
+-- hexo-deployer-heroku@0.1.2
+-- hexo-deployer-openshift@0.1.2
+-- hexo-deployer-rsync@0.1.3
+-- hexo-filter-flowchart@1.0.4
+-- hexo-filter-github-emojis@2.0.1
+-- hexo-filter-sequence@1.0.3
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-json-content@3.0.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-inject@1.0.0
+-- hexo-math@3.0.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
+-- hexo-search@1.0.4
+-- hexo-server@0.3.3
`-- hexo-symbols-count-time@0.6.0

Your package.json `package.json`: 
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "ajv": "^5.0.0",
    "hexo": "^3.8.0",
    "hexo-asset-image": "0.0.3",
    "hexo-deployer-git": "^1.0.0",
    "hexo-deployer-heroku": "^0.1.2",
    "hexo-deployer-openshift": "^0.1.2",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-filter-flowchart": "^1.0.4",
    "hexo-filter-github-emojis": "^2.0.1",
    "hexo-filter-sequence": "^1.0.3",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.2.11",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-search": "^1.0.4",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.6.0"
  },
  "devDependencies": {
    "eslint": "^5.16.0"
  }
}

## For BUG

1.  无法显示代码块中的 XML 关闭标签

    Cannot display XML Close Tag in Code Block

2. 文章：[链接](https://febers.github.io/Spring-学习笔记（一）：基本理念和-Bean-装配/) 。可以看到 XML 代码`<beans></beans>`显示成`<beans>beans>`，其中的"< /"没有显示

    The article: [Link](https://febers.github.io/Spring-学习笔记（一）：基本理念和-Bean-装配/) . You can see that `<beans></beans>` is displayed as `<beans>beans>`，`< /` is not shown.

My hexo blog  repo: https://github.com/Febers/febers.github.io

**Comment by YoshinoriN** [comment]
@Febers 
Hi. I can't reproduce it. My test environment is...

* theme: landscape
* hexo-renderer-marked: 0.3.2

![issue](https://user-images.githubusercontent.com/11273093/59083867-f8adfc00-8933-11e9-86c5-6a4779f3bf74.png)

I think may be caused by `hexo-renderer-marked`. Your `hexo-renderer-marked` is old.
Would you please try to update your `hexo-renderer-marked` to `0.3.x` or `1.0.x`?

**Comment by tomap** [comment]
I also tried to reproduce => no issue on my test:
https://hexo-theme-minidyne-demo.netlify.com/2002/02/02/old-post-2/
source
https://github.com/tomap/hexo-theme-minidyne-demo/blob/master/source/_posts/old-post-2.md

Same suggestion. Please update hexo-renderer-marked

**Comment by Febers** [comment]
> @Febers
> Hi. I can't reproduce it. My test environment is...
> 
> * theme: landscape
> * hexo-renderer-marked: 0.3.2
> 
> ![issue](https://user-images.githubusercontent.com/11273093/59083867-f8adfc00-8933-11e9-86c5-6a4779f3bf74.png)
> 
> I think may be caused by `hexo-renderer-marked`. Your `hexo-renderer-marked` is old.
> Would you please try to update your `hexo-renderer-marked` to `0.3.x` or `1.0.x`?

## update by command
I used the command `npm update hexo-renderer-marked --save` to update it, but i seems to useless.  In package.json, it also 
```
  "dependencies": {
    ......
    "hexo-renderer-marked": "^0.2.11",
    ......
  },
```
and the `node_modules\hexo-renderer-marked\package.json` also is
```
{
  "_from": "hexo-renderer-marked@^0.2.11",
  "_id": "hexo-renderer-marked@0.2.11",
  "_inBundle": false,
  "_integrity": "sha1-Mv04gNPDl5/XuAFewSGmxE/0n4Q=",
  "_location": "/hexo-renderer-marked",
  "_phantomChildren": {
    "get-stdin": "4.0.1"
  },
``` 
I deploy hexo and issue exists.

## update manually 
So I download the least release(1.0.1) and replace the old file dir. And I change hexo `package.json` manually: 
```
  "dependencies": {
    ......
    "hexo-renderer-marked": "1.0.1",
    ......
  },
```
But after I deploy hexo, the issue still exists.

**Comment by Febers** [comment]
> I also tried to reproduce => no issue on my test:
> https://hexo-theme-minidyne-demo.netlify.com/2002/02/02/old-post-2/
> source
> https://github.com/tomap/hexo-theme-minidyne-demo/blob/master/source/_posts/old-post-2.md
> 
> Same suggestion. Please update hexo-renderer-marked

After I updated the hexo-renderer-marked, the issue exits.  x (

**Comment by tomap** [comment]
Once you have done the update manually. Run "npm install" and redeploy

**Comment by Febers** [comment]
> Once you have done the update manually. Run "npm install" and redeploy

It seems to useless, now when i input ``
```
$ npm ls --depth 0
hexo-site@0.0.0 D:\Work\GitBlog\febers.github.io
+-- ajv@5.0.0
+-- eslint@5.16.0
+-- hexo@3.8.0
+-- hexo-asset-image@0.0.3
+-- hexo-deployer-git@1.0.0
+-- hexo-deployer-heroku@0.1.2
+-- hexo-deployer-openshift@0.1.2
+-- hexo-deployer-rsync@0.1.3
+-- hexo-filter-flowchart@1.0.4
+-- hexo-filter-github-emojis@2.0.1
+-- hexo-filter-sequence@1.0.3
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-json-content@3.0.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-inject@1.0.0
+-- hexo-math@3.0.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@1.0.1
+-- hexo-renderer-stylus@0.3.3
+-- hexo-search@1.0.4
+-- hexo-server@0.3.3
`-- hexo-symbols-count-time@0.6.0

npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0
```

**Comment by tcrowe** [comment]
A tool I use all the time is `npm-check-updates` to upgrade all the modules:

```sh
npm install -g npm-check-updates
cd my-hexo-blog-dir
ncu -an
npm install
```

**Comment by tomap** [comment]
It seems you are having trouble updating an npm dependency.
This is not an hexo issue :)
Please google "how to update an npm dependency?"
You'll probably find better answer than what we can tell you
