### ISSUE TITLE
请问hexo有分门别类管理功能吗？

### ISSUE THREAD

**Issue by Splendid-sun** [hexojs/hexo#3577]
用hexo框架写了自己的博客，到现在博文越来越多了，感觉杂乱，不知道hexo有没有能够把不同类别的博文分门别类的功能，就如同操作系统的文件夹管理一样。使几百篇博文显得有序，比如整理一个汇总页面，然后点进去又是分支页面。

**Comment by vipzrx** [comment]
用标签方式,给每个文章一个或者多个标签.参考微信好友管理方式

**Comment by stevenjoezhang** [comment]
标签、分类功能都有

**Comment by YoshinoriN** [comment]
@vipzrx @stevenjoezhang 
Thank you for your support :)

@Splendid-sun
Please re-open this issue if you have more question.

Thanks.
