### ISSUE TITLE
Document issue: kill all your adjectives

### ISSUE THREAD

**Issue by tamtm** [hexojs/hexo#3578]
Eg: in readme.md
"Features: - Blazing fast generating"
Really? Find me a slow one

Mark Twain once said: "When you catch an adjective, kill it"
Unnecessary adjectives lead to confusion.
And if you guys think they are funny? No, they are annoying

**Comment by tomap** [comment]
Please, open a nice (but not blazing) PR, I'm eager to review it.

**Comment by tcrowe** [comment]
Contributions from @tamtm 

+ (1) Issue https://github.com/hexojs/hexo/issues/created_by/tamtm
+ (0) PRs https://github.com/hexojs/hexo/pulls?utf8=✓&q=author%3Atamtm+
+ (1) All other issues through Hexo org https://github.com/search?q=org%3Ahexojs+author%3Atamtm&type=Issues

I don't see any reason why we should consider this issue.
