### ISSUE TITLE
hexo的文章怎么删除？

### ISSUE THREAD

**Issue by foulchild** [hexojs/hexo#3579]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

Your package.json `package.json`:

**Comment by SukkaW** [comment]
Just delete the `.md` file in your `source/_posts` directories and that would be ok.

**Comment by foulchild** [comment]
> 只需删除目录中的`.md`文件即可`source/_posts`。
删除了无法完成hexo g和hexo d的操作
文章依然存在，QAQ

**Comment by SukkaW** [comment]
Try `hexo clean` and then `hexo s` or `hexo g`?

**Comment by weyusi** [comment]
@foulchild 
does the issue still persists even after `hexo clean`?
