### ISSUE TITLE
hexo怎么删除文章？

### ISSUE THREAD

**Issue by foulchild** [hexojs/hexo#3580]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

Your package.json `package.json`:

**Comment by YoshinoriN** [comment]
Duplicate #3579
