### ISSUE TITLE
Latest LINUX: Broken Install

### ISSUE THREAD

**Issue by cherusk** [hexojs/hexo#3582]
## Environment Info

Node version(`node -v`: **10-13!**):

## For BUG

 1. BUG description
Always running into [No-command-is-execute](https://hexo.io/docs/troubleshooting#No-command-is-executed) on latest LINUX(Fedora/Ubuntu).

 2. The way to reproduce

Following the official setup instructions on hexo.io

## For question
 Are you following systematic testing on these platforms at all?

**Comment by tcrowe** [comment]
`Are you following systematic testing on these platforms at all?` -- Yes, sir!

Hexo tags the `./package.json` with the hexo version. It must be the same version running as the one installed too, I believe.

```
npm rm hexo hexo-cli -g
npm install hexo-cli@latest npm-check-updates -g

# in hexo project directory
rm -rf node_modules db.json debug.log
ncu -an
npm install
hexo serve --debug
```

If you must run as root please use the npm config `unsafe-perm` https://docs.npmjs.com/misc/config#unsafe-perm

`npm config set -g unsafe-perm true`

Can you let me know if any of this helps @cherusk ? 👋
