### ISSUE TITLE
Gravatat Helper related

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#3584]
## For question

From pull #1561 Hexo gravatar helper start to using `https` instead of `http://`.

Using HTTPS is definitely much safer, but it is certain that there are still some blog using HTTP. In this case using '//' might be more suitable.

Besides that, the documents related to [gravatar helper](https://hexo.io/docs/helpers#gravatar) is outdated (and still showing `http://www.gravatar.com`).

I can open new pr if hexo team thinks it is necessary.

**Comment by tcrowe** [comment]
Hello @SukkaW 👋 

Do you know how this is usually used?

Like so? `<img src="<%- gravatar("someone@nowhere.dev") %>">`

If it is used like that we do not actually need to specify the protocol. `https://` can become just `//`.

---

For reference:

https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/gravatar.js#L15

**Comment by SukkaW** [comment]
From the docs and thecode I believe `<img src="<%- gravatar("someone@nowhere.dev") %>">` is the use case.
The `//` is better not just because it is shorter, as for people who still stick to ****y HTTP, just a simple gravatar loading using HTTPS is not helpful to the safety and security. The `//` would cause issue only if page is under `file://`.

And whatever, at least the document of gravatar helper need updated. I have already fork the site repo and ready for the PR.
