### ISSUE TITLE
cannot use "Windows" of tags??

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#3586]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

Your package.json `package.json`: 

## For feature request

cannot use "Windows" of tags??

文章有Windows標簽
但是打開  xxxxxx.com/tags/Windows/ 卻是404頁面

我的blog是 jerryc.me
https://jerryc.me/tags/Windows/  404畫面

hexo clean 了好多次 依舊這樣

**Comment by tcrowe** [comment]
I think categories and tags get changed to lower case for the URL: https://jerryc.me/tags/windows/

<img width="309" alt="Screen Shot 2019-06-18 at 10 49 57 AM" src="https://user-images.githubusercontent.com/1634015/59703317-df6c4180-91b6-11e9-840a-419c21e0a7ca.png">

For this maybe you can change this:

```yml
categories:
- Windows
```

To this 👇 

```yml
categories:
- windows
```

---

This part is not easy to change but you can try if you need to.

https://github.com/jerryc127/hexo-theme-butterfly/blob/79971d49dbded45d306eedd0d2d8ce40b5582838/layout/includes/aside.pug#L98

https://hexo.io/docs/helpers#tagcloud

https://github.com/hexojs/hexo/blob/447246e009630e359a4bad9ae6b6dcb922668c42/lib/plugins/helper/tagcloud.js#L160

---

Does that help @jerryc127 ? It's a nice looking theme! 👌🏻

**Comment by jerryc127** [comment]
it bugs of hexo ?
i found that the when i hexo s,
it works, can show the tags/Windows/ page
but when i hexo d 
it appear the bugs

**Comment by tcrowe** [comment]
`it bugs of hexo ?` -- I don't know.

https://jerryc.me/tags/windows/ ⬅️ See it is converted to lower case?

Is it possible to replace all categories with lower case?

**Comment by tcrowe** [comment]
Sorry, I mean tags!
