### ISSUE TITLE
using note in hexo and rtl support

### ISSUE THREAD

**Issue by ghost1372** [hexojs/hexo#3587]
hi Does hexo support right to left?
and how can i use something like this in hexo?
![Untitled](https://user-images.githubusercontent.com/9213496/59631449-17df3180-915d-11e9-9f74-aa900ef1a157.png)

**Comment by tcrowe** [comment]
Hay @ghost1372 👋 I think there are a few options for you:

For example if you use the default theme you can open the layout file and change the top html tag. `themes/landscape/layout/_partial/head.ejs` 

From this: `<html>`

To this: `<html dir="rtl">`

Here's how it works: https://www.w3schools.com/tags/att_global_dir.asp

---

Atlernatively you can use the CSS to style it right-to-left (RTL):

```css
p.rtl {
  direction: rtl;
}
```

https://www.w3schools.com/cssref/pr_text_direction.asp

---

It's not specific to Hexo. It will work in any web page. Can you try and let me know if it worked, @ghost1372 ?

**Comment by ghost1372** [comment]
@tcrowe  tnx it worked.

**Comment by tcrowe** [comment]
You're welcome! Our chat is slow but you can also talk to us there: https://gitter.im/hexojs/hexo
