### ISSUE TITLE
how to write the categories? (no use list_categories)

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#3588]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

Your package.json `package.json`: 

## For feature request

how to write the categories? (no use list_categories)

i want to achieve the same effect like list_categories()

i try to do it (pug)

```pug
 ul.aside_category_item
        - site.categories.sort('name').each(function(category){
          if (!category.parent)
            li.aside_category_list
              a.aside_category_list_link(href='/' + `${category.path}`)
                span.aside_category_list_name= category.name
                span.aside_category_list_length= category.length
              
                if (category.child)
                  site.categories.sort('name').each(function(item){
                    if item.parent 
                      if (item.name == category.name)
                        ul.aside_category_item
                          li.aside_category_list
                            a.aside_category_list_link(href='/' + `${item.path}`)
                              span.aside_category_list_name= item.name
                              span.aside_category_list_length= item.length
                    })
                
           
        - })
```

it does not work.
how to change?

**Comment by tcrowe** [comment]
Hello again @jerryc127 👋 

First let me show you with EJS which I use most often. Later we can make it into pug lang.

```ejs
<%
function displayCategories(parent = undefined) {
  site.categories
    .find({ parent })
    .sort("name")
    .each(function(category) {
      // count the child categories
      const childCount = site.categories.find({ parent: category._id }).count()
      %>
      <li>
        <a href="<%=url_for(category.path)%>"><%=category.name%></a>
        
        <% if (childCount > 0) { %>
          <ul>
            <% displayCategories(category._id) %>
          </ul>
        <% } %>
      </li>
      <%
    });
}
%>

<h3>Hierarchical category display</h3>

<ul>
  <% displayCategories() %>
</ul>
```

---

For pug you need `mixin` https://pugjs.org/language/mixins.html

**Comment by tcrowe** [comment]
Result:

<img width="281" alt="Screen Shot 2019-06-20 at 12 10 57 PM" src="https://user-images.githubusercontent.com/1634015/59871303-7a4e5280-9354-11e9-9dcc-ab84244a709f.png">

**Comment by jerryc127** [comment]
> Result:
> 
> <img alt="Screen Shot 2019-06-20 at 12 10 57 PM" width="281" src="https://user-images.githubusercontent.com/1634015/59871303-7a4e5280-9354-11e9-9dcc-ab84244a709f.png">

thx , it work
and do you know how to write archives? (no use  list_archives() )?
hope can help me.

**Comment by tcrowe** [comment]
I'm not sure what `list_archives` does? Can you show what you are looking for please?

**Comment by jerryc127** [comment]
> ow what you are looking for please?

thx reply, the list_archives() show
![image](https://user-images.githubusercontent.com/16351105/59959585-30e53b00-94ed-11e9-9960-faedeb955304.png)

**Comment by jerryc127** [comment]
@VincentTV
