### ISSUE TITLE
Commands:   help     Get help on a command.  init     Create a new Hexo folder.  version  Display version information.

### ISSUE THREAD

**Issue by alanjustalan** [hexojs/hexo#3592]
想问下这是出现了什么问题？

PS D:\blog> hexo g
Usage: hexo <command>

Commands:
  help     Get help on a command.  init     Create a new Hexo folder.  version  Display version information.
Global Options:
  --config  Specify config file instead of using _config.yml  --cwd     Specify the CWD  --debug   Display all verbose messages in the terminal  --draft   Display draft posts  --safe    Disable all plugins and scripts  --silent  Hide output on console
For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
PS D:\blog> hexo s
Usage: hexo <command>

Commands:
  help     Get help on a command.  init     Create a new Hexo folder.  version  Display version information.
Global Options:
  --config  Specify config file instead of using _config.yml  --cwd     Specify the CWD  --debug   Display all verbose messages in the terminal  --draft   Display draft posts  --safe    Disable all plugins and scripts  --silent  Hide output on console
For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
PS D:\blog> hexo server
Usage: hexo <command>

Commands:
  help     Get help on a command.  init     Create a new Hexo folder.  version  Display version information.
Global Options:
  --config  Specify config file instead of using _config.yml  --cwd     Specify the CWD  --debug   Display all verbose messages in the terminal  --draft   Display draft posts  --safe    Disable all plugins and scripts  --silent  Hide output on console
For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

**Comment by stevenjoezhang** [comment]
看上去是依赖问题，需要重新安装
