### ISSUE TITLE
How to modify the rendering template?|请问如何修改渲染模板？

### ISSUE THREAD

**Issue by shanlanCoding** [hexojs/hexo#3594]
### Chinese
我打算给正文的img标签添加一个属性，完整的我想要的img标签如下：
`<img src="xxx.com/xx.jpg" alt="" referrerpolicy="no-referrer"></img>`
我所添加的属性为：` referrerpolicy="no-referrer"`

请问我该修改哪个文件，才能达到我需要的效果。

期待您的回复。

--------
### English
I intend to add an attribute to the IMG tag of the text. The complete img tag I want is as follows:
` <img src="xx xx.com/xx.jpg" alt=""referrer policy="no-referrer"> </img>`
The attributes I added are: `referrerpolicy='no-referrer'.`
I would like to ask which file I should modify to achieve the desired effect.

We look forward to your reply.

**Comment by kinggozhang** [comment]
Markdown render should control content of img tag. you can check that.
alternatively, 
you can try to use getElementsByTagName('img'), to get all img elements, and assign your attributes ...

**Comment by shanlanCoding** [comment]
“Markdown render should control content of img tag”
How do I operate this?
-------------
“getElementsByTagName('img')”，I see，Thank you.




------------------ 原始邮件 ------------------
发件人: "kinggozhang"<notifications@github.com>; 
发送时间: 2019年7月1日(星期一) 中午11:33
收件人: "hexojs/hexo"<hexo@noreply.github.com>; 
抄送: "两载"<291637732@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [hexojs/hexo] How to modify the rendering template?|请问如何修改渲染模板？ (#3594)




Markdown render should control content of img tag. you can check that.
 alternatively,
 you can try to use getElementsByTagName('img'), to get all img elements, and assign your attributes ...
