### ISSUE TITLE
如何在多台电脑上写博客

### ISSUE THREAD

**Issue by holysin** [hexojs/hexo#360]
博客刚开始部在家里的电脑上，现在我想在公司也能编写。开始以为只要clone一下github上的文件就可以，但发现不行。有人解决过这个问题吗

**Comment by whygonghui** [comment]
试试这个：http://ibartman.com/2015/01/27/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E5%A4%9A%E5%8F%B0%E7%94%B5%E8%84%91%E7%AE%A1%E7%90%86hexo-%E6%BA%90%E6%96%87%E4%BB%B6/

**Comment by leesei** [comment]
`hexo-deployer-git` 只會把生成的HTML 放到 git 上
你的源md 文件可以自行開branch 用git 管理, 可參考[theme-freemind](https://github.com/wzpan/hexo-theme-freemind/tree/source).

請關閉這issue
