### ISSUE TITLE
hexo server just cuts off in the middle of generating the page

### ISSUE THREAD

**Issue by AlvaroDeMenard** [hexojs/hexo#3605]
## Environment Info

Node version: v10.16.0

Hexo and Plugin version(`npm ls --depth 0`): 
hexo-site@0.0.0 C:\blog
+-- grunt@1.0.4
+-- hexo@3.8.0
+-- hexo-admin@2.3.0
+-- hexo-browsersync@0.3.0
+-- hexo-deployer-git@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-helper-qrcode@1.0.2
+-- hexo-reference@1.0.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-jade@0.4.1
+-- hexo-renderer-marked@1.0.1
+-- hexo-renderer-pug@0.0.5
+-- hexo-renderer-sass@0.4.0
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
`-- hexo-wordcount@6.0.1

## For BUG

See the diff here (hexo server on the left, hexo server --draft on the right), look at the bottom: https://www.diffchecker.com/6l7XSWKH

It just cuts off in the middle of the code for some reason. 

This only happens if the content of the page is long enough. If I remove some random bit of text, it works normally. Is there some sort of max-length variable that limits the size of generated pages in draft mode?

Edit: after adding some more text, it turns out that this happens with "hexo server", too. On the other hand "hexo generate" works perfectly fine.

Edit 2: 8 hours later, with no change, it now works as it should. Bizarre. Something clock-related?

**Comment by YoshinoriN** [comment]
Not sure bat this issue is similar to https://github.com/hexojs/hexo-browsersync/issues/15
