### ISSUE TITLE
Update hexo-front-matter

### ISSUE THREAD

**Issue by Ryuno-Ki** [hexojs/hexo#3611]
In order to fix a security vulnerability in the transitive dependency js-yaml, https://github.com/hexojs/hexo-front-matter/issues/17 needs to be fixed first and then updated here.
Afterwards publish a new version on npm please.

https://www.npmjs.com/package/hexo shows v3.9.0 which is still vulnerable to https://npmjs.com/advisories/788 according to `npm audit`.

**Comment by weyusi** [comment]
Can this be closed in favor of https://github.com/hexojs/hexo-front-matter/issues/17 ?

**Comment by Ryuno-Ki** [comment]
No.
Because you have a dependency here, which needs to be updated after the release of the frontmatter.

**Comment by Ryuno-Ki** [comment]
Since I don't use this any more, I wouldn't mind if it were closed. However, 4.0.0 seems to be around the corner …

**Comment by YoshinoriN** [comment]
@Ryuno-Ki 
Thanks :) 

I understand and I close this issue.
Best wishes to your new website 😄
