### ISSUE TITLE
订阅功能与站点地图功能出现xml源码？

### ISSUE THREAD

**Issue by ShanYi-Hui** [hexojs/hexo#3616]
点击‘订阅’或者‘站点地图’，跳转到https://huishanyi.club/atom.xml 和 https://huishanyi.club/baidusitemap.xml

**Comment by stevenjoezhang** [comment]
这是预期行为。

**Comment by ShanYi-Hui** [comment]
> 这是预期行为。

那这个订阅功能如何使用？展示xml源码意义何在？

**Comment by stevenjoezhang** [comment]
有些浏览器或者rss客户端能读取这个xml，然后自动获取更新，博客发了新文章就可以第一时间知道。不过感觉以前很流行，现在用的比较少了。

**Comment by ShanYi-Hui** [comment]
> 有些浏览器或者rss客户端能读取这个xml，然后自动获取更新，博客发了新文章就可以第一时间知道。不过感觉以前很流行，现在用的比较少了。

了解了，谢谢啦！     ^_^
