### ISSUE TITLE
Why click on the article title link to jump to the browser's download page.

### ISSUE THREAD

**Issue by sun-wenming** [hexojs/hexo#3617]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):
v10.16.0

Your site `_config.yml` (Optional):
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://sun-wenming.github.io
root: /
permalink: :year/:month/:day/:category/:title
permalink_defaults:
```
Your theme `_config.yml` (Optional): 
`theme: next`

Hexo and Plugin version(`npm ls --depth 0`): 
```
+-- hexo@3.9.0
+-- hexo-deployer-git@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-qiniu-sync@1.4.7
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@1.0.1
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.3.3

```

## For BUG

Why click on the article title link to jump to the browser's download page.
Hexo address : https://sun-wenming.github.io/

Github address : https://github.com/sun-wenming/sun-wenming.github.io

## For question
Why click on the article title link to jump to the browser's download page.

I just used this, I don't know how to solve it, I need help.

**Comment by tcrowe** [comment]
Hey @sun-wenming 😸 

Test URL: https://sun-wenming.github.io/2019/07/08/Vue/vue/Gin-vue-js-HTML5-History-Mode

<img width="292" alt="Screen Shot 2019-07-08 at 12 02 06 PM" src="https://user-images.githubusercontent.com/1634015/60832021-2dea7b80-a178-11e9-889e-e25b8c90d8a0.png">

The server thinks this file is a `application/octet-stream` but it should be `text/html`.

https://github.com/sun-wenming/sun-wenming.github.io/tree/master/2019/07/08/Vue/vue

The file does not have the `.html` extension. Maybe a hexo plugin removes the extension.

---

+ ⚠️ Delete this API key quickly
+ Don't upload the source to github
+ Only use `hexo deploy` and not `git push`

**Comment by tcrowe** [comment]
Maybe delete repository and re-create it?

**Comment by tomap** [comment]
Also, droping this line 
https://github.com/sun-wenming/sun-wenming.github.io/blob/hexo/_config.yml#L24
will produce a .html file, which might solve your issue :)

**Comment by sun-wenming** [comment]
@tcrowe  Thanks for your suggestions.I will create a private repository to store the source code and replace the API key.
 
@tomap 
Thank you for your suggestion, I compared the _config.yaml of re-create project.
I found that permalinks need `/` to end. Like this：

```
permalink:  :year/:month/:day/:category/:title/
```

**Comment by tcrowe** [comment]
You're welcome @sun-wenming 🤗
