### ISSUE TITLE
feature request - redirect pages

### ISSUE THREAD

**Issue by siaimes** [hexojs/hexo#3619]
## Environment Info

Node version(`node -v`: **Should be at least nodejs 6.9. If not, please update before posting an issue!**):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

Your package.json `package.json`: 

## For feature request

I modified the blog schema and the old links are now inaccessible. I am trying to find a solution that redirects old links to new links, but hexo doesn't seem to implement this feature. I found Jekyll with this feature. Can you refer to this optimized hexo?
[jekyll/jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from)

**Comment by YoshinoriN** [comment]
@siaimes 
Please try to use [hexo-generator-alias](https://github.com/hexojs/hexo-generator-alias) :)

**Comment by siaimes** [comment]
> @siaimes
> Please try to use [hexo-generator-alias](https://github.com/hexojs/hexo-generator-alias) :)

It works, thank you guys.
