### ISSUE TITLE
deploy 之后文件已经上传到 github，但输入网址时一直显示404错误，请问问题可能出现在哪里？

### ISSUE THREAD

**Issue by zippera** [hexojs/hexo#362]

**Comment by GHdeng** [comment]
https://github.com/GHdeng/GHdeng.github.io 可以帮我看下吗?一直是404

**Comment by leesei** [comment]
http://ghdeng.github.io/2016/04/23/hello-world/ 能訪問
你被牆了?

**Comment by qazsweet** [comment]
我更新了代码和图标，在reporepositories中可以看到，但是打开 http://qazsweet.github.io/ 之后并没有更新显示的内容和图标。我把本地的删除，重新clone也不行。可以帮我看一下吗？

**Comment by huangashz** [comment]
一直404 ，可以帮我看看吗，感激涕零！！~~~ https://github.com/huangashz/huangashz.github.io/

**Comment by leesei** [comment]
huangashz.github.io 能訪, 你被牆了?

http://qazsweet.github.io/ 一堆403
```
http://madforjekyll.cu.cc/css/clean-blog.css Failed to load resource: the server responded with a status of 403 (Forbidden)
```

**Comment by airfight** [comment]
我的也是404 可以帮忙看下？https://airflight.github.io/

**Comment by airfight** [comment]
https://github.com/airfight/airflight.github.io

**Comment by ShinoharaYuri** [comment]
@airfight 

airfight
airflight.github.io
仔細看看

**Comment by yilongping** [comment]
怎么解决啊？我的也是404
重新做了几遍都是404

**Comment by leesei** [comment]
@airfight 你的repo 錯名了, airflight vs airfight

**Comment by Allen-kevin** [comment]
我的也是，等了好久，还是404
这是我在github上的地址https://github.com/Allen-kevin/Allen-kevin.github.io.git
这是我.yml中添加的repository:  http://github.com/Allen-kevin/Allen-kevin.github.io.git
                                branch: master

**Comment by Allen-kevin** [comment]
谁能帮忙看下https://Allen-kevin.github.io/

**Comment by ShinoharaYuri** [comment]
@Allen-kevin  This repository is empty.

**Comment by Allen-kevin** [comment]
@ShinoharaYuri 那我应该怎么做

**Comment by perixiaowan** [comment]
deploy:
    type: git
  
repo: git@github.com:perixiaowan/perixiaowan.github.io.git
  branch: master


你是这样添加的么？
在2016年09月24日 14:49，kevin 写道:

我的也是，等了好久，还是404
这是我在github上的地址https://github.com/Allen-kevin/Allen-kevin.github.io.git
这是我.yml中添加的repository: http://github.com/Allen-kevin/Allen-kevin.github.io.git
branch: master

**Comment by perixiaowan** [comment]
deploy之后有没有报错信息？




在2016年09月25日 07:42，kevin 写道:

@ShinoharaYuri 那我应该怎么做

**Comment by Allen-kevin** [comment]
@perixiaowan deploy之后是这样的
![image](https://cloud.githubusercontent.com/assets/22408418/18812031/24477c2c-82f9-11e6-9cb0-5533f639a4b1.png)

**Comment by perixiaowan** [comment]
一般deploy之后会有进度条。即使没有进度条，也会有提示信息。什么都没有说明可能没有连上github，你看你配置都正确吗？或者你截个图你的github上配置，再截个hexo下的目录，看看是否正常？




在2016年09月25日 08:22，kevin 写道:

@perixiaowan deploy之后是这样的

**Comment by Allen-kevin** [comment]
@perixiaowan 
这个是hexo下的目录
![image](https://cloud.githubusercontent.com/assets/22408418/18812184/27a2fe78-82fe-11e6-8a65-fce1dfb861ca.png)

**Comment by Allen-kevin** [comment]
@perixiaowan 
![image](https://cloud.githubusercontent.com/assets/22408418/18812195/8652d33a-82fe-11e6-8dee-6003dd7b7a62.png)
不知道为什么github pages 这里一直是None,不能选

**Comment by perixiaowan** [comment]
你用下面这个测试下，看ssh通不通，如果不通，需要你配置下你的sshssh -T git@github.com



在2016年09月25日 09:01，kevin 写道:

@perixiaowan

不知道为什么github pages 这里一直是None,不能选

**Comment by perixiaowan** [comment]
还有就是，你public目录下有内容吗？如果没有，你deploy之前需要generate下
在2016年09月25日 09:01，kevin 写道:

@perixiaowan

不知道为什么github pages 这里一直是None,不能选

**Comment by Allen-kevin** [comment]
@perixiaowan 
我的public 下有内容，我正在配置ssh，这里先过谢啦，回头可能还有问题，会需要向你多多请教

**Comment by ShinoharaYuri** [comment]
https://hexo.io/docs/deployment.html
https://help.github.com/articles/testing-your-ssh-connection/

重新查看一下 檢查每個地方有沒有問題

**Comment by perixiaowan** [comment]
好的，没问题。




在2016年09月25日 09:30，kevin 写道:

@perixiaowan
我的public 下有内容，我正在配置ssh，这里先过谢啦，回头可能还有问题，会需要向你多多请教

**Comment by Allen-kevin** [comment]
@perixiaowan 
为什么我运行第一天命令npm install -g hexo-cli就报错，加sudo也不行
![image](https://cloud.githubusercontent.com/assets/22408418/18813436/466956bc-832c-11e6-8a07-03bc75e01a15.png)

**Comment by Allen-kevin** [comment]
who can tell me ,what should i do?
![image](https://cloud.githubusercontent.com/assets/22408418/18813926/9e5a6922-833d-11e6-990a-1b91eb56653d.png)

**Comment by perixiaowan** [comment]
我看你报错的链接是不是写错了？hithub.com?还是github.com?

**Comment by Allen-kevin** [comment]
@perixiaowan 
哈哈，是的，后来我发现了，现在能用了，就是多折腾了一会，谢谢啦，有机会多交流

**Comment by itcuihao** [comment]
提交gh-pages后，页面没有更新，还是原来的。帮忙看下，麻烦啦~[http://itcuihao.github.io/](url)
