### ISSUE TITLE
资源文件夹生成的html无法正常引用

### ISSUE THREAD

**Issue by caoPhoenix** [hexojs/hexo#3621]
设置post_asset_folder: true之后，比如说:

`$hexo new "test"`

创建一个新博客，_posts文件夹会同时创建一个test文件夹，当我在test.md中用:

`![some text](text/picture.png)`

引用图片时，

`$hexo g`

生成的 index.html文件对这个图片的引用是

`<img src="test/problem.png" alt="some text">`

而实际上在public文件夹中，index.html和picture.png是在同一个目录下，导致无法正常引用。

**Comment by stevenjoezhang** [comment]
请使用 Asset image tag
```
{% asset_img [class names] slug [width] [height] [title text [alt text]] %}
```
