### ISSUE TITLE
Question: Is it possible to include external scripts in the deployment?

### ISSUE THREAD

**Issue by twatzl** [hexojs/hexo#3631]
So by default the generated hexo page loads some scripts from jsdelivr.net.
Is there a configuration option which allows me to include the scripts in the generated code and serve them from my own server instead?

**Comment by tcrowe** [comment]
Hey @twatzl :wave:

The scripts and styles are theme-specific and customizable within `./themes/your-theme-name/layout`.

Here's the list if you didn't see it yet:
https://hexo.io/themes/

It's possible to fork or create them how you want. =]

**Comment by tomap** [comment]
Hi, 
The scripts included by jsdelivr are probably included by your theme, not by hexo itself
You should find your theme's repository (Google it) and ask the question there.
Or simply change it yourself. Go to theme/<theme's name>/and find the references and convert them to local files

**Comment by twatzl** [comment]
Yeah I found the references later in the code when I was fixing something in the theme. It appears that my theme has an option for deploying them locally. 

Thanks for your quick help.
