### ISSUE TITLE
How to include css from node packages in the deployment? 

### ISSUE THREAD

**Issue by twatzl** [hexojs/hexo#3637]
Hello, 

so this is a followup to #3631. I now know that I have to reconfigure the theme to get rid of the CDNs, but how can I get hexo to serve css and js files from node_modules?

For example i ran `npm install --save bulma`. Now I have bulma in my node_modules directory, but is there a way to include the css file in the deployment other than to copy it manually to the source folder?

**Comment by YoshinoriN** [comment]
Hi @twatzl

You should some bundle(build tool) like the webpack. Following is example.

```
$ npm install webpack webpack-cli copy-webpack-plugin --save-dev
```

```js
//webpack.config.js
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  plugins: [
    new CopyPlugin([
      { from: './node_modules/hoge/bulma.min.js', to: 'yourDistinationDirectory' },
    ]),
  ],
};
```

```js
//package.json
  "scripts": {
    "build": "webpack --mode production && hexo generate",
  },
```

I have not tried the above example. but it will work well.

**Comment by twatzl** [comment]
Thank you. I have to fix some other stuff before, but then I will try it out.

**Comment by twatzl** [comment]
Sorry, but it does not really work.

1. webpack requires a config option called entry. I have no idea what to put there, so i just created an empty js file at ./src/index.js
2. webpack does not copy the files to /my/blog/public/css, but to /my/blog/dist/public/css

Do you know how to fix those 2 things?

**Comment by twatzl** [comment]
I have it working now with the following webpack.config.js and an empty ./src/index.js:

```
const CopyPlugin = require('copy-webpack-plugin');
const path = require('path');

module.exports = {
  plugins: [
    new CopyPlugin([
      { from: './node_modules/bulma/css/bulma.min.css', to: './public/css' },
    ]),
  ],
  output: {
    path: path.resolve(__dirname, './')
  }
};
```

is there a better way instead of the empty index.js file?

**Comment by YoshinoriN** [comment]
@twatzl 
If you using some css preprocessor like `scss`. You can specify it instead of `index.js`.
But, if no. I have no idea.
