### ISSUE TITLE
Hello, I have written a theme plug-in for hexo, how can I publish it on your official website?

### ISSUE THREAD

**Issue by JoeyBling** [hexojs/hexo#3641]
Hello, I have written a theme plug-in for hexo, how can I publish it on your official website?

**Comment by YoshinoriN** [comment]
@JoeyBling 

* Please read the [publish documente](https://hexo.io/docs/themes#Publishing)
* Create PR to [official site repo](https://github.com/hexojs/site)

Thanks :)

**Comment by JoeyBling** [comment]
> @JoeyBling
> 
> * Please read the [publish documente](https://hexo.io/docs/themes#Publishing)
> * Create PR to [official site repo](https://github.com/hexojs/site)
> 
> Thanks :)

Thank you!
