### ISSUE TITLE
Integrating Hexo blog with existing site

### ISSUE THREAD

**Issue by mcraveiro** [hexojs/hexo#3644]
Hi Hexo developers,

Thank you very much for a very useful tool. We are trying to integrate Hexo with an existing nodejs express application, and have a question regarding how this should be done. However, I'm afraid I am not particularly knowledgeable about JS, so we are probably doing something wrong.

We first followed #476, which said that the hexo files can be placed anywhere. Due to this we created two top-level projects in our git repo, as follows:

```
/blog -> result of an hexo init, contains its own modules, etc.
/public -> the public folder of our site
/views -> views of our site
/routes -> routes of our site
package.json -> our own packages, which do not include hexo.
...
```
We updated ```publicdir``` on our ```_config.yml``` to point to ```../public/blog``` and then created a link on our existing site that points to that directory.  Thus, when we run ```hexo generate``` in ```/blog```, it populates ```public/blog```. However, the problem we then have is that all of the hexo code assumes the resources to be available in the root whereas in our case they are available under ```/blog``` (e.g. ```public/blog```). Due to this it fails to find the CSS resources, etc.

We then looked into #3414, which suggests we should be doing some kind of mapping with the hexo routes [1], but as I do not understand enough of JS I haven't managed to figure out how to integrate this with our project.

At this point we are a bit stuck. Any pointers in the right direction would be greatly appreciated.

Many thanks.

Marco

[1] https://expressjs.com/en/guide/using-middleware.html

**Comment by mcraveiro** [comment]
Hi, we managed to find a solution for this in the end by using the configuration option ```root```:

```
root: /blog
```
All of the resources are found correctly. We have a minor problem in that the "home" link now takes us back to the blog instead of the main site, but that is not a big problem. Cheers

**Comment by dougmolineux** [comment]
@mcraveiro I'm having a similar problem, were you ever able to get the "home" link to point to the actual "home" of your website? I've tried various combinations of `url` and `root` but either nothing works at all (all dependencies fail to load) or the `home` link will not go back to the actual home page.

**Comment by mcraveiro** [comment]
Apologies @dougmolineux, I've moved on to using a simpler blogging framework based on Emacs and I don't remember much of what I was doing with Hexo sadly.

**Comment by dougmolineux** [comment]
@mcraveiro Not a problem at all, thank you very much for the response! Good luck to you

**Comment by CHYGO1985** [comment]
> @mcraveiro I'm having a similar problem, were you ever able to get the "home" link to point to the actual "home" of your website? I've tried various combinations of `url` and `root` but either nothing works at all (all dependencies fail to load) or the `home` link will not go back to the actual home page.

Not sure if you have resolve the issue, here is my solution,  hope it helps :)
