### ISSUE TITLE
ERROR Asset render failed: lib/font-awesome/bower.json

### ISSUE THREAD

**Issue by lonePatient** [hexojs/hexo#3651]
- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x]  Node.js is higher than 6.9

## Question

hexo g

error:

ERROR Asset render failed: lib/font-awesome/bower.json
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)

**Comment by tcrowe** [comment]
Hey @lonePatient 👋 

This might be a good way to use `skip_render` in the config.

As you might imagine it's a popular feature to stop a file from going through hexo's processing.

https://hexo.io/docs/configuration#Directory

```yml
skip_render:
  - "lib/**/*"
```

Maybe something like that ⤴️

I haven't used it but there's also `include` and `exclude` on the config page.
