### ISSUE TITLE
closed tag problem of generated HTML

### ISSUE THREAD

**Issue by JoeyBling** [hexojs/hexo#3652]
When I execute **`hexo s-g` or `hexo g`**
The generated HTML tag does not end properly,But it doesn't affect browser rendering
The version I used `3.9.0`
But I didn't have this problem with version `3.7.1`
![](https://user-images.githubusercontent.com/25240064/62505035-9424f580-b82d-11e9-843c-f83cdd779daa.png)
I use the theme [yilia-plus](https://github.com/JoeyBling/hexo-theme-yilia-plus)
I've tried this with the official default theme,But problems remain
How can i debug or fix it ?

**Comment by curbengh** [comment]
I noticed this issue before, though I couldn't reproduce it reliably

Can you attach your `package.json` and `_config.yml` (let me know if they're private)? It may be caused by plugins.

**Comment by JoeyBling** [comment]
@curbengh Thank you for your reply
I use the official default theme `landscape`，the  problem can also occur!
The other configurations were left untouched.
version `3.9.0`

**Comment by JoeyBling** [comment]
@curbengh At the beginning I also thought the theme plug-in problem, later I directly use the 'hexo init' command to initialize a new project will also appear this problem

**Comment by curbengh** [comment]
I can [reproduce](https://github.com/curbengh/hexo-testing/blob/gh-pages/index.html) the issue, but not in local testing after modify something. Annoyingly, I can't remember the changes I made.

I'll do more testing.

**Comment by JoeyBling** [comment]
@curbengh I've debugging, and find there's something wrong with this pull request
> https://github.com/hexojs/hexo/pull/3315
When I delete that file, the problem won't appear
- `lib/plugins/filter/meta_generator.js`
But I don't know if there will be any other problems later, so I would like to ask for your help. Thank you

**Comment by curbengh** [comment]
Somehow in my cause the issue goes away even with "meta_generator.js".
Can you try this modified [landscape theme](https://github.com/hexojs/hexo/files/3471292/landscape.zip)?

**Comment by JoeyBling** [comment]
@curbengh I don't think it's about the subject. I'll try first

**Comment by JoeyBling** [comment]
@curbengh Sorry, I take back what I said just now, this modified theme is actually ok，
But the question is what?
I don't know

**Comment by JoeyBling** [comment]
I use the theme [yilia-plus](https://github.com/JoeyBling/hexo-theme-yilia-plus)

**Comment by YoshinoriN** [comment]
@JoeyBling @curbengh 
My understanding this issue has already been solved https://github.com/hexojs/hexo-theme-landscape/pull/123

**Comment by JoeyBling** [comment]
@YoshinoriN Thank you very much. You solved my problem perfectly. I fixed my theme according to this bug

And I have another question, how to remove the meta tag `generator` property generated

```<meta name="generator" content="Hexo 3.9.0">```

**Comment by JoeyBling** [comment]
fix it
> [https://github.com/hexojs/hexo-theme-landscape/pull/123](https://github.com/hexojs/hexo-theme-landscape/pull/123)

**Comment by curbengh** [comment]
> And I have another question, how to remove the meta tag `generator` property generated

currently, there is no option to disable it. I could add the option.

**Comment by JoeyBling** [comment]
@curbengh I think your can add this and look forward to fix it in the next release
