### ISSUE TITLE
hexo 表格文字无法居中和右对齐

### ISSUE THREAD

**Issue by yelangpi** [hexojs/hexo#3657]
.md写了  :-:  -:  而且网页源代码也有  =center  =right ，但是网站上显示仍然左对齐，
网页：https://yelangpi.github.io/2019/08/09/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%80%BB%E7%BB%93/

**Comment by yelangpi** [comment]
版本3.9.0

**Comment by YoshinoriN** [comment]
Please check your marked settings.
Maybe you have to enable `gfm` option.

https://github.com/hexojs/hexo-renderer-marked#options

**Comment by yelangpi** [comment]
> Please check your marked settings.
> Maybe you have to enable `gfm` option.
> 
> https://github.com/hexojs/hexo-renderer-marked#options

thank you, installing hexo-renderer-markdown-it  do it
