### ISSUE TITLE
hexo只能识别_post当前目录下的md文件吗？如果我将md放置在_post/***/目录下就无法识别，怎么搞定？也就是hexo支持多级目录创建文章吗 ? 比如这样 :`hexo new post 2016/05/xx.md' 希望能在 _post/2016/05下生成 xx.md文章

### ISSUE THREAD

**Issue by 6westboy9** [hexojs/hexo#3666]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
是支持的呀

**Comment by 6westboy9** [comment]
> 是支持的呀
我怎么不行呢？是怎么创建的？可以看下你创建后的目录结构吗？
