### ISSUE TITLE
Replace cheerio with native API

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo#3677]
## Feature Request

From the [benchmark](https://github.com/hexojs/hexo/issues/3663) (performed by @SukkaW) we can see that [cheerio](https://github.com/cheeriojs/cheerio) can cause significant performance hit.

While cheerio is not necessary for the core functions of Hexo, it is currently utilized by several default plugins:

- [x] ~~[meta_generator.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/meta_generator.js)~~
- [x] ~~[external_link.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/after_post_render/external_link.js)~~
- [ ] [toc.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/toc.js)
- [x] ~~[open_graph](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/open_graph.js)~~

We are hoping to re-implement them without depending on cheerio, if possible.

Related PRs:
- meta_generator: ~~https://github.com/hexojs/hexo/pull/3669~~ ~~https://github.com/hexojs/hexo/pull/3671~~
- open_graph: ~~https://github.com/hexojs/hexo/pull/3670~~ ~~https://github.com/hexojs/hexo/pull/3679~~ ~~https://github.com/hexojs/hexo/pull/3680~~
- external_link: ~~https://github.com/hexojs/hexo/pull/3685~~
- toc: https://github.com/hexojs/hexo/pull/3850

Related issue:
- https://github.com/hexojs/hexo/pull/550

**Comment by curbengh** [comment]
Can this be part of [the roadmap](https://github.com/hexojs/hexo/issues/2492)?

**Comment by SukkaW** [comment]
Cheerio use `perse5` now and use `htmlparser2` before.

There is a [benchmark](https://github.com/AndreasMadsen/htmlparser-benchmark) between NodeJS side dom parser: https://travis-ci.org/AndreasMadsen/htmlparser-benchmark

![image](https://user-images.githubusercontent.com/40715044/63223519-62c30700-c1e9-11e9-9d60-02c311e4cb68.png)

**Comment by curbengh** [comment]
That means cheerio@1.x is slower than cheerio@0.x.

---

After a glance through the [htmlparser2](https://github.com/fb55/htmlparser2), I wonder if we can use it directly, instead of via cheerio; not sure if that can bring perf benefit.

**Comment by SukkaW** [comment]
@curbengh Hexo is now using `cheerio@0.22`
Maybe we should first test the performance of hexo using `cheerio@1.x`, to see is it actually slower.

**Comment by SukkaW** [comment]
https://github.com/cheeriojs/cheerio/issues/1205#issuecomment-398022252

cheerio has no cache, and `toc()` helper, `open_graph()` helper let cheerio load the same post content. Should we share the cheerio dom with those helpers?

**Comment by curbengh** [comment]
Interesting, perhaps cheerio@1.x includes some optimizations that somehow negate the latency of parse5. Judging from https://github.com/cheeriojs/dom-serializer/pull/85, cheerio@1.x dropped `decodeEntities` and `xmlMode` options, maybe that's why it's faster.

This also means parse5 may not be that slow, so we can consider it in addition to htmlparser2.

**Comment by segayuu** [comment]
The [DOMParser](https://www.npmjs.com/package/dom-parser) package performs [high-speed](https://github.com/snakazawa/html-parser-comparison) analysis according to [web standards Draft].
However, it may be inconvenient because it is a pure parser.

**Comment by curbengh** [comment]
DOMParser looks promising, too bad it can't do any manipulation.

**Comment by curbengh** [comment]
I just tried re-implementing toc using dom-parser. Somehow `parentNode` doesn't work, to replace `$.parent()`.

``` js
const DomParser = require('dom-parser')

const source = `<span>hey<h1>aaa</h1><h2>bbb</h2><h3>ccc</h3></span>`
const dom = new DomParser().parseFromString(source)

const heading = dom.getElementsByTagName('h1')
console.log(heading[0].parentNode)
// null
```

**Comment by SukkaW** [comment]
cheerio is easy to use, and I think the problem of cheerio is it will become very slow when it need to load huge content (for small content cheerio will consume 11ms, for huge content cheerio might consume 65ms).
We might try to use regex to obtain small fragment, then let cheerio to load and manipulate that fragment.

**Comment by SukkaW** [comment]
For the optimization for `toc()` helper, I start with [conditional](https://github.com/hexojs/hexo/pull/3670) require cheerio and [return before cheerio.load](https://github.com/hexojs/hexo/pull/3667): [sukkaw/hexo:lazy-cheerio-for-toc](https://github.com/SukkaW/hexo/tree/lazy-cheerio-for-toc). But the performance dropped by 5%, so I stopped.

@curbengh do you work out the `dom-parser` problem?

**Comment by curbengh** [comment]
Nope, I'm still far off.

**Comment by SukkaW** [comment]
`toc()` helper needs `parentNode`, which makes nearly impossible using regex to replace cheerio.

**Comment by segayuu** [comment]
Regular expressions are specialized for searching from the left, and it is necessary to search from the right to find parents efficiently.
Is there any way other than using `String#lastIndexOf()' and 'RegExp#sticky' flag?

**Comment by SukkaW** [comment]
[html-dom-parser](https://www.npmjs.com/package/html-dom-parser), which is a wrapper of `htmlparser2`, can turn a dom tree into json. And `parent` is supported in `html-dom-parser`.

@curbengh Have a look?

**Comment by SukkaW** [comment]
Currently I have came up with this, a pieces of codes to flatten the `html-dom-parser` output.

```javascript
const parser = require('html-dom-parser');

const output = parser('<p>Hello, <span>world!</span></p><span>123</span>');
console.log(output);

/*
[ { type: 'tag',
    name: 'p',
    attribs: {},
    children: [ [Object], [Object] ],
    next:
     { type: 'tag',
       name: 'span',
       attribs: {},
       children: [Array],
       next: null,
       prev: [Circular],
       parent: null },
    prev: null,
    parent: null },
  { type: 'tag',
    name: 'span',
    attribs: {},
    children: [ [Object] ],
    next: null,
    prev:
     { type: 'tag',
       name: 'p',
       attribs: {},
       children: [Array],
       next: [Circular],
       prev: null,
       parent: null },
    parent: null } ]
 */

let result= {};

Object.assign(result, parseOutput);

const flatten = (tag) => {
  if (!tag.children.length) return tag;
  for (let child of tag.children) {
    if (child.children) {
      flatten(child);
    }
    result[Object.keys(result).length] = child;
  }
};

for (let tag of parseOutput) {
  flatten(tag);
}

console.log(result);

/*
{ '0':
   { type: 'tag',
     name: 'p',
     attribs: {},
     children: [ [Object], [Object] ],
     next:
      { type: 'tag',
        name: 'span',
        attribs: {},
        children: [Array],
        next: null,
        prev: [Circular],
        parent: null },
     prev: null,
     parent: null },
  '1':
   { type: 'tag',
     name: 'span',
     attribs: {},
     children: [ [Object] ],
     next: null,
     prev:
      { type: 'tag',
        name: 'p',
        attribs: {},
        children: [Array],
        next: [Circular],
        prev: null,
        parent: null },
     parent: null },
  '2':
   { data: 'Hello, ',
     type: 'text',
     next:
      { type: 'tag',
        name: 'span',
        attribs: {},
        children: [Array],
        next: null,
        prev: [Circular],
        parent: [Object] },
     prev: null,
     parent:
      { type: 'tag',
        name: 'p',
        attribs: {},
        children: [Array],
        next: [Object],
        prev: null,
        parent: null } },
  '3':
   { data: 'world!',
     type: 'text',
     next: null,
     prev: null,
     parent:
      { type: 'tag',
        name: 'span',
        attribs: {},
        children: [Array],
        next: null,
        prev: [Object],
        parent: [Object] } },
  '4':
   { type: 'tag',
     name: 'span',
     attribs: {},
     children: [ [Object] ],
     next: null,
     prev:
      { data: 'Hello, ',
        type: 'text',
        next: [Circular],
        prev: null,
        parent: [Object] },
     parent:
      { type: 'tag',
        name: 'p',
        attribs: {},
        children: [Array],
        next: [Object],
        prev: null,
        parent: null } },
  '5':
   { data: '123',
     type: 'text',
     next: null,
     prev: null,
     parent:
      { type: 'tag',
        name: 'span',
        attribs: {},
        children: [Array],
        next: null,
        prev: [Object],
        parent: null } } }
 */
```

**Comment by curbengh** [comment]
I am indeed struggling with traversing levels of html-dom-parser output. I'll see how I can proceed. Feel free to work on toc.js, I may only do it this weekend.

**Comment by SukkaW** [comment]
```javascript
const parse5 = require("parse5");

const html = `
<!-- Based on example.org -->
<!doctype html>
<html>
<body>
<div id="container">
    <h1>Example Domain</h1>
    <p>This domain is established to be used for illustrative examples in documents. You may use this
    domain in examples without prior coordination or asking for permission.</p>
    <p id="text"><a href="http://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
`;

const dom = parse5.parse(html);

console.log(dom);
```

will result in an Object of DOM Tree.

Since parse5 doesn't provide methods like `getElementById`, we still need to flatten the Object and traverse through it.

**Comment by SukkaW** [comment]
```js
  const flatten = (obj) => {
    const array = Array.isArray(obj) ? obj : [obj];
    return array.reduce((acc, value) => {
      acc.push(value);
      if (value.children) {
        acc = acc.concat(flatten(value.children));
      }
      return acc;
    }, []);
  };
```

There is a sample code snipppet about how to flatten an array or Object in ES6 way.

**Comment by SukkaW** [comment]
It seems that cheerio used in `toc()` helper just can not be dropped.

`parentNode` of `dom-parser` is broken, `parse5` has no `parent` support, and it is very hard to implement a `textContent` when using `html-dom-parser`.

**Comment by curbengh** [comment]
Just a note that the current published version of cheerio@1.x (an rc) still suffer from [this bug](https://github.com/cheeriojs/cheerio/issues/1198). The [fix](https://github.com/cheeriojs/cheerio/pull/1307) is yet to be published.

Anyhow, I still determined to have toc without cheerio. We can check out how others implement it.

Edit: Just checked out [eleventy-plugin-toc](https://github.com/jdsteinbach/eleventy-plugin-toc) & [eleventy-plugin-nesting-toc](https://github.com/JordanShurmer/eleventy-plugin-toc), they also depend on cheerio...

Perhaps can investigate how other langs implement it.

**Comment by SukkaW** [comment]
@curbengh 
It will be very simple for `toc()` helper to support a regular post since most markdown renderer for hexo will insert id for every heading (both of `hexo-renderer-marked` and `hexo-renderer-markdown-it` enable it by default).

The real chanllenge is the post which is doesn't written in markdown, which each heading tags might not have id attr, thus `toc()` helper have to look up for its parent element.

**Comment by stevenjoezhang** [comment]
Some issues about `id for every heading`:
https://github.com/theme-next/hexo-theme-next/issues/1227
https://github.com/theme-next/hexo-theme-next/issues/1168
https://github.com/theme-next/hexo-theme-next/issues/882

**Comment by SukkaW** [comment]
@curbengh https://github.com/derhuerst/flickr-photo-url/pull/10

I have found a PR about some project relpace cheerio with htmlparser2. I might carry out some expriment then.

**Comment by SukkaW** [comment]
@curbengh 

Although for Hexo itself, the behavior of `toc()` helper doesn't changes. But dropping cheerio will break theme that load `cheerio` from hexo's `node_modules`. We should mention it in `4.2.0`'s release notes to warn the theme maintainers & users.

**Comment by SukkaW** [comment]
Hexo has completely replace lodash with native JavaScript after #3850 is merged, so the issue can be closed now.

cheerio will remain in devDependencies since it is quite useful when making a unit test.
