### ISSUE TITLE
JS Helper should have the ability to add async/defer/integrity attributes

### ISSUE THREAD

**Issue by caffeinewriter** [hexojs/hexo#3687]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

The default `js()` helper should ideally have the ability to add attributes like async and defer, which can help significantly with time-to-first-paint. Perhaps to maintain backwards compatibility, take in either a string which maintains current behavior, or an object which could have the attributes as keys.

**Comment by curbengh** [comment]
Working on it https://github.com/hexojs/hexo/pull/3681

**Comment by caffeinewriter** [comment]
Thanks! I checked issues, but I didn't think to check PRs. Looking forward to that landing!

**Comment by curbengh** [comment]
As not to disappoint you, since this feature is not high priority (can always use `<script>`), most probably it won't be part of v4 release. But I'll try my best to land this in v4.1.

**Comment by curbengh** [comment]
Btw, in the meantime, you could also consider a custom JS helper with this ability.
Simply add [this file](https://gitlab.com/curben/blog/blob/master/scripts/addJs.js) into the `scripts/` folder, and use `<%- addJs({src: '', integrity: ''}) %>` (function name is customizable). The only difference is that path name must ends with .js.
