### ISSUE TITLE
highlight documentation

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo#3688]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

The `highlight` configuration key is not properly documented.

https://hexo.io/docs/configuration#Writing

The key `highlight` has for description `Code block settings`, nothing more. What's the default value? What kind of value does it accepts?

I also understood that the default syntax highlighter of Hexo is highlight.js but that not written in the doc. What is the highlight.js version currently used? What languages are supported? All? Only common ones? What syntax highlight themes are supported?

**Comment by YoshinoriN** [comment]
### highlight version

highlight feature are implemented in the hexo-util.
The hexo 3.9.0 using the hexo-util 0.6.3. And its highlight version is [9.4.0](https://github.com/hexojs/hexo-util/blob/5b60f2cbbb425b04bc41f4660671b6cb70e38764/package.json#L44)

### Default value

Default value is [here](https://github.com/hexojs/hexo/blob/f3e0f5ce4f08d0a4ba004a0cbde23e8be8a0cdbb/lib/hexo/default_config.js#L35-L39).

Sorry, I don't know more info.

**Comment by noraj** [comment]
Thanks @YoshinoriN , I would be great that the parameter in [here](https://github.com/hexojs/hexo/blob/f3e0f5ce4f08d0a4ba004a0cbde23e8be8a0cdbb/lib/hexo/default_config.js#L35-L39) be documented on the configuration documentation.

**Comment by curbengh** [comment]
https://github.com/hexojs/site/pull/1057
