### ISSUE TITLE
Support for including CNAME and 404 files before uploading to git?

### ISSUE THREAD

**Issue by hakcat** [hexojs/hexo#3692]
## Check List

Please check followings before submitting a new feature request.

- [ ] I have already read [Docs page](https://hexo.io/docs/)
- [ ] I have already searched existing issues

**Comment by SukkaW** [comment]
Add `CNAME` and `404.html` files directly in the `source` directories will do.

**Comment by curbengh** [comment]
To demonstrate, this is my blog's [source folder](https://gitlab.com/curben/blog/tree/master/source). You shouldn't need to [configure](https://gitlab.com/curben/blog/blob/master/_config.yml#L28) anything, as 404.html will be rendered according to `page` layout (of your theme) by default, and CNAME shouldn't get rendered. If CNAME somehow gets rendered, add it to the [`skip_render`](https://gitlab.com/curben/blog/blob/master/_config.yml#L28) list.
