### ISSUE TITLE
安装hexo博客时，hexo init blog这一步卡住了

### ISSUE THREAD

**Issue by bigbearbx** [hexojs/hexo#3693]
D:\blog>hexo init blog
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
Cloning into 'D:\blog\blog'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 81 (delta 0), reused 1 (delta 0), pack-reused 77
Unpacking objects: 100% (81/81), done.
Submodule 'themes/landscape' (https://github.com/hexojs/hexo-theme-landscape.git) registered for path 'themes/landscape'
Cloning into 'D:/blog/blog/themes/landscape'...
remote: Enumerating objects: 1018, done.
remote: Total 1018 (delta 0), reused 0 (delta 0), pack-reused 1018
Receiving objects: 100% (1018/1018), 3.20 MiB | 352.00 KiB/s, done.
Resolving deltas: 100% (555/555), done.
Submodule path 'themes/landscape': checked out '73a23c51f8487cfcd7c6deec96ccc7543960d350'
[32mINFO [39m Install dependencies
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[ .................] \ fetchMetadata: sill pacote version manifest for hexo-pagination@0.0.2 fetched in 34605ms

**Comment by SukkaW** [comment]
如果在安装依赖这一步出现了卡顿，请尝试为 NPM 设置代理、或为 NPM 设置镜像源（[CNPM](https://r.cnpmjs.org/) 或 [淘宝 NPM](https://registry.npm.taobao.org/)）。

**Comment by liuyib** [comment]
我也是执行这一步一直报错：`npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.`。
![image](https://user-images.githubusercontent.com/38221479/64091973-64fa9900-cd85-11e9-89f9-9c8aa2b14eb1.png)
我在原来能跑起来的项目中执行 `npm ls core-js` 后，输出如下：
![image](https://user-images.githubusercontent.com/38221479/64092069-c458a900-cd85-11e9-97bd-8ccc4b5acade.png)
所以，是不是需要更新一下依赖？

**Comment by stevenjoezhang** [comment]
升级Hexo到4.0即可。依赖问题已被解决。

**Comment by chenshuai-coder** [comment]
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
Cloning into 'D:\blog'...
D:/blog/.git: Permission denied
WARN  git clone failed. Copying data instead
WARN  Failed to install dependencies. Please run 'npm install' manually!
在这一步卡住了，ssh配置和npm换源都试了，还是不行

**Comment by xuanyinmu** [comment]
换个教程，删了重来



---原始邮件---
发件人: "chenshuai-coder"<notifications@github.com&gt;
发送时间: 2020年4月8日(星期三) 晚上7:19
收件人: "hexojs/hexo"<hexo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [hexojs/hexo] 安装hexo博客时，hexo init blog这一步卡住了 (#3693)




 
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
 Cloning into 'D:\blog'...
 D:/blog/.git: Permission denied
 WARN  git clone failed. Copying data instead
 WARN  Failed to install dependencies. Please run 'npm install' manually!
 在这一步卡住了，ssh配置和npm换源都试了，还是不行

**Comment by chenshuai-coder** [comment]
已解决，，要在管理员模式下运行，普通模式，会出现错误

**Comment by zoe-icu** [comment]
@chenshuai-coder 解决了我的问题

**Comment by Guolighting** [comment]
$ hexo init blog
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
fatal: unable to access 'https://github.com/hexojs/hexo-starter.git/': Proxy CONNECT aborted
WARN  git clone failed. Copying data instead
FATAL {
  err: [Error: ENOENT: no such file or directory, scandir 'C:\Users\gl\AppData\Roaming\npm\node_modules\hexo-cli\assets'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'scandir',
    path: 'C:\\Users\\gl\\AppData\\Roaming\\npm\\node_modules\\hexo-cli\\assets'
  }
} Something's wrong. Maybe you can find the solution here: %s http://hexo.io/docs/troubleshooting.html
