### ISSUE TITLE
有after_post_render，有沒有after_page_render?

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#3702]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

想對生成的img 或 代碼框進行修改，添加複製按鈕。。
雖然可以通過js來動態添加，
但我想通過hexo内置的api進行修改。。
我知道after_post_render，但這也只限制post頁的修改，而不是全部網頁的修改。。
不知有沒有其他的api,例如after_page_render ？ 或者有什麽其他方法？

**Comment by curbengh** [comment]
> 全部網頁

what about [`after_render`](https://hexo.io/api/rendering#after_render_Filters)? It applies to both post and page.
``` js
hexo.extend.filter.register('after_render:html', (str, data) => {
  const result = UglifyJS.minify(str);
  return result.code;
});
```

More [example](https://gitlab.com/curben/blog/blob/master/scripts/copy-button.js).
