### ISSUE TITLE
我想设置主页为第一个分类的界面,就是分类之后的页面,请问怎么设置呢

### ISSUE THREAD

**Issue by DragonFlykeeperDC** [hexojs/hexo#3703]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by curbengh** [comment]
> 分类之后的页面
Do you mean category or tag? Let say it's category, so you want your homepage to be a list of categories?
