### ISSUE TITLE
The order of posts in specified categories

### ISSUE THREAD

**Issue by aprz512** [hexojs/hexo#3706]
Now, it seems like the post list in category order by date.

For example, i have 4 posts, it shows like below:

https://xxxxx/categories/xxx/

\----------
|
· 2019
|
· 0001-post
|
· 0003-post
|
· 0004-post
|
· 0002-post
\---------

I want it ordered by post's title, it should be like this:
\----------
|
· 2019
|
· 0001-post
|
· 0002-post
|
· 0003-post
|
· 0004-post
|
\---------

or

\----------
|
· 2019
|
· 0004-post
|
· 0003-post
|
· 0002-post
|
· 0001-post
|
\---------

**Comment by curbengh** [comment]
In your `_config.yml`
``` yml
category_generator:
  order_by: title
```

`title` for ascending order, `-title` for descending.

**Comment by aprz512** [comment]
Does not work。I found the problem。
Seems `hexo-genetator-category/lib/generator.js` this file, sort `-date` in hard code.

**Comment by curbengh** [comment]
> Seems hexo-genetator-category/lib/generator.js this file, sort -date in hard code.

The option was [recently introduced](https://github.com/hexojs/hexo-generator-category/pull/23). Please upgrade hexo-generator-category to v1.0.0.

**Comment by aprz512** [comment]
Thanks
