### ISSUE TITLE
Get the current mode(production | development)?

### ISSUE THREAD

**Issue by wzpan** [hexojs/hexo#371]
express 提供了 development 和 production 兩種工作模式，利用這個可以做一些特別的功能。

Since express offers two working modes(development mode and production mode), we can use them to do some cool stuff.

例如，如果我可以在我的模板裏獲取當前的模式，那麼我可以編寫腳本讓其在開發者模式插入普通的 css 和 javascript 文件，而在 production 模式下改爲插入用 YUICompressor 壓縮後的 .min.css 和 .min.js 文件。

For instance, if I can get current mode in my templates, I can write some scripts to insert different css and javascripts depending on what the current mode is.

在使用 Ruby on Rails 和 mustache 模板語言的 [ruhoh](http://ruhoh.com/) 裏，類似的代碼如下：

For [ruhoh](http://ruhoh.com/), another static blog generator based on Ruby on Rails and mustache template language, I can do that by writing the following codes:

```
{{# stylesheets.load }}
    {{# env.production }}
        bootstrap.min.css
        bootstrap-responsive.min.css
        style.min.css
        responsive.min.css        
    {{/ env.production }}
    {{^ env.production }}
        bootstrap.css
        bootstrap-responsive.css
        style.css
        responsive.css    
    {{/ env.production }}    
{{/ stylesheets.load }}
```

如果 hexo 支持這樣的功能，那麼將對修改樣式帶來方便。是否可以實現這樣的功能？

If hexo also exposes this kind of interface, that will helps a lot to modify style sheets. Can it?

**Comment by gurdotan** [comment]
So is there a way to know what environment we're currently in? And is it possible to be in `development` and then change to `production` once the site is deployed with `hexo deploy`?
