### ISSUE TITLE
windows可以安装那个mac的pow吗

### ISSUE THREAD

**Issue by qinzeduomoxiong** [hexojs/hexo#3711]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by qinzeduomoxiong** [comment]
windows可以安装mac的pow吗 不能的话有什么替代的可以安装呢

**Comment by curbengh** [comment]
No.

> [Pow is a zero-config Rack server for **Mac OS X**](http://pow.cx/)
