### ISSUE TITLE
Is hexo incompatible with IE browser? IE browser opens pages in a messy way

### ISSUE THREAD

**Issue by DragonFlykeeperDC** [hexojs/hexo#3713]
hexo不兼容ie浏览器吗,ie浏览器打开页面很乱 
![image](https://user-images.githubusercontent.com/41666627/64676497-4cd2fa00-d4a8-11e9-9b92-aad30b80c4e8.png)

**Comment by stevenjoezhang** [comment]
Old version of IE is [not support by Microsoft from January 12, 2016](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support). [IE 11 was supported till 2015 year](https://ru.wikipedia.org/wiki/Internet_Explorer_11).

**Comment by curbengh** [comment]
My guess is that the theme doesn't include [html5shiv](https://github.com/aFarkas/html5shiv). Even [hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape) doesn't have it (not saying it should, depends on user demand).
