### ISSUE TITLE
Can not find git user information

### ISSUE THREAD

**Issue by FantasyVR** [hexojs/hexo#3714]
I just config multi-git user in my pc. However, when I tried to deploy Hexo project. I got an error: `Fatal: unable to auto-detect email address`.
I configured user name and email with:
```bash
git config user.name "myname"
git config user.email "myemail"
```
But the error still occures.
Below is the screenshot:
![图片](https://user-images.githubusercontent.com/6712304/64701604-a56fba80-d4db-11e9-919e-a951cf4fbab8.png)

**Comment by curbengh** [comment]
> > Try run git config -g user.email
> 
> `error: unknow swith 'g'`

What about `git config --global user.email`

btw, if the repository is not private, you can use Travis CI to automate the deployment. See https://hexo.io/docs/github-pages
