### ISSUE TITLE
Article don't be shown in homepage

### ISSUE THREAD

**Issue by Yiuo** [hexojs/hexo#3715]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

I create a new page but not category or tag or about, I want to use it to store some articles that don't be shown in homepage. Now that page is all ready, but the articles still can see in homepage :(  How to solve thx.

**Comment by curbengh** [comment]
So, you want to create a new homepage?

1. Rename your `themes/installed-theme/layout/index.ejs` to `index.ejs.bk`
2. Duplicate the file which has the new layout to `index.ejs`.
3. `$ hexo clean && hexo server`
4. Check the homepage.
