### ISSUE TITLE
关于 pagination 

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#3720]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

我创建了一个page,但是没有跟主页那样 10篇文章就分页。。
怎么做才会分页？

![image](https://user-images.githubusercontent.com/16351105/64871534-fc11fb80-d677-11e9-84dd-3a7cbc6f0f62.png)
![image](https://user-images.githubusercontent.com/16351105/64871545-046a3680-d678-11e9-8b02-af9fb572da98.png)
![image](https://user-images.githubusercontent.com/16351105/64871560-0d5b0800-d678-11e9-8701-3d9f46ad6e46.png)

**Comment by curbengh** [comment]
you probably need to roll your own script (a js file in themes/melody/scripts/) to use [hexo-paginator](https://github.com/hexojs/hexo-pagination) since you're creating a new layout.

Refer to [hexo-generator-index](https://github.com/hexojs/hexo-generator-archive) or [hexo-generator-tag](https://github.com/hexojs/hexo-generator-tag).

Take note of `layout:` option of [hexo-pagination](https://github.com/hexojs/hexo-pagination#paginationbase-posts-options), because you need to set it to `layout: 'your-custom-layout'`.

**Comment by jerryc127** [comment]
what mean of layout ?
![image](https://user-images.githubusercontent.com/16351105/64918452-ef54eb00-d7d0-11e9-872b-b16a3130d15b.png)

i use page.type to generate the page, so what layout in this page

**Comment by jerryc127** [comment]
hope can help me . thx @curbengh

**Comment by curbengh** [comment]
Looks like it's the `page` layout ("themes/melody/layout/page.pug"), it may look like

``` js
const pagination = require('hexo-pagination');
const posts = locals.posts.sort('-date');
const path = this.path;

pagination(path, posts, {
  perPage: 10,
  format: 'page/%d/',
  layout: 'page'
});
```

**Comment by jerryc127** [comment]
I try this
```
var pagination = require('hexo-pagination');


hexo.extend.generator.register('sub-menu', function (locals) {

  const posts = locals.categories.findOne({name: 'Android'}).posts
  return pagination('/test/', posts, {
    perPage: 3,
    format: 'page/%d/',
    layout: ['sub-menu','page' ,'archive', 'index'],

  });
})
```

but it something wrong
![image](https://user-images.githubusercontent.com/16351105/64918871-b0299880-d7d6-11e9-8acd-5be5cbb8eb02.png)

@curbengh

**Comment by jerryc127** [comment]
thx @curbengh 
i solve

**Comment by curbengh** [comment]
Mind sharing the code? I'm curious to see your solution and it can help others too.

**Comment by jerryc127** [comment]
it not solve..

do you know what the mean of this code?

```
  return locals.categories.reduce((result, category) => {
 
    const posts = category.posts.sort(orderBy);
    const data = pagination(category.path, posts, {
      perPage,
      layout: ['category', 'archive', 'index'],
      format: paginationDir + '/%d/',
      data: {
        category: category.name
      }
    });

    return result.concat(data);
  }, []);
```

  return locals.categories.reduce((result, category) => {, []);

i want to traverse all pages and match the page which set the 'layout: sub-menu'  in front-matter,
want all page which set the 'layout: sub-menu'  in front-matter have a pagination.
@curbengh

**Comment by curbengh** [comment]
I think Array.filter() should suffice?

``` js
  const posts = [].concat(locals.posts.toArray(), locals.pages.toArray())
    .filter(post => {
      return post.layout === 'sub-menu';
    })
    .sort((a, b) => {
      return b.updated - a.updated;
    });
```

I haven't test the code, it might not be `post.layout`. Perhaps you can prepend `console.log` to find out the data structure,

``` js
console.log(post);
return post.layout === 'sub-menu';
```
