### ISSUE TITLE
设置只能自己访问

### ISSUE THREAD

**Issue by qiji2018** [hexojs/hexo#3723]
想使用hexo当笔记用，怎么设置只能自己本机访问，同局域网他人不能访问

**Comment by stevenjoezhang** [comment]
防火墙

**Comment by qiji2018** [comment]
mac本 哪里可以设置

**Comment by stevenjoezhang** [comment]
看看这个：https://support.apple.com/zh-cn/guide/mac-help/mh34041/mac

**Comment by YoshinoriN** [comment]
@qiji2018 
This issue caused by your PC or network etc... Not caused by hexo. I close this issue.

@stevenjoezhang 
Thank you for support :)
