### ISSUE TITLE
 I have many many articles that need to be updated to the blog，But it boom

### ISSUE THREAD

**Issue by chenshiforever** [hexojs/hexo#3726]
I have 3,000 articles that need to be updated to the blog. The md files of these articles are all in the post directory, but I have tested it for a long time. The current maximum number of posts can only reach 1000. If it exceeds 1000, it will crash in the gen stage. I don't know if there is any way to help me accomplish this goal?
中文版：我现在大约有3000篇文章需要更新到博客，这些文章的md文件都在post目录下面，但是我测试了很久，目前的最大post数量只能到1000，如果超过了1000个，就会在gen阶段崩溃，不知道有不有方法能帮我完成这个目标呢？

this is error info

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::Smi::SmiPrint
 6: v8::internal::StackGuard::HandleInterrupts
 7: v8::internal::AsmJsScanner::IsNumberStart
 8: 0000004D256843C1

**Comment by SukkaW** [comment]
Set node_flags `--max-old-space-size=8192` should work.

**Comment by YoshinoriN** [comment]
@chenshiforever 
Another solution, we merged [`concurrency` option](#3665) for this issue that includes [v4.0.0](https://github.com/hexojs/hexo/milestone/24).

You can use `concurrency` option if you use the master branch. I'm using the master branch on my blog and that seems stable.

**Comment by chenshiforever** [comment]
> Set node_flags `--max-old-space-size=8192` should work.

I tried this method, but it didn't work.

**Comment by chenshiforever** [comment]
> @chenshiforever
> Another solution.
> We merged [concurrency option](https://github.com/hexojs/hexo/pull/3665) for this issue. It will be released in [v4.0.0](https://github.com/hexojs/hexo/milestone/24).
> 
> You can use `concurrency` option if you use the `master` branch. I'm using the [master branch (a58acb9)](https://github.com/hexojs/hexo/tree/a58acb9ca0a62f58eb6f0f751f001c0e984849db) on my blog and that seems stable.

it's very good! I solved it! 感谢大佬
