### ISSUE TITLE
cant insert bordered table in markdown

### ISSUE THREAD

**Issue by winterland1989** [hexojs/hexo#374]
when i try to insert table with following syntax:
| Time per digitalWrite | Arduino | Wiring, const pin  | Wiring, non-const pin |
|-: | :-: | :-: | :-:  |
|8-bit loop variable |  4.09 us |   0.23 us |   4.53 us |
|16-bit loop variable | 4.20 us |   0.25 us |   4.63 us |

i did get a table, but its style is wrong, when i try to modify the table's style, i found that  the code highlighter use table as well, thus i cant make the border visible, is there a solution to solve this?

**Comment by nadrane** [comment]
Is it possible to just add a class to tables that are generated using markdown tables but not add that class to tables inside figures?
