### ISSUE TITLE
Add `build` script property

### ISSUE THREAD

**Issue by leo** [hexojs/hexo#3740]
When running `hexo init`, this is what you see:

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": ""
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-server": "^0.3.3"
  }
}
```

Would it be possible to add a `build` script to **all the templates**? Like so:

```
"scripts": {
  "build": "hexo generate"
}
```

By doing that, you would open up Hexo to a wide range of deployment providers that automatically detect the `build` script. Aside from that, it would also help when developing locally, since you can just invoke `yarn build` to build your site.

**Comment by curbengh** [comment]
Reminds me of Zeit that I stumbled upon a few weeks ago, which [detects](https://zeit.co/docs/v2/build-step/) `build` script.
