### ISSUE TITLE
 Quality of Documentation for Extension Developer is Terrible

### ISSUE THREAD

**Issue by cedric-sun** [hexojs/hexo#3747]
> ### [Initialize](https://hexo.io/api/index.html)
> First, we have to create a Hexo instance.

Well, seriously? You don't have to create a hexo instance if you are developing plugins, because the hexo runtime invoked from the CLI will load your script instead. That's merely the very first meaningful sentences of you API document, and it's wrong. At least please add some restriction and provide some context, and avoid making too general statements, otherwise it could be very confusing to new plugins developer.

Some pages of the document is just brusque, like [Processor](https://hexo.io/api/processor).

Last thing. It's good we have all those API document around, but that's not a "guide" on extension development. Are we supposed to write our extension right in the `node_modules` directory under the hexo root? Or should we put it in some separate directory and refer to it in  the `package.json` of hexo? In the latter case should we add `hexo` in `dependencies`? Or `devDependencies`? Or not at all? At least I was expecting some recommendation or pros-and-cons from the official team, not from some personal blogs.

I don't think that quality of developmental documentation is consistent with a 28k stars repo. Do you have any plan to improve it?

**Comment by curbengh** [comment]
Transferring to https://github.com/hexojs/site as that's the source of documentation.
