### ISSUE TITLE
Hexo command not found

### ISSUE THREAD

**Issue by TeAmP0is0N** [hexojs/hexo#3749]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Node.js is higher than 6.9

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

```bash
 hexo init blog

Command 'hexo' not found, did you mean:

  command 'hex' from deb basez

Try: sudo apt install <deb name>
```

**Comment by tomap** [comment]
Try `npx hexo init blog`
Also, did you read this doc: 
https://hexo.io/docs/#Install-Hexo

**Comment by TeAmP0is0N** [comment]
Yeah, I read the blog but didn't work.

**Comment by tomap** [comment]
Hum, can you provide more information?
Like the result of the command line you tried?
screenshots, copy of the text output, your os, results of `npm -v` and `node -v` ?

**Comment by TeAmP0is0N** [comment]
Solved, thank you!

**Comment by JonOnEarth** [comment]
Hey, man, how you solve this problem?
