### ISSUE TITLE
什么时候hexo的Markdown语法能支持MathJax的语法

### ISSUE THREAD

**Issue by eonun** [hexojs/hexo#3750]
什么时候hexo的Markdown渲染能支持MathJax的语法，虽然有hexo-math插件，但兼容性不太好，建议官方渲染其就能渲染，现在的Markdown编辑器都有对MathJax的渲染，但hexo却不支持-_-

**Comment by curbengh** [comment]
Are you using hexo-renderer-marked?

**Comment by stevenjoezhang** [comment]
https://github.com/stevenjoezhang/hexo-filter-mathjax

**Comment by stevenjoezhang** [comment]
Closing as answered.

**Comment by curbengh** [comment]
Hey everyone, I am rewriting hexo-math atm (https://github.com/hexojs/hexo-math/pull/130). It's ready for testing, just install it by `$ npm install hexo-math@curbengh/hexo-math#overhaul`. If there is no issue, I plan to release it on this weekend.
