### ISSUE TITLE
Replace lodash with native API

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#3753]
## Feature Request

The idea came from https://github.com/hexojs/site/pull/1139#discussion_r332336052 & #3677.

There is [an article](https://codeburst.io/why-you-shouldnt-use-lodash-anymore-and-use-pure-javascript-instead-c397df51a66) suggests we don't need lodash anymore.

According to benchmark below we can see es6 performance more or less as same as Lodash, in term of CPU, Memory or Handling time, at least in browser.

- https://dustinpfister.github.io/2017/11/20/lodash_foreach/
- https://hackernoon.com/es6-lodash-native-javascript-nodejs-example-tutorial-map-function-functional-programming-performance-speed-69645e613049
- https://www.reddit.com/r/javascript/comments/8j2hmq/performance_lodash_vs_es6_map/

There are also some benchmark of lodash vs es6 and es6 is definitely much faster in browser:

- https://blog.bitsrc.io/you-dont-need-lodash-or-how-i-started-loving-javascript-functions-3f45791fa6cd
- https://codeburst.io/why-you-shouldnt-use-lodash-anymore-and-use-pure-javascript-instead-c397df51a66

IMHO, we might consider replace at least some lodash with native js.

A guide about how to replace lodash with es6: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

A list of files that requires lodash:

**hexo**

- [x] [lib/plugins/console/deploy.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/console/deploy.js)
- [x] [lib/theme/view.js](https://github.com/hexojs/hexo/blob/master/lib/theme/view.js)
- [x] [lib/plugins/filter/template_locals/i18n.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/template_locals/i18n.js)
- [x] [lib/theme/index.js](https://github.com/hexojs/hexo/blob/master/lib/theme/index.js)
- [x] [lib/hexo/load_config.js](https://github.com/hexojs/hexo/blob/master/lib/hexo/load_config.js)
- [x] [lib/plugins/filter/post_permalink.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/post_permalink.js)
- [x] [lib/plugins/helper/toc.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/toc.js)
- [x] [lib/plugins/helper/date.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/date.js)
- [x] [lib/hexo/multi_config_path.js](https://github.com/hexojs/hexo/blob/master/lib/hexo/multi_config_path.js)
- [x] [lib/plugins/filter/new_post_path.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/new_post_path.js)
- [x] [lib/hexo/post.js](https://github.com/hexojs/hexo/blob/master/lib/hexo/post.js)
- [x] ~~[lib/hexo/index.js](https://github.com/hexojs/hexo/blob/master/lib/hexo/index.js)~~
- [x] [test/scripts/hexo/load_config.js](https://github.com/hexojs/hexo/blob/master/test/scripts/hexo/load_config.js)
- [x] [test/scripts/filters/backtick_code_block.js](https://github.com/hexojs/hexo/blob/master/test/scripts/filters/backtick_code_block.js)

We might start with lib located under `lib/plugins/`

**warehouse**

- [x] [lib/document.js](https://github.com/hexojs/warehouse/blob/109151a3dbd9782eac97c2d6ff30d0a35a25e2ab/lib/document.js)
- [x] [lib/model.js](https://github.com/hexojs/warehouse/blob/109151a3dbd9782eac97c2d6ff30d0a35a25e2ab/lib/model.js)

cc @curbengh @segayuu

**Comment by SukkaW** [comment]
Also, benchmark is needed to see if the generation becomes faster after we remove lodash.

**Comment by curbengh** [comment]
I created a [project](https://github.com/orgs/hexojs/projects/5) to help us learn from each other's PRs in this task.

Currently, Hexo [exposes](https://hexo.io/docs/variables#Global-Variables) lodash function globally. If we manage to refactor everything, we might consider dropping lodash entirely. That is definitely a breaking change, perhaps part of v5 roadmap.

**Comment by SukkaW** [comment]
> Currently, Hexo [exposes](https://hexo.io/docs/variables#Global-Variables) lodash function globally. If we manage to refactor everything, we might consider dropping lodash entirely. That is definitely a breaking change, perhaps part of v5 roadmap.

@curbengh  We might drop in helpers & filters first, which might not cause any breaking changes and can be done in v4.

**Comment by SukkaW** [comment]
Currently, there is no better ways to replace `lodash.merge` or `lodash.asignIn` with vanilla JS. I assume it is the reason we should use lodash.

**Comment by curbengh** [comment]
One annoyance I found with `Object.assign()` is that it doesn't replace key with undefined value, especially when assigning a default config for a plugin. a key will have `undefined` value when the value is left empty, even the [default config](https://github.com/hexojs/hexo-starter/blob/master/_config.yml) has empty keys. As such, I always need to check for `undefined` and assign default value _again_.

lodash's `_.defaults` (used previously in hexo) doesn't need that extra step.

``` js
// Sample _config
const hexo = { aaa: { bbb: undefined } }

hexo.aaa = Object.assign({ bbb: 'ccc' }, hexo.aaa)
// undefined

hexo.aaa = _.defaults({ bbb: 'ccc' }, hexo.aaa)
// 'ccc'

hexo.aaa = _.defaultsDeep({ bbb: 'ccc' }, hexo.aaa)
// 'ccc'

hexo.aaa = _.merge({ bbb: 'ccc' }, hexo.aaa)
// 'ccc'

hexo.aaa = _.assign({ bbb: 'ccc' }, hexo.aaa)
// undefined

hexo.aaa = _.assignIn({ bbb: 'ccc' }, hexo.aaa)
// undefined

hexo.aaa = _.extend({ bbb: 'ccc' }, hexo.aaa)
// undefined
```

**Comment by SukkaW** [comment]
@curbengh Yeah, only replace `_.defaults` with `Object.assign` when there is no `undefined` will be met.
Also, when there is no prototype thing need to be merged, `Object.assign` could be used to replace `_.assignIn` as well, just as I did in #3785

**Comment by SukkaW** [comment]
I have tried `Object.getPrototypeOf`, `Reflect.getPrototypeOf` even deprecated `__proto__`, but none of them could match the performance of `lodash.merge`.

**Comment by SukkaW** [comment]
I have nearly finished:

```js
function extend(...args) {
  for (let i < args.length - 1; i >= 0; --i) {
    for (const key in args[i])
      args[0][key] = args[i][key];
  }

  return args[0];
}
```

The `extend()` below could merge multiple one-level objects along with its prototype. But it just can not perform a deep-level object merge.

**Comment by SukkaW** [comment]
Hexo has completely replace lodash with native JavaScript after #3969, so the issue can be closed now.

I have added a separate item `Remove _ (lodash) from Locals` to Roadmap (#2492). Since removing lodash from `Locals` should considered as a Breaking Changes, we will finish it in Hexo 5.0.
