### ISSUE TITLE
fatal: Could not read from remote repository after inputing  "hexo d"

### ISSUE THREAD

**Issue by llllllllr** [hexojs/hexo#3755]
It was not the first time I commit the blogs. 
"hexo d" works before ,but today I met the problem 

> fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Spawn failed

**Comment by curbengh** [comment]
Please provide:

1. Hexo and Plugin version(`npm ls --depth 0`)
2. Your package.json `package.json`
