### ISSUE TITLE
perf: database.save is become slower than before

### ISSUE THREAD

**Issue by dailyrandomphoto** [hexojs/hexo#3758]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [x] Node.js is higher than 6.9

## Expected behavior
When I generate `hexojs/site` project on my local, I found it takes a long time than before.
With `--debug` option, it shows that `database.save` takes a lot of time.

## Actual behavior
With `hexo@3.9.0`, saving the database takes about **2 seconds**, but with latest version of hexo, saving the database takes about **1 minute** on Travis CI, and **4 minutes** on my local VM.

## How to reproduce?

```sh
git clone https://github.com/hexojs/site.git
cd site
npm install
npm run build --debug
```

## Environment & Settings
I've compared the speed of generating works with different versions. I found from this [commit](https://github.com/hexojs/hexo/commit/bc7740f5637d109bbd64d65314e2959bc491a7ed) it becomes slow.
It relates to 
- chore(deps): update warehouse requirement from ^2.2.0 to ^3.0.0 #3736

Test name | hexo version | Elapsed time of `database.save` | Build log on Travis | Repo Link
--- | --- | --- | --- | ---
test1 | 3.9.0 | 2s | [link](https://travis-ci.org/dailyrandomphoto/site/builds/596179375#L2786) | [link](https://github.com/dailyrandomphoto/site/tree/compare-hexo-perf-1)
test2 | [Merge pull request #3675 from curbengh/external-link](https://github.com/hexojs/hexo/commit/6142b843376b54f88229dd580a4e23add71ed1b3) | 2s | [link](https://travis-ci.org/dailyrandomphoto/site/builds/596192504#L2786) | [link](https://github.com/dailyrandomphoto/site/tree/compare-hexo-perf-2)
test3 | [chore(deps): update warehouse requirement from ^2.2.0 to ^3.0.0 (#3736) ](https://github.com/hexojs/hexo/commit/bc7740f5637d109bbd64d65314e2959bc491a7ed) | 57s | [link](https://travis-ci.org/dailyrandomphoto/site/builds/596175208#L2786) | [link](https://github.com/dailyrandomphoto/site/tree/compare-hexo-perf-3)
test4 | latest version [perf(cache): improve cache and reduce Memory Usages (#3756)](https://github.com/hexojs/hexo/commit/6f6084cb4d5772061aa45703b258634a0db13cee) | 63s | [link](https://travis-ci.org/dailyrandomphoto/site/builds/596174683#L2829) | [link](https://github.com/dailyrandomphoto/site/tree/compare-hexo-perf-4)

**Node.js & npm version**
```
$ node --version
v10.16.3
$ npm --version
6.9.0
```

**Your package.json `package.json`**

test1
```
"hexo": "^3.9.0",
```

test2
```
"hexo": "github:hexojs/hexo#6142b843376b54f88229dd580a4e23add71ed1b3",
```

test3
```
"hexo": "github:hexojs/hexo#bc7740f5637d109bbd64d65314e2959bc491a7ed",
```

test4
```
"hexo": "github:hexojs/hexo#6f6084cb4d5772061aa45703b258634a0db13cee",
```

## Others
test1
<img width="495" alt="site - Travis CI 2019-10-11 00-40-35" src="https://user-images.githubusercontent.com/51783821/66588814-d6690b00-ebbf-11e9-9544-6bf6fb1f904e.png">

test2
<img width="528" alt="2019101102" src="https://user-images.githubusercontent.com/51783821/66589060-52fbe980-ebc0-11e9-9ee2-356d04ddebc3.png">

test3
<img width="520" alt="2019101103" src="https://user-images.githubusercontent.com/51783821/66589075-58593400-ebc0-11e9-84fe-882f43d64e02.png">

test4
<img width="498" alt="2019101104" src="https://user-images.githubusercontent.com/51783821/66589095-60b16f00-ebc0-11e9-8a7b-008020d7654c.png">

**Comment by SukkaW** [comment]
https://github.com/hexojs/warehouse/compare/2.2.0...3.0.0

Compare between `warehouse@2` and `warehouse@3`.

**Comment by SukkaW** [comment]
It seems that I have found the smoking gun:
https://github.com/hexojs/warehouse/commit/0e2eeb39f5590e23b5a555ee4312affcd2c6a43e

**Comment by SukkaW** [comment]
I have run a benchmark:

| Hexo 4.0 | NodeJS 8 | NodeJS 10 | NodeJS 12 |
|:---:|:---:|:---:|:---:|
| Load Files | 6.9s / 2.87s | 6.06s / 2.59s | 6.06s / 2.55s |
| Genrate Files | 11s / 10s | 8.99s / 8.7s | 9.18s / 8,95s |
| Save Database | 0.7s / 0.6s | 0.6s / 0.8s | 0.51s / 0.45s |

| This PR | NodeJS 8 | NodeJS 10 | NodeJS 12 |
|:---:|:---:|:---:|:---:|
| Load Files | 6.8s / 2.8s | 6.09s / 2.57s | 6.09s / 2.6s |
| Genrate Files | 11s / 10s | 8.99s / 8.65s | 9.24s / 8.97s |
| Save Database | 0.6s / 0.6s | 0.6s / 0.7s | 0.45s / 0.48s |

(Cold Processing / Hot Processing)

I think it is ok to go.
