### ISSUE TITLE
"npm test" fails occasionally (potential race condition)

### ISSUE THREAD

**Issue by seaoak** [hexojs/hexo#3759]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Node.js is higher than 6.9

## Expected behavior

"npm test" always runs successfully.

## Actual behavior

When "npm test" is repeated, it fails occasionally.
The failure is a test case "process() - hash changed" in `test/scripts/box/box.js`.

## How to reproduce?

```
$ while npm test; do :; done
```

On my environments (VPS on cloud, my desktop Windows PC),
"npm test" fails within 2-10 times.

## Environment & Settings

* Node.js v12.11.1, v10.16.3, v8.16.2
* HEAD of master branch / @6f6084cb4d5772061aa45703b258634a0db13cee
* Ubuntu 16.04.6 LTS, Windows 10 Pro 64bit (revision 1903)

## Details

When "npm test" runs multiple times, a test case in 'test/scripts/box/box.js` fails occasionally.
This is caused by a potential race condition.

The test case "process() - hash changed" fails
if it starts and finishes within wall-clock timer tick (=1ms).

This can be explained by the implementation of "box.Cache" (`lib/models/cache.js`).
"box.Cache" makes decision about "cache hit/miss" based on "mtime" and "hash" of target file.
"box.Cache" says "cache miss" only when both "mtime" and "hash" are changed.

The test case expects that "box.Cache" says "cache miss" always when "hash" is changed.
Unfortunately "box.Cache" says "cache hit" if "mtime" is not changed.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/pull/3760
