### ISSUE TITLE
updated的功能支持

### ISSUE THREAD

**Issue by feiZhang** [hexojs/hexo#376]
不知道updated目前有什么用。按照字面理解可能是，page应该是根据updated进行排序分页的，
现在是根据date。文章url也是根据date生成的。
就无法实现：
更新了某篇文章之后，此片文章url不变，但是显示的第一页。

**Comment by mingming-killer** [comment]
感谢 3 楼的补丁，终于可以按更新日期排序了。

**Comment by mingming-killer** [comment]
感谢 3 楼的补丁，终于可以按更新日期排序了。

回楼上的，你要照着3楼给的补丁，去改你用的 hexo 的源代码。PS：补丁中最后一处修改不要打上去。

**Comment by zhangolve** [comment]
感谢楼上，大概明白了。

**Comment by cutler** [comment]
那给的链接打不开了，应该怎么改啊？

**Comment by Xuanwo** [comment]
3楼链接打得开啊

**Comment by HJHL** [comment]
update值如何让它自动生成呢？必须得手动修改吗？

**Comment by NoahDragon** [comment]
@HJHL 有些Theme是支持自动生成Updated。比如[hexo-theme-indigo](https://github.com/yscoder/hexo-theme-indigo)
