### ISSUE TITLE
post.path contains "(double quotation marks) will generate wrong URL

### ISSUE THREAD

**Issue by walfud** [hexojs/hexo#3774]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Others

If post file named: _js 里面的 "相等性" 你了解多少_, hexo will generate:

```html
<a class="post-title-link" href="/js/js 里面的 " 相等性"="" 你了解多少="" "="" itemprop="url">
            <span itemprop="name">....</span>
          </a>
```

`href` need to be encoded I think.

**Comment by curbengh** [comment]
May I know where did you get the link? Archive? In a post?

**Comment by curbengh** [comment]
Maybe related to https://github.com/hexojs/hexo/pull/3704, can you try in hexo v4?

**Comment by walfud** [comment]
> May I know where did you get the link?
> 
> Which theme are you using?
> 
> I just tested the filename, it's encoded on archive page, so I need to know the source of the unencoded `<a>`.

![image](https://user-images.githubusercontent.com/9317897/67181838-538e4e80-f410-11e9-901f-41cbd9cf66b3.png)

**Comment by walfud** [comment]
> Maybe related to #3704, can you try in hexo v4?

Hi, v4 works fine. Thank you for helping.
