### ISSUE TITLE
add google analytics and re-generate, but gA code not added to existing post

### ISSUE THREAD

**Issue by lab4quant** [hexojs/hexo#3775]
## Check List

Please check followings before submitting a new issue.

- [*] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [*] I have already searched existing issues and they are not help to me
- [*] I examined error or warning messages and it's difficult to solve
- [*] Node.js is higher than 6.9

## Question
hello, i use hexo to publish a blog, but i forgot to add google analytics
after first deploy, i added google analytics in `_config.yml` and re-generate and deployed, but gA code not added to existing post

my blog repo: https://github.com/quantlibjs/blog, 
deployed via travis-ci: https://travis-ci.com/quantlibjs/blog

how can i add `google analytics` to my post?

thank you!

**Comment by YoshinoriN** [comment]
Hi @lab4quant :)

You have to add an analytics setting to theme's `_config.yml`. 
So, [here](https://github.com/quantlibjs/blog/blob/bdfd712c3de7adc51b185dc8579abb6ca239be15/themes/landscape/_config.yml#L31).

**Comment by lab4quant** [comment]
Hi, @YoshinoriN , thanks for the reply

i added setting after first deploy https://github.com/quantlibjs/blog/blob/master/_config.yml#L95

the problem is, after the setting change, i re-generate and re-deployed my blog, the analytic code not updated to my blog

**Comment by lab4quant** [comment]
Hi, @YoshinoriN , sorry, i updated the wrong config file, now i understand
thank you!
