### ISSUE TITLE
meta_generator tag is not added to <head>

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo#3777]
I was working on hexo-generator-feed and noticed [`autodiscovery.js`](https://github.com/hexojs/hexo-generator-feed/blob/master/lib/autodiscovery.js) doesn't work. When I check on the rendered html, I then noticed `<meta name="generator>` is also missing. It's also missing on Hexo.io.

https://github.com/hexojs/hexo/blob/5d94690d44148dc75d676d0c22d011d0ccc591f7/lib/plugins/filter/after_render/meta_generator.js#L10

I tried,

``` js
data.replace(/<head>(?!<\/head>).+?<\/head>/, (str) => console.log(str))
```

no output.

@SukkaW 
I'm debugging this, need your help as well.

**Comment by SukkaW** [comment]
Is the `<head>` empty? Since the pattern will ignore empty `<head>` tag.

**Comment by curbengh** [comment]
The regex doesn't seem to work over multiple lines,

``` js
const data = `<head>
foobar
</head>`

data.replace(/<head>(?!<\/head>).+?<\/head>/, (str) => console.log(str))
// no output
```

**Comment by curbengh** [comment]
[`s` option](https://stackoverflow.com/a/159139) seems to work.

``` js
const data = `<head>
foobar
</head>`

data.replace(/<head>(?!<\/head>).+?<\/head>/s, (str) => console.log(str))
```
