### ISSUE TITLE
为什么使用markdownpad编写文章时插入图片正常，可是生成的时候部分图片无法显示

### ISSUE THREAD

**Issue by GCPD123** [hexojs/hexo#3787]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by curbengh** [comment]
Can you attach the markdown file (if multiple files are affected, just attach one) and the rendered html source? Then can you specify which picture is displayed fine and which one is not?
