### ISSUE TITLE
分页显示问题

### ISSUE THREAD

**Issue by Gsynf** [hexojs/hexo#3794]
如图，使用的Next主题，分页这里有些问题，分页显示1，2，3，……9，<i class="fa fa angle-right" i>
![Snipaste_2019-10-24_08-56-00](https://user-images.githubusercontent.com/47135298/67444694-c24fef80-f63c-11e9-90a3-c9181a54717b.jpg)

**Comment by Gsynf** [comment]
换用其他主题测试，也都有问题，应该是hexo本身的问题

**Comment by jerryc127** [comment]
4.0 更新说明已经说了啊
![image](https://user-images.githubusercontent.com/16351105/67489071-80a65f80-f6a3-11e9-9666-011938c8323a.png)

自己修改 类似这样
![image](https://user-images.githubusercontent.com/16351105/67489108-9156d580-f6a3-11e9-96c3-542330ca7b53.png)

**Comment by Gsynf** [comment]
@jerryc127 请问这个在哪里加啊？我用的是Next主题，找到了类似的pagination文件，但是修改后hexo g报错。

**Comment by jerryc127** [comment]
@Gsynf  https://github.com/theme-next/hexo-theme-next/blob/master/layout/_partials/pagination.swig

看了下 next最新的已經加上了

**Comment by Gsynf** [comment]
@jerryc127 嗯呢，我也找到了

**Comment by stevenjoezhang** [comment]
另见 https://github.com/hexojs/hexo/issues/3729
