### ISSUE TITLE
Cannot send response after hexo.source.process()

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [hexojs/hexo#3814]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Node.js is higher than 6.9

## Question
I'm trying to write publish function for new hexo admin. The task should be simple:
1. Move the file from `_drafts` into `_posts`
2. Let hexo process the file
3. Return the new post id.

Currenly I'm stuck at step 2. 
When I to run `res.success( )` after `hexo.source.process( )`, I can see console logs, everything is ok (the new file is found, etc), except for the response, instead of my response, hexo returns  `Cannot POST /bridge-api/publish/`. 

** bridge-api is the route for my admin panel.

![image](https://user-images.githubusercontent.com/11393457/67638505-1aa91a80-f8e5-11e9-85ee-5ec9b1232abe.png)

This is my code, I added comments on when `res.success( )` works and when it fails.
```js
	const Post = hexo.model("Post");
	const SOURCE_DIR = hexo.source_dir;
	const POSTS_DIR = SOURCE_DIR + "_posts";
	const DRAFTS_DIR = SOURCE_DIR + "_drafts";

	router.use("publish/", "POST", (req, res) => {
		const oldPath = req.body.path;
		const fileName = oldPath.split(DRAFTS_DIR)[1];
		const newPath = path.join(POSTS_DIR, fileName);
		try {
			fs.renameSync(oldPath, newPath);
                        //res.success("This works!");
			hexo.source.process([newPath]).then(() => {
                               //res.success("This wll return 404!");
				const allPosts = Post.toArray();
				const post = allPosts.filter(post => post.source.includes(fileName));
                                console.log("Found: ", post); // Shows the correct post
				if (post.length !== 1) {
					res.error(500, "Sorry, I can't find the new post id.");
				} else {
					res.success(post);
				}
			});
		} catch (error) {
			res.error(500, "Sorry, something went wrong.", error);
		}
	});
```

**Comment by dailyrandomphoto** [comment]
Maybe you missed `return`.
try 
```diff
-			hexo.source.process([newPath]).then(() => {
+			return hexo.source.process([newPath]).then(() => {
```

**Comment by DeepSpaceHarbor** [comment]
@dailyrandomphoto  I tried, but that didn't help. I'm still getting the same result.

**Comment by seaoak** [comment]
Could you make sure whether your "router" supports asynchronous handlers.
Your handler is "asynchronous" because `hexo.source.process()` returns a Promise.
If your "router" expects "synchronous" handler only,
it will say "404 NOT FOUND" because your handler returns `undefined` without calling any callback.

BTW, `try...catch` statement will not work as you expect.
It cannot handle exceptions inside a Promise.
In that case, `Promise.prototype.catch()` will be useful as follows:

```js
    router.use("publish/", "POST", (req, res) => {
        const oldPath = req.body.path;
        const fileName = oldPath.split(DRAFTS_DIR)[1];
        const newPath = path.join(POSTS_DIR, fileName);
        try {
            fs.renameSync(oldPath, newPath);
            //res.success("This works!");
            hexo.source.process([newPath]).then(() => {
                //res.success("This wll return 404!");
                const allPosts = Post.toArray();
                const post = allPosts.filter(post => post.source.includes(fileName));
                console.log("Found: ", post); // Shows the correct post
                if (post.length !== 1) {
                    res.error(500, "Sorry, I can't find the new post id.");
                } else {
                    res.success(post);
                }
            }).catch(error => {
                res.error(500, "something wrong", error);
            });
        } catch (error) {
            res.error(500, "Sorry, something went wrong.", error);
        }
    });
```

**Comment by DeepSpaceHarbor** [comment]
After further investigation, looks like this is problem within my code.
Thank you all for the help, I'll close the issue since, the problem is on my side.
