### ISSUE TITLE
404问题

### ISSUE THREAD

**Issue by pidada** [hexojs/hexo#3816]
- 功能都是OK，除了一点
- 点击“home”或者tag等几个标签总是报错404，而且URL地址最后面总是出现
%20，请问是什么情况的

**Comment by mojuchen** [comment]
巧了，我也遇到了

**Comment by pidada** [comment]
你解决了吗？？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 莫居尘 <notifications@github.com&gt;
发送时间: 2019年10月29日 23:09
收件人: hexojs/hexo <hexo@noreply.github.com&gt;
抄送: pidada <756803877@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hexojs/hexo] 404问题 (#3816)




巧了，我也遇到了

**Comment by mojuchen** [comment]
在 next 的 _config.yml 文件里的第 95 行
94:menu:
95:  home: / || home

改为：
95:  home: /|| home

**Comment by pidada** [comment]
tags，categories这几个也是这样改得？？？可以加微信聊吗？756803877



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 莫居尘 <notifications@github.com&gt;
发送时间: 2019年10月29日 23:16
收件人: hexojs/hexo <hexo@noreply.github.com&gt;
抄送: pidada <756803877@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hexojs/hexo] 404问题 (#3816)




在 next 的 _config.yml 文件里的第 95 行
 94:menu:
 95:  home: / || home
 
改为：
 95:  home: /|| home

**Comment by pidada** [comment]
你是什么操作系统？我是苹果的，我之前用window10，不用操作的！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 莫居尘 <notifications@github.com&gt;
发送时间: 2019年10月29日 23:23
收件人: hexojs/hexo <hexo@noreply.github.com&gt;
抄送: pidada <756803877@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hexojs/hexo] 404问题 (#3816)



肯定要改的，试试就知道了嗷。加微信算了哈哈哈哈 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "pidada"<notifications@github.com&amp;gt;;  
 发送时间: 2019年10月29日(星期二) 晚上11:19 
 收件人: "hexojs/hexo"<hexo@noreply.github.com&amp;gt;;  
 抄送: "莫奕基"<552191481@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [hexojs/hexo] 404问题 (#3816) 
 
 
 
 tags，categories这几个也是这样改得？？？可以加微信聊吗？756803877  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: 莫居尘 <notifications@github.com&amp;amp;gt;  
  发送时间: 2019年10月29日 23:16  
  收件人: hexojs/hexo <hexo@noreply.github.com&amp;amp;gt;  
  抄送: pidada <756803877@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt;  
  主题: 回复：[hexojs/hexo] 404问题 (#3816)  
   
   
   
   
  在 next 的 _config.yml 文件里的第 95 行  
   94:menu:  
   95:  home: / || home  
     
  改为：  
   95:  home: /|| home

**Comment by mojuchen** [comment]
我申请了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pidada"<notifications@github.com&gt;; 
发送时间: 2019年10月29日(星期二) 晚上11:37
收件人: "hexojs/hexo"<hexo@noreply.github.com&gt;; 
抄送: "莫奕基"<552191481@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [hexojs/hexo] 404问题 (#3816)



大佬加你啦 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: ruan-l <notifications@github.com&amp;gt; 
 发送时间: 2019年10月29日 23:34 
 收件人: hexojs/hexo <hexo@noreply.github.com&amp;gt; 
 抄送: pidada <756803877@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[hexojs/hexo] 404问题 (#3816) 
 
 
 
 加QQ吧，2759531005  
   
   
   
  ---原始邮件---  
  发件人: "莫居尘"<notifications@github.com&amp;amp;gt;  
  发送时间: 2019年10月29日(星期二) 晚上11:23  
  收件人: "hexojs/hexo"<hexo@noreply.github.com&amp;amp;gt;;  
  抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题: Re: [hexojs/hexo] 404问题 (#3816)  
   
   
  肯定要改的，试试就知道了嗷。加微信算了哈哈哈哈   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "pidada"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2019年10月29日(星期二) 晚上11:19   
   收件人: "hexojs/hexo"<hexo@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "莫奕基"<552191481@qq.com&amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [hexojs/hexo] 404问题 (#3816)   
     
     
     
   tags，categories这几个也是这样改得？？？可以加微信聊吗？756803877    
       
       
       
    发自我的iPhone    
       
       
    ------------------ 原始邮件 ------------------    
    发件人: 莫居尘 <notifications@github.com&amp;amp;amp;amp;gt;    
    发送时间: 2019年10月29日 23:16    
    收件人: hexojs/hexo <hexo@noreply.github.com&amp;amp;amp;amp;gt;    
    抄送: pidada <756803877@qq.com&amp;amp;amp;amp;gt;, Author <author@noreply.github.com&amp;amp;amp;amp;gt;    
    主题: 回复：[hexojs/hexo] 404问题 (#3816)    
       
       
       
       
    在 next 的 _config.yml 文件里的第 95 行    
     94:menu:    
     95:  home: / || home    
         
    改为：    
     95:  home: /|| home

**Comment by yeziyz** [comment]
试过了 不管用啊

**Comment by yeziyz** [comment]
管用了 谢谢

**Comment by Hardendless** [comment]
有用，谢谢了！

**Comment by Zlatanlong** [comment]
![image](https://user-images.githubusercontent.com/27723937/74224978-cccdec00-4cf4-11ea-86ab-0e6d57141c20.png)
这里的url也不对，请问有人知道是哪里错了嘛

**Comment by moreant** [comment]
> 侧边栏里日志的url也不对，会把配置文件中的 || 和后面的archive都加上，请问有人知道是哪里错了嘛

这个仓库早就停止维护了，去用新仓库吧
https://github.com/theme-next/hexo-theme-next

**Comment by liuurick** [comment]
![image](https://user-images.githubusercontent.com/35891330/111055165-094ab900-84ae-11eb-85f6-8f687b2d827d.png)
把空格去掉就行了
