### ISSUE TITLE
请问markdown中html代码是如何识别的

### ISSUE THREAD

**Issue by JsthcitPizifly** [hexojs/hexo#3820]
在我写形如 `<font color =XXXXX>text </font>`这样的句子的时候，他有时候渲染会识别成text标签 有时候会识别成 <font>标签...我有点懵

**Comment by curbengh** [comment]
I briefly glanced through the [spec](https://github.github.com/gfm/#raw-html), as long as the html element is valid, it should be recognized as so.

In your case, not sure if it's typo in your comment, but it should be,

``` html
<font color="#xxxxxx">text</font>
```

`<font>` has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font) in the HTML spec though, perhaps that explains why it's not recognized.
