### ISSUE TITLE
hexo new新建页面，头部自动添加一些信息，没有按照模板创建

### ISSUE THREAD

**Issue by Dorisfeng** [hexojs/hexo#3822]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 6.9

## Environment & Settings

**Node.js & npm version**

```
v10.15.0 & 6.4.1
```

**Comment by Dorisfeng** [comment]
![image](https://user-images.githubusercontent.com/31895359/67836720-4bc55d00-fb28-11e9-82ff-776d7bf432a6.png)
上面是模板，下面是新建的页面
```
<!--
 * @Author: your name
 * @Date: 2019-10-30 15:15:52
 * @LastEditTime: 2019-10-30 15:16:09
 * @LastEditors: your name
 * @Description: In User Settings Edit
 * @FilePath: /blog/source/_posts/前端的网络请求方式.md
 -->
```
这些配置是自动出来的，而且还会报格式出错，删了还会出来，还影响了下面title的显示

**Comment by YoshinoriN** [comment]
Certainly, this is not hexo issue.
I think maybe you are using [this VSCode plugin](https://github.com/OBKoro1/koro1FileHeader).
