### ISSUE TITLE
when i use the hexo d ,Error: EPERM: operation not permitted, mkdir

### ISSUE THREAD

**Issue by WodaQ** [hexojs/hexo#3823]
E:\study\myself\webServer\blog>hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: EPERM: operation not permitted, mkdir 'E:\study\myself\webServer\blog\.deploy_git\css'

before the error throw, 
This command was once used normally.
and I am already in administrator mode

**Comment by seaoak** [comment]
@WodaQ Could you please reproduce with `--debug` option?

```
> hexo d --debug
```
