### ISSUE TITLE
hexo-server issues

### ISSUE THREAD

**Issue by GerhardMes** [hexojs/hexo#3824]
I have made everything mentioned in the Docs. But when typing "hexo server" it seems the command is not known. The terminal tells me Usage: hexo <command> as a help, and that "hexo server" is not understood. 
I already reinstalled the server, but no changes.
any advice?

Thanks Gerhard

**Comment by YoshinoriN** [comment]
Did you execute `hexo init`?
Which directory did you run `hexo server`?

**Comment by curbengh** [comment]
Can you attach the output of `ls` command, in the same folder that you attempted to run "hexo server". Can you also attach the content of "package.json"?
