### ISSUE TITLE
I can't generate after install hexo-deployer-git or npm install hexo(I reset my computer)

### ISSUE THREAD

**Issue by SenaKawasumi** [hexojs/hexo#3828]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
It should generate a lot of files, but it doesn't. Before I run npm install hexo-deployer-git --save and have to run npm install hexo --save everything is ok, but after that happened these things.
![20191104013021](https://user-images.githubusercontent.com/28686083/68089330-b537c980-fea2-11e9-855b-e3f243973ba0.png)

## Actual behavior
And it just generate 0 files.
![20191104012354](https://user-images.githubusercontent.com/28686083/68089321-99ccbe80-fea2-11e9-99c3-354dd9460830.png)

## How to reproduce?

* after install hexo-deployer-git or npm install hexo

## Environment & Settings

**Node.js & npm version**
Node.js 10.16.3 
npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.39.2',
  node: '10.16.3',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.54',
  zlib: '1.2.11' }

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**
hexo: 3.9.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.18362 win32 x64
http_parser: 2.8.0
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a

```
```

**Your package.json `package.json`**
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-autoprefixer": "^1.0.0",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-related-popular-posts": "^2.0.6",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}

```
```

**Comment by stevenjoezhang** [comment]
If nothing has changed, why should Hexo regenerate it?

**Comment by SenaKawasumi** [comment]
> If nothing has changed, why should Hexo regenerate it?

No, I run hexo clean first.

**Comment by curbengh** [comment]
Try hexo 4?

``` diff
-"hexo": "^3.9.0",
+"hexo": "^4.0.0",
```

**Comment by SukkaW** [comment]
@stevenjoezhang 

Hexo usually takes about seconds to load source, not milliseconds.

@curbengh 

See? His `package.json` has `hexo.version: 4.0.0` but `hexo: ^3.9.0` in `dependencies`. It seems that he is trying to downgrade from Hexo 4.0.0 to 3.9.0.

I think it is ok to close this issue now.
