### ISSUE TITLE
Regression in CI benchmark

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo#3833]
Usually cold processing can complete within 25 seconds, lately I noticed it has increased to more than a minute.

I haven't find the cause yet, I did notice the regression in https://github.com/hexojs/hexo/pull/3808 https://github.com/hexojs/hexo/pull/3812 https://github.com/hexojs/hexo/pull/3813

Commit Time (GMT) | Commit | Cold Processing Time<br/>(Node 8)
--- | --- | ---
#3813
27 Oct 14:48 | c8fee535b310528fdc01a7761e5df5edf91f9c8c | 24s
29 Oct 12:26 | 330d88bf3a59a949a94677a81d2dc8619ba78ab5 | 38s
#3808
28 Oct 06:39 | 28949da9412f9ca8e08c91b85a73c1e7cbfc24fc | 23s
02 Nov 03:29 | 48d2c527370800c25c6093be8fd857e70c9c0045 | 40s
#3812 
27 Oct 13:32 | 322251361950463e16c1fbeac6e9bc5c995dbc6e | 23s
28 Oct  05:09 | ab23935be17f7b2bc6bd79488c1a065f164e5398 | 35s

Reverting #3808 and #3813  in #3831, but no difference. Haven't try #3812 yet.

Commit Time (GMT) | Commit | PR | Cold Processing Time<br/>(Node 8)
--- | --- | --- | ---
Latest master
05 Nov 01:32 | 77f3e21c34cec3de72409989c2babea582594f03 | #3829 | 42s
Revert attempt
05 Nov 02:21 | 8a475a845f70151521fae0a3027415642e95c499 | #3831 | 40s

---

I also tried dropping recent commits until 3448a6dccdcc4fcb264514e3ffe8f11060a00d3e, see [revert-lodash](https://github.com/curbengh/hexo/tree/revert-lodash) tree. The processing time did come back to normal 26s ([build log](https://travis-ci.com/curbengh/hexo/jobs/252867495)).

---

Looks like whatwg API is the cause #3812 
I revert #3812 in https://github.com/hexojs/hexo/pull/3834, processing time is 27s ([build log](https://travis-ci.com/hexojs/hexo/jobs/252876628)).

In Node 13, it dropped from [81s](https://travis-ci.com/hexojs/hexo/jobs/252852712) to [27s](https://travis-ci.com/hexojs/hexo/jobs/252876631).

**Comment by SukkaW** [comment]
| | Node.js 8 | Node.js 10 | Node.js 12 | Node.js 13 |
| Current master branch (#3829) | 37s | 33s | 85s | 83s |
| PR #3814 | 27s | 27s | 27s | 26s |
| PR #3815 | 41s | 33s | 85s | 82s |

I have to say, the benchmark result is consistent.

**Comment by SukkaW** [comment]
@curbengh 

I have setup a benchmark on `runkit`: https://runkit.com/sukkaw/5dc278520410ce00133cb012

It seems that whatwg url is definitely slower.

**Comment by curbengh** [comment]
I just had an idea, since `external_link` filter incurs perf cost (regardless of legacy or whatwg), an alternative approach is to implement it under [`hexo-renderer-marked`](https://github.com/hexojs/hexo-renderer-marked/blob/master/lib/renderer.js#L63-L70) and hexo-renderer-markdown-it. This approach is more efficient because it is specific to links, compared to a filter that has to run through every content to look for links.

Having it under renderer means links in post/page can be applied, as long they are in `[]()` markdown syntax. This means a limitation of renderer approach is that raw `<a>` (especially in theme layout) won't be applied. Another way to look at it is that the coverage is between `external_link.field: post` and `external_link.field: site`.

I still think `external_link` filter can be useful (especially the coverage offered by `field: site`), but disable it by default and enable it in renderer instead. Not now, perhaps in the next major version.

I intend to add the feature to hexo-renderer-marked in the coming days. It will be disabled by default.

**Comment by SukkaW** [comment]
@curbengh 

I agree with that idea. We might add this to our Roadmap.

**Comment by curbengh** [comment]
Discussion move to https://github.com/hexojs/hexo/issues/3846.
