### ISSUE TITLE
New post can't be updated to GitHub page

### ISSUE THREAD

**Issue by YuanzhaoChen** [hexojs/hexo#3836]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question

I wrote a new post and it can't be updated to my GitHub pages, it worked perfectly fine when I opened it locally using  "hexo s". I tried to use hexo clean but the problem still exists, how can I solve it ?
Commands I had used for trouble shooting:
`hexo clean`
`hexo g`
`hexo s`
`hexo d`

## Environment & Settings

**Node.js & npm version**

```
Node.js: v12.13.0
npm: 6.12.0
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
{
  "name": "hexo-theme-next",
  "version": "7.5.0",
  "description": "Elegant and powerful theme for Hexo",
  "main": "gulpfile.js",
  "scripts": {
    "test": "gulp"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/theme-next/hexo-theme-next.git"
  },
  "keywords": [
    "hexo",
    "theme",
    "next"
  ],
  "author": "NexT <support@theme-next.org> (https://theme-next.org)",
  "license": "AGPL",
  "bugs": {
    "url": "https://github.com/theme-next/hexo-theme-next/issues"
  },
  "homepage": "https://theme-next.org",
  "devDependencies": {
    "eslint": "^6.5.1",
    "eslint-config-theme-next": "^1.1.3",
    "gulp": "^4.0.2",
    "gulp-eslint": "^6.0.0",
    "gulp-shell": "^0.7.1",
    "js-yaml": "^3.13.1",
    "stylint": "^2.0.0"
  },
  "engines": {
    "node": ">=8.6.0"
  }
}
```

**Comment by suvvm** [comment]
I had the same problem，is GitHub server broken？

**Comment by stevenjoezhang** [comment]
https://www.githubstatus.com/

**Comment by YuanzhaoChen** [comment]
Alright it turns out it's because Github server was down, problem solved.
