### ISSUE TITLE
Feature Request - On click animated gif

### ISSUE THREAD

**Issue by h0ek** [hexojs/hexo#3855]
Would be cool to have a play/stop button for animated gifs.
Here are some examples, maybe something from below can be implemented to hexo.

http://rubentd.com/gifplayer/
https://www.hongkiat.com/blog/on-click-animated-gif/
https://codepen.io/hoanghals/pen/dZrWLZ

thanks

**Comment by SukkaW** [comment]
You can request this feature to the maintainer of your theme. You can also make a hexo-plugin by yourself. It is hard for Hexo to implement any built-in player that requires third-party vendor/libs.
