### ISSUE TITLE
Inconsistent check for Nunjucks disabling flag

### ISSUE THREAD

**Issue by FlyingDR** [hexojs/hexo#3860]
Nunjucks disabling flag check is potentially broken because of inconsistency of logic of passing and checking `disableNunjucks` parameter from renderers.

As of v4.0.0 `disableNunjucks` flag is defined by [checking corresponding flag](https://github.com/hexojs/hexo/blob/9662366f9122192359f15861fe05574365e8465e/lib/hexo/post.js#L248) from renderer that is received through `get()` method. This `get()` method selects between normal and sync stores, but uses normal store by default. However, as can be seen from [renderer registration method](https://github.com/hexojs/hexo/blob/9662366f9122192359f15861fe05574365e8465e/lib/extend/renderer.js#L53), this normal store contains `Promise` and hence provides no access to `disableNunjucks` flag that can be passed from renderer. Such flag will be stored into `storeSync` which contains [original](https://github.com/hexojs/hexo/blob/9662366f9122192359f15861fe05574365e8465e/lib/extend/renderer.js#L50) renderer function.

Correct code for `disableNunjucks` flag checking should use `storeSync`:
```js
const disableNunjucks = ext && ctx.render.renderer.get(ext) && !!ctx.render.renderer.get(ext, true).disableNunjucks;
```
notice second `true` argument for `get()`.

**Comment by curbengh** [comment]
PR welcome

**Comment by noraj** [comment]
By chance could it help with https://github.com/hexojs/hexo/issues/3259 ?

**Comment by curbengh** [comment]
> By chance could it help with #3259 ?

`disableNunjucks` is used in [renderer](https://hexo.io/api/renderer) to disable nunjucks for all the files covered by the renderer.

``` js
hexo.extend.renderer.register('md', 'html', (data, { disableNunjucks: true }) => {
  // ...
});
```

For example this plugin https://github.com/think-in-universe/hexo-stop-tag-plugins disables all nunjucks in markdown files. A side effect is that [tag plugin](https://hexo.io/docs/tag-plugins) `{%` is also not processed, which is not optimal. User should be able to write `{{` in a post regardless it's wrapped in a codeblock or not, without worrying it gets rendered as nunjucks; while at the same time, able to use tag plugin.

**Comment by noraj** [comment]
unstale
