### ISSUE TITLE
How to move hexo blog to new device ?

### ISSUE THREAD

**Issue by adrhmnhkm** [hexojs/hexo#3861]
I have a hexo blog on my old laptop. and now I want to move the configuration to a new laptop. maybe someone can give a guide. thank you :)

**Comment by SukkaW** [comment]
First, delete `node_modules` under your Hexo site directory. Then copy your  Hexo site directory to your new device. Run `npm install hexo-cli -g && npm install` in your site directory on your new device. Then you will be able to use Hexo on your new device.

**Comment by xnotyuki** [comment]
i have a hexo blog on an old computer that i wish to update on another device soon. sorry if this is a redundant question but will i be able to update my blog on both the old and new devices by following these steps?

also by copying it means i can just manually ctrl+C the entire hexo site folder and transfer it to my new device with no issue right?
