### ISSUE TITLE
请问如何将我定义的主题提交到hexo官网

### ISSUE THREAD

**Issue by howardliu-cn** [hexojs/hexo#3872]
请问如何将我定义的主题提交到hexo官网？我定义的主题在 名字叫做 hexo-theme-clean-dark ，在 <https://github.com/howardliu-cn/hexo-theme-clean-dark>，我的个人站点<https://www.howardliu.cn/>正在使用这个主题，期望将其提交到hexo官网，希望能够在 <https://hexo.io/themes/>被搜索到，可以让更多的人找到这个主题，并且使用这个主题。

**Comment by stevenjoezhang** [comment]
在这里发Pull request: https://github.com/hexojs/site

**Comment by howardliu-cn** [comment]
已经提交PR，信息在 <https://github.com/hexojs/site/pull/1221>
