### ISSUE TITLE
 Is it possible to customize the folder directly by `hexo server` ？

### ISSUE THREAD

**Issue by moonlitusun** [hexojs/hexo#3877]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

I have so many posts in hexo blog, and it runs server slowly,  I think it is very cumbersome by using 
`_` prefix. so,  is it possible to customize the folder directly by `hexo server` ,  

```bash
hexo s -f ./travel/landon.md
#
hexo s -d ./travel
```

and it's base on _post dir

**Comment by curbengh** [comment]
I don't think hexo has whitelist-post feature, currently only blacklist (via [`skip_render:`](skip_render))

A workaround I can think of is to use a reverse pattern in `skip_render`.

``` yml
_config.yml
skip_render: "!_posts/travel/**"
```

don't know if it works though.

**Comment by moonlitusun** [comment]
It works well, thank you so much.

**Comment by curbengh** [comment]
I'm actually surprised it works :sweat_smile:
