### ISSUE TITLE
markdown图片url带空格不能显示

### ISSUE THREAD

**Issue by iyezhou** [hexojs/hexo#3879]
老版本可以正常显示，4.0不能显示

**Comment by curbengh** [comment]
Can you show an example link? Can you try replacing the space with `%20`?

``` diff
-![caption](http://example.com/foo bar)
+![caption](http://example.com/foo%20bar)
```

Are you using hexo-renderer-marked?

**Comment by iyezhou** [comment]
I replace space with `%20` can solve this problem, but I must change all md files, Is there any solution that need not modify source md file?
example: http://www.appblog.cn/2019/09/15/Shadowsocks%20+%20Privoxy%20%E6%90%AD%E5%BB%BA%20http%20%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1/

**Comment by iyezhou** [comment]
my package.json
```
"dependencies": {
    "hexo": "^4.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-server": "^1.0.0"
}
```

**Comment by curbengh** [comment]
hexo 4 (specifically hexo-renderer-marked) uses newer version of marked and I believe marked may have dropped supporting space in link. markdown-it (used in hexo-renderer-markdown-it) also doesn't support.

I don't think the markdown standard supports space in link, not even github supports it.

Try writing the following in comment and preview it,

``` md
[test](http://www.appblog.cn/2019/09/15/Shadowsocks +%20Privoxy%20%E6%90%AD%E5%BB%BA%20http%20%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1/)
```

**Comment by iyezhou** [comment]
But my previous version really supports spaces. and my previous source md files have no problem.

my previous version package.json
```
"dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-server": "^0.2.0"
  }
```

**Comment by curbengh** [comment]
Newer marked may have dropped support for space in link, in order to support `title=""` attribute in `<img>` element.

``` md
![Alt](/path/to/img.jpg "image title")
```

becomes

``` html
<img src="/path/to/img.jpg" alt="Alt" title="image title">
```

**Comment by iyezhou** [comment]
I see, thank you very much
