### ISSUE TITLE
Config Exclude is not excluding file types

### ISSUE THREAD

**Issue by krausekai** [hexojs/hexo#3881]
First to rule-out hexo, I made a test folder, installed ``micromatch`` and created a test file, and ran it in the command-line. Worked perfectly.

**Micromatch Example - Working:**

```
const micromatch = require('micromatch');

console.log(micromatch.isMatch("path/a/file.jpg", "**.jpg"));
```

```
const micromatch = require('micromatch');

console.log(micromatch.isMatch("path/a/file.jpg", ["**.jpg"]));
```

**Hexo version:**
4.0.0

**Config Exclude Examples - Not Working:**

```
exclude:
  - "**.jpg"
```

```
exclude:
  - ["**.jpg"]
```

```
exclude: "**.jpg"
```

```
exclude: ["**.jpg"]
```

Then, run ``hexo clean`` and ``hexo -g``.

How come this isn't working in Hexo (using micromatch), but does work in micromatch?

**Comment by seaoak** [comment]
I found that `exclude:` option is no effect for files in "post_asset_folder".

I think this is caused by a bug of `lib/plugins/processor/post.js`.

I will make a patch soon.

**Comment by krausekai** [comment]
That seems to be the case. I am using the "post_asset_folder" option.

Thank you!
