### ISSUE TITLE
如果主题下面有node modules，hexo serve会报错内存溢出

### ISSUE THREAD

**Issue by Shen-Yu** [hexojs/hexo#3885]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
我期望在开发主题的时候能实时预览效果，我的主题里面静态资源用webpack来进行打包

## Actual behavior
当我在主题目录下安装完依赖之后并run dev，回到项目根目录serve，发现报错

## How to reproduce?

* Step1
在主题目录下安装完依赖
* Step2
回到项目根目录serve
* etc...
发现报错

## Environment & Settings

**Node.js & npm version**
10.14.1
6.4.1
```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**
4.0.0
```
```

**Your package.json `package.json`**
    "hexo": "^4.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-server": "^1.0.0"
```
```

**Comment by curbengh** [comment]
May be fixed by https://github.com/hexojs/hexo/pull/3797 (to be released in 4.1.0).

Can you test the master branch?

``` diff
package.json
-"hexo": "^4.0.0",
+"hexo": "hexojs/hexo",
```

**Comment by Shen-Yu** [comment]
Thank you,but it's still not work.

**Comment by curbengh** [comment]
what about the `ignore:` option in _config.yml?

``` yml
ignore:
  - '**/themes/*/node_modules/**'
```

**Comment by curbengh** [comment]
node_modules/ and .git/ in themes/ folder are now always ignored in Hexo 4.1.1+.
https://github.com/hexojs/hexo/pull/3918
