### ISSUE TITLE
The proposal of installing theme through npm

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#3890]
The original discussion is at #2471 

Here is my proposal: 

1. We should not treat `hexo-theme-` prefixed package as a hexo plugin. See @tomap 's commit:  https://github.com/hexojs/hexo/compare/master...tomap:feature/themeAsPackagediff-3d0f701643104f3b0e388b8f6a9a7f3eR38
2. Users are still required to specify their theme's name in `_config.yml`, because...
3. Hexo will read `themes/[name]` directory first, then search `hexo-theme-[name]` directory under `node_modules`. It means the theme under `themes` directory should have higher priority. In this way no extra `theme_from_npm: true` configuration is needed. 
4. `theme_config` in `_config.yml` looks good, but it is better to have a separate theme config. We could introduce `_config.[name].yml`. Currently, `theme_config` has higher priority than `_config.yml` under theme directories. After bring up `_config.[name].yml`, I suggest the `theme_config in _config.yml > _config.[name].yml > _config.yml under theme directories` which will retain highest priority for `theme_config`.
5. ~~Also, we need to fix the issue that some plugins can not read theme config from `theme_config`: https://github.com/hexojs/hexo/issues/2471#issuecomment-557877081~~ 

IMHO, we could easily bring up this feature without any Breaking Changes: the theme structure, current configurations and setup will not be affected. Yes, I mean we can even bring up this feature during Hexo 4.x development.

cc @hexojs/core @jiangtj

**Comment by SukkaW** [comment]
FYI: 
Currently there are more than 50 packages on npm has `hexo-theme-` prefixed: https://www.npmjs.com/search?q=hexo-theme

**Comment by stevenjoezhang** [comment]
> We should not treat hexo-theme- prefixed package as a hexo plugin.

Is there a good way to handle this situation?
Plugin: https://www.npmjs.com/package/hexo-theme-next-anchor
Theme: https://www.npmjs.com/package/hexo-theme-next

**Comment by tomap** [comment]
> > We should not treat hexo-theme- prefixed package as a hexo plugin.
> 
> Is there a good way to handle this situation?
> Plugin: https://www.npmjs.com/package/hexo-theme-next-anchor
> Theme: https://www.npmjs.com/package/hexo-theme-next

We could contact all owners of `hexo-theme-*` on npm.org when they are not themes

The package hexo-theme-next-anchor is indeed a plugin. 
We should suggest the owner to change it's name

For the package hexo-theme-next, it is a theme. so, in this case, no problem

**Comment by tomap** [comment]
@SukkaW I edited your issue to add numbers for each items

for 1. indeed, that is the pre requisite
but in the list of packages on npm, as you mentioned, there are multiple packages prefixed "hexo-theme-*"
I looked at each of them, and I believe that none are plugins, except one:
https://www.npmjs.com/package/hexo-theme-next-anchor
=> not a big deal. we'll contact the owner
And we have to decide is that means waiting for Hexo 5 or a smaller 4.1 could be ok

for 2. ok

for 3. ok, but it will make the code a bit more complex because the theme_dir will be more complex to determine (not a big deal either)

for 4. ok also, but this is a bonus

for 5. this is not really a bonus, because without that, we cannot customize .less (and I believe it is probably the same for .sass

If I have time, I'll start with 3.
(I don't have a lot of time those days, but maybe...)

**Comment by jiangtj** [comment]
`hexo-theme-*` is treated as a theme by default, so this is not a problem, just contact the owner to modify it.
@stevenjoezhang rename `hexo-theme-next-anchor` to `hexo-next-anchor`, maybe better. Or load 
 all `hexo-theme-next-*` plugin manual.
https://github.com/hexojs/hexo/blob/master/lib/hexo/load_plugins.js#L51

**Comment by stevenjoezhang** [comment]
IMHO, distinguishing between a theme and a plugin is not complicated, you just need to determine whether a `layout` directory exists - it is a pity to deprecate some modules for this reason.

cc @1v9

**Comment by paulkre** [comment]
Great proposal! Would love to use this feature.

**Comment by SukkaW** [comment]
> you just need to determine whether a `layout` directory exists - it is a pity to deprecate some modules for this reason.

Another idea is only to exclude `hexo-theme-[name]` from being loaded as a plugin. But it means installing multiple themes will become impossible.

**Comment by tomap** [comment]
> Also, we need to fix the issue that some plugins can not read theme config from theme_config: #2471 (comment)

I just retested the item 5. and it seems to work without my changes. I must have tested wrong :)

**Comment by jiangtj** [comment]
> Another idea is only to exclude `hexo-theme-[config.theme]` from being loaded as a plugin. But it means installing multiple themes will become impossible.

This brings me to another idea. We can configure in the configuration file, which need to be excluded

**Comment by SukkaW** [comment]
@tomap Yeah, `theme_config` is supposed to be included in `Locals.prototype.theme`.

https://github.com/hexojs/hexo/blob/5fba0a08bf1e7eaa81bf9156f6bd1e83b1e500a0/lib/hexo/index.js#L360

@jiangtj It would be more complex for a user to configure it.

> This brings me to another idea. We can configure in the configuration file, which need to be excluded

**Comment by SukkaW** [comment]
https://github.com/hexojs/hexo/issues/2471#issuecomment-557870309

Related progress.

**Comment by SukkaW** [comment]
@tomap We could start by excluding `hexo-theme-${config.theme}` from being loading as a plugin.

**Comment by stevenjoezhang** [comment]
`hexo-theme-landscape` was registered on npm a few years ago: https://www.npmjs.com/package/hexo-theme-landscape
Maybe we need to contact the current package owner or npm support.

**Comment by curbengh** [comment]
Since this is already in progress, I'm unpinning this in favor of https://github.com/hexojs/hexo/issues/4260.

**Comment by SukkaW** [comment]
https://github.com/hexojs/hexo/pull/4120#issuecomment-619574347

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/pull/4154#issuecomment-620342744

**Comment by sergeyzwezdin** [comment]
@SukkaW Maybe it's possible to release npm themes support before of Hexo 5? I'd like to have it without waiting for next release of Hexo.

**Comment by stevenjoezhang** [comment]
I have added https://github.com/hexojs/hexo/pull/4120#issuecomment-619574347 to 5.0.0 roadmap. This Issue can be closed.

**Comment by SukkaW** [comment]
@stevenjoezhang 

https://github.com/hexojs/hexo/pull/4120#issuecomment-619574347

> Is it possible to merge config.theme_config into theme.config after ctx.theme loads?

The `ctx.theme.config` is loaded through `this.theme.process()`:

https://github.com/hexojs/hexo/blob/edef5c2a9c1217aaab02f64397e7e94d2f98e4fa/lib/hexo/index.js#L306-L309

See: https://github.com/hexojs/hexo/blob/master/lib/theme/index.js ,

https://github.com/hexojs/hexo/blob/edef5c2a9c1217aaab02f64397e7e94d2f98e4fa/lib/theme/processors/config.js#L11-L14

That's right before `this._generate()` (Before posts are rendered, before `this.generateLocals()` began to build locals).

**Comment by stevenjoezhang** [comment]
When executing `hexo clean`, `customThemeName` here is always the default value `landscape`

https://github.com/hexojs/hexo/blob/14890743dd00e1a1e7c4bd9c7ef632f609d35a4c/lib/hexo/load_plugins.js#L44-L45

This will cause Hexo to load all themes except landscape as plugins.

See also https://github.com/next-theme/hexo-theme-next/issues/65

CC @hexojs/core

**Comment by SukkaW** [comment]
@stevenjoezhang 

> This will cause Hexo to load all themes except landscape as plugins.

Might be related with https://github.com/hexojs/hexo/pull/4386.

**Comment by stevenjoezhang** [comment]
How about changing the loading logic to ignore all `hexo-theme-*` plugins, not only `hexo-theme-${customThemeName}`?

However this goes back to the plugin name issue discussed in November 2019: https://github.com/hexojs/hexo/issues/3890#issuecomment-559881813

**Comment by jiangtj** [comment]
How about load the plugins in theme's dependencies?

See my theme. I have add those needed dependencies.
https://github.com/jiangtj/hexo-theme-cake/blob/91036aa12be4a577705b990252367a93ea089b18/package.json#L47-L50

These plugins are required, but user muse install them in their blog project

Here is a my solution, but I think it’s best done in hexo, do you think?
https://github.com/jiangtj/hexo-theme-cake/blob/91036aa12be4a577705b990252367a93ea089b18/lib/load.js#L24-L27
https://github.com/jiangtj/hexo-theme-cake/blob/91036aa12be4a577705b990252367a93ea089b18/lib/utils.js#L34-L40

**Comment by SukkaW** [comment]
@jiangtj 

By default `npm i hexo-theme-[theme's name]` should install those `dependencies` and theme could access them.

So what you need is to make the theme loading required hexo's plugin, right?

My thought is to include those plugins inside `dependencies` so the `npm i` will be able to install them as well. We could also introduces a new entry to `package.json`, which will tell hexo plugins to be loaded.

**Comment by jiangtj** [comment]
> So what you need is to make the theme loading required hexo's plugin, right?
> 
> My thought is to include those plugins inside `dependencies` so the `npm i` will be able to install them as well. We could also introduces a new entry to `package.json`, which will tell hexo plugins to be loaded.

Yesh

**Comment by noraj** [comment]
What about these kind of issues : 

- Changing some color variables from a CSS file : https://github.com/hexojs/hexo-theme-landscape/issues/186
- Changing or adding a new lang in `languages/mylang.yml`

Because with a npm module you don't want to change any of `node_modules/theme/` files. So have you an idea for file override other than for `_config.yml` with [Alternate Theme Config](https://hexo.io/docs/configuration#Alternate-Theme-Config).

**Comment by rayfoss** [comment]
> What about these kind of issues :
> 
> * Changing some color variables from a CSS file : [Colors from _config.yml hexo-theme-landscape#186](https://github.com/hexojs/hexo-theme-landscape/issues/186)
> * Changing or adding a new lang in `languages/mylang.yml`
> 
> Because with a npm module you don't want to change any of `node_modules/theme/` files. So have you an idea for file override other than for `_config.yml` with [Alternate Theme Config](https://hexo.io/docs/configuration#Alternate-Theme-Config).

Hindsight is 2020. We could have refused to automatically merge arrays, too late. 

Ideas:
- We could allow changing the merge strategy to "simple". 
- we could add a schema and theme version to the config, which would determine how we migrate it to the latest version in steps.
- we could allow object values on strings to define special behavior like `{ $enabled: false, $value: "cloud" }`

**Comment by tomap** [comment]
Tu change color, you can rely on variables that go from config to css. I did that in my theme with stylus

https://github.com/tomap/hexo-theme-minidyne/blob/9bcd4e4e9b07d14db456978c7d5d12876380a132/source/css/style.styl#L3

Declare a variable with proper name and boom

**Comment by rayfoss** [comment]
@tomap ... check the title... what we're trying to do with Hexo 5 is configure the theme, not modify it. We only have the ability to modify the theme using predefined endpoints, like _confgi.landscape.yml.

**Comment by stevenjoezhang** [comment]
Sorry for the late reply. Modifying the layout and styles with Hexo can be difficult because different themes use different template engines and have different code styles. Hexo provides an injector that allows you to insert HTML code at specific locations, but for more precise customization, the theme needs to provide relevant interfaces. Here are my suggestions: 

1. You can try using the plugin https://github.com/jiangtj/hexo-extend-theme, which allows you to replace any file in the theme.

2. You can fork the theme and use it. In fact, themes like "landscape" are not updated frequently, so you can easily follow the upstream updates. 

I will close this issue because the main problem has been resolved. If you have any new questions, please feel free to open a new issue.
