### ISSUE TITLE
新版样式 markdown样式有问题

### ISSUE THREAD

**Issue by P-P-X** [hexojs/hexo#3900]
![image](https://user-images.githubusercontent.com/51700453/69959664-a5171680-1542-11ea-8070-63d0ed27d081.png)

Markdown code 渲染出来这种

## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by curbengh** [comment]
Can you attach the affected codeblock to pastebin.com?
Can you right click on the problematic part and select "Inspect element", and attach the html source?
Which theme do you use?

**Comment by albertnetymk** [comment]
I believe it's the same problem as https://github.com/hexojs/hexo-util/issues/145, which is fixed in 4.1.1
