### ISSUE TITLE
Some bugs with `hexo d`

### ISSUE THREAD

**Issue by 543877815** [hexojs/hexo#3906]
I found a little bug when I changed the filename of the post (`\source\_post`) from lowercase to uppercase like `test.md` => `TEST.md`. 

Well, everything worked correctly when I ran hexo in the localhost (http://localhost:4000/2019/02/06/test/) and in Github page (http://xxx.github.io/2019/02/06/test/).
Then, I changed the filename from lowercase to uppercase. 
So, in localhost, the URL should be http://localhost:4000/2019/02/06/TEST/, and that's ok
The problem is, I ran `hexo d --g` to update my blog in GitHub page, and I tried to visit the post via http://xxx.github.io/2019/02/06/TEST/, but the page is not found (404). So I checked my repo of the GitHub page, and I found the folder was still "test", which means it was not updated. And I checked my "public" folder in the local, well, the folder was "TEST". 

After that, I changed the `test.md` to `test1.md`, just added some letter, and nothing wrong happened. It is wired. So why `hexo d` wouldn't update the folder name from lowercase to uppercase.

btw, I could still get access to the post via http://xxx.github.io/2019/02/06/test/. But the link from the archives page and root page were all changed to http://xxx.github.io/2019/02/06/TEST/.

**Comment by dailyrandomphoto** [comment]
It's not a bug of Hexo. Git is not case sensitive on Windows and Mac.
If you have renamed your posts, then you can follow this step to rename files or directories which managed by git.
```sh
git mv test test.tmp
git mv test.tmp TEST
```

Refer to:
https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git
