### ISSUE TITLE
 _posts have too much *.md files. can _posts support sub directories and show file in the index page

### ISSUE THREAD

**Issue by believeZJP** [hexojs/hexo#3909]
## Check List

Please check followings before submitting a new issue.

- [ ✔️] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ✔️] I have already searched existing issues and they are not help to me
- [ ✔️] I examined error or warning messages and it's difficult to solve
- [✔️ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ✔️] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
3.8.0
hexo: 3.8.0
hexo-cli: 3.1.0
os: Darwin 18.0.0 darwin x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

**Your package.json `package.json`**

```
```

## Others

_posts have too much *.md files, it is difficult to find a certain *.md file,is  _posts support sub directories and the *.md files in sub directories also show in the index page?

I know now we can use `hexo new page 'newPage'` to create a page.

but we need to visit the newPage by `localhost:4000/newPage`,
and it need to add link to menu otherwise other people can't find the newPage

**Comment by bestony** [comment]
You can organized your file with sub folders,  it will be load in hexo, and path will have the folder name.

just like this.

```bash
➜  source git:(master) ✗ tree
.
└── _posts
    ├── posts
    │   └── posts-abcide.md
    ├── start-from-now.md
    └── worktime.md

2 directories, 3 files
```

with link `http://localhost:4000/2019/12/06/posts/posts-abcide/`

**Comment by dailyrandomphoto** [comment]
Hexo supports sub directories.

You can move post *.md files into sub directories.
e.g.
- before
```
_posts/
  post-1.md
  post-2.md
  post-3.md
```

- after
```
_posts/
  post-1.md
  dir-a/
    post-2.md
  dir-b/
  post-3.md
```
permalink: `/posts/post-2.md` => `/posts/dir-a/post-2.md`

If you want use the original permalinks, you can change `_config.yml` like this.
```diff
_config.yml

- permalink: :category/:title/
+ permalink: :category/:name/
```
Then permalink still is `/posts/post-2.md` .


To add new post with command line, you can use `--path` option.
```sh
hexo new post --path=dir-c/post4.md Title
```

**Comment by believeZJP** [comment]
Thanks a lot!
