### ISSUE TITLE
Question about permalinks

### ISSUE THREAD

**Issue by umncsk** [hexojs/hexo#3914]
Hello.

I have been using Hexo for a while. It's very easy to use and nice, but there are times when you only care about one point.

If I do `hexo clean` when changing the theme or plugin, the link will change if the permalink is set to` id`.

I'm in trouble because the destination of the results displayed in the search changes.

Are you planning to change it to the only value?

**Comment by curbengh** [comment]
Please attach the value of your `permalink:` of `_config.yml`. Does it affect every post? If affect one post only, what is the filename?

**Comment by umncsk** [comment]
Thanks for replying.
Is there no way to make the ID unique?
Or is `clean` unnecessary even if I change the theme?

**Comment by curbengh** [comment]
> Is there no way to make the ID unique?
Not that I'm aware of, ID is always uniquely generated when resetting database

> Or is `clean` unnecessary even if I change the theme?
It's necessary because the database also track theme's content.

**Comment by umncsk** [comment]
I see ...
Is there any way to specify the same `id` as before after` clean`?

**Comment by curbengh** [comment]
I don't think there is an option for that.

One way I can think of is introduce a new variable `:hash` to permalink, which takes a hash of the post's title, so the value persists as long the title stays the same.

**Comment by umncsk** [comment]
Does that mean I need to create a new plugin if I want to set `: hash`?

**Comment by curbengh** [comment]
I don't know if plugin can do that. I'll create a PR for `:hash`. I can't guarantee it can get merged though, :crossed_fingers:

**Comment by umncsk** [comment]
appreciate it.
I will also work on it as much as I can ... !

**Comment by curbengh** [comment]
Have a try https://github.com/hexojs/hexo/pull/3922 :smiley:

**Comment by dailyrandomphoto** [comment]
@umncsk 
https://github.com/rozbo/hexo-abbrlink is a plugin that sets a hash value to the front-matter.
Add plugin to Hexo:
```sh
npm install hexo-abbrlink
```
Modify permalink in _config.yml file:
```yaml
permalink: posts/:abbrlink/
```

And for another choice, 
https://github.com/dailyrandomphoto/hexo-unique-post-path is a plugin that creates new posts with unique auto-generated paths.


```sh
$ hexo new2 "Hello World!"

INFO  Created: ./source/_posts/ck2c0zo1y0001gyyn5c2ma96m.md

$ hexo new2

INFO  Created: ./source/_posts/ck20kqmij0001ieyn4es62xh7.md
```

Even after running `hexo clean` or updating the post title, both keep their unique path. This will avoid 404 errors.

**Comment by dailyrandomphoto** [comment]
@curbengh 
A new variable `:hash` will be useful. It is better if the value persists even if the title changes.
`:id` is really useless and users should avoid using it.

**Comment by curbengh** [comment]
> It is better if the value persists even if the title changes.

hash the date instead?

**Comment by dailyrandomphoto** [comment]
> It is better if the value persists even if the title changes.

Write the hash value into the front-matter will achieve this. (Just like https://github.com/rozbo/hexo-abbrlink does)
it is irrelevant to generating hash values ​​with any algorithm.

**Comment by curbengh** [comment]
I'm wary of writing non-user-created data to the front-matter, need to create a new option (e.g. `permalink_hash:` to use `:hash`).

**Comment by umncsk** [comment]
Hashing the date and time is a good solution. 

I'm glad you guys think seriously :laughing:
