### ISSUE TITLE
For better performance, I need to set meta_generator to be false????

### ISSUE THREAD

**Issue by mystic-cg** [hexojs/hexo#3919]
hexo version: 4.1.0
> Hexo 3.9.0+ inserts the tag automatically; to get the performance benefit, meta_generator: option needs to be disabled,
_config.yml
meta_generator: false

**Comment by SukkaW** [comment]
We recommend to disable `meta_generator` in your `_config.yml` if you have already added `meta_generator()` in your theme layout.

**Comment by mystic-cg** [comment]
Okay, I'll check it. Thanks for your reply.

**Comment by carl0schen** [comment]
My `<head>` output is:
`<meta name="generator" content="Hexo undefined">`

Why can't I get the version?

**Comment by curbengh** [comment]
@carl0schen 

Can you attach your `package.json`?

**Comment by curbengh** [comment]
The implementation is incorrect, I'll fix it up.

**Comment by SukkaW** [comment]
This issue should be fixed by #4070.

Once theme has used `meta_generator()`, the `meta_generator` filter will be automatically disabled.
