### ISSUE TITLE
hexo无法运行

### ISSUE THREAD

**Issue by xfx98** [hexojs/hexo#3933]
hexo命令长时间未响应，输入hexo就卡在那了

**Comment by SukkaW** [comment]
Please describe your issue as much cleared as possible and provide as much information as possible.

**Comment by xfx98** [comment]
win系统的hexo长时间运行不了。。。

**Comment by zuanshijia** [comment]
我遇到了同样的问题，重装系统和换硬件都没用，只能是软件的问题
