### ISSUE TITLE
light主题对于Quote的解析

### ISSUE THREAD

**Issue by hongbinzuo** [hexojs/hexo#394]
我在用sublime text写一段markdown文本后，使用python markdown preview的插件预览，很好看，是左对齐的。但是在hexo部署之后，就变成居中对齐，而且是斜体、字体变大，我不知道是light主题的问题，还是hexo默认解析markdown文本的问题。

能不能在light主题配置quote的样式呢？或者只能自己用HTML写吗？谢谢

hexo的显示结果：
![hexo_light_md_quote_text](https://f.cloud.github.com/assets/1685008/1740182/9e6e8026-63bd-11e3-8537-73ba764cdb5c.PNG)

python markdown preview的显示结果：
![python_md_quote_text](https://f.cloud.github.com/assets/1685008/1740183/9e6feb82-63bd-11e3-8c93-e997fcfef6eb.PNG)

**Comment by yweiquan** [comment]
```
blockquote
      border-left 5px solid #c7c7c7
      font-style normal
      font-family font-serif
      font-size 14px
      padding 1px 0px 10px 20px
      text-align lef
```
