### ISSUE TITLE
关于站内搜索和点击爱心效果突然失效的问题

### ISSUE THREAD

**Issue by Icecream-blue-sky** [hexojs/hexo#3989]
具体问题是我的站内搜索功能突然失效，点击无任何反应，并且报错：Uncaught SyntaxError: Unexpected token '<'; 并且自己插入的脚本也突然失效，报同样的错，具体也在： https://github.com/EYHN/hexo-helper-live2d/issues/154 提出了，那边说不是他们的问题，其实我也不知道到底是谁的问题，原谅我不懂前端，之前用live2d前也出现过类似问题，一脸懵逼。我的博客做过的所有更改都在 https://zoutq.com/2019/12/18/hexo-icarus%E5%8D%9A%E5%AE%A2%E6%9B%B4%E6%94%B9%E8%AE%B0%E5%BD%95/ 写出来了，不知道是不是我的某个操作，导致这个奇怪的bug，希望你们有哪位前端大佬能给个建议，可能这不是hexo本身的问题，但我觉得写这个框架的人都很厉害，来碰碰运气，如果大佬们也无法解决，我会自觉关闭这个issue的，谢谢！！

**Comment by curbengh** [comment]
https://zoutq.com/js/main.js has `<div>` at the end of file.

``` js
...
    var $toc = $('#toc');
    if ($toc.length > 0) {
        var $mask = $('<div>');
        $mask.attr('id', 'toc-mask');

        $('body').append($mask);

        function toggleToc() {
            $toc.toggleClass('is-active');
            $mask.toggleClass('is-active');
        }

        $toc.on('click', toggleToc);
        $mask.on('click', toggleToc);
        $('.navbar-main .catalogue').on('click', toggleToc);
    }
})(jQuery);
</div></div>
```

https://zoutq.com/js/insight.js also have html elements,

``` js
...
    }).on('touchstart', function (e) {
        touch = true;
    }).on('touchmove', function (e) {
        touch = false;
    });
})(jQuery, window.INSIGHT_CONFIG);</integer></string></string></p></span></span></i></header></div></header></section>
```

---

It only happens when you install hexo-helper-live2d? No issue after removing it?

**Comment by Icecream-blue-sky** [comment]
> https://zoutq.com/js/main.js has `<div>` at the end of file.
> 
> ```js
> ...
>     var $toc = $('#toc');
>     if ($toc.length > 0) {
>         var $mask = $('<div>');
>         $mask.attr('id', 'toc-mask');
> 
>         $('body').append($mask);
> 
>         function toggleToc() {
>             $toc.toggleClass('is-active');
>             $mask.toggleClass('is-active');
>         }
> 
>         $toc.on('click', toggleToc);
>         $mask.on('click', toggleToc);
>         $('.navbar-main .catalogue').on('click', toggleToc);
>     }
> })(jQuery);
> </div></div>
> ```
> 
> https://zoutq.com/js/insight.js also have html elements,
> 
> ```js
> ...
>     }).on('touchstart', function (e) {
>         touch = true;
>     }).on('touchmove', function (e) {
>         touch = false;
>     });
> })(jQuery, window.INSIGHT_CONFIG);</integer></string></string></p></span></span></i></header></div></header></section>
> ```
> 
> It only happens when you install hexo-helper-live2d? No issue after removing it?
I remember that it happens after I install hexo-helper-live2d.However, it still happens after I uninstall it.I don't know if my memory was wrong or something files change forever after I install hexo-helper-live2d.And my insight search used to be out of action(before I install live2d...but became well after I re-install hexo).But there are some difference——when I click the search button, it jumps to a blanck page(about blocked).Still, at that time, I also found html elements suddenly appear in insight.js and main.js.All of my changes have been written in https://zoutq.com/2019/12/18/hexo-icarus%E5%8D%9A%E5%AE%A2%E6%9B%B4%E6%94%B9%E8%AE%B0%E5%BD%95/.One of them cause the strange problem.

**Comment by Icecream-blue-sky** [comment]
> https://zoutq.com/js/main.js has `<div>` at the end of file.
> 
> ```js
> ...
>     var $toc = $('#toc');
>     if ($toc.length > 0) {
>         var $mask = $('<div>');
>         $mask.attr('id', 'toc-mask');
> 
>         $('body').append($mask);
> 
>         function toggleToc() {
>             $toc.toggleClass('is-active');
>             $mask.toggleClass('is-active');
>         }
> 
>         $toc.on('click', toggleToc);
>         $mask.on('click', toggleToc);
>         $('.navbar-main .catalogue').on('click', toggleToc);
>     }
> })(jQuery);
> </div></div>
> ```
> 
> https://zoutq.com/js/insight.js also have html elements,
> 
> ```js
> ...
>     }).on('touchstart', function (e) {
>         touch = true;
>     }).on('touchmove', function (e) {
>         touch = false;
>     });
> })(jQuery, window.INSIGHT_CONFIG);</integer></string></string></p></span></span></i></header></div></header></section>
> ```
> 
> It only happens when you install hexo-helper-live2d? No issue after removing it?

My local insight.js and main.js don't have html elements.

**Comment by dailyrandomphoto** [comment]
https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/clicklove.js
syntax error
```js
!function(e,t,a){
...
    function r(){
        for(var e=0;e   // <== syntax error
```

https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/main.js#L90-L91
contains html tag
```js
})(jQuery);
</div></div>
```

https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/insight.js#L239
contains html tag
```js
})(jQuery, window.INSIGHT_CONFIG);</integer></string></string></p></span></span></i></header></div></header></section>
```

**Comment by Icecream-blue-sky** [comment]
> https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/clicklove.js
> syntax error
> 
> ```js
> !function(e,t,a){
> ...
>     function r(){
>         for(var e=0;e   // <== syntax error
> ```
> 
> https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/main.js#L90-L91
> contains html tag
> 
> ```js
> })(jQuery);
> </div></div>
> ```
> 
> https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/insight.js#L239
> contains html tag
> 
> ```js
> })(jQuery, window.INSIGHT_CONFIG);</integer></string></string></p></span></span></i></header></div></header></section>
> ```

My local insight.js and main.js don't contain html elements.

**Comment by Icecream-blue-sky** [comment]
> > https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/clicklove.js
> > syntax error
> > ```js
> > !function(e,t,a){
> > ...
> >     function r(){
> >         for(var e=0;e   // <== syntax error
> > ```
> > 
> > 
> > https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/main.js#L90-L91
> > contains html tag
> > ```js
> > })(jQuery);
> > </div></div>
> > ```
> > 
> > 
> > https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/blob/master/js/insight.js#L239
> > contains html tag
> > ```js
> > })(jQuery, window.INSIGHT_CONFIG);</integer></string></string></p></span></span></i></header></div></header></section>
> > ```
> 
> My local insight.js and main.js don't contain html elements.And my local insight.js is complete.

**Comment by dailyrandomphoto** [comment]
@Icecream-blue-sky check out  https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky check out [Icecream-blue-sky/Icecream-blue-sky.github.io@f6401c8](https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0)

Amazing!How did that happen?I found that my local .deploy_git/js files were different from my local /source/js files.It means my local files are changed unknowly.And my local files and github are out of sync.Now I doubt that my git has some problems or other reason.Is there any simple solution?I want to change the .deploy_git/js directly.But I'm not sure if it will cause new problems.Thank you very much!

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky check out [Icecream-blue-sky/Icecream-blue-sky.github.io@f6401c8](https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0)

I try to change my local source/js/insight.js file(delete some comment codes).However, it only change the content.json.The .deploy_git/js/insight.js doesn't change at all.I used to change my _config.yml of hexo(delete "ignore:") which is recorded at https://zoutq.com/2019/12/18/hexo-icarus%E5%8D%9A%E5%AE%A2%E6%9B%B4%E6%94%B9%E8%AE%B0%E5%BD%95/#more (the 19th change).Is it related to this or not?Forgive me so many questions!

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky check out [Icecream-blue-sky/Icecream-blue-sky.github.io@f6401c8](https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0)

I have tried to change my .deploy_git/js/clicklove.js directly.But nothing even changed on my github even my local .deploy_git/js/clicklove.js after I hexo clean&hexo g -d.I can only wait for your answer.

**Comment by dailyrandomphoto** [comment]
@Icecream-blue-sky 
Perhaps there is a plugin that replaces the contents of these files.
1. Please provide your configuration and build environment information.
Please DO NOT CONTAINS SECRET INFORMATION.

**Your site `_config.yml`** 

```
```

**Your theme `_config.yml`** 

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

2. How about your local files in `public/js/`?
`public/js/insight.js`, `public/js/main.js`, `public/js/clicklove.js` 
Same as the files in `source/js/` or not?

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky
> Perhaps there is a plugin that replaces the contents of these files.
> 
> 1. Please provide your configuration and build environment information.
>    Please DO NOT CONTAINS SECRET INFORMATION.
> 
> **Your site `_config.yml`**
> 
> **Your theme `_config.yml`**
> 
> **Hexo and Plugin version(`npm ls --depth 0`)**
> 
> **Your package.json `package.json`**
> 
> 1. How about your local files in `public/js/`?
>    `public/js/insight.js`, `public/js/main.js`, `public/js/clicklove.js`
>    Same as the files in `source/js/` or not?

1、
my site _config.yml

[site _config.txt](https://github.com/hexojs/hexo/files/3997946/site._config.txt)

my theme _config.yml
[theme _config.txt](https://github.com/hexojs/hexo/files/3997950/theme._config.txt)
my hexo and plugin version
+-- hexo@3.9.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- live2d-widget-model-hijiki@1.0.5
`-- npm-check@5.9.0

my package.json
site:
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "live2d-widget-model-hijiki": "^1.0.5",
    "npm-check": "^5.9.0"
  }
}

theme:
{
  "name": "hexo-theme-icarus",
  "version": "2.6.0",
  "private": true
}


2、The public/js/insight.js, public/js/main.js, public/js/clicklove.js files are different from source/js.

**Comment by stevenjoezhang** [comment]
If you uninstall this plugin: hexo-helper-live2d Is everything OK? Maybe you have found the answer: https://github.com/EYHN/hexo-helper-live2d/issues/154

**Comment by Icecream-blue-sky** [comment]
> If you uninstall this plugin: hexo-helper-live2d Is everything OK? Maybe you have found the answer: [EYHN/hexo-helper-live2d#154](https://github.com/EYHN/hexo-helper-live2d/issues/154)

No，nothing changes.The insight.js and clicklove.js are still out of action.

**Comment by dailyrandomphoto** [comment]
@Icecream-blue-sky 
I think I found the cause of the problem.

https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR36
```diff
                var id = 'code-' + Date.now() + (Math.random() * 1000 | 0);
-                var button = '<a href="javascript:;" class="copy" title="Copy" data-clipboard-target="#' + id + ' .code"><i class="fas fa-copy"></i></a>';
+                var button = '<a href="javascript:;" class="copy" title="Copy" data-clipboard-target="#' + id + ' .code" target="_blank" rel="noopener"><i class="fas fa-copy"></i></a>';
                
```

This change indicates that `js/main.js` has been processed by [`externalLinkFilter`](https://github.com/hexojs/hexo/blob/3.9.0/lib/plugins/filter/after_post_render/external_link.js).
However, only pages and posts will be processed by it.
[`content.json`](https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0#diff-047672827cf5d555327d0363f32ca014) shows that the js files and CSS files have been saved to the page model.

I guess you put js files and CSS files under `source/`.
I tried this, and the problem can be reproduced in my local.

According to your blog, this is the culprit of the problem.
<img width="742" alt="2019122501" src="https://user-images.githubusercontent.com/51783821/71427843-a4177600-26f7-11ea-95ed-710bdac401dd.png">

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky
> I think I found the cause of the problem.
> 
> [Icecream-blue-sky/Icecream-blue-sky.github.io@f6401c8#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR36](https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR36)
> 
> ```diff
>                 var id = 'code-' + Date.now() + (Math.random() * 1000 | 0);
> -                var button = '<a href="javascript:;" class="copy" title="Copy" data-clipboard-target="#' + id + ' .code"><i class="fas fa-copy"></i></a>';
> +                var button = '<a href="javascript:;" class="copy" title="Copy" data-clipboard-target="#' + id + ' .code" target="_blank" rel="noopener"><i class="fas fa-copy"></i></a>';
>                 
> ```
> 
> This change indicates that `js/main.js` has been processed by [`externalLinkFilter`](https://github.com/hexojs/hexo/blob/3.9.0/lib/plugins/filter/after_post_render/external_link.js).
> However, only pages and posts will be processed by it.
> [`content.json`](https://github.com/Icecream-blue-sky/Icecream-blue-sky.github.io/commit/f6401c8cd9790712ad65ce1be9d6a2a2bd81b7b0#diff-047672827cf5d555327d0363f32ca014) shows that the js files and CSS files have been saved to the page model.
> 
> I guess you put js files and CSS files under `source/`.
> I tried this, and the problem can be reproduced in my local.
> 
> According to your blog, this is the culprit of the problem.
> <img alt="2019122501" width="742" src="https://user-images.githubusercontent.com/51783821/71427843-a4177600-26f7-11ea-95ed-710bdac401dd.png">
You are right!!!My problem has been solved.Probably the happiest thing today is this. I have been confused by this question for almost a month.So what I want to say is——you have really saved my life!Thks!!!

**Comment by dailyrandomphoto** [comment]
> You are right!!!My problem has been solved.Probably the happiest thing today is this. I have been confused by this question for almost a month.So what I want to say is——you have really saved my life!Thks!!!

I'm glad that the issue is resolved. Have fun with Hexo.

**Comment by xyhcode** [comment]
I had the same problem but I can't figure out what the problem is at the moment but I just keep on Uncaught SyntaxError: Unexpected token '<'
