### ISSUE TITLE
为什么我部署的hexo到GitHub后，打开网页是404 （yhy.github.io）

### ISSUE THREAD

**Issue by yhybulider** [hexojs/hexo#3998]
![image](https://user-images.githubusercontent.com/48554508/71270279-287e9780-238c-11ea-827a-c34b1267e79a.png)
![image](https://user-images.githubusercontent.com/48554508/71270344-4cda7400-238c-11ea-9638-9790dc889b76.png)

**Comment by yhybulider** [comment]
麻烦各位大佬看看

**Comment by dailyrandomphoto** [comment]
@yhybulider The blog url is https://yhybulider.github.io/yhy.github.io/ 
Not https://yhy.github.io/

**Comment by yhybulider** [comment]
thanks,I forked someone else's blog before. I didn't even notice that

**Comment by yhybulider** [comment]
> @yhybulider The blog url is https://yhybulider.github.io/yhy.github.io/
> Not https://yhy.github.io/

thanks,I forked someone else's blog before. I didn't even notice that
