### ISSUE TITLE
Feature request: support other syntax highlight libraries

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo#4010]
This is a spin out of https://github.com/hexojs/hexo-util/issues/19#issuecomment-539356312.

The idea is to support different libraries other than the current [highlight.js](https://highlightjs.org/), e.g.

- [atom's highlights](https://github.com/atom/highlights)
- [prism](https://prismjs.com/)

A major benefit is that theme dev can use/adapt from much more css. Some library may also be [faster](https://github.com/hexojs/hexo/issues/1036#issuecomment-73735029) than another. https://github.com/hexojs/hexo-util/issues/39 can be addressed by atom and prism.

---

Currently, highlight.js is tightly integrated into hexo, so adding another library is expected not to be straightforward. One possible issue is configuration, which I think should be tackled first.

So, to change library, user can specify `engine` (I will refer both `library` and `engine` interchangeably for the rest of the comment),

``` yml
highlight:
  engine: hljs|atom|prism
```

No problem, but here comes the tricky part, configuring _each_ of them. While each engine may share similar options, I think ideally they should be separated, like so:

``` yml
highlight:
  engine: ...
  hljs:
    gutter: true
  prism: ...
```

`highlight.hljs` is preferred over `highlight.highlight` for clarity. But currently the option is used to address https://github.com/hexojs/hexo-util/issues/19#issuecomment-267040668 using
``` yml
highlight:
  hljs: true
```

Retaining compatibility is possible (like https://github.com/hexojs/hexo/pull/3675), i.e. can check `highlight.hljs` is a boolean or not. If boolean, parse it as `highlight.hljs.classPrefix`.

``` yml
highlight:
  hljs:
    classPrefix: ''|'hljs-'
```

Likewise, the approach could also apply to retain compatibility with the current options:

```
highlight:
  auto_detect:
  line_number:
  tab_replace:
```

However, I suggest not to retain old options forever, they can be dropped in hexo@5 for instance, and permanently move to under `highlight.hljs`.

A side benefit of having hljs-specific option is that users familiar with the engine can use its option naming instead; hexo rename some option which confuse those users. See https://github.com/hexojs/hexo-util/issues/40.

---

Previous suggestion https://github.com/hexojs/hexo/issues/1300

**Comment by SukkaW** [comment]
During https://github.com/hexojs/hexo-util/pull/168, I have noticed PrismJS is mainly designed for working at browser side. Many features likes "highlight specific lines", "The first line number" only work in browser.

So if we are going to bring PrismJS to Hexo, IMHO we should address two options:

1. `browser` mode. In this mode Hexo will produce HTML snippet that will could be processed by `prism.js` & `prism.css` in browser. The full features of PrismJS could be used then, and it will be compatible with all options of current `include_code()` and `code()` helper.
2. `preprocess` mode. In this mode Hexo will produce prism-parsed HTML snippet. Then theme/user only need to add `prism.css`. However, many features will no longer works under `preprocess` mode thus will not be compatible with `include_code()` and `code()` helper.

**Comment by SukkaW** [comment]
`backtick_code` filter is important for Hexo. Hexo has extended the "markdown backticks syntax" by supporting `caption` and many other thing. `backtick_code` filter also enables the possibility of consistent code highlight across `hexo-renderer-marked` & `hexo-renderer-markdown-it`.

---

For PrismJS `browser` mode, `marked.setOptions.highlight` shouldn't be used as well: We already have `backtick_code` filter, and PrismJS in browser could support all the features brought by "Hexo extended markdown backticks syntax"

For PrismJS `preprocess` mode, `backtick_code` filter could be disabled as well, because it is quite "useless" ("Hexo extended markdown backticks syntax" related feature will no longer works). If we then use `marked.setOptions.highlight` to handle them, `hexo-renderer-markdown-it` will have no syntax highlight).

**Comment by SukkaW** [comment]
@hexojs/core @curbengh 

I have transferred this issue to Hexo repo.

**Comment by stevenjoezhang** [comment]
Here is a feature request about adding filter event for backtick code block: #1891
This opens up more possibilities for users & plugin developers

**Comment by SukkaW** [comment]
@stevenjoezhang 

What about bring up an new API `hexo.extend.highlight`? Plugin developer then could provide a function using `lang`, `tab`, `mark `, `code` to output the highlighted code?

**Comment by stevenjoezhang** [comment]
This will be a breaking change. Maybe we need to make prism highlight use the same API? https://github.com/hexojs/hexo/pull/4119

**Comment by SukkaW** [comment]
> This will be a breaking change. Maybe we need to make prism highlight use the same API? #4119

I am considering about it.

I still have no idea about how the API should be designed.
