### ISSUE TITLE
hexo所生成的html中og:url的值都被转码https:&#x2F;&#x2F;...？

### ISSUE THREAD

**Issue by note4** [hexojs/hexo#4012]
## Question

```
<meta property="og:url" content="https:&#x2F;&#x2F;yijile.com&#x2F;index.html">
```

问题站点：https://yijile.com/
好像基于hexo-theme-landscape修改的主题都有出现这样的问题！

Problem site: https://yijile.com/
It seems that the theme modified based on hexo-theme-landscape has such problems!

我想这可能是一个常见问题，所以没有提供更多资料。只是我没有想到合适的关键词去寻找解决问题，包括翻页的箭头符合也被转义了。

I think this may be a common problem, so no more information was provided. It's just that I didn't think of suitable keywords to find a solution to the problem, including the arrow matching of page turning has been escaped.

**Comment by SukkaW** [comment]
It seems that the issue has been solved by @curbengh in https://github.com/hexojs/hexo-util/pull/159 in Hexo 4.2.0.

Please make sure you have updated your Hexo to newest version. The current newest version of Hexo is 4.2.0.

**Comment by SukkaW** [comment]
I have also tested your site on an `Open Graph Check`: https://opengraphcheck.com/result.php?url=https%3A%2F%2Fyijile.com%2F . It seems that there will be no problem even the URL is escaped.

So I will close the issue.
