### ISSUE TITLE
About partial and fragment_cache

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4016]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

what difference of partial and fragment_cache ?

for example:
in layout.ejs
<%- partial(footer.ejs, cache: true) %>

or

in the footer.ejs

use fragment_cache to each items of footer

which is better?

**Comment by curbengh** [comment]
It depends whether you expect the whole footer.ejs to be the same across all pages. If yes, enable cache in partial().

Otherwise, use fragment_cache to cache specific item(s) in footer.ejs.

**Comment by jerryc127** [comment]
it support pug ?
i trying add in my theme.  but the time of generation is noting change.

**Comment by SukkaW** [comment]
@jerryc127 

There are two ways to enable fragment cache.

1. Set 3rd parameter of `partial()` to `true`:

```js
partial(path, {}, { cache: true })
```

2. Use `fragment_cache`:

```js
fragment_cache(cacheId, () => {
  // Should have a return value
  return partial(path)
})
```

**Comment by curbengh** [comment]
> it support pug ?

should work in any template

> i trying add in my theme. but the time of generation is noting change.

I guess it depends how many posts/pages you have.

**Comment by jerryc127** [comment]
thx for help
