### ISSUE TITLE
Is there any way I can render /categories page ?

### ISSUE THREAD

**Issue by gourav** [hexojs/hexo#4018]
Hi. 
I want to create a view like [this](https://dribbble.com/shots/4737383-BigBinary-Blog). Basically idea is to have a dedicated page showing different categories in grid format and mentioning their post count as well. I can maintain a JSON file in a theme I am writing to pull out respective icons for the categories, but I can't seem to figure out the way to create a page that is served when /categories is requested. 

Would this require development of a plugin ?

**Comment by dailyrandomphoto** [comment]
You can follow these steps:
1. `hexo new page categories`
2. add `layout: categories` to the front-matter of just created page. `source/categories/index.md`
3. add a layout file to your theme. e.g. `themes/landscape/layout/categories.ejs`
4. use [`list_categories`](https://hexo.io/docs/helpers#list-categories) helper build your category list. [example](https://github.com/ppoffice/hexo-theme-icarus/blob/d30c6d5fbecbe4e3a0c7d672b4ea54928e6efd29/layout/categories.ejs)
5. use [`transform` option](https://hexo.io/docs/helpers#list-categories) or other hacks to show your icons.
