### ISSUE TITLE
The proposal of new type of extension: Inject

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#4047]
Related issue: https://github.com/hexojs/hexo/issues/3086

It is always hard for themes and plugins to insert third-party library (css, js, etc.) into a Hexo site.

Currently the only option is to used `hexo.extend.filter.register('after_render:html', (str, data)` and `(/<\/body>/gi.test(htmlContent))` or `s.replace(/<\/head>/, htmlContent + '</head>')` to inject custom HTML snippet.

There is already a plugin [hexo-inject](https://github.com/hexojs/hexo-inject). Although we are continuing doing housekeeping job, but the plugin is already be considered as deprecated and can not work with newest version of Hexo. So Hexo could provide a official API for inserting custom HTML element by utilizing `after_render:html` filter.

Here is my proposal:

**Synopsis**

```js
hexo.extend.inject.register(entryPoint, str);

hexo.extend.inject.register(entryPoint, () => {
  // ...
  return str;
});
```

**Entry Point**

- `head_begin`: right after `<head>` (not recommended*)
- `head_end`: right before `</head>`
- `body_begin`: right after `<body>`
- `body_end`: right before `</body>`

*: `head_start` could break SEO. According to [MDN](https://mdn.io/title): 

> Search engines typically display about the first 55–60 characters of a page title. Text beyond that may be lost, so try not to have titles longer than that. If you must use a longer title, make sure the important parts come earlier and that nothing critical is in the part of the title that is likely to be dropped.

**Method**

- `get(entryPoint)`: return an Array contains registered HTML snippet.
- `register(entryPoint, data)`: add HTML snippet to the Array of entry point.
- `list()`: return an Object of stored HTML snippet. The data structure should like this:

```
{
  head_begin: [Set object],
  head_end: [Set object],
  body_start: [Set object],
  body_end: [Set object],
}
```

> `Inject` should store HTML snippet with Set and `get()` should use `Array.from()` to transform Set into Array.

**Implementation**

Create a new extend `inject.js` under `lib/extend/`. `Inject` should be similar to `Migrator`, and `new Inject()` should be added to `hexo.extend`.

Create a new filter under `lib/plugins/filter/after_render/` and `this.extend.inject.get(entryPoint)` will be used.

cc @hexojs/core @xiazeyu

**Comment by jiangtj** [comment]
Here are some of my thoughts
- I care more about performance. In what ways do you consider finding injection points? If regular, maybe this issue #4048 would be better handled in advance
- https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/after_render/meta_generator.js refactor it through this feature
- https://hexo.io/docs/helpers.html#partial partial has more extensibility, so why not consider using it to implement Inject

**Comment by jiangtj** [comment]
If `after_route_render` is added, we can predicate where we need to inject through `locals`.

```js
hexo.extend.filter.register('after_route_render', (data,locals) => {
  if (locals.page.__index) {
    return data.replace('<body>','<body>只有主页才添加')
  }
});
```

like this

```js
class Injector {
  //...
  register(entry, value, predicate = ()=>true) {
    if (!entry) throw new TypeError('entry is required');
    if (typeof value === 'function') value = value();
    this.store[entry].add({ value, predicate });
  }
}
```

```js
  function injector(data, pattern, flag, isBegin = true) {
    return data.replace(pattern, str => {
      if (data.includes(`hexo injector ${flag}`)) return str;
      const arr = _Injector.get(flag)
                    .filter(element => element.predicate(locals))
                    .map(element => element.value);
      //...
    }
  }
```

```js
// Use
hexo.extend.inject.register(entryPoint, str, locals => locals.page.__index);
```

In fact, there is a need to inject only under certain circumstances
https://www.netlifycms.org/docs/add-to-your-site/
![image](https://user-images.githubusercontent.com/15902347/71776835-f64b7780-2fd2-11ea-90ac-5ff84cb00fd8.png)

**Comment by jiangtj** [comment]
In addition, priorities also need to be considered. Whether it is `css` or `js`, there must be a sequence.

**Comment by jiangtj** [comment]
I am thinking about how to implement the solution on NexT with `Inject`

Is `this` in the helper equal to `locals`?

**Comment by SukkaW** [comment]
@jiangtj 

I don't know, maybe not.

However, I am working to bring `is()` helper to `Injector`.

**Comment by jiangtj** [comment]
> Set and Array both support order.

In `java`, `Set` does not support order, it is equivalent to `Map`, key and value are the same.

Array support order, but we cannot control, for example, in plugins A and B, who will be executed first

**Comment by SukkaW** [comment]
> for example, in plugins A and B, who will be executed first

That doesn't matter. All plugins should register their inject separately.
