### ISSUE TITLE
"&laquo;" and "&laquo;" doesn't display correctly.

### ISSUE THREAD

**Issue by JingwangLi** [hexojs/hexo#4053]
I just updated the hexo(4.2.0) of my blog, but I found that "&laquo;" and "&laquo;" doesn't display rightly, just like this:
![image](https://user-images.githubusercontent.com/29228612/71762382-81f8d180-2f09-11ea-8955-c900254d1577.png)
It should be this(hexo version 3.8.0 is correct):
![image](https://user-images.githubusercontent.com/29228612/71762403-b53b6080-2f09-11ea-921e-cbdc7471901e.png)
I also tried the "&lt;", it's right. What's wrong with the version 4.2.0?

**Comment by SukkaW** [comment]
By default, `paginator()` helper will escape input. Please add `{ escape: true }` to disable it.

This Breaking Change is introduced in Hexo 4.0.0, a major version bump.

Related Pull Request: https://github.com/hexojs/hexo/pull/3728

**Comment by JingwangLi** [comment]
> By default, `paginator()` helper will escape input. Please add `{ escape: true }` to disable it.
> 
> This Breaking Change is introduced in Hexo 4.0.0, a major version bump.
> 
> Related Pull Request: #3728

May be you want to say `{ escape: false }`? The default setting is `{ escape: true }`. The problem was solved, thank you.
