### ISSUE TITLE
```代码块中的HTML标签被渲染

### ISSUE THREAD

**Issue by edfus** [hexojs/hexo#4054]
## Check List

Please check followings before submitting a new issue.

- I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- I have already searched existing issues and they are not help  to me
- I examined error or warning messages and it's difficult to solve
- Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- Node.js is higher than 8.6.0

## Expected behavior
![style in typora](https://cdn.jsdelivr.net/gh/edfus/store/others/expected.png)
## Actual behavior
![output in html](https://cdn.jsdelivr.net/gh/edfus/store/others/actual.png)
## How to reproduce?

```md

\```js

dvs
<input />
sd
<script dv>
    sdvsdvsdvdv
dsavs
dsvsdv</script>
af

\```

```

- hexo g -f -d

## Environment & Settings

**Node.js & npm version**

```
node -v
v12.14.0

npm -v
6.13.4

```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- @babel/core@7.7.7
+-- babel-preset-es2015@6.24.1
+-- del@5.1.0
+-- gulp@4.0.2
+-- gulp-babel@8.0.0
+-- gulp-changed@4.0.2
+-- gulp-clean-css@4.2.0
+-- gulp-debug@4.0.0
+-- gulp-htmlclean@2.7.22
+-- gulp-htmlmin@5.0.1
+-- gulp-if@3.0.0
+-- gulp-imagemin@6.2.0
+-- gulp-minify-css@1.2.4
+-- gulp-plumber@1.2.1
+-- gulp-uglify@3.0.2
+-- hexo@4.2.0
+-- hexo-asset-image@1.0.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-permalink-pinyin@1.1.0
+-- hexo-prism-plugin@2.3.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it@4.0.0 (git+https://github.com/hexojs/hexo-renderer-markdown-it.git#5508dc44204b3737d2e49af9b103a1a814b0d282)
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-wordcount@6.0.1
+-- markdown-it-emoji@1.4.0
+-- markdown-it-footnote@3.0.2
+-- markdown-it-sub@1.0.0
+-- markdown-it-sup@1.0.0
`-- markdown-it-task-lists@2.1.1

```

## Others

输出结果如下：

```
<pre class="line-numbers language-language-js"><code class="language-language-js">
dvs
<input>
sd
<script dv="">
    sdvsdvsdvdv
dsavs
dsvsdv</script>
af
<span aria-hidden="true" class="line-numbers-rows"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></span></code></pre>

```

其中的`<` | `>`等并没有被自动转义……

是否是因为更换了markdown渲染引擎为hexo-renderer-markdown-it的原因？

**Comment by curbengh** [comment]
`<` and `>` should be escaped, regardless of hexo-renderer-marked or hexo-renderer-markdown-it.

I tested both plugins, and `<` `>` did get escaped

![Screenshot at 2020-01-10 23-45-26](https://user-images.githubusercontent.com/43627182/72155591-55f6b800-3403-11ea-8ce1-5296ef8037f8.png)

Can you make a preview with `hexo server` to skip gulp?

**Comment by edfus** [comment]
Thanks : )

That cannot produce the expected result... It seems like gulp or not doesn't matter.

I also tried changing the `prism_plugin - mode: \`realtime\``, which just **deleted** all the HTML tags in code blocks.
>
> ```html
>
><pre class="line-numbers  language-language-js"><code class=" language-language-js">
>dvs
>
>sd
>
>    sdvsdvsdvdv
>dsavs
>dsvsdv
>af
>
>```
>

<span aria-hidden="true" class="line-numbers-rows"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></span></code></pre>
 
Using the default highlight plugin doesn't work too.

In addition : I reinstalled all the plugins but still got that frustrating result...

**Comment by SukkaW** [comment]
@edfus It seems that you are using @ele828's `hexo-prism-plugin`. Uninstall it to see if the issue still there.

**Comment by edfus** [comment]
@SukkaW Uninstalling that plugin solves the problem, thanks!
