### ISSUE TITLE
Use `Cache` to determine if filter is enabled

### ISSUE THREAD

**Issue by jiangtj** [hexojs/hexo#4056]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/after_render/meta_generator.js

Currently, the meta_generator filter has performance problems. It is recommended to use a helper, but regular matching will still be used.

Maybe use [Cache](https://github.com/hexojs/hexo-util#cache) is a good solution.

```js
function metaGeneratorHelper() {
  cache.set('meta_generator', true);
  return `<meta name="generator" content="Hexo ${this.env.version}">`;
}
```

```js
function hexoMetaGeneratorInject(data) {
  let flag = cache.get('meta_generator');
  if (flag) return;
  const { config } = this;
  //...
}
```

## Others

#4047 Inject can also do this, if use helpers in the theme, can improve performance.

**Comment by SukkaW** [comment]
I assume what you mean is a global plugins' status manager.

**Comment by SukkaW** [comment]
We could add `this.prop = {}` into `helper`'s `constructor()`, And set `ctx.extend.helper.prop.meta_generator = true` inside `meta_generator()`.

Later in `meta_generator` filter we could read `this.extend.helper.prop.meta_generator` to determine if `meta_generator()` helper is used or not.
