### ISSUE TITLE
问题: 为什么 next 主题要将所有的 keyword 转化为 tag?

### ISSUE THREAD

**Issue by HanleyLee** [hexojs/hexo#4072]
## Check List

Please check followings before submitting a new issue.

- [ x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x ] I have already searched existing issues and they are not help to me
- [x ] I examined error or warning messages and it's difficult to solve
- [x ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x ] Node.js is higher than 8.6.0

## Question

我不理解为什么 next 主题要将所有的`meta`中的`keywords`转化为`tag`

我想对我的网站进行 seo, 在参考了大量资料后我对每个网页的 keywords 进行了设置, 包括站点的 keywords, 结果我在网页元素中的`head`并没有发现`keywords`属性, 反而全部转换为了`tag`属性.

我仔细查看了`hexo/lib/plugins/helper/open_graph.js`这个文件, 我发现这个文件会将所有 keywords 转化为 tag 属性, 如果文章没有设置 keywords 的话就会使用站点的 keywords.

在我搜索资料的时候, 我发现目前网上的人基本上还都是会将 keywords 的设置作为 seo 优化的一个环节, 为什么 hexo 要将 keywords 强制转化为 tag?

我非常不理解, 希望有人能为我解答, 感谢!

**Comment by SukkaW** [comment]
If this issue is related with NexT, you should report to NexT instead.

`article:tag` is introduced in #3805. According to the [documents of open graph protocol](https://ogp.me/#array):

> If a tag can have multiple values, just put multiple versions of the same `<meta>` tag on your page. 

Also, it is clear that `meta[name="keywords"]` tag has no effect on SEO (For Bing it is even causing negative effects). [Here](https://yoast.com/meta-keywords/) is the post from Yoast SEO (One of the most famous WordPress SEO plugin). In this post:

> Because the reality is, that if you’re trying to rank for any term that’s even only a little competitive, meta keywords won’t help. You should write engaging, meaningful content on a technically well-optimized platform and get good links and social engagement. That’s what builds great rankings, meta keywords have nothing to do with it.

If you are very interested in optimizing SEO, you should really focus on creating meaningful content. Because honestly speaking, taking your site as a case, writing articles like `总结` really do no help with SEO.

**Comment by HanleyLee** [comment]
> If this issue is related with NexT, you should report to NexT instead.
> 
> `article:tag` is introduced in #3805. `meta[name="keywords"]` is deprecated in that Pull Request as well. According to the [documents of open graph protocol](https://ogp.me/#array):
> 
> > If a tag can have multiple values, just put multiple versions of the same `<meta>` tag on your page.
> 
> Also, it is clear that `meta[name="keywords"]` tag has no effect on SEO (For Bing it is even causing negative effects). [Here](https://yoast.com/meta-keywords/) is the post from Yoast SEO (One of the most famous WordPress SEO plugin). In this post:
> 
> > Because the reality is, that if you’re trying to rank for any term that’s even only a little competitive, meta keywords won’t help. You should write engaging, meaningful content on a technically well-optimized platform and get good links and social engagement. That’s what builds great rankings, meta keywords have nothing to do with it.
> 
> If you are very interested in optimizing SEO, you should really focus on creating meaningful content. Because honestly speaking, taking your blog as a case, writing articles like `xxxx 总结` really do no help with SEO.

Thank you so much for your reply, now I understand too much article tech how to seo with keywords is really sucks😂

For me, my blog is also my notes for pretty gramming, so i will not revise the title.
