### ISSUE TITLE
TOC (Table of contents) helper

### ISSUE THREAD

**Issue by tommy351** [hexojs/hexo#408]
## Usage

``` ejs
<%- toc(str, [options]) %>
```
- **str** - Input string
- **options** - Options
  - **class** - Class name
  - **list_number** - Display list number

**Comment by kuanyui** [comment]
Any way to use this like `<!-- toc -->` ? Because I tend to place the TOC at exactly where I want in different article.

I've tried to reuse `tocHelper()`, but cannot find a way to call the function... (Sorry, not familiar with Node.js...):

```js
hexo.extend.filter.register('post', function(data) {
    data.content = data.content.replace(/<!-{2,} *toc *-{2,}>/, hexo.plugins.helper.toc.tocHelper(data.content));
    return data;
});
```

**Comment by wzpan** [comment]
@Kuanyui ,you can only call this helper in your theme template files(.ejs).

**Comment by kuanyui** [comment]
But I don't want to add the TOC at a fix position.

**Comment by wzpan** [comment]
If so, then don't use this helper. There are many other jQuery plugins that are more flexible and suitable for your demand. *e.g.* http://fuelyourcoding.com/scripts/toc/

**Comment by JiantaoFu** [comment]
"<%- toc(page.content, {list_number: true}) %>"  adding extra list number, and i can't remove it by {list_number: false}
![image](https://cloud.githubusercontent.com/assets/12674006/7922064/9695b36e-085e-11e5-8b96-f2f66371bba2.png)

{list_number: true}
![image](https://cloud.githubusercontent.com/assets/12674006/7920862/653aa520-0856-11e5-9937-6a135bc998bb.png)

**Comment by bubkoo** [comment]
@JiantaoFu set `list-style:none` in your css.

**Comment by Arnold-Hu** [comment]
Could toc function provide the depth option? I think this option could make the page more simple and eligant.

**Comment by bennyn** [comment]
@kuanyui have you found an alternative TOC helper? I also want to add a TOC only for specific articles and not in the template for all of my articles.

**Comment by bennycode** [comment]
I saw that the [tocHelper](https://github.com/hexojs/hexo/blob/6.1.0/lib/plugins/helper/toc.js#L5) is registered in the Hexo.js code with `helper.register('toc', require('./toc'));`. Any chance I can reuse this in my own JavaScript code to make use of this helper at other places?
