### ISSUE TITLE
bug? tag plugins 能嵌套使用么?

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4083]
## Check List

Please check followings before submitting a new issue.

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [X] I have already searched existing issues and they are not help to me
- [X] I examined error or warning messages and it's difficult to solve
- [X] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [X] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

tag plugins 能嵌套适用么?
我自己写了2个tag plugins,嵌套使用后导致pug生成乱
使用：
![image](https://user-images.githubusercontent.com/16351105/72531818-3cdf8280-38ad-11ea-9723-6cedf577b405.png)

结果导致
我的网页生成格式出问题
正常是这样
![image](https://user-images.githubusercontent.com/16351105/72531986-8e880d00-38ad-11ea-9d66-325f5c4411e0.png)
 结果使用后变成这样
![image](https://user-images.githubusercontent.com/16351105/72532052-a52e6400-38ad-11ea-8101-2cdb4d4eb3e6.png)

pug里
![image](https://user-images.githubusercontent.com/16351105/72532083-b4adad00-38ad-11ea-944e-033f028d3272.png)

**Comment by stevenjoezhang** [comment]
Of course. Here is an example: https://theme-next.org/docs/tag-plugins/tabs
6 nested tags are rendered correctly.
