### ISSUE TITLE
paginator() helpers lacks of class customization

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo#4084]
## Check List

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Like #4058, [paginator()](https://hexo.io/docs/helpers#paginator) helper needs to be customizable and needs to have customizable classes.

We need options like prevClass, nextClass, spaceClass, allClass, currentClass, etc.

A lot of CSS framework like [Bulma](https://bulma.io/) are working 100% with classes, so not being able to set a class on the generated tags make the use of the helper impossible.
For example with bulma a `<h1>` won't be stylized without a class, it needs `class="title is-1"`, the same apply for all elements.

**Comment by SukkaW** [comment]
I will have a look at the required `pagination` structure for:

- Bulma: https://bulma.io/documentation/components/pagination/
- Bootstrap: https://getbootstrap.com/docs/4.3/components/pagination/
- Spectre.css: https://picturepan2.github.io/spectre/components/pagination.html

**Comment by noraj** [comment]
Maybe Zurb foundation? https://get.foundation/sites/docs/pagination.html

**Comment by stevenjoezhang** [comment]
+1

https://github.com/theme-next/hexo-theme-next/blob/50984669932a2591f55e0a7c83da11b9a1c980b7/layout/_partials/pagination.swig#L5-L6

**Comment by stevenjoezhang** [comment]
Feature added in https://github.com/hexojs/hexo/pull/5001
