### ISSUE TITLE
403 Forbidden appears when the local host accesses the cloud server

### ISSUE THREAD

**Issue by WJ231009014** [hexojs/hexo#4086]
I use nginx on my cloud server, and the local host pushes to the remote repository using git normally. But the following picture appears through domain name access：
![ScreenClip](https://user-images.githubusercontent.com/41817475/72658538-47089a80-39ed-11ea-9f27-ff345edfe2f6.png)
Help me please!

**Comment by LLLLucas** [comment]
同样的问题？解决了吗
