### ISSUE TITLE
404 There isn't a GitHub Pages site here.

### ISSUE THREAD

**Issue by liuyunfz** [hexojs/hexo#4098]
### The following is from a web translation, may have syntax errors please understand:
Hello, I'm having trouble deploying hexo to GitHub, it is working when i run it on local localhost testing.
![img](https://cdn.jsdelivr.net/gh/liuyunfz/liuyunfz.github.io/img/15.png)
But when I submitted it to GitHub, there was a 404 problem with the URL access.
![img](https://cdn.jsdelivr.net/gh/liuyunfz/liuyunfz.github.io/img/16.png)
I've searched the Web for similar questions, but they're all caused by incorrect submissions. For this I proofread my files and found it normal, but still inaccessible.
Description: This issue often occurs in my updates, and every time I submit an update there is a random probability that 404 issues will occur, which I can access when I enable backup re-updates.
Related links: Here's the GitHub address for my blog: https://github.com/liuyunfz/liuyunfz.github.io

Here's my blog (404 errors are currently inaccessible): http://blog.6yfz.cn/

Hope to get an effective solution, if there is information missing, please reply to me below, I see will be immediately added.
Thank you so much.

### 以下为中文原文：
您好，我在将hexo部署到GitHub上遇到了问题，我在本地localhost测试正常运行
![img](https://cdn.jsdelivr.net/gh/liuyunfz/liuyunfz.github.io/img/15.png)
但是当我hexo deploy提交到GitHub上，通过网址访问却出现了404问题
![img](https://cdn.jsdelivr.net/gh/liuyunfz/liuyunfz.github.io/img/16.png)
我曾在网上搜索过类似问题，但他们都是因为错误的提交文件导致的。为此我校对了我的文件，发现正常，但却仍然无法访问。
描述：这个问题经常出现在我的更新中，每次我将更新提交后都有随机的概率可以出现404问题，而当我启用备份重新更新后却可以访问。
具体链接：以下是我博客的GitHub地址：https://github.com/liuyunfz/liuyunfz.github.io

以下是我的博客（目前已经出现404错误无法访问）：http://blog.6yfz.cn/

希望能得到有效的解决方案，如果有信息遗漏，请在下面回复我，我看到后会立即补上。
不胜感激。

**Comment by YoshinoriN** [comment]
Would you please check the followings?

* [Managing a custom domain for your GitHub Pages site](https://help.github.com/cn/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site)
* [About custom domains and GitHub Pages](https://help.github.com/cn/github/working-with-github-pages/about-custom-domains-and-github-pages)

**Comment by liuyunfz** [comment]
> Would you please check the followings?
> 
> * [Managing a custom domain for your GitHub Pages site](https://help.github.com/cn/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site)
> * [About custom domains and GitHub Pages](https://help.github.com/cn/github/working-with-github-pages/about-custom-domains-and-github-pages)

Thank you, I've looked at your content carefully, but I still don't find out what the problem is. Today I'm trying to deploy hexo on another platform and find it working, so I guess it's a GitHub issue.
But I didn't set up extra on GitHub before, so the only possible reason is that the file triggered some of GitHub's rules, or just a BUG. These are my guesses.
谢谢，您的内容我已仔细查阅过，但仍未发现问题所在。今日我尝试在其他平台部署hexo发现可以正常运行，因此我猜测应该是属于GitHub的问题.
不过此前我并未额外的在GitHub上进行设置，所以唯一可能的原因就是文件触发了GitHub的某些规则，或者只是单纯的一个BUG。这些是我的猜想。

**Comment by SukkaW** [comment]
@liuyunfz 

GitHub Pages is using Fastly CDN, and GitHub will trigger cache purge on Fastly after Page is build. Sometimes GitHub will have trouble purging the cache on Fastly, or you just visit the page during Fastly cache purging.

An advice is to after first time deploy GitHub Pages, add your custom domain to GitHub, you could trigger a second deploy to make GitHub Pages build again, which might helps.

**Comment by liuyunfz** [comment]
通过重新创建库并且部署，我解决了这个问题，目前暂时没有出现404问题，所以这个问题的所在并不是在hexo或是nodejs等，而应该出在GitHub的某项服务上，虽然我现在仍未找出问题所在，不过好在他现在解决了，所以我打算关闭这个问题（因为这个问题只是我的个例）

By recreating the library and deploying, I solved this problem, there is no 404 problem, so the problem is not in hexo or nodejs, etc., but should be in a GitHub service, although I still haven't found out the problem, but good now he solves, So I'm going to close this question (because it's just my case)

**Comment by LLLLucas** [comment]
我报错403怎么办呀

**Comment by liuyunfz** [comment]
> 我报错403怎么办呀

403访问拒绝，应该是服务器问题或者CDN，你是部署在GitHub page上的吗？
