### ISSUE TITLE
hexo new title 命令创建文章时候，title包含()、空格、~、等特殊字符时候会替换成 “-” 符号

### ISSUE THREAD

**Issue by coderhaotf** [hexojs/hexo#4104]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
希望通过hexo new title命令创建相应的title
## How to reproduce?
hexo new "文章系列(一)" 
hexo new "文章系列 一 "
hexo new "文章系列 一&*~# "
* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by ahazxm** [comment]
try `hexo new post "your title" -p "your title.md"`

[`-p`, `--path`](https://hexo.io/docs/commands#new): Customize the path of the post.

**Comment by stevenjoezhang** [comment]
`slugize` of `hexo-util` does not allow special characters
https://github.com/hexojs/hexo-util/blob/master/lib/slugize.js
<img width="617" alt="截屏2020-04-02 上午11 16 20" src="https://user-images.githubusercontent.com/16272760/78207147-646ce100-74d3-11ea-90be-50de86a6d9b7.png">
