### ISSUE TITLE
Hexo blog "article title" problem

### ISSUE THREAD

**Issue by Qftm** [hexojs/hexo#4113]
# Hexo new title problem
**Hexo new title 时，title 包含”空格“会自动转换为”-“，希望标题能够兼容空格。**

# blog "article title" problem
**在source/_posts目录里面，手动建立文章（example：“HCTF wp.md”），文章标题包含空格会造成文章生成的index.html里面的<img>标签生成出现很大的Bug，导致markdown文章里面的图片不能正常解析**

**Comment by stevenjoezhang** [comment]
你好，已经有一个相似的 Issue，可以到这里讨论： https://github.com/hexojs/hexo/issues/4104
这个 Issue 先关了。
