### ISSUE TITLE
Why lose my Custom domain on pages when I run hexo deploy?

### ISSUE THREAD

**Issue by lnpu** [hexojs/hexo#4121]
Why github lose my custom domain on pages settings when I run hexo deploy? it often lose custom domain and restore to default xxx.github.io domain, I resave my custom domain every time. How to save it persistently?Thank you.

**Comment by stevenjoezhang** [comment]
Create a `CNAME` file in source file.

**Comment by stevenjoezhang** [comment]
There is a discussion about it https://github.com/hexojs/hexo-deployer-git/issues/87
I'm closing this issue. Please join the discussion there :)
