### ISSUE TITLE
SyntaxError: Invalid regular expression flags

### ISSUE THREAD

**Issue by sdlyfjx** [hexojs/hexo#4123]
FATAL Invalid regular expression flags
`node_modules\hexo\lib\plugins\filter\after_render\meta_generator.js:10`

I upgrade my hexo from 3.8 to 4.2 .
First I find this error when I use NodeJS8.9.0 and check the Issues then I find the resolution:upgrade my nodejs version to 8.17.0 and it worked.
But I need run hexo on TencentCloud Serverless Framework which only have nodejs6.10 and 8.9.0 environment. So I must fixed this problom.

Becouse of node8.9.0 not support the regular flags 's', it only have 'i' 'm' and 'g'.
Then I delete the /s in the RegExp and it worked fine.
So can we fixed this probloms?

Sorry for my bad english.

> 因为腾讯云SCF上只有Node8.9.0的运行环境，Hexo升级4.2后在那个`meta_generator.js`中的正则表达式用了/s的单行匹配模式，但是Node8.9.0不支持这个模式（默认就是单行吧？除非/m启用多行匹配），所以能不能把这个问题修复一下？蟹蟹。

**Comment by stevenjoezhang** [comment]
Both Node.js6 and 8 are outdated: https://nodejs.org/en/about/releases/
This is a serious security issue, and I suggest you send a ticket to Tencent Cloud to point out the problem.

**Comment by sdlyfjx** [comment]
Er......
I understand the NodeJS8 out of date and may have some security issues.
但是现在这个问题不会导致安全问题吧？Node高版本中也会支持Node8.9的正则写法，只不过加入了/s模式来进行单行匹配。即使不写/s的话高版本是不是也默认进行单行匹配？
所以如果官方可以把这个/s去掉，是不是不会影响什么问题？
而且这个组件仅仅是在渲染完后在<head></head>中加入一个Hexo版本号的标签。
功能可以有，但不是必须。但加入了这个功能却导致了低版本的兼容性。

这个正则表达式如果不用/s模式是不是确实会导致安全性问题？这个我还不是特别清楚。还请告知。

**Comment by Himself65** [comment]
hexo will not support < 8 and you can use `@babel/helper-create-regexp-features-plugin` to compatible code

see: https://www.npmjs.com/package/@babel/helper-create-regexp-features-plugin

and this issue should be closed

**Comment by Himself65** [comment]
and single-line mode cannot remove directly, see this example

https://github.com/hexojs/hexo/blob/7f0537f4104375a5e98c6920278afc5a68af5579/test/scripts/filters/meta_generator.js#L61-L73

**Comment by sdlyfjx** [comment]
@Himself65 Thank you for your answer and your pr. Although it has been closed, but it works for me.
Thanks very much.

这个用正则替换在head里加上generator的功能，粗暴一点直接先找到head里面<meta>里面有name="generator"的给去掉，然后直接把</head>替换成<meta xxxx></head>不就好啦？

**Comment by dzf0023** [comment]
so it is fine to delete  's', right
