### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by cloudXA** [hexojs/hexo#4129]
I try this dirctive,and the error above

`$ hexo init blog`

INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
Cloning into 'C:\Project\blog-hexo\blog'...
fatal: unable to access 'https://github.com/hexojs/hexo-starter.git/': Failed 
to connect to 127.0.0.1 port 1080: Connection refused
WARN  git clone failed. Copying data instead
WARN  Failed to install dependencies. Please run 'npm install' manually!

**Comment by SukkaW** [comment]
Please check your proxy status before setting up Hexo.

**Comment by No5972** [comment]
try replacing ```npm``` with ```cnpm``` (NOT TESTED)
```js
const npmCommand = commandExistsSync('yarn') ? 'yarn' : 'npm';
```

```js
const npmCommand = commandExistsSync('yarn') ? 'yarn' : 'cnpm';
```
file is located in ```node_modules\hexo-cli\lib\console\init.js```
