### ISSUE TITLE
[external_link filter] More robust handling of invalid url

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#4130]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Actual behavior

Facing `TypeError [ERR_INVALID_URL]` for invalid URL. Related: #3988 #4107

## How to reproduce?

Including a invalid URL likes `http://localhost:4000你好世界` in the post.

## How the issue happened

Hexo has mitigated to newer the WHATWG URL API which is much strict than the Legacy URL API. The problem is `marked.js` (which is implemented into `hexo-renderer-marked` as a Hexo plugin) has a `autolink` feature (which will turn any URL-liked things into `<a>` tag) which can not be disabled (@NoahDragon even had an issue at marked.js: https://github.com/markedjs/marked/issues/882).

Hexo's `external_link` filter will extract `href` from `<a>` tag and treat them as valid URL, so any invalid URL included in `<a>` tag will lead to `new URL()` to fail.

## So, the solution?

Well, although the Legacy URL API is considered to be deprecated, however there is no way for the WHATWG URL API to handle an invalid URL. A `try .. catch` could be used, or we could simply revert the changes and only use the Legacy URL API in `isExternalLink()` util.

cc @hexojs/core @curbengh @qinyuanpei

**Comment by imaginezz** [comment]
https://github.com/jerryc127/hexo-theme-butterfly/issues/154#issuecomment-623270356

**Comment by imaginezz** [comment]
https://github.com/hexojs/hexo-util/pull/204
