### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by septs** [hexojs/hexo#4136]
If I can consider migrating to typescript, I can greatly contribute to the code.

**Comment by septs** [comment]
If I approve, I will start with https://github.com/hexojs/hexo-util, modernize.

1. strict typing
2. expose es-module
3. classify

**Comment by SukkaW** [comment]
I prefer start with [`warehouse`](https://github.com/hexojs/warehouse), the database used by Hexo.

We have a plan to [migrate it to TypeScript](https://github.com/hexojs/warehouse/pull/60/files) but it stalled.

**Comment by septs** [comment]
@SukkaW plz create a official issue.
