### ISSUE TITLE
请教关于theme目录下主题自带的_config.yml文件的提交问题

### ISSUE THREAD

**Issue by tinyvane** [hexojs/hexo#4148]
各位，请教一个问题。

我的hexo使用的是一个第三方的theme，添加方式为

git clone https://github.com/ppoffice/hexo-theme-hueman.git themes/hueman

然后我修改了这个hueman目录下的_config.yml.default为_config.yml。

现在的问题是：

我如果在另外一台电脑上，希望git pull这个我修改过的_config.yml，是没有的，因为在我的github的branche里面，themes/hueman目录是别人的项目，里面的文件我无法修改。

请教应该怎么处理这个问题呢？

谢谢

**Comment by zombie110year** [comment]
git subtree

**Comment by tinyvane** [comment]
> git subtree

谢谢你，我去学习下。

**Comment by stevenjoezhang** [comment]
你应该能在  https://github.com/ppoffice/hexo-theme-hueman 这个页面的右上方，看到一个名为「Fork」的按钮。点一下它，就能获得一个你可以修改的副本。
