### ISSUE TITLE
Could I use custom index page?

### ISSUE THREAD

**Issue by jewian** [hexojs/hexo#415]
I would like to use Hexo to generate blog page to the sub-directory xxxx.com/blog/.

In the meanwhile, I would like to create a custom index page xxxx.com/index.html (and maybe other custom pages like xxx.com/photos.html).

And the whole personal  site (custom pages + Hexo generated blog pages) will be hosted by GitHub.

Could I do that?

**Comment by ianpogi5** [comment]
To remove auto generated index.html, uninstall hexo-generator-index
```sh
npm remove hexo-generator-index
```
