### ISSUE TITLE
How to make the config file and the js file to communicate with each other in a custom hexo plugin.

### ISSUE THREAD

**Issue by MoNwastaken** [hexojs/hexo#4163]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
12.13.1
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

I have made a script for hexo and now I'd like to make it into a plugin so it's easier to install and configure. Everything is ready and published on npm as an alpha version but it's not working yet. How do I make the two files communicate with each other so I can type data in the `_config.yml` and use them in the `index.js`?
<br/> This is my first time messing around with this, but I didn't find anything that would help.
<br/> If it helps understanding my problem there is a link for the project: [hexo-css-merge](https://www.npmjs.com/package/hexo-css-merge)

**Comment by jiangtj** [comment]
you can get var in `_config.yml` by `hexo.config`

e.g.
```js
let config = Object.assign({some default config}, hexo.config.your_key)
```

**Comment by MoNwastaken** [comment]
Thank you!
It works like charm
