### ISSUE TITLE
list_archives and list_categories can limit the number of generate?

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4166]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Others

list_archives and list_categories can limit the number of generate?
if the categories all show , it too long.
and then i want limit the top 8 
为了美观，如果太多archives和categories会导致页面很长，
因此我想要限制list_archives和list_categories的生成数量，例如 只显示头8个就好。。

不知道可以怎么做？

**Comment by YoshinoriN** [comment]
@jerryc127 

[list_archives](https://github.com/hexojs/hexo/blob/9b4968875169a62d053cfd57da87e22e7ed98a8b/lib/plugins/helper/list_archives.js#L64) cannot specify a limit.

[list_categories ](https://hexo.io/docs/helpers#list-categories) has the `depth` option.
Is this option to meet your requirements?

Thanks :)

**Comment by stevenjoezhang** [comment]
Instead of using `list_archives` helper, you can do it manually, e.g.
https://github.com/theme-next/hexo-theme-next/blob/master/layout/_macro/post-collapse.swig

**Comment by jerryc127** [comment]
> Instead of using `list_archives` helper, you can do it manually, e.g.
> https://github.com/theme-next/hexo-theme-next/blob/master/layout/_macro/post-collapse.swig

i try to copy the origin list_archives.js to my script folder and modify it. it work
but i dont know how to modify the list_categories js

**Comment by jiangtj** [comment]
@jerryc127 you can modify this line https://github.com/hexojs/hexo/blob/17ee23fa181bcc2c3b47eba5b345762aef1eac36/lib/plugins/helper/list_categories.js#L30

And remove recursive operations
https://github.com/hexojs/hexo/blob/17ee23fa181bcc2c3b47eba5b345762aef1eac36/lib/plugins/helper/list_categories.js#L38-L40
https://github.com/hexojs/hexo/blob/17ee23fa181bcc2c3b47eba5b345762aef1eac36/lib/plugins/helper/list_categories.js#L101-L103

**Comment by jerryc127** [comment]
thx,
i had solve it.
modify the list_categories and list archives
https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/scripts/helpers/aside_archives.js
https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/scripts/helpers/aside_categories.js
