### ISSUE TITLE
Why your documentation sucks and needs a little (major migration consiting of redelpyment) change

### ISSUE THREAD

**Issue by Claywd** [hexojs/hexo#4170]
## Check List

Please check followings before submitting a new issue.

- [x ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ x] I have already searched existing issues and they are not help  to me
- [ x] I examined error or warning messages and it's difficult to solve
- [ x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ x] Node.js is higher than 8.6.0

## Expected behavior
I expect your "getting started" page to start by getting on the main task.... which is *NOT* installing the freaking tool. That's basic (2yrs our of undergrad, the damn npm command should cover your getting started) stuff.... I want getting started to begin using the platforms pages to publish meangingful content for someone who doesn't know markup.code
## Actual behavior

Getting started should include a summary of , at the very list links whcih point to, pages aspiring top explain why and how your platform 

## How to reproduce?

* hit the fucking get started page.....

## Environment & Settings

**Node.js & npm version**

```
lawls
```

**Your site `_config.yml`** (Optional)

```
lawls
```

**Your theme `_config.yml`** (Optional)

```
lawls
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
lawls
```

**Your package.json `package.json`**

```
lawls
```

## Others

To all the shitty (starter and lazy) devs in the world.... this getting started template is to stop idiots from posting before they've done their due diligence. Take pride, work hard, and use all the proceeds to leave a mark worth learning from. (a.k.a pass it on) 

don't craft your art for profits. craft it for art and innovation

I get that many will disregard to comments written here, but employers, future employers, maybe even present employers will see the truth I've both spewed and edited here. Hopefully they all see how I am trying to help this project...

FYI I'm using this framework to standup my first ever blog... which explains the more than opinionated github issue.

**Comment by SukkaW** [comment]
From your **offensive** and **rude** issue I could see you seems to have some better idea about our document. Considering this is a Open Source project which is maintained by voluntary developer,  IMHO if you want to have a better document, just write it yourself and open a pull request. Every contribution is welcome as long as it follows our [contributing guide](https://hexo.io/docs/contributing).
