### ISSUE TITLE
publish not to _posts but still to _drafts

### ISSUE THREAD

**Issue by zhenglinli** [hexojs/hexo#4184]
I installed hexo in Ubuntu 18.04, that's a wired problem:
When I run:
`hexo publish testfile`
It should be moved into `_posts/`
however the article was move to `_draft/` and add an index after the file name.
I have reinstall hexo, and have create an empty fold to run hexo init, didn't work.
 I don't know how to fix it.
![Screenshot from 2020-03-12 14-33-16](https://user-images.githubusercontent.com/20159772/76493820-8643ec80-646e-11ea-998e-b6c4cf7ccf6c.png)

**Comment by zhenglinli** [comment]
I reinstalled hexo again, and it works. Wired problem. Thanks for your excellent project!

**Comment by stevenjoezhang** [comment]
The reinstallation may have fixed the wrong configuration or upgraded dependencies.
I'm closing this issue. Please re-open if it is still outstanding 😊
