### ISSUE TITLE
Mac安装问题connect EINVAL 0.0.1.186:443 - Local (0.0.0.0:0)

### ISSUE THREAD

**Issue by EthanGMAT** [hexojs/hexo#4188]
## Question

Mac安装hexo时出现如下错误，
npm ERR! code EINVAL
npm ERR! errno EINVAL
npm ERR! request to https://registry.npmjs.org/hexo-cli failed, reason: connect EINVAL 0.0.1.186:443 - Local (0.0.0.0:0)
## Environment & Settings
Mac Catalina 10.15.3
**Node.js & npm version**

```
node version v12.16.1
npm version 6.13.4
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

![image](https://user-images.githubusercontent.com/56030518/76696906-87be2080-66cb-11ea-8632-c9214337eddd.png)
我用的时Astrill VPN，安装的时候，无论时打开VPN还是关上VPN，显示都是一样。

**Comment by HoshinoTouko** [comment]
这看起来是你的 Proxy 的问题，并不是 Hexo 的问题。

**Comment by stevenjoezhang** [comment]
此问题与 Hexo 本身无关。请联系你的互联网服务供应商解决。
