### ISSUE TITLE
再执行hexo init初始化时找不到主类

### ISSUE THREAD

**Issue by Ytu-str** [hexojs/hexo#4194]
npm下执行hexo init在最后会出现找不到主类，在git bush下执行是乱码的
cts :
83x <134/161>
Receiuing objects: 100x <161/161). 31.79 KiB I 285.00 KiB/s. done.
Resolving deltas: 100% <74. *?4)。 done.
Submodule ' themes/landscape' (https://github . com/ 'he xojs/hexo -theme- landscape .git
registered for path ' themes/ landsc ape I
Cloning into 'D:代码/git/hexo/blog/themes/ landscape' ...
renote: Enumerating objects: 1063. done. 
renote: Total 1063 <delta 0)。reused 日<delta 0)。pack- reused 1063
Receiuing objects: 100x <1063/1063>. 3.21 MiB : 1.69 MiB/s. done.
Resoluing deltas: 100x <585>585>. done .
Warning: Your console font probably doesn' t support Unicode. If you experience s 
trange characters in the output. cons ider switching to a TrueType font such as C
onsolas !
Submodule path ' thenes/ landscape': checked out ' ?3a23c51f 848?cf cd?c6deec96ccc754
3960d350'
Warning: Your console font probably doesn't support Unicode. If you experience s
trange characters in the output, consider switching to a TrueType font such as C
onsolas !
INFO Install dependenc ies
错误:找不到或无法加载主类install
INF0 Start blogging with Hexo!
D:代码\git Vhexo>

**Comment by stevenjoezhang** [comment]
The outputs from the shell you use is hard to read. This makes it impossible for others to help you solve the problem.
