### ISSUE TITLE
How to use special characters(like "+") in filename?

### ISSUE THREAD

**Issue by CHN-ChenYi** [hexojs/hexo#4195]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question

When I run the command
```
hexo publish "C++ Note"
```
Hexo tries to find a file named "C Note.md" in the draft folder instead of "C++ Note.md"
How can I solve this problem?

## Environment & Settings

**Node.js & npm version**

```
node.js -v : 13.9.0
npm -v : 6.13.7
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /home/toga-manjaro/Code/blog_ori
├── cheerio@1.0.0-rc.3
├── hexo@4.2.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "cheerio": "^1.0.0-rc.3",
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

```

**Comment by stevenjoezhang** [comment]
`slugize` of `hexo-util` does not allow special characters
https://github.com/hexojs/hexo-util/blob/master/lib/slugize.js
<img width="617" alt="截屏2020-04-02 上午11 16 20" src="https://user-images.githubusercontent.com/16272760/78207147-646ce100-74d3-11ea-90be-50de86a6d9b7.png">

**Comment by CHN-ChenYi** [comment]
> `slugize` of `hexo-util` does not allow special characters
> https://github.com/hexojs/hexo-util/blob/master/lib/slugize.js
> <img alt="截屏2020-04-02 上午11 16 20" width="617" src="https://user-images.githubusercontent.com/16272760/78207147-646ce100-74d3-11ea-90be-50de86a6d9b7.png">
> 
> #4104

Thanks! Then I won't use special characters in the future

**Comment by stevenjoezhang** [comment]
Yes, this is a feature, not a bug. Of course, maybe we can find a better way to handle special characters in file names.
