### ISSUE TITLE
"hexo server" command not found after using custom plugin

### ISSUE THREAD

**Issue by ssoor** [hexojs/hexo#4202]
Hexo-server is now a plugin and enabled by default, but the hexo-server plugin will fail when the user is configured with a custom plugin.

The solution is to add hexo-server to the list of plugins.
```
# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
-hexo-server
-hexo-custom-plugin ...
```

But this situation may not be friendly to novices. Suggestions are given in the documentation.

**Comment by jiangtj** [comment]
> the player

Which player？

**Comment by ssoor** [comment]
> > the player
> 
> Which player？

Sorry, here should be the user

**Comment by stevenjoezhang** [comment]
In newer versions of Hexo, you do not need to specify `plugins:`, Hexo will automatically load the plugins.

**Comment by stevenjoezhang** [comment]
Here is a discussion about it https://github.com/hexojs/site/issues/262
