### ISSUE TITLE
Set up end-to-end tests?

### ISSUE THREAD

**Issue by flaurida** [hexojs/hexo#4203]
Hi there 👋unless I'm mistaken, I didn't find end-to-end tests in `hexo`. I maintain an [open source library](https://github.com/qawolf/qawolf) that creates Playwright/Jest tests and runs them in CI.

Would you like me to set up end-to-end tests on this project? Please let me know 😊

**Comment by SukkaW** [comment]
Hexo has no need for end-to-end test.
