### ISSUE TITLE
Your connection is not private（你的连接不是私密连接）

### ISSUE THREAD

**Issue by Steven-Shixq** [hexojs/hexo#4204]
En: what problem with my GitHub page? What should I do? Thanks.
Zh: 我的博客使用国内的网络上不了了，翻墙的时候可以上，这是什么问题呢，想请教一下大家，谢谢。
google chrome：
![image](https://user-images.githubusercontent.com/37492848/77631149-2594d380-6f87-11ea-8c7a-a09c4a378d30.png)

**Comment by stevenjoezhang** [comment]
https://www.v2ex.com/t/656367#reply115

This issue is irrelevant to Hexo.
