### ISSUE TITLE
Deploy overwrites custom domain setting. I have a CNAME file under \source.

### ISSUE THREAD

**Issue by noodlemaster** [hexojs/hexo#4205]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

Hi, I have been experienced an issue where every time i use hexo deploy, it overwrites the custom domain setting on github page. I have a CNAME.txt file with my domain name under \source. And it does generate a same file under \public. 
<img width="615" alt="Screen Shot 2020-03-26 at 6 10 14 PM" src="https://user-images.githubusercontent.com/38833869/77706002-13338d80-6fb9-11ea-969f-e332b39fde08.png">

**Comment by noodlemaster** [comment]
Or should I write www.mydomain.com in CNAME.txt and put www.mydomian.com in Github setting as well?

**Comment by mystic-cg** [comment]
Yes, you should set both to be the same.

**Comment by stevenjoezhang** [comment]
Hi, There is a discussion about it: https://github.com/hexojs/hexo-deployer-git/issues/87

**Comment by noodlemaster** [comment]
Hi, I have set my domain in CNAME as domain.com so is the custom domain setting on github, bur it still doesn't work...


<img width="713" alt="Screen Shot 2020-03-27 at 9 48 13 AM" src="https://user-images.githubusercontent.com/38833869/77806742-7f77c500-707d-11ea-9a18-538f8bb2058a.png">
<img width="646" alt="Screen Shot 2020-03-27 at 9 47 24 AM" src="https://user-images.githubusercontent.com/38833869/77806752-856da600-707d-11ea-9cd5-a766626603b5.png">
