### ISSUE TITLE
How to get hexo to run on tomcat

### ISSUE THREAD

**Issue by YuppyHub** [hexojs/hexo#4207]
hi, I want the files generated by hexo to run on tomcat. I configured hexo / _config.yml `public_dir`. The homepage can be displayed, but the specific article entered is `404`. How does the file generated by hexo run in tomcat?

**Comment by jiangtj** [comment]
Put the generated files into the webapps directory.

**Comment by YuppyHub** [comment]
> Put the generated files into the webapps directory.

你好， 你是中国人我直接打中文啦~， 生成后的文件应该是 public_dir 目录指向的目录对吗？这个我已经配置了。
我运行 `hexo generate`后有生成相应的文件。生成后启动 webapp 首页是可以访问的，但具体的 `分类`、`归档`、`文章详情` 访问都是 404 呢

**Comment by YuppyHub** [comment]
sorry ，是我操作不当， 现在可以了~ :)

**Comment by xuanyinmu** [comment]
我不太懂，可能是主题的（配置）问题 没有启用估计就这样了
那个 怎么取消这个hexo 的订阅啊 邮件老是发过来 有点烦人




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YuppyHub"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午4:41
收件人:&nbsp;"hexojs/hexo"<hexo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [hexojs/hexo] How to get hexo to run on tomcat (#4207)





  
Put the generated files into the webapps directory.
  
你好， 你是中国人我直接打中文啦~， 生成后的文件应该是 public_dir 目录指向的目录对吗？这个我已经配置了。
 我运行 hexo generate后有生成相应的文件。生成后启动 webapp 首页是可以访问的，但具体的 分类、归档、文章详情 访问都是 404 呢
