### ISSUE TITLE
Is there a tool for recovering an entire html5 website back to hexo markdown sources?

### ISSUE THREAD

**Issue by jiapei100** [hexojs/hexo#4219]
Hi,

I happened to have lost my hexo markdown sources the other day. I just wonder if there is a way to recover **all hexo markdown sources** from the entire html5 website?
My website is able to be obtained at [https://github.com/LongerVision/longervision.github.io](https://github.com/LongerVision/longervision.github.io) .

**Comment by SukkaW** [comment]
I am afraid not.

If you have `RSS` for your website, you might be able to use [hexo-migrator-rss](https://github.com/hexojs/hexo-migrator-rss) to get your post back.

But if you only have HTML presented, there might be no other way but migrate it manually.
