### ISSUE TITLE
使用html标签的时候换行会被认为是换行

### ISSUE THREAD

**Issue by laoyang945** [hexojs/hexo#422]
比如写一个简单的表格
如果html标签之间有换行的话，hexo会先去处理这些换行，然后再处理html标签的内容，这会导致很大的一个空白。不知道算是bug还是系统无法避免的东西。解决的方式是把html全部放在一行就行

**Comment by CKJOKER** [comment]
the bug is still remained.

**Comment by leesei** [comment]
Ref #1388
