### ISSUE TITLE
parsing code error in  backticks

### ISSUE THREAD

**Issue by xxxxnnxxxx** [hexojs/hexo#4220]
```{{7*7}}``` ---> 49
`{{7*7}}` ---> 49

this like a template injection
![hexo_code](https://user-images.githubusercontent.com/12854812/78468138-3f80a400-7747-11ea-89f6-d6e2e3a11f7f.png)
![hexo_display](https://user-images.githubusercontent.com/12854812/78468140-44455800-7747-11ea-8131-a8b5b1d0def4.png)
![hexo-version](https://user-images.githubusercontent.com/12854812/78468172-a8681c00-7747-11ea-9630-fc5eb4ae500b.png)

**Comment by SukkaW** [comment]
@stevenjoezhang @seaoak 

It seems that the swig tag inside backtick code filter is not properly escaped. Should we bring up a new filter to fix this?

**Comment by stevenjoezhang** [comment]
I think it is necessary to discuss this issue. Here's another one about backtick code filter

https://github.com/hexojs/hexo/issues/4190

**Comment by seaoak** [comment]
I'm trying to make a small patch for this issue (and the issue #4190).

https://github.com/hexojs/hexo/pull/4229

@SukkaW @stevenjoezhang 
Could you taste it?
