### ISSUE TITLE
Support for sending Webmentions

### ISSUE THREAD

**Issue by muety** [hexojs/hexo#4223]
## Check List

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

I'd like to have Hexo support the [Webmention](https://www.w3.org/TR/webmention/) W3C recommendation. Hexo, as a publishing software, might parse all hyperlinks of a newly created blog post right after its publication and then attempt to trigger Webmention requests for each of them. Ultimately, Webmention support would be a step towards a more decentralized and open web. 

There was already a [similar feature request](https://github.com/gohugoio/hugo/issues/4313) for Hugo. Maybe this feature wouldn't be part of Hexo's core, but rather be realized as a plugin. If so, please let me know and close the issue. Just wanted to initially bring up the topic and maybe have it gain some attention.

**Comment by SukkaW** [comment]
This should be done by a hexo's plugin instead of hexo itself.
