### ISSUE TITLE
How to check/configure hexo version?

### ISSUE THREAD

**Issue by jiapei100** [hexojs/hexo#4225]
I use `npm install -g hexo-cli` to install **hexo**, and after installation, hexo version can be checked as:

```console
➜  ~ hexo version
hexo-cli: 3.1.0
os: Linux 5.3.0-45-generic linux x64
node: 12.16.1
v8: 7.8.279.23-node.31
uv: 1.34.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1
```

However, it seems the most recent hexo is already of version **4.2**?
How can I use the **NEWEST** hexo?

Cheers
Pei

**Comment by stevenjoezhang** [comment]
Hello, 3.1.0 is the version of hexo-cli, not Hexo. The way to check the Hexo version is **in the Issue template, but you deleted this template.**
