### ISSUE TITLE
 I'd like to apply for admission

### ISSUE THREAD

**Issue by kjhuanhao** [hexojs/hexo#4226]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

   Hello! I am a developer in China and have been using hexo for more than a year.

   In the process of using hexo, I found that many users of hexo made a lot of documents for hexo, which is the case in China. But the documentation is messy, and I have a different take on the tutorials, which I originally posted on my hexo blog.

  Over time, many people came to me with questions about hexo, and I answered them. So I had an idea to build a Chinese hexo documentation website. It can help many Chinese users get to know hexo and hexo's extended gameplay in different ways.

  Many people have reported that the documentation on hexo's official website is somewhat difficult to understand in China, or that they often cannot access hexo.io for some reason. Most of them are students, from junior high school to college (which is our student status in China). There's a lot they don't know, and my hexo Chinese site can help them learn a lot about hexo, and I've written the documentation like a textbook, and it's easy to understand.

  At this point, I hope to have my hexo Chinese site displayed on your website. I use a framework like vuepress because it presents the documentation better. On making this project is open source, <https://github.com/kjhuanhao/hexocn>, visit <https://hexocn.cn/>, I will do it, now it's just a demo, I collected a lot of articles about hexo the simple articles (such as the use of the markdown) is no exception.

  I hope to receive your reply.

**Comment by SukkaW** [comment]
First of all, thanks for your contribution toward hexo community.

But since Hexo has its own documents open-sourced at [hexojs/site](https://github.com/hexojs/site), you could contribute directly to our document (which we will be happy for that) instead of maintaining your own version of documents.

Also you should only run a mirror site based on [hexojs/site](https://github.com/hexojs/site). Still, serving hexo's documents with VuePress (which is not hexo) doesn't seem like a good idea, right?

**Comment by kjhuanhao** [comment]
Thank you for your reply. I thought I could use hexojs, and I thought about that at first. I will demo the heoxjs effect to you as soon as possible.
