### ISSUE TITLE
Does not display the title of the article

### ISSUE THREAD

**Issue by scillidan** [hexojs/hexo#4228]
nihao
When I use `hexo 3.8.0` and `icarus 2.3.0` , I can use `title: #` to make the article on the **homepage(important!)** not display the title, like this
![](https://raw.githubusercontent.com/scillidan/scillidan.driver.github/master/icarus_issues_569.png)
But when I use `hexo 4.2.0`, when I do this, the title will be displayed as a `.md` file name.
I don't know if this is a bug or a request. I also submitted an issue in [this place](https://github.com/ppoffice/hexo-theme-icarus/issues/663)
I hope to have this option to can hide the title.

**Comment by stevenjoezhang** [comment]
This issue is caused by https://github.com/hexojs/hexo/pull/3672

See also

https://github.com/hexojs/hexo-theme-unit-test#post
https://github.com/hexojs/hexo-theme-unit-test/blob/master/source/_posts/no-title.md

In addition, `title: #` is not standard usage. Just leave it blank.

**Comment by scillidan** [comment]
thanks, I go watching it.
