### ISSUE TITLE
关于 kind-of 插件安全性报错的问题

### ISSUE THREAD

**Issue by helloearly** [hexojs/hexo#4231]
## Check List

Please check followings before submitting a new issue.

- [x] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
6.10.2
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 F:\Blog
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.3.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it-plus@1.0.4
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-symbols-count-time@0.7.1
`-- hexo-wordcount@6.0.1
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.2.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.7.1",
    "hexo-wordcount": "^6.0.1"
  }
}
```

## Others

当我把**整个** Blog 推送到 GitHub 中时，GitHub 给了我一个安全提示：

![image](https://user-images.githubusercontent.com/44915258/78845452-20ca2800-7a3b-11ea-8295-f464fd62087b.png)

我使用了 `npm update`，可是它仍然存在。

这是它给的冲突说明：

![image](https://user-images.githubusercontent.com/44915258/78845508-49eab880-7a3b-11ea-914a-4fdc55306f49.png)

请问如何解决此问题？非常感谢。

**Comment by SukkaW** [comment]
Please run `npm audit` and paste the output here.

**Comment by helloearly** [comment]
=== npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   hexo

  Path            hexo > swig-templates > optimist > minimist

  More info       https://npmjs.com/advisories/1179


  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   hexo-deployer-git

  Path            hexo-deployer-git > swig-templates > optimist > minimist

  More info       https://npmjs.com/advisories/1179

found 2 low severity vulnerabilities in 710 scanned packages
  2 vulnerabilities require manual review. See the full report for details.

**Comment by stevenjoezhang** [comment]
`swig-templates` 的依赖问题已经（或即将）被解决。请等待 `hexo` 和 `hexo-deployer-git` 发布的下一个版本.

**Comment by helloearly** [comment]
> `swig-templates` 的依赖问题已经（或即将）被解决。请等待 `hexo` 和 `hexo-deployer-git` 发布的下一个版本.

非常感谢！
