### ISSUE TITLE
Images in Page "index" directories don't work like normal post_asset_folder's

### ISSUE THREAD

**Issue by churbis** [hexojs/hexo#4236]
## Expected behavior
post_asset_folder: true creates asset folders for pages that work

## Actual behavior
post_asset_folder: true creates a folder named index in the root directory when you run the $hexo new page <pagename> command (/<pagename>/index) but this folder does not work like the other asset folders.

## How to reproduce?
1. Create a page using the command
2. Put assets in the folder that's created along side of index.md
3. Images are not referenced via markdown ("![]()") or plugin ("{%asset_img%}") as per usual asset_folder behavior

## Environment & Settings

**Node.js & npm version**
Windows 10 64
Node v12.10
NPM 6.10.3

**Comment by jiangtj** [comment]
{% asset  img%} is used to solve the relative path between home and post, but this problem does not exist in page. You can directly use the most common markdown syntax.

**Comment by churbis** [comment]
Thank you, yes that works fine. 

The images can’t be in the index folder created by the command to resolve relatively for markdown syntax to work well. Is there any use for these “index” directories that are created by the command? If they should probably be removed from the page creation command. Their behavior is inconsistent.

**Comment by jiangtj** [comment]
I don't understand what you mean, see this example.

```
├─source
│  ├─example-page
│  │  ├─index.md
│  │  ├─some-pic.png
```

if you want to use those assets in `page`, just common md syntax

```md
![](some-pic.png)
```

**Comment by churbis** [comment]
Your example makes sense, but that's not what hexo is doing for me. The
"hexo new page <page>" command is creating a directory tree like this:

├─source

│  ├─example-page

│  │  ├─index.md

│  │  ├─index

The "index" there next to index.md is a directory it's creating.
Presumably because I turned on asset folders in the config.yml. So
either putting images in source/example-page/index/some-pic.png should
work, or it just shouldn't create that index folder (likely a bug and
the best fix).

**Comment by jiangtj** [comment]
I think that the index directory should not be created.
