### ISSUE TITLE
Pretty Urls

### ISSUE THREAD

**Issue by fiik346** [hexojs/hexo#4237]
Trailing html doesn't work. I want to change the address from site.com/xxx/hello-world/ to site.com/xxx/hello-world.html, but it can't from _config.yml. How to do it?

**Comment by SukkaW** [comment]
Try this:

```yaml
permalink: /xxx/:title.html
```

or this:

```yaml
permalink: /xxx/:name.html # If you want to use file name instead of full path
```

**Comment by fiik346** [comment]
This work. Thanks
