### ISSUE TITLE
hexo next 中的表格无法居中和右对齐 看见了一个回答 但是仍然没有解决 

### ISSUE THREAD

**Issue by qzsking1** [hexojs/hexo#4240]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
|||
| - | - |
| hexo | 哪个版本的 Hexo？ |
| next | 哪个版本的 NexT？ |
| 中的表格无法居中和右对齐 | 请提供截图或者链接？ |
| 看见了一个回答 | 哪个回答？ |
| 但是仍然没有解决 | 你是如何尝试解决的？ |

这很有可能是 Markdown Renderer 的问题。但你的提问没有提供任何有效信息，这个 Issue 先关了。

**Comment by qzsking1** [comment]
![image](https://user-images.githubusercontent.com/59715997/79060272-bec92700-7cb5-11ea-80d0-f4f29c182f20.png)
谢谢 我使用的这个方法解决了问题

**Comment by qzsking1** [comment]
谢谢 解决了
![image](https://user-images.githubusercontent.com/59715997/79088022-e979b500-7d73-11ea-8eec-ffdcd6d3527f.png)
