### ISSUE TITLE
如何在js中调用Hexo提供的变量?

### ISSUE THREAD

**Issue by XuxuGood** [hexojs/hexo#4243]
如何在js中调用Hexo提供的变量?

**Comment by stevenjoezhang** [comment]
如果你指的是在前端js中调用渲染过程中的变量，可以尝试在页面中创建一个`<script>`标签并向全局变量赋值。

**Comment by dhndzwxj** [comment]
> 如果你指的是在前端js中调用渲染过程中的变量，可以尝试在页面中创建一个`<script>`标签并向全局变量赋值。

我想在js中调用主题配置文件`_config.yml`中的变量， 请问代码要怎么写呢？

**Comment by stevenjoezhang** [comment]
类似这样
```
<script>
let theme = '{{ config.theme }}';
</script>
```
具体语法取决于主题使用的模版引擎

**Comment by dhndzwxj** [comment]
主题使用的模板引擎是pug，那么还是您给的代码格式吗？
Xiaojun Wang
13718899506
Department of Economy
Renmin University of China




---- 回复的原邮件 ----
发件人  ***@***.***> 发送日期  2023年2月25日 23:50 收件人  ***@***.***> 抄送人  Junker ***@***.***> ,
 ***@***.***> 主题  Re: [hexojs/hexo] 如何在js中调用Hexo提供的变量? (#4243)  

类似这样
<script>

let theme = '{{ config.theme }}';

</script>

具体语法取决于主题使用的模版引擎
