### ISSUE TITLE
[hexo generate] css link from index.html doesn't work for mac/linux user

### ISSUE THREAD

**Issue by lalaphoon** [hexojs/hexo#4244]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

**Please skip the entire block go to the bottom**
## Expected behavior
hi, I just start using hexo today and my blog is fresh new, it only had hello word post. However when I wanted to run hexo generate, it successfully generate the public folder and db, everything is there. when i clicked index.html, the look of page should be exact the same as how i see when i run hexo server.
## Actual behavior
when i clicked the index.html and tried to see the rendered file locally, my webpage has no style at all - just plain text.
## How to reproduce?

* i'm a mac user, and just follow the configuration until **hexo generate**

## Environment & Settings

**Node.js & npm version**

```
hexo: 4.2.0
hexo-cli: 3.1.0
os: Darwin 18.7.0 darwin x64
node: 12.14.1
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.1
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1
```

## Solution
I know what caused the issue.
This is what I generated on index.html for link to style
```
<link rel="stylesheet"   href="/css/style.css">
```
However, for Linux users it must be ./css/style.css to make it actually work
```
<link rel="stylesheet"   href="./css/style.css">
```

**Comment by stevenjoezhang** [comment]
Hello, please use `http` protocol instead of `file` protocol to visit the website generated by Hexo.
