### ISSUE TITLE
404 page issue with relative_link turned on

### ISSUE THREAD

**Issue by tarunbatra** [hexojs/hexo#4245]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
When `relative_link` is turned on, and we make a request to a non existent page like https://site.com/blog/non-existant-page, it should render 404 page properly like it does when I hit https://site.com/non-existant

## Actual behavior
The page which loads is not proper. Screenshots:
<img width="1280" alt="Screenshot 2020-04-15 at 4 26 50 AM" src="https://user-images.githubusercontent.com/5329230/79281879-58205500-7ed1-11ea-9984-79180148745e.png">
![Screenshot 2020-04-15 at 4 28 14 AM](https://user-images.githubusercontent.com/5329230/79281972-9158c500-7ed1-11ea-8ab7-00467273d5ac.png)
I know this might be a feature and not a bug, but there has to be a way around this even if that's the case.

## How to reproduce?
Go to https://tarunbatra.com/blog/non-existant-page and see the difference.
The expected experience is https://tarunbatra.com/non-existant

## Environment & Settings

**Node.js & npm version**
```
node -v
v8.17.0
npm -v
6.13.4
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
tarunbatra.github.io@0.0.1 /Users/batraji/Personal/tarunbatra.github.io
├── hexo@4.2.0
├── hexo-canonical-link@1.0.2
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-cname3@1.0.1
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-reading-time@1.0.3
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

**Your package.json `package.json`**

```
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.2.0",
    "hexo-canonical-link": "^1.0.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-cname3": "^1.0.1",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-reading-time": "^1.0.3",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  },

```

**Comment by stevenjoezhang** [comment]
The URL of the 404 page might be different each time, thus you need to set `relative_link` to `false`. I think there is no other solution.

**Comment by tarunbatra** [comment]
I need `relative_link` because this site may not be deployed on root always. eg. the same site is deployed on IPFS at https://ipfs.io/ipfs/QmYBHcsR6H8Q8V7vezwz6HKv3GGWDtBmgXRqJnk8J88YSA/.

I understand this might not be an issue many people face but is there a solution for this case?

**Comment by SukkaW** [comment]
Unstale.

**Comment by SukkaW** [comment]
@tarunbatra It appears that your theme handles css/js in-correctly thus causing css & js not loaded properly.

It is not the fault of Hexo, as we already introduces a lot of helper function dealing with relative path. Ask theme's author to utilize those function then.
