### ISSUE TITLE
First time is not rendering links. Second time, no problem.

### ISSUE THREAD

**Issue by angelcervera** [hexojs/hexo#4246]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question
I have this simple markdown:

```
```text
Hello
\```

{% post_link recycled_homemade_cluster 'Recycled homemade cluster' %}

```text
Hello
\```

{% post_link recycled_homemade_cluster 'Recycled homemade cluster' %}
```

And this is what it is rendering.

![image](https://user-images.githubusercontent.com/293444/79324294-4a85c200-7f07-11ea-8872-909c5089b8a2.png)

Why the second time is rendering the link correctly but it is not in the first time?

## Environment & Settings

**Node.js & npm version**

```
$ npm --version
6.13.4
$ node --version
v12.16.1

```

**Your site `_config.yml`** (Optional)

```
markdown:
  anchors:
    permalink: false
  render:
    html: true
    breaks: false
    typographer: false
```

**Your theme `_config.yml`** (Optional)

I'm using the https://github.com/ppoffice/hexo-theme-icarus theme.

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /home/angelcc/projects/angelcervera.github.io
├── cheerio@1.0.0-rc.3
├── hexo@4.2.0
├── hexo-auto-canonical@0.1.1
├── hexo-cookieconsent@1.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-markdown-it@4.1.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo-toc@1.1.0

```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "cheerio": "^1.0.0-rc.3",
    "hexo": "^4.2.0",
    "hexo-auto-canonical": "^0.1.1",
    "hexo-cookieconsent": "^1.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it": "^4.1.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-toc": "^1.1.0"
  }
}
```

**Comment by SukkaW** [comment]
It has been fixed by @stevenjoezhang
