### ISSUE TITLE
When the post tags is empty.  page.tags still equal to true ?

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4247]
## Check List

Please check followings before submitting a new issue.

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [X] I have already searched existing issues and they are not help to me
- [X] I examined error or warning messages and it's difficult to solve
- [X] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [X] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

When the post tags is empty.  page.tags still equal to true ?
In my code
```
- if (page.keywords) pageKeywords = Array.isArray(page.keywords) ? (page.keywords).join(',') :  ([]).join(',') || page.keywords
- else if (page.tags && page.tags.data) pageKeywords = page.tags.data.map(function(tag) {return tag.name;}).join(',')
- else pageKeywords = Array.isArray(config.keywords) ? (config.keywords).join(','):  ([]).join(',') || config.keywords
```
the post tags is empty, and the final show the that `<meta name="keywords" content="">`

i try to hide the the second code (page.tags)
the final show the keywords is config.keywords

it seem page.tags && page.tags.data is return true ?

**Comment by stevenjoezhang** [comment]
This is not surprising in JavaScript
<img width="380" alt="截屏2020-04-17 上午1 37 32" src="https://user-images.githubusercontent.com/16272760/79488261-0bad5480-804c-11ea-8e87-933b61f041d3.png">

**Comment by jerryc127** [comment]
thx
so it return a empty array.

i try to change the condition
if (page.tags.length)
it error 
Cannot read property 'length' of undefined
how can i solve it ?

**Comment by stevenjoezhang** [comment]
```js
if (page.tags && page.tags.length)
```

**Comment by jerryc127** [comment]
thx
