### ISSUE TITLE
What can I do to make the comments of page false by default

### ISSUE THREAD

**Issue by zkqiang** [hexojs/hexo#4249]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question

https://github.com/hexojs/hexo/blob/0e3b9ec2abafd35b0c40d91071d0315ee89614b2/lib/models/post.js#L34

What can I do to make the comments of page false by default?

I want to open the comments just through front-matter of pages. And I don't want to go through another variable

**Comment by stevenjoezhang** [comment]
I'm afraid not. As you can see, this is hard-coded. I suggest you use another front matter variable, e.g. `comment`
