### ISSUE TITLE
Hexo can't load modules compiled with inlineSource / inlineSourceMaps due to unexpected EOF

### ISSUE THREAD

**Issue by booninite** [hexojs/hexo#4251]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
A valid Node.js file output by TypeScript with inlineSource/inlineSourceMaps is loaded successfully by Hexo.

## Actual behavior

If the file ends like so:

```typescript
});
//# sourceMappingURL=data:application/json;<redacted>
```

Hexo will fail to load the module with the following message:

```sh
ERROR Plugin load failed: @dpu/hexo-github-include
/private/var/tmp/_bazel_shimmerjs/11e7d2c979b319c610564f987eb77063/execroot/kdk12_sh/node_modules/@dpu/hexo-github-include/index.js:69
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9naXRodWItaW5jbHVkZS9pbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQUFBLHlDQUFzQztJQUN0QyxpQ0FBZ0M7SUFFaEMsb0VBQW9FO0lBQ3BFLDBFQUEwRTtJQUMxRSxzQkFBc0I7SUFDdEIsTUFBTSxJQUFJLEdBQUcscUJBQXFCLENBQUM7SUFDbkMsTUFBTSxPQUFPLEdBQUcsT0FBTyxDQUFDO0lBRXhCLHNEQUFzRDtJQUN0RCxhQUFhO0lBQ2IsSUFBSSxDQUFDLE1BQU0sQ0FBQyxHQUFHLENBQUMsUUFBUSxDQUFDLGdCQUFnQixFQUFFLENBQU8sSUFBSSxFQUFFLEVBQUU7UUFDdEQsTUFBTSxJQUFJLEdBQUcsSUFBSSxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBQ3JCLElBQUksQ0FBQyxJQUFJLEVBQUU7WUFDUCxNQUFNLElBQUksS0FBSyxDQUFDLGdDQUFnQyxDQUFDLENBQUM7U0FDckQ7UUFDRCxNQUFNLElBQUksR0FBRyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUM7UUFDckIsTUFBTSxHQUFHLEdBQUcscUNBQXFDLElBQUksRUFBRSxDQUFDO1FBQ3hELG9DQUFvQztRQUNwQyxNQUFNLElBQUksR0FBRyxNQUFNLE9BQU8sQ0FBQyxHQ

SyntaxError: Unexpected end of input
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at runInThisContext (vm.js:306:10)
    at /private/var/tmp/_bazel_shimmerjs/11e7d2c979b319c610564f987eb77063/execroot/kdk12_sh/node_modules/hexo/lib/hexo/index.js:291:18
    at tryCatcher (/private/var/tmp/_bazel_shimmerjs/11e7d2c979b319c610564f987eb77063/execroot/kdk12_sh/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/private/var/tmp/_bazel_shimmerjs/11e7d2c979b319c610564f987eb77063/execroot/kdk12_sh/node_modules/bluebird/js/release/promise.js:547:31)
```

However, if a newline is added after the sourcemap:

```typescript
});
//# sourceMappingURL=data:application/json;<redacted>

```

It will load successfully.

Also, if the sourcemap is removed entirely (without a newline added):

```typescript
});
```

It will load successfully.  

## How to reproduce?

* Create simple hello world plugin in TypeScript.
* Compile it with `inlineSource` and `inlineSourceMap` set to `true`
* Declare plugin as dependency in Hexo project via package.json
* Run `hexo generate`

## Environment & Settings

**Node.js & npm version**

```
v13.6.0
6.13.4
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by SukkaW** [comment]
This might be caused by Hexo mechanism of loading plugin (which is heavily based on Node.js 0.11.x Module). We will have a look at this.

**Comment by stevenjoezhang** [comment]
Additional new lines are required here.

https://github.com/hexojs/hexo/blob/dd8976c32ca6d89551640afad16ddafa587f8c26/lib/hexo/index.js#L290
