### ISSUE TITLE
Hexo can't display TOC in Simplified Chinese correctly, while TOC in English is OK.

### ISSUE THREAD

**Issue by Steven-Shixq** [hexojs/hexo#4253]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
TOC (with Simplified Chinese ) display is ok in my Markdown editor: 
![image](https://user-images.githubusercontent.com/37492848/79823307-080c2b80-83c6-11ea-9555-a22f16bd7072.png)

## Actual behavior
Hexo can't display TOC in Simplified Chinese correctly: 
![image](https://user-images.githubusercontent.com/37492848/79823183-b5cb0a80-83c5-11ea-9008-30068c532dae.png)
While hexo display TOC in English is OK：
![image](https://user-images.githubusercontent.com/37492848/79823235-d7c48d00-83c5-11ea-8b45-28b9f355a58a.png)

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
$ hexo --version
hexo: 4.2.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.17763 win32 x64
node: 12.14.1
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.1
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1
```
npm & cnpm:

```
$ npm -v
6.13.4
$ cnpm -v
cnpm@6.1.1 (C:\Users\25835\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@6.13.6 (C:\Users\25835\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@12.14.1 (C:\Program Files\nodejs\node.exe)
npminstall@3.27.0 (C:\Users\25835\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\25835\AppData\Roaming\npm
win32 x64 10.0.17763
registry=https://r.npm.taobao.org
```

**Your site `_config.yml`** (Optional)
language: zh-CN
![image](https://user-images.githubusercontent.com/37492848/79823467-7b15a200-83c6-11ea-885b-6ee51d0cf6cf.png)

```
```

**Your theme `_config.yml`** (Optional)

Butterfly Version: 2.1.0

**Hexo and Plugin version(`npm ls --depth 0`)**

```
$ npm ls --depth 0
hexo-site@0.0.0 C:\Users\25835\blog
+-- UNMET DEPENDENCY @upupming/hexo-renderer-markdown-it-plus@2.0.2
| +-- @neilsustc/markdown-it-katex@0.4.0
| +-- clone@2.1.2
| +-- highlight.js@9.17.1
| +-- markdown-it@8.4.2
| +-- markdown-it-abbr@1.0.4
| +-- markdown-it-deflist@2.0.3
| +-- markdown-it-emoji@1.4.0
| +-- markdown-it-footnote@3.0.2
| +-- markdown-it-ins@2.0.0
| +-- markdown-it-mark@2.0.0
| +-- markdown-it-sub@1.0.0
| +-- markdown-it-sup@1.0.0
| +-- markdown-it-toc@1.1.0
| `-- uslug@1.0.4
+-- cheerio@0.22.0
+-- hexo@4.2.0
+-- hexo-algolia@1.3.1
+-- hexo-browsersync@0.3.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index-pin-top@0.2.2
+-- hexo-generator-search@2.4.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1 -> C:\Users\25835\blog\node_modules\_hexo-helper-live2d@3.1.1@hexo-helper-live2d
+-- UNMET DEPENDENCY hexo-katex@^0.0.13
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-jade@0.5.0
+-- UNMET DEPENDENCY hexo-renderer-kramed@^0.1.4
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-pug@1.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-tag-aplayer@3.0.4
`-- hexo-wordcount@6.0.1

npm ERR! missing: @upupming/hexo-renderer-markdown-it-plus@2.0.2, required by hexo-site@0.0.0
npm ERR! missing: hexo-katex@^0.0.13, required by hexo-site@0.0.0
npm ERR! missing: hexo-renderer-kramed@^0.1.4, required by hexo-site@0.0.0
npm ERR! missing: chalk@1.1.3, required by hexo-helper-live2d@3.1.1
npm ERR! missing: chokidar@2.1.8, required by hexo-helper-live2d@3.1.1
npm ERR! missing: hexo-bunyan@1.0.0, required by hexo-helper-live2d@3.1.1
npm ERR! extraneous: chalk@1.1.3 C:\Users\25835\blog\node_modules\hexo-helper-live2d\node_modules\chalk
npm ERR! extraneous: chokidar@2.1.8 C:\Users\25835\blog\node_modules\hexo-helper-live2d\node_modules\chokidar
npm ERR! extraneous: hexo-bunyan@1.0.0 C:\Users\25835\blog\node_modules\hexo-helper-live2d\node_modules\hexo-bunyan
npm ERR! missing: bluebird@^3.5.1, required by hexo-fs@1.0.2
npm ERR! missing: chokidar@^2.0.4, required by hexo-fs@1.0.2
npm ERR! missing: escape-string-regexp@^1.0.5, required by hexo-fs@1.0.2
npm ERR! missing: graceful-fs@^4.1.11, required by hexo-fs@1.0.2
npm ERR! missing: hexo-bunyan@^1.0.0, required by hexo-log@0.2.0
npm ERR! missing: chalk@^1.1.1, required by hexo-log@0.2.0

```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "@upupming/hexo-renderer-markdown-it-plus": "^2.0.2",
    "cheerio": "^0.22.0",
    "hexo": "^4.0.0",
    "hexo-algolia": "^1.3.1",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-katex": "^0.0.13",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-wordcount": "^6.0.1"
  }
}
```

## Others

**Platform:** Windows
**hexo theme:** Butterfly version: 2.1.0

Thanks

**Comment by stevenjoezhang** [comment]
It seems that this is related to the theme you are using.

**Comment by Qinka** [comment]
> It seems that this is related to the theme you are using.

@stevenjoezhang 

I don't think so. I got the same error after I upgrade Hexo from 3.x to 4.x (other libraries upgrade too).  But I do not upgrade the theme. 

I found all the Chinese characters are converted into code. For example, the character `动` is converted into `&#x52A8;`.  Then API `toc` convert `&#x52A8;` to `&amp;#x52A8;`. 

（英文可能说不清楚，我再用中文说一遍。）
肯定不是主题的问题。我把 hexo 更新到了 4.x 之后，才遇见的这个问题，通过 ejs 调试了一下发现，在使用 `toc` 这个API 的时候，输入的内容中，中文就变成了类似 `&#x52A8;` 的状态。然后 `toc` 这个 API 只把 `&` 进行了编码，然后就成了上面截图里面的那个样子了。。

**Comment by Qinka** [comment]
（我直接写中文了）
@stevenjoezhang 
我测试了一下 把 hexo 换回 3.8 就没事了， 4.2 还是不行。

我翻了一下相关代码，发现这个 https://github.com/hexojs/hexo-util/blob/master/lib/escape_html.js#L6 地方有问题，这个代码直接把 `&` 转义成了 `&amp;` 没有管已经转义了的部分。https://github.com/hexojs/hexo-util/blob/2.0.0/lib/unescape_html.js  这里面反转义并没有处理被转义中文字符，然后就炸了呀。

**Comment by Qinka** [comment]
@Steven-Shixq  作为路人建议你放弃 hexo 这个东西吧，把帮人看样子是不打算修这个问题了。 这个问题 https://github.com/hexojs/hexo-util/issues/200 连查都不查就关闭了，非要用，可以用 4.0.0 这个版本，这个版本还没有他们自己写的 unescape 和 escape 函数。

**Comment by stevenjoezhang** [comment]
我从 Hexo 3.5 用到 4.2，用过不下十个主题，从来没有遇到过这样的 bug。想要研究清楚需要时间，因为不同的环境、不同的 Hexo 插件、不同的配置都可能导致问题。

正如你自己所说
> 通过 ejs 调试了一下发现，在使用 toc 这个API 的时候，输入的内容中，中文就变成了类似 `&#x52A8;` 的状态。

这很有可能才是问题的根本原因。中文不应该在这里被转义。

我本来准备花点时间继续研究这个问题的，但看到你发表的不当言论后，我放弃了。辛辛苦苦帮人解决问题，回头被一句「非蠢即坏」甩在脸上，那可真是有够可笑啊。仿佛项目维护者的付出都是理所当然的，你只用负责坐享其成，不满意的话还可以恶语相向？

我不理解你为何会对开源项目维护者存在恶意。如果有问题的解决方案，欢迎提交Pull Request，我们会表示感谢。如果你自己进行研究并得出了结论，可以提出一些建设性的意见，我们也非常欢迎。

这一切的前提，是能够尊重他人，并且友善地与他人交流。这是基本的教养，而不是 GitHub 或开源社区应该教会你的。看上去你准备放弃 Hexo，我相信这对大家都是好事。
