### ISSUE TITLE
Question: How to exclude file from Hexo output

### ISSUE THREAD

**Issue by sergeyzwezdin** [hexojs/hexo#4262]
## Question

For example, I have a file - `image1.jpg` - in `_posts` folder. When I generate the website, to file copied as expected. Is there any way to exclude this file from copying to output directory?

**Comment by stevenjoezhang** [comment]
The answer is yes. You can use the `hexo.route.remove` method. Here is an example

https://github.com/theme-next/hexo-theme-next/blob/master/scripts/filters/minify.js

**Comment by sergeyzwezdin** [comment]
@stevenjoezhang Brilliant, thank you 🙏🏻
