### ISSUE TITLE
hexo generates empty files

### ISSUE THREAD

**Issue by honkiko** [hexojs/hexo#4267]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
Closing as not following issue template.
If you're using Node.js 14, please downgrade to 13 or 12.

**Comment by stevenjoezhang** [comment]
Update on Feb 14th, 2021: the previous reply is outdated. Hexo is compatible with Node.js 14 since version 4.2.1 released on May 14, 2020. See also https://github.com/hexojs/hexo/pull/4285
