### ISSUE TITLE
代码块里不能包含代码块？

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4273]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

在代码块里书写代码
例如

```markdown
{% hideToggle Butterfly安裝方法 %}
在你的博客根目錄裏

​```git
git clone -b master https://github.com/jerryc127/hexo-theme-butterfly.git themes/Butterfly
​```

如果想要安裝比較新的dev分支，可以

​```git
git clone -b dev https://github.com/jerryc127/hexo-theme-butterfly.git themes/Butterfly
​```

{% endhideToggle %}
```

把上面这段文字书写在代码块里（语言为markdown)
但是hexo渲染时，会报错，发现渲染器把中间代码块的三个点当作代码块的结束标志了
![image](https://user-images.githubusercontent.com/16351105/80314999-7702dd80-8827-11ea-9811-35f4f97dc5b0.png)

报错

![image](https://user-images.githubusercontent.com/16351105/80315009-85e99000-8827-11ea-9e50-7e5dd2ddce9d.png)

不知道这是不是bug

----------------------------------------------------------------------------------------------
代码内容
![image](https://user-images.githubusercontent.com/16351105/80315069-ed074480-8827-11ea-925b-e2216821fb30.png)
期望看到的结果
![image](https://user-images.githubusercontent.com/16351105/80315079-f7c1d980-8827-11ea-804e-fe43498b6c7d.png)

**Comment by carl0schen** [comment]
I have the same question.
E.g
```
{% codeblock %}
{% raw %}
content
{% endraw %}
{% endcodeblock %}
```
Execution Results:
```
content
```

The code in the `codeblock` cannot be displayed.
Please teach me how to write the `codeblock` tag to display it correctly.

Thanks.

**Comment by stevenjoezhang** [comment]
Use the code tag

    {% code %}
    {% hideToggle Butterfly安裝方法 %}
    在你的博客根目錄裏

    ​```git
    git clone -b master https://github.com/jerryc127/hexo-theme-butterfly.git themes/Butterfly
    ​```

    如果想要安裝比較新的dev分支，可以

    ​```git
    git clone -b dev https://github.com/jerryc127/hexo-theme-butterfly.git themes/Butterfly
    ​```

    {% endhideToggle %}
    {% endcode %}
