### ISSUE TITLE
密码忘了怎么办

### ISSUE THREAD

**Issue by li1679829296** [hexojs/hexo#4286]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
这个可能有帮助： https://github.com/hexojs/hexo-deployer-git/issues/175
