### ISSUE TITLE
node 14 incompatible

### ISSUE THREAD

**Issue by oceanpad** [hexojs/hexo#4289]
When Generate htmls.

Node 14.1.0(Latest): Generated html files are all empty.

Node 12.16.3(LTS): Ok

**Comment by stevenjoezhang** [comment]
Please search for existing issues before creating a new issue, thanks.

#4268
#4272
#4275
#4281
https://github.com/hexojs/hexo/issues/4288
hexojs/hexo-deployer-git#177

**Comment by YoshinoriN** [comment]
@oceanpad 

We published [v4.2.1](https://github.com/hexojs/hexo/releases/tag/4.2.1).
v4.2.1 has included fixed compatible with Node 14.

Thanks :)
