### ISSUE TITLE
After run "hexo d", I always receive the email,

### ISSUE THREAD

**Issue by Kris451** [hexojs/hexo#4291]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional
<img width="952" alt="批注 2020-05-03 203812" src="https://user-images.githubusercontent.com/57905590/80914467-57ffd080-8d7e-11ea-89b0-4c0edd5a0a4d.png">
)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by jerryc127** [comment]
你这也不关hexo的问题的

**Comment by Kris451** [comment]
我已经找到了问题所在：我使用了node.js14.1.0版本，这个版本与hexo的兼容似乎还有一些问题，在执行  `hexo g` 和 `hexo d` 后， git会显示循环依赖项中缺少一些内容，虽然在执行 `hexo s` 后仍然可以在本地看到 localhost:4000 的内容，但是此时 `hexo d` 后，页面一直是404。在我卸载node.js后，我又重新安装了node.js12.16.3版本，问题就解决了。感谢！

**Comment by stevenjoezhang** [comment]
是的，现在 Node.js 14 的兼容性存在问题，可以在这里讨论，谢谢： https://github.com/hexojs/hexo/issues/4260
这个 Issue 先关了，有其他问题欢迎提出~
