### ISSUE TITLE
代码块会被自动分开为 左右 2 块

### ISSUE THREAD

**Issue by Leader755** [hexojs/hexo#4293]
![image](https://user-images.githubusercontent.com/37180494/80990339-c325d180-8e68-11ea-8266-b29aa4d48ef9.png)

我的问题如下，代码块会被自动分开为 左右 2 块，所有的代码都是这样的。我是从语雀上导出的后，同步出来，就会成这样。怎么才能解决这问题。（My problem is as follows, the code block will be automatically divided into 2 blocks, and all the code is like this. After I exported it from Yuque, and it was synchronized, it would become like this. How can this problem be solved.）

**Comment by jerryc127** [comment]
看看你导出的md文件对应的代码块是怎样的？

**Comment by Leader755** [comment]
![image](https://user-images.githubusercontent.com/37180494/81023714-d99d4e80-8ea3-11ea-9e68-834306998a4d.png)
![image](https://user-images.githubusercontent.com/37180494/81023732-e752d400-8ea3-11ea-828e-bfa1380546e4.png)
以上就是该博客当前的显示，和元 md 文档的代码块部分。

**Comment by jerryc127** [comment]
看了一下你网页生成代码
这个问题是你主题的问题了
hexo生成的代码没错
你向你的主題github反馈

**Comment by SukkaW** [comment]
It seems that you are using hexo-theme-next.

@stevenjoezhang @liolok Would you mind digging to this? Maybe it is related with https://github.com/hexojs/hexo-util/pull/153

**Comment by stevenjoezhang** [comment]
Actually it's not hexo-theme-next. ref
https://github.com/Leader755/leader755.github.io/blob/ee3a54f7ab0fb8d5700fee541108591073102599/2020/05/01/yuque/pdrp5a/index.html#L460

https://github.com/hongweifuture/hexo-theme-halo

This may be a problem caused by my previous attempt to change the html structure of the code block generated by `hexo-util`.

**Comment by stevenjoezhang** [comment]
It's a bug of hexo-theme-halo and has nothing to do with Hexo

https://github.com/hongweifuture/hexo-theme-halo/blob/b13c36695e1c00b0b7bd31d338a6703636bf9e42/source/libs/codeBlock/codeBlockFuction.js#L4
