### ISSUE TITLE
上传 github出现奇怪的报错

### ISSUE THREAD

**Issue by Leader755** [hexojs/hexo#4294]
上传 github 出现奇怪的报错信息，但是并不影响上传。之前也见到有人提出同样的问题。给出的解决方法是将 https换成 ssh,但这是在 win 系统的解决方案。但是 mac 上目前为止并没有看到有效的解决方案。（The previous solution was to convert https to ssh, but the solution in win system. But so far no effective solution has been seen on mac.）
![image](https://user-images.githubusercontent.com/37180494/81082379-c763f480-8f25-11ea-8816-fee68a957075.png)

**Comment by stevenjoezhang** [comment]
请提供更多信息。这是您第二次不按照模板提交 Issue： https://github.com/hexojs/hexo/issues/4293
为了避免其它用户在此问题上浪费时间，此 Issue 将被直接关闭。
