### ISSUE TITLE
How to filter and render different posts based on YAML front-matter?

### ISSUE THREAD

**Issue by mvxt** [hexojs/hexo#4295]
## Check List
- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

### Goal
I am trying to create a portfolio site. There's a blog, but there's also a "professional history" page.

There are two types of posts: a normal "blog" post, and a "cv" post, which is an entry in the professional history.

I want to filter so that the blog portions (e.g. index, tags, categories, archives, etc.) only render the "blog" type posts, and ignore the "cv" type posts.

Then, on the professional history page, I only want to render and loop through "cv" type posts, and ignore "blog" type posts.

Example posts:
```
---
title: Example Blog Post
type: blog
---

...etc.
```
```
---
title: Example Job History
type: cv
---

...etc.
```

As an example, let's say I have 1 "blog" post and 1 "cv" post. My Archive should show only 1 post. My blog index page should only show that I have one post.

And then when I navigate to the Professional History page, I only see the professional history entry, information rendered from the "cv" type post.

How do I achieve this?

## Environment & Settings

**Node.js & npm version**

```
$ node -v
v13.9.0
$ npm -v
6.13.7
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
$ npm ls --depth 0
mvxt-blog-site@1.0.0 /Users/mikeyvxt/workspace/mvxt
├── hexo@4.2.0
├── hexo-critical-css@1.0.6
├── hexo-filter-crossorigin@0.1.3
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.1.6
├── hexo-html-minifier@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

**Your package.json `package.json`**

```
{
  "name": "mvxt-blog-site",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "dev": "hexo server",
    "watch": "hexo generate --watch"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-critical-css": "^1.0.6",
    "hexo-filter-crossorigin": "^0.1.3",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-html-minifier": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}
```

## Others
**Current Code**: https://github.com/mvxt/hexo-theme-studio
**Example Site**: https://www.mvxt.me

- Home, Archives, Topics pages are blog-related.
- CV page has entries hard-coded - my ultimate goal is to be able to write those entries in individual post files, designate "cv" type in front-matter, and render only those posts on the CV page.

Hopefully my question makes sense!

**Comment by stevenjoezhang** [comment]
Relevant issue https://github.com/hexojs/hexo/issues/1675
