### ISSUE TITLE
有没有办法让"hexo-generator-search"的"content"存原始的md文档内容

### ISSUE THREAD

**Issue by doobo** [hexojs/hexo#4296]
示例：https://5fu8.com/search.xml
现在里面的content内容，是解析后的html内容，如果我想放到公众号里面去，很多样式不能用，能不能设置参数，让"hexo-generator-search"生成的"content"内容为原始的md内容，这样方便重新解析！

**Comment by stevenjoezhang** [comment]
你好，hexo-generator-search 是第三方插件。这是 Hexo 的仓库，只解决 Hexo 本身的 Issue。谢谢。
