### ISSUE TITLE
Do you accept this code block PR ?

### ISSUE THREAD

**Issue by lnxpgn** [hexojs/hexo#4297]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question

My [blog](https://lnxpgn.github.io/) uses Hexo and the theme [NexT](https://github.com/theme-next/hexo-theme-next). I want to use CSS `white-space: pre-wap` in code blocks to wrap long lines to next lines automatically, don't like moving scroll bars again and again, but the line numbers don't match the source code lines. 

```html
<div class="highlight-container">
  <figure class="highlight jsx">
    <div class="table-container">   <!-- added by NexT -->
      <table><tbody>
        <tr>
          <!-- line numbers -->
          <td class="gutter">
            <pre>
              <span class="line">1</span>
              <br>
              <span class="line">2</span>
            </pre>
          </td>
          <!-- source code -->
          <td class="code">
            <pre>
              <span class="line">
                <span class="literal">Hello</span>
                <br>
                <span class="literal">World</span>
              </span>
            </pre>
          </td>
        </tr>
      </tbody></table>
    </div>
  </figure>
</div>
```
The whole table has only one row. I changed the table structure, like this:

```html
<div class="highlight-container">
  <figure class="highlight jsx">
    <div class="table-container">   <!-- added by NexT -->
      <table><tbody>
        <tr>
          <!-- line number -->
          <td class="gutter">
            <pre>
              <span class="line">1</span>
            </pre>
          </td>
          <!-- source code -->
          <td class="code">
            <pre>
              <span class="line">
                <span class="literal">Hello</span>
              </span>
            </pre>
          </td>
        </tr>
        
        <tr>
          <!-- line number -->
          <td class="gutter">
            <pre>
              <span class="line">2</span>
            </pre>
          </td>
          <!-- source code -->
          <td class="code">
            <pre>
              <span class="line">
                <span class="literal">World</span>
              </span>
            </pre>
          </td>
        </tr>
      </tbody></table>
    </div>
  </figure>
</div>
```
A line number and its source code are in one table row.  I only modified several places of NexT to make them work together. The change has compatible issues with other themes. It's better to create a PR than patching the source code, but I am not sure whether you accept this PR. 

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
Hexo: v4.2.0
NexT: v7.8.0
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
I tried. The answer is no (Pull request reverted)

https://github.com/hexojs/hexo-util/pull/132

https://github.com/hexojs/hexo-util/issues/145
