### ISSUE TITLE
Is it possible to open the newly created post for editing immediately

### ISSUE THREAD

**Issue by johnjacobkenny** [hexojs/hexo#4300]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

it would be great if we can configure a default editor and when we run `hexo new post <title>` it can open text editor with that file.

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/issues/4242

**Comment by johnjacobkenny** [comment]
Sorry for the duplicate! If there are any "for beginner" bugs, I can pick any. Thanks :smiley:
