### ISSUE TITLE
_config.ymal 中 url 字段设置为 /，hexo@4.2.0 报错 TypeError [ERR_INVALID_URL]

### ISSUE THREAD

**Issue by lingxing1017** [hexojs/hexo#4307]
## Check List

Please check followings before submitting a new issue.

- [☑️] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [☑️] I have already searched existing issues and they are not help to me
- [☑️] I examined error or warning messages and it's difficult to solve
- [☑️] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [☑️] Node.js is higher than 8.6.0

## Question

_config.ymal 中 url 字段设置为 /，hexo@3.9.0 可以正常渲染，hexo@4.2.0 报错 TypeError [ERR_INVALID_URL]: Invalid URL: http://

当 url 字段设置为如 /test 时，hexo@4.2.0 可以正常渲染，且经过实验两者对博文的渲染结果一致

想请教下这个字段是否有设置的必要性，还是说跟主题是否会用到这个字段有关？

## Environment & Settings

**Node.js & npm version**

```
node 版本：v12.1.0
npm 版本：6.14.5
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
├── hexo@4.2.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-server": "^1.0.0"
  }
}
```

**Comment by stevenjoezhang** [comment]
URL 字段用于设置博客域名，例如 `https://yoursite.com`
`/` 和 `/test` 均为非法参数，可能导致不可预料的后果。

**Comment by lingxing1017** [comment]
> URL 字段用于设置博客域名，例如 `https://yoursite.com`
> `/` 和 `/test` 均为非法参数，可能导致不可预料的后果。

在哪些位置会使用到？如果我是有多个博客域名，这个位置是随意选一个即可，是否会导致其他域名无法访问

**Comment by stevenjoezhang** [comment]
主题中可能会使用到。例如用于生成 `<link rel=canonical>` 标签： https://support.google.com/webmasters/answer/139066?hl=en
此外有些评论系统需要根据当前页面的完整地址加载，如果设置不当，那么在不同域名访问同一个页面，评论的数据就会不互通。

将 `url` 项设置为其中一个域名一般不会有问题。

**Comment by lingxing1017** [comment]
> 主题中可能会使用到。例如用于生成 `<link rel=canonical>` 标签： https://support.google.com/webmasters/answer/139066?hl=en
> 此外有些评论系统需要根据当前页面的完整地址加载，如果设置不当，那么在不同域名访问同一个页面，评论的数据就会不互通。
> 
> 将 `url` 项设置为其中一个域名一般不会有问题。

我使用的主题应该是不需要这个字段，评论系统我也关闭了，那有方法可以忽略这个字段的检查吗

**Comment by stevenjoezhang** [comment]
需要修改 Hexo 的有关源码才能实现。由于
> _config.yml 中 url 字段设置为 /

是无效的设置，恐怕我无法提供更多帮助。

**Comment by zwshine** [comment]
你好，请问url这个问题解决了么？

**Comment by lingxing1017** [comment]
你好，

我看了一下问题原纪录，以及我本地的 _config.ymal 文件，最终方案就是将 url 设置为实际绑定的域名了

2024年7月2日 15:01，zwshine ***@***.***> 写道：



你好，请问url这个问题解决了么？
