### ISSUE TITLE
hexo init connection fail

### ISSUE THREAD

**Issue by xuedaobian** [hexojs/hexo#4320]
fatal: unable to access 'https://github.com/hexojs/hexo-starter.git/': Failed to connect to 127.0.0.1 port 1080: Connection refused
WARN  git clone failed. Copying data instead
WARN  Failed to install dependencies. Please run 'npm install' manually!

**Comment by stevenjoezhang** [comment]
Please check your proxy settings.
Closing as duplicate of https://github.com/hexojs/hexo/issues/4129
