### ISSUE TITLE
hexo generate 命令生成的本地public目录下index.html内容为空

### ISSUE THREAD

**Issue by qiumeihui** [hexojs/hexo#4327]
本来想新建一篇文章，但是hexo server本地一直打不开，也没报错。
然后执行了hexo clean。
接着hexo generate 命令生成的本地public目录下index.html内容为空。

希望能帮忙看一下什么问题。非常感谢

**Comment by a2603802339** [comment]
我的直接是不生成html文件，执行hexo g --debug没有发现任何错误，npm install hexo-generator-index也无用

**Comment by qiumeihui** [comment]
> 我的直接是不生成html文件，执行hexo g --debug没有发现任何错误，npm install hexo-generator-index也无用。打开[http://localhost:4000显示Cannot](http://localhost:4000%E6%98%BE%E7%A4%BACannot) GET /

我遇到这种问题大概5、6次了，一直不清楚为何导致的。如果你找到原因了麻烦告诉我一下哈

**Comment by hezhicai1** [comment]
我的也和你们差不多 加载不到HTML文件，回去一看竟让全是空的 陔！

**Comment by hezhicai1** [comment]
我的也和你们差不多 加载不到HTML文件，回去一看竟让全是空的 陔！

**Comment by hezhicai1** [comment]
我的弄好了 一般是 你们修改了yml配置文件的地方会报错 ，修改了哪里就还原哪个部分

**Comment by 2410635019** [comment]
我也是，本地测试是空白，然后我开始重新搭建hexo，但是hexo s提示我npm install hexo--save
我照做了，然后报错
