### ISSUE TITLE
How to get the post ID

### ISSUE THREAD

**Issue by A-limon** [hexojs/hexo#433]
I want use post id in my theme,I check the document about variables but noting found.

``` ejs
<%= item.?? %>
```

**Comment by tangkunyin** [comment]
然而这个post id每次重新生成文章时（hexo g）都会变化。引发的问题是如果用这个id作为第三方平台的唯一标识，那就会出问题。比如我用搜狐畅言做评论，这篇文章id变动后，评论就没了

**Comment by dimaslanjaka** [comment]
```js
console.log(this._id);
```
