### ISSUE TITLE
In the local public file generated by the hexo g command index.html The file is empty, and using the hexo D command will display fatal: unable to find remote helper for 'httpd'. How to solve this problem

### ISSUE THREAD

**Issue by lihai2333** [hexojs/hexo#4332]
In the local public file generated by the hexo g command index.html The file is empty, and using the hexo D command will display fatal: unable to find remote helper for 'httpd'. How to solve this problem!!!

**Comment by stevenjoezhang** [comment]
Please provide the necessary information according to the Issue template, otherwise no one else can help you.
