### ISSUE TITLE
unexpected contributions present to my github profile and the most terrible thing is the contributions of my busiest day can be modified!

### ISSUE THREAD

**Issue by Ele-Peng** [hexojs/hexo#4335]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
- the contributions of my busiest day were static, cannot be modified. 
- contributions should add one at a time.

## Actual behavior
- more then 10 contributions were added.
- the contributions of my busiest day were added too.
- my commits were only 30+ in April 4.

## How to reproduce?

* hexo d -g
* git add .
* git commit -m 'xxx'
* git pull
* git push

## Environment & Settings

**Node.js & npm version**

```
n/10.16.0
```

**Your site `_config.yml`** (Optional)

```

```

**Your theme `_config.yml`** (Optional)

```
hexo-theme-lx
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo: 4.2.0
hexo-cli: 3.1.0
os: Darwin 18.7.0 darwin x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "-": "0.0.1",
    "hexo": "^4.2.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.3.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

```

## Others
- [my github hexo blog repo site](https://github.com/Ele-Peng/Ele-Peng.github.io)

**Comment by SukkaW** [comment]
So what? Stop using the token of your own account to deploy your blog.

Go back to register a new GitHub account, add it as one of your repo's collaborator, then use its token with git config set to its name & email.

Example: @SukkaBot @traviscibot @DIYgod-bot

**Comment by Ele-Peng** [comment]
like this? [new account git commits history](https://img.meituan.net/kylisean/3d31d905d6414e0fd82ba18b545a8b4b436800.png)
I still feel confused.I have tried to use git configby new account's name & email.but the deploy account still old. and the contributions were add more than one.

**Comment by Ele-Peng** [comment]
and what can i do for recalculating the contritions? the contributions over 2,000 look like strange.
