### ISSUE TITLE
hexo执行时命令行的错误日志在哪里查看

### ISSUE THREAD

**Issue by grofis** [hexojs/hexo#4341]
![image](https://user-images.githubusercontent.com/5236541/83388705-7a3e4a00-a421-11ea-9e73-e3dad36f21ad.png)

hexo执行时命令行的错误日志在哪里查看？

命令行滚动不了.

**Comment by stevenjoezhang** [comment]
从报错信息来看，有文章的 Front-matter 中存在语法错误。

另外 NexT 主题的仓库以移至新地址 http://github.com/next-theme/hexo-theme-next

**Comment by jiangtj** [comment]
你可以将日志输出到指定文件中
```
hexo g >> file-path
```
