### ISSUE TITLE
Proyect without theme - WARN  No layout: index.html

### ISSUE THREAD

**Issue by guidopontet** [hexojs/hexo#4345]
Hi, is there a way to create a simple website without using a theme? I tried to remove theme folder and apply configs to `_config.yml` but the next warning is shown:

```
WARN  No layout: index.html
```

Thanks!

**Comment by jiangtj** [comment]
hexo needs the template defined in the theme's layout to render html. If you don't want to use any theme, you can write html directly and set `skip_render` for your html file.
```
skip_render:
  - your html file
```
