### ISSUE TITLE
i hv question with rebots.txt and sitemap.xml [中文/English]

### ISSUE THREAD

**Issue by shukangzhang** [hexojs/hexo#4349]
Hi guys, i wonder if rebots.txt and sitemap.xml hv conflict.

I mean, if i post a new post, then i run hexo d -g, the new website link will be automaticlly included in sitemap.xml, but will it be automaticlly written in rebots.txt or not?

If not, what will google search console react. sitemap.xml hv higher priority or rebots.txt hv higher priority? 

In a word, i want to know what will happen, when rebots.txt and sitemap.xml dont hv the same URLs.

Thx!!! love you all. 

老铁们，我想问rebots.txt和sitemap.xml如果包含不同的链接google search console会怎么反应啊，我没搞懂收录原理，现在只把[shukangzhang.com/sitemap.xml] 提交了，robots.txt没敢提交

**Comment by stevenjoezhang** [comment]
你好，Hexo 只是一个静态站点生成器，收录则是由搜索引擎进行的，我们无法解答这个问题。
如果想要搞懂收录原理，请向搜索引擎的技术支持发送邮件询问，谢谢！
