### ISSUE TITLE
How to display URL as non-URLcode in a webpage,like Chinese?

### ISSUE THREAD

**Issue by AmelieNet** [hexojs/hexo#4351]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question

Copyright information of my website can't be displayed in Chinese.   
It only displays URLcode and not Chinese.
Like this:  
<http://edwin.cf:8080/2020/06/09/音乐测试/>

![1](https://user-images.githubusercontent.com/7888766/84180854-c4c36480-aaba-11ea-9544-2ede72f0d1d9.png)

The others are like this:

![2](https://user-images.githubusercontent.com/7888766/84181090-27b4fb80-aabb-11ea-827b-7db23284b347.png)

**As far as I know, this is returned by the variable `page.permalink`.**

## Environment & Settings

**Node.js & npm version**

```
Node.js version: v13.14.0
npm version: 6.14.5
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /srv/www/hexo
├── hexo@4.2.1
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index-pin-top@0.2.2
├── hexo-generator-search@2.4.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-pug@1.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── hexo-tag-aplayer@3.0.4
├── hexo-tag-dplayer@0.3.3
└── valine@1.4.14

```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.2.1",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-tag-dplayer": "^0.3.3",
    "valine": "^1.4.14"
  }
}
```

## Others

I use [melody](https://github.com/Molunerfinn/hexo-theme-melody) theme.

**`page.permalink` in [here](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/layout/post.pug#L87)**

**My website: <http://edwin.cf:8080/>**

**Comment by stevenjoezhang** [comment]
Hello, this means that there is a compatibility issue between hexo-theme-melody and Hexo 4. Please contact the theme maintainer for help, thank you.
