### ISSUE TITLE
Can I integrate an img-fluid class to make my images responsive in hexo blog?

### ISSUE THREAD

**Issue by Fing15** [hexojs/hexo#4372]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by curbengh** [comment]
Assuming you're using hexo-renderer-marked, it's possible in the _upcoming_ hexo-renderer-marked v3.

Save the following code to "scripts/img-fluid.js":

``` js
'use strict'
/* global hexo */

const { encodeURL, url_for } = require('hexo-util')
const { parse } = require('url')

hexo.extend.filter.register('marked:renderer', function (renderer) {
  const { config } = this
  renderer.image = function (href, title, alt) {
    let relative_link = false
    let prependRoot = false
    if (config.relative_link) relative_link = config.relative_link
    if (config.marked) prependRoot = config.marked.prependRoot

    if (!parse(href).hostname && !relative_link && prependRoot) {
      href = url_for.call(options, href)
    }

    // Add `class="img-fluid"`
    let out = `<img src="${encodeURL(href)}" class="img-fluid"`
    if (alt) out += ` alt="${alt}"`
    if (title) out += ` title="${title}"`

    out += '>'
    return out
  }
})
```

Since v3 is not yet released, if you want to test it:

``` diff
package.json
  "dependencies": {
    "hexo": "^4.2.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
-    "hexo-renderer-marked": "^2.0.0",
+    "hexo-renderer-marked": "hexojs/hexo-renderer-marked",
    "hexo-server": "^1.0.0"
  }
```

**Comment by SukkaW** [comment]
@Fing15 

**Updated**

`hexo-renderer-marked @3` is now released. Run following command to upgrade:

```bash
npm i hexo-renderer-marked@latest
```

Then use code provided by @curbengh.

**Comment by Fing15** [comment]
I downloaded the new release, added the img-fluid.js code, updated the package but it's still not working. The images are not resizing and they lack the `img-fluid` class.

**Comment by curbengh** [comment]
Can I have your Hexo and Plugin version (`$ npm ls --depth 0`)?

**Comment by curbengh** [comment]
To check whether "scripts/img-fluid.js" is executed, run `hexo generate --debug", there should be a line:

```
Script loaded: scripts/img-fluid.js
```

I also suggest to add a test `console.log()` in the middle of the script:

``` diff
'use strict'
/* global hexo */

const { encodeURL, url_for } = require('hexo-util')
const { parse } = require('url')

hexo.extend.filter.register('marked:renderer', function (renderer) {
  const { config } = this
  renderer.image = function (href, title, alt) {
    let relative_link = false
    let prependRoot = false
    if (config.relative_link) relative_link = config.relative_link
    if (config.marked) prependRoot = config.marked.prependRoot

    if (!parse(href).hostname && !relative_link && prependRoot) {
      href = url_for.call(options, href)
    }

    // Add `class="img-fluid"`
    let out = `<img src="${encodeURL(href)}" class="img-fluid"`
    if (alt) out += ` alt="${alt}"`
    if (title) out += ` title="${title}"`

    out += '>'
+   console.log('img-fluid script')
    return out
  }
})
```

Then when you run `hexo generate` again, the command prompt should display "img-fluid script" message a few times.

**Comment by Fing15** [comment]
The `img-fluid` works in the `archive` section of the blog, but not in the blog post. 

@curbengh This is the result from `npm ls --depth 0`

`+-- hexo@4.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-search@2.4.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-hide-posts@0.1.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
`

**Comment by curbengh** [comment]
Thanks, output seems fine to me.

> The img-fluid works in the archive section of the blog, but not in the blog post.

`archive` section usually includes title and excerpt only. Do you embed image in excerpt section (of a post)?
