### ISSUE TITLE
Cannot GET /%20/

### ISSUE THREAD

**Issue by mtiger95** [hexojs/hexo#4375]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

 
这个是我的配置文件，我已经把 “||” 前面和后面的空格都去掉了，但运行后，home 和 archives 这两个还是会跳转带有 /%20/ 的路径导致失败，但tags 和 categories 却可以，很奇怪的问题。

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
menu:
  home: /|| home
  tags: /tags/|| tags
  categories: /categories/|| th
  archives: /archives/|| archive
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
"dependencies": {
    "hexo": "^4.2.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-wordcount": "^6.0.1"
  }
```

**Your package.json `package.json`**

```
"dependencies": {
    "hexo": "^4.2.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-wordcount": "^6.0.1"
  }
```

## Others
去掉了空格还是不能正常运行起来，请官方文档特别备注这个问题的解决方法和提示。

**Comment by mtiger95** [comment]
Cannot GET /%20/    我的node version 10.16.3, npm version 6.9.0

**Comment by stevenjoezhang** [comment]
如果你用的 NexT 主题，请升级你的主题： https://github.com/next-theme/hexo-theme-next
如果你用的不是 NexT 主题，请降级你的 Hexo： `npm i hexo@3.9.0`
