### ISSUE TITLE
Drop Node.js 10 support & Require Node.js >= 12

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#4378]
Continuing #3508 & #3698.

With Node.js 12 we will be able to use:

- `Object.fromEntries`
- `Array#values`
- `String#matchAll`
- `Array#flat`, `Array#flatMap`
- Well-formed JSON.stringify: https://github.com/tc39/proposal-well-formed-stringify
- Class field: https://github.com/tc39/proposal-class-fields
- Static field: https://github.com/tc39/proposal-static-class-features/

Also, `worker_threads` requires Node.js 12+ as well, which is important for multi-core usage proposal (#4355).

On the other hand, `async/await` is significantly faster than native Promise and its performance is now comparable to that of Bluebird:

![image](https://user-images.githubusercontent.com/40715044/85673927-f5c8a980-b6f6-11ea-85c0-85710911c4a4.png)
![image](https://user-images.githubusercontent.com/40715044/85673938-fa8d5d80-b6f6-11ea-85cf-b82becb3f143.png)

> Ref: https://blog.kuzzle.io/bluebird-vs-native-vs-async/await-state-of-promises-performances-in-2019
> Ref: https://v8.dev/blog/fast-async

----

Eventually we will drop Node.js 10. The question is whether we should bump minimum required Node.js version to 12 before we publish Hexo 5.0.0.

cc @hexojs/core @curbengh @segayuu @seaoak @tomap @stevenjoezhang

**Comment by tomap** [comment]
So, we will drop node 12 with hexo 6?

**Comment by SukkaW** [comment]
@tomap Yeah, wait for Hexo 6.

**Comment by stevenjoezhang** [comment]
Node.js 10 will reach EOL on April 30, 2021

https://github.com/nodejs/Release

See also https://github.com/hexojs/hexo-generator-index/pull/51

**Comment by stevenjoezhang** [comment]
Node.js 12 supports esm `import` `export` without `--experimental-modules` flag

Automated ESM conversion tools: https://github.com/lebab/lebab https://github.com/wessberg/cjstoesm
(Both of them could not perfectly handle naming conflicts of `const` and `import`)

**Comment by stevenjoezhang** [comment]
Closed by #4750
