### ISSUE TITLE
Why can't I search my website through search engine ?

### ISSUE THREAD

**Issue by pxim** [hexojs/hexo#4384]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

``` 
``` 
 node v12.14.0  
 npm v6.14.5  

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

I have submitted relevant information on Baidu, Bing and Google's webmaster platform .
site:  https://pxi.gitee.io
baidu:
![image](https://user-images.githubusercontent.com/5111701/85935359-88995c00-b922-11ea-8d1d-73eb9619df21.png)
![image](https://user-images.githubusercontent.com/5111701/85935361-93ec8780-b922-11ea-9293-7457e4aaea57.png)
![image](https://user-images.githubusercontent.com/5111701/85935394-dada7d00-b922-11ea-8130-3dc3f1c20e85.png)

bing:
![image](https://user-images.githubusercontent.com/5111701/85935399-f04fa700-b922-11ea-8f9f-777792d12bcb.png)
![image](https://user-images.githubusercontent.com/5111701/85935430-53413e00-b923-11ea-8fad-44fbe6317011.png)
![image](https://user-images.githubusercontent.com/5111701/85935435-5dfbd300-b923-11ea-95ab-69cd6e16ae40.png)

google:
![image](https://user-images.githubusercontent.com/5111701/85935455-8a175400-b923-11ea-8f9c-710732757590.png)
![image](https://user-images.githubusercontent.com/5111701/85935462-ad420380-b923-11ea-8e7a-b2877ca451db.png)
![image](https://user-images.githubusercontent.com/5111701/85935472-c9de3b80-b923-11ea-8d8e-a50fbf3811ec.png)

At present, only Google can search my website, and no other search engine can search my website information

**Comment by SukkaW** [comment]
Submitting sitemap does nothing help to search engine indexing.

Trying to make more meaningful content rather than `创建npm和发布流程`.

Also there are many 404 links on your blog, e.g:

```
https://pxi.gitee.io/2020/06/03/Threejs/%E3%80%90Threejs%E3%80%91%E5%BC%80%E5%8F%91%E7%BB%8F%E9%AA%8C%E9%9B%86/
https://pxi.gitee.io/2020/05/25/Markdown/markdown%E5%86%99%E4%BD%9C%E5%B8%AE%E5%8A%A9/
https://pxi.gitee.io/2019/08/23/Old/React%20%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/
```

Having your posts 404 is also bad for SEO.

Try removing all 404 posts and creating some meaningful content. There's a post that might help: https://blog.skk.moe/post/how-to-write-for-seo/.

**Comment by pxim** [comment]
> Submitting sitemap does nothing help to search engine indexing.
> 
> Trying to make more meaningful content rather than `创建npm和发布流程`.
> 
> Also there are many 404 links on your blog, e.g:
> 
> ```
> https://pxi.gitee.io/2020/06/03/Threejs/%E3%80%90Threejs%E3%80%91%E5%BC%80%E5%8F%91%E7%BB%8F%E9%AA%8C%E9%9B%86/
> https://pxi.gitee.io/2020/05/25/Markdown/markdown%E5%86%99%E4%BD%9C%E5%B8%AE%E5%8A%A9/
> https://pxi.gitee.io/2019/08/23/Old/React%20%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/
> ```
> 
> Having your posts 404 is also bad for SEO.
> 
> Try removing all 404 posts and creating some meaningful content. There's a post that might help: https://blog.skk.moe/post/how-to-write-for-seo/.

I'm not familiar with the management of this website. I'd like to consult .
If a website has several 404 pages, other pages can not be found ?
Why can Google find it? Baidu and Bing can't .
