### ISSUE TITLE
Accessing non-existent property 'xxx' of module exports inside circular dependency in Node.js 14.x

### ISSUE THREAD

**Issue by Himself65** [hexojs/hexo#4397]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## Expected behavior

running without warnings.

## Actual behavior

```powershell
$ hexo server
(node:3524) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3524) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:3524) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:3524) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:3524) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:3524) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.

```

## How to reproduce?

```bash
npm install -g hexo-cli
npx hexo init hexo-test
cd hexo-test
yarn server
```

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```powershell
PS C:\Users\Himself65\desktop\github\test\hexo-test> node -v
v14.5.0
PS C:\Users\Himself65\desktop\github\test\hexo-test> npm -v
6.14.5
```

## Others

`Node.js 14` landed a feature which will log when circular dependency

Refs: https://github.com/nodejs/node/issues/32987

**Comment by stevenjoezhang** [comment]
It's caused by stylus, not Hexo

**Comment by Himself65** [comment]
Thanks.

Closing

**Comment by Rakenfor** [comment]
I had the same error, but it is that you are calling said module itself or calling a module that depends on it, generating this in a loop, try to find said package
