### ISSUE TITLE
When I do 'hexo g', it happened without my except. 

### ISSUE THREAD

**Issue by liuminchao123** [hexojs/hexo#4399]
ERROR:
`
ERROR Asset render failed: css/main.css
Error: d:/Myblog/blog/node_modules/stylus/lib/functions/index.styl:14:5
   10| // require a color
   11|
   12| require-color(color)
   13|   unless color is a 'color'
   14|     error('RGB or HSL value expected, got a ' + -string(color))
-----------^
   15|
   16| // require a unit
   17|

RGB or HSL value expected, got a null
`
it made my blog downtime. 
And I can't fit it.
Hope that the big brother will give a solution.

**Comment by jiangtj** [comment]
This seems to be the error reported by stylus renderer, which theme are you using?

**Comment by liuminchao123** [comment]
@jiangtj 
Next

**Comment by liuminchao123** [comment]
@jiangtj 
When I use Next, it happens. But I use other themes, it disappears.

**Comment by jiangtj** [comment]
Have you changed the theme configuration file? What version of hexo and next are you using?
