### ISSUE TITLE
My blog/source/_posts has one blog but when I visit my blog ,I can find five.I have tried "hexo d " and "hexo g".It do'nt work

### ISSUE THREAD

**Issue by Zhangang1999** [hexojs/hexo#4406]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by Himself65** [comment]
Can you show your repo to let us reproduce?
