### ISSUE TITLE
Tag plugin async callback

### ISSUE THREAD

**Issue by visioncan** [hexojs/hexo#441]
I'm tried to extend Tag plugin for `<img>` tag from Filckr, I use `async` and `request` to fetch FlickrAPI json. but callback can't waiting for output.
I think that is because of async.

How can make this work?
thank you and your awesome Hexo! :smile:

**Comment by akfish** [comment]
@tommy351 And now filter plugins don't have async method. Am I missing something?

**Comment by tommy351** [comment]
@akfish Filter plugins still support async method. You need to use promise instead.

**Comment by akfish** [comment]
@tommy351 Thanks for the information.
