### ISSUE TITLE
data-checked-head="true" is added automatically in the script tag?

### ISSUE THREAD

**Issue by abhishekgautam101** [hexojs/hexo#4427]
I am adding Google Adsense Auto Ads verification script in the head tag of my Hexo blog which has clean-blog theme installed. The original script is
```
<script data-ad-client="ca-pub-8344324360472051" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
```
But upon deployment it adds a new attribute data-checked-head="true" in the script tag, and makes the script as shown below
```
<script data-ad-client="ca-pub-8344324360472051" async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" data-checked-head="true"></script>
```
Because of this change which Hexo does automatically, Google fails to verify my website. Please help!

**Comment by SukkaW** [comment]
Can your confirm whether the Hexo-generated HTML has `data-checked-head="true"` attribute?

Open the `public` directory and open any HTML file and check again then.

**Comment by abhishekgautam101** [comment]
I have checked Hexo generated public folder, it does not have data-checked-head='true' attribute. It appears after I do 'hexo deploy' and inspect blog on browser

**Comment by SukkaW** [comment]
So where do your blog deploy to? GitHub or your own server? Try to check the deployed HTML to see if there is any `data-checked-head="true" ` attribute.

**Comment by abhishekgautam101** [comment]
It deployed on heroku

**Comment by abhishekgautam101** [comment]
How can I see deployed HTML ? There is no option to edit deployed code on heroku.

**Comment by abhishekgautam101** [comment]
Don't bother. I made myself a custom theme for blogger and switched my blog there.

**Comment by HCHJEONG** [comment]
Look at this:

You need to break the snippet you just copied into two scripts.

```
<script async src="//pagead2 ... "></script>

<script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-xxxxxxxxxxxxxxxxxxxx",
        enable_page_level_ads: true
      });
</script>
```

In this way, you are supposed to use javascript code to set ads attribute "true" instead of just pasting the snippet.
