### ISSUE TITLE
Post Processor: about race condition

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#4430]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question

According to https://github.com/hexojs/hexo/commit/9ba40f4dd5894c20905a5380020833da8275015a

> Parallel processing and parallel generating may cause race conditions. We have to solve this in warehouse.

And in https://github.com/hexojs/hexo/commit/9ba40f4dd5894c20905a5380020833da8275015a#diff-18267fb4b13330715876832e13d9697fR83 it says:

> FIXME: Data may be inserted when reading files. Load it again to prevent race condition. We have to solve this in warehouse.

@tommy351 Would you mind providing information about "race condition" and how to trigger it? I have no idea about how to reproduce it and don't know which warehouse function is the culprit.

## Others

By removing the line `const doc = Page.findOne({source: path});` the generation speed is about 20% faster.

**Comment by tommy351** [comment]
I don't remember the detail at this moment. It may be related to file watch I guessed? I will try to look into the source code later.

**Comment by SukkaW** [comment]
@tommy351 Thanks very much!

**Comment by SukkaW** [comment]
unstale
