### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by qianglinc** [hexojs/hexo#4432]
## Check List

Please check followings before submitting a new issue.

- [x]  I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
Node.js v12.18.2
NPM 6.14.6
```

**Your site `_config.yml`** (Optional)

```
theme: hexo-theme-matery
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /blog
├── hexo@4.2.1
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-search@2.4.0
├── hexo-generator-tag@1.0.0
├── hexo-prism-plugin@2.3.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo-wordcount@6.0.1

```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.2.1",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-prism-plugin": "^2.3.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-wordcount": "^6.0.1"
  }
}

```

## Others

The following problems will occur when accessing the home page through the domain name. After the first request is initiated, it will wait for a period of time before loading the second request

Through the packet capture, I found a POST request package to Google. For some reasons, my region can't access Google

```
POST /safebrowsing/clientreport/realtime HTTP/1.1
Host: safebrowsing.google.com
Connection: close
Content-Length: 36
Content-Type: application/octet-stream
Sec-Fetch-Site: none
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Accept-Encoding: gzip, deflate


 http://leelemonm.cn/  

```
photo:

-  [1](https://test-1259576427.cos.ap-nanjing.myqcloud.com/20200719202538.png)
-  [2](https://test-1259576427.cos.ap-nanjing.myqcloud.com/20200719222547.png)

**Comment by stevenjoezhang** [comment]
Can not reproduce. It might be caused by Browser plugins.
<img width="1792" alt="截屏2020-07-20 下午12 55 16" src="https://user-images.githubusercontent.com/16272760/87901007-74abca80-ca88-11ea-9f11-3ba6fff1a6cb.png">
