### ISSUE TITLE
Private posts with hexo

### ISSUE THREAD

**Issue by jehy** [hexojs/hexo#4433]
## Check List

Please check followings before submitting a new feature request.

- [X] I have already read [Docs page](https://hexo.io/docs/)
- [X] I have already searched existing issues

## Feature Request

There is a plugin for hiding private posts - `hexo-hide-posts` - but it does't hide post if it is accessed directly, post is left in repo data and can be easily found and also I think that it should be a part of base hexo itself. It should be really simple - hexo should just skip reading this post if it has a private flag.

Of cause, it means that post will only be readable via source file, but I think that it's exactly what we need for private posts.

We would need to add a notice that private posts need private hexo repos, but this is also fine and clear.

**Comment by stevenjoezhang** [comment]
You can use drafts: https://hexo.io/docs/writing#Drafts

**Comment by jehy** [comment]
@stevenjoezhang Using drafts is pretty much indirect, messy and dangerous way. Real drafts will be in the same place as private posts, without any difference, and it is possible to accidentially publish them.

**Comment by jehy** [comment]
Added a simple PR which implements this feature.

**Comment by curbengh** [comment]
> Private posts are not drafts, that's completely another feature.

but https://github.com/hexojs/hexo/pull/4435 is functionally similar to drafts? My understanding of a private post is that the post is still rendered, but a reader (pre-approved by the blogger) needs to login to view it.

---

btw, a post/page is skipped whenever it has an underscore prefix `_foo.md`, this is another way of setting an article as draft; except for `_posts`, any files inside a folder with an underscore prefix are skipped.

**Comment by jiangtj** [comment]
Hexo won't read outside the source folder file, you may be able to create a `secret` folder outside. 

> a post/page is skipped whenever it has an underscore prefix

Or underlined folders, the articles inside will also be ignored, e.g. `_secret`

**Comment by jiangtj** [comment]
I still don't understand why the function of hiding is needed.

If you don’t need the article to be rendered and displayed, you can create a new private repo for storage.

**Comment by curbengh** [comment]
> https://github.com/hexojs/hexo/issues/4433#issuecomment-678865598
> If you don’t need the article to be rendered and displayed, you can create a new private repo for storage.

I believe that's what OP meant

> https://github.com/hexojs/hexo/issues/4433#issue-663563013
> We would need to add a notice that private posts need private hexo repos

---

One idea is to utilise to have a front-matter like:

```
---
title: a private post
redirect: https://github.com/user/private-repo/blob/source/source/_posts/a-private-post.md
---
```

The post still shows up on index page, but viewing it will be 302-redirect to the repo link.
It's quite similar to [hexo-generator-alias](https://github.com/hexojs/hexo-generator-alias) but it's mostly limited to internal redirect, redirecting a post to external link requires two aliases.

**Comment by jehy** [comment]
> I still don't understand why the function of hiding is needed.
> 
> If you don’t need the article to be rendered and displayed, you can create a new private repo for storage.

Yup, I don't want article to be displayed. But I have already a public blog, and I don't want to make another one.
With hexo workflow and my PR, it works great - I have a private repo which contains all posts, and some of them are marked as private.
And I have a public repo on github.io which is automatically published from the private one via github actions, and it only contains public posts and assets.

Of cause, there can be thousands of workarounds like drafts, redirects, layouts and so on. But why not have a simple and clear feature of private posts?

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-generator-alias/pull/48 seems to be quite close to what you want.

```
---
title: a private post
redirect: https://github.com/user/private-repo/blob/source/source/_posts/a-private-post.md
---
```

**Comment by jehy** [comment]
> [hexojs/hexo-generator-alias#48](https://github.com/hexojs/hexo-generator-alias/pull/48) seems to be quite close to what you want, unless you prefer not to have the private post's link (/2020/01/02/a-private-post) and its title show up in index page.

Private post with public title aren't much private :)

> `private: true` as implemented in #4435 is not accurate because Hexo wouldn't know whether the repo is private,

Hexo does not need to know anything about it. Post will be private and excluded from everywhere if source repo is private. It seems obvious - how else can you expect any content to be private in public repo?

> using layout: 'draft' syntax is more accurate to its function. #4435 is essentially setting an article as draft, so it is actually a workaround itself to emulate a private post.

#4435 does not set article as draft, is simply removes it from any index and doesn't mess with draft system. Drafts and private posts should be completely different entities.

**Comment by curbengh** [comment]
> Private post with public title aren't much private

Depends on one's need, some may prefer to keep only the content private.

> Post will be private and excluded from everywhere if source repo is private.

Well, a post will only be private _if_ the source is private.

> Drafts and private posts should be completely different entities.

In https://github.com/hexojs/hexo/pull/4435, they are practically the same. They're not necessarily completely different, I never mention that `hexo publish` has to support `layout: 'draft'`.

---

I suggest `publish: false` since it doesn't assume private repo nor conflict with draft.

**Comment by jehy** [comment]
> Same possibility that a user could make a typo on the front-matter (e.g. `privatr: true`) and the private post then get published.

Yup, but this way you can only accidentally publish one post. While when using drafts - you can accidentially publish all of them at once.

> I suggest publish: false since it doesn't assume private repo nor conflict with draft.

Yeah, that looks fine too.

**Comment by jehy** [comment]
@curbengh Oops, while I changed `private:true` to `publish:false`, I found out that we already have property `published`, and those will create a mess :(

**Comment by darekkay** [comment]
Isn't [hexo-hide-posts](https://www.npmjs.com/package/hexo-hide-posts) what you're looking for?

**Comment by jehy** [comment]
> Isn't [hexo-hide-posts](https://www.npmjs.com/package/hexo-hide-posts) what you're looking for?

No, I already described it in feature request.

**Comment by stevenjoezhang** [comment]
Regarding your initial requirement:
> Of cause, it means that post will only be readable via source file, but I think that it's exactly what we need for private posts.

You can place the article outside of Hexo's source folder, and it won't be processed. For example, as mentioned in the previous discussion, you can create a `_secret` folder to store these articles. I will close this feature request.
