### ISSUE TITLE
Option to specify db.json directory

### ISSUE THREAD

**Issue by jehy** [hexojs/hexo#4434]
## Check List

Please check followings before submitting a new feature request.

- [X] I have already read [Docs page](https://hexo.io/docs/)
- [X] I have already searched existing issues

## Feature Request

My db.json is already 9MB. Everything still works fine, but my IDE tries to index it and becomes slow. Also, when I search for data in project, search is also performed into db file, which isn't needed. IDEA IDE can exclude directory from index, but can't exclude particular file. Can we add an option to change db.json directory?

**Comment by stevenjoezhang** [comment]
Use `output` arg:
https://github.com/hexojs/hexo/blob/c0bf22284c0c2e85bcd5c94b11823d86a0072035/lib/hexo/index.js#L141-L150
