### ISSUE TITLE
[Proposal] Migrate benchmark to GitHub Action

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#4437]
- [x] Add `benchmark.js` to GitHub Action and remove it from Travis CI
- [x] Rewrite `profiling.sh` into `profiling.js` (And profiling will stay on Travis CI)
- [x] Find a new place to deploy the flamegraph (Maybe the JSON format of performance data as well)
- [x] Add `profiling.js` to GitHub Action along with new deployments, then remove the profiling from Travis CI
- [ ] Use @hexobot to post comment about the performance & flamegraph url under every PR & commits (just like coverall)

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/pull/4413
