### ISSUE TITLE
Idea: use themes as npm packages

### ISSUE THREAD

**Issue by jehy** [hexojs/hexo#4441]
## Check List

Please check followings before submitting a new feature request.

- [ x] I have already read [Docs page](https://hexo.io/docs/)
- [x ] I have already searched existing issues

## Feature Request
I really liked the idea that hexo plugins are npm packages. But I think that we could apply same approach to hexo themes. Then themes will be easier to update, semantic versioning will be applied, and they will be excluded from version control. Also it would be easier to build themes from source - as npm packages, they will simply have all neccesary dev dependencies.

I already tried this approach on current hexo and it worked with several small hacks:

1) fork theme you like
2) add package.json to theme repo
3) install theme from GitHub as dependency in your blog: `"theme-light": "git+https://github.com/jehy/hexo-theme-light.git"`
4) add post install script which adds symlink to package in `themes` directory: `"postinstall": "ln -snf ../node_modules/theme-light themes/light"`

I really like how simpler everything bacame after it. Official support for this feature would be great.

**Comment by stevenjoezhang** [comment]
This feature will be part of the Hexo 5.0 release. See also https://github.com/hexojs/hexo/issues/3890 https://github.com/hexojs/hexo/issues/2471

**Comment by jehy** [comment]
Great, thanks!
