### ISSUE TITLE
Injector does not bind function to hexo object

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo#4446]
Noticed in https://github.com/hexojs/hexo-math/pull/130

In `filter`, the function is automatically binded to `hexo`,

``` js
hexo.extend.filter.register('after_post_render', require('./lib/filter'))
```

``` js
function filterFn(str, data) {
  // this works
  const mathCfg = this.config.math
  return str
}
```

However, that style doesn't work in injector,

``` js
hexo.extend.injector.register('head_end', require('./lib/inject'))
```

``` js
function injectFn() {
  // doesn't work
  const mathCfg = this.config.math
  return `<lorem>${mathCfg.css}</lorem>`
}
```

I need to manually bind it,

``` js
hexo.extend.injector.register('head_end', require('./lib/inject').bind(hexo))
```

**Comment by stevenjoezhang** [comment]
Tags are not bound either. Most of them use a function as return value, e.g.

https://github.com/hexojs/hexo/blob/add6c0068131a161716813f47c4ff49a7c945d13/lib/plugins/tag/asset_img.js#L13-L16

**Comment by curbengh** [comment]
probably most tags don't need to access the config; meanwhile injector inserts to all pages by default and may need to inserts some config value, especially for inserting to `<head>`.

**Comment by SukkaW** [comment]
> In `filter`, the function is automatically binded to `hexo`,

It is not binding. Filter is using Reflect.apply to force the code run in hexo context.

**Comment by curbengh** [comment]
The original proposal https://github.com/hexojs/hexo/issues/4047 mentioned the injector is designed as a convenient wrapper around `after_render:html`

> Currently the only option is to used `hexo.extend.filter.register('after_render:html', (str, data)` and `(/<\/body>/gi.test(htmlContent))` or `s.replace(/<\/head>/, htmlContent + '</head>')` to inject custom HTML snippet.

If Injector is suitable for that use case, a dev might replace existing filter with injector without `String.replace()`. If existing filter has `this.config`, the new code doesn't work without binding. indeed, the docs can mention Injector needs binding, but since Injector is seen as a replacement (for that use case), it feels strange Filter doesn't need binding, while Injector needs it.

> Filter is using Reflect.apply to force the code run in hexo context.

why not run Injector in hexo content?

**Comment by SukkaW** [comment]
> why not run Injector in hexo context?

`Injector` is designed to insert code snippet that is not depended on current HTML content (That's why `meta_generator` remains a feature) and won't change across pages (It requires binding locals). `Injector` is suitable for:

- Insert Analytics SDK
- Insert dependencies for plugins (video/player players, third-party syntax highlighting)

In short, `Injector` serves as a replacement for deprecated [hexo-inject](https://github.com/hexojs/hexo-inject).

**Comment by SukkaW** [comment]
> However, that style doesn't work in injector,

```js
hexo.extend.injector.register('head_end', require('./lib/inject')(hexo))

// ===============

module.exports = (hexo) => () => {
  const mathCfg = hexo.config.math
  return `<lorem>${mathCfg.css}</lorem>`
}
```

It is a possibly workaround.

**Comment by stevenjoezhang** [comment]
> It is an idea from functional programing. A function that "exports" will return another function to be called.

This is exactly how Hexo handles tags. Can be traced back to this commit in 2014

https://github.com/hexojs/hexo/commit/3323364f3a81b539f303f6dec4ae666bb3c34dcc
