### ISSUE TITLE
WARN  Deprecated config detected: "use_date_for_updated" is deprecated, please use "updated_option" instead.

### ISSUE THREAD

**Issue by iwyang** [hexojs/hexo#4450]
`hexo s`后，提示：
```
INFO  Validating config
WARN  Deprecated config detected: "use_date_for_updated" is deprecated, please use "updated_option" instead. See https://hexo.io/docs/configuration for more details.
```
这是什么问题呀！

**Comment by jiangtj** [comment]
https://hexo.io/docs/configuration#Date-Time-format

This configuration item has been updated, please refer to the document to modify

Deprecated: the current version has done forward compatible, but does not guarantee that future versions support the configuration.

Please modify in time

**Comment by curbengh** [comment]
_config.yml

``` yml
use_date_for_updated: true # deprecated
```

``` yml
updated_option: date # use this
```
