### ISSUE TITLE
FR: Install theme's dependencies into the site directory before a build

### ISSUE THREAD

**Issue by outloudvi** [hexojs/hexo#4453]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request
Some themes (e.g. [Hive](https://github.com/farnaziifz/hive-hexo) and [Overdose](https://github.com/HyunSeob/hexo-theme-overdose)) would require additional renderers (e.g. `hexo-renderer-sass`) or other npm packages (e.g. `jquery`) during their build, but currently there is no way for a theme to install them except for asking users to install them manually. If Hexo can install the theme dependencies automatically to the site, installing and changing themes will be easier.

**Comment by stevenjoezhang** [comment]
> but currently there is no way for a theme to install them except for asking users to install them manually

Actuanlly, there are two ways to install dependencies.:
1. Install theme through npm. All the dependencies of the theme will be installed automatically
2. Use `postinstall` script in `package.json`

However, the two themes you mentioned have not been updated for years. You need to contact the maintainer to publish them on npm.

**Comment by outloudvi** [comment]
@stevenjoezhang Got it. Thank you for your reply!

**Comment by jerryc127** [comment]
i have a same question.
the theme need the hexo-renderer-pug
so i add to the theme‘s package.json

I install the theme use npm.
but i run the hexo, it seen like the hexo not detect the hexo-renderer-pug
![image](https://user-images.githubusercontent.com/16351105/89176452-289a7300-d5bc-11ea-9c08-4e3dfcef1f89.png)

**Comment by SukkaW** [comment]
@jerryc127 Further discussion about hexo plugin please join here: https://github.com/hexojs/hexo/issues/3890#issuecomment-667913944
