### ISSUE TITLE
Image cannot be load by relative path using markdown syntax

### ISSUE THREAD

**Issue by v-tawe** [hexojs/hexo#4454]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
12.16.2
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 E:\Blog
+-- hexo@5.0.0
+-- hexo-all-minifier@0.5.3
+-- hexo-asset-image@1.0.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-all-minifier": "^0.5.3",
    "hexo-asset-image": "^1.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

```

## Others

when using markdown syntax involved image `![Hello](hello.png)`, the render link is `https://xxxx/.io//hello.png`, so weird there contains a **.io/** in the link.

Already enabled `post_asset_folder: true` and had put the images under correspond asset folder。

https://v-tawe.github.io/2020/07/31/fluid-guide-1/#%E6%96%87%E7%AB%A0%E5%86%85%E5%AE%B9%E5%9B%BE%E7%89%87

**Comment by curbengh** [comment]
Do you change any config of [hexo-theme-fluid](https://github.com/fluid-dev/hexo-theme-fluid)? Can you attach your site config?

**Comment by SukkaW** [comment]
@curbengh 

For themes like NexT it not only shows the content at the post page about also at the index. Thus, the same `<img>` element will have different root.

**Comment by SukkaW** [comment]
@curbengh A solution is that we could modify the behavior of `hexo-renderer-marked`, utilizing `url_for()` for `image` element renderer, make sure every src of `<img>` will be resolved correctly.

But it will also affect user that highly relied on relative path (e.g. Hosting a blog at IPFS)

**Comment by curbengh** [comment]
> For themes like NexT it not only shows contents at the post page about also at the index.

I see, many themes also show post's excerpt at the index and excerpt might contain a image.

> utilizing `url_for()` for image element renderer, make sure every src of `<img>` will be resolved correctly.

It's already [utilised](https://github.com/hexojs/hexo-renderer-marked/blob/0000e3af02181b6821913be56d7672a2c0b17add/lib/renderer.js#L90) to prepend root. But I agree `image` renderer needs improvement to support `post_asset_folder`, but not through `url_for()` because I don't think it should cover `post_asset_folder`.

**Comment by liolok** [comment]
https://liolok.github.io/How-to-Add-Image-to-Hexo-Blog-Post/

**Comment by curbengh** [comment]
I managed to port [asset_img](https://hexo.io/docs/tag-plugins#Include-Assets) tag plugin to hexo-renderer-marked, see https://github.com/hexojs/hexo-renderer-marked/pull/159.

How to test:
1. `$ npm install hexo-renderer-marked@curbengh/hexo-renderer-marked#post-asset`
2.
  ``` yml
  #_config.yml
  post_asset_folder: true
  marked:
    prependRoot: true
    postAsset: true
  ```

**Comment by liolok** [comment]
No, the tag plugin syntax was never what users want.

**Comment by liolok** [comment]
Sorry to say that, but wrong direction.

**Comment by SukkaW** [comment]
@liolok 

> Sorry to say that, but wrong direction.

If so, *personally* I will have to blame the theme, and start removing `post_assets_folder` feature (Hugo has no `post_asset_folder` as well). I am sorry to say, if you want markdown, then there will be only one version HTML being generated.

Stop asking serving different version of HTML at different pages. It just won't work.

@curbengh I am thinking removing `post_asset_folder` feature, forcing user to manage their image in `_source` folder directly, no image resolving will be involved at our side. Another idea is forcing `url_for` for all images, always generate absolute path for all images.

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/3245

**Comment by liolok** [comment]
Hugo has no `post_asset_folder` ~~but seems to do the work naturally without theme.~~

Okay I checked and the links in Hugo stay the same, so pictures in home page summary will not correctly rendered. 

But at least the links that work in markdown source do the same in post page, in Hexo with `post_asset_folder=true`, they don't, which is weird to most users.

Introducing a tag plugin syntax didn't make all the users happy, in fact I saw pretty few people settled down with that.

However I advise that deprecate the `post_asset_folder` feature rather than complete removal, to avoid break the use case of "few people" above.

For new users Hexo does the same as Hugo about page resources, which is simply copy and paste them to `/public`, no strange non-markdown syntax, no confusing relative path converting. Let the plugins and themes do whatever they want.

**Comment by curbengh** [comment]
> No, the tag plugin syntax was never what users want.

https://github.com/hexojs/hexo-renderer-marked/pull/159 prepends the post path to image path:

``` yml
#_config.yml
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
```

- **postAsset** - Resolve post asset's image path to relative path and prepend root valuewhen [`post_asset_folder`](https://hexo.io/docs/asset-folders) is enabled.
  * "image.jpg" is located at "/2020/01/02/foo/image.jpg", which is a post asset of "/2020/01/02/foo/".
  * `![](image.jpg)` becomes `<img src="/2020/01/02/foo/image.jpg">`

No tag plugin syntax required, `![](image.jpg)` markdown syntax will be rendered to `<img src="/2020/01/02/foo/image.jpg">`. The option `postAsset` option is disabled by default for now, it may be enabled by default in future once deemed stable (along with `prependRoot`).

Please help test https://github.com/hexojs/hexo-renderer-marked/pull/159, I tested in Ubuntu and non-WSL Windows 10.
