### ISSUE TITLE
page.prev_link is empty, when index is on page 2

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [hexojs/hexo#4458]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## How to reproduce?
1. Clone the demo repository. https://github.com/DeepSpaceHarbor/hexo-demo-bug
2. npm i
3. hexo server
4. Go to http://localhost:4000/page/2/
5. Check the previous page button
6. Check the console

## Expected behavior
According to the [hexo documentation](https://hexo.io/docs/variables#Page-Variables) the page.prev_link should contain the link to the previous page.

## Actual behavior
page.prev_link is an empty string.
![image](https://user-images.githubusercontent.com/11393457/89121262-afb4f180-d4bd-11ea-9ddb-9d660b613eec.png)

The relevant code, can be found here: https://github.com/DeepSpaceHarbor/hexo-demo-bug/blob/103587453810a37905b730e412cd5a9dfed1cffb/themes/Space-Station-Operator/layout/_partial/page/pagination.ejs#L6

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v14.7.0
6.14.5
```

**Comment by stevenjoezhang** [comment]
`page.prev_link` is only supported in post page (e.g. `post.ejs` in layout). It's not working in `index.ejs` and `tag.ejs` in Space-Station-Operator theme. The `paginator` helper should be used instead.
