### ISSUE TITLE
auto Open markdown file after running hexo new in ubuntu?

### ISSUE THREAD

**Issue by penetrater** [hexojs/hexo#4459]
## Check List

Please check followings before submitting a new feature request.

- [ ] I have already read [Docs page](https://hexo.io/docs/)
- [+] I have already searched existing issues

## Feature Request
https://github.com/hexojs/hexo/issues/1007
`var spawn = require('child_process').spawn;

// Hexo 2.x
hexo.on('new', function(path){
  spawn('vi', [path]);
});

// Hexo 3
hexo.on('new', function(data){
  spawn('vi', [data.path]);
});`
`var spawn = require('child_process').spawn;
 // Hexo 3
hexo.on('new', function(data){
spawn('vim', [data.path], { stdio: 'inherit' });
});`

None of these will automatically open the new file.（in ubuntu20）
ubuntu 20 error
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn typora --no-sandbox ENOENT`
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn sudo bash -c typora ENOENT
`

**Comment by stevenjoezhang** [comment]
There is a discussion about it: #4242
I'm closing this issue. Please join the discussion there :)
