### ISSUE TITLE
Scripts are not loaded when theme is located in node_modules

### ISSUE THREAD

**Issue by oncletom** [hexojs/hexo#4461]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## Expected behavior

When I install a theme with npm (eg: `npm i hexo-theme-next`), and I use one of its defined "tags" (as of Nunjuck tags), I expect it to be available in my content.

## Actual behavior

When I install a theme with npm (eg: `npm i hexo-theme-next`), and I use one of its defined "tags" (as of Nunjuck tags), and start the development server (`hexo server`) I face an error which indicates me hexo does not about this "tag".

## How to reproduce?

* Install hexo
* Install a theme via npm
* Write an article with a tag (like [caniuse tag](https://github.com/next-theme/hexo-theme-next/blob/master/scripts/tags/caniuse.js)
* Face the error:

```
err: Error [Nunjucks Error]: _posts/blah.md [Line 5, Column 4] unknown block tag: caniuse
```

## Is the problem still there under "Safe mode"?

Yes, because it is related to plugins/themes.

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v12.16.0
6.13.4
```

**Your site `_config.yml`** (Optional)

```yaml
theme: 'hexo-theme-next'
theme_dir: node_modules
```

**Comment by stevenjoezhang** [comment]
Replace
```
theme: 'hexo-theme-next'
```

With
```
theme: next
```

And remove

```
theme_dir: node_modules
```

In Hexo `_config.yml`, then try again.

**Comment by oncletom** [comment]
Yes indeed, it works!

I would not have guessed this by reading the doc.

Question: what if the theme is hosted under an organization name, like `@foo/hexo-theme-bar`? Or if I want to call it `@myuser/hexo-theme`?

**Comment by SukkaW** [comment]
> what if the theme is hosted under an organization name, like `@foo/hexo-theme-bar`?

Theme hosted under an organization hasn't been supported yet.

**Comment by oncletom** [comment]
Gotcha.

Thanks for answering me 👍
