### ISSUE TITLE
Hexo deployment is successful, but the blog address cannot be accessed

### ISSUE THREAD

**Issue by Tommy0604** [hexojs/hexo#4463]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
v12.13.1 & 6.12.1
```

**Your site `_config.yml`** (Optional)

```
url: http://XXXXXX.github.io/

deploy:
  type: git
  repo: git@github.com:XXXXXX/XXXXXX.github.io.git
  branch: master

```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-cli: 4.1.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}

```

## Others

`hexo s ` success 
`hexo d` success 
但是部署到github后，

无法访问此网站
网址为 https://XXXXXX.github.io/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_ADDRESS_INVALID

But after deployment to making, unable to access this web site is https://XXXXXX.github.io/ web page may be temporarily unable to connect, or it has permanently moved to a new url.

**Comment by SukkaW** [comment]
Please check your network first. If your network environment is fine, you will still be able to see GitHub 404 even the deployment failed, like this:

![image](https://user-images.githubusercontent.com/40715044/89185190-699a8380-d5cc-11ea-9504-2c6faac494e2.png)

**Comment by Tommy0604** [comment]
> Please check your network first. If your network environment is fine, you will still be able to see GitHub 404 even the deployment failed, like this:
> 
> ![image](https://user-images.githubusercontent.com/40715044/89185190-699a8380-d5cc-11ea-9504-2c6faac494e2.png)

I dont know why this happens, It's normal to visit other blogs😵

**Comment by YoshinoriN** [comment]
@Tommy0604 
I can see your [blog](https://github.com/Tommy0604/Tommy0604.github.io).
May we close this?
