### ISSUE TITLE
bash: hexo: command not found

### ISSUE THREAD

**Issue by zryyyy** [hexojs/hexo#4464]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question
bash: hexo: command not found

## Environment & Settings

**Node.js & npm version**

```
v14.7.0
v6.14.7
```

## Others
$ npm install -g hexo-cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\hexo-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code EEXIST
npm ERR! path C:\Users\zry\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo
npm ERR! dest C:\Users\zry\AppData\Roaming\npm\hexo
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\zry\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo' -> 'C:\Users\zry\AppData\Roaming\npm\hexo'
npm ERR! File exists: C:\Users\zry\AppData\Roaming\npm\hexo
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zry\AppData\Roaming\npm-cache\_logs\2020-08-04T14_30_53_188Z-debug.log

$ npm install -g hexo-cli
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zry\AppData\Roaming\npm-cache\_logs\2020-08-04T14_36_52_701Z-debug.log

$ npm install hexo --save
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\zry\Blog\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\zry\Blog\package.json'
npm WARN Blog No description
npm WARN Blog No repository field.
npm WARN Blog No README data
npm WARN Blog No license field.

+ hexo@5.0.0
added 88 packages from 348 contributors and audited 89 packages in 43.15s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by curbengh** [comment]
Try reinstall:

```
$ npm remove -g hexo-cli
$ npm install -g hexo-cli
```

**Comment by zryyyy** [comment]
still not working


19318@LEGION MINGW64 ~/Blog
$ npm remove -g hexo-cli
up to date in 0.059s

19318@LEGION MINGW64 ~/Blog
$ npm install -g hexo-cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\hexo-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code EEXIST
npm ERR! path C:\Users\zry\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo
npm ERR! dest C:\Users\zry\AppData\Roaming\npm\hexo.ps1
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\zry\AppData\Roaming\npm\node_modules\hexo-cli\bin\hexo' -> 'C:\Users\zry\AppData\Roaming\npm\hexo.ps1'
npm ERR! File exists: C:\Users\zry\AppData\Roaming\npm\hexo.ps1
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zry\AppData\Roaming\npm-cache\_logs\2020-08-10T08_19_10_874Z-debug.log

**Comment by YoshinoriN** [comment]
Please try...

1. delete `C:\Users\zry\AppData\Roaming\npm\node_modules\hexo-cli` & `C:\Users\zry\AppData\Roaming\npm\hexo.ps1`
2. `npm install -g hexo-cli`

**Comment by zryyyy** [comment]
> Please try...
> 
> 1. delete `C:\Users\zry\AppData\Roaming\npm\node_modules\hexo-cli` & `C:\Users\zry\AppData\Roaming\npm\hexo.ps1`
> 2. `npm install -g hexo-cli`

Thank you😘
