### ISSUE TITLE
SEO is not friendly to Chinese

### ISSUE THREAD

**Issue by penetrater** [hexojs/hexo#4466]
## Check List

Please check followings before submitting a new feature request.

- [Y] I have already read [Docs page](https://hexo.io/docs/)
- [Y] I have already searched existing issues

## Feature Request

"例子"：means "demo".

SEO is not friendly to Chinese.
so I hope that after hexo creates a new file，The file name can be encrypted.

for example：
hexo new “例子”
The created file is: 6b7f8c7462c1640611d2e219988d95dd.md

https://www.keylala.cn/aes
text：例子
the key：default（Fill in nothing）
ecb 128bits pcks7 hex
After encryption：6b7f8c7462c1640611d2e219988d95dd
It can also be decrypted.
6b7f8c7462c1640611d2e219988d95dd<------>例子

6b7f8c7462c1640611d2e219988d95dd.md---------SEO is more friendly to such names.
not base64,It contains symbols / .
not hash,It is unidirectional.
I hope the hexo team can support this feature.

cmd like this：hexo new “例子” -e    |  hexo new “例子” e | hexo ennew “例子”
The created file is: 6b7f8c7462c1640611d2e219988d95dd.md

**Comment by SukkaW** [comment]
Please provide the content of your `_config.yml`. I am pretty sure you have your `new_post_permalink` misconfigured.

**Comment by penetrater** [comment]
new_post_permalink: :year-:month-:day-:title.md
but title is chinese

**Comment by penetrater** [comment]
Do you have any good suggestions？
