### ISSUE TITLE
"before_post_render", "after_post_render" executed on non-article page

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo#4468]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## Expected behavior

`before_post_render` and `after_post_render` should only executed on posts and pages.

## Actual behavior

Non-article files (like css) being processed by `before_post_render` & `after_post_render` well.

## Is the problem still there under "Safe mode"?

Yes.

## Other Information

Add following content to `scripts/test.js`:

```js
hexo.on('generateBefore', () => {
    hexo.model('Page').toArray().forEach(i => console.log(i.path));
})
```

And non-article paths will show up.

----

https://github.com/hexojs/site/pull/1506

cc @curbengh

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/1591

**Comment by SukkaW** [comment]
Interesting:

```bash
$ hexo list page
```

The `list` command is also affected.

**Comment by jiangtj** [comment]
https://github.com/hexojs/hexo/blob/b7d15b95cb7e48b855f9d4c72bc24078b7b7a505/lib/plugins/processor/asset.js#L114-L120

renderable is defined in the pattern, maybe we can add some default value for skip_render

https://github.com/hexojs/hexo/blob/b7d15b95cb7e48b855f9d4c72bc24078b7b7a505/lib/box/index.js#L132-L141

BTW, `pattern.match() => params` is strange. I think it should be `pattern.match() => false/true`

**Comment by curbengh** [comment]
> maybe we can add some default value for skip_render

Tested working. I add a test css in `source/css/test.css`.

``` yml
skip_render:
  - '**.css'
```

``` js
// should not show css
hexo.on('generateBefore', () => {
  hexo.model('Page').toArray().forEach(i => console.log(i.path));
})

hexo.extend.filter.register('before_post_render', function(data){
  if (data.source.endsWith('.md') === false) console.log(data.content.substring(0, 50))
  return data;
});

hexo.extend.filter.register('after_post_render', function(data){
  if (data.source.endsWith('.md') === false) console.log(data.content.substring(0, 50))
  return data;
});
```

`after_render:css` still works:

``` js
// should show css
hexo.extend.filter.register('after_render:css', function(str, data){
  console.log(str.substring(0, 50))
  console.log(data.path)
  return str
});
```

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/blob/b7d15b95cb7e48b855f9d4c72bc24078b7b7a505/lib/hexo/post.js#L245-L249

I tried:

``` js
    return promise.then(content => {
      data.content = content;
      // Run "before_post_render" filters
      if (data.source && data.source.startsWith('_posts/')) return ctx.execFilter('before_post_render', data, { context: ctx });
      return
    }).then(() => {
```

Then I realised [backtick_code_block.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/before_post_render/backtick_code_block.js) is a `before_post_render` filter, so if I use that workaround, "backtick_code_block.js" wouldn't execute on page (files outside of "posts/" folder).

To ensure "backtick_code_block.js" still works, we may need a new filter "before_render".
