### ISSUE TITLE
A question about markdown

### ISSUE THREAD

**Issue by pi-dal** [hexojs/hexo#4473]
##### Version
- hexo: 5.0.0
- hexo-cli: 3.1.0
- os: Darwin 19.5.0 darwin x64
- node: 13.11.0
- hexo-site@0.0.0 /Users/pi-dal/pi-dal-blog
├── hexo@5.0.0
├── hexo-algoliasearch@0.4.2
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-markdown-it@4.1.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
##### My _config.yml
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-latex2img
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSide: 'left'
    permalinkSymbol: ¶
##### What I wrote in markdown:
![markdown-wrote](https://i.imgur.com/isdLLMC.png)
##### But it shows as follows:
![markdown-show](https://i.imgur.com/MmQrG7V.png)
##### I want it to be displayed in the following form:
_终端应该是程序员日常使用比较多的工具了吧。对于终端的配置一直是一大**世纪难题**。这次，我将在本文简述如何配置_
##### Thanks😘😘😘

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/issues/3321 https://github.com/hexojs/hexo/issues/2821

**Comment by pi-dal** [comment]
@curbengh These have no effect on my problem.

**Comment by pi-dal** [comment]
@stevenjoezhang I saw it, thanks.
