### ISSUE TITLE
err: Error: Spawn failed, Please help me

### ISSUE THREAD

**Issue by const-love-365-10000** [hexojs/hexo#4480]
## Check List

Please check followings before submitting a new issue.

- [ ✔] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [✔ ] I have already searched existing issues and they are not help  to me
- [✔ ] I examined error or warning messages and it's difficult to solve
- [✔] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [✔ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## My question：
I deployed the hexO to a server, and my site worked fine, but then my server ran out of time, and I switched servers, and I moved all the data from the previous server to the new server, and I ran "Hexo g -d" on my local computer, and there was a problem.
Please help me.
（我将hexo部署到服务器上，在之前我的网站运行正常，但是后来我的服务器到期了，我换了一个服务器，并且把之前服务器的数据全部转移到新的服务器上,当我在本地运行`hexo g -d`时，报错。）
## Error message（报错信息）：
NexT version 8.0.0-rc.5
Documentation: https://theme-next.js.org
========================================
INFO  Start processing
WARN  Since language_switcher is turned on, the caching is disabled to avoid potential hazards.
INFO  Files loaded in 357 ms
INFO  0 files generated in 465 ms
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
On branch master
nothing to commit, working tree clean
ssh: connect to host yujin123.cn port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous>(C:\Users\14258\Desktop\myBlog\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.cp.emit (C:\Users\14258\Desktop\myBlog\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
    code: 128
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
## Expected behavior
  `hexo g -d` ，success.
## Actual behavior
  Error, error message on top
## How to reproduce?

* Step1
    I deleted the.git and.deploy_git files from my local computer, but still no use
    (我删掉了本地电脑里的.git和.deploy_git文件，但是仍然没用)
* Step2
  搞了一整天，实在搞不定
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
```

**Your site `_config.yml`** (Optional)

```yaml
  deploy:
    type: git
    repo: root@yujin123.cn:/www/hexo/repos/blog.git 
    branch: master
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-cli: 4.2.0
os: Windows_NT 10.0.18363 win32 x64
node: 12.17.0
v8: 7.8.279.23-node.37
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.2"
  },
  "dependencies": {
    "hexo": "^5.0.2",
    "hexo-admin": "^2.3.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-searchdb": "^1.3.2",
    "hexo-generator-tag": "^1.0.0",
    "hexo-migrator-wordpress": "^2.1.0",
    "hexo-related-popular-posts": "^5.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^2.0.0",
    "hexo-simple-image": "^1.0.2",
    "hexo-theme-next": "^8.0.0-rc.5",
    "hexo-word-counter": "0.0.2"
  }
}

```

**Comment by stevenjoezhang** [comment]
简单来说就是你的网络无法通过 ssh 连接 GitHub。可以考虑挂个代理。

**Comment by const-love-365-10000** [comment]
> 简单来说就是你的网络无法通过 ssh 连接 GitHub。可以考虑挂个代理。

可是我用的是国内的阿里云服务器，之前用的时候也没挂过代理

**Comment by stevenjoezhang** [comment]
看错了，是你的本地电脑无法连接 yujin123.cn 的 22 端口。可以检查防火墙设置或联系阿里云客服。

**Comment by const-love-365-10000** [comment]
> 看错了，是你的本地电脑无法连接 yujin123.cn 的 22 端口。可以检查防火墙设置或联系阿里云客服。

搞定了😊，是因为我的 known_hosts 文件里保存的是我以前的服务器地址，导致两者冲突，把这个文件删了就行了。
要感谢你给我提供的思路。

**Comment by PlumGarden** [comment]
请问题主具体怎么解决的呀，我也出现了一样的问题，没太看明白是什么出了问题
