### ISSUE TITLE
unespected `hexoPostRenderEscape` appeared

### ISSUE THREAD

**Issue by ChrAlpha** [hexojs/hexo#4481]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## Expected behavior

I wanna use origin highlight.js to render my code. So, I modified the Hexo site `_config.yml` according to the [docs](https://hexo.io/docs/syntax-highlight.html#hljs). 

```
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: false
  tab_replace: ''
```

## Actual behavior

The special highlight.js that modified by Hexo as well as PrismJS works well with no matter how complex content. However, the origin highlight.js mode makes an issue when rendering codeblocks located under other markdown syntax (list, quoteblock, etc).

The origin highlight.js mode is able to render single codeblock properly.

<img width="892" alt="屏幕快照 2020-08-18 上午11 43 15" src="https://user-images.githubusercontent.com/53332481/90468100-5ea52e80-e148-11ea-9b4c-25e5c827894b.png">

But when rendering codeblock **espacially the codeblock located under other markdown syntax**, unespected `hexoPostRenderEscape` appeared.

<img width="931" alt="屏幕快照 2020-08-18 上午11 43 58" src="https://user-images.githubusercontent.com/53332481/90468177-92805400-e148-11ea-8203-a6c5189b2179.png">

In this case, I just wanna render the codeblock under the list (markdown syntax).

```
\`\`\`
sudo yum-config-manager \
--add-repo \
https://download.docker.com/linux/centos/docker-ce.repo
\`\`\`
```

## How to reproduce?

* configure the hexo site `_config.yml` as using the origin highlight.js
* add a codeblock **including more than one line of code** under other markdown syntax such as:
  
  ```
  > ```
  > some codes.
  > 
  > blablabla
  > 
  > blablabla
  > 
  > ...
  > ```
  ```

  (the codeblock under quoteblock)

## Is the problem still there under "Safe mode"?

Yes, it's still there even in "Safe mode".

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
node: v12.18.3
npm: 6.14.7
```

**Your site `_config.yml`** (Optional)

```yaml
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: false
  tab_replace: ''
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /xxx/xxxx
├── gulp@4.0.2
├── gulp-autoprefixer@7.0.1
├── gulp-clean-css@4.3.0
├── gulp-htmlclean@2.7.22
├── gulp-htmlmin@5.0.1
├── gulp-uglify-es@2.0.0
├── hexo@5.0.2
├── hexo-blog-encrypt@3.0.13
├── hexo-cli@3.1.0
├── hexo-deployer-git@2.1.0
├── hexo-filter-nofollow@2.0.2
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@2.2.0
├── hexo-generator-index-pin-top@0.2.2
├── hexo-generator-json-content@4.2.3
├── hexo-generator-seo-better-sitemap@0.0.3
├── hexo-generator-tag@0.2.0
├── hexo-hide-posts@0.1.1
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-less@1.0.0
├── hexo-renderer-marked@3.0.0
├── hexo-renderer-stylus@0.3.3
├── hexo-server@1.0.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.0.2"
  },
  "dependencies": {
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^7.0.1",
    "gulp-clean-css": "^4.3.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-uglify-es": "^2.0.0",
    "hexo": "5.0.2",
    "hexo-blog-encrypt": "^3.0.12",
    "hexo-cli": "^3.1.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-seo-better-sitemap": "0.0.3",
    "hexo-generator-tag": "^0.2.0",
    "hexo-hide-posts": "^0.1.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^1.0.0"
  },
  "devDependencies": {}
}

```

## Others

By reading #4171 #4472, I roughly understand that `hexoPostRenderEscape` is used to prevent rendering markdown syntax in codeblock as markdown is rendered before tag-plugins. But in some complex situations, it will also bring some issues. I am really looking forwards to finding that this issue has been fixed already.

**Comment by SukkaW** [comment]
Should be fixed by #4472 & #4478.

Try `npm i hexojs/hexo` to see if the issue still exists.

**Comment by ChrAlpha** [comment]
Great! None of the problems at the formerly site have recurred! I believe this issue has been fixed well.

By the way, Hexo still goes by the version of `5.0.2` up to now. So, it means that this issue has been fixed already but you haven't published a new release for it, right?

Anyway, it works! thx

**Comment by SukkaW** [comment]
> By the way, Hexo still goes by the version of `5.0.2` up to now. So, it means that this issue has been fixed already but you haven't published a new release for it, right?

Yes.
