### ISSUE TITLE
After upgrading to the latest Hexo, now click on a chapter on the table of contents, and the jump cannot be completed

### ISSUE THREAD

**Issue by asdf2014** [hexojs/hexo#4484]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## Expected behavior

After upgrading to the latest Hexo, now click on a chapter on the table of contents, and the jump cannot be completed.

## Actual behavior

Click on a chapter in the table of contents to immediately jump to the corresponding chapter.

## How to reproduce?

* Open [https://yuzhouwan.com/posts/5845/](https://yuzhouwan.com/posts/5845/)
* Click on a chapter in the table of contents

## Is the problem still there under "Safe mode"?

Yes.

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
latest version
```

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/pull/1540
