### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by KumaNNN** [hexojs/hexo#4486]
## Check List

Please check followings before submitting a new issue.

- [x] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
node: v12.18.1
npm: 6.14.5
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo : 5+
next: 7.8.0
```

## Error(错误)

```
Uncaught TypeError: Cannot read property 'replace' of null
```
![1597952261281](https://user-images.githubusercontent.com/31473722/90820149-83c1b900-e363-11ea-91a8-650e400cca7f.jpg)

### hexo : 5+

next 主题未更新版本号，[fdaf3e3](https://github.com/theme-next/hexo-theme-next/commit/fdaf3e325ca5eaf345dd23c2e16932030c81a64d)  修复了此问题。
Next theme is not updated version number, [fdaf3e3](https://github.com/theme-next/hexo-theme-next/commit/fdaf3e325ca5eaf345dd23c2e16932030c81a64d)  fixes this problem.

### hexo : 4

无错误
No error.

## Solution(解决方案)
使用 [hexo-theme-next:master](https://github.com/theme-next/hexo-theme-next) 中的文件 `next\source\js\utils.js` 覆盖`themes\next\source\js\utils.js`
Overlay `themes\next\source\js\utils.js` with file  `next\source\js\utils.js`  from [hexo-theme-next:master](https://github.com/theme-next/hexo-theme-next).

## Note
如果你遇到同样的问题，可尝试此方案。
If you have the same problem, try this solution.

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo/issues/4484
I'm closing this issue. Please join the discussion there :)
