### ISSUE TITLE
How to modify <HEAD> depending of <BODY> ?

### ISSUE THREAD

**Issue by valeriso** [hexojs/hexo#4491]
## Check List

- [ * ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ * ] I have already searched existing issues and they are not help to me
- [ * ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ * ] Node.js is higher than 8.6.0

## Question
I am trying to use HEXO with AMP HTML, and I want automatically add "<script async custom-element='amp-..."> tags to <HEAD> section after I use AMP in <body>. So, I want to find AMP tags in BODY, find corresponding script tags and insert them into <HEAD>.

Example:
<body>
...
<amp-mega-menu height="40" layout="fixed-height" class="border bg-gray-200">
</amp-mega-menu>
<%- partial('partial/myfile') %>
...
</body>

- then I need to add to <head>:
<HEAD>
...
<script async custom-element='amp-mega-menu' src='https://cdn.ampproject.org/v0/amp-mega-menu-0.1.js'></script>
...
</HEAD>

Firstly I wrote a simple helper and used it in <HEAD>:
hexo.extend.helper.register('test01', function() {
var ampage = this.page["content"];
var answer = "";
var amptags = {};
var result = {};
amptags["amp-3d-gltf"] = "<script async custom-element='amp-3d-gltf' src='https://cdn.ampproject.org/v0/amp-3d-gltf-0.1.js'></script>";
// (and ~50 other AMP tags are here, skiped...)
if (ampage) {
  ampkeys = Object.keys(amptags);
  for (var value of ampkeys) {
    if (ampage.indexOf('<'+value) >=0) {
      result[value] = amptags[value];
    };
  };
  var rkeys = Object.keys(result);
  for (var r of rkeys) {
    answer += result[r] + '\n'
  };
 };
 return answer;
});

It works fine when I use AMP HTML elements in <body>, but this script does not see AMP HTML tags in included <%- partial('partial/myfile') %> files.

I decided that it is necessary to wait end of rendering event, and I wrote second script with after_rendering filter:
hexo.extend.helper.register('test02', function() {
  var answer = "";
  var ans= "";
  var amptags = {};
  var result = {};
  var ampstr;
  amptags["amp-3d-gltf"] = "<script async custom-element='amp-3d-gltf' src='https://cdn.ampproject.org/v0/amp-3d-gltf-  0.1.js'></script>";
  // all other tags were here
  hexo.extend.filter.register('after_render:html', (data) => {
    if(data) {
      let ampage = data
      ampkeys = Object.keys(amptags);
      for (var value of ampkeys) {
        if (ampage.indexOf('<'+value) >=0) {
          result[value] = amptags[value];
        };
      };
      var rkeys = Object.keys(result);
      for (var r of rkeys) {
           answer += result[r] + '\n'
      };
     data = data.replace('</head>', '\n'+answer+'\n</head>')
    }
    return data;
  })
});

Again, it works the same way: all ok with content of <BODY> and ignores content of all <% partial .... %>

How can I get full content of <body> including partials?

## Environment & Settings

**Node.js & npm version**
Node v12.18.3
Npm v6.14.8

**Hexo and Plugin version(`npm ls --depth 0`)**
hexo: 4.2.1
hexo-cli: 4.0.0

**Comment by curbengh** [comment]
The content `partial()` should be already included by the time `after_render:html` is executed.

> I want to find AMP tags in BODY, find corresponding script tags and insert them into.

does AMP tag differ in each article? If they're all similar and the corresponding script tags are similar, [`Injector`](https://hexo.io/api/injector) is more suitable for the job.
