### ISSUE TITLE
图片插入问题

### ISSUE THREAD

**Issue by zznnqq210** [hexojs/hexo#4492]
为啥我md里插入了图片，执行hexo g过后生成的图片路径变成了/.cn/xxx，不知道这个.cn怎么来的？
![image](https://user-images.githubusercontent.com/12114031/90997177-64d95600-e5f3-11ea-993c-bfb1dc71c969.png)
这个图片已经放入和md文件同名的一个文件夹下，且post_asset_folder也设置为true了，求助！
![image](https://user-images.githubusercontent.com/12114031/90997281-b7b30d80-e5f3-11ea-8f3b-b8e1372e8641.png)

**Comment by JackEggie** [comment]
我也遇到了这个问题。

看上去是渲染的时候 asset 的 url 生成错误。我遇到的是在路径前面加了 `.io`，原因可能是 hexo 根配置中的 url 和 root 项的解析错误。

```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jackeggie.github.io/
root: /
permalink: :title/
permalink_defaults:
```

```plain
INFO  Start processing
update link as:-->/.io//git-workflows-gitflow.png
update link as:-->/.io//git-workflows-gitflow.png
update link as:-->/.io//%E6%B5%8B%E8%AF%95%E5%9B%BE%E7%89%87.jpeg
update link as:-->/.io//%E6%B5%8B%E8%AF%95%E5%9B%BE%E7%89%87.jpeg
update link as:-->/.io//jvm-memory-structure.png
update link as:-->/.io//jvm-memory-structure.png
INFO  Files loaded in 1.46 s
```

**Comment by jiangtj** [comment]
> update link as:-->/.io//git-workflows-gitflow.png
> update link as:-->/.io//git-workflows-gitflow.png
> update link as:-->/.io//%E6%B5%8B%E8%AF%95%E5%9B%BE%E7%89%87.jpeg
> update link as:-->/.io//%E6%B5%8B%E8%AF%95%E5%9B%BE%E7%89%87.jpeg
> update link as:-->/.io//jvm-memory-structure.png
> update link as:-->/.io//jvm-memory-structure.png

这个看起来是某个插件输出的，你能删除它再次测试么，如果没问题建议去插件的Repo提交相关issue

**Comment by stevenjoezhang** [comment]
看上去是这个 https://github.com/xcodebuild/hexo-asset-image/blob/3c114cf0c0343ab28469635085b225fcae7fb9d3/index.js#L59
仓库已经 archived 了

**Comment by stevenjoezhang** [comment]
另见 https://github.com/xcodebuild/hexo-asset-image/issues/47
