### ISSUE TITLE
Permalink update problem.

### ISSUE THREAD

**Issue by tyadan** [hexojs/hexo#4493]
#4162  Check List

Please check followings before submitting a new issue.

- [*] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [*] I have already searched existing issues and they are not help  to me
- [*] I examined error or warning messages and it's difficult to solve
- [*] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [*] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## Expected behavior
Using Hexo version 5.1.1, the permalink seems have some problems.

In my post front-matter, I have defined every post with permalink, for example:

categories: ***
**permalink: zfs-zil-l2arc**
date: 2019-01-08 09:30:00 

After build my site, it seems some of the permalink ends with  "/", some didn't.

Because I'm using valine to do the discuss and count thins, it uses the permalink to id every post, in Hexo 4.* ,every permalink ends whith "/" , in Hexo 5.* , some of them didn't cause valine can't id the post correctly. 

It seems in post_permalink.js 5.* has changed the postPermalinkFilter caused this problem.

**Comment by SukkaW** [comment]
> After build my site, it seems some of the permalink ends with "/", some didn't.

Are both `ends with /` & `not ends with /` accessible?

And would you mind providing the structure of your `source/_posts` and `public` directories?
