### ISSUE TITLE
How to work Hexo

### ISSUE THREAD

**Issue by lifeofcoding12** [hexojs/hexo#4509]
Hello I started using Hexo I have overall no idea how to do anything I had look around for information I could find so far nothing to provide basic information for example how to do get post or article or page made. 

I followed someone else  guide on Youtube done what the guy said and nothing happened.

**Comment by SukkaW** [comment]
Do you mean "How Hexo works?"

**Comment by lifeofcoding12** [comment]
Yes that's correct I could find no information or help at all for how to use it looks pretty good overall but I have no idea how to do anything in regards to it except setup the software.

Sorry for the delay in replying to you .

**Comment by SukkaW** [comment]
> Yes that's correct I could find no information or help at all for how to use it looks pretty good overall but I have no idea how to do anything in regards to it except setup the software.
> 
> Sorry for the delay in replying to you .

Hexo is open-sourced. Just read the source code.
