### ISSUE TITLE
hexo generator 生成中文连接变成百分号%xx

### ISSUE THREAD

**Issue by Jaredtop** [hexojs/hexo#4513]
![image](https://user-images.githubusercontent.com/57387296/91960389-6f56c680-ed3c-11ea-8184-875b9fa656e5.png)

## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by jerryc127** [comment]
5.0.0 开始 会把 中文转义了
不是 Bugs
