### ISSUE TITLE
Incorrect layout files used in the theme folder

### ISSUE THREAD

**Issue by nobody-65534** [hexojs/hexo#4521]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
In a theme structure like this:
```
.
├── gulpfile.js
├── _src
│   ├── _config.yml
│   ├── assets
│   ├── js
│   ├── languages
│   ├── layout
│   └── scripts
├── _config.yml
├── languages
├── layout
├── scripts
└── source
```
`./layout/*.ejs` are used as template

## Actual behavior

`./_src/layout/*.ejs` are used

## How to reproduce?

```
 hexo init test && cd test
 mkdir themes/landscape/_src/ && cp themes/landscape/layout/ themes/landscape/_src/ -r
 echo "Please do not use me" > themes/landscape/_src/layout/layout.ejs
 hexo s
 curl http://localhost:4000
```

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v14.8.0
6.14.7
```

**Your site `_config.yml`** (Optional)

**Your theme `_config.yml`** (Optional)

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /***/
├── hexo@5.1.1
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.2.0
├── hexo-renderer-stylus@2.0.1
└── hexo-server@2.0.0
```

**Your package.json `package.json`**

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.1.1"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0"
  }
}

```

## Others

I keep all my source code and assets in `./_src/`. A gulpfile is used to process these file, then they are output to `./` according to hexo theme structure.

**Comment by curbengh** [comment]
> `cp themes/landscape/layout/ themes/landscape/_src/ -r`

Hexo currently assume there is only one layout folder in a theme. While it may be possible to ignore layout in underscore-prefixed folder, I wonder why there are two layouts in the first place?

---

May I know your use case for gulp? Hexo's [router](https://hexo.io/api/router) + [after_render](https://hexo.io/api/rendering#after-render-Filters) API may be able to replace it. Examples: https://github.com/hexojs/site/pull/1053 https://github.com/hexojs/site/pull/1138

**Comment by nobody-65534** [comment]
> May I know your use case for gulp?

I use gulp to compile and minify css and js. It's also used to compress image assets.  

In the theme I'm working on, `gulp-rev` is used to revisioning these generated files. It has to process `./_src/layout/*.ejs` and replace url of static files, then output them to `./layout/`. 

For example, `<% css("css/style.css") %>` in the template will be rewrite to `<% css("css/style-bf2a9b604a.css") %>`. That's why I have two sets of layout file in my theme directory.
