### ISSUE TITLE
Error uploading large file

### ISSUE THREAD

**Issue by MoyangSensei** [hexojs/hexo#4523]
Last night I tried to upload a 230mb video file as an attachment. I put this video file in / blog / source / download, which is my newly created directory. There are some other download attachments under this directory, but they are not more than 100MB, which is not the problem of this directory.

I didn't know that on GitHub, uploading a single file can't exceed the 100 MB limit. Then I used "hexo G - D" to update my blog. Of course, this update failed and gave a hint that the file was too large.

So I deleted the video file and deployed the blog again using the above command, but this time it still failed: the video file will still be compressed and the file will be too large. But I've actually removed this big file.

I try to use "hexo clean" and use "hexo G - D" many times, which has always been the problem. Now my local files can't be uploaded, but the content of the deployed website can be opened and browsed.

How can I solve this problem? If it can't be solved, how can I restore the version I have uploaded?

```
INFO  345 files generated in 1.11 s
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
位于分支 master
无文件要提交，干净的工作区
枚举对象: 46, 完成.
对象计数中: 100% (46/46), 完成.
使用 4 个线程进行压缩
压缩对象中: 100% (24/24), 完成.
写入对象中: 100% (32/32), 233.96 MiB | 1.42 MiB/s, 完成.
总共 32（差异 10），复用 0（差异 0），包复用 0
remote: Resolving deltas: 100% (10/10), completed with 6 local objects.
remote: D, [2020-09-07T10:14:16.450052 #17904] DEBUG -- : FAILBOT EXCEPTION: action=processing exception=NoMethodError original_type: GitHub::PreReceiveBlob::PushRejected data={"release"=>"0bb4e55968bb1f6b7b7d390b446cdc964bf797fa", "current_ref"=>"queue-prep-train-35e24042-50d29c5-5acbcfe-ec02ede", "app"=>"github-user", "ruby"=>"ruby 2.7.1p92 (2020-07-11 revision 4ec8c70524) [x86_64-linux]", "server"=>"github-dfs-43b2987.ash1-iad.github.net", "deployed_to"=>"production", "kube_namespace"=>"unknown", "pusher"=>"MoyangSensei", "proto"=>"http", "path"=>"/data/repositories/d/nw/d8/72/69/206495913/175965206.git", "from"=>"hooks/pre-receive.rb.rb [MoyangSensei/MoyangSensei.github.io.git]", "audit_msg"=>"{ \"above_lock_quota\":false, \"above_warn_quota\":false, \"babeld\":\"cc5efb01\", \"babeld_proto\":\"http\", \"check_lfs_integrity\":false, \"cmdline\":\"/usr/lib/git-core/git receive-pack --stateless-rpc .\", \"committer_date\":\"1599498690 -0700\", \"disable_hooks\":true, \"features\":\" report-status side-band-64k agent=git/2.26.0\", \"frontend\":\"unicorn-gitauth-api-5fdd5866b4-5vm7h\", \"frontend_pid\":153, \"frontend_ppid\":6, \"git_dir\":\"/data/repositories/d/nw/d8/72/69/206495913/175965206.git\", \"git_dir_safe\":\"/data/repositories/d/nw/d8/72/69/206495913/175965206.git\", \"gitauth_version\":\"0bb4e559\", \"hostname\":\"github-dfs-43b2987.ash1-iad.github.net\", \"pgroup\":\"22210\", \"pid\":22210, \"ppid\":22193, \"program\":\"receive-pack\", \"proxy_pre_fetch_and_detect_have_present\":false, \"quotas_enabled\":true, \"real_ip\":\"150.109.16.230\", \"received_objects\":32, \"remote_addr\":\"10.52.17.56\", \"remote_port\":\"50608\", \"repo_config\":\"{}\", \"repo_id\":175965206, \"repo_name\":\"MoyangSensei/MoyangSensei.github.io\", \"repo_public\":true, \"request_id\":\"5765:4172:1DE629A:29B1DE6:5F5669C2\", \"status\":\"pre_receive_hook\", \"use_http_postrx\":true, \"user_id\":48516430, \"user_login\":\"MoyangSensei\", \"user_operator_mode\":false }", "env"=>"production", "error_code"=>"91320122eae987eaa87ebe0e14ce85e9", "exception_detail"=>[{"type"=>"GitHub::PreReceiveBlob::PushRejected", "value"=>"GitHub::PreReceiveBlob::PushRejected", "stacktrace"=>[]}], "created_at"=>"2020-09-07T17:14:16.448381Z", "refs"=>"refs/heads/master: e2e6725502be4757ea22ce0475e01d77e793331d", "files"=>"download/\xE8\xA7\x86\xE9\xA2\x91\xE6\x91\x98\xE8\xA6\x81/DimensionFour_result_short.zip: 233599619 bytes", "repo_id"=>175965206, "rollup"=>"2a7bc1e29623942867c40e965f833e13"}
remote: D, [2020-09-07T10:14:16.450145 #17904] DEBUG -- : GitHub::PreReceiveBlob::PushRejected
remote: D, [2020-09-07T10:14:16.452278 #17904] DEBUG -- : undefined method `hour' for 1:Integer
remote: D, [2020-09-07T10:14:16.452340 #17904] DEBUG -- : /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/lib/github/config/failbot.rb:85:in `block in <top (required)>'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/vendor/gems/2.7.1/ruby/2.7.0/gems/failbot-2.5.5/lib/failbot.rb:345:in `report!'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/vendor/gems/2.7.1/ruby/2.7.0/gems/failbot-2.5.5/lib/failbot.rb:322:in `report'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/lib/github/githooks/pre_receive_blob.rb:75:in `check'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/lib/github/githooks/push_context.rb:40:in `block (2 levels) in check'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/vendor/gems/2.7.1/ruby/2.7.0/gems/dogstatsd-ruby-4.1.0/lib/datadog/statsd.rb:356:in `time'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/lib/github/githooks/push_context.rb:39:in `block in check'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/lib/github/githooks/push_context.rb:34:in `each'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/lib/github/githooks/push_context.rb:34:in `check'
remote: hooks/pre-receive.rb:52:in `block in <main>'
remote: /data/github/releases/20200907144807-0bb4e55968bb1f6b7b7d390b446cdc964bf797fa/vendor/gems/2.7.1/ruby/2.7.0/gems/dogstatsd-ruby-4.1.0/lib/datadog/statsd.rb:356:in `time'
remote: hooks/pre-receive.rb:51:in `<main>'
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 91320122eae987eaa87ebe0e14ce85e9
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File download/视频摘要/DimensionFour_result_short.zip is 222.78 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/MoyangSensei/MoyangSensei.github.io.git
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
error: 推送一些引用到 'https://github.com/MoyangSensei/MoyangSensei.github.io.git' 失败
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Spawn failed
    at ChildProcess.<anonymous> (/Users/jfy/blog/node_modules/hexo-util/lib/spawn.js:52:19)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

**Comment by MoyangSensei** [comment]
Before the above operation, my blog is no problem. It is very certain that the problem occurred because the video file was submitted.

Please help me, thank you!

**Comment by jiangtj** [comment]
It's github limit, we can't do anything. Maybe move your video file to your cloud disk
https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota#file-and-repository-size-limitations

**Comment by MoyangSensei** [comment]
> It's github limit, we can't do anything. Maybe move your video file to your cloud disk
> https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota#file-and-repository-size-limitations

Thanks. Now I know. But I have deleted this file and uploaded my blog again, it doesn't work and give the same error, I just want to recover this error.

**Comment by stevenjoezhang** [comment]
Delete this file won't work because it's stored in Git commit history. You need to run git reset and force push.

**Comment by MoyangSensei** [comment]
I tried to run the following command in my blog's local subdirectory:
```
git init
git remote add origin ......(my https)
git reset --hard 220909...... (my last hard)
git pull origin master
git push -u origin master -f
```

But it didn't actually work when I tried to run it again
```
hexo g-d
```
The [same error] is still given. The local subdirectory of the blog only adds [public] files that have been uploaded to GitHub.

I found that git's rollback only downloaded the files from the website to the local. The key is that the local file of hexo is different from the public file uploaded to hexo. The uploaded content is also generated from local content.

Is it the wrong path for me to run the "git" command above? Can you give me some specific measures? Thanks a lot.

**Comment by MoyangSensei** [comment]
> Delete this file won't work because it's stored in Git commit history. You need to run git reset and force push.

I tried to run the following command in my blog's local subdirectory:
```
git init
git remote add origin ......(my https)
git reset --hard 220909...... (my last hard)
git pull origin master
git push -u origin master -f
```

But it didn't actually work when I tried to run it again
```
hexo g-d
```
The [same error] is still given. The local subdirectory of the blog only adds [public] files that have been uploaded to GitHub.

I found that git's rollback only downloaded the files from the website to the local. The key is that the local file of hexo is different from the public file uploaded to hexo. The uploaded content is also generated from local content.

Is it the wrong path for me to run the "git" command above? Can you give me some specific measures? Thanks a lot.

**Comment by MoyangSensei** [comment]
i really need my blog's work and I hope someone can help me. Plz.

**Comment by SukkaW** [comment]
> Delete this file won't work because it's stored in Git commit history. You need to run git reset and force push.

**Comment by Rimbaud-Lee** [comment]
就在昨天，我遇到了和同样的问题，不过就在刚刚我已经解决了，我在查解决方案时看到了你的提问，我非常非常理解被这个报错支配的痛苦，我感觉我有义务向你解答。

解决方案如下：
在你的博客根目录中有个`.deploy_git`文件夹，在这个文件夹内打开`Git Bash`，输入`git log`命令，查看向GitHub的提交日志。这里可以查到我最近提交的几次commit和时间以及对应的一串数字字母组合，找到你想恢复的那个commit的那串数字字母组合，输入指令`git reset xxxxxxxxxxxxxxxxxxx`，问题就可以解决了（注意，`xxxxxxxxxxxxxxxxxxx`是commit的那串数字字母组合）。
这个指令完成之后，就相当于将你的博客恢复到对应的版本中，之后就可以进行正常的`hexo d`了！
我不知道有没有解释清楚，如果还有疑问，欢迎提问，一定解答。推荐参看`https://ztygcs.github.io/posts/%E5%A4%A7%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E5%AF%BC%E8%87%B4github%E6%8A%A5%E9%94%99/`这篇博文，我就是通过这篇文章解决的。

OS：你的英语真好，我在这看了半天还以为你是个外国网友，辛辛苦苦码了半天英文才发现你的报错代码里竟然有中文？！好气.......

**Comment by MoyangSensei** [comment]
> 就在昨天，我遇到了和同样的问题，不过就在刚刚我已经解决了，我在查解决方案时看到了你的提问，我非常非常理解被这个报错支配的痛苦，我感觉我有义务向你解答。
> 
> 解决方案如下：
> 在你的博客根目录中有个`.deploy_git`文件夹，在这个文件夹内打开`Git Bash`，输入`git log`命令，查看向GitHub的提交日志。这里可以查到我最近提交的几次commit和时间以及对应的一串数字字母组合，找到你想恢复的那个commit的那串数字字母组合，输入指令`git reset xxxxxxxxxxxxxxxxxxx`，问题就可以解决了（注意，`xxxxxxxxxxxxxxxxxxx`是commit的那串数字字母组合）。
> 这个指令完成之后，就相当于将你的博客恢复到对应的版本中，之后就可以进行正常的`hexo d`了！
> 我不知道有没有解释清楚，如果还有疑问，欢迎提问，一定解答。推荐参看`https://ztygcs.github.io/posts/%E5%A4%A7%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E5%AF%BC%E8%87%B4github%E6%8A%A5%E9%94%99/`这篇博文，我就是通过这篇文章解决的。
> 
> OS：你的英语真好，我在这看了半天还以为你是个外国网友，辛辛苦苦码了半天英文才发现你的报错代码里竟然有中文？！好气.......

谢谢你呀。之前我重装解决了，实际上也是没解决这个问题，这个方法我也记录下。

**Comment by wrencanfly** [comment]
> 就在昨天，我遇到了和同样的问题，不过就在刚刚我已经解决了，我在查解决方案时看到了你的提问，我非常非常理解被这个报错支配的痛苦，我感觉我有义务向你解答。
> 
> 解决方案如下： 在你的博客根目录中有个`.deploy_git`文件夹，在这个文件夹内打开`Git Bash`，输入`git log`命令，查看向GitHub的提交日志。这里可以查到我最近提交的几次commit和时间以及对应的一串数字字母组合，找到你想恢复的那个commit的那串数字字母组合，输入指令`git reset xxxxxxxxxxxxxxxxxxx`，问题就可以解决了（注意，`xxxxxxxxxxxxxxxxxxx`是commit的那串数字字母组合）。 这个指令完成之后，就相当于将你的博客恢复到对应的版本中，之后就可以进行正常的`hexo d`了！ 我不知道有没有解释清楚，如果还有疑问，欢迎提问，一定解答。推荐参看`https://ztygcs.github.io/posts/%E5%A4%A7%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E5%AF%BC%E8%87%B4github%E6%8A%A5%E9%94%99/`这篇博文，我就是通过这篇文章解决的。
> 
> OS：你的英语真好，我在这看了半天还以为你是个外国网友，辛辛苦苦码了半天英文才发现你的报错代码里竟然有中文？！好气.......

Thanks a lot! That's really saved my time a lot. Thanks!!!

**Comment by enkr1** [comment]
> 就在昨天，我遇到了和同样的问题，不过就在刚刚我已经解决了，我在查解决方案时看到了你的提问，我非常非常理解被这个报错支配的痛苦，我感觉我有义务向你解答。
> 
> 解决方案如下： 在你的博客根目录中有个`.deploy_git`文件夹，在这个文件夹内打开`Git Bash`，输入`git log`命令，查看向GitHub的提交日志。这里可以查到我最近提交的几次commit和时间以及对应的一串数字字母组合，找到你想恢复的那个commit的那串数字字母组合，输入指令`git reset xxxxxxxxxxxxxxxxxxx`，问题就可以解决了（注意，`xxxxxxxxxxxxxxxxxxx`是commit的那串数字字母组合）。 这个指令完成之后，就相当于将你的博客恢复到对应的版本中，之后就可以进行正常的`hexo d`了！ 我不知道有没有解释清楚，如果还有疑问，欢迎提问，一定解答。推荐参看`https://ztygcs.github.io/posts/%E5%A4%A7%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E5%AF%BC%E8%87%B4github%E6%8A%A5%E9%94%99/`这篇博文，我就是通过这篇文章解决的。
> 
> OS：你的英语真好，我在这看了半天还以为你是个外国网友，辛辛苦苦码了半天英文才发现你的报错代码里竟然有中文？！好气.......

访问不聊了 救命老师。我现在卡着不能 deploy

**Comment by enkr1** [comment]
omg i got what u meant liao! 谢谢你！！！！！

**Comment by enkr1** [comment]
issue solved! 大神

**Comment by uiolee** [comment]
Delete `.deploy_git` will be a simple solution.

However, be aware that this will result in the loss of local and remote git records.
