### ISSUE TITLE
External Image url does not display

### ISSUE THREAD

**Issue by FrankSFLYS** [hexojs/hexo#4526]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
I used extra folder to save my image (source/images/) and it worked well. These days I built a image server to store my pictures, and external link is used in the md file. But the images just don't show on the page. Both md syntax `![](url)` and hexo syntax `{% asset_image url %}` are used, neither of them work. If I middle-click the image (open in new tab) it shows, which means that the url is right. The page is on [树莓派改造无线打印机](https://frank.xin/2020/09/09/%E6%A0%91%E8%8E%93%E6%B4%BE%E6%94%B9%E9%80%A0%E6%97%A0%E7%BA%BF%E6%89%93%E5%8D%B0%E6%9C%BA/) ,check it out. Right-click the image link and open it in a new tab shows the picture.
## Actual behavior
I want the images to show.
## How to reproduce?

* Upload a picture on to the server and you will get a link to it.
* Paste the link into `![](link)` in the md file
* `hexo g`

## Is the problem still there under "Safe mode"?
Yes, it's still there.

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
node -v
v12.18.3

npm -v
6.14.6
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
npm ls --depth 0
hexo-site@0.0.0 F:\hexo
+-- hexo@3.8.0
+-- hexo-asset-image@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-markdown-it-plus@1.0.4
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.3.3
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}
```

## Others
**Updates** The images display correctly on local server (`hexo server`).

**Comment by curbengh** [comment]
Looks fine to me.

![frank xin](https://user-images.githubusercontent.com/43627182/93014531-f59ec280-f5f0-11ea-8eac-592a63c39180.png)

**Comment by FrankSFLYS** [comment]
> Looks fine to me.
> 
> ![frank xin](https://user-images.githubusercontent.com/43627182/93014531-f59ec280-f5f0-11ea-8eac-592a63c39180.png)

What happened to my devices? Both my phone and laptop, WiFi and cellular don't work.

**Comment by SukkaW** [comment]
@FrankSFLYS 

![image](https://user-images.githubusercontent.com/40715044/93095444-b0a08c00-f6d5-11ea-8d92-9fad431a1ac8.png)

Looks like you have `Mixed Content`.

**Comment by FrankSFLYS** [comment]
OK, my image server costs to upgrade to `https`, so I downgrade everything to `http`, and it displays now.
