### ISSUE TITLE
【HELP】 hexo generate '<' to '&lt;' and '>' to '&gt;' in index.html

### ISSUE THREAD

**Issue by CapAllen** [hexojs/hexo#4531]
## Check List

Please check followings before submitting a new issue.

- [x ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ x] I have already searched existing issues and they are not help to me
- [ x] I examined error or warning messages and it's difficult to solve
- [x ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
Node.js  v10.15.3
npm  6.4.1
site  http://capallen.gitee.io
theme Next
```

## Others

The page shows like this:
![image](https://user-images.githubusercontent.com/35265537/93072495-0f550e00-f6b4-11ea-908f-438b4a64c7ea.png)

So , I check the code of `index.html` and it shows like this:
`<a href="/archives" rel="section">&lt;i class="menu-item-icon fa fa-fw fa-archive"&gt;&lt;/i&gt; &lt;br/&gt;归档&lt;span class="badge"&gt;28&lt;/span&gt;</a>`

As we can see, the `<` has been generated to `&lt;`, and `>` to `&gt;`.

What should I do? Thx for your help.

**Comment by stevenjoezhang** [comment]
NexT v7.1.0 is incompatible with Hexo 4.0+
See part "Hexo 与 NexT 兼容性" in this page: https://github.com/next-theme/hexo-theme-next/issues/4

**Comment by CapAllen** [comment]
> 
> 
> NexT v7.1.0 is incompatible with Hexo 4.0+
> See part "Hexo 与 NexT 兼容性" in this page: [next-theme/hexo-theme-next#4](https://github.com/next-theme/hexo-theme-next/issues/4)

Thanks
