### ISSUE TITLE
The page build failed for the `master` branch with the following error:

### ISSUE THREAD

**Issue by 010WHC** [hexojs/hexo#4543]
The page build failed for the `master` branch with the following error:

Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=296050324&page_build_id=204098918

**Comment by stevenjoezhang** [comment]
See https://github.com/hexojs/hexo/issues/3212#issuecomment-406441746
