### ISSUE TITLE
如何在文章markdwon解析之前判断是否含有img图像呢

### ISSUE THREAD

**Issue by awnawnawn** [hexojs/hexo#4544]
我想在有图像的文章页里加载一些javascriprt，有什么内置的语法可以实现吗？

**Comment by awnawnawn** [comment]
我想在有图像的文章页里加载一些javascriprt

**Comment by stevenjoezhang** [comment]
如果你指的是在 Node.js 端运行的 javascript，可以用正则检测 `img` 标签
