### ISSUE TITLE
Deploy后无法上传到GitHub master分支 github.io站点404

### ISSUE THREAD

**Issue by Wchoward** [hexojs/hexo#4550]
<img width="736" alt="屏幕快照 2020-10-08 15 51 23" src="https://user-images.githubusercontent.com/29882211/95430323-37b3ed80-097e-11eb-9b88-077d7972ee28.png">
<img width="936" alt="屏幕快照 2020-10-08 15 51 43" src="https://user-images.githubusercontent.com/29882211/95430351-40a4bf00-097e-11eb-8d71-9b2f867afc14.png">
<img width="1217" alt="屏幕快照 2020-10-08 15 51 51" src="https://user-images.githubusercontent.com/29882211/95430356-43071900-097e-11eb-85b5-fbebef623cc5.png">

## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
nodejs v13.11.0
npm v6.13.7
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@1.0.0 /Users/howard/study/ABC/wchoward.github.io
├── hexo@4.2.1
├── hexo-asset-image@1.0.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-sitemap@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-markdown-it-plus@1.0.4
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── markdown-it-footnote@3.0.2
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.2.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "markdown-it-footnote": "^3.0.2"
  }
}
```

**Comment by jiangtj** [comment]
Please try `hexo g`, and look at your `public` dir. Is the html file generated here?

**Comment by Wchoward** [comment]
> Please try `hexo g`, and look at your `public` dir. Is the html file generated here?

I tried `hexo clean` and `hexo g`, and html files are generated in `public` dir. However, when I deploy `hexo d`, all files except html files are uploaded at github master branch.

**Comment by jiangtj** [comment]
https://github.com/hexojs/hexo-deployer-git/blob/d38cabda0571286a96ec64ef6e85c1955215276d/lib/deployer.js#L109

看一下 `.deploy_git` 文件夹，是不是也有html文件

很好奇的你问题，如果`.deploy_git` 文件夹也存在html的话，可能是git配置有问题。。。

hexo-deployer-git插件做的工作很简单

[√] hexo g 生成内容
[?] 复制内容到`.deploy_git`
[?] git push内容到github上

**Comment by Wchoward** [comment]
> https://github.com/hexojs/hexo-deployer-git/blob/d38cabda0571286a96ec64ef6e85c1955215276d/lib/deployer.js#L109
> 
> 看一下 `.deploy_git` 文件夹，是不是也有html文件
> 
> 很好奇的你问题，如果`.deploy_git` 文件夹也存在html的话，可能是git配置有问题。。。
> 
> hexo-deployer-git插件做的工作很简单
> 
> [√] hexo g 生成内容
> [?] 复制内容到`.deploy_git`
> [?] git push内容到github上

![屏幕快照 2020-10-10 16 20 20](https://user-images.githubusercontent.com/29882211/95650191-914e2080-0b14-11eb-9d5c-b903589984c5.png)
`.deploy_git`中存在html文件，也安装了Hexo-deployer-git插件。
`.deploy_git`文件夹中css等文件 均能够更新push到github上，但是所有的html的网页均无法push

**Comment by Wchoward** [comment]
是否有可能是hexo-deployer-git插件存在类似.gitignore的配置，把我的`.html`后缀的文件全部忽略掉了？如果有的话，这个配置在哪里呢？

**Comment by jiangtj** [comment]
> 是否有可能是hexo-deployer-git插件存在类似.gitignore的配置，把我的`.html`后缀的文件全部忽略掉了？

插件的忽略的确有，但是作用在复制这步，你没配而且也的确全复制过去了

其它地方是没有忽略了，push操作就是单纯调用Git push命令

https://github.com/hexojs/hexo-deployer-git/blob/a431418a7bf4389171c3c648b6e44bbead138a17/lib/deployer.js#L76-L84

**Comment by Wchoward** [comment]
> > 是否有可能是hexo-deployer-git插件存在类似.gitignore的配置，把我的`.html`后缀的文件全部忽略掉了？
> 
> 插件的忽略的确有，但是作用在复制这步，你没配而且也的确全复制过去了
> 
> 其它地方是没有忽略了，push操作就是单纯调用Git push命令
> 
> https://github.com/hexojs/hexo-deployer-git/blob/a431418a7bf4389171c3c648b6e44bbead138a17/lib/deployer.js#L76-L84

@jiangtj 谢谢，是的，我进入`.deploy_git`文件夹直接手动git push，也是直接显示 Everything up-to-date. 直接忽略掉了文件夹里的html文件

**Comment by Wchoward** [comment]
我重新`hexo g` 和 `hexo d`后，发现，并不会帮我把.html后缀的文件create mode，这是为什么？
<img width="704" alt="image" src="https://user-images.githubusercontent.com/29882211/95669357-906bcc00-0bb2-11eb-8995-270cf6bb0dc8.png">

**Comment by stevenjoezhang** [comment]
Superseded by https://github.com/hexojs/hexo-deployer-git/issues/194
