### ISSUE TITLE
hexo5 tags layout error

### ISSUE THREAD

**Issue by tuhongwei** [hexojs/hexo#4551]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
sidebar tag a with the class 'sidebar_archives-link' not 'sidebar_archives-none-link'
## Actual behavior
sidebar tag a with the class 'sidebar_archives-none-link'
## How to reproduce?

*install hexo5
* create an ejs template called sidebar.ejs
* in sidebar.ejs, use '<% var tags = list_tags({style: 'none', separator: '', class: 'mdui-ripple sidebar_archives'}) %>
   <%- tags %>', then the sidebar tag layout will be wrong. When I change the hexo version to v4, the layout will be right.

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
node: v12.2.0
npm: v6.9.0
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/4059
