### ISSUE TITLE
Add support for yarn 2.0 Plug'n'Play feature 

### ISSUE THREAD

**Issue by gwd0715** [hexojs/hexo#4552]
Since Yarn 2.0 is out with support for Plug'n'Play module resolution turned on by default, it would be great to see support for it within hexo and hexo-cli.

Related links:
https://classic.yarnpkg.com/en/docs/pnp/
https://yarnpkg.com/advanced/pnpapi

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo-cli/pull/227

**Comment by gwd0715** [comment]
Thanks! So no support then.
