### ISSUE TITLE
hexo无法启动

### ISSUE THREAD

**Issue by leeseean** [hexojs/hexo#4554]
![image](https://user-images.githubusercontent.com/17198500/95658702-f9b9f380-0b4e-11eb-8e14-9f48cd8bfe2e.png)
怎么生成ejs的目录结构，官方mi命令生成的都是md文件。
![image](https://user-images.githubusercontent.com/17198500/95658719-1d7d3980-0b4f-11eb-9b53-8e52ba14ec7b.png)

**Comment by stevenjoezhang** [comment]
报错来自主题内部，请联系你所使用的主题的开发者解决问题。
