### ISSUE TITLE
injector 怎麽獲取主題的配置？

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4557]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

cannot get theme config in extend Injector ?

injector 怎麽獲取主題的配置？
我試了可以通過  hexo.config.theme_config來獲取，但這個只能在有使用_config.xxxx.yml 這種配置文件時獲取到
但是如果是通過主題文件夾的_config.yml 配置的的，獲取不到，通過console.log查看，并沒有theme_config參數，而hexo.theme.config返回的是空數組。
請問要怎麽獲取到？

**Comment by stevenjoezhang** [comment]
injector 是为 Hexo 插件向页面中加入内容而设计的，因此不需要获得主题的配置。如果您是主题开发者，应通过编写主题的模板文件来加入内容，而不是 injector
