### ISSUE TITLE
Hexo on Ipad

### ISSUE THREAD

**Issue by adrhmnhkm** [hexojs/hexo#4562]
How to move my hexo site to ipad, is that possible ?

**Comment by stevenjoezhang** [comment]
Do you mean:
1. Install Hexo environment on iPad

or

2. Browse your website on iPad?

**Comment by adrhmnhkm** [comment]
> Do you mean:
> 
> 1. Install Hexo environment on iPad
> 
> or
> 
> 1. Browse your website on iPad?

Install hexo enviroment on iPad

**Comment by stevenjoezhang** [comment]
There is a discussion about running Node.js on iOS: https://github.com/nodejs/node/issues/7158
