### ISSUE TITLE
页面文章中代码块如果是xml或者html格式，后标签就显示不正确

### ISSUE THREAD

**Issue by lucas-zhangfan** [hexojs/hexo#4564]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

页面文章中代码块如果是xml或者html格式，后标签就显示不正确，但markdown文档显示是正常的，请问这是什么原因？

1. 博客页面展示的代码块内容有问题，</标签> 无法正确展示；
![image](https://user-images.githubusercontent.com/46958209/97382281-f3c16200-1905-11eb-97bd-38efd0cf824c.png)

2. markdown文档是正确的；
![image](https://user-images.githubusercontent.com/46958209/97382356-2cf9d200-1906-11eb-884e-08ab7e74ea02.png)

3. xml和html格式的代码快都有此问题；
## Environment & Settings

**Node.js & npm version**
![image](https://user-images.githubusercontent.com/46958209/97382435-5dda0700-1906-11eb-9350-cdc3594c790b.png)

![image](https://user-images.githubusercontent.com/46958209/97382540-8feb6900-1906-11eb-9f41-419ab31ba456.png)

![image](https://user-images.githubusercontent.com/46958209/97382498-7a763f00-1906-11eb-9fb9-b7b8411e9673.png)
```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by SukkaW** [comment]
Already fixed in Hexo 5.0.0. Please upgrade your Hexo version.
