### ISSUE TITLE
hexo v4.2.0 更新至 v5.2.0后，报未定义toDate()错误；

### ISSUE THREAD

**Issue by lucas-zhangfan** [hexojs/hexo#4565]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

在hexo v4.2.0 更新至 v5.2.0后，hexo g && hexo d 后会报如下错误，在ejs.js文件中并未定义toDate()方法。请问这个怎么解决？

After the hexo v4.2.0 update to v5.2.0, and execute the command "hexo g && hexo d" . It reported the following error: The method named "toDate()" was not defined in the ejs.js. How to solve this, please?

![image](https://user-images.githubusercontent.com/46958209/97397307-e87d2f00-1923-11eb-9b54-4de676c3f8dd.png)

## Environment & Settings
![image](https://user-images.githubusercontent.com/46958209/97397585-938de880-1924-11eb-8567-a249f330b79c.png)

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by lucas-zhangfan** [comment]
![image](https://user-images.githubusercontent.com/46958209/97400666-78be7280-192a-11eb-9d69-8fd2c8251a22.png)
将 node_modules/hexo-generator-baidu-sitemap/baidusitemap.ejs 中报错语句删除后，hexo g && hexo d 可正常执行，但hexo v4.2.0 中关于markdown中 代码块格式为 xml 和 html 时页面显示不正确问题，未能同通过升级hexo版本至v5.0.0得到解决。请问有什么解决办法？
![image](https://user-images.githubusercontent.com/46958209/97401466-d4d5c680-192b-11eb-8c68-987ae92a9e31.png)

**Comment by stevenjoezhang** [comment]
执行 `hexo clean` 试试

**Comment by lucas-zhangfan** [comment]
> 执行 `hexo clean` 试试

这个没有用，每次执行，都会先执行一次hexo clean
![image](https://user-images.githubusercontent.com/46958209/97515672-82001b80-19cc-11eb-9c34-25f623a12bd9.png)

**Comment by jerryc127** [comment]
你试试这个
1. npm cache clean --force
2. delete node_modules folder
3. delete package-lock.json file
4. npm install
5. hexo clean; hexo g

**Comment by lucas-zhangfan** [comment]
> 你试试这个
> 
> 1. npm cache clean --force
> 2. delete node_modules folder
> 3. delete package-lock.json file
> 4. npm install
> 5. hexo clean; hexo g

还是未生效，很奇怪
