### ISSUE TITLE
输入命令报错

### ISSUE THREAD

**Issue by Yuxushen** [hexojs/hexo#4567]
用 “hexo Init“ 命令 出现报错 'rm -rf node_modules && npm install --force'，怎么办？

**Comment by SukkaW** [comment]
What you should do is run the command in your terminal:

```bash
rm -rf node_modules && npm install --force
```

**Comment by stevenjoezhang** [comment]
如果您看到报错的内容是`rm -rf node_modules && npm install --force`，那么请使用您最喜欢的命令行执行`rm -rf node_modules && npm install --force`
