### ISSUE TITLE
remote: error: GH006: Protected branch update failed for refs/heads/master.

### ISSUE THREAD

**Issue by maglin07** [hexojs/hexo#4568]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by YoshinoriN** [comment]
This is not hexo issue. Please read GitHub doc. 

> [About protected branches
](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-protected-branches)
