### ISSUE TITLE
npm install hexo-cli -g没有生成assets文件，然后第二部报错如下

### ISSUE THREAD

**Issue by tmlabbott** [hexojs/hexo#4569]
err: [Error: ENOENT: no such file or directory, scandir '/www/server/nvm/versions/node/v14.15.0/lib/node_modules/hexo-cli/assets

**Comment by YinchenWang** [comment]
same error，lost assets

FATAL {
  err: [Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/hexo-cli/assets'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'scandir',
    path: '/usr/local/lib/node_modules/hexo-cli/assets'
  }
} Something's wrong. Maybe you can find the solution here: %s http://hexo.io/docs/troubleshooting.html

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo-cli/pull/266
I'm closing this issue. Please join the discussion there :)
