### ISSUE TITLE
How can I upgrade hexo?

### ISSUE THREAD

**Issue by erotavlas** [hexojs/hexo#4572]
I have currently installed hexo globally using npm on Windows using 

`npm install -g hexo-cli`

I am currently on the following version (outside blog folder)

hexo-cli: 4.2.0

WHen I run  `hexo --version` from inside blog folder I get this 

hexo: 4.2.1
hexo-cli: 4.2.0

When I try to run either of the following nothing happens

npm update -g hexo
npm update -g hexo-clii

The version always stays on 4.2.0.

My package.json file for blog looks like this

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.2.1",
    "hexo-browsersync": "^0.3.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}
```

What is the proper way to upgrade hexo when installed globally.?

**Comment by stevenjoezhang** [comment]
Run
```
npm i hexo@5.2.0
```
The latest version of `hexo-cli` is 4.2.0 thus you don't need to upgrade it globally
