### ISSUE TITLE
Page style of code boom  when I use ```with a blank | 带空格的```的代码块样式炸了

### ISSUE THREAD

**Issue by nidbCN** [hexojs/hexo#4573]
## Check List 自查表

Please check followings before submitting a new issue.

- [ √] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [√ ] I have already searched existing issues and they are not help  to me
- [ √] I examined error or warning messages and it's difficult to solve
- [ √] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ √] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior 期望
**I USE TWO LANGUAGE TO WRITE THIS REPORT,ONLY READ ONE IS ENOUGH**
**我用了两种语言来写这个报告，只看其中一个即可**
我写了一些代码块，就像这样
I write some codes,such as:"
```c
// This is code 1
``` 
The next is:
```c
// This is code 2
```
That 's all"

我希望它能像GitHub和其它用MarkDown的网站一样渲染出两个代码块
I expect it will be render like Github or other website which use MarkDown,just two block of codes
[![BbhHMD.png](https://s1.ax1x.com/2020/11/10/BbhHMD.png)](https://imgchr.com/i/BbhHMD)

## Actual behavior 实际

[![Bb4kZj.png](https://s1.ax1x.com/2020/11/10/Bb4kZj.png)](https://imgchr.com/i/Bb4kZj)
Hexo只渲染了第一个和最后一个标签
Hexo only render the first tag and the last.
## How to reproduce? 咋复现的

Write two normal code blocks with ```,add a blank (' ') on one of the tags,and it will be ignore.
正常的写两个代码块，在其中一个标签后面加上空格，然后它就不被渲染了

## Is the problem still there under "Safe mode"? 安全模式也有？
Yes,I think it produce no matter Safe mode
我觉得它和安全模式无关叭

## Environment & Settings 环境和设置

**Node.js & npm version(`node -v && npm -v`)**

```
[root@AliCloud blog]# node -v && npm -v
v13.14.0
6.14.4
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
[root@AliCloud blog]# npm ls --depth 0
hexo-site@0.0.0 /data/blog
├── hexo@5.2.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.2.0
├── hexo-renderer-stylus@2.0.1
└── hexo-server@2.0.0

```

**Your package.json `package.json`**

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.2.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0"
  }
}
```

I think it is nessary to fix if it is a bug.Because when someone insert a blank careless.The page hexo render will confuse him/her.
我觉得如果这是个bug，修一下还是挺有必要的。因为谁要是不小心敲了个空格进去。渲染出来的页面会很迷惑的。
**THANKS FOR READING THIS 感谢您百忙之中拨冗查看**

**Comment by stevenjoezhang** [comment]
See also https://spec.commonmark.org/0.29/#fenced-code-blocks

> The closing code fence may be indented up to three spaces, and may be followed only by spaces, which are ignored.
