### ISSUE TITLE
Internal Links

### ISSUE THREAD

**Issue by m73** [hexojs/hexo#458]
Hi. I can't seem to find it anywhere, so I'll ask. How can I make internal links in a post to my other posts easily?

**Comment by kuanyui** [comment]
For Emacs user, I wrote [a function to insert article's (static) link easily](https://github.com/kuanyui/writing-utils.el/blob/master/hexo.el#L137). Hope this would be useful for Emacs users.

**Comment by YJ2CS** [comment]
## 中文
在hxo更换了markdown渲染引擎后，你可以使用markdown-it的插件`@gerhobbelt/markdown-it-wikilinks`去实现这项功能，

具体见[@gerhobbelt/markdown-it-wikilinks](https://www.npmjs.com/package/@gerhobbelt/markdown-it-wikilinks),

需要注意的是，你应该使用下列的命令安装这个包
```bash
npm i @gerhobbelt/markdown-it-wikilinks
```

## English

After hxo replaces the markdown rendering engine, you can use the markdown-it plug-in `@gerhobbelt/markdown-it-wikilinks` to implement this function, 

see [@gerhobbelt/markdown-it-wikilinks](https:// www.npmjs.com/package/@gerhobbelt/markdown-it-wikilinks),

 it should be noted that you should use the following command to install this package
```bash
npm i @gerhobbelt/markdown-it-wikilinks
```
