### ISSUE TITLE
with hexo API how to know the project is hexo blog

### ISSUE THREAD

**Issue by tmirun** [hexojs/hexo#4582]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

with hexo API how I can to know the project has hexo implement?
> 用 hexo API 我怎么知道 这个项目是 hexo 项目？

**Comment by SukkaW** [comment]
Hexo project will have hexo property inside package.json, and here is the implementation of `hexo-cli`: https://github.com/hexojs/hexo-cli/blob/0cbe1574ab95eb87bce5f866a04bdcc0c35a2b03/lib/find_pkg.js#L14-L19

**Comment by tmirun** [comment]
@SukkaW thank you again, wi will close this comment
