### ISSUE TITLE
如何更新 hexo 版本？

### ISSUE THREAD

**Issue by zhwangart** [hexojs/hexo#4589]
如题，请问如何更新 hexo 版本？
文档中搜索也搜索不到，只提到要使用最新版本，但是到底怎么更新？
> #### Node.js 版本限制
> 我们强烈建议永远安装最新版本的 Hexo，以及 推荐的 Node.js 版本。

到底怎么更新？

**Comment by YoshinoriN** [comment]
@zhwangart 
Check the below comments.

> https://github.com/hexojs/hexo/issues/4572#issuecomment-724829192

Please search existing issues before submitting a new issue.

Thank you :)
