### ISSUE TITLE
The tags / categories escaping problem in Front-matter

### ISSUE THREAD

**Issue by songhn233** [hexojs/hexo#4593]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
Tags should be displayed correctly
## Actual behavior
Wrong display of symbols in tags / categories
## How to reproduce?

Add below to the Front-matter

```yaml
tags:
- c++
- c
```
In the page, both of these urls will appear as `localhost:xxxx/4000/tags/c`, `c++` tag is not properly escaped

`category.path`  variable seems to be a problem.

**Comment by SukkaW** [comment]
```yaml
tags:
- "c++"
- c
```

Will it works?

**Comment by songhn233** [comment]
> ```yaml
> tags:
> - "c++"
> - c
> ```
> 
> Will it works?

I have tried this method but it seems not to work, when generated there is only `c` in the tag folder under the public and the page displays the same.

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/4104#issuecomment-607597936
