### ISSUE TITLE
I hope hexo can support posting the files in the specified directory in the draft folder to the _posts folder.希望hexo能够支持将草稿文件夹中指定目录中的文件发布到_posts文件夹中.

### ISSUE THREAD

**Issue by aner1001** [hexojs/hexo#4599]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request
Hello hexo,
        I am a Chinese developer who just started using the hexo blog. I found that I can specify the directory `$ hexo new draft dt1--path pro/draftTest1` at the same time when creating a draft, but I cannot specify the directory where the draft is located when publishing. `hexo publish draftTest1` or `hexo publish draftTest1 --path pro/` cannot be executed.
        Is it possible to add the function to specify the draft in the draft file path for publishing. Thank you very much for watching my suggestions.

![](https://raw.githubusercontent.com/aner1001/picBed/master/blog/2020/12/24/20201224075455.png)
---
你好hexo，
      我是一名刚开始使用hexo博客的中国开发者。我发现我可在创建草稿时同时指定目录`$ hexo new draft dt1--path pro/draftTest1`,但是在发布的时候却不能指定草稿所在的的目录。`hexo publish draftTest1` 或者`hexo publish draftTest1 --path pro/`是不能执行的。
      是否可以添加功能指定草稿文件路径中的草稿进行发布。非常感谢看我的建议。
---

**Comment by stevenjoezhang** [comment]
See https://github.com/hexojs/hexo/issues/1821
The slug of draft posts is strange
