### ISSUE TITLE
主题微调后就报错

### ISSUE THREAD

**Issue by Olivia98106** [hexojs/hexo#4600]
ERROR { TypeError: /home/ubuntu/thuCCM/themes/keep/layout/tag.ejs:1
 >> 1| <%- partial('page') %>

/home/ubuntu/thuCCM/themes/keep/layout/page.ejs:3
    1| <div class="page-container">
    2| 
 >> 3|     <% if (theme.style.first_screen.enable && is_home() && !page.prev) { %>
    4|         <%- partial('_partial/first-screen.ejs') %>
    5|     <% } %>
    6|

**Comment by stevenjoezhang** [comment]
请联系您所使用的主题的开发者解决此问题，谢谢！
