### ISSUE TITLE
What does the custom field "hexo" in `package.json` do?

### ISSUE THREAD

**Issue by fnick851** [hexojs/hexo#4601]
I have a probably easy question. What does the custom field `hexo` in `package.json` do? I couldn't find if it is documented somewhere.
```
 "hexo": {
    "version": "4.2.1"
  },
```
Thanks! My full `package.json` file can be found below.

## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
{
  "private": true,
  "version": "2.0.0",
  "scripts": {
    "hexo": "hexo",
    "new": "hexo new post",
    "serve": "hexo serve",
    "deploy": "hexo deploy -g",
    "clean": "hexo clean"
  },
  "dependencies": {
    "hexo": "^4.2.1",
    "hexo-browsersync": "^0.3.0",
    "hexo-cli": "^3.1.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "volta": {
    "node": "15.5.0"
  }
}
```

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo-cli/issues/249
I'm closing this issue. Please join the discussion there :)
