### ISSUE TITLE
How do I remove categories from permalinks

### ISSUE THREAD

**Issue by liuzane** [hexojs/hexo#4602]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

How do I remove categories from permalinks，My _config.yml is set like this: permalink: :year/:month/:day/:title.html, but renders the actual path to add the categories

I'm looking forward to: http://example.com/2020/12/25/title.html

But now is actually like this: http://example.com/2020/12/25/categories/title.html

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing index.html from permalinks

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "server": "hexo server",
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo clean && hexo deploy"
  },
  "hexo": {
    "version": "5.3.0"
  },
  "dependencies": {
    "hexo": "^5.3.0",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-neat": "^1.0.4",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

**Comment by baoang** [comment]
try to make a small adjustment

permalink: :year/:month/:day/:post_title.html

**Comment by liuzane** [comment]
> try to make a small adjustment
> 
> permalink: :year/:month/:day/:post_title.html



> try to make a small adjustment
> 
> permalink: :year/:month/:day/:post_title.html

thank you, the problem has been solved，I used :year/:month/:day/:name.html, 

:title -> relative to "source/_posts/" folder
:name -> the file name
:post_title -> the post title

**Comment by liuzane** [comment]
> try to make a small adjustment
> 
> permalink: :year/:month/:day/:post_title.html



> try to make a small adjustment
> 
> permalink: :year/:month/:day/:post_title.html

thank you, the problem has been solved，I used :year/:month/:day/:name.html, 

:title -> relative to "source/_posts/" folder
:name -> the file name
:post_title -> the post title
