### ISSUE TITLE
No css styles on the served page

### ISSUE THREAD

**Issue by CRH6F-A-0464** [hexojs/hexo#4603]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
normal page under `hexo server`
## Actual behavior
I'm using `hexo-theme-icarus`.
**No styles on the generated page, only plain texts.**
Here is the output of `hexo s --debug`:
```
GET / 200 63.099 ms - -
GET /css/default.css 404 2.832 ms - 154 
GET /images/logo.png 200 1.586 ms - -
GET /images/avatar2.png 200 1.162 ms - -
GET /js/column.js 404 1.046 ms - 151
GET /js/back_to_top.js 404 1.276 ms - 156
GET /js/animation.js 200 4.047 ms - -
GET /js/main.js 200 3.140 ms - -
GET /js/insight.js 200 3.312 ms - -
GET /js/back_to_top.js 404 0.573 ms - 156
GET /manifest.json 200 0.706 ms - -
```
As seen from above, `default.css` isn't generated.
## How to reproduce?
`sudo hexo s --debug`
## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v15.5.0
7.3.0
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /Users/<whatever>/hexo
├── bulma-stylus@0.8.0
├── deepmerge@4.2.2
├── hexo-component-inferno@0.10.4
├── hexo-deployer-git@0.3.1
├── hexo-deployer-rsync@1.0.0
├── hexo-deployer-sftp@0.1.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-log@2.0.0
├── hexo-pagination@1.0.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-inferno@0.1.3
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@2.0.1
├── hexo-server@0.2.2
├── hexo-tag-aplayer@3.0.4
├── hexo-util@2.4.0
├── hexo@5.3.0
├── inferno-create-element@7.4.6
└── inferno@7.4.6
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.3.0"
  },
  "dependencies": {
    "bulma-stylus": "^0.8.0",
    "deepmerge": "^4.2.2",
    "hexo": "^5.3.0",
    "hexo-component-inferno": "^0.10.4",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-rsync": "^1.0.0",
    "hexo-deployer-sftp": "^0.1.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-log": "^2.0.0",
    "hexo-pagination": "^1.0.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^0.2.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-util": "^2.4.0",
    "inferno": "^7.4.6",
    "inferno-create-element": "^7.4.6"
  }
}

```

**Comment by Misaka13514** [comment]
Are you using the default `landscape` theme? If the answer is negative, use the default theme, try again and see the layout.

**Comment by CRH6F-A-0464** [comment]
@Misaka13514 I don't have the default theme here......

**Comment by stevenjoezhang** [comment]
Please open an issue here: https://github.com/ppoffice/hexo-theme-icarus/issues
