### ISSUE TITLE
toc helpers bug?

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4606]
## Check List

Please check followings before submitting a new issue.

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [X] I have already searched existing issues and they are not help  to me
- [X] I examined error or warning messages and it's difficult to solve
- [X] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [X] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

hexo的[toc輔助函數](https://hexo.io/zh-tw/docs/helpers#toc)
生成的toc内容不是應該在`<ol class='toc'></div>`裏面麽？
爲什麽有的toc内容在外面？

![image](https://user-images.githubusercontent.com/16351105/103453649-eca83d00-4d16-11eb-87ad-8b6d7dba8394.png)

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/issues/2137
