### ISSUE TITLE
start contributing by recreating an issue , but how to re create ?

### ISSUE THREAD

**Issue by gautamz07** [hexojs/hexo#4609]
So I was tinkering around hexo and want to start contributing, just want to ask , I see for contributing , you basically run the following commands :-

```
$ git clone https://github.com/<username>/hexo.git
$ cd hexo
$ npm install
$ git submodule update --init
```

Now , after I have the above done , I get the following structure.

```
.github
bin
lib
node_modules
tests
```

Say I want to debug issue #4603 ( feel free to point me to any other issue to re create ), how would I recreate this issue in my local setup now , any idea ?

**Comment by stevenjoezhang** [comment]
In general, we need to reproduce the bug with all the blog source code
