### ISSUE TITLE
post with subtitle

### ISSUE THREAD

**Issue by generalibm** [hexojs/hexo#4611]
## Check List

Please check followings before submitting a new feature request.

- [V] I have already read [Docs page](https://hexo.io/docs/)
- [V] I have already searched existing issues

## Feature Request
I hope that `hexo new post "tiltle"` can generate an extra `subtile` in front-matter so that I could describe my new post with four parts `title`, `subtile` and `description` in introduction and then the body of the post, which wold like the articles in The economist.

## Others
I know that some theme has add this feature like [this one](https://mulder21c.github.io/hexo-theme-amorfati/2019/01/21/post-with-subtitle/).

**Comment by jiangtj** [comment]
```
---
title: {{ title }}
date: {{ date }}
// ...
subtitle: {{ subtitle }}
---
```

You can add subtitle in Scaffolds.

https://hexo.io/docs/writing.html#Scaffolds

And add `--subtitle` in cli

```
hexo new post "tiltle" --subtitle=subtitle
```

And then you need to modify the theme layout to display the subtitle.
