### ISSUE TITLE
How do I init old version

### ISSUE THREAD

**Issue by LXF-DX3906** [hexojs/hexo#4612]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by LXF-DX3906** [comment]
I have tried to run `npm install hexo@4.2.0` to install the old version hexo, but I generated the latest version hexo when I run `hexo init blog`.

**Comment by stevenjoezhang** [comment]
`hexo init blog` will always install the latest version. You can try to init the blog first, then run `npm install hexo@4.2.0` in the blog directory.
