### ISSUE TITLE
Enable custom theme/source dir configuration

### ISSUE THREAD

**Issue by sshwy** [hexojs/hexo#4613]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Enable custom configuration for directory when creating a new hexo instance.

## Others

I'm recently working on my custom theme for hexo, and I want to make tests for it. I've read [API Document](https://hexo.io/zh-cn/api/) and [some of source code of hexo](https://github.com/hexojs/hexo/blob/master/lib/hexo/index.js), neither of which tells me a way to specify custom directories for theme and source respectively. This makes it difficult for me to test my theme.

**Comment by stevenjoezhang** [comment]
You can the theme by installing it via npm.
```
npm i /local/path/to/hexo-theme-xxx
```
