### ISSUE TITLE
请问一下，在我搭建hexo时npm install hexo-deployer-git --save后出现这个问题，无法部署到github

### ISSUE THREAD

**Issue by lejiaid** [hexojs/hexo#4618]
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Administrator\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\package.json'
npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No README data
npm WARN Administrator No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hexo-deployer-git@2.1.0
updated 1 package and audited 135 packages in 1.813s

8 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by stevenjoezhang** [comment]
看上去您在一个错误的目录中执行了此命令。请先进入博客目录中，再安装相关插件。

**Comment by gzlannin** [comment]
尝试在用户目录下安装

例如：

c:\Users\你的用户名\
