### ISSUE TITLE
put a pipe char (i.e. | ) between the backtick (i.e. ` ) chars in markdown cannot render properly.

### ISSUE THREAD

**Issue by BlueHeart0621** [hexojs/hexo#4624]
## Problem
I want to build a markdown table containing code enclose by \` \` grammar. It works fine except the code containing pip character (i.e | ) . Like following:

| a |  r  |
| - | - |
|  `let i=i&2`  |  r1 |
|  `let i=i\|2`  |  r2 |

On github, the source code is following:
```markdown
| a |  r  |
| - | - |
|  `let i=i&2`  |  r1 |
|  `let i=i\|2`  |  r2 |
```
When I render it by hexo, it display like this:
![图片](https://user-images.githubusercontent.com/42397957/106087283-a64fcd80-615e-11eb-8449-f9daf1f831b5.png)

It seems that hexo always regard pip character (i.e. | ) as a delimiter, despite escaping pip character or not. 

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v15.6.0
6.14.11
```

Thanks.

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo-renderer-marked/issues/138
I'm closing this issue. Please join the discussion there :)
