### ISSUE TITLE
[Feature Request]---about read the system environment variables

### ISSUE THREAD

**Issue by aner1001** [hexojs/hexo#4628]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request
Hello, developer, I am a Chinese hexo blog user. Hope to solve the following problem
Is it possible to develop, read the system environment variables in config.yml in the configuration file of the hexo blog. Like this
_config.yml
  url: $BLOG_SITE_URL
  root: /

是否可以开发出，hexo博客的配置文件中config.yml，读取系统环境变量.像这样
url: $BLOG_SITE_URL
root: /

**Comment by stevenjoezhang** [comment]
可以执行以下命令（请先备份`_config.yml`，因为会移除文件中的空行和注释）
```
hexo config url $BLOG_SITE_URL
```

**Comment by leimao** [comment]
> 可以执行以下命令（请先备份`_config.yml`，因为会移除文件中的空行和注释）
> 
> ```
> hexo config url $BLOG_SITE_URL
> ```

@stevenjoezhang 我感觉这个做法丧失了申请人的本意。我们希望`_config.yml`可以成为某个所有人都可以看到的public的file，而您的做法其实达不到我们想要的这个目的。谢谢。
