### ISSUE TITLE
CPU DoS when generating HTML for crafted Markdown documents

### ISSUE THREAD

**Issue by peng-hui** [hexojs/hexo#4629]
### Environments
`Linux pc 4.9.0-14-amd64 hexojs/hexo-cli#1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux`

### Versions
```
hexo-cli: 4.2.0
os: Linux 4.9.0-14-amd64 linux x64
node: 15.7.0
v8: 8.6.395.17-node.23
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 88
nghttp2: 1.42.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1i
cldr: 38.1
icu: 68.2
tz: 2020d
unicode: 13.0
```

#### Summary
Hexo can generate HTML web pages given certain Markdown documents. When specially crafting the Markdown file can lead to hexo execute for a much longer time. For example, I only put one Markdown file under the `source/_posts/` folder, and run `hexo g`, it takes over one minute to finish (even could not finish). I claim this is a performance issue that negatively affects user experience and needs to be addressed. 

#### Reproduce
1. Prepare special Markdown files and put them into the `source/_posts` folder. Here I provide several examples.
```python
"**_* " * 50000
```
```python
"**x [a*b**c*](d)" * 50000
```
```python
"*_* _" * 50000
```
```python
"[ a_" * 50000
```
The above snippets are in python. You can use that to generate strings and store them in Markdown files for testing.
2. Each time with one such Markdown file in a fresh hexo site. You can `hexo g` to generate a draft or build the site.
3. Check the time. Or in the previous step, you just use `time hexo g` in Linux environment. You can observe obviously longer time.

**Comment by stevenjoezhang** [comment]
See also https://github.com/markedjs/marked/issues/1927

**Comment by peng-hui** [comment]
Was this fixed already? If yes, let's close it
