### ISSUE TITLE
hexo搭建博客 文章打开后页面空白

### ISSUE THREAD

**Issue by Fusenheizi** [hexojs/hexo#4631]
主页可以打开，文章标题等正常显示，但要点进浏览后移动端出现404界面，pc端页面空白

新建一篇新的文章后，也是能在主页看到，但无法打开

博客地址： https://fusenheizi.github.io

找了很久也没找到解决方法

**Comment by stevenjoezhang** [comment]
我打开没问题 https://fusenheizi.github.io/2021/013116107.html

**Comment by Fusenheizi** [comment]
> 我打开没问题 https://fusenheizi.github.io/2021/013116107.html

嗯...因为我解决了hhhh

**Comment by stevenjoezhang** [comment]
问题解决了就好～
