### ISSUE TITLE
Rendering non-empty markdown file into html with empty body (with solution sugguested)

### ISSUE THREAD

**Issue by huangy10** [hexojs/hexo#4632]
I have already written a blog about the bug and the solution: [解决Hexo将非空白Markdown文件渲染为空白内容问题](https://www.codewoody.com/posts/59722/).

It is quit annoying that hexo sometime renders a non-empty markdown file into a web page with empty body when I am editing the md file.  Here the "empty body" means that the target html is generated with header and footers,  nevertheless the title and content are gone. By resaving the markdown file again, it is possible that the correct html file can be generated. After diving into the source code of hexo, I find out the reason.

Actually, when the bug occurs, the `data.content` is an empty string from the beginning when is is read from the file. This is because chokidar trigger the `onchange` event too fast. When the md file is modified, the `onchange` event is triggered when the OS starts writing the md file. It is possible that when hexo tries to retrieve the file content, the writing process is not finished yet. Then hexo will get an empty string.

To solve the problem, the watcher of chokidar should be given the option `awaitWriteFinish`. According to the docuemnt of chokidar

> `awaitWriteFinish` (default: `false`). By default, the add event will fire when a file first appear on disk, before the entire file has been written. Furthermore, in some cases some change events will be emitted while the file is being written. In some cases, especially when watching for large files there will be a need to wait for the write operation to finish before responding to a file creation or modification. Setting `awaitWriteFinish` to `true` (or a truthy value) will poll file size, holding its `add` and `change` events until the size does not change for a configurable amount of time. The appropriate duration setting is heavily dependent on the OS and hardware. For accurate detection this parameter should be relatively high, making file watching much less responsive. Use with caution.
> 
> - `options.awaitWriteFinish` can be set to an object in order to adjust timing params:
>     - `awaitWriteFinish.stabilityThreshold` (default: `2000`). Amount of time in milliseconds for a file size to remain constant before emitting its event.
>     - `awaitWriteFinish.pollInterval` (default: 100). File size polling interval.

Specifically, in file `lib/box/index.js`, changing the initial value of `options` of  class `Box` like this:

```js
this.options = Object.assign({
  persistent: true,
  awaitWriteFinish: {
      stabilityThreshold: 200
  }
}, options);
```

will solve this bug.

## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

**Comment by huangy10** [comment]
I notice that in line 80 of file `lib/plugins/processor/asset.js`, the is a comment says that

```js
// FIXME: Data may be inserted when reading files. Load it again to prevent
// race condition. We have to solve this in warehouse.
```

I think may this issue will solve this problem as well.

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/4271 https://github.com/hexojs/hexo/issues/2245
