### ISSUE TITLE
hexo deploy not successful

### ISSUE THREAD

**Issue by VincentCheungCW** [hexojs/hexo#4635]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
v13.12.0
6.14.4
```

**Your site `_config.yml`** (Optional)

```
deploy:
  type: git
  repo: https://github.com/VincentCheungCW/VincentCheungCW.github.io.git
  branch: master
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 
├── hexo@5.3.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.3.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
└── hexo-theme-landscape@0.0.3
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.3.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3"
  }
}

```

## Others

when i run `hexo d`, encountered this:
 jiang@JianeMacBook-Pro  ~/Documents/blog  hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
 jiang@JianeMacBook-Pro  ~/Documents/blog  

nothing added on github repo

**Comment by hjhnb** [comment]
Has it been resolved?

**Comment by VincentCheungCW** [comment]
> Has it been resolved?

not yet

**Comment by akemihomura0105** [comment]
same problem with you :(

**Comment by akemihomura0105** [comment]
Same problem with you :(
When I try to use git push in .deploy_git by hand, this is work. But when I use the hexo deploy, the same problem appear.

nothing added on github repo

**Comment by silent198214** [comment]
Same problem with me, even new hexo project.

**Comment by strsun** [comment]
![image](https://user-images.githubusercontent.com/78631256/107145501-f445ac00-697c-11eb-81a8-c7165d596857.png)

It seems I have the same problem. When I type 'hexo deploy' , the console will output the result as I the image attached. And my github nothing changed. I have spent almost two days above this and test on  another machine, github account. But it still failed.

**Comment by lqj9600** [comment]
I have the same problem！！！

**Comment by fristalpha** [comment]
为啥都有这种问题

**Comment by mk310** [comment]
我在mac 和 ubuntu上都试过了 还换了了个账号 还是解决不了

**Comment by My-WZJ233** [comment]
弄了一下午，试了好多方法，都不管用

**Comment by nebulacat000** [comment]
我也是，有大神指导一下吗

**Comment by hizablet** [comment]
遇到一样的问题了为啥呢？

**Comment by caohuilong** [comment]
同样的问题，难顶

**Comment by so1n** [comment]
我出现了相同的问题,版本5.3.0.但是3.3.8版本并没有该问题

**Comment by hjhnb** [comment]
大家可以进群交流一下解决办法：qq857473043

**Comment by hizablet** [comment]
> ![image](https://user-images.githubusercontent.com/78631256/107145501-f445ac00-697c-11eb-81a8-c7165d596857.png)
> 
> It seems I have the same problem. When I type 'hexo deploy' , the console will output the result as the image I attached. But my github repositories nothing changed. I have spent almost two days above this and test on another machine, github account. It still failed.

-----中文-----
是的不知道是什么原因，我是之前弄了一个博客，然后想搭建一个新博客，环境还是一样，就是换了一个文件夹进行【GIt bash here】，然后SSH也连接了新的GIthub 账号，因为配置【ssh -T git@github.com】 提示成功了，所以应该不是SSH的原因，然后我的站点配置文件【_config.yml】之前按这样的设置是可以的：
```
deploy: 
  type: git
  repository: https://github.com/username/username.github.io
  branch: main #这里我是弄的GitHub默认的main分支，不是master分支
```
我新的账号配置也是这样👆，空格都加了！`hexo clean`和`hexo g`和`hexo s`都没有问题，就是`hexo d`配置出现：
```
$ hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
```
我觉得可能是有Bug？？？

**Comment by strsun** [comment]
> > ![image](https://user-images.githubusercontent.com/78631256/107145501-f445ac00-697c-11eb-81a8-c7165d596857.png)
> > It seems I have the same problem. When I type 'hexo deploy' , the console will output the result as the image I attached. But my github repositories nothing changed. I have spent almost two days above this and test on another machine, github account. It still failed.
> 
> -----中文-----
> 是的不知道是什么原因，我是之前弄了一个博客，然后想搭建一个新博客，环境还是一样，就是换了一个文件夹进行【GIt bash here】，然后SSH也连接了新的GIthub 账号，因为配置【ssh -T [git@github.com](mailto:git@github.com)】 提示成功了，所以应该不是SSH的原因，然后我的站点配置文件【_config.yml】之前按这样的设置是可以的：
> 
> ```
> deploy: 
>   type: git
>   repository: https://github.com/username/username.github.io
>   branch: main #这里我是弄的GitHub默认的main分支，不是master分支
> ```
> 
> 我新的账号配置也是这样👆，空格都加了！`hexo clean`和`hexo g`和`hexo s`都没有问题，就是`hexo d`配置出现：
> 
> ```
> $ hexo d
> INFO  Validating config
> INFO  Deploying: git
> INFO  Clearing .deploy_git folder...
> INFO  Copying files from public folder...
> ```
> 
> 我觉得可能是有Bug？？？

看起来是，我反复搭建了四五次，都会出现这样的问题，现在的情况是，寻找一个其他的解决方法

**Comment by stevenjoezhang** [comment]
大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈

```
npm un hexo-deployer-git
npm i hexojs/hexo-deployer-git
```

**Comment by so1n** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

未在master安装的输出:
```bash
➜  blog hexo d        
(node:28047) ExperimentalWarning: The fs.promises API is experimental
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
```
在master安装:
```bash
➜  blog hexo d        
(node:28047) ExperimentalWarning: The fs.promises API is experimental
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
位于分支 master
无文件要提交，干净的工作区
分支 'master' 设置为跟踪来自 'git@github.com:so1n/so1n.github.io.git' 的远程分支 'master'。
Everything up-to-date
INFO  Deploy done: git
```

多了一段输出, 但还是不会提交

**Comment by My-WZJ233** [comment]
可不可以在执行完hexo g命令之后，直接用VSCode的源代码管理功能把public文件夹中的文件手动部署到GitHub

**Comment by stevenjoezhang** [comment]
`hexo-deployer-git` version 3.0.0 has been released, please update the plugin to resolve this issue.

`hexo-deployer-git` 3.0.0 版本已发布，请更新插件来修复此问题。

```
npm i hexo-deployer-git@3.0.0
```

There is a discussion about it: #4634
I'm closing this issue. Please join the discussion there :)
