### ISSUE TITLE
请教一下，当我使用“hexo d”想要将本地的hexo部署到github上面时，反馈的提示是这样的

### ISSUE THREAD

**Issue by nebulacat000** [hexojs/hexo#4636]
$ hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...

它并没有在网页生效，甚至在仓库也没看到改变

**Comment by miangou** [comment]
建议查看这个Issues
https://github.com/hexojs/hexo/issues/4634

**Comment by Minghezhao** [comment]
所以我现在解决办法是手动push到仓库里

**Comment by TszHong0411** [comment]
跟我一模一樣...

**Comment by nebulacat000** [comment]
> 建议查看这个Issues
> #4634

你好，首先谢谢你的回帖！！！但是因为我是第一次往仓库push文件，所以尝试了直接往main的branch上传public的文件（网页拖入），上传成功了，但是网页刷新后却是404。。。

**Comment by nebulacat000** [comment]
> 所以我现在解决办法是手动push到仓库里

我是在网页直接将public拖入到main的branch力的，但是用https://username.github.io/网页登入却是404了。。。

**Comment by TszHong0411** [comment]
要等

**Comment by TszHong0411** [comment]
> > 所以我现在解决办法是手动push到仓库里
> 
> 我是在网页直接将public拖入到main的branch力的，但是用[https://username.github.io/网页登入却是404了。。。](https://username.github.io/%E7%BD%91%E9%A1%B5%E7%99%BB%E5%85%A5%E5%8D%B4%E6%98%AF404%E4%BA%86%E3%80%82%E3%80%82%E3%80%82)

你的github pages好像没开启

**Comment by nebulacat000** [comment]
> > > 所以我现在解决办法是手动push到仓库里
> > 
> > 
> > 我是在网页直接将public拖入到main的branch力的，但是用[https://username.github.io/网页登入却是404了。。。](https://username.github.io/%E7%BD%91%E9%A1%B5%E7%99%BB%E5%85%A5%E5%8D%B4%E6%98%AF404%E4%BA%86%E3%80%82%E3%80%82%E3%80%82)
> 
> 你的github pages好像没开启

请问你指的是我的仓库那里的setting的github pages吗？我那里显示为
Your site is published at https://username.github.io/
应该就是开启了

**Comment by hizablet** [comment]
遇到同样的问题！！！请问是为什么呀？我站点配置文件也没有错啊…快哭了

**Comment by hizablet** [comment]
hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...

_config.yml have blank ` `
```
deploy:
  type: git
  repository: https://github.com/h****t/h****t.github.io
  branch: main
```
hexo clean
```
$ hexo clean
INFO  Validating config
INFO  Deleted database.
INFO  Deleted public folder.
```
hexo g
```
$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 821 ms
(node:1032) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1032) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:1032) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:1032) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:1032) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:1032) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Generated: archives/index.html
INFO  Generated: archives/2021/index.html
INFO  Generated: archives/2021/02/index.html
INFO  Generated: index.html
INFO  Generated: fancybox/jquery.fancybox.min.css
INFO  Generated: js/script.js
INFO  Generated: css/style.css
INFO  Generated: 2021/02/07/hello-world/index.html
INFO  Generated: css/fonts/fontawesome-webfont.woff2
INFO  Generated: css/fonts/fontawesome-webfont.eot
INFO  Generated: css/fonts/FontAwesome.otf
INFO  Generated: css/fonts/fontawesome-webfont.woff
INFO  Generated: fancybox/jquery.fancybox.min.js
INFO  Generated: css/fonts/fontawesome-webfont.ttf
INFO  Generated: js/jquery-3.4.1.min.js
INFO  Generated: css/images/banner.jpg
INFO  Generated: css/fonts/fontawesome-webfont.svg
INFO  17 files generated in 1.98 s
```
hexo s
```
$ hexo s
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
```
hexo d
```
$ hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
```
it stopped at `INFO  Copying files from public folder...`
i think my`_config.yml`is right, beacause i deploy another github account and it succeed, but i dont know why this account failed, SSH is connected:
```
$ ssh -T git@github.com
Hi h****t! You've successfully authenticated, but GitHub does not provide shell access.
```
Please Help me!!!😭，Thanks very much！！！

**Comment by nebulacat000** [comment]
> hexo d
> INFO Validating config
> INFO Deploying: git
> INFO Clearing .deploy_git folder...
> INFO Copying files from public folder...
> 
> _config.yml have blank ` `
> 
> ```
> deploy:
>   type: git
>   repository: https://github.com/h****t/h****t.github.io
>   branch: main
> ```
> 
> hexo clean
> 
> ```
> $ hexo clean
> INFO  Validating config
> INFO  Deleted database.
> INFO  Deleted public folder.
> ```
> 
> hexo g
> 
> ```
> $ hexo g
> INFO  Validating config
> INFO  Start processing
> INFO  Files loaded in 821 ms
> (node:1032) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:1032) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:1032) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> (node:1032) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (node:1032) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:1032) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> INFO  Generated: archives/index.html
> INFO  Generated: archives/2021/index.html
> INFO  Generated: archives/2021/02/index.html
> INFO  Generated: index.html
> INFO  Generated: fancybox/jquery.fancybox.min.css
> INFO  Generated: js/script.js
> INFO  Generated: css/style.css
> INFO  Generated: 2021/02/07/hello-world/index.html
> INFO  Generated: css/fonts/fontawesome-webfont.woff2
> INFO  Generated: css/fonts/fontawesome-webfont.eot
> INFO  Generated: css/fonts/FontAwesome.otf
> INFO  Generated: css/fonts/fontawesome-webfont.woff
> INFO  Generated: fancybox/jquery.fancybox.min.js
> INFO  Generated: css/fonts/fontawesome-webfont.ttf
> INFO  Generated: js/jquery-3.4.1.min.js
> INFO  Generated: css/images/banner.jpg
> INFO  Generated: css/fonts/fontawesome-webfont.svg
> INFO  17 files generated in 1.98 s
> ```
> 
> hexo s
> 
> ```
> $ hexo s
> INFO  Validating config
> INFO  Start processing
> INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
> ```
> 
> hexo d
> 
> ```
> $ hexo d
> INFO  Validating config
> INFO  Deploying: git
> INFO  Clearing .deploy_git folder...
> INFO  Copying files from public folder...
> ```
> 
> it stopped at `INFO Copying files from public folder...`
> i think my`_config.yml`is right, because i deploy another Github account and it succeed, but i dont know why this account failed, SSH is connected:
> 
> ```
> $ ssh -T git@github.com
> Hi h****t! You've successfully authenticated, but GitHub does not provide shell access.
> ```
> 
> Please Help me!!!😭，Thanks very much！！！
> 在国外的网站看到也有人有这个问题，希望大佬门能解决下🙏

我目前可以访问了，我的解决办法也是借鉴大佬们的做法，直接将public上传到github对应的仓库下，但是因为我对git bash不太熟悉，所以我是直接在仓库页面那里拖入public文件的，而且刚拖完页面刷新也是404，这里的话等个十分钟左右就好了

**Comment by nebulacat000** [comment]
> 所以我现在解决办法是手动push到仓库里

你好，我等了十分钟左右吧，就可以了，再次感谢！！！

**Comment by nebulacat000** [comment]
> 建议查看这个Issues
> #4634

你好，等待了十分钟左右就可以了，再次感谢！！！

**Comment by hjhnb** [comment]
大家可以进群交流一下解决办法：qq857473043

**Comment by jcg9487** [comment]
我也是这个问题，不知道大佬们解决没，而且我本地预览，使用next主题，列表上不显示图片，文章里显示。

**Comment by hizablet** [comment]
> 我也是这个问题，不知道大佬们解决没，而且我本地预览，使用next主题，列表上不显示图片，文章里显示。

预览都可以啊，就是部署不了…

**Comment by stevenjoezhang** [comment]
大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈

```
npm un hexo-deployer-git
npm i hexojs/hexo-deployer-git
```

**Comment by ailaiwuyou** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

可以解决问题

**Comment by TszHong0411** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

贊

**Comment by caohuilong** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

可以解决，赞！

**Comment by Douglasssy** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

ohhhhhhh it works！！！

**Comment by git-liweichao** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

解决了卡我好久的问题，厉害！

**Comment by nebulacat000** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

太赞了！！！

**Comment by hizablet** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

Github的默认分支不是main吗？

**Comment by hizablet** [comment]
> > hexo d
> > INFO Validating config
> > INFO Deploying: git
> > INFO Clearing .deploy_git folder...
> > INFO Copying files from public folder...
> > _config.yml have blank ` `
> > ```
> > deploy:
> >   type: git
> >   repository: https://github.com/h****t/h****t.github.io
> >   branch: main
> > ```
> > 
> > 
> > hexo clean
> > ```
> > $ hexo clean
> > INFO  Validating config
> > INFO  Deleted database.
> > INFO  Deleted public folder.
> > ```
> > 
> > 
> > hexo g
> > ```
> > $ hexo g
> > INFO  Validating config
> > INFO  Start processing
> > INFO  Files loaded in 821 ms
> > (node:1032) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > (node:1032) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> > (node:1032) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> > (node:1032) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> > (node:1032) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> > (node:1032) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> > INFO  Generated: archives/index.html
> > INFO  Generated: archives/2021/index.html
> > INFO  Generated: archives/2021/02/index.html
> > INFO  Generated: index.html
> > INFO  Generated: fancybox/jquery.fancybox.min.css
> > INFO  Generated: js/script.js
> > INFO  Generated: css/style.css
> > INFO  Generated: 2021/02/07/hello-world/index.html
> > INFO  Generated: css/fonts/fontawesome-webfont.woff2
> > INFO  Generated: css/fonts/fontawesome-webfont.eot
> > INFO  Generated: css/fonts/FontAwesome.otf
> > INFO  Generated: css/fonts/fontawesome-webfont.woff
> > INFO  Generated: fancybox/jquery.fancybox.min.js
> > INFO  Generated: css/fonts/fontawesome-webfont.ttf
> > INFO  Generated: js/jquery-3.4.1.min.js
> > INFO  Generated: css/images/banner.jpg
> > INFO  Generated: css/fonts/fontawesome-webfont.svg
> > INFO  17 files generated in 1.98 s
> > ```
> > 
> > 
> > hexo s
> > ```
> > $ hexo s
> > INFO  Validating config
> > INFO  Start processing
> > INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
> > ```
> > 
> > 
> > hexo d
> > ```
> > $ hexo d
> > INFO  Validating config
> > INFO  Deploying: git
> > INFO  Clearing .deploy_git folder...
> > INFO  Copying files from public folder...
> > ```
> > 
> > 
> > it stopped at `INFO Copying files from public folder...`
> > i think my`_config.yml`is right, because i deploy another Github account and it succeed, but i dont know why this account failed, SSH is connected:
> > ```
> > $ ssh -T git@github.com
> > Hi h****t! You've successfully authenticated, but GitHub does not provide shell access.
> > ```
> > 
> > 
> > Please Help me!!!😭，Thanks very much！！！
> > 在国外的网站看到也有人有这个问题，希望大佬门能解决下🙏
> 
> 我目前可以访问了，我的解决办法也是借鉴大佬们的做法，直接将public上传到github对应的仓库下，但是因为我对git bash不太熟悉，所以我是直接在仓库页面那里拖入public文件的，而且刚拖完页面刷新也是404，这里的话等个十分钟左右就好了

除了托文件夹还有什么方法吗😂

**Comment by hizablet** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

`hexo d` 可以解决问题了！谢谢您！

**Comment by hizablet** [comment]
> > 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> > ```
> > npm un hexo-deployer-git
> > npm i hexojs/hexo-deployer-git
> > ```
> 
> `hexo d` 可以部署了！谢谢您！
> 但是域名还是404不知道为啥

域名问题已经解决，是GitHub的设置问题：
因为我设置了private🤦‍
`Private`改成`Public`功能：首先点击`setting`，然后往下翻找到`Danger Zone`，然后点击`Change visibility`选择`Make public`并输入仓库名进行确认即可。选择了`Public`功能之后，再在`setting`界面，找到`GitHub Pages`标题下的`Source`，把`None`改成`main`即可。然后刷新页面，之后的设置就可以通过域名`username.github.io`访问啦！

**Comment by simeixue** [comment]
> 大家能否帮忙测试一下，直接从 master 分支安装 hexo-deployer-git 是否可以解决问题？谢谢反馈
> 
> ```
> npm un hexo-deployer-git
> npm i hexojs/hexo-deployer-git
> ```

可以了！！！

**Comment by stevenjoezhang** [comment]
`hexo-deployer-git` version 3.0.0 has been released, please update the plugin to resolve this issue.

`hexo-deployer-git` 3.0.0 版本已发布，请更新插件来修复此问题。

```
npm i hexo-deployer-git@3.0.0
```

There is a discussion about it: #4634
I'm closing this issue. Please join the discussion there :)

**Comment by dgy924143558** [comment]
在page setting的Source里改成hexo设置的branch，默认是main所以不行。

**Comment by totooss** [comment]
我在搭建博客的时候hexo d 停止在INFO Validating config，没有报错，ssh -T -p 443 git@ssh.github.com 显示的也是成功，请问怎么解决
