### ISSUE TITLE
支持 HTML 注释语法元信息声明？ (Support HTML comment syntax meta information declaration?)

### ISSUE THREAD

**Issue by xianghongai** [hexojs/hexo#4637]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

现在是以 YAML 前置元信息形式声明的：
Currently using YAML pre-metainformation form:

```markdown
---
<hexo option>
---
```

上面声明内容，当在本地用其它工具查看时，会被渲染出来。
The content declared above will be rendered when viewed with other tools.

这类配置是给 CLI 用的，编辑者只需要在源码文件中查看即可。我们能否支持 HTML 注释方式实现？
These configurations are for CLI, and editors only need to view them in the source file. Can we support HTML comments?

```markdown
<!---
<hexo option>
--->
```

这样 浏览器 (Markdown Viewer)、编辑器 (VSCode、Typora) 这类本地工具渲染时，能忽略这类注释内容。
In this way, other tools such as browsers (Markdown Viewer) and editors (VSCode, Typora) can ignore meta comments when rendering.

使用 `<!---  --->` 约定，是为了区分标准 `<!--  -->` 语法，以跳过某些不是文档元信息的内容。
The convention of `<!--- --->` is used to distinguish the standard `<!-- -->` syntax, that can skip some content that is not document meta information.

## Others

NULL.

**Comment by stevenjoezhang** [comment]
你可以向 hexo-front-matter 提交 pull request 改变这一功能
