### ISSUE TITLE
hexo-deployer-git, it is not published on Github, and it runs without errors

### ISSUE THREAD

**Issue by Multiplys** [hexojs/hexo#4639]
It is not published on Github, and it runs without errors

C:\program\hexo\test>hexo deploy
INFO Validating config
INFO Start processing
INFO Files loaded in 271 ms
(node:17036) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
(node:17036) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:17036) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:17036) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:17036) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:17036) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO Generated: archives/index.html
INFO Generated: archives/2021/index.html
INFO Generated: archives/2021/02/index.html
INFO Generated: uncategorized/hello-world/index.html
INFO Generated: js/script.js
INFO Generated: index.html
INFO Generated: fancybox/jquery.fancybox.min.css
INFO Generated: css/style.css
INFO Generated: css/fonts/fontawesome-webfont.woff2
INFO Generated: css/fonts/fontawesome-webfont.woff
INFO Generated: css/fonts/FontAwesome.otf
INFO Generated: css/fonts/fontawesome-webfont.ttf
INFO Generated: css/fonts/fontawesome-webfont.eot
INFO Generated: css/images/banner.jpg
INFO Generated: fancybox/jquery.fancybox.min.js
INFO Generated: js/jquery-3.4.1.min.js
INFO Generated: css/fonts/fontawesome-webfont.svg
INFO 17 files generated in 1.14 s
INFO Deploying: git
INFO Clearing .deploy_git folder...
INFO Copying files from public folder...

The .deploy_git folder is generated in the current directory, in which is the git folder and the generated static files
_config.yml:

deploy:
type: git
repo: https://github.com/Multiplys/Multiplys.github.io
branch: main
token: xxxxxxx
name: Multiplys
email: xx@xx.com

**Comment by SkyYkb** [comment]
Same problem.
```
$ hexo deploy
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
$
```
And the webpages just can't be deployed...

**Comment by izjr** [comment]
`npm un hexo-deployer-git
npm i hexojs/hexo-deployer-git`

**Comment by izjr** [comment]
`npm un hexo-deployer-git`
`npm i hexojs/hexo-deployer-git`

**Comment by stevenjoezhang** [comment]
`hexo-deployer-git` version 3.0.0 has been released, please update the plugin to resolve this issue.

`hexo-deployer-git` 3.0.0 版本已发布，请更新插件来修复此问题。

```
npm i hexo-deployer-git@3.0.0
```

There is a discussion about it: #4634
I'm closing this issue. Please join the discussion there :)
