### ISSUE TITLE
Is there any built in tag/method to link to homepage?

### ISSUE THREAD

**Issue by adnan360** [hexojs/hexo#4647]
## Check List

Please check followings before submitting a new issue.

- [ x ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ x ] I have already searched existing issues and they are not help to me
- [ x ] I examined error or warning messages and it's difficult to solve
- [ x ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ x ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

I've checked [docs for tags](https://hexo.io/docs/tag-plugins). But I found no tag that I could use to link to homepage from both my pages and posts markdown. Is there any built in way to link to homepage without installing any plugins?

I want it to work on both posts and pages.

## Environment & Settings

**Node.js & npm version**

```
~ $ node --version
v14.15.4
~ $ npm --version
6.14.10
```

**Your site `_config.yml`** (Optional)

```
...
permalink: :year/:month/:title.html
#permalink: :id/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
...
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
$ npm ls --depth 0
hexo-site@0.0.0 /run/media/user/storage/Codes/lazplanet.gitlab.io
├── hexo@5.3.0
├── hexo-asset-link@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-migrator-wordpress@2.1.2
├── hexo-multiauthor@0.0.1
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.3.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@1.0.0
├── request@2.88.2
├── turndown@7.0.0
└── xml2js@0.4.23
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.3.0"
  },
  "dependencies": {
    "hexo": "^5.3.0",
    "hexo-asset-link": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-multiauthor": "0.0.1",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^1.0.0",
    "request": "^2.88.2",
    "turndown": "^7.0.0",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "hexo-migrator-wordpress": "^2.1.2"
  }
}
```

**Comment by stevenjoezhang** [comment]
Try this:
```
[Home page](/)
```

**Comment by adnan360** [comment]
@stevenjoezhang 
It works both on pages and posts, even with my permalink setup which is great. The only problem is if I keep the site on a subdirectory, it will point to the domain, not the subdirectory. So I think this is a nice workaround, but not a permanent solution.
