### ISSUE TITLE
Hexo deploy git isn't working at my pc

### ISSUE THREAD

**Issue by zzysite** [hexojs/hexo#4648]
I'm writing my blog today, but when I use `hexo deploy` command, At lease it says `INFO  Copying files from public folder...`. It's so weird, it can't apply my files to GitHub. I'm sure I have my own SSH key and true config at my pc

Runtime:
* Windows 10 64-bit
* Node.js 14.15.5
* Git for Windows 2.30.1

## How to reproduce?

* Step1: Use `hexo clean` and `hexo g` command
* Step2 Use `hexo deploy` command

![image.png](https://i.loli.net/2021/02/11/jzZUueT5VsXAmYg.png)

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo/issues/4634
I'm closing this issue. Please join the discussion there :)
