### ISSUE TITLE
JavaScript代码执行有问题

### ISSUE THREAD

**Issue by ssx976432449** [hexojs/hexo#4651]
## Check List

我检查过我的JavaScript代码没有问题，浏览器的缓存我也清理过，但还是出现不了我想要的效果

## Information

我在应用一个主题以后在JavaScript文件中加入一点我自己的代码，但是我的代码在我第一次进入页面时没有执行，我在这个页面刷新以后就执行了。求助！

加入的代码是：

```
$(".hideWord").mouseenter(function(){
	$(".hideWord").css("color","wheat");
});
$(".hideWord").mouseleave(function(){
	$(".hideWord").css("color","brown");
});
```

**Comment by oCoke** [comment]
这个有可能是主题的问题。

**Comment by stevenjoezhang** [comment]
估计是PJAX的问题，你可以发个链接让大家帮忙看看。
