### ISSUE TITLE
After hexo g. < & > &lt; & &gt; &amp; 為什麼？

### ISSUE THREAD

**Issue by TszHong0411** [hexojs/hexo#4657]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

I have a Javascript file. After `hexo cl && hexo g`. 
![](https://cdn.jsdelivr.net/gh/tszhong0411/image/issue1.png)

## Environment & Settings

**Node.js & npm version**

``` 
Node.js: v14.15.5 Npm: 7.5.4
```

**Your site `_config.yml`** (Optional)

```
https://tszhong0411.vercel.app
```

**Your theme `_config.yml`** (Optional)

```
butterfly
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.3.0"
  },
  "dependencies": {
    "gulp": "^4.0.2",
    "hexo": "^5.0.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-butterfly-artitalk": "^1.0.1",
    "hexo-deployer-git": "^3.0.0",
    "hexo-excerpt": "^1.1.6",
    "hexo-filter-github-emojis": "^3.0.4",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-calendar": "github:howiefh/hexo-generator-calendar",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-search": "^2.4.1",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-offline": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-web-push-notification": "^0.2.3",
    "hexo-wordcount": "^6.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.13.8",
    "@babel/preset-env": "^7.13.9",
    "gulp-babel": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-html-minifier-terser": "^6.0.1",
    "gulp-htmlclean": "^2.7.22",
    "gulp-uglify": "^3.0.2",
    "install": "^0.13.0"
  }
}

```

**Comment by jiangtj** [comment]
Upgrade to the latest hexo, does this problem still exist?
