### ISSUE TITLE
Couldn't type # in subtitle

### ISSUE THREAD

**Issue by thewon86** [hexojs/hexo#4658]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
```
###  shell string length：`${#var}`
```
## Actual behavior

Unhandled rejection Template render error: (unknown path)
  Error: expected end of comment, got end of file

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v10.23.3
6.14.11
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
NexT version 8.2.1
Documentation: https://theme-next.js.org
========================================
hexo: 5.2.0
hexo-cli: 4.2.0
os: Linux 3.10.0-1160.15.2.el7.x86_64 linux x64
http_parser: 2.9.4
node: 10.23.3
v8: 6.8.275.32-node.59
uv: 1.34.2
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.41.0
napi: 7
openssl: 1.1.1i
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019c
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
`{#` is interpreted as a comment of the nunjucks template by Hexo

**Comment by retzzz** [comment]
@stevenjoezhang when I disable Nunjucks, all tag plugin described in [https://hexo.io/docs/tag-plugins](https://hexo.io/docs/tag-plugins) doesn't work. Is it possible to disable the comments checking of Nunjucks only.

Or do you know if there is any other method to add html anchor `<id="anchor_name">` except using the way I mentioned above?

**Comment by stevenjoezhang** [comment]
You can try another markdown renderer plugin (instead of pandoc). For example, [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it) is compatible with latex syntax and will add anchors automatically

**Comment by retzzz** [comment]
@stevenjoezhang I tried _hexo-renderer-markdown-it_. It can add anchor for heading automatically. But I can use below method to add anchor for any text before
```
[text]{#anchor}
```

Is there any way to add anchor to any text with _hexo-renderer-markdown-it_ except use html tag?

**Comment by retzzz** [comment]
I used html `<span id="HTML-anchor"></span>` to add anchor in any place. It looks not too bad.

**Comment by narutozxp** [comment]
@retzzz add space between { and #
