### ISSUE TITLE
Article to Email Template 

### ISSUE THREAD

**Issue by dprutean** [hexojs/hexo#4661]
I would like to use a markdown page (post) to generate an email template.
Is this possible?
Requirements:
* images have to use the complete domain name (https://somedomain.com/...)
* add some inline CSS to images. Emails are using a basic HTML

Here an example of translation [example Markdown to email](https://pbpython.com/markdown-email.html)

**Comment by jiangtj** [comment]
I think this is not a function that hexo needs to pay attention to. If you need to convert md files to html, you can use marked or markdown-it, etc.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#e-mail_links
