### ISSUE TITLE
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated. Deprecated as of 10.7.0. Please use highlight(code, options) instead.

### ISSUE THREAD

**Issue by KevinZjYang** [hexojs/hexo#4672]
## Check List

Please check followings before submitting a new issue.

- [x] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.

[highlight.js new version](https://github.com/highlightjs/highlight.js/releases/tag/10.7.1)

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo-util/issues/245
I'm closing this issue. Please join the discussion there :)
