### ISSUE TITLE
Hexo安装失败 Failed to install Hexo using npm

### ISSUE THREAD

**Issue by camoufleur-yu** [hexojs/hexo#4673]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- (I didn't because I simply failed to install hexo first)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

Having installed Node.js and git, I tried to install Hexo in Git Bash at C:\myblog (a custom folder) with npm, and ended up with unexpected warnings:

> $ npm install -g hexo-cli

> C:\Program Files\nodejs\node_global\hexo -> C:\Program Files
\nodejs\node_global\node_modules\hexo-cli\bin\hexo

> WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\hexo-cli\node_modules\chokidar
\node_modules\fsevents): 

> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin", "arch":"any"} (current {"os":"win32", "arch":"x64"}) + hexo-cli@4.2.0

> updated 1 package in 13.079s

And, wondering whether I installed Hexo successfully, I tried to get Hexo's version (hexo -v), which turned out:

> bash: hexo: command not found

don't know what to do now.

## Environment & Settings

**Node.js & npm version**

`Node.js: v14.16.0`
`npm: 6.14.11`

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

Also, because I have to install Hexo at disk C (the only disk on my laptop), I always run git bash with admin authority

**Comment by TriDiamond** [comment]
>WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\hexo-cli\node_modules\chokidar
\node_modules\fsevents):

> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin", "arch":"any"} (current {"os":"win32", "arch":"x64"}) + hexo-cli@4.2.0

These warning doesn't affect your installation.

Since you use admin authority to run git bash, try `sudo hexo -v`
