### ISSUE TITLE
[Proposal] Live user counter in footer (per index page) or (per website) 

### ISSUE THREAD

**Issue by MartijnLindeman** [hexojs/hexo#4677]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Description:
User counter in the footer of the webpage to track/count live current users/sessions visiting the website / or each individual webpage.

Example:
(see footer)
https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page
(image)
https://gyazo.com/f536755d79667c96e843888f1897aaa5

**Comment by yoshinorin** [comment]
@MartijnLindeman 
hexo is just a static site generator.

As far as I know, it is impossible only hexo. If you want to make it you have to implement it to a theme by yourself using Google analytics API or other tools.

**Comment by stevenjoezhang** [comment]
You can try this plugin: [Revolver Maps](https://www.revolvermaps.com/?target=gallery)
