### ISSUE TITLE
安装成功 NODE.js 和 npm后，无法安装hexo

### ISSUE THREAD

**Issue by 12121-12121** [hexojs/hexo#4680]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question
安装成功 NODE.js 和 npm 后，无法安装 hexo
执行`$ npm install -g hexo-cli`命令后，报错。
```
/usr/local/node/bin/hexo -> /usr/local/node/lib/node_modules/hexo-cli/bin/hexo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ hexo-cli@4.2.0
updated 1 package in 11.155s

```
即使更换了淘宝镜像源也不行。

## Environment & Settings

**Node.js & npm version**

```
v14.16.0
6.14.11
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by aurorataro** [comment]
兄啊 最好还是发英文 中文外国开发者不一定看得懂 你这个应该是环境问题 你可以把这个发到相关的贴吧 qq群问问

**Comment by XiaMoHuaHuo-CN** [comment]
npm 报错是正常现象，这里显示你已经安装了
