### ISSUE TITLE
I have a question : In Setup your blog, there is an error using the command....

### ISSUE THREAD

**Issue by Biutefou-xhm** [hexojs/hexo#4686]
`[root@yerozi ~]# hexo init blog
/usr/lib/node_modules/hexo-cli/node_modules/chalk/source/index.js:106
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/hexo-cli/lib/hexo.js:3:15)
`
The commands related to hexo all have this error.

**Comment by Biutefou-xhm** [comment]
I have solved it

**Comment by wangwanchao** [comment]
> I have solved it

How did you deal with it?

**Comment by xiaogu-space** [comment]
I have the same problem，how did you deal with it?

**Comment by xiaogu-space** [comment]
https://segmentfault.com/a/1190000020634859

**Comment by Biutefou-xhm** [comment]
@wangwanchao @xiaogu-space I'll do it after I install it again.I think it should be installed hexo and hexo-cli.

**Comment by stevenjoezhang** [comment]
Hexo requires Node.js 12.4.0 because Node.js 10 is End-of-Life on April 30, 2021

**Comment by Biutefou-xhm** [comment]
@stevenjoezhang 
I am using node.js 12, use the command ` dnf module install -y nodejs:12 ` to install.
View the available node versions:`dnf module list nodejs`

Let me talk about the commands used in my build process:
```
yum install -y firewalld git-core
systemctl start firewalld
firewall-cmd --zone=public --add-port=4000/tcp --permanent
firewall-cmd --reload
dnf module install -y nodejs:12
npm install -g hexo hexo-cli 
hexo init xwt
cd xwt/
npm install
hexo g
hexo s 
```

I use docker to build, so in order to open the port, I installed a firewall.
Before executing the `dnf module install -y nodejs:12` command, you can check which node js is available：`dnf module list nodejs`
