### ISSUE TITLE
上传隐私信息如何删除？

### ISSUE THREAD

**Issue by yzhou15** [hexojs/hexo#4688]
上传隐私信息到仓库后，提交记录一直存在，并且可以查看。尝试过清空仓库提交记录，甚至删除仓库，但是每次hexo d 之后，所有的提交记录又都出现，如何解决这个问题？

**Comment by yzhou15** [comment]
After uploading the private information to the warehouse, the submission record always exists and can be viewed. I have tried to clear the warehouse submission records or even delete the warehouse, but every time after hexo d, all submission records appear again. How to solve this problem?

**Comment by stevenjoezhang** [comment]
在 Hexo 博客目录下找到名为 `.deploy_git` 的文件夹，将其删除。

**Comment by yzhou15** [comment]
啊，原来是这样，困扰了我一晚上。。我原先以为hexo cl&amp; hexo g就是可以重新推了。。原来需要这样做。。非常感谢呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月25日(星期天) 晚上7:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hexojs/hexo] 上传隐私信息如何删除？ (#4688)



在 Hexo 博客目录下找到名为 .deploy_git 的文件夹，将其删除。
