### ISSUE TITLE
how can i put one tag plugin in another tag plugin

### ISSUE THREAD

**Issue by shuangovo** [hexojs/hexo#4698]
I put my custom tag plugin (slider) into hideToggle;It just turn to text on my page,how can can it be rendered.
````md
{% hideToggle 题解 %}
双指针 + 哈希表
{% slider %}
![](url)
![](url)
{% endslider %}
{% endhideToggle %}
````
![捕获](https://user-images.githubusercontent.com/54254822/118578386-aa136880-b7be-11eb-983b-2c283047370b.JPG)

**Comment by stevenjoezhang** [comment]
The syntax you used is correct. The problem may be that HTML is escaped by the renderer.
`hideToggle` and `slider` are not the built-in tags of Hexo. Please ask the author of these tag plugins for help.

**Comment by shuangovo** [comment]
I works successfully through adding some javascripts
![捕获3](https://user-images.githubusercontent.com/54254822/118602761-aa732a00-b7e5-11eb-934e-dc8f00ace3c4.JPG)
