### ISSUE TITLE
Hexo Capitalization on Pages Not Working

### ISSUE THREAD

**Issue by 0rang-3** [hexojs/hexo#4700]
I want to create a page that displays some information about a Discord Bot I created. 

So, in terminal, I typed `hexo new page "Discord"`. I after that typed what I want. Then, I typed `hexo server` in terminal to run my website on my computer, and on the homescreen of my website, the "d" in "Discord" isn't capitalized. My other pages (Home, Achieve, and About) are all capitalized, but my Discord page isn't

Does anyone know a fix for this? Any help is appreciated. Thanks!

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/118949718-1abbb000-b98c-11eb-8ec8-e33d92be795b.png)

Can’t reproduce, do you use a third-party theme? they may modify the page title.

**Comment by TheScaryShark** [comment]
I used a hexo theme called Hiker (it's on the hexo website). It capitalizes a post correctly but doesn't capitalize a Hexo Page
