### ISSUE TITLE
TypeError: line.matchAll is not a function

### ISSUE THREAD

**Issue by tomcatYH** [hexojs/hexo#4702]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by tomcatYH** [comment]
node：v10.16.3
hexo: 5.4.0
hexo-cli: 4.2.0

**Comment by tomcatYH** [comment]
resolved

**Comment by WeihongPan** [comment]
> resolved

I have the same issue! How did you resolve it?

**Comment by tomcatYH** [comment]
> > resolved
> 
> I have the same issue! How did you resolve it?
The node version dose not match the hexo version; update the lasted node version

**Comment by stevenjoezhang** [comment]
Hexo requires Node.js 12.4.0 because Node.js 10 is End-of-Life on April 30, 2021

**Comment by myyangang** [comment]
@stevenjoezhang That works! Thanks you sooooooo much

**Comment by stevenjoezhang** [comment]
The minimum required Node.js version of Hexo will be updated in the next release (Perhaps Hexo 6): https://github.com/hexojs/hexo/pull/4779
