### ISSUE TITLE
Travis-CI is NOT FREE anymore!!!

### ISSUE THREAD

**Issue by Marsir04** [hexojs/hexo#4706]
In this website: [将 Hexo 部署到 GitHub Pages](https://hexo.io/zh-cn/docs/github-pages)
It's recommended that **Travis-CI** could be used **without charge** to git, BUT now it is **NOT FREE** anymore!
Please refine this page ASAP! Thanks a lot!

**Could anyone recommend some FREE CI tools to me ?** QAQ

**Comment by SukkaW** [comment]
![image](https://user-images.githubusercontent.com/40715044/119750959-e6d11500-becc-11eb-859b-014668a3c0ab.png)
