### ISSUE TITLE
How to render code blocks from other Markdown files?

### ISSUE THREAD

**Issue by bennycode** [hexojs/hexo#4708]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

I created my first Hexo tag plugin to [insert Markdown files](https://github.com/bennycode/hexo-insert-markdown) in posts. My goal is to render a page based on multiple Markdown sources. My plugin works great with plain text but it does not work well when the included Markdown files contain other tags like [codeblock](https://hexo.io/docs/tag-plugins#Code-Block). 

**Current behaviour**

When I use a `codeblock` in my post everything looks good **but** when I use `codeblock` in an external Markdown file, which is included by my plugin, then the syntax highlighting does not work properly. 

I guess I am calling the wrong render method in my plugin but which one is the right one?

That's what my plugin currently calls:

```js
return hexo.render.renderSync({
  path: 'some/markdown.md'
});
```

**Expected behaviour**

I want my plugin to render Markdown content exactly the way like Hexo.js renders all my other Markdown files. I already tried to use `marked` in my plugin but it also didn't turn out to look nice (line numbers & line highlighting is missing):

```js
const marked = require('marked');
// ...
const content = fs.readFileSync(file, 'utf8');
return marked(content);
```

## Environment & Settings

My Hexo version is 5.4.0

And these are my renderer packages:

- hexo-renderer-ejs v1.0.0
- hexo-renderer-marked v4.0.0
- hexo-renderer-scss v1.2.0
- hexo-renderer-stylus v2.0.1

## Others

Link to my plugin code:
- https://github.com/bennycode/hexo-insert-markdown

**Comment by yoshinorin** [comment]
@bennycode 
Hi :)
I'm not sure why `renderSync` function does not render codeblock but, I submitted PR to your plugin. Please check it.

> https://github.com/bennycode/hexo-insert-markdown/pull/1

**Comment by bennycode** [comment]
Thanks @yoshinorin, your PR helped me very much!

Here is the solution:

```js
hexo.extend.tag.register('insertmd', async (args) => {
  // ...
  const result = await hexo.post.render(source = file);
  return result.content;
}, {async: true});
```
