### ISSUE TITLE
Q: exclude some features when running on localhost

### ISSUE THREAD

**Issue by jjude** [hexojs/hexo#471]
Is it possible to identify if hexo is running on localhost and avoid some things like analytics? I dont want the localhost to contribute to analytics. Thank you.

**Comment by gurdotan** [comment]
@shulhi can you elaborate on how this solves the problem of having analytics only in production?
According to your example if I understand correctly, the `production` variable is always `false`, even when the site is deployed.

**Comment by shulhi** [comment]
@gurdotan Can't remember exactly, I haven't been using hexo for a while now. The idea is that the theme would read the variable from the config file and conditionally render the analytics part of the dom, although the config file would need to be adjusted for production vs development.
