### ISSUE TITLE
hexo and or config not defined

### ISSUE THREAD

**Issue by enter-rebel** [hexojs/hexo#4710]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question
I am expecting to define variable on config and use it latter on helper or template.
The attempt lead me to https://github.com/hexojs/hexo/issues/4163#issuecomment-592923480, so I use that syntax.
But it always shows that either the hexo or the config is not defined.
side note/question:
1. I am not sure when to use `<%` `<%-`  and `<%=`.
2. did we use var to define any variable, including local variable?

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**calling the partial**

```
<% partial('_partials/analytic.ejs') %>
```

**defining js variable**

```
let id= <% hexo.config.foo %>;
```

## Others

Oddly enough, even I comment that line hexo still won't serve the local server.

**Comment by jerryc127** [comment]
change `hexo.config.foo` to `config.foo`

**Comment by enter-rebel** [comment]
I already tried that even before creating this issue

**Comment by jerryc127** [comment]
hexo.config is used in script ,
you look like using in ejs ? so you only need `config` rather than `hexo.config`

**Comment by enter-rebel** [comment]
Yep, would you help me by chat?
