### ISSUE TITLE
npm无法安装hexo-cli@5.x版本

### ISSUE THREAD

**Issue by royalmetoo** [hexojs/hexo#4717]
如图，最新版本4.2，但是我git版本，和nodejs版本也已经是最新的，怎么能安装hexo 5.x版本呀？
![image](https://user-images.githubusercontent.com/53411943/121692498-b8714d80-cafa-11eb-97fc-a39f65b05e9b.png)

**Comment by jiangtj** [comment]
Re-execute the following command
```
npm install hexo-cli -g
```

**Comment by stevenjoezhang** [comment]
`hexo-cli`和`hexo`是两个不同的包，`hexo-cli@4.2`会安装`hexo@5`
