### ISSUE TITLE
How to use Hexo "concurrency"

### ISSUE THREAD

**Issue by HarrisonQi** [hexojs/hexo#4721]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

How should I use concurrency command?

I use this by this command but not work(always generate all posts now):
```shell
hexo g -c 30
```

Maybe I should use this by `hexo g -c30` or `hexo g -c=30`?

What's the right way to use? Thanks for your help

## Environment & Settings

**Node.js & npm version**

```
6.14.13
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by SukkaW** [comment]
`concurrency` means how many files should be generated *at the same time*, and all the files will still be generated.

**Comment by HarrisonQi** [comment]
> `concurrency` determines how many files should be generated _at the same time_, and all the files will still be generated.

I know this mean. How to use this command?
