### ISSUE TITLE
部署到GitHub，报错了，请问大神这是错在哪里？？？

### ISSUE THREAD

**Issue by Geda-999** [hexojs/hexo#4725]
## 部署到GitHub，报错了，请问大神这是错在哪里？？？

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (C:\Users\Administrator\Desktop\boke\bl\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (events.js:311:20)
      at ChildProcess.cp.emit (C:\Users\Administrator\Desktop\boke\bl\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
    code: 128
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/123895464-75d0c180-d992-11eb-8a3d-95e2e8eca46e.png)

**Comment by yinhanghang** [comment]
我也是这个情况，解决了吗？

**Comment by yinhanghang** [comment]
1. 删除`.deploy_git`文件夹;
2. 输入`git config --global core.autocrlf false`
3. 然后，依次执行：`hexo cleanhexo ghexo d`
这个我尝试了，还是没用

**Comment by yzqdev** [comment]
> 1. 删除`.deploy_git`文件夹;
> 2. 输入`git config --global core.autocrlf false`
> 3. 然后，依次执行：`hexo cleanhexo ghexo d`
>    这个我尝试了，还是没用

这个是无法访问远程git账户的错误
可能是你的github账户的密码改了,然而本地的git还存着原来的密码,在windows控制面板里面吧git账户删掉重新登录一下试试

**Comment by jiangtj** [comment]
错误信息很明确的
- 检查账户密钥是否正确
- 检查部署仓库设置是否正确，以及仓库是否存在

**Comment by stevenjoezhang** [comment]
也可能是这个问题 https://github.com/hexojs/hexo/issues/4757
另外可以试下挂个代理

**Comment by Wakeuppppp** [comment]
> ## 部署到GitHub，报错了，请问大神这是错在哪里？？？
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists. FATAL { err: Error: Spawn failed at ChildProcess. (C:\Users\Administrator\Desktop\boke\bl\node_modules\hexo-util\lib\spawn.js:51:21) at ChildProcess.emit (events.js:311:20) at ChildProcess.cp.emit (C:\Users\Administrator\Desktop\boke\bl\node_modules\cross-spawn\lib\enoent.js:34:29) at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) { code: 128 } } Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

看看这篇文章的解决方案三 https://wakeuppppp.github.io/2022/09/20/some-problems-with-hexo/
