### ISSUE TITLE
Plugin development: how to remove generated empty files

### ISSUE THREAD

**Issue by sshwy** [hexojs/hexo#4727]
## Check List

Please check followings before submitting a new issue.

- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

Recently I've worked on my hexo plugin and I had a demand of removing empty js files generated by an [aync renderer](https://hexo.io/api/renderer#Async-Mode) (a webpack renderer to be exact), which looks like

```js
function renderer ({ path }) {
  if(isEntry(path)) {
    const config = {
      entry: path,
      ...
    };
    return webpackInmemoryRenderAsync(config, this); // return a promise
  }
  return ''; // this generates empty files
}

hexo.extend.renderer.register('js', 'js', renderer);
```

What should I do?

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
Use `hexo.route.remove`, for example
https://github.com/next-theme/hexo-theme-next/blob/master/scripts/filters/minify.js#L24

**Comment by sshwy** [comment]
> Use `hexo.route.remove`, for example
> https://github.com/next-theme/hexo-theme-next/blob/master/scripts/filters/minify.js#L24

Thanks! This helps a lot.
