### ISSUE TITLE
这TypeError是个啥玩意？

### ISSUE THREAD

**Issue by yltx** [hexojs/hexo#4728]
## Check List

Please check followings before submitting a new issue.

- [-] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [-] I have already searched existing issues and they are not help  to me
- [-] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [-] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
将本地文件部署至github时出错。
## Actual behavior
![image.png](https://i.loli.net/2021/06/30/6YchJjyDoEG4nNx.png)
## How to reproduce?
本地尝试了hexo s，是可以正常使用的；但不知道为什么一旦尝试部署就出错，npm已经是最新版本了，不知道为什么，去查了docs也没看到这个error
* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
应该是node版本和hexo-fs版本不匹配的问题。删除`node_modules`再重新安装试试。

**Comment by yltx** [comment]
> 应该是node版本和hexo-fs版本不匹配的问题。删除`node_modules`再重新安装试试。

仍然报错。![image.png](https://i.loli.net/2021/06/30/PRuIHNdEkr1JeYS.png)![image.png](https://i.loli.net/2021/06/30/WhglSRVADQBMLiU.png)

**Comment by stevenjoezhang** [comment]
能提供一下`package.json`的内容吗？

**Comment by yltx** [comment]
> 能提供一下`package.json`的内容吗？
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "bootstrap": "^4.3.1",
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-symbols-count-time": "^0.6.1",
    "hexo-wordcount": "^6.0.1"
  }
}
```

**Comment by yltx** [comment]
> 升级一下依赖包。改成这样
> 
> ```json
> {
>   "name": "hexo-site",
>   "version": "0.0.0",
>   "private": true,
>   "hexo": {
>     "version": "3.8.0"
>   },
>   "dependencies": {
>     "bootstrap": "^5.0.2",
>     "hexo": "^5.4.0",
>     "hexo-deployer-git": "^3.0.0",
>     "hexo-generator-archive": "^1.0.0",
>     "hexo-generator-category": "^1.0.0",
>     "hexo-generator-index": "^2.0.0",
>     "hexo-generator-searchdb": "^1.3.4",
>     "hexo-generator-tag": "^1.0.0",
>     "hexo-renderer-ejs": "^1.0.0",
>     "hexo-renderer-marked": "^4.0.0",
>     "hexo-renderer-stylus": "^2.0.1",
>     "hexo-server": "^2.0.0",
>     "hexo-symbols-count-time": "^0.7.1",
>     "hexo-wordcount": "^6.0.1"
>   }
> }
> ```
> 
> 再执行`npm install`和`hexo clean`

好了，谢谢

**Comment by yltx** [comment]
> 升级一下依赖包。改成这样
> 
> ```json
> {
>   "name": "hexo-site",
>   "version": "0.0.0",
>   "private": true,
>   "hexo": {
>     "version": "3.8.0"
>   },
>   "dependencies": {
>     "bootstrap": "^5.0.2",
>     "hexo": "^5.4.0",
>     "hexo-deployer-git": "^3.0.0",
>     "hexo-generator-archive": "^1.0.0",
>     "hexo-generator-category": "^1.0.0",
>     "hexo-generator-index": "^2.0.0",
>     "hexo-generator-searchdb": "^1.3.4",
>     "hexo-generator-tag": "^1.0.0",
>     "hexo-renderer-ejs": "^1.0.0",
>     "hexo-renderer-marked": "^4.0.0",
>     "hexo-renderer-stylus": "^2.0.1",
>     "hexo-server": "^2.0.0",
>     "hexo-symbols-count-time": "^0.7.1",
>     "hexo-wordcount": "^6.0.1"
>   }
> }
> ```
> 
> 再执行`npm install`和`hexo clean`

出问题 他现在能正常编译了 但编译完了之后网站显示是有问题的

![image.png](https://i.loli.net/2021/07/02/GZDo8XuABr7Nafk.png)

我觉得既然之前一直是没有问题的，那我这个文件应该是没问题的吧，所以这又是啥？不会又是版本不匹配吧？

**Comment by stevenjoezhang** [comment]
你用的啥主题？

**Comment by yltx** [comment]
> 你用的啥主题？

next

**Comment by stevenjoezhang** [comment]
NexT  旧版不兼容了。把改过的文件备份一下，安装这个新版： https://github.com/next-theme/hexo-theme-next

**Comment by yltx** [comment]
> NexT 旧版不兼容了。把改过的文件备份一下，安装这个新版： https://github.com/next-theme/hexo-theme-next

草 还是得升级啊？我之前尝试升级的时候发现config有一堆形式改了 相当于重配一次 嫌麻烦就没搞了……没想到还是没逃过去

**Comment by stevenjoezhang** [comment]
这仨的版本会互相牵制： Node.js Hexo NexT
你遇到的第一个问题是 Node.js 版本比支持的 Hexo 版本高，第二个问题是 Hexo 版本比支持的 NexT 版本高
升级就只能一起升级了。新版 Hexo 的速度提升还是很大的。

**Comment by yltx** [comment]
> 这仨的版本会互相牵制： Node.js Hexo NexT
> 你遇到的第一个问题是 Node.js 版本比支持的 Hexo 版本高，第二个问题是 Hexo 版本比支持的 NexT 版本高
> 升级就只能一起升级了。新版 Hexo 的速度提升还是很大的。

但是config的写法大幅更改 似乎是整个架构改了 对我来说就相当于要重配一次整个blog了😢
