### ISSUE TITLE
Not compatible?

### ISSUE THREAD

**Issue by Zz-886** [hexojs/hexo#4731]
CentOS version: 8.3
Node version:  16.4.0
GIT version:  2.32.0
![image](https://user-images.githubusercontent.com/55978588/124202752-a9842680-db0d-11eb-83b0-8a3988d2fb15.png)

## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by jiangtj** [comment]
You may not install the node environment correctly.

**Comment by stevenjoezhang** [comment]
Please try to reinstall node.
