### ISSUE TITLE
Bringing issues back to issues themselves

### ISSUE THREAD

**Issue by kecrily** [hexojs/hexo#4738]
> **Bringing issues back to issues themselves**

Convert the issues under the `discussion` label to the discussion feature provided by GitHub.

Also maybe we can create an official communication platform on the IM platform for discussion? I think Discord is very suitable for doing this, there are already many open source communities that have chosen to set up channels there as well.

**Comment by yoshinorin** [comment]
@hexojs/core 
We are already discuss about this matter in #2999 
How do you think?

Basically I agree with use `GitHub discussion`.
