### ISSUE TITLE
Is it possible to generate a post to two urls?

### ISSUE THREAD

**Issue by jk195417** [hexojs/hexo#4740]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

Is it possible to generate a post to two urls?

something like

`_config.yml`

```yml
permalink: :title/
secondary_link: :year/:month/:day/:title/
```

and generated urls becomes

- my-site.dev/new-post/
- my-site.dev/2021/07/19/new-post/

**Comment by jiangtj** [comment]
https://github.com/hexojs/hexo-generator-alias
Is it help for you?

**Comment by jk195417** [comment]
I have seen this plugin, just want to check with you is there a Hexo native solution(config) I missed before I use it

Very appreciate😀
