### ISSUE TITLE
default_layout config variable not properly used by hexo

### ISSUE THREAD

**Issue by mahnunchik** [hexojs/hexo#4746]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

`default_layout` overrides default layout for all pages.

## Actual behavior

layout of pages still `post` from default config.

## How to reproduce?

* set `default_layout` to something different from `post`
* generate
* expect that `post` was used

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v14.17.3
6.14.13
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
`default_layout` does not take effect on the pages, it only changes the default layout of the posts. I think this is an intentional feature
