### ISSUE TITLE
url_for tag plugin

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo#4749]
## Check List

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Add a [tag plugin](https://hexo.io/docs/tag-plugins) for [url_for](https://hexo.io/docs/helpers.html#url-for) (and [full_url_for](https://hexo.io/docs/helpers.html#full-url-for)) [helper](https://hexo.io/docs/helpers.html).

## Existing tags plugins

Surprisingly there are [post_path and post_link](https://hexo.io/docs/tag-plugins#Include-Posts) that works only for posts in the `source/_posts/` folder and [asset_path and asset_link](https://hexo.io/docs/tag-plugins#Include-Assets) for assets in the `post_asset_folder` but there is nothing for pages or something more generic.

## Issue

So if you wan to refer to `source/docs/b.md` from `source/docs/a.md` you can use a classic abosulute link eg. `[b](/docs/b)` or `[b](/docs/b.html)` or a classic relative link `[b](docs/b)`.

Classic absolute links won't work when you have a `root: /root/` prefix in `_config.yml` because your link will be `/docs/b.html` instead of `/root/docs/b.html`, and relative links won't work if you are not at the root, eg. if you are at `/root/docs/` your link will be `/root/docs/docs/b.html`. That's why `url_for` and `full_url_for were created in the first place, but they are not available from content.

**Comment by noraj** [comment]
unstale

**Comment by stevenjoezhang** [comment]
Added in https://github.com/hexojs/hexo/pull/5198
