### ISSUE TITLE
fatal: 请求被中止: 未能创建 SSL/TLS 安全通道。怎么回事啊啊啊啊

### ISSUE THREAD

**Issue by yzmoci** [hexojs/hexo#4754]
Administrator@USER-20200607RT MINGW32 ~/Desktop/blog
$ hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
On branch master
nothing to commit, working tree clean
fatal: An error occurred while sending the request.
fatal: 请求被中止: 未能创建 SSL/TLS 安全通道。
error: unable to read askpass response from 'D:/Program Files/Git/mingw32/libexec/git-core/git-gui--askpass'
Username for 'https://github.com': yzmoci
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: unable to access 'https://github.com/yzmoci/yzmoci.github.io.git/': The requested URL returned error: 403
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (C:\Users\Administrator\Desktop\blog\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (events.js:314:20)
      at ChildProcess.cp.emit (C:\Users\Administrator\Desktop\blog\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
    code: 128
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by stevenjoezhang** [comment]
从8月13日起，GitHub不再支持通过邮箱和密码校验身份。你需要使用personal access token，或者用ssh密钥登陆GitHub，这样才能向仓库上传代码。
