### ISSUE TITLE
Can't deploy to github even though I have personal token in the _config.yml

### ISSUE THREAD

**Issue by masterrite** [hexojs/hexo#4757]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

I'm using the latest version of hexo-deployer-git but I can't access my repo. Here's the error:
```
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: unable to access 'https://github.com/*****.github.io/': The requested URL returned error: 403
FATAL { err:
   { Error: Spawn failed
       at ChildProcess.<anonymous> (F:\Hexo\node_modules\hexo-util\lib\spawn.js:52:19)
       at ChildProcess.emit (events.js:198:13)
       at ChildProcess.cp.emit (F:\Hexo\node_modules\cross-spawn\lib\enoent.js:40:29)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 128 } } 'Something\'s wrong. Maybe you can find the solution here: %s' 'https://hexo.io/docs/troubleshooting.html'
```

## Environment & Settings

**Node.js & npm version**

```
hexo: 5.4.0
hexo-cli: 4.3.0
os: win32 10.0.19043
http_parser: 2.9.3
node: 10.22.0
v8: 6.8.275.32-node.58
uv: 1.34.2
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.41.0
napi: 6
openssl: 1.1.1g
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019c
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/*****.github.io
  branch: master
  token: ghp_*****
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
$ npm ls --depth 0
hexo-site@0.0.0 F:\Hexo
+-- ajv@8.6.2
+-- ajv-keywords@5.0.0
+-- eslint@4.12.1
+-- hexo@5.4.0
+-- hexo-deployer-git@1.0.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index@0.2.1
+-- hexo-generator-json-content@3.0.1
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@0.2.0
+-- hexo-image-caption@0.1.1
+-- hexo-math@4.0.0
+-- hexo-pagination@1.0.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-pandoc@0.2.6
+-- hexo-renderer-pug@1.0.0
+-- hexo-renderer-sass@0.3.2
+-- hexo-renderer-scss@1.2.0
+-- hexo-renderer-stylus@0.3.3
+-- hexo-renderer-swig@1.1.0
+-- hexo-server@0.3.3
+-- hexo-tag-aplayer@3.0.4
+-- hexo-tag-bootstrap@0.1.2
+-- hexo-tag-cplayer@1.0.0
+-- hexo-tag-mplayer@1.0.1
`-- hexo-wordcount@6.0.1
```

**Your package.json `package.json`**

```
```

**Comment by zcsheng95** [comment]
I had the same issue and I solved it by change:
  repository: https://github.com/*****.github.io
to
   repository: https://oauth2:yourtoken@github.com/*****.github.io

**Comment by masterrite** [comment]
> I had the same issue and I solved it by change:
> repository: https://github.com/*****.github.io
> to
> repository: https://oauth2:yourtoken@github.com/*****.github.io

Thanks! This works. Do you know why, though?

**Comment by FreshManCode** [comment]
You can change your url https format to ssh format in _config.yml  file. Following is my example :
![image](https://user-images.githubusercontent.com/17489990/131785771-b691be62-146e-42a9-881e-4ccd04136dd0.png)

**Comment by wtffqbpl** [comment]
> You can change your url https format to ssh format in _config.yml file. Following is my example : ![image](https://user-images.githubusercontent.com/17489990/131785771-b691be62-146e-42a9-881e-4ccd04136dd0.png)

thx homie, i've solved my problem with your method.

**Comment by FreshManCode** [comment]
you're welcome!

**Comment by Firestar-Reimu** [comment]
请问如何获得`https://oauth2:yourtoken@`的部分？
