### ISSUE TITLE
Where is Localhost?

### ISSUE THREAD

**Issue by SingingFoot** [hexojs/hexo#4767]
I started the server with "hexo server", but there is nothing at localhost:4000. I got only:

PS C:\Users\user\Documents\Hexo> hexo server
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --debug   Display all verbose messages in the terminal    
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
PS C:\Users\user\Documents\Hexo> hexo new "My New Post"
Usage: hexo <command>

**Comment by stevenjoezhang** [comment]
Have you installed the `hexo-server` plugin in `C:\Users\user\Documents\Hexo\package.json`?

**Comment by SingingFoot** [comment]
@stevenjoezhang it is one level down here: C:\Users\user\Documents\Hexo\techwriter\package.json But I did not installed it specially, it was installed automatically. Also I have C:\Users\user\Documents\Hexo\package-lock.json

**Comment by stevenjoezhang** [comment]
Open the power shell at this directory: `C:\Users\user\Documents\Hexo\techwriter`
And run the following command
```
npm i
hexo server
```
to see if it works

**Comment by SingingFoot** [comment]
@stevenjoezhang Woooooooooow! It works! Immediately! Honestly, I even don't know what is Windows Power Shell. I suspect, it is a kind of FireWall in the form of command line. I need to read about it. Thanks a lot! You are great!

**Comment by stevenjoezhang** [comment]
Hexo will read dependency packages from `package.json`, so it's necessary to execute commands like `hexo s` in the same directory.

If you have any recommendations or find bugs, feel free to open a new issue. Good Issues are always welcomed 🎉
