### ISSUE TITLE
Hexo should NOT process JS files as Markdown #1696

### ISSUE THREAD

**Issue by lorezyra** [hexojs/hexo#4774]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
Hexo should ignore JS files and treat them similar to images by copying to the HTML folder

## Actual behavior
Hexo processes the JS (asset) files like a MD file. This breaks the Javascript file and makes it unusable for the given MD->HTML file.

## How to reproduce?

* add JS file to the same folder as an image file. Example: `page.js`
* run `hexo gen` and note the JS files have been modified with the addition of front-matter.

## Is the problem still there under "Safe mode"?
 Problem persist

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v15.14.0
7.21.1
```

**Your site `_config.yml`** (Optional)
https://github.com/lorezyra/blog.RichieBartlett.com/blob/eee7067a3e9c58f1b7db7cb8a88ef38d7ad5762b/_config.yml

**Your theme `_config.yml`** (Optional)
https://github.com/lorezyra/blog.RichieBartlett.com/blob/Production/themes/theme2.richiebartlett.com/_config.yml

**Hexo and Plugin version(`npm ls --depth 0`)**

```
├── expand-range@2.0.2
├── filename-regex@2.0.1
├── hexo-auto-category@0.2.1
├── hexo-breadcrumb@1.0.2
├── hexo-calendar@1.0.4
├── hexo-deployer-git@3.0.0
├── hexo-filter-github-emojis@3.0.4
├── hexo-filter-mathjax@0.7.0
├── hexo-footnotes@1.0.2
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-search@2.4.2
├── hexo-generator-seo-friendly-sitemap@0.2.1
├── hexo-generator-tag@1.0.0
├── hexo-pdf@1.1.1
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@4.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── hexo-tag-twitter@1.0.2
├── hexo-tag-wikipedia@1.0.1
├── hexo-tag-youtube-responsive@0.4.2
├── hexo-theme-bamboo@2.4.2
├── hexo-theme-landscape@0.0.3
├── hexo-util@2.5.0
├── hexo-wordcount@6.0.1
├── hexo@5.4.0
├── is-posix-bracket@0.1.1
├── object.omit@3.0.0
├── parse-glob@2.0.1
├── preserve@0.2.0
├── regex-cache@0.4.4
└── suncalc@1.8.0
```

**Your package.json `package.json`**
https://github.com/lorezyra/blog.RichieBartlett.com/blob/Production/package.json

## Others

Added images and JS files to a folder to reference in a markdown file. However, HEXO processed the files and created HTML for these files as though they were MD files.

Request: please have HEXO ignore *.js files and just add to the folder for the HTML to reference (treat JS like an image file).

**Comment by SukkaW** [comment]
Hexo shouldn't exclude js files by default. Some hexo plugins require this behavior to work (like `hexo-uglify` requires js files to be processed by hexo's filter API). Also, what happened if one day someone wants to write a blog post using javascript and create a hexo renderer plugin called `hexo-renderer-javascript`?

There is no other ways but:

- Use post assets folder feature
- Manually ignore those `js` files in your `_config.yml`

**Comment by lorezyra** [comment]
> what happened if one day someone wants to write a blog post using javascript and create a hexo renderer plugin called hexo-renderer-javascript?

This is irrelevant. The purpose of hexo is to convert markdown files to HTML. The EJS templating can add javascript if the theme designer incorporates it as such. For files that have code blocks embedded, this is not a problem as its inside the markdown file. But a file that is NOT a markdown file should NOT get the front-matter prepended to the file.

My use case is to reference the JS files for users to download. It's easier for me to manage those files if they are in the asset folder with the images for the post. 

> * Use post assets folder feature

```
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
```
I am using the asset folder feature. Hexo is processing the non-image files in the asset folder like markdown files. The JS files are in the asset folder and still getting treated like markdown files. Why is it prepending front-matter to a javascript file?

**Comment by lorezyra** [comment]
This may be related to https://github.com/hexojs/hexo/issues/4468

**Comment by SukkaW** [comment]
> Would this setting in my `_config.yml` files resolve my issue?
> 
> ```
> skip_render:
>   - _posts/**/*.js
>   - _posts/**/*.css
> ```

Yes, it should help.

**Comment by lorezyra** [comment]
Recommend adding this to the site documentation. I shouldn't have to scan through the github issues to find it.
