### ISSUE TITLE
配置文件没有启动

### ISSUE THREAD

**Issue by FTxxHalf** [hexojs/hexo#4785]
请问我是有文件没有放置对吗？第一个板块将配置文件信息给显示出来了。
![屏幕截图 2021-09-25 004607](https://user-images.githubusercontent.com/91110111/134711570-c1ab2c6f-12c6-47b4-b11f-298194ad44f9.png)

**Comment by stevenjoezhang** [comment]
你能提供一下博客的源码吗？
