### ISSUE TITLE
Misuse of hexo-log

### ISSUE THREAD

**Issue by mahnunchik** [hexojs/hexo#4787]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

Log level can be set in config or env var

## Actual behavior

Log level hardcoded to info.

## Others

https://github.com/hexojs/hexo/blob/master/lib/hexo/index.js#L135

It should be:

```js
this.log = logger({
  debug: ...,
});
```

https://github.com/hexojs/hexo-log/blob/master/lib/log.js#L38-L51

**Comment by SukkaW** [comment]
No. The code is working as intended.
