### ISSUE TITLE
请问如何实现多个主题共存？比如一个页面为主题1，然后通过点击页面内链接跳转到另一个主题2的页面

### ISSUE THREAD

**Issue by PretttyC** [hexojs/hexo#4795]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings
**Node.js & npm version**
**Your site `_config.yml`** (Optional)
**Your theme `_config.yml`** (Optional)
**Hexo and Plugin version(`npm ls --depth 0`)**
**Your package.json `package.json`**
## Others

如题，比如我想实现主页面用next主题，首页内有多个链接，每个链接点击可以跳转到其他主题的页面，如book主题

**Comment by fightinggg** [comment]
我也希望想这样，比如说我的blog是fightinggg.github.io ， 

我希望next主题在fightinggg.github.io/next路径下
landspace主题在fightinggg.github.io/landspace路径下
xxx主题在fightinggg.github.io/xxx路径下

当然也有一个最前面的页面fightinggg.github.io/index.html引导读者进入不同的主题

**Comment by stevenjoezhang** [comment]
目前只能通过写脚本进行多次 `hexo g` 操作才行。Hexo 和主题是强耦合的。
