### ISSUE TITLE
hexo不支持复选框

### ISSUE THREAD

**Issue by Firestar-Reimu** [hexojs/hexo#4807]
```
- [x] Alice
- [ ] Bob
```

在Hexo Markdown中渲染会变成这样

![Screenshot_20211103_112618](https://user-images.githubusercontent.com/65082432/140006188-f291541e-6abf-4c4d-84c8-3339dc50f003.png)

**Comment by stevenjoezhang** [comment]
取决于你用的markdown渲染插件。marked是支持的。

**Comment by Firestar-Reimu** [comment]
OK，这是因为我为了增强公式显示而采用了hexo-renderer-kramed，而那个因为不知名的原因没有跟上marked的进度，没有支持，只能通过自己加代码，已解决！
