### ISSUE TITLE
hexo 表格无法居中

### ISSUE THREAD

**Issue by Firestar-Reimu** [hexojs/hexo#4808]
在hexo中插入 HTML 表格

表格默认左对齐，加了`align="center"`后其余都居中了，只有表格没有居中

https://blog.firestar-reimu.top/tools/Time-Calculator/

**Comment by stevenjoezhang** [comment]
前端的 HTML 和 CSS 都是Hexo主题控制的，你需要询问你所使用的主题的开发者。

**Comment by stevenjoezhang** [comment]
一些 Markdown 插件也支持控制表格的对齐的语法，见 https://www.markdownguide.org/extended-syntax/#alignment
