### ISSUE TITLE
a themes in hexo site will redirect to a porn site

### ISSUE THREAD

**Issue by BboyNoah** [hexojs/hexo#4811]
## Others

![image](https://user-images.githubusercontent.com/13010589/140611246-c172f606-8df1-4ea2-9f16-a181e5955aff.png)
![image](https://user-images.githubusercontent.com/13010589/140611263-785c9be1-3ae9-4d44-a374-334f6b8fb414.png)

**Comment by stevenjoezhang** [comment]
Thanks for your feedback, the preview url of hexo-theme-believe has been updated
