### ISSUE TITLE
Hexo部署到云服务器，提交文件不完整，缺失index.html等

### ISSUE THREAD

**Issue by Tajang-ctf** [hexojs/hexo#4812]
步骤都是对的，过程也没有任何报错，访问服务器显示404，查看日志后，说是缺少index.html，但我本地public下生成的明明有，请问如何解决

**Comment by Fluuuegel** [comment]
Same as me. I deploy it with ftpsync but the index file cannot be updated.

**Comment by ShanZJ-gvs** [comment]
您好，请问解决了？我原来是用Nginx直接指向hexo/public/下的index，但是我关闭了服务器后，重新执行hexo clean 和hexo g后，index.html没有了，但是可以访问文章。如：这个是可以访问的==>http://gvssimux.com/2020/10/11/LeetCode/BigDataNote7/，但是http://gvssimux.com/以及http://gvssimux.com/archives/都是不可以.....

**Comment by ShanZJ-gvs** [comment]
> 



> 步骤都是对的，过程也没有任何报错，访问服务器显示404，查看日志后，说是缺少index.html，但我本地public下生成的明明有，请问如何解决

你可以试试把所有md文件换成英文的，我原本是中午的文件，是可以，但后来就生成不了index.html，全部改成了英文就可以了
