### ISSUE TITLE
多个 hexo 博客显示这种警报，什么情况？

### ISSUE THREAD

**Issue by note4** [hexojs/hexo#4813]
![image](https://user-images.githubusercontent.com/6513389/140961889-d30c4613-c28d-4db5-b422-9b5a242d4709.png)

https://jinxiaolong.com/2020/05/19/SwiftQuiz/

![image](https://user-images.githubusercontent.com/6513389/140961969-cdcc4a29-17ad-4778-9dda-4fe2ac587d36.png)

页面源代码里面是没有这些内容的，但是不同设备访问都会提示这个

## Check List

Please check followings before submitting a new issue.

- [ ] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
把 Valine 关了吧。Valine 的已知漏洞将允许攻击者通过发布评论劫持当前页面。

**Comment by note4** [comment]
> 把 Valine 关了吧。Valine 的已知漏洞将允许攻击者通过发布评论劫持当前页面。

有没有靠谱的插件推荐？
