### ISSUE TITLE
Fix author Object object on open_graph helper function

### ISSUE THREAD

**Issue by dimaslanjaka** [hexojs/hexo#4814]
## Check List

Please check followings before submitting a new feature request.

- [ x ] I have already read [Docs page](https://hexo.io/docs/)
- [ x ] I have already searched existing issues

## Feature Request

open_graph helper need improvement.

fix open_graph helper on og:meta (article:author) Object Object
Currently, many themes use front matter:
```yaml
author: # author object each pages or posts
  nick/nickname/name: "name author"
  url: "http://web.tld/page/profile.html"
```
The above configuration useful to create an author name with a hyperlink that will lead to the `about me` page or a page related to the article's author profile (seo internal/author link/schema jsonld).
**example**
```html
<a href="{{ page.author.url }}" alt="{{ page.author.name }}" rel="author">{{ page.author.name }}</a>
```
```ejs
<script type="application/ld+json">
{
  "@context": "https://schema.org/",
  "@type": "Person",
  "name": "{{ page.author.name }}"
... and so on
}
</script>
```

iam already test this codes but not working, i dont know how to contribute
```js
// switch `const` to `let`
// /lib/plugins/helper/open_graph.js line 72
let author = options.author || config.author
// /lib/plugins/helper/open_graph.js line 144
if (author) {
  /**
   * Fix author [object object]
   */
  console.log(typeof author); // not show anything
  // noinspection JSUnresolvedVariable
  if (typeof author.nick === "string") {
    // noinspection JSUnresolvedVariable
    author = author.nick;
  }
  // noinspection JSUnresolvedVariable
  if (typeof author.nickname === "string") {
    // noinspection JSUnresolvedVariable
    author = author.nickname;
  }
  // noinspection JSUnresolvedVariable
  if (typeof author.name === "string") {
    // noinspection JSUnresolvedVariable
    author = author.name;
  }
  result += og("article:author", author);
}
```
## Screenshots
Theme code:
![image](https://user-images.githubusercontent.com/12471057/140989151-6e481831-c800-4e4d-9e88-cfd884702eb5.png)
Result:
![image](https://user-images.githubusercontent.com/12471057/140987163-735af25d-5a0a-4329-bb68-43ee2edcc0c3.png)
Front matter:
```md
author:
  nick:
  link:
```

**Comment by SukkaW** [comment]
https://github.com/hexojs/hexo/pull/4815#pullrequestreview-803062690

> `author.nick`, `author.nickname` and `author.name` is not officially supported by the Hexo. We won't merge this just because your theme uses it.
> 
> Just imagine what happened if another theme uses `author.firstName` and `author.lastName`? What if a theme uses `author.firstNamePunctuation` and `author.lastNamePunctuation` for CJK users? What happened if one day you want `author.nick` and `author.name` both being shown?

**Comment by jiangtj** [comment]
https://github.com/hexojs/site/pull/1731

If the theme has a custom author config, you need to modify the Open Graph options as well

example:
```js
open_graph({author: config.author.nick})
```

**Comment by dimaslanjaka** [comment]
> [hexojs/site#1731](https://github.com/hexojs/site/pull/1731)
> 
> If the theme has a custom author config, you need to modify the Open Graph options as well
> 
> example:
> 
> ```js
> open_graph({author: config.author.nick})
> ```

thanks for tips. iam too confused because official hexo not complete usage documentation.
