### ISSUE TITLE
为什么 安装了 hexo 后在 themes 目录下看不到 landscape 主题目录了？The default theme path could not be found？

### ISSUE THREAD

**Issue by zhwangart** [hexojs/hexo#4818]
请问为什么 安装了 hexo 后，在 themes 目录下看不到 landscape 主题目录了？但是却能使用到这个主题？

After installing hexo, I can't see the landscape theme directory in the Themes directory. But you can use this theme?

## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by stevenjoezhang** [comment]
landscape 主题是通过 npm 安装的，在 package.json 中可以看到

**Comment by zhwangart** [comment]
> landscape 主题是通过 npm 安装的，在 package.json 中可以看到

噢，看到了，灰常感谢～

**Comment by LukeLiou** [comment]
> landscape 主题是通过 npm 安装的，在 package.json 中可以看到

@stevenjoezhang 如果主题是通过npm安装的，想借题问两个问题：
1. 想要自定义themes/next/layout/_partials/head.swig文件应该怎么操作呢？老版本的hexo是支持的
2. 赞赏开关设置为true，那些收款码图片应该存在哪个文件夹下，如你所见，通过npm安装的，theme文件夹是空的
期望你的回复，谢谢～
