### ISSUE TITLE
next主题中文二级目录无法展开，但是英文二级目录可以展开

### ISSUE THREAD

**Issue by MrChanGG** [hexojs/hexo#4832]
查看到控制台的信息
Uncaught TypeError: Cannot set property 'display' of undefined
    at miguanPlugin.run (adpingbi.js:10)
    at Object.success (adpingbi.js:84)
    at success (jquery.js:5267)
    at XMLHttpRequest.xhr.onreadystatechange (jquery.js:5207)

**Comment by MrChanGG** [comment]
详情点击https://mrchangg.github.io/2021/09/20/LeetCode-JAVA/       第三个一级目录有一个二级的英文目录

**Comment by stevenjoezhang** [comment]
你用的这个版本的 NexT 已经过时了，先升级一下主题： https://github.com/next-theme/hexo-theme-next

**Comment by MrChanGG** [comment]
> 你用的这个版本的 NexT 已经过时了，先升级一下主题： https://github.com/next-theme/hexo-theme-next

太太太太感谢了！！！！！！！可以了
