### ISSUE TITLE
potential security vulnerabilities in Hexo

### ISSUE THREAD

**Issue by pplmx** [hexojs/hexo#4835]
![image](https://user-images.githubusercontent.com/26994103/144950601-7ed5cc3e-04d0-4b4d-9aaf-7a8f19d61b42.png)

**Comment by FansChou** [comment]
When will this be handled? I also encountered the same prompt

**Comment by SukkaW** [comment]
@FansChou @pplmx 

We have released an announcement about the CVE: https://github.com/hexojs/hexo/issues/4838
