### ISSUE TITLE
so what's this ？ Render error?

### ISSUE THREAD

**Issue by wo02ie** [hexojs/hexo#4853]
### Discussed in https://github.com/hexojs/hexo/discussions/4852

<div type='discussions-op-text'>

<sup>Originally posted by **wo02ie** January  3, 2022</sup>
![微信截图_20220103212945](https://user-images.githubusercontent.com/74661756/147936142-551c1441-99f9-4846-8122-305545ccafa8.png)
![微信截图_20220103213033](https://user-images.githubusercontent.com/74661756/147936148-393c5fec-e2c3-49a1-a51b-0d5610d45d41.png)
</div>

**Comment by yoshinorin** [comment]
duplicate #4852
