### ISSUE TITLE
TOC: Support unnumbered titles

### ISSUE THREAD

**Issue by Cerallin** [hexojs/hexo#4860]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

I was using `hexo-generator-pandoc` to generate HTML files.
Markdown in the form of 
```markdown
### First Title

### Unnumbered title
```
will be rendered to
```HTML
<h3 id="first-title">First title</h3>

<h3 id="unnumbered-title" class="unnumbered">Unnumbered title</h3>
```

Is there any solution to unnumber titles in TOC? A common usage scenario is writing with the heading "Reference".

**Comment by Cerallin** [comment]
I've read the TOC part of the codes in `hexo` and `hexo-utils` and made sure that unnumbered titles were not supported. @SukkaW May I contribute to adding this feature?

P.S. I've also read the docs and was noticed that features about `min_depth` were not documented.

**Comment by yoshinorin** [comment]
@Cerallin 

I don't understand what is difference between [toc#list_number](https://hexo.io/docs/helpers#toc) and `unnumbered`.
Would you please explain more detail?

**Comment by Cerallin** [comment]
> I don't understand what is difference between [toc#list_number](https://hexo.io/docs/helpers#toc) and `unnumbered`. Would you please explain more detail?

Sorry for the ambiguous statements. What I am trying to express could be compared with LaTeX.

Something in tex like this

```tex
\section{Title}
\section*{Unnumbered Title}
```

will be rendered as

```
1. Title
Unnumbered Title
```

in which `Unnumbered title` is not numbered, does not have a `2.` before it.

The feature I want is to control the `list_number` of each heading by adding class `unnumbered`, which is automatically generated by pandoc.

**Comment by yoshinorin** [comment]
@Cerallin 

> The feature I want is to control the list_number of each heading by adding class unnumbered, which is automatically generated by pandoc.

OK, I understand.

> May I contribute to adding this feature?

Sure, you can contribute :)
We can't promise to merge it, but we will review it if you submit a PR.

**Comment by yoshinorin** [comment]
refs: https://github.com/hexojs/hexo-util/pull/269
