### ISSUE TITLE
npm package colors LIBERTY Issue (Running the "forever list" and would result in a Denial of Service (DoS) to any Node.js server )

### ISSUE THREAD

**Issue by npljy** [hexojs/hexo#4865]
2022-1-9开始github actions中执行hexo clean命令时报异常LIBERTY LIBERTY LIBERTY，如图
![github actions](https://s4.ax1x.com/2022/01/10/7E0SB9.png)

**Comment by spinF** [comment]
See https://github.com/Marak/colors.js/issues/285

This is caused by the NPM package `colors` in a version > `1.4.0`. The developer deliberately introduced an infinite loop that prints this stuff to the console. The dependency on `colors` should be pinned to version `1.4.0`.

**Comment by npljy** [comment]
> Marak/colors.js#285

thanks

**Comment by npljy** [comment]
> See [Marak/colors.js#285](https://github.com/Marak/colors.js/issues/285)
> 
> This is caused by the NPM package `colors` in a version > `1.4.0`. The developer deliberately introduced an infinite loop that prints this stuff to the console. The dependency on `colors` should be pinned to version `1.4.0`.




> See [Marak/colors.js#285](https://github.com/Marak/colors.js/issues/285)
> 
> This is caused by the NPM package `colors` in a version > `1.4.0`. The developer deliberately introduced an infinite loop that prints this stuff to the console. The dependency on `colors` should be pinned to version `1.4.0`.

---

thanks

**Comment by yoshinorin** [comment]
@spinF 
Thank you for your support :)

@hexojs/core 
I checked hexo official plugins & themes.
Any package does not depend on `colors`. So, we do not need to fix them.

> https://github.com/yoshinorin/hexo-colors-investigate

```json
//  package.json
// install all official plugins
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.0.0"
  },
  "dependencies": {
    "hexo": "^6.0.0",
    "hexo-asset-pipeline": "^1.8.0",
    "hexo-autoprefixer": "^2.0.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-clean-css": "^2.0.0",
    "hexo-deployer-ftpsync": "^0.1.1",
    "hexo-deployer-git": "^3.0.0",
    "hexo-deployer-heroku": "^0.1.2",
    "hexo-deployer-rsync": "^1.0.0",
    "hexo-filter-lqip": "^1.4.1",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-filter-responsive-images": "^1.7.0",
    "hexo-fontawesome": "^2.2.1",
    "hexo-front-matter": "^3.0.0",
    "hexo-fs": "^3.1.0",
    "hexo-generator-alias": "^1.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-html-minifier": "^1.0.0",
    "hexo-i18n": "^1.0.0",
    "hexo-log": "^3.0.0",
    "hexo-math": "^4.0.0",
    "hexo-migrator-rss": "^1.1.0",
    "hexo-migrator-wordpress": "^2.1.2",
    "hexo-pagination": "^2.0.0",
    "hexo-renderer-dot": "^0.2.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-haml": "^0.2.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-less": "^4.0.0",
    "hexo-renderer-markdown-it": "^6.0.0",
    "hexo-renderer-marked": "^4.1.0",
    "hexo-renderer-pug": "^2.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-renderer-swig": "^1.1.0",
    "hexo-server": "^3.0.0",
    "hexo-tag-imgurl": "^0.0.3",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-uglify": "^2.0.0",
    "hexo-util": "^2.5.0",
    "warehouse": "^4.0.0"
  },
  "devDependencies": {
    "eslint-config-hexo": "^5.0.0"
  }
}
```

```sh
$ npm ls colors
hexo-site@0.0.0 C:\Users\hexo\hexo-colors-investigate
└── (empty)
```

**Comment by yoshinorin** [comment]
P.S: addresses https://snyk.io/blog/open-source-npm-packages-colors-faker/

**Comment by SukkaW** [comment]
@yoshinorin Our logger is using nanocolors/picocolors, which is also used by Webpack / ESLint & Babel. If they don't have such problem, we don't have as well.

**Comment by yoshinorin** [comment]
@SukkaW 
Sorry, so lack of explanation.

The current colors latest version is `1.4.0`.  The `1.4.0` is a safe (not including vulnerability) version.

I assume the npm team revoked it and rollbacked the latest version to `1.4.0`.  I can't find the official announcement. But,  certainly, the version containing the vulnerability seems to have been revoked.

So, we no need to anymore :)

> https://www.npmjs.com/package/colors

![colors](https://user-images.githubusercontent.com/11273093/149616262-d3f4e359-2ed6-45ee-9082-d269ea988353.jpg)

**Comment by SukkaW** [comment]
> @SukkaW Sorry, so lack of explanation.
> 
> The current colors latest version is `1.4.0`. The `1.4.0` is a safe (not including vulnerability) version.
> 
> I assume the npm team revoked it and rollbacked the latest version to `1.4.0`. I can't find the official announcement. But, certainly, the version containing the vulnerability seems to have been revoked.
> 
> So, we no need to anymore :)

npm & GitHub do revert the changes. And what I am saying is that hexo isn't affected by it on the first day 😄, and probably will not in the future, too.
