### ISSUE TITLE
Support sortKeys with js-yaml

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4887]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
```
  menu: {
    '首頁': '/ || fas fa-home',
    '2021': '/archives/ || fas fa-archive',
    '標籤': '/tags/ || fas fa-tags',
    '分類': '/categories/ || fas fa-folder-open',
    '娛樂||fa fa-heartbeat||hide': {
      Music: '/music/ || fas fa-music',
      '圖庫': '/Gallery/ || fas fa-images',
      '電影': '/movies/ || fas fa-video'
    },
    '友鏈': '/link/ || fas fa-link',
    '留言板': '/messageboard/ || fas fa-comment-dots',
    '更多示例': 'https://github.com/jerryc127/hexo-theme-butterfly/issues/76 || fas fa-cat'
  }
```

## Actual behavior
```
  menu: {
    '2021': '/archives/ || fas fa-archive',
    '首頁': '/ || fas fa-home',
    '標籤': '/tags/ || fas fa-tags',
    '分類': '/categories/ || fas fa-folder-open',
    '娛樂||fa fa-heartbeat||hide': {
      Music: '/music/ || fas fa-music',
      '圖庫': '/Gallery/ || fas fa-images',
      '電影': '/movies/ || fas fa-video'
    },
    '友鏈': '/link/ || fas fa-link',
    '留言板': '/messageboard/ || fas fa-comment-dots',
    '更多示例': 'https://github.com/jerryc127/hexo-theme-butterfly/issues/76 || fas fa-cat'
  }
```
## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
menu:
  首頁: / || fas fa-home
  2021: /archives/ || fas fa-archive
  標籤: /tags/ || fas fa-tags
  分類: /categories/ || fas fa-folder-open
  娛樂||fa fa-heartbeat||hide:
    Music: /music/ || fas fa-music
    圖庫: /Gallery/ || fas fa-images
    電影: /movies/ || fas fa-video
  友鏈: /link/ || fas fa-link
  留言板: /messageboard/ || fas fa-comment-dots
  更多示例: https://github.com/jerryc127/hexo-theme-butterfly/issues/76 || fas fa-cat
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

能不能禁止 yaml 生成的 key 不进行排序？

生成的 json， 把 key 进行排序了，数字被提前。

我看 js-yaml 有个 sortKeys 配置，默认就是 false

**Comment by yoshinorin** [comment]
By default, the `js-yaml` does not sort by key.

> https://github.com/nodeca/js-yaml/tree/49baadd52af887d2991e2c39a6639baa56d6c71b#dump-object---options-

**Comment by jerryc127** [comment]
> By default, the `js-yaml` does not sort by key.
> 
> > https://github.com/nodeca/js-yaml/tree/49baadd52af887d2991e2c39a6639baa56d6c71b#dump-object---options-

why the number was put first in actual behavior ?

**Comment by stevenjoezhang** [comment]
According to https://github.com/nodeca/js-yaml/issues/622

> The ECMAScript 2015 specification (and later versions) requires that keys of an object are enumerated in a specific order:

> - non-negative integer keys [in ascending numeric order](https://262.ecma-international.org/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys), then
> - string keys in the order added, then
> - symbol typed keys in the order added.
