### ISSUE TITLE
How to select all posts in a certain tag or category and assign it to page.posts of the page I just created?

### ISSUE THREAD

**Issue by daisygao** [hexojs/hexo#493]
When I try to create a page "\Projects" to list all my posts with category "Projects" in an Archive-page style, I use the command `"hexo n category Projects"`. However, when rendering the page using `category.ejs`, `page.posts` can't be recognized. I wonder if there's a way to let this page object be filled with all posts with category "Projects"?

Thanks!

**Comment by connor11528** [comment]
Updated link for warehouse: https://github.com/hexojs/warehouse
