### ISSUE TITLE
hexo渲染的博客文章会将类似于&emsp；的符号，并不会处理显示为空格，而是以字符的形式显示出来/Blog posts rendered by hexo will display symbols similar to &emsp; instead of being displayed as spaces, but as characters

### ISSUE THREAD

**Issue by lym0518** [hexojs/hexo#4946]
## Check List

Please check followings before submitting a new issue.

- I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
-  I have already searched existing issues and they are not help  to me
- I examined error or warning messages and it's difficult to solve
- Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
markdown文章中输入类似&emsp；的符号在部署后会显示为空格。

Symbols like &emsp；entered in markdown articles will be displayed as spaces after deployment.
## Actual behavior
markdown文章中输入类似&emsp；的符号在部署后会显示为&emsp；

Symbols like &emsp；entered in markdown articles will be displayed as &emsp；after deployment
## How to reproduce?
* Step1：在markdown文章中输入&emsp；/ Type &emsp；in the markdown post
* Step2：运行 hexo server / Run Hexo server

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
node: v16.14.2 npm: 8.5.0
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- aplayer@1.10.1
+-- hexo-autonofollow@1.0.1
+-- hexo-deployer-git@3.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index-pin-top@0.2.2
+-- hexo-generator-index@2.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.3
+-- hexo-generator-seo-friendly-sitemap@0.2.1
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@5.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-tag-aplayer@2.0.7
+-- hexo-theme-landscape@0.0.3
+-- hexo-theme-volantis@5.0.0-rc.3
+-- hexo-wordcount@6.0.1
+-- hexo@5.4.1
`-- valine@1.4.16
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.1"
  },
  "dependencies": {
    "aplayer": "^1.10.1",
    "hexo": "^5.0.0",
    "hexo-autonofollow": "^1.0.1",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-seo-friendly-sitemap": "^0.2.1",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0",
    "hexo-tag-aplayer": "^2.0.2",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-theme-volantis": "^5.0.0-rc.3",
    "hexo-wordcount": "^6.0.1",
    "valine": "^1.4.14"
  }
}
```

**Comment by jiangtj** [comment]
The & replace with &amp; is in a common utility 🤔

https://github.com/hexojs/hexo-util/blob/master/lib/escape_html.js

**Comment by MHuiG** [comment]
```bash
git clone git@github.com:volantis-x/community.git && cd community

git reset --hard b96c4289a1833260acfe8252f5cd21bd4fa862d3

git submodule update --init

npm i && hexo s
```

see: http://localhost:4000/how-to-update/

![image](https://user-images.githubusercontent.com/38281581/168455091-44fb8dad-d2a1-430b-9475-96e82ea50c24.png)

**Comment by MHuiG** [comment]
```bash
git clone git@github.com:volantis-x/community.git && cd community

git reset --hard 54d3585f0fc4dbe44c7935f84429e5268612a8b6

git submodule update --init

npm i && hexo s
```

see: http://localhost:4000/how-to-update/


![image](https://user-images.githubusercontent.com/38281581/168455323-10640127-2571-4b3b-9d8d-2e1af4581fdb.png)

**Comment by MHuiG** [comment]
What is the difference between [b96c4289a1833260acfe8252f5cd21bd4fa862d3](https://github.com/volantis-x/community/tree/b96c4289a1833260acfe8252f5cd21bd4fa862d3) and [54d3585f0fc4dbe44c7935f84429e5268612a8b6](https://github.com/volantis-x/community/tree/54d3585f0fc4dbe44c7935f84429e5268612a8b6)

**Comment by MHuiG** [comment]
May be  hexo-renderer-ejs or hexo-renderer-marked

**Comment by MHuiG** [comment]
确认了 hexo-renderer-marked@4 是正常的 hexo-renderer-marked@5 渲染异常

**Comment by lym0518** [comment]
> 可能是 hexo-renderer-ejs 或 hexo-renderer-marked 或 hexo

It is indeed possible, thank you for your reply, I will think about it again
This problem appeared rather suddenly, only in the last few releases

**Comment by lym0518** [comment]
> 确认了 hexo-renderer-marked@4 是正常的 hexo-renderer-marked@5 渲染异常

原来如此，这是好早之前的问题了，那一天更新后开始出现。

**Comment by stevenjoezhang** [comment]
Caused by https://github.com/hexojs/hexo-renderer-marked/pull/214/commits/9e1c7ade8e62293ab7d8b60e5c9c2d11c8c55389
