### ISSUE TITLE
When there is one "-----------------------" in document, it will occur "YAMLException"

### ISSUE THREAD

**Issue by longdafeng** [hexojs/hexo#4961]
## Check List

Please check followings before submitting a new issue.

- [done ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [done ] I have already searched existing issues and they are not help  to me
- [done ] I examined error or warning messages and it's difficult to solve
- [done ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ done] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Promblem

I meet the problem "err: YAMLException: end of the stream or a document separator is expected"

I migration my markdown books from MkDocs to Hexo. 

There is no Front-matter in my documents. There are more than 1000 markdown documents, so I can't add front-matter to every document. 

If there is one ":" in my document, it will leading to this problem. 

I found there are several template in the directory of scaffolds, "draft.md/page.md/post.md"
```
---
title: {{ title }}
tags: {{tags}}
categories: {{categories}}
​---
```

I want to :
1. This error won't occur. 
2. I wish my markdown's file name will be the page's {{title}} and {{description}}

How to do?

```
^[[41mERROR^[[49m {
  err: YAMLException: end of the stream or a document separator is expected (4:77)

   1 |  ...
   2 |  ...
   3 |  ...
   4 |  ... r (ODC) consists of three parts:
  -----------------------------------------^
   5 |  ...
   6 |  ...
      at generateError (/Users/longda/work/longda/obcloud/obcloud/node_modules/js-yaml/lib/loader.js:183:10)
      at throwError (/Users/longda/work/longda/obcloud/obcloud/node_modules/js-yaml/lib/loader.js:187:9)
      at readDocument (/Users/longda/work/longda/obcloud/obcloud/node_modules/js-yaml/lib/loader.js:1645:5)
      at loadDocuments (/Users/longda/work/longda/obcloud/obcloud/node_modules/js-yaml/lib/loader.js:1688:5)
      at Object.load (/Users/longda/work/longda/obcloud/obcloud/node_modules/js-yaml/lib/loader.js:1714:19)
      at parseYAML (/Users/longda/work/longda/obcloud/obcloud/node_modules/hexo-front-matter/lib/front_matter.js:69:23)
      at parse (/Users/longda/work/longda/obcloud/obcloud/node_modules/hexo-front-matter/lib/front_matter.js:50:12)
      at /Users/longda/work/longda/obcloud/obcloud/node_modules/hexo/lib/plugins/processor/asset.js:55:18
      at tryCatcher (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:544:35)
      at Promise._settlePromise (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise_array.js:145:14)
      at PromiseArray._iterate (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise_array.js:115:31)
      at PromiseArray.init [as _init] (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise_array.js:79:10)
      at Promise._settlePromise (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:601:21)
      at Promise._settlePromise0 (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/Users/longda/work/longda/obcloud/obcloud/node_modules/bluebird/js/release/promise.js:673:18) {
    reason: 'end of the stream or a document separator is expected',
    mark: {
      name: null,
      buffer: 'Architecture \n' +
        '=================================\n' +
```

## Is the problem still there under "Safe mode"?

Safe mode works fine. 

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
node -v && npm -v
v14.15.5
8.1.4

hexo migrate --help
INFO  Validating config
INFO  ==================================
  ███╗   ██╗███████╗██╗  ██╗████████╗
  ████╗  ██║██╔════╝╚██╗██╔╝╚══██╔══╝
  ██╔██╗ ██║█████╗   ╚███╔╝    ██║
  ██║╚██╗██║██╔══╝   ██╔██╗    ██║
  ██║ ╚████║███████╗██╔╝ ██╗   ██║
  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝   ╚═╝
========================================
NexT version 8.11.0
Documentation: https://theme-next.js.org
========================================

package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.1.0"
  },
  "dependencies": {
    "hexo": "^6.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-searchdb": "^1.4.0",
    "hexo-generator-sitemap": "^3.0.1",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-markdown-it": "^6.0.1",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-theme-next": "^8.11.0",
    "markdown-it-checkbox": "^1.1.0",
    "markdown-it-expandable": "^1.0.2",
    "markdown-it-imsize": "^2.0.1"
  }
}
```

**Comment by yoshinorin** [comment]
@longdafeng 

I assume your yaml file has extra space or tag. Please check them.

> https://github.com/hexojs/hexo/issues/832#issuecomment-54764743

**Comment by longdafeng** [comment]
I don't think the problem is #832. 


There is no Front-matter in my documents. 

there are no section like this:
```
---
title: test
---
```

Some markdown documents are fine, but some occur probjem, which there are ":" in these document with problem. 


> @longdafeng
> 
> I assume your yaml file has extra space or tag. Please check them.
> 
> > [#832 (comment)](https://github.com/hexojs/hexo/issues/832#issuecomment-54764743)

**Comment by longdafeng** [comment]
any help will be appreciated. 
@stevenjoezhang , do you have any idea to resolve it? Thanks in advance.

**Comment by stevenjoezhang** [comment]
You need to add a Front-matter section in the posts:

```
---
title: test
---
```

Otherwise ":" in the post content will be parsed as YAML Front-matter, causing syntax error

**Comment by longdafeng** [comment]
I want to migrate my markdown books from MkDocs to Hexo. There are more than 1000 markdown documents, this is an huge task for me (I can write a script do this task). what's more there are 2 document systems to display these documents, so I can't add "front-matter" to these documents. 

In my oponion, there should be a method to skip render front-matter. 

@stevenjoezhang, thanks in advance

**Comment by longdafeng** [comment]
Sorry for disturbing, @curbengh , @tommy351 , @SukkaW , @segayuu , @NoahDragon , may I ask how to resolve this problem? Any help are appreciated, thanks in advance.

**Comment by longdafeng** [comment]
@yoshinorin  Do you have any ideas to resolve this problem, any help are appreciated.

**Comment by yoshinorin** [comment]
I don't know why your environment has a problem (`YAMLException`).
Anyway, hexo `6.x.x` can process a post without front-matter. I just tried it locally.

```sh
// create new hexo pj
$ hexo init issue4961
INFO  Validating config
INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
INFO  Install dependencies

...

INFO  Start blogging with Hexo!
```

After creating a new project, I wrote a post without frontmatter.

```md
// _posts\test-no-front-matter.md

$ hexo new test-no-front-matter
INFO  Validating config
INFO  Created: ~\sandbox\issue4961\source\_posts\test-no-front-matter.md
```

And run `hexo server`  I can see the content without Errors.

![1](https://user-images.githubusercontent.com/11273093/168027785-195adb28-a965-434a-a3e5-ae9944cb290a.jpg)

Also, hexo can generate HTML from it.

```
$ hexo g
INFO  Validating config
INFO  Start processing

....

INFO  Generated: 2022/05/12/test-no-front-matter/index.html
INFO  18 files generated in 357 ms
```

---

I assume you can use hexo API, if you want to add a `title` (or other metadata) to your posts without front-matter.
I have been never tried to use them for update metadata, but may be effective.

> https://hexo.io/api/generator#Generate-All-Posts
> https://hexo.io/api/#Execute-Commands

**Comment by longdafeng** [comment]
@yoshinorin  Thanks 

There is no : in your markdown, so it won't occur problem. 

There is one or more colon in the document, at the same time, there is no front-matter, it will occur "YAMLException"

**Comment by yoshinorin** [comment]
This error does not happen only `:`. 
But, when I use `---` with `:` the ` YAMLException` sometimes happens.

I wrote some patterns below.

```md
// OK (without ---)

This is a test for issue:4916
```

```md
// Sometimes happens (not every time)

This is a test for issue:4916
---
```

```md
// Sometimes happens (not every time)

This is a test for issue : 4916
---
```

```md
// every time happen

---
This is a test for issue:4916
This is a test for issue : 4916
---
```

```md
// OK

---
This is a test for issue:4916
---
```

```md
// No-errors but nothing is rendered

---
This is a test for issue : 4916
---
```

---

Not sure but as far as I know, can not ignore parsing yaml.

IMHO, we will not implement it, because this case assumes a very rare case. But, we may implement it if receive many requests from users.

Also, we may accept if someone submits PR about this.

**Comment by longdafeng** [comment]
@yoshinorin  Today I debug my document,  I found the root cause,  what I found is the same as what you found. 

The document doesn't allow '---'

I have two document occur this problem. 

Document 1:


```
Architecture 
=================================

The architecture of  Developer Center (ODC) consists of three parts:

* **[Basic features](#basic-features)**

  

* **[Core features](#core-features)**

  

* **[Advanced features](#advanced-features)**

  


Basic features 
-----------------------

* User Management: This feature provides services such as account creation, system logon, and password modification.

  

* Connection Management: This feature allows you to manage connections to  Database in MySQL and Oracle modes. You can create, save, copy, and delete database connections.

  

```


Event if there is one "-----------------------" between \``` and \``` , it will also exist problem

**Comment by longdafeng** [comment]
Due to "-----------------------" can be regcognize one format of title in markdown,  

For example;
Title
-----------------------


so  could we ignore "-----------------------",  don't parse it as YAML.

**Comment by longdafeng** [comment]
@yoshinorin @stevenjoezhang @bkeepers @jjgod  @NoahDragon @SukkaW 

Do you have any idea about this issue, any help are appreciated.

**Comment by longdafeng** [comment]
I am disappointed at Hexo, one month past, no one give me an answer how to resolve it. 

In my oponion, the label of this issue is wrong, it should be [feature-request](https://github.com/hexojs/hexo/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request)

**Comment by longdafeng** [comment]
close this issue, due to no one answer

**Comment by stevenjoezhang** [comment]
I have answered your question 2 months ago. I have no idea why you think no one give you an answer how to resolve it.
