### ISSUE TITLE
hexo标签外挂失败

### ISSUE THREAD

**Issue by kebuAAA** [hexojs/hexo#5004]
因为是刚刚使用hexo，在公式显示异常和图片显示的问题的时候来来回回安装了几次插件，不知道为什么现在我的tag plugins外挂都会失败，不知道哪位大佬可以教教我应该怎么排查问题出在哪里呢

**Comment by stevenjoezhang** [comment]
有报错信息吗？截个图，或者把出问题的文章代码发上来。

**Comment by kebuAAA** [comment]
问题我解决了，应该是不小心卸载某些重要的包导致的，谢谢您
&nbsp;


可不
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月24日(星期五) 中午1:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hexojs/hexo] hexo标签外挂失败 (Issue #5004)





 
有报错信息吗？截个图，或者把出问题的文章代码发上来。
