### ISSUE TITLE
Custom tag plugin - render hexo tags using hexo.render

### ISSUE THREAD

**Issue by Ilya122** [hexojs/hexo#5049]
Hello all, 

## Check List

Please check followings before submitting a new issue.

- [x] I have already confirmed other issue template and they are not different my want
- [x] Not a question, feature-request, bug
    - Please submit to [discussion](https://github.com/hexojs/hexo/discussions) if your issue is a question.

## Information

I'm trying to use ``hexo.render.renderSync(..)`` to render the tag ``{% post_link my_post %}`` like so:

```js
hexo.extend.tag.register('cardlink', (args) => {
    let header = args[0];
    return `<div class="content-card">
                <h4>${header}</h4>
                    <div class="content-card-content">
                    ${
                         hexo.render.renderSync({
                                 text: '{% post_link ' + args[1] + ' %}',
                                 render: 'markdown'
                            }) 
                    }
                </div>
            </div>`;
});
```

However It renders like a regular text:
``<p>{% post_link my_link ‘link’ %}</p>``

## Environment & Settings

**Node.js & npm version**

Node JS: 12.12.0
NpmVer: 6.11.3

Part of my package.json:
```
{
....
,
    "hexo": {
        "version": "6.2.0"
    },
    "dependencies": {
        "hexo": "^6.2.0",
        "hexo-deployer-heroku": "^0.1.2",
        "hexo-generator-archive": "^1.0.0",
        "hexo-generator-category": "^1.0.0",
        "hexo-generator-index": "^1.0.0",
        "hexo-generator-search": "^2.4.3",
        "hexo-generator-tag": "^1.0.0",
        "hexo-reading-time": "^1.0.3",
        "hexo-renderer-ejs": "^1.0.0",
        "hexo-renderer-marked": "^3.3.0",
        "hexo-renderer-scss": "^1.2.0",
        "hexo-renderer-stylus": "^1.1.0",
        "hexo-server": "^1.0.0",
        "hexo-sliding-spoiler": "^1.2.1",
        "hexo-card-links": "file:hexo-card-links-0.0.1.tgz"
    },
    "engines": {
        "node": "12.12.0",
        "npm": "6.14.6"
    },
    "devDependencies": {
        "hexo-feed": "^1.1.0"
    }
```

Either I'm doing something silly or It's not possible to render hexo tags (Like post_link) like that? 
Also it lacks documentation - where do I find all the options?  Beside reading the source code. 

Thanks!

**Comment by renbaoshuo** [comment]
You can try to use `hexo.tag.render`.

https://github.com/hexojs/hexo/blob/104b72139078b2682ede67f5b4c2148625cd7ebe/test/scripts/extend/tag.js#L12-L15

**Comment by Ilya122** [comment]
> You can try to use `hexo.tag.render`.
> 
> https://github.com/hexojs/hexo/blob/104b72139078b2682ede67f5b4c2148625cd7ebe/test/scripts/extend/tag.js#L12-L15

Thanks it looks promising but how do I need to obtain a tag instance to render the extension ``post_link``?
I see they use `` const tag = new Tag();``

**Comment by Ilya122** [comment]
Ok I solved it by using directly the post_link with the ``context`` from ``hexo``
```js
const PostLink = require('hexo/lib/plugins/tag/post_link');

hexo.extend.tag.register('cardlink', (args) => {
    let header = args[0];
    let postLinkPath = PostLink(hexo.render.context)([args[1], 'true']);

    return `<div class="content-card">
                <h4>${header}</h4>
                    <div class="content-card-content">
                    ${
                         hexo.render.renderSync({
                                 text: postLinkPath,
                                 render:'markdown'
                            }) 
                    }
                </div>
            </div>`;
});
```

``args[1]`` is the direct markdown page name. 

Thanks for the idea :)
