### ISSUE TITLE
重启机器后hexo和npm都不见了

### ISSUE THREAD

**Issue by jenenliu** [hexojs/hexo#505]
按照http://zespia.tw/hexo/docs/index.html
步骤安装都成功了，然后自己也成功搭建了博客。第二天重启机器后，想发个新的post，发现hexo没了，hexo：command not found.
npm也没了，npm: command not found
运行nodejs -v，显示v0.10.15
.nvm和.npm文件夹都存在，想重新用nvm安装nodejs，显示已为最新版本
想用ubuntu的apt安装npm包，重新安装hexo的时候出现错误
求大神解答
Many thanks ;)

**Comment by oknixus** [comment]
@jenenliu 是不是说，安装的时候，不是全局安装的！然后就导致只能在某个目录中使用？

**Comment by Xuanwo** [comment]
@oknixus Yes.

**Comment by oknixus** [comment]
@Xuanwo 查了一下，没找到局部改全局的方法，难道只能用软链？

**Comment by Xuanwo** [comment]
@oknixus 卸载了重新用`-g`命令安装
