### ISSUE TITLE
Resource file like css and json should skip rendering by default

### ISSUE THREAD

**Issue by D-Sketon** [hexojs/hexo#5056]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Resource file like css and json should skip rendering by default. In this case, users don't need to add file path to `skip_render` in `_config.yml`

## Others

if this feature can be realized, the issue #4976 may be solved

**Comment by renbaoshuo** [comment]
I don't think it should be set as the default option, some existing plugins (like https://github.com/hexojs/hexo-clean-css) depend on this behavior.

**Comment by renbaoshuo** [comment]
Maybe we can consider setting `disableNunjucks` to `true` for css files.

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/4468
