### ISSUE TITLE
Transliteration URLs into English by default

### ISSUE THREAD

**Issue by itfarrier** [hexojs/hexo#506]
Will it be?

**Comment by Chiliec** [comment]
I'm also interesting. Anyone implemented it?

**Comment by Xuanwo** [comment]
Only URLs ?

I'm confused by this feature.
What will happen if I own files like 你好，世界.md and Hello, world.md (after tansliterating, they are the same) ?

**Comment by dailyrandomphoto** [comment]
Here is a plugin to transliterate post filename and URL to English.

https://github.com/dailyrandomphoto/hexo-unique-post-path/issues/14
