### ISSUE TITLE
Folders with name that begins with a dot are ignored when generating

### ISSUE THREAD

**Issue by AnotiaWang** [hexojs/hexo#5074]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

I want to keep my GitHub Workflow files in the `public` folder since I have workflows related to the `main` branch. I moved the `.github` folder to `source`, and added `.github` to `skip_render` list.

## Expected behavior

After running `hexo g` the `.github` folder should appear in `/public`.

## Actual behavior

The folder is ignored when generating.

## How to reproduce?

* Add a `.github` folder in `/source`, and put some files in it
* Add `.github` folder to `skip_render` in  `_config.yml`
* Run `hexo cl` and `hexo g`

## Is the problem still there under "Safe mode"?

Yes

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v16.17.0
8.5.4
```

**Your site `_config.yml`** (Optional)

```yaml
skip_render: 
  - '.github/workflows/*'
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 F:\Git\animenz
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.3.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── hexo-theme-inside@2.7.0-beta.20
├── hexo-theme-keep@3.4.3
├── hexo-theme-landscape@0.0.3
└── hexo@6.3.0
```

**Your package.json `package.json`**

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-inside": "^2.7.0-beta.20",
    "hexo-theme-keep": "^3.4.0",
    "hexo-theme-landscape": "^0.0.3"
  }
}
```

**Comment by lorezyra** [comment]
Config error. Don’t define a folder in `skip _render` if you actually want it copied to the public folder.

**Comment by D-Sketon** [comment]
Folders with name that begins with a dot or a underscode are considered hidden files and will be excluded when being read in Hexo.

**Comment by stevenjoezhang** [comment]
You can add it to `include`:
```
skip_render: 
  - '.github/workflows/*'
include:
  - '.github/workflows/*'
```
