### ISSUE TITLE
Google+ shouldn't be there

### ISSUE THREAD

**Issue by Plasabl** [hexojs/hexo#5084]
## Expected behavior
There wouldn't be icon for Google+
## Actual behavior
There is icon for Google+ and it doesn't work
## How to reproduce?

1 Choose to post for sharing
2. Click post's Google+-icon

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**
Node.js v16.17.1.

**Hexo and Plugin version(`npm ls --depth 0`)**
4.3.0

## Others

Shut down Google+ for consumer (personal) accounts on April 2, 2019.

**Comment by stevenjoezhang** [comment]
There is no Google+ related component in Hexo. You may report the issue to the developers of the Hexo theme you're using
