### ISSUE TITLE
Capability for a Multi part blog series

### ISSUE THREAD

**Issue by o7-machinehum** [hexojs/hexo#5089]
## Check List

Please check followings before submitting a new feature request.

- [ x] I have already read [Docs page](https://hexo.io/docs/)
- [ x] I have already searched existing issues

## Feature Request

This is more of a question than a feature request. I'll probably make something manually if the feature doesn't exist. I wonder if there is the capability to make a multi-part blog through tags or something? Somewhere you could define the name of the first part, and then it will make a link back to part 1 (and a link to part 2 from part 1)

**Comment by lorezyra** [comment]
I employ the TOC and custom `{% link %}` tag that points the visitor to my other pages/posts. Essentially, you could label your posts as you see fit and link them manually together.

**Comment by stevenjoezhang** [comment]
If you have only a few blog articles, you can manually use the `post_link` tag to link to different articles. If you want to automate this process, you may need to develop a plugin yourself, as Hexo does not provide such functionality.
