### ISSUE TITLE
relative link is incorrent after executing `hexo s`

### ISSUE THREAD

**Issue by D-Sketon** [hexojs/hexo#5110]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

After executing `hexo s`, the relative link of css url in the server should be the same as the one in the public folder.

For example: 
The file in the public folder has the following line: 
`<link rel="stylesheet" href="../../../../css/style.css">`

Then the view page source code in the browser should also have the following line:
`<link rel="stylesheet" href="../../../../css/style.css">`

## Actual behavior
Actually the view page source code in the browser has:
`<link rel="stylesheet" href="css/style.css">`
This causes the css of all pages except the home page to fail to load.

![image](https://user-images.githubusercontent.com/49871906/202886589-000e1093-9cde-4968-99e5-fc6e503d1505.png)

## How to reproduce?

* Step1
`hexo init blog` to use the lastest hexo and default theme.
* Step2
change _config.yml
```yaml _config.yml
relative_link: true
```
* Step3
`hexo g && hexo s` and see `localhost:4000/archives` in the browser

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v16.18.0
8.19.2
```

**Your site `_config.yml`** (Optional)

just change relative_link
```yaml
relative_link: true
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /home/jack/桌面/blog/blog
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@6.0.0
├── hexo-renderer-stylus@2.1.0
├── hexo-server@3.0.0
├── hexo-theme-landscape@0.0.3
└── hexo@6.3.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3"
  }
}
```

## Others

I also tried the old version `5.4.2` of hexo and it doesn't seem to have this problem.

**Comment by stevenjoezhang** [comment]
Relevant PR: https://github.com/hexojs/hexo/pull/4789
The cache should be disabled when `relative_link` is `true`. @SukkaW

**Comment by D-Sketon** [comment]
> Relevant PR: #4789 The cache should be disabled when `relative_link` is `true`. @SukkaW

issues #4895 is also related to this PR
