### ISSUE TITLE
Add "draft" variable to front-matter to control if article is a draft like hugo

### ISSUE THREAD

**Issue by suncle1993** [hexojs/hexo#5122]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

an example front-matter:

```
---
date: '2022-12-04T18:31:37'
abbrlink: 1358609975
draft: true
---
```

if draft is true, this article will not be rendered, just like article file in _draft directory

**Comment by WangNianyi2001** [comment]
If you really need this feature ASAP, you can customize the `.ejs` files in your theme to get a workaround. Just look for where the posts are iterated (usually with `site.posts`), add a filter after that and it's done.

**Comment by SukkaW** [comment]
Just curious. Is there any reason that you don't want to use the draft folders?

**Comment by WangNianyi2001** [comment]
@SukkaW My guess is that sometimes people (like me) organize published posts in separated folders under `_posts`. Using `_drafts` folder then publishing them via CLI will not do the classification job automatically.

**Comment by suncle1993** [comment]
> @SukkaW My guess is that sometimes people (like me) organize published posts in separated folders under `_posts`. Using `_drafts` folder then publishing them via CLI will not do the classification job automatically.

Yes, you are right.  This is indeed my scene. I need to write and organize a series of articles in seperated folders under `_posts`.

**Comment by stevenjoezhang** [comment]
@suncle1993 @WangNianyi2001 You can set `published: false` in Front-matter. It's an undocumented feature.

**Comment by suncle1993** [comment]
> @suncle1993 @WangNianyi2001 You can set `published: false` in Front-matter. It's an undocumented feature.

I will try this magic feature. Thank you.

**Comment by stevenjoezhang** [comment]
If you confirm that this feature meets your expectations, I will update the documentation.

**Comment by suncle1993** [comment]
> If you confirm that this feature meets your expectations, I will update the documentation.

after add `published: false` to Front-matter, it take effect. Thank you.
