### ISSUE TITLE
Hexo failed to highlight codefence inside a blockquote.

### ISSUE THREAD

**Issue by SakuraWald** [hexojs/hexo#5147]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

The codes inside a blockquote should be rendered the same as MarkedDemo.
But hexo didn't. I am not sure whether this is is the problem of hexo or marked.js

![image](https://user-images.githubusercontent.com/10484271/212831336-33977e14-3751-438c-bec0-f746c69f7216.png)

![image](https://user-images.githubusercontent.com/10484271/212831393-bcfafbb0-9c86-4b8e-be28-6696869a1572.png)

## Actual behavior

The codes insides a blockquote are actually rendered in-correctly. (The ">" should not be a part of the codes.)

![image](https://user-images.githubusercontent.com/10484271/212836640-acc469dc-7aa6-4409-8673-e8bee1e0d031.png)

![image](https://user-images.githubusercontent.com/10484271/212833428-27c59d6a-397d-4d64-9565-afb7dedf7d1c.png)

## How to reproduce?

Try to write down this.
```
>```java
>This is the first line.
>This is the second line.
>This is the thrid line.
>```
```

## Is the problem still there under "Safe mode"?
YES !

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
 ~/Workspace/Github/sakurawald.github.io   main ±  node -v
v16.19.0
 ~/Workspace/Github/sakurawald.github.io   main ±  npm -v
9.2.0
```

**Your site `_config.yml`** (Optional)

```yaml
I have tested the "default highlight", "highlightjs" and "prismjs".
All of them behave the same.
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
 ✘  ~/Workspace/Github/sakurawald.github.io   main ±  npm ls --depth 0
hexo-site@0.0.0 /home/sakurawald/Workspace/Github/sakurawald.github.io
├── hexo-deployer-git@3.0.0
├── hexo-filter-mermaid-diagrams@1.0.5
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-migrator-wordpress@2.1.2
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-kramed@0.1.4
├── hexo-renderer-pug@3.0.0
├── hexo-renderer-stylus@2.1.0
├── hexo-server@3.0.0
├── hexo@6.3.0
├── pjax@0.2.8
└── remove@0.1.5

```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-migrator-wordpress": "^2.1.2",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "pjax": "^0.2.8",
    "remove": "^0.1.5"
  }
}

```

## Others

Though I use "kramed", but I test on "marked" too, both of them have the same bug.
Maybe this is not a bug of the markdown render, but a bug of hexo.

**Comment by SakuraWald** [comment]
This bug happens even when you disable highlight plugins.
![image](https://user-images.githubusercontent.com/10484271/212834900-2baee352-573b-4f30-94a4-10fb5ae48050.png)
![image](https://user-images.githubusercontent.com/10484271/212834878-ea733fe7-bc0c-4543-9e16-518587f32576.png)

**Comment by stevenjoezhang** [comment]
Try adding some spaces between '>' and '```'

    > ```java
    > This is the first line.
    > This is the second line.
    > This is the thrid line.
    > ```

**Comment by SakuraWald** [comment]
> 

The reason for the error is that the highlight function is called at the wrong time.
If you call the highlight function manually, then everything goes well.
Anyway, there are still some rendering problems on hexo.
