### ISSUE TITLE
希望配置文件可以支持环境变量

### ISSUE THREAD

**Issue by pengwon** [hexojs/hexo#5154]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

虽然hexo主要面向个人博客，但有些博客希望可以开源形式发布，但有些插件的配置信息又是私密的，所以希望配置文件可以支持环境变量。这样通过类似GitHub Actions这样的自动部署工具依然可以完成而无需担心信息泄露。

**Comment by stevenjoezhang** [comment]
如果是在自动化流程中，可以使用以下命令
```
export THEME=next
hexo config theme $THEME
```

**Comment by pengwon** [comment]
感谢回答 @stevenjoezhang

如果需要配置某个参数下的选项该怎么做，比如

``` yml
index_generator:
  path: ''
  per_page: 10
  order_by: -date
```

想配置`per_page`的值，万分感谢。
 
现在执行`git config`

``` powershell
❯ hexo config index_generator
INFO  Validating config
{ per_page: 10, order_by: '-date', path: '' }
```

**Comment by pengwon** [comment]
刚才又试了下，可以用`.`访问

``` powershell
❯ hexo config index_generator.per_page
INFO  Validating config
10
```

开始也试这个方法了，可能正巧参数为空，以为这样不行。
