### ISSUE TITLE
在 GitHub Pages 上部署 Hexo 

### ISSUE THREAD

**Issue by cnsino** [hexojs/hexo#5164]
通过该方式
https://hexo.io/zh-cn/docs/github-pages.html
部署的页面404，发现以下问题

1. 部署后发现gh-pages 的文件大写全为“0 lines (0 sloc)  0 Bytes”，文件目录正常；
详见：https://github.com/Arukara/Taissan/tree/gh-pages

2. 发现其在构建时输出的文件内容为空，如下Test1中无输出内容
![image](https://user-images.githubusercontent.com/121778348/221410703-e04ed827-300b-4df4-9d4e-ce03f15fa2c7.png)

**Comment by stevenjoezhang** [comment]
你的仓库里面没有 Hexo 主题，你需要修改 package.json 把主题加进去，或者把主题的源码上传到 themes 目录下
