### ISSUE TITLE
怎么关闭4格空格变成代码块

### ISSUE THREAD

**Issue by 1976083684** [hexojs/hexo#5165]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by 1976083684** [comment]
TAB缩进(4)，还是会变成代码块，好烦恼，我的文章是从typora移植过来的，基本文章开头都是4个空格缩进，结果文章都变成代码块了，欸

**Comment by 1976083684** [comment]
怎么解决呢，好烦，感觉又不方便了

**Comment by stevenjoezhang** [comment]
这个语法叫做 `Indented code block`，Hexo 用的 marked 默认是启用的，改起来有点麻烦

**Comment by WangNianyi2001** [comment]
你可以写个 batch 或者 shell 脚本把你的博客源码批量处理一下。另外，请遵守 issue 格式。

**Comment by leesei** [comment]
For your reference, you can use this regex to replace leading space to empty string.
`^[ ]{4}` match only 4 spaces at the start of line
`^[ ]{4,}` match only 4 or more spaces at the start of line

https://regex101.com/r/DIR3UC/1
