### ISSUE TITLE
Cache busting for CSS and JavaScript resources

### ISSUE THREAD

**Issue by Cerallin** [hexojs/hexo#5189]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

When I was using the helpers, `css()` and `js()`, to insert resource files into my layouts, I noticed that there were no options to append query strings after the URLs dynamically.

For example, I want to append `?t=1681694914100` after `/css/style.css`, and the timestamp is actually regenerated each time I run the command `hexo generate`. 

Currently, there is a workaround: using injectors to do the URL replacement after HTML rendering. However, I still hope it's possible to add an option because the workarounds based on regex may have hidden danger and those based on parsers are too heavy (IMHO).

In all, I would like to know if an option such as `cache: false | "timestamp" | "sha1"` to be added to `css()` and `js()` is convenient.

**Comment by 7zMonkey** [comment]
应该是非必要的吧，可以通过`scripts `实现，个人感觉应该是主题作者实现这个功能，因为css/js是由主题作者载入的。

**Comment by stevenjoezhang** [comment]
You can install this plugin: https://github.com/next-theme/hexo-optimize
Then enable the static resource versioning feature.
