### ISSUE TITLE
[Request] ToC: link to the first heading position

### ISSUE THREAD

**Issue by kamasylvia** [hexojs/hexo#5197]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

I am experiencing an issue with the `toc` helper function, where the TOC is not properly linking to the first heading in my content.

### Expected behavior:

The TOC should properly link to the first heading/h1/`#` in the post.

### Actual behavior:

The TOC is not properly linking to the first heading/h1/`#` in the post.

**Comment by D-Sketon** [comment]
Is this a bug report or a feature request?
Please give more details.

**Comment by kamasylvia** [comment]
It seems the h1 is lacking active hyperlinks enabling navigability, whereas subordinate headings are properly instantiated with anchored links for navigation.

https://user-images.githubusercontent.com/9450184/236076985-5d7147b5-eaa5-48c4-b88b-bd8ae6ce2ddc.mp4

**Comment by kamasylvia** [comment]
I find the solution here https://github.com/jerryc127/hexo-theme-butterfly/issues/515
