### ISSUE TITLE
Multicore usage

### ISSUE THREAD

**Issue by improvedk** [hexojs/hexo#520]
Processing ~300 posts takes almost a minute, which is workable, but I'd like it to be much faster.

Looking at the task manager I see 13 node.exe processes (I've got 12 cores). 12 processes running `hexo\lib\plugins\console\generate\worker.js`, but doing nothing. And then a single process running `hexo\bin\hexo g` using 100% of the single core.

Am I missing something, or shouldn't hexo be able to utilize those other cores? `multi_thread` is set to `true` in my _config.yml, but I'm not sure if it's relevant.

**Comment by stevenjoezhang** [comment]
Thanks for your feedback. Please join the discussion here: #4355 :)
