### ISSUE TITLE
hexo:108: command not found: 方法

### ISSUE THREAD

**Issue by xdu-chenrj** [hexojs/hexo#5200]
I created an article called "Arrays类的copyOf()方法", and then the hexo command failed, displaying "hexo:109: command not found: 方法".

I tried reinstalling, but it also failed` npm i hexo@6.0.0 `
Please help me, thank you very much

**Comment by xdu-chenrj** [comment]
Update: I woke up this morning and found it to be normal. I don't understand

**Comment by stevenjoezhang** [comment]
你能截个图看看吗？

**Comment by xdu-chenrj** [comment]
截图没能留下，但是问题解决了，第二天重启电脑之后问题就解决了
