### ISSUE TITLE
Use nativebird instead of bluebird

### ISSUE THREAD

**Issue by so1ve** [hexojs/hexo#5215]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Hexo v7 still dependents on bluebird, which seems to be an overkill. Most of its features have been implemented in native promise now, so we can switch to [nativebird](https://github.com/doodlewind/nativebird) for better performance.

## Others

If this proposal is accepted I'm willing to implement

**Comment by stevenjoezhang** [comment]
See https://github.com/hexojs/hexo/issues/3328

**Comment by so1ve** [comment]
Yeah I have seen that before, but I'm not sure whether hexo uses some non-builtin promise methods. Feel free to close.

**Comment by SukkaW** [comment]
> I've seen a lot of Bluebird-specific APIs used in the Hexo source code 🤔 WDYT?

Bluebird and Hexo were born when ECMAScript Promise didn't exist/API was not stable.

And since some Hexo plugins may still rely on callback-based APIs, using Bluebird's `.asCallback` method can help maintain backward compatibility.

**Comment by so1ve** [comment]
Makes sense!
