### ISSUE TITLE
By pass security check: do not allow ../ in path

### ISSUE THREAD

**Issue by novysodope** [hexojs/hexo#5250]
## Check 
-  I have already read [Docs page](https://hexo.io/docs/)
-  I have already searched existing issues

## Feature Request
When browsing the project code, I found a vulnerability fix for arbitrary file reading:

[security check: do not allow ../ in path](https://github.com/hexojs/hexo/blob/a3e68e7576d279db22bd7481914286104e867834/lib/plugins/tag/include_code.js#L49)

After a brief thought, I found that this safety check is incomplete,that is to say, I can bypass here

In windows, I can use `..\` bypass:

```java
{% include_code ..\..\..\..\..\..\..\..\..\..\..\test.txt %}
```
![image](https://github.com/hexojs/hexo/assets/45167857/e6e6cb26-dda9-4cbc-8257-a08e29810be2)

The Linux file system does not support reading backslashes, theoretically it can be read through `..\/..\/..\/..\/..\/etc/passwd`,but I did not verify successfully on Linux. This operation was only verified successfully in the Windows environment.

So my suggestion is not only to do not allow `../` in path, also to do not allow `..\` in path, or change `../` to `..` , `file`

**Comment by stevenjoezhang** [comment]
I agree that include_code should only encompass files within the Hexo workspace. Otherwise, malicious attackers might manipulate users into revealing sensitive files from the disk through relative paths.
