### ISSUE TITLE
I want to create a static JSON data from the article list and Markdown document, which can be used by other external programs

### ISSUE THREAD

**Issue by xiyuvi** [hexojs/hexo#5252]
## Feature Request

I want to create a static JSON data from the article list and Markdown document, which can be used by other external programs。
I hope Hexo can support this feature, so that Hexo can play the role of headless CMS. Thank you very much

**Comment by renbaoshuo** [comment]
You can write a custom generator to generate the data you want.

https://hexo.io/api/generator

**Comment by stevenjoezhang** [comment]
For example: https://github.com/next-theme/hexo-generator-searchdb
