### ISSUE TITLE
css() and js() helper memoizing interacts badly with relative_links and local css/js files

### ISSUE THREAD

**Issue by JoshuaGrams** [hexojs/hexo#5261]
## Check List

Please check followings before submitting a new issue.

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [X] I have already searched existing issues and they are not help  to me
  - Well, I *tried* searching but "css" and "js" aren't very useful search terms. But I tried "helpers" and a bunch of things, and I looked through all 61 open issues, so I don't *think* this has been reported...
- [X] I examined error or warning messages and it's difficult to solve
- [X] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [X] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

Given:

* A local css file: `/blog/root/style.css`, for example.
* `relative_links: true`

Then:

* In `/blog/root/index.html` you want `css(style.css)` to return `style.css`
* In `/blog/root/archive/index.html` you want `css(style.css)` to give `../style.css`
* In `/blog/root/yyyy/mm/dd/title/index.html` you want it to give `../../../../style.css`

## Actual behavior

Both of these call e.g. `moize(cssHelper, ...)` ([here](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/css.js#L26) and [here](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/js.js#L26)) so the functions are evaluated once and the result will be correct for only one particular level of nesting. Worse, the result may change semi-randomly based on which file is rendered first (i.e. it might be different on different incremental builds).

So if `relative_links` is set and these helpers are given a local path, the memoization needs to take into account not only the argument to the function but also the page it's being rendered for.

**Comment by stevenjoezhang** [comment]
It should have been fixed by #5217

**Comment by JoshuaGrams** [comment]
Ah, so it is. Ugh, how did I not find that before I spent three hours chasing it down? Thanks!
