### ISSUE TITLE
Deployer not found: git

### ISSUE THREAD

**Issue by mcheping520** [hexojs/hexo#5270]
在部署博客的时候提示Deployer not found: git
![image](https://github.com/hexojs/hexo/assets/102772286/bc629fed-edd1-4318-93c4-c47196ca3800)

**Comment by D-Sketon** [comment]
安装 hexo-deployer-git

**Comment by mcheping520** [comment]
> 安装 hexo-deployer-git

好的，我犯迷糊了（雾
