### ISSUE TITLE
[bug] The js copied from the `Source` directory have been modified.

### ISSUE THREAD

**Issue by lqzhgood** [hexojs/hexo#5294]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

only copy files, don't modify

in docs https://hexo.io/docs/setup.html#source,  

> Renderable files (e.g. Markdown, HTML) will be processed

I think is not include `.js`

## Actual behavior

`test.js`  have been modified.  `/{{index}}/` > `//`

## How to reproduce?

* hexo init test
* cd test
* create `test.js` in `source` folder
  
```js
const a = ''.replace(/{{index}}/, 'ok')
```
    
* `npm run server` to start hexo
* open `http://localhost:4000/test.js`
* `test.js`  have been modified.

```js
const a = ''.replace(//, 'ok')
```

## Is the problem still there under "Safe mode"?

yes

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v18.16.0
9.8.1
```

**Your site `_config.yml`** (Optional)

default by hexo 6.3.0

**Hexo and Plugin version(`npm ls --depth 0`)**

<details>
 <summary>default by hexo 6.3.0</summary>

```
hexo-site@0.0.0 C:\Users\lqzh\Desktop\1\123
+-- hexo-generator-archive@2.0.0 -> .\node_modules\.pnpm\hexo-generator-archive@2.0.0\node_modules\hexo-generator-archive
+-- hexo-generator-category@2.0.0 -> .\node_modules\.pnpm\hexo-generator-category@2.0.0\node_modules\hexo-generator-category
+-- hexo-generator-index@3.0.0 -> .\node_modules\.pnpm\hexo-generator-index@3.0.0\node_modules\hexo-generator-index
+-- hexo-generator-tag@2.0.0 -> .\node_modules\.pnpm\hexo-generator-tag@2.0.0\node_modules\hexo-generator-tag
+-- hexo-renderer-ejs@2.0.0 -> .\node_modules\.pnpm\hexo-renderer-ejs@2.0.0\node_modules\hexo-renderer-ejs
+-- hexo-renderer-marked@6.1.1 -> .\node_modules\.pnpm\hexo-renderer-marked@6.1.1\node_modules\hexo-renderer-marked
+-- hexo-renderer-stylus@3.0.0 -> .\node_modules\.pnpm\hexo-renderer-stylus@3.0.0\node_modules\hexo-renderer-stylus
+-- hexo-server@3.0.0 -> .\node_modules\.pnpm\hexo-server@3.0.0\node_modules\hexo-server
+-- hexo-theme-landscape@1.0.0 -> .\node_modules\.pnpm\hexo-theme-landscape@1.0.0\node_modules\hexo-theme-landscape
`-- hexo@6.3.0 -> .\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo
```

</details>

**Your package.json `package.json`**

<details>
 <summary>default by hexo 6.3.0</summary>

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0"
  }
}
```

</details>

**Comment by stevenjoezhang** [comment]
Please upgrade to Hexo v7.0.0-rc1 and try again

**Comment by lqzhgood** [comment]
update to `v7.0.0-rc2` is ok, thank you ~
