### ISSUE TITLE
Inline codeblock with double brackets caught errors

### ISSUE THREAD

**Issue by dimaslanjaka** [hexojs/hexo#5305]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## How to reproduce?

https://github.com/orgs/hexojs/discussions/5303#discussioncomment-7192995

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**
 

```
v18.18.0
9.8.1
```

**Your site `_config.yml`** (Optional)

```yaml
url: https://www.webmanajemen.com
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

**Comment by D-Sketon** [comment]
I've noticed that when rendering, there is no renderer for markdown
![image](https://github.com/hexojs/hexo/assets/49871906/fe025163-22c8-4269-b000-19eaebbad5a5)

**Comment by dimaslanjaka** [comment]
> I've noticed that when rendering, there is no renderer for markdown It seems that hexo-renderer-marked wasn't successfully registered try
> 
> ```js
> const Hexo = require('./dist/hexo');
> 
> const hexo = new Hexo(__dirname, { silent: true })
> 
> const main = async () => {
>   await hexo.loadPlugin('../hexo-renderer-marked/index.js');
>   await hexo.init();
>   
>   const content =   `
>   ## below is pretext
> 
>   inline codeblock \`build-\${{ hashFiles('package-lock.json') }}\`
> 
>   \`\`\`js
>   const varx = \`build-\${{ hashFiles('package-lock.json') }}\`
>   \`\`\`
> 
>   \`\`\`ts
>   const xvar = \`build-\${{ hashFiles('package-lock.json') }}\`
>   \`\`\`
> 
>   \`\`\`
>   const var = \`build-\${{ hashFiles('package-lock.json') }}\`
>   \`\`\`
> 
>   ## below is meta info
> 
>   - published: {{ page.date }}
>   - modified: {{ page.updated }}
>   `
> 
>   
>   const data = await hexo.post.render(null, {
>     content,
>     engine: 'md'
>   });
>   console.log(data.content.trim())
> }
> 
> main()
> ```

yes. the hexo instance need register the renderer plugin to make the post renderer working perfectly
