### ISSUE TITLE
No index.html in root directory

### ISSUE THREAD

**Issue by nikraza** [hexojs/hexo#5315]
Installed hexo, created a new post, published, generated - no `index.html` in `root` directory. Browsing folders in browser generates 404 errors when I go to `public` folder (no 404 error) and follow any internal links to test posts I created.

**Comment by uiolee** [comment]
I cannot reproduced your case and no one provides enough information, I am going to **close** this issue. 

If the problem still exists, please **reopen** this issue and provide more information.
