### ISSUE TITLE
profiling error generated from the external PR

### ISSUE THREAD

**Issue by D-Sketon** [hexojs/hexo#5332]
> https://github.com/marocchino/sticky-pull-request-comment/issues/930

In https://github.com/hexojs/hexo/actions/workflows/benchmark.yml
PRs from external repositories can cause profiling to fail
```
Error: Request failed due to following response errors:
 - Resource not accessible by integration
```

**Comment by uiolee** [comment]
[marocchino/sticky-pull-request-comment#basic](https://github.com/marocchino/sticky-pull-request-comment/blob/main/README.md#basic)

https://github.com/hexojs/hexo/blob/268882b19a9a8510ce7df7d8a978ba2dd130d7be/.github/workflows/commenter.yml#L11

maybe it nedd PR permissions
