### ISSUE TITLE
v7.0.0 Can not change highlight to prismjs

### ISSUE THREAD

**Issue by g-mero** [hexojs/hexo#5351]
### Check List

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [ ] I have already searched existing issues and they are not help to me.
- [ ] I examined error or warning messages and it's difficult to solve.
- [ ] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [ ] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

I want to use prismjs highlight my code. But it always use highlightjs, even I already set highlightjs.enable to false in _config.yml

### Actual behavior

This issue only found on v7.0.0, work fine on old version.

![image](https://github.com/hexojs/hexo/assets/62990607/bc11137f-717c-4256-90c0-ea0985b5c562)
![image](https://github.com/hexojs/hexo/assets/62990607/30989adb-fc79-490d-9a83-2ba8b1ab5800)

### How to reproduce?

set highlightjs to false, rebuilt your proj

### Is the problem still there under `Safe mode`?

no

**Comment by D-Sketon** [comment]
also see https://github.com/hexojs/hexo/issues/5283

**Comment by noraj** [comment]
also see https://github.com/hexojs/hexo/releases/tag/v7.0.0

**Comment by D-Sketon** [comment]
We have updated the site, please see [syntax-highlight](https://hexo.io/docs/syntax-highlight) for more information.
