### ISSUE TITLE
创建自定义页面

### ISSUE THREAD

**Issue by wleelw** [hexojs/hexo#5368]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

他应该在is_page()函数执行时返回true

### Actual behavior

实际返回false

### How to reproduce?

```js
// generate categories Page
hexo.extend.generator.register('categories', function(locals) {
  if(!this.theme.config.page.categories)return
  const lang = hexo.theme.i18n.get(this.config.language || 'zh-CN')
  return {
    path: 'categories/index.html',
    layout: ['page'],
    data: {
      title: lang["page.category"],
      type: 'categories',
      comment: false
    }
  };
});
```

### Is the problem still there under `Safe mode`?

结果依然

### Your Node.js & npm version

```text
v18.17.0
10.2.0
```

### Your Hexo and Plugin version

```text
hexo-site@0.0.0 /Users/sco/Desktop/project/web/Private/untitled
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@6.1.1
├── hexo-renderer-pug@3.0.0
├── hexo-renderer-stylus@3.0.0
├── hexo-server@3.0.0
├── hexo-theme-landscape@1.0.0
└── hexo@7.0.0
```

### Your `package.json`

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.0.0"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.1.1",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0"
  }
}
```

### Others

我使用了layout=page但最返回的结果却并不是page，我需要什么方式去实现？

**Comment by ocoke** [comment]
I think the pages file should be outside of the `_posts` folder.
