### ISSUE TITLE
Markdown 代码解析问题

### ISSUE THREAD

**Issue by Astray-git** [hexojs/hexo#538]
```
{{#each}}
   //  代码里有这样的表达式就不能 generate 了
{{/each}}
```

代码区块中有 Handlebars.js 的表达式就会报错

```
SyntaxError: Unexpected token ;
    at Object.Function (<anonymous>)
    ...
```

**Comment by mingmings** [comment]
你好，我这里使用倒不是报错，但是显示很奇怪
![image](https://cloud.githubusercontent.com/assets/3365500/7830817/4f6b8bfa-0483-11e5-8e70-bc088d76562e.png)，并且代码块样式也已经发生变化
我以为是主题的缘故，更换主题后，仍旧显示如此，hexo 3.1.1 ，不知道是哪方面的缘故
