### ISSUE TITLE
fail to build hexo

### ISSUE THREAD

**Issue by uiolee** [hexojs/hexo#5408]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

Build successfully

### Actual behavior

> https://github.com/hexojs/hexo/actions/runs/7666372926/job/20894038821?pr=5407

![fail](https://github.com/hexojs/hexo/assets/22849383/356a5117-5b40-4dc2-94ab-df9bf163c71a)

```
> hexo@7.1.1 build D:\hexo
> tsc -b

node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/types/index.d.ts:9:14 - error TS2420: Class 'import("D:/hexo/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/types/index").FSWatcher' incorrectly implements interface 'import("fs").FSWatcher'.
  Type 'FSWatcher' is missing the following properties from type 'FSWatcher': ref, unref

9 export class FSWatcher extends EventEmitter implements fs.FSWatcher {
               ~~~~~~~~~


Found 1 error.

 ELIFECYCLE  Command failed with exit code 1.
```

### How to reproduce?

1. git clone
2. npm i
3. npm run build

### Is the problem still there under `Safe mode`?

..

**Comment by uiolee** [comment]
```diff
-    "@types/node": "^18.11.8",
+    "@types/node": "^18.11.8 <18.19.9",
```

typescript build will failed in `@types/node@18.19.9` and newer

**Comment by panxsz** [comment]
![管理员_ Windows PowerShell 2024_1_27 14_07_10](https://github.com/hexojs/hexo/assets/56928299/5e80a494-49fe-4714-b9c4-6d37cd4f9c76)

**Comment by uiolee** [comment]
https://github.com/paulmillr/chokidar/issues/1299
