### ISSUE TITLE
Hexo strips leading spaces in code blocks

### ISSUE THREAD

**Issue by TripleCamera** [hexojs/hexo#5422]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

Leading spaces in code blocks are not stripped.

### Actual behavior

Leading spaces in code blocks are stripped.

### How to reproduce?

Render the following lines:
``````````markdown
This is a paragraph.
```
    This is a code block
    with 4 spaces
    at the beginning of
    each line.
```
``````````

Here is [a live example on my blog](https://triplecamera.github.io/renderer-test/).

### Is the problem still there under `Safe mode`?

Cannot generate pages at all under safe mode.

### Your Node.js & npm version

```text
v20.11.0
10.2.4
```

### Your Hexo and Plugin version

```text
hexo-site@0.0.0 D:\GitHub\triplecamera.github.io
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-pandoc@0.4.0
├── hexo-renderer-stylus@3.0.1
├── hexo-server@3.0.0
├── hexo-theme-next@8.19.1
└── hexo@7.1.1
```

### Your `package.json`

See <https://github.com/TripleCamera/triplecamera.github.io>.

### Your site's `_config.yml` (Optional)

See <https://github.com/TripleCamera/triplecamera.github.io>.

**Comment by uiolee** [comment]
https://github.com/hexojs/hexo-util/blame/1cf5b21ceeb0d2f9456f9003b9f956c43903d4ff/lib/highlight.ts#L23

**Comment by TripleCamera** [comment]
Hi, how is everything going?

**Comment by TripleCamera** [comment]
Cheers! :tada:
