### ISSUE TITLE
编译后,发布时多了一个不存在的空文件

### ISSUE THREAD

**Issue by itl-coder** [hexojs/hexo#5438]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

编译后多了一个空文件,文件在本地不存在,编译后就会出现

### Actual behavior

![image](https://github.com/hexojs/hexo/assets/129035751/defe76c1-2707-4986-9398-105673e257ea)
![image](https://github.com/hexojs/hexo/assets/129035751/038a12af-23b3-472b-a94f-b0fe310362ba)
![image](https://github.com/hexojs/hexo/assets/129035751/fb0eec66-9c6d-48ee-ab74-dfc459525879)

### How to reproduce?

未知情况下发生的

### Is the problem still there under `Safe mode`?

no

### Your Node.js & npm version

```text
C:\Users\coderitl>node -v
v18.19.0

C:\Users\coderitl>npm -v
10.5.0

C:\Users\coderitl>
```

### Your Hexo and Plugin version

```text
D:\itl-coder-hexo>npm ls --depth 0
hexo-site@0.0.0 D:\itl-coder-hexo
+-- hexo-abbrlink@2.2.1
+-- hexo-admonition@1.1.2
+-- hexo-blog-encrypt@3.1.9
+-- hexo-browsersync@0.3.0
+-- hexo-butterfly-clock@1.0.7
+-- hexo-butterfly-footer-beautify@1.0.6
+-- hexo-butterfly-swiper@1.0.12
+-- hexo-butterfly-tag-plugins-plus@1.0.17
+-- hexo-deployer-git@4.0.0
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-category@2.0.0
+-- hexo-generator-index@3.0.0
+-- hexo-generator-search@2.4.3
+-- hexo-generator-tag@2.0.0
+-- hexo-hide-posts@0.4.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-kramed@0.1.4
+-- hexo-renderer-pug@3.0.0
+-- hexo-renderer-stylus@3.0.0
+-- hexo-server@3.0.0
+-- hexo-theme-landscape@1.0.0
`-- hexo@7.0.0
```

### Your `package.json`

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.0.0"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-admonition": "^1.1.2",
    "hexo-blog-encrypt": "^3.1.9",
    "hexo-browsersync": "^0.3.0",
    "hexo-butterfly-clock": "^1.0.7",
    "hexo-butterfly-footer-beautify": "^1.0.6",
    "hexo-butterfly-swiper": "^1.0.12",
    "hexo-butterfly-tag-plugins-plus": "^1.0.17",
    "hexo-deployer-git": "^4.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-tag": "^2.0.0",
    "hexo-hide-posts": "^0.4.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0"
  }
}
```

**Comment by uiolee** [comment]
If your problem disappear under "Safe mode", it means the problem is probably at your installed plugins or theme, not at hexo.

**Comment by itl-coder** [comment]
![image](https://github.com/hexojs/hexo/assets/129035751/40a20a0d-6e42-40a8-b0ce-109dcac4bcb3)
an'qua安全模式下依然存在该问题,没有找到解决方法

**Comment by uiolee** [comment]
run
```
hexo clean 
hexo g --safe
```

**Comment by uiolee** [comment]
Because it cannot be reproduced and no one provides enough information, I am going to **close** this issue. 

If the problem still exists, please **reopen** this issue and provide more information.
