### ISSUE TITLE
对于无序列表中的代码块渲染出错

### ISSUE THREAD

**Issue by QSlotus** [hexojs/hexo#5450]
如题。
这是我的markdown内容：
![image](https://github.com/hexojs/hexo-renderer-marked/assets/109905194/0a27ad2e-214a-4c7b-95fe-b66bb6e65d2d)
在vscode自带的markdown渲染中是正常的：
![image](https://github.com/hexojs/hexo-renderer-marked/assets/109905194/c5c5bd1f-096a-4c5d-aa9d-2b3be08e6017)
而使用 `hexo s` 后预览的界面却渲染错误：
![image](https://github.com/hexojs/hexo-renderer-marked/assets/109905194/638f3815-7100-4f99-91e5-18000ce56211)

**Comment by Liu8Can** [comment]
无序列表中添加代码实际上是不符合markdown标准格式的，需要额外做适配。比如在typora和vscode中就可以，但是在obsidian中就不可以。
因此，建议在写代码块时就直接另起一行，这样兼容性更好，不然即使在hexo中解决了，在其他平台也可能出问题。

**Comment by stevenjoezhang** [comment]
这个 Issue 先关了，请加入 #5423 的讨论

**Comment by stevenjoezhang** [comment]
Fixed by https://github.com/hexojs/hexo/pull/5617
