### ISSUE TITLE
Deployment is taking too much time

### ISSUE THREAD

**Issue by Atif-Sheikh** [hexojs/hexo#5456]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

It should take less than 10 minutes

### Actual behavior

Takes 40+ minutes for deployment and Blog generation.

### How to reproduce?

hexo g

### Is the problem still there under `Safe mode`?

Yes

### Your Node.js & npm version

```text
v18.19.0
10.2.3
```

**Comment by stevenjoezhang** [comment]
Currently, we are aware that in some cases, Hexo generation can be very slow: https://github.com/hexojs/hexo/issues/2579 https://github.com/hexojs/hexo/issues/4309
To answer your question, we need more information, such as whether your blog has a lot of articles or images?

**Comment by Atif-Sheikh** [comment]
> Currently, we are aware that in some cases, Hexo generation can be very slow: #2579 #4309 To answer your question, we need more information, such as whether your blog has a lot of articles or images?

@stevenjoezhang We have around 600+ articles and yes every article has images as well.

**Comment by Atif-Sheikh** [comment]
@stevenjoezhang Can we expect the fix from the Hexo ASAP as most of the users are struggling with this issue?

**Comment by yoshinorin** [comment]
As mentioned in comment [#2579](https://github.com/hexojs/hexo/issues/2579#issuecomment-1345157672), almost certainly your environment will be speed improvement by deleting `db.json` before running `hexo g` or `hexo s`, as suggested if you're not using the [id](https://hexo.io/docs/permalinks#Variables) for persistence purposes.

There are no official Hexo plugins that use `ids` for persistence purposes, but we don't know about third-party plugins.

In fact, I've been deleting `db.json` before running `hexo g` and `hexo s` for quite some time, and it's quite effective. In my current environment, I have 1800 `.md` files and 1500 image files (jpg, png), and `db.json` is 37MB. Without deleting `db.json`, `hexo g` takes about 8 minutes to complete, but with it deleted, it finishes in less than a minute."

**Comment by Atif-Sheikh** [comment]
> Did you encounter this problem after upgrading your Hexo version? As far as I know, slowdowns in generation time are not common, so I can't pinpoint the exact cause of this issue, nor do we know how to optimize it. If possible, you can help us by conducting an experiment: run the command
> 
> ```shell
> npm i -g 0x
> 0x node_modules/.bin/hexo g
> ```
> 
> This command will generate an HTML file (flamegraph), and we can use this information to identify where the performance bottleneck is.

@stevenjoezhang Here is the [`flamegraph`](https://github.com/hexojs/hexo/files/14977124/flamegraph_updated.html.zip) file, Please take a look at it and yes I'm using the latest Hexo version.

**Comment by stevenjoezhang** [comment]
Additionally, the `hexo-asset-pipeline` also occupies a significant amount of processing time. This plugin has actually been deprecated by the Hexo team since 2022: https://github.com/hexojs/hexo-asset-pipeline. If you need to compress HTML files, I recommend using the [hexo-optimize](https://github.com/next-theme/hexo-optimize) plugin, which uses a Rust-based HTML compression library for better performance. For image compression, you may need to look for other tools as alternatives.

**Comment by stevenjoezhang** [comment]
I will close this issue, if the problem persists, feel free to continue replying.
