### ISSUE TITLE
Syntax that causes all block tags to fail

### ISSUE THREAD

**Issue by akfish** [hexojs/hexo#546]
Syntax in the following form will cause error when used in block tag:

``` markdown
{% anyblock %}
{{(\)}}
{% endanyblock %}
```

Variations are:
- `{{(anything_before\)}}`
- `{{(\anything_after)}}`
- `{{(before\and_after)}}`

When generating pages, the following error will be thrown:

```
[error] HexoError: Process failed: _posts/tag-bug-test.md
Error: Unable to parse "(\)" on line 2.
    at Object.exports.throwError (\npm\
node_modules\hexo\node_modules\swig\lib\utils.js:179:9)
    at parseVariable (\npm\node_modules
\hexo\node_modules\swig\lib\parser.js:485:13)
    at \npm\node_modules\hexo\node_modu
les\swig\lib\parser.js:629:15
    at Object.exports.each (\npm\node_m
odules\hexo\node_modules\swig\lib\utils.js:45:11)
    at Object.exports.parse (\npm\node_
modules\hexo\node_modules\swig\lib\parser.js:618:9)
    at parse (\npm\node_modules\hexo\no
de_modules\swig\lib\swig.js:322:19)
    at Object.precompile (\npm\node_mod
ules\hexo\node_modules\swig\lib\swig.js:455:23)
    at Object.compile (\npm\node_module
s\hexo\node_modules\swig\lib\swig.js:560:16)
    at \npm\node_modules\hexo\lib\post\
render.js:69:29
    at \npm\node_modules\hexo\node_modu
les\async\lib\async.js:548:21
```

This affects all block tags: `blockquote`, `codeblock`, `rawblock` and etc and any extended block tags.

This bug is discovered when testing my [hexo-math](https://github.com/akfish/hexo-math) plugin, which renders math equations written in LaTex, with the following syntax:

```
Gaussian Distribution: 
{% math-block %}
f(x) = {1 \over \sigma\sqrt{2\pi} }\,e^{- {{(x-\mu )^2 \over 2\sigma^2}}}
{% endmath-block %}
```

`{{(x-\mu )^2 \over 2\sigma^2}}` causes this issue. 

As you can see, this syntax does appears in legitimate usage. Any way to avoid this before it's fixed?

**Comment by Xuanwo** [comment]
@tommy351 You closed https://github.com/hexojs/hexo/issues/549 , fixed?

**Comment by sebs** [comment]
This is now more than 4 years old, may I ask the question if the hexo project is still alive? Looking into this bugtracker leaves me unsure.

**Comment by tomap** [comment]
Hi @sebs, I'll try to look into it, reproduce the issue, see if it's linked to a dependency, and relay the issue to them. But you can help, it's a huge amount of work, to follow, answer, reply to issues... Any help is welcome

**Comment by sebs** [comment]
Its probably a good idea, to sort the tracker by oldest and close whatever is older than X, maybe with a message about a cleanup. maybe some feature requests are more to be ideas and can be added to a document instead of the tracker. Others will maybe not be implemented. Then maybe everything up to 2016 check if there is stuff that needs feedback and maybe close in case.

**Comment by sebs** [comment]
Ah ... if you need me volunteering .. its not much that I do these days. So I would be ok to throw some days into cleanup the bugtracker (only to re fill it with my own issues)

**Comment by stevenjoezhang** [comment]
There is a discussion about it #3259
I'm closing this issue. Please join the discussion there :)
