### ISSUE TITLE
'hexo' is not a recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by davidfekke** [hexojs/hexo#548]
I get the following error after I have installed hexo globally on Windows;

'hexo' is not a recognized as an internal or external command, operable program or batch file.

What am I doing wrong?

**Comment by Lin07ux** [comment]
I get the same error. I cann't fix it.

**Comment by Xuanwo** [comment]
while install nodejs, please choose add the path.
And install hexo with `npm install hexo-cli -g`

**Comment by Lin07ux** [comment]
I fixed the error: I had change the "npm prefix", but I did not add the path to global PATH. Now, everything is OK! Thank you!
