### ISSUE TITLE
Remove bluebird

### ISSUE THREAD

**Issue by ffha** [hexojs/hexo#5496]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/).
- [X] I have already searched existing issues.

### Feature Request

As the [bluebird's readme](https://github.com/petkaantonov/bluebird) says:

> Please use native promises instead if at all possible. Native Promises have been stable in Node.js and browsers for around 6 years now and they have been fast for around 3. Bluebird still offers some useful utility methods and you can use it - but please consider native promises first.
…
Currently - it is only recommended to use Bluebird if you need to support old browsers or EoL Node.js or as an intermediate step to use warnings/monitoring to find bugs.

**Comment by D-Sketon** [comment]
duplicated. see also #5215
