### ISSUE TITLE
auto_spacing: true 不起作用

### ISSUE THREAD

**Issue by CX330Blake** [hexojs/hexo#5509]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

如題

### Actual behavior

如題

### How to reproduce?

config.yml設置

### Is the problem still there under `Safe mode`?

yes

**Comment by D-Sketon** [comment]
auto_spacing configuration has been invalid since https://github.com/hexojs/hexo-filter-auto-spacing/commit/3493a23e483f7804f9d4ce324e7d45b935fea514
