### ISSUE TITLE
The web page is not generated when the article filename contains specific words

### ISSUE THREAD

**Issue by hghgthifg** [hexojs/hexo#5540]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

Html files are generated in public folder

### Actual behavior

No html files are generated in public folder, and when I use ```hexo d```, the website cannot be deployed successfully either. But when I use ```hexo s```, it seems all right.

### How to reproduce?

1. Create an article whose filename contains "生成" which means "generate" in English, or "建造", which means "build".
2. Use ```hexo g``` to generate html files.

### Is the problem still there under `Safe mode`?

When I use safe mode, no files are generated even the trouble makers are deleted

**Comment by uiolee** [comment]
can not reproduce

```log
$ hexo new '生成'
INFO  Validating config
INFO  Created: D:\git\hexojs\hexo-starter\source\_posts\生成.md

$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 580 ms
INFO  Generated: archives/index.html
INFO  Generated: 404/index.html
INFO  Generated: archives/2024/06/index.html
INFO  Generated: index.html
INFO  Generated: css/style.css
INFO  Generated: fancybox/jquery.fancybox.min.css
INFO  Generated: archives/2024/09/index.html
INFO  Generated: js/script.js
INFO  Generated: archives/2024/index.html
INFO  Generated: fancybox/jquery.fancybox.min.js
INFO  Generated: js/jquery-3.6.4.min.js
INFO  Generated: css/images/banner.jpg
INFO  Generated: 2024/06/21/hello-world/index.html
INFO  Generated: js/a.ts
INFO  Generated: 2024/09/04/生成/index.html
INFO  15 files generated in 554 ms
```

**Comment by hghgthifg** [comment]
> can not reproduce
> 
> ```
> $ hexo new '生成'
> INFO  Validating config
> INFO  Created: D:\git\hexojs\hexo-starter\source\_posts\生成.md
> 
> $ hexo g
> INFO  Validating config
> INFO  Start processing
> INFO  Files loaded in 580 ms
> INFO  Generated: archives/index.html
> INFO  Generated: 404/index.html
> INFO  Generated: archives/2024/06/index.html
> INFO  Generated: index.html
> INFO  Generated: css/style.css
> INFO  Generated: fancybox/jquery.fancybox.min.css
> INFO  Generated: archives/2024/09/index.html
> INFO  Generated: js/script.js
> INFO  Generated: archives/2024/index.html
> INFO  Generated: fancybox/jquery.fancybox.min.js
> INFO  Generated: js/jquery-3.6.4.min.js
> INFO  Generated: css/images/banner.jpg
> INFO  Generated: 2024/06/21/hello-world/index.html
> INFO  Generated: js/a.ts
> INFO  Generated: 2024/09/04/生成/index.html
> INFO  15 files generated in 554 ms
> ```

[NOIP2022-建造军营.md](https://github.com/user-attachments/files/16883191/NOIP2022-.md)

Maybe you can try this file. If you still can't reproduce, it may be a bug with the theme.

**Comment by uiolee** [comment]
can not reproduce

```log
$ hexo g 
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 864 ms
INFO  Generated: 404/index.html
INFO  Generated: archives/index.html        
INFO  Generated: archives/2023/index.html   
INFO  Generated: tags/dp/index.html
INFO  Generated: index.html
INFO  Generated: archives/2024/06/index.html
INFO  Generated: archives/2024/09/index.html
INFO  Generated: archives/2024/index.html   
INFO  Generated: tags/Tarjan/index.html     
INFO  Generated: js/a.ts
INFO  Generated: tags/OI/index.html
INFO  Generated: tags/缩点/index.html
INFO  Generated: tags/题解/index.html
INFO  Generated: categories/题解/index.html
INFO  Generated: css/style.css
INFO  Generated: fancybox/jquery.fancybox.min.css       
INFO  Generated: archives/2023/11/index.html
INFO  Generated: js/jquery-3.6.4.min.js
INFO  Generated: fancybox/jquery.fancybox.min.js        
INFO  Generated: js/script.js
INFO  Generated: 2024/09/04/foo生成bar/index.html       
INFO  Generated: 2023/11/12/NOIP2022-建造军营/index.html
INFO  Generated: css/images/banner.jpg
INFO  Generated: 2024/06/21/hello-world/index.html      
INFO  Generated: 2024/09/04/生成/index.html
INFO  25 files generated in 588 ms
```
