### ISSUE TITLE
menu items not working when site is a subdirectory 

### ISSUE THREAD

**Issue by practicalli-johnny** [hexojs/hexo#583]
I have an Hexo website using the default landscape theme.  I wanted to have the navbar at the top to have a few additional entries, pointing to pages or external URLs.  So I added these entries in the `menu:` section of the themes `_config.yml` file, pointing to pages I created with the command `hexo new page "clojure"` or to external URLs

```
menu:
  Home:      /
  Archives:  /archives/
  Clojure:   /clojure/
  Ubuntu:    /ubuntu/
  Slides:    http://jr0cket.github.io/
  DevGuides: http://jr0cket.github.io/developer-guides
rss: /atom.xml
```

When I visit Home or the external URL links, that works okay.  When I visit the Archive, Clojure or Ubuntu links in the navbar, they fail because they don't include the subfolder name.

For example, the archive link in the top level navbar has the link

```
http://localhost:4000/archive
```

and when deployed on github pages, has the link:

```
http://jr0cket.github.io/archives/
```

when it should have the respective links

```
http://localhost:4000/hexo-themes-test/archive
http://jr0cket.github.io/hexo-themes-test/archives/
```

In the root _config.yml file, I defined the website URL using github pages, also specifying the child directory:

```
url: http://jr0cket.github.io/hexo-themes-test
root: /hexo-themes-test/
```

Unless I have missed something, it seems you either have to hard code the child folder into the menu or this seems like a bug.

Thank you

**Comment by Danceiny** [comment]
Oh, I got the same problem with you, and I have tried your methods, the shit slash/////////////
i'm lucky to see this article, i have fix it.Thank you a lot!
