### ISSUE TITLE
Hexo to use relative path instead of URL

### ISSUE THREAD

**Issue by KaptainKrayola** [hexojs/hexo#592]
I want to be able to generate a site that I can open from a windows folder or any URL just by uploading the folder.   Currently it seems that the config requires a URL to build the site but that will not work in this case.

Can you add an argument/option that allows for all links / stylesheets / etc to just be relative to the location the file is opened from?

**Comment by jbenet** [comment]
Im curious if this is still a problem. In many settings, the URL root cannot be determined a priori, so all the links must be relative. 

- Does hexo support this use case today? 
- Can all generated links be made relative?
- What's the easiest way to do so?

If this is the case, i'll come back with a really cool way to deploy hexo websites for free :)  -- Thanks.

**Comment by podybman** [comment]
I find myself having this issue on a fresh install. 
Regression?

**Comment by stevenjoezhang** [comment]
@podybman It depends on the theme you are using. If it has `fragment_cache` enabled and does not provide an option to disable, relative links may be incorrect.

**Comment by podybman** [comment]
It's a fresh install si that's the default theme (landscape I believe)

**Comment by stevenjoezhang** [comment]
@podybman If you found that the style is missing, it's caused by https://github.com/hexojs/hexo/pull/5217
You can try to install the latest release candidate version of Hexo `npm i hexo@7.0.0-rc2`

**Comment by Xuanwo** [comment]
Hi, please don't reply to an old & closed issues. Start a new one instead, thanks!
