### ISSUE TITLE
hexo new failed

### ISSUE THREAD

**Issue by fantasyty** [hexojs/hexo#593]
```
date: 2014-04-23 11:18:01.827
argv: C:\Program Files\nodejs\node.exe C:\Users\yue.taoy\AppData\Roaming\npm\node_modules\hexo\bin\hexo new why failed
os: Windows_NT 6.1.7601 win32 x64
version:
  hexo: 2.5.3
  http_parser: 1.0
  node: 0.10.26
  v8: 3.14.5.9
  ares: 1.9.0-DEV
  uv: 0.10.25
  zlib: 1.2.3
  modules: 11
  openssl: 1.0.1e

---

[debug] 11:18:01.744 Config file loaded
[debug] 11:18:01.745 Version info checked successfully
[debug] 11:18:01.775 Loading database.
[debug] 11:18:01.814 Script load successfully: fancybox.js
[error] 11:18:01.824 Error: ENOENT, open 'D:\study\blog\source\_posts\:.md'
Error: ENOENT, open 'D:\study\blog\source\_posts\:.md'
```

刚安装完第一次hexo new，generate，deploy都是正常的，试玩了一会开始new第二篇的时候就error了。环境重新部署之后，还是第二次的时候挂掉了。这个是怎么回事？

**Comment by Xuanwo** [comment]
我怀疑跟文件名有关：`:.md`

**Comment by leesei** [comment]
Related to filename, we should also escape `:`.
But I suppose this is already handled in `hexo-util/lib/slugize.js`?

Reference:
[filenames - What characters are safe in cross-platform file names for Linux, Windows and OS-X - Super User](http://superuser.com/questions/358855/what-characters-are-safe-in-cross-platform-file-names-for-linux-windows-and-os)

**Comment by Xuanwo** [comment]
@leesei https://github.com/hexojs/hexo-util/blob/master/lib/escape_regexp.js#L7 , `:` not escaped.
