### ISSUE TITLE
After updating config for theme, hexo generate won't update the style.css file.

### ISSUE THREAD

**Issue by NicholasTD07** [hexojs/hexo#595]
For example, when I commented out the sidebar section in `_config.yml` file. `hexo g` won't update the `style.css` file. However I think it should be. Right now, I am doing `hexo clean` before a `hexo g`.

I tried to fix this by my own but failed. (I am still very new to node.js.)
Could you give me some ideas/directions about how I can fix it? I mean, if you don't want to do it. :smile: 

Thanks.

**Comment by Xuanwo** [comment]
Closed for no more discussion.
