### ISSUE TITLE
Is there a Community somewhere else? 

### ISSUE THREAD

**Issue by prigazzi** [hexojs/hexo#601]
Hey guys, So far I'm loving Hexo, but let me ask a question... 
Do you have some community going somewhere else besides this Github Issues? There are some things I'd like to show up, my latests Theme or ways I solved things, and I think having only Github Issues as a "discussion forum" can get in the way. 

Do you have any forum, IRC, news-list, or anything to talk about Hexo-related things?

**Comment by RichardJECooke** [comment]
https://gitter.im/hexojs/hexo
