### ISSUE TITLE
怎么在某些图片上禁用 fancybox？

### ISSUE THREAD

**Issue by twiceyuan** [hexojs/hexo#605]
一些图片本身链接了一个地址，在启用 fancybox 后点击图片原来的地址就失效了

**Comment by ixiusama** [comment]
您好，我想知道如何才能指定一个文件的 ` class ` 为 ` nofancybox ` ？我想使用 ` hexo-tag-emojis ` 来进行添加 ` Emoji ` 表情，但是 ` nofancybox ` 总是不工作。

**Comment by wzpan** [comment]
[Image](https://hexo.io/docs/tag-plugins.html#Image) 的 Tag Plugin 应该支持指定样式呀。
