### ISSUE TITLE
"Error: Theme landscape does not exist." on Windows

### ISSUE THREAD

**Issue by 66beta** [hexojs/hexo#607]
**nodejs v0.10.28, Windows 7 X86**

when I run "hexo init test", got the error msg:
[
PS C:\Users\aaa\Documents> hexo init test
[error] Error: Theme landscape does not exist.
Error: Theme landscape does not exist.
    at C:\Program Files\nodejs\node_modules\hexo\lib\loaders\config.js:219:16
    at Object.cb [as oncomplete] (fs.js:168:19)
]

I've tried using nodist, same error...

**Comment by sebie** [comment]
Did @66beta method  work for you @ianks ? Also having same problem, going to try the method above.
