### ISSUE TITLE
更新2.6.0后generate生成页面错误

### ISSUE THREAD

**Issue by moreoronce** [hexojs/hexo#632]
<code>hexo clean</code>
<code>hexo generate</code>

然后打开页面显示的是：

<%- partial('_partial/head') %>
<%- partial('_partial/header') %>
<%- body %>
<% if (theme.sidebar && theme.sidebar !== 'bottom'){ %> <%- partial('_partial/sidebar') %> <% } %>
<%- partial('_partial/footer') %>
<%- partial('_partial/mobile-nav') %> <%- partial('_partial/after-footer') %>

补充：

theme使用的是默认的landscape

**Comment by qiaohaijun** [comment]
thanks

**Comment by ferstar** [comment]
多谢楼上
