### ISSUE TITLE
Categories page title/h1/description

### ISSUE THREAD

**Issue by arkasha69** [hexojs/hexo#643]
Hi, is it possible to setup for categories/tags pages title, h1, description and etc.

**Comment by leesei** [comment]
Hexo support [data files](https://hexo.io/docs/data-files.html).
You may modify the themes tags and categories layout template to do a matching with this file to display custom info.

Use the [`log()` helper](https://github.com/hexojs/hexo/pull/1391) to dump the variables available to the template.
Please close the issue if you don't have further issue.

**Comment by Xuanwo** [comment]
Closed for no more update.
