### ISSUE TITLE
Error occurs when deploy to Github Pages

### ISSUE THREAD

**Issue by thelingxichen** [hexojs/hexo#648]
Hi, when I run 

> hexo deploy

Error occurs like the following:

> [info] Start deploying: github
> [info] Clearing .deploy folder...
> [info] Copying files from public folder...
> On branch master
> nothing to commit, working directory clean
> ERROR: Repository not found.
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> [info] Deploy done: github>

In my configuration file,  the code is like this:

> deploy:
>   type: github
>   repository: git@github.com:paprikachan/paprikachan.github.io.git
>   branch: master

And I have already add the SSH to my Github account. I really cannot figure out why this didn't work. Thanks.

**Comment by LalindaSampath** [comment]
Hi Team,

I'm having the same problem. My Hexo version is 3.2.2. In my root directory there's no .deploy folder. Instead of that I have a folder named .deploy_git. After `cd .deploy_git` when I run `git remote -v`, cmd does not show any output. How to fix this?

**Comment by SharleneL** [comment]
@LalindaSampath Hi have you already solved the problem? Same issue here :(

**Comment by guanzhenxing** [comment]
Hi, this problem again.How to fix this?

**Comment by ChaoPei** [comment]
same issue

**Comment by jc-wow** [comment]
so, there's still no answer here?

**Comment by bmitchinson** [comment]
@jc-wow reference jr0cket's answer. Check your remotes, and if they're both listed, and your configuration file has the correct repository link, attempt to clone it. If you can't clone, that's an issue with git and your permissions, nothing to do with hexo.

**Comment by jc-wow** [comment]
> @jc-wow reference jr0cket's answer. Check your remotes, and if they're both listed, and your configuration file has the correct repository link, attempt to clone it. If you can't clone, that's an issue with git and your permissions, nothing to do with hexo.

thanks buddy, I have figure it out.

**Comment by jc-wow** [comment]
_this 's my error:_

> INFO  Clearing .deploy_git folder...
> INFO  Copying files from public folder...
> INFO  Copying files from extend dirs...
> [master 3a7417b] Site updated: 2019-07-12 09:47:45
>  6 files changed, 16 insertions(+), 16 deletions(-)
> ERROR: Repository not found.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
_here's my deployment in _config.yml:_

>  deploy:
>   type: git
>   repo: git@github.com:jc-wow/jc-wow.github.io.git
>   branch: master
**PlEASE ENSURE your repository name on github the same as {username}.github.io in repo in _config.yml！**
