### ISSUE TITLE
连续执行generate，public下会产生不同的结果

### ISSUE THREAD

**Issue by hhlux** [hexojs/hexo#65]
执行hexo generate一次，public下会产生所有的文章，但没有archives文件夹
public
  2013
    01
      16
         new_post
         new_post2

当再执行一下hexo generate，public下会产生archives文件夹，但archives下除了index.html，却没有其它文章：
public 
  archives
    2013
      01
        index.html

再执行一次generate，就会变回第一种情况。

另外部署到github后，点击archives经常出现404错误，但本地preview完全正常，不知道是不是因为这个generate的问题？

**Comment by xjvf** [comment]
完全不能生成index，不能deploy，也不能用server。但是同环境相同设置下其它的repo都正常生成。。。
崩溃了
exo-site@0.0.0
├── hexo@3.7.1
├── hexo-algoliasearch@0.3.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
