### ISSUE TITLE
Static home page

### ISSUE THREAD

**Issue by panzhangwang** [hexojs/hexo#654]
I need setup a static home page for my blog. Any help will be appreciated.

**Comment by simonh1000** [comment]
How can I have a page that is rendered by Hexo (i.e. with the themes headers and footer etc) from markdown but set as the home (landing) page with the blog element put in a directory `/blog`

**Comment by Ehesp** [comment]
Does the theme have to support this? Trying the above with http://blog.zhangruipeng.me/hexo-theme-hueman/ just shows the default still.
