### ISSUE TITLE
Rawblock in page are not correctly parsed

### ISSUE THREAD

**Issue by fwz** [hexojs/hexo#655]
Hi all, I encounter a similar problem to issue #587. But it's a different one. 

originally, I use

{% rawblock %}
some html and js code
{% endrawblock %}

to include a d3.js demo in the my post(regular md file), and it works good.

After I update to Hexo 2.x, chars such as " and < are encoded and not correctly parsed. 

for example,
```
var vis = d3.select("#div_Force_based_label_placement").append("svg:svg");
```

now becomes
```
var vis = d3.select(&quot;#div_Force_based_label_placement&quot;).append(&quot;svg:svg&quot;);
```

How can I fix it? any suggestion would be appreciated, thanks!

**Comment by Xuanwo** [comment]
Hello, dose this problem exist in version 3?

**Comment by Xuanwo** [comment]
ref: https://github.com/hexojs/hexo/blob/master/package.json#L36

Closed for fixed.
