### ISSUE TITLE
how to customize the order of categories/tags

### ISSUE THREAD

**Issue by starrysl** [hexojs/hexo#669]
Hi. I want to ask how to manually change the order of the categories/tags which are shown in the side widgets?

**Comment by macscripter** [comment]
Hi,

I would like to have an order of categories defined by my "own order". For example, "category 3", "category 1", " category 5". I see that I can use the length, name as a criteria. But is it possible to put the array that would be my own order? Something like ["category 3", "category 1", " category 5"]?

Thanks in advance!

**Comment by cangyuyao** [comment]
Sorry but is this solved? Is there an option to disable `orderby`?
I try to use `orderby: 'none'` and remove this line but it still sorts in some way, different from by `name` or `length` but not in the order I write in the front-matter. 
https://github.com/hexojs/hexo/blob/92b979f4a3fa8714aebd3d11c3295d466b870905/lib/plugins/helper/list_tags.js#L47

**Comment by stevenjoezhang** [comment]
Set the value of `orderby` in Hexo `_config.yml` to the key you used in the front-matter. For example, if you set `orderby: 'sticky'`, then use the key `sticky` to sort posts:

```
---
title: Title
sticky: 10
---
```

**Comment by cangyuyao** [comment]
> Set the value of `orderby` in Hexo `_config.yml` to the key you used in the front-matter. For example, if you set `orderby: 'sticky'`, then use the key `sticky` to sort posts:
> 
> ```
> ---
> title: Title
> sticky: 10
> ---
> ```

I mean the order of the categories/tags in `post.tags`, `site.tags` etc, not the order of all posts.
