### ISSUE TITLE
Capitalization of Hexo blog posts

### ISSUE THREAD

**Issue by andrewboni** [hexojs/hexo#679]
If I write the following:

```bash
hexo n "This is an Awesome Blog Post"
```
The slug that is generated is `/2014/06/15/This-is-an-Awesome-Blog-Post/`, which is different from the behavior of, say, Octopress. Octopress automatically lowercases all slugs (as do most other static blogs and CMSs).

I realize that there is the `titlecase: true` options in `_config.yml`, but many times I want custom capitalization in my titles.

The ideal scenario would be:
 - I can do any of the following:
```bash
hexo n "This is an Awesome Blog Post"
hexo n "THIS IS AN AWESOME BLOG POST"
hexo n "This Is An AwEsOme Blog PoSt"
``` 
- All slugs are lowercased, e.g. `/2014/06/15/this-is-an-awesome-blog-post/`

Thoughts?

**Comment by bennyn** [comment]
Setting [filename_case](https://hexo.io/docs/configuration.html#Writing) to `1` did the trick for me!
