### ISSUE TITLE
如何控制图片尺寸?

### ISSUE THREAD

**Issue by youthy** [hexojs/hexo#708]
```
  ![](image_url)
```

是原本尺寸,有时候插的图比较大,如何控制尺寸呢,或者弄成缩略图,点开后放大的功能?求教

**Comment by aeronxie** [comment]
为啥用html我的不行呢~~~在markdown中显示变小了，然后一部署就不行了

**Comment by 7loiter** [comment]
yilia主题，同样markdown中有效果，部署之后就不行了，本地不联网预览显示变小，联网预览同样不行。

**Comment by Xuanwo** [comment]
这个50%是否生效取决于你之前一个div的大小，可以试试直接指定px

**Comment by itbj** [comment]
是否有新的方法了？谢谢。

**Comment by zeusro** [comment]
## 居中图片

```html
<p align="center">
  <img src="https://user-images.githubusercontent.com/5803609/88500160-7e8a7c00-cffa-11ea-95c7-32579177273c.png" alt="Zeusro的微信二维码"/>
</p>
```

<p align="center">
  <img src="https://user-images.githubusercontent.com/5803609/88500160-7e8a7c00-cffa-11ea-95c7-32579177273c.png" alt="Zeusro的微信二维码"/>
</p>

## 居中指定比例

```html
<p align="center">
  <img src="https://user-images.githubusercontent.com/5803609/88500160-7e8a7c00-cffa-11ea-95c7-32579177273c.png" alt="Zeusro的微信二维码" width='50%' height='50%'/>
</p>
```

<p align="center">
  <img src="https://user-images.githubusercontent.com/5803609/88500160-7e8a7c00-cffa-11ea-95c7-32579177273c.png" alt="Zeusro的微信二维码" width='50%' height='50%'/>
</p>

## 居中指定像素

```html
<p align="center">
  <img src="https://user-images.githubusercontent.com/5803609/88500160-7e8a7c00-cffa-11ea-95c7-32579177273c.png" alt="Zeusro的微信二维码" width='50px' height='50px'/>
</p>
```

<p align="center">
  <img src="https://user-images.githubusercontent.com/5803609/88500160-7e8a7c00-cffa-11ea-95c7-32579177273c.png" alt="Zeusro的微信二维码" width='120px' height='120px'/>
</p>

**Comment by wakaka123wakaka** [comment]
因为我引用的图片较多，是否可以通过添加某个全局变量实现只要静态生成 就直接自动符合我想要显示的大小呢

**Comment by ZongbinTu** [comment]
使用
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
来引用生成markdown图片带上文章路径，无法控制图片尺寸
