### ISSUE TITLE
.ejs 中，page 对象有误

### ISSUE THREAD

**Issue by victorwoo** [hexojs/hexo#729]
在 http://hexo.io/docs/variables.html 中，介绍 **Page Variables** 分为 **Article (post, page, …)** 和 **Home (index)** 两类。但在实际 `hexo generate` 时，post 页面的 `page` 对象没有 `title` 等属性，却有 `per_page` 等属性。

例如为 `themes\landscape\layout\_partial\header.ejs` 顶部添加这样一段代码

```
<div>title: <%= page.title %></div>
<div>per_page: <%= page.per_page %></div>
```

启动 `hexo server`，浏览 http://localhost:4000/2014/07/16/hello-world/ ，可以看到：

> title: Hello World
> per_page: undefined

但是在 `hexo generate` 生成的 `public\2014\07\16\hello-world\index.html` 文件中，查看到的却是：

> <div>title: undefined</div>
> 
> <div>per_page: 10</div>

我的 hexo 版本：

> hexo: 2.7.1
> os: Windows_NT 6.2.9200 win32 x64
> http_parser: 1.0
> node: 0.10.26
> v8: 3.14.5.9
> ares: 1.9.0-DEV
> uv: 0.10.25
> zlib: 1.2.3
> modules: 11
> openssl: 1.0.1e

印象中以前的 2.5.7 版本似乎没有这个问题。

**Comment by Xuanwo** [comment]
Fixed?

**Comment by Xuanwo** [comment]
@victorwoo, still have the problem?
