### ISSUE TITLE
hexo server正常，但是无法上传到github

### ISSUE THREAD

**Issue by liuhai19821028** [hexojs/hexo#739]
hexo server是正常的，可以在http://localhost:4000/打开，hexo generate也没有任何报错信息，但是hexo deploy时报错，无法上传。错误代码如下：
Error:spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)

**Comment by yanlee26** [comment]
2016-11-12
18:01	Unregistered VCS roots detected
		The following directories are roots of VCS repositories, but they are not registered in the Settings: 
		C:\Users\立\Desktop\blog2resharpe\themes\next
		C:\Users\立\Desktop\blog2resharpe\.deploy_git
		Add roots  Configure  Ignore

18:02	Failed to create GitHub Repository
		Can't create repository: blog2resharpe1
		Couldn't parse GitHub response

**Comment by yanlee26** [comment]
我的这是什么原因啊，传不到github上
