### ISSUE TITLE
allow theme config to be overridden

### ISSUE THREAD

**Issue by jaredly** [hexojs/hexo#756]
Currently, there's no way to override theme variables from the main site _config.yml. I'd love to have a `theme` section or something, which would enable me to keep my theme in a separate repository, and the configuration with my blog.

**Comment by arlair** [comment]
For those who find this, it was actually done in #757. Very cool.

**Comment by phicarre** [comment]
Yes, very cool and useful ...
But how can we override the layout settings in the theme_config section ?
