### ISSUE TITLE
Duplicate POST in db.json

### ISSUE THREAD

**Issue by imZack** [hexojs/hexo#772]
When I am using `hexo server` to preview my posts in windows 8, it will fire multiple file changed events (I think it's chokidar's issue paulmillr/chokidar#104) and let db.json have duplicate posts. If I use `hexo clean` to delete db.json and `hexo generate` it will be fine.

Is there any workaround or suggestions?

**Comment by szarouski** [comment]
The issue is still relevant. Steps to reproduce:
1) hexo server
2) go to the index page or archive in browser
3) edit one of the posts .md files
4) reload browser 
5) observe duplicated posts

```
hexo: 2.8.3
os: Windows_NT 6.2.9200 win32 x64
http_parser: 2.2
node: 0.11.13
v8: 3.25.30
uv: 0.11.25
zlib: 1.2.3
modules: 14
openssl: 1.0.1g
```

**Comment by victormiguez** [comment]
Same problem here. I'm using Windows 8.1.
For now I'm using Ubuntu on Vagrant to solve this issue.

**Comment by szarouski** [comment]
@tommy351 I updated chokidar to version 0.12.6 and don't see weird behaviour anymore. I tried various things and everything works just great. Can you please update package.json when you have a moment?

Thank you

**Comment by tommy351** [comment]
Chokidar in Hexo 3.0.0-beta.2 has been updated to 0.12.x. You can give it a try.

**Comment by szarouski** [comment]
Thank you for reply. Are plugins like hexo-generator-feed, hexo-generator-sitemap, hexo-renderer-ejs compatible with Hexo 3?

**Comment by tommy351** [comment]
- hexo-generator-feed: 1.0.0 is compatible with Hexo 3
- hexo-generator-sitemap: 1.0.0 is compatible with Hexo 3
- hexo-renderer-ejs: No need to update
- hexo-renderer-marked: 0.2.x is compatible with Hexo 3

More info: [Migrating from 2.x to 3.0](https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0)

**Comment by szarouski** [comment]
Thank you sir, I'm definitely going to try it out

**Comment by szarouski** [comment]
Hexo 3 doesn't feel stable yet, would it be possible for now to update hexo 2 with updated chokidar please?

**Comment by leesei** [comment]
3.0 is official.
Please open new issue if problem persists.
