### ISSUE TITLE
Is this a bug of  util.highlight ?

### ISSUE THREAD

**Issue by wuchong** [hexojs/hexo#774]
When I update hexo to 2.8+ , I find  some code block has problems.

If there are a lot of lines in the code block, it will have a bank on the top and bottom . like this:

![0805103951](https://cloud.githubusercontent.com/assets/5378924/3806499/c5b60e26-1c4d-11e4-97f0-aa9134a81872.jpg)

If we have multiline comment , it will only parse the first line.  The html like this:

```html 
<pre>
<div class="line"><span class="comment">/*</span></div>
<div class="line"> * Integer 类中的 parseInt 函数</div>
<div class="line"> * Copyright (c) 1994, 2010, Oracle and/or its affiliates. All rights reserved.</div><div class="line"> */</div>
...
</pre>
```

I find #687 wrap each line with `<div class="line"> `

Is this a bug  ? Or do I need to modify my theme css? I use  [jacman](https://github.com/wuchong/jacman) for my theme.  @tommy351

**Comment by leesei** [comment]
Fixed in 3.0.
