### ISSUE TITLE
用hexo d推送到github博客文章或者修改配置,不算contributions吗?

### ISSUE THREAD

**Issue by ClutchBear** [hexojs/hexo#782]
今天自己的文章用markdown语法修改了很多次,怎么都没有算contributions?
每次修改后都推送一遍看效果的.

**Comment by nameit** [comment]
看看你的.gitconfig里的user是不是变成其他邮箱或用户名了，也可以在.deploy_git文件夹下的.git文件夹里的config文件进行重新配置user。

**Comment by TylerYang** [comment]
我遇到了一样的问题，不过刚刚解决了。 原因是我commit 到的不是 default branch 。  可以通过设置 branches => update default branch 来解决。

**Comment by terenceYu1997** [comment]
@nameit 果真是这样,我.git文件里面有user的配置, 但是.deploy_git里面的.git文件夹的config没有设置user, 把最外层.git的user的配置复制过来,提交后就有贡献了

**Comment by YuFy1314** [comment]
![](https://user-images.githubusercontent.com/24446694/44696495-61fe0600-aaaa-11e8-9254-26f6459cdffd.png)
@terenceYu1997   是这个路径下的config么??   这个config下面没有user   只有这些:
![](https://user-images.githubusercontent.com/24446694/44696536-8d80f080-aaaa-11e8-8713-db30e25d5a09.png)

**Comment by YuFy1314** [comment]
我的项目结构是这样的, 关于提交之后不能显示到contribution的问题你们解决了么?
![](https://user-images.githubusercontent.com/24446694/44696616-e6508900-aaaa-11e8-87c3-7caf3337a981.png)

**Comment by BinTaoMa** [comment]
> 我的项目结构是这样的, 关于提交之后不能显示到contribution的问题你们解决了么? ![](https://user-images.githubusercontent.com/24446694/44696616-e6508900-aaaa-11e8-87c3-7caf3337a981.png)

一点没有

**Comment by uiolee** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

This has nothing to do with hexo.

The most likely reason is that there is a delay in contributions update, the account name and email are incorrectly set in git, or the commit is not pushed to the default branch.

If anyone still has questions, I recommend asking Github, or starting a topic in [discussions](https://github.com/orgs/hexojs/discussions)
