### ISSUE TITLE
代码块前后意外加了很多空行

### ISSUE THREAD

**Issue by hongbinzuo** [hexojs/hexo#792]
我的代码是正常的Java代码，但是写在Markdown文本里，被hexo解释成html后就在代码块首尾意外加了好多空行，如http://hongbinzuo.github.io/2014/08/13/Manacher/ 所示。

hexo环境：
hexo: 2.8.2
os: Linux 3.13.0-32-generic linux x64
http_parser: 1.0
node: 0.10.25
v8: 3.14.5.9
ares: 1.10.0
uv: 0.10.23
zlib: 1.2.8
modules: 11
openssl: 1.0.1f

**Comment by leesei** [comment]
Fixed in 3.0.
