### ISSUE TITLE
post和page permalink不一样，page不想包含index.html

### ISSUE THREAD

**Issue by joysboy** [hexojs/hexo#799]
我的post permalink类似http://xfeng.me/switch-to-hexo/ ，但是我的page的permalink却是这样http://xfeng.me/about/index.html

因为使用多说评论服务，ds-threads-key我设置为post.path，之前从wp迁移过来，原来的key是post.id，但是hexo没法自动递增生成id，所以我吧url中path作为key，对应hexo的post.path，但是发现page生成的post.path值为about/index.html，多了一个index.html，这样就没法和我多说数据里的key对应上，没法正常显示原来page的评论

我的page文件是source/about/index.md ，如果改成source/about.md，生成的URL是http://xfeng.me/about.html ，这个也不是我想要的

如何生成page的URL里不包含index.html，例如http://xfeng.me/about/

另外post.slug这个变量对于page是未定义的吗

**Comment by szarouski** [comment]
:+1: (lets continue discussion in english please). I also would like to know if there is or will be a standard way to get page permalink without index.html (posts don't have it)?

**Comment by Xuanwo** [comment]
不要用page.path啊，可以用page.source

**Comment by szarouski** [comment]
page.source is quite different for home page, posts, pages, etc...
```
undefined
_posts/asynchronous-programming-with-ES6-generators-promises-and-npm-co.md
projects/index.md
```

What I would like to have instead is just 
/
/asynchronous-programming-with-ES6-generators-promises-and-npm-co/
/projects/

Currently I'm using `page.permalink.replace(/index\.html$/, '')`, but I'm not certain that is a right way.

**Comment by Xuanwo** [comment]
@leesei It looks like fixed, we commit an pr that remove all the `index.html`.
