### ISSUE TITLE
本地预览与线上结果不一样问题

### ISSUE THREAD

**Issue by tudouya** [hexojs/hexo#806]
我在本地修改了博客主题的某些地方，在本地预览的时候都是可以的，但是更新到github以后就不行了，主要有两个地方的问题：
1.我修改了收藏夹图标，替换掉了主题原有的收藏夹图标，本地预览正常，github上的文件目录显示的也是我更改后的图标，但是在网页标题栏上显示的还是原来的。
2.更改了某个链接，让链接在新窗口打开，本地也是行的，但是线上就不行，查看了线上的源码，有"_blank"属性，但是不能在新窗口打开。
＝＝＝＝
我在本地执行了hexo clean,也删除了db.json但是都不行，求助～～

**Comment by phping1** [comment]
@tudouya ,我也遇到同样的问题。解决办法：
执行 hexo clean 后再部署就好了。就是缓存问题。

**Comment by youngseaz** [comment]
真的是缓存问题，一用ctrl+f5解决，谢谢

**Comment by dengjianf** [comment]
可以的！多谢！ctr+F5

**Comment by developNote** [comment]
### **ctrl+f5**
