### ISSUE TITLE
Links for archives are not ended with `/`, which cause 404 in Pow

### ISSUE THREAD

**Issue by timnew** [hexojs/hexo#807]
Links generated by `Hexo.helper.list_archives` are not ended with `/`. `Pow` only finds `/path/index.html` when url is `/path/`. `/path` is treated as file by `Pow`.

**Comment by Xuanwo** [comment]
@timnew Had this merged into the master?

**Comment by Xuanwo** [comment]
ref: https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/list_archives.js#L56

Fixed
