### ISSUE TITLE
Space cause line-break in Tag Cloud

### ISSUE THREAD

**Issue by timnew** [hexojs/hexo#810]
![Line-break in tag cloud](https://cloud.githubusercontent.com/assets/1287238/4019649/7744848a-2a7f-11e4-9781-871fb606d005.png)
`Bit Slice` displays correctly is because I manually escaped the space.
Others, such as `Continues Integration` is broken into separate lines.

**Comment by leesei** [comment]
Please close this issue as your plugin can fix it.
