### ISSUE TITLE
Tag cloud should limit the tags in fequency order instead of display order

### ISSUE THREAD

**Issue by timnew** [hexojs/hexo#811]
When `amount` is set to tag cloud helper, the tags more than the `amount` won't be displayed.
But the issue is that the limit logic happens in display order.

But the common requirement is "As a blogger, I want to display the most used 40 tags in alphabetic order", which is impossible to achieve with current `tagcloud` helper.

**Comment by leesei** [comment]
@tommy351 what do you think if we change the default setting of `tagcloud` helper?

**Comment by leesei** [comment]
relates #507
