### ISSUE TITLE
partial不支持向上级目录查找，绝对路径也不可以使用

### ISSUE THREAD

**Issue by dnxbf321** [hexojs/hexo#819]
|- A
|----a.ejs
|-B
|----b.ejs

当前在a.ejs处，partial('../B/b')不能获取b.ejs

**Comment by Xuanwo** [comment]
Fiexed？

**Comment by Xuanwo** [comment]
@tommy351  Had this fixed?

**Comment by stevenjoezhang** [comment]
Fixed in Hexo v3.x

**Comment by YoshinoriN** [comment]
@stevenjoezhang 
Thanks :)
As you say this issue already fixed.
