### ISSUE TITLE
在博客中添加项目主页后显示404

### ISSUE THREAD

**Issue by zhangolve** [hexojs/hexo#820]
我看到有同样搭建在github上的这个博客http://hukai.me/     ，在这个博客里面有一个http://hukai.me/android-training-course-in-chinese/index.html    网页，而根据我的了解http://hukai.me/android-training-course-in-chinese/index.html     这个网页的生成也是通过gh-pages，项目pages，于是我试着fork了一个2048的项目到自己的github上，打开 http://zhangolve.github.io/2048   .之后跳转到我的博客上（http:hktkdy.com   ）出现404页面，但是在那个项目的 options中显示这个项目主页已经published，请问这是怎么回事，怎么解决？

![](http://hktkdy.qiniudn.com/issuehexo.png)
我的github：https://github.com/zhangolve  其中的2048项目是我fork的其他人的项目。

**Comment by mindcont** [comment]
1、youname.github.io下新建CNAME文件，写入类似blog.youdomin.com  注意UTF-8格式
2、配置dns， 记录类型 CNAME ,主机记录 blog ，记录值 youname.github.io
