### ISSUE TITLE
Enable muti-language support

### ISSUE THREAD

**Issue by csarron** [hexojs/hexo#821]
I wonder if I can build a multi-language featured website using Hexo, is there anyone considering this issue?

**Comment by johnnyshields** [comment]
+1 for adding I18n support in the pages, not just the themes. Ideally I18n files should be loaded from both `<project root>/languages/` and `/themes/xxx/languages`

**Comment by AdrieanKhisbe** [comment]
shouldn't be close?
Seems it has been implemnted :)

**Comment by Xuanwo** [comment]
Yes, I think it finished.
