### ISSUE TITLE
Best way to get most popular posts or most comments posts?

### ISSUE THREAD

**Issue by andrewboni** [hexojs/hexo#835]
I'm wondering what the best way to get a list of, say, the 10 most popular posts, either by views or by comments, so that I can add a small sidebar widget. I know that since this is static, it's a little tricky, but has anyone done this?

Disqus outlines [a way to get comments for a post](https://help.disqus.com/customer/portal/articles/1131783-tutorial-get-comment-counts-with-the-api), but it doesn't seem ideal for a blog with hundreds of posts.

Is there a better way? Bonus points if it's all client side JS as opposed to generating it during a `hexo generate`. Thanks!

**Comment by leesei** [comment]
Hexo, as a static site generator, does not track those measures.
They could be implemented by plugin and themes though.

**Comment by tea3** [comment]
@andrewboni @jr0cket @revelt @leesei 
I published plugin referring to here.  Please use it if you want.
https://github.com/tea3/hexo-related-popular-posts

**Comment by revelt** [comment]
@tea3 Awesome! 🦄 🦄 🦄 🍻 🍻 🍻 🍻
