### ISSUE TITLE
multi-lang site building

### ISSUE THREAD

**Issue by hexindent** [hexojs/hexo#836]
hexo 2.8 includes the multi-language support and I find it useful to separate my posts. But it doesn't meet my needs to build a multi-lang site because the `--lang` argument covers no page.
I want to set up a site in this order

    /
     |-en/
     |       |-blog/
     |       |        |-post1.md
     |       |        |-post2.md
     |       |        |-...
     |       |docs/
     |       |        |-install.html
     |       |        |-conf.html
     |       |        |-...
     |       |about/
     |       |        |-index.html
     |-zh/
     |       |-blog/
     |       |        |-thread1.md
     |       |        |-thread2.md
     |       |        |-...
     |       |-wiki/
     |       |        |-setup.html
     |       |        |-calibrate.html
     |       |        |-...
     |       |about/
     |       |        |-index.html

Can I achieve this with the latest hexo? I tried but it didn't work:

    $ hexo n page "about" --lang en
    [info] File created at ~/site/source/about/index.md

Thanks!

**Comment by nickbuddendotcom** [comment]
Hey guys what's the status on multi-lingual pages? Tried `hexo new page 'Page Name' --lang en` today and didn't work

**Comment by Xuanwo** [comment]
Closed for added.
