### ISSUE TITLE
How to run Hexo at the environment with existing Node JS app on a subdomain?

### ISSUE THREAD

**Issue by dogusev** [hexojs/hexo#839]
Hi!
How can I ran Hexo server and another node js app on the same environment, also need to set path for hexo blog like blog.mysitename.com ?

**Comment by georgeedwards** [comment]
@leesei Thanks for this, what would a `app.use(vhost('blog.gisonrg.me', require('./blog.js')));` line look like? Where should you point your vhost to in a hexo setup?

**Comment by TonyRenHK** [comment]
any example? I have meet the same case @leesei

**Comment by leesei** [comment]
Creates static content with `hexo generate`.
Configure it with a virtual host of whatever HTTP server you're using.
