### ISSUE TITLE
用hexo server后浏览器只显示如下信息

### ISSUE THREAD

**Issue by PegasusWang** [hexojs/hexo#842]
<%- partial('_partial/head') %>
<%- partial('_partial/header', null, {cache: !config.relative_link}) %>
<%- body %>
<% if (theme.sidebar && theme.sidebar !== 'bottom'){ %> <%- partial('_partial/sidebar', null, {cache: !config.relative_link}) %> <% } %>
<%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
<%- partial('_partial/mobile-nav', null, {cache: !config.relative_link}) %> <%- partial('_partial/after-footer') %>

**Comment by WuHuaJi0** [comment]
@Xuanwo 按照你说的，确实解决了问题。能说下这是什么原因所致吗？

**Comment by Xuanwo** [comment]
因为没有安装好hexo的渲染插件~

**Comment by andyuan1000** [comment]
都没有说到点子上：
这说明服务器解析错误，解决方案：


npm install hexo-renderer-ejs --save
npm install hexo-renderer-stylus --save
npm install hexo-renderer-marked --save
