### ISSUE TITLE
hexo deploy failed with rsync type! how to config the _config.yml?

### ISSUE THREAD

**Issue by yinone** [hexojs/hexo#844]
this is my deploy config

    deploy:
        type: rsync
        host: varyone.com
        user: yinone
        root:  /public_html/

this is the node error:

    Error: spawn ENOENT
       at errnoException (child_process.js:998:11)
       at Process.ChildProcess._handle.onexit (child_process.js:789:34)
       [error] 17:10:38.257 Deploy failed: rsync (code -1)

please tell me the solution,thanks

**Comment by leesei** [comment]
Please try the new [hexojs/hexo-deployer-rsync](https://github.com/hexojs/hexo-deployer-rsync) plugin and report if issue persists.

**Comment by wanzhiyu** [comment]
请问最后如何解决的？
