### ISSUE TITLE
Does hexo support markdown completely?

### ISSUE THREAD

**Issue by YumeMichi** [hexojs/hexo#845]
Does hexo support markdown completely? I meet some troubles about markdown, they work well on MDwiki and GitHub, but hexo not!

Watch here
MDwiki: http://dsy.im/#!mdwiki-tourial.md
Hexo: http://dsylcy.net/posts/mdwiki-tourials/
src: https://github.com/idsy/mdwiki-idsy/blob/gh-pages/mdwiki-tourial.md

**Comment by kimown** [comment]
你也发现了这个问题吗，我现在是发现hexo里面无法编写流程图。你是markdown什么语法不支持啊？

**Comment by Xuanwo** [comment]
因为Marked不支持。

**Comment by leesei** [comment]
流程图 本來就不是markdown 一部份
現在你可以用[plugin](https://hexo.io/plugins/) 改用marked 以外的其他renderer 和支持plantuml.
