### ISSUE TITLE
重复生成

### ISSUE THREAD

**Issue by QianChenglong** [hexojs/hexo#847]
当开启server后，手动添加markdown文件到_post目录下，会重复生成。

控制台截图：
![2014-09-19_102819](https://cloud.githubusercontent.com/assets/1881126/4329977/af354912-3fa4-11e4-9505-91492a72d88b.png)

Web截图：
![2014-09-19_102934](https://cloud.githubusercontent.com/assets/1881126/4329989/dbfcd9e2-3fa4-11e4-9b6c-d146272b9c53.png)

**Comment by Xuanwo** [comment]
你好，最新的版本还有这个问题吗？
