### ISSUE TITLE
系统重装，文章丢失，还能恢复么？

### ISSUE THREAD

**Issue by blue7wings** [hexojs/hexo#860]
还能从github上恢复文章么？如果不能恢复，重新搭建，那么以前的文章，样式都会被覆盖么？谢谢各位解答一下。。

**Comment by Xuanwo** [comment]
@blue7wings 只要md文档还在，使用原来的主题，你的博客就会回来了~

**Comment by s40523119** [comment]
假設遺失部分幾個md文件，還可以找回嗎?  線上部落格已經發布。
