### ISSUE TITLE
how to ref the asset in the post when post_asset_folder: false 

### ISSUE THREAD

**Issue by aulphar** [hexojs/hexo#863]
how to ref the asset in the post when set `post_asset_folder: false`?
say i run `hexo new MyPost1` then ` source\_posts\MyPost1` is created. i put `test.jpg` under the folder but how do i reference it in the MyPost1.md? `![Image1](test.jpg "Image1 title")` could work when showing the post but won't work on the home page

**Comment by Xuanwo** [comment]
Do this by ![Image1](/year/month/day/MyPost1/test.jpg)

**Comment by leesei** [comment]
I think this is better:
https://hexo.io/docs/asset-folders.html
