### ISSUE TITLE
how to generate tags/index.html

### ISSUE THREAD

**Issue by elaijuh** [hexojs/hexo#864]
As I see some themes has `tags` as navigation pill and link to `/tags/index.html`. Default generator will not render the tags.ejs to html, how can I achieve that?

**Comment by esttorhe** [comment]
@elaijuh did you find any fixes for this?
I'm experiencing the same issue

**Comment by Xuanwo** [comment]
this depand on your themes

**Comment by esttorhe** [comment]
@Xuanwo care to be a little more specific?

I would happily submit a `PR` to the theme I'm using in order to correctly support the `tags` but I have no idea why is not being generated even though `tags.ejs` is there

**Comment by Xuanwo** [comment]
https://github.com/Xuanwo/xuanwo.github.io/tree/blog/source/tags

looks like this

**Comment by esttorhe** [comment]
Thanks @Xuanwo; I actually looked at some themes and ended up copying and modifying the `tags.ejs` to match my theme with the «correct» stuff and not its working (the tags).

Will take a look at your commit and see how to better improve my hack :)

Thanks again :bow:

**Comment by Xuanwo** [comment]
Nothing special, enjoy using hexo~
