### ISSUE TITLE
Arguments to path.join must be strings (deploy to OpenShift)

### ISSUE THREAD

**Issue by aixnr** [hexojs/hexo#870]
My installation steps:

* Create DIY cartridge on the OpenShift
* Clone the cartridge to local
* `hexo init` to the folder
* `cd` into that folder, `npm install`
* `nano _config.yml` to edit the deploy mode

```
deploy:
  type: openshift
  remote: origin
  branch: master
```

* `.gitignore` contained the following lines: I deleted it

```
.DS_Store
Thumbs.db
db.json
debug.log
node_modules/
public/
.deploy/
```

* `hexo generate` went fine, however `hexo deploy` returned the following error.

```js
[info] Start deploying: openshift
[error] TypeError: Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.module.exports [as openshift] (/Users/anarchy/.nvm/v0.10.32/lib/node_modules/hexo/lib/plugins/deployer/openshift.js:47:22)
    at /Users/anarchy/.nvm/v0.10.32/lib/node_modules/hexo/lib/plugins/console/deploy.js:76:22
    at iterate (/Users/anarchy/.nvm/v0.10.32/lib/node_modules/hexo/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/anarchy/.nvm/v0.10.32/lib/node_modules/hexo/node_modules/async/lib/async.js:165:9)
    at /Users/anarchy/.nvm/v0.10.32/lib/node_modules/hexo/lib/plugins/console/deploy.js:66:11
    at /Users/anarchy/.nvm/v0.10.32/lib/node_modules/hexo/lib/plugins/console/deploy.js:32:27
    at Object.cb [as oncomplete] (evalmachine.<anonymous>:168:19)
```

I have a very strong feeling that I did wrong somewhere else. Btw, I didn't empty the original contents of the DIY cartridge (it had stuffs like diy folder, misc folder, and README.md).

**Comment by tommyku** [comment]
I solved the problem by changing the line in `hexo/lib/plugins/deployer/openshift.js`
```
file.copyFile(blogDir+'/testrubyserver.rb', publicDir);
```
to
```
file.copyFile(blogDir+'/testrubyserver.rb', publicDir+'/testrubyserver.rb');
```
Wanted to make a pull request, but can't find `deployer/openshift.js` from this repo...

**Comment by tommy351** [comment]
@tommyku Built-in deployer plugins will be separated from the main module in Hexo 3.0. Heroku and OpenShift deployer are not done yet.

- [hexo-deployer-git](https://github.com/hexojs/hexo-deployer-git)
- [hexo-deployer-heroku](https://github.com/hexojs/hexo-deployer-heroku)
- [hexo-deployer-openshift](https://github.com/hexojs/hexo-deployer-openshift)
- [hexo-deployer-rsync](https://github.com/hexojs/hexo-deployer-rsync)

**Comment by Alex1990** [comment]
*Just record this error I came cross.*

After changing the repository name on github, I forgot to update the `repo` url in `_config.yml`. So the current `repo`  url is inexistent in actually. Then, executing `hexo generate` or `hexo deploy` command will result the below error message:
```
chaoalex:myblog$ hexo d
[info] Start deploying: git
[error] TypeError: Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:471:13)
    at Object.module.exports [as git] (/Users/chaoalex/w/myblog/node_modules/hexo-deployer-git/lib/deployer.js:18:26)
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:76:22
    at iterate (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:165:9)
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:66:11
    at /usr/local/lib/node_modules/hexo/lib/plugins/console/deploy.js:32:27
    at FSReqWrap.cb [as oncomplete] (evalmachine.<anonymous>:228:19)
```

**Comment by leesei** [comment]
This issue was moved to hexojs/hexo-deployer-openshift#1
