### ISSUE TITLE
bug (?) in post_asset.js

### ISSUE THREAD

**Issue by jemos** [hexojs/hexo#872]
Hi,

It seems `lib/plugins/processor/post_asset.js` is trying to use `path` before validating if its defined (line 31). This can cause a crash when launching hexo. It was triggered when I tried to use hexo-tag-asset-res from timnew. Moving that line into the conditional (which also looks more correct) seems to fix the problem.

	diff --git a/lib/plugins/processor/post_asset.js b/lib/plugins/processor/post_asset.js
	index f36b491..c2fb98b 100644
	--- a/lib/plugins/processor/post_asset.js
	+++ b/lib/plugins/processor/post_asset.js
	@@ -28,9 +28,9 @@ module.exports = function(data, callback){
	 
	   if (doc){
	     post = Post.get(doc.post_id);
	-    postPath = post.path;
	 
	     if (post){
	+      postPath = post.path;
	       doc.update({
	         path: url.resolve(postPath, data.source.substring(post.asset_dir.length)),
	         modified: data.type === 'update',
	@@ -68,4 +68,4 @@ module.exports = function(data, callback){
	       callback();
	     });
	   }
	-};
	\ No newline at end of file
	+};

Considering it's not on purpose, I'm not sure if it's something already fixed.. Hope it helps something anyway.

Regards,
Jean Mousinho

**Comment by leesei** [comment]
The code is obsolete.
