### ISSUE TITLE
bug: 刷新頁面後 Render 出來的內容跟原文相異

### ISSUE THREAD

**Issue by joyceim** [hexojs/hexo#874]
**博客已經停用一切插件和換回預設主題作測試**

render 後進入本地環境之後本來跟原文一樣都是標題在前面，不過刷新頁面之後就多了一張圖在標題上面。（下圖紅圈示）

![](https://cloud.githubusercontent.com/assets/2826248/4518209/18c461d6-4c7c-11e4-8d84-ebd9fb7ad64e.jpg)

**Comment by Xuanwo** [comment]
@tommy351 This already fixed ?
Due to this line https://github.com/hexojs/hexo-theme-landscape/blob/master/layout/_partial/post/gallery.ejs#L1 , if not fixed , I will make a pr to do this.

**Comment by NoahDragon** [comment]
No one report such issue since then.
