### ISSUE TITLE
关于更新URL变化问题

### ISSUE THREAD

**Issue by waiducom** [hexojs/hexo#876]
您好，每次执行hexo g 生成文章时，文章的ID是变化的，怎样可以保留第一次生成时的URL ID链接？

**Comment by tangkunyin** [comment]
这是个问题，得想办法解决掉

**Comment by Xuanwo** [comment]
为啥是个问题？。。

**Comment by tangkunyin** [comment]
因为文章id总是变化，如果网友保存了网址。就等于没保存。不过我还是完美解决了，哈哈。你可以去我网站看看

**Comment by Xuanwo** [comment]
哈？不是有permelink么。
