### ISSUE TITLE
Error:  npm install

### ISSUE THREAD

**Issue by sandylaw** [hexojs/hexo#878]
System: elementaryos 0.3 x64 

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/home/sandy/.nvm/v0.10.32/bin/node',
1 verbose cli   '/home/sandy/.nvm/v0.10.32/bin/npm',
1 verbose cli   'install' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/home/sandy/hexo',
5 verbose install   [ 'hexo-renderer-ejs',
5 verbose install     'hexo-renderer-stylus',
5 verbose install     'hexo-renderer-marked' ] ]
6 info preinstall hexo-site@
7 verbose readDependencies using package.json deps
8 verbose cache add [ 'hexo-renderer-ejs@*', null ]
9 verbose cache add name=undefined spec="hexo-renderer-ejs@*" args=["hexo-renderer-ejs@*",null]
10 verbose parsed url { protocol: null,
10 verbose parsed url   slashes: null,
10 verbose parsed url   auth: null,
10 verbose parsed url   host: null,
10 verbose parsed url   port: null,
10 verbose parsed url   hostname: null,
10 verbose parsed url   hash: null,
10 verbose parsed url   search: null,
10 verbose parsed url   query: null,
10 verbose parsed url   pathname: 'hexo-renderer-ejs@*',
10 verbose parsed url   path: 'hexo-renderer-ejs@*',
10 verbose parsed url   href: 'hexo-renderer-ejs@*' }
11 verbose cache add [ 'hexo-renderer-stylus@*', null ]
12 verbose cache add name=undefined spec="hexo-renderer-stylus@*" args=["hexo-renderer-stylus@*",null]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: 'hexo-renderer-stylus@*',
13 verbose parsed url   path: 'hexo-renderer-stylus@*',
13 verbose parsed url   href: 'hexo-renderer-stylus@*' }
14 verbose cache add [ 'hexo-renderer-marked@*', null ]
15 verbose cache add name=undefined spec="hexo-renderer-marked@*" args=["hexo-renderer-marked@*",null]
16 verbose parsed url { protocol: null,
16 verbose parsed url   slashes: null,
16 verbose parsed url   auth: null,
16 verbose parsed url   host: null,
16 verbose parsed url   port: null,
16 verbose parsed url   hostname: null,
16 verbose parsed url   hash: null,
16 verbose parsed url   search: null,
16 verbose parsed url   query: null,
16 verbose parsed url   pathname: 'hexo-renderer-marked@*',
16 verbose parsed url   path: 'hexo-renderer-marked@*',
16 verbose parsed url   href: 'hexo-renderer-marked@*' }
17 verbose cache add name="hexo-renderer-ejs" spec="*" args=["hexo-renderer-ejs","*"]
18 verbose parsed url { protocol: null,
18 verbose parsed url   slashes: null,
18 verbose parsed url   auth: null,
18 verbose parsed url   host: null,
18 verbose parsed url   port: null,
18 verbose parsed url   hostname: null,
18 verbose parsed url   hash: null,
18 verbose parsed url   search: null,
18 verbose parsed url   query: null,
18 verbose parsed url   pathname: '*',
18 verbose parsed url   path: '*',
18 verbose parsed url   href: '*' }
19 verbose addNamed [ 'hexo-renderer-ejs', '*' ]
20 verbose addNamed [ null, '*' ]
21 verbose cache add name="hexo-renderer-stylus" spec="*" args=["hexo-renderer-stylus","*"]
22 verbose parsed url { protocol: null,
22 verbose parsed url   slashes: null,
22 verbose parsed url   auth: null,
22 verbose parsed url   host: null,
22 verbose parsed url   port: null,
22 verbose parsed url   hostname: null,
22 verbose parsed url   hash: null,
22 verbose parsed url   search: null,
22 verbose parsed url   query: null,
22 verbose parsed url   pathname: '*',
22 verbose parsed url   path: '*',
22 verbose parsed url   href: '*' }
23 verbose addNamed [ 'hexo-renderer-stylus', '*' ]
24 verbose addNamed [ null, '*' ]
25 verbose cache add name="hexo-renderer-marked" spec="*" args=["hexo-renderer-marked","*"]
26 verbose parsed url { protocol: null,
26 verbose parsed url   slashes: null,
26 verbose parsed url   auth: null,
26 verbose parsed url   host: null,
26 verbose parsed url   port: null,
26 verbose parsed url   hostname: null,
26 verbose parsed url   hash: null,
26 verbose parsed url   search: null,
26 verbose parsed url   query: null,
26 verbose parsed url   pathname: '*',
26 verbose parsed url   path: '*',
26 verbose parsed url   href: '*' }
27 verbose addNamed [ 'hexo-renderer-marked', '*' ]
28 verbose addNamed [ null, '*' ]
29 silly lockFile b3653f8d-hexo-renderer-ejs hexo-renderer-ejs@*
30 verbose lock hexo-renderer-ejs@* /home/sandy/.npm/b3653f8d-hexo-renderer-ejs.lock
31 silly lockFile c34a33e1-hexo-renderer-stylus hexo-renderer-stylus@*
32 verbose lock hexo-renderer-stylus@* /home/sandy/.npm/c34a33e1-hexo-renderer-stylus.lock
33 silly lockFile 377509ff-hexo-renderer-marked hexo-renderer-marked@*
34 verbose lock hexo-renderer-marked@* /home/sandy/.npm/377509ff-hexo-renderer-marked.lock
35 silly addNameRange { name: 'hexo-renderer-ejs', range: '*', hasData: false }
36 silly addNameRange { name: 'hexo-renderer-stylus', range: '*', hasData: false }
37 silly addNameRange { name: 'hexo-renderer-marked', range: '*', hasData: false }
38 verbose request where is /hexo-renderer-ejs
39 verbose request registry https://registry.npmjs.org/
40 verbose request id 16d7bacadd8c9d19
41 verbose url raw /hexo-renderer-ejs
42 verbose url resolving [ 'https://registry.npmjs.org/', './hexo-renderer-ejs' ]
43 verbose url resolved https://registry.npmjs.org/hexo-renderer-ejs
44 verbose request where is https://registry.npmjs.org/hexo-renderer-ejs
45 info trying registry request attempt 1 at 19:54:30
46 http GET https://registry.npmjs.org/hexo-renderer-ejs
47 verbose request where is /hexo-renderer-stylus
48 verbose request registry https://registry.npmjs.org/
49 verbose url raw /hexo-renderer-stylus
50 verbose url resolving [ 'https://registry.npmjs.org/', './hexo-renderer-stylus' ]
51 verbose url resolved https://registry.npmjs.org/hexo-renderer-stylus
52 verbose request where is https://registry.npmjs.org/hexo-renderer-stylus
53 info trying registry request attempt 1 at 19:54:30
54 http GET https://registry.npmjs.org/hexo-renderer-stylus
55 verbose request where is /hexo-renderer-marked
56 verbose request registry https://registry.npmjs.org/
57 verbose url raw /hexo-renderer-marked
58 verbose url resolving [ 'https://registry.npmjs.org/', './hexo-renderer-marked' ]
59 verbose url resolved https://registry.npmjs.org/hexo-renderer-marked
60 verbose request where is https://registry.npmjs.org/hexo-renderer-marked
61 info trying registry request attempt 1 at 19:54:30
62 http GET https://registry.npmjs.org/hexo-renderer-marked
63 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
64 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
65 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
66 info trying registry request attempt 2 at 19:54:40
67 http GET https://registry.npmjs.org/hexo-renderer-ejs
68 info trying registry request attempt 2 at 19:54:40
69 http GET https://registry.npmjs.org/hexo-renderer-marked
70 info trying registry request attempt 2 at 19:54:40
71 http GET https://registry.npmjs.org/hexo-renderer-stylus
72 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
73 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
74 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
75 info trying registry request attempt 3 at 19:55:40
76 http GET https://registry.npmjs.org/hexo-renderer-ejs
77 info trying registry request attempt 3 at 19:55:40
78 http GET https://registry.npmjs.org/hexo-renderer-marked
79 info trying registry request attempt 3 at 19:55:40
80 http GET https://registry.npmjs.org/hexo-renderer-stylus
81 silly lockFile b3653f8d-hexo-renderer-ejs hexo-renderer-ejs@*
82 silly lockFile b3653f8d-hexo-renderer-ejs hexo-renderer-ejs@*
83 silly lockFile 377509ff-hexo-renderer-marked hexo-renderer-marked@*
84 silly lockFile 377509ff-hexo-renderer-marked hexo-renderer-marked@*
85 silly lockFile c34a33e1-hexo-renderer-stylus hexo-renderer-stylus@*
86 silly lockFile c34a33e1-hexo-renderer-stylus hexo-renderer-stylus@*
87 error Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
87 error     at SecurePair.<anonymous> (tls.js:1367:32)
87 error     at SecurePair.emit (events.js:92:17)
87 error     at SecurePair.maybeInitFinished (tls.js:979:10)
87 error     at CleartextStream.read [as _read] (tls.js:471:13)
87 error     at CleartextStream.Readable.read (_stream_readable.js:340:10)
87 error     at EncryptedStream.write [as _write] (tls.js:368:25)
87 error     at doWrite (_stream_writable.js:225:10)
87 error     at writeOrBuffer (_stream_writable.js:215:5)
87 error     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
87 error     at write (_stream_readable.js:601:24)
87 error     at flow (_stream_readable.js:610:7)
87 error     at Socket.pipeOnReadable (_stream_readable.js:642:5)
88 error If you need help, you may report this *entire* log,
88 error including the npm and node versions, at:
88 error     <http://github.com/npm/npm/issues>
89 error System Linux 3.13.0-35-generic
90 error command "/home/sandy/.nvm/v0.10.32/bin/node" "/home/sandy/.nvm/v0.10.32/bin/npm" "install"
91 error cwd /home/sandy/hexo
92 error node -v v0.10.32
93 error npm -v 1.4.28
94 verbose exit [ 1, true ]

**Comment by Xuanwo** [comment]
Hello, do you still have the problem?

**Comment by sandylaw** [comment]
Not at all.
Now I use archlinux.
