### ISSUE TITLE
Static Images

### ISSUE THREAD

**Issue by rootools** [hexojs/hexo#88]
Hi. I have a problem with static image. E.g. I write new post and i want to add image to my post. how can I do this? Then I upload it to the githab pages

**Comment by huangteng** [comment]
I have a problem, I can only see the image in the hexo main page, but when I clicked into the post, I cannot see it any more, someone has the same problem ?
Here is my blog:
huangteng.github.io

**Comment by richardwei2008** [comment]
Please refer to http://stackoverflow.com/questions/30861278/hexo-change-folder-structure-when-generate-static-files

Set post_asset_folder: true in _config.yml
Create new post with hexo new post "Some New Post"
Place image in source/_posts/Some-New-Post/, e.g. source/_posts/Some-New-Post/cat.jpg
Display image in post with ![](cat.jpg)

Hope this help @rootools @huangteng

**Comment by enter-rebel** [comment]
Sadly in my case, I can't use the markdown syntax, my use is on a theme.
