### ISSUE TITLE
permalinks :title is file path

### ISSUE THREAD

**Issue by m80126colin** [hexojs/hexo#881]
I found that `:title`, a variable of permalinks, is NOT only a filename but also a file path under `source/` if you categories your markdown files into several directories.

**Comment by Xuanwo** [comment]
What do you mean?

**Comment by nt3rp** [comment]
I *might* be having a similar problem as @m80126colin (though I am not entirely sure).

One might have settings as follows:

```yml
new_post_name: :year-:month-:day-:title.md # File name of new post
permalink: :year/:month/:day/:title/
```

In this case, new files are created as expected (e.g. `hexo new "Hello World"` creates `2015-01-01-hello-world.md`)

However, what is not expected (or rather, isn't clear how to change the configuration to support this) is that the permalink will not be correct.

Expected:
```
<root>/2015/01/01/hello-world
```

Actual:
```
<root>/2015/01/01/2015-01-01-hello-world
```

I had a blog previously running on Hexo 2.x that worked with this setup, but it seems something has change in Hexo 3.

**Comment by leesei** [comment]
@nt3rp @tommy351 I think we need to update the doc for these config and variables in `Post`

As a side question, how `permalink` is resolved from all these?
Several [`permalink`  related](https://github.com/hexojs/hexo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+permalink) issues could be resolved once we get these cleared.
