### ISSUE TITLE
Accessing helpers, page, config from helper.ejs

### ISSUE THREAD

**Issue by gg8345** [hexojs/hexo#882]
Hi !

I'm trying to get a helper to work by adding `<%- myHelper() -%>` in 'post.ejs', but unfortunately when interpreting the file, the interpreter can't find the definition of 'page', 'config' or helper functions like 'url_for()'.. This is probably not the right way but if somebody has a better idea of how to do the same thing I would be very grateful :).

```javascript
  var ejs = require('ejs')
    , path = require('path')
    , file = hexo.util.file2;

  var tmplSrc = path.join(__dirname, 'myHelper.ejs'),
    tmpl = ejs.compile(file.readFileSync(tmplSrc, 'utf8'));

  hexo.extend.helper.register('myHelper', function() {
    return tmpl();
  })

}).call(this);
```

**Comment by leesei** [comment]
Refer to [this PR](https://github.com/hexojs/hexo/pull/1391) for steps to add a helper.
Reopen if you have any issue.
