### ISSUE TITLE
generate后首页生成的摘要会重复出现很多次

### ISSUE THREAD

**Issue by classicemi** [hexojs/hexo#883]
开着`hexo s`写博客，因为会边写边保存，生成的index页中正在写的这篇博客的摘要会重复出现很多次，主题为light，默认状态，没有经过任何改动。

生成主页截图：
![20141017171151](https://cloud.githubusercontent.com/assets/3982491/4676670/cc893c54-55dd-11e4-9e73-dbd6a2fc82d1.png)

**Comment by Xuanwo** [comment]
`hexo clean`然后再`hexo g`之后的内容有问题么？
