### ISSUE TITLE
How can I disable layout for index.ejs?

### ISSUE THREAD

**Issue by myst729** [hexojs/hexo#887]
I have `layout.ejs` for every sub page/post. But my homepage have a very different design, how can I render `index.ejs` without being wrapped by `layout.ejs`? In other words, can I disable layout for "root" page?

**Comment by asvdw** [comment]
I'm looking for the same feature. Any idea ?

**Comment by leesei** [comment]
By "root" do you mean the landing/index page?
If so, refer to #1491, add `index.md` and remove `hexo-generator-index`.

**Comment by erutan** [comment]
necro, but it's still open so /shrug

the best way to do this would just be to create a new layout, and call that from the front-matter.  via https://hexo.io/docs/templates.html it looks like you either nest layouts inside of layout.ejs or have none at all? if so it'd be nice to just have the jekyll behaviour where you can have default layouts (per site or collection/type) amd modifying `layout` in the front-matter overrides that and just starts from the specific layout.

> By default, the `layout` template is used by all other templates. You can specify additional layouts in the front-matter or set it to false to disable it. It’s even possible to build a complex nested structure by including more layout templates in your top layout.

**Comment by myst729** [comment]
@erutan Yep, that's how I have done :laughing:
