### ISSUE TITLE
通过公网IP+端口号访问hexo失败

### ISSUE THREAD

**Issue by xiaowuzhu** [hexojs/hexo#889]
各位，我在腾讯云上配置好hexo以后,用localhost:4000可以访问，但是通过公网IP+端口号访问失败，这是什么原因？多谢O(∩_∩)O

**Comment by Alex1990** [comment]
我有个类似的问题，MAC 下的 Terminal 里面执行`hexo s`后，通过`localhost:4000`/`127.0.0.1:4000`可以访问，但是通过**本地 IP:端口**不可以访问。这样导致在 VirtualBox 虚拟机里面的系统无法通过**MAC 本地 IP:端口**访问来调试。
是不是要通过`hexo generate`/`hexo deploy`生成静态文件呢？

**Comment by Xuanwo** [comment]
可以生成静态文件之后用nginx之类的进行一下反代。

还有，原issue要是解决了就close吧= =

**Comment by Alex1990** [comment]
我是在做主题，修改下样式，想在虚拟机的IE中预览下就要每次生成，太麻烦了orz

这个问题不是我开的

@xiaowuzhu 或者作者关闭吧
