### ISSUE TITLE
建议提供HEXO的删除文档功能

### ISSUE THREAD

**Issue by Jreen** [hexojs/hexo#89]
THANKS

**Comment by thinkerchan** [comment]
确实.....如果只删除md文件的话....有时候还会编译出来

**Comment by Xuanwo** [comment]
@thinkerchan 你的错觉

**Comment by weiwunb** [comment]
# 顶这个问题 #
提供一个删除功能能减少不少工作量呢

**Comment by leesei** [comment]
用`hexo server` 的關一下重開.
還看見的話可以`rm db.json`.

用static file 的:
```sh
rm source/_posts/TO_DELETE.md
hexo clean
hexo generate
```

hexo new 應視為輔助功能, 不是核心功能
hexo 是"static site generator", 文件管理人手做是應該的

**Comment by syw2014** [comment]
我把其他文章删除了，重新generate后，但在github page上打开页面还是能看到旧的，但点进去是404，不知道怎么解决

**Comment by kobe0308** [comment]
我把其他文章删除了，重新generate后，但在github page上打开页面还是能看到旧的，但点进去是404，不知道怎么解决 => 這個問題看似還沒有覺,誰能協助確認一下嗎?

**Comment by goubo** [comment]
如果删除md后还能看见奇奇怪怪的东西，可以执行一下 `hexo clean`

**Comment by yaoqs** [comment]
such as:
```
hexo delete my_post //delete post
hexo modify my_post //modify post
```
