### ISSUE TITLE
带有 scope 的插件无法正确加载

### ISSUE THREAD

**Issue by lianqin7** [hexojs/hexo#891]
如题，因为现在 npm 有了 scope 的功能  `{ "name": "@scope/hexo-renderer-xxx" }`，所以安装到本地 `node_modules` 的目录结构可能如下：

```
- node_modules/
     + hexo-renderer-ejs/
     + hexo-renderer-markdown/
     ...
     - @scope/
         + hexo-renderer-xxx/
```

https://github.com/hexojs/hexo/blob/master/lib/loaders/plugins.js 仅做了单层目录判断，导致 `hexo-renderer-xxx` 无法正确加载

**Comment by NoahDragon** [comment]
npm has changed a lot since then. I assume this issue has been resolved.
