### ISSUE TITLE
Paginating a post?

### ISSUE THREAD

**Issue by myst729** [hexojs/hexo#896]
Sometimes a post may be very long.

WordPress provides a feature that you can insert `<!-- nextpage -->` in your post content.
![image](https://cloud.githubusercontent.com/assets/519733/4838293/7aeb1044-5fe6-11e4-8285-d13867f88429.png)

 And when you visit the post, there will be links to different pages.
![image](https://cloud.githubusercontent.com/assets/519733/4838296/8c005592-5fe6-11e4-855b-fe678865ec31.png)

I'd like to know whether Hexo is going to provide the feature as a helper or something?

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo/issues/3035
