### ISSUE TITLE
The variable path and url is not correct

### ISSUE THREAD

**Issue by DanielZhu** [hexojs/hexo#898]
Hi, the author of Hexo,

I write a simple theme for my site, and it has another new page named 'about' which is displayed in the site nav, like the nav below.
Home Archives About
But the variables url and path in header.ejs is not correct when I tried to print them in the corresponding page , the url always show as 'http://mysitedomain/archives' except the home page.

All the issues happened in my online website, it works well using localhost

Do you have any comments?

**Comment by leesei** [comment]
Can you post your repo?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
