### ISSUE TITLE
how can i delete some tag or categories

### ISSUE THREAD

**Issue by reky** [hexojs/hexo#899]
how can i delete some tag or categories, ?

**Comment by reaniwen** [comment]
It doesn't work on my computer. I tried "hexo clean" and "hexo clean life"(life is the cat I want to delete).
But life is still there

**Comment by wjho** [comment]
maybe there are some posts are still in life cat?

**Comment by leesei** [comment]
Remove the tag/category from all the post, `hexo clean` and then generate/serve.

**Comment by enkr1** [comment]
same hexo clean does not remove the tags and categories locally

**Comment by EngNashar** [comment]
the same issue hexo clear ,hexo generate with no categories in the markdown file changing the browser and cleaning the cache of the browser and categories still there

**Comment by EngNashar** [comment]
try to remove tags and categories from .md even if you don't want to delete both of them and check the _config.yml categories and tags
to this value
# Category & Tag
default_category: uncategorized
category_map:
tag_map:
