### ISSUE TITLE
 How to set permalink id to number ,not random string

### ISSUE THREAD

**Issue by Malayke** [hexojs/hexo#905]
我想设置文章的url为：
category/:id.html
即id为数字，但是hexo的id是随机的字符串

比如 category 设置为 article 时，文章的链接为：
I want to set url is: 
http://localhost:4000/article/123.html
而不是
Not:
http://localhost:4000/article/jr3kez5rstnkhs0i.html

**Comment by taozhijiang** [comment]
+1

**Comment by NoahDragon** [comment]
可以使用https://github.com/rozbo/hexo-abbrlink
然后将 :id 替换为 :abbrlink

**Comment by taozhijiang** [comment]
反正我是放弃了，毕竟用随机的url不太友好。
昨天我已放弃，将所有的md文件重命名为英文名，虽然造就了一大批死链接，长痛不如短痛

https://taozj.org 欢迎交换链接

**Comment by NoahDragon** [comment]
@taozhijiang 其实英文链接对SEO更友好，就是每次中文文章都要想个英文名是有些郁闷。

**Comment by taozhijiang** [comment]
应该是吧。反正我的域名没有备案，所以至今没有被百度收录，哔了狗了，是不是以后蜘蛛只需要按照被案列表爬虫就可以了。
其实英文也不难，而且就算丢到谷歌翻译中提取几个关键词也比随机url要强很多吧。
