### ISSUE TITLE
mac 安装hexo问题

### ISSUE THREAD

**Issue by lcepy** [hexojs/hexo#913]
系统版本：osx 10.10

已经安装了Xcode，Xcode命令行工具

sudo npm install -g hexo 

在命令行中抛如下警告信息：

> fsevents@0.2.0 install /usr/local/lib/node_modules/hexo/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

>gyp WARN EACCES user "root" does not have permission to access the dev dir >"/Users/xiangwenwen/.node-gyp/0.10.33"
>gyp WARN EACCES attempting to reinstall using temporary dev dir >"/usr/local/lib/node_modules/hexo/node_modules/chokidar/node_modules/fsevents/.node-gyp"

网上找了下资料，说是没有g++，我能确定自己安装了。

**Comment by yiyizym** [comment]
使用

sudo npm install -g hexo


遇到相同的问题

> fsevents@0.2.0 install /usr/local/lib/node_modules/hexo/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: Connection closed while downloading tarball file
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:239:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1098:46)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (http.js:1519:11)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:943:16
gyp ERR! stack     at process._tickCallback (node.js:419:13)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/hexo/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.2.0

**Comment by CookieJaySJ** [comment]
我也遇到这个问题啦～～  可是我使用chmod 777 /var/root 这个命令还是没有作用？   请问该怎么做啊

**Comment by Xuanwo** [comment]
Mac上面不能使用nvm？

**Comment by CookieJaySJ** [comment]
已经弄好了~~   谢谢哈

**Comment by Xuanwo** [comment]
提供一下如何解决的，方便后来人

**Comment by CookieJaySJ** [comment]
sudo npm install -g -unsafe-perm hexo     虽然有报错,但是貌似不影响正常使用QAQ

**Comment by Xuanwo** [comment]
`-unsafe-perm` 这个是什么选项？

**Comment by CookieJaySJ** [comment]
嗯嗯    因为我找了一天多,都没有找到其他解决办法     有可能是yosemite10.10系统的问题

**Comment by Xuanwo** [comment]
因为`fsevent`依赖的问题，出现warning是正常的，这个不算报错

**Comment by CookieJaySJ** [comment]
这样啊~   谢谢啦

**Comment by Wenqulai** [comment]
一样遇到这个问题，现在已解决。说一下解决方案：
sudo  npm install -g hexo --registry=https://registry.npm.taobao.org
这样做后虽然仍然会有warn错误，但是等一下就好了。

**Comment by dupengtao** [comment]
我也遇到了这样的问题，后面解决了，主要原因是没有装Xcode

**Comment by FrankBian** [comment]
可以跟着hexo官网那个setup一步一步进行配置



Best Regards,
Frank Bian

**Comment by lvyunyi** [comment]
同样遇到这个问题，搜到了它：http://stackoverflow.com/questions/15633029/npm-no-longer-working

**Comment by qingqinghebiancao** [comment]
@icepy 同样遇到了你的这个安装问题，请问你是怎么解决的吖？？( ⊙ o ⊙ )！
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "hexo"
npm ERR! node v0.10.33
npm ERR! npm v2.1.7
npm ERR! path /usr/local/lib/node_modules/hexo/.gitmodules
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/hexo/.gitmodules'
npm ERR! { [Error: EACCES, unlink '/usr/local/lib/node_modules/hexo/.gitmodules']
npm ERR! errno: 3,
npm ERR! code: 'EACCES',
npm ERR! path: '/usr/local/lib/node_modules/hexo/.gitmodules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/hexo/.gitmodules'
npm ERR! error rolling back { [Error: EACCES, unlink '/usr/local/lib/node_modules/hexo/.gitmodules']
npm ERR! error rolling back errno: 3,
npm ERR! error rolling back code: 'EACCES',
npm ERR! error rolling back path: '/usr/local/lib/node_modules/hexo/.gitmodules' }

npm ERR! Please include the following file with any support request:
npm ERR! /Users/xiangwenwen/npm-debug.log

**Comment by icepy** [comment]
@qingqinghebiancao

感觉好像是墙的原因，我现在换了台Mac，开了VPN现在没有报错了。

**Comment by qingqinghebiancao** [comment]
@icepy 我有按照网上说的改镜像https://cnodejs.org/topic/4f9904f9407edba21468f31e，但是还是没安装成功%>_<%

**Comment by icepy** [comment]
@qingqinghebiancao  要不你开下VPN吧，在node-gyp那里会稍微等待会儿，因为在交检。

**Comment by icepy** [comment]
@qingqinghebiancao  其他步骤和官网的那个一样

**Comment by qingqinghebiancao** [comment]
@icepy 好的,那我试下！谢谢！

**Comment by hilen** [comment]
我使用这种方法可以了
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

然后
```
sudo npm -g install hexo-cli
```

**Comment by code4s** [comment]
使用 `sudo npm install -g -unsafe-perm hexo` 安装成功啦！

**Comment by andy90s** [comment]
@code4a  thanks ,it works for me that 'sudo npm install -g -unsafe-perm hexo'

**Comment by LongQingling** [comment]
`
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "-unsafe-perm" "hexo"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ETIMEDOUT 172.16.10.7:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lori/npm-debug.log`

弄了一晚上没弄好

**Comment by sharonlucong** [comment]
`sudo npm install -g -unsafe-perm hexo-cli` <- works!
