### ISSUE TITLE
主页的归档的时间格式不支持中文

### ISSUE THREAD

**Issue by myqianlan** [hexojs/hexo#918]
hexo版本2.8.3.
在更改language为 zh_CN后，其渲染出来的仍旧是英文。就像下图这样
![qq 20141117003330](https://cloud.githubusercontent.com/assets/5117885/5062211/f2594d26-6df1-11e4-9279-067e8f09cb82.jpg)

请问如何设置才能显示中文，或者说是这个版本hexo的问题？(´･_･`)

**Comment by Xuanwo** [comment]
你好，这个问题解决了么？

**Comment by leesei** [comment]
Hexo 的`list_archives()` 是最簡單的列表
要客製化文字要theme 支持
