### ISSUE TITLE
hexo generate hexoerror: render failed refence error

### ISSUE THREAD

**Issue by christinaliaiping** [hexojs/hexo#923]
I want deploy hexo to my github pages. But after  I changed the deploy configuration as my github respository in the _config.yml and run the command "hexo generate", I got into the trouble as follow:
![hexoerror](https://cloud.githubusercontent.com/assets/4392644/5083140/6a6d9616-6f2b-11e4-9d35-ee18be19c0fb.jpg)
PS: I deployed hexo in windows. Any help will be apprieciated. Thankyou!

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
