### ISSUE TITLE
`include_code` link and `root` config

### ISSUE THREAD

**Issue by smmoosavi** [hexojs/hexo#928]
when i change `root` config, download link of `include_code` dose not work correctly

_config.yml:

```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /test/
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# ... other configs
```

source/_post/My-New-Post.md:

```
title: My New Post
date: 2014-11-18 22:11:46
tags:

---

{% include_code test.html lang:html test.html %}
```

download link in page: `http://localhost:4000/downloads/code/test.html`

expected download link: `http://localhost:4000/test/downloads/code/test.html`

and console: `GET /downloads/code/test.html 404 2.802 ms - 37`

extra info:
- theme: landscape
- version: hexo: 2.8.3

**Comment by Xuanwo** [comment]
@smmoosavi How about in the newest version?

**Comment by curbengh** [comment]
should be resolved by now
https://github.com/hexojs/hexo/blob/cdac4d90fdefbda5caf521076688c1177e87eb67/lib/plugins/tag/include_code.js#L59

Feel free to reopen otherwise.
