### ISSUE TITLE
`hexo deploy` will never finish while `hexo server` is running

### ISSUE THREAD

**Issue by cutewalker** [hexojs/hexo#933]
hi guys:
I found that when `hexo server` is running, command `hexo deploy` will never finish though it in fact has done every thing. Just stop `hexo server` make things fine as usually.

I am not sure whether it is really a bug since I have not test on other machines.

here is the version of hexo and its deps: 
```
$ hexo --version
hexo: 2.8.3
os: Linux 3.15.10-201.fc20.i686+PAE linux ia32
http_parser: 2.0
node: 0.10.32
v8: 3.14.5.10
ares: 1.10.0
uv: 0.10.28
zlib: 1.2.8
modules: 11
```

**Comment by revelt** [comment]
yeah, I noticed too, when server is on, it's not a good idea to use any other commands – stop the server first..

**Comment by Xuanwo** [comment]
Closed for no more update.
