### ISSUE TITLE
Front-matter设置某一个配置项，让hexo忽略某一个md文件

### ISSUE THREAD

**Issue by gejiawen** [hexojs/hexo#937]
我某个目录下的md文件并不想被hexo解析成html文件，我只想hexo在generator的过程中，将此md文件移动到public文件夹中的对应目录中就行了。

`Front-matter`有提供这个选项么？或者给我指条明路，我自己来修改hexo源码也可以。

:cry:

**Comment by hengyunabc** [comment]
希望能添加一个exclude_folder的配置。改后缀实在是太不方便了。

**Comment by Xuanwo** [comment]
最新版本已经支持这个功能了，可以参考 http://xuanwo.org/2014/08/14/hexo-usual-problem/#Hexo3-0%E4%BB%A5%E4%B8%8A%E6%94%AF%E6%8C%81

**Comment by gejiawen** [comment]
#1146
