### ISSUE TITLE
Custom Collections like Tags and Categories

### ISSUE THREAD

**Issue by jakeoftrades** [hexojs/hexo#938]
Lets say, in my 'movie blog', I have "Actors" collection. Is it possible by adding it in Front Matter like

actors: 
   - Jake
   - Jill

and list all "actors" in archive page? Adding all these info into "tags" isn't viable in my case.  Would appreciate if it can be accomplished or any workaround.

**Comment by amejias101** [comment]
Is this how I could implement something like /projects/projectA and projects/projectB ? In this case projectA and projectB are like blog posts but use 'projects' as the parent slug
