### ISSUE TITLE
og:url incorrect when site is put under subdirectory

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#942]
`_config.yml`

```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com/child
root: /child/
```

In HTML's meta

``` html
<meta property="og:url" content="http://yoursite.com/child/child/">
```

**Comment by apalskoi** [comment]
I am having the same issue. I have fixed it for now by adding a replacement for the 'url' option of open_graph in the layout/_partial/head.ejs:

url: url.replace('/blog/blog', '/blog') - my blog is in the '/blog' subdirectory.

``` <%- open_graph({twitter_id: theme.twitter, google_plus: theme.google_plus, fb_admins: theme.fb_admins, fb_app_id: theme.fb_app_id, url: url.replace('/blog/blog', '/blog')}) %>```

**Comment by kflu** [comment]
Same problem here. Problem is facebook won't display images when sharing links that have the invalid og:image tags. I worked it around by commenting those out. 

But it seems the true fix really should be in `node_modules\hexo\lib\plugins\helper\open_graph.js`:

```javascript

  images = images.map(function(path) {
    if (!urlFn.parse(path).host) {
      if (path[0] !== '/') path = '/' + path;
      return config.url + path;
    }

    return path;
  });
```

**Comment by kflu** [comment]
OK. I've fixed this with:

```

  images = images.map(function(path) {
    if (!urlFn.parse(path).host) {
      if (path[0] !== '/') {
        return urlFn.resolve(url, path);
      }
    }

    return path;
  });
```
