### ISSUE TITLE
"npm install -g hexo" failed on windows 7 64bit

### ISSUE THREAD

**Issue by mowater** [hexojs/hexo#944]
Microsoft Windows [版本 6.1.7600]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Windows\system32>node -v
v0.10.33

C:\Windows\system32>npm -v
1.4.28

C:\Windows\system32>hexo -v
'hexo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Windows\system32>npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open 'C:\Windows\system32\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd C:\Windows\system32
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path C:\Windows\system32\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Windows\system32\npm-debug.log
npm ERR! not ok code 0

C:\Windows\system32>npm install -g hexo
npm WARN optional dep failed, continuing fsevents@0.2.0
C:\Program Files\nodejs\node_global\hexo -> C:\Program Files\nodejs\node_global\
node_modules\hexo\bin\hexo
hexo@2.8.3 C:\Program Files\nodejs\node_global\node_modules\hexo
├── strip-indent@0.1.3
├── hexo-front-matter@0.0.4
├── sprintf-js@0.0.7
├── colors@0.6.2
├── graceful-fs@3.0.5
├── minimist@0.2.0
├── mime@1.2.11
├── async@0.9.0
├── warehouse@0.2.2 (async@0.7.0)
├── lodash@2.4.1
├── highlight.js@8.1.0
├── moment@2.8.4
├── chokidar@0.8.2 (recursive-readdir@0.0.2)
├── morgan@1.5.0 (basic-auth@1.0.0, depd@1.0.0, debug@2.1.0, on-finished@2.1.
1)
├── compression@1.2.1 (vary@1.0.0, bytes@1.0.0, on-headers@1.0.0, debug@2.1.0
, compressible@2.0.1, accepts@1.1.3)
├── connect@3.3.3 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.1.0, finalhandl
er@0.3.2)
├── js-yaml@3.2.3 (esprima@1.0.4, argparse@0.1.16)
├── serve-static@1.7.1 (utils-merge@1.0.0, parseurl@1.3.0, escape-html@1.0.1,
 send@0.10.1)
├── cheerio@0.17.0 (entities@1.1.1, dom-serializer@0.0.1, CSSselect@0.4.1, ht
mlparser2@3.7.3)
└── swig@1.4.1 (optimist@0.6.1, uglify-js@2.4.15)

C:\Windows\system32>

**Comment by Baymaxxx** [comment]
cd到hexo之后也不能运行，和楼上一样的问题。求解，thx

**Comment by Xuanwo** [comment]
因为现在已经没有这个全局包了，请先执行`npm install hexo-cli -g`，然后在hexo目录中执行`hexo init` & `npm install`

**Comment by codetin** [comment]
npm install hexo@2.8 -g

**Comment by zjw-swun** [comment]
C:\Users\jiawei\AppData\Roaming\npm

**Comment by nzsghdx** [comment]
git 安装目录\bin
node 安装目录
hexo 用户目录\AppData\Roaming\npm
三个都需要配置环境变量，配置好了一般就行了

**Comment by cmshome** [comment]
http://blog.csdn.net/qq_27093465/article/details/72954725
图文记录我是如何在Windows上解决这个问题，不才刚刚开始摸索这东西。留下我摸索时的链接，希望可以帮助后来的哥们。

**Comment by cmshome** [comment]
http://blog.csdn.net/qq_27093465/article/details/72954725
图文记录我是如何在Windows上解决这个问题，不才刚刚开始摸索这东西。留下我摸索时的链接，希望可以帮助后来的哥们。

**Comment by kongbaiye** [comment]
环境变量没有配置好，给系统变量 path里追加上存放node全局模块的目录路径（我的是E:\nodejs\node_global）就好了。

我的node安装在E:\nodejs，
存放node全局模块的目录通过npm config set prefix "E:\nodejs\node_global" 设置为了E:\nodejs\node_global
