### ISSUE TITLE
新增一个类别，但是页面上不会显示

### ISSUE THREAD

**Issue by lirenke** [hexojs/hexo#952]
我想在页面上新增一个类别，在主目录的_config.yml里面：
    # Category & Tag
    default_category: uncategorized
    category_map:
         test1: test
    tag_map:

但是重新生成页面后，public\categories目录下并不会生成test，页面上也不会显示test1。怎么破？

**Comment by Xuanwo** [comment]
同意楼上，新增类别需要在文章的yml头中添加相关信息。
