### ISSUE TITLE
怎么访问源码目录下的文件？

### ISSUE THREAD

**Issue by linkarys** [hexojs/hexo#956]
比如有一些静态的html是手写的， 我希望这些文件在最终站点上是可访问的， 那么问题就是我需要把这些文件需要放在哪个目录？访问的路径应该是什么？_config.yml的`code_dir: downloads/code`是做什么用的？初用hexo, 问题看起来有点low, 还请多指教， 谢谢！

**Comment by yujiangshui** [comment]
@acechao 多谢。
@linkarys 解决了，记得 close
