### ISSUE TITLE
What tools are required besides npm/ node?

### ISSUE THREAD

**Issue by bguiz** [hexojs/hexo#957]
The main documentation page includes this warning:

> For Mac users
> You may encounter some problems when compiling. Please install Xcode from App Store first. After > Xcode is installed, open Xcode and go to Preferences -> Download -> Command Line Tools -> Install to install command line tools.

What tools are required to be on the command line besides npm and node?
Given that this project is 100% Javascript, is there really a need for non-node tooling dependencies?

**Comment by leesei** [comment]
Some of the dependencies of hexo is not purely javascript, so your platform should be able to build them.
