### ISSUE TITLE
HEXO deploy 后显示成功,但github上没有更新,网页上也没有新加的文章.

### ISSUE THREAD

**Issue by acechao** [hexojs/hexo#961]
>1.这是deploy后的截图：
![](http://i.imgur.com/MNxT36V.png)
>2.本地git环境:Msysgit+Tortoisegit
>3.hexo clean 多次再hexo n/g/d 还是这样的问题！

我的暂时解决办法：
1.将 acechao.github.io 克隆到本地
2.用本地文件同步工具bestsync将 .deploy文件夹和acechao.github.io两个文件夹同步起来
3.然后再将acechao.github.io 同步到远程仓库！

PS:哎哟妈呀 ！写个博客这么麻烦啊！大神能不能给我支支招，像个黑客(hexo)一样简单的写博客！

**Comment by GeneralZYQ** [comment]
我一开始也没法进行部署，或者说，部署之后没有显示我的文章。
但是改成hero deploy -g 之后就好了。您可以试试

**Comment by wangyaoxu** [comment]
```bash
hexo clean
hexo deploy
```
works ！

**Comment by lusg02** [comment]
@GeneralZYQ  确实，不懂什么原理。。我试了`hexo d`，`hexo d -g`都不管用，看到你这儿换成`hexo deploy -g`后管用啦

**Comment by Cristiano-3** [comment]
Ubuntu16.04, hexo版本信息
hexo: 3.3.9
hexo-cli: 1.0.4
os: Linux 4.13.0-32-generic linux x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

这样子可以:
mv .deploy_git/  .. （删除或移到其他地方）
hexo deploy -g

**Comment by ChenPt** [comment]
进入博客的地址，打开控制台清除缓存， hexo clean， hexo g -d 重新部署一遍。我今天就是因为缓存的原因一直部署不上，清除缓存后就OK了

**Comment by leoxu1007** [comment]
你好，我想问一下，在本地输入了这个之后，
LeonoMacBook-Pro:inori.life leoxu$ sudo hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
On branch master
nothing to commit, working tree clean
git@inori.life's password: 
Everything up-to-date
Branch master set up to track remote branch master from git@inori.life:/var/repo/blog.git.
INFO  Deploy done: git
LeonoMacBook-Pro:inori.life leoxu$ 
vps上的git仓库 /var/repo/blog.git 没有任何变化，而我的网站主目录/home/www/hexo也没有任何变化。
但是也没报错。为什么啊。。。

**Comment by geekyouth** [comment]
url 地址添加?#后缀拼接新址，重新访问既可避免缓存问题

**Comment by TrillStones** [comment]
检查_config.yml中的内容，特别注意:后面需要有一个空格

**Comment by Juston-ee** [comment]
PS E:\Blog> hexo clean
INFO  Deleted database.
INFO  Deleted public folder.
PS E:\Blog> hexo d -g
INFO  Start processing
INFO  Files loaded in 3.31 s
INFO  Generated: index.html
INFO  Generated: README.md
INFO  Generated: CNAME
INFO  Generated: categories/index.html
INFO  Generated: archives/index.html
INFO  Generated: tags/index.html
INFO  Generated: 404/index.html
INFO  Generated: tags/Hello-World/index.html
INFO  Generated: img/algolia.svg
INFO  Generated: img/favicon.ico
INFO  Generated: img/post_loadding.svg
INFO  Generated: img/icp.png
INFO  Generated: img/404.jpg
INFO  Generated: img/comment_bg.png
INFO  Generated: archives/2019/12/index.html
INFO  Generated: img/friend_404.gif
INFO  Generated: archives/2019/index.html
INFO  Generated: css/var.css
INFO  Generated: js/baidupush.js
INFO  Generated: js/main.js
INFO  Generated: js/runtimeshow.js
INFO  Generated: js/tw_cn.js
INFO  Generated: js/utils.js
INFO  Generated: css/index.css
INFO  Generated: js/third-party/anime.min.js
INFO  Generated: js/third-party/piao.js
INFO  Generated: js/third-party/canvas-nest.js
INFO  Generated: js/third-party/activate-power-mode.js
INFO  Generated: js/search/algolia.js
INFO  Generated: js/search/local-search.js
INFO  Generated: js/third-party/click_heart.js
INFO  Generated: js/third-party/ClickShowText.js
INFO  Generated: js/third-party/canvas-ribbon.js
INFO  Generated: js/third-party/fireworks.js
INFO  Generated: 2019/12/10/hello-world/index.html
INFO  Generated: img/avatar.png
INFO  Generated: js/third-party/jquery.fancybox.min.js
INFO  Generated: js/third-party/jquery.min.js
INFO  38 files generated in 1.13 s
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
warning: LF will be replaced by CRLF in 2019/12/10/hello-world/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in archives/2019/12/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in archives/2019/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in archives/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in categories/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in css/index.css.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/baidupush.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/main.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/runtimeshow.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/search/algolia.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/search/local-search.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/ClickShowText.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/anime.min.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/canvas-nest.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/canvas-ribbon.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/fireworks.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/jquery.fancybox.min.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/jquery.min.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/third-party/piao.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/tw_cn.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in js/utils.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tags/Hello-World/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tags/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in 404/index.html.
The file will have its original line endings in your working directory
[master c73e9ec] Site updated: 2019-12-18 12:07:43
 2 files changed, 73 insertions(+), 1 deletion(-)
 create mode 100644 404/index.html
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 820 bytes | 820.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 2 local objects.
To github.com:Juston-ee/Juston-ee.github.io.git
   983e163..c73e9ec  HEAD -> master
Branch 'master' set up to track remote branch 'master' from 'git@github.com:Juston-ee/Juston-ee.github.io.git'.
INFO  Deploy done: git


一切都正常
GitHub上也有文件 
![image](https://user-images.githubusercontent.com/50875004/71055426-7af36480-2190-11ea-84b1-bbb04859ac0c.png)


但是
![image](https://user-images.githubusercontent.com/50875004/71055401-5f885980-2190-11ea-9e47-8ebf51a44922.png)
就是一直 404 
不知道给怎么办了。。。
请指教！！！

**Comment by Lintkey** [comment]
我也有类似的问题，后来发现是因为浏览器缓存没清，浏览器默认从缓存中加载网页，导致看不到上传更新后的内容，直接<kbd>Shift</kbd>+<kbd>F5</kbd>强制刷新浏览器缓存就行了，单纯刷新有些内容是不会更新的。

**Comment by xww0826** [comment]
> 我一开始也没法进行部署，或者说，部署之后没有显示我的文章。 但是改成hexo deploy -g 之后就好了。您可以试试

Thanks

**Comment by Enchantedovo** [comment]
>你好，我跟你的情况一样，请问你解决了吗

**Comment by Enchantedovo** [comment]
> PS E:\Blog> hexo clean INFO Deleted database. INFO Deleted public folder. PS E:\Blog> hexo d -g INFO Start processing INFO Files loaded in 3.31 s INFO Generated: index.html INFO Generated: README.md INFO Generated: CNAME INFO Generated: categories/index.html INFO Generated: archives/index.html INFO Generated: tags/index.html INFO Generated: 404/index.html INFO Generated: tags/Hello-World/index.html INFO Generated: img/algolia.svg INFO Generated: img/favicon.ico INFO Generated: img/post_loadding.svg INFO Generated: img/icp.png INFO Generated: img/404.jpg INFO Generated: img/comment_bg.png INFO Generated: archives/2019/12/index.html INFO Generated: img/friend_404.gif INFO Generated: archives/2019/index.html INFO Generated: css/var.css INFO Generated: js/baidupush.js INFO Generated: js/main.js INFO Generated: js/runtimeshow.js INFO Generated: js/tw_cn.js INFO Generated: js/utils.js INFO Generated: css/index.css INFO Generated: js/third-party/anime.min.js INFO Generated: js/third-party/piao.js INFO Generated: js/third-party/canvas-nest.js INFO Generated: js/third-party/activate-power-mode.js INFO Generated: js/search/algolia.js INFO Generated: js/search/local-search.js INFO Generated: js/third-party/click_heart.js INFO Generated: js/third-party/ClickShowText.js INFO Generated: js/third-party/canvas-ribbon.js INFO Generated: js/third-party/fireworks.js INFO Generated: 2019/12/10/hello-world/index.html INFO Generated: img/avatar.png INFO Generated: js/third-party/jquery.fancybox.min.js INFO Generated: js/third-party/jquery.min.js INFO 38 files generated in 1.13 s INFO Deploying: git INFO Clearing .deploy_git folder... INFO Copying files from public folder... INFO Copying files from extend dirs... warning: LF will be replaced by CRLF in 2019/12/10/hello-world/index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in archives/2019/12/index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in archives/2019/index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in archives/index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in categories/index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in css/index.css. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/baidupush.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/main.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/runtimeshow.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/search/algolia.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/search/local-search.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/ClickShowText.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/anime.min.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/canvas-nest.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/canvas-ribbon.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/fireworks.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/jquery.fancybox.min.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/jquery.min.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/third-party/piao.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/tw_cn.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in js/utils.js. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in tags/Hello-World/index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in tags/index.html. The file will have its original line endings in your working directory warning: LF will be replaced by CRLF in 404/index.html. The file will have its original line endings in your working directory [master c73e9ec] Site updated: 2019-12-18 12:07:43 2 files changed, 73 insertions(+), 1 deletion(-) create mode 100644 404/index.html Enumerating objects: 9, done. Counting objects: 100% (9/9), done. Delta compression using up to 8 threads Compressing objects: 100% (5/5), done. Writing objects: 100% (6/6), 820 bytes | 820.00 KiB/s, done. Total 6 (delta 3), reused 0 (delta 0) remote: Resolving deltas: 100% (3/3), completed with 2 local objects. To github.com:Juston-ee/Juston-ee.github.io.git 983e163..c73e9ec HEAD -> master Branch 'master' set up to track remote branch 'master' from '[git@github.com](mailto:git@github.com):Juston-ee/Juston-ee.github.io.git'. INFO Deploy done: git
> 
> 一切都正常 GitHub上也有文件 ![image](https://user-images.githubusercontent.com/50875004/71055426-7af36480-2190-11ea-84b1-bbb04859ac0c.png)
> 
> 但是 ![image](https://user-images.githubusercontent.com/50875004/71055401-5f885980-2190-11ea-9e47-8ebf51a44922.png) 就是一直 404 不知道给怎么办了。。。 请指教！！！

你好，我的问题跟你一样，请问你是如何解决的？

**Comment by 1040706977** [comment]
![image](https://github.com/hexojs/hexo/assets/56628320/18cc69ab-59b5-4f56-a00a-c173b3e423f9)解决了，github需要手动开启pages。萌新的我并不知道，很多教程并没有这一步( •̀ ω •́ )y
