### ISSUE TITLE
Deploy on Heroku cannot "GET" resources

### ISSUE THREAD

**Issue by zacharygcook** [hexojs/hexo#962]
My deployment on Heroku seems to finally work: I have made the Procfile, modified _config.yml, and after "hexo deploy" the terminal shows no errors. 

Then, when I go to the app's Heroku URL the post & all markup shows like it should.

However, for some reason the resources (such as the CSS) do not show up, and when I go to their url all I see is:

```
Cannot GET /blog/css/style.css
```

Or

```
Cannot GET /blog/fancybox/jquery.fancybox.css
```

And on & on for every resource file. 

I really don't know where to go from here. Could somebody help with this issue?

My code is open to the public at: https://github.com/djlovegrind/texasca-blog

Thanks for your help!

**Comment by BH0** [comment]
I am the same / similar issue; root is set to '/' and I'm still experiencing the issue...
