### ISSUE TITLE
怎么设置 hexo 的文章内的图片大小

### ISSUE THREAD

**Issue by kawaiiushio** [hexojs/hexo#969]
怎么设置 hexo 的文章内的图片大小

像这个 http://ippotsuko.com/about/

_(:з」∠)_ 跪了啊

**Comment by iissnan** [comment]
使用`Image` tag plugin，详见：

[Hexo Tag-plugins - Image](http://hexo.io/docs/tag-plugins.html#Image)

**Comment by kawaiiushio** [comment]
昨天的东京服务器应该没问题吧

2015-01-21 10:17 GMT+08:00 Vi <notifications@github.com>:
