### ISSUE TITLE
code block高亮设为plain后，代码会被当做html处理

### ISSUE THREAD

**Issue by kongweihan** [hexojs/hexo#974]
在写伪代码或者画简单图表时，我需要没有高亮的code block，但是代码却被解释为html，如下

    ``` plain
    <a>
    ```
显示出来什么都没有，code block是空的。如果我想画图

    ``` plain
    small <-- --> big
    ```
显示出来是

    small <-- --=""> big

我知道可以escape所有html字符，但这似乎不是很合理，plain text就应该是以code方式显示的plain text

**Comment by hcoona** [comment]
我试了两位的例子，都能够正确显示
![ScreenShot](https://cloud.githubusercontent.com/assets/712433/7300150/14c99090-ea0d-11e4-8f26-1f61e369e896.png)

**Comment by hcoona** [comment]
```
➜ ~ hexo --version
hexo-cli: 0.1.4
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by leesei** [comment]
What's the theme your're using?

**Comment by leesei** [comment]
Please open new issue if the problem persists with latest build.
