### ISSUE TITLE
How can I create a custom page?

### ISSUE THREAD

**Issue by TivonJJ** [hexojs/hexo#975]
I want to create a category page and tag page, They can show all categories and tags. Or more variables from hexo

**Comment by yujiangshui** [comment]
静态页面，人肉更新的话，可以新建 page，或者直接创建 html 文件，放在 source 文件夹下面。

需要获取变量以及自动更新的花，需要参照 http://hexo.io/docs/themes.html 这里开发 theme，新建 category.ejs 和 tag.ejs 等模板文件，然后调用 http://hexo.io/docs/variables.html 这里面你需要的变量。
