### ISSUE TITLE
hexo clean后重新生成不带有以前的文章。

### ISSUE THREAD

**Issue by nolouch** [hexojs/hexo#979]
1.想要用,但加了还是没效果，就想清除一下缓存试试。
2.hexo clean 后，hexo g 生成不带有_post里以前写的*.md,而只能是clean后用hexo n 生产的md才能生产相应的页面。

这两个问题怎么解决。

**Comment by Xuanwo** [comment]
1：
这个貌似需要主题支持？修改之后需要Ctrl+F5强制刷新才能看到效果，或者清除浏览器缓存。

2：
感觉不合理，因为我从来没有用hexo n来生成过新的文档。而且hexo的执行逻辑就是检索_post文件夹下的md文件，所以我觉得问题应该出在你是不是定位错了地方。建议删掉那个文件夹，重新hexo init一遍，然后在新生成的_post文件夹下面添加md文件。

**Comment by nolouch** [comment]
重新装了解决了，谢谢 @Xuanwo

**Comment by Xuanwo** [comment]
关闭这个issue吧~
