### ISSUE TITLE
hexo 除了推送到github 上，是否可以推送到其他的服务器上，比如vps 上？

### ISSUE THREAD

**Issue by 2005wangliqun** [hexojs/hexo#980]
主要是国内访问github 比较慢，打开网站的首页需要等待很长时间，所以打算把自己租个服务器，然后把博客的内容推送到自己的博客上。
现在的疑问主要是有以下几个：
1 我需要在自己的服务器上，安装哪些软件？
2 hexo 通过push 的方式推送本地的文章到服务器上，我是否也需要在自己的服务器上搭建一个类似github 的系统才能push?
3 主要想用markdown 写文章，然后推送到可以快速访问的服务器上，这个方案是否可行？或者有其他更佳的方案？
谢谢！

**Comment by Xuanwo** [comment]
我感觉要是在VPS上面搞得话，直接`hexo s`就已经建好一个nodejs服务器了~

**Comment by hikerpig** [comment]
1. 在VPS上建立一个裸仓库 site.git,  写一下post-update的git hook. 然后在VPS上另一个目录clone一下这个仓库, 每次push到site.git的时候cd site && git pull ../path/to/site.git && hexo s
2. 或者使用hexo generate出所有静态文件以后用rsync 把public文件夹推到VPS上, 然后配一个静态文件服务器就好, nginx之类的

**Comment by Xuanwo** [comment]
如果问题解决了就close掉吧= =
