### ISSUE TITLE
[REQUEST] Auto-Tweet (Publicize) new post/page on deployment

### ISSUE THREAD

**Issue by ootput** [hexojs/hexo#982]
Hello,

Sorry in advance if this is the incorrect channel for feature-requests, though hopefully this has already been implemented/requested in a fashion so that I further advocate its use.

The feature I'm after exists in wordpress.com's pages, and documentation can be found here: http://en.support.wordpress.com/publicize/ - specifically the section on twitter.

Of course, wordpress.com implementation relies heavily on a gui - for accessibility; and for authorizing account connections - so it may be difficult to duplicate on the console-nature of hexo.

Notwithstanding, I think it would be a fantastic feature for Hexo, wherein I can have tweets containing shortened urls (git.io) to new blog entries.

Though I understand if the code required would bloat my lean-mean-blog-platform of choice, I just thought it would be nice.

Regards,
Joe

Edit:
I've found some documentation on Passport (authentication middleware for Node.js) at http://passportjs.org/  and https://github.com/paullang/express-angular, but I can't seem to make heads-or-tails of it as I'm essentially an end-user only.

**Comment by sebie** [comment]
You could try IFTTT, if you wanted to. Using the RSS feed and connecting your Twitter account to it. Hope it helps a bit.
