### ISSUE TITLE
hexo的stylus包无法编译

### ISSUE THREAD

**Issue by kevin14** [hexojs/hexo#983]
CSS无法编译，估计是hexo-renderer-stylus包出了问题，我现在的版本是v2.8.3，所用到的package都是最新的。

**Comment by jackhub** [comment]
是不是表现为部署后, 通过localhost 访问就是个文本网页, 什么样式都没有 ? 我也这样, 什么主题都用不了, 完全按照手册做的, 折腾了一天还是不行~~

**Comment by kevin14** [comment]
@jackhub 是哦，别折腾了，这个版本的bug。我感觉是没有把stylus编译成功，也许是那个包的问题。

**Comment by tommy351** [comment]
抱歉，0.2.0 是為 Hexo 3.0 設計的，請安裝舊版。

``` bash
$ npm install hexo-renderer-stylus@0.1 --save
```

ref hexojs/hexo-renderer-stylus#5

**Comment by kevin14** [comment]
@jackhub 你的主页很好看 ，很整洁 ， 等他们修好了bug，我就用你的theme。

**Comment by kevin14** [comment]
@tommy351 好的 谢谢你！

**Comment by kisnows** [comment]
原来是插件有bug，找了一天问题，终于解决了。
