### ISSUE TITLE
mac 上 在chrome/firefox/safari 打开 localhost:4000/特别的慢，大家遇到过？

### ISSUE THREAD

**Issue by 2005wangliqun** [hexojs/hexo#984]
新建一个hexo 目录立即 hexo g; hexo s  后在浏览器中输入  localhost:4000 打开网页特别慢，需要几分钟，大家遇到过这样的情况么？

**Comment by jackhub** [comment]
而且加载出来没有样式, 我看好像没有css文件, 要怎么搞呀, 我换了很多主题, 都不生成css文件, 搞了一天了, 要怎么解决??

**Comment by shunia** [comment]
@2005wangliqun 默认样式(Landscape)引用了google的字体库,如果你在墙里,慢很正常.换个默认样式,或者搜索自定义样式的方法以去除这段引用.
@jackhub css这个应该是个新bug,貌似更新了新版的同学全遇到了(hexo 2.8.3)

**Comment by kevin14** [comment]
这个是因为样式没有编译成功，最新版本的bug，我已弃疗。

**Comment by kevin14** [comment]
@2005wangliqun  https://github.com/hexojs/hexo/issues/983 这里已经给出解决方案
