### ISSUE TITLE
style.css cannot be served

### ISSUE THREAD

**Issue by jameswomack** [hexojs/hexo#985]
The website hangs on `<link rel="stylesheet" href="/css/style.css" type="text/css">` every time. It appears that it is not generated when I use `hexo generate`. I am using the default landscape theme, The JS and HTML is served just fine.

**Comment by lifehale1993** [comment]
Web page has been loaded style.css file when I opened the service. At the same time, I can't find style.css in the compiled CSS directory after used hexo generate.

**Comment by jackhub** [comment]
I have the same problem~

**Comment by ring0li** [comment]
have the same problem~

**Comment by shunia** [comment]
Plus one (+1), searched around but found no solution, so may be it's a new problem.

**Comment by tommy351** [comment]
Sorry. hexo-renderer-stylus is rewritten for Hexo 3.0. Please install the old version instead.

``` bash
$ npm install hexo-renderer-stylus@0.1 --save
```

ref hexojs/hexo-renderer-stylus#5

**Comment by ring0li** [comment]
it's ok!

**Comment by jackhub** [comment]
thanks for help, it's ok now

**Comment by lifehale1993** [comment]
It works now，thanks！

**Comment by kinglion** [comment]
It works now，thanks！

**Comment by ChJJin** [comment]
it works, thanks!!
