### ISSUE TITLE
How to upgrade to new version?

### ISSUE THREAD

**Issue by douglarek** [hexojs/hexo#99]
When I use old `hexo` version to setup my site, how can I upgrade it to new version?

**Comment by ziyuang** [comment]
@tommy351 the link says 

> Sparrow has been acquired by Google, Inc.
> For media inquiries, please contact press@google.com.

Can you provide an updated link?

**Comment by Lixinyi-DUT** [comment]
Just type
```
npm install
```
ALL RELATIVE PACKAGES can be updated automatically, and you have no need to worry about configured files.
