### ISSUE TITLE
hexo how to generate yaml front matter

### ISSUE THREAD

**Issue by QianChenglong** [hexojs/hexo#993]
I known where to config post template(`scaffolds/post.md`), here is 

    ---
    title: {{ title }}
    categories: []
    tags: []
    date: {{ date }}
    ---

But when I `hexo new title.md`, it generates like this

    title: title
    categories: []
    tags: []
    date: 2015-01-15 17:32:51
    ---

Strangely, the leading `---` is gone!

How to fix it???

**Comment by Anachron** [comment]
@QianChenglong well it seems it's using the defaults:
https://github.com/hexojs/hexo/blob/master/lib/hexo/scaffold.js#L11-L19

**Comment by QianChenglong** [comment]
Sorry, I had tested it. Modify `post.md`, it works. Modify `scaffold.js`, It still. So it's not using the defaults.Do you have this problem?

**Comment by tommy351** [comment]
[front-matter](https://github.com/hexojs/front-matter) module removes prefixing dashes when transforming data to strings.
