### ISSUE TITLE
public/ missing css

### ISSUE THREAD

**Issue by orchard2012** [hexojs/hexo#995]
nexo init
npm intall
when
#nexo g
the public folder missing css file

**Comment by kinglion** [comment]
I also match this problem
![qq 20150119172450](https://cloud.githubusercontent.com/assets/3380489/5798539/1b6d2f32-a003-11e4-85d9-525c5db4551f.png)

**Comment by kinglion** [comment]
tommy351 commented 11 days ago
Sorry. hexo-renderer-stylus is rewritten for Hexo 3.0. Please install the old version instead.

$ npm install hexo-renderer-stylus@0.1 --save
ref hexojs/hexo-renderer-stylus#5
