### ISSUE TITLE
SyntaxHighlighter 支持?

### ISSUE THREAD

**Issue by Notedown-cn** [hexojs/hexo#999]
hexo的代码高亮解析出来没有class. 以及某些字段解析不出高亮
```
<td>
<div class="line number1 index0 alt2">xxxx</div>
<div class="line number2 index1 alt1">xxxx</div>
<div class="line number3 index2 alt2">xxxx</div>
<div class="line number4 index3 alt1">xxxx</div>
```
只能修改为http://alexgorbatchev.com/SyntaxHighlighter/       (javascript加载解析)
hexo的与https://highlightjs.org/  也不一样 
在新版本中 .能否加强代码显示上..这样就比jekyll好很多了

**Comment by hqman** [comment]
生成代码 figure + pre 和 **hljs**  html结构有区别

**Comment by jcnote** [comment]
同问

**Comment by Xuanwo** [comment]
可以自己指定高亮的语言，参考https://highlightjs.org/

**Comment by Xuanwo** [comment]
Closed for no more updatem please create new issues.
